### ISSUE TITLE
kvserver: investigate exceeding uncommitted entry size

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#100096]
**Describe the problem**

See https://github.com/cockroachdb/cockroach/issues/99464. We were seeing lots of these messages:

> appending new entries to log would exceed uncommitted entry size limit; dropping proposal

That's not good! These proposals will have to be picked up by `refreshProposalsLocked` which takes ~200ms.

If something changed recently that causes us to hit this more frequently (as seems to be the case, anecdotally) we need to add at least rudimentary flow control here.

It is somewhat expected to hit this in general. To generate proposals and to put them into raft requires only disk reads, but getting them committed requires a durable write, including likely round-trips to followers (to obtain quorum). The former can be done at much higher throughput than the latter.

**To Reproduce**

Running the test in #99464 reproduces this in 100% of all runs I did, averaging around ~70 related log messages per run.

I also seem to hit this reliably with the unit test `BenchmarkReplicaProposal`

**Expected behavior**

Some kind of flow control, similar to the quota pool but locally. Ideally we would delay grabbing a latch for a write if we can tell that raft is not currently accepting more proposals. Maybe we want to avoid doing most of this buffering inside of RawNode anyway, and instead improve our proposal buffer to provide this backpressure signal instead. Unsure, needs more thought.

**Additional data / screenshots**

Adding better visibility into this issue in https://github.com/cockroachdb/cockroach/pull/100083.

**Comment by tbg** [comment]
Surprise plot twist - I added logging that would fire whenever we'd get `ErrProposalDropped` from `rawNode.Propose`. The logging... never fired along with the warning that triggered this investigation. So I hacked a `debug.PrintStack` into the warning, lo and behold it's always this stack, i.e. via `maybeUnquiesceAndWakeLeaderLocked` and not via actual proposals to the raft group 😕 

<details>
<summary>Details</summary>


```
W230330 15:16:11.208906 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 381  1 appending new entries to log would exceed uncommitted entry size limit; dropping proposal
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382  stack: ‹goroutine 216 [running]:›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹runtime/debug.Stack()›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹    GOROOT/src/runtime/debug/stack.go:24 +0x65›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftLogger).Warningf(0xc003ac2780, {0x5c20e7d?, 0x0?}, {0xc0034601a0?, 0x13?, 0x13?})›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft.go:92 +0x6b›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹go.etcd.io/raft/v3.(*raft).appendEntry(0xc001fab080, {0xc002fc37a0?, 0x1, 0x1})›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹    go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:767 +0x178›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹go.etcd.io/raft/v3.stepLeader(0xc001fab080, {0x2, 0x0, 0x1, 0x0, 0x0, 0x0, {0xc002fc37a0, 0x1, 0x1}, ...})›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹    go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:1239 +0x256e›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹go.etcd.io/raft/v3.(*raft).Step(0xc001fab080, {0x2, 0x0, 0x1, 0x0, 0x0, 0x0, {0xc002fc37a0, 0x1, 0x1}, ...})›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹    go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:1156 +0xed5›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹go.etcd.io/raft/v3.(*RawNode).Propose(...)›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹    go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go:89›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).maybeUnquiesceAndWakeLeaderLocked(0xc001609900)›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft_quiesce.go:92 +0x358›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked(0xc001609900, 0x1?, 0xc002d2ad20?)›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1975 +0x347›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:753 +0x2fc›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:709 +0x17b›
W230330 15:16:11.209204 216 go.etcd.io/raft/v3/raft.go:767 ⋮ [T1,n1,s1,r63/1:‹/Table/104{-/8/8359…}›] 382 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc0016a6000, 0xc000adbbf0?)›
```

</details>

This smells like a buglet. I think we propose a big batch of entries (which goes in, but now there's negative uncommitted size left), and then we for some reason - likely accidentally - hit the "unquiesce" path here

https://github.com/cockroachdb/cockroach/blob/c2460f1b0fc94c8fcbd98273cec35061494fc2dd/pkg/kv/kvserver/replica_raft.go#L1955-L1956

and try to propose an empty entry, which gets dropped. I wouldn't be surprised if we hit this path on each raft iteration. Possibly `Lead` is just not properly maintained in the "edge" case of a single-voter `RawNode`. That should be easy to verify.

**Comment by tbg** [comment]
Looking a bit more, we can only hit this unquiesce path if quiesced[^1] so it must be a little more subtle than that. How can the replica be quiesced if it refuses an empty entry (meaning it has uncommitted log entries)?

It should fail this check:

https://github.com/cockroachdb/cockroach/blob/76afb004ce71fac3c2bb19f33ef8c247e2775211/pkg/kv/kvserver/replica_raft_quiesce.go#L289-L294

or this check:

https://github.com/cockroachdb/cockroach/blob/76afb004ce71fac3c2bb19f33ef8c247e2775211/pkg/kv/kvserver/replica_raft_quiesce.go#L318-L323

or this one:

https://github.com/cockroachdb/cockroach/blob/76afb004ce71fac3c2bb19f33ef8c247e2775211/pkg/kv/kvserver/replica_raft_quiesce.go#L385-L391

You get the idea.

Given how easy this is to reproduce, probably best to slap it with a bit of printf and have another go.

[^1]: https://github.com/cockroachdb/cockroach/blob/76afb004ce71fac3c2bb19f33ef8c247e2775211/pkg/kv/kvserver/replica_raft_quiesce.go#L96-L97

**Comment by pavelkalinnikov** [comment]
> The mystery is that we're refusing to append an empty entry but then, without applying anything, accept 30mb of entries.

Can this be due to https://github.com/etcd-io/raft/issues/11? The uncommitted log size can be reset upon election.

**Comment by pavelkalinnikov** [comment]
@tbg

> and then we append 30mb worth of entries, which for some reason is _not_ dropped:
> 
> ```
> I230331 08:10:47.722485 205 kv/kvserver/store_raft.go:655 ⋮ [T1,n1,s1,r62/1:‹/{Table/61-Max}›,raft] 237  raft ready handling: 0.11s [append=0.05s, apply=0.00s, commit-append-non-blocking-sync=0.06s, other=0.00s], wrote [append-batch=30 MiB, append-ent=30 MiB (1), ]; node might be overloaded
> ```

This doesn't look like a new 30 MB proposal being accepted. These 30 MB is probably what the uncommitted buffer contained, and the reason why it rejected the unquiescence proposal. What we see in this log message is that the 30 MB finally gets flushed to the storage (via raft Ready handling).

**Comment by tbg** [comment]
I think I understand this better now. This test writes lots of large blobs, and leaves enough time between blobs to allow the range to quiesce.

So we start with a quiesced replica, which now gets a ~50MiB proposal. First, this goes into the proposal buffer, which queues an update check:

https://github.com/cockroachdb/cockroach/blob/1cd507a7c6582fd91bb56123e62bd4fde45c4d22/pkg/kv/kvserver/replica_proposal_buf.go#L335-L346

This triggers raft processing, which calls `withRaftGroupLocked` (which in turn passes a closure that flushes the proposal buffer):

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/replica_raft.go#L749-L752

Peeking into `withRaftGroupLocked`, we see that it invokes the closure *before* unquiescing:

https://github.com/cockroachdb/cockroach/blob/1cd507a7c6582fd91bb56123e62bd4fde45c4d22/pkg/kv/kvserver/replica_raft.go#L1968-L1992

So we first flush the proposal buffer, then unquiesce. But flushing a 50MiB proposal from the buffer into the unstable raft log will consume the unstable log budget in raft. So by the time we unquiesce, there is no more space and the unquiesce's append gets rejected. This isn't a problem - after all, if there's unstable log, raft already needs to distribute something to the followers and is thus going to wake them up.

I don't think there's anything new here in this cycle other than that we made the `copy` roachtest more aggressive and able to hit this reliably (or maybe it always hit this and we just never looked at the logs).

I tried out this little patch which proposes a "true" empty command (instead of a nonempty command containing a "nil" CRDB payload) - true empty commands are exempt from uncommitted log size tracking - like this:

```diff
@@ -89,11 +88,10 @@ func (r *Replica) maybeUnquiesceAndWakeLeaderLocked() bool {
        r.store.unquiescedReplicas.Unlock()
        r.maybeCampaignOnWakeLocked(ctx)
        // Propose an empty command which will wake the leader.
-       data := raftlog.EncodeRaftCommand(raftlog.EntryEncodingStandardWithoutAC, makeIDKey(), nil)
-       _ = r.mu.internalRaftGroup.Propose(data)
+       _ = r.mu.internalRaftGroup.Propose(nil /* data */)
        return true
 }
```

and voila, I'm (unsurprisingly) no longer seeing the messages. I'll send that patch separately.

@aliher1911 I believe you mentioned also having seen this message "randomly". Do you have something I can look at? Maybe there are multiple things going on.

**Comment by tbg** [comment]
Chatted with Erik, removing GA-blocker since there's nothing new/bad here. Will check in with Oleg when he's back to see where else he saw this message.
