### ISSUE TITLE
sql: flake in TestLogic_inverted_filter_json_array - segfault in `physicalplan.(*fakeSpanResolverIterator).Seek`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#100108]
Here:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/9340668?buildTab=overview&showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true&showLog=9340668_78961_2267.78954.78959&logFilter=debug

```
   === RUN   TestLogic_inverted_filter_json_array
          test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/6535798b40cef7a583c94fc454e99189/logTestLogic_inverted_filter_json_array2347995649
          test_log_scope.go:79: use -show-logs to present logs inline
      unexpected fault address 0x577a4853bb8
      fatal error: fault
      [signal SIGSEGV: segmentation violation code=0x1 addr=0x577a4853bb8 pc=0x22303cb]
      
      goroutine 39552 [running]:
      runtime.throw({0x50f098e?, 0x0?})
        GOROOT/src/runtime/panic.go:1047 +0x5d fp=0xc009556be8 sp=0xc009556bb8 pc=0x46593d
      runtime.sigpanic()
        GOROOT/src/runtime/signal_unix.go:842 +0x2c5 fp=0xc009556c38 sp=0xc009556be8 pc=0x47c345
      github.com/cockroachdb/cockroach/pkg/sql/physicalplan.(*fakeSpanResolverIterator).Seek(0xc008fe7980, {0x64f9520, 0xc00697cff0}, {{0xc0081f0a08, 0x15, 0x18}, {0xc0081f0a38, 0x15, 0x15}}, 0x0)
        github.com/cockroachdb/cockroach/pkg/sql/physicalplan/fake_span_resolver.go:174 +0x8eb fp=0xc009556e88 sp=0xc009556c38 pc=0x22303cb
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).partitionSpan(0x0?, {0x64f9520, 0xc00697cff0}, 0x2?, {{0xc0081f0a08, 0x15, 0x18}, {0xc0081f0a38, 0x15, 0x15}}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1216 +0x2cc fp=0xc009557210 sp=0xc009556e88 pc=0x345962c
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).deprecatedPartitionSpansSystem(0xc001102640, {0x64f9520, 0xc00697cff0}, 0xc002186790, {0xc00697ce10, 0x1, 0xc002eb8240?})
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1295 +0x20b fp=0xc0095573a0 sp=0xc009557210 pc=0x345a44b
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PartitionSpans(0x4?, {0x64f9520?, 0xc00697cff0?}, 0x17?, {0xc00697ce10?, 0x0?, 0x0?})
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1173 +0x51 fp=0xc0095573f0 sp=0xc0095573a0 pc=0x3459231
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planTableReaders(0xc001102640, {0x64f9520, 0xc00697cff0}, 0x0?, 0xc000e21680, 0xc0095577f8)
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1847 +0x85 fp=0xc009557688 sp=0xc0095573f0 pc=0x345d985
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createTableReaders(0x747b6e17c8b0498?, {0x64f9520, 0xc00697cff0}, 0xc002186790, 0xc005585c00)
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1682 +0x325 fp=0xc0095578a8 sp=0xc009557688 pc=0x345d1e5
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlanForPlanNode(0x1?, {0x64f9520, 0xc00697cff0}, 0xc002186790, {0x64fbaf8?, 0xc005585c00?})
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:3501 +0x1f6 fp=0xc009558360 sp=0xc0095578a8 pc=0x3469a36
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForJoin(0x497b5a0?, {0x64f9520, 0xc00697cff0}, 0x64f9520?, 0xc005ef9360)
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:3244 +0x65 fp=0xc009558830 sp=0xc009558360 pc=0x3468425
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlanForPlanNode(0x0?, {0x64f9520, 0xc00697cff0}, 0xc002186790, {0x64fb580?, 0xc005ef9360?})
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:3444 +0x736 fp=0xc0095592e8 sp=0xc009558830 pc=0x3469f76
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForLookupJoin(0xc001102640, {0x64f9520, 0xc00697cff0}, 0xc002186790, 0xc005828240)
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2781 +0x65 fp=0xc0095597e0 sp=0xc0095592e8 pc=0x34651a5
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlanForPlanNode(0x2?, {0x64f9520, 0xc00697cff0}, 0xc002186790, {0x64fb5f0?, 0xc005828240?})
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:3460 +0x551 fp=0xc00955a298 sp=0xc0095597e0 pc=0x3469d91
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForJoin(0xc000e21428?, {0x64f9520, 0xc00697cff0}, 0xc0082d87a0?, 0xc005ef94a0)
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:3244 +0x65 fp=0xc00955a768 sp=0xc00955a298 pc=0x3468425
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlanForPlanNode(0xc005ef9540?, {0x64f9520, 0xc00697cff0}, 0xc002186790, {0x64fb580?, 0xc005ef94a0?})
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:3444 +0x736 fp=0xc00955b220 sp=0xc00955a768 pc=0x3469f76
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlanForPlanNode(0x33b0de0?, {0x64f9520, 0xc00697cff0}, 0xc002186790, {0x64fb970?, 0xc005ef9540?})
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:3469 +0x22c fp=0xc00955bcd8 sp=0xc00955b220 pc=0x3469a6c
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlan(0xc0082d9dc8?, {0x64f9520?, 0xc00697cff0?}, 0x64f9520?, {{0x64fb970, 0xc005ef9540}, 0x0})
        github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:3376 +0x71 fp=0xc00955bd38 sp=0xc00955bcd8 pc=0x34697b1
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0x203001?, {0x64f9520, 0xc00697cff0}, 0x0?, 0xc002186790, 0x0?, {{0x64fb970?, 0xc005ef9540?}, 0x0?}, 0xc003ceb500, ...)
        github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1873 +0x139 fp=0xc00955bdf0 sp=0xc00955bd38 pc=0x3482699
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func2(0xc00457de10, 0x0?, {0x64f9520, 0xc00697cff0}, 0xc002008000?, 0xc001a8f3b0?, 0x0?)
        github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1632 +0xcb fp=0xc00955be88 sp=0xc00955bdf0 pc=0x3480f2b
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll(0x0?, {0x64f9520, 0xc00697cff0}, 0xc00457e250, 0x64f9520?, 0xc00457de10, 0xc003ceb500, 0x0)
        github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1635 +0x1e5 fp=0xc00955bf90 sp=0xc00955be88 pc=0x3480c05
      github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc00457d800, {0x64f9520?, 0xc00697cff0}, 0xc00457de10, 0xc00697cff0?, {0x654b5a0?, 0xc003f71bf0}, 0xc003f71bf0?, 0xc005a34398)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1771 +0x5eb fp=0xc00955c0a0 sp=0xc00955bf90 pc=0x33bce6b
      github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00457d800, {0x64f9478, 0xc008fe6580}, 0xc00457de10, {0x654b5a0, 0xc003f71bf0})
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1351 +0xc28 fp=0xc00955c538 sp=0xc00955c0a0 pc=0x33b9c88
      github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00457d800, {0x64f9520?, 0xc003f71890?}, {{0x6522c60, 0xc0061aa910}, {0x0, 0x0, 0x0}, {0xc00172c781, 0x240}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:770 +0x2c0f fp=0xc00955d090 sp=0xc00955c538 pc=0x33b4a8f
      github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1({0x64f9520?, 0xc003f71890?})
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:137 +0xbc fp=0xc00955d140 sp=0xc00955d090 pc=0x33b18bc
      github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling(0x64f9520?, {0x64f9520?, 0xc003f71890?}, {0x6522c60?, 0xc0061aa910?}, 0x736c501e99118b4f?, 0x0?)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2660 +0x330 fp=0xc00955d290 sp=0xc00955d140 pc=0x33c39f0
      github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00457d800, {0x64f9520, 0xc003f71890}, {{0x6522c60, 0xc0061aa910}, {0x0, 0x0, 0x0}, {0xc00172c781, 0x240}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:136 +0x4da fp=0xc00955d420 sp=0xc00955d290 pc=0x33b12ba
      github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal(0xc00457d800, {0x64f9520, 0xc003f71890}, {{0x0, 0x0}, 0xc0049fc900, {0xc000a397d0, 0x1, 0x1}, {0x0, ...}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:226 +0x18b fp=0xc00955d588 sp=0xc00955d420 pc=0x33b1b0b
      github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2({{0x0, 0x0}, 0x0, {0xc10181ae4331cd42, 0x253924537, 0x0}, 0x1}, 0xc00457d800, 0xc00955d980, 0xc00955d970, ...)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2197 +0x54b fp=0xc00955d7a0 sp=0xc00955d588 pc=0x33a25cb
      github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00457d800)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2199 +0x6df fp=0xc00955de90 sp=0xc00955d7a0 pc=0x33a04df
      github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00457d800, {0x64f9520, 0xc003f71230}, 0x11bd060?, 0xc001f20800?, 0x11bd0c0?)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2038 +0x20b fp=0xc00955df48 sp=0xc00955de90 pc=0x339fa6b
      github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx.func1()
        github.com/cockroachdb/cockroach/pkg/sql/internal.go:172 +0xac fp=0xc00955dfe0 sp=0xc00955df48 pc=0x34eda0c
      runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00955dfe8 sp=0xc00955dfe0 pc=0x49a081
      created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx
        github.com/cockroachdb/cockroach/pkg/sql/internal.go:171 +0x195
```

Jira issue: CRDB-26256

**Comment by mgartner** [comment]
Marking as a GA-blocker for now until we diagnose the problem.

**Comment by cucaroach** [comment]
We looked into this and came up empty, seems like a memory corruption and we're gonna close it and see if it happens again.
