### ISSUE TITLE
merge lets range split config values

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1002]
three node local cluster,
``` 
./cockroach range split f
./cockroach range ls
./cockroach range merge f
./cockroach range ls
15:23 $ ./cockroach range ls
level="WARNING" time="2015-05-12T15:23:58-04:00" file="context.go" line="158" msg="running in insecure mode, this is strongly discouraged. See --insecure and --certs."
""-"\x00status-store-\t\x01" [1]
	0: node-id=1 store-id=1 attrs=[]
"\x00status-store-\t\x01"-"\xff\xff" [2]
	0: node-id=1 store-id=1 attrs=[]
```

shortly after on the second and third nodes:
```
level="WARNING" time="2015-05-12T15:20:53-04:00" file="multiraft.go" line="910" msg="node 200000002 failed to send message to 100000001: connection is shut down"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x47201d7]

goroutine 25 [running]:
github.com/coreos/etcd/raft.(*multiNode).run(0xc20819c780)
	/Users/tschottdorf/go/src/github.com/coreos/etcd/raft/multinode.go:234 +0xc57
created by github.com/coreos/etcd/raft.StartMultiNode
	/Users/tschottdorf/go/src/github.com/coreos/etcd/raft/multinode.go:55 +0xb6
```

and the first one panicked in this line for the config for the zone configs.

```
if !r.ContainsKey(cd.keyPrefix.PrefixEnd()) {
  log.Fatalf("range splits configuration values for %s", cd.keyPrefix)
}
```

So there are two things:

- did we really split the config? If so, we shouldn't and if not, the check is wrong.
- the other two nodes shouldn't run into a nil pointer panic when the first kills itself.

**Comment by tamird** [comment]
I believe this is fixed in https://github.com/cockroachdb/cockroach/pull/1638.
