### ISSUE TITLE
kvserver: flake in TestRangeLocalUncertaintyLimitAfterNewLease on master

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#100491]
Found e.g here https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9407560?buildTab=overview&showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true

```
No pass/skip/fail event found for test
=== RUN   TestRangeLocalUncertaintyLimitAfterNewLease
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/cf37c672d8047f2c0f0376aa18bb51c0/logTestRangeLocalUncertaintyLimitAfterNewLease3777875751
    test_log_scope.go:79: use -show-logs to present logs inline
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1  clock synchronization error: this node is more than 400ms away from at least half of the known nodes (0 of 1 are within the offset)
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !goroutine 12570 [running]:
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0)
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x89
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc003534a00, {{{0xc001935b30, 0x24}, {0x0, 0x0}, {0x5f5c525, 0x1}, {0x5f5c527, 0x1}}, 0x17527dca5eb8f7e9, ...})
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/util/log/clog.go:260 +0xb8
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x7517f90, 0xc00558bb90}, 0x2, 0x4, 0x1, 0x0?, {0x5e7adb0, 0x2}, {0xc008b25ab8, 0x1, ...})
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/util/log/channels.go:106 +0x645
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/util/log.loggerOps.Fatalf(...)
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:1378
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/server.NewServer.func3()
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/server/server.go:347 +0x9c
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat.func2({0x7517f90, 0xc005a9f290})
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:2553 +0x56b
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc000f5ce00, {0x7517f90, 0xc005a9f290}, {0x0?, 0x12?}, 0xc004577e30)
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322 +0xd1
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc006a40a00, {0x7517f90, 0xc005a9f290}, 0xc005a9f260, {0xc006aa5d80?, 0x0?})
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:2460 +0x4af
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/rpc.(*Context).grpcDialNodeInternal.func1({0x7517f90, 0xc005a9f290})
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:2301 +0xc6
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !  github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !For more context, check log files in: /artifacts/tmp/_tmp/cf37c672d8047f2c0f0376aa18bb51c0/logTestRangeLocalUncertaintyLimitAfterNewLease3777875751
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !****************************************************************************
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !This node experienced a fatal error (printed above), and as a result the
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !process is terminating.
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !problem in CockroachDB. With your help, the support team at Cockroach Labs
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !will try to determine the root cause, recommend next steps, and we can
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !improve CockroachDB based on your report.
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !Please submit a crash report by following the instructions here:
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !    https://github.com/cockroachdb/cockroach/issues/new/choose
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !If you would rather not post publicly, please contact us directly at:
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !    support@cockroachlabs.com
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !
F230403 17:45:19.088662 12570 1@server/server.go:347  [T1,n3] 1 !The Cockroach Labs team appreciates your feedback.
```

Jira issue: CRDB-26463

**Comment by knz** [comment]
i'll send a skip
