### ISSUE TITLE
nil deref in etcdraft/multinode.go:234

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1010]
The following test appears to have failed:

[#2374](https://circleci.com/gh/cockroachdb/cockroach/2374):

```
level="INFO" time="2015-05-12T21:03:18Z" file="multiraft.go" line="760" msg="node 300000003: group 1 raft ready"
level="INFO" time="2015-05-12T21:03:18Z" file="multiraft.go" line="765" msg="HardState updated: {Term:6 Vote:0 Commit:30 XXX_unrecognized:[]}"
level="INFO" time="2015-05-12T21:03:18Z" file="multiraft.go" line="774" msg="Snapshot updated: data:\"\\n<\\n\\030\\000\\377\\000\\377\\000\\377i\\t\\001res-\\010\\020\\353`se\\274\\nf\\000\\001\\022 \\022\\004\\010\\000\\020\\000\\030\\000 \\000(\\0002\\022\\n\\013\\202\\001\\010\\n\\006\\022\\004\\010\\000\\020\\004\\035:\\030\\234!\\nC\\n "
level="INFO" time="2015-05-12T21:03:18Z" file="multiraft.go" line="777" msg="Outgoing Message[0]: 12884901891->4294967297 MsgAppResp Term:6 Log:0/30"
level="WARNING" time="2015-05-12T21:03:18Z" file="multiraft.go" line="916" msg="node 100000001 failed to send message to 200000002: transport.go:169: unknown peer 200000002"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0xae5317]

goroutine 4930 [running]:
github.com/coreos/etcd/raft.(*multiNode).run(0xc208145a40)
	/go/src/github.com/coreos/etcd/raft/multinode.go:234 +0xc57
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:55 +0xb6

goroutine 1 [chan receive]:
testing.RunTests(0x10f6238, 0x15a9e20, 0xa5, 0xa5, 0xc207ffc501)
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:203 +0x2cb
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0xe3
FAIL	github.com/cockroachdb/cockroach/storage	3.803s
=== RUN TestBatchBasics
level="INFO" time="2015-05-12T21:03:56Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:03:56Z" file="rocksdb.go" line="113" msg="closing in-memory rocksdb instance"
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
level="INFO" time="2015-05-12T21:03:56Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:03:56Z" file="rocksdb.go" line="113" msg="closing in-memory rocksdb instance"
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
level="INFO" time="2015-05-12T21:03:56Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:07:01Z" file="multiraft.go" line="777" msg="Outgoing Message[1]: 12884901891->4294967297 MsgAppResp Term:6 Log:0/56"
level="INFO" time="2015-05-12T21:07:01Z" file="multiraft.go" line="777" msg="Outgoing Message[2]: 12884901891->4294967297 MsgAppResp Term:6 Log:0/56"
level="WARNING" time="2015-05-12T21:07:01Z" file="multiraft.go" line="916" msg="node 200000002 failed to send message to 100000001: transport.go:169: unknown peer 100000001"
level="WARNING" time="2015-05-12T21:07:01Z" file="multiraft.go" line="916" msg="node 200000002 failed to send message to 100000001: transport.go:169: unknown peer 100000001"
level="WARNING" time="2015-05-12T21:07:01Z" file="multiraft.go" line="916" msg="node 300000003 failed to send message to 100000001: transport.go:169: unknown peer 100000001"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0xc4c5e9]

goroutine 2908 [running]:
github.com/coreos/etcd/raft.(*multiNode).run(0xc2084d34a0)
	/go/src/github.com/coreos/etcd/raft/multinode.go:234 +0xfa9
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:55 +0xde

goroutine 1 [chan receive]:
testing.RunTests(0x1392098, 0x18822a0, 0xa5, 0xa5, 0x1)
--
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1290 +0x10d9
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0x133
FAIL	github.com/cockroachdb/cockroach/storage	6.958s
=== RUN TestBatchBasics
level="INFO" time="2015-05-12T21:07:49Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:07:49Z" file="rocksdb.go" line="113" msg="closing in-memory rocksdb instance"
--- PASS: TestBatchBasics (0.01s)
=== RUN TestBatchGet
level="INFO" time="2015-05-12T21:07:49Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:07:49Z" file="rocksdb.go" line="113" msg="closing in-memory rocksdb instance"
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
level="INFO" time="2015-05-12T21:07:49Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:07:01Z" file="multiraft.go" line="777" msg="Outgoing Message[1]: 12884901891->4294967297 MsgAppResp Term:6 Log:0/56"
level="INFO" time="2015-05-12T21:07:01Z" file="multiraft.go" line="777" msg="Outgoing Message[2]: 12884901891->4294967297 MsgAppResp Term:6 Log:0/56"
level="WARNING" time="2015-05-12T21:07:01Z" file="multiraft.go" line="916" msg="node 200000002 failed to send message to 100000001: transport.go:169: unknown peer 100000001"
level="WARNING" time="2015-05-12T21:07:01Z" file="multiraft.go" line="916" msg="node 200000002 failed to send message to 100000001: transport.go:169: unknown peer 100000001"
level="WARNING" time="2015-05-12T21:07:01Z" file="multiraft.go" line="916" msg="node 300000003 failed to send message to 100000001: transport.go:169: unknown peer 100000001"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0xc4c5e9]

goroutine 2908 [running]:
github.com/coreos/etcd/raft.(*multiNode).run(0xc2084d34a0)
	/go/src/github.com/coreos/etcd/raft/multinode.go:234 +0xfa9
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:55 +0xde

goroutine 1 [chan receive]:
testing.RunTests(0x1392098, 0x18822a0, 0xa5, 0xa5, 0x1)
--
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1290 +0x10d9
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0x133
FAIL	github.com/cockroachdb/cockroach/storage	6.958s
=== RUN TestBatchBasics
level="INFO" time="2015-05-12T21:07:49Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:07:49Z" file="rocksdb.go" line="113" msg="closing in-memory rocksdb instance"
--- PASS: TestBatchBasics (0.01s)
=== RUN TestBatchGet
level="INFO" time="2015-05-12T21:07:49Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:07:49Z" file="rocksdb.go" line="113" msg="closing in-memory rocksdb instance"
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
level="INFO" time="2015-05-12T21:07:49Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:03:18Z" file="multiraft.go" line="760" msg="node 300000003: group 1 raft ready"
level="INFO" time="2015-05-12T21:03:18Z" file="multiraft.go" line="765" msg="HardState updated: {Term:6 Vote:0 Commit:30 XXX_unrecognized:[]}"
level="INFO" time="2015-05-12T21:03:18Z" file="multiraft.go" line="774" msg="Snapshot updated: data:\"\\n<\\n\\030\\000\\377\\000\\377\\000\\377i\\t\\001res-\\010\\020\\353`se\\274\\nf\\000\\001\\022 \\022\\004\\010\\000\\020\\000\\030\\000 \\000(\\0002\\022\\n\\013\\202\\001\\010\\n\\006\\022\\004\\010\\000\\020\\004\\035:\\030\\234!\\nC\\n "
level="INFO" time="2015-05-12T21:03:18Z" file="multiraft.go" line="777" msg="Outgoing Message[0]: 12884901891->4294967297 MsgAppResp Term:6 Log:0/30"
level="WARNING" time="2015-05-12T21:03:18Z" file="multiraft.go" line="916" msg="node 100000001 failed to send message to 200000002: transport.go:169: unknown peer 200000002"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0xae5317]

goroutine 4930 [running]:
github.com/coreos/etcd/raft.(*multiNode).run(0xc208145a40)
	/go/src/github.com/coreos/etcd/raft/multinode.go:234 +0xc57
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:55 +0xb6

goroutine 1 [chan receive]:
testing.RunTests(0x10f6238, 0x15a9e20, 0xa5, 0xa5, 0xc207ffc501)
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:203 +0x2cb
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0xe3
FAIL	github.com/cockroachdb/cockroach/storage	3.803s
=== RUN TestBatchBasics
level="INFO" time="2015-05-12T21:03:56Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:03:56Z" file="rocksdb.go" line="113" msg="closing in-memory rocksdb instance"
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
level="INFO" time="2015-05-12T21:03:56Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"
level="INFO" time="2015-05-12T21:03:56Z" file="rocksdb.go" line="113" msg="closing in-memory rocksdb instance"
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
level="INFO" time="2015-05-12T21:03:56Z" file="rocksdb.go" line="88" msg="opening in-memory rocksdb instance"

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
also ocurred in #1002 but after the recent change #1005 this has become normal. I've also reproduced it a couple of times during testing.

**Comment by tschottdorf** [comment]
The failure is related to a message making it into multinode for a group it doesn't know. I'll look into it.

**Comment by bdarnell** [comment]
FYI I'm working on some issues that might be related: a race between rangeGCQueue removing the range and store.ProposeRaftCommand re-creating it. I think I'm going to have to remove buffering in MultiRaft's channels, which might address this race as well.
