### ISSUE TITLE
stability: handleRaftReady gets stuck for more than 500ms

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#10174]
On running sql test: TestRaceWithBackfil, I see the replica mu being held for 733ms by handleRaftReady.

```
I161022 02:28:53.849921 1 rand.go:76  Random seed: 1512371731776666051
I161022 02:28:53.897519 23 storage/engine/rocksdb.go:349  opening in memory rocksdb instance
I161022 02:28:53.901935 23 gossip/gossip.go:236  [n?] initial resolvers: []
W161022 02:28:53.901979 23 gossip/gossip.go:1063  [n?] no resolvers found; use --join to specify a connected node
W161022 02:28:53.903668 23 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I161022 02:28:53.904882 23 server/node.go:419  [n?] store [n0,s0] not bootstrapped
I161022 02:28:53.907139 10 storage/replica_proposal.go:292  [s1,r1/1:/M{in-ax}] new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 410306h29m2.906370336s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=2016-10-22 02:28:53.90706848 +0000 UTC]
I161022 02:28:53.907837 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
I161022 02:28:53.908121 23 server/node.go:351  [n?] **** cluster {3865baf0-21d3-4efc-9d84-dbe0a3342549} has been created
I161022 02:28:53.908246 23 server/node.go:352  [n?] **** add additional nodes by specifying --join=127.0.0.1:44779
I161022 02:28:53.916908 23 gossip/gossip.go:271  [n?] NodeID set to 1
I161022 02:28:53.918981 23 server/node.go:432  [n?] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:0}
I161022 02:28:53.919025 23 server/node.go:320  [n?] node ID 1 initialized
I161022 02:28:53.919225 23 gossip/gossip.go:286  [n?] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:44779" > attrs:<> locality:<> 
I161022 02:28:53.919334 23 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I161022 02:28:53.919486 23 server/node.go:562  [n?] connecting to gossip network to verify cluster ID...
I161022 02:28:53.925492 23 server/node.go:583  [n?] node connected via gossip and verified as part of cluster {"3865baf0-21d3-4efc-9d84-dbe0a3342549"}
I161022 02:28:53.925560 23 server/node.go:370  [n?] node=1: started with [[]=] engine(s) and attributes []
I161022 02:28:53.925632 23 server/server.go:564  [n1] starting https server at 127.0.0.1:36729
I161022 02:28:53.925656 23 server/server.go:565  [n1] starting grpc/postgres server at 127.0.0.1:44779
I161022 02:28:53.925697 23 server/server.go:566  [n1] advertising CockroachDB node at 127.0.0.1:44779
I161022 02:28:53.941532 195 storage/split_queue.go:103  [n1,split,s1,r1/1:/M{in-ax}] splitting at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I161022 02:28:53.962869 205 sql/event_log.go:94  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:44779} Attrs: Locality:} ClusterID:{UUID:3865baf0-21d3-4efc-9d84-dbe0a3342549} StartedAt:1477103333925525187}
I161022 02:28:54.089090 195 storage/replica_command.go:2354  [n1,split,s1,r1/1:/M{in-ax}] initiating a split of this range at key /Table/11 [r2]
I161022 02:28:54.164020 195 storage/replica_command.go:2354  [n1,split,s1,r1/1:/{Min-Table/11}] initiating a split of this range at key /Table/12 [r3]
I161022 02:28:54.207632 195 storage/replica_command.go:2354  [n1,split,s1,r1/1:/{Min-Table/11}] initiating a split of this range at key /Table/13 [r4]
I161022 02:28:54.279907 195 storage/replica_command.go:2354  [n1,split,s1,r1/1:/{Min-Table/11}] initiating a split of this range at key /Table/14 [r5]
I161022 02:28:54.431475 247 sql/event_log.go:94  [n1,client=127.0.0.1:40755] Event: "create_database", target: 50, info: {DatabaseName:t Statement:CREATE DATABASE t User:root}
I161022 02:28:54.435787 247 sql/event_log.go:94  [n1,client=127.0.0.1:40755] Event: "create_table", target: 51, info: {TableName:t.test Statement:CREATE TABLE t.test (k INT PRIMARY KEY, v INT, pi DECIMAL DEFAULT (DECIMAL '3.14')) User:root}
I161022 02:28:54.436941 195 storage/split_queue.go:103  [n1,split,s1,r5/1:/{Table/14-Max}] splitting at keys [/Table/50/0]
I161022 02:28:54.437565 195 storage/replica_command.go:2354  [n1,split,s1,r5/1:/{Table/14-Max}] initiating a split of this range at key /Table/50 [r6]
I161022 02:28:54.453456 247 sql/event_log.go:94  [n1,client=127.0.0.1:40755] Event: "create_index", target: 51, info: {TableName:test IndexName:vidx Statement:CREATE UNIQUE INDEX vidx ON t.test (v) User:root MutationID:1}
I161022 02:28:54.470771 195 storage/split_queue.go:103  [n1,split,s1,r6/1:/{Table/50-Max}] splitting at keys [/Table/51/0]
I161022 02:28:54.492144 195 storage/replica_command.go:2354  [n1,split,s1,r6/1:/{Table/50-Max}] initiating a split of this range at key /Table/51 [r7]
I161022 02:28:54.522549 247 sql/event_log.go:94  Event: "finish_schema_change", target: 51, info: {MutationID:1}
I161022 02:28:55.037480 247 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:40755] memory usage increases to 16 KiB (+48)
I161022 02:28:55.038066 247 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:40755] memory usage increases to 32 KiB (+48)
I161022 02:28:55.038305 247 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:40755] memory usage increases to 64 KiB (+48)
I161022 02:28:55.041171 247 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:40755] memory usage increases to 128 KiB (+48)
W161022 02:28:57.489612 180 storage/replica.go:498  [n1,s1,r7/1:/{Table/51-Max}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 733.125063ms (>500ms):
goroutine 180 [running]:
runtime/debug.Stack(0x1d95e88, 0x1d95ec8, 0x47)
	/home/vivek1/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/syncutil.ThresholdLogger.func1(0x2bb299c7)
	/home/vivek1/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:63 +0xe1
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*TimedMutex).Unlock(0xc4200f4078)
	/home/vivek1/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:90 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc4200f4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vivek1/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1827 +0xee
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4205be600, 0x7)
	/home/vivek1/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3025 +0x13e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4200cb400, 0xc42020e000)
	/home/vivek1/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:230 +0x28c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/home/vivek1/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42020e000, 0xc420625d60)
	/home/vivek1/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:191 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/home/vivek1/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0x66
I161022 02:28:57.740034 247 sql/event_log.go:94  [n1,client=127.0.0.1:40755] Event: "alter_table", target: 51, info: {TableName:test Statement:ALTER TABLE t.test ADD COLUMN x DECIMAL DEFAULT (DECIMAL '1.4') User:root MutationID:2 CascadeDroppedViews:[]}
I161022 02:28:57.767825 247 sql/lease.go:267  publish (count leases): descID=51 name=test version=5 count=1
I161022 02:28:58.772623 247 sql/event_log.go:94  Event: "finish_schema_change", target: 51, info: {MutationID:2}
I161022 02:28:58.902824 247 sql/lease.go:267  publish (count leases): descID=51 name=test version=6 count=1
I161022 02:29:03.265116 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
I161022 02:29:03.271697 244 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:44779->127.0.0.1:40738: use of closed network connection
```

**Comment by petermattis** [comment]
Can you provide more reproduce details? I just ran:

```
~ cd sql; go test -count 20 -v -run TestRaceWithBackfill 2>&1 | tee out
~ grep raftMu: out
```

Not a single occurrence of `raftMu` being held too long.

**Comment by vivekmenezes** [comment]
```
make stress PKG=./pkg/sql TESTS=TestRaceWithBackfill TESTTIMEOUT=30s STRESSFLAGS='-stderr -maxfails 1 -p 100'
```

should reproduce it on your local machine. As soon as the test times out you should be able to scroll up to see errors like:

```
W161024 14:48:26.063280 104 storage/replica.go:509  [n1,s1,r7/1:/{Table/51-Max}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 2.531533103s (>500ms):
```

**Comment by petermattis** [comment]
Well, that's sort of expected, isn't it? You're running 100 simultaneous copies of the test. Yeah, I think you'll see some locks held for an excessively long time in the tail.

**Comment by tschottdorf** [comment]
Agreed, this would be expected under harsh stress testing (100 processes on a laptop is *pretty harsh*, btw).
