### ISSUE TITLE
sqlstats: `PersistedSQLStats.Stop()` blocking server drain

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#102574]
Seen on a 23.1 test cluster, drain stalls for several minutes until it times out:

```
roachprod run grinaker-231:7 './cockroach node drain --insecure --self'
node is draining... 
ERROR: drain timeout, consider adjusting --drain-wait, especially under custom server.shutdown.{drain,query,connection,lease_transfer}_wait cluster settings
Failed running "node drain"
```

Goroutine dumps show it blocked here:

```
goroutine 1670852493 [semacquire, 6 minutes]:
sync.runtime_Semacquire(0xc004a828c8?)
	GOROOT/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0x0?)
	GOROOT/src/sync/waitgroup.go:139 +0x52
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).Stop(0xc004a82840, {0x6fc1f58, 0xc00950fc40})
	github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/pkg/sql/sqlstats/persistedsqlstats/provider.go:134 +0x125
github.com/cockroachdb/cockroach/pkg/server.(*drainServer).drainClients(0xc004a51700, {0x6fc2000?, 0xc08f2bc060?}, 0x6fc2000?)
	github.com/cockroachdb/cockroach/pkg/server/drain.go:416 +0x332
github.com/cockroachdb/cockroach/pkg/server.(*drainServer).drainInner(0xc004a51700, {0x6fc2000, 0xc08f2bc060}, 0xc02fcb92d0, 0x60?)
	github.com/cockroachdb/cockroach/pkg/server/drain.go:334 +0xed
github.com/cockroachdb/cockroach/pkg/server.(*drainServer).runDrain(0xc001d374b0?, {0x6fc2000, 0xc08f2bc060}, 0x0?)
	github.com/cockroachdb/cockroach/pkg/server/drain.go:302 +0x19a
github.com/cockroachdb/cockroach/pkg/server.(*drainServer).handleDrain(0xc004a829a0?, {0x6fc2000, 0xc08f2bc060}, 0xc018827de0, {0x6ffd550, 0xc0241e5a20})
	github.com/cockroachdb/cockroach/pkg/server/drain.go:152 +0x134
github.com/cockroachdb/cockroach/pkg/server.(*adminServer).Drain(0xc004a829a0, 0xc018827de0, {0x6ffd550, 0xc0241e5a20})
	github.com/cockroachdb/cockroach/pkg/server/drain.go:98 +0x11c
github.com/cockroachdb/cockroach/pkg/server/serverpb._Admin_Drain_Handler({0x59df7c0?, 0xc004a33a70}, {0x6ff78a8, 0xc018827dc0})
	github.com/cockroachdb/cockroach/pkg/server/serverpb/bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go:6238 +0xd0
github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.StreamServerInterceptor.func1({0x59df7c0, 0xc004a33a70}, {0x6ff7fb0?, 0xc027d0f7a0?}, 0xc0945aa318, 0x5de6af8)
	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:164 +0x6c4
google.golang.org/grpc.chainStreamInterceptors.func1.1({0x59df7c0?, 0xc004a33a70?}, {0x6ff7fb0?, 0xc027d0f7a0?})
	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1482 +0x5b
github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func4({0x59df7c0, 0xc004a33a70}, {0x6ff7fb0, 0xc027d0f7a0}, 0x11c79f0?, 0xc00950fb80)
	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:285 +0x74
google.golang.org/grpc.chainStreamInterceptors.func1.1({0x59df7c0?, 0xc004a33a70?}, {0x6ff7fb0?, 0xc027d0f7a0?})
	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485 +0x83
github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2.1({0x0?, 0x0?})
	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:252 +0x2d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc00091c980, {0x6fc2000, 0xc018923f50}, {0xc003fb8a98?, 0x47203f?}, 0xc003fb8a50)
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322 +0xd1
github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2({0x59df7c0, 0xc004a33a70}, {0x6ff7fb0?, 0xc027d0f7a0?}, 0xc0945aa318, 0xc00950fb80)
	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:251 +0xef
google.golang.org/grpc.chainStreamInterceptors.func1.1({0x59df7c0?, 0xc004a33a70?}, {0x6ff7fb0?, 0xc027d0f7a0?})
	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485 +0x83
google.golang.org/grpc.chainStreamInterceptors.func1({0x59df7c0, 0xc004a33a70}, {0x6ff7fb0, 0xc027d0f7a0}, 0xc0945aa318, 0x5de6af8)
	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1487 +0x12b
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000052780, {0x700f780, 0xc010b8f380}, 0xc007cd3b00, 0xc000ed7e30, 0xa0fe480, 0x0)
	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1636 +0x11c6
google.golang.org/grpc.(*Server).handleStream(0xc000052780, {0x700f780, 0xc010b8f380}, 0xc007cd3b00, 0x0)
	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1717 +0x9ea
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc/external/org_golang_google_grpc/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc/external/org_golang_google_grpc/server.go:963 +0x28a
```

Jira issue: CRDB-27539

**Comment by erikgrinaker** [comment]
Other goroutines in `persistentsqlstats`:

```
goroutine 685 [chan send, 2999 minutes]:
github.com/cockroachdb/cockroach/pkg/sql.(*sqlActivityUpdateJob).Resume.func2()
	github.com/cockroachdb/cockroach/pkg/sql/sql_activity_update_job.go:98 +0x25
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).startSQLStatsFlushLoop.func1.2(0xc004a82840?)
	github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/pkg/sql/sqlstats/persistedsqlstats/provider.go:193 +0x91
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).startSQLStatsFlushLoop.func1({0x6fc2000, 0xc0079ea2a0})
	github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/pkg/sql/sqlstats/persistedsqlstats/provider.go:195 +0x319
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b

goroutine 369276 [semacquire, 2815 minutes]:
sync.runtime_SemacquireMutex(0x3b?, 0x7c?, 0xc0355c0ec0?)
	GOROOT/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc004a82860)
	GOROOT/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
	GOROOT/src/sync/mutex.go:90
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).SetFlushDoneCallback(0xc0503194c8?, 0xc019f672e0?)
	github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/pkg/sql/sqlstats/persistedsqlstats/provider.go:138 +0x59
github.com/cockroachdb/cockroach/pkg/sql.(*sqlActivityUpdateJob).Resume(0xc00ba9c270, {0x6fc2000, 0xc0108964e0}, {0x575cb60?, 0xc00ba9c298})
	github.com/cockroachdb/cockroach/pkg/sql/sql_activity_update_job.go:97 +0x237
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2(0xc017d4c9c0?, 0x0?, {0x6f960b0?, 0xc00ba9c270?}, {0x6fc2000?, 0xc0108964e0?}, {0x575cb60?, 0xc00ba9c298?}, 0xc08b989850)
	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1624 +0xcc
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine(0xc0006fca00, {0x6fc2000, 0xc00d300db0}, {0x575cb60, 0xc00ba9c298}, {0x6f960b0, 0xc00ba9c270}, 0xc017d4c9c0, {0xc012cf2680, 0x7}, ...)
	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1625 +0x8df
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob(0xc0006fca00, {0x6fc1f58, 0xc00c063240}, {0x6f960b0, 0xc00ba9c270}, 0xc017d4c9c0, {0xc012cf2680, 0x7}, {0xc00584de20, 0x7})
	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:474 +0x637
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func2({0x6fc2000?, 0xc00d300b40?})
	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:388 +0x146
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
```

**Comment by erikgrinaker** [comment]
I see @knz was in this area recently: #100476.

Mind having a look?

**Comment by erikgrinaker** [comment]
The fact that we've been waiting 2815 minutes to acquire a mutex in `SetFlushDoneCallback()` seems bad.

**Comment by erikgrinaker** [comment]
Full goroutine dump: [goroutines.txt](https://github.com/cockroachdb/cockroach/files/11352960/goroutines.txt)
