### ISSUE TITLE
benchmark tests panic with 96 bytes of unexpected leftover memory

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#10296]
Seen in `sql.test.stderr` from [this run](https://teamcity.cockroachdb.com/viewLog.html?buildTypeId=Cockroach_BenchmarkTests&buildId=37818) of the benchmark tests.

```
161028 07:43:02.977208 1986260 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:52114] memory usage increases to 64 KiB (+188)
I161028 07:43:02.977346 1986260 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:52114] memory usage increases to 128 KiB (+188)
I161028 07:43:02.977613 1986260 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:52114] memory usage increases to 256 KiB (+188)
I161028 07:43:02.978144 1986260 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:52114] memory usage increases to 512 KiB (+188)
panic: unexpected leftover memory: 96 bytes [recovered]
    panic: unexpected leftover memory: 96 bytes

goroutine 1986045 [running]:
panic(0x17082a0, 0xc421a169f0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42e6e8000)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x17082a0, 0xc421a169f0)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/mon.(*MemoryUsageMonitor).StopMonitor(0xc42023b550, 0x7f06f5bc1380, 0xc43e783ac0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/mon/mem_usage.go:130 +0x2a2
github.com/cockroachdb/cockroach/pkg/sql.(*Session).Finish(0xc42023ad00, 0xc4222ad540)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:193 +0x99
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).finish(0xc4267a4000, 0x7f06f5bc1340, 0xc42e642510)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:154 +0x7e
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42957a5a0, 0x7f06f5bc1340, 0xc42e642510, 0x23efda0, 0xc427bec380, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:245 +0x659
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x23efe00, 0xc42e87e000)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:488 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc42e6e8000, 0xc4201741a0, 0x23efe00, 0xc42e87e000, 0xc42815a020)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
    /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

**Comment by knz** [comment]
Root cause: when a txn is retried, the ResultList computed in the first try are not Close()d.
