### ISSUE TITLE
storage: pebble fatal commit error in `TestCCLLogic_multi_region_zone_configs` unit test on 23.1

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#103021]
See[ failure](https://teamcity.cockroachdb.com/viewLog.html?buildId=10017468&buildTypeId=Cockroach_BazelEssentialCi) in CI. 

```
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1  pebble: fatal commit error: allocation failed because arena is full
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !goroutine 9524 [running]:
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0)
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x89
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc0011038c0, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, 0x175dcb50660bc1bd, ...})
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:260 +0xb8
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x71110f8, 0xc000a2af60}, 0x3, 0x4, 0x3, 0x0?, {0x5bedc93, 0x1e}, {0xc00c35d9e0, 0x1, ...})
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:106 +0x645
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.loggerStorage.FatalfDepth(...)
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:2223
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/storage.pebbleLogger.Fatalf({{0x71110f8?, 0xc000a2af60?}, 0xc009291040?}, {0x5bedc93?, 0x463207?}, {0xc00c35d9e0?, 0x10?, 0xc00e5b4438?})
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:687 +0x56
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/pebble.(*DB).applyInternal(0xc00368e500, 0xc00a480140, 0xc00e5b4480?, 0xa2?)
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:811 +0x278
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/pebble.(*DB).ApplyNoSyncWait(0x642f2e?, 0x1a6b0fd?, 0x15a0e5b4720?)
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:765 +0x25
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).CommitNoSyncWait(0x1f?)
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:568 +0x2c
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*LogStore).storeEntriesAndCommitBatch(0xc00e5b4d30, {0x71110f8, 0xc009d8a990}, {0x0?, 0x0?, 0x0?}, {0x13, 0xffffffffffffffff, 0x3, 0x0, ...}, ...)
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:247 +0x7d5
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*LogStore).StoreEntries(0xc00e5b4d30, {0x71110f8, 0xc009d8a990}, {0x4ddf5e?, 0x7f8dbde94700?, 0x130?}, {0x13, 0xffffffffffffffff, 0x3, 0x0, ...}, ...)
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:139 +0x110
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:972 +0x1137
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:718 +0x19b
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc006e7f500, 0x71110f8?)
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:646 +0x145
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0xc004903c20, {0x71110f8, 0xc007e3c8d0}, {0x70f58b0, 0xc006e7f500}, 0xc00bf98400)
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:392 +0x1f2
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x71110f8?, 0xc007e3c8d0?})
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:299 +0x45
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !For more context, check log files in: /artifacts/tmp/_tmp/3bd8bf58f451d1175df6c8dde3b28cd7/logTestCCLLogic_multi_region_zone_configs1571098934
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !
F230510 13:29:41.876302 9524 3@pebble/db.go:811  [n5,s5,pebble] 1 !For more context, check log files in: /artifacts/tmp/_tmp/3bd8bf58f451d1175df6c8dde3b28cd7/logTestCCLLogic_multi_region_zone_configs1571098934
```

Jira issue: CRDB-27797

**Comment by jbowens** [comment]
Fixed by cockroachdb/pebble#2517
