### ISSUE TITLE
sql: TestAmbiguousCommitDueToLeadershipChange times out

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#10341]
times out in `make stress PKG=./sql TESTS=TestAmbiguousCommitDueToLeadershipChange` (after the default 2min timeout, likely also with `TESTTIMEOUT=30s`).

```
goroutine 796 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/pkg/sql_test.TestAmbiguousCommitDueToLeadershipChange.func1(0x1482b6b16cd4e703, 0x0, 0x100000001, 0x1, 0x7, 0x0, 0xc42079e300, 0x0, 0xc420e360e0, 0x0, ...)
       	/home/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/sql/ambiguous_commit_test.go:74 +0x232
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc4214d6700, 0x7f1ad297e3c0, 0xc4204a97a0, 0x1482b6b16cd4e703, 0x0, 0x100000001, 0x1, 0x7, 0x0, 0xc42079e300, ...)
       	/home/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1126 +0x33e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc4205f8380, 0x7f1ad297e3c0, 0xc4204a9740, 0x1482b6b16cd4e703, 0x0, 0x100000001, 0x1, 0x7, 0x0, 0xc42079e300, ...)
       	/home/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2312 +0x755
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc4201c2600, 0x7f1ad297e3c0, 0xc4204a96b0, 0x0, 0x0, 0x100000001, 0x1, 0x7, 0x0, 0xc42079e300, ...)
       	/home/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x202
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x0, 0x0)
       	/home/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:843 +0x2a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc4201e2090, 0xc420149848, 0x0, 0x0)
       	/home/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0x100
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc4200db400, 0x7f1ad297e3c0, 0xc4204a95f0, 0xc421354460, 0xc4204a95f0, 0xc4209a1a60, 0x5d8117)
       	/home/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:854 +0x1ed
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc4200db400, 0x7f1ad297e3c0, 0xc4204a95f0, 0xc421354460, 0x0, 0x156, 0x156)
       	/home/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:874 +0x9b
github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler(0x1816520, 0xc4200db400, 0x7f1ad297e3c0, 0xc4204a9320, 0xc4204b4370, 0x0, 0x0, 0x0, 0x0, 0x756ea13bf9d696)
       	/home/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:1512 +0x27d
google.golang.org/grpc.(*Server).processUnaryRPC(0xc4201c6d20, 0x2332fa0, 0xc42048a2d0, 0xc42129ef00, 0xc4200f4570, 0x22fd6b0, 0x0, 0x0, 0x0)
       	/home/tschottdorf/go/src/google.golang.org/grpc/server.go:611 +0xc50
google.golang.org/grpc.(*Server).handleStream(0xc4201c6d20, 0x2332fa0, 0xc42048a2d0, 0xc42129ef00, 0x0)
       	/home/tschottdorf/go/src/google.golang.org/grpc/server.go:769 +0x6b0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4208aeaa0, 0xc4201c6d20, 0x2332fa0, 0xc42048a2d0, 0xc42129ef00)
       	/home/tschottdorf/go/src/google.golang.org/grpc/server.go:422 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
       	/home/tschottdorf/go/src/google.golang.org/grpc/server.go:423 +0xa3
````

**Comment by tschottdorf** [comment]
Assigning @spencerkimball based on `git blame`.
