### ISSUE TITLE
changefeedccl: flake in TestChangefeedHandlesRollingRestart

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#103791]
Found [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10209945?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true)

```
No pass/skip/fail event found for test
=== RUN   TestChangefeedHandlesRollingRestart
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/b478c2ad99c391e44e94a7d30cff9d79/logTestChangefeedHandlesRollingRestart39318544
    test_log_scope.go:79: use -show-logs to present logs inline
    helpers_test.go:902: making cloudstorage feed factory
    changefeed_test.go:6237:
          Error Trace:  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_test.go:6237
          Error:        Received unexpected error:
                        waiting to tick: current=1684851539.246234656,0 min=1684851539.246370137,0
                        (1) attached stack trace
                          -- stack trace:
                          | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*jobFeed).TickHighWaterMark.func1
                          |   github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/testfeed_test.go:501
                          | github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError.func1
                          |   github.com/cockroachdb/cockroach/pkg/testutils/soon.go:71
                          | github.com/cockroachdb/cockroach/pkg/util/retry.ForDuration
                          |   github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:213
                          | github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError
                          |   github.com/cockroachdb/cockroach/pkg/testutils/soon.go:77
                          | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*jobFeed).TickHighWaterMark
                          |   github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/testfeed_test.go:493
                          | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedHandlesRollingRestart
                          |   github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_test.go:6237
                          | testing.tRunner
                          |   GOROOT/src/testing/testing.go:1446
                          | runtime.goexit
                          |   GOROOT/src/runtime/asm_amd64.s:1594
                        Wraps: (2) waiting to tick: current=1684851539.246234656,0 min=1684851539.246370137,0
                        Error types: (1) *withstack.withStack (2) *errutil.leafError
          Test:         TestChangefeedHandlesRollingRestart
    panic.go:522: still waiting for job status; current reverting
*
* INFO: slow quiesce. stack traces:
* goroutine 190822 [running]:
* [...]
```

Jira issue: CRDB-28203

**Comment by knz** [comment]
cc @miretskiy is that going to be improved by your in-flight PR?

**Comment by miretskiy** [comment]
> 

job registry shutdown PR? not sure...
