### ISSUE TITLE
kv: panic "use of tracing span after finish" in server tests related to replica rebalancer & multi-store

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#103763]
**Describe the problem**

I ran `dev test //pkg/server` and got the following error on one of the tests. The stack trace tells me it's something about the replica rebalancer (`kvserver.ResolveLBRebalancingObjective`).

```
panic: use of Span after Finish. Span: initialize-additional-stores. Finish previously called at: <stack not captured. Set debugUseAfterFinish> [recovered]
        panic: use of Span after Finish. Span: initialize-additional-stores. Finish previously called at: <stack not captured. Set debugUseAfterFinish>

goroutine 41541 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0x8acb42e90?, {0x1fa7360, 0x8bf7bd200})
        github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:229 +0x6a
panic({0x465720, 0x85c93dd80})
        GOROOT/src/runtime/panic.go:884 +0x212
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish(0x886d470?)
        github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:181 +0x12b
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).RecordingType(0x8acd2b400)
        github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:441 +0x1e
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsVerbose(...)
        github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:449
github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog({0x1fa7360, 0x85d27c480})
        github.com/cockroachdb/cockroach/pkg/util/log/trace.go:92 +0x3a
github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x1fa7360, 0x85d27c480}, 0x2, 0x1, 0x0, 0x0?, {0xe110b3, 0x47}, {0x0, 0x0, ...})
        github.com/cockroachdb/cockroach/pkg/util/log/channels.go:101 +0x554
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
        github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
github.com/cockroachdb/cockroach/pkg/util/log.Infof(...)
        github.com/cockroachdb/cockroach/bazel-out/freebsd-fastbuild/bin/pkg/util/log/log_channels_generated.go:277
github.com/cockroachdb/cockroach/pkg/kv/kvserver.ResolveLBRebalancingObjective({0x1fa7360, 0x85d27c480}, 0x85fd88000, 0x8ad542430?)
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/rebalance_objective.go:265 +0xce
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RebalanceObjectiveManager).maybeUpdateRebalanceObjective(0x85f6bfbc0, {0x1fa7360, 0x85d27c480})
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/rebalance_objective.go:231 +0xdb
github.com/cockroachdb/cockroach/pkg/kv/kvserver.newRebalanceObjectiveManager.func3(_, {0x20000000, 0x20000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xbff0000000000000, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/rebalance_objective.go:211 +0x4c
github.com/cockroachdb/cockroach/pkg/kv/kvserver/allocator/storepool.(*StorePool).capacityChanged(_, _, {0x20000000, 0x20000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/allocator/storepool/store_pool.go:1020 +0x177
github.com/cockroachdb/cockroach/pkg/kv/kvserver/allocator/storepool.(*StorePool).storeDescriptorUpdate(_, {0x7, {{0x0, 0x0, 0x0}}, {0x3, {{0x8ad5423e9, 0x3}, {0x8ad542410, 0xf}}, ...}, ...})
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/allocator/storepool/store_pool.go:589 +0x4c7
github.com/cockroachdb/cockroach/pkg/kv/kvserver/allocator/storepool.(*StorePool).storeGossipUpdate(0x8ac52e0f0, {0x8ad5422e6?, 0x7?}, {{0x8bd092000, 0x14e, 0x160}, {0x1761b9ab3ac7e666, 0x0, 0x0}})
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/allocator/storepool/store_pool.go:560 +0x1a5
github.com/cockroachdb/cockroach/pkg/gossip.(*infoStore).runCallbacks.func1()
        github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/infostore.go:340 +0x74
github.com/cockroachdb/cockroach/pkg/gossip.newInfoStore.func1({0x8ae46b800?, 0x0?})
        github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/infostore.go:188 +0x177
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
        github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
        github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
```

**To Reproduce**

`dev test //pkg/server` on my machine. 

The other bits in the stack dump mention `server.TestNodesV2` so I assume the problem can be reproduced by stress-running that specific test.

Jira issue: CRDB-28193

**Comment by erikgrinaker** [comment]
cc @cockroachdb/kv-distribution

**Comment by knz** [comment]
also in `TestMultiStoreIDAlloc`.

**Comment by kvoli** [comment]
I think this is using the init function scope ctx for callbacks:

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/rebalance_objective.go#L211

It should be using a bg ctx.

**Comment by knz** [comment]
@kvoli when you fix this don't forget to use AnnotateCtx on the new context.

**Comment by kvoli** [comment]
The `RebalanceObjectiveManager` doesn't have an ambient context to annotate the new context with. Could you explain more @knz?

**Comment by knz** [comment]
> The RebalanceObjectiveManager doesn't have an ambient context to annotate the new context with

Then make one :)
Or alternatively use `logtags.AddTags(context.Background(), logtags.FromContext(initCtx))`
but really the ambientctx is better, because it will ensure the objective manager events will be included in traces.

**Comment by kvoli** [comment]
I see what you mean, thanks for explaining.
