### ISSUE TITLE
sql: support qualified function names

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#10417]
We may have to support qualified function names to support Hibernate.

Repro:
Run @nvanbenschoten's example Hibernate app (cockroachdb/examples-orms#2) twice. (The first time currently fails because of the currently being addressed lack of `pg_catalog.pg_settings`.)

Output:
```
ERROR: ERROR: unknown function: pg_catalog.pg_get_expr
Exception in thread "main" org.hibernate.exception.GenericJDBCException: Error accessing column metadata: company.customers
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
        at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.convertSQLException(InformationExtractorJdbcDatabaseMetaDataImpl.java:97)
        at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.getColumn(InformationExtractorJdbcDatabaseMetaDataImpl.java:485)
        at org.hibernate.tool.schema.extract.internal.TableInformationImpl.getColumn(TableInformationImpl.java:68)
        at org.hibernate.mapping.Table.sqlAlterStrings(Table.java:456)
        at org.hibernate.tool.schema.internal.SchemaMigratorImpl.migrateTable(SchemaMigratorImpl.java:367)
        at org.hibernate.tool.schema.internal.SchemaMigratorImpl.performMigration(SchemaMigratorImpl.java:260)
        at org.hibernate.tool.schema.internal.SchemaMigratorImpl.doMigration(SchemaMigratorImpl.java:137)
        at org.hibernate.tool.schema.internal.SchemaMigratorImpl.doMigration(SchemaMigratorImpl.java:110)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:176)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:65)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:308)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:476)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:707)
        at com.cockroachlabs.Application.buildSessionFactory(Application.java:45)
        at com.cockroachlabs.Application.main(Application.java:17)
Caused by: org.postgresql.util.PSQLException: ERROR: unknown function: pg_catalog.pg_get_expr
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
        at org.postgresql.jdbc.PgDatabaseMetaData.getColumns(PgDatabaseMetaData.java:1703)
        at org.postgresql.jdbc.PgDatabaseMetaData.getColumns(PgDatabaseMetaData.java:1802)
        at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.getColumn(InformationExtractorJdbcDatabaseMetaDataImpl.java:458)
```

I tried adding `pg_catalog.pg_expr` as an identity function:

```
diff --git a/pkg/sql/parser/builtins.go b/pkg/sql/parser/builtins.go
index 2f74848..9fac249 100644
--- a/pkg/sql/parser/builtins.go
+++ b/pkg/sql/parser/builtins.go
@@ -1142,6 +1142,15 @@ var Builtins = map[string][]Builtin{
                        },
                },
        },
+       "pg_catalog.pg_get_expr": {
+               Builtin{
+                       Types:      VariadicType{TypeString},
+                       ReturnType: TypeString,
+                       fn: func(_ *EvalContext, args DTuple) (Datum, error) {
+                               return args[0], nil
+                       },
+               },
+       },
 }

 func init() {
```

However, this didn't resolve the issue. I suspect that we're not parsing function names with `.` correctly.

@knz any thoughts here?

**Comment by nvanbenschoten** [comment]
Qualified functions are subtly different from normal functions with a `.` in the name in that they can also be used in their unqualified form. For instance,  

```
select pg_catalog.pg_get_expr(def.adbin, def.adrelid) from pg_catalog.pg_attrdef def
```

and 

```
select pg_get_expr(def.adbin, def.adrelid) from pg_catalog.pg_attrdef def
```

both work. We could work around this by adding the qualified and unqualified version of these functions to our `Builtins` map, but that seems messy and wont work for duplicated unqualified names.

**Comment by knz** [comment]
What ought to be done here is similar to what we did for virtual tables. We must introduce the notion of namespaces for builtin functions too, and look up functions in the namespaces where they are defined (probably modulo a lookup list in the session). Meanwhile I kinda understand that pg uses "schemas" (like "pg_catalog") as namespaces and anchors functions in there too. 

So this gives me an idea to hack something in our product that would make sense for the time being. We could do the lookup of a non-qualified function first in our regular builtin list; then if it is not found there, try to prepend each name in our existing `Session.SearchPath` with a '.' separator and search again. The code that does function lookups is currently embedded in `FuncExpr.TypeCheck()` in `sql/parser/type_check.go`, that would need to be extended accordingly.

Later on we should probably have "function descriptors" (which we'll need anyway whenever we support user-defined functions) and fully anchor builtin functions to db/namespace descriptors.

**Comment by knz** [comment]
Oh I forgot to say, if the name is already qualified you can find this out via `FuncExpr.Context`, see the check that currently rejects prefixes `if len(fname.Context) > 0 { ... }` in there.

**Comment by cuongdo** [comment]
@knz will you have time to take this on soon?
