### ISSUE TITLE
acceptance: TestDockerNodeJS is flaky

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#104172]
I've seen this fail a few times on bors, e.g. [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=10336751&buildTypeId=Cockroach_BazelEssentialCi).

Jira issue: CRDB-28383

**Comment by rafiss** [comment]
in case we lose the artifacts:
```
  1) failure smoke test
       causes the docker build to fail on a test failure:
     AssertionError [ERR_ASSERTION]: undefined undefined undefined
      at Context.it (base-test.js:21:14)
      at callFn (/usr/lib/node/mocha/lib/runnable.js:354:21)
      at Test.Runnable.run (/usr/lib/node/mocha/lib/runnable.js:346:7)
      at Runner.runTest (/usr/lib/node/mocha/lib/runner.js:442:10)
      at /usr/lib/node/mocha/lib/runner.js:560:12
      at next (/usr/lib/node/mocha/lib/runner.js:356:14)
      at /usr/lib/node/mocha/lib/runner.js:366:7
      at next (/usr/lib/node/mocha/lib/runner.js:290:14)
      at Immediate.<anonymous> (/usr/lib/node/mocha/lib/runner.js:334:5)
  2) sequelize
       can create a model with an inverted index:
     Uncaught Error: Connection terminated unexpectedly
      at Connection.con.once (/usr/lib/node/pg/lib/client.js:179:21)
      at TLSSocket.<anonymous> (/usr/lib/node/pg/lib/connection.js:123:10)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
(node:23) UnhandledPromiseRejectionWarning: Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:364:12)
    at Connection.end (/usr/lib/node/pg/lib/connection.js:313:22)
    at global.Promise (/usr/lib/node/pg/lib/client.js:410:23)
    at new Promise (<anonymous>)
    at Client.end (/usr/lib/node/pg/lib/client.js:409:12)
    at Context.after (/mnt/data/node/client.js:51:10)
    at callFn (/usr/lib/node/mocha/lib/runnable.js:354:21)
    at Hook.Runnable.run (/usr/lib/node/mocha/lib/runnable.js:346:7)
    at next (/usr/lib/node/mocha/lib/runner.js:304:10)
    at Immediate._onImmediate (/usr/lib/node/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Unhandled rejection TypeError: Cannot read property 'currentRetry' of undefined
    at /usr/lib/node/mocha/lib/runner.js:563:28
    at done (/usr/lib/node/mocha/lib/runnable.js:301:5)
    at /usr/lib/node/mocha/lib/runnable.js:365:11
    at tryCatcher (/usr/lib/node/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/lib/node/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
non-zero exit code: 2
*
* INFO: command left-over files in /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestDockerNodeJS/runMode=docker#01/d9d385ad
*
    dockercluster.go:717: unexpected extra event &{0 die} (after [])
    --- FAIL: TestDockerNodeJS/runMode=docker#01 (13.41s)
   
```

**Comment by rafiss** [comment]
I think that test failure was caused by this error I found in the CRDB logs.
```
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607  a panic has occurred!
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +panic: â€¹reflect: reflect.Value.Set using unaddressable valueâ€º
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +(1) attached stack trace
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  -- stack trace:
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | runtime.gopanic
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	GOROOT/src/runtime/panic.go:884
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.RecoverAndReportNonfatalPanic
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:148
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | runtime.gopanic
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	GOROOT/src/runtime/panic.go:884
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | reflect.flag.mustBeAssignableSlow
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	GOROOT/src/reflect/value.go:260
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | reflect.flag.mustBeAssignable
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	GOROOT/src/reflect/value.go:247
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | reflect.Value.Set
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	GOROOT/src/reflect/value.go:2154
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/cockroachdb/cockroach/pkg/server/diagnostics.stringRedactor.Primitive
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/cockroachdb/cockroach/pkg/server/diagnostics/reporter.go:446
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.walkPrimitive
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:251
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.walk
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:179
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.walkMap
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:233
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.walk
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:182
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.walkStruct
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:385
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.walk
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:188
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.walkStruct
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:385
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.walk
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:188
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.walkStruct
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:385
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.walk
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:188
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/mitchellh/reflectwalk.Walk
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/mitchellh/reflectwalk/external/com_github_mitchellh_reflectwalk/reflectwalk.go:92
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/cockroachdb/cockroach/pkg/server/diagnostics.(*Reporter).collectSchemaInfo
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/cockroachdb/cockroach/pkg/server/diagnostics/reporter.go:340
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/cockroachdb/cockroach/pkg/server/diagnostics.(*Reporter).CreateReport
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/cockroachdb/cockroach/pkg/server/diagnostics/reporter.go:193
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/cockroachdb/cockroach/pkg/server/diagnostics.(*Reporter).ReportDiagnostics
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/cockroachdb/cockroach/pkg/server/diagnostics/reporter.go:137
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/cockroachdb/cockroach/pkg/server/diagnostics.(*Reporter).PeriodicallyReportDiagnostics.func1
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/cockroachdb/cockroach/pkg/server/diagnostics/reporter.go:113
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | runtime.goexit
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +  | 	GOROOT/src/runtime/asm_amd64.s:1594
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +Wraps: (2) panic: â€¹reflect: reflect.Value.Set using unaddressable valueâ€º
E230531 21:33:00.991669 2543 1@util/log/logcrash/crash_reporting.go:188 â‹® [T1,n1] 28607 +Error types: (1) *withstack.withStack (2) *errutil.leafError
```

**Comment by rafiss** [comment]
@Xiang-Gu can you try to determine why the panic occurred?

**Comment by rafiss** [comment]
This patch should fix it:
```
diff --git a/pkg/server/diagnostics/reporter.go b/pkg/server/diagnostics/reporter.go
index 62b68124f18..190798ce12e 100644
--- a/pkg/server/diagnostics/reporter.go
+++ b/pkg/server/diagnostics/reporter.go
@@ -442,7 +442,7 @@ func anonymizeZoneConfig(dst *zonepb.ZoneConfig, src zonepb.ZoneConfig, secret s
 type stringRedactor struct{}

 func (stringRedactor) Primitive(v reflect.Value) error {
-    if v.Kind() == reflect.String && v.String() != "" {
+    if v.CanSet() && v.Kind() == reflect.String && v.String() != "" {
         v.Set(reflect.ValueOf("_").Convert(v.Type()))
     }
     return nil
```

However, I don't know if that's the full solution. We should find out which field is having trouble, and why is it unaddressable. This should be possible with extra logging like this, then trying to get a repro:
```
@@ -443,6 +444,9 @@ type stringRedactor struct{}

 func (stringRedactor) Primitive(v reflect.Value) error {
     if v.Kind() == reflect.String && v.String() != "" {
+        if !v.CanSet() {
+            panic(fmt.Sprintf("cannot set. type=%s origVal=%s", v.Type().String(), v.String()))
+        }
         v.Set(reflect.ValueOf("_").Convert(v.Type()))
     }
     return nil
```

**Comment by rafiss** [comment]
Maybe we should even just merge that logging change and just wait for the next failure. I'll leave that decision to you @xiang-gu

**Comment by Xiang-Gu** [comment]
@rafiss provided more context in this [thread](https://cockroachlabs.slack.com/archives/CHVV403F0/p1686154985485659?thread_ts=1686089668.391209&cid=CHVV403F0) and the summary is that this code path is the "old" schema info collection and no one is actively looking at it (instead the "new" schema info collection framework is the `schematelemetry` package). We won't remove it entirely either but rather amend the check with a `v.CanSet()`. I will pull up a PR right now.
