### ISSUE TITLE
Debug Zip Missing Panic Logs

### ISSUE THREAD

**Issue by JeffSwenson** [cockroachdb/cockroach#104210]
**Describe the problem**

I collected a debug zip for a cluster that recently had nodes restart due to a panic. I was taking the debug zip in order to determine why a node was panicing. The stderr log containing the unexpected panic was not included in the debug zip. 

The debug zip logs contained this error that was generated by taking the debug zip. The error seems to suggest CRDB was unable to parse the stderr logs including the panic:

```
E230601 14:51:13.619603 86574 server/status.go:1310 ⋮ [T1,n1,status] 581 decoding on line 8: malformed log entry
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log.(*entryDecoderV2).Decode.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/log/format_crdb_v2.go:528
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | [...repeated from below...]
Wraps: (2) decoding on line 8
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log.(*entryDecoderV2).peekNextFragment
  | 	github.com/cockroachdb/cockroach/pkg/util/log/format_crdb_v2.go:615
  | github.com/cockroachdb/cockroach/pkg/util/log.(*entryDecoderV2).Decode
  | 	github.com/cockroachdb/cockroach/pkg/util/log/format_crdb_v2.go:548
  | github.com/cockroachdb/cockroach/pkg/server.(*statusServer).LogFile
  | 	github.com/cockroachdb/cockroach/pkg/server/status.go:1306
  | github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_LogFile_Handler.func1
  | 	github.com/cockroachdb/cockroach/pkg/server/serverpb/bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:9040
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:115
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1162
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:276
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:105
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:243
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:241
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165
  | google.golang.org/grpc.chainUnaryInterceptors.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1167
  | github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_LogFile_Handler
  | 	github.com/cockroachdb/cockroach/pkg/server/serverpb/bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:9042
  | google.golang.org/grpc.(*Server).processUnaryRPC
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1340
  | google.golang.org/grpc.(*Server).handleStream
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1713
  | google.golang.org/grpc.(*Server).serveStreams.func1.2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:965
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (4) malformed log entry
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
```

The content of the std error file was:

```
sh-4.4# cat cockroach-stderr.cockroachdb-0.root.2023-05-31T21_52_20Z.000030.log
I230531 21:52:20.499220 1 util/log/file_sync_buffer.go:238 ⋮ [config]   file created at: 2023/05/31 21:52:20
I230531 21:52:20.499241 1 util/log/file_sync_buffer.go:238 ⋮ [config]   running on machine: cockroachdb-0
I230531 21:52:20.499248 1 util/log/file_sync_buffer.go:238 ⋮ [config]   binary: CockroachDB CCL v23.1.2 (x86_64-pc-linux-gnu, built 2023/05/25 15:51:13, go1.19.4)
I230531 21:52:20.499255 1 util/log/file_sync_buffer.go:238 ⋮ [config]   arguments: [/cockroach/cockroach start --certs-dir /cockroach/cockroach-certs --listen-addr 0.0.0.0:26258 --http-addr 0.0.0.0:8080 --sql-addr 0.0.0.0:26257 --advertise-addr cockroachdb-0.cockroachdb.us-west-2.svc.cluster.local:26258 --advertise-sql-addr cockroachdb-0.cockroachdb.us-west-2.svc.cluster.local:26257 --join _grpc._tcp.cockroachdb.us-west-2.svc --experimental-dns-srv --cache 25% --max-sql-memory 25% --locality=region=aws-us-west-2,az=aws-us-west-2a,dns=cockroachdb-0.cockroachdb.us-west-2.svc.cluster.local --log-config-file /cockroach/config/logs.yaml --log-config-vars HOST_IP --external-io-dir=disabled --max-offset=100ms]
I230531 21:52:20.499284 1 util/log/file_sync_buffer.go:238 ⋮ [config]   log format (utf8=✓): crdb-v2
I230531 21:52:20.499288 1 util/log/file_sync_buffer.go:238 ⋮ [config]   line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid [chan@]file:line redactionmark \[tags\] [counter] msg
I230531 21:52:20.498414 1 util/log/flags.go:211  [-] 1  stderr capture started
panic: invalid tenant ID 0

goroutine 6603729 [running]:
github.com/cockroachdb/cockroach/pkg/roachpb.assertValid(0x5398fe0?)
        github.com/cockroachdb/cockroach/pkg/roachpb/pkg/roachpb/tenant.go:99 +0x59
github.com/cockroachdb/cockroach/pkg/roachpb.MustMakeTenantID(...)
        github.com/cockroachdb/cockroach/pkg/roachpb/pkg/roachpb/tenant.go:52
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.backupShowerDefault.func1({0x7281e90, 0xc00644dd40}, {{0xc008bfee10, 0x2e0}, {0xc00c389130, 0x1, 0x1}, {0xc001812600, 0x1, 0x1}, ...})
        github.com/cockroachdb/cockroach/pkg/ccl/backupccl/show.go:967 +0x24eb
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.manifestInfoReader.showBackup({{{0xc008961500?, 0x0?, 0x0?}, 0xc00c284120?}}, {0x7281e90?, 0xc00c284fc0?}, _, _, {{0xc008bfee10, 0x2e0}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/ccl/backupccl/show.go:120 +0x205
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.showBackupPlanHook.func1({0x7281e90, 0xc00c284f00}, {0x0?, 0x0?, 0x0?}, 0xc00e8503c0?)
        github.com/cockroachdb/cockroach/pkg/ccl/backupccl/show.go:531 +0x1fc5
github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1()
        github.com/cockroachdb/cockroach/pkg/sql/planhook.go:205 +0xa4
created by github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec
        github.com/cockroachdb/cockroach/pkg/sql/planhook.go:203 +0x1b2
```

Epic CRDB-32134

**Comment by JeffSwenson** [comment]
Internal thread: https://cockroachlabs.slack.com/archives/C04N0AS14CT/p1685631557807329?thread_ts=1685463812.618679&cid=C04N0AS14CT

**Comment by michae2** [comment]
[paraphrasing @c-raj during postmortem]: We saw this in the `cockroach-stderr.*.log.err.txt` files gathered by the debug.zip:

```
rpc error: code = Internal desc = An internal server error has occurred. Please check your CockroachDB logs for more details.
```

Then @joshimhoff had to shell into one of the nodes to get the actual contents of `cockroach-stderr.*.log` which had the stacktrace, as described in this [thread](https://cockroachlabs.slack.com/archives/C073N36Q16Z/p1715854123020149).

**Comment by michae2** [comment]
Jira: https://cockroachlabs.atlassian.net/browse/CRDB-32222

**Comment by michae2** [comment]
Only because it caused difficulty during a recent escalation, and it seems like the observability team might not have the bandwidth to address it anytime soon. And I'm guessing it's not too difficult. But you're right, this ins't really in an area owned by the queries team.

**Comment by yuzefovich** [comment]
I see. Looks like Akshay is assigned to this issue, so hopefully it'll get addressed soon. I'll drop it from Queries board.

**Comment by alyshanjahani-crl** [comment]
I've observed a similar failure mode where a panic in the log files causes the `_status/logs` endpoint to fail.

@aa-joshi could you take a look at https://github.com/cockroachdb/cockroach/issues/151493
