### ISSUE TITLE
sql: server panic when not passing the right number of args to a query and using lib/pq directly

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#10469]
Doesn't seem to repro easily in a standalone test (the expected error about missing arguments is returned to the client), but this branch repros: `https://github.com/andreimatei/cockroach/tree/driverutil-test`

`make test PKG=./pkg/cli TESTS=TestDumpBytes`

The cli/dump.go code on the branch has a bug and so arguments are missing.
I think the server crashes on the second iteration of the loop, on this line:
https://github.com/andreimatei/cockroach/blob/driverutil-test/pkg/cli/dump.go#L229

```
    panic: SELECT b, * FROM t@primary AS OF SYSTEM TIME 1478278234955975090.0000000000 WHERE ROW (b) > ROW ($1) ORDER BY b LIMIT 100: interface conversion: parser.VariableExpr is *parser.Placeholder, not *parser.IndexedVar

goroutine 118 [running]:
panic(0x51a5220, 0xc4205b5260)
    /Users/andrei/work/src/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420385290)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x51a5220, 0xc4205b5260)
    /Users/andrei/work/src/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc4208a8554, 0x79)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:409 +0x149
panic(0x51d1aa0, 0xc420316d00)
    /Users/andrei/work/src/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*selectNode).expandPlan.func1(0x8212ca8, 0xc4203d2de0, 0xc4203d2de0, 0xc42041d918, 0xc420386101)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/select.go:410 +0xc3
github.com/cockroachdb/cockroach/pkg/sql.(*varConvertVisitor).VisitPre(0xc4205b5240, 0x5b85d20, 0xc4203d2de0, 0xc420386140, 0x16, 0xc420386140)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/expr_filter.go:80 +0x10e
github.com/cockroachdb/cockroach/pkg/sql/parser.WalkExpr(0x5b78020, 0xc4205b5240, 0x5b85d20, 0xc4203d2de0, 0x5b85ae0, 0xc420386140, 0x492b800)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/parser/walk.go:435 +0x55
github.com/cockroachdb/cockroach/pkg/sql/parser.walkExprSlice(0x5b78020, 0xc4205b5240, 0xc42058db80, 0x1, 0x1, 0x0, 0x0, 0x1, 0xc42013f900)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/parser/walk.go:329 +0xad
github.com/cockroachdb/cockroach/pkg/sql/parser.(*Tuple).Walk(0xc420738900, 0x5b78020, 0xc4205b5240, 0xc420316b01, 0x5b85f60)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/parser/walk.go:352 +0x5e
```

**Comment by knz** [comment]
I found a repro. Thanks for finding this bug!
