### ISSUE TITLE
*: Investigate memory/go routine leaks in klauspost/pgzip library

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#106774]
Observed on telemetry cluster...

Super high CPU usage; majority due to go GC:
<img width="1483" alt="Screenshot 2023-07-13 at 2 28 59 PM" src="https://github.com/cockroachdb/cockroach/assets/54641364/7113ffdd-8ccd-44da-8623-cf6c15266598">

Heap: (75% attributed to gzip):
<img width="1492" alt="Screenshot 2023-07-13 at 2 29 49 PM" src="https://github.com/cockroachdb/cockroach/assets/54641364/b1dcb26c-8da4-4898-91ea-6cb06783899e">

Multiple go routines with the following stack(s):
```
goroutine 867880839 [chan receive, 2722 minutes]:
github.com/klauspost/pgzip.(*Writer).Write.func1()
	github.com/klauspost/pgzip/external/com_github_klauspost_pgzip/gzip.go:364 +0x5a
created by github.com/klauspost/pgzip.(*Writer).Write
	github.com/klauspost/pgzip/external/com_github_klauspost_pgzip/gzip.go:360 +0x20c

goroutine 877321273 [chan receive, 2653 minutes]:
github.com/klauspost/pgzip.(*Writer).Write.func1()
	github.com/klauspost/pgzip/external/com_github_klauspost_pgzip/gzip.go:364 +0x5a
created by github.com/klauspost/pgzip.(*Writer).Write
	github.com/klauspost/pgzip/external/com_github_klauspost_pgzip/gzip.go:360 +0x20c
```

Only 2 changefeeds running; that should not add up to such high memory...
And we should never have pgzip go routines running for hours on end.
There is something highly suspect happening in that compression library.

Jira issue: CRDB-29711

**Comment by miretskiy** [comment]
Putting DR on this issue because DR is also a large user of this library.
