### ISSUE TITLE
sql: panic on DROP INDEX

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10673]
Found with nightly RSG today:
https://teamcity.cockroachdb.com/viewLog.html?buildId=47548&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: DROP INDEX ident , UNCOMMITTED CASCADE: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: DROP INDEX ident , UNCOMMITTED CASCADE: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b4 pc=0x9a6322]

goroutine 31771 [running]:
panic(0x16f7f40, 0xc420e63950)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42029c000)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x16f7f40, 0xc420e63950)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc427068cf6, 0x26)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:416 +0x149
panic(0x171b180, 0xc420012120)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*TableDescriptor).MaybeUpgradeFormatVersion(0x0, 0x17c7340)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/structured.go:345 +0x22
github.com/cockroachdb/cockroach/pkg/sql.(*planner).getDescriptor(0xc426baeb70, 0x2398280, 0xc422e47120, 0x23aa500, 0xc4282e6fc0, 0x0, 0x0, 0x74)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/descriptor.go:211 +0x2b3
github.com/cockroachdb/cockroach/pkg/sql.(*planner).getTableOrViewDesc(0xc426baeb70, 0xc422693080, 0x8c7745, 0xc427068d01, 0x5)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:146 +0x1e0
github.com/cockroachdb/cockroach/pkg/sql.(*planner).getTableDesc(0xc426baeb70, 0xc422693080, 0x95a4b0, 0x238c380, 0x2)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:158 +0x39
github.com/cockroachdb/cockroach/pkg/sql.(*planner).mustGetTableDesc(0xc426baeb70, 0xc422693080, 0xc427068d01, 0x5, 0x1)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:197 +0x39
github.com/cockroachdb/cockroach/pkg/sql.(*planner).findTableContainingIndex(0xc426baeb70, 0xc426b83043, 0x5, 0xc427068d01, 0x5, 0x0, 0xc421edf6c0, 0x85a069)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:556 +0x13d
github.com/cockroachdb/cockroach/pkg/sql.(*planner).expandIndexName(0xc426baeb70, 0xc4249d5c20, 0x2, 0xc42524c540, 0x2)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:585 +0xaa
github.com/cockroachdb/cockroach/pkg/sql.(*planner).DropIndex(0xc426baeb70, 0xc4249d5da0, 0xc42a5cab80, 0x62, 0x62, 0x62)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/drop.go:244 +0xbb
```

**Comment by knz** [comment]
cc @mjibson

**Comment by knz** [comment]
Dup https://github.com/cockroachdb/cockroach/issues/10322
