### ISSUE TITLE
Node crashes during transaction after taking other node down

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#1071]
Scenario:
- init node 0
- start nodes 0, 1, 2
- start client (examples/bank/ with --use-transaction=true) specifying node 1 address
- wait a bit to make sure we have a steady stream of operations and until range 1 is replicated across all nodes.
- gracefully kill node 0

Result:
node 2 dies on a nil pointer deref:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xabcf89]

goroutine 116270 [running]:
github.com/cockroachdb/cockroach/storage.(*Store).resolveWriteIntentError(0xc208122000, 0x7f48ededd380, 0xc20820ede0, 0xc208f7cdc0, 0xc20812e240, 0x7f48edee3de8, 0xc2081e2280, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1234 +0x1069
github.com/cockroachdb/cockroach/storage.func·035(0xc208dbac70, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1128 +0x6f2
github.com/cockroachdb/cockroach/util.RetryWithBackoff(0xc208dbac70, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc208f91860, 0x0, ...)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/retry.go:81 +0x60
github.com/cockroachdb/cockroach/storage.(*Store).ExecuteCmd(0xc208122000, 0x7f48ededd380, 0xc2083431d0, 0x7f48edee3de8, 0xc2081e2280, 0x7f48edee3e40, 0xc208c00a00, 0x0, 0x0, 0x0, ...)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1154 +0x762
github.com/cockroachdb/cockroach/kv.(*LocalSender).Send(0xc20801d440, 0x7f48ededd380, 0xc2083431d0, 0x7f48edee3de8, 0xc2081e2280, 0x7f48edee3e40, 0xc208c00a00, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/kv/local_sender.go:150 +0x1cd
github.com/cockroachdb/cockroach/server.(*nodeServer).executeCmd(0xc2080a4000, 0x7f48edee3de8, 0xc2081e2280, 0x7f48edee3e40, 0xc208c00a00, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:501 +0xd3
github.com/cockroachdb/cockroach/server.(*nodeServer).Scan(0xc2080a4000, 0xc2081e2280, 0xc208c00a00, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:544 +0xb1
reflect.Value.call(0xe25580, 0xf30ac0, 0x13, 0xf5ac90, 0x4, 0xc208f91f28, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xe25580, 0xf30ac0, 0x13, 0xc208f91f28, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc2080ec200, 0xc208035f40, 0xc20817f0f8, 0xc208081f00, 0xc208168000, 0xf38b60, 0xc2081e2280, 0x16, 0xf28b40, 0xc208c00a00, ...)
	/usr/local/go/src/net/rpc/server.go:382 +0x1f7
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:476 +0x44a
```

store.go:1234 corresponds to:
```
  // We pushed the transaction(s) successfully, so resolve the intent(s).
  for i, intent := range wiErr.Intents {
    pushReply := bReply.Responses[i].GetValue().(*proto.InternalPushTxnResponse)
    resolveArgs := &proto.InternalResolveIntentRequest{
      RequestHeader: proto.RequestHeader{
        // Use the pushee's timestamp, which might be lower than the
        // pusher's request timestamp. No need to push the intent higher
        // than the pushee's txn!
        Timestamp: pushReply.PusheeTxn.Timestamp,
        Key:       intent.Key,
        User:      UserRoot,
        Txn:       pushReply.PusheeTxn,
      },   // <<<----- line 1234
    }
    resolveReply := &proto.InternalResolveIntentResponse{}
    // Add resolve command with wait=false to add to Raft but not wait for completion.
    waitForResolve := wait && i == len(wiErr.Intents)-1
    if resolveErr := rng.AddCmd(ctx, client.Call{Args: resolveArgs, Reply: resolveReply}, waitForResolve); resolveErr != nil {
      return resolveErr
    }
  }
```

Possibly relevant log entry shortly before crash: notice the nil value for args.Txn
```
L="INFO" T="2015-05-20T08:23:51-04:00" F="range_command.go:600" Msg="failed to push intent \"\" {id=4ea66e21-42a6-4c5e-bde3-3a949f0c61c6 pri=1177944141, iso=SERIALIZABLE, stat=PENDING, epo=0, ts=1432124630.628940344,0 orig=1432124630.628940344,0 max=1432124630.878940105,0} vs <nil> using priority=1171429496"
```

**Comment by MBerhault** [comment]
Occurs without killing any nodes.
I added logging right before L1234: (re-formatted for readability):
you'll notice a lack of PusheeTxn field in pushReply.
```
L="INFO" T="2015-05-20T09:36:59-04:00" F="store.go:1226" Msg="DEBUG:
pushReply: header:<timestamp:<wall_time:0 logical:0 > > 
intent: {Key:\"000000000\" Txn:\"\" {id=2399ab14-87f2-4ffc-8645-b48e9ffef9da pri=2052587552, iso=SERIALIZABLE, stat=PENDING, epo=0, ts=1432129012.288715363,1 orig=1432129010.166620493,0 max=1432129010.416620493,0} XXX_unrecognized:[]}
UserRoot: root"

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xabd123]

goroutine 1120891 [running]:
github.com/cockroachdb/cockroach/storage.(*Store).resolveWriteIntentError(0xc208122000, 0x7f7167f1b030, 0xc208282d20, 0xc2083d6f80, 0xc20808e630, 0x7f7167f26570, 0xc208276f00, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1236 +0x1203
github.com/cockroachdb/cockroach/storage.func·035(0xc208394070, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1128 +0x6f2
github.com/cockroachdb/cockroach/util.RetryWithBackoff(0xc208394070, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc2081af860, 0x0, ...)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/retry.go:81 +0x60
github.com/cockroachdb/cockroach/storage.(*Store).ExecuteCmd(0xc208122000, 0x7f7167f1b030, 0xc2082ef6b0, 0x7f7167f26570, 0xc208276f00, 0x7f7167f265c8, 0xc208144c80, 0x0, 0x0, 0x0, ...)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1154 +0x762
github.com/cockroachdb/cockroach/kv.(*LocalSender).Send(0xc20801d440, 0x7f7167f1b030, 0xc2082ef6b0, 0x7f7167f26570, 0xc208276f00, 0x7f7167f265c8, 0xc208144c80, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/kv/local_sender.go:150 +0x1cd
github.com/cockroachdb/cockroach/server.(*nodeServer).executeCmd(0xc2080a4000, 0x7f7167f26570, 0xc208276f00, 0x7f7167f265c8, 0xc208144c80, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:501 +0xd3
github.com/cockroachdb/cockroach/server.(*nodeServer).Scan(0xc2080a4000, 0xc208276f00, 0xc208144c80, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:544 +0xb1
reflect.Value.call(0xe25720, 0xf30c60, 0x13, 0xf5ae30, 0x4, 0xc2081aff28, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xe25720, 0xf30c60, 0x13, 0xc2081aff28, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc2080ec240, 0xc208035f80, 0xc20816c000, 0xc208081f80, 0xc2083602e0, 0xf38d00, 0xc208276f00, 0x16, 0xf28ce0, 0xc208144c80, ...)
```

**Comment by tschottdorf** [comment]
a `nil` value for `args.Txn` is fine. That just means that the trying to push is not in a transaction. We've had troubles in this method before - it's just very complex and it's easy to forget some things may be nil sometimes. I'm taking a look.

**Comment by tschottdorf** [comment]
The InternalPushTxnResponse looks empty, which is impossible if it actually reached `InternalPushTxn`. Is there maybe a race condition due to the fact that the same Call is used for multiple requests? Not sure how we'd end up with an empty response in that case but something is fishy here.

**Comment by tschottdorf** [comment]
Can reproduce this locally. Should get an idea shortly.

**Comment by tschottdorf** [comment]
probably the same double retry error as for the other thing earlier.

**Comment by yananzhi** [comment]
@tschottdorf  ref the pull request #1045. that bug may cause this problem.

**Comment by tschottdorf** [comment]
@yananzhi yes, must be the same thing. I could've sworn I had seen it again since but that was probably just #1086.

**Comment by tschottdorf** [comment]
@MBerhault see if you spot this again and reopen. I've run the kv test (which previously had this error) a couple hundred times.

**Comment by tschottdorf** [comment]
it's back.
