### ISSUE TITLE
stability: continuous block_writer test stalling

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#10727]
SHA: dd6e8e1fce4135f6308384b7f359f9c64eada2e3

Last night's 4-node, 4 `block_writer` instance continuous load test stalled after about 20 minutes of load:

```
[02:24:48][TestContinuousLoad_BlockWriter] 	continuous_load_test.go:178: no queries in the last 2m0s
```

The logs show a continuous stream of slow Raft operations starting about 15 minutes into the test:

```
W161116 07:18:08.132248 1445350 storage/engine/rocksdb.go:1010  batch [256562/16980562/39] commit took 625.269686ms (>500ms):
goroutine 1445350 [running]:
runtime/debug.Stack(0x179ba20, 0x23d8f00, 0xc4200142c0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc423492380, 0xc422619f50, 0x23de8c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1010 +0x212
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applySnapshot(0xc423bac000, 0x7fdb08a46840, 0xc422619f50, 0x84474848ec4a2d3e, 0x50b28df0c4754ab9, 0xa, 0xc4221bed80, 0x35, 0x40, 0xc4221bedc0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raftstorage.go:669 +0xc31
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc423bac000, 0x84474848ec4a2d3e, 0x50b28df0c4754ab9, 0xa, 0xc4221bed80, 0x35, 0x40, 0xc4221bedc0, 0x35, 0x40, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2240 +0x11eb
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc420311500, 0x7fdb08a46840, 0xc422619c80, 0xc422b425f8, 0x84474848ec4a2d3e, 0x50b28df0c4754ab9, 0xa, 0xc4221bed80, 0x35, 0x40, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2953 +0xc82
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc420311500, 0xc422b425a0, 0x7fdb07c4a038, 0xc422974e80, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2608 +0x746
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x23df880, 0xc422974e80, 0xc420156fc0, 0x7fdb08a46840, 0xc42373e9c0, 0xc42046e738, 0xc42046e740)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:362 +0x17f
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x7fdb08a46840, 0xc42373e9c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:363 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4201a1dd0, 0x209b785, 0x19, 0x16c, 0x0, 0x0, 0xc42373ea50, 0x7fdb08a46840, 0xc42373e9c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:264 +0xdf
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:265 +0x234
```

and

```
W161116 07:24:06.312473 89 storage/replica.go:554  [n1,s1,r12/10:/{Table/51/1/8…-Max}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 1.40112555s (>500ms):
goroutine 89 [running]:
runtime/debug.Stack(0x1d9e770, 0x1d9e7b0, 0x47)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/syncutil.ThresholdLogger.func1(0x53837aae)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:65 +0xe1
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*TimedMutex).Unlock(0xc4231f8078)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:92 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc4231f8000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2179 +0xee
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc420311500, 0xc)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3201 +0x13e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420312320, 0xc4201a1dd0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:230 +0x28c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a1dd0, 0xc4201d4e80)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
```

**Comment by cuongdo** [comment]
Per-node logs can be found in the failing test's artifacts:

https://teamcity.cockroachdb.com/viewLog.html?buildId=49465&buildTypeId=C_BW_4Nodes_6Hours&tab=artifacts

**Comment by petermattis** [comment]
This seems similar to the problem we're seeing on `delta`.

**Comment by petermattis** [comment]
I've asked @cuongdo to try and bisect to figure out which commit this started happening on. As a first step, he's going to see if it reliably happens on current master.

**Comment by cuongdo** [comment]
This is hard to reliably reproduce using the `block_writer` test. I launched four runs:

1. Failed in 30 minutes
2. Failed in 1h8m
3. Still running after 3h32m
4. Still running after 1h48m

Bisecting will likely be error-prone and lengthy.

**Comment by petermattis** [comment]
@cuongdo Is this still happening?

**Comment by cuongdo** [comment]
nope, not since the code yellow
