### ISSUE TITLE
stress: nightly CI job sometimes exits 2

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#107779]
![image](https://github.com/cockroachdb/cockroach/assets/5076964/34b6054c-4c94-48ba-83a0-5379de4032ad)

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11084331?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true

[Slack](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1690495844628399)

Jira issue: CRDB-30193

**Comment by tbg** [comment]
Also

```
failed parent test "TestCancelQuery" (no subtests)
  consolidating failed subtest "reject_cancel_from_wrong_client_IP" into parent test "TestCancelQuery"
  panic: assignment to entry in nil map
  goroutine 1 [running]:
  github.com/cockroachdb/cockroach/pkg/cmd/bazci/githubpost.getIssueFilerForFormatter.func1({0xdd5f10, 0xc00003a038}, {{0xc0003366f0, 0x27}, {0xc00012a0c0, 0x34}, {0xc00012a240, 0xf}, {0xc0002f6380, 0x34b}})
    github.com/cockroachdb/cockroach/pkg/cmd/bazci/githubpost/githubpost.go:104 +0x16a
  github.com/cockroachdb/cockroach/pkg/cmd/bazci/githubpost.processFailures({0xdd5f10, 0xc00003a038}, 0xc000280080, 0xb549a0?)
    github.com/cockroachdb/cockroach/pkg/cmd/bazci/githubpost/githubpost.go:558 +0x98c
  github.com/cockroachdb/cockroach/pkg/cmd/bazci/githubpost.listFailuresFromTestXML({0xdd5f10, 0xc00003a038}, {0xdcdcc0?, 0xc000014048?}, 0x0?)
    github.com/cockroachdb/cockroach/pkg/cmd/bazci/githubpost/githubpost.go:521 +0x1c7
  github.com/cockroachdb/cockroach/pkg/cmd/bazci/githubpost.PostFromTestXML({0xca27a5?, 0xbe?}, {0xdcdcc0, 0xc000014048})
    github.com/cockroachdb/cockroach/pkg/cmd/bazci/githubpost/githubpost.go:129 +0x52
  main.processTestXmls({0xc0002245c0, 0x1, 0xcb6ae3?})
    main/pkg/cmd/bazci/bazci.go:486 +0x2ad
  main.bazciImpl(0x12a5500?, {0xc0001b7c20?, 0x11, 0x12})
    main/pkg/cmd/bazci/bazci.go:384 +0x1290
  github.com/spf13/cobra.(*Command).execute(0x12a5500, {0xc000002290, 0x12, 0x13})
    github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:856 +0x67c
  github.com/spf13/cobra.(*Command).ExecuteC(0x12a5500)
    github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:974 +0x3bd
  github.com/spf13/cobra.(*Command).Execute(...)
    github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:902
  main.main()
    main/pkg/cmd/bazci/main.go:42 +0x7b
  Process exited with code 2
```

**Comment by rickystewart** [comment]
> Also, e.g.

This one seems unrelated. Might open another issue for this.
