### ISSUE TITLE
storage: goroutine leak in TestReplicateQueueRebalance

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10781]
Found in: https://teamcity.cockroachdb.com/viewLog.html?buildId=51030&buildTypeId=Cockroach_UnitTests

```
<autogenerated>:10: Leaked goroutine: goroutine 32639 [chan receive]: github.com/cockroachdb/cockroach/pkg/storage.(*Replica).beginCmds.func1(0xc42225f680, 0xc420243000, 0xc42045c198, 0xc42045c1a0) /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1370 +0x94 created by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).beginCmds /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1376 +0x14c4
```

**Comment by tamird** [comment]
Looks like a result of command cancellation without command queue cleanup during shutdown. Possibly introduced in #10772? @spencerkimball

**Comment by tamird** [comment]
This generated some 14 failures in this morning's `stress` run.
