### ISSUE TITLE
cdc: Stuck changefeed

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#108040]
As reported by @erikgrinaker , running experiment emitting into null:// sink deadlocked changefeed.
Relevant stacks below:

```
goroutine 6459467 [select, 108 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent.(*blockingBuffer).Get(0xc0b481b880, {0x7881e68, 0xc01bf92b40})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go:202 +0x165
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed.copyFromSourceToDestUntilTableEvent({0x7881e68, 0xc01bf92b40}, {0x7f1b0ddc1fa8?, 0xc094dcbdb8?}, {0x7f1aff8edf78, 0xc0b481b880}, 0xc0308be640?, {0x785e190?, 0xc04efa3b00?}, {0x17778b07a2024400, ...}, ...)
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed/kv_feed.go:707 +0x282
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed.(*kvFeed).runUntilTableEvent.func3({0x7881e68, 0xc01bf92b40})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed/kv_feed.go:510 +0x13f
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:72 +0xa5


goroutine 6459469 [select, 108 minutes]:
github.com/cockroachdb/cockroach/pkg/util/quotapool.(*AbstractPool).Acquire(0xc04b0309a0, {0x7881e68, 0xc01bf92d40}, {0x7857ba0, 0xc0b481b8a8})
	github.com/cockroachdb/cockroach/pkg/util/quotapool/quotapool.go:281 +0x75c
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent.(*blockingBuffer).AcquireMemory.func1(0x3cbcbcc?, 0xc0a0e29380?, {0x7881e68?, 0xc01bf92d40?})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go:241 +0xeb
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent.(*blockingBuffer).AcquireMemory(0xc0b481b880, {0x7881e68?, 0xc01bf92d40?}, 0x1a4)
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go:245 +0xd0
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent.(*blockingBuffer).Add(0xc0b481b880, {0x7881e68, 0xc01bf92d40}, {0xc08dbf1410, 0x2, {0x0, 0x0, 0x0}, {0xc12aaaecadd02bce, 0x2c44208c122, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go:268 +0x265
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed.(*rangefeed).addEventsToBuffer(0xc04b030a50, {0x7881e68?, 0xc01bf92d40?})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed/physical_kv_feed.go:109 +0x4cc
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:72 +0xa5
```

Jira issue: CRDB-30296

**Comment by erikgrinaker** [comment]
Reproduces readily with the following roachtest from #107722.

```
cdc/scan/catchup/nodes=5/cpu=16/rows=1G/ranges=100000/protocol=rangefeed/format=json/sink=null
```

It splits off 100.000 ranges, ingests 1 billion rows, then creates the following changefeed:

```sql
CREATE CHANGEFEED FOR kv.kv INTO 'null://' WITH cursor = <before_inserts>, end_time = <now>, format = 'json', min_checkpoint_frequency = '10s';
```

The changefeed will stop making progress after a few minutes, with catchup scans blocked sending to the stream, because the stream processors are blocked on quota acquisition as shown above. This happens across all nodes.
