### ISSUE TITLE
tenant startup hang

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#108209]
Seen in CI [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11125167?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true)

Log in case it gets deleted: Latest failure log for posterity: [gist.github.com/cucaroach/f94fdad2445225a218817cfdf6550357](https://gist.github.com/cucaroach/f94fdad2445225a218817cfdf6550357)

Backtrace of hang:

```
      goroutine 18866 [select, 59 minutes]:
      github.com/cockroachdb/cockroach/pkg/sql.(*ieResultChannel).firstResult(0xc00847a740, {0x549e280, 0xc00847cba0})
        github.com/cockroachdb/cockroach/pkg/sql/internal_result_channel.go:116 +0xf9
      github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal(0xc0079ab720, {0x549e280, 0xc00847cb10}, {0x47e4c44, 0x1f}, 0xc00847a740, 0x0?, {{{0x4773812, 0x4}}, {0x0, ...}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/internal.go:1089 +0x10a9
      github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).ExecEx(0x77359400?, {0x549e280, 0xc00847cb10}, {0x47e4c44, 0x1f}, 0x0?, {{{0x4773812, 0x4}}, {0x0, 0x0}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/internal.go:688 +0x185
      github.com/cockroachdb/cockroach/pkg/startupmigrations.runner.execAsRoot({{0x54c8ac0, 0xc005c09e60}, {{0xc001cdd698}, {0xc001cdd698}, 0x0}, 0xc0079ab720, 0xc00570c000}, {0x549e280?, 0xc00847cb10?}, {0x47e4c44, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/startupmigrations/migrations.go:384 +0xfc
      github.com/cockroachdb/cockroach/pkg/startupmigrations.runner.execAsRootWithRetry({{0x54c8ac0, 0xc005c09e60}, {{0xc001cdd698}, {0xc001cdd698}, 0x0}, 0xc0079ab720, 0xc00570c000}, {0x549e280, 0xc00847cb10}, {0x47e4c44, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/startupmigrations/migrations.go:400 +0x305
      github.com/cockroachdb/cockroach/pkg/startupmigrations.optInToDiagnosticsStatReporting({0x549e280, 0xc00847cb10}, {{0x54c8ac0, 0xc005c09e60}, {{0xc001cdd698}, {0xc001cdd698}, 0x0}, 0xc0079ab720, 0xc00570c000})
        github.com/cockroachdb/cockroach/pkg/startupmigrations/migrations.go:731 +0x125
      github.com/cockroachdb/cockroach/pkg/startupmigrations.(*Manager).EnsureMigrations.func3({0x549e280?, 0xc00847cb10?})
        github.com/cockroachdb/cockroach/pkg/startupmigrations/migrations.go:610 +0x4d
      github.com/cockroachdb/cockroach/pkg/util/startup.RunIdempotentWithRetry({0x549e280?, 0xc002a62c60?}, 0xc00316d860, {0x47d209c, 0x1c}, 0xc00799d390)
        github.com/cockroachdb/cockroach/pkg/util/startup/retry.go:127 +0x2ab
      github.com/cockroachdb/cockroach/pkg/startupmigrations.(*Manager).EnsureMigrations(0xc003fdd300, {0x549e280, 0xc002a62c60}, {0x5c09290?, 0xc0?, 0x570c000?, 0xc0?})
        github.com/cockroachdb/cockroach/pkg/startupmigrations/migrations.go:608 +0xe0d
      github.com/cockroachdb/cockroach/pkg/server.(*SQLServer).preStart(_, {_, _}, _, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1391 +0x9f1
      github.com/cockroachdb/cockroach/pkg/server.startTenantInternal({_, _}, _, {_, _}, {0xc00570c000, 0xc0019bee10, 0xc0014686c0, 0xc0014a8370, 0xc00466f240, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/server/tenant.go:339 +0x1518
      github.com/cockroachdb/cockroach/pkg/server.(*TestServer).StartTenant(_, {_, _}, {{0xa}, 0x0, 0x0, 0x0, 0x0, 0x0, {{0x0, ...}, ...}, ...})
        github.com/cockroachdb/cockroach/pkg/server/testserver.go:898 +0xf96
      github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartTenant({_, _}, {_, _}, {{0xa}, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:419 +0xa3
      github.com/cockroachdb/cockroach/pkg/sql_test.TestTenantStatementTimeoutAdmissionQueueCancelation(0xc00192f1e0)
        github.com/cockroachdb/cockroach/pkg/sql_test/pkg/sql/run_control_test.go:842 +0x6e7
      testing.tRunner(0xc00192f1e0, 0x4a5b058)
        GOROOT/src/testing/testing.go:1446 +0x10b
      created by testing.(*T).Run
        GOROOT/src/testing/testing.go:1493 +0x35f
```

There's 34 internal executor threads, they are stuck in these places:

```
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.acquireNodeLease
github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).Admit
google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader
```

Kinda feels like some sort of livelock.

Jira issue: CRDB-30363

**Comment by knz** [comment]
we have addressed this.

**Comment by RaduBerinde** [comment]
@knz do you have a reference to the PR(s) that fixed it? Trying to figure out if another issue (#110479) is a dup.

**Comment by knz** [comment]
A combination of:
- #109514
- #109111
- #104859  
- #108613 
- #107824
