### ISSUE TITLE
acceptance: flake in TestDockerCLI_test_connect

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#108393]
Seen on [this](https://teamcity.cockroachdb.com/viewLog.html?buildId=11239992&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_Tests_Acceptance) build on staging.

```
No pass/skip/fail event found for test
=== RUN   TestDockerCLI_test_connect/runMode=docker
    --- FAIL: TestDockerCLI_test_connect/runMode=docker (1.20s)
panic: Error response from daemon: unauthorized: authentication required [recovered]
	panic: Error response from daemon: unauthorized: authentication required [recovered]
	panic: Error response from daemon: unauthorized: authentication required

goroutine 62 [running]:
testing.tRunner.func1.2({0x4c29cc0, 0xc00094ae40})
	GOROOT/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1399 +0x39f
panic({0x4c29cc0, 0xc00094ae40})
	GOROOT/src/runtime/panic.go:884 +0x212
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*DockerCluster).stopOnPanic(0xc00349e0f0, {0x6406b10, 0xc000082048})
	github.com/cockroachdb/cockroach/pkg/acceptance/cluster/pkg/acceptance/cluster/dockercluster.go:254 +0x94
panic({0x4c29cc0, 0xc00094ae40})
	GOROOT/src/runtime/panic.go:884 +0x212
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.maybePanic(...)
	github.com/cockroachdb/cockroach/pkg/acceptance/cluster/pkg/acceptance/cluster/docker.go:245
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*DockerCluster).initCluster(0xc00349e0f0, {0x6406b10, 0xc000082048})
	github.com/cockroachdb/cockroach/pkg/acceptance/cluster/pkg/acceptance/cluster/dockercluster.go:359 +0x950
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*DockerCluster).Start(0xc00349e0f0, {0x6406b10?, 0xc000082048})
	github.com/cockroachdb/cockroach/pkg/acceptance/cluster/pkg/acceptance/cluster/dockercluster.go:656 +0x146
github.com/cockroachdb/cockroach/pkg/acceptance.StartCluster({0x6406b10, 0xc000082048}, 0xc000007d40, {{0xc000cad5a0, 0x1c}, {0x0, 0x0, 0x0}, 0x12a05f200, 0x0, ...})
	github.com/cockroachdb/cockroach/pkg/acceptance/util_cluster.go:80 +0x308
github.com/cockroachdb/cockroach/pkg/acceptance.testDocker.func1(0xc000007d40)
	github.com/cockroachdb/cockroach/pkg/acceptance/util_docker.go:138 +0x89e
testing.tRunner(0xc000007d40, 0xc000d22a40)
	GOROOT/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:1493 +0x35f
```
I'm not sure who is the owner of this, guessing Foundations.

**Comment by rafiss** [comment]
We do own this test, but `Error response from daemon: unauthorized: authentication required` is an error that only happens if the `docker pull` command has issues downloading the image from the registry. So I think DevInf would need to debug this.

**Comment by rickystewart** [comment]
Looks like some temporary network flake.

We could add retries in `pkg/acceptance/cluster/docker.go` (function `pullImage`)
