### ISSUE TITLE
stability: concurrent map read and map write

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10871]
This occurred on `delta` ~1h after wiping and recreating the cluster:

```
fatal error: concurrent map read and map write

goroutine 15692295 [running]:
runtime.throw(0x18f9478, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc66f9d7370 sp=0xc66f9d7350
runtime.mapaccess1_fast32(0x1748c80, 0xc608429830, 0x1, 0xc6576b8200)
	/usr/local/go/src/runtime/hashmap_fast.go:21 +0x1a4 fp=0xc66f9d7398 sp=0xc66f9d7370
github.com/cockroachdb/cockroach/pkg/roachpb.(*Transaction).MarshalTo(0xc651a81b00, 0xc531bc6fe3, 0xf6, 0xf6, 0xd4, 0x1d, 0xc)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/data.pb.go:945 +0x799 fp=0xc66f9d7528 sp=0xc66f9d7398
github.com/cockroachdb/cockroach/pkg/roachpb.(*Error).MarshalTo(0xc5efb196d0, 0xc531bc6fc6, 0x113, 0x113, 0x107, 0x3, 0xc66f9d7608)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/errors.pb.go:1337 +0x1f6 fp=0xc66f9d7588 sp=0xc66f9d7528
github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchResponse_Header).MarshalTo(0xc5e24af8c0, 0xc531bc6fc3, 0x116, 0x116, 0x116, 0x3, 0x116)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:4548 +0x10f fp=0xc66f9d7618 sp=0xc66f9d7588
github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchResponse).MarshalTo(0xc5e24af8c0, 0xc531bc6fc0, 0x119, 0x119, 0x119, 0x119, 0x183f960)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:4509 +0x102 fp=0xc66f9d7850 sp=0xc66f9d7618
github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchResponse).Marshal(0xc5e24af8c0, 0x7f7234485dd8, 0xc5e24af8c0, 0xc66f9d78e0, 0x1, 0x7f7234485dd8)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:4494 +0x84 fp=0xc66f9d78a8 sp=0xc66f9d7850
github.com/golang/protobuf/proto.Marshal(0x7f7234485dd8, 0xc5e24af8c0, 0xc5e24af8c0, 0xc66f9d7938, 0x18d4fed, 0x2, 0x1)
	/go/src/github.com/golang/protobuf/proto/encode.go:233 +0x7e fp=0xc66f9d7900 sp=0xc66f9d78a8
google.golang.org/grpc.protoCodec.Marshal(0x183f960, 0xc5e24af8c0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/rpc_util.go:68 +0x79 fp=0xc66f9d7958 sp=0xc66f9d7900
google.golang.org/grpc.(*protoCodec).Marshal(0x28ff458, 0x183f960, 0xc5e24af8c0, 0xc, 0xc66f9d7a40, 0xa4442b, 0xc420181180, 0x7f7234432840)
	<autogenerated>:22 +0x60 fp=0xc66f9d79a0 sp=0xc66f9d7958
google.golang.org/grpc.encode(0x24057e0, 0x28ff458, 0x183f960, 0xc5e24af8c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/google.golang.org/grpc/rpc_util.go:264 +0x2eb fp=0xc66f9d7a38 sp=0xc66f9d79a0
google.golang.org/grpc.(*Server).sendResponse(0xc4202c9ea0, 0x240d1e0, 0xc4214b41b0, 0xc538b63860, 0x183f960, 0xc5e24af8c0, 0x0, 0x0, 0xc6576b81d8, 0x0, ...)
	/go/src/google.golang.org/grpc/server.go:512 +0x91 fp=0xc66f9d7ad8 sp=0xc66f9d7a38
google.golang.org/grpc.(*Server).processUnaryRPC(0xc4202c9ea0, 0x240d1e0, 0xc4214b41b0, 0xc538b63860, 0xc42041df50, 0x23ceea0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:637 +0x108c fp=0xc66f9d7d60 sp=0xc66f9d7ad8
google.golang.org/grpc.(*Server).handleStream(0xc4202c9ea0, 0x240d1e0, 0xc4214b41b0, 0xc538b63860, 0x0)
	/go/src/google.golang.org/grpc/server.go:769 +0x6b0 fp=0xc66f9d7f20 sp=0xc66f9d7d60
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42073c2a0, 0xc4202c9ea0, 0x240d1e0, 0xc4214b41b0, 0xc538b63860)
	/go/src/google.golang.org/grpc/server.go:422 +0xab fp=0xc66f9d7f58 sp=0xc66f9d7f20
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc66f9d7f60 sp=0xc66f9d7f58
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/google.golang.org/grpc/server.go:423 +0xa3
```

@tamird The binary included your fix in #10869. I was including that fix because I hit the associated crash several times. Perhaps this is related.

**Comment by tamird** [comment]
Certainly seems related. Is that the only goroutine stack trace we got?

**Comment by petermattis** [comment]
[cockroach.stderr.104.196.173.128.txt.zip](https://github.com/cockroachdb/cockroach/files/602406/cockroach.stderr.104.196.173.128.txt.zip)

**Comment by petermattis** [comment]
Oops, that's the wrong one. Hold on.

**Comment by tamird** [comment]
Well, I would try removing the optimization of not cloning the last error
like the original version of my PR did.

**Comment by petermattis** [comment]
Ok, I'll try that. I'll have egg on my face if that is the fix.

**Comment by petermattis** [comment]
Seems to be fixed.
