### ISSUE TITLE
stability: terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10872]
This occurred on `delta` ~1h of wiping and recreating the cluster. Notably, it occurred shortly after #10871 and on a different node:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

`std::bad_alloc` is a C++-ism. No other stacktrace was generated so its a bit difficult to tell what happened. Shortly before dying, there were a number of Raft snapshots applied:

```
I161120 22:38:24.939993 6176251 storage/replica_raftstorage.go:617  [n5,s10,r85/5:/Table/51/1/2{730920…-872954…}] applying Raft snapshot at index 111534 (id=480beea4, encoded size=79117157, 76 rocksdb batches, 46 log entries)
I161120 22:38:25.323675 6176799 storage/replica_raftstorage.go:617  [n5,s10,r37/?:/Table/51/1/5{176534…-316200…}] applying Raft snapshot at index 432819 (id=0de75cd9, encoded size=78002142, 75 rocksdb batches, 720 log entries)
I161120 22:38:25.337263 6175710 storage/replica_raftstorage.go:617  [n5,s9,r80/3:/Table/51/1/7{055381…-197738…}] applying Raft snapshot at index 113423 (id=d4dfd214, encoded size=79547723, 76 rocksdb batches, 11 log entries)
I161120 22:38:25.615746 6176018 storage/replica_raftstorage.go:617  [n5,s10,r91/2:/Table/51/1/4{754757…-895087…}] applying Raft snapshot at index 108303 (id=5950d230, encoded size=78124443, 75 rocksdb batches, 13 log entries)
I161120 22:38:25.674927 6176533 storage/replica_raftstorage.go:617  [n5,s9,r66/8:/Table/51/1/4{466757…-614162…}] applying Raft snapshot at index 122311 (id=cc54ca8b, encoded size=82341099, 79 rocksdb batches, 33 log entries)
I161120 22:38:25.839955 6176341 storage/replica_raftstorage.go:617  [n5,s10,r38/7:/Table/51/1/4{320246…-466757…}] applying Raft snapshot at index 292977 (id=108c3923, encoded size=81623618, 78 rocksdb batches, 19 log entries)
I161120 22:38:25.920161 6176801 storage/replica_raftstorage.go:617  [n5,s10,r67/6:/Table/51/1/{387836…-402658…}] applying Raft snapshot at index 121879 (id=36013bef, encoded size=82369130, 79 rocksdb batches, 93 log entries)
```

This is curious because Raft snapshots should be rare. A bit before this, there are some warnings about `raftMu` being held for a very long time:

```
W161120 22:38:21.878353 285 storage/replica.go:554  [n5,s10,r67/6:/Table/51/1/{387836…-402658…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 21.912021286s (>500ms):
goroutine 285 [running]:
runtime/debug.Stack(0x1db03e8, 0x1db0428, 0x47)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/syncutil.ThresholdLogger.func1(0x51a0ee926)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:65 +0xe1
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*TimedMutex).Unlock(0xc42eeca878)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:92 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc42eeca800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2201 +0xee
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc420978380, 0x43)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3203 +0x13e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204c03c0, 0xc420552000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:230 +0x28c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420552000, 0xc420440980)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
```

and

```
W161120 22:38:22.032236 286 storage/replica.go:554  [n5,s10,r32/16:/Table/51/1/1{719577…-866936…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 22.059734325s (>500ms):
goroutine 286 [running]:
runtime/debug.Stack(0x1db03e8, 0x1db0428, 0x47)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/syncutil.ThresholdLogger.func1(0x522dcd535)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:65 +0xe1
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*TimedMutex).Unlock(0xc437b88478)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:92 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc437b88400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2201 +0xee
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc420978380, 0x20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3203 +0x13e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204c03c0, 0xc420552000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:230 +0x28c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420552000, 0xc4204409c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
```

**Comment by petermattis** [comment]
Hmm, there might have be a panic lost somewhere:

```
[bcd] 2016/11/20 22:37:59 Tracer timeout: 2m0s
[bcd] 2016/11/20 22:37:59 Retrieved tid: 30388
[bcd] 2016/11/20 22:37:59 Retrieved goid: 218
[bcd] 2016/11/20 22:37:59 Command: &{/opt/backtrace/bin/ptrace [/opt/backtrace/bin/ptrace --load= --module=go:enable,true,filter,user,goid,218 --faulted 30380 -L WARNING --kv cgo-compiler:gcc 4.9.2 --kv go-version:go1.7.3 --kv platform:linux amd64 --kv tag:beta-20161110-270-g13d3b39-dirty --kv time:2016/11/20 21:29:46 --fault-thread 30388 --kv error:runtime error: invalid memory address or nil pointer dereference --classifier runtime.errorString] [] /home/cockroach/logs <nil> <nil> 0xc420554008 [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>}
[bcd] 2016/11/20 22:37:59 Waiting for tracer completion...
```

This indicates that backtrace is trying to perform a dump. Notice that this occurred before the long `raftMu` hold time warnings.

**Comment by petermattis** [comment]
I think we should disable backtrace. We've seen it complain before about running out of memory and I think this is an instance when a panic was thrown but we don't see the panic because backtrace took too long to dump.

**Comment by petermattis** [comment]
Closing as backtrace has been disabled.
