### ISSUE TITLE
stability: concurrent map read/write on delta

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#10900]
sha: 019c063

crash on `104.196.63.254` about 50 minutes after start:

```
fatal error: concurrent map read and map write

goroutine 13353161 [running]:
runtime.throw(0x18f0d92, 0x21)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc66a0e2cf0 sp=0xc66a0e2cd0
runtime.mapaccess2_fast32(0x17416e0, 0xc664d75560, 0x2, 0x1a9ea48, 0xc66a0e2d90)
        /usr/local/go/src/runtime/hashmap_fast.go:66 +0x1ae fp=0xc66a0e2d18 sp=0xc66a0e2cf0
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send.func1(0xc66a0e3470, 0xc66a0e34e8, 0x148918446681d98f, 0x0, 0xc66a0e34e0, 0xc420235500)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2284 +0xc3 fp=0xc66a0e2d90 sp=0xc66a0e2d18
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc420235500, 0x7f201e0ae480, 0xc482ace780, 0x148918446592ed3d, 0x0, 0x400000002, 0x3, 0x30, 0x0, 0xc5352018c0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2443 +0xadb fp=0xc66a0e3458 sp=0xc66a0e2d90
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc420259aa0, 0x7f201e0ae480, 0xc482ace6f0, 0x0, 0x0, 0x400000002, 0x3, 0x30, 0x0, 0xc535201800, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x202 fp=0xc66a0e3630 sp=0xc66a0e3458
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:819 +0x2a1 fp=0xc66a0e3778 sp=0xc66a0e3630
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc420528000, 0xc66a0e3848, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0x100 fp=0xc66a0e37d0 sp=0xc66a0e3778
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc420173180, 0x7f201e0ae480, 0xc482ace210, 0xc55121a380, 0xc482ace210, 0xc6147fba60, 0x5d9b37)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:830 +0x1ed fp=0xc66a0e39e0 sp=0xc66a0e37d0
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc420173180, 0x7f201e0ae480, 0xc482ace210, 0xc55121a380, 0x0, 0x22b, 0x22b)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:850 +0x9b fp=0xc66a0e3a60 sp=0xc66a0e39e0
github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler(0x18a0600, 0xc420173180, 0x7f201e0ae480, 0xc4ad069980, 0xc608ec4f00, 0x0, 0x0, 0x0, 0xc43a4d03a0, 0x5dc0c8)
        /go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:1522 +0x27d fp=0xc66a0e3ae8 sp=0xc66a0e3a60
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420405540, 0x2402fe0, 0xc4203e0870, 0xc5705f4780, 0xc42042f830, 0x23c4d20, 0x0, 0x0, 0x0)
        /go/src/google.golang.org/grpc/server.go:611 +0xc50 fp=0xc66a0e3d70 sp=0xc66a0e3ae8
google.golang.org/grpc.(*Server).handleStream(0xc420405540, 0x2402fe0, 0xc4203e0870, 0xc5705f4780, 0x0)
        /go/src/google.golang.org/grpc/server.go:769 +0x6b0 fp=0xc66a0e3f30 sp=0xc66a0e3d70
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4205b8c60, 0xc420405540, 0x2402fe0, 0xc4203e0870, 0xc5705f4780)
        /go/src/google.golang.org/grpc/server.go:422 +0xab fp=0xc66a0e3f68 sp=0xc66a0e3f30
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc66a0e3f70 sp=0xc66a0e3f68
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/google.golang.org/grpc/server.go:423 +0xa3
```

Source: store.go:2284:
```
      if pErr != nil {
        pErr.OriginNode = ba.Replica.NodeID
        txn := pErr.GetTxn()
        if txn == nil {
          txn = ba.Txn
        }
        txn.UpdateObservedTimestamp(ba.Replica.NodeID, now)  // <<---- L2284
        pErr.SetTxn(txn)
      } else {
        if br.Txn == nil {
          br.Txn = ba.Txn
        }
        br.Txn.UpdateObservedTimestamp(ba.Replica.NodeID, now)
        // Update our clock with the outgoing response txn timestamp.
        s.cfg.Clock.Update(br.Txn.Timestamp)
      }
```

**Comment by mberhault** [comment]
panicparsed goroutines:
[cockroach.goroutines.txt](https://github.com/cockroachdb/cockroach/files/603991/cockroach.goroutines.txt)

raw goroutines:
[cockroach.goroutines.gz](https://github.com/cockroachdb/cockroach/files/603992/cockroach.goroutines.gz)


full stderr:
[cockroach.stderr.gz](https://github.com/cockroachdb/cockroach/files/603990/cockroach.stderr.gz)

**Comment by a-robinson** [comment]
For what it's worth, there was a ton of contention starting about 5 minutes before the panic, so it may be worth taking a look at the logs when investigating.

**Comment by tamird** [comment]
Heh, easy one. https://github.com/cockroachdb/cockroach/pull/10903
