### ISSUE TITLE
ccl/cloudccl/cloudprivilege: cloudprivilege_ccl test fails if no network access

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#109054]
The test times out in this case. I've copied one of the stacks below; to me this suggests that we're trying to read from some SQL connection that will never connect. I'm not sure if this is a red herring.

```
goroutine 29248 [IO wait]:
internal/poll.runtime_pollWait(0x1373ab870, 0x72)
	GOROOT/src/runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0x14005a1d800?, 0x140053a0000?, 0x0)
	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x14005a1d800, {0x140053a0000, 0x700, 0x700})
	GOROOT/src/internal/poll/fd_unix.go:167 +0x1e0
net.(*netFD).Read(0x14005a1d800, {0x140053a0000?, 0x14005236f98?, 0x8?})
	GOROOT/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x14007d06df0, {0x140053a0000?, 0x10eb72688?, 0x6?})
	GOROOT/src/net/net.go:183 +0x34
crypto/tls.(*atLeastReader).Read(0x1400792edb0, {0x140053a0000?, 0x0?, 0x102fa1de8?})
	GOROOT/src/crypto/tls/conn.go:787 +0x40
bytes.(*Buffer).ReadFrom(0x14005237078, {0x1097cd4c0, 0x1400792edb0})
	GOROOT/src/bytes/buffer.go:202 +0x90
crypto/tls.(*Conn).readFromUntil(0x14005236e00, {0x1097dc4a0?, 0x14007d06df0}, 0x30000007d?)
	GOROOT/src/crypto/tls/conn.go:809 +0xd4
crypto/tls.(*Conn).readRecordOrCCS(0x14005236e00, 0x0)
	GOROOT/src/crypto/tls/conn.go:616 +0xd8
crypto/tls.(*Conn).readRecord(...)
	GOROOT/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0x14005236e00, {0x1400519f000, 0x1000, 0x0?})
	GOROOT/src/crypto/tls/conn.go:1315 +0x178
bufio.(*Reader).Read(0x140067e8a20, {0x14006116620, 0x5, 0x14005bece70?})
	GOROOT/src/bufio/bufio.go:237 +0x1e0
io.ReadAtLeast({0x1097cb600, 0x140067e8a20}, {0x14006116620, 0x5, 0x200}, 0x5)
	GOROOT/src/io/io.go:332 +0xa0
io.ReadFull(...)
	GOROOT/src/io/io.go:351
github.com/lib/pq.(*conn).recvMessage(0x14006116600, 0x14006e998a0)
	github.com/lib/pq/external/com_github_lib_pq/conn.go:1004 +0xcc
github.com/lib/pq.(*conn).recv1Buf(0x14006116600, 0x102ca6c10?)
	github.com/lib/pq/external/com_github_lib_pq/conn.go:1059 +0x2c
github.com/lib/pq.(*conn).recv1(...)
	github.com/lib/pq/external/com_github_lib_pq/conn.go:1086
github.com/lib/pq.(*conn).simpleExec(0x14006116600, {0x1400235f0e0?, 0x9a})
	github.com/lib/pq/external/com_github_lib_pq/conn.go:664 +0x174
github.com/lib/pq.(*conn).Exec(0x14006116600, {0x1400235f0e0, 0x9a}, {0x10cfca2a0, 0x0, 0x0})
	github.com/lib/pq/external/com_github_lib_pq/conn.go:921 +0x194
github.com/lib/pq.(*conn).ExecContext(0x14009e4d3b0?, {0x109822ab0, 0x140000bc090}, {0x1400235f0e0, 0x9a}, {0x10cfca2a0, 0x0, 0x102c41a1c?})
	github.com/lib/pq/external/com_github_lib_pq/conn_go18.go:46 +0xb4
database/sql.ctxDriverExec({0x109822ab0?, 0x140000bc090?}, {0x137dd1810?, 0x14006116600?}, {0x0?, 0x0?}, {0x1400235f0e0?, 0x3f2?}, {0x10cfca2a0?, 0x109820190?, ...})
	GOROOT/src/database/sql/ctxutil.go:31 +0xb0
database/sql.(*DB).execDC.func2()
	GOROOT/src/database/sql/sql.go:1679 +0x12c
database/sql.withLock({0x1097f0420, 0x14002f21dd0}, 0x14005a00d38)
	GOROOT/src/database/sql/sql.go:3439 +0x7c
database/sql.(*DB).execDC(0x14000ebbd40?, {0x109822ab0, 0x140000bc090}, 0x14002f21dd0, 0x14005a00e18?, {0x1400235f0e0, 0x9a}, {0x0, 0x0, 0x0})
	GOROOT/src/database/sql/sql.go:1674 +0x198
database/sql.(*DB).exec(0x10cdfc400?, {0x109822ab0, 0x140000bc090}, {0x1400235f0e0, 0x9a}, {0x0, 0x0, 0x0}, 0x9a?)
	GOROOT/src/database/sql/sql.go:1659 +0xa0
database/sql.(*DB).ExecContext(0x107282829?, {0x109822ab0, 0x140000bc090}, {0x1400235f0e0, 0x9a}, {0x0, 0x0, 0x0})
	GOROOT/src/database/sql/sql.go:1633 +0xa8
database/sql.(*DB).Exec(...)
	GOROOT/src/database/sql/sql.go:1651
pkg/ccl/cloudccl/cloudprivilege/cloudprivilege_test.TestURIRequiresAdminOrPrivilege.func4(0x1038bed40?)
	pkg/ccl/cloudccl/cloudprivilege/cloudprivilege_test/pkg/ccl/cloudccl/cloudprivilege/privileges_test.go:150 +0x9c
testing.tRunner(0x140062196c0, 0x1400792ed80)
	GOROOT/src/testing/testing.go:1446 +0x10c
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:1493 +0x300

```

Epic: CRDB-8308

**Comment by stevendanna** [comment]
Ah, looks likely given the epic link.

**Comment by stevendanna** [comment]
🤦 but it's easier to just turn the wifi off on your machine

:D Yes, that works and reproduces.  Well, at least now I'm all set up to debug remote build stuff if required.

**Comment by msbutler** [comment]
looks like this test fails because we're working with s3/azure/gcs uris. we should move this to the cloud unit test suite.

**Comment by msbutler** [comment]
@stevendanna have you investigated this further? Do you think its fine to skip each relevant subtest that requires an s3/gcs/azure connection during RBE and add this test to the cloud unit test suite?

**Comment by msbutler** [comment]
@rickystewart is this still a problem, or has our remote testing env changed to allow tests that require network access?
