### ISSUE TITLE
ccl/cloudccl/externalconn: externalconn_test fails if no network access

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#109055]
The test times out in this case. I've pasted one of the stacks below; this suggests to me that we are trying to read from a SQL connection that will never connect, as I mentioned in #109054. However, this may be a red herring.

```
goroutine 132832 [IO wait]:
internal/poll.runtime_pollWait(0x113d6f960, 0x72)
	GOROOT/src/runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0x14006f89f80?, 0x14004158700?, 0x0)
	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x14006f89f80, {0x14004158700, 0x700, 0x700})
	GOROOT/src/internal/poll/fd_unix.go:167 +0x1e0
net.(*netFD).Read(0x14006f89f80, {0x14004158700?, 0x140028f9a18?, 0x8?})
	GOROOT/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x140062c8798, {0x14004158700?, 0x6e1?, 0x1400c0d1de0?})
	GOROOT/src/net/net.go:183 +0x34
crypto/tls.(*atLeastReader).Read(0x14004b36078, {0x14004158700?, 0x0?, 0x1005457b8?})
	GOROOT/src/crypto/tls/conn.go:787 +0x40
bytes.(*Buffer).ReadFrom(0x140028f9af8, {0x106523420, 0x14004b36078})
	GOROOT/src/bytes/buffer.go:202 +0x90
crypto/tls.(*Conn).readFromUntil(0x140028f9880, {0x106531100?, 0x140062c8798}, 0x30000007d?)
	GOROOT/src/crypto/tls/conn.go:809 +0xd4
crypto/tls.(*Conn).readRecordOrCCS(0x140028f9880, 0x0)
	GOROOT/src/crypto/tls/conn.go:616 +0xd8
crypto/tls.(*Conn).readRecord(...)
	GOROOT/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0x140028f9880, {0x14008896000, 0x1000, 0x0?})
	GOROOT/src/crypto/tls/conn.go:1315 +0x178
bufio.(*Reader).Read(0x14005239680, {0x14006c41520, 0x5, 0x100190f60?})
	GOROOT/src/bufio/bufio.go:237 +0x1e0
io.ReadAtLeast({0x106521580, 0x14005239680}, {0x14006c41520, 0x5, 0x200}, 0x5)
	GOROOT/src/io/io.go:332 +0xa0
io.ReadFull(...)
	GOROOT/src/io/io.go:351
github.com/lib/pq.(*conn).recvMessage(0x14006c41500, 0x1400a4df480)
	github.com/lib/pq/external/com_github_lib_pq/conn.go:1004 +0xcc
github.com/lib/pq.(*conn).recv1Buf(0x14006c41500, 0x14002e38ae0?)
	github.com/lib/pq/external/com_github_lib_pq/conn.go:1059 +0x2c
github.com/lib/pq.(*conn).recv1(...)
	github.com/lib/pq/external/com_github_lib_pq/conn.go:1086
github.com/lib/pq.(*conn).simpleExec(0x14006c41500, {0x1400073d200?, 0x75})
	github.com/lib/pq/external/com_github_lib_pq/conn.go:664 +0x174
github.com/lib/pq.(*conn).Exec(0x14006c41500, {0x1400073d200, 0x75}, {0x10982f240, 0x0, 0x0})
	github.com/lib/pq/external/com_github_lib_pq/conn.go:921 +0x194
github.com/lib/pq.(*conn).ExecContext(0x164fcdca5?, {0x106570cb0, 0x1400007a090}, {0x1400073d200, 0x75}, {0x10982f240, 0x0, 0x30000007d?})
	github.com/lib/pq/external/com_github_lib_pq/conn_go18.go:46 +0xb4
database/sql.ctxDriverExec({0x106570cb0?, 0x1400007a090?}, {0x112eef8d0?, 0x14006c41500?}, {0x0?, 0x0?}, {0x1400073d200?, 0x10026e350?}, {0x10982f240?, 0x109377708?, ...})
	GOROOT/src/database/sql/ctxutil.go:31 +0xb0
database/sql.(*DB).execDC.func2()
	GOROOT/src/database/sql/sql.go:1679 +0x12c
database/sql.withLock({0x106542d38, 0x14003deb320}, 0x1400a4df918)
	GOROOT/src/database/sql/sql.go:3439 +0x7c
database/sql.(*DB).execDC(0x140023f4d00?, {0x106570cb0, 0x1400007a090}, 0x14003deb320, 0x14006734d60?, {0x1400073d200, 0x75}, {0x0, 0x0, 0x0})
	GOROOT/src/database/sql/sql.go:1674 +0x198
database/sql.(*DB).exec(0x2?, {0x106570cb0, 0x1400007a090}, {0x1400073d200, 0x75}, {0x0, 0x0, 0x0}, 0x40?)
	GOROOT/src/database/sql/sql.go:1659 +0xa0
database/sql.(*DB).ExecContext(0x106549868?, {0x106570cb0, 0x1400007a090}, {0x1400073d200, 0x75}, {0x0, 0x0, 0x0})
	GOROOT/src/database/sql/sql.go:1633 +0xa8
github.com/cockroachdb/cockroach/pkg/cloud/externalconn/testutils.(*Tenant).ExecWithErr(...)
	github.com/cockroachdb/cockroach/pkg/cloud/externalconn/testutils/tenant_state.go:42
pkg/ccl/cloudccl/externalconn/externalconn_test_test.TestDataDriven.func1.3(0x1400439bd40, 0x14004dea148)
	pkg/ccl/cloudccl/externalconn/externalconn_test_test/pkg/ccl/cloudccl/externalconn/datadriven_test.go:105 +0x900
github.com/cockroachdb/datadriven.RunTest.func1({0x1065db970?, 0x1400439bd40?}, 0x1400439bd40?)
	github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:118 +0x44
github.com/cockroachdb/datadriven.runDirective.func1({0x1065db970?, 0x1400439bd40?}, 0x10b421878?, 0x80?)
	github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:337 +0x70
github.com/cockroachdb/datadriven.runDirective({0x1065db970, 0x1400439bd40}, 0x14004dea120, 0x140086ed5a8?)
	github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:342 +0x58
github.com/cockroachdb/datadriven.runDirectiveOrSubTest({0x1065db970, 0x1400439bd40}, 0x1400439bd40?, {0x140086ed5a8, 0x15}, 0x14005732f08?)
	github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:211 +0x84
github.com/cockroachdb/datadriven.runSubTest.func1({0x1065db970, 0x1400439bd40})
	github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:259 +0xc8
github.com/cockroachdb/datadriven.subTest.func1(0x100e3c4e0?)
	github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/test_interface.go:27 +0x30
testing.tRunner(0x1400439bd40, 0x1400c5947e0)
	GOROOT/src/testing/testing.go:1446 +0x10c
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:1493 +0x300

```

Epic CRDB-14596
Jira issue: CRDB-30754

**Comment by dt** [comment]
I'm removing `C-test-failure` from these as that label is currently being used to track failures specifically in our release-gating CIs and has thus been given special meaning in the CY process (and is part of the CY dashboard query).

**Comment by msbutler** [comment]
looks like certain tests fail because some open s3/azure/gcs uris ([example](https://github.com/cockroachdb/cockroach/blob/5cd4c7becf95e66c1432ec6e30f554559a975702/pkg/ccl/cloudccl/externalconn/testdata/create_drop_external_connection#L102)). we should move the relevant subtests to the cloud unit test suite.
