### ISSUE TITLE
SIGSEGV on 'cockroach sql --certs-dir' running with empty certificate files

### ISSUE THREAD

**Issue by abra7134** [cockroachdb/cockroach#111256]
**Describe the problem**

When starting `cockroach sql --certs-dir` falls with **SIGSEGV** if the folder contains empty certificates.

**To Reproduce**
```bash
$ mkdir certs
$ touch certs/client.root.crt
$ touch certs/client.root.key
$ docker run --rm -ti -v $(pwd)/certs:/certs cockroachdb/cockroach:v23.1.10 sql --certs-dir /certs
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1  a panic has occurred!
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +runtime error: invalid memory address or nil pointer dereference
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +(1) attached stack trace
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  -- stack trace:
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | runtime.sigpanic
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    GOROOT/src/runtime/signal_unix.go:839
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | crypto/x509.IsEncryptedPEMBlock
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    GOROOT/src/crypto/x509/pem_decrypt.go:105
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/jackc/pgconn.configTLS
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/jackc/pgconn/external/com_github_jackc_pgconn/config.go:724
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/jackc/pgconn.ParseConfigWithOptions
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/jackc/pgconn/external/com_github_jackc_pgconn/config.go:349
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/jackc/pgconn.ParseConfig
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/jackc/pgconn/external/com_github_jackc_pgconn/config.go:222
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/jackc/pgx/v4.ParseConfig
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/jackc/pgx/v4/external/com_github_jackc_pgx_v4/conn.go:131
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli/clisqlclient.(*sqlConn).EnsureConn
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/cockroachdb/cockroach/pkg/cli/clisqlclient/conn.go:177
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg.(*Context).Run
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg/context.go:205
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.runTerm
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/cockroachdb/cockroach/pkg/cli/sql_shell_cmd.go:64
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:72
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/spf13/cobra.(*Command).execute
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:856
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/spf13/cobra.(*Command).ExecuteC
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:974
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/spf13/cobra.(*Command).Execute
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:902
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.Run
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/cockroachdb/cockroach/pkg/cli/cli.go:300
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.doMain
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/cockroachdb/cockroach/pkg/cli/cli.go:143
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.Main
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    github.com/cockroachdb/cockroach/pkg/cli/cli.go:68
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | main.main
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    main/pkg/cmd/cockroach/main.go:26
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | runtime.main
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    GOROOT/src/runtime/proc.go:250
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  | runtime.goexit
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +  |    GOROOT/src/runtime/asm_amd64.s:1594
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +Wraps: (2) runtime error: invalid memory address or nil pointer dereference
E230926 05:42:51.736907 1 1@util/log/logcrash/crash_reporting.go:188  [-] 1 +Error types: (1) *withstack.withStack (2) runtime.errorString
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x3196fc4]

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.RecoverAndReportPanic({0x7303020, 0xc0000be058}, 0xc001a619f8?)
    github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:131 +0x78
panic({0x54484a0, 0xa57d4d0})
    GOROOT/src/runtime/panic.go:884 +0x212
crypto/x509.IsEncryptedPEMBlock(...)
    GOROOT/src/crypto/x509/pem_decrypt.go:105
github.com/jackc/pgconn.configTLS(0xc001018172?, {0xc001018172, 0x9}, {0x1?})
    github.com/jackc/pgconn/external/com_github_jackc_pgconn/config.go:724 +0x744
github.com/jackc/pgconn.ParseConfigWithOptions({0xc001018160, 0xa9}, {0x4ea2a7?})
    github.com/jackc/pgconn/external/com_github_jackc_pgconn/config.go:349 +0x1a7b
github.com/jackc/pgconn.ParseConfig(...)
    github.com/jackc/pgconn/external/com_github_jackc_pgconn/config.go:222
github.com/jackc/pgx/v4.ParseConfig({0xc001018160, 0xa9})
    github.com/jackc/pgx/v4/external/com_github_jackc_pgx_v4/conn.go:131 +0x3d
github.com/cockroachdb/cockroach/pkg/cli/clisqlclient.(*sqlConn).EnsureConn(0xc001616680, {0x7303020, 0xc0000be058})
    github.com/cockroachdb/cockroach/pkg/cli/clisqlclient/conn.go:177 +0xb6
github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg.(*Context).Run(0xc000a792c0, {0x7303020, 0xc0000be058}, {0x73702c0?, 0xc001616680})
    github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg/context.go:205 +0x9c
github.com/cockroachdb/cockroach/pkg/cli.runTerm(0x53b3c6?, {0x8?, 0x203000?, 0x203000?})
    github.com/cockroachdb/cockroach/pkg/cli/sql_shell_cmd.go:64 +0x20a
github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1(0xa5f6d20?, {0xc000cc24c0?, 0x0?, 0x2?})
    github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:72 +0x43
github.com/spf13/cobra.(*Command).execute(0xa5f6d20, {0xc000cc23a0, 0x2, 0x2})
    github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xa5e8ea0)
    github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
    github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:902
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
    github.com/cockroachdb/cockroach/pkg/cli/cli.go:300
github.com/cockroachdb/cockroach/pkg/cli.doMain(0xa5f6d20, {0xc00073401a, 0x3})
    github.com/cockroachdb/cockroach/pkg/cli/cli.go:143 +0x1e9
github.com/cockroachdb/cockroach/pkg/cli.Main()
    github.com/cockroachdb/cockroach/pkg/cli/cli.go:68 +0x157
main.main()
    main/pkg/cmd/cockroach/main.go:26 +0x17
```

**Expected behavior**

Correct program termination

**Additional data / screenshots**

**Environment:**
 - CockroachDB version 23.1.10 (official Docker image)
 - Server OS: Debian 11 (not matter)

**Additional context**

Jira issue: CRDB-31836

**Comment by rafiss** [comment]
This has the same cause as https://github.com/cockroachdb/cockroach/issues/137595.

https://github.com/cockroachdb/cockroach/pull/139667 should resolve it.
