### ISSUE TITLE
jobs: TestRetriesWithExponentialBackoff is flaky under stress

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#112763]
This was on a 23.2 backport.

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/12273030?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
No pass/skip/fail event found for test
=== RUN   TestRetriesWithExponentialBackoff/pause_running
    registry_test.go:822: condition failed to evaluate within 45s: from registry_test.go:830: waiting job 910125136442097665 to reach a terminal state, currently running
panic: send on closed channel [recovered]
  panic: send on closed channel
goroutine 34997 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0xbe?, {0x6e34360, 0xc00c22b170})
  github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:230 +0x6a
panic({0x50db2e0, 0x6dec650})
  GOROOT/src/runtime/panic.go:884 +0x213
github.com/cockroachdb/cockroach/pkg/jobs.TestRetriesWithExponentialBackoff.func6.2.1({0x6e34360, 0xc00be33dd0})
  github.com/cockroachdb/cockroach/pkg/jobs/registry_test.go:737 +0xb5
github.com/cockroachdb/cockroach/pkg/jobs/jobstest.FakeResumer.Resume({0xc00899c2e0, 0xc00899c2f0, 0x0, 0x0, 0x0}, {0x6e34360?, 0xc00be33dd0?}, {0xc0093c4360?, 0x0?})
  github.com/cockroachdb/cockroach/pkg/jobs/jobstest/resumer.go:39 +0x50
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2(0xc00dfc2b60?, 0x0?, 0xc004ccb810, {0x6e32130?, 0xc00c22b110?}, {0x6e34360?, 0xc00be33dd0?}, {0x563fd60?, 0xc004c35eb8?})
  github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1664 +0xcc
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine(0xc004863900, {0x6e34360, 0xc00c831440}, {0x563fd60, 0xc004c35eb8}, {0x6e32130, 0xc00c22b110}, 0xc00dfc2b60, {0xc00c61f8b8, 0x7}, ...)
  github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1665 +0xa3f
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob(0xc004863900, {0x6e34360, 0xc00c831440}, {0x6e32130, 0xc00c22b110}, 0xc00dfc2b60, {0xc00c61f8b8, 0x7}, {0xc0091e5488, 0x16})
  github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:477 +0x556
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func2({0x6e34360?, 0xc00c22b170?})
  github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:389 +0x146
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
  github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
  github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x43b
```

**Comment by msbutler** [comment]
just hit this on 23.2 https://teamcity.cockroachdb.com/viewLog.html?buildId=12329012&buildTypeId=Cockroach_BazelExtendedCi

**Comment by adityamaru** [comment]
saw this again here https://teamcity.cockroachdb.com/viewLog.html?buildId=12419922&buildTypeId=Cockroach_BazelExtendedCi

**Comment by adityamaru** [comment]
actually my error seems to be a little different:
```
=== RUN   TestRetriesWithExponentialBackoff/pause_running
    registry_test.go:796: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/jobs/registry_test.go:796
        	            				github.com/cockroachdb/cockroach/pkg/jobs/registry_test.go:873
        	Error:      	Not equal: 
        	            	expected: 41
        	            	actual  : 40
        	Test:       	TestRetriesWithExponentialBackoff/pause_running
        	Messages:   	unexpected number of jobs resumed in retry 40
*
* INFO: slow quiesce. stack traces:
* goroutine 38271 [running]:
* github.com/cockroachdb/cockroach/pkg/util/allstacks.GetWithBuf({0x0, 0x0?, 0x0})
* 	github.com/cockroachdb/cockroach/pkg/util/allstacks/allstacks.go:32 +0x93
* github.com/cockroachdb/cockroach/pkg/util/allstacks.Get(...)
* 	github.com/cockroachdb/cockroach/pkg/util/allstacks/allstacks.go:19
* github.com/cockroachdb/cockroach/pkg/util/log.DumpStacks({0xc60ed00, 0xc00013e008}, {0x8653833, 0xc})
* 	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:427 +0x65
* github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Quiesce.func2()
* 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:580 +0x4b
* created by time.goFunc
* 	GOROOT/src/time/sleep.go:176 +0x48
* 
* goroutine 1 [chan receive, 4 minutes]:
* testing.(*T).Run(0xc001474d00, {0x86cc54e, 0x21}, 0x89b3880)
* 	GOROOT/src/testing/testing.go:1630 +0x82e
* testing.runTests.func1(0x0?)
* 	GOROOT/src/testing/testing.go:2036 +0x8e
* testing.tRunner(0xc001474d00, 0xc0031e18e8)
* 	GOROOT/src/testing/testing.go:1576 +0x217
* testing.runTests(0xc000f16e60?, {0xf7e6880, 0x49, 0x49}, {0x0?, 0x0?, 0xfbdce20?})
* 	GOROOT/src/testing/testing.go:2034 +0x87d
* testing.(*M).Run(0xc000f16e60)
* 	GOROOT/src/testing/testing.go:1906 +0xb45
* github.com/cockroachdb/cockroach/pkg/jobs_test.TestMain(0x86c47aa?)
* 	github.com/cockroachdb/cockroach/pkg/jobs_test/pkg/jobs/main_test.go:35 +0x291
* main.main()
* 	main/bazel-out/k8-fastbuild/bin/pkg/jobs/jobs_test_/testmain.go:274 +0x6ec
* 
* goroutine 8 [chan receive]:
* github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
* 	github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:117 +0x72
* created by github.com/cockroachdb/cockroach/pkg/util/log.init.5
* 	github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:83 +0x2a
* ```

**Comment by stevendanna** [comment]
When I stress it locally I get a 3rd kind of failure:

```
--- FAIL: TestRetriesWithExponentialBackoff (52.72s)
    test_log_scope.go:170: test logs captured to: /tmp/_tmp/36d09785a9c246f79b738d896ab18d71/logTestRetriesWithExponentialBackoff3965307374
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:111: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    conditional_wrap.go:190: 
        pkg/jobs/registry_test.go:720: (TestRetriesWithExponentialBackoff.func6)
                NOTICE: .InternalDB() called via implicit interface ApplicationLayerInterface;
        HINT: consider using .ApplicationLayer().InternalDB() instead.
    conditional_wrap.go:194: TIP: consider replacing the test server initialization from:
            ts, ... := serverutils.StartServer(t, ...)
            defer ts.Stopper().Stop(...)
        to:
            srv, ... := serverutils.StartServer(t, ...)
            defer srv.Stopper().Stop(...)
            ts := srv.ApplicationLayer()
        
        See also: https://go.crdb.dev/p/testserver-and-cluster-virtualization
    test_server_shim.go:111: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    conditional_wrap.go:190: 
        pkg/jobs/registry_test.go:720: (TestRetriesWithExponentialBackoff.func6)
                NOTICE: .InternalDB() called via implicit interface ApplicationLayerInterface;
        HINT: consider using .ApplicationLayer().InternalDB() instead.
    conditional_wrap.go:194: TIP: consider replacing the test server initialization from:
            ts, ... := serverutils.StartServer(t, ...)
            defer ts.Stopper().Stop(...)
        to:
            srv, ... := serverutils.StartServer(t, ...)
            defer srv.Stopper().Stop(...)
            ts := srv.ApplicationLayer()
        
        See also: https://go.crdb.dev/p/testserver-and-cluster-virtualization
    test_server_shim.go:111: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    test_server_shim.go:217: scheduled job created without a cluster ID
    --- FAIL: TestRetriesWithExponentialBackoff/revert_on_fail (0.81s)
        testing.go:1490: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
    panic.go:523: -- test log scope end --
FAIL
I231030 17:23:57.732910 1 (gostd) testmain.go:229  [-] 1  Test //pkg/jobs:jobs_test exited with error code 1
```

**Comment by msbutler** [comment]
ooof

> scheduled job created without a cluster ID

relates to something I added a month ago 
https://github.com/cockroachdb/cockroach/pull/111374

**Comment by stevendanna** [comment]
@msbutler Yeah, looking into it now. Looks like our cluster ID isn't initialized by the time the upgrade manager attempts to create some scheduled jobs.

**Comment by msbutler** [comment]
sounds like a real bug :D
