### ISSUE TITLE
rangefeed,storage: optimize rangefeed reads for 1PC transactions

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#113090]
`Replica.handleLogicalOpLogRaftMuLocked` does a `MVCCGetWithValueHeader` in https://github.com/cockroachdb/cockroach/blob/68ad71d1b8fd96261a37163e31f2caa72a5ae387/pkg/kv/kvserver/replica_rangefeed.go#L711

This is to retrieve the value for 2 cases: `*enginepb.MVCCWriteValueOp` and `*enginepb.MVCCCommitIntentOp`. In the former case the value is guaranteed to be in the `pebble.Batch` and we don't need a full `Iterator` that reads from the `Batch` and from the `DB`. This case occurs with 1PC transactions which can be common in high volume workloads which are sensitive to the cost of rangefeeds. We have seen high read IOPS and read bandwidth caused by rangefeeds, for example in https://cockroachlabs.slack.com/archives/C05VAJ5H3QS/p1697836194598449?thread_ts=1697816983.111109&cid=C05VAJ5H3QS (with stacks that look like [1]), because we are looking up in all levels of the `DB`.

The value could be provided using a SET or a RANGEKEYSET and we have the exact `MVCCKey` at which the value resides.
Our understanding is that inline values (with no timestamp) are not supported for rangefeeds, but we can easily fallback to the normal path if the value timestamp is empty (like the fallback to the `MVCCGetWithValueHeader` for the intent case).

The first step here would be to add a Get method on the `pebble.Batch` which would return the latest SET and RANGEKEYSET in the batch.

[1]
```
goroutine 882 [runnable]:
sync.runtime_SemacquireRWMutexR(0x0?, 0x8?, 0xc0000bc088?)
	GOROOT/src/runtime/sema.go:82 +0x26
sync.(*RWMutex).RLock(...)
	GOROOT/src/sync/rwmutex.go:71
github.com/cockroachdb/pebble/internal/cache.(*shard).Get(0xc000c12340, 0x129c551?, 0x0?, 0x0?)
	github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/clockpro.go:115 +0x4c
github.com/cockroachdb/pebble/internal/cache.(*Cache).Get(0x0?, 0x12955f2?, 0x7fb4cc630680?, 0x7fb18a5b60ad?)
	github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/clockpro.go:810 +0x3c
github.com/cockroachdb/pebble/sstable.(*Reader).readBlock(0xc01cd5b880, {0x79f4a08, 0xc0000bc088}, {0x12729ca?, 0xc015cecb00?}, 0x0, {0x0, 0x0}, 0xc015e56ba8, 0x0)
	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:527 +0x8e
github.com/cockroachdb/pebble/sstable.(*Reader).readFilter(0xc015e58340?, {0x79f4a08?, 0xc0000bc088?}, 0x13?)
	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:454 +0x45
github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).seekPrefixGE(0xc005b7a480, {0xc01f8eb470, 0x13, 0x30}, {0xc041019aa0, 0x13, 0x13}, 0x0?, 0x0?)
	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:785 +0x105
github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).SeekPrefixGE(0xc015e58190?, {0xc01f8eb470?, 0x1?, 0x13?}, {0xc041019aa0?, 0x18?, 0x13516bb?}, 0xd8?)
	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:765 +0xd7
github.com/cockroachdb/pebble.(*levelIter).SeekPrefixGE(0xc015e58190, {0xc01f8eb470, 0x13, 0x30}, {0xc041019aa0, 0x13, 0x13}, 0x4)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:770 +0x12c
github.com/cockroachdb/pebble.(*mergingIter).seekGE(0xc015e56dd8, {0xc041019aa0?, 0x133a8f1?, 0xc0295c5d10?}, 0xda72e9?, 0xd?)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1048 +0xe5
github.com/cockroachdb/pebble.(*mergingIter).SeekPrefixGE(0xc015e56dd8, {0xc01f8eb470?, 0x30?, 0xc041019aa0?}, {0xc041019aa0?, 0x13?, 0x12?}, 0x1d?)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1124 +0x9d
github.com/cockroachdb/pebble.(*Iterator).SeekPrefixGE(0xc015e56800, {0xc041019aa0, 0x13, 0x13})
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1467 +0x59d
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).SeekEngineKeyGEWithLimit(0xc009ecb168, {{0xc017d55aa0, 0x12, 0x1d}, {0x0, 0x0, 0x0}}, {0x0, 0x0, 0x0})
	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:402 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*LockTableIterator).SeekEngineKeyGEWithLimit(0xc03b8e0000, {{0xc017d55aa0, 0x12, 0x1d}, {0x0, 0x0, 0x0}}, {0x0, 0x0, 0x0})
	github.com/cockroachdb/cockroach/pkg/storage/lock_table_iterator.go:201 +0x168
github.com/cockroachdb/cockroach/pkg/storage.(*intentInterleavingIter).SeekGE(0xc0267b0900, {{0xc00c240a00, 0xc, 0x10}, {0x0, 0x0, 0x0}})
	github.com/cockroachdb/cockroach/pkg/storage/intent_interleaving_iter.go:579 +0x45d
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMVCCScanner).get(0xc024c32c00, {0x79f4a78, 0xc003bf7e90})
	github.com/cockroachdb/cockroach/pkg/storage/pebble_mvcc_scanner.go:559 +0xa7
github.com/cockroachdb/cockroach/pkg/storage.mvccGetWithValueHeader({0x79f4a78, 0xc003bf7e90}, {0x7a790c0, 0xc0267b0900}, {0xc00c240a00, 0xc, 0x10}, {0x178fec925bc69b76, 0x0, 0x0}, ...)
	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1443 +0x4ba
github.com/cockroachdb/cockroach/pkg/storage.MVCCGetWithValueHeader({0x79f4a78, 0xc003bf7e90}, {0x7a40608?, 0xc009ecae00?}, {0xc00c240a00, 0xc, 0x10}, {0x178fec925bc69b76, 0x0, 0x0}, ...)
	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1368 +0x38d
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleLogicalOpLogRaftMuLocked(0xc003c04c80, {0x79f4a78, 0xc003bf7e90}, 0xc00f9959b0, {0x7a40608, 0xc009ecae00})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go:709 +0x530
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).runPostAddTriggersReplicaOnly(0xc003c04d90, {0x79f4a78, 0xc003bf7e90}, 0xc02fbbd528)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go:496 +0xa87
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).Stage(0xc003c04d90, {0x79f4a78, 0xc003bf7e90}, {0x7a18340?, 0xc02fbbd528})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go:152 +0x2d8
github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.mapCmdIter({0x7a28740?, 0xc003c05138}, 0xc015cee5b8)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/cmd.go:192 +0x158
github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch(0xc015ceeb08, {0x79f4a78, 0xc003bf7e90}, {0x7a28740, 0xc003c05108})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:284 +0x15d
github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries(0xc015ceeb08, {0x79f4a78, 0xc003bf7e90})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:251 +0x9a
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1053 +0x13b9
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:740 +0x1a7
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc004561500, 0xc004b77bf0?)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:689 +0x14b
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0xc001fa1c70, {0x79f4a78, 0xc003c4f5c0}, {0x79d7cb0, 0xc004561500}, 0xc004560a80)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:418 +0x1f2
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x79f4a78?, 0xc003c4f5c0?})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:321 +0x45
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x43b
```

Jira issue: CRDB-32745

**Comment by sumeerbhola** [comment]
Running an experiment with a single node cluster
```
roachprod create -n 2 --clouds gce --gce-machine-type n2-standard-8 --local-ssd=false sumeer-cpu
roachprod put sumeer-cpu:1 /Users/sumeer/go/src/github.com/cockroachdb/cockroach/artifacts/cockroach-master ./cockroach
roachprod put sumeer-cpu:2 /Users/sumeer/go/src/github.com/cockroachdb/cockroach/artifacts/workload ./workload
roachprod start sumeer-cpu:1
roachprod run sumeer-cpu:2 -- ./workload run kv --tolerate-errors --init --histograms=perf/stats.json --concurrency=1024 --splits=1000 --min-block-bytes=5000 --max-block-bytes=5000 --duration=7200m0s --read-percent=0  {pgurl:1-1}
```

And started a changefeed:
```
SET CLUSTER SETTING enterprise.license = '...';
SET CLUSTER SETTING changefeed.mux_rangefeed.enabled = true;
SET CLUSTER SETTING kv.rangefeed.enabled = true;
SET CLUSTER SETTING kv.rangefeed.scheduler.enabled=true;
CREATE CHANGEFEED FOR kv.kv INTO 'null://' WITH no_initial_scan;
```

The iterator reads of sstable blocks almost doubles with rangefeeds:
<img width="1644" alt="Screenshot 2023-10-26 at 3 52 46 PM" src="https://github.com/cockroachdb/cockroach/assets/54990988/5ae3cbc7-128a-4295-9daf-5563df25de16">

But there isn't a similar increase in disk reads. Looking at a cpu profile, the number of pread calls due to `handleLogicalOpLogRaftMuLocked` are only < 25% of those due to the `MVCCPut`. This is different from the other experiment possibly for 2 reasons (a) the rangefeed is always running on the same node that recently did the MVCCPut for that range (since it is also the leaseholder) so locality of access is higher, (b) this experiment is running with large blocks to build up the LSM size quickly (the other one was running with the default block-bytes=1), so fewer keys, so bloom filters are likely more effective.
<img width="1574" alt="Screenshot 2023-10-26 at 3 54 18 PM" src="https://github.com/cockroachdb/cockroach/assets/54990988/363a68d5-7aef-471a-b6f6-2085b2b8995b">

**Comment by sumeerbhola** [comment]
Running the prototype in https://github.com/sumeerbhola/cockroach/tree/batch_only_rangefeed which uses the Pebble change in https://github.com/cockroachdb/pebble/pull/3017, for this workload.
All the rangefeed reads can use the batch-only iterator
```
I231027 01:42:31.658716 856 kv/kvserver/replica_rangefeed.go:731 ⋮ [T1,Vsystem,n1,s1,r944/1:‹/Table/106/1/-45{4257…-2415…}›,raft] 824  rangefeed: count: 2370000, batch-only: 2369914, error: 0
```

The block bandwidth from the `pebble.Iterator` is half that of master. And the throughput is ~10% higher. The resource bottleneck consistently includes CPU, while on master it is mostly only the LSM. The first part of the graph below is master and the later part is with the prototype.
<img width="829" alt="Screenshot 2023-10-27 at 9 07 55 AM" src="https://github.com/cockroachdb/cockroach/assets/54990988/29c69e0c-53b2-470d-8ec2-afa86e77429a">

<img width="822" alt="Screenshot 2023-10-27 at 9 03 45 AM" src="https://github.com/cockroachdb/cockroach/assets/54990988/73a4688a-970a-47e9-9440-fdf1facb118b">

The MVCC bytes were growing throughout, so this possibly slightly unfair to the prototype. Also, ignore the noise in the early part of the prototype run, which was due to catchup scans that I eliminated by cancelling the existing changefeed and recreating it.
<img width="821" alt="Screenshot 2023-10-27 at 9 13 05 AM" src="https://github.com/cockroachdb/cockroach/assets/54990988/bd8eac3b-77dc-43e9-8ed2-d521c4697ea8">
<img width="821" alt="Screenshot 2023-10-27 at 9 12 06 AM" src="https://github.com/cockroachdb/cockroach/assets/54990988/daf26ffb-f060-4579-a3db-9704323074ed">

**Comment by sumeerbhola** [comment]
Unclear if we saturated disk in these experiments, or was it just the LSM write bandwidth because of maximum of 3 compactions. When we saturate IOPS, like in the experiment that originally motivated this issue, where read IOPS was saturated, the effect of reducing rangefeed reads can be non-linear (we no longer fall over the cliff). The fsync bandwidth was reasonable:
<img width="824" alt="Screenshot 2023-10-27 at 1 05 27 PM" src="https://github.com/cockroachdb/cockroach/assets/54990988/e857c4d6-224b-46ad-9b84-a100bffdd2b0">

According to https://cloud.google.com/compute/docs/disks/performance#zonal, Zonal SSD PD: 30 read IOPS/GB, 30 write IOPS/GB, 0.48 MB/s/GB. This was a 500GB PD, so we should get 15000 read IOPS, 15000 write IOPS, 240 MB/s.
Our IOPS usage is 5.5K mean read IOPS, 2.5K mean write IOPS, so well below the provisioned limit. But our throughput is 600+ MB/s. I don't quite understand why.
<img width="1430" alt="Screenshot 2023-10-27 at 1 13 35 PM" src="https://github.com/cockroachdb/cockroach/assets/54990988/632cbfcf-9bc2-41eb-95e5-d12fde16ea54">
