### ISSUE TITLE
c2c: TestStreamingAutoReplan times out during lockProcessing

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#113238]
Running `./dev test pkg/ccl/streamingccl/streamingest -f  TestStreamingAutoReplan --race --stress --cpus 4 --count 50 --test-args='-test.timeout 5m'` reliably leads to a timeout on master during a `testcluster.WaitForFullReplication()` call after we add two test servers to the cluster [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go#L723).

One stack trace I saw on a 15 minute time out:
```
goroutine 66 [chan send, 13 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).lockProcessing(...)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:547
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).DrainQueue(0xc005170000, 0xc012046790?)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:1394 +0xd4
github.com/cockroachdb/cockroach/pkg/kv/kvserver.forceScanAndProcess({0xcc59698, 0x11dacd60}, 0xc004e70000, 0xc005170000)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue_helpers_testutil.go:42 +0x175
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).ForceReplicationScanAndProcess(...)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue_helpers_testutil.go:55
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForFullReplication.func2(0xc004e70000)
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1455 +0x13a
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1(0x8ab7cc0?, 0xc00129e150?)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149 +0x58
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range(0xc001deef70, 0xc012046b80)
  github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:358 +0x184
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores(0xc001deef30, 0xc011daec88)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:148 +0x73
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForFullReplication(0xc003a13c00)
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1447 +0x44d
github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest.TestStreamingAutoReplan(0xc0038bb6c0)
  github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go:683 +0x9cd
testing.tRunner(0xc0038bb6c0, 0x997a020)
  GOROOT/src/testing/testing.go:1595 +0x239
created by testing.(*T).Run in goroutine 1
  GOROOT/src/testing/testing.go:1648 +0x82b
```

Jira issue: CRDB-32823

**Comment by msbutler** [comment]
I'm unsure why this have begun to flake more in extended CI-- the cmd above reliably fails the test on 23.2 as well
