### ISSUE TITLE
kvnemesis: raft closed timestamp regression

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#114059]
Using the patch https://gist.github.com/jbowens/af624623867ca4dd8c27be2064eafcfd 
```
initialized metamorphic constant "parse-json-impl" with value 0
initialized metamorphic constant "coldata-batch-size" with value 1628
initialized metamorphic constant "span-reuse-rate" with value 80
initialized metamorphic constant "mvcc-incremental-iter-tbi" with value false
initialized metamorphic constant "disable-checksstconflicts-range-key-masking" with value true
initialized metamorphic constant "addsst-rewrite-concurrency" with value 5
initialized metamorphic constant "raft-log-truncation-clearrange-threshold" with value 912389
initialized metamorphic constant "raft-step-down-on-removal" with value false
initialized metamorphic constant "kv.rangefeed.use_dedicated_connection_class.enabled" with value true
initialized metamorphic constant "default-batch-bytes-limit" with value 14062
initialized metamorphic constant "row-container-rows-per-chunk-shift" with value 1
initialized metamorphic constant "max-batch-size" with value 9064
initialized metamorphic constant "max-batch-byte-size" with value 15506416
initialized metamorphic constant "inverted-joiner-batch-size" with value 1
initialized metamorphic constant "zig-zag-joiner-batch-size" with value 1
initialized metamorphic constant "spilling-queue-initial-len" with value 15
initialized metamorphic constant "merge-joiner-groups-buffer" with value 10
initialized metamorphic constant "ColIndexJoin-batch-size" with value 135014
initialized metamorphic constant "parallel-scan-result-threshold" with value 1381
initialized metamorphic constant "resolve-membership-single-scan-enabled" with value false
initialized metamorphic constant "copy-batch-size" with value 8389
initialized metamorphic constant "async-IE-result-channel-buffer-size" with value 28
initialized metamorphic constant "use-index-lookup-for-descriptors-in-database" with value false
initialized metamorphic constant "multiple_active_portals_enabled" with value true
I231108 18:16:59.895704 1 (gostd) rand.go:250  [-] 1  random seed: -5137607734787381697
=== RUN   TestKVNemesisMultiNode
    test_log_scope.go:170: test logs captured to: /tmp/cockroach/_tmp/aebd4ae0ee87eb180496c1e4da089c8e/logTestKVNemesisMultiNode554630916
    test_log_scope.go:81: use -show-logs to present logs inline
    kvnemesis_test.go:284: seed: 1581016586226339512
    kvnemesis_test.go:197: kvnemesis logging to /tmp/cockroach/_tmp/aebd4ae0ee87eb180496c1e4da089c8e/kvnemesis1409678025
panic: raft closed timestamp regression in cmd: 0ad4ef7915f2d9f7 (term: 6, index: 15); batch state: 1699467454.363124760,0, command: 1699467454.251881189,0, lease: repl=(n4,s4):3 seq=6 start=1699467455.023997901,0 epo=1 pro=1699467455.050226403,0, req: Delete [/Table/100/"921399d2662065ac",/Min), applying at LAI: 2.
Closed timestamp was set by req: <unknown; not leaseholder or not lease request> under lease: repl=(n4,s4):3 seq=6 start=1699467455.023997901,0 epo=1 pro=1699467455.050226403,0; applied at LAI: 1. Batch idx: 3.
Raft log tail:
0,0 /Local/RangeID/87/u/RaftLog/logIndex:15 (0x0169df757266746c000000000000000f00): Term:6 Index:15 Type:EntryNormal  (ID 0ad4ef7915f2d9f7) by lease #6
proposer_lease_sequence:6 max_lease_index:2 closed_timestamp:<wall_time:1699467454251881189 > replicated_eval_result:<write_timestamp:<wall_time:1699467457220837413 > delta:<last_update_nanos:1699467457220837413 gc_bytes_age:-105 key_bytes:12 val_bytes:10 val_count:1 > > logical_op_log:<ops:<write_value:<key:"\354\022921399d2662065ac\000\001" timestamp:<wall_time:1699467457220837413 > > > > trace_data:<key:"crdb-tracer-spanid" value:"1f480b794554a22a" > trace_data:<key:"crdb-tracer-traceid" value:"2272cc9f2c98e869" > trace_data:<key:"rec" value:"v" >
write batch:
Put: 1699467457.220837413,0 /Table/100/"921399d2662065ac" (0xec12393231333939643236363230363561630001001795b8a5eefc002509): "\x00\x00\x00\x05e\n\x00\x12\x01>"
0,0 /Local/RangeID/87/u/RaftLog/logIndex:14 (0x0169df757266746c000000000000000e00): Term:6 Index:14 Type:EntryNormal  (ID 4a37f23fa745a2e1) by lease #6
proposer_lease_sequence:6 max_lease_index:1 closed_timestamp:<wall_time:1699467454363124760 > replicated_eval_result:<write_timestamp:<wall_time:1699467457334971485 > delta:<last_update_nanos:1699467457334971485 live_bytes:147 live_count:1 key_bytes:33 key_count:1 val_bytes:114 val_count:1 intent_bytes:30 intent_count:1 lock_count:1 > > logical_op_log:<ops:<write_intent:<txn_id:6765e212-730a-42f6-9c22-867af51eac70 txn_key:"\354\022a6afc0ccb2e7a517\000\001" txn_min_timestamp:<wall_time:1699467457334971485 > timestamp:<wall_time:1699467457334971485 > > > > trace_data:<key:"crdb-tracer-spanid" value:"371a32995ca19d6" > trace_data:<key:"crdb-tracer-traceid" value:"424a888f4a0dfebd" > trace_data:<key:"rec" value:"v" >
write batch:
Put: /Local/Lock/Table/100/"a6afc0ccb2e7a517" 036765e212730a42f69c22867af51eac70 (0x017a6b12ec126136616663306363623265376135313700ff01000100036765e212730a42f69c22867af51eac7012): 1699467457.334971485,0 txn={id=6765e212 key=/Table/100/"a6afc0ccb2e7a517" iso=Serializable pri=0.00785044 epo=0 ts=1699467457.334971485,0 min=1699467457.334971485,0 seq=1} ts=1699467457.334971485,0 del=false klen=12 vlen=18 mergeTs=<nil> txnDidNotUpdateMeta=true
Put: 1699467457.334971485,0 /Table/100/"a6afc0ccb2e7a517" (0xec12613661666330636362326537613531370001001795b8a5f5c98c5d09): "\x00\x00\x00\x05e\n\x00\x12\x01?Y@ύ\x03v63"
0,0 /Local/RangeID/87/u/RaftLog/logIndex:13 (0x0169df757266746c000000000000000d00): Term:6 Index:13 Type:EntryNormal  (ID 174586ad919d0c61) by lease #6
proposer_lease_sequence:6 max_lease_index:1 closed_timestamp:<wall_time:1699467454220166867 > replicated_eval_result:<write_timestamp:<> delta:<sys_bytes:209 sys_count:1 > > logical_op_log:<> trace_data:<key:"crdb-tracer-spanid" value:"57408be841ad35c7" > trace_data:<key:"crdb-tracer-traceid" value:"43f7d2178c451aed" > trace_data:<key:"rec" value:"v" >
write batch:
Put: 0,0 /Local/Range/Table/100/"84d9de20c1e47df2"/Transaction/"154e8702-1d72-4f75-99ef-a00fb855082d" (0x016b12ec123834643964653230633165343764663200ff01000174786e2d154e87021d724f7599efa00fb855082d00): meta={id=154e8702 key=/Table/100/"84d9de20c1e47df2" iso=Serializable pri=0.00374294 epo=0 ts=1699467457.106561745,0 min=1699467457.106561745,0 seq=3} lock=true stat=STAGING rts=0,0 wto=false gul=0,0 ifw=2
0,0 /Local/RangeID/87/u/RaftLog/logIndex:12 (0x0169df757266746c000000000000000c00): Term:6 Index:12 Type:EntryNormal  (ID 4a37f23fa745a2e1) by lease #6
proposer_lease_sequence:6 max_lease_index:1 closed_timestamp:<wall_time:1699467454363124760 > replicated_eval_result:<write_timestamp:<wall_time:1699467457334971485 > delta:<last_update_nanos:1699467457334971485 live_bytes:147 live_count:1 key_bytes:33 key_count:1 val_bytes:114 val_count:1 intent_bytes:30 intent_count:1 lock_count:1 > > logical_op_log:<ops:<write_intent:<txn_id:6765e212-730a-42f6-9c22-867af51eac70 txn_key:"\354\022a6afc0ccb2e7a517\000\001" txn_min_timestamp:<wall_time:1699467457334971485 > timestamp:<wall_time:1699467457334971485 > > > > trace_data:<key:"crdb-tracer-spanid" value:"371a32995ca19d6" > trace_data:<key:"crdb-tracer-traceid" value:"424a888f4a0dfebd" > trace_data:<key:"rec" value:"v" >
write batch:
Put: /Local/Lock/Table/100/"a6afc0ccb2e7a517" 036765e212730a42f69c22867af51eac70 (0x017a6b12ec126136616663306363623265376135313700ff01000100036765e212730a42f69c22867af51eac7012): 1699467457.334971485,0 txn={id=6765e212 key=/Table/100/"a6afc0ccb2e7a517" iso=Serializable pri=0.00785044 epo=0 ts=1699467457.334971485,0 min=1699467457.334971485,0 seq=1} ts=1699467457.334971485,0 del=false klen=12 vlen=18 mergeTs=<nil> txnDidNotUpdateMeta=true
Put: 1699467457.334971485,0 /Table/100/"a6afc0ccb2e7a517" (0xec12613661666330636362326537613531370001001795b8a5f5c98c5d09): "\x00\x00\x00\x05e\n\x00\x12\x01?Y@ύ\x03v63"
0,0 /Local/RangeID/87/u/RaftLog/logIndex:11 (0x0169df757266746c000000000000000b00): Term:6 Index:11 Type:EntryNormal : EMPTY [recovered]
	panic: raft closed timestamp regression in cmd: 0ad4ef7915f2d9f7 (term: 6, index: 15); batch state: 1699467454.363124760,0, command: 1699467454.251881189,0, lease: repl=(n4,s4):3 seq=6 start=1699467455.023997901,0 epo=1 pro=1699467455.050226403,0, req: Delete [/Table/100/"921399d2662065ac",/Min), applying at LAI: 2.
Closed timestamp was set by req: <unknown; not leaseholder or not lease request> under lease: repl=(n4,s4):3 seq=6 start=1699467455.023997901,0 epo=1 pro=1699467455.050226403,0; applied at LAI: 1. Batch idx: 3.
Raft log tail:
0,0 /Local/RangeID/87/u/RaftLog/logIndex:15 (0x0169df757266746c000000000000000f00): Term:6 Index:15 Type:EntryNormal  (ID 0ad4ef7915f2d9f7) by lease #6
proposer_lease_sequence:6 max_lease_index:2 closed_timestamp:<wall_time:1699467454251881189 > replicated_eval_result:<write_timestamp:<wall_time:1699467457220837413 > delta:<last_update_nanos:1699467457220837413 gc_bytes_age:-105 key_bytes:12 val_bytes:10 val_count:1 > > logical_op_log:<ops:<write_value:<key:"\354\022921399d2662065ac\000\001" timestamp:<wall_time:1699467457220837413 > > > > trace_data:<key:"crdb-tracer-spanid" value:"1f480b794554a22a" > trace_data:<key:"crdb-tracer-traceid" value:"2272cc9f2c98e869" > trace_data:<key:"rec" value:"v" >
write batch:
Put: 1699467457.220837413,0 /Table/100/"921399d2662065ac" (0xec12393231333939643236363230363561630001001795b8a5eefc002509): "\x00\x00\x00\x05e\n\x00\x12\x01>"
0,0 /Local/RangeID/87/u/RaftLog/logIndex:14 (0x0169df757266746c000000000000000e00): Term:6 Index:14 Type:EntryNormal  (ID 4a37f23fa745a2e1) by lease #6
proposer_lease_sequence:6 max_lease_index:1 closed_timestamp:<wall_time:1699467454363124760 > replicated_eval_result:<write_timestamp:<wall_time:1699467457334971485 > delta:<last_update_nanos:1699467457334971485 live_bytes:147 live_count:1 key_bytes:33 key_count:1 val_bytes:114 val_count:1 intent_bytes:30 intent_count:1 lock_count:1 > > logical_op_log:<ops:<write_intent:<txn_id:6765e212-730a-42f6-9c22-867af51eac70 txn_key:"\354\022a6afc0ccb2e7a517\000\001" txn_min_timestamp:<wall_time:1699467457334971485 > timestamp:<wall_time:1699467457334971485 > > > > trace_data:<key:"crdb-tracer-spanid" value:"371a32995ca19d6" > trace_data:<key:"crdb-tracer-traceid" value:"424a888f4a0dfebd" > trace_data:<key:"rec" value:"v" >
write batch:
Put: /Local/Lock/Table/100/"a6afc0ccb2e7a517" 036765e212730a42f69c22867af51eac70 (0x017a6b12ec126136616663306363623265376135313700ff01000100036765e212730a42f69c22867af51eac7012): 1699467457.334971485,0 txn={id=6765e212 key=/Table/100/"a6afc0ccb2e7a517" iso=Serializable pri=0.00785044 epo=0 ts=1699467457.334971485,0 min=1699467457.334971485,0 seq=1} ts=1699467457.334971485,0 del=false klen=12 vlen=18 mergeTs=<nil> txnDidNotUpdateMeta=true
Put: 1699467457.334971485,0 /Table/100/"a6afc0ccb2e7a517" (0xec12613661666330636362326537613531370001001795b8a5f5c98c5d09): "\x00\x00\x00\x05e\n\x00\x12\x01?Y@ύ\x03v63"
0,0 /Local/RangeID/87/u/RaftLog/logIndex:13 (0x0169df757266746c000000000000000d00): Term:6 Index:13 Type:EntryNormal  (ID 174586ad919d0c61) by lease #6
proposer_lease_sequence:6 max_lease_index:1 closed_timestamp:<wall_time:1699467454220166867 > replicated_eval_result:<write_timestamp:<> delta:<sys_bytes:209 sys_count:1 > > logical_op_log:<> trace_data:<key:"crdb-tracer-spanid" value:"57408be841ad35c7" > trace_data:<key:"crdb-tracer-traceid" value:"43f7d2178c451aed" > trace_data:<key:"rec" value:"v" >
write batch:
Put: 0,0 /Local/Range/Table/100/"84d9de20c1e47df2"/Transaction/"154e8702-1d72-4f75-99ef-a00fb855082d" (0x016b12ec123834643964653230633165343764663200ff01000174786e2d154e87021d724f7599efa00fb855082d00): meta={id=154e8702 key=/Table/100/"84d9de20c1e47df2" iso=Serializable pri=0.00374294 epo=0 ts=1699467457.106561745,0 min=1699467457.106561745,0 seq=3} lock=true stat=STAGING rts=0,0 wto=false gul=0,0 ifw=2
0,0 /Local/RangeID/87/u/RaftLog/logIndex:12 (0x0169df757266746c000000000000000c00): Term:6 Index:12 Type:EntryNormal  (ID 4a37f23fa745a2e1) by lease #6
proposer_lease_sequence:6 max_lease_index:1 closed_timestamp:<wall_time:1699467454363124760 > replicated_eval_result:<write_timestamp:<wall_time:1699467457334971485 > delta:<last_update_nanos:1699467457334971485 live_bytes:147 live_count:1 key_bytes:33 key_count:1 val_bytes:114 val_count:1 intent_bytes:30 intent_count:1 lock_count:1 > > logical_op_log:<ops:<write_intent:<txn_id:6765e212-730a-42f6-9c22-867af51eac70 txn_key:"\354\022a6afc0ccb2e7a517\000\001" txn_min_timestamp:<wall_time:1699467457334971485 > timestamp:<wall_time:1699467457334971485 > > > > trace_data:<key:"crdb-tracer-spanid" value:"371a32995ca19d6" > trace_data:<key:"crdb-tracer-traceid" value:"424a888f4a0dfebd" > trace_data:<key:"rec" value:"v" >
write batch:
Put: /Local/Lock/Table/100/"a6afc0ccb2e7a517" 036765e212730a42f69c22867af51eac70 (0x017a6b12ec126136616663306363623265376135313700ff01000100036765e212730a42f69c22867af51eac7012): 1699467457.334971485,0 txn={id=6765e212 key=/Table/100/"a6afc0ccb2e7a517" iso=Serializable pri=0.00785044 epo=0 ts=1699467457.334971485,0 min=1699467457.334971485,0 seq=1} ts=1699467457.334971485,0 del=false klen=12 vlen=18 mergeTs=<nil> txnDidNotUpdateMeta=true
Put: 1699467457.334971485,0 /Table/100/"a6afc0ccb2e7a517" (0xec12613661666330636362326537613531370001001795b8a5f5c98c5d09): "\x00\x00\x00\x05e\n\x00\x12\x01?Y@ύ\x03v63"
0,0 /Local/RangeID/87/u/RaftLog/logIndex:11 (0x0169df757266746c000000000000000b00): Term:6 Index:11 Type:EntryNormal : EMPTY

goroutine 5716 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0x1ffb82a?, {0x6c0ac70, 0xc0079e6390})
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:230 +0x6a
panic({0x4dd81e0, 0xc0084cffb0})
	GOROOT/src/runtime/panic.go:884 +0x213
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic({0x6c0ac70, 0xc007d06780}, 0xc000f1e000, {0x518c61a?, 0x0?}, {0xc006f46248?, 0x0?, 0x0?})
	github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:417 +0x1b4
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).assertNoCmdClosedTimestampRegression(0xc00dd60690, {0x6c0ac70, 0xc007d06780}, 0xc0043a46b8)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go:736 +0x53d
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).Stage(0xc00dd60690, {0x6c0ac70, 0xc007d06780}, {0x6c2c040?, 0xc0043a46b8})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go:117 +0x145
github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.mapCmdIter({0x6c39ca0?, 0xc00dd60a38}, 0xc006f465b8)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/cmd.go:192 +0x158
github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch(0xc006f46b08, {0x6c0ac70, 0xc01620aed0}, {0x6c39ca0, 0xc00dd60a08})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:284 +0x15d
github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries(0xc006f46b08, {0x6c0ac70, 0xc01620aed0})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:251 +0x9a
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1053 +0x13b9
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:740 +0x1a7
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc002a08000, 0x6c0ac70?)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:689 +0x14b
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0xc005d6bd50, {0x6c0ac70, 0xc0079e6390}, {0x6bf0720, 0xc002a08000}, 0xc00292a000)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:418 +0x1f2
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x6c0ac70?, 0xc0079e6390?})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:321 +0x45
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x43b
```

Jira issue: CRDB-33319

**Comment by jbowens** [comment]
Appears to be a duplicate of #70894.
