### ISSUE TITLE
sql: TestFakeSpanResolver timed out under stress race

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#114132]
See CI build [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12574024&buildTypeId=Cockroach_BazelExtendedCi).

Jira issue: CRDB-33362

**Comment by yuzefovich** [comment]
Looks like we were in the process of starting up a cluster for this test:
```
goroutine 38 [select]:
google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc00c56db00)
	google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/transport.go:328 +0x11a
google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
	google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/transport.go:343
google.golang.org/grpc.(*csAttempt).recvMsg(0xc0049c95f0, {0x78d0420?, 0xc00e9a13c0}, 0x0)
	google.golang.org/grpc/external/org_golang_google_grpc/stream.go:1046 +0x14d
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc00c56d3d4?)
	google.golang.org/grpc/external/org_golang_google_grpc/stream.go:900 +0x57
google.golang.org/grpc.(*clientStream).withRetry(0xc00c56d320, 0xc019b05540, 0xc019b05510)
	google.golang.org/grpc/external/org_golang_google_grpc/stream.go:751 +0x198
google.golang.org/grpc.(*clientStream).RecvMsg(0xc00c56d320, {0x78d0420, 0xc00e9a13c0})
	google.golang.org/grpc/external/org_golang_google_grpc/stream.go:899 +0x188
github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.(*tracingClientStream).RecvMsg(0xc00a23dbe0, {0x78d0420, 0xc00e9a13c0})
	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:392 +0x59
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*multiRaftDelegateRaftSnapshotClient).Recv(0xc0013fbc00)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:195 +0x68
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).DelegateSnapshot(0xc000bf8380, {0xb15d3b8, 0xc0074002d0}, 0xc00e1c7880)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:1176 +0x287
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendSnapshotUsingDelegate.func2({0xb15d3b8, 0xc0074002d0})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_command.go:2875 +0x90
github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout({0xb15d460, 0xc012c460c0}, {0x7ac1e2e, 0xd}, 0x34630b8a000, 0xc0085ebbb8)
	github.com/cockroachdb/cockroach/pkg/util/timeutil/timeout.go:29 +0x128
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendSnapshotUsingDelegate(0xc001615100, {0xb15d460, 0xc012c460c0}, {0x3, 0x3, 0x3, 0x1}, 0x1, 0x1, 0x1, ...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_command.go:2872 +0xe65
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).initializeRaftLearners(0xc001615100, {0xb15d460, 0xc012c460c0}, 0xc00fd888c0, 0x0?, 0x0?, 0x0?, {0x7aea5af, 0x16}, {0xc00af7af00, ...}, ...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_command.go:1846 +0xdb6
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).changeReplicasImpl(0xc001615100, {0xb15d460, 0xc012c460c0}, 0x0?, 0x0?, 0x0?, 0xb15d460?, {0x7aea5af, 0x16}, {0xc00af7af00, ...}, ...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_command.go:1083 +0x87d
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicateQueue).changeReplicas(...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicate_queue.go:1114
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicateQueue).applyChange(0xc0028d5ae0?, {0xb15d460, 0xc012c460c0}, {0x4, {0xb1aaae8, 0xc001615100}, {0xb139808, 0xc0053ea320}, {0x1, 0x1, ...}}, ...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicate_queue.go:815 +0x22e
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicateQueue).processOneChange(0xc0044350e0, {0xb15d460, 0xc012c460c0}, 0x7ac9d3b?, 0xf?, 0xc0085ecc60?, 0x1?, 0x80?, 0x0)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicate_queue.go:916 +0x358
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicateQueue).processOneChangeWithTracing(0xc0044350e0, {0xb15d428, 0xc012c46000}, 0xc001615100, 0x4000000000000000?, 0x5?)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicate_queue.go:759 +0x27a
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicateQueue).process(0xc0044350e0, {0xb15d428, 0xc012c46000}, 0xc001615100, {0x7f4d7d4e42d0, 0xc0001b5540})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicate_queue.go:668 +0x48f
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica.func1({0xb15d428, 0xc012c46000})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:1036 +0x2f5
github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout({0xb15d460, 0xc0028cc1b0}, {0xc006a7f200, 0x21}, 0xdf8475800, 0xc0085ed770)
	github.com/cockroachdb/cockroach/pkg/util/timeutil/timeout.go:29 +0x128
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica(0xc0035ac9a0, {0xb15d460, 0xc0066bbf50}, {0xb1a5720, 0xc001615100})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:995 +0x65c
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).DrainQueue(0xc0035ac9a0, 0xc004e3d8f8?)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:1399 +0x205
github.com/cockroachdb/cockroach/pkg/kv/kvserver.forceScanAndProcess({0xb15d3f0, 0xc0000840c8}, 0xc002450a80, 0xc0035ac9a0)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue_helpers_testutil.go:42 +0x15e
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).ForceReplicationScanAndProcess(...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue_helpers_testutil.go:55
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForFullReplication.func2(0xc002450a80)
	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1448 +0x150
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1(0x733e4c0?, 0xc001340cc0?)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149 +0x5e
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range(0xc0010384c0, 0xc019b07cf8)
	github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:358 +0x191
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores(0xc001038480, 0xc004e3de00)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:148 +0x76
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForFullReplication(0xc001665100)
	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1440 +0x4ba
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start(0xc001665100, {0xb19a700?, 0xc000392820?})
	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:449 +0xa0b
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartCluster({_, _}, _, {{{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_cluster_shim.go:288 +0x145
github.com/cockroachdb/cockroach/pkg/sql/physicalplan_test.TestFakeSpanResolver(0xc000392820)
	github.com/cockroachdb/cockroach/pkg/sql/physicalplan_test/pkg/sql/physicalplan/fake_span_resolver_test.go:37 +0x13b
testing.tRunner(0xc000392820, 0x7df0138)
	GOROOT/src/testing/testing.go:1576 +0x217
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:1629 +0x806
```
I think this type of problem should be addressed by #114169.
