### ISSUE TITLE
sql: TestCreateStatsControlJob slow to quiesce under stressrace

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#115420]
**Describe the problem**

In a recent 23.2 backport, I saw this fail in CI:

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/12930404?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Taking a quick look at the stats, at least one place we are stuck is here:

```
* goroutine 40249 [chan receive, 2 minutes]:
* github.com/cockroachdb/cockroach/pkg/sql/stats_test.createStatsRequestFilter.func1({0xc00ec60fc0?, 0xb1f47c0?}, 0xc016f52ab0?)
* 	github.com/cockroachdb/cockroach/pkg/sql/stats_test/pkg/sql/stats/create_stats_job_test.go:566 +0x14d
* github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes(0xc00111f100, {0xb1f47c0, 0xc016f52a80}, 0xc00ec60fc0)
* 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:173 +0x4b6
* github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes(0xc0045c8a80, {0xb1f47c0, 0xc016f52a50}, 0xc00ec60fc0)
* 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:193 +0xcbe
* github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes(0xc0144cd4d0?, {0xb1f47c0, 0xc016f52a50}, 0xc00ec60fc0)
* 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:202 +0x173
* github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc0030e4c00, {0xb1f47c0, 0xc016f529c0}, {0xc0034ade60?}, 0xc00ec60fc0)
* 	github.com/cockroachdb/cockroach/pkg/server/node.go:1328 +0x7d3
* github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc0030e4c00, {0xb1f47c0, 0xc016f52960}, 0xc00ec60fc0)
* 	github.com/cockroachdb/cockroach/pkg/server/node.go:1462 +0x465
* github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func1({0xb1f47c0, 0xc016f52960}, {0x7ab4220?, 0xc00ec60fc0})
* 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:704 +0x7d
* github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1({0xb1f47c0, 0xc016f52960}, {0x7ab4220, 0xc00ec60fc0}, 0xc003d92a40, 0xc002b9c840)
* 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:97 +0x1d5
* github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1({0xb1f47c0, 0xc016f52960}, {0x7ab4220, 0xc00ec60fc0})
* 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:815 +0x8f
* github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3({0xb1f47c0, 0xc016f52960}, {0x7ab4220, 0xc00ec60fc0}, 0xc003d92a40, 0xc003d92a60)
* 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:169 +0xf9
* github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1({0xb1f47c0, 0xc016f52960}, {0x7ab4220, 0xc00ec60fc0})
* 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:815 +0x8f
* github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor({0xc00324c000?, {{0x7fd9d407a700?}, {0xb22c200?, 0xc001256780?}}}, {0xb1f47c0, 0xc016f52960}, {0x7ab4220, 0xc00ec60fc0}, 0xc003d92a40, 0xc003d92ae0)
* 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:105 +0x2f4
* github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1({0xb1f47c0, 0xc016f52960}, {0x7ab4220, 0xc00ec60fc0})
* 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:815 +0x8f
* github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1({0xb1f47c0, 0xc016f52960})
* 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:136 +0x71
* github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc0001b8e60, {0xb1f47c0, 0xc016f52960}, {0xacecbb8bee808008?, 0x25a0afc8801017ce?}, 0xc013ece8f0)
* 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:336 +0x148
* github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1({0xb1f47c0, 0xc016f52960}, {0x7ab4220, 0xc00ec60fc0}, 0xc003d92a40, 0xc003d92b00)
* 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:134 +0x138
* github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1({0xb1f47c0, 0xc016f52960}, {0x7ab4220, 0xc00ec60fc0})
* 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:815 +0x8f
```

The request filter is installed by the test and is waiting on a channel send, which is never going to happen because the test is done. My guess at what is happening here is that under stressrace the auto stats job is starting up which might get stuck on this filter.

Jira issue: CRDB-34023

**Comment by yuzefovich** [comment]
This test is now skipped under race.
