### ISSUE TITLE
server: TestServerController timeout under stressrace

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#116469]
In this [CI run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/13131147?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) I saw TestServerController timeout under stressrace. Appears to be during an upgrade:

```
=== RUN   TestServerController
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/5b2c9b3a394428c7572d34050aad8975/logTestServerController1896300813
    test_log_scope.go:81: use -show-logs to present logs inline
panic: test timed out after 7m12s

running tests:
  TestServerController (7s)

goroutine 82920 [running]:
testing.(*M).startAlarm.func1()
  GOROOT/src/testing/testing.go:2259 +0x259
created by time.goFunc
  GOROOT/src/time/sleep.go:176 +0x45

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0014871e0, {0x8586ef5, 0x14}, 0x88bae20)
  GOROOT/src/testing/testing.go:1649 +0x871
testing.runTests.func1(0x0?)
  GOROOT/src/testing/testing.go:2054 +0x85
testing.tRunner(0xc0014871e0, 0xc00338f848)
  GOROOT/src/testing/testing.go:1595 +0x262
testing.runTests(0xc001a0a8c0?, {0xedbace0, 0x7e, 0x7e}, {0x0?, 0xc003113710?, 0xf17a940?})
  GOROOT/src/testing/testing.go:2052 +0x8ae
testing.(*M).Run(0xc001a0a8c0)
  GOROOT/src/testing/testing.go:1925 +0xcd8
github.com/cockroachdb/cockroach/pkg/server_test.TestMain(0x85d30ff?)
  github.com/cockroachdb/cockroach/pkg/server_test/pkg/server/main_test.go:38 +0x31e
main.main()
  main/bazel-out/k8-fastbuild/bin/pkg/server/server_test_/testmain.go:384 +0x82c

goroutine 7 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000b4ab00)
  go.opencensus.io/stats/view/external/io_opencensus_go/stats/view/worker.go:292 +0x199
created by go.opencensus.io/stats/view.init.0 in goroutine 1
  go.opencensus.io/stats/view/external/io_opencensus_go/stats/view/worker.go:34 +0xfd

goroutine 9 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/goschedstats.init.0.func1()
  github.com/cockroachdb/cockroach/pkg/util/goschedstats/runnable.go:172 +0x13b
created by github.com/cockroachdb/cockroach/pkg/util/goschedstats.init.0 in goroutine 1
  github.com/cockroachdb/cockroach/pkg/util/goschedstats/runnable.go:164 +0x25

goroutine 10 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
  github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:117 +0x6e
created by github.com/cockroachdb/cockroach/pkg/util/log.init.5 in goroutine 1
  github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:83 +0x25

goroutine 11 [chan receive, 7 minutes]:
github.com/cockroachdb/cockroach/pkg/util/log.signalFlusher()
  github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:141 +0xae
created by github.com/cockroachdb/cockroach/pkg/util/log.init.5 in goroutine 1
  github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:84 +0x31

goroutine 50 [syscall, 7 minutes]:
os/signal.signal_recv()
  GOROOT/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
  GOROOT/src/os/signal/signal_unix.go:23 +0x1d
created by os/signal.Notify.func1.1 in goroutine 11
  GOROOT/src/os/signal/signal.go:151 +0x47

goroutine 80301 [select]:
github.com/cockroachdb/cockroach/pkg/util/retry.(*Retry).Next(0xc003198638)
  github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:128 +0x27d
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).waitForJobsToBeTerminalOrPaused(0xc00415ea00, {0xba5ec60, 0xc018e7d530}, {0xc004d10cf8, 0x1, 0x1}, 0xc00db3f9e0)
  github.com/cockroachdb/cockroach/pkg/jobs/wait.go:107 +0x2ce
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).waitForJobs(0xc00415ea00?, {0xba5ec60?, 0xc018e7d530}, {0xc004d10cf8?, 0x1, 0x1}, 0x100000048ca91?)
  github.com/cockroachdb/cockroach/pkg/jobs/wait.go:157 +0x251
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Run(0xc018e7d530?, {0xba5ec60, 0xc018e7d530}, {0xc004d10cf8, 0x1, 0x1})
  github.com/cockroachdb/cockroach/pkg/jobs/wait.go:213 +0x125
github.com/cockroachdb/cockroach/pkg/upgrade/upgrademanager.(*Manager).runMigration.func3({0xba5ec60, 0xc018e7d530})
  github.com/cockroachdb/cockroach/pkg/upgrade/upgrademanager/manager.go:746 +0xb0
github.com/cockroachdb/cockroach/pkg/util/startup.RunIdempotentWithRetry.func1({0xba5ec60, 0xc018e7d530})
  github.com/cockroachdb/cockroach/pkg/util/startup/retry.go:121 +0x3f
github.com/cockroachdb/cockroach/pkg/util/startup.RunIdempotentWithRetryEx[...]({0xba5ec60?, 0xc01aeccdb0}, 0xc007fbec60, {0x85752d6, 0x10}, 0xc003198ee8)
  github.com/cockroachdb/cockroach/pkg/util/startup/retry.go:142 +0x34a
github.com/cockroachdb/cockroach/pkg/util/startup.RunIdempotentWithRetry({0xba5ec60, 0xc01aeccdb0}, 0x1?, {0x85752d6, 0x10}, 0xc003199118)
  github.com/cockroachdb/cockroach/pkg/util/startup/retry.go:120 +0xa8
github.com/cockroachdb/cockroach/pkg/upgrade/upgrademanager.(*Manager).runMigration(0xc0049f1340, {0xba5ec60, 0xc01aeccdb0}, {0xba5eb80?, 0xc0018b5b30}, {{0x8548c04?, 0x86174a3?}}, {0x16, 0x2, 0x0, ...}, ...)
  github.com/cockroachdb/cockroach/pkg/upgrade/upgrademanager/manager.go:743 +0x6c6
github.com/cockroachdb/cockroach/pkg/upgrade/upgrademanager.(*Manager).RunPermanentUpgrades(0xc0049f1340, {0xba5ec60, 0xc01aeccdb0}, {0x17, 0x1, 0x0, 0x20})
  github.com/cockroachdb/cockroach/pkg/upgrade/upgrademanager/manager.go:283 +0xe79
github.com/cockroachdb/cockroach/pkg/server.(*SQLServer).preStart(_, {_, _}, _, {{0xba18320, 0xc004305180}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
  github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1637 +0x19ee
github.com/cockroachdb/cockroach/pkg/server.(*topLevelServer).PreStart(0xc0040d8000, {0xba5e7c8, 0x1031a380})
  github.com/cockroachdb/cockroach/pkg/server/server.go:2058 +0x5766
github.com/cockroachdb/cockroach/pkg/server.(*testServer).PreStart(0xc0068db500, {0xba5e7c8, 0x1031a380})
  github.com/cockroachdb/cockroach/pkg/server/testserver.go:807 +0xe5
github.com/cockroachdb/cockroach/pkg/server.(*testServer).Start(0xc0068db500, {0xba5e7c8, 0x1031a380})
  github.com/cockroachdb/cockroach/pkg/server/testserver.go:883 +0xdb
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.(*wrap).Start(0xc007f90bd0, {0xba5e7c8, 0x1031a380})
  github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/testutils/serverutils/ts_control_forwarder_generated.go:15 +0x74
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerOnlyE({_, _}, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:279 +0x282
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerOnly({_, _}, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:294 +0x87
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer({_, _}, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:312 +0x70
github.com/cockroachdb/cockroach/pkg/server.TestServerController(0xc011aec000)
  github.com/cockroachdb/cockroach/pkg/server/server_controller_test.go:39 +0x1ac
testing.tRunner(0xc011aec000, 0x88bae20)
  GOROOT/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
  GOROOT/src/testing/testing.go:1648 +0x846

...
```

Jira issue: CRDB-34635

**Comment by rimadeodhar** [comment]
I'm going to bump this down to P-3 and leave it open. The DB Server team plans to pick this up as a part of our H2 roadmap.

**Comment by cthumuluru-crdb** [comment]
This is ticket is pretty only and when I ran a couple of weeks back, I was not able to reproduce the issue under stress. I'm inclined to close this and pick it up next time it happens.
