### ISSUE TITLE
stability: blue 8 OOM

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#11718]
cockroach-blue-08 exited without a comment right after a snapshot.  It clearly was running slowly recently with a lot of processes taking longer than 1s.

Here's the tail of the log:
```
I161130 16:48:25.750658 372 server/status/runtime.go:228  runtime stats: 13 GiB RSS, 3068 goroutines, 4.5 GiB/2.3 GiB/7.6 GiB GO alloc/idle/total, 4.3 GiB/5.2 GiB CGO alloc/total, 102931.94cgo/sec, 1.87/0.43 %(u/s)time, 0.01 %gc (1x)
W161130 16:48:25.806540 420962 storage/engine/rocksdb.go:1030  batch [300799/20896188/46] commit took 1.22555972s (>500ms):
goroutine 420962 [running]:
runtime/debug.Stack(0xecfd0f9d8, 0x2263d166, 0x29ee940)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc4fe17ae00, 0xc438e88a50, 0x253aec0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1030 +0x1d2
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applySnapshot(0xc4213ad200, 0x2533960, 0xc438e88a50, 0x984675f6cf140167, 0x79c4a9f5d4757e8d, 0xc5b6549800, 0x2a, 0x40, 0xc54ff2a000, 0x578, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raftstorage.go:714 +0xc9e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4213ad200, 0x984675f6cf140167, 0x79c4a9f5d4757e8d, 0xc5b6549800, 0x2a, 0x40, 0xc54ff2a000, 0x578, 0x6aa, 0xc4cc8406c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2383 +0x1207
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc420487500, 0x2533960, 0xc438e88690, 0xc4cc840780, 0x984675f6cf140167, 0x79c4a9f5d4757e8d, 0xc5b6549800, 0x2a, 0x40, 0xc54ff2a000, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2982 +0xd70
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc420487500, 0xc4cc8406c0, 0x7f874ec8cd30, 0xc453c99000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2628 +0x717
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x25393e0, 0xc453c99000, 0xc4204c5140, 0x2533960, 0xc4424ee870, 0xc46d56f738, 0xc46d56f740)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:362 +0x182
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x2533960, 0xc4424ee870)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:363 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4203fa000, 0x21f2f21, 0x19, 0x16c, 0x0, 0x0, 0xc4424ee900, 0x2533960, 0xc4424ee870)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:264 +0xdf
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:265 +0x234
I161130 16:48:25.819889 420962 storage/replica_raftstorage.go:639  [n8,s8,r9003/2:/Table/51/1/51{48961…-50078…},@c4213ad200] applied Raft snapshot in 16512ms [clear=14883ms batch=382ms entries=4ms commit=1242ms]
```

**Comment by petermattis** [comment]
I think the process ran out of memory:

<img width="932" alt="screen shot 2016-11-30 at 2 11 45 pm" src="https://cloud.githubusercontent.com/assets/6201335/20767123/f944ccae-b706-11e6-811e-10447cbf6b42.png">

```
~ dmesg
...
[3143325.509061] Out of memory: Kill process 44203 (cockroach) score 914 or sacrifice child
[3143325.513019] Killed process 44203 (cockroach) total-vm:18234916kB, anon-rss:13509388kB, file-rss:0kB
```

**Comment by dianasaur323** [comment]
assigning @BramGruneir

**Comment by petermattis** [comment]
This happened a long time ago. There is likely little that can be done now and it is possible that the cause of the OOM was already fixed.
