### ISSUE TITLE
pkg/sql/schemachanger: `TestAlterTableDMLInjection` fails under `race` [out of bounds error in createStatsDefaultColumns]

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#118690]
[EngFlow link](https://tanzanite.cluster.engflow.com/invocations/default/928a3274-593b-4ac1-a27e-0975c02c7809?testReportRun=2&testReportAttempt=0#targets-Ly9wa2cvc3FsL3NjaGVtYWNoYW5nZXI6c2NoZW1hY2hhbmdlcl90ZXN0)

```
panic: runtime error: index out of range [5] with length 5 [recovered]
	panic: runtime error: index out of range [5] with length 5 [recovered]
	panic: runtime error: index out of range [5] with length 5 [recovered]
	panic: runtime error: index out of range [5] with length 5
goroutine 159232 [running]:
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1()
	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58 +0x5f3
panic({0x7cc2b60?, 0xc0016439c8?})
	GOROOT/src/runtime/panic.go:920 +0x270
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1()
	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58 +0x5f3
panic({0x7cc2b60?, 0xc0016439c8?})
	GOROOT/src/runtime/panic.go:920 +0x270
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1()
	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58 +0x5f3
panic({0x7cc2b60?, 0xc0016439c8?})
```

Jira issue: CRDB-35843

**Comment by rafiss** [comment]
based on the stack trace, this is another occurrence of https://github.com/cockroachdb/cockroach/issues/118537

```
goroutine 159232 [running]:
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1()
	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58 +0x5f3
panic({0x7cc2b60?, 0xc0016439c8?})
	GOROOT/src/runtime/panic.go:920 +0x270
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1()
	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58 +0x5f3
panic({0x7cc2b60?, 0xc0016439c8?})
	GOROOT/src/runtime/panic.go:920 +0x270
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1()
	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58 +0x5f3
panic({0x7cc2b60?, 0xc0016439c8?})
	GOROOT/src/runtime/panic.go:920 +0x270
github.com/cockroachdb/cockroach/pkg/sql.createStatsDefaultColumns.func1({0xae285d0, 0xc00ae6bb60})
	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:414 +0xca
github.com/cockroachdb/cockroach/pkg/sql.createStatsDefaultColumns.func3(0x7, 0x0)
	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:440 +0x98
github.com/cockroachdb/cockroach/pkg/sql.createStatsDefaultColumns({0xad79898, 0xc000d2dce0}, {0xae54610?, 0xc005ce9900}, 0x1, 0x1, 0xc8, 0xc000d2dce0?)
	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:475 +0x74a
github.com/cockroachdb/cockroach/pkg/sql.(*createStatsNode).makeJobRecord(0xc00e800850, {0xad79898, 0xc000d2dce0})
	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:259 +0x9cc
github.com/cockroachdb/cockroach/pkg/sql.(*createStatsNode).runJob(0xc00e800850, {0xad79898, 0xc000d2dce0})
	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:128 +0x65
github.com/cockroachdb/cockroach/pkg/sql.(*createStatsNode).startExec(0x0?, {{0xad79898?, 0xc000d2dce0?}, 0xc0127cb000?, 0xc00a031ff8?})
```

**Comment by rafiss** [comment]
fixed by https://github.com/cockroachdb/cockroach/pull/118930
