### ISSUE TITLE
sqlproxy tests segfault in --race tests

### ISSUE THREAD

**Issue by JeffSwenson** [cockroachdb/cockroach#119869]
A handful of tests in the sqlproxyccl test package segfault in the --stress --race builds. So far I have been unable to reproduce the failures.

The SQL proxy makes no explicit use of the unsafe package, so I'm skeptical the test failures are caused by memory unsafety within the sql proxy. There is a history of weird go runtime bugs when run via --race (e.g. https://github.com/golang/go/issues/60825#issuecomment-1593800172), but all known instances appear to be fixed in the go toolchain we are using.

The only consistent factor between the failures is the segfault occurs with `time.goFunc` as a root stack that is panicing. time.goFunc is used by the go stdlib to implement `time.AfterFunc`.

```
runtime.throw({0x7f91817fc348?, 0x4c63bb?})
	GOROOT/src/runtime/panic.go:1047 +0x5d fp=0x7f91817fc300 sp=0x7f91817fc2d0 pc=0x49a69d
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x48
```

Observed Instances:
* TestProxyProtocol (23.1 #116190, #121347)
* TestProxyAgainstSecureCRDB (23.1 #119193)
* TestPodWatcher (23.2 #115754)

Jira issue: CRDB-36363

**Comment by JeffSwenson** [comment]
[Pre-emptible_Nightlies_Stress_Bazel_1000_s_run_every_night_5111283.log](https://github.com/cockroachdb/cockroach/files/14484420/Pre-emptible_Nightlies_Stress_Bazel_1000_s_run_every_night_5111283.log)

**Comment by JeffSwenson** [comment]
The most recent reproduction of this was on the go1.19.13 toolchain:

```sh
git checkout 9ad399071aba1d361202f9ed6f64aae4f9351f4b
swenson@gceworker-jeffswenson:~/Code/cockroach$ ./dev go version
go version go1.19.13 linux/amd64
```

**Comment by JeffSwenson** [comment]
I checked out go1.19.13 and verified it has the fix for https://github.com/golang/go/issues/60844.

```
git checkout go1.19.13
swenson@crlMBP-PLQWWRDK95MTUz go % git log --grep=racecallatomic
commit c9d5dd5466b017eb91d6d10e5fb71434acd94f36
Author: Cherry Mui <cherryyz@google.com>
Date:   Thu Jun 15 18:16:51 2023 -0400

    [release-branch.go1.19] runtime: use 1-byte load for address checking in racecallatomic

    In racecallatomic, we do a load before calling into TSAN, so if
    the address is invalid we fault on the Go stack. We currently use
    a 8-byte load instruction, regardless of the data size that the
    atomic operation is performed on. So if, say, we are doing a
    LoadUint32 at an address that is the last 4 bytes of a memory
    mapping, we may fault unexpectedly. Do a 1-byte load instead.
    (Ideally we should do a load with the right size, so we fault
    correctly if we're given an unaligned address for a wide load
    across a page boundary. Leave that for another CL.)

    Fix AMD64, ARM64, and PPC64. The code already uses 1-byte load
    on S390X.

    Fixes #60844.
    Updates #60825.

    Change-Id: I3dee93eb08ba180c85e86a9d2e71b5b520e8dcf0
    Reviewed-on: https://go-review.googlesource.com/c/go/+/503937
    Run-TryBot: Cherry Mui <cherryyz@google.com>
    TryBot-Result: Gopher Robot <gobot@golang.org>
    Reviewed-by: Than McIntosh <thanm@google.com>
    Reviewed-by: David Chase <drchase@google.com>
    (cherry picked from commit 1a7709d6af76c06d465c5e969b502fc206f8e687)
    Reviewed-on: https://go-review.googlesource.com/c/go/+/503977
    Auto-Submit: Dmitri Shuralyov <dmitshur@google.com>
    TryBot-Bypass: Dmitri Shuralyov <dmitshur@golang.org>
    Reviewed-by: Austin Clements <austin@google.com>
```

**Comment by JeffSwenson** [comment]
There is a similar issue open in the go issue tracker https://github.com/golang/go/issues/64447.

**Comment by JeffSwenson** [comment]
I observed a new instance of this when I was running tests locally. I was trying to deflake a different test on the release-23.2 branch. 

I was running `./dev test --stress --race --filter TestPrivateEndpointsACL ./pkg/ccl/sqlproxyccl`.

```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x5753253 pc=0x8742a50]

goroutine 4054 [running]:
runtime.throw({0x4d28bb?, 0x4d12e0?})
        GOROOT/src/runtime/panic.go:1077 +0x5c fp=0x7f2c85bfe300 sp=0x7f2c85bfe2d0 pc=0x4a759c
runtime: g 4054: unexpected return pc for runtime.throw called from 0x7f2c85bfe340
stack: frame={sp:0x7f2c85bfe2d0, fp:0x7f2c85bfe300} stack=[0xc003e34000,0xc003e35000)

created by time.goFunc
        GOROOT/src/time/sleep.go:176 +0x45

goroutine 1 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x98?, 0x19?, 0x18?)
        GOROOT/src/runtime/proc.go:398 +0xce fp=0xc005953438 sp=0xc005953418 pc=0x4aa48e
runtime.chanrecv(0xc00306ed20, 0xc003e9f51f, 0x1)
        GOROOT/src/runtime/chan.go:583 +0x385 fp=0xc0059534b0 sp=0xc005953438 pc=0x4746e5
runtime.chanrecv1(0x974cd00?, 0x8c26680?)
        GOROOT/src/runtime/chan.go:442 +0x12 fp=0xc0059534d8 sp=0xc0059534b0 pc=0x474332
testing.(*T).Run(0xc002f5d040, {0x984e3fc, 0x17}, 0x9bf1640)
```

**Comment by JeffSwenson** [comment]
We haven't seen this in a while, so I'm closing this issue.
