### ISSUE TITLE
kvserver/concurrency: `BenchmarkLockTable` hanging

### ISSUE THREAD

**Issue by herkolategan** [cockroachdb/cockroach#120883]
**Describe the problem**

The `BenchmarkLockTable` from the `./pkg/kv/kvserver/concurrency` package is getting stuck on `BenchmarkLockTable/groups=1,outstanding=4,read=0/` 

**To Reproduce**

```
./dev bench ./pkg/kv/kvserver/concurrency --timeout=20m --filter=BenchmarkLockTable --count=1 --bench-time=1s --bench-mem -v --stream-output --ignore-cache
```

**Output**

```
# ./dev bench ./pkg/kv/kvserver/concurrency --timeout=20m --filter=BenchmarkLockTable --count=1 --bench-time=1s --bench-mem -v --stream-output --ignore-cache
$ bazel test --test_timeout=1200 pkg/kv/kvserver/concurrency:all --nocache_test_results --test_arg -test.run=- --test_arg -test.bench=BenchmarkLockTable --test_sharding_strategy=disabled --test_arg -test.v --test_arg -test.benchtime=1s --test_arg -test.benchmem --crdb_test_off --test_env COCKROACH_TEST_FIXTURES_DIR=/Users/herko/Library/Caches/crdb-test-fixtures --sandbox_writable_path=/Users/herko/Library/Caches/crdb-test-fixtures --test_output streamed
INFO: Invocation ID: 6b1076e6-f66f-48c1-9e8c-0b6a2d650880
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Analyzed 3 targets (0 packages loaded, 288 targets configured).
INFO: Found 2 targets and 1 test target...
goos: darwin
goarch: arm64
BenchmarkLockTable
BenchmarkLockTable/groups=1,outstanding=1,read=0/
BenchmarkLockTable/groups=1,outstanding=1,read=0/-10         	  193794	      6185 ns/op	    6573 B/op	      39 allocs/op
BenchmarkLockTable/groups=1,outstanding=1,read=1/
BenchmarkLockTable/groups=1,outstanding=1,read=1/-10         	  233892	      5101 ns/op	    5395 B/op	      30 allocs/op
BenchmarkLockTable/groups=1,outstanding=1,read=2/
BenchmarkLockTable/groups=1,outstanding=1,read=2/-10         	  290410	      4125 ns/op	    4217 B/op	      21 allocs/op
BenchmarkLockTable/groups=1,outstanding=1,read=3/
BenchmarkLockTable/groups=1,outstanding=1,read=3/-10         	  359509	      3249 ns/op	    3038 B/op	      12 allocs/op
BenchmarkLockTable/groups=1,outstanding=1,read=4/
BenchmarkLockTable/groups=1,outstanding=1,read=4/-10         	  694599	      1784 ns/op	     960 B/op	       2 allocs/op
BenchmarkLockTable/groups=1,outstanding=1,read=5/
BenchmarkLockTable/groups=1,outstanding=1,read=5/-10         	  613974	      1741 ns/op	     960 B/op	       2 allocs/op
BenchmarkLockTable/groups=1,outstanding=2,read=0/
BenchmarkLockTable/groups=1,outstanding=2,read=0/-10         	  112242	     13076 ns/op	    7380 B/op	      39 allocs/op
BenchmarkLockTable/groups=1,outstanding=2,read=1/
BenchmarkLockTable/groups=1,outstanding=2,read=1/-10         	  138296	      9293 ns/op	    6200 B/op	      30 allocs/op
BenchmarkLockTable/groups=1,outstanding=2,read=2/
BenchmarkLockTable/groups=1,outstanding=2,read=2/-10         	  169635	      7520 ns/op	    5012 B/op	      21 allocs/op
BenchmarkLockTable/groups=1,outstanding=2,read=3/
BenchmarkLockTable/groups=1,outstanding=2,read=3/-10         	  179359	      7304 ns/op	    3579 B/op	      11 allocs/op
BenchmarkLockTable/groups=1,outstanding=2,read=4/
BenchmarkLockTable/groups=1,outstanding=2,read=4/-10         	  889480	      1151 ns/op	     960 B/op	       2 allocs/op
BenchmarkLockTable/groups=1,outstanding=2,read=5/
BenchmarkLockTable/groups=1,outstanding=2,read=5/-10         	 1000000	      1277 ns/op	     960 B/op	       2 allocs/op
```

**Additional context**
On the microbenchmark jobs a regular `timeout` didn't manage to terminate the process.

**Trace**
```
Received SIGTERM, printing stack traces of all goroutines:
goroutine 10 [running]:
github.com/bazelbuild/rules_go/go/tools/bzltestutil.RegisterTimeoutHandler.func1()
	github.com/bazelbuild/rules_go/go/tools/bzltestutil/external/io_bazel_rules_go/go/tools/bzltestutil/timeout.go:36 +0x4c
created by github.com/bazelbuild/rules_go/go/tools/bzltestutil.RegisterTimeoutHandler in goroutine 1
	github.com/bazelbuild/rules_go/go/tools/bzltestutil/external/io_bazel_rules_go/go/tools/bzltestutil/timeout.go:33 +0x98

goroutine 1 [chan receive, 4 minutes]:
testing.(*B).run1(0x14000051188)
	GOROOT/src/testing/benchmark.go:217 +0xa0
testing.(*B).Run(0x14000050788, {0x101485398?, 0x140003799e8?}, 0x101bc2bb0)
	GOROOT/src/testing/benchmark.go:682 +0x3f4
testing.runBenchmarks.func1(0x14000050788)
	GOROOT/src/testing/benchmark.go:543 +0x40
testing.(*B).runN(0x14000050788, 0x1)
	GOROOT/src/testing/benchmark.go:193 +0x130
testing.runBenchmarks({0x0, 0x0}, 0x0?, {0x1028e2d60, 0x10, 0x1001c8f24?})
	GOROOT/src/testing/benchmark.go:552 +0x520
testing.(*M).Run(0x1400049f900)
	GOROOT/src/testing/testing.go:2043 +0x894
main.main()
	main/bazel-out/darwin_arm64-fastbuild/bin/pkg/kv/kvserver/concurrency/concurrency_test_/testmain.go:218 +0x3e4

goroutine 8 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
	github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:117 +0x50
created by github.com/cockroachdb/cockroach/pkg/util/log.init.5 in goroutine 1
	github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:83 +0x24

goroutine 9 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/pkg/util/log.signalFlusher()
	github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:141 +0x78
created by github.com/cockroachdb/cockroach/pkg/util/log.init.5 in goroutine 1
	github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:84 +0x30

goroutine 67 [syscall]:
os/signal.signal_recv()
	GOROOT/src/runtime/sigqueue.go:149 +0x2c
os/signal.loop()
	GOROOT/src/os/signal/signal_unix.go:23 +0x1c
created by os/signal.Notify.func1.1 in goroutine 9
	GOROOT/src/os/signal/signal.go:151 +0x28

goroutine 22 [chan receive, 2 minutes]:
testing.(*B).doBench(0x14000140c88)
	GOROOT/src/testing/benchmark.go:267 +0x78
testing.(*benchContext).processBench(0x1400080a108, 0x32?)
	GOROOT/src/testing/benchmark.go:582 +0x2cc
testing.(*B).run(0x14000140f08?)
	GOROOT/src/testing/benchmark.go:258 +0x68
testing.(*B).Run(0x14000051188, {0x140003902c0?, 0x1400023def8?}, 0x140004223e0)
	GOROOT/src/testing/benchmark.go:683 +0x400
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.BenchmarkLockTable(0x14000051188)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1881 +0x144
testing.(*B).runN(0x14000051188, 0x1)
	GOROOT/src/testing/benchmark.go:193 +0x130
testing.(*B).run1.func1()
	GOROOT/src/testing/benchmark.go:215 +0x50
created by testing.(*B).run1 in goroutine 1
	GOROOT/src/testing/benchmark.go:208 +0x90

goroutine 53044550 [chan receive, 2 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.doBenchWork(0x140001e3118, {0x140001d6300, {0x101bf7a00, 0x1400040c000}, 0x14000610070, 0x14000610078}, 0x14000a00060)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1732 +0x5d4
created by github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.runRequests in goroutine 52945910
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1854 +0x88

goroutine 53044578 [chan receive, 2 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.doBenchWork(0x140001e3068, {0x140001d6300, {0x101bf7a00, 0x1400040c000}, 0x14000610070, 0x14000610078}, 0x14000a00060)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1732 +0x5d4
created by github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.runRequests in goroutine 52945910
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1854 +0x88

goroutine 52945910 [chan receive, 2 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.runRequests(0x14000140c88, {0x101bcb418, 0x14000896a10}, {0x140001e2f08, 0x4, 0x100201944?}, {0x140001d6300, {0x101bf7a00, 0x1400040c000}, 0x14000610070, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1849 +0xd0
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.BenchmarkLockTable.func1(0x14000140c88)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1915 +0x390
testing.(*B).runN(0x14000140c88, 0x19908)
	GOROOT/src/testing/benchmark.go:193 +0x130
testing.(*B).launch(0x14000140c88)
	GOROOT/src/testing/benchmark.go:316 +0x170
created by testing.(*B).doBench in goroutine 22
	GOROOT/src/testing/benchmark.go:266 +0x68

goroutine 53044513 [chan receive, 2 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.doBenchWork(0x140001e2fb8, {0x140001d6300, {0x101bf7a00, 0x1400040c000}, 0x14000610070, 0x14000610078}, 0x14000a00060)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1732 +0x5d4
created by github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.runRequests in goroutine 52945910
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1854 +0x88

goroutine 53044549 [chan receive, 2 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.doBenchWork(0x140001e2f08, {0x140001d6300, {0x101bf7a00, 0x1400040c000}, 0x14000610070, 0x14000610078}, 0x14000a00060)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1732 +0x5d4
created by github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.runRequests in goroutine 52945910
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_test.go:1854 +0x88
```

Jira issue: CRDB-36928

**Comment by arulajmani** [comment]
This is probably because of https://github.com/cockroachdb/cockroach/pull/121840, which has since been fixed. We wouldn't expect this test to promote locks had it not been for https://github.com/cockroachdb/cockroach/pull/122231.
