### ISSUE TITLE
kvserver: "missing event variant" log fatal during Bench //pkg/kv/kvserver/rangefeed:rangefeed_test

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#121087]
I ran into this log.Fatal during `Bench //pkg/kv/kvserver/rangefeed:rangefeed_test` of [Bazel Extended CI](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/14558550?buildTab=overview&expandBuildProblemsSection=true&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true):

This was on master c5d1b23ded9be10271b5398242b4b622b08c8f7f plus https://github.com/cockroachdb/cockroach/pull/120875 which I believe is unrelated.

```
[17:46:21]W:		 [Run benchmark tests] Bench //pkg/kv/kvserver/rangefeed:rangefeed_test (5s)
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] + tc_end_block 'Bench //pkg/kv/kvserver/raftlog:raftlog_test'
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] + echo '
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] ##teamcity[blockClosed name='\''Bench //pkg/kv/kvserver/raftlog:raftlog_test'\'']
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] '
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] + for target in $targets
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] + tc_start_block 'Bench //pkg/kv/kvserver/rangefeed:rangefeed_test'
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] + echo '
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] ##teamcity[blockOpened name='\''Bench //pkg/kv/kvserver/rangefeed:rangefeed_test'\'']
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] '
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] + bazel run --config=test --config=crosslinux --config=ci --test_sharding_strategy=disabled //pkg/kv/kvserver/rangefeed:rangefeed_test -- -test.bench=. -test.benchtime=1x -test.short -test.run=-
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] Loading:
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] Loading:
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] Loading: 0 packages loaded
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] Analyzing: target //pkg/kv/kvserver/rangefeed:rangefeed_test (0 packages loaded, 0 targets configured)
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] INFO: Analyzed target //pkg/kv/kvserver/rangefeed:rangefeed_test (0 packages loaded, 11 targets configured).
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] INFO: Found 1 target...
[17:46:21]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] [0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[17:46:22]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] [7 / 8] [Prepa] GoLink pkg/kv/kvserver/rangefeed/rangefeed_test_/rangefeed_test
[17:46:24]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] [7 / 8] GoLink pkg/kv/kvserver/rangefeed/rangefeed_test_/rangefeed_test; 1s processwrapper-sandbox
[17:46:25]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] Target //pkg/kv/kvserver/rangefeed:rangefeed_test up-to-date:
[17:46:25]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test]   _bazel/bin/pkg/kv/kvserver/rangefeed/rangefeed_test_/rangefeed_test
[17:46:25]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] INFO: Elapsed time: 3.797s, Critical Path: 3.44s
[17:46:25]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
[17:46:25]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] INFO: Build completed successfully, 2 total actions
[17:46:25]W:			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] INFO: Running command line: external/bazel_tools/tools/test/test-setup.sh pkg/kv/kvserver/rangefeed/rangefeed_test_/rangefeed_test '-test.bench=.' '-test.benchtime=1x' -test.short '-test.run=-'
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] exec ${PAGER:-/usr/bin/less} "$0" || exit 1
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] Executing tests from //pkg/kv/kvserver/rangefeed:rangefeed_test
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] -----------------------------------------------------------------------------
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "parse-json-impl" with value 0
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "coldata-batch-size" with value 3240
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "span-reuse-rate" with value 78
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "COCKROACH_ENABLE_HDR_HISTOGRAMS" with value true
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "COCKROACH_BTREE_SPAN_FRONTIER_ENABLED" with value true
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "use-mux-rangefeed" with value false
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "lock-table-iters-before-seek" with value 2
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "mvcc-incremental-iter-tbi" with value false
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "mvcc-value-disable-simple-encoding" with value true
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "storage.value_blocks.enabled" with value false
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "storage.experimental.eventually_file_only_snapshots.enabled" with value false
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "kv.snapshot_receiver.excise.enabled" with value false
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "storage.ingest_split.enabled" with value false
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "storage.ingest_as_flushable.enabled" with value false
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "mvcc-max-iters-before-seek" with value 2
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "disable-checksstconflicts-range-key-masking" with value true
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] initialized metamorphic constant "small-engine-blocks" with value true
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] goos: linux
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] goarch: amd64
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] cpu: Intel(R) Xeon(R) CPU @ 3.10GHz
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeed/procType=scheduler/opType=write/numRegs=1-16         	       1	     23076 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeed/procType=scheduler/opType=write/numRegs=10-16        	       1	   5644196 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeed/procType=scheduler/opType=write/numRegs=100-16       	       1	   5428721 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeed/procType=scheduler/opType=commit/numRegs=1-16        	       1	     50962 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeed/procType=scheduler/opType=commit/numRegs=10-16       	       1	   5859412 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeed/procType=scheduler/opType=commit/numRegs=100-16      	       1	   5645789 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeed/procType=scheduler/opType=closedts/numRegs=1-16      	       1	     24290 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeed/procType=scheduler/opType=closedts/numRegs=10-16     	       1	   5170617 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeed/procType=scheduler/opType=closedts/numRegs=100-16    	       1	   5300224 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeedBudget/budget=false-16                                	       1	     13893 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] BenchmarkRangefeedBudget/budget=true-16                                 	       1	     28582 ns/op
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] I240326 00:46:25.488316 25 1@kv/kvserver/rangefeed/event_size.go:265  [-] 1  the server is terminating due to a fatal error (see the DEV channel for details)
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2  missing event variant: &{ops:[] ct:{Timestamp:{WallTime:0 Logical:0}} initRTS:false sst:<nil> sync:<nil> alloc:<nil>}
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !goroutine 25 [running]:
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !runtime/debug.Stack()
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !	GOROOT/src/runtime/debug/stack.go:24 +0x5e
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(_, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...})
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:280 +0xe7
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x2737b88, 0x3e17a00}, 0x2, 0x4, 0x0, 0x0?, {0x222b0b4, 0x1a}, {0xc000643d28, 0x1, ...})
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:109 +0x5c5
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !	github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:848
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*event).MemUsage(0xc0001e2c88?)
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/event_size.go:265 +0xc5
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.BenchmarkMemoryAccounting.func1(0xc0001e2c88)
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/event_size_test.go:571 +0x3ad
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !testing.(*B).runN(0xc0001e2c88, 0x1)
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !	GOROOT/src/testing/benchmark.go:193 +0xf8
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !testing.(*B).run1.func1()
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !	GOROOT/src/testing/benchmark.go:215 +0x4e
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !created by testing.(*B).run1 in goroutine 113
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !	GOROOT/src/testing/benchmark.go:208 +0x90
[17:46:25] :			 [Bench //pkg/kv/kvserver/rangefeed:rangefeed_test] F240326 00:46:25.488355 25 kv/kvserver/rangefeed/event_size.go:265  [-] 2 !
```

Jira issue: CRDB-37061

**Comment by michae2** [comment]
@wenyihu6 do you think this might be fallout from https://github.com/cockroachdb/cockroach/pull/120347?

**Comment by wenyihu6** [comment]
Ahh yes, looks like it. I will disable the benchmark.

**Comment by wenyihu6** [comment]
Closed by https://github.com/cockroachdb/cockroach/issues/120902.
