### ISSUE TITLE
backupccl: admin split can hang for several minutes during online restore linking phase

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#121017]
As of #119894,  admin splits during the linking phase can occasionally hang for several minutes. To reproduce, run the following online restore roachtest a couple times:
```
roachtest run restore/online/workload=true/tpce/400GB/aws/inc-count=1/nodes=4/cpus=8 --cockroach=artifacts/cockroach --user=$CLUSTER --cloud aws --count 5
```
Before #119894 landed, the online restore link phase would complete in less than a minute, but now we occasionally observe the link phase hang at 99% for about 5-10 minutes before finishing. 

When I look at the stacks, it seems we're stuck in kv sending the _first_ split in the span here:
https://github.com/cockroachdb/cockroach/blob/e1826becec9c41576a4bc6ae52abac2d8b90cf43/pkg/ccl/backupccl/restore_online.go#L230
Full stack below (from an different sha):
```
goroutine 8722 [select, 9 minutes]:
google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc01641f9e0)
  google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/transport.go:328 +0x7c
google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
  google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/transport.go:343
google.golang.org/grpc.(*csAttempt).recvMsg(0xc00826fc70, {0x62688a0, 0xc01535f880}, 0x7f5b0f7ed498?)
  google.golang.org/grpc/external/org_golang_google_grpc/stream.go:1046 +0xc9
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0x0?)
  google.golang.org/grpc/external/org_golang_google_grpc/stream.go:900 +0x1f
google.golang.org/grpc.(*clientStream).withRetry(0xc01641f7a0, 0xc002eb9f88, 0xc002eb9f78)
  google.golang.org/grpc/external/org_golang_google_grpc/stream.go:751 +0x13a
google.golang.org/grpc.(*clientStream).RecvMsg(0xc01641f7a0, {0x62688a0?, 0xc01535f880?})
  google.golang.org/grpc/external/org_golang_google_grpc/stream.go:899 +0x113
google.golang.org/grpc.invoke({0x7cb2c98?, 0xc010d5da40?}, {0x6523807?, 0x10?}, {0x63e4420, 0xc01641f680}, {0x62688a0, 0xc01535f880}, 0x1249?, {0xc0138d9e00, ...})
  google.golang.org/grpc/external/org_golang_google_grpc/call.go:73 +0xcb
github.com/cockroachdb/cockroach/pkg/rpc.NewContext.ClientInterceptor.func8({0x7cb2c98, 0xc010d5da40}, {0x6523807, 0x21}, {0x63e4420, 0xc01641f680}, {0x62688a0, 0xc01535f880}, 0xc0118dd888, 0x68bc2d8, ...)
  github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:249 +0x258
google.golang.org/grpc.(*ClientConn).Invoke(0xc0118dd888, {0x7cb2c98?, 0xc010d5da40?}, {0x6523807?, 0x0?}, {0x63e4420?, 0xc01641f680?}, {0x62688a0?, 0xc01535f880?}, {0x0, ...})
  google.golang.org/grpc/external/org_golang_google_grpc/call.go:35 +0x205
github.com/cockroachdb/cockroach/pkg/kv/kvpb.(*internalClient).Batch(0xc00c810620, {0x7cb2c98, 0xc010d5da40}, 0xc01641f680, {0x0, 0x0, 0x0})
  github.com/cockroachdb/cockroach/pkg/kv/kvpb/bazel-out/k8-opt/bin/pkg/kv/kvpb/kvpb_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvpb/api.pb.go:10213 +0xc5
github.com/cockroachdb/cockroach/pkg/rpc/nodedialer.TracingInternalClient.Batch({{0x7d1ea68?, 0xc00c810620?}}, {0x7cb2c98, 0xc010d5da40}, 0xc01641f560, {0x0, 0x0, 0x0})
  github.com/cockroachdb/cockroach/pkg/rpc/nodedialer/nodedialer.go:282 +0x20a
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).sendBatch(0xc016b6ef60, {0x7cb2c98, 0xc010d5da40}, 0x10d5da40?, {0x7ca7f30, 0xc003ec0db0}, 0xc01641f560)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:214 +0x1bc
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).SendNext(0xc016b6ef60, {0x7cb2c98, 0xc010d5da40}, 0xc01641f560)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:192 +0x87
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendToReplicas(0xc001086b08, {0x7cb2cd0, 0xc009f8cb40}, 0xc01641f440?, {0xc0013cfea0, 0xc010da0a90}, 0x0)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:2473 +0x1223
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch(0xc001086b08, {0x7cb2cd0, 0xc009f8cb40}, 0xc01641f440, {{0xc00df465e0, 0xc, 0xc}, {0xc00df46870, 0xd, 0xd}}, ...)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1946 +0x71b
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges(0xc001086b08, {0x7cb2cd0, 0xc009f8cb40}, 0xc01641f440, {{0xc00df465e0, 0xc, 0xc}, {0xc00df46870, 0xd, 0xd}}, ...)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1498 +0x36a
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send(0xc001086b08, {0x7cb2cd0, 0xc009f8cb10}, 0xc01641f440)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1114 +0x655
github.com/cockroachdb/cockroach/pkg/kv.(*CrossRangeTxnWrapperSender).Send(0xc0085fe9c8, {0x7cb2cd0, 0xc009f8cb10}, 0xc01641f440)
  github.com/cockroachdb/cockroach/pkg/kv/db.go:229 +0xa2
github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender(0xc0085fe960, {0x7cb2cd0, 0xc009f8cb10}, 0xc01641f440, {0x7c5fe00, 0xc0085fe9c8})
  github.com/cockroachdb/cockroach/pkg/kv/db.go:1124 +0xe7
github.com/cockroachdb/cockroach/pkg/kv.(*DB).send(...)
  github.com/cockroachdb/cockroach/pkg/kv/db.go:1107
github.com/cockroachdb/cockroach/pkg/kv.sendAndFill({0x7cb2cd0, 0xc009f8cb10}, 0xc0021279c0, 0xc00accf188)
  github.com/cockroachdb/cockroach/pkg/kv/db.go:956 +0x10a
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Run(0xc0085fe960, {0x7cb2cd0, 0xc009f8cb10}, 0xc00accf188)
  github.com/cockroachdb/cockroach/pkg/kv/db.go:979 +0x6a
github.com/cockroachdb/cockroach/pkg/kv.(*DB).AdminSplit(0xc0085fe960, {0x7cb2cd0, 0xc009f8cb10}, {0x611ef80, 0xc015bb4b10}, {0xc002127ae8?, 0xcf2a0e?}, {0x0, 0x0, 0x0})
  github.com/cockroachdb/cockroach/pkg/kv/db.go:678 +0xa7
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.sendSplitAt({0x7cb2c98?, 0xc001ada780?}, {0x7d10d00, 0xc0148b68e0}, {0xc00df465e0, 0xc, 0xc})
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_online.go:249 +0x173
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.sendAddRemoteSSTs.sendAddRemoteSSTWorker.func3({0x7cb2c98, 0xc001ada780})
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_online.go:200 +0x7ac
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.sendAddRemoteSSTs.Group.GoCtx.func4()
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x1f
golang.org/x/sync/errgroup.(*Group).Go.func1()
  golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 8684
  golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x96
```

Jira issue: CRDB-37028

**Comment by msbutler** [comment]
verified that the hanging goes away if you remove the add sstable calls, the hanging split goes away, which further points to the idea the split is hanging on a non-empty range

**Comment by msbutler** [comment]
The multiple minute hanging behavior is no longer apparent as of https://github.com/cockroachdb/cockroach/pull/119922, and on larger roachtests the link phase is signficantly slower because of a different [bug](https://github.com/cockroachdb/cockroach/issues/122309). Closing this out.
