### ISSUE TITLE
kvserver/rangefeed: BenchmarkRangefeed panic

### ISSUE THREAD

**Issue by herkolategan** [cockroachdb/cockroach#121429]
To reproduce:
```
./dev bench ./pkg/kv/kvserver/rangefeed --timeout=20m --filter=BenchmarkRangefeed --count=1 --bench-time=1s --bench-mem -v --stream-output --ignore-cache
```

Output:

```
$ bazel test --test_timeout=1200 pkg/kv/kvserver/rangefeed:all --nocache_test_results --test_arg -test.run=- --test_arg -test.bench=BenchmarkRangefeed --test_sharding_strategy=disabled --test_arg -test.v --test_arg -test.benchtime=1s --test_arg -test.benchmem --crdb_test_off --test_env COCKROACH_TEST_FIXTURES_DIR=/Users/herko/Library/Caches/crdb-test-fixtures --sandbox_writable_path=/Users/herko/Library/Caches/crdb-test-fixtures --test_output streamed
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 415a7bb8-d8ed-46c0-963b-efc348ece4aa
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Analyzed 2 targets (845 packages loaded, 25402 targets configured).
INFO: Found 1 target and 1 test target...
goos: darwin
goarch: arm64
BenchmarkRangefeed
BenchmarkRangefeed/procType=legacy/opType=write/numRegs=1
BenchmarkRangefeed/procType=legacy/opType=write/numRegs=1-10         	 1467762	       778.1 ns/op	     429 B/op	       7 allocs/op
BenchmarkRangefeed/procType=legacy/opType=write/numRegs=10
BenchmarkRangefeed/procType=legacy/opType=write/numRegs=10-10        	  227383	      5440 ns/op	     512 B/op	       8 allocs/op
BenchmarkRangefeed/procType=legacy/opType=write/numRegs=100
BenchmarkRangefeed/procType=legacy/opType=write/numRegs=100-10       	   20037	     85438 ns/op	     514 B/op	       9 allocs/op
BenchmarkRangefeed/procType=legacy/opType=commit/numRegs=1
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x10629f904]

goroutine 685 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0x1400204c060?, {0x106f15200, 0x1401c3df080})
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:230 +0x68
panic({0x106bbf8c0?, 0x107ffd8d0?})
	GOROOT/src/runtime/panic.go:770 +0x124
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*txnPushAttempt).pushOldTxns(0x140005e8f30, {0x106f15200, 0x1401c3df080})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/task.go:266 +0x34
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*txnPushAttempt).Run(0x1400050b718?, {0x106f15200, 0x1401c3df080})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/task.go:254 +0x54
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x128
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 654
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x31c
I240331 10:53:16.122162 1 (gostd) testmain.go:207  [-] 1  Test //pkg/kv/kvserver/rangefeed:rangefeed_test exited with error code 2
```

**Comment by kvoli** [comment]
This may be a test only issue, the `TxnPusher` isn't getting initialized w/ the legacy rangefeed processor for benchmarking. I'll try out an older SHA to see if this is a recent problem.

```
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*LegacyProcessor).Start(0x140000f21a0, 0x1400038f320, 0x0)
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:365 +0x1ec
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.newTestProcessor({0x1045e0d40, 0x140001c6c88}, {0x14000571d88, 0x5, 0x0?})
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor_test.go:432 +0x620
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.runBenchmarkRangefeed(0x140001c6c88, {0x0, {0x103b962df, 0x5}, 0x1, 0x7fffffffffffffff})
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/bench_test.go:97 +0x240
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.BenchmarkRangefeed.func1(0x140001c6c88?)
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/bench_test.go:54 +0x5c
testing.(*B).runN(0x140001c6c88, 0x1)
        GOROOT/src/testing/benchmark.go:193 +0x130
testing.(*B).run1.func1()
        GOROOT/src/testing/benchmark.go:215 +0x50
created by testing.(*B).run1 in goroutine 50
        GOROOT/src/testing/benchmark.go:208 +0x90
```

**Comment by kvoli** [comment]
No nil ptr deref on 23.2 (b9ed369c48f0ab409f2ea5234152469255a6bab3).

**Comment by kvoli** [comment]
Bisected to 8eb7ca994b6e37d28e629364f036ba1828a16deb.

**Comment by kvoli** [comment]
`TxnPusher` is always nil in these benchmarks tests. The regression came from `oldTxns` here no longer being empty:

https://github.com/cockroachdb/cockroach/blob/35e57249b709a423d1299e76f24d9cbc30dcdd94/pkg/kv/kvserver/rangefeed/processor.go#L493-L493

**Comment by kvoli** [comment]
This is a test only issue introduced in 6fcbdfcd, on a prior good version (pre-legacy rangefeed removal) we avoid setting the push txn interval unless the txn pusher is non-nil:

https://github.com/cockroachdb/cockroach/blob/9f20cd9f92a2a034ae1eb1cb15e7a28bb1016139/pkg/kv/kvserver/rangefeed/processor.go#L112-L119

On master, post-revert (https://github.com/cockroachdb/cockroach/commit/8eb7ca994b6e37d28e629364f036ba1828a16deb) and re-introduction of the legacy rangefeed scheduler, we always set the default:

https://github.com/cockroachdb/cockroach/blob/35e57249b709a423d1299e76f24d9cbc30dcdd94/pkg/kv/kvserver/rangefeed/processor.go#L125-L130

Removing the release blocker and marking as a testing issue. I'll open a patch.
