### ISSUE TITLE
changefeedccl: transaction restarts do not respect session-based filtering

### ISSUE THREAD

**Issue by andyyang890** [cockroachdb/cockroach#121589]
In performance testing using TPCC, it was observed that transaction retries were correlated with changefeed events escaping session-based filtering. Replacing the `txn.OmitInRangefeeds` line in the snippet below with `true` seems to resolve this issue, leading to suspicions that transactions that need to retry due to a `TransactionAbortedError` are somehow dropping the `OmitInRangefeeds` flag:
https://github.com/cockroachdb/cockroach/blob/e53cc10829fa7740de7b40bfed5e5496e8bc4e26/pkg/kv/kvpb/data.go#L63-L75

Further investigation is needed to determine the root cause.

Jira issue: CRDB-37355

Epic CRDB-34240

**Comment by andyyang890** [comment]
Noting for the record that I added this log line and found two types of stack traces where the flag is being overwritten from `true` to `false` via `(*roachpb.Transaction).Update`:

```
diff --git a/pkg/roachpb/data.go b/pkg/roachpb/data.go
index 3d2880a6ce2..7bf3bea3443 100644
--- a/pkg/roachpb/data.go
+++ b/pkg/roachpb/data.go
@@ -20,6 +20,7 @@ import (
        "hash/crc32"
        "math"
        "math/rand"
+       "runtime/debug"
        "sort"
        "strconv"
        "sync"
@@ -1376,6 +1377,10 @@ func (t *Transaction) Update(o *Transaction) {
        // function.
        t.AdmissionPriority = o.AdmissionPriority
        // OmitInRangefeeds doesn't change.
+       if t.OmitInRangefeeds && !o.OmitInRangefeeds {
+               stack := string(debug.Stack())
+               log.Warningf(ctx, "OmitInRangefeeds is overwritten from true to false. stack: %s", stack)
+       }
        t.OmitInRangefeeds = o.OmitInRangefeeds
 }
```

Type 1:
  ```
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921  OmitInRangefeeds is overwritten from true to false. stack: ‹goroutine 332147 [running]:›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹runtime/debug.Stack()›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      GOROOT/src/runtime/debug/stack.go:24 +0x5e›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/roachpb.(*Transaction).Update(0xc08582ed80, 0xc08582eea0)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/roachpb/pkg/roachpb/data.go:1381 +0xbf9›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch({_, _}, {_, _}, {_, _}, {_, _}, _, 0xc0729b8fc0, ...)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:334 +0xd7d›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper(_, {_, _}, {_, _}, {_, _}, _, _, 0xc012589110, ...)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:736 +0x1d6›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes(_, {_, _}, {_, _}, {_, _}, _, _, 0xc012589110, ...)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:703 +0x359›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatch(_, {_, _}, {_, _}, _, _, _, {{0x17c2e5b1f861d488, 0x0}, ...})›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:472 +0x7d0›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateProposal(0xc00f08bb08, {0x7d01790, 0xc07955e4e0}, {0xc155beb440, 0x8}, 0xc0729b8fc0, 0xc012589110, 0xc04f417498, {{0x17c2e5b1f861d488, 0x0}, ...})›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:956 +0x1a7›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).requestToProposal(0xc00f08bb08, {0x7d01790, 0xc07955e4e0}, {0xc155beb440, 0x8}, 0xc0729b8fc0, 0x0?, 0xc04f417498, {{0x17c2e5b1f861d488, 0x0}, ...})›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:1053 +0x86›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose(0xc00f08bb08, {0x7d01790, 0xc07955e4e0}, 0xc0729b8fc0, 0xc012589110, 0xc04f417498, {{0x17c2e5b1f861d488, 0x0}, {0x17c2e5b1db998510, 0x0}}, ...)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:124 +0x16c›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch(0xc00f08bb08, {0x7d01790, 0xc0c8fe2e10}, 0xc0729b8fc0, 0xc012589110)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:193 +0x6dd›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries(0xc00f08bb08, {0x7d01790, 0xc0c8fe2e10}, 0xc0729b8fc0, 0x68eb150)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:512 +0x3c3›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes(0xc00f08bb08, {0x7d01790?, 0xc0c8fe2de0?}, 0xc0729b8fc0)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:186 +0x6e5›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes(0xc00c712008, {0x7d01790?, 0xc0c8fe2db0?}, 0xc0729b8fc0)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:193 +0x83c›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes(0xc001715780, {0x7d01790, 0xc0c8fe2db0}, 0xc0729b8fc0)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:203 +0x7e›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc00376cc08, {0x7d01790?, 0xc0c8fe2d80?}, {0xc0037f3c20?}, 0xc0729b8fc0)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/server/node.go:1431 +0x5b9›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc00376cc08, {0x7d01790, 0xc0c8fe2bd0}, 0xc0729b8fc0)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/server/node.go:1625 +0x2da›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvpb._Internal_Batch_Handler.func1({0x7d01790?, 0xc0c8fe2bd0?}, {0x6414a40?, 0xc0729b8fc0?})›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvpb/bazel-out/k8-opt/bin/pkg/kv/kvpb/kvpb_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvpb/api.pb.go:10584 +0xcb›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.ServerInterceptor.func12({0x7d01790, 0xc0c8fe2bd0}, {0x6414a40, 0xc0729b8fc0}, 0xc079c10720, 0xc03f1b2228)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:97 +0x4b2›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹google.golang.org/grpc.getChainUnaryHandler.func1({0x7d01790, 0xc0c8fe2bd0}, {0x6414a40, 0xc0729b8fc0})›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1163 +0xb2›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3({0x7d01790, 0xc0c8fe2bd0}, {0x6414a40, 0xc0729b8fc0}, 0xc079c10720?, 0xc0bcf31040)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:169 +0x76›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹google.golang.org/grpc.getChainUnaryHandler.func1({0x7d01790, 0xc0c8fe2bd0}, {0x6414a40, 0xc0729b8fc0})›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1163 +0xb2›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor({0xc00211e000?, {{0x46e4e5?}, {0x7d40920?, 0xc003704fc0?}}}, {0x7d01790, 0xc0c8fe2bd0}, {0x6414a40, 0xc0729b8fc0}, 0xc079c10720, 0xc0bcf30fc0)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:95 +0x1e4›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹google.golang.org/grpc.getChainUnaryHandler.func1({0x7d01790, 0xc0c8fe2bd0}, {0x6414a40, 0xc0729b8fc0})›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1163 +0xb2›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1({0x7d01790?, 0xc0c8fe2bd0?})›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:136 +0x36›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc001e2c2d0, {0x7d01790, 0xc0c8fe2bd0}, {0xc0bcf30f80?, 0xc04f419978?}, 0xc04f419970)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:336 +0xcb›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1({0x7d01790?, 0xc0c8fe2bd0?}, {0x6414a40?, 0xc0729b8fc0?}, 0xc079c10720?, 0xc03f1b2228?)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:134 +0x8f›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1({0x7d01790, 0xc0c8fe2bd0}, {0x6414a40, 0xc0729b8fc0}, 0xc079c10720, 0x70?)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1154 +0x85›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹github.com/cockroachdb/cockroach/pkg/kv/kvpb._Internal_Batch_Handler({0x63e53c0, 0xc00376cc08}, {0x7d01790, 0xc0c8fe2bd0}, 0xc09ebd7b90, 0xc001c5b8e0)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvpb/bazel-out/k8-opt/bin/pkg/kv/kvpb/kvpb_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvpb/api.pb.go:10586 +0x143›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹google.golang.org/grpc.(*Server).processUnaryRPC(0xc0035cc780, {0x7d56e40, 0xc011f6cea0}, 0xc070d03b00, 0xc001764780, 0xb8d1040, 0x0)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1336 +0xd16›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹google.golang.org/grpc.(*Server).handleStream(0xc0035cc780, {0x7d56e40, 0xc011f6cea0}, 0xc070d03b00, 0x0)›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1704 +0x9da›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹google.golang.org/grpc.(*Server).serveStreams.func1.2()›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      google.golang.org/grpc/external/org_golang_google_grpc/server.go:965 +0x8d›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 2045›
W240403 22:29:22.443090 332147 roachpb/data.go:1382 ⋮ [-] 88921 +‹      google.golang.org/grpc/external/org_golang_google_grpc/server.go:963 +0x226›
  ```

Type 2:
  ```
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929  OmitInRangefeeds is overwritten from true to false. stack: ‹goroutine 328421 [running]:›
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929 +‹runtime/debug.Stack()›
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929 +‹      GOROOT/src/runtime/debug/stack.go:24 +0x5e›
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929 +‹github.com/cockroachdb/cockroach/pkg/roachpb.(*Transaction).Update(0xc072dcb8c0, 0xc05ffa64b8)›
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929 +‹      github.com/cockroachdb/cockroach/pkg/roachpb/pkg/roachpb/data.go:1381 +0xbf9›
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929 +‹github.com/cockroachdb/cockroach/pkg/kv/kvserver/txnwait.(*Queue).startQueryPusherTxn.func1({0x7d01790, 0xc07a922c90})›
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929 +‹      github.com/cockroachdb/cockroach/pkg/kv/kvserver/txnwait/queue.go:929 +0x532›
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929 +‹github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()›
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929 +‹      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x13a›
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929 +‹created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 325092›
W240403 22:29:22.445178 328421 roachpb/data.go:1382 ⋮ [-] 88929 +‹      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x3fe›
  ```

@miraradeva has been helping me investigate (thanks!) and she believes it stems from the fact that the transaction record does not store the `OmitInRangefeeds` flag. We'll continue to investigate.
