### ISSUE TITLE
storage/backupccl: DownloadSpan call hung for 4+ minutes

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#121805]
Running `./dev test pkg/ccl/backupccl/backuprand --stress` on my gceworker on master (sha `2bd61ba8700c0ada35d8d6dd24546e2a36999900`) failed on a test run time out. A sampling of the stack trace suggests several `downloadSpan` calls waiting for the main db lock.

```
goroutine 5964 [sync.Cond.Wait, 4 minutes]:
sync.runtime_notifyListWait(0xc003b941f8, 0x7)
  GOROOT/src/runtime/sema.go:569 +0x159
sync.(*Cond).Wait(0xc003b94008?)
  GOROOT/src/sync/cond.go:70 +0x85
github.com/cockroachdb/pebble.(*DB).downloadSpan.func5(0xc003b94008, 0xc00624bc18?, 0xc00624bc00)
  github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:1998 +0x130
github.com/cockroachdb/pebble.(*DB).downloadSpan(0xc003b94008, {0x7e39760, 0xc009883bd0}, {{0xc008c4bc88, 0x3, 0x8}, {0xc008c4bc90, 0x3, 0x8}, 0x1})
  github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:2000 +0x328
github.com/cockroachdb/pebble.(*DB).Download(0xc003b94008, {0x7e39798?, 0xc0077b6ae0?}, {0xc008aafdf0, 0x1, 0x4?})
  github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:2034 +0x210
github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).Download(0xc00144b688, {0x7e39760?, 0xc000053ea0?}, {{0xc008c4bc88, 0x3, 0x8}, {0xc008c4bc90, 0x3, 0x8}}, 0x1)
  github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1024 +0x1e5
github.com/cockroachdb/cockroach/pkg/server.downloadSpans.func1({0x7e39760, 0xc000053ea0}, 0xf0f00c005372008?)
  github.com/cockroachdb/cockroach/pkg/server/span_download.go:133 +0x12a
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.func1({0x7e39760?, 0xc000053ea0?})
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:177 +0x25
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.Group.GoCtx.func2()
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x1f
golang.org/x/sync/errgroup.(*Group).Go.func1()
  golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 4319
  golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x96
```

another stack trace:

```
goroutine 5955 [sync.Mutex.Lock, 4 minutes]:
sync.runtime_SemacquireMutex(0x0?, 0x2?, 0x4f4729280c2de?)
  GOROOT/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc003b94120)
  GOROOT/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
  GOROOT/src/sync/mutex.go:90
github.com/cockroachdb/pebble.(*DB).downloadSpan.func5(0xc003b94008, 0xc00745dc18, 0xc00745dc00)
  github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:1982 +0x65
github.com/cockroachdb/pebble.(*DB).downloadSpan(0xc003b94008, {0x7e39760, 0xc009883950}, {{0xc008c4bad8, 0x2, 0x8}, {0xc008c4bae0, 0x2, 0x8}, 0x1})
  github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:2000 +0x328
github.com/cockroachdb/pebble.(*DB).Download(0xc003b94008, {0x7e39798?, 0xc0077b67b0?}, {0xc00745ddf0, 0x1, 0xc0000e8008?})
  github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:2034 +0x210
github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).Download(0xc00144b688, {0x7e39760?, 0xc000053ea0?}, {{0xc008c4bad8, 0x2, 0x8}, {0xc008c4bae0, 0x2, 0x8}}, 0x1)
  github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1024 +0x1e5
github.com/cockroachdb/cockroach/pkg/server.downloadSpans.func1({0x7e39760, 0xc000053ea0}, 0xf0f00c00584c008?)
  github.com/cockroachdb/cockroach/pkg/server/span_download.go:133 +0x12a
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.func1({0x7e39760?, 0xc000053ea0?})
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:177 +0x25
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.Group.GoCtx.func2()
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x1f
golang.org/x/sync/errgroup.(*Group).Go.func1()
  golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 4319
  golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x96
```

**Comment by msbutler** [comment]
fwiw, i reran this test because we're still seeing empty virtual ssts https://github.com/cockroachdb/cockroach/issues/121751

**Comment by msbutler** [comment]
i'll try running this test with the race detector to get a more descriptive message.

**Comment by itsbilal** [comment]
This sounds like a Cockroach version of https://github.com/cockroachdb/pebble/issues/3470

**Comment by itsbilal** [comment]
Good thing is the fix for that is already in pebble and is just awaiting a pebble bump in cockroach: https://github.com/cockroachdb/pebble/pull/3483

**Comment by msbutler** [comment]
ah sweet, glad it wasn't a new bug!

**Comment by RaduBerinde** [comment]
I will close when I bump the dep later today.

**Comment by msbutler** [comment]
closed via https://github.com/cockroachdb/cockroach/pull/121869
