### ISSUE TITLE
queries: TestCacheAutoRefresh times out under stress on 23.2 release branch

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#122127]
I'm trying to backport https://github.com/cockroachdb/cockroach/pull/121855 and I'm hitting a timeout in `TestCacheAutoRefresh` under stress.  The run can be found [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/14777452?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true).

Should this test be disabled under stress?  Or the timeout lengthened? 

Jira issue: CRDB-37717

**Comment by DrewKimball** [comment]
I don't think this test is doing anything particularly expensive, at least, beyond other tests. Looks like the slowness was in cluster setup:
```
initialized metamorphic constant "kv-batch-size" with value 1
```
```
goroutine 77812 [runnable]:
github.com/dustin/go-humanize.Ftoa(0x3ff0000000000000?)
  github.com/dustin/go-humanize/external/com_github_dustin_go_humanize/ftoa.go:38 +0x9d
github.com/cockroachdb/cockroach/pkg/kv/kvpb.humanizeCount(0x1)
  github.com/cockroachdb/cockroach/pkg/kv/kvpb/pkg/kv/kvpb/api.go:2114 +0x68
github.com/cockroachdb/cockroach/pkg/kv/kvpb.(*ScanStats).SafeFormat(0xc0023455e0, {0xa8f8ff0, 0xc001d1b3b0}, 0x1?)
  github.com/cockroachdb/cockroach/pkg/kv/kvpb/pkg/kv/kvpb/api.go:2126 +0x178
github.com/cockroachdb/redact/internal/rfmt.(*pp).handleMethods(0xc001d1b3b0, 0x76)
  github.com/cockroachdb/redact/internal/rfmt/external/com_github_cockroachdb_redact/internal/rfmt/print.go:630 +0x3d1
github.com/cockroachdb/redact/internal/rfmt.(*pp).printArg(0xc001d1b3b0, {0x7a3c220, 0xc0023455e0}, 0x76)
  github.com/cockroachdb/redact/internal/rfmt/external/com_github_cockroachdb_redact/internal/rfmt/print.go:810 +0x182a
github.com/cockroachdb/redact/internal/rfmt.(*pp).doPrintf(0xc001d1b3b0, {0x7c0c3f9, 0x2}, {0xc004127190?, 0x1, 0x1})
  github.com/cockroachdb/redact/internal/rfmt/external/com_github_cockroachdb_redact/internal/rfmt/print.go:1144 +0x37a
github.com/cockroachdb/redact/internal/rfmt.Sprintf({0x7c0c3f9, 0x2}, {0xc004127190, 0x1, 0x1})
  github.com/cockroachdb/redact/internal/rfmt/external/com_github_cockroachdb_redact/internal/rfmt/print.go:227 +0x5d
github.com/cockroachdb/redact.Sprintf(...)
  github.com/cockroachdb/redact/external/com_github_cockroachdb_redact/markers_print.go:41
github.com/cockroachdb/cockroach/pkg/util/tracing.(*spanInner).Recordf(0xc004afd808, {0x7c0c3f9, 0x2}, {0xc004127190, 0x1, 0x1})
  github.com/cockroachdb/cockroach/pkg/util/tracing/span_inner.go:285 +0xa5
github.com/cockroachdb/cockroach/pkg/util/tracing.(*spanInner).RecordStructured(0xc004afd808, {0xa8d5d50?, 0xc0023455e0})
  github.com/cockroachdb/cockroach/pkg/util/tracing/span_inner.go:271 +0x165
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).RecordStructured(0xc004afd800, {0xa8d5d50, 0xc0023455e0})
  github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:483 +0x5b
github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch.func2()
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:244 +0xb3
github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch({_, _}, {_, _}, {_, _}, {_, _}, _, 0xc003495d40, ...)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:443 +0x2325
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeReadOnlyBatchWithServersideRefreshes(_, {_, _}, {_, _}, {_, _}, _, _, 0xc0055725c8, ...)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go:463 +0x605
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeReadOnlyBatch(0xc001dac880, {0xa89f668, 0xc00a368240}, 0xc003495d40, 0xc00346c3c0)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go:125 +0x9a5
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries(0xc001dac880, {0xa89f668, 0xc00a368240}, 0xc003495d40, 0x7f5f528)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:511 +0x547
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes(0xc001dac880, {0xa89f668, 0xc00a637e30}, 0xc003495d40)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:185 +0x589
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes(0xc0096af500, {0xa89f668, 0xc00a637ad0}, 0xc003495d40)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:193 +0xd32
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes(0xc005574428?, {0xa89f668, 0xc00a637ad0}, 0xc003495d40)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:202 +0x177
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc0057e8c00, {0xa89f668, 0xc00a637a70}, {0xc00440ca20?}, 0xc003495d40)
  github.com/cockroachdb/cockroach/pkg/server/node.go:1328 +0x893
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc0057e8c00, {0xa89f668, 0xc00a637a10}, 0xc003495d40)
  github.com/cockroachdb/cockroach/pkg/server/node.go:1462 +0x465
github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func1({0xa89f668, 0xc00a637a10}, {0x7baa4e0?, 0xc003495d40})
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:704 +0x77
github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.ServerInterceptor.func12({0xa89f668, 0xc00a637a10}, {0x7baa4e0, 0xc003495d40}, 0xc0096a0b60, 0xc006068db0)
  github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:97 +0x62c
github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.chainUnaryServerInterceptors.bindUnaryServerInterceptorToHandler.func4({0xa89f668, 0xc00a637a10}, {0x7baa4e0, 0xc003495d40})
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:815 +0x89
github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3({0xa89f668, 0xc00a637a10}, {0x7baa4e0, 0xc003495d40}, 0xc0096a0b60, 0xc0096a0b80)
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:169 +0xf1
github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.chainUnaryServerInterceptors.bindUnaryServerInterceptorToHandler.func4({0xa89f668, 0xc00a637a10}, {0x7baa4e0, 0xc003495d40})
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:815 +0x89
github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor({0xc001bec000?, {{0x48d1b5?}, {0xa8d6df0?, 0xc016d52840?}}}, {0xa89f668, 0xc00a637a10}, {0x7baa4e0, 0xc003495d40}, 0xc0096a0b60, 0xc0096a0ba0)
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:105 +0x2f4
github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.chainUnaryServerInterceptors.bindUnaryServerInterceptorToHandler.func4({0xa89f668, 0xc00a637a10}, {0x7baa4e0, 0xc003495d40})
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:815 +0x89
github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1({0xa89f668, 0xc00a637a10})
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:136 +0x6b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc01097eaa0, {0xa89f668?, 0xc00a637a10}, {0xaf?, 0x0?}, 0xc0055756f0)
  github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:336 +0x186
github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1({0xa89f668, 0xc00a637a10}, {0x7baa4e0?, 0xc003495d40}, 0xc0096a0b60, 0xc0096a0bc0)
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:134 +0x15c
github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.chainUnaryServerInterceptors.bindUnaryServerInterceptorToHandler.func4({0xa89f668, 0xc00a637a10}, {0x7baa4e0, 0xc003495d40})
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:815 +0x89
github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func2({0xa89f668, 0xc00a637a10}, {0xc00382b760?, 0x48cd09?}, {0x7baa4e0, 0xc003495d40}, {0x7a83880?, 0xc000be5600}, 0xc005575908?, {0x0, ...})
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:714 +0x7b
github.com/cockroachdb/cockroach/pkg/rpc.NewContext.ClientInterceptor.func8({0xa89f668, 0xc00a637a10}, {0x7c9232b, 0x21}, {0x7baa4e0, 0xc003495d40}, {0x7a83880, 0xc000be5600}, 0x48cd09?, 0xc013e82010, ...)
  github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:228 +0x583
github.com/cockroachdb/cockroach/pkg/rpc.getChainUnaryInvoker.func1({0xa89f668, 0xc00a637a10}, {0x7c9232b, 0x21}, {0x7baa4e0, 0xc003495d40}, {0x7a83880, 0xc000be5600}, 0x0?, {0x0, ...})
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:899 +0x19a
github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func3({0xa89f668, 0xc00a6375f0}, 0xc0034959e0, {0x0, 0x0, 0x0})
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:784 +0x453
github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.Batch(...)
  github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:907
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).sendBatch(0xc007944060, {0xa89f668, 0xc00a6375f0}, 0x0?, {0xa892060, 0xc0076e4960?}, 0xc0034959e0)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:211 +0x2a3
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).SendNext(0xc007944060, {0xa89f668, 0xc00a6375f0}, 0x1?)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:189 +0x145
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.raceTransport.SendNext({{0xa8d7840?, 0xc007944060?}}, {0xa89f668, 0xc00a6375f0}, 0xc0034959e0)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport_race.go:76 +0x3b7
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendToReplicas(0xc005c71b80, {0xa89f668, 0xc00a6375f0}, 0xc003495680, {0xc01934eba0, 0xc002a37a00, 0xc002a37a70, 0x0, 0x0}, 0x0)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:2423 +0x1dd3
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch(0xc005c71b80, {0xa89f668?, 0xc00a6375f0}, 0xc003495680, {{0xc0058051f9, 0x1, 0x7}, {0xc0058051f9, 0x2, 0x7}}, ...)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1920 +0x9ac
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges(0xc005c71b80, {0xa89f668?, 0xc00a6375f0}, 0xc003495680, {{0xc0058051f9, 0x1, 0x7}, {0xc0058051f9, 0x2, 0x7}}, ...)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1488 +0x1158
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send(0xc005c71b80, {0xa89f668, 0xc00a637590}, 0xc003495680)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1104 +0xa50
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnLockGatekeeper).SendLocked(0xc00563d038, {0xa89f668, 0xc00a637590}, 0xc003495680)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go:82 +0x26f
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnMetricRecorder).SendLocked(0xc00563d000, {0xa89f668, 0xc00a637590}, 0xc005578150?)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go:47 +0x1e9
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts(0xc00563cf20, {0xa89f668, 0xc00a637590}, 0xc003495680, 0x5)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:222 +0x2d3
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked(0xc00563cf20, {0xa89f668, 0xc00a637590}, 0xc003495680)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:150 +0x1d9
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked(0xc00563cee0, {0xa89f668, 0xc00a637590}, 0xc003495680)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:149 +0x95f
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked(0xc00563cdb0, {0xa89f668, 0xc00a637590}, 0xa?)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go:295 +0x245
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked(0xc00563cd90, {0xa89f668, 0xc00a637590}, 0xc003495680)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:114 +0x39e
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked(0xc00563cce0, {0xa89f668, 0xc00a637590}, 0xc003495680)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:246 +0x7d4
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send(0xc00563cb00, {0xa89f668, 0xc00a637500}, 0xc003495680)
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:533 +0xa14
github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender(0xc01097f540, {0xa89f668, 0xc00a637500}, 0xc003495680, {0x7fe5c156d2c8, 0xc00563cb00})
  github.com/cockroachdb/cockroach/pkg/kv/db.go:1114 +0x182
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send(0xc0031c2e70, {0xa89f668, 0xc00a637500}, 0xc003495680)
  github.com/cockroachdb/cockroach/pkg/kv/txn.go:1244 +0x2d5
github.com/cockroachdb/cockroach/pkg/kv.sendAndFill({0xa89f668, 0xc00a637500}, 0xc0055792a8, 0xc00563d080)
  github.com/cockroachdb/cockroach/pkg/kv/db.go:946 +0x270
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Run(0xc0031c2e70, {0xa89f668, 0xc00a637500}, 0xffffffffffffff01?)
  github.com/cockroachdb/cockroach/pkg/kv/txn.go:784 +0xa8
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Get(0xc0031c2e70, {0xa89f668, 0xc00a637500}, {0x798d0c0, 0xc008e535f0})
  github.com/cockroachdb/cockroach/pkg/kv/txn.go:492 +0x1aa
github.com/cockroachdb/cockroach/pkg/kv/kvserver.conditionalGetDescValueFromDB({0xa89f668, 0xc00a637500}, 0xc00a636bd0?, {0xc0083d9a58, 0x1, 0x8}, 0x0, 0xc005579dd0)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_command.go:3334 +0x125
github.com/cockroachdb/cockroach/pkg/kv/kvserver.execChangeReplicasTxn.func2({0xa89f668, 0xc00a636bd0}, 0xc0031c2e70)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_command.go:2355 +0x251
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec(0xc0031c2e70, {0xa89f668, 0xc00a636bd0}, 0xc005579e08)
  github.com/cockroachdb/cockroach/pkg/kv/txn.go:1032 +0xa2
github.com/cockroachdb/cockroach/pkg/kv.runTxn({0xa89f668, 0xc00a636bd0}, 0xc00a636bd0?, 0xa?)
  github.com/cockroachdb/cockroach/pkg/kv/db.go:1079 +0x65
github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl(0xc01097f540, {0xa89f668, 0xc00a636bd0}, 0xd8937f4?, 0x0?, 0x0?, 0x4?)
  github.com/cockroachdb/cockroach/pkg/kv/db.go:1042 +0xed
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn(...)
  github.com/cockroachdb/cockroach/pkg/kv/db.go:1017
github.com/cockroachdb/cockroach/pkg/kv/kvserver.execChangeReplicasTxn({0xa89f668?, 0xc00a636bd0}, 0xc003404360, 0xc00f5e1180, {0x7c5380a, 0x16}, {0xc009506280, 0x46}, {0xc005579fa4, 0x1, ...}, ...)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_command.go:2337 +0x3f5
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).initializeRaftLearners(0xc001dac880, {0xa89f668?, 0xc00a636bd0}, 0xc00f5e1180, 0x0?, 0x0?, 0x0?, {0x7c5380a, 0x16}, {0xc009506280, ...}, ...)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_command.go:1795 +0x875
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).changeReplicasImpl(0xc001dac880, {0xa89f668, 0xc00a636bd0}, 0x0?, 0x0?, 0x0?, 0xa89f668?, {0x7c5380a, 0x16}, {0xc009506280, ...}, ...)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_command.go:1109 +0x87d
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicateQueue).changeReplicas(...)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicate_queue.go:1114
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicateQueue).applyChange(0xc0109a4be0?, {0xa89f668, 0xc00a636bd0}, {0x4, {0xa8ebfb0, 0xc001dac880}, {0xa872d28, 0xc0047d26e0}, {0x1, 0x1, ...}}, ...)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicate_queue.go:815 +0x20e
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicateQueue).processOneChange(0xc0014f0780, {0xa89f668, 0xc00a636bd0}, 0x7c31668?, 0xf?, 0xc00557ae80?, 0x1?, 0xd0?, 0x0)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicate_queue.go:916 +0x35c
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicateQueue).processOneChangeWithTracing(0xc0014f0780, {0xa89f6d8, 0xc003c49d50}, 0xc001dac880, 0x4000000000000000?, 0x5?)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicate_queue.go:759 +0x2b9
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicateQueue).process(0xc0014f0780, {0xa89f6d8, 0xc003c49d50}, 0xc001dac880, {0x7fe57504fc18, 0xc00f5db2c0})
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicate_queue.go:668 +0x450
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica.func1({0xa89f6d8, 0xc003c49d50})
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:1036 +0x2d6
github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout({0xa89f668, 0xc00a636b10}, {0xc0082954a0, 0x22}, 0xdf8475800, 0xc00557b9c0)
  github.com/cockroachdb/cockroach/pkg/util/timeutil/timeout.go:29 +0x12e
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica(0xc0096806e0, {0xa89f668, 0xc00a636a80}, {0xa8e5c00, 0xc001dac880})
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:995 +0x71f
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).DrainQueue(0xc0096806e0, 0xc005041b48?)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:1406 +0x217
github.com/cockroachdb/cockroach/pkg/kv/kvserver.forceScanAndProcess({0xa89f588, 0xedbb7c0}, 0xc0096af500, 0xc0096806e0)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue_helpers_testutil.go:42 +0x17e
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).ForceReplicationScanAndProcess(...)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue_helpers_testutil.go:55
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForFullReplication.func2(0xc0096af500)
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1448 +0x12b
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1(0x7487420?, 0xc00120f4d0?)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149 +0x58
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range(0xc0049d5a20, 0xc00557bf68)
  github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:358 +0x184
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores(0xc0049d59e0, 0xc005042088)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:148 +0x8e
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForFullReplication(0xc003e1c000)
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1440 +0x4ce
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start(0xc003e1c000, {0xa8d4540, 0xc00262e680?})
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:449 +0x9f8
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartCluster({_, _}, _, {{{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...})
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_cluster_shim.go:288 +0x13e
github.com/cockroachdb/cockroach/pkg/sql/stats.TestCacheAutoRefresh(0xc00262e680)
  github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache_test.go:439 +0x15a
testing.tRunner(0xc00262e680, 0x7f5d9c8)
  GOROOT/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
  GOROOT/src/testing/testing.go:1648 +0x846
```
