### ISSUE TITLE
TestMRSystemDatabase timed out under stress race

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#122363]
See flake[ here](https://teamcity.cockroachdb.com/viewLog.html?buildId=14822879&buildTypeId=Cockroach_BazelExtendedCi). Goroutine dump suggests we're hanging in lock processing. 
```
goroutine 26 [chan send]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).lockProcessing(...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:556
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).DrainQueue(0xc005d28b00, {0xdb07e40, 0x12f72b60}, 0xc0031fa1e0)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:1447 +0xe5
github.com/cockroachdb/cockroach/pkg/kv/kvserver.forceScanAndProcess({0xdb07e40, 0x12f72b60}, 0xc002a15808, 0xc005d28b00)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue_helpers_testutil.go:42 +0x188
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).ForceReplicationScanAndProcess(...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue_helpers_testutil.go:55
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForFullReplication.func2(0xc002a15808)
	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1451 +0x12b
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1(0x93c75a0?, 0xc002a15808)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:150 +0x58
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range(0xc0022f69c8, 0xc014993718)
	github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:385 +0x19d
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores(0xc0022f6990, 0xc00a649930)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149 +0x8e
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForFullReplication(0xc003192708)
	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1443 +0x5ae
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start(0xc003192708, {0xdb46e50, 0xc003fe01a0})
	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:456 +0xa38
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster({_, _}, _, {{{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:238 +0x92
github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl/multiregionccltestutils.TestingCreateMultiRegionClusterWithRegionList({_, _}, {_, _, _}, _, {{0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go:132 +0x295
github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl/multiregionccltestutils.TestingCreateMultiRegionCluster({_, _}, _, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go:89 +0x1f0
github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl.TestMrSystemDatabase(0xc003fe01a0)
	github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl/multiregion_system_table_test.go:51 +0x25c
testing.tRunner(0xc003fe01a0, 0xa26df60)
	GOROOT/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 1
	GOROOT/src/testing/testing.go:1742 +0x826
```

Jira issue: CRDB-37834

**Comment by arulajmani** [comment]
Looks like overload. Lots of log lines of the form:

```
I240412 23:18:22.563234 737 kv/kvserver/store_raft.go:699 â‹® [T1,Vsystem,n1,s1,r4/1:â€¹/System{/tsd-tse}â€º,raft] 340  raft ready handling: 0.53s [append=0.00s, apply=0.41s, , other=0.12s], wrote [append-batch=49 B, apply=323 KiB (1)] pebble stats: [commit-wait 552ns sem 19.78Âµs]; node might be overloaded
```

We can skip this under stress race.
