### ISSUE TITLE
storage: panic in HandleSnapshot

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12249]
Found in: https://teamcity.cockroachdb.com/viewLog.html?buildId=86361&buildTypeId=Cockroach_UnitTests

```
[02:58:32] :		 [TestGossipHandlesReplacedNode] I161210 02:55:33.269359 40749 storage/replica_raftstorage.go:468  [n1,replicate,s1,r3/1:/Table/1{2-3},@c421486a00] generated preemptive snapshot 220c1297 at index 35
[02:58:32] :		 [TestGossipHandlesReplacedNode] I161210 02:55:33.273473 40757 storage/replica_raftstorage.go:468  [n2,replicate,s2,r2/2:/Table/1{1-2},@c4205e0500] generated preemptive snapshot da131f41 at index 43
[02:58:32] :		 [TestGossipHandlesReplacedNode] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	panic: runtime error: invalid memory address or nil pointer dereference
[02:58:32] :		 [TestGossipHandlesReplacedNode] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x662718]
[02:58:32] :		 [TestGossipHandlesReplacedNode] 
[02:58:32] :		 [TestGossipHandlesReplacedNode] goroutine 40898 [running]:
[02:58:32] :		 [TestGossipHandlesReplacedNode] panic(0x1faf920, 0xc4200120f0)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/usr/local/go/src/runtime/panic.go:500 +0x1ae
[02:58:32] :		 [TestGossipHandlesReplacedNode] github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42022a6c0)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xd8
[02:58:32] :		 [TestGossipHandlesReplacedNode] panic(0x1faf920, 0xc4200120f0)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/usr/local/go/src/runtime/panic.go:458 +0x271
[02:58:32] :		 [TestGossipHandlesReplacedNode] github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc4216d4380, 0xc42213c6c0, 0x2ae12bc5aef0, 0xc4217c1690, 0x300e180, 0xc420012170)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2698 +0xbc9
[02:58:32] :		 [TestGossipHandlesReplacedNode] github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x302c780, 0xc4217c1690, 0xc421306960, 0x2ae12bc432c8, 0xc420a8c4b0, 0x65a4d0, 0xc420c53738)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:362 +0x258
[02:58:32] :		 [TestGossipHandlesReplacedNode] github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x2ae12bc432c8, 0xc420a8c4b0)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:363 +0x75
[02:58:32] :		 [TestGossipHandlesReplacedNode] github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc42022a6c0, 0x2cfd03f, 0x19, 0x16c, 0x0, 0x0, 0xc4205de2d0, 0x2ae12bc432c8, 0xc420a8c4b0)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:264 +0xed
[02:58:32] :		 [TestGossipHandlesReplacedNode] created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:265 +0x2b0
```

**Comment by tamird** [comment]
The line numbers don't exactly match up, but I think this is caused by #12192.

**Comment by tamird** [comment]
Most nodes on cyan and cobalt have crashed and all of our nightly acceptance tests have failed, which is likely related to this issue.
