### ISSUE TITLE
acceptance: crash and test failure in TestGossipRestart (prop-eval kv)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12251]
Found in https://teamcity.cockroachdb.com/viewLog.html?buildId=86930

```
[10:50:39] :		 [TestGossipRestart] I161210 10:50:39.713524 2530 acceptance/cluster/localcluster.go:768  node 0: stderr at /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestGossipRestart-14df1556/roach-14df1556-0/stderr.2016-12-10T10_50_39Z.log
[10:50:39] :		 [TestGossipRestart] I161210 10:50:39.745228 2530 acceptance/cluster/localcluster.go:768  node 1: stderr at /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestGossipRestart-14df1556/roach-14df1556-1/stderr.2016-12-10T10_50_39Z.log
[10:50:39] :		 [TestGossipRestart] I161210 10:50:39.745625 2530 acceptance/cluster/localcluster.go:770  ~~~ node 1 CRASHED ~~~~
[10:50:39] :		 [TestGossipRestart] I161210 10:50:39.826087 2334 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32802: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:32802" <nil>}
[10:50:40] :		 [TestGossipRestart] I161210 10:50:40.049091 529 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32786: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:32786" <nil>}
[10:50:40] :		 [TestGossipRestart] I161210 10:50:40.051375 196 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32778: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:32778" <nil>}
[10:50:40] :		 [TestGossipRestart] I161210 10:50:40.106028 483 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32782: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:32782" <nil>}
[10:50:40] :		 [TestGossipRestart] I161210 10:50:40.225421 2530 acceptance/cluster/localcluster.go:768  node 2: stderr at /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestGossipRestart-14df1556/roach-14df1556-2/stderr.2016-12-10T10_50_40Z.log
[10:50:40] :		 [TestGossipRestart] I161210 10:50:40.236794 83 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32772: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:32772" <nil>}
[10:50:40] :		 [TestGossipRestart] I161210 10:50:40.258030 663 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32788: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:32788" <nil>}
[10:50:40] :		 [TestGossipRestart] I161210 10:50:40.316505 2603 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32814: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:32814" <nil>}
[10:50:40] :		 [TestGossipRestart] I161210 10:50:40.327121 86 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32772: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:32772" <nil>}
[10:50:40] :		 [TestGossipRestart] I161210 10:50:40.348195 215 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:32780: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:32780" <nil>}
[10:50:40] :		 [TestGossipRestart] 	util.go:556: condition failed to evaluate within 20s: failed to get gossip status from node 1: Get https://<nil>/_status/gossip/local: dial tcp: lookup <nil>: invalid domain name
[10:50:40] :		 [TestGossipRestart] 	localcluster.go:702: unexpected extra event &{1 die} (after [{0 die} {1 die} {2 die} {0 restart} {1 restart} {2 restart}])
[10:50:40] :		 [TestGossipRestart] 	util.go:556: condition failed to evaluate within 20s: failed to get gossip status from node 1: Get https://<nil>/_status/gossip/local: dial tcp: lookup <nil>: invalid domain name
	localcluster.go:702: unexpected extra event &{1 die} (after [{0 die} {1 die} {2 die} {0 restart} {1 restart} {2 restart}])
```

**Comment by tamird** [comment]
Can you include the tail of the crashed node's log?

**Comment by knz** [comment]
Here it is:
```
I161210 10:50:21.662213 148 storage/replica_raftstorage.go:633  [n3,s3,r4/?:{-},@c42016c500] applying preemptive snapshot at index 56 (id=3beb26fc, encoded size=34730, 1 rocksdb batches, 46 log entries)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6495b8]

goroutine 150 [running]:
panic(0x17e50c0, 0xc42001a060)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42043c870)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x17e50c0, 0xc42001a060)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc42037e380, 0xc420e70480, 0x7f5d7b9200f8, 0xc420d60660, 0x2508260, 0xc42001a100)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2698 +0x966
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x25265a0, 0xc420d60660, 0xc42014cae0, 0x7f5d7b9f6840, 0xc420de5710, 0xc420801738, 0xc420801740)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:362 +0x182
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x7f5d7b9f6840, 0xc420de5710)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:363 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc42043c870, 0x21fc2fc, 0x19, 0x16c, 0x0, 0x0, 0xc420de57a0, 0x7f5d7b9f6840, 0xc420de5710)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:264 +0xdf
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:265 +0x234
```

**Comment by tamird** [comment]
Thanks! Looks the same as #12249.

On Dec 10, 2016 06:24, "kena" <notifications@github.com> wrote:

Here it is:

I161210 10:50:21.662213 148 storage/replica_raftstorage.go:633
[n3,s3,r4/?:{-},@c42016c500] applying preemptive snapshot at index 56
(id=3beb26fc, encoded size=34730, 1 rocksdb batches, 46 log entries)
panic: runtime error: invalid memory address or nil pointer
dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6495b8]

goroutine 150 [running]:
panic(0x17e50c0, 0xc42001a060)
	/usr/local/go/src/runtime/panic.go:500
+0x1a1github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42043c870)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x17e50c0, 0xc42001a060)
	/usr/local/go/src/runtime/panic.go:458
+0x243github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc42037e380,
0xc420e70480, 0x7f5d7b9200f8, 0xc420d60660, 0x2508260, 0xc42001a100)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2698
+0x966github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x25265a0,
0xc420d60660, 0xc42014cae0, 0x7f5d7b9f6840, 0xc420de5710,
0xc420801738, 0xc420801740)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:362
+0x182github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x7f5d7b9f6840,
0xc420de5710)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:363
+0x5dgithub.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc42043c870,
0x21fc2fc, 0x19, 0x16c, 0x0, 0x0, 0xc420de57a0, 0x7f5d7b9f6840,
0xc420de5710)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:264 +0xdf
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:265 +0x234

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cockroachdb/cockroach/issues/12251#issuecomment-266201317>,
or mute the thread

**Comment by knz** [comment]
Thanks for highlighting!

Dup #12249.
