### ISSUE TITLE
kv/kvserver/loqrecovery: TestReplicaCollection timed out

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#123085]
I saw this timeout of TestReplicaCollection on release-24.1 in CI:

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/14977650?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true

This was on https://github.com/cockroachdb/cockroach/pull/122855 which is d73fd4abd4a2911db21a79920dede531d8cd5f0f plus an unrelated commit, so I think it includes https://github.com/cockroachdb/cockroach/pull/122184. @pav-kv do you think this is related to https://github.com/cockroachdb/cockroach/issues/114643?

Here's the top of the goroutine dump, rest is in https://gist.github.com/michae2/adcb29b111b7811c6b0a99c0bef12501

```
No pass/skip/fail event found for test
=== RUN   TestReplicaCollection
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/95fc0dff57a5bf3a6a9cc9666d301bb7/logTestReplicaCollection3243897287
    test_log_scope.go:81: use -show-logs to present logs inline
panic: test timed out after 1m48s
running tests:
  TestReplicaCollection (1m48s)
goroutine 23684 [running]:
testing.(*M).startAlarm.func1()
  GOROOT/src/testing/testing.go:2366 +0x265
created by time.goFunc
  GOROOT/src/time/sleep.go:177 +0x45
goroutine 1 [chan receive, 1 minutes]:
testing.(*T).Run(0xc001baf380, {0x82b0116, 0x15}, 0x8608a08)
  GOROOT/src/testing/testing.go:1750 +0x851
testing.runTests.func1(0xc001baf380)
  GOROOT/src/testing/testing.go:2161 +0x86
testing.tRunner(0xc001baf380, 0xc001d9b8d8)
  GOROOT/src/testing/testing.go:1689 +0x21f
testing.runTests(0xc001f07c80, {0xe3de780, 0x21, 0x21}, {0xc0000061c0?, 0xc001f07c38?, 0xe793e40?})
  GOROOT/src/testing/testing.go:2159 +0x8bf
testing.(*M).Run(0xc001800a00)
  GOROOT/src/testing/testing.go:2027 +0xf18
github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test.TestMain(0xc001800a00)
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test/pkg/kv/kvserver/loqrecovery/main_test.go:35 +0x265
main.main()
  main/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/loqrecovery/loqrecovery_test_/testmain.go:194 +0x825
```

Jira issue: CRDB-38196

**Comment by kvoli** [comment]
This doesn't look related to https://github.com/cockroachdb/cockroach/issues/114643, where the port is being reused.

From the stacks, the times out collecting the replica info:

<details><summary>stack</summary>
<p>

```
      goroutine 42 [select]:
      google.golang.org/grpc/internal/transport.(*recvBufferReader).readClient(0xc017dedef0, {0xc002f8a6a0, 0x5, 0x5})
        google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/transport.go:195 +0x136
      google.golang.org/grpc/internal/transport.(*recvBufferReader).Read(0xc017dedef0, {0xc002f8a6a0, 0x5, 0x5})
        google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/transport.go:175 +0x35b
      google.golang.org/grpc/internal/transport.(*transportReader).Read(0xc007d76f90, {0xc002f8a6a0, 0x5, 0x5})
        google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/transport.go:495 +0x5d
      io.ReadAtLeast({0xb0921c0, 0xc007d76f90}, {0xc002f8a6a0, 0x5, 0x5}, 0x5)
        GOROOT/src/io/io.go:335 +0xd0
      io.ReadFull(...)
        GOROOT/src/io/io.go:354
      google.golang.org/grpc/internal/transport.(*Stream).Read(0xc002c1bd40, {0xc002f8a6a0, 0x5, 0x5})
        google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/transport.go:479 +0x127
      google.golang.org/grpc.(*parser).recvMsg(0xc002f8a690, 0x7fffffff)
        google.golang.org/grpc/external/org_golang_google_grpc/rpc_util.go:561 +0x6e
      google.golang.org/grpc.recvAndDecompress(0xc002f8a690, 0xc002c1bd40, {0x0, 0x0}, 0x7fffffff, 0x0, {0xb0b8a80, 0xf965f80})
        google.golang.org/grpc/external/org_golang_google_grpc/rpc_util.go:692 +0x7c
      google.golang.org/grpc.recv(0xc002f8a690, {0x7fd5c3dc8c80, 0xc00177cac0}, 0xc002c1bd40, {0x0, 0x0}, {0x81276a0, 0xc004e109b0}, 0x7fffffff, 0x0, ...)
        google.golang.org/grpc/external/org_golang_google_grpc/rpc_util.go:758 +0xb4
      google.golang.org/grpc.(*csAttempt).recvMsg(0xc00bed1ba0, {0x81276a0, 0xc004e109b0}, 0x0)
        google.golang.org/grpc/external/org_golang_google_grpc/stream.go:1060 +0x568
      google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc00bed1ba0)
        google.golang.org/grpc/external/org_golang_google_grpc/stream.go:900 +0x51
      google.golang.org/grpc.(*clientStream).withRetry(0xc002c1bb00, 0xc015d688d8, 0xc015d688c8)
        google.golang.org/grpc/external/org_golang_google_grpc/stream.go:735 +0x478
      google.golang.org/grpc.(*clientStream).RecvMsg(0xc002c1bb00, {0x81276a0, 0xc004e109b0})
        google.golang.org/grpc/external/org_golang_google_grpc/stream.go:899 +0x1df
      github.com/cockroachdb/cockroach/pkg/server/serverpb.(*adminRecoveryCollectReplicaInfoClient).Recv(0xc006a7c6a0)
        github.com/cockroachdb/cockroach/pkg/server/serverpb/bazel-out/k8-fastbuild/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go:5372 +0x66
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery.CollectRemoteReplicaInfo({0xb0cff08, 0xf965f80}, {0xb171008, 0xc003d00680})
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery/collect.go:53 +0x2ed
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test.TestReplicaCollection.func1(0x1, 0x0)
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test/pkg/kv/kvserver/loqrecovery/server_integration_test.go:90 +0xf8
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test.TestReplicaCollection(0xc001baf520)
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test/pkg/kv/kvserver/loqrecovery/server_integration_test.go:117 +0x74d
      testing.tRunner(0xc001baf520, 0x8608a08)
        GOROOT/src/testing/testing.go:1689 +0x21f
      created by testing.(*T).Run in goroutine 1
        GOROOT/src/testing/testing.go:1742 +0x826
```


</p>
</details> 

https://github.com/cockroachdb/cockroach/blob/9203985b8ee0092cc9ba1f517cb5f1306f07e2ff/pkg/kv/kvserver/loqrecovery/server_integration_test.go#L90-L90

https://github.com/cockroachdb/cockroach/blob/9203985b8ee0092cc9ba1f517cb5f1306f07e2ff/pkg/kv/kvserver/loqrecovery/collect.go#L51-L53

The corresponding receiver is on a select, looking up a descriptor:

<details><summary>Details</summary>
<p>

```
      goroutine 23186 [select]:
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*call).result(0xc004b14840, {0xb0d00d8, 0xc007d77830}, 0x0)
        github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:250 +0x15d
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.Future.WaitForResult(...)
        github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:234
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangecache.(*RangeCache).tryLookup(0xc003d1d020, {0xb0d00d8, 0xc007d77830}, {0xe4094ca, 0x1, 0x1}, {0xc003d1d020?, 0xc0136dc0d0?}, 0x0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangecache/range_cache.go:800 +0x9e6
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangecache.(*RangeCache).lookupInternal(0xc003d1d020, {0xb0d00d8, 0xc007d77830}, {0xe4094ca, 0x1, 0x1}, {0xc003d1d020?, 0xc0136dc0d0?}, 0x0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangecache/range_cache.go:670 +0x145
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangecache.(*RangeCache).LookupWithEvictionToken(...)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangecache/range_cache.go:589
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).getRoutingInfo(0xc00376ec08, {0xb0d00d8, 0xc007d77830}, {0xe4094ca, 0x1, 0x1}, {0xc003d1d020?, 0xc0136dc0d0?}, 0x0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1000 +0xed
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch(0xc00376ec08, {0xb0d00d8, 0xc007d77830}, 0xc01288a5a0, {{0xe4094ca, 0x1, 0x1}, {0xe4094c8, 0x1, 0x1}}, ...)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:2052 +0x55f
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges(0xc00376ec08, {0xb0d00d8, 0xc007d77830}, 0xc01288a5a0, {{0xe4094ca, 0x1, 0x1}, {0xe4094c8, 0x1, 0x1}}, ...)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1616 +0x1031
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send(0xc00376ec08, {0xb0d00d8, 0xc007d777a0}, 0xc01288a5a0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1232 +0xa3a
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnLockGatekeeper).SendLocked(0xc0132e8568, {0xb0d00d8, 0xc007d777a0}, 0xc01288a5a0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go:82 +0x26c
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnMetricRecorder).SendLocked(0xc0132e8518, {0xb0d00d8, 0xc007d777a0}, 0xc01288a5a0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go:46 +0x1da
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts(0xc0132e8438, {0xb0d00d8, 0xc007d777a0}, 0xc01288a5a0, 0x5)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:239 +0x273
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked(0xc0132e8438, {0xb0d00d8, 0xc007d777a0}, 0xc01288a5a0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:167 +0x1d9
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked(0xc0132e83f8, {0xb0d00d8, 0xc007d777a0}, 0xc01288a5a0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:149 +0x95f
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked(0xc0132e82b0, {0xb0d00d8, 0xc007d777a0}, 0xc01288a5a0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go:325 +0x245
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked(0xc0132e8290, {0xb0d00d8, 0xc007d777a0}, 0xc01288a5a0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:117 +0x3d9
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked(0xc0132e81e8, {0xb0d00d8, 0xc007d777a0}, 0xc01288a5a0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:246 +0x7bc
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send(0xc0132e8008, {0xb0d0148, 0xc00ff5e150}, 0xc01288a5a0)
        github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:535 +0xa77
      github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender(0xc000d35680, {0xb0d0148, 0xc00ff5e150}, 0xc01288a5a0, {0x7fd5cfc30b60, 0xc0132e8008})
        github.com/cockroachdb/cockroach/pkg/kv/db.go:1124 +0x182
      github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send(0xc00491b3f0, {0xb0d0148, 0xc00ff5e150}, 0xc01288a5a0)
        github.com/cockroachdb/cockroach/pkg/kv/txn.go:1282 +0x37d
      github.com/cockroachdb/cockroach/pkg/kv.sendAndFill({0xb0d0148, 0xc00ff5e150}, 0xc0122beaa8, 0xc0132e8c08)
        github.com/cockroachdb/cockroach/pkg/kv/db.go:956 +0x27e
      github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Run(0xc00491b3f0, {0xb0d0148, 0xc00ff5e150}, 0xc0132e8c08)
        github.com/cockroachdb/cockroach/pkg/kv/txn.go:800 +0xa8
      github.com/cockroachdb/cockroach/pkg/kv.(*Txn).scan(0xc00491b3f0, {0xb0d0148, 0xc00ff5e150}, {0x7fccca0, 0xc002f8a8d0}, {0x7fccca0, 0xc002f8a8e8}, 0x64, 0x0, 0x1, ...)
        github.com/cockroachdb/cockroach/pkg/kv/txn.go:646 +0x218
      github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Scan(...)
        github.com/cockroachdb/cockroach/pkg/kv/txn.go:660
      github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Iterate(0xc00491b3f0, {0xb0d0148, 0xc00ff5e150}, {0x7fccca0, 0xc002f8a8d0}, {0x7fccca0, 0xc002f8a8e8}, 0x64, 0xc0122bee70)
        github.com/cockroachdb/cockroach/pkg/kv/txn.go:740 +0xde
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery.Server.ServeClusterReplicas.func2({0xb0d0148, 0xc00ff5e150})
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery/server.go:178 +0x2e7
      github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout({0xb0d00d8, 0xc007d77320}, {0x82b54e5, 0x16}, 0x37e11d600, 0xc0122bf0b8)
        github.com/cockroachdb/cockroach/pkg/util/timeutil/timeout.go:29 +0x12e
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery.Server.ServeClusterReplicas({0xc0039b9520, 0xc002f959e0, 0xc00393c000, 0xc003b26900, 0xc0012edcb0, 0xc0012edce0, {{0xc001c5cc30, 0x12}, {0xb14a660, 0xc003a9ed00}}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery/server.go:170 +0x4da
      github.com/cockroachdb/cockroach/pkg/server.(*systemAdminServer).RecoveryCollectReplicaInfo(0xc002983968, 0xf965f80, {0xb10b0a0, 0xc006a7c7a0})
        github.com/cockroachdb/cockroach/pkg/server/admin.go:3365 +0x2e5
      github.com/cockroachdb/cockroach/pkg/server/serverpb._Admin_RecoveryCollectReplicaInfo_Handler({0x820aa40, 0xc002983968}, {0xb102c28, 0xc0084fcd60})
        github.com/cockroachdb/cockroach/pkg/server/serverpb/bazel-out/k8-fastbuild/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go:6298 +0x13e
      github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.StreamServerInterceptor.func13({0x820aa40, 0xc002983968}, {0xb102d48, 0xc0039f3180}, 0xc002f8a828, 0x8609b08)
        github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:165 +0x449
      google.golang.org/grpc.getChainStreamHandler.func1({0x820aa40, 0xc002983968}, {0xb102d48, 0xc0039f3180})
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:1478 +0x119
      github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func4({0x820aa40, 0xc002983968}, {0xb102d48, 0xc0039f3180}, 0xc002f8a828, 0xc001458440)
        github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:178 +0xd7
      google.golang.org/grpc.getChainStreamHandler.func1({0x820aa40, 0xc002983968}, {0xb102d48, 0xc0039f3180})
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:1478 +0x119
      github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2.1({0xc001275360?, 0x38?})
        github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:145 +0x66
      github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc001275360, {0xb0d00d8, 0xc007d77230}, {0x0?, 0xc0014583c0?}, 0xc00c7157f0)
        github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:337 +0x186
      github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2({0x820aa40, 0xc002983968}, {0xb102d48, 0xc0039f3180}, 0xc002f8a828, 0xc0014583c0)
        github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:144 +0x15c
      google.golang.org/grpc.NewServer.chainStreamServerInterceptors.chainStreamInterceptors.func2({0x820aa40, 0xc002983968}, {0xb102d48, 0xc0039f3180}, 0xc002f8a828, 0x8609b08)
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:1469 +0xdd
      google.golang.org/grpc.(*Server).processStreamingRPC(0xc0027b4f00, {0xb11c4e0, 0xc00fba9860}, 0xc01288a000, 0xc0012ecea0, 0xe3c3220, 0x0)
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:1627 +0x20ef
      google.golang.org/grpc.(*Server).handleStream(0xc0027b4f00, {0xb11c4e0, 0xc00fba9860}, 0xc01288a000, 0x0)
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:1708 +0xfc5
      google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:965 +0xe5
      created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 22338
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:963 +0x4a8
```

</p>
</details> 


There are quite a few other stacks also waiting on a replica lookup and some on a lease request. I'll stress on that commit for a repro.

**Comment by kvoli** [comment]
No repro after stress racing for an hour.

**Comment by RaduBerinde** [comment]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_MaybeStressrace/15653734?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true
