### ISSUE TITLE
storage/engine: segfault in engine.dbApplyBatchRepr

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12363]
While testing a local single node cluster on top of #12323 my node crashed with:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4f5ebe8]

runtime stack:
runtime.throw(0x548231d, 0x2a)
	/Users/pmattis/Development/go-1.7/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/Users/pmattis/Development/go-1.7/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 87 [syscall, locked to thread]:
runtime.cgocall(0x4d324c0, 0xc432c29238, 0x0)
	/Users/pmattis/Development/go-1.7/src/runtime/cgocall.go:131 +0x110 fp=0xc432c291e8 sp=0xc432c291a8
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBApplyBatchRepr(0x8800e70, 0xc42e4d0800, 0x68d, 0x0, 0x0)
	??:0 +0x57 fp=0xc432c29238 sp=0xc432c291e8
github.com/cockroachdb/cockroach/pkg/storage/engine.dbApplyBatchRepr(0x8800e70, 0xc42e4d0800, 0x68d, 0x800, 0x5d7c331, 0x6275f40)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1393 +0xae fp=0xc432c292b0 sp=0xc432c29238
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).ApplyBatchRepr(0xc4203fe410, 0xc42e4d0800, 0x68d, 0x800, 0xc42bc11160, 0x8)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:436 +0x4c fp=0xc432c292f0 sp=0xc432c292b0
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc4338ac1c0, 0xc42efbec60, 0x5d93f60)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1024 +0x3d4 fp=0xc432c29440 sp=0xc432c292f0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc42c488000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2566 +0x4db fp=0xc432c29d50 sp=0xc432c29440
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc42c488000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2449 +0xc5 fp=0xc432c29dd0 sp=0xc432c29d50
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4203b4e00, 0x12)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3328 +0x137 fp=0xc432c29ec0 sp=0xc432c29dd0
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4200a46e0, 0xc42031d3b0)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:230 +0x28c fp=0xc432c29f28 sp=0xc432c29ec0
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33 fp=0xc432c29f48 sp=0xc432c29f28
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42031d3b0, 0xc420133fe0)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d fp=0xc432c29f70 sp=0xc432c29f48
runtime.goexit()
	/Users/pmattis/Development/go-1.7/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc432c29f78 sp=0xc432c29f70
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
```

The testing involved running `roachdemo -n 1 -- --logtostderr` and `block_writer` (with no arguments). I think I may have stopped and restarted `block_writer`. There is nothing in #12323 that would affect this code. 

It's late, perhaps I'm reading the goroutine stack traces wrong. Here are the full dumps:  [goroutines.txt](https://github.com/cockroachdb/cockroach/files/653641/goroutines.txt) [stacks.txt](https://github.com/cockroachdb/cockroach/files/653644/stacks.txt)

**Comment by petermattis** [comment]
@bdarnell This happened a while ago and only a single time, but could possibly be related to #12875.

**Comment by petermattis** [comment]
Happened again while experimenting with a commit which disables the `TimedMutex` (i.e. a completely innocuous change):

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4f5ccf8]

runtime stack:
runtime.throw(0x54fb835, 0x2a)
	/Users/pmattis/Development/go-1.8/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/Users/pmattis/Development/go-1.8/src/runtime/signal_unix.go:274 +0x2db

goroutine 105 [syscall, locked to thread]:
runtime.cgocall(0x4d26380, 0xc42847f248, 0x100)
	/Users/pmattis/Development/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc42847f200 sp=0xc42847f1c0
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBApplyBatchRepr(0x8a1e080, 0xc423fd5800, 0x2f8, 0x0, 0x0)
	github.com/cockroachdb/cockroach/pkg/storage/engine/_obj/_cgo_gotypes.go:185 +0x57 fp=0xc42847f248 sp=0xc42847f200
github.com/cockroachdb/cockroach/pkg/storage/engine.dbApplyBatchRepr.func1(0x8a1e080, 0xc423fd5800, 0x2f8, 0x0, 0x0)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1458 +0x80 fp=0xc42847f290 sp=0xc42847f248
github.com/cockroachdb/cockroach/pkg/storage/engine.dbApplyBatchRepr(0x8a1e080, 0xc423fd5800, 0x2f8, 0x400, 0xac9bd56, 0x62acaa0)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1458 +0x61 fp=0xc42847f2f8 sp=0xc42847f290
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).ApplyBatchRepr(0xc42034c4b0, 0xc423fd5800, 0x2f8, 0x400, 0xc427033d60, 0x8)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:445 +0x4c fp=0xc42847f338 sp=0xc42847f2f8
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc422a561c0, 0xc423f92330, 0x5daeea0)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1081 +0x39e fp=0xc42847f488 sp=0xc42847f338
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc421366b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2645 +0x4c2 fp=0xc42847fda0 sp=0xc42847f488
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc421366b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2528 +0xdd fp=0xc42847fe30 sp=0xc42847fda0
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4201e0380, 0x65)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3329 +0x131 fp=0xc42847ff28 sp=0xc42847fe30
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420446000, 0xc42018ed80)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:227 +0x270 fp=0xc42847ff88 sp=0xc42847ff28
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:178 +0x33 fp=0xc42847ffa8 sp=0xc42847ff88
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42018ed80, 0xc420297a00)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d fp=0xc42847ffd0 sp=0xc42847ffa8
runtime.goexit()
	/Users/pmattis/Development/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42847ffd8 sp=0xc42847ffd0
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
```

Note that I'm using go1.8rc3 locally while the previous crash was on go1.7.3.

**Comment by petermattis** [comment]
I have no reason to believe this has been fixed, but without a reproducible crash it will be very hard to fix. Removing the 1.0 milestone.

**Comment by petermattis** [comment]
Closing as this hasn't been seen in months. Will reopen if it reoccurs.
