### ISSUE TITLE
Manual range split causes panic

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#1242]
Starting a 3 node cluster on AWS and ran the bank example against it. No problems.
Added another 2 nodes.

Attempted a range split:
```
./cockroach range split 000000500 --addr=cockroach-db-1441359306.us-east-1.elb.amazonaws.com:8080 --insecure
```

Two nodes died.

The first one with:
```
W0603 14:11:51.065761      11 store.go:1179] failed to resolve on inconsistent read: replica 1:1 not leader; leader is 3:3
W0603 14:11:51.065969      11 store.go:1179] failed to resolve on inconsistent read: replica 1:1 not leader; leader is 3:3
panic: intents:<key:"\000\000\000k\000\001rdsc" txn:<name:"split range 1 at \"000000012\"" key:"000000012" id:"\021l\377R\345\307O\330\255\202\260\016\177\274\365)" priority:2037030288 isolation:SERIALIZABLE status:PENDING epoch:0 timestamp:<wall_time:1433340701486318134 logical:0 > orig_timestamp:<wall_time:1433340701486318134 logical:0 > max_timestamp:<wall_time:1433340701736318134 logical:0 > certain_nodes:<> > > resolved:false
```

The other node died with:
```
E0603 14:11:55.751688      11 raft_transport.go:174] raft message to node 1 failed: read tcp 172.31.22.174:8080: connection reset by peer
I0603 14:11:55.770180      11 client.go:233] client 172.31.22.174:8080 heartbeat failed: read tcp 172.31.22.174:8080: connection reset by peer; recycling...
I0603 14:11:55.770343      11 client.go:233] client 172.31.22.174:8080 heartbeat failed: read tcp 172.31.22.174:8080: connection reset by peer; recycling...
W0603 14:11:55.771377      11 raft_transport.go:170] raft client for node 1 closed
I0603 14:11:55.771523      11 gossip.go:460] client disconnected: read tcp 172.31.22.174:8080: connection reset by peer
panic: requested entry at index is unavailable
```

**Comment by tschottdorf** [comment]
may or may not be the same as #1191. You don't have a stacktrace?

**Comment by MBerhault** [comment]
I have full stack traces and logs since process startup.

Node 0:
```
W0603 14:11:51.065574      11 store.go:1179] failed to resolve on inconsistent read: replica 1:1 not leader; leader is 3:3
W0603 14:11:51.065761      11 store.go:1179] failed to resolve on inconsistent read: replica 1:1 not leader; leader is 3:3
W0603 14:11:51.065969      11 store.go:1179] failed to resolve on inconsistent read: replica 1:1 not leader; leader is 3:3
panic: intents:<key:"\000\000\000k\000\001rdsc" txn:<name:"split range 1 at \"000000012\"" key:"000000012" id:"\021l\377R\345\307O\330\255\202\260\016\177\274\365)" priority:2037030288 isolation:SERIALIZABLE status:PENDING epoch:0 timestamp:<wall_time:1433340701486318134 logical:0 > orig_timestamp:<wall_time:1433340701486318134 logical:0 > max_timestamp:<wall_time:1433340701736318134 logical:0 > certain_nodes:<> > > resolved:false

goroutine 26 [running]:
github.com/cockroachdb/cockroach/multiraft.func·008()
  /go/src/github.com/cockroachdb/cockroach/multiraft/storage.go:176 +0x7e9
github.com/cockroachdb/cockroach/util.func·001()
  /go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
  /go/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0xe3
```

Node 2:
```
E0603 14:11:55.751688      11 raft_transport.go:174] raft message to node 1 failed: read tcp 172.31.22.174:8080: connection reset by peer
I0603 14:11:55.770180      11 client.go:233] client 172.31.22.174:8080 heartbeat failed: read tcp 172.31.22.174:8080: connection reset by peer; recycling...
I0603 14:11:55.770343      11 client.go:233] client 172.31.22.174:8080 heartbeat failed: read tcp 172.31.22.174:8080: connection reset by peer; recycling...
W0603 14:11:55.771377      11 raft_transport.go:170] raft client for node 1 closed
I0603 14:11:55.771523      11 gossip.go:460] client disconnected: read tcp 172.31.22.174:8080: connection reset by peer
panic: requested entry at index is unavailable

goroutine 57 [running]:
github.com/coreos/etcd/raft.(*raft).sendAppend(0xc208b0e0c0, 0x200000002)
  /go/src/github.com/coreos/etcd/raft/raft.go:250 +0x159
github.com/coreos/etcd/raft.stepLeader(0xc208b0e0c0, 0x4, 0x300000003, 0x200000002, 0x6, 0x0, 0xa, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/raft.go:523 +0x6f3
github.com/coreos/etcd/raft.(*raft).Step(0xc208b0e0c0, 0x4, 0x300000003, 0x200000002, 0x6, 0x0, 0xa, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/raft.go:487 +0x259
github.com/coreos/etcd/raft.(*multiNode).run(0xc20813f4a0)
  /go/src/github.com/coreos/etcd/raft/multinode.go:236 +0xd0b
created by github.com/coreos/etcd/raft.StartMultiNode
  /go/src/github.com/coreos/etcd/raft/multinode.go:56 +0xb6
```

**Comment by MBerhault** [comment]
Trying to reproduce locally, but so far no luck. Though I did get it to crash on a bad split key:
```
I0603 10:20:53.704617   26902 range_command.go:833] initiating a split of range=1 ["" - "000000036") at key "\x00tsdcr.node.calls.error.3\x00\x01\t\x01\v\x06\x13F"
```
This then caused crashes due to:
```
F0603 10:20:57.317662   26902 range.go:982] range splits configuration values for "\x00zone"
goroutine 41 [running]:
github.com/cockroachdb/cockroach/util/log.stacks(0xc20a822101, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/log/clog.go:901 +0xcd
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x1653380, 0x3, 0x134e88c, 0x8, 0x3d6, 0x0, 0xc20a822180)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/log/clog.go:773 +0x11b
github.com/cockroachdb/cockroach/util/log.AddStructured(0x0, 0x0, 0x3, 0x2, 0x1087450, 0x28, 0xc20823fc90, 0x1, 0x1)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/log/structured.go:38 +0x120
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0xc200000003, 0x1087450, 0x28, 0xc20823fc90, 0x1, 0x1)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/log/log.go:58 +0x82
github.com/cockroachdb/cockroach/util/log.Fatalf(0x1087450, 0x28, 0xc20823fc90, 0x1, 0x1)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/log/log.go:161 +0x75
github.com/cockroachdb/cockroach/storage.(*Range).maybeGossipConfigsLocked(0xc208168090, 0xc20823fe58)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/range.go:982 +0x29b
github.com/cockroachdb/cockroach/storage.(*Range).maybeGossipConfigs(0xc208168090, 0xc20823fe58)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/range.go:967 +0x77
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipConfigs(0xc208166000, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:619 +0x200
github.com/cockroachdb/cockroach/storage.func·031()
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:569 +0x21d
github.com/cockroachdb/cockroach/util.func·001()
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0xe3
```

**Comment by tschottdorf** [comment]
looks a lot like #1191 then. The last stacktrace is probably a cousin of #1002.

**Comment by bdarnell** [comment]
The logs for node3 are full of
`
E0603 13:49:02.881376      11 range_command.go:105] executed a command with excessive future clock offset: hlc.go:220: Remote wall time offsets from local physical clock: 1433339343137030618 (255671844ns ahead)
`

(the reported offsets go up to 400ms) This is a log.Error without a return, so we execute the command without ratcheting our clock up to the highest observed value. Is this safe? I think we need to fail the request here if we've discovered a clock offset that is too high to process. I don't know yet whether this is related to the crashes.

**Comment by bdarnell** [comment]
It looks like nodes become unresponsive for several seconds during or after the split. In the logs we see each node become leader in turn and then split the range again. Nodes 2 and 3 see the effect of node 1's split, but not each other's.

The same time period on each log (note the gap between 14:11:25 and 14:11:29 on node 1):

node1.log:
```
I0603 14:11:25.529989      11 range_command.go:833] initiating a split of range=1 ["" - "\xff\xff") at key "000000380"
I0603 14:11:29.713978      11 range_command.go:770] range 2: new leader lease replica 1:1 00:00:00.000 +1433340687.334s
I0603 14:11:29.742605      11 range_command.go:770] range 1: new leader lease replica 1:1 14:11:29.000 +1.008s
I0603 14:11:29.756285      11 range_command.go:770] range 2: new leader lease replica 1:1 14:11:28.000 +1.001s
E0603 14:11:29.759137      11 range_command.go:105] executed a command with excessive future clock offset: hlc.go:220: Remote wall time offsets from local physical clock: 1433340690097569734 (338453822ns ahead)
I0603 14:11:33.521355      11 range_command.go:770] range 1: new leader lease replica 1:1 14:11:31.000 +1.165s
I0603 14:11:35.521749      11 node.go:563] runtime stats: 4761 goroutines, 96.84MB active, 174243.45cgo/sec, 0.51/0.00 %(u/s)time, 0.11 %gc (59x)
```

node2.log:
```
I0603 14:11:28.726840      10 range_command.go:770] range 1: new leader lease replica 2:2 14:11:28.000 +1.261s
I0603 14:11:28.828556      10 range_command.go:833] initiating a split of range=1 ["" - "000000380") at key "000000011"
I0603 14:11:29.736892      10 range_command.go:770] range 2: new leader lease replica 2:2 14:11:27.000 +1.604s
W0603 14:11:31.936353      10 store.go:1179] failed to resolve on inconsistent read: replica 2:2 not leader; leader is 1:1
I0603 14:11:32.484088      10 range_command.go:770] range 2: new leader lease replica 2:2 14:11:31.000 +1.262s
I0603 14:11:33.977575      10 range_command.go:770] range 2: new leader lease replica 2:2 14:11:33.000 +1.052s
```

node3.log:
```
I0603 14:11:27.884603      11 range_command.go:770] range 1: new leader lease replica 3:3 14:11:27.000 +1.252s
I0603 14:11:27.927226      11 range_command.go:833] initiating a split of range=1 ["" - "000000380") at key "000000012"
I0603 14:11:31.617809      11 range_command.go:770] range 2: new leader lease replica 3:3 14:11:29.000 +1.158s
I0603 14:11:33.200712      11 range_command.go:770] range 2: new leader lease replica 3:3 14:11:32.000 +1.196s
I0603 14:11:35.848598      11 range_command.go:770] range 2: new leader lease replica 3:3 14:11:34.000 +1.137s
```

**Comment by tschottdorf** [comment]
We shouldn't be executing those requests with high clock offset. They should be logged prominently and return an error.

**Comment by bdarnell** [comment]
We can't return an error here; it's in Range.executeCmd which must be perfectly consistent on all nodes where it completes. If we can't process the command then we'll have to panic or log.Fatal; we can't process additional raft commands after this point. 

I think we have to do our clock offset monitoring at a higher level. We can reject a command due to clock weirdness before it goes into raft, but once it's in raft we must process it.

**Comment by spencerkimball** [comment]
There's no super strong error issue here. We should adjust things so that we log the error, adjust the clock forward past where we are comfortable going, and process the command. This doesn't affect correctness here, it just moves our clock forward uncomfortable far (and probably means nodes are going to commit suicide).
