### ISSUE TITLE
changefeedccl: setting min_checkpoint_frequency to 0s causes a panic in 24.1

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#126848]
Creating a changefeed on `release-24.1` with `min_checkpoint_frequency = '0s'` causes a panic.

This issue was encountered on an M2 Mac running the ARM version of `release-24.1`, but the issue does not seem ARM-specific. The error seems to come from [here](https://github.com/cockroachdb/cockroach/blob/0c41066138cbe35917c8090613ed92b276bbacb7/pkg/ccl/changefeedccl/changefeed_processors.go#L655): when the flush frequency is set to 0, there is a call to `rand.Int63n(0)`, which will panic as 0 is not an allowed argument.

This is a bug as the [documentation](https://www.cockroachlabs.com/docs/stable/create-changefeed) suggests this is a legal setting:

> If this is set to 0s, a node will flush as long as the high-water mark has increased for the ranges that particular node is processing.

```
panic: invalid argument to Int63n

goroutine 3701 [running]:
math/rand.(*Rand).Int63n(0x401aa26e10?, 0x0?)
	GOROOT/src/math/rand/rand.go:122 +0xe4
math/rand.Int63n(0x0)
	GOROOT/src/math/rand/rand.go:443 +0x28
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.nextFlushWithJitter({0x75cda60, 0xbe79740}, 0x0, 0x668c3706?)
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:645 +0x64
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).noteResolvedSpan.func2()
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:828 +0x6c
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).noteResolvedSpan(0x40181afb88, {{{0x4018768708, 0x2, 0x8}, {0x4018768710, 0x2, 0x8}}, {0x17e051f190798a67, 0x0}, 0x0})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:831 +0x39c
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).tick(0x40181afb88)
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:774 +0x354
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).Next(0x40181afb88)
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:686 +0x84
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Next(0x4018798808)
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1375 +0x8c
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run({0x75ce670, 0x4018745e00}, {0x75f3da0, 0x4018798808}, {0x759afe8, 0x4005bfac08})
	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:198 +0x48
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run(0x4018798808, {0x75ce638?, 0x401871d900?}, {0x759afe8, 0x4005bfac08})
	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:723 +0x6c
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0x40185a7b88, {0x75ce638, 0x401871d900}, 0x0?)
	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:579 +0x180
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0x40018b1040, {0x75ce638, 0x401871d8b0}, 0x401877e340, 0x0, 0x4018765d00, 0x4005bfac08, 0x4018798008, 0x0)
	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:928 +0x91c
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.startDistChangefeed.func1({0x75ce638, 0x401871d860})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_dist.go:321 +0x304
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GoAndWait.Group.GoCtx.func1()
	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x2c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 3686
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x98

```

Jira issue: CRDB-40159

**Comment by rickystewart** [comment]
Oh, never mind, this is already reported and fixed: https://github.com/cockroachdb/cockroach/issues/125312
