### ISSUE TITLE
benchmarks: panic: attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12850]
Looks like BenchmarkBank2_Cockroach-16 produces a panic in the nightly benchmark tests. From `sql.test.stderr` in https://teamcity.cockroachdb.com/viewLog.html?buildId=114365&buildTypeId=Cockroach_BenchmarkTests&tab=artifacts:

```
panic: attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING (finalized: false) [recovered]
	panic: 
UPDATE bench.bank
  SET balance = CASE id WHEN $1 THEN balance-$3 WHEN $2 THEN balance+$3 END
  WHERE id IN ($1, $2) AND (SELECT balance >= $3 FROM bench.bank WHERE id = $1): attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING (finalized: false) [recovered]
	panic: 
UPDATE bench.bank
  SET balance = CASE id WHEN $1 THEN balance-$3 WHEN $2 THEN balance+$3 END
  WHERE id IN ($1, $2) AND (SELECT balance >= $3 FROM bench.bank WHERE id = $1): attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING (finalized: false)

goroutine 411743 [running]:
panic(0x189eee0, 0xc424781a50)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc422b82000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x189eee0, 0xc424781a50)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc421009001, 0xae)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:455 +0x149
panic(0x1857280, 0xc424781a30)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).resetStateAndTxn(0xc421375668, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:360 +0x3dc
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc421d669a0, 0xc421375600, 0xc421009001, 0xae, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:689 +0xcf8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc421d669a0, 0xc421375600, 0xc421009001, 0xae, 0xc423d19410, 0x0, 0x0, 0x0, 0x632900)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:461 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc421230c00, 0x7f1700249400, 0xc4251cdda0, 0xc421009001, 0xae, 0xc423d19410, 0x2b9fbc8, 0x0, 0x0, 0xc420f61000, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:792 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc421230c00, 0x7f1700249400, 0xc4251cdda0, 0xc421230c28, 0x9, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:778 +0x20a
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc421230c00, 0x7f1700249400, 0xc4251cdda0, 0x5400, 0xc420ae82f8, 0x7f1700249400, 0xc42363e300, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:420 +0xc70
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420ae81c0, 0x7f1700249400, 0xc42363e300, 0x2686460, 0xc422f18000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:309 +0x999
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x26873c0, 0xc4231604d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:522 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc422b82000, 0xc4214c0060, 0x26873c0, 0xc4231604d0, 0xc42299a620)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

**Comment by jordanlewis** [comment]
This is in fact easily reproducible. Just run:

`make bench PKG=./pkg/sql BENCHES=BenchmarkBank`

**Comment by andreimatei** [comment]
Tighter repro: `GOMAXPROCS=2 make bench PKG=./pkg/sql BENCHES=BenchmarkBank2_Cockroach`

Something funky's going on: a transaction seems to be getting a retryable error that was intended for another transaction.
https://github.com/cockroachdb/cockroach/blob/master/pkg/internal/client/txn.go#L551

That shouldn't lead to a crash, but I also don't think it should be happening in this test. Investigating...

**Comment by andreimatei** [comment]
I believe this has something to do with changes that have been made around 2 weeks ago (12 days ago to be exact, which is funny since the test apparently was flaky some time before that?) in how subqueries are started; subqueries are now started by a visitor, before the parent query is started, and their errors don't prevent the parent from attempting to run. And so the parent might run in a KV transaction that's not supposed to exist anymore.
I'm still looking at the specifics.
