### ISSUE TITLE
storage: panic after setting/changing constraint

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#12863]
Testing Bram's https://github.com/BramGruneir/cockroach/tree/rebalance branch.

Here's what I did:

``` shell
# Started 6 nodes, 3 with a store attribute and east locality, and 3 with a west locality.
$ cockroach start --store=path=node1,attrs=block --locality=region=east --background;
$ cockroach start --store=path=node2,attrs=block --locality=region=east --port=26258 --http-port=8081 --join=localhost:26257 --background;
$ cockroach start --store=path=node3,attrs=block --locality=region=east --port=26259 --http-port=8082 --join=localhost:26257 --background;
$ cockroach start --store=path=node4 --locality=region=west --port=26260 --http-port=8083 --join=localhost:26257 --background;
$ cockroach start --store=path=node5 --locality=region=west --port=26261 --http-port=8084 --join=localhost:26257 --background;
$ cockroach start --store=path=node6 --locality=region=west --port=26262 --http-port=8085 --join=localhost:26257 --background;

# Reduced max range size.
$ echo -e "range_min_bytes: 1\nrange_max_bytes: 262144" | cockroach zone set .default -f -

# Ran block_writer for 10s.
$ cd ../examples-go/block_writer; block_writer -duration 10s

# Added required constraint matching store attribute for node 1, 2, and 3.
$ cd ../../cockroach; echo 'constraints: [+block]' | cockroach zone set datablocks -f -

# Ran block_writer for 1m.
$ cd ../examples-go/block_writer; block_writer -duration 1m
```

After ~14 seconds, I got this panic:

``` shell
panic: tocommit(178) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost? [recovered]
	panic: tocommit(178) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?

goroutine 109 [running]:
panic(0x51daaa0, 0xc4227cde80)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420394870)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x51daaa0, 0xc4227cde80)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/storage.(*raftLogger).Panicf(0xc4227cdcd0, 0x540dd25, 0x5d, 0xc421f1abc0, 0x2, 0x2)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/raft.go:111 +0x107
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc4220e9b20, 0xb2)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/log.go:191 +0x166
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc421c4ee10, 0x8, 0x14, 0x2, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1095 +0x54
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.stepFollower(0xc421c4ee10, 0x8, 0x14, 0x2, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1041 +0x31f
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc421c4ee10, 0x8, 0x14, 0x2, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:778 +0x11ef
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*RawNode).Step(0xc422a05b80, 0x8, 0x14, 0x2, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:195 +0xc9
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest.func4(0xc422a05b80, 0x0, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3083 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc4217a3200, 0x55ada00, 0xc422221878, 0x4, 0x1)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:522 +0x139
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroup(0xc4217a3200, 0xc422221878, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:539 +0x92
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc42032c380, 0x8f628e8, 0xc421ebb830, 0xc421a28300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3084 +0xbe5
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc42032c380, 0x53)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3321 +0x174
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42029f340, 0xc420394870)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:241 +0x267
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420394870, 0xc4208e6140)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
2017/01/11 17:21:12 error running blockwriter 8dbcf38c-8c4e-4418-a233-ef0660bceb48: pq: result is ambiguous (sending to all 3 replicas failed; last error: [NotLeaseHolderError] range 17: replica {2 2 18} not lease holder; current lease is repl={3 3 3} start=1484173230.254001162,0 exp=1484173281.335199521,0 pro=1484173272.335204220,0, but RPC failure may have masked txn commit)
```

When I tried to reproduce this, I saw a different problem. Node 1 seems to have died on block_writer.

``` shell
$ cd ../examples-go/block_writer; block_writer -duration 1m
    1s:  403.9/sec   403.7/sec
    2s:  475.9/sec   439.8/sec
    3s:  414.9/sec   431.5/sec
    4s:  377.1/sec   417.9/sec
    5s:  343.0/sec   402.9/sec
    6s:  366.9/sec   396.9/sec
    7s:  364.0/sec   392.2/sec
    8s:  441.2/sec   398.3/sec
    9s:  377.0/sec   396.0/sec
   10s:  377.0/sec   394.1/sec
   11s:  388.8/sec   393.6/sec
   12s:  474.1/sec   400.3/sec
   13s:  426.3/sec   402.3/sec
   14s:  459.3/sec   406.4/sec
   15s:  384.0/sec   404.9/sec
   16s:  449.0/sec   407.6/sec
   17s:  443.0/sec   409.7/sec
   18s:  414.0/sec   410.0/sec
   19s:  446.0/sec   411.8/sec
   20s:  292.0/sec   405.9/sec
   21s:  317.0/sec   401.6/sec
   22s:  303.9/sec   397.2/sec
2017/01/11 18:01:24 error running blockwriter 82aa76a4-912a-4275-9db0-852359ba9df3: read tcp 127.0.0.1:54983->127.0.0.1:26257: read: connection reset by peer
```

When I tried to reproduce this again, `block_writer` finished but node 3 died. 

``` shell
$ ps
  PID TTY           TIME CMD
 9028 ttys000    0:00.03 /Applications/iTerm.app/Contents/MacOS/iTerm2 --server /usr/bin/login -fpl jesseseldess /Applications/iTerm.app/Contents/MacOS/iTerm2 --launch_shell
 9030 ttys000    0:00.59 -bash
12032 ttys000    1:08.37 cockroach start --store=path=node1,attrs=block --locality=region=east
12034 ttys000    0:32.30 cockroach start --store=path=node2,attrs=block --locality=region=east --port=26258 --http-port=8081 --join=localhost:26257
12038 ttys000    0:43.27 cockroach start --store=path=node4 --locality=region=west --port=26260 --http-port=8083 --join=localhost:26257
12040 ttys000    0:25.23 cockroach start --store=path=node5 --locality=region=west --port=26261 --http-port=8084 --join=localhost:26257
12042 ttys000    0:37.33 cockroach start --store=path=node6 --locality=region=west --port=26262 --http-port=8085 --join=localhost:26257
```

**Comment by jseldess** [comment]
Got what looks like this same panic in a slightly different scenario. This time, I didn't reduce the range size at all. I set a required constraint (`+block`), used block writer, and then reversed the constraint to see data move off nodes (`-block`).

```
# Start 7 nodes, the first three with the `block` store attributed.
$ cockroach start --store=path=node1,attrs=block --background;
$ cockroach start --store=path=node2,attrs=block --port=26258 --http-port=8081 --join=localhost:26257 --background;
$ cockroach start --store=path=node3,attrs=block --port=26259 --http-port=8082 --join=localhost:26257 --background;
$ cockroach start --store=path=node4 --port=26260 --http-port=8083 --join=localhost:26257 --background;
$ cockroach start --store=path=node5 --port=26261 --http-port=8084 --join=localhost:26257 --background;
$ cockroach start --store=path=node6 --port=26262 --http-port=8085 --join=localhost:26257 --background;
$ cockroach start --store=path=node7 --port=26263 --http-port=8086 --join=localhost:26257 --background;

# Run block_writer for 10 seconds.
$ cd ../examples-go/block_writer; block_writer -duration 10s

# Set required constraint for datablocks database.
$ cd ../../cockroach; echo 'constraints: [+block]' | cockroach zone set datablocks -f -

# Run block_writer for 1 min.
$ cd ../examples-go/block_writer; block_writer -duration 1m

# Change datablocks db config to prohibited constraint.
$ cd ../../cockroach; echo 'constraints: [-block]' | cockroach zone set datablocks -f -
```

Got this panic very soon after:
```
~/src/github.com/cockroachdb/cockroach$ panic: tocommit(3268) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost? [recovered]
	panic: tocommit(3268) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?

goroutine 76 [running]:
panic(0x51daaa0, 0xc4227d8ae0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4203fa6c0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x51daaa0, 0xc4227d8ae0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/storage.(*raftLogger).Panicf(0xc4227d8950, 0x540dd25, 0x5d, 0xc42083e180, 0x2, 0x2)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/raft.go:111 +0x107
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc420365960, 0xcc4)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/log.go:191 +0x166
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc421150d20, 0x8, 0x1d7, 0x37, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1095 +0x54
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.stepFollower(0xc421150d20, 0x8, 0x1d7, 0x37, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1041 +0x31f
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc421150d20, 0x8, 0x1d7, 0x37, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:778 +0x11ef
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*RawNode).Step(0xc420f51600, 0x8, 0x1d7, 0x37, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:195 +0xc9
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest.func4(0xc420f51600, 0x0, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3083 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc420306000, 0x55ada00, 0xc421065878, 0x4, 0x1)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:522 +0x139
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroup(0xc420306000, 0xc421065878, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:539 +0x92
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc42034e700, 0x9549180, 0xc424a86000, 0xc4215dc780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3084 +0xbe5
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc42034e700, 0x6)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3321 +0x174
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4202531e0, 0xc4203fa6c0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:241 +0x267
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203fa6c0, 0xc4203c9a00)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
```

**Comment by BramGruneir** [comment]
I just got ```F170112 14:40:45.633895 10308 storage/replica_command.go:1105  [n5,s5,r1/29:/M{in-eta2/Table/…},@c420caa900] range lookup of meta key /Meta2/Table/13/1/2017-01-12T19:40:42.41853Z/210303852390547456/0 found only non-matching ranges: []``` instead

**Comment by BramGruneir** [comment]
Got that other fatal again:```
F170112 14:50:28.613161 132104 storage/replica_command.go:1105  [n1,s1,r316/1:/Meta2/Table/51/1/{383…-583…},@c4245c3500] range lookup of meta key /Meta2/Table/51/1/5809267664695428192/"f21212e0-4a93-4f95-a80d-acdb67ffe516"/2558 found only non-matching ranges: []```

**Comment by jseldess** [comment]
Which of the steps above are you following, @BramGruneir? I'll try again as well.

**Comment by BramGruneir** [comment]
I'm trying it again right now.  I've been using the first set.

**Comment by a-robinson** [comment]
This issue has been tracked down in #14193 / #14231, with the underlying cause explained in https://github.com/cockroachdb/cockroach/issues/14193#issuecomment-287493273. Closing as a dupe.
