### ISSUE TITLE
distsql: panic 'flow already registered'

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#12876]
Ran into the panic below the first time I tried to run a distsql query on a node. Did not run into it again after restart. Nothing useful in the logs, except a long spam of messages like the one below (prior to the query being run).
```
I170112 14:11:20.066619 5270719 vendor/google.golang.org/grpc/server.go:723  grpc: Server.processUnaryRPC failed to write status: stream error: code = 4 desc = "context deadline exceeded"
```

I looked through the code and the only explanation I can come up with is if the distsql planner's nodeID was not set correctly. Then we may end up sending a setup flow request to ourselves AND setup a sync flow locally with the same id.

Investigate the nodeID issue and make this into an error not a panic.

```
panic: flow already registered [recovered]
	panic: SELECT COUNT(*) FROM comments;: flow already registered [recovered]
	panic: SELECT COUNT(*) FROM comments;: flow already registered

goroutine 5064283 [running]:
panic(0x1767a00, 0xc4f5d471e0)
	/home/radu/goroot/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4200b0870)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x1767a00, 0xc4f5d471e0)
	/home/radu/goroot/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc4abcf31b7, 0x1e)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:455 +0x149
panic(0x1722600, 0xc4f5d471c0)
	/home/radu/goroot/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*flowRegistry).RegisterFlow(0xc4202285d0, 0xe94ba1002c773502, 0x5fd584bb82d464b0, 0xc4f5a11680, 0xc4c729cc30)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow_registry.go:130 +0x328
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start(0xc4f5a11680, 0x1af3fe0)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:350 +0x1f7
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).PlanAndRun(0xc4203e6310, 0x7fd97b5218e8, 0xc48798a000, 0xc4ea2e4000, 0x249cfc0, 0xc4af580300, 0xc46fe48000, 0x0, 0xc4d6dc90c0)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1474 +0x1366
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execDistSQL(0xc4201ba9a0, 0xc43c922d70, 0x249cfc0, 0xc4af580300, 0xc50af37ee8, 0x0, 0x0)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1222 +0x113
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc4201ba9a0, 0x2494da0, 0xc4dca0bfb0, 0xc43c922d70, 0xc50af30001, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1343 +0x49d
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc4201ba9a0, 0x2494da0, 0xc4dca0bfb0, 0xc43c922d70, 0x101, 0xc43c922c68, 0x0, 0x0, 0x0, 0x0, ...)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1113 +0x2ab
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc4201ba9a0, 0xc4ed3f0c50, 0x1, 0x1, 0xc43c922d70, 0xc43c922c68, 0x101, 0x0, 0x6, 0xaf38b48, ...)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:850 +0x7db
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc4201ba9a0, 0xc43c922d70, 0x1, 0xc43c922c68, 0xc4ed3f0c90, 0xc4ed3f0c50, 0x1, 0x1, 0x0, 0x0, ...)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:768 +0xf8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func2(0xc4ea2e4000, 0xc4ed3f0c90, 0x0, 0x0)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:621 +0x2b7
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc4ea2e4000, 0xc4ad550101, 0xc420018140, 0xc4ad555880, 0x0, 0x0)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:520 +0x215
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4201ba9a0, 0xc43c922c00, 0xc4abcf31b7, 0x1e, 0x0, 0x0, 0x0, 0x0, 0xc4e6bad300)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:643 +0x5b0
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4201ba9a0, 0xc43c922c00, 0xc4abcf31b7, 0x1e, 0x0, 0x0, 0x0, 0x0, 0xc4abcf3100)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:461 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc49b401800, 0x7fd97b5218e8, 0xc4b0e53950, 0xc4abcf31b7, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x701601, ...)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:792 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc49b401800, 0x7fd97b5218e8, 0xc4b0e53950, 0xc49b401828, 0x23, 0x0)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:470 +0xb3
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc49b401800, 0x7fd97b5218e8, 0xc4b0e53950, 0x5400, 0xc420250138, 0x7fd97b5218e8, 0xc4b0e53920, 0x0, 0x0)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:397 +0xa62
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420250000, 0x7fd97b5218e8, 0xc4b0e53920, 0x249c280, 0xc4d66a0000, 0x0, 0x0)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:309 +0x999
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x249c280, 0xc4d66a0000)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:522 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4200b0870, 0xc420042030, 0x249c280, 0xc4d66a0000, 0xc4209c5780)
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/home/radu/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

**Comment by RaduBerinde** [comment]
Unassigning issues that someone should look into while I'm gone.

**Comment by dianasaur323** [comment]
@RaduBerinde do you still want to take a look at this now that you are back?

**Comment by andreimatei** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/333253424/

**Comment by RaduBerinde** [comment]
This is now converted to an error. Moving to 1.2 since we don't have much to go on in terms of reproducing the condition.

**Comment by dt** [comment]
hello!

on sapphire-1, right now:
```
root@localhost:26257/> IMPORT TABLE lineitem (l_orderkey INTEGER NOT NULL, l_partkey INTEGER NOT NULL, l_suppkey INTEGER NOT NULL, l_linenumber INTEGER NOT NULL, l_quantity DECIMAL(15,2) NOT NULL, l_extendedprice DECIMAL(15,2) NOT NULL, l_discount DECIMAL(15,2) NOT NULL, l_tax DECIMAL(15,2) NOT NULL, l_returnflag CHAR(1) NOT NULL, l_linestatus CHAR(1) NOT NULL, l_shipdate DATE NOT NULL, l_commitdate DATE NOT NULL, l_receiptdate DATE NOT NULL, l_shipinstruct CHAR(25) NOT NULL, l_shipmode CHAR(10) NOT NULL, l_comment VARCHAR(44) NOT NULL, PRIMARY KEY (l_orderkey, l_linenumber), INDEX l_ok (l_orderkey ASC), INDEX l_pk (l_partkey ASC), INDEX l_sk (l_suppkey ASC), INDEX l_sd (l_shipdate ASC), INDEX l_cd (l_commitdate ASC), INDEX l_rd (l_receiptdate ASC), INDEX l_pk_sk (l_partkey ASC, l_suppkey ASC), INDEX l_sk_pk (l_suppkey ASC, l_partkey ASC)) CSV DATA ('http://192.168.1.4:2015/csv/sf-5/lineitem.tbl.1', 'http://192.168.1.5:2015/csv/sf-5/lineitem.tbl.2', 'http://192.168.1.6:2015/csv/sf-5/lineitem.tbl.3', 'http://192.168.1.7:2015/csv/sf-5/lineitem.tbl.4', 'http://192.168.1.4:2015/csv/sf-5/lineitem.tbl.5', 'http://192.168.1.5:2015/csv/sf-5/lineitem.tbl.6', 'http://192.168.1.6:2015/csv/sf-5/lineitem.tbl.7', 'http://192.168.1.7:2015/csv/sf-5/lineitem.tbl.8') WITH temp = 'http://192.168.1.4:2015,192.168.1.5:2015,192.168.1.6:2015,192.168.1.7:2015/import-temp', delimiter = '|', distributed, transform_only;
pq: unexpected error: different nodes with the same address: [3 2] and %!d(MISSING) (we've been trying to track this particular issue down; please report your reproduction at https://github.com/cockroachdb/cockroach/issues/12876)
```

**Comment by RaduBerinde** [comment]
![image](https://user-images.githubusercontent.com/16544120/30172793-c74dec22-93c3-11e7-9297-c677a87c70a8.png)

n2 and n3 indeed look like they have the same address (though n2 doesn't look live in gossip). Possibly some misconfiguration? We should either detect this and fail earlier or handle it gracefully in distsql.

**Comment by a-robinson** [comment]
Looks like this problem is CSV-specific. The normal DistSQL code path nicely health-checks and version-checks nodes before planning on them:

https://github.com/cockroachdb/cockroach/blob/1700c4060c9c830dc1f038a15f20ab15f8aeb753/pkg/sql/distsql_physical_planner.go#L896-L906

The CSV code, on the other hand, uses a different code path that just grabs all nodes that have ever existed, including decommissioned nodes, seemingly without doing any checks on them:

https://github.com/cockroachdb/cockroach/blob/1700c4060c9c830dc1f038a15f20ab15f8aeb753/pkg/ccl/importccl/csv.go#L927-L935

https://github.com/cockroachdb/cockroach/blob/1700c4060c9c830dc1f038a15f20ab15f8aeb753/pkg/sql/distsql_plan_csv.go#L215-L219

Passing back to @mjibson since this doesn't appear to be a gossip-related issue and I'm not super familiar with the code paths involved.

**Comment by andreimatei** [comment]
Ah, missed the part where both repros were for imports. Good catch.

**Comment by SJAnderson** [comment]
@andreimatei just got this. it happened after i rebooted my server and my PD SSD didn't attach itself before my daemon started cockroach again.
