### ISSUE TITLE
stability: cyan wedged on no leaseholder for system config range after restart

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#12966]
Going from 9e0824e to 05b9ea7 (and a subsequent upgrade to cff695a), `cyan` started behaving massively differently.

restart times:
```
I170114 02:00:43.811762 1 cli/start.go:322  CockroachDB 9e0824e (linux amd64, built 2017/01/14 00:58:08, go1.7.4)
I170117 19:00:30.229094 1 cli/start.go:325  CockroachDB 05b9ea7 (linux amd64, built 2017/01/17 18:14:17, go1.7.4)
I170118 02:00:28.344176 1 cli/start.go:325  CockroachDB cff695a (linux amd64, built 2017/01/18 01:36:04, go1.7.4)
```

some concrete differences (seen both on grafana and the admin UI):
* a lot of `cyan` metrics went from being relevant to exporting zeroes:
![cyan_replicas](https://cloud.githubusercontent.com/assets/5901480/22067549/c3375de6-dd5f-11e6-8f4f-2b8377c1eafa.png)
![cyan_replicas_admin](https://cloud.githubusercontent.com/assets/5901480/22067600/f87fbb60-dd5f-11e6-9a44-cfe335d60c54.png)

* sql QPS dropped (same load)
![cyan_sql](https://cloud.githubusercontent.com/assets/5901480/22067644/21f6bd04-dd60-11e6-8e0b-05baadfa3c5f.png)
![cyan_sql_admin](https://cloud.githubusercontent.com/assets/5901480/22067645/21f78400-dd60-11e6-8eca-ad6c36bdd900.png)

All nodes are currently up. Poking some more.

**Comment by mberhault** [comment]
Interestingly, `cobalt` was wiped and upgraded to cff695a overnight (the latest sha running on `cyan`), but looks normal.

side note: `cyan` auto-deploy is paused.

**Comment by a-robinson** [comment]
#12557 looks most suspicious out of the things that went in between cyan pushes. but It's strange that cobalt is happier after its deploy last night than before. cc @andreimatei for any theories

**Comment by mberhault** [comment]
except this is after 05b9ea7, which is the first sha to experience these problems.
that PR was picked up as part of the cff695a deploy which came a few hours later

**Comment by bdarnell** [comment]
Not much to see between those two commits: https://github.com/cockroachdb/cockroach/compare/9e0824e...05b9ea7

**Comment by mberhault** [comment]
all nodes are failing to compute metrics due to `system config not yet available`, which also explains queues being at zero.

First node to restart (`104.209.248.59`) shows:
```
I170117 19:00:30.229094 1 cli/start.go:325  CockroachDB 05b9ea7 (linux amd64, built 2017/01/17 18:14:17, go1.7.4)
W170117 19:00:34.761620 116 storage/store.go:1308  [n1,s1] error gossiping system config: [NotLeaseHolderError] range 10: replica {1 1 1} not lease holder; lease holder unknown
I170117 19:00:34.766322 15 storage/store.go:1250  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
```

**Comment by mberhault** [comment]
so I don't think this is a regression, just restart-induced-wedginess.

**Comment by mberhault** [comment]
here's the log on the first node (seemingly the leaseholder for r10 at the time of restart):
```
I170117 19:00:16.264032 132 server/status/runtime.go:228  runtime stats: 5.5 GiB RSS, 420 goroutines, 238 MiB/206 MiB/590 MiB GO alloc/idle/total, 3.9 GiB/5.0 GiB CGO alloc/total, 43957.63cgo/sec, 2.26/0.36 %(u/s)time, 0.01 %gc (9x)
I170117 19:00:22.705697 1 cli/start.go:431  received signal 'terminated'
I170117 19:00:22.710011 1 cli/start.go:456  initiating graceful shutdown of server
E170117 19:00:22.907712 1 cli/start.go:478  received signal 'terminated' during shutdown, initiating hard shutdown
Error: received signal 'terminated' during shutdown, initiating hard shutdown
Failed running "start"
I170117 19:00:30.229094 1 cli/start.go:325  CockroachDB 05b9ea7 (linux amd64, built 2017/01/17 18:14:17, go1.7.4)
I170117 19:00:30.229888 1 cli/start.go:134  writing go and jemalloc memory profiles to /home/cockroach/logs every 10s
I170117 19:00:30.330594 15 cli/start.go:356  starting cockroach node
I170117 19:00:30.330639 15 cli/start.go:358  using local environment variables: COCKROACH_CONSISTENCY_CHECK_PANIC_ON_FAILURE, COCKROACH_MEMPROF_INTERVAL, COCKROACH_ENABLE_RULE_SOLVER, COCKROACH_LIGHTSTEP_TOKEN
W170117 19:00:30.333509 15 gossip/gossip.go:1138  [n?] no incoming or outgoing connections
I170117 19:00:30.338322 15 storage/engine/rocksdb.go:326  opening rocksdb instance at "/mnt/data1"
I170117 19:00:31.340045 74 vendor/google.golang.org/grpc/clientconn.go:766  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.1.5:26257: getsockopt: connection refused"; Reconnecting to {192.168.1.5:26257 <nil>}
W170117 19:00:31.340187 72 gossip/client.go:119  [n?] failed to start gossip client to 192.168.1.5:26257: rpc error: code = 14 desc = grpc: the connection is unavailable
I170117 19:00:32.133456 15 server/config.go:456  1 storage engine initialized
I170117 19:00:32.340113 74 vendor/google.golang.org/grpc/clientconn.go:766  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.1.5:26257: getsockopt: connection refused"; Reconnecting to {192.168.1.5:26257 <nil>}
I170117 19:00:32.340576 44 vendor/google.golang.org/grpc/clientconn.go:766  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.1.6:26257: getsockopt: connection refused"; Reconnecting to {192.168.1.6:26257 <nil>}
W170117 19:00:32.340620 42 gossip/client.go:119  [n1] failed to start gossip client to 192.168.1.6:26257: rpc error: code = 14 desc = grpc: the connection is unavailable
I170117 19:00:33.141438 74 vendor/google.golang.org/grpc/clientconn.go:766  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.1.5:26257: getsockopt: connection refused"; Reconnecting to {192.168.1.5:26257 <nil>}
I170117 19:00:33.340574 44 vendor/google.golang.org/grpc/clientconn.go:766  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.1.6:26257: getsockopt: connection refused"; Reconnecting to {192.168.1.6:26257 <nil>}
I170117 19:00:33.341051 61 vendor/google.golang.org/grpc/clientconn.go:766  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.1.7:26257: getsockopt: connection refused"; Reconnecting to {192.168.1.7:26257 <nil>}
W170117 19:00:33.341343 59 gossip/client.go:119  [n1] failed to start gossip client to 192.168.1.7:26257: rpc error: code = 14 desc = grpc: the connection is unavailable
I170117 19:00:34.341117 61 vendor/google.golang.org/grpc/clientconn.go:766  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.1.7:26257: getsockopt: connection refused"; Reconnecting to {192.168.1.7:26257 <nil>}
I170117 19:00:34.341381 99 vendor/google.golang.org/grpc/clientconn.go:766  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.1.8:26257: getsockopt: connection refused"; Reconnecting to {192.168.1.8:26257 <nil>}
W170117 19:00:34.341439 65 gossip/client.go:119  [n1] failed to start gossip client to 192.168.1.8:26257: rpc error: code = 14 desc = grpc: the connection is unavailable
I170117 19:00:34.487396 44 vendor/google.golang.org/grpc/clientconn.go:766  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.1.6:26257: getsockopt: connection refused"; Reconnecting to {192.168.1.6:26257 <nil>}
W170117 19:00:34.756312 15 storage/store.go:861  [n1] storeMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Store).Start for 2.620705734s (>100ms):
goroutine 15 [running]:
runtime/debug.Stack(0x1e03a50, 0x1e03a90, 0x3b)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/syncutil.ThresholdLogger.func1(0x9c34cbc6)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:67 +0xe1
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*TimedMutex).Unlock(0xc4208ae658)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:97 +0xb6
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Start(0xc4208ae380, 0x7fc576bff138, 0xc420127dd0, 0xc42000c120, 0xc4203bd1f0, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1141 +0x498
github.com/cockroachdb/cockroach/pkg/server.(*Node).initStores(0xc4201dcf00, 0x7fc576bff138, 0xc420127dd0, 0xc420887aa0, 0x1, 0x1, 0xc42000c120, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:424 +0x209
github.com/cockroachdb/cockroach/pkg/server.(*Node).start(0xc4201dcf00, 0x7fc576bff138, 0xc420127dd0, 0x2564180, 0xc420448320, 0xc420887aa0, 0x1, 0x1, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:346 +0x11d
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start(0xc420237400, 0x7fc576bff138, 0xc420127dd0, 0xc42042bcc0, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:598 +0xdcd
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1.1(0x7fc576bff138, 0xc4201274d0, 0xc4201360c8, 0xc42000c120, 0xc420512150, 0x257ac60, 0xc42012a5a0, 0x19a6b9c, 0x7, 0x1b99968, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:375 +0x241
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1(0x7fc576bff138, 0xc4201274d0, 0xc4201360c8, 0xc42000c120, 0xc420512150, 0x257ac60, 0xc42012a5a0, 0x19a6b9c, 0x7, 0x1b99968, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:417 +0xb2
created by github.com/cockroachdb/cockroach/pkg/cli.runStart
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:420 +0x857
W170117 19:00:34.761620 116 storage/store.go:1308  [n1,s1] error gossiping system config: [NotLeaseHolderError] range 10: replica {1 1 1} not lease holder; lease holder unknown
I170117 19:00:34.766322 15 storage/store.go:1250  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170117 19:00:34.770737 15 server/node.go:439  [n1] initialized store [n1,s1]: {Capacity:211242639360 Available:72010973184 RangeCount:2209 LeaseCount:0}
I170117 19:00:34.770794 15 server/node.go:324  [n1] node ID 1 initialized
I170117 19:00:34.771008 15 gossip/gossip.go:292  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"cockroach-cyan-01:26257" > attrs:<> locality:<>
I170117 19:00:34.771327 15 storage/stores.go:296  [n1] read 5 node addresses from persistent storage
I170117 19:00:34.771722 15 server/node.go:571  [n1] connecting to gossip network to verify cluster ID...
I170117 19:00:34.771775 15 server/node.go:595  [n1] node connected via gossip and verified as part of cluster "a1480eb8-3ab4-4576-9fae-c20d71a39122"
I170117 19:00:34.771834 15 server/node.go:374  [n1] node=1: started with [[]=/mnt/data1] engine(s) and attributes []
I170117 19:00:34.773023 15 sql/executor.go:322  [n1] creating distSQLPlanner with address {tcp cockroach-cyan-01:26257}
I170117 19:00:34.775407 15 server/server.go:629  [n1] starting https server at cockroach-cyan-01:8080
I170117 19:00:34.775443 15 server/server.go:630  [n1] starting grpc/postgres server at cockroach-cyan-01:26257
I170117 19:00:34.775464 15 server/server.go:631  [n1] advertising CockroachDB node at cockroach-cyan-01:26257
I170117 19:00:34.789351 67 gossip/client.go:125  [n1] started gossip client to 192.168.1.4:26257
I170117 19:00:34.789647 67 gossip/client.go:130  [n1] closing client to node 1 (192.168.1.4:26257): stopping outgoing client to node 1 (192.168.1.4:26257); loopback connection
```

It seems we determine we have an unknown lease holder before starting anything, then stay in that state.

**Comment by petermattis** [comment]
I thought @spencerkimball fixed a bug recently where we would re-gossip the system config every time the lease was reacquired. Did that get broken somehow?

**Comment by mberhault** [comment]
@spencerkimball is going to check the code for system config gossip.
Wiping cyan (running low on disk) and re-enabling continuous deployment.
