### ISSUE TITLE
gossip: too many nodes (4) in nodeSet

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12979]
Just saw this crash on `delta` running a custom binary (with no changes to gossip) based on 4af2bb46f9f5a873ca5a24b525c3c61930e60499:

`F170118 19:33:59.298072 121 gossip/node_set.go:147  too many nodes (4) in nodeSet (maxSize=3); gossip logic is broken: &{nodes:map[4:{} 2:{} 8:{}] placeholders:1 maxSize:3 gauge:0xc4203d86e0}`

Wasn't doing anything special, just restarting the cluster.

**Comment by a-robinson** [comment]
Ack, looks like I just missed the fact that we were willing to try opening so many connections during bootstrap. I don't think the fix should be terrible, but it'll take a little while to think through and put together a test for it and I'm going to be offline for a while starting at 3.

Do you need this to move forward with testing? If so, I'd recommend removing the `log.Fatal`s in `gossip/node_set.go`. They didn't account for this behavior and may need to be removed as the real fix anyway to ensure that bootstrapping can work properly.

**Comment by a-robinson** [comment]
For posterity (i.e. me in a couple hours), the relevant stack trace is:

```
F170118 19:33:59.298072 121 gossip/node_set.go:147  too many nodes (4) in nodeSet (maxSize=3); gossip logic is broken: &{nodes:map[4:{} 2:{} 8:{}] placeholders:1 maxSize:3 gauge:0xc4203d86e0}
goroutine 121 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x1, 0x11c439a3, 0x298e520, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:849 +0xa5
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x298fb80, 0xc400000004, 0x2194e4a, 0x12, 0x93, 0xc420c83d40, 0x8b)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:714 +0x784
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7fcc6b961208, 0xc42000e2f8, 0x1b00000004, 0x2, 0x19695a2, 0x48, 0xc4211ffab8, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:146 +0x296
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7fcc6b961208, 0xc42000e2f8, 0x1, 0xc400000004, 0x19695a2, 0x48, 0xc4211ffab8, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:88 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x7fcc6b961208, 0xc42000e2f8, 0x19695a2, 0x48, 0xc4211ffab8, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/pkg/gossip.(*nodeSet).updateGauge(0xc42063a1a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/gossip/node_set.go:147 +0x1e9
github.com/cockroachdb/cockroach/pkg/gossip.(*nodeSet).addPlaceholder(0xc42063a1a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/gossip/node_set.go:127 +0x36
github.com/cockroachdb/cockroach/pkg/gossip.(*client).start(0xc4212ec300, 0xc42063a180, 0xc42015b080, 0xc42046cf80, 0xc42033b680, 0xc420c83b00)
        /go/src/github.com/cockroachdb/cockroach/pkg/gossip/client.go:88 +0x35
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).startClientLocked(0xc42063a180, 0x24b2a00, 0xc420b44140)
        /go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1240 +0x306
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).bootstrap.func1.1()
        /go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1018 +0x4f6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask(0xc42033b680, 0xc4211ffe40, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:224 +0x100
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).bootstrap.func1()
        /go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1030 +0x173
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42033b680, 0xc420208980)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
```
