### ISSUE TITLE
storage: span use after call to Finish()

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13039]
`blue-01` ran out of disk space and shortly after panicked with this error:

```
log: exiting because of error: write /home/cockroach/logs/cockroach.cockroach-blue-01.root.2017-01-21
T14_25_37Z.014032.INFO.log: no space left on device
panic: span used after call to Finish():
&{tracer:<nil> event:0xda93a0 Mutex:{state:0 sema:0} raw:{Context:{TraceID:4520504264690132216 SpanID
:9074158976196420569 Sampled:false Baggage:map[]} ParentSpanID:0 Operation:server start Start:{sec:63
620527919 nsec:352895538 loc:0x29f7ec0} Duration:24680193386 Tags:map[] Logs:[]} numDroppedLogs:0}

goroutine 28 [running]:
panic(0x17e5400, 0xc4343434c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go.(*spanImpl).maybeAssertSanityLocked(0xc42044a140)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go/debug.go:31 +0x341
github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go.(*spanImpl).Lock(0xc42044a140)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go/debug.go:25 +0x3f
github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go.(*spanImpl).LogFields(0xc42044a140, 0xc430e49fc0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/opentracing/basictracer-go/span.go:123 +0xd3
github.com/cockroachdb/cockroach/pkg/util/tracing.(*TeeSpan).LogFields(0xc4204401e0, 0xc430e49fc0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tee_tracer.go:183 +0x73
github.com/cockroachdb/cockroach/pkg/util/log.eventInternal(0x7fb371cfadc0, 0xc420442120, 0xc42cdb0000, 0x1979f14, 0x8, 0xc423705d00, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:132 +0x4bc
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7fb371cfadc0, 0xc420442120, 0x7fb300000002, 0x2, 0x199ae9d, 0x22, 0xc423705ef0, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:145 +0x249
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7fb371cfadc0, 0xc420
```

The panic stack trace looks truncated. Not sure if there is anything actionable here, but clearly we have an error path that is misusing a span, presumably somewhere in the `storage` package.

**Comment by RaduBerinde** [comment]
Bummer that we don't have more of thee stack trace.. I assume it's too late to look for that trace/span in lightstep.

**Comment by petermattis** [comment]
You can try looking on lightstep, but since the process crashed right away it might not have been uploaded.

**Comment by dianasaur323** [comment]
@petermattis is this something you still want to look at before 1.0?

**Comment by petermattis** [comment]
No, I don't think there is anything actionable here.
