### ISSUE TITLE
backup: TestBackupRestoreRandomDataRoundtrips crashes with Pebble invariants turned on

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#133142]
https://github.com/cockroachdb/cockroach/pull/133113

https://mesolite.cluster.engflow.com/invocations/default/7a127137-3ec7-4cc4-8d8a-3ace4f4a21eb?treeFilterStatus=failed#targets-Ly9wa2cvY2NsL2JhY2t1cGNjbC9iYWNrdXByYW5kOmJhY2t1cHJhbmRfdGVzdA==

```
=== RUN   TestBackupRestoreRandomDataRoundtrips
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestBackupRestoreRandomDataRoundtrips1653288402
    test_log_scope.go:76: use -show-logs to present logs inline
    backup_rand_test.go:139: Verifying table "ta\rbLe_1"
    backup_rand_test.go:139: Verifying table "tab l_e_2"
    backup_rand_test.go:139: Verifying table "tabl\\fe_3"
    backup_rand_test.go:139: Verifying table "table_4"
    backup_rand_test.go:139: Verifying table "ta\rbLe_1"
    backup_rand_test.go:139: Verifying table "tab l_e_2"
    backup_rand_test.go:139: Verifying table "tabl\\fe_3"
    backup_rand_test.go:139: Verifying table "table_4"
    backup_rand_test.go:139: Verifying table "ta\rbLe_1"
    backup_rand_test.go:139: Verifying table "tab l_e_2"
    backup_rand_test.go:139: Verifying table "tabl\\fe_3"
    backup_rand_test.go:139: Verifying table "table_4"
    backup_rand_test.go:139: Verifying table "ta\rbLe_1"
    backup_rand_test.go:139: Verifying table "tab l_e_2"
    backup_rand_test.go:139: Verifying table "tabl\\fe_3"
    backup_rand_test.go:139: Verifying table "table_4"
    backup_rand_test.go:216: Testing subset backup/restore table_4
    backup_rand_test.go:139: Verifying table "table_4"
    backup_rand_test.go:229: combo 1 [table_4]
    backup_rand_test.go:216: Testing subset backup/restore "tabl\fe_3"
    backup_rand_test.go:139: Verifying table "tabl\\fe_3"
    backup_rand_test.go:229: combo 2 [tabl\fe_3]
    backup_rand_test.go:216: Testing subset backup/restore "tabl\fe_3", table_4
    backup_rand_test.go:139: Verifying table "tabl\\fe_3"
    backup_rand_test.go:139: Verifying table "table_4"
    backup_rand_test.go:229: combo 3 [tabl\fe_3 table_4]
    backup_rand_test.go:216: Testing subset backup/restore "tab l_e_2"
    backup_rand_test.go:139: Verifying table "tab l_e_2"
    backup_rand_test.go:229: combo 4 [tab l_e_2]
    backup_rand_test.go:216: Testing subset backup/restore "tab l_e_2", table_4
    backup_rand_test.go:139: Verifying table "tab l_e_2"
    backup_rand_test.go:139: Verifying table "table_4"
    backup_rand_test.go:229: combo 5 [tab l_e_2 table_4]
    backup_rand_test.go:216: Testing subset backup/restore "tab l_e_2", "tabl\fe_3"
    backup_rand_test.go:139: Verifying table "tab l_e_2"
    backup_rand_test.go:139: Verifying table "tabl\\fe_3"
panic: runtime error: slice bounds out of range [:247358465] with capacity 18432
	panic: Release called on a BufferPool with in-use buffers
goroutine 16122 [running]:
github.com/cockroachdb/pebble/sstable/block.(*BufferPool).Release(0xc00965a9c8)
	github.com/cockroachdb/pebble/sstable/block/external/com_github_cockroachdb_pebble/sstable/block/buffer_pool.go:172 +0xc5
panic({0x6b28920?, 0xc007fea7b0?})
	GOROOT/src/runtime/panic.go:770 +0x132
github.com/cockroachdb/pebble/sstable/rowblk.(*Iter).readEntry(0xc0057ce800?)
	github.com/cockroachdb/pebble/sstable/rowblk/external/com_github_cockroachdb_pebble/sstable/rowblk/rowblk_iter.go:386 +0x466
github.com/cockroachdb/pebble/sstable/rowblk.(*Iter).Next(0xc002cdf4a8)
	github.com/cockroachdb/pebble/sstable/rowblk/external/com_github_cockroachdb_pebble/sstable/rowblk/rowblk_iter.go:1077 +0x116
github.com/cockroachdb/pebble/sstable/rowblk.(*Iter).SeekGE(0xc002cdf4a8, {0xc0094c0098, 0x4, 0x8}, 0x1?)
	github.com/cockroachdb/pebble/sstable/rowblk/external/com_github_cockroachdb_pebble/sstable/rowblk/rowblk_iter.go:694 +0x64d
github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).seekGEHelper(0x89722e0, {0xc0094c0098, 0x4, 0x8}, 0x0, 0x0)
	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:842 +0x24a
github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).SeekGE(0x89722e0, {0xc0094c0098, 0x4?, 0x8?}, 0x0?)
	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:747 +0x194
github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).First(0x0?)
	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:1175 +0x2e
github.com/cockroachdb/pebble.(*levelIter).skipEmptyFileForward(0xc004bd7408)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:829 +0x34
github.com/cockroachdb/pebble.(*levelIter).Next(0xc004bd7408)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:767 +0x9a
github.com/cockroachdb/pebble.(*mergingIter).nextEntry(0xc009aa66c0, 0xc003316048, {0x0?, 0x19?, 0xc0049a43f8?})
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:541 +0x27b
github.com/cockroachdb/pebble.(*mergingIter).Next(0xc009aa66c0)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1189 +0x51
github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).nextPos(0xc006044510)
	github.com/cockroachdb/pebble/internal/keyspan/external/com_github_cockroachdb_pebble/internal/keyspan/interleaving_iter.go:646 +0x8f
github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).Next(0xc006044510)
	github.com/cockroachdb/pebble/internal/keyspan/external/com_github_cockroachdb_pebble/internal/keyspan/interleaving_iter.go:478 +0xe5
github.com/cockroachdb/pebble/internal/compact.(*Iter).iterNext(0xc006044308)
	github.com/cockroachdb/pebble/internal/compact/external/com_github_cockroachdb_pebble/internal/compact/iterator.go:668 +0x2e
github.com/cockroachdb/pebble/internal/compact.(*Iter).nextInStripeHelper(0xc006044308)
	github.com/cockroachdb/pebble/internal/compact/external/com_github_cockroachdb_pebble/internal/compact/iterator.go:714 +0x3d
github.com/cockroachdb/pebble/internal/compact.(*Iter).nextInStripe(...)
	github.com/cockroachdb/pebble/internal/compact/external/com_github_cockroachdb_pebble/internal/compact/iterator.go:705
github.com/cockroachdb/pebble/internal/compact.(*Iter).setNext(0xc006044308)
	github.com/cockroachdb/pebble/internal/compact/external/com_github_cockroachdb_pebble/internal/compact/iterator.go:803 +0x27b
github.com/cockroachdb/pebble/internal/compact.(*Iter).Next(0xc006044308)
	github.com/cockroachdb/pebble/internal/compact/external/com_github_cockroachdb_pebble/internal/compact/iterator.go:577 +0xf7d
github.com/cockroachdb/pebble/internal/compact.(*Runner).writeKeysToTable(0xc0049a5708, {0x88a73a0, 0xc009aea008})
	github.com/cockroachdb/pebble/internal/compact/external/com_github_cockroachdb_pebble/internal/compact/run.go:179 +0x4e6
github.com/cockroachdb/pebble/internal/compact.(*Runner).WriteTable(0xc0049a5708, {0x52, 0x2, {0x0, 0x0, {0x0, 0x0}, 0x0, {0x0, 0x0}, ...}}, ...)
	github.com/cockroachdb/pebble/internal/compact/external/com_github_cockroachdb_pebble/internal/compact/run.go:143 +0x1ca
github.com/cockroachdb/pebble.(*DB).compactAndWrite(0xc0055fe488, 0x82, 0xc00965a908, {0x0, 0x0, 0x0}, 0x6)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:2913 +0x706
github.com/cockroachdb/pebble.(*DB).runCompaction(0xc0055fe488, 0x82, 0xc00965a908)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:2808 +0x5cd
github.com/cockroachdb/pebble.(*DB).compact1(0xc0055fe488, 0xc00965a908, 0x0)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:2252 +0x19e
github.com/cockroachdb/pebble.(*DB).compact.func1({0x8833378?, 0xc00a321710?})
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:2166 +0xa7
runtime/pprof.Do({0x8833218?, 0xd1eddc0?}, {{0xc001335e40?, 0x137b4e0?, 0x87dd180?}}, 0xc0054fbf88)
	GOROOT/src/runtime/pprof/runtime.go:51 +0x9d
github.com/cockroachdb/pebble.(*DB).compact(0x137b008?, 0x707e68e?, 0xc0054fbf98?)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:2163 +0x65
created by github.com/cockroachdb/pebble.(*DB).tryScheduleAutoCompaction in goroutine 16113
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:1845 +0x42b
```

Jira issue: CRDB-43467

**Comment by RaduBerinde** [comment]
No longer an issue (https://github.com/cockroachdb/cockroach/pull/138251 passed CI)
