### ISSUE TITLE
sql: postgres jdbc doesn't work with BACKUP

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#13326]
The following program panics CockroachDB with the `org.postgresql:postgresql:9.4.1212` jar, but the statement works fine from both `cockroach sql` and `psql`.

```
import java.sql.*;

public class Test {
    public static void main(String[] args) throws Exception {
        Class.forName("org.postgresql.Driver");
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:postgresql://127.0.0.1:26257/system?sslmode=disable", "root", "");
            conn.createStatement().executeQuery("BACKUP DATABASE system TO '/tmp/foo'");
        } finally {
            if (conn != null) { conn.close(); }
        }
    }
}
```

logs from CockroachDB
```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 598 [running]:
panic(0x52edc80, 0xc420012110)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4203a63f0)
	/Users/dan/Dropbox/Projects/crl1/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x52edc80, 0xc420012110)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc420413600, 0x7c9a980, 0xc420a754d0)
	/Users/dan/Dropbox/Projects/crl1/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:340 +0x74
panic(0x52edc80, 0xc420012110)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).sendResponse(0xc420413600, 0x7c9a980, 0xc420a754d0, 0xc4208dd9f0, 0x1, 0x1, 0x62cae40, 0x0, 0x0, 0x531c600, ...)
	/Users/dan/Dropbox/Projects/crl1/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:953 +0x6f9
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc420413600, 0x7c9a980, 0xc420a754d0, 0xc42085702c, 0x24, 0xc420e2b470, 0x62cae40, 0x0, 0x0, 0xc42016fa00, ...)
	/Users/dan/Dropbox/Projects/crl1/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:822 +0x202
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc420413600, 0x7c9a980, 0xc420a754d0, 0xc420413628, 0x9, 0x0)
	/Users/dan/Dropbox/Projects/crl1/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:799 +0x20a
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420413600, 0x7c9a980, 0xc420a754d0, 0xc420b259b0, 0x5400, 0xc420328138, 0x7c9a980, 0xc420a754a0, 0x0, 0x0)
	/Users/dan/Dropbox/Projects/crl1/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:442 +0xaea
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420328000, 0x7c9a980, 0xc420a754a0, 0x5da64c0, 0xc420a653f0, 0x0, 0x0)
	/Users/dan/Dropbox/Projects/crl1/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:308 +0xa22
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x5da64c0, 0xc420a653f0)
	/Users/dan/Dropbox/Projects/crl1/src/github.com/cockroachdb/cockroach/pkg/server/server.go:527 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4203a63f0, 0xc420136130, 0x5da64c0, 0xc420a653f0, 0xc420ab0000)
	/Users/dan/Dropbox/Projects/crl1/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/Users/dan/Dropbox/Projects/crl1/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

**Comment by danhhz** [comment]
I suspect it has something to do with `hookFnNode` but had trouble connecting the dots. @knz, do you know what the issue is? I'm happy to make the fix, but there's a lot of code between this panic and planNode that I'm not familiar with

**Comment by dt** [comment]
This might be my doing... it's the formatCodes picking to send the correct format for each datum.

**Comment by knz** [comment]
yes, that looks like it.

**Comment by dt** [comment]
I haven't dug in, but I'm guessing the difference is that JDBC is doing a prepare/exec cycle, using exercising the "portal" codepath -- the simple text query path just passes `nil` to the formatCols and thus doesn't attempt to grab format codes from it. If so, then this should also reproduce via one of the other drivers that uses prepare/exec, and the issue is probably that the hook install just isn't setting up the right number of cols.

**Comment by danhhz** [comment]
I have a fix locally that I've verified works with my java program. @knz before I start digging, any pointers to how I'd write a test for this?

**Comment by knz** [comment]
The only place remotely related that I can think of is TestPGPreparedQuery (and TestPGPrepareFail) in `sql/pgwire_test.go`.
