### ISSUE TITLE
o11y: /api/v2/login 500 http response in roachtest

### ISSUE THREAD

**Issue by kyle-a-wong** [cockroachdb/cockroach#133493]
**Describe the problem**

In a roachtest that creates a single node cluster, requests to `POST /api/v2/login/` frequently returns a 500 status code response. This happens on both local and non local runs. 

**To Reproduce**

To reproduce, make a test as follows:
```
func registerDbConsole(r registry.Registry) {
	r.Add(registry.TestSpec{
		Name:             "db-console/login",
		Owner:            registry.OwnerObservability,
		Cluster:          r.MakeClusterSpec(1),
		CompatibleClouds: registry.AllClouds,
		Suites:           registry.Suites(registry.Nightly),
		Randomized:       false,
		Run:              runDbConsoleLogin,
		Timeout:          1 * time.Hour,
	})
}

func runDbConsoleLogin(ctx context.Context, t test.Test, c cluster.Cluster) {
	c.Start(ctx, t.L(), option.DefaultStartOpts(), install.MakeClusterSettings())
	node := c.Node(1)
	version, _ := fetchCockroachVersion(ctx, t.L(), c, node[0])
	t.L().Printf("cockroach version: %s", version)

	internalAdminUIAddrs, _ := c.InternalAdminUIAddr(ctx, t.L(), node)
	url := fmt.Sprintf("https://%s/api/v2/login/?username=user&password=pw", internalAdminUIAddrs[0])
	out, _ := exec.Command("curl", "--request", "POST", "-k", url).Output()
	sOut := string(out)
	require.False(t, strings.Contains(string(out), "internal server error"))
}
```

**Expected behavior**
This test should pass and the output from the curl request should be: `the provided credentials did not match any account on the server`

**Additional data / screenshots**
Error logs in the server contain the following:
```
E241025 20:06:50.196764 2737 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 257  a panic has occurred!
E241025 20:06:50.196764 2737 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 257 +use of Span after Finish. Span: ‹/cockroach.roachpb.Internal/Batch›. Finish previously called at: ‹goroutine 2368 [running]:›
E241025 20:06:50.196764 2737 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 257 +(1) attached stack trace
E241025 20:06:50.196764 2737 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 257 +  -- stack trace:
E241025 20:06:50.196764 2737 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 257 +  | runtime.gopanic
E241025 20:06:50.196764 2737 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 257 +  | 	GOROOT/src/runtime/panic.go:770
...
```
The error is always a panic due to `use of Span after Finish` but its not always the same span. 
**Environment:**
I tested both locally built off master and with a v24.2.3 binary 

**Additional context**
This only seems the happen when the cluster has 1 node. If I update the test registration to: `r.MakeClusterSpec(4)` it works as expected. I also tried making a single node cluster via roachprod and manually doing the same curl request and there were no errors.

Jira issue: CRDB-43646

**Comment by kyle-a-wong** [comment]
the mixed-version test in https://github.com/cockroachdb/cockroach/pull/133855 run's into this issue, even when the cluster has 5 nodes (4 of which are used in the mixed-version cluster)
