### ISSUE TITLE
sql: panic when using non-supported SAVEPOINTs

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#13545]
To reproduce:

```
[14:21:1]% cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257> begin transaction;
BEGIN
root@:26257> savepoint p;
driver: bad connection
```

Server log:

```
I170212 14:21:12.837921 197 sql/executor.go:538  [client=[::1]:52259,user=root,n1] execRequest: savepoint p;
I170212 14:21:12.838012 197 sql/executor.go:864  [client=[::1]:52259,user=root,n1] executing 1/1: SAVEPOINT p
I170212 14:21:12.838078 197 sql/executor.go:677  [client=[::1]:52259,user=root,n1] execRequest: error: SAVEPOINT not supported except for COCKROACH_RESTART
F170212 14:21:12.838175 197 sql/executor.go:708  [client=[::1]:52259,user=root,n1] got a non-retryable error but the KV transaction is not finalized. TxnState: Open, err: SAVEPOINT not supported except for COCKROACH_RESTART
err:SAVEPOINT not supported except for COCKROACH_RESTART

txn: "sql txn" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000000,0 orig=1486927272.837984555,0 max=0.000000000,0 wto=false rop=false
goroutine 197 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0, 0x31f58cdd, 0x639a1a0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:853 +0xa5
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x639b740, 0xc400000004, 0x5dc12ef, 0xf, 0x2c4, 0xc420499a00, 0x198)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:716 +0x7a8
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7eac180, 0xc42043c420, 0xc400000004, 0x2, 0x5564bad, 0x69, 0xc4208dd178, 0x4, 0x4)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:146 +0x296
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7eac180, 0xc42043c420, 0x1, 0xc400000004, 0x5564bad, 0x69, 0xc4208dd178, 0x4, 0x4)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:66 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x7eac180, 0xc42043c420, 0x5564bad, 0x69, 0xc4208dd178, 0x4, 0x4)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:150 +0x7e
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc42031a180, 0xc420847b00, 0xc420910013, 0xc, 0x0, 0x0, 0x0, 0x0, 0xc4208dd300)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:708 +0xfaa
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc42031a180, 0xc420847b00, 0xc420910013, 0xc, 0x0, 0x0, 0x0, 0x0, 0xc420910000)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:479 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc4208ace00, 0x7eac180, 0xc42017be90, 0xc420910013, 0xc, 0x0, 0x0, 0x0, 0x0, 0x455c401, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:813 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc4208ace00, 0x7eac180, 0xc42017be90, 0xc4208ace28, 0x11, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:491 +0xb3
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc4208ace00, 0x7eac180, 0xc42017be90, 0xc4207da5c0, 0x5400, 0xc420188150, 0x9340908, 0xc420907cc0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:419 +0x8de
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420188000, 0x9340908, 0xc420907cc0, 0x5ea72c0, 0xc4202294a0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:415 +0xa2c
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x5ea72c0, 0xc4202294a0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:533 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4203f2d80, 0xc420156170, 0x5ea72c0, 0xc4202294a0, 0xc4208264c0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

**Comment by tschottdorf** [comment]
I ran into this too and wasted time diagnosing this, and so will many others trying out an unsupported ORM, so would be good to fix.
