### ISSUE TITLE
sql: CockroachDB panics on a date vs timestamptz comparison.

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#13692]
Running the following query causes CockroachDB to panic(!) and die:

```
select
	n_name,
	sum(l_extendedprice * (1 - l_discount)) as revenue
from
	customer,
	orders,
	lineitem,
	supplier,
	nation,
	region
where
	c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and l_suppkey = s_suppkey
	and c_nationkey = s_nationkey
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'AFRICA'
	and o_orderdate >= date '1997-01-01'
	and o_orderdate < date '1997-01-01' + interval '1' year
group by
	n_name
order by
	revenue desc;
```

on a TPC-H dataset (PR incoming) causes the following panic:

```
./cockroach start
CockroachDB node starting at 2017-02-21 14:02:13.581244892 -0500 EST
build:      CCL f3c82c667 @ 2017/02/21 16:21:47 (go1.7.3)
admin:      http://localhost:8080
sql:        postgresql://root@localhost:26257?sslmode=disable
logs:       cockroach-data/logs
store[0]:   path=cockroach-data
status:     restarted pre-existing node
clusterID:  efbc7704-1c75-4857-b407-e4b4a3dd373f
nodeID:     1
panic: unsupported comparison: date to timestamptz [recovered]
	panic: select
	n_name,
	sum(l_extendedprice * (1 - l_discount)) as revenue
from
	customer,
	orders,
	lineitem,
	supplier,
	nation,
	region
where
	c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and l_suppkey = s_suppkey
	and c_nationkey = s_nationkey
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'AFRICA'
	and o_orderdate >= date '1997-01-01'
	and o_orderdate < date '1997-01-01' + interval '1' year
group by
	n_name
order by
	revenue desc;
: unsupported comparison: date to timestamptz [recovered]
	panic: select
	n_name,
	sum(l_extendedprice * (1 - l_discount)) as revenue
from
	customer,
	orders,
	lineitem,
	supplier,
	nation,
	region
where
	c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and l_suppkey = s_suppkey
	and c_nationkey = s_nationkey
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'AFRICA'
	and o_orderdate >= date '1997-01-01'
	and o_orderdate < date '1997-01-01' + interval '1' year
group by
	n_name
order by
	revenue desc;
: unsupported comparison: date to timestamptz [recovered]
	panic: select
	n_name,
	sum(l_extendedprice * (1 - l_discount)) as revenue
from
	customer,
	orders,
	lineitem,
	supplier,
	nation,
	region
where
	c_custkey = o_custkey
	and l_orderkey = o_orderkey
	and l_suppkey = s_suppkey
	and c_nationkey = s_nationkey
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'AFRICA'
	and o_orderdate >= date '1997-01-01'
	and o_orderdate < date '1997-01-01' + interval '1' year
group by
	n_name
order by
	revenue desc;
: unsupported comparison: date to timestamptz

goroutine 837 [running]:
panic(0x538f1c0, 0xc420df4bb0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42038e090)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:198 +0x6e
panic(0x538f1c0, 0xc420df4bb0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc42016c400, 0xa0b1f40, 0xc421098180)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:340 +0x74
panic(0x538f1c0, 0xc420df4bb0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc421159000, 0x1d5)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:473 +0x149
panic(0x5340ea0, 0xc420df4b90)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/parser.(*DDate).Compare(0xc421139e50, 0x5f07560, 0xc420a704c0, 0xc4210a6b60)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/parser/datum.go:914 +0x120
github.com/cockroachdb/cockroach/pkg/sql.simplifyOneAndExpr(0x5f00e00, 0xc420e20d80, 0x5f00e00, 0xc420e20e00, 0x1, 0xc420a70f40, 0x2, 0x2, 0x5f02300)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:382 +0xb11
github.com/cockroachdb/cockroach/pkg/sql.simplifyAndExpr(0xc42122e6f0, 0x5f07740, 0x64294d0, 0x5f02300)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:273 +0x2d9
github.com/cockroachdb/cockroach/pkg/sql.simplifyExpr(0x5f00aa0, 0xc42122e6f0, 0xc420351800, 0x46a57bf, 0xc4212861f0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:145 +0x264
github.com/cockroachdb/cockroach/pkg/sql.analyzeExpr(0x5f00aa0, 0xc42122e6f0, 0x4, 0xc420a70ee0, 0x0, 0x4)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:49 +0x42
github.com/cockroachdb/cockroach/pkg/sql.(*planner).selectIndex(0xc421042160, 0xc420cb4000, 0x0, 0x6429400, 0x0, 0x38, 0xc42025fc20, 0xc421282008)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:125 +0x10d1
github.com/cockroachdb/cockroach/pkg/sql.expandScanNode(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc420cb4000, 0x5f035c0, 0x18, 0x20, 0xc420a70ea0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:279 +0xea
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x5f05060, 0xc420cb4000, 0xc421282000, 0x0, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:230 +0x665
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x5f04ee0, 0xc420970460, 0x5f05060, 0xc421282000, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:119 +0x188c
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x5f04ee0, 0xc420970620, 0xc42122da10, 0xc420e71440, 0xc4210a7910, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:123 +0x1927
github.com/cockroachdb/cockroach/pkg/sql.expandRenderNode(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc420ca78c0, 0xc420e71530, 0x34, 0x0, 0xc42122ddda)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:290 +0xbd
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x5f05000, 0xc420ca78c0, 0x5ee230a, 0x5f05000, 0xc420ca78c0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:233 +0x29b4
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0xc421139f20, 0x1, 0x1, 0x5f04d60, 0xc420e31080, 0x16, 0xc4210a7d68, 0x4413dcf, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:181 +0x243c
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0xc421042160, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x5f050c0, 0xc420a58fd0, 0xa000000, 0x0, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:200 +0x1d13
github.com/cockroachdb/cockroach/pkg/sql.(*planner).expandPlan(0xc421042160, 0x5f050c0, 0xc420a58fd0, 0x5f050c0, 0xc420a58fd0, 0x0, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:34 +0x73
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optimizePlan(0xc421042160, 0x5f050c0, 0xc420a58fd0, 0xc420df4020, 0x2, 0x2, 0x1, 0x5f050c0, 0xc420a58fd0, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/optimize.go:38 +0xd7
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc421042160, 0x5efd180, 0xc4210986c0, 0xc41b12b601, 0x63f2160, 0xc4210a8110, 0x4379402, 0xed03e85fa)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:204 +0x12b
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc420142300, 0x5efd180, 0xc4210986c0, 0xc421042160, 0xc4210a0001, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1363 +0xa3
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc420142300, 0x5efd180, 0xc4210986c0, 0xc421042160, 0x101, 0xc421042068, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1153 +0x2a5
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc420142300, 0xc421017ad0, 0x1, 0x1, 0xc421042160, 0xc421042068, 0x101, 0x6, 0x6, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:891 +0x7cb
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc420142300, 0xc421042160, 0x1, 0xc421042068, 0xc421017b20, 0xc421017ad0, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:805 +0xf8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func2(0xc420ab8780, 0xc421017b20, 0x0, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:644 +0x2b7
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc420ab8780, 0xc420f20101, 0xc420222240, 0xc420f228c0, 0xc400000000, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:511 +0x1c4
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420142300, 0xc421042000, 0xc421159000, 0x1d5, 0x0, 0x0, 0x0, 0x0, 0xc4213f1300)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:666 +0x5e3
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420142300, 0xc421042000, 0xc421159000, 0x1d5, 0x0, 0x0, 0x0, 0x0, 0xc421159000)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:479 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc42016c400, 0xa0b1f40, 0xc421098180, 0xc421159000, 0x1d5, 0x0, 0x0, 0x0, 0x0, 0x4566601, ...)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:813 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc42016c400, 0xa0b1f40, 0xc421098180, 0xc42016c428, 0x1da, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:491 +0xb3
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc42016c400, 0xa0b1f40, 0xc421098180, 0xc4210172a0, 0x5400, 0xc42017c150, 0xa0b2100, 0xc420d35a80, 0x0, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:419 +0x8de
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42017c000, 0xa0b2100, 0xc420d35a80, 0x5f05780, 0xc420fa8d10, 0x0, 0x0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:415 +0xa2c
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x5f05780, 0xc420fa8d10)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/server/server.go:536 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc42038e090, 0xc42002c108, 0x5f05780, 0xc420fa8d10, 0xc420b8d3a0)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

I am unable to construct a more minimal example. Doing things like
```
SELECT now()::date < now()::timestamptz;
+--------------------------------+
| now()::DATE < now()::TIMESTAMP WITH TIME ZONE |
+--------------------------------+
| true                           |
+--------------------------------+
```
seems to work fine. cc @cuongdo, but I'm investigating this myself for a bit.

**Comment by arjunravinarayan** [comment]
Found another query that panics, and it's less verbose:

```
select
	sum(l_extendedprice * l_discount) as revenue
from
	lineitem
where
	l_shipdate >= date '1997-01-01'
	and l_shipdate < date '1997-01-01' + interval '1' year
	and l_discount between 0.07 - 0.01 and 0.07 + 0.01
	and l_quantity < 24;
```

**Comment by mjibson** [comment]
Interestingly, this passes:

```
> SELECT '2001-01-01'::DATE < '2001-01-01 00:00:00'::TIMESTAMP WITH TIME ZONE;
+--------------------------------+
| '2001-01-01'::DATE < '2001-01-01 00:00:00'::TIMESTAMP WITH TIME ZONE |
+--------------------------------+
| false                          |
+--------------------------------+
```

So the comparison can happen, just seems to have problems when the comparison involves row data. Do these operations not use the same code path? I haven't looked more, just am curious about why the above succeeds.

**Comment by nvanbenschoten** [comment]
The issue here is that when de756be added support for mixed type comparisons between date types, it missed adding the associated logic to the [`Datum.Compare`](https://github.com/cockroachdb/cockroach/blob/8fe4d6d588c94cc8b3079158d4e23ef871c797f7/pkg/sql/parser/datum.go#L910) methods like we have for [numeric types](https://github.com/cockroachdb/cockroach/blob/8fe4d6d588c94cc8b3079158d4e23ef871c797f7/pkg/sql/parser/datum.go#L302). The fact that that was necessary is a complete mess, and I'm working on a fix that merges `CmpOps` in with the `Datum.Compare` method. This requires a bit of grossness because we'll need to thread an `EvalContext` in a bunch of places, and it will probably inspire us to split `Datum.Compare` from `Datum.EncodedCompare` because there are a few instances (like `NaN::FLOAT`) where the logical comparator is not the same as the encoded key comparator. Still, it shouldn't be too bad.
