### ISSUE TITLE
Node unresponsive after other node gets offline

### ISSUE THREAD

**Issue by bauerj** [cockroachdb/cockroach#13942]
I have two cockroachdb nodes, one of which went offline. The other one is still active but doesn't respond to SQL queries. I expected it would still work when one of the nodes fails.

The web interface on the remaining node looks like this:

![image](https://cloud.githubusercontent.com/assets/598790/23655183/4c4c9f20-0334-11e7-9d45-0d3e93f248f4.png)

Calls to `/_admin/v1/health` return `node not in the liveness table`.

Log output:
```
root@helicarrier:/cockroach# grep -F '[config]' cockroach-data/logs/cockroach.INFO
I170307 11:41:21.974009 1 util/log/clog.go:999  [config] file created at: 2017/03/07 11:41:21
I170307 11:41:21.974009 1 util/log/clog.go:999  [config] running on machine: helicarrier
I170307 11:41:21.974009 1 util/log/clog.go:999  [config] binary: CockroachDB CCL beta-20170216 (linux amd64, built 2017/02/16 13:45:12, go1.7.5)
I170307 11:41:21.974009 1 util/log/clog.go:999  [config] arguments: [/cockroach/cockroach start --advertise-host=helicarrier.bauerj.eu --ca-cert=/tls/ca.cert --cert=/tls/helicarrier.cert --key=/tls/helicarrier.key --join=moonraker.bauerj.eu]
```

```
root@helicarrier:/cockroach/cockroach-data/logs# cat cockroach.ERROR
E170307 11:41:23.634322 104 util/log/clog.go:999  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
E170307 11:41:23.634320 104 server.go:2315  http: TLS handshake error from 94.211.186.214:28735: EOF
E170307 11:41:23.644216 108 server.go:2315  http: TLS handshake error from 94.211.186.214:28738: EOF
E170307 11:41:23.648747 109 server.go:2315  http: TLS handshake error from 94.211.186.214:28736: EOF
E170307 11:41:23.653401 110 server.go:2315  http: TLS handshake error from 94.211.186.214:28737: EOF
E170307 11:41:33.799030 130 server.go:523  http2: server: error reading preface from client 95.211.186.214:28744: timeout waiting for client preface
E170307 11:41:33.802761 132 server.go:523  http2: server: error reading preface from client 95.211.186.214:28745: timeout waiting for client preface
E170307 11:41:33.807293 134 server.go:523  http2: server: error reading preface from client 95.211.186.214:28746: timeout waiting for client preface
E170307 11:41:36.958938 309 server.go:2315  http: TLS handshake error from 94.211.186.214:28756: EOF
E170307 11:41:42.096865 393 server.go:2315  http: TLS handshake error from 94.211.186.214:28765: EOF
E170307 11:41:53.804204 148 server/admin.go:769  context deadline exceeded
E170307 11:41:53.804217 148 server/admin.go:849  rpc error: code = 13 desc = An internal server error has occurred. Please check your CockroachDB logs for more details.
E170307 11:42:24.543361 519 server/admin.go:769  context deadline exceeded
E170307 11:42:24.543375 519 server/admin.go:849  rpc error: code = 13 desc = An internal server error has occurred. Please check your CockroachDB logs for more details.
E170307 11:42:54.583415 864 server/admin.go:769  context deadline exceeded
E170307 11:42:54.583433 864 server/admin.go:849  rpc error: code = 13 desc = An internal server error has occurred. Please check your CockroachDB logs for more details.
```

```
root@helicarrier:/cockroach/cockroach-data/logs# cat cockroach.FATAL
F170307 11:41:21.625924 16 util/log/clog.go:999  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
F170307 11:41:21.625875 16 server/server.go:769  [n2] failed to get list of completed migrations: node unavailable; try another peer
goroutine 16 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0, 0x254e199c, 0x2cb3160, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:853 +0xa5
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2cb47a0, 0xc400000004, 0x247821e, 0x10, 0x301, 0xc4216100c0, 0x53)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:716 +0x7a8
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f591af4b4e8, 0xc4203d36b0, 0x4, 0x2, 0x0, 0x0, 0xc420abf5e8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:146 +0x296
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f591af4b4e8, 0xc4203d36b0, 0x1, 0xc400000004, 0x0, 0x0, 0xc420abf5e8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:66 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x7f591af4b4e8, 0xc4203d36b0, 0xc420abf5e8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:159 +0x76
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start(0xc4201c0900, 0x7f591af4b4e8, 0xc4203d36b0, 0xc420231ac0, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:769 +0x2407
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1.1(0x7f591af4b4e8, 0xc4203ef2f0, 0xc420022030, 0xc4200741b0, 0xc420012650, 0x27e8400, 0xc4203eb720, 0xc4203e9b90, 0xfb96ce, 0x2d05760)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:378 +0x241
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1(0x7f591af4b4e8, 0xc4203ef2f0, 0xc420022030, 0xc4200741b0, 0xc420012650, 0x27e8400, 0xc4203eb720, 0xc4203e9b90, 0xc42000dce0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:420 +0x8d
created by github.com/cockroachdb/cockroach/pkg/cli.runStart
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:423 +0x99d
```

**Comment by bauerj** [comment]
The other node just went back online and suddenly both started working again.

This is what's in the logs after the connection was re-established:

**Server that was online**
```
root@helicarrier:/cockroach/cockroach-data/logs# cat cockroach.ERROR
E170307 11:59:54.269922 1248 server/status.go:388  [n2,status] context deadline exceeded
E170307 11:59:54.319547 1255 server/admin.go:709  context deadline exceeded
E170307 11:59:58.334981 83 storage/queue.go:628  [replicate,n2,s2,r88/2:/System/tsd/cr.node.sql.mon.c…,@c4201b9c00] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 11:59:58.530364 83 storage/queue.go:628  [replicate,n2,s2,r131/2:/System/tsd/cr.node.sql.mon.i…,@c4206b2380] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 11:59:58.751435 83 storage/queue.go:628  [replicate,n2,s2,r151/2:/System/tsd/cr.node.sys.…,@c4206b3500] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 11:59:58.950531 83 storage/queue.go:628  [replicate,n2,s2,r162/2:/System/tsd/cr.node.sql.mon.…,@c4203b0e00] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 11:59:59.132204 83 storage/queue.go:628  [replicate,n2,s2,r163/2:/System/tsd/cr.node.sql.laten…,@c4202c5880] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 11:59:59.332065 83 storage/queue.go:628  [replicate,n2,s2,r112/2:/System/tsd/cr.store.intentby…,@c42069e000] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 11:59:59.532457 83 storage/queue.go:628  [replicate,n2,s2,r168/2:/System/tsd/cr.node.distsende…,@c42014dc00] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 11:59:59.735436 83 storage/queue.go:628  [replicate,n2,s2,r81/2:/System/tsd/cr.node.sql.mon.i…,@c4206b2000] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 11:59:59.932863 83 storage/queue.go:628  [replicate,n2,s2,r130/2:/System/tsd/cr.node.txn.resta…,@c4202c9500] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 12:00:00.137292 83 storage/queue.go:628  [replicate,n2,s2,r21/2:/Table/5{0-1},@c420755500] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 12:00:00.333539 83 storage/queue.go:628  [replicate,n2,s2,r105/2:/System/tsd/cr.node.sql.mon.c…,@c4201b9500] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 12:00:00.535696 83 storage/queue.go:628  [replicate,n2,s2,r90/2:/System/tsd/cr.store.r{a…-e…},@c4207f5180] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 12:00:00.734129 83 storage/queue.go:628  [replicate,n2,s2,r100/2:/System/tsd/cr.node.sys.fd.op…,@c4206b3880] range requires a replication change, but lacks a quorum of live replicas (0/2)
```

```
root@helicarrier:/cockroach/cockroach-data/logs# cat cockroach.INFO
I170307 11:59:55.522393 1375 gossip/client.go:131  [n2] started gossip client to moonraker.bauerj.eu:26257
I170307 11:59:55.537907 1375 gossip/client.go:136  [n2] closing client to node 1 (moonraker.bauerj.eu:26257): stopping outgoing client to node 1 (moonraker.bauerj.eu:26257); already have incoming
I170307 11:59:55.543461 1459 gossip/client.go:131  [n2] started gossip client to moonraker.bauerj.eu:26257
I170307 11:59:55.558752 1459 gossip/client.go:136  [n2] closing client to node 1 (moonraker.bauerj.eu:26257): stopping outgoing client to node 1 (moonraker.bauerj.eu:26257); already have incoming
I170307 11:59:56.548944 1488 gossip/client.go:131  [n2] started gossip client to moonraker.bauerj.eu:26257
I170307 11:59:56.564791 1488 gossip/client.go:136  [n2] closing client to node 1 (moonraker.bauerj.eu:26257): stopping outgoing client to node 1 (moonraker.bauerj.eu:26257); already have incoming
I170307 11:59:57.399210 1497 storage/raft_transport.go:437  [n2] raft transport stream to node 1 established
I170307 11:59:57.554549 1505 gossip/client.go:131  [n2] started gossip client to moonraker.bauerj.eu:26257
I170307 11:59:57.570265 1505 gossip/client.go:136  [n2] closing client to node 1 (moonraker.bauerj.eu:26257): stopping outgoing client to node 1 (moonraker.bauerj.eu:26257); already have incoming
E170307 11:59:58.334981 83 storage/queue.go:628  [replicate,n2,s2,r88/2:/System/tsd/cr.node.sql.mon.c…,@c4201b9c00] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 11:59:58.530364 83 storage/queue.go:628  [replicate,n2,s2,r131/2:/System/tsd/cr.node.sql.mon.i…,@c4206b2380] range requires a replication change, but lacks a quorum of live replicas (0/2)
I170307 11:59:59.565437 1558 gossip/client.go:131  [n2] started gossip client to moonraker.bauerj.eu:26257
I170307 11:59:59.581120 1558 gossip/client.go:136  [n2] closing client to node 1 (moonraker.bauerj.eu:26257): stopping outgoing client to node 1 (moonraker.bauerj.eu:26257); already have incoming
E170307 11:59:59.735436 83 storage/queue.go:628  [replicate,n2,s2,r81/2:/System/tsd/cr.node.sql.mon.i…,@c4206b2000] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 11:59:59.932863 83 storage/queue.go:628  [replicate,n2,s2,r130/2:/System/tsd/cr.node.txn.resta…,@c4202c9500] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 12:00:00.137292 83 storage/queue.go:628  [replicate,n2,s2,r21/2:/Table/5{0-1},@c420755500] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 12:00:00.333539 83 storage/queue.go:628  [replicate,n2,s2,r105/2:/System/tsd/cr.node.sql.mon.c…,@c4201b9500] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170307 12:00:00.535696 83 storage/queue.go:628  [replicate,n2,s2,r90/2:/System/tsd/cr.store.r{a…-e…},@c4207f5180] range requires a replication change, but lacks a quorum of live replicas (0/2)
I170307 12:00:00.552543 1032 vendor/google.golang.org/grpc/server.go:723  grpc: Server.processUnaryRPC failed to write status: stream error: code = 4 desc = "context deadline exceeded"
I170307 12:00:00.570704 1657 gossip/client.go:131  [n2] started gossip client to moonraker.bauerj.eu:26257
I170307 12:00:00.586357 1657 gossip/client.go:136  [n2] closing client to node 1 (moonraker.bauerj.eu:26257): stopping outgoing client to node 1 (moonraker.bauerj.eu:26257); already have incoming
I170307 12:00:00.586394 35 gossip/gossip.go:1192  [n2] node has connected to cluster via gossip
I170307 12:00:00.586568 35 storage/stores.go:312  [n2] wrote 1 node addresses to persistent storage
E170307 12:00:00.734129 83 storage/queue.go:628  [replicate,n2,s2,r100/2:/System/tsd/cr.node.sys.fd.op…,@c4206b3880] range requires a replication change, but lacks a quorum of live replicas (0/2)
I170307 12:00:00.918744 86 storage/replica_raftstorage.go:414  [raftsnapshot,n2,s2,r107/2:/System/tsd/cr.store.queue.gc…,@c42069f880] generated Raft snapshot fa3a1e44 at index 287695
W170307 12:00:01.427233 100 storage/node_liveness.go:238  [n2,hb] slow heartbeat took 46.2s
I170307 12:00:02.329304 92 sql/event_log.go:95  [n2] Event: "node_restart", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:helicarrier.bauerj.eu:26257} Attrs: Locality:} ClusterID:9d83b5c1-2fed-4eb2-86c3-83d4ca05a7f8 StartedAt:1488887955198755495 LastUp:1488849448251976702}
I170307 12:00:02.823424 16 server/server.go:771  [n2] done ensuring all necessary migrations have run
I170307 12:00:02.823456 16 server/server.go:773  [n2] serving sql connections
I170307 12:00:05.202254 93 server/status/runtime.go:228  runtime stats: 175 MiB RSS, 455 goroutines, 50 MiB/31 MiB/97 MiB GO alloc/idle/total, 43 MiB/50 MiB CGO alloc/total, 1388.40cgo/sec, 0.07/0.03 %(u/s)time, 0.00 %gc (8x)
I170307 12:00:05.387991 86 storage/store.go:3312  [raftsnapshot,n2,s2,r107/2:/System/tsd/cr.store.queue.gc…,@c42069f880] streamed snapshot: kv pairs: 2051, log entries: 4, 4469ms
I170307 12:00:07.722855 86 storage/replica_raftstorage.go:414  [raftsnapshot,n2,s2,r123/2:/System/tsd/cr.node.sql.mon.a…,@c420221880] generated Raft snapshot 8201ead3 at index 231660
I170307 12:00:13.688159 86 storage/store.go:3312  [raftsnapshot,n2,s2,r123/2:/System/tsd/cr.node.sql.mon.a…,@c420221880] streamed snapshot: kv pairs: 2935, log entries: 2, 5965ms
I170307 12:00:13.970245 86 storage/replica_raftstorage.go:414  [raftsnapshot,n2,s2,r76/2:/System/tsd/cr.store.rocksdb.…,@c42080b180] generated Raft snapshot e9d36bb8 at index 482615
I170307 12:00:15.201321 91 gossip/gossip.go:438  [n2] gossip status (ok, 2 nodes)
```

**Server that was offline**

```
root@moonraker:/cockroach/cockroach-data/logs# cat cockroach.ERROR
E170307 12:00:01.755579 63 util/log/clog.go:999  [config] file created at: 2017/03/07 12:00:01
E170307 12:00:01.755579 63 util/log/clog.go:999  [config] running on machine: moonraker
E170307 12:00:01.755579 63 util/log/clog.go:999  [config] binary: CockroachDB CCL beta-20170216 (linux amd64, built 2017/02/16 13:45:12, go1.7.5)
E170307 12:00:01.755579 63 util/log/clog.go:999  [config] arguments: [/cockroach/cockroach start --advertise-host=moonraker.bauerj.eu --ca-cert=/tls/ca.cert --cert=/tls/moonraker.cert --key=/tls/moonraker.key]
E170307 12:00:01.755579 63 util/log/clog.go:999  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
E170307 12:00:01.755574 63 storage/queue.go:628  [replicate,n1,s1,r125/1:/System/tsd/cr.node.sql.laten…,@c42023a700] range requires a replication change, but lacks a quorum of live replicas (1/2)
```

```
root@moonraker:/cockroach/cockroach-data/logs# cat cockroach.INFO
I170307 11:59:50.195071 27 cli/start.go:359  starting cockroach node
I170307 11:59:50.596358 27 storage/engine/rocksdb.go:336  opening rocksdb instance at "cockroach-data"
I170307 11:59:53.818748 27 server/config.go:482  1 storage engine initialized
I170307 11:59:55.043887 27 storage/store.go:1261  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170307 11:59:55.044023 27 server/node.go:456  [n1] initialized store [n1,s1]: {Capacity:127524143104 Available:107867275264 RangeCount:116 LeaseCount:0}
I170307 11:59:55.044186 27 server/node.go:341  [n1] node ID 1 initialized
I170307 11:59:55.044486 27 gossip/gossip.go:293  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"moonraker.bauerj.eu:26257" > attrs:<> locality:<>
I170307 11:59:55.044907 27 storage/stores.go:296  [n1] read 1 node addresses from persistent storage
I170307 11:59:55.045308 27 server/node.go:605  [n1] connecting to gossip network to verify cluster ID...
I170307 11:59:55.115718 27 server/node.go:629  [n1] node connected via gossip and verified as part of cluster "9d83b5c1-2fed-4eb2-86c3-83d4ca05a7f8"
I170307 11:59:55.115866 27 server/node.go:391  [n1] node=1: started with [[]=cockroach-data] engine(s) and attributes []
I170307 11:59:55.116212 27 sql/executor.go:333  [n1] creating distSQLPlanner with address {tcp moonraker.bauerj.eu:26257}
I170307 11:59:55.138133 27 server/server.go:644  [n1] starting https server at moonraker:8080
I170307 11:59:55.138151 27 server/server.go:645  [n1] starting grpc/postgres server at moonraker:26257
I170307 11:59:55.138163 27 server/server.go:646  [n1] advertising CockroachDB node at moonraker.bauerj.eu:26257
I170307 11:59:55.513908 67 gossip/client.go:131  [n1] started gossip client to helicarrier.bauerj.eu:26257
I170307 11:59:57.410775 125 storage/raft_transport.go:437  [n1] raft transport stream to node 2 established
I170307 12:00:01.195027 27 server/server.go:771  [n1] done ensuring all necessary migrations have run
I170307 12:00:01.195073 27 server/server.go:773  [n1] serving sql connections
E170307 12:00:01.755574 63 storage/queue.go:628  [replicate,n1,s1,r125/1:/System/tsd/cr.node.sql.laten…,@c42023a700] range requires a replication change, but lacks a quorum of live replicas (1/2)
I170307 12:00:01.812777 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 16 KiB (+209)
I170307 12:00:01.813104 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 32 KiB (+179)
I170307 12:00:01.813390 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 64 KiB (+192)
I170307 12:00:01.813869 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 135 KiB (+9576)
I170307 12:00:01.855678 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 16 KiB (+209)
I170307 12:00:01.855819 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 32 KiB (+179)
I170307 12:00:01.856043 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 64 KiB (+192)
I170307 12:00:01.856513 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 135 KiB (+9576)
I170307 12:00:01.917589 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 16 KiB (+209)
I170307 12:00:01.917703 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 32 KiB (+179)
I170307 12:00:01.917940 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 64 KiB (+192)
I170307 12:00:01.918432 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 135 KiB (+9576)
I170307 12:00:01.936408 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 16 KiB (+209)
I170307 12:00:01.936513 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 32 KiB (+179)
I170307 12:00:01.936696 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 64 KiB (+192)
I170307 12:00:01.937090 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 135 KiB (+9576)
W170307 12:00:01.950907 79 storage/node_liveness.go:238  [n1,hb] slow heartbeat took 6.8s
I170307 12:00:01.954892 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 16 KiB (+209)
I170307 12:00:01.954990 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 32 KiB (+179)
I170307 12:00:01.955161 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 64 KiB (+192)
I170307 12:00:01.955573 212 sql/mon/mem_usage.go:510  [client=172.22.0.1:40878,user=labels,n1] txn: memory usage increases to 135 KiB (+9576)
I170307 12:00:02.230367 71 sql/event_log.go:95  [n1] Event: "node_restart", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:moonraker.bauerj.eu:26257} Attrs: Locality:} ClusterID:9d83b5c1-2fed-4eb2-86c3-83d4ca05a7f8 StartedAt:1488887995115730304 LastUp:1488849438106421750}
I170307 12:00:05.120661 69 storage/store.go:3965  [n1,s1] sstables (read amplification = 3):
0 [ 288K  1 ]: 288K
5 [  15M  4 ]: 8M 6M 1M 504K
6 [ 381M 14 ]: 100M[3] 37M 28M 15M 273K 197K 166K 163K 41K 40K 39K 21K
I170307 12:00:05.138438 72 server/status/runtime.go:228  runtime stats: 137 MiB RSS, 456 goroutines, 65 MiB/472 KiB/80 MiB GO alloc/idle/total, 22 MiB/29 MiB CGO alloc/total, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (13x)
I170307 12:00:05.398843 187 storage/replica_raftstorage.go:596  [n1,s1,r107/1:/System/tsd/cr.store.queue.gc…,@c420677880] applying Raft snapshot at index 287695 (id=fa3a1e44, encoded size=11606865, 12 rocksdb batches, 4 log entries)
I170307 12:00:07.636039 187 storage/replica_raftstorage.go:604  [n1,s1,r107/1:/System/tsd/cr.store.queue.gc…,@c420677880] applied Raft snapshot in 2237ms [clear=1930ms batch=197ms entries=0ms commit=110ms]
I170307 12:00:13.699059 863 storage/replica_raftstorage.go:596  [n1,s1,r123/1:/System/tsd/cr.node.sql.mon.a…,@c42008e000] applying Raft snapshot at index 231660 (id=8201ead3, encoded size=16623694, 16 rocksdb batches, 2 log entries)
I170307 12:00:13.962268 863 storage/replica_raftstorage.go:604  [n1,s1,r123/1:/System/tsd/cr.node.sql.mon.a…,@c42008e000] applied Raft snapshot in 263ms [clear=40ms batch=98ms entries=0ms commit=125ms]
I170307 12:00:15.137984 72 server/status/runtime.go:228  runtime stats: 305 MiB RSS, 92 goroutines, 15 MiB/84 MiB/110 MiB GO alloc/idle/total, 132 MiB/150 MiB CGO alloc/total, 42857.80cgo/sec, 0.51/0.24 %(u/s)time, 0.00 %gc (10x)
I170307 12:00:24.565398 39 gossip/gossip.go:1192  [n1] node has connected to cluster via gossip
I170307 12:00:24.566081 39 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I170307 12:00:25.138554 72 server/status/runtime.go:228  runtime stats: 280 MiB RSS, 92 goroutines, 57 MiB/48 MiB/116 MiB GO alloc/idle/total, 111 MiB/135 MiB CGO alloc/total, 334.08cgo/sec, 0.22/0.08 %(u/s)time, 0.00 %gc (4x)
I170307 12:00:27.541034 916 storage/replica_raftstorage.go:596  [n1,s1,r76/1:/System/tsd/cr.store.rocksdb.…,@c4206e5180] applying Raft snapshot at index 482615 (id=e9d36bb8, encoded size=40651110, 39 rocksdb batches, 2 log entries)
W170307 12:00:31.117211 916 storage/engine/rocksdb.go:1104  batch [4/715/44] commit took 611.785649ms (>500ms):
goroutine 916 [running]:
runtime/debug.Stack(0x1a0d420, 0x27ddb60, 0xc4200603e0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc422e74fc0, 0x0, 0x20, 0x7ff69259f268)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1104 +0x169
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applySnapshot(0xc4206e5180, 0x7ff69259f268, 0xc4206f26f0, 0x1e4ad130b86bd3e9, 0xde67edd1ce73d9b5, 0xc42348d800, 0x27, 0x40, 0xc4207720c0, 0x2, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raftstorage.go:670 +0xb30
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4206e5180, 0x1e4ad130b86bd3e9, 0xde67edd1ce73d9b5, 0xc42348d800, 0x27, 0x40, 0xc4207720c0, 0x2, 0x2, 0xc420243d40, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2660 +0x12ea
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc420180000, 0x7ff69259f268, 0xc420772120, 0xc420243e00, 0x1e4ad130b86bd3e9, 0xde67edd1ce73d9b5, 0xc42348d800, 0x27, 0x40, 0xc4207720c0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3122 +0xc97
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc420180000, 0xc420243d40, 0x7ff69255a938, 0xc422ee8c50, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2768 +0x5a3
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x27e7140, 0xc422ee8c50, 0xc420408af0, 0x7ff69259f268, 0xc420badda0, 0xc420404f38, 0xc420404f40)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:362 +0x182
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x7ff69259f268, 0xc420badda0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:363 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc42008cc60, 0x1b5f04f, 0x3, 0x1, 0x0, 0x0, 0xc420bade30, 0x7ff69259f268, 0xc420badda0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:283 +0xdf
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:284 +0x14a
I170307 12:00:31.118488 916 storage/replica_raftstorage.go:604  [n1,s1,r76/1:/System/tsd/cr.store.rocksdb.…,@c4206e5180] applied Raft snapshot in 3577ms [clear=2813ms batch=120ms entries=0ms commit=644ms]
I170307 12:00:35.140752 72 server/status/runtime.go:228  runtime stats: 428 MiB RSS, 83 goroutines, 77 MiB/36 MiB/123 MiB GO alloc/idle/total, 203 MiB/234 MiB CGO alloc/total, 749.97cgo/sec, 0.34/0.19 %(u/s)time, 0.00 %gc (0x)
I170307 12:00:45.138177 72 server/status/runtime.go:228  runtime stats: 357 MiB RSS, 315 goroutines, 30 MiB/77 MiB/123 MiB GO alloc/idle/total, 162 MiB/205 MiB CGO alloc/total, 664.85cgo/sec, 0.17/0.08 %(u/s)time, 0.00 %gc (7x)
I170307 12:00:55.117649 70 gossip/gossip.go:438  [n1] gossip status (ok, 2 nodes)

```

**Comment by petermattis** [comment]
@bauerj If you only have 2 nodes in your cluster, this is expected behavior, though the UI experience leaves a lot to be desired. CockroachDB uses quorum replication and requires a minimum of 3 nodes for fault tolerance. The UI should be doing a better job warning you if you're running a 2 node cluster and could also alert if 1 of those nodes goes away.

**Comment by bauerj** [comment]
Okay, that seems to be a misunderstanding on my side then. Thanks for the clarification!

I agree that a warning message would be a great idea.

**Comment by kuanluo** [comment]
@maxlang Could this be part of the warning work that you're tackling?

**Comment by mrtracy** [comment]
Related: #7813
