### ISSUE TITLE
sql: EXPLAIN (trace) UPSERT panic

### ISSUE THREAD

**Issue by yznming** [cockroachdb/cockroach#14061]
**Steps to Repro**
Create schema:
````
CREATE TABLE t1 (
id INT NULL,
name STRING NULL,
FAMILY "primary" (id, name, rowid)); 
````

Execute
````
explain(trace) upsert into t1 values(1, 'sfew');
````
Result: panic
````
panic: txn: unexpected leftover memory: 1076 bytes [recovered]
        panic: explain(trace) upsert into t1 values(1, 'sfew');: txn: unexpected leftover memory: 1076 bytes [recovered]
        panic: explain(trace) upsert into t1 values(1, 'sfew');: txn: unexpected leftover memory: 1076 bytes [recovered]
        panic: explain(trace) upsert into t1 values(1, 'sfew');: txn: unexpected leftover memory: 1076 bytes

goroutine 551 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42030df40)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:198 +0x6e
panic(0x1a902e0, 0xc421155fb0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc42012c000, 0x7f4c8d2d01b8, 0xc420e9c660)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:340 +0x74
panic(0x1a902e0, 0xc421155fb0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc420e970e6, 0x30)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:484 +0x131
panic(0x1a3ed20, 0xc421155f90)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/mon.(*MemoryMonitor).Stop(0xc420087b68, 0x7f4c8d2d01b8, 0xc4211bd530)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/mon/mem_usage.go:339 +0x24e
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).finishSQLTxn(0xc420087ae8, 0x7f4c8d2d0298, 0xc420b282c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:370 +0x4b
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420460000, 0xc420087a80, 0xc420e970e6, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:742 +0xc40
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420460000, 0xc420087a80, 0xc420e970e6, 0x30, 0x0, 0x0, 0x0, 0x0, 0xc420e97000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:490 +0x12d
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:490 +0x12d
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc42012c000, 0x7f4c8d2d01b8, 0xc420e9c660, 0xc420e970e6, 0x30, 0x0, 0x0, 0x0, 0x0, 0xa5bf01, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:819 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc42012c000, 0x7f4c8d2d01b8, 0xc420e9c660, 0xc42012c028, 0x35, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:491 +0xc9
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc42012c000, 0x7f4c8d2d01b8, 0xc420e9c660, 0xc420b7a250, 0x5400, 0xc42025e160, 0x7f4c8d2d0298, 0xc420b281c0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:419 +0x89b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42025e000, 0x7f4c8d2d0298, 0xc420b281c0, 0x28bed80, 0xc4201a94a0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:415 +0x917
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x28bed80, 0xc4201a94a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:544 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc42030df40, 0xc42000e040, 0x28bed80, 0xc4201a94a0, 0xc420ade080)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x239
````

**Comment by andreimatei** [comment]
The panic is not expected, but `EXPLAIN(TRACE) UPSERT ...` will not do what you want. `EXPLAIN(TRACE)` only works with `SELECT`s.

**Comment by yznming** [comment]
@andreimatei Got it. I meet it by accident while investigating another issue.

**Comment by justinj** [comment]
Hi @yznming! I'm having trouble reproducing this panic (on master, and going back to commits from early March), any chance you could see if it still happens for you? Thanks!

**Comment by justinj** [comment]
I'm going to close this issue for now, if you think it's still a problem please let me know and I'll reopen!
