### ISSUE TITLE
sql: node crash with explain

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#14238]
The node serving the request crashed if I try to explain a query on beta-20170309
```sql
CREATE TABLE Test (ID serial PRIMARY KEY, Date TimeStampTZ,INDEX date_idx (Date));
insert into Test (Date) values ('2017-03-17 15:33:00'::timestamptz);

explain select * from Test where Date >='2017-01-01 00:00:00'::TimeStamp;
```

The node will crash and in the log, I see
```
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 26996 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4203634a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:198 +0x6e
panic(0x1ab98e0, 0x2878ec0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc42209c200, 0x7f614d43acc0, 0xc4398842a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:340 +0x74
panic(0x1ab98e0, 0x2878ec0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).sendResponse(0xc42209c200, 0x7f614d43acc0, 0xc4398842a0, 0xc421790aa0, 0x1, 0x1, 0x2dd4cd8, 0x0, 0x0, 0xc4348a3600, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:961 +0x497
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc42209c200, 0x7f614d43acc0, 0xc4398842a0, 0xc4348a364d, 0x48, 0xc42683b518, 0x2dd4cd8, 0x0, 0x0, 0x1acd900, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:828 +0x202
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc42209c200, 0x7f614d43acc0, 0xc4398842a0, 0xc42209c228, 0x9, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:805 +0x19d
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc42209c200, 0x7f614d43acc0, 0xc4398842a0, 0xc429460620, 0x5400, 0xc4202e0160, 0x7f614d43ada0, 0xc42942d300, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:442 +0xa7b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4202e0000, 0x7f614d43ada0, 0xc42942d300, 0x28bed80, 0xc4261a2140, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:415 +0x917
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x28bed80, 0xc4261a2140)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:544 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4203634a0, 0xc42000e040, 0x28bed80, 0xc4261a2140, 0xc421194240)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x239
```

**Comment by knz** [comment]
Hello! Many thanks for your report.
The crash is happening when the database is trying to send a result back to the client, however I cannot see in the stack trace that the error is related to the EXPLAIN statement.
Also I just tried with your example and I cannot see the same error.

Can I ask you to run the server with the command-line flag `--vmodule=executor=2` and try again? Then send a copy of the INFO log together with the panic stack trace for further examination.

Thanks!

**Comment by leomkkwan** [comment]
Hi, Thank you for look into this. The Log file is attached.

You are right, if I try that from CLI, it works. It only crashed when I am using a GUI.

I am using DBeaver.

Thanks,

[cockroach.fdn1.root.2017-03-17T16_18_06-04_00.025848.INFO.log.txt](https://github.com/cockroachdb/cockroach/files/851674/cockroach.fdn1.root.2017-03-17T16_18_06-04_00.025848.INFO.log.txt)

**Comment by knz** [comment]
Thanks for the suggestion to use DBeaver. I was able to reproduce the crash. Now investigating.

**Comment by knz** [comment]
I have found the problem and created a fix. Hopefully it will be included in next week's beta.
Until then, note that only the EXPLAIN statement is affected. You can use the CLI for explain, and DBeaver for the other SQL statements.
