### ISSUE TITLE
rpc: 40% throughput hit with snappy compression enabled

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#14721]
Enabled snappy compression on `blue` and one of the nodes died after an hour or so. 

```
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 9 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4200a6640)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0x94
panic(0x1b36fc0, 0x294af20)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
bytes.(*Buffer).Write(0xc4592c5f80, 0xc45ce9c000, 0x12, 0x12adc, 0x0, 0x0, 0xc45ce9c012)
        /usr/local/go/src/bytes/buffer.go:138 +0xc9
github.com/cockroachdb/cockroach/vendor/github.com/golang/snappy.(*Writer).write(0xc463de9bf0, 0x0, 0
x0, 0x0, 0xc43a354000, 0xc45acbe3c0, 0x54)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/snappy/encode.go:249 +0x2ec
github.com/cockroachdb/cockroach/vendor/github.com/golang/snappy.(*Writer).Flush(0xc463de9bf0, 0xc42c
a6c330, 0x54)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/snappy/encode.go:272 +0x78
github.com/cockroachdb/cockroach/vendor/github.com/golang/snappy.(*Writer).Close(0xc463de9bf0, 0xc45a
cbe3c0, 0x54)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/snappy/encode.go:279 +0x2f
github.com/cockroachdb/cockroach/pkg/rpc.snappyCompressor.Do(0x2970fe0, 0xc4592c5f80, 0xc45acbe3c0, 0
x54, 0x54, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/snappy.go:32 +0x18d
github.com/cockroachdb/cockroach/pkg/rpc.(*snappyCompressor).Do(0x2e02110, 0x2970fe0, 0xc4592c5f80, 0xc45acbe3c0, 0x54, 0x54, 0x0, 0x0)
        <autogenerated>:30 +0x77
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.encode(0x2988760, 0x2e02110, 0x1c11360, 0xc42ca6c330, 0x297e260, 0x2e02110, 0xc4592c5f80, 0x0, 0x0, 0x69e992, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:289 +0x3d8
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*serverStream).SendMsg(0xc4357f4dc0, 0x1c11360, 0xc42ca6c330, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:574 +0x116
github.com/cockroachdb/cockroach/pkg/storage.(*multiRaftRaftMessageBatchServer).Send(0xc429d80260, 0xc42ca6c330, 0xc42ca6c330, 0xc44984ad70)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go:346 +0x49
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc4200bfc00, 0xe62)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3434 +0x1d3
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4203283f0, 0xc4200a6640)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:225 +0x24b
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4200a6640, 0xc42191e680)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:210 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:211 +0x66
```

**Comment by petermattis** [comment]
I re-enabled snappy compression on `blue` on Friday and it has been running without problem for over 24 hours.

The panic happened for the following chunk of code:

```
func (b *Buffer) Write(p []byte) (n int, err error) {
	b.lastRead = opInvalid
	m := b.grow(len(p))
	return copy(b.buf[m:], p), nil
}
```

In particular, the `copy` line is at `buffer.go:138`. Seems very unlikely there is a bug in this part of the standard library. I'm not sure what else could have happened.

**Comment by petermattis** [comment]
Still no reproduction of the panic. I did a small performance comparison on `blue` with compression enabled vs disabled. Enabling compressions caused a 40% throughput hit. Ouch!

I'm going to punt this issue to 1.1.

**Comment by bdarnell** [comment]
As noted in https://github.com/cockroachdb/cockroach/issues/15702#issuecomment-300014997, compression could really help with large commands such as those generated by DeleteRange or GC. These commands can be so large that the time it takes to transmit them over the network can lead to missed heartbeats. 

40% is a steep price to pay, though. It seems like we must be doing something wrong there.

**Comment by petermattis** [comment]
40% is suspiciously high given the benchmark numbers for how fast snappy can compress/decompress. I need to figure out what is going on.

**Comment by petermattis** [comment]
Probably worthwhile to figure out if there is overhead to a no-op gRPC compressor.

**Comment by bdarnell** [comment]
There's also an easy reduction in allocations to save the `snappy.Writer` in the `rpc.snappyCompressor` (and use its `Reset` method in `Do`).

**Comment by a-robinson** [comment]
Fixed by #15826

**Comment by a-robinson** [comment]
Is there a reason we didn't ever switch snappy compression to be on by default?

**Comment by petermattis** [comment]
No reason. We were just about to release 1.0 when we fixed the perf issue. Should probably enable it now.
