### ISSUE TITLE
storage: panic in timestamp cache request size vs. total bytes

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#14734]
This was in running `make stress` for `sql/TestParallel/subquery_retry_multinode` on team-city: https://teamcity.cockroachdb.com/viewLog.html?buildId=213618&buildTypeId=Cockroach_UnitTests_Test&tab=buildLog#_focus=940

It didn't show up on a subsequent 5m test run on team-city.

I did a code audit for any chance of locking misbehavior and ran a lengthy `make stressrace` to try and catch something I missed, but couldn't reproduce locally.

```
[23:12:42][Step 2/2] ERROR: a panic has occurred!
[23:12:42][Step 2/2] If no details are printed below, check the log file for details.
[23:12:42][Step 2/2] panic: bad reqSize: 330 < 880 [recovered]
[23:12:42][Step 2/2] 	panic: bad reqSize: 330 < 880 [recovered]
[23:12:42][Step 2/2] 	panic: bad reqSize: 330 < 880
[23:12:42][Step 2/2] 
[23:12:42][Step 2/2] goroutine 7406 [running]:
[23:12:42][Step 2/2] github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4226a8820)
[23:12:42][Step 2/2] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0x94
[23:12:42][Step 2/2] panic(0x1a8aa00, 0xc421d7f8c0)
[23:12:42][Step 2/2] 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
[23:12:42][Step 2/2] github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send.func1(0xc423d91528, 0xc423d915a0, 0x14b3dd9bb0a08dea, 0x0, 0xc423d91598, 0xc421ddac00)
[23:12:42][Step 2/2] 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2498 +0x224
[23:12:42][Step 2/2] panic(0x1a8aa00, 0xc421d7f8c0)
[23:12:42][Step 2/2] 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
[23:12:42][Step 2/2] github.com/cockroachdb/cockroach/pkg/storage.(*timestampCache).ExpandRequests(0xc420bc4fc0, 0x14b3dd9bb056cfb3, 0xc400000000)
[23:12:42][Step 2/2] 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/timestamp_cache.go:632 +0x612
[23:12:42][Step 2/2] github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyTimestampCache(0xc42155d800, 0xc4239ef030, 0xc420ad1400, 0x0)
[23:12:42][Step 2/2] 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1870 +0xeb
[23:12:42][Step 2/2] github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc42155d800, 0x2aea94217980, 0xc420ad1410, 0x14b3dd9bb056cfb3, 0x0, 0x500000005, 0x3, 0x1, 0x0, 0xc4202b7790, ...)
```

**Comment by petermattis** [comment]
Well that's definitely not supposed to happen which is why I added that assertion in the first place.

**Comment by petermattis** [comment]
Via code inspection I see there are a handful of places where new entry is added without adjusting `TimestampCache.bytes`.
