### ISSUE TITLE
storage: "panic: llrb: inverted range" when running tests with stressrace

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14827]
When running `make stressrace PKG=./storage/ STRESSFLAGS='-stderr -maxfails 1 -p 32'` on an azworker, I hit the following panic:

```
panic: llrb: inverted range

goroutine 55564 [running]:
github.com/cockroachdb/cockroach/vendor/github.com/biogo/store/llrb.(*Tree).DoRange(0xc4200b6b48, 0xc4213f5950, 0x3241200, 0xc42198cc90, 0x3241200, 0xc42198ccc0, 0x2204be0)
	/home/alex/go/src/github.com/cockroachdb/cockroach/vendor/github.com/biogo/store/llrb/llrb.go:505 +0x161
github.com/cockroachdb/cockroach/pkg/util/cache.(*OrderedCache).DoRange(0xc4200b6af0, 0xc4213f5b10, 0x2204be0, 0xc42068b720, 0x2204be0, 0xc42068b740, 0x1)
	/home/alex/go/src/github.com/cockroachdb/cockroach/pkg/util/cache/cache.go:428 +0x1d4
github.com/cockroachdb/cockroach/pkg/kv.(*rangeDescriptorCache).clearOverlappingCachedRangeDescriptors(0xc42135ea00, 0x7fcad19511b0, 0xc420e2e5d0, 0xc42059fe00, 0xc4213f5ba0, 0x67e83a)
	/home/alex/go/src/github.com/cockroachdb/cockroach/pkg/kv/range_cache.go:609 +0x53e
github.com/cockroachdb/cockroach/pkg/kv.(*rangeDescriptorCache).insertRangeDescriptorsLocked(0xc42135ea00, 0x7fcad19511b0, 0xc420e2e5d0, 0xc42059fe00, 0x1, 0x1, 0x0, 0xc42059fec0)
	/home/alex/go/src/github.com/cockroachdb/cockroach/pkg/kv/range_cache.go:547 +0xa5
github.com/cockroachdb/cockroach/pkg/kv.(*rangeDescriptorCache).lookupRangeDescriptorInternal.func3(0x0, 0x0, 0x0, 0x0)
	/home/alex/go/src/github.com/cockroachdb/cockroach/pkg/kv/range_cache.go:329 +0x409
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/singleflight.(*Group).doCall(0xc42135ea38, 0xc421585130, 0xc421f30600, 0x12, 0xc421aa2000)
	/home/alex/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/singleflight/singleflight.go:93 +0x4d
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/singleflight.(*Group).DoChan
```

We haven't seen this error in quite some time, since https://github.com/cockroachdb/cockroach/issues/6027. I've attached the full logs from the `stressrace` run here:

[llrb-panic.txt](https://github.com/cockroachdb/cockroach/files/914804/llrb-panic.txt)

**Comment by tamird** [comment]
#14835.
