### ISSUE TITLE
bank example crash after many instances of #1483

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1504]
I was running the bank example through nginx as a load balancer, and kept hitting #1483 and restarting nodes whenever I'd hit it. Eventually the bank app crashed:
```
F0625 11:56:07.658483   56660 bank.go:154] write too old: timestamp 1435247767.379851103,1 <= 1435247767.379851103,1
goroutine 18 [running]:
github.com/cockroachdb/cockroach/util/log.stacks(0xc2080ac201, 0x0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:886 +0xcd
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x4f2a5e0, 0x3, 0x4eb4950, 0x7, 0x9a, 0x0, 0xc2080ac240)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:758 +0x11b
github.com/cockroachdb/cockroach/util/log.AddStructured(0x0, 0x0, 0x3, 0x2, 0x0, 0x0, 0xc2080f7f40, 0x1, 0x1)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:37 +0x120
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x0, 0x0, 0xc2080f7f40, 0x1, 0x1)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/log/log.go:61 +0x82
github.com/cockroachdb/cockroach/util/log.Fatal(0xc2080f7f40, 0x1, 0x1)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/log/log.go:157 +0x75
main.(*Bank).continuouslyTransferMoney(0xc20801ed40, 0x64)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/examples/bank/bank.go:154 +0x313
created by main.main
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/examples/bank/bank.go:271 +0x47d
```
full trace: https://gist.github.com/tamird/0db6c3d16a8f31acf4d6

**Comment by tamird** [comment]
looks like this is fixed by #1512
