### ISSUE TITLE
cmd/allocsim gratuitous segfaults

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15184]
I was ready to blame the recent build changes, but it seems to reproduce even before them.

```
$ go run cmd/allocsim/main.go
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e02cb6]

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/cmd/internal/localcluster.(*Node).Kill(0x0)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/cmd/internal/localcluster/localcluster.go:434 +0x26
github.com/cockroachdb/cockroach/pkg/cmd/internal/localcluster.(*Cluster).Close(0xc4205f83f0)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/cmd/internal/localcluster/localcluster.go:139 +0x4c
panic(0x53fa720, 0x632a200)
	/Users/alex/go1.8/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/cmd/internal/localcluster.(*Node).Start(0xc42061a240)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/cmd/internal/localcluster/localcluster.go:410 +0x81f
github.com/cockroachdb/cockroach/pkg/cmd/internal/localcluster.(*Cluster).makeNode(0xc4205f83f0, 0x0, 0x7fff5fbffa60, 0x67, 0xc42037c0a0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/cmd/internal/localcluster/localcluster.go:196 +0x85e
github.com/cockroachdb/cockroach/pkg/cmd/internal/localcluster.(*Cluster).Start(0xc4205f83f0, 0x5598500, 0x8, 0x1, 0x7fff5fbffa60, 0x67, 0xc42037c010, 0x1, 0x1, 0x0, ...)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/cmd/internal/localcluster/localcluster.go:126 +0x36c
main.main()
	/Users/alex/cockroach/pkg/cmd/allocsim/main.go:510 +0xdee
exit status 2
```

It even panics printing the help text...

```
$ go run cmd/allocsim/main.go --help
Usage of /var/folders/0y/zlxqfzj16sgfrxt7p13jqxhw0000gn/T/go-build147236078/command-line-arguments/_obj/exe/main:
  -b int
    	block size (default 1000)
  -duration duration
    	how long to run the simulation for (default 2562047h47m16.854775807s)
  -f string
    	config file that specifies an allocsim workload (overrides -n)
  -log-backtrace-at value
    	when logging hits line file:N, emit a stack trace
  -log-dir value
    	if non-empty, write log files in this directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43e0265]

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/humanizeutil.(*BytesValue).String(0xc42037a350, 0x541ebc0, 0xc42037a350)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/util/humanizeutil/humanize.go:104 +0x25
flag.isZeroValue(0xc420014cc0, 0xc420013808, 0x7, 0x55c2450)
	/Users/alex/go1.8/src/flag/flag.go:395 +0x102
flag.(*FlagSet).PrintDefaults.func1(0xc420014cc0)
	/Users/alex/go1.8/src/flag/flag.go:469 +0x1b9
flag.(*FlagSet).VisitAll(0xc420072060, 0xc42020f3f0)
	/Users/alex/go1.8/src/flag/flag.go:325 +0x67
flag.(*FlagSet).PrintDefaults(0xc420072060)
	/Users/alex/go1.8/src/flag/flag.go:478 +0x4f
flag.PrintDefaults()
	/Users/alex/go1.8/src/flag/flag.go:501 +0x2d
flag.glob..func1()
	/Users/alex/go1.8/src/flag/flag.go:525 +0xc5
flag.commandLineUsage()
	/Users/alex/go1.8/src/flag/flag.go:963 +0x27
flag.(*FlagSet).usage(0xc420072060)
	/Users/alex/go1.8/src/flag/flag.go:826 +0x2f
flag.(*FlagSet).parseOne(0xc420072060, 0xbb0e570, 0x0, 0xa000005385e80)
	/Users/alex/go1.8/src/flag/flag.go:868 +0x200
flag.(*FlagSet).Parse(0xc420072060, 0xc42000c2b0, 0x1, 0x1, 0xc42020f7b8, 0x4013462)
	/Users/alex/go1.8/src/flag/flag.go:913 +0x60
flag.Parse()
	/Users/alex/go1.8/src/flag/flag.go:941 +0x72
main.main()
	/Users/alex/cockroach/pkg/cmd/allocsim/main.go:408 +0xa1
exit status 2
```

**Comment by a-robinson** [comment]
This wouldn't normally be big deal except that I want to test some lease rebalancing scoring tweaks to make thrashing less likely.

**Comment by tamird** [comment]
Naively, looks like I broke it in 888f68622fcc678040aee05f4e37f06be5a15778.

**Comment by a-robinson** [comment]
Looks likely.

I started out by looking into the help text crash first, which is a different problem. There's some weird linking funniness where the flags from the logs package are getting created but not initialized properly, which doesn't look like it should be possible. Specifically, the log file/dir size flags are being initialized with nil pointers for their values. This has been broken ever since they were added by 0b2ce71aaed9633ed23a0a1d10829e1d25618a7b (cc @knz). It's arguable that allocsim should just use the standard go log package rather than our fancy one.

**Comment by tamird** [comment]
I'd support that change.

**Comment by a-robinson** [comment]
Using the standard log package isn't gonna cut it, since allocsim imports a bunch of other packages that transitively import our log package.

**Comment by tamird** [comment]
Sad.
