### ISSUE TITLE
distsql: panic on "expected consecutive span pieces"

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#15249]
I upgraded `navy` this morning to 9873f30d6329393539af06b2993c9630cfa0ad8f

```
CockroachDB node starting at 2017-04-21 07:32:44.422000224 +0000 UTC
build:      CCL 9873f30 @ 2017/04/20 23:51:26 (go1.8.1)
admin:      https://cockroach-navy-0005:8080
sql:        postgresql://root@cockroach-navy-0005:26257?sslcert=certs%2Fclient.root.crt&sslkey=certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt
logs:       /home/cockroach/logs
store[0]:   path=/mnt/data1
status:     restarted pre-existing node
clusterID:  4adc89e4-f492-4d70-8723-aefc1adf3ac3
nodeID:     5
```

Two nodes died: `cockroach-navy-0005` and `cockroach-navy-0001` about 1.5/2 hours later:

from `cockroach-navy-0005`:
```
I170421 09:22:33.005883 118 storage/split_queue.go:109  [split,n5,s5,r1125/3:/Table/51/1/1{210213…-344219…}] splitting size=67108915 max=67108864
I170421 09:22:33.472210 118 storage/replica_command.go:2626  [split,n5,s5,r1125/3:/Table/51/1/1{210213…-344219…}] initiating a split of this range at key /Table/51/1/1277265556 [r1914]
F170421 09:22:33.649170 1110 sql/distsql_physical_planner.go:445  [client=127.0.0.1:59676,user=root,n5] expected consecutive span pieces [/Table/51/1/{671627989-806282654} /Table/51/1/12{10213070-77265556}] /Table/51/1/1{210213070-344219992}
goroutine 1110 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x401, 0x26b18d58, 0x2b64e40, 0xc42fb95340)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:837 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2b664a0, 0xc400000004, 0x242a135, 0x1f, 0x1bd, 0xc42fb95290, 0xaf)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:709 +0x52f
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f12078dc180, 0xc42c14e510, 0x7f1200000004, 0x2, 0x1afbb05, 0x26, 0xc42ad86c40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:146 +0x27b
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f12078dc180, 0xc42c14e510, 0x1, 0xc400000004, 0x1afbb05, 0x26, 0xc42ad86c40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:68 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x7f12078dc180, 0xc42c14e510, 0x1afbb05, 0x26, 0xc42ad86c40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:162 +0x7e
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).partitionSpans(0xc421248000, 0xc42ad88ce8, 0xc42ce8f5f0, 0x1, 0x1, 0x0, 0x0, 0xc42dab8000, 0x5, 0x8)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:445 +0x8f0
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createTableReaders(0xc421248000, 0xc42ad88ce8, 0xc422f0e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:554 +0x118
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createPlanForNode(0xc421248000, 0xc42ad88ce8, 0x27359e0, 0xc422f0e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1388 +0x811
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createPlanForNode(0xc421248000, 0xc42ad88ce8, 0x2735960, 0xc430c2d320, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1397 +0x8d8
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createPlanForNode(0xc421248000, 0xc42ad88ce8, 0x27357e0, 0xc4279d1560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1437 +0xc39
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).PlanAndRun(0xc421248000, 0x7f12078dc180, 0xc42c14e510, 0xc424a9d540, 0x27357e0, 0xc4279d1560, 0xc432cef300, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:338 +0x10a
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execDistSQL(0xc42005eea0, 0xc430627000, 0x27357e0, 0xc4279d1560, 0xc42ad8c398, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1352 +0x1b3
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc42005eea0, 0x272c980, 0xc42ce8f200, 0xc430627000, 0x0, 0x0, 0xc425f90100, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1504 +0x42c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc42005eea0, 0xc421036000, 0x272c980, 0xc42ce8f200, 0xc42a4d5130, 0xc42a000000, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1254 +0x471
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc42005eea0, 0xc421036000, 0xc42a4d5230, 0x1, 0x1, 0xc42a4d5130, 0x0, 0x0, 0x0, 0xc42ad8cb90, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:950 +0x818
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc42005eea0, 0xc421036000, 0xc42a4d5230, 0x1, 0x1, 0xc42a4d5130, 0x1, 0xc42a4d5248, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:858 +0xd1
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func1(0x7f12078dc180, 0xc42c14e510, 0xc424a9d540, 0xc42a4d5248, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:690 +0x216
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc424a9d540, 0x7f12078dc180, 0xc42c14e510, 0xc42a010000, 0xc43194f800, 0x1, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:612 +0xb6
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc42005eea0, 0xc421036000, 0xc4202b9ba5, 0x3a, 0xc42a4d5130, 0x0, 0x0, 0x0, 0x0, 0x1975200)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:712 +0x690
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc42005eea0, 0xc421036000, 0xc4202b9ba5, 0x3a, 0xc42a4d5130, 0x0, 0x0, 0x0, 0xc4202b9b00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:493 +0x11b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc420122400, 0xc4202b9ba5, 0x3a, 0xc42a4d5130, 0xc42a4d5128, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:831 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc420122400, 0xc420122428, 0xc4205c8f60, 0xc420122445)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:818 +0x1e0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420122400, 0x7f12078dc180, 0xc4206ef2f0, 0xc420cf0fa0, 0x5400, 0xc420768a10, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:450 +0xb52
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4207688c0, 0x7f12078dc140, 0xc421d99640, 0x27335a0, 0xc420d8c000, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x926
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x27347a0, 0xc4230c8be0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:614 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4205d2820, 0x7f12078dc180, 0xc4202c0300, 0xc4206a2028, 0x27347a0, 0xc4230c8be0, 0xc420dd4180)
       /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x267
```

and `cockroach-navy-0001`:
```
I170421 10:07:20.630680 162 storage/replica_command.go:2626  [split,n1,s1,r1099/4:/Table/51/1/1{746733â<80>¦-880713â<80>¦}] initiating a split of this range at key /Table/51/1/1813642612 [r1925]
F170421 10:07:20.887672 822 sql/distsql_physical_planner.go:445  [client=127.0.0.1:33638,user=root,n1] expected consecutive span pieces [/Table/51/1/1{746733135-813642612}] /Table/51/1/1{746733135-880713052}
goroutine 822 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x301, 0x34e8d05e, 0x2b64e40, 0xc4370e4d10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:837 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2b664a0, 0xc400000004, 0x242a135, 0x1f, 0x1bd, 0xc436959710, 0x8e)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:709 +0x52f
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7ff32c0c8840, 0xc42a67fc50, 0x7ff300000004, 0x2, 0x1afbb05, 0x26, 0xc437328c40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:146 +0x27b
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7ff32c0c8840, 0xc42a67fc50, 0x1, 0xc400000004, 0x1afbb05, 0x26, 0xc437328c40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:68 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x7ff32c0c8840, 0xc42a67fc50, 0x1afbb05, 0x26, 0xc437328c40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:162 +0x7e
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).partitionSpans(0xc420e703f0, 0xc43732ace8, 0xc429a06e10, 0x1, 0x1, 0x0, 0x0, 0xc42b0bc300, 0x5, 0x8)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:445 +0x8f0
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createTableReaders(0xc420e703f0, 0xc43732ace8, 0xc441ad8000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:554 +0x118
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createPlanForNode(0xc420e703f0, 0xc43732ace8, 0x27359e0, 0xc441ad8000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1388 +0x811
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createPlanForNode(0xc420e703f0, 0xc43732ace8, 0x2735960, 0xc444cf4c60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1397 +0x8d8
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createPlanForNode(0xc420e703f0, 0xc43732ace8, 0x27357e0, 0xc43403ac60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1437 +0xc39
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).PlanAndRun(0xc420e703f0, 0x7ff32c0c8840, 0xc42a67fc50, 0xc4213023c0, 0x27357e0, 0xc43403ac60, 0xc43c73d900, 0x2, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:338 +0x10a
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execDistSQL(0xc4203afa00, 0xc440fb2800, 0x27357e0, 0xc43403ac60, 0xc43732e398, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1352 +0x1b3
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc4203afa00, 0x272c980, 0xc429a06a80, 0xc440fb2800, 0x0, 0x0, 0xc425abac00, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1504 +0x42c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc4203afa00, 0xc421473680, 0x272c980, 0xc429a06a80, 0xc423a4a1b0, 0xc437000000, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1254 +0x471
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc4203afa00, 0xc421473680, 0xc423a4a2e0, 0x1, 0x1, 0xc423a4a1b0, 0x0, 0x0, 0x0, 0xc43732eb90, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:950 +0x818
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc4203afa00, 0xc421473680, 0xc423a4a2e0, 0x1, 0x1, 0xc423a4a1b0, 0x1, 0xc423a4a2f8, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:858 +0xd1
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func1(0x7ff32c0c8840, 0xc42a67fc50, 0xc4213023c0, 0xc423a4a2f8, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:690 +0x216
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc4213023c0, 0x7ff32c0c8840, 0xc42a67fc50, 0xc423010000, 0xc42ef03180, 0x1, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:612 +0xb6
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4203afa00, 0xc421473680, 0xc431401ec8, 0x3a, 0xc423a4a1b0, 0x0, 0x0, 0x0, 0x0, 0x1975200)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:712 +0x690
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4203afa00, 0xc421473680, 0xc431401ec8, 0x3a, 0xc423a4a1b0, 0x0, 0x0, 0x0, 0xc431401f00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:493 +0x11b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc421fcf400, 0xc431401ec8, 0x3a, 0xc423a4a1b0, 0xc423a4a1a8, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:831 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc421fcf400, 0xc421fcf428, 0xc423a6af00, 0xc421fcf445)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:818 +0x1e0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc421fcf400, 0x7ff32c0c8840, 0xc420e88750, 0xc420e92f40, 0x5400, 0xc4205d4310, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:450 +0xb52
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4205d41c0, 0x7ff32c0c8800, 0xc421dfd740, 0x27335a0, 0xc421c99c00, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x926
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x27347a0, 0xc420a1b0e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:614 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4205d0000, 0x7ff32c0c8840, 0xc4203ad5f0, 0xc42000e0d8, 0x27347a0, 0xc420a1b0e0, 0xc420275680)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x267
```

**Comment by mberhault** [comment]
@cockroachdb/distsql 

nodes are still down for investigation.

**Comment by tamird** [comment]
Are there interleaved tables on this cluster? Possibly distsql isn't coping
well with @eisenstatdavid's #15043.

**Comment by RaduBerinde** [comment]
Looks like the span resolver returns those two spans with the same start
key @andreimatei

**Comment by RaduBerinde** [comment]
Discussed with Andrei. The planner code makes some optimistic assumptions about the SpanResolver. Easy fix.

**Comment by dianasaur323** [comment]
closing out as fixed by https://github.com/RaduBerinde/cockroach/commit/ba16f666b8ec1d6a67932784445f1603658e06cf

**Comment by dianasaur323** [comment]
whoops! Not merged yet :P Life is hard.
