### ISSUE TITLE
storage: TestMultiStoreEventFeed counts wrong

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1531]
The following test appears to have failed:

[#4214](https://circleci.com/gh/cockroachdb/cockroach/4214):

```
I0628 14:50:12.923111     322 range_command.go:837] initiating a split of range=2 ["b" - "\xff\xff") at key "z"
I0628 14:50:12.946720     322 range_command.go:1014] initiating a merge of range=3 ["z" - "\xff\xff") into range=2 ["b" - "z")
I0628 14:50:13.213604     322 multiraft.go:509] node 300000003: got message for unknown group 3; creating it
I0628 14:50:13.214234     322 multiraft.go:509] node 200000002: got message for unknown group 3; creating it
I0628 14:50:13.218772     322 range_command.go:774] range 3: new leader lease replica 1:1 00:00:00.000 +1.000s
--- FAIL: TestMultiStoreEventFeed-2 (0.74s)
	client_event_test.go:343: update counts did not match expected value. Actual values have been printed to compare with above expectation.
	client_event_test.go:344: Update count information:
		proto.StoreID(1): {
		  proto.Put:                  18,
		  proto.ConditionalPut:       7,
		  proto.Increment:            2,
		  proto.Delete:               2,
		  proto.EndTransaction:       6,
		  proto.InternalLeaderLease:  3,
		},
--
E0628 14:50:17.896658     322 queue.go:266] failure processing range range=2 ["b" - "\xff\xff") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
E0628 14:50:17.906982     322 queue.go:266] failure processing range range=1 ["" - "b") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
--- PASS: TestStoreStatus-2 (0.09s)
=== RUN: ExampleAllocatorRebalancing
--- PASS: ExampleAllocatorRebalancing (0.08s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	6.610s
=== RUN TestBatchBasics-2
I0628 14:50:52.185678     445 rocksdb.go:88] opening in-memory rocksdb instance
I0628 14:50:52.186418     445 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics-2 (0.00s)
=== RUN TestBatchGet-2
I0628 14:50:52.187233     445 rocksdb.go:88] opening in-memory rocksdb instance
I0628 14:50:52.187412     445 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet-2 (0.00s)
=== RUN TestBatchMerge-2
I0628 14:50:52.188095     445 rocksdb.go:88] opening in-memory rocksdb instance
PASS
ok  	github.com/cockroachdb/cockroach/kv	24.871s
=== RUN TestHeartbeatSingleGroup-2
--- PASS: TestHeartbeatSingleGroup-2 (0.39s)
=== RUN TestHeartbeatMultipleGroupsJointLeader-2
panic: test timed out after 5m0s

goroutine 508 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 2 minutes]:
testing.RunTests(0xb65148, 0xd06b60, 0xa, 0xa, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/multiraft/storage.go:145 +0xb9b
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0x133
FAIL	github.com/cockroachdb/cockroach/multiraft	300.030s
=== RUN TestMemoryStorage-2
--- PASS: TestMemoryStorage-2 (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/multiraft/storagetest	0.041s
=== RUN TestClientCmdIDIsEmpty-2
--- PASS: TestClientCmdIDIsEmpty-2 (0.00s)
=== RUN TestResponseHeaderSetGoError-2
--- PASS: TestResponseHeaderSetGoError-2 (0.00s)
=== RUN TestResponseHeaderNilError-2
--- PASS: TestResponseHeaderNilError-2 (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
ping @mrtracy

**Comment by tschottdorf** [comment]
^- two more copies here

**Comment by mrtracy** [comment]
Still haven't had a chance to get back and fix this test (which is now disabled). It's on my todo list but I don't know the relative priority.

The issue is that the initial process of replicating the range to the second and third node can race in terms of events; sometimes the second node is replicated fast enough to see the replication events for the third node, but sometimes it is not.

The most direct fix I can think of is to fix `mtc.replicateRange` to (optionally) isolate the creation of each individual replica.

**Comment by tschottdorf** [comment]
The test generally seems to not the feed, but a fairly specific number of events in a three-node system. Unless we fudge it, I don't think we can ever rely on everything having a very specific order (and thus, count). I wouldn't invest too much in this test. Maybe instead of exact counts it can just test that we see at least that many of each.

**Comment by tamird** [comment]
Removing `multi-cpu` since this test is not a blocker now that it's skipped.

**Comment by mrtracy** [comment]
Per #4021, this test should remain disabled; it should be removed entirely as part of #4021.
