### ISSUE TITLE
request issued during shutdown blocks test teardown

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1538]
The following test appears to have failed:

[#4241](https://circleci.com/gh/cockroachdb/cockroach/4241):

```
W0629 03:15:47.446199     324 multiraft.go:950] node 300000003 failed to send message to 400000004: transport.go:159: transport is closed
W0629 03:15:47.446253     324 multiraft.go:950] node 300000003 failed to send message to 200000002: transport.go:159: transport is closed
W0629 03:15:47.446775     324 multiraft.go:950] node 400000004 failed to send message to 200000002: transport.go:159: transport is closed
W0629 03:15:47.446844     324 multiraft.go:950] node 400000004 failed to send message to 300000003: transport.go:159: transport is closed
W0629 03:15:47.446931     324 multiraft.go:950] node 400000004 failed to send message to 100000001: transport.go:159: transport is closed
panic: test timed out after 30s

goroutine 5602 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0x11bf240, 0x169ff20, 0xb3, 0xb3, 0xc207fff501)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:207 +0x2cb
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0xe3
FAIL	github.com/cockroachdb/cockroach/storage	30.049s
=== RUN TestBatchBasics-2
I0629 03:16:02.068449     442 rocksdb.go:88] opening in-memory rocksdb instance
I0629 03:16:02.069436     442 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics-2 (0.02s)
=== RUN TestBatchGet-2
I0629 03:16:02.089331     442 rocksdb.go:88] opening in-memory rocksdb instance
I0629 03:16:02.089721     442 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet-2 (0.00s)
=== RUN TestBatchMerge-2
I0629 03:16:02.090545     442 rocksdb.go:88] opening in-memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
the stopper has drained, but is waiting on the stop WaitGroup. The stack trace shows a lot of RunWorker routines running, and at least some of them are stuck in various places because MultiRaft stopped fairly early in this run. Example:

```go
	errChan, pendingCmd := r.proposeRaftCommand(r.context(), args, &proto.InternalLeaderLeaseResponse{})
	var err error
	if err = <-errChan; err == nil {
		// Next if the command was committed, wait for the range to apply it.
		err = <-pendingCmd.done // stuck here, will never come back from it.
	}
	return err
```

This request exists only because `maybeGossipFirstRange` calls `getLeaseForGossip`. It shouldn't be doing that when the stopper is draining, and I would expect some of the other instances to look the same.
