### ISSUE TITLE
Crashing the DB with some TXs creating contention

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#15412]
Hi,

I am running on latest with  build: CCL 9052d7c @ 2017/04/27 16:25:10 (go1.8.1)
I was trying to stimulate some contention to check how my retry logic on the client side was working and found out that in some situations, I was crashing the server:

```
I170428 00:27:07.110161 664 sql/executor.go:1084  [client=127.0.0.1:63403,user=root,n1] UPDATE roles SET public = false WHERE id = 'admin'
I170428 00:27:07.110516 664 sql/executor.go:1084  [client=127.0.0.1:63403,user=root,n1] ERROR: txn aborted "sql txn" id=ae919663 key=/Table/1182/1/"manage_activity"/0 rw=true pri=0.01998227 iso=SERIALIZABLE stat=ABORTED epo=0 ts=1493310424.062994456,1 orig=1493310423.563391145,0 max=1493310424.063391145,0 wto=false rop=false seq=7
I170428 00:27:07.110540 664 sql/executor.go:718  [client=127.0.0.1:63403,user=root,n1] execRequest: error: txn aborted "sql txn" id=ae919663 key=/Table/1182/1/"manage_activity"/0 rw=true pri=0.01998227 iso=SERIALIZABLE stat=ABORTED epo=0 ts=1493310424.062994456,1 orig=1493310423.563391145,0 max=1493310424.063391145,0 wto=false rop=false seq=7
I170428 00:27:07.110903 664 sql/executor.go:1084  [client=127.0.0.1:63403,user=root,n1] preparing: RELEASE SAVEPOINT cockroach_restart
I170428 00:27:07.111150 664 sql/executor.go:565  [client=127.0.0.1:63403,user=root,n1] execRequest: RELEASE SAVEPOINT cockroach_restart
I170428 00:27:07.111183 664 sql/executor.go:918  [client=127.0.0.1:63403,user=root,n1] executing 1/1: RELEASE SAVEPOINT cockroach_restart
I170428 00:27:07.111233 664 sql/executor.go:718  [client=127.0.0.1:63403,user=root,n1] execRequest: error: current transaction is aborted, commands ignored until end of transaction block
F170428 00:27:07.111291 664 sql/executor.go:752  [client=127.0.0.1:63403,user=root,n1] got a non-retryable error but the KV transaction is not finalized. TxnState: RestartWait, err: current transaction is aborted, commands ignored until end of transaction block
err:current transaction is aborted, commands ignored until end of transaction block

txn: "sql txn" id=<nil> key=/Min rw=false pri=0.01998227 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000000,0 orig=1493310427.111165604,0 max=0.000000000,0 wto=false rop=false seq=0
goroutine 664 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x200, 0x6a22dfc, 0x6376ca0, 0x10)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:837 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x6378260, 0xc400000004, 0x5e5c6d2, 0xf, 0x2f0, 0xc420185680, 0x1df)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:707 +0x553
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x8881000, 0xc420ed8300, 0x4, 0x2, 0x55b07f8, 0x69, 0xc420e47128, 0x4, 0x4)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:146 +0x27b
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x8881000, 0xc420ed8300, 0x1, 0xc400000004, 0x55b07f8, 0x69, 0xc420e47128, 0x4, 0x4)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:68 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x8881000, 0xc420ed8300, 0x55b07f8, 0x69, 0xc420e47128, 0x4, 0x4)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:162 +0x7e
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc42020c1c0, 0xc420db1b00, 0xc42216e309, 0x23, 0xc420aa1c80, 0x0, 0x0, 0x0, 0x0, 0x53f5800)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:752 +0x10f8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc42020c1c0, 0xc420db1b00, 0xc42216e309, 0x23, 0xc420aa1c80, 0x0, 0x0, 0x0, 0xc42216e300)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:488 +0x11b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc421077200, 0xc42216e309, 0x23, 0xc420aa1c80, 0x63ad050, 0x0, 0x0, 0x55cf600, 0x0, 0x0, ...)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:836 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc421077200, 0xc421077228, 0xc420bc8f60, 0xc421077245)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:823 +0x1e0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc421077200, 0x8881000, 0xc4209e6720, 0xc420ac1be0, 0x5400, 0xc42016c310, 0x0, 0x0)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:455 +0xb52
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42016c1c0, 0x88810e0, 0xc4210a1740, 0x5f1e5e0, 0xc421acfd60, 0x0, 0x0)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x926
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x5f1e5e0, 0xc421acfd60)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:615 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc42017c000, 0x8881000, 0xc4201b4330, 0xc42040c048, 0x5f1e5e0, 0xc421acfd60, 0xc420b97e90)
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /Users/jelan/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x267
```

On a side note, what is the minimum of work that is needed with 2 transactions to get one failing with the retry error ?

**Comment by andreimatei** [comment]
Great find! Is this easy to reproduce? Could you share the client program with us?

**Comment by tlvenn** [comment]
Hi @andreimatei , that should be fairly easy to reproduce. I start 5 concurrent async task, and feed them with:

```
Ecto.Adapters.SQL.query(__MODULE__, "update permissions set mask = #{i} where id = 'manage_activity'")
if i == 1, do: Process.sleep(4000), else: Process.sleep(500 * i)
Ecto.Adapters.SQL.query(__MODULE__, "update roles set public = true where id = 'admin'")
```

Each of those async task are run inside a transaction with the retry logic in place (it issues `SAVEPOINT cockroach_restart` immediately after `begin` and finish with `RELEASE SAVEPOINT cockroach_restart` before committing.

**Comment by tlvenn** [comment]
@andreimatei have you been able to reproduce the issue ?

**Comment by andreimatei** [comment]
I haven't had a chance to look yet but I want to. Without looking at the source, I have a feeling that this might be caused by incorrect client logic (besides the server problem which should handle this gracefully and not crash). Do you issue a ROLLBACK TO SAFEPOINT when the RELEASE fails with a retryable error? If so, if you could share a client binary and a database dump to test against, that'd be extremely useful.

For your earlier question about how to cause retryable errors, I think the easiest way is to start transaction A, perform a read (to get a transaction timestamp), then start transaction B and issue a read, then go back to transaction A and try to do a write that conflicts with B's read. At this point, B shouldn't be able to commit (you might have to attempt a COMMIT or RELEASE to actually observe the error, I'm not sure).

**Comment by tlvenn** [comment]
I am pretty sure you are correct that the culprit is within the client logic. I have yet to properly pattern match on the retry error that CDB should emit and I am not sure that the Elixir driver is propagating properly that error to me.

Thanks for the pointer on how to cause retryable errors in a simpler manner, I will see investigate further.

**Comment by andreimatei** [comment]
I'm able to reproduce the crash in the way I suspected: trigger a retryable error in a session that expressed interest in doing client-retries (through `savepoint cockroach_restart`), and then issuing a random statement instead of `rollback to savepoint cockroach_restart`. So, @tlvenn, I think it' very likely that the client code is not quite right.

This might be a regression because of some error handling refactoring that happened a while ago. Or perhaps it was always broken. In any case, I'm doing something about it.

**Comment by tlvenn** [comment]
Thanks for the fix @andreimatei  !
