### ISSUE TITLE
sql: panic: unsupported result type: NULL

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#15525]
```
create database d;
create table t (i int);
SELECT NULL , * FROM d.t;
```
panics:

```
SELECT NULL , * FROM d.t;: unsupported result type: NULL

goroutine 308 [running]:
runtime/debug.Stack(0x6d83980, 0xc4204008a0, 0x5384120)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6d83980, 0xc4204008a0, 0x5384120, 0xc4203391e0)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:78 +0x123
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42071eb40, 0x6d83980, 0xc4204008a0)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0x90
panic(0x5384120, 0xc4203391e0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc4201ee000, 0x6d83980, 0xc420572090)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:353 +0x74
panic(0x5384120, 0xc4203391e0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc42062f12c, 0x19)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:498 +0x131
panic(0x532e060, 0xc420339140)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumTypeToColumnType(0x5fc0840, 0x644f780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/structured.go:1774 +0x2d6
github.com/cockroachdb/cockroach/pkg/sql.getTypesForPlanResult(0x5fc2f00, 0xc4204ff680, 0x0, 0x0, 0x0, 0xc4213acc90, 0x1, 0x1)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1163 +0x2bd
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).selectRenders(0xc420b822d0, 0xc4218b8760, 0xc4204ff680)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:696 +0x59
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createPlanForNode(0xc420b822d0, 0xc4218b8b90, 0x5fc2f00, 0xc4204ff680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1419 +0x97d
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).PlanAndRun(0xc420b822d0, 0x6d83980, 0xc42138efc0, 0xc420604420, 0x5fc2f00, 0xc4204ff680, 0xc4213dec00, 0x40109f8, 0xc4218b8cc0)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:387 +0x10a
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execDistSQL(0xc420236e00, 0xc42074cc80, 0x5fc2f00, 0xc4204ff680, 0xc4218bc278, 0x0, 0x0)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1424 +0x20c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc420236e00, 0x5fb9f80, 0xc42138ef90, 0xc42074cc80, 0xc42138f001, 0x0, 0xc4218bc300, 0x0, 0x0, 0x0, ...)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1581 +0x42c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc420236e00, 0xc420cc5b00, 0x5fb9f80, 0xc42138ef90, 0x0, 0x101, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1316 +0x471
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc420236e00, 0xc420cc5b00, 0xc420315a70, 0x1, 0x1, 0x0, 0x101, 0x0, 0x0, 0xc4218bcbe8, ...)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:961 +0x818
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc420236e00, 0xc420cc5b00, 0xc420315a70, 0x1, 0x1, 0x0, 0x1, 0xc420315a80, 0x0, 0x0, ...)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:869 +0xd1
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func1(0x6d83980, 0xc42138efc0, 0xc420604420, 0xc420315a80, 0x0, 0x0)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:701 +0x216
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc420604420, 0x6d83980, 0xc42138efc0, 0x10101, 0xc4206b8000, 0x0, 0x0)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:640 +0xb6
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420236e00, 0xc420cc5b00, 0xc42062f12c, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42062f100)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:723 +0x690
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420236e00, 0xc420cc5b00, 0xc42062f12c, 0x19, 0x0, 0x0, 0x0, 0x0, 0xc42062f100)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:504 +0x11b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc4201ee000, 0xc42062f12c, 0x19, 0x0, 0x0, 0x0, 0x0, 0x440a801, 0x0, 0x0, ...)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:836 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc4201ee000, 0xc4201ee028, 0xc420f0c180, 0x51)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:504 +0xa9
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc4201ee000, 0x6d83980, 0xc420572090, 0xc420216090, 0x5400, 0xc420237490, 0x0, 0x0)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:432 +0x8bd
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420237340, 0x6d83a60, 0xc420c28100, 0x5fc1d40, 0xc42071e820, 0x0, 0x0)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x926
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x5fc1d40, 0xc42071e820)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/server/server.go:619 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc42071eb40, 0x6d83980, 0xc4204008a0, 0xc42080a020, 0x5fc1d40, 0xc42071e820, 0xc420b06360)
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/Users/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x267
```

May have something to do with dist sql, so assigning radu also.

Found with RSG.

**Comment by RaduBerinde** [comment]
Interesting. Distsql requires a ColumnType for any datum transferred between processors. In this case we have an "untyped" NULL. I think we can use any columntype in this case because we would only have NULLs.
