### ISSUE TITLE
Deadlock in TestNodeStatus

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1558]
The following test appears to have failed:

[#4275](https://circleci.com/gh/cockroachdb/cockroach/4275):

```
E0629 16:41:38.835995     437 queue.go:266] failure processing range range=1 ["" - "b") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
E0629 16:41:38.854336     437 queue.go:266] failure processing range range=1 ["" - "b") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
E0629 16:41:38.869960     437 queue.go:266] failure processing range range=1 ["" - "b") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
E0629 16:41:38.887279     437 queue.go:266] failure processing range range=1 ["" - "b") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
E0629 16:41:38.920274     437 queue.go:266] failure processing range range=1 ["" - "b") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
panic: test timed out after 5m0s

goroutine 506958 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x14ad5c8, 0x19f1720, 0x1d, 0x1d, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
goroutine 506962 [runnable]:
github.com/cockroachdb/cockroach/rpc.sendOne(0xc208357720, 0x12a05f200, 0xc20817b5d8, 0x8, 0x12a86c0, 0xc208143080, 0x1296a60, 0xc2081a9ea0, 0xc208492a80)
	/go/src/github.com/cockroachdb/cockroach/rpc/send.go:235 +0xb51
created by github.com/cockroachdb/cockroach/rpc.Send
	/go/src/github.com/cockroachdb/cockroach/rpc/send.go:173 +0x1854
FAIL	github.com/cockroachdb/cockroach/server	300.095s
=== RUN TestStdFlagToPflag-2
--- PASS: TestStdFlagToPflag-2 (0.00s)
=== RUN TestNoLinkTesting-2
--- PASS: TestNoLinkTesting-2 (1.48s)
=== RUN: Example_basic
I0629 16:36:41.766532     445 rocksdb.go:88] opening in-memory rocksdb instance
I0629 16:36:41.773144     445 range_command.go:774] range 1: new leader lease replica 1:1 00:00:00.000 +1435595802.771s
I0629 16:36:41.791359     445 node.go:297] initialized store store=1:1 ([]=): {Capacity:257668677632 Available:206152253440 RangeCount:0 XXX_unrecognized:[]}
I0629 16:36:41.791514     445 node.go:226] new node allocated ID 1
I0629 16:36:41.792213     445 gossip.go:165] gossiping node descriptor node_id:1 address:<network:"tcp" address:"127.0.0.1:50503" > attrs:<> 

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Haven't been able to repro this recently, closing for now.
