### ISSUE TITLE
sql: panic: could not parse 'string' as type bool

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#15632]
```
SELECT IFNULL ( 'string' , FALSE )
```

Found with RSG.

**Comment by jordanlewis** [comment]
I'll take a look at this. Here's the panic:

```
goroutine 334 [running]:
runtime/debug.Stack(0x7f564c0, 0xc42021a180, 0x3)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x7f564c0, 0xc42021a180, 0x5309ec0, 0xc4210b2380)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/stderr_redirect.go:80 +0xeb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420522000, 0x7f564c0, 0xc42021a180)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0x90
panic(0x5309ec0, 0xc4210b2380)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc421657600, 0x7f564c0, 0xc4202ce120)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:348 +0x74
panic(0x5309ec0, 0xc4210b2380)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc42023e000, 0x1c)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:492 +0x131
panic(0x5309ec0, 0xc4210b2360)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/parser.typeCheckSameTypedExprs.func2.1(0x5eaec20, 0x632d1c0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/type_check.go:1071 +0x181
github.com/cockroachdb/cockroach/pkg/sql/parser.typeCheckSameTypedExprs.func2(0x5eaec20, 0x632d1c0, 0x632d101, 0x632d1c0, 0x5eac640, 0x632d21a, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/type_check.go:1094 +0x594
github.com/cockroachdb/cockroach/pkg/sql/parser.typeCheckSameTypedExprs(0xc4206eb810, 0x5eaebc0, 0x632d1c0, 0xc420b11800, 0x2, 0x2, 0x16, 0xc420a9e700, 0x16, 0x54387c0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/type_check.go:1189 +0xdd4
github.com/cockroachdb/cockroach/pkg/sql/parser.(*CoalesceExpr).TypeCheck(0xc420a9e700, 0xc4206eb810, 0x5eaebc0, 0x632d1c0, 0x0, 0x0, 0xc4210b22a0, 0x1)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/type_check.go:307 +0x7d
github.com/cockroachdb/cockroach/pkg/sql/parser.TypeCheck(0x5ea79a0, 0xc420a9e700, 0xc4206eb810, 0x5eaebc0, 0x632d1c0, 0x1, 0x632d770, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:85 +0xbd
github.com/cockroachdb/cockroach/pkg/sql.(*planner).analyzeExpr(0xc4206eb800, 0x7f564c0, 0xc4202ce390, 0x5ea79a0, 0xc420a9e700, 0xc420978250, 0x1, 0x1, 0x632d770, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:1665 +0x20d
github.com/cockroachdb/cockroach/pkg/sql.(*planner).computeRender(0xc4206eb800, 0x7f564c0, 0xc4202ce390, 0x5ea79a0, 0xc420a9e700, 0x0, 0x0, 0x5eaebc0, 0x632d1c0, 0xc420978250, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/targets.go:39 +0x18d
github.com/cockroachdb/cockroach/pkg/sql.(*planner).computeRenderAllowingStars(0xc4206eb800, 0x7f564c0, 0xc4202ce390, 0x5ea79a0, 0xc420a9e700, 0x0, 0x0, 0x5eaebc0, 0x632d1c0, 0xc420978250, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/targets.go:68 +0x1fc
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).initTargets(0xc42205c7e0, 0x7f564c0, 0xc4202ce390, 0xc420b11860, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:344 +0x14e
github.com/cockroachdb/cockroach/pkg/sql.(*planner).SelectClause(0xc4206eb800, 0x7f564c0, 0xc4202ce390, 0xc420351b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:261 +0x319
github.com/cockroachdb/cockroach/pkg/sql.(*planner).Select(0xc4206eb800, 0x7f564c0, 0xc4202ce390, 0xc4202ce360, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:194 +0x51e
github.com/cockroachdb/cockroach/pkg/sql.(*planner).newPlan(0xc4206eb800, 0x7f564c0, 0xc4202ce390, 0x5ea84e0, 0xc4202ce360, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:345 +0x2947
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc4206eb800, 0x7f564c0, 0xc4202ce390, 0x5ea84e0, 0xc4202ce360, 0x5909b801, 0x12d62ba3, 0xc421662230, 0xc4216622b0, 0x4012612)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:219 +0x9c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc420349a00, 0x5ea84e0, 0xc4202ce360, 0xc4206eb800, 0xc4202ce401, 0x0, 0x7b3d6bf949c05f00, 0x0, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1529 +0x125
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc420349a00, 0xc420d66480, 0x5ea84e0, 0xc4202ce360, 0x0, 0x101, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1300 +0x471
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc420349a00, 0xc420d66480, 0xc4210b22f0, 0x1, 0x1, 0x0, 0x4000101, 0x0, 0xc400000000, 0xc421662c08, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:955 +0x818
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc420349a00, 0xc420d66480, 0xc4210b22f0, 0x1, 0x1, 0x0, 0x1, 0xc4210b2308, 0x3a562d5f71ef9d00, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:863 +0xd1
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func1(0x7f564c0, 0xc4202ce390, 0xc420fa68c0, 0xc4210b2308, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:695 +0x216
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc420fa68c0, 0x7f564c0, 0xc4202ce390, 0x10101, 0xc420351c00, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:612 +0xb6
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420349a00, 0xc420d66480, 0xc42023e000, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42023e000)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:717 +0x690
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420349a00, 0xc420d66480, 0xc42023e000, 0x1c, 0x0, 0x0, 0x0, 0x0, 0xc42023e000)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:498 +0x11b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc421657600, 0xc42023e000, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x43f9101, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:831 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc421657600, 0xc421657628, 0xc421648060, 0x51)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:499 +0xa9
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc421657600, 0x7f564c0, 0xc4202ce120, 0xc4210b2290, 0x5400, 0xc4205f2310, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:427 +0x8bd
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4205f21c0, 0x9945828, 0xc420a9e540, 0x5eb03c0, 0xc421048640, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x926
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x5eb03c0, 0xc421048640)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:615 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc420522000, 0x7f564c0, 0xc42021a180, 0xc420534038, 0x5eb03c0, 0xc421048640, 0xc420589d40)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x267
```
