### ISSUE TITLE
TestReplicateAddAndRemove-2 failed

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#1569]
[4283](https://circleci.com/gh/cockroachdb/cockroach/4283)
```
error

        I0629 20:03:22.742073     334 rocksdb.go:88] opening in-memory rocksdb instance
I0629 20:03:22.743075     334 range.go:967] gossiping cluster id  from store 1, range 1
I0629 20:03:22.743793     334 range_command.go:774] range 1: new leader lease replica 1:1 00:00:00.000 +1.000s
I0629 20:03:22.743877     334 range.go:1028] gossiping accounting config from store 1, range 1
I0629 20:03:22.743961     334 range.go:1028] gossiping permissions config from store 1, range 1
I0629 20:03:22.744036     334 range.go:1028] gossiping zones config from store 1, range 1
I0629 20:03:22.744141     334 range.go:975] gossiping sentinel from store 1, range 1
I0629 20:03:22.744169     334 range.go:979] gossiping first range from store 1, range 1
I0629 20:03:22.744658     334 rocksdb.go:88] opening in-memory rocksdb instance
I0629 20:03:22.745141     334 rocksdb.go:88] opening in-memory rocksdb instance
I0629 20:03:22.745758     334 rocksdb.go:88] opening in-memory rocksdb instance
I0629 20:03:22.750197     334 multiraft.go:509] node 400000004: got message for unknown group 1; creating it
I0629 20:03:22.764850     334 multiraft.go:509] node 200000002: got message for unknown group 1; creating it
W0629 20:03:22.771531     334 multiraft.go:950] node 100000001 failed to send message to 200000002: transport.go:170: unknown peer 200000002
W0629 20:03:22.772366     334 multiraft.go:950] node 100000001 failed to send message to 200000002: transport.go:170: unknown peer 200000002
I0629 20:03:22.781835     334 multiraft.go:509] node 300000003: got message for unknown group 1; creating it
I0629 20:03:22.799383     334 range.go:967] gossiping cluster id  from store 2, range 1
I0629 20:03:22.807916     334 range.go:1028] gossiping accounting config from store 2, range 1
E0629 20:03:22.808097     334 range.go:1020] failed loading permissions config map: prefix.go:114: no default prefix specified
E0629 20:03:22.808185     334 range.go:1020] failed loading zones config map: prefix.go:114: no default prefix specified
I0629 20:03:22.808228     334 rocksdb.go:88] opening in-memory rocksdb instance
I0629 20:03:22.809164     334 range.go:1028] gossiping accounting config from store 3, range 1
I0629 20:03:22.810194     334 range.go:1028] gossiping permissions config from store 3, range 1
I0629 20:03:22.810342     334 range.go:1028] gossiping zones config from store 3, range 1
I0629 20:03:22.810490     334 range_command.go:774] range 1: new leader lease replica 1:1 00:00:00.000 +1.000s
I0629 20:03:22.810610     334 range.go:1028] gossiping accounting config from store 1, range 1
I0629 20:03:22.810679     334 range.go:967] gossiping cluster id  from store 1, range 1
I0629 20:03:22.810707     334 range.go:1028] gossiping accounting config from store 4, range 1
I0629 20:03:22.810830     334 range.go:1028] gossiping permissions config from store 4, range 1
I0629 20:03:22.810939     334 range.go:1028] gossiping zones config from store 4, range 1
I0629 20:03:22.811175     334 range.go:1028] gossiping permissions config from store 1, range 1
I0629 20:03:22.811392     334 range.go:1028] gossiping zones config from store 1, range 1
E0629 20:03:22.811509     334 split_queue.go:134] unable to fetch zones config from gossip: gossip.go:249: key "zones" does not exist or has expired
I0629 20:03:22.811796     334 range.go:975] gossiping sentinel from store 1, range 1
I0629 20:03:22.811846     334 range.go:979] gossiping first range from store 1, range 1
I0629 20:03:22.812103     334 rocksdb.go:88] opening in-memory rocksdb instance
I0629 20:03:22.812668     334 rocksdb.go:88] opening in-memory rocksdb instance
I0629 20:03:22.813249     334 rocksdb.go:88] opening in-memory rocksdb instance
I0629 20:03:22.816899     334 multiraft.go:509] node 400000004: got message for unknown group 1; creating it
I0629 20:03:22.831641     334 multiraft.go:509] node 200000002: got message for unknown group 1; creating it
W0629 20:03:22.835645     334 multiraft.go:950] node 100000001 failed to send message to 200000002: transport.go:170: unknown peer 200000002
W0629 20:03:22.836211     334 multiraft.go:950] node 100000001 failed to send message to 200000002: transport.go:170: unknown peer 200000002
W0629 20:03:22.844219     334 multiraft.go:206] node 200000002: not fanning out heartbeat from unknown node 100000001 (but responding anyway)
I0629 20:03:22.847333     334 multiraft.go:509] node 300000003: got message for unknown group 1; creating it
W0629 20:03:22.848073     334 multiraft.go:206] node 200000002: not fanning out heartbeat from unknown node 300000003 (but responding anyway)
W0629 20:03:22.848192     334 multiraft.go:206] node 200000002: not fanning out heartbeat from unknown node 400000004 (but responding anyway)
I0629 20:03:22.860483     334 range.go:1028] gossiping accounting config from store 2, range 1
I0629 20:03:22.860682     334 range.go:1028] gossiping permissions config from store 2, range 1
I0629 20:03:22.860837     334 range.go:1028] gossiping zones config from store 2, range 1
I0629 20:03:22.861343     334 range.go:967] gossiping cluster id  from store 2, range 1
W0629 20:03:22.868118     334 multiraft.go:950] node 400000004 failed to send message to 100000001: transport.go:159: transport is closed
I0629 20:03:22.868609     334 range.go:1028] gossiping accounting config from store 4, range 1
I0629 20:03:22.868860     334 range.go:1028] gossiping permissions config from store 4, range 1
I0629 20:03:22.869129     334 range.go:1028] gossiping zones config from store 4, range 1
panic: test timed out after 30s

goroutine 12036 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0x11c05c8, 0x16a15a0, 0xb4, 0xb4, 0xc207fff501)
	/usr/src/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20800ac30, 0x50)
	/usr/src/go/src/testing/testing.go:485 +0x6c
github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck(0xc20800ac30)
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x28
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc20800ac30)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x28
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:418 +0x1d1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x16bfbe0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1038 +0x75
created by github.com/cockroachdb/cockroach/util/log.init·1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0xcc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3954 [select]:
github.com/cockroachdb/cockroach/storage.func·013()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:207 +0x2cb
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0xe3

goroutine 3607 [select]:
github.com/cockroachdb/cockroach/storage.func·013()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:207 +0x2cb
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0xe3

goroutine 3583 [select]:
github.com/cockroachdb/cockroach/multiraft.func·007()
	/go/src/github.com/cockroachdb/cockroach/multiraft/storage.go:145 +0x90a
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0xe3
...
```

**Comment by tamird** [comment]
Haven't been able to reproduce this recently, closing for now.
