### ISSUE TITLE
getsockopt: connection refused, accept4: too many open files in system

### ISSUE THREAD

**Issue by kokizzu** [cockroachdb/cockroach#15885]
Is this a question, feature request, or bug report?

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

node 1
```
I170512 08:41:26.554755 1 util/log/clog.go:1011  [config] file created at: 2017/05/12 08:41:26
I170512 08:41:26.554755 1 util/log/clog.go:1011  [config] running on machine: GTune59
I170512 08:41:26.554755 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0 (linux amd64, built 2017/05/10 13:19:57, go1.8.1)
I170512 08:41:26.554755 1 util/log/clog.go:1011  [config] arguments: [./cockroach start --insecure --host=localhost]

```

node 2
```
I170512 08:42:04.452815 1 util/log/clog.go:1011  [config] file created at: 2017/05/12 08:42:04
I170512 08:42:04.452815 1 util/log/clog.go:1011  [config] running on machine: GTune59
I170512 08:42:04.452815 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0 (linux amd64, built 2017/05/10 13:19:57, go1.8.1)
I170512 08:42:04.452815 1 util/log/clog.go:1011  [config] arguments: [./cockroach start --insecure --store=node2 --host=localhost --port=26258 --http-port=8081 --join=localhost:26257]
```

node 3
```
I170512 08:42:12.605019 1 util/log/clog.go:1011  [config] file created at: 2017/05/12 08:42:12
I170512 08:42:12.605019 1 util/log/clog.go:1011  [config] running on machine: GTune59
I170512 08:42:12.605019 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0 (linux amd64, built 2017/05/10 13:19:57, go1.8.1)
I170512 08:42:12.605019 1 util/log/clog.go:1011  [config] arguments: [./cockroach start --insecure --store=node3 --host=localhost --port=26259 --http-port=8082 --join=localhost:26257]
```

2. Please describe the issue you observed:

- What did you do?
create 3 cluster as described on the example, trying to check chance for duplicate `serial` generation.

- What did you expect to see?

Run this script:
``` bash
for x in `seq 1 1000`; do 
   echo "INSERT INTO t1.test(b) VALUES('1-$x');" | ./cockroach sql --insecure &
   echo "INSERT INTO t1.test(b) VALUES('2-$x');" | ./cockroach sql --insecure --port 26258 &
   echo "INSERT INTO t1.test(b) VALUES('3-$x');" | ./cockroach sql --insecure --port 26257 &
done
```

- What did you see instead?
for the first time it's ok, for the second time running that script: 
```
dial tcp [::1]:26257: getsockopt: connection refused
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26257: getsockopt: connection refused
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26257: getsockopt: connection refused
Failed running "sql"
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26257: getsockopt: connection refused
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26258: getsockopt: connection refused
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26258: getsockopt: connection refused
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26258: getsockopt: connection refused
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26258: getsockopt: connection refused
Failed running "sql"
Failed running "sql"
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26257: getsockopt: connection refused
Failed running "sql"
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26257: getsockopt: connection refused
Failed running "sql"
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26258: getsockopt: connection refused
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26257: getsockopt: connection refused
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26257: getsockopt: connection refused
Failed running "sql"
Failed running "sql"
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26257: getsockopt: connection refused
Failed running "sql"
Failed running "sql"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:26257: getsockopt: connection refused
Failed running "sql"
Failed running "sql"
Failed running "sql"
Failed running "sql"
Error: unable to connect or connection lost.
```

on the primary node: `* ERROR: Reported as error 5381bba595d94062ab2f96f4c2106ea7`

The log:

```
I170512 08:58:13.432362 669 vendor/google.golang.org/grpc/transport/http2_client.go:1231  transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:33276->127.0.0.1:26258: read: connection reset by peer.
W170512 08:58:13.434618 686 storage/raft_transport.go:442  [n1] raft transport stream to node 2 failed: rpc error: code = Internal desc = transport is closing
I170512 08:58:13.469692 630 vendor/google.golang.org/grpc/transport/http2_server.go:323  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:26257->127.0.0.1:38400: read: connection reset by peer
I170512 08:58:13.495093 17123 vendor/google.golang.org/grpc/transport/http2_client.go:1231  transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:47074->127.0.0.1:26258: read: connection reset by peer.
I170512 08:58:13.495498 672 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:26258: getsockopt: connection refused"; Reconnecting to {localhost:26258 <nil>}
E170512 08:58:15.153942 21 util/log/crash_reporting.go:148  Reported as error 5381bba595d94062ab2f96f4c2106ea7
F170512 08:58:15.153971 21 util/netutil/net.go:161  accept tcp 127.0.0.1:26257: accept4: too many open files in system
goroutine 21 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0, 0x92d69be, 0x2c014e0, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:858 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2c02cc0, 0xc400000004, 0x24cc64e, 0x13, 0xa1, 0xc4213b1860, 0x42)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:724 +0x591
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7fad28e1abd8, 0xc4200164e8, 0x1b00000004, 0x2, 0x0, 0x0, 0xc420a3ded0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:158 +0x4b3
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7fad28e1abd8, 0xc4200164e8, 0x1, 0xc400000004, 0x0, 0x0, 0xc420a3ded0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:68 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x7fad28e1abd8, 0xc4200164e8, 0xc420a3ded0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:171 +0x76
github.com/cockroachdb/cockroach/pkg/util/netutil.FatalIfUnexpected(0x27b5580, 0xc4213b00a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:161 +0xde
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func10.1()
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:746 +0x47
sync.(*Once).Do(0xc4204acaa0, 0xc420452f60)
        /usr/local/go/src/sync/once.go:44 +0xbe
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func10(0x7fad28e1f660, 0xc4201d2450)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:747 +0x64
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420198630, 0xc42040d0e0, 0xc4201d9ac0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad
```

possibly the previous connection not closed correctly?

```
$ cat /proc/sys/fs/file-max
16384
$ ulimit -n
32767
$ sudo lsof -u `whoami` | wc -l
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
21557
```

**Comment by kokizzu** [comment]
also, after `quit` it takes 1 minutes 30 seconds to `start` again

**Comment by kokizzu** [comment]
my suggestion is, before starting the server, there should be a recommendation about sysctl parameters and how to set them.

**Comment by bdarnell** [comment]
It's really strange for `/proc/sys/fs/file-max` to be lower than `ulimit -n` - we look at the current value of `ulimit` to avoid exceeding it but we don't look for `file-max` because we expect it to always be higher. What version of linux are you using? Is this the default for `file-max` and `ulimit -n` on your system or have you changed one or both of them? 

We have [ulimit recommendations](https://www.cockroachlabs.com/docs/recommended-production-settings.html#file-descriptors-limit) but we don't currently say anything about `file-max` because we haven't seen it be an issue in the past.

**Comment by kokizzu** [comment]
i'm using `4.10.13-1-aufs_friendly` kernel on 64-bit ArchLinux, i think it's not the default, i change the `file-max` to higher because `IntelliJ IDEA` complaining that the previous value is too low.

ah, apparently the default value is higher *__*): `3274786`

this is definitely my fault.

**Comment by bdarnell** [comment]
OK, I'm transferring this to a docs issue to be mentioned in the recommended production settings page: cockroachdb/docs#1411
