### ISSUE TITLE
sql: panic in generate_series

### ISSUE THREAD

**Issue by hwaastad** [cockroachdb/cockroach#15900]
Started testing cockroachdb on a 6 node cluster.

I do a preparedstatment insert and the instance panics and restarts.

Maybe a not supported query, but still should not panic.

Output:

```
2.5.2017 22:02:07* ERROR: [n6] a panic has occurred!
12.5.2017 22:02:07*
12.5.2017 22:02:07*
12.5.2017 22:02:07* ERROR: [n6] Reported as error a5c612bc904a41ecbd3d5126e5f7d48a
12.5.2017 22:02:07*
12.5.2017 22:02:08SELECT pg_type.oid, typname   FROM pg_catalog.pg_type   LEFT   JOIN (select ns.oid as nspoid, ns.nspname, r.r           from pg_namespace as ns           join ( select s.r, (current_schemas(false))[s.r] as nspname                    from generate_series(1, array_upper(current_schemas(false), 1)) as s(r) ) as r          using ( nspname )        ) as sp     ON sp.nspoid = typnamespace  WHERE typname = $1  ORDER BY sp.r, pg_type.oid DESC LIMIT 1: interface conversion: parser.Datum is parser.dNull, not *parser.DTable
12.5.2017 22:02:08
12.5.2017 22:02:08goroutine 1584 [running]:
12.5.2017 22:02:08runtime/debug.Stack(0x7f4fbf2f7328, 0xc420458990, 0x18bea20)
12.5.2017 22:02:08	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x7f4fbf2f7328, 0xc420458990, 0x1914d60, 0xc4201efcf0, 0x1)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:89 +0x2af
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4206ce000, 0x7f4fbf2f7328, 0xc420458990)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0x99
12.5.2017 22:02:08panic(0x1914d60, 0xc4201efcf0)
12.5.2017 22:02:08	/usr/local/go/src/runtime/panic.go:489 +0x2cf
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc421084c00, 0x7f4fbf2f7328, 0xc421448510)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:353 +0x74
12.5.2017 22:02:08panic(0x1914d60, 0xc4201efcf0)
12.5.2017 22:02:08	/usr/local/go/src/runtime/panic.go:489 +0x2cf
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc4213d807f, 0x1be)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:499 +0x131
12.5.2017 22:02:08panic(0x194d260, 0xc420f23180)
12.5.2017 22:02:08	/usr/local/go/src/runtime/panic.go:489 +0x2cf
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*valueGenerator).Start(0xc4202681e0, 0x7f4fbf2f7328, 0xc421785590, 0x0, 0x0)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/generator.go:99 +0x12a
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).Start(0xc4218598c0, 0x7f4fbf2f7328, 0xc421785590, 0x0, 0x0)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:129 +0x48
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*joinNode).Start(0xc420231420, 0x7f4fbf2f7328, 0xc421785590, 0x0, 0x0)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/join.go:323 +0x8a
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).Start(0xc4218597a0, 0x7f4fbf2f7328, 0xc421785590, 0x0, 0x0)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:129 +0x48
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*joinNode).Start(0xc4202315e0, 0x7f4fbf2f7328, 0xc421785590, 0x0, 0x0)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/join.go:323 +0x8a
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*filterNode).Start(0xc420df6ab0, 0x7f4fbf2f7328, 0xc421785590, 0xc420df6a20, 0xc4201efc60)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/filter.go:60 +0x48
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).Start(0xc421859680, 0x7f4fbf2f7328, 0xc421785590, 0x0, 0xc4201efc60)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:129 +0x48
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*sortNode).Start(0xc4217d6c60, 0x7f4fbf2f7328, 0xc421785590, 0x0, 0xc4201efc20)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sort.go:362 +0x48
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*limitNode).Start(0xc420df6a20, 0x7f4fbf2f7328, 0xc421785590, 0x27d3060, 0xc420df6a20)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/limit.go:82 +0x4c
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*planner).startPlan(0xc420ba2c80, 0x7f4fbf2f7328, 0xc421785590, 0x27d3060, 0xc420df6a20, 0xc4210820f8, 0x5fa4e3)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:239 +0x8e
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execClassic(0xc420221340, 0xc420ba2c80, 0x27d3060, 0xc420df6a20, 0xc421082218, 0x0, 0x0)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1439 +0x93
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc420221340, 0x27ca2c0, 0xc421785560, 0xc420ba2c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1577 +0x78d
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc420221340, 0xc421bbe900, 0x27ca2c0, 0xc421785560, 0xc4201ae1d0, 0x2000101, 0x0, 0x0, 0x0, 0x0, ...)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1314 +0x463
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc420221340, 0xc421bbe900, 0xc4201aeb20, 0x1, 0x1, 0xc4201ae1d0, 0x101, 0x0, 0x0, 0xc421082b80, ...)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:955 +0x818
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc420221340, 0xc421bbe900, 0xc4201aeb20, 0x1, 0x1, 0xc4201ae1d0, 0x1, 0xc4201aeb38, 0x0, 0x0, ...)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:863 +0xd1
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func1(0x7f4fbf2f7328, 0xc421785590, 0xc421bbac60, 0xc4201aeb38, 0x0, 0x0)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:695 +0x1df
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc421bbac60, 0x7f4fbf2f7328, 0xc421785590, 0x10101, 0xc420410700, 0x0, 0x0)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:640 +0xb6
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420221340, 0xc421bbe900, 0xc4213d807f, 0x1be, 0xc4201ae1d0, 0x0, 0x0, 0x0, 0x0, 0x19a7c00)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:717 +0x66d
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420221340, 0xc421bbe900, 0xc4213d807f, 0x1be, 0xc4201ae1d0, 0x0, 0x0, 0x0, 0xc4213d8200)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:505 +0x11b
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc421084c00, 0xc4213d807f, 0x1be, 0xc4201ae1d0, 0xc4201ae1bc, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:836 +0x94
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc421084c00, 0xc421084c28, 0xc4213228a0, 0xc421084c45)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:823 +0x1e0
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc421084c00, 0x7f4fbf2f7328, 0xc421448510, 0xc4202065e0, 0x5400, 0xc420221d50, 0x0, 0x0)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:455 +0xb52
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420221c00, 0x7f4fbf2f7508, 0xc42137eb80, 0x27d2020, 0xc42054b360, 0x0, 0x0)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x926
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x27d2020, 0xc42054b360)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:621 +0x149
12.5.2017 22:02:08github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4206ce000, 0x7f4fbf2f7328, 0xc420458990, 0xc4203a4038, 0x27d2020, 0xc42054b360, 0xc4202bde00)
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xa9
12.5.2017 22:02:08created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
12.5.2017 22:02:08	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x267
```

**Comment by andreimatei** [comment]
I can reproduce without preparing the statement with:

```
SELECT pg_type.oid, typname   FROM pg_catalog.pg_type   LEFT   JOIN (select ns.oid as nspoid, ns.nspname, r.r           from pg_namespace as ns           join ( select s.r, (current_schemas(false))[s.r] as nspname                    from generate_series(1, array_upper(current_schemas(false), 1)) as s(r) ) as r          using ( nspname )        ) as sp     ON sp.nspoid = typnamespace  WHERE typname = 'xxx'  ORDER BY sp.r, pg_type.oid DESC LIMIT 1;
```

**Comment by jordanlewis** [comment]
Thanks for the report. There's a bug in `generate_series` that causes a panic when the second parameter is `NULL`.

```
root@:26257/> SELECT generate_series(1, array_upper(current_schemas(false), 1));
driver: bad connection
connection lost; opening new connection and resetting session parameters...
```

**Comment by jordanlewis** [comment]
I'm not totally sure what your query's intent is, but you should be able to work around the problem by checking if `current_schemas(false)` is empty before going ahead with the operation.

Sorry that you're experiencing this difficulty!

**Comment by hwaastad** [comment]
Hi,
it seems it was caused by a bad jdbc url (having no db set......as in jdbc:postgresql://<host>:<port>/) so there was no db defined. Obviously an user error, but that's not the first time...and I guess not the last it might happen ;-)

**Comment by knz** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/272095439/

**Comment by knz** [comment]
@jordanlewis I am a bit confused about this. If I understand correctly, set-generating functions construct thedata source in `getGeneratorPlan` which uses `(*FuncExpr).Eval()`. This should contain a check for NULL arguments. Why doesn't that check kick in here?

**Comment by jordanlewis** [comment]
The trouble is that the `Eval` is run in `valueGenerator.Start`, not before. During the data source construction phase in `planner.makeGenerator`, the expression is merely analyzed - not evaluated.

If it's valid to evaluate the expression during `makeGenerator`, we should just do that. If not, and it's in fact required that we hold off on evaluating the expression until the plan begins, we'll need to make a simple `NullValueGenerator` that simply returns no rows.

**Comment by knz** [comment]
Yeah it's not possible to Eval during Start, because the arguments themselves may contain subqueries. 
What you suggest is a good thing.
