### ISSUE TITLE
storage: fatal error "on-disk and in-memory state diverged"

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#16001]
build: 4e83bea
failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=250777&buildTypeId=Cockroach_Nightlies_ContinuousPhotos4Nodes6hours

Relevant logs:
```
E170517 08:05:54.052692 698917 util/log/crash_reporting.go:153  [n2,s2,r1/2:/{Min-System/}] Reported as error 45d48432d6be4cc39af443747445a270
F170517 08:05:54.052715 698917 storage/replica.go:1360  [n2,s2,r1/2:/{Min-System/}] on-disk and in-memory state diverged:
[RaftAppliedIndex: 841 != 840]
goroutine 698917 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xaaa00, 0x3246096, 0x2c2d100, 0x10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:858 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2c2e960, 0xc400000004, 0x24c35fa, 0x12, 0x550, 0xc420c6f740, 0x60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:724 +0x591
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f2e05caf9d0, 0xc420e9a840, 0x7f2e00000004, 0x2, 0x1b4a298, 0x28, 0xc421276c20, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:158 +0x4b3
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f2e05caf9d0, 0xc420e9a840, 0x1, 0xc400000004, 0x1b4a298, 0x28, 0xc421276c20, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:68 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x7f2e05caf9d0, 0xc420e9a840, 0x1b4a298, 0x28, 0xc421276c20, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:162 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).assertStateLocked(0xc420e7ce00, 0x7f2e05caf9d0, 0xc420e9a840, 0x27c76a0, 0xc420336e70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1360 +0x3b1
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).assertState(0xc420e7ce00, 0x7f2e05caf9d0, 0xc420e9a840, 0x27c76a0, 0xc420336e70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1346 +0xa0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleEvalResult(0xc420e7ce00, 0x7f2e05caf9d0, 0xc420e9a840, 0xc420cdd000, 0x2c703e8, 0x0, 0x0, 0xc4202a9bf0, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:802 +0x131
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).propose(0xc420e7ce00, 0x7f2e05caf9d0, 0xc420e9a840, 0x14bf5626386ce4aa, 0x1, 0x14bf562ae629c079, 0x10, 0x200000002, 0x2, 0x14bf562ae629c079, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2488 +0x2d0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc420e7ce00, 0x7f2e05caf9d0, 0xc420e9a840, 0x14bf562bf36aabdb, 0x7, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2237 +0x349
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc420e7ce00, 0x7f2e05caf9d0, 0xc420e9a840, 0x14bf562bf36aabdb, 0x7, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2091 +0x98
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc420e7ce00, 0x7f2e05caf9d0, 0xc420e9a840, 0x14bf562bf36aabdb, 0x7, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1425 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*pendingLeaseRequest).requestLeaseAsync.func1(0x7f2e05caf9d0, 0xc420ecbe60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go:213 +0x5a7
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc42055c5a0, 0x7f2e05d94118, 0xc420016488, 0x1b11d71, 0x3, 0x1, 0x0, 0x0, 0xc420b03440)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:294 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:295 +0x14a
```

Full log of crashing node:
[diverged.cockroach.stderr.txt](https://github.com/cockroachdb/cockroach/files/1008878/diverged.cockroach.stderr.txt)

Assigning to @petermattis for triage.

**Comment by a-robinson** [comment]
Already triaged, debugged, and fixed :) - https://github.com/cockroachdb/cockroach/issues/15979
