### ISSUE TITLE
bug: ORDER BY test OFFSET 10; panics the node if test is not indexed

### ISSUE THREAD

**Issue by tvi** [cockroachdb/cockroach#16090]
I have observed on my table when doing 
`SELECT * FROM "main_Customer" ORDER BY test LIMIT 10 OFFSET 10`
if test is not indexed column it returns always 0 rows; no matter how full the table is even with 30 rows (it should return 10).
Then I tried it without Limit
`SELECT * FROM "main_Customer" ORDER BY test OFFSET 10`
and my node panics.

If test is indexed everything works just as expected.

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

```
I170523 22:41:50.275998 1 util/log/clog.go:1011  [config] file created at: 2017/05/23 22:41:50
I170523 22:41:50.275998 1 util/log/clog.go:1011  [config] running on machine: bender
I170523 22:41:50.275998 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0 (darwin amd64, built 2017/05/10 13:17:56, go1.8.1)
I170523 22:41:50.275998 1 util/log/clog.go:1011  [config] arguments: [cockroach start --insecure --host=localhost]
I170523 22:41:50.275998 1 util/log/clog.go:1011  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
I170523 22:41:50.275998 1 cli/start.go:575  CockroachDB CCL v1.0 (darwin amd64, built 2017/05/10 13:17:56, go1.8.1)
I170523 22:41:50.379593 7 cli/start.go:338  starting cockroach node
W170523 22:41:50.382712 7 server/server.go:162  running in insecure mode, this is strongly discouraged. See --insecure.
W170523 22:41:50.386473 7 server/config_unix.go:106  soft open file descriptor limit 10240 is under the recommended limit 15000; this may decrease performance
please see https://www.cockroachlabs.com/docs/recommended-production-settings.html for more details
I170523 22:41:50.386737 7 storage/engine/rocksdb.go:380  opening rocksdb instance at "/Users/tvi/go/src/github.com/tvi/gotham/_examples/gorm/cockroach-data"
I170523 22:41:50.426046 7 server/config.go:421  1 storage engine initialized
I170523 22:41:50.426622 7 server/server.go:678  [n?] sleeping for 458.465224ms to guarantee HLC monotonicity
W170523 22:41:50.906472 97 storage/store.go:1339  [n1,s1,r5/1:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):1 not lease holder; lease holder unknown
I170523 22:41:50.906744 7 storage/store.go:1252  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170523 22:41:50.906832 7 server/node.go:467  [n1] initialized store [n1,s1]: {Capacity:249779191808 Available:128712523776 RangeCount:70 LeaseCount:0}
I170523 22:41:50.906879 7 server/node.go:351  [n1] node ID 1 initialized
I170523 22:41:50.906996 7 gossip/gossip.go:297  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"localhost:26257" > attrs:<> locality:<> 
I170523 22:41:50.907223 7 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I170523 22:41:50.908372 7 server/node.go:608  [n1] connecting to gossip network to verify cluster ID...
I170523 22:41:50.908401 7 server/node.go:633  [n1] node connected via gossip and verified as part of cluster "da78a4de-c3ab-4435-9b2c-8cab781af824"
I170523 22:41:50.908454 7 server/node.go:405  [n1] node=1: started with [[]=/Users/tvi/go/src/github.com/tvi/gotham/_examples/gorm/cockroach-data] engine(s) and attributes []
I170523 22:41:50.908638 7 sql/executor.go:338  [n1] creating distSQLPlanner with address {tcp localhost:26257}
I170523 22:41:50.914489 7 server/server.go:741  [n1] starting http server at localhost:8080
I170523 22:41:50.914509 7 server/server.go:742  [n1] starting grpc/postgres server at localhost:26257
I170523 22:41:50.914523 7 server/server.go:743  [n1] advertising CockroachDB node at localhost:26257
I170523 22:41:50.915103 7 server/server.go:853  [n1] done ensuring all necessary migrations have run
I170523 22:41:50.915123 7 server/server.go:855  [n1] serving sql connections
I170523 22:41:50.915229 7 cli/start.go:409  node startup completed:
CockroachDB node starting at 2017-05-23 22:41:50.915147736 +0200 CEST
build:      CCL v1.0 @ 2017/05/10 13:17:56 (go1.8.1)
admin:      http://localhost:8080
sql:        postgresql://root@localhost:26257?sslmode=disable
logs:       /Users/tvi/go/src/github.com/tvi/gotham/_examples/gorm/cockroach-data/logs
store[0]:   path=/Users/tvi/go/src/github.com/tvi/gotham/_examples/gorm/cockroach-data
status:     restarted pre-existing node
clusterID:  da78a4de-c3ab-4435-9b2c-8cab781af824
nodeID:     1
panic: row index 0 out of range

goroutine 478 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowContainer).At(0xc42098a000, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go:268 +0x205
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*rowContainer).MaybeReplaceMax(0xc42098a000, 0xc4216459e8, 0x6, 0x6, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/row_container.go:111 +0x4b
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortTopKStrategy).Execute(0xc42098a000, 0x6b9b8e8, 0xc421098330, 0xc421242000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorterstrategy.go:149 +0x10d
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sorter).Run(0xc421242000, 0x6b9b8e8, 0xc421098330, 0xc420543dd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:107 +0x2d4
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:321 +0x337

```

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

2. Please describe the issue you observed:

- What did you do?
```
SELECT * FROM "main_Customer" ORDER BY ID OFFSET 10;
connection lost; opening new connection and resetting session parameters...
+------------------------------------------+-----------------+-------------+--------------+------+------------------------------------------+
|                    id                    |      email      |    name     | phone_number | test |                test_test                 |
+------------------------------------------+-----------------+-------------+--------------+------+------------------------------------------+
| 6053d3343000fcc545d728765af98635b13b100e | email@email.com | FName LName |            0 | Test | 6053d3343000fcc545d728765af98635b13b100e |

SELECT * FROM "main_Customer" ORDER BY test OFFSET 10;
driver: bad connection
connection lost; opening new connection and resetting session parameters...
```

- What did you expect to see?

- What did you see instead?
Panic - node dies.

Table looks like this

```
CREATE TABLE "main_Customer" (
	id STRING NOT NULL,
	email STRING NULL,
	name STRING NULL,
	phone_number STRING NULL,
	test STRING NULL,
	test_test STRING NULL,
	CONSTRAINT "primary" PRIMARY KEY (id ASC),
	FAMILY "primary" (id, email, name, phone_number, test, test_test)
)
```

**Comment by jordanlewis** [comment]
Thanks for the report and sorry you're experiencing this difficulty.

I've confirmed your report:

```
root@:26257/test> create table t (a int);
CREATE TABLE
root@:26257/test> insert into t values(1),(2);
INSERT 2
root@:26257/test> SELECT a FROM t ORDER BY a LIMIT 1 offset 1;
+---+
| a |
+---+
+---+
(0 rows)
root@:26257/test> SELECT a FROM t ORDER BY a offset 1;
+---+
| a |
+---+
+---+
(0 rows)
```

The last command produces a panic:
```
panic: row index 0 out of range

goroutine 644 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowContainer).At(0xc420e12000, 0x0, 0x0, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go:268 +0x205
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*rowContainer).MaybeReplaceMax(0xc420e12000, 0xc420f799e8, 0x1, 0x1, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/row_container.go:111 +0x4b
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortTopKStrategy).Execute(0xc420e12000, 0x92235b8, 0xc420c9fc80, 0xc420cee000, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorterstrategy.go:149 +0x10d
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sorter).Run(0xc420cee000, 0x92235b8, 0xc420c9fc80, 0xc420563dd0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:107 +0x2d4
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:321 +0x337
```

Assigning to @RaduBerinde for DistSQL triage.

**Comment by RaduBerinde** [comment]
I am out until Mon. @andreimatei can you take a look? The code is for the
"top K" implementation which maintains a max heap of size K.

**Comment by RaduBerinde** [comment]
Possible workaround is to disable distsql in the session, SET DISTSQL = off

**Comment by andreimatei** [comment]
Looking

**Comment by andreimatei** [comment]
At least for the crash, the problem has to do different code seemingly treating both `0` and `MaxInt64` as "no limit", and the confusion leading to some bad arithmetic and integer overflow. Will figure it out.

**Comment by andreimatei** [comment]
@tvi Thanks for your report! The fix is going to part of bug-fix release to be done soon.
