### ISSUE TITLE
sql: recursive read lock acquisition in TestLogic

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#16141]
Observed in https://github.com/cockroachdb/cockroach/pull/16133 (https://teamcity.cockroachdb.com/viewLog.html?buildId=257029&buildTypeId=Cockroach_UnitTests) though I've actually seen sporadic `TestLogic` failures for a long time, but because of the obscurity of test output (see #16137), never investigated.

Relevant bits: 

```
goroutine 106673 [semacquire, 12 minutes]:
sync.runtime_Semacquire(0xc423ee39d8)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).Lock(0xc423ee39d0)
	/usr/local/go/src/sync/rwmutex.go:91 +0xdd
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*RWMutex).Lock(0xc423ee39d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/mutex_sync.go:70 +0x3b
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).updateSystemConfig(0xc423ee3860, 0xc4240c5800, 0x1c, 0x20)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:405 +0x4b
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).Start.func1(0x7fce4bea7800, 0xc424cabe30)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:375 +0x141
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423b42940, 0xc420fd06e0, 0xc420372400)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 107583 [semacquire, 12 minutes]:
sync.runtime_Semacquire(0xc423ee39dc)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).RLock(0xc423ee39d0)
	/usr/local/go/src/sync/rwmutex.go:43 +0x95
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).getDatabaseCache(0xc423ee3860, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:416 +0x54
github.com/cockroachdb/cockroach/pkg/sql.(*Session).resetForBatch(0xc42af18480, 0xc423ee3860)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:464 +0x3d
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).Prepare(0xc423ee3860, 0xc4221d0730, 0x1, 0x1, 0xc42af18480, 0xc420db6420, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:430 +0x85
github.com/cockroachdb/cockroach/pkg/sql.PreparedStatements.New(0xc42af18480, 0xc42b1cdef0, 0xc423ee3860, 0xc4221d070d, 0x1, 0xc4221d0730, 0x1, 0x1, 0x8, 0xc420db6420, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/prepare.go:99 +0x92
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc423ee3860, 0xc42af18480, 0x7fce1cc85e40, 0xc4208b8580, 0x0, 0xc420000101, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1308 +0x161d
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc423ee3860, 0xc42af18480, 0xc4221d06e0, 0x1, 0x1, 0x0, 0x101, 0x0, 0xc42001ec00, 0xc420467d40, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1018 +0xac3
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc423ee3860, 0xc42af18480, 0xc4221d06e0, 0x1, 0x1, 0x0, 0x1, 0xc4221d0708, 0x5926fd00, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:926 +0x107
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed.func1(0x7fce4bea7800, 0xc420db63f0, 0xc4211df080, 0xc4221d0708, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:758 +0x273
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc4211df080, 0x7fce4bea7800, 0xc420db63f0, 0x10101, 0xc421dda0e0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:640 +0xe3
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc423ee3860, 0xc42af18480, 0xc4221d06e0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:780 +0x7fe
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc423ee3860, 0xc42af18480, 0xc425234050, 0x15, 0x0, 0x0, 0x15, 0x15, 0x0, 0xc425234050)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:661 +0x918
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc423ee3860, 0xc42af18480, 0xc425234050, 0x15, 0x0, 0x0, 0x0, 0x0, 0xc421a84a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:528 +0x198
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc421a84a00, 0xc421a84a28, 0xc42af9f6e0, 0x51)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:505 +0x11d
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc421a84a00, 0x7fce4bea7800, 0xc42b1cde30, 0xc424fff0f0, 0x5400, 0xc42d5eaf50, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:432 +0x9f5
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42d5eae00, 0x7fce4bea8538, 0xc422a38c00, 0x307a900, 0xc422844e00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0xe7d
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x307bb00, 0xc42a1db7c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:626 +0x17f
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc420fd06e0, 0x7fce4bea7800, 0xc4212bf590, 0xc420541f38, 0x307bb00, 0xc42a1db7c0, 0xc4221e4510)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xdd
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x2f9
```

It's a bit hard to see what's going on here, but `TestLogic` uses a test hook that causes `sql.(*Executor).execParsed` to hold `sql.Executor.systemConfigMu` in read mode; it seems that `sql.(*Executor).execParsed` can wind up calling `sql.(*Executor).getDatabaseCache` which also attempts to acquire a read lock on `sql.Executor.systemConfigMu`. Meanwhile, a gossip update interleaving these events may attempt to acquire a **write** lock on `sql.Executor.systemConfigMu`, resulting in the deadlock above.

I'm going to submit a PR that makes the logic here easier to follow, but doesn't fix the problem.

**Comment by tamird** [comment]
@knz for triage.

**Comment by knz** [comment]
There's something I don't get: if I have two concurrent calls to a single mutex' Lock() method, I should see one of them succeed right? Why would they both hang against each other?

**Comment by tamird** [comment]
One is a call to Lock, the other is a call to RLock.

**Comment by knz** [comment]
@andreimatei I think you're the best person to look at this, next to Peter.

**Comment by petermattis** [comment]
`sync.RWMutex` can not safely be used recursively. The use of `RWMutex` here was too subtle. I'm going to get rid of it.
