### ISSUE TITLE
sqlccl: goroutine leak in TestBackupRestoreLocal

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#16190]
https://teamcity.cockroachdb.com/viewQueued.html?itemId=258801

```
<autogenerated>:12: Leaked goroutine: goroutine 7560 [select]:
    github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc424878a00, 0xc42490ee50, 0x5, 0x5, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:145 +0x70a
    github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc421d67d00, 0xc42490ee50, 0x5, 0x5, 0xc42002e800, 0xc4230e0b68, 0x6acb72)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:328 +0x79
    io.ReadAtLeast(0x2fe5260, 0xc421d67d00, 0xc42490ee50, 0x5, 0x5, 0x5, 0xc41ff6790d, 0x0, 0x0)
        /usr/local/go/src/io/io.go:307 +0xb7
    io.ReadFull(0x2fe5260, 0xc421d67d00, 0xc42490ee50, 0x5, 0x5, 0x0, 0x7, 0x18)
        /usr/local/go/src/io/io.go:325 +0x73
    github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc42490ee40, 0x7fffffff, 0x69cc9a, 0xc42001a000, 0xc42001a000, 0x2, 0x7, 0x6)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:255 +0xa0
    github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.recv(0xc42490ee40, 0x2ff90a0, 0x3e52b70, 0xc421d67d00, 0x2fed1e0, 0x3e52b70, 0x20ea200, 0xc4235e7510, 0x7fffffff, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:351 +0x61
    github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc420b5e580, 0x20ea200, 0xc4235e7510, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:379 +0x1da
    github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*distSQLFlowStreamClient).Recv(0xc4235e4a40, 0xb32cfa7e36aa308c, 0xc422413520, 0xc42030a880)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/api.pb.go:247 +0x86
    github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*outbox).waitForDrainSignalFromConsumer.func1(0xc424157920, 0x3002400, 0xc4235e4a40, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:285 +0x63
    created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*outbox).waitForDrainSignalFromConsumer
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:298 +0xc1
```

**Comment by tamird** [comment]
#16042, #16160.
