### ISSUE TITLE
server: failed to run migration "create system.jobs table"

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#16206]
https://sentry.io/cockroach-labs/cockroachdb/issues/270615506/

This fatal error happens during the setup phase of `TestRebalance_3To5Small`:
```
F170530 15:02:28.001741 9 server/server.go:848  [n1] failed to run migration "create system.jobs table": unexpected value: raw_bytes:"\254m\310!\001\036" timestamp:<wall_time:1496156520520292097 logical:0 >
goroutine 9 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0, 0x1a93c4, 0x2c82600, 0x10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:891 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2c83fe0, 0xc400000004, 0x24f7a1d, 0x10, 0x350, 0xc42137e820, 0x9f)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:761 +0x56c
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f37e32b7438, 0xc42017d560, 0x4, 0x2, 0x0, 0x0, 0xc42179d6a0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:158 +0x4b3
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f37e32b7438, 0xc42017d560, 0x1, 0x4, 0x0, 0x0, 0xc42179d6a0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:68 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x7f37e32b7438, 0xc42017d560, 0xc42179d6a0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:171 +0x76
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start(0xc42057e000, 0x7f37e32b7438, 0xc42017d560, 0xc4202a47c0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:848 +0x21bd
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1.1(0x7f37e32b7438, 0xc420014480, 0xc42000e050, 0xc420656000, 0xc4201a1210, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:357 +0x203
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1(0x7f37e32b7438, 0xc420014480, 0x2807bc0, 0xc4201ec038, 0xc42000e050, 0xc420656000, 0xc4201a1210, 0xc420666600)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:414 +0xdf
created by github.com/cockroachdb/cockroach/pkg/cli.runStart
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:417 +0x3b6
```

For some reason, the only nightly test this has affect is the [Allocator Test 3 to 5 10G test](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_AllocatorTest3to510g&tab=buildTypeHistoryList&branch_Cockroach_Nightlies=__all_branches__). The test fails during a health check that happens after the 4th and 5th nodes come up. Also, the last several failures of that test are all due to this error.

There are several interesting errors on the failed node that precede the fatal error:
```
E170530 14:54:58.541718 124 storage/replica_proposal.go:458  [n1,s1,r1/1:/M{in-ax}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
...
E170530 14:59:46.688098 1331 storage/replica_command.go:2149  [replica consistency checker,n1,s1,r315/1:/Table/51/1/17{30631…-63725…}] could not CollectChecksum from replica (n2,s2):2: rpc error: code = DeadlineExceeded desc = context deadline exceeded
...
(several of these)
E170530 15:00:19.408089 9 migrations/migrations.go:206  [n1] failed attempt to acquire migration lease: lease /System/"system-version/lease" is not available until at least 1496156446.966431523,0
...
E170530 15:00:23.506246 1983 storage/replica_range_lease.go:192  [n1,s1,r341/1:/Table/{0-11}] heartbeat failed on epoch increment
```

The various logs (e.g. [this one](https://teamcity.cockroachdb.com/viewLog.html?buildId=259160&buildTypeId=Cockroach_AllocatorTest3to510g&tab=artifacts)) have a lot more errors.

**Comment by a-robinson** [comment]
Ugh, this looks like a dumb mistake that I should have caught in code review. Thanks for triaging!
