### ISSUE TITLE
distsql: flow drain goroutine leak (detected via TestBackupRestoreLocal)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#16590]
Found here: https://teamcity.cockroachdb.com/viewQueued.html?itemId=274906

or here: https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=274901&_focus=1595

```
leaktest.go:90: Leaked goroutine: goroutine 7645 [select]:
	github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc420b218c0, 0xc4201e5b30, 0x5, 0x5, 0x0, 0x0, 0x0)
		/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:145 +0x556
	github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*transportReader).Read(0xc420a71890, 0xc4201e5b30, 0x5, 0x5, 0x6d37b4, 0xc422200ea0, 0x1b47470)
		/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:349 +0x55
	io.ReadAtLeast(0x26f1a60, 0xc420a71890, 0xc4201e5b30, 0x5, 0x5, 0x5, 0xc422392600, 0xc424ab5b00, 0x5)
		/usr/local/go/src/io/io.go:307 +0xa9
	io.ReadFull(0x26f1a60, 0xc420a71890, 0xc4201e5b30, 0x5, 0x5, 0x663901, 0xc42155f890, 0xc421c26cf0)
		/usr/local/go/src/io/io.go:325 +0x58
	github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc424ab5b00, 0xc4201e5b30, 0x5, 0x5, 0x2bd23c0, 0x2bd23c0, 0x18fa201)
		/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:333 +0xc8
	github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc4201e5b20, 0x400000, 0x18b6600, 0x2bd23c0, 0x19ed640, 0xc42026afb0, 0xc421c26db0, 0xc421c26db0)
		/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:280 +0x65
	github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.recv(0xc4201e5b20, 0x2705ba0, 0x2bd23c0, 0xc424ab5b00, 0x26f9920, 0x2bd23c0, 0x19c2ba0, 0xc4233a0670, 0x400000, 0x0, ...)
		/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:376 +0x4d
	github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc4221fac60, 0x19c2ba0, 0xc4233a0670, 0x0, 0x0)
		/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:393 +0xf2
	github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*distSQLFlowStreamClient).Recv(0xc4233a0660, 0x125690e, 0xc4240db0e0, 0xc421ee3080)
		/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/api.pb.go:244 +0x62
	github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*outbox).waitForDrainSignalFromConsumer.func1(0xc422864c60, 0x27100a0, 0xc4233a0660, 0x0, 0x0)
		/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:285 +0x52
	created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*outbox).waitForDrainSignalFromConsumer
		/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:298 +0x8a
```

cc @raduberinde @andreimatei

**Comment by RaduBerinde** [comment]
Dup of #16042.
