### ISSUE TITLE
bank example: http: Accept error: too many open files;

### ISSUE THREAD

**Issue by mbertschler** [cockroachdb/cockroach#1664]
I was playing around with cockroach when the bank example threw a lot of http errors. I am on OS X 10.10.4.
```
$ bank
A simple program that keeps moving money between bank accounts.

I0713 09:12:14.123718   17012 storage/engine/rocksdb.go:99] opening in-memory rocksdb instance
I0713 09:12:14.125376   17012 storage/range_command.go:782] range 1: new leader lease replica 1:1 01:00:00.000 +1436771535.125s
I0713 09:12:14.126568   17012 server/node.go:293] initialized store store=1:1 ([]=): {Capacity:499046809600 Available:107457851392 RangeCount:0 XXX_unrecognized:[]}
I0713 09:12:14.126614   17012 server/node.go:223] new node allocated ID 1
I0713 09:12:14.126709   17012 gossip/gossip.go:166] gossiping node descriptor node_id:1 address:<network:"tcp" address:"127.0.0.1:58579" > attrs:<> 
I0713 09:12:14.126737   17012 server/node.go:383] connecting to gossip network to verify cluster ID...
I0713 09:12:14.126831   17012 storage/range.go:1000] gossiping cluster id cluster-1 from store 1, range 1
I0713 09:12:14.126871   17012 storage/range.go:1008] gossiping sentinel from store 1, range 1
I0713 09:12:14.126890   17012 storage/range.go:1012] gossiping first range from store 1, range 1
I0713 09:12:14.126973   17012 storage/range.go:1061] gossiping accounting config from store 1, range 1
I0713 09:12:14.127012   17012 storage/range.go:1061] gossiping permissions config from store 1, range 1
I0713 09:12:14.127042   17012 storage/range.go:1061] gossiping user config from store 1, range 1
I0713 09:12:14.127075   17012 storage/range.go:1061] gossiping zones config from store 1, range 1
I0713 09:12:14.127117   17012 server/node.go:400] node connected via gossip and verified as part of cluster "cluster-1"
I0713 09:12:14.127151   17012 server/node.go:258] Started node with [[]=] engine(s) and attributes []
I0713 09:12:14.127235   17012 server/server.go:200] starting https server at 127.0.0.1:58579
I0713 09:12:14.127281   17012 server/testserver.go:79] Test server listening on https: 127.0.0.1:58579
I0713 09:12:14.149128   17012 rpc/client.go:122] client 127.0.0.1:58579 connected
I0713 09:12:14.616741   17012 examples/bank/bank.go:204] done initializing all accounts, bank is worth $1000000
1 transfers were executed at 1.0/second.
I0713 09:12:15.637818   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:15.650065   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 10ms
I0713 09:12:15.713213   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:15.743333   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:15.816734   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:15.871756   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 10ms
I0713 09:12:16.370093   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:16.458065   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:16.492533   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:17.011416   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:17.063657   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 10ms
The bank is in good order.
225 transfers were executed at 139.2/second.
I0713 09:12:17.401920   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:17.439273   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 10ms
I0713 09:12:17.770158   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:17.832057   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 10ms
I0713 09:12:17.891080   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:18.377365   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:18.404199   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:18.434297   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:18.541125   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:18.590909   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:18.783931   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
The bank is in good order.
209 transfers were executed at 110.4/second.
E0713 09:12:19.146252   17012 storage/queue.go:263] failure processing range range=1 ["" - "\xff\xff") from replicate queue: storage/allocator.go:204: unable to allocate a target store; no candidates available
I0713 09:12:19.158083   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:19.182503   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 10ms
I0713 09:12:19.254847   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 20ms
I0713 09:12:19.320085   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:19.370137   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:19.549289   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:19.564756   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:19.961044   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:20.000480   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:20.027217   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:20.365072   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:20.539497   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:20.556045   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:20.742905   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:21.297105   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:21.327932   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 10ms
I0713 09:12:21.361496   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:21.665681   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
I0713 09:12:21.691946   17012 server.go:1775] http: Accept error: accept tcp 127.0.0.1:58579: too many open files; retrying in 5ms
The bank is in good order.
226 transfers were executed at 86.0/second.
```

**Comment by bdarnell** [comment]
OSX has a very low default limit for the number of file descriptors (256), which isn't enough room for the bank example to run in its default configuration (100 parallel transfers, each using one file descriptor on the "client" and one on the "server". In this example the client and server are the same process).

You can run the bank example with reduced concurrency with `./bank --num-parallel-transfers=50`, or increase the limit by running `ulimit -n 1024` before running `bank`. We should probably just reduce the default for `--num-parallel-transfers` to 50.

Other options include forking separate processes for the client and server instead of running them in one process (only doubles our headroom, though), or replacing the HTTP/1 transport with something that can reuse connections (either HTTP/2 or our RPC system).

**Comment by mbertschler** [comment]
Thanks for that information, with `ulimit -n 1024` the example works. But when I try to run it with 200 parallel transfers i get:
```
$ bank -num-parallel-transfers 200
A simple program that keeps moving money between bank accounts.

I0713 18:26:11.592485   17708 storage/engine/rocksdb.go:99] opening in-memory rocksdb instance
I0713 18:26:11.594119   17708 storage/range_command.go:782] range 1: new leader lease replica 1:1 01:00:00.000 +1436804772.594s
I0713 18:26:11.595420   17708 server/node.go:293] initialized store store=1:1 ([]=): {Capacity:499046809600 Available:104678957056 RangeCount:0 XXX_unrecognized:[]}
I0713 18:26:11.595488   17708 server/node.go:223] new node allocated ID 1
I0713 18:26:11.595577   17708 gossip/gossip.go:166] gossiping node descriptor node_id:1 address:<network:"tcp" address:"127.0.0.1:59740" > attrs:<> 
I0713 18:26:11.595625   17708 server/node.go:383] connecting to gossip network to verify cluster ID...
I0713 18:26:11.595725   17708 storage/range.go:1000] gossiping cluster id cluster-1 from store 1, range 1
I0713 18:26:11.595766   17708 storage/range.go:1008] gossiping sentinel from store 1, range 1
I0713 18:26:11.595785   17708 storage/range.go:1012] gossiping first range from store 1, range 1
I0713 18:26:11.595869   17708 storage/range.go:1061] gossiping accounting config from store 1, range 1
I0713 18:26:11.595908   17708 storage/range.go:1061] gossiping permissions config from store 1, range 1
I0713 18:26:11.595937   17708 storage/range.go:1061] gossiping user config from store 1, range 1
I0713 18:26:11.595970   17708 storage/range.go:1061] gossiping zones config from store 1, range 1
I0713 18:26:11.596013   17708 server/node.go:400] node connected via gossip and verified as part of cluster "cluster-1"
I0713 18:26:11.596048   17708 server/node.go:258] Started node with [[]=] engine(s) and attributes []
I0713 18:26:11.596087   17708 server/server.go:200] starting https server at 127.0.0.1:59740
I0713 18:26:11.596121   17708 server/testserver.go:79] Test server listening on https: 127.0.0.1:59740
I0713 18:26:11.617163   17708 rpc/client.go:122] client 127.0.0.1:59740 connected
I0713 18:26:12.088228   17708 examples/bank/bank.go:204] done initializing all accounts, bank is worth $1000000
0 transfers were executed at 0.0/second.
The bank is in good order.
0 transfers were executed at 0.0/second.
E0713 18:26:16.639765   17708 storage/queue.go:263] failure processing range range=1 ["" - "\xff\xff") from replicate queue: storage/allocator.go:204: unable to allocate a target store; no candidates available
E0713 18:26:21.737141   17708 storage/queue.go:263] failure processing range range=1 ["" - "\xff\xff") from replicate queue: storage/allocator.go:204: unable to allocate a target store; no candidates available
E0713 18:26:26.813325   17708 storage/queue.go:263] failure processing range range=1 ["" - "\xff\xff") from replicate queue: storage/allocator.go:204: unable to allocate a target store; no candidates available
E0713 18:26:31.908470   17708 storage/queue.go:263] failure processing range range=1 ["" - "\xff\xff") from replicate queue: storage/allocator.go:204: unable to allocate a target store; no candidates available
E0713 18:26:35.085842   17708 client/txn.go:304] failure aborting transaction: txn "bank.go:149" id=74180183 key="000000890" pri=99.70110026 iso=SERIALIZABLE stat=PENDING epo=4 ts=1436804788.459179878,1 orig=1436804788.459179878,1 max=1436804783.761607170,0: timestamp regression: 1436804788.459179878,2; abort caused by: txn "bank.go:149" id=74180183 key="000000890" pri=99.70110026 iso=SERIALIZABLE stat=PENDING epo=4 ts=1436804788.459179878,1 orig=1436804788.459179878,1 max=1436804783.761607170,0: timestamp regression: 1436804788.459179878,2
F0713 18:26:35.085904   17708 examples/bank/bank.go:154] txn "bank.go:149" id=74180183 key="000000890" pri=99.70110026 iso=SERIALIZABLE stat=PENDING epo=4 ts=1436804788.459179878,1 orig=1436804788.459179878,1 max=1436804783.761607170,0: timestamp regression: 1436804788.459179878,2
goroutine 5150 [running]:
github.com/cockroachdb/cockroach/util/log.stacks(0xc2095c6001, 0x0, 0x0, 0x0)
	/Users/mbertschler/dev/src/golang/src/github.com/cockroachdb/cockroach/util/log/clog.go:865 +0xcd
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x4fbaa40, 0x3, 0x4f3d8ad, 0x15, 0x9a, 0x0, 0xc2095c60c0)
	/Users/mbertschler/dev/src/golang/src/github.com/cockroachdb/cockroach/util/log/clog.go:737 +0x11b
github.com/cockroachdb/cockroach/util/log.AddStructured(0x0, 0x0, 0x3, 0x2, 0x0, 0x0, 0xc20afd1f40, 0x1, 0x1)
	/Users/mbertschler/dev/src/golang/src/github.com/cockroachdb/cockroach/util/log/structured.go:39 +0x120
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x0, 0x0, 0xc20afd1f40, 0x1, 0x1)
	/Users/mbertschler/dev/src/golang/src/github.com/cockroachdb/cockroach/util/log/log.go:65 +0x82
github.com/cockroachdb/cockroach/util/log.Fatal(0xc20afd1f40, 0x1, 0x1)
	/Users/mbertschler/dev/src/golang/src/github.com/cockroachdb/cockroach/util/log/log.go:161 +0x75
main.(*Bank).continuouslyTransferMoney(0xc20801ed80, 0x64)
	/Users/mbertschler/dev/src/golang/src/github.com/cockroachdb/cockroach/examples/bank/bank.go:154 +0x313
created by main.main
	/Users/mbertschler/dev/src/golang/src/github.com/cockroachdb/cockroach/examples/bank/bank.go:271 +0x47d

21400 more lines of goroutines...
```

After `sudo ulimit -n 2048` 200 parallel transactions work again.

**Comment by bdarnell** [comment]
The timestamp regression bug is being tracked in #1350.

**Comment by mbertschler** [comment]
Okay thanks! I am just poking around a bit and think that cockroach is a very impressive project.
