### ISSUE TITLE
storage: panic in timestamp cache

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#16901]
https://teamcity.cockroachdb.com/viewLog.html?buildId=288188&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Running this test for a few minutes on my laptop didn't reproduce it.

Partial stack trace:

```
E170706 06:58:05.671928 47242518 util/log/crash_reporting.go:82  [n1] a panic has occurred!
W170706 06:58:05.672208 182 storage/store.go:3569  [n1,s1,r5/1:/Table/{0-11}] handle raft ready: 1.0s [processed=1]
E170706 06:58:05.675474 47242518 util/log/crash_reporting.go:183  [n1] Reported as error 3dfc345caf92466cb0c7c5136b0a76a4
panic: bad reqSize: 14 < 152 [recovered]
    panic: bad reqSize: 14 < 152 [recovered]
    panic: bad reqSize: 14 < 152

goroutine 47242518 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4200b0630, 0x7f0b2111e8c0, 0xc42cea8c00)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:180 +0xb1
panic(0x186ebe0, 0xc4295ce150)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send.func1(0xc4283eb540, 0xc4283eb5b0, 0x14ceab7e3f00479a, 0x0, 0xc4283eb5a8, 0xc420214800)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2491 +0x224
panic(0x186ebe0, 0xc4295ce150)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/storage.(*timestampCache).ExpandRequests(0xc4200ee000, 0x14cea8d5d767f9f7, 0xc400000000, 0xc4203dc6b8, 0x2, 0x8, 0xc42a390fd0, 0xf, 0x10)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/timestamp_cache.go:659 +0x5c0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyTimestampCache(0xc4201fee00, 0xc4319dbab0, 0xc42cea8c00, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2093 +0x176
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc4201fee00, 0x7f0b2111e8c0, 0xc42cea8cf0, 0x14cea8d5d767f9f7, 0x0, 0x100000001, 0x1, 0x5, 0x3ff0000000000000, 0xc426516820, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2465 +0x27f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc4201fee00, 0x7f0b2111e8c0, 0xc42cea8cf0, 0x14cea8d5d767f9f7, 0x0, 0x100000001, 0x1, 0x5, 0x3ff0000000000000, 0xc426516820, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2342 +0x9d
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc4201fee00, 0x7f0b2111e8c0, 0xc42cea8cf0, 0x14cea8d5d767f9f7, 0x0, 0x100000001, 0x1, 0x5, 0x3ff0000000000000, 0xc426516820, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1677 +0x23d
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc420214800, 0x7f0b2111e8c0, 0xc42cea8c30, 0x14cea8d5d767f9f7, 0x0, 0x100000001, 0x1, 0x5, 0x3ff0000000000000, 0xc426516820, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2593 +0x5ad
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc4205b0800, 0x7f0b2111e8c0, 0xc42cea8c00, 0x0, 0x0, 0x100000001, 0x1, 0x5, 0x3ff0000000000000, 0xc426516820, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x1ea
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x7f0b2111e8c0, 0xc42cea8c00, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:821 +0x19d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc4200b0630, 0x7f0b2111e8c0, 0xc42cea8c00, 0x1aaa9f0, 0x10, 0xc4283eb820, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0xf7
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc420527b80, 0x7f0b2111e8c0, 0xc42cea8c00, 0xc42779cf48, 0xc42cea8c00, 0x1f, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:832 +0x119
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc420527b80, 0x7f0b2111e8c0, 0xc42cea8c00, 0xc42779cf48, 0x1f, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:849 +0x99
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1.1(0xc42b07fdb0, 0xc42779cf20, 0x7f0b2111e8c0, 0xc42cea8a50, 0xc420ba7788, 0xed8b70, 0x7f0b2111e8c0)
    /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:257 +0x49e
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1(0xc42b07fdb0, 0xc42779cf20, 0x7f0b2111e8c0, 0xc42cea8a50, 0x272fa40, 0xc4203bc1c0, 0xc42c8c41e0)
    /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:270 +0x7e
created by github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext
    /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:283 +0x141
```

**Comment by tschottdorf** [comment]
Do you know what statement(s) it was running when this happened?

**Comment by mjibson** [comment]
Nope. This is further complicated because it was running 20 go routines each generating random statements.

**Comment by petermattis** [comment]
Ugh, I thought these panics were behind me.

**Comment by tschottdorf** [comment]
👃 👈

**Comment by petermattis** [comment]
@mjibson Has there been any reproduction of this? I just unsuccessfully took a crack at trying to reproduce and also spent a while staring at the code to see what accounting was missed.

**Comment by mjibson** [comment]
I have not seen this again in the RSG tests, no. However they were broken for a while and now have a test that fails every night, so it could be a rare thing that will come up later. I'm not opposed to bumping to 1.2 or some other later milestone.

**Comment by petermattis** [comment]
@nvanbenschoten Seems like this will go away with the skiplist-based timestamp cache implementation.

**Comment by nvanbenschoten** [comment]
Yeah, and it will be replaced with a handful just like it. I'll be sure to close when the skiplist-based timestamp cache is added.
