### ISSUE TITLE
rocksdb: range deletion tombstones + IngestExternalFile likely still crashes

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16922]
Noticed during restore testing on top of 9cffddae94eabcb66982e3426952decd07ff43c0. Happened fairly regularly:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1806aed]

runtime stack:
runtime.throw(0x1ce8004, 0x2a)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 47 [syscall, locked to thread]:
non-Go function
        pc=0x1806aed
non-Go function
        pc=0x1787ca1
non-Go function
        pc=0x1788020
runtime.cgocall(0x1696080, 0xc440125f60, 0x7f3fb93ed8c0)
        /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc440125f10 sp=0xc440125ed0
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBIngestExternalFile(0x7f3fb93ed8c0, 0xc42bf8d200, 0x29, 0x1, 0x0, 0x0)
        github.com/cockroachdb/cockroach/pkg/storage/engine/_obj/_cgo_gotypes.go:425 +0x57 fp=0xc440125f60 sp=0xc440125f10
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).IngestExternalFile.func1(0x7f3fb93ed8c0, 0xc42bf8d200, 0x29, 0xc42bf8d201, 0x0, 0x0)
```

The issue went away with the following diff:

```diff
diff --git a/pkg/storage/replica_raftstorage.go b/pkg/storage/replica_raftstorage.go
index 972af1105..3c9435e08 100644
--- a/pkg/storage/replica_raftstorage.go
+++ b/pkg/storage/replica_raftstorage.go
@@ -611,7 +611,7 @@ func clearRangeData(
                // The metadata ranges have a relatively small number of keys making usage
                // of range tombstones (as created by ClearRange) a pessimization.
                var err error
-               if i < metadataRanges {
+               if true || i < metadataRanges { // HACK
                        err = batch.ClearIterRange(iter, keyRange.start, keyRange.end)
                } else {
                        err = batch.ClearRange(keyRange.start, keyRange.end)
```

I have a script that repros this, happy to share it privately.

@benesch, I'm throwing this your way as a follow-up to https://github.com/cockroachdb/cockroach/pull/16871.

**Comment by benesch** [comment]
Hmm, can't seem to reproduce. Could you apply https://github.com/facebook/rocksdb/commit/215076ef06eaa3d47771836a39c22160fbe05635 to c-deps/rocksdb in your branch and see if that fixes the problem?

**Comment by benesch** [comment]
`cd c-deps/rocksdb && git cherry-pick 215076e` applies cleanly for me.

**Comment by tschottdorf** [comment]
Works with the cherry-pick.
