### ISSUE TITLE
sql: panic: cannot reset if we've already sent results for this txn

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#17592]
panic while executing "SHOW KV TRACE FOR DROP USER IF EXISTS TIME , REPEATABLE , VARCHAR , ident , FILTER , NAME": cannot reset if we've already sent results for this txn

https://teamcity.cockroachdb.com/viewLog.html?buildId=320932&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Found with RSG.

**Comment by jordanlewis** [comment]
@mjibson this doesn't reproduce for me:

```
root@:26257/test> SHOW KV TRACE FOR DROP USER IF EXISTS "time", repeatable, "varchar", ident, filter, "name";
+-----------+-----+---------+---------+-----------+------+
| timestamp | age | message | context | operation | span |
+-----------+-----+---------+---------+-----------+------+
+-----------+-----+---------+---------+-----------+------+
(0 rows)
```

I'm nervous that this is a stateful issue. I'll keep digging.

**Comment by jordanlewis** [comment]
Repro:

```
root@:26257/> begin; SELECT generate_series(1, 10000); select crdb_internal.force_retry('1s'); end;
driver: bad connection
connection lost; opening new connection: all session settings will be lost
```

```
E170814 18:39:58.382124 263 sql/session.go:1128  [client=[::1]:62028,user=root,n1] a SQL panic has occurred!
E170814 18:39:58.382238 263 util/log/crash_reporting.go:81  [n1] a panic has occurred!
panic: cannot reset if we've already sent results for this txn [recovered]
        panic: panic while executing "begin; SELECT generate_series(1, 10000); select crdb_internal.force_retry('1s'); end;": cannot reset if we've already sent results for this txn [recovered]
        panic: panic while executing "begin; SELECT generate_series(1, 10000); select crdb_internal.force_retry('1s'); end;": cannot reset if we've already sent results for this txn [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4570507]

goroutine 263 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.sendCrashReport(0x77a41e0, 0xc420390f30, 0x0, 0x0, 0x54e14c0, 0xc420bb7820, 0x4)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:150 +0x37
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x77a41e0, 0xc420390f30, 0x0, 0x0, 0x559b2a0, 0xc420bc6fc0, 0x1)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:100 +0x320
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420510000, 0x77a41e0, 0xc420390f30)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:179 +0xab
panic(0x559b2a0, 0xc420bc6fc0)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc420abe000, 0x77a41e0, 0xc420231290)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:416 +0xa1
panic(0x559b2a0, 0xc420bc6fc0)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc420c56000, 0x575913d, 0x9, 0xc42065702c, 0x55)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1139 +0x28d
panic(0x54e14c0, 0xc420bb7750)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).Reset(0xc420abe000, 0x77a45c0, 0xc420bc86c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:1138 +0xad
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed.func1(0x77a45c0, 0xc420bc86c0, 0xc420e96420, 0xc420aca998, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:857 +0x1e3
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc420e96420, 0x77a45c0, 0xc420bc86c0, 0x1, 0xc420402600, 0x1614f135, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:722 +0xa8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc4203fe480, 0xc420c56000, 0xc42000aa00, 0x4, 0x4, 0x0, 0x0, 0xc420021900, 0x6274500)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:882 +0x47c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4203fe480, 0xc420c56000, 0xc42065702c, 0x55, 0x0, 0x0, 0x55, 0xfd4)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:767 +0x482
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4203fe480, 0xc420c56000, 0xc42065702c, 0x55, 0x0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:649 +0x129
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc420abe000, 0xc420abe028, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:578 +0x148
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420abe000, 0x77a41e0, 0xc420231290, 0xc420aca450, 0x5400, 0xc42001c568, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:496 +0x8bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42001c400, 0x77a45c0, 0xc420bc81c0, 0x629a8e0, 0xc420bcc0a0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x96c
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x629a8e0, 0xc420bcc0a0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/server/server.go:733 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc420510000, 0x77a41e0, 0xc420390f30, 0xc4206fe000, 0x629a8e0, 0xc420bcc0a0, 0xc420d4e000)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0x267
```

**Comment by mjibson** [comment]
Is this going to get resolved for the 1.1 release? It is still failing every day in RSG tests.

**Comment by jordanlewis** [comment]
Yes, @andreimatei has taken over my PR for this. I assume the failure against this statement is the same as my force_retry example.

**Comment by andreimatei** [comment]
Indeed. Working on it. Hope to have a PR out today.
