### ISSUE TITLE
sql: lookup by DB prefix is broken

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#17637]
panic while executing "SHOW EXPERIMENTAL_FINGERPRINTS FROM TABLE ident AS OF SYSTEM TIME 0": interface conversion: interface {} is nil, not *log.ReportingSettings

https://teamcity.cockroachdb.com/viewLog.html?buildId=322791&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Assigning for triage.

Found with RSG.

**Comment by dt** [comment]
#17629 ?

**Comment by tschottdorf** [comment]
Seeing this crash still means that `log.Fatal` was called. Repro locally:

```
root@:26257/> create database ident;
CREATE DATABASE

Time: 6.975057ms

root@:26257/> CREATE TABLE ident.ident (i INT);
CREATE TABLE

Time: 10.101891ms

root@:26257/> SHOW EXPERIMENTAL_FINGERPRINTS FROM TABLE ident.ident AS OF SYSTEM TIME 0;
driver: bad connection
```

```

F170814 13:56:53.139793 584 roachpb/data.go:749  [client=[::1]:55560,user=root,n1] uninitialized txn: "unnamed" id=65d3f76f key=/Min rw
=false pri=0.01368816 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000000,0 orig=0.000000000,0 max=0.000000000,0 wto=false rop=false seq
=1
goroutine 584 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x201, 0x82ef02f93, 0x678bc40, 0xc4206ac480)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:822 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x678d800, 0xc400000004, 0x61d5b11, 0xf, 0x2ed, 0xc420108a80,
0xdf)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:731 +0x55d
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x62b2400, 0xc420c867b0, 0xc400000004, 0x2, 0x56fa551, 0x15, 0xc421216dc0,
0x1, 0x1)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:161 +0x4c4
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x62b2400, 0xc420c867b0, 0x1, 0x4, 0x56fa551, 0x15, 0xc421216dc0, 0x1, 0x1)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:66 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x62b2400, 0xc420c867b0, 0x56fa551, 0x15, 0xc421216dc0, 0x1, 0x1)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:160 +0x7e
github.com/cockroachdb/cockroach/pkg/roachpb.(*Transaction).AssertInitialized(0xc420e930a0, 0x62b2400, 0xc420c867b0)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/data.go:749 +0xc3
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).validateTxnForBatch(0xc4201fa540, 0x62b2400, 0xc420c867b0, 0xc4200ac310, 0xc420c867b0, 0xc420e4e360)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:539 +0x6e
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc4201fa540, 0x62b2400, 0xc420c867b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420e930a0, ...)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:328 +0x6a5
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).send(0xc42017ce00, 0x62b2340, 0xc420e45880, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420e930a0, ...)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:554 +0x2ac
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Send(0xc4204abce0, 0x62b2340, 0xc420e45880, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:908 +0x31f
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Send-fm(0x62b2340, 0xc420e45880, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:486 +0x83
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0x62b2340, 0xc420e45880, 0xc421217c10, 0xc4215fce00, 0xc420412fa0, 0x568e380)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:463 +0x101
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Run(0xc4204abce0, 0x62b2340, 0xc420e45880, 0xc4215fce00, 0x0, 0x0)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:486 +0xd1
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Get(0xc4204abce0, 0x62b2340, 0xc420e45880, 0x55dc3e0, 0xc4203c1800, 0xc4202efb20, 0xc421217d88, 0x10, 0x0, 0x0, ...)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:337 +0x9d
github.com/cockroachdb/cockroach/pkg/sql.getDescriptor(0x62b2340, 0xc420e45880, 0xc4204abce0, 0x62a4300, 0xc4202efb20, 0x62be3c0, 0xc4203c17e0, 0x0, 0x0, 0x0)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/sql/descriptor.go:172 +0xc0
github.com/cockroachdb/cockroach/pkg/sql.getDatabaseDesc(0x62b2340, 0xc420e45880, 0xc4204abce0, 0x62ab140, 0xc420a221d0, 0xc4201a22cd, 0x5, 0x0, 0x0, 0x0)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/sql/database.go:125 +0x10c
```

**Comment by knz** [comment]
Simpler:

```sql
select 1 from nonexistent as of system time 0; -- works fine
select 1 from nonexistent.nonexistent as of system time 0; -- panic
```

so lookup by db prefix is broken. I know where to look
