### ISSUE TITLE
TestServer failed

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17864]
https://teamcity.cockroachdb.com/viewLog.html?buildId=332648&buildTypeId=Cockroach_UnitTests

among maybe other things,

```
E170823 18:29:54.330094 4909 util/log/crash_reporting.go:183  [n1] Reported as error 2ccc848528104376a732d4da09483ca7
panic: send on closed channel [recovered]
    panic: send on closed channel

goroutine 4909 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420a1a000, 0x7fb3853029e0, 0xc42130f050)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:182 +0xb2
panic(0x1938fa0, 0xc42027c7c0)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*RowChannel).Push(0xc4200af400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2799c60, 0xc4210d1aa0, 0x0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:320 +0x1d8
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).cancel(0xc420fad8c0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:459 +0x222
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Wait(0xc420fad8c0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:387 +0x11b
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ServerImpl).RunSyncFlow.func1(0x7fb385253170, 0xc42154f200)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/server.go:347 +0xfd
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask(0xc420a1a000, 0x7fb3853029e0, 0xc42130f050, 0x1b1b69f, 0x20, 0xc421633ba0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:230 +0xf7
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ServerImpl).RunSyncFlow(0xc420982c00, 0x27b9ce0, 0xc4201f9950, 0x27aa720, 0xc420982c00)
```

**Comment by andreimatei** [comment]
I hope it's the same as #17851

**Comment by tschottdorf** [comment]
Are you sure? This doesn't seem the same.

**Comment by andreimatei** [comment]
Well, same root cause - something seems funky with the new distsql cancellation.
