### ISSUE TITLE
storage: rocksdb hung on write

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#17902]
While running a 15 node, 2tb restore on GCE, one of the nodes repeatedly bricked, even after restart. The wedge was inside RocksDB: https://gist.github.com/benesch/bc4059f7d231921e5d674c416b4239c0

Looks like RocksDB is causing an infinite write stall because compactions aren't keeping up, or something. Perhaps a bad disk on this particular node, but perhaps a RocksDB bug (or a Cockroach + RocksDB interaction bug), so thought I'd flag it.

@petermattis, could you determine if this is worth investigating any further?

**Comment by benesch** [comment]
Also, I should note: that node managed to bring the restore to a halt, even though it was considered dead. As soon as I `killall -9 cockroach`'d the node, the restore proceeded. Something somewhere is missing a timeout. I know that's not much to go on.

**Comment by petermattis** [comment]
The log files contains some info about RocksDB-level "stalls". Search for `^Stalls`.

**Comment by benesch** [comment]
```Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 1 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 1 total count
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 395 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 394 total count
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 411 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 16 total count
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 427 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 16 total count
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 441 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 14 total count
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 454 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 13 total count```

I assume "454 slowdown for pending_compaction_bytes" is an indication of compaction stalls?

**Comment by petermattis** [comment]
Yes, that's an indication that compaction is keeping up. The other messages near those lines should indicate the number of pending compaction bytes.

**Comment by benesch** [comment]
Ok, here's some more context from before the last `Stalls` line above:

```
I170824 18:42:50.077486 277 server/status/runtime.go:223  [n3] runtime stats: 3.7 GiB RSS, 268 goroutines, 937 MiB/107 MiB/1.1 GiB GO alloc/idle/total, 2.3 GiB/2.6 GiB CGO alloc/total, 4461.88cgo/sec, 0.38/0.19 %(u/s)time, 0.00 %gc (0x)
W170824 18:42:54.654289 65623 storage/node_liveness.go:370  [replicate,n3,s3,r1186/1:/Table/51/1/583{17235…-72817…}] slow heartbeat took 60.0s
E170824 18:42:54.654306 65623 storage/replica_range_lease.go:192  [replicate,n3,s3,r1186/1:/Table/51/1/583{17235…-72817…}] context deadline exceeded
W170824 18:42:54.670005 231 storage/replica.go:1381  [replica consistency checker,n3,s3,r4012/1:/Table/51/1/2135{0626…-6224…}] have been waiting 1m0s attempting to acquire lease
W170824 18:42:54.670007 65674 storage/node_liveness.go:370  [replica consistency checker,n3,s3,r4012/1:/Table/51/1/2135{0626…-6224…}] slow heartbeat took 60.0s
E170824 18:42:54.670020 65674 storage/replica_range_lease.go:192  [replica consistency checker,n3,s3,r4012/1:/Table/51/1/2135{0626…-6224…}] context deadline exceeded
I170824 18:43:00.080999 277 server/status/runtime.go:223  [n3] runtime stats: 3.8 GiB RSS, 267 goroutines, 1012 MiB/34 MiB/1.1 GiB GO alloc/idle/total, 2.3 GiB/2.6 GiB CGO alloc/total, 4460.23cgo/sec, 0.39/0.19 %(u/s)time, 0.00 %gc (0x)
I170824 18:43:00.185286 274 storage/store.go:4142  [n3,s3] sstables (read amplification = 4):
3 [ 56M     8 ]: 16M 15M 10M[2] 4M 2M 3K 2K
4 [ 10G  3760 ]: 32M[66] 29M 26M[3] 25M[2] 23M 22M[2] 19M 17M 16M[36] 15M 12M 11M 10M[10] 9M[6] 7M 4M 3M 2M[3450] 1M[58] 1024K 1015K[2] 1003K 1001K 1000K 998K 993K 989K 972K 971K 949K 946K 940K 937K 918K 916K 913K 901K 890K 889K 882K 870K 860K[3] 841K 839K 835K 832K 831K 825K 823K[2] 818K 813K 811K 804K 790K 773K 769K 766K 764K 763K 762K 754K 753K 751K 741K 733K 729K 716K 713K[3] 710K 700K 687K 671K 665K 654K 651K 650K 636K 627K 625K 619K 606K 590K 581K 575K 574K 567K 555K[2] 553K 547K 537K 509K 493K 488K 479K 463K 457K 448K 446K 420K 413K 392K 365K 356K 305K 277K 181K 163K 150K 112K 85K 51K 40K 33K 14K 2K[15]
5 [ 11G   225 ]: 68M[3] 67M[2] 66M[5] 65M 64M[124] 60M 59M[4] 57M 47M 42M[21] 41M[17] 38M 37M[2] 35M 33M 27M 26M 25M 24M[2] 23M[4] 22M 20M 18M[9] 17M[2] 16M[4] 14M 8M 6M 5M 4M 1M 63K 14K 7K 5K 2K[4]
6 [ 39G 18188 ]: 68M[6] 67M[3] 66M[8] 65M[2] 64M[15] 59M 51M 42M[3] 41M[3] 40M 39M 37M 36M[2] 33M 32M[9] 30M 29M 27M 22M 21M[2] 19M 18M[2] 16M[10] 14M 12M 11M[4] 10M[5] 9M[2] 8M 7M 6M 5M 4M[3] 3M 2M[17376] 1M[48] 1023K[2] 1016K 1013K 1012K 1008K 1004K 1002K 998K 992K 991K 985K 983K 981K 967K 966K 965K[2] 963K 955K[2] 954K[2] 949K 948K 939K 938K 936K 915K 911K 908K 907K 904K 901K 900K 896K 895K 894K 891K 885K 884K 882K 880K 875K 873K 868K 867K 866K 865K 859K[2] 857K[3] 854K 852K[2] 851K[2] 848K 844K 842K 841K 835K 833K 831K 830K 829K[2] 828K[2] 827K 826K 824K 821K 819K 817K[2] 816K[3] 815K 814K 813K 811K 809K 806K 804K 802K 801K 796K 793K 792K 787K 785K 783K 781K[2] 780K 777K[2] 776K[2] 774K 771K 770K 768K 764K 760K 759K 758K 755K 754K 752K 750K 744K 742K 741K 739K 737K 734K 733K[2] 730K 729K 724K[2] 723K 721K 718K 717K 713K 712K 707K 706K 702K[2] 700K 699K 697K 696K 694K 693K 683K 681K 680K[2] 677K 676K 675K[2] 672K[2] 670K 666K 665K[2] 664K 663K[2] 661K[2] 660K 658K 655K 654K 652K 649K[2] 648K 646K[2] 643K 640K[2] 638K 632K[2] 631K 628K 625K 624K 622K 621K 618K[2] 617K 616K[2] 613K[3] 612K 611K 609K 602K 601K 600K 597K[2] 596K[2] 594K 591K 588K 584K[3] 583K 581K 580K 577K[2] 575K 574K 573K 571K[2] 568K 567K[2] 566K 564K 563K 560K[2] 558K 557K 555K 548K 547K 544K 542K 541K[2] 540K 539K[2] 536K[2] 534K[2] 533K[2] 530K 529K 527K 524K 522K 519K[2] 518K 517K[3] 514K 510K 506K 505K[2] 502K[2] 500K 498K 497K 495K 494K 493K[3] 491K 490K[2] 489K 486K 484K[2] 483K[2] 482K 480K 479K[2] 478K 477K[2] 476K 475K 473K 472K 471K[2] 468K 467K[2] 463K 461K 460K 459K 457K[2] 455K 452K 451K 450K 448K 445K 442K 440K 439K 438K[3] 437K[2] 435K 434K 433K[3] 432K 428K[3] 427K[3] 426K 424K[2] 423K 420K 419K[2] 417K[2] 416K 415K 414K 413K 411K[2] 410K 408K[2] 407K[2] 405K[2] 403K[2] 402K 401K 400K[3] 399K 397K 396K 395K 394K 393K 392K 391K 390K[2] 389K 387K 386K 385K 384K 383K 382K[2] 381K 379K 371K[3] 370K 368K[3] 367K[2] 364K[2] 361K 358K[2] 357K[2] 355K[2] 354K[2] 351K[2] 348K[2] 347K 344K[3] 340K[2] 336K 334K[2] 332K[3] 328K 327K[2] 324K 323K 321K 320K 317K 316K[2] 315K[2] 313K[2] 312K 311K 309K 308K[5] 307K 305K 302K[3] 299K 297K[2] 295K 292K 291K[2] 290K 289K 286K 285K 284K 282K[2] 280K 279K[2] 278K 277K[2] 275K 273K 271K 270K 268K[2] 267K 264K 263K[2] 260K 258K 256K[2] 250K 248K[2] 247K 246K 245K 244K 243K 242K 239K[3] 237K[2] 235K[2] 234K 233K 232K 231K[2] 230K 229K 228K[2] 227K 226K 225K[2] 224K 223K 220K[4] 219K 218K 217K[2] 214K[2] 213K 212K 211K 210K 209K[2] 208K 207K[2] 205K[2] 202K 200K 192K[2] 190K 187K 186K[2] 185K[3] 184K 181K[2] 180K 179K[2] 176K[4] 175K[2] 173K[2] 172K 170K[2] 168K 167K 164K 160K 156K 155K 154K[2] 152K[2] 151K 148K[2] 146K[2] 143K[3] 141K 140K 139K[2] 137K 133K 131K[2] 130K 128K 122K[2] 121K[3] 119K 118K 117K[2] 115K 114K[3] 113K 112K 110K 109K 108K 107K 106K[2] 105K[3] 101K 100K 98K[2] 96K[2] 95K 94K 91K 90K 89K 88K 86K[3] 84K 80K[2] 71K 70K 64K 62K 61K 59K 57K 56K 55K 49K 47K 45K[2] 44K 40K 39K[2] 38K 35K[2] 32K[2] 28K[2] 27K[3] 22K 17K 16K 13K 12K 10K[2] 6K[2] 5K 4K 2K[6]
I170824 18:43:00.186220 274 storage/store.go:4143  [n3,s3] 
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      0/0    0.00 KB   0.0      0.0     0.0      0.0       1.7      1.7       0.0   0.9      0.0    164.5        10        20    0.519       0      0
  L3      8/0   56.01 MB   0.9      2.5     1.7      0.8       2.5      1.6       0.0   1.5    144.4    142.0        18        15    1.180   2590K    60K
  L4   3760/1   10.13 GB  26.1      4.7     0.8      3.9       4.5      0.6       0.8   5.4     12.9     12.3       373       121    3.086   6762K   865K
  L5    225/118 11.15 GB   1.0    470.1     3.0    467.1     469.7      2.6       0.2 155.8    133.4    133.3      3608       188   19.194    689M   386K
  L6  18188/0   38.67 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.5   0.0      0.0      0.0         0         0    0.000       0      0
 Sum  22181/119 60.00 GB   0.0    477.3     5.5    471.8     478.3      6.5       1.5 261.7    121.9    122.1      4010       344   11.657    699M  1312K
 Int      0/0    0.00 KB   0.0     93.1     0.4     92.7      93.1      0.4       0.0 99959127040.0     94.1     94.1      1013        13   77.895    138M      0
Uptime(secs): 3438.2 total, 3438.2 interval
Flush(GB): cumulative 1.669, interval 0.000
AddFile(GB): cumulative 0.159, interval 0.000
AddFile(Total Files): cumulative 82, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 237406, interval 0
Cumulative compaction: 478.29 GB write, 142.45 MB/s write, 477.30 GB read, 142.16 MB/s read, 4009.9 seconds
Interval compaction: 93.09 GB write, 27.73 MB/s write, 93.09 GB read, 27.73 MB/s read, 1012.6 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 454 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 13 total count
```

I don't see anything there that would explain this:

```
goroutine 178 [syscall, 40 minutes, locked to thread]:
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBApplyBatchRepr(0x7f384ec580c0, 0xc420a73800, 0x381, 0x0, 0x0, 0x0)
	github.com/cockroachdb/cockroach/pkg/storage/engine/_obj/_cgo_gotypes.go:202 +0x57
github.com/cockroachdb/cockroach/pkg/storage/engine.dbApplyBatchRepr.func1(0x7f384ec580c0, 0xc420a73800, 0x381, 0xc44bfc1c00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1904 +0x89
github.com/cockroachdb/cockroach/pkg/storage/engine.dbApplyBatchRepr(0x7f384ec580c0, 0xc420a73800, 0x381, 0x400, 0xed1310a00, 0x2517e56d, 0x2f134a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1904 +0x70
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).ApplyBatchRepr(0xc420387900, 0xc420a73800, 0x381, 0x400, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:572 +0x56
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc42d848b40, 0xc424a3b800, 0xe9, 0x400)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1476 +0x3ba
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc42d848b40, 0x37fbc00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1412 +0x815
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyRaftCommand(0xc420cf4000, 0x7f3857768130, 0xc43cf12600, 0xc42915a158, 0x8, 0xc47080c200, 0x38, 0x40, 0xc47080c240, 0x38, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4500 +0x466
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc420cf4000, 0x7f3857768130, 0xc43cf12600, 0xc42915a158, 0x8, 0x8, 0x23, 0x300000003, 0x1, 0x14ddd9a575da7633, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4281 +0x52e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc420cf4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3432 +0x12db
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc420c8e400, 0x7f3857768130, 0xc461b96030, 0xc460fa0300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3177 +0xca2
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc420c8e400, 0x7f3857768130, 0xc420bcc420, 0x17f4)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3511 +0x18c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420c82090, 0x7f3857768130, 0xc420bcc420)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:227 +0x25f
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f3857768130, 0xc420bcc420)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420df38a0, 0xc4204239e0, 0xc420df3890)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:198 +0xad
```

**Comment by petermattis** [comment]
I have a vague recollection about a bug in RocksDB related to stalls.

**Comment by petermattis** [comment]
If you're encountering this repeatedly, you could try bumping `{soft,hard}_pending_compaction_bytes_limit` to some very large value. Those default to 64GB and 256GB respectively. I'm guessing that the 2MB sstables used for importing are counting towards the compaction bytes number.

**Comment by petermattis** [comment]
There is a `rocksdb.estimate-pending-compaction-bytes` property we could retrieve and log. See `DBImpl::GetStats` for an example of retrieving a property from RocksDB.

**Comment by benesch** [comment]
I can look into logging compaction bytes tomorrow; in the meantime, though, another restore wedged like this:

```
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:226
#1  0x00000000018e4da0 in ?? ()
#2  0x00000000018e4e5e in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#3  0x0000000001774674 in rocksdb::WriteThread::BlockingAwaitState(rocksdb::WriteThread::Writer*, unsigned char) ()
#4  0x0000000001774731 in rocksdb::WriteThread::AwaitState(rocksdb::WriteThread::Writer*, unsigned char, rocksdb::WriteThread::AdaptationContext*) ()
#5  0x0000000001775805 in rocksdb::WriteThread::EnterUnbatched(rocksdb::WriteThread::Writer*, rocksdb::InstrumentedMutex*) ()
#6  0x00000000016ca1df in rocksdb::DBImpl::IngestExternalFile(rocksdb::ColumnFamilyHandle*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, rocksdb::IngestExternalFileOptions const&) ()
#7  0x000000000168f900 in DBIngestExternalFile ()
#8  0x0000000001630499 in _cgo_983e885e771f_Cfunc_DBIngestExternalFile ()
#9  0x0000000000607e30 in _start ()
```

There's several other RocksDB threads with similar stacks, though often they got there through other means. E.g.:

```
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:226
#1  0x00000000018e4da0 in ?? ()
#2  0x00000000018e4e5e in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#3  0x0000000001774674 in rocksdb::WriteThread::BlockingAwaitState(rocksdb::WriteThread::Writer*, unsigned char) ()
#4  0x0000000001774731 in rocksdb::WriteThread::AwaitState(rocksdb::WriteThread::Writer*, unsigned char, rocksdb::WriteThread::AdaptationContext*) ()
#5  0x00000000016df947 in rocksdb::DBImpl::WriteImpl(rocksdb::WriteOptions const&, rocksdb::WriteBatch*, rocksdb::WriteCallback*, unsigned long*, unsigned long, bool) ()
#6  0x00000000016e0ffb in rocksdb::DBImpl::Write(rocksdb::WriteOptions const&, rocksdb::WriteBatch*) ()
#7  0x00000000016e10c4 in rocksdb::DB::Put(rocksdb::WriteOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::Slice const&) ()
#8  0x00000000016e1111 in rocksdb::DBImpl::Put(rocksdb::WriteOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::Slice const&) ()
#9  0x000000000168cac6 in DBImpl::Put(DBKey, DBSlice) ()
#10 0x000000000168e74a in DBPut ()
#11 0x0000000001630a5c in _cgo_983e885e771f_Cfunc_DBPut ()
#12 0x0000000000607e30 in _start ()
```

This looks worryingly like https://github.com/facebook/rocksdb/issues/2388.

**Comment by pkieltyka** [comment]
perhaps the pure Go implementation of rocksdb: badger

https://github.com/cockroachdb/cockroach/issues/17929

**Comment by petermattis** [comment]
@pkieltyka Badger is not a pure Go implementation of RocksDB. RocksDB provides significantly more functionality. It would be a very large project to switch.

**Comment by petermattis** [comment]
@benesch Is there anything you want me to do here? Is this still happening after bumping the restore sstable size?

**Comment by pkieltyka** [comment]
FWIW, I really want to use cockroachdb for my next project in prod, but Im concerned to rely on a cgo library for the storage engine. Specifically because its a blackbox to the runtime with memory leaks or other issues. I hope you guys look at badger sometime and add the missing features it requires and build on it, whatever those features of Rocksdb that you need whether its snapshots or whatever. The authors of badger have mentioned a few times that they want to keep it minimal (which is awesome), but all of RocksDB's features can be built ontop of badger with what exists today. Just my 2 cents of feedback.

**Comment by petermattis** [comment]
@pkieltyka I'm not sure that all of RocksDB's features can be built on top of Badger. For example, range deletion tombstones involve somewhat deep integration into the storage system. Regardless, I think it is possible that Badger could be extended to meet our needs, but doing so would require a very large amount of effort which we've concluded is not worth doing at this time. If you have an interest in doing so, I can sketch out just how much work would be involved, though this is not the issue to do it on.

PS Cgo isn't that scary. From my perspective, it would be scarier to rely on a brand new storage engine regardless of the language it was written in.

**Comment by petermattis** [comment]
With #18479 merged, I'm tossing this back your way @benesch.

**Comment by benesch** [comment]
The nightly 2tb restore has been quite happy recently, so punting to 1.2.

**Comment by benesch** [comment]
Haven't seen this in a good while, and it's always been a somewhat vague issue. Closing.
