### ISSUE TITLE
"descriptor is not initialized" panic

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#17952]
https://sentry.io/cockroach-labs/cockroachdb/issues/333879812/

```
*errors.errorString: string errors.go:280
  File "github.com/cockroachdb/cockroach/pkg/roachpb/errors.go", line 280, in NewRangeKeyMismatchError
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 1471, in requestCanProceed
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 3658, in processRaftCommand
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 2885, in handleRaftReadyRaftMuLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/store.go", line 3109, in processRaftRequest
...
(4 additional frame(s) were not displayed)

string errors.go:280
```

**Comment by irfansharif** [comment]
+cc https://github.com/cockroachdb/cockroach/issues/6027, https://github.com/cockroachdb/cockroach/pull/6143
We're hitting the following panic: https://github.com/cockroachdb/cockroach/blob/5b757262d33d814bda1deb2af20161a1f7749df3/pkg/roachpb/errors.go#L280

**Comment by kurttheviking** [comment]
I believe I just encountered this error after setting up a new instance though have not previously encountered this error before (this is also my first 1.0.6 node). Let me know if this is indeed similar and if there is any other debug info I can provide.

```
Build Tag:    v1.0.6
Build Time:   2017/09/14 15:15:48
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  8edb4c9235a7bb8aa80761375db12bb4a7e5afeb
Build Type:   release
```

```
* ERROR: a panic has occurred!
*
*
* ERROR: a panic has occurred!
*
*
* ERROR: Reported as error aa4407df2aca451ca0b66bf32445b3d9
*
descriptor is not initialized: r2:{-} [(n1,s1):1, next=2]

goroutine 3120 [running]:
runtime/debug.Stack(0x7f961a2febb8, 0xc420016468, 0x18ad1e0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x7f961a2febb8, 0xc420016468, 0x18ad1e0, 0xc420230680, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:121 +0x32b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4204c8c80, 0x7f961a2febb8, 0xc420016468)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0x99
panic(0x18ad1e0, 0xc420230680)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/roachpb.NewRangeKeyMismatchError(0xc420195da8, 0x1, 0x8, 0xc420195da8, 0x2, 0x8, 0xc420274480, 0xc420195dd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/errors.go:280 +0x218
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).requestCanProceed(0xc42036d200, 0xc420195da8, 0x1, 0x8, 0xc420195da8, 0x2, 0x8, 0x14e626fda7bd95e7, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1484 +0x1be
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).propose(0xc42036d200, 0x7f961a2a71c0, 0xc421502b40, 0xc42129f680, 0x14e626fda7bd95e7, 0x0, 0x0, 0x0, 0x2, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2493 +0x184
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc42036d200, 0x7f961a2a71c0, 0xc421502b40, 0x14e626fda7bd95e7, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2243 +0x301
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc42036d200, 0x7f961a2a71c0, 0xc421502b40, 0x14e626fda7bd95e7, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2097 +0x98
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc42036d200, 0x7f961a2a71c0, 0xc421502b40, 0x14e626fda7bd95e7, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1431 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*pendingLeaseRequest).requestLeaseAsync.func1(0x7f961a2a71c0, 0xc420327f80)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go:212 +0x599
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4204c8c80, 0x7f961a2febb8, 0xc420016468, 0x1aed671, 0x3, 0x1, 0x0, 0x0, 0xc420bda840)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:294 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:295 +0x14a
```

**Comment by irfansharif** [comment]
+cc @cuongdo for triage.

**Comment by a-robinson** [comment]
@kurttheviking Was this the first time that you started up the node or had you run it previously, stopped it, and restarted it?

If you could provide the rest of the logs, that would help as well. They're stored in the store directory, which by default is `cockroach-data` in your shell's working directory, so you'll find them in `cockroach-data/logs/` unless you passed a custom `--store` flag.

**Comment by kurttheviking** [comment]
@a-robinson in this case it was the very first time I started the node; since then I have not seen it.

I can pull the logs and send them your way. Do you want the entire directory? It seems like I've got a few files in there with `cockroach.log` aliased to the latest one.

**Comment by a-robinson** [comment]
Ooh that's very interesting. Yes, it'll be easiest if you just send the entire log directory along. If you don't want to post it here for some reason, you can also send it to alex at cockroachlabs.com

**Comment by kurttheviking** [comment]
@a-robinson just sent an email; thanks!

**Comment by a-robinson** [comment]
Tentatively bumping the milestone to 1.2, but will bring it back to 1.1 if the extra log file(s) I requested in the email thread contain enough info to track this down.

**Comment by a-robinson** [comment]
https://github.com/cockroachdb/cockroach/pull/20794#issuecomment-352525417

**Comment by mberhault** [comment]
Sentry issue: [COCKROACHDB-GC](https://sentry.io/cockroach-labs/cockroachdb/issues/558589820/)
