### ISSUE TITLE
panic: flow: no bytes in account to release, v1.1 alpha

### ISSUE THREAD

**Issue by d4l3k** [cockroachdb/cockroach#17980]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

```
I170828 16:02:37.934602 1 util/log/clog.go:975  [config] file created at: 2017/08/28 16:02:37
I170828 16:02:37.934602 1 util/log/clog.go:975  [config] running on machine: ashley
I170828 16:02:37.934602 1 util/log/clog.go:975  [config] binary: CockroachDB CCL v1.1-alpha.20170817 (linux amd64, built 2017/08/17 22:29:49, go1.8.3)
I170828 16:02:37.934602 1 util/log/clog.go:975  [config] arguments: [cockroach start --insecure --host=localhost --http-port 8181]
```

Full logs: https://gist.github.com/d4l3k/bc5c15060e0a7916232cdc41b4fa78ff
Running with only a single node on localhost.
Binary installed via https://aur.archlinux.org/packages/cockroachdb-bin/

Occured with version `1.1_alpha.20170803` and `1.1_alpha.20170817`.

2. Please describe the issue you observed:

- What did you do?

I launched a server and then attempted to query the DB instance via gorm/sql.
```
$ cockroach sql -d pok --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL v1.1-alpha.20170817 (linux amd64, built 2017/08/17 22:29:49, go1.8.3) (same version as client)
# Cluster ID: 862f1d8f-1c5d-4553-bf10-ed1bba297c26
#
# Enter \? for a brief introduction.
#
root@:26257/pok> SELECT * FROM models WHERE (models.deleted_at IS NULL) AND ((models.domain_id = 'luk.ai')) ORDER BY updated_at DESC LIMIT 15 OFFSET 0;
driver: bad connection
connection lost; opening new connection: all session settings will be lost
error retrieving the transaction status: read tcp 127.0.0.1:34568->127.0.0.1:26257: read: connection reset by peer
connection lost; opening new connection: all session settings will be lost
error retrieving the database name: dial tcp [::1]:26257: getsockopt: connection refused
```

- What did you expect to see?

It return the results.

- What did you see instead?

It panicked with

```
panic: flow: no bytes in account to release, current 1456, free 2064

goroutine 409 [running]:
github.com/cockroachdb/cockroach/pkg/sql/mon.(*BytesMonitor).ShrinkAccount(0xc421134d80, 0x7ff6ca23c918, 0xc4200144c8, 0xc42116fb68, 0x810)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/mon/bytes_usage.go:471 +0x1d5
github.com/cockroachdb/cockroach/pkg/sql/mon.(*BoundAccount).Shrink(0xc42116fb68, 0x7ff6ca23c918, 0xc4200144c8, 0x810)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/mon/bytes_usage.go:546 +0x52
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowContainer).PopFirst(0xc42116fb00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go:318 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortTopKStrategy).Execute(0xc4202c4c90, 0x7ff6ca1f2930, 0xc4211a0c60, 0xc421164900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorterstrategy.go:235 +0x284
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sorter).Run(0xc421164900, 0x7ff6ca1f2930, 0xc4211a0c60, 0xc42116f888)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:150 +0x652
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:360 +0x332
```

It's very reproducible. I just have to launch the server and run that SQL command.

**Comment by d4l3k** [comment]
Seems the minimum reproduce case is
```sql
SELECT * FROM models ORDER BY updated_at DESC LIMIT 15;
```
Interestingly
```sql
SELECT * FROM models ORDER BY updated_at LIMIT 15;
```
and
```sql
SELECT * FROM models ORDER BY updated_at DESC;
```
both work.

The `CREATE TABLE` statement: https://gist.github.com/d4l3k/290317fc62489cfa67aa99d2414281a0
Doesn't seem to be immediately reproducible just creating the table and running the query.

**Comment by d4l3k** [comment]
Here's a stripped down version of the SQL dump that can reproduce it on a clean instance.
https://gist.github.com/d4l3k/1990cb954417912bc545883412e8aec6

**Comment by d4l3k** [comment]
Discussion with @benesch  https://gitter.im/cockroachdb/cockroach?at=59a4b1f19acddb2407dbf57f

**Comment by benesch** [comment]
I think I found the bug, actually. Drawing up a PR.

**Comment by cuongdo** [comment]
Also, hello @d4l3k and thanks for the bug report!

**Comment by d4l3k** [comment]
@cuongdo Hey, happy to help!
