### ISSUE TITLE
cli/tables: pretty row formatter runs out of memory when formatting large results

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#18329]
This OOM occurred while running `SELECT * FROM tpch.lineitem ORDER BY l_extendedprice` which has a 25GB result set. Will try to get a memory profile but the culprit seems to be https://github.com/cockroachdb/cockroach/blob/91a299dd6205c23cb02fa601c3500850cb93605a/pkg/cli/format_table.go#L125

This issue should be reproducible with a faster query. Not sure who to assign here so assigning to @vivekmenezes for triage.

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1d10640, 0x16)
    /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xc6ca480000, 0x12000000, 0x7f0cfd3fd900, 0x2fc18d8)
    /usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x2f86f60, 0x12000000, 0x5cff71)
    /usr/local/go/src/runtime/malloc.go:440 +0x374
runtime.(*mheap).grow(0x2f86f60, 0x9000, 0x0)
    /usr/local/go/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0x2f86f60, 0x9000, 0x100)
    /usr/local/go/src/runtime/mheap.go:678 +0x44f
runtime.(*mheap).alloc_m(0x2f86f60, 0x9000, 0x100000000, 0xc400000000)
    /usr/local/go/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
    /usr/local/go/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0x7f0cfd3fdad8)
    /usr/local/go/src/runtime/asm_amd64.s:343 +0xab
runtime.(*mheap).alloc(0x2f86f60, 0x9000, 0x10100000000, 0x2f88370)
    /usr/local/go/src/runtime/mheap.go:628 +0xa0
runtime.largeAlloc(0x12000000, 0x7f0d024fe001, 0xc500000002)
    /usr/local/go/src/runtime/malloc.go:807 +0x93
runtime.mallocgc.func1()
    /usr/local/go/src/runtime/malloc.go:702 +0x3e
runtime.systemstack(0xc420452ba0)
    /usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
    /usr/local/go/src/runtime/proc.go:1132

    goroutine 1 [running]:
runtime.systemstack_switch()
    /usr/local/go/src/runtime/asm_amd64.s:281 fp=0xc420712e58 sp=0xc420712e50
runtime.mallocgc(0x12000000, 0x1bd34c0, 0x3000000001, 0x3400000036)
    /usr/local/go/src/runtime/malloc.go:703 +0x930 fp=0xc420712ef8 sp=0xc420712e58
runtime.newarray(0x1bd34c0, 0x200000, 0x0)
    /usr/local/go/src/runtime/malloc.go:833 +0x64 fp=0xc420712f38 sp=0xc420712ef8
runtime.hashGrow(0x1af95e0, 0xc4204fa060)
    /usr/local/go/src/runtime/hashmap.go:880 +0xbe fp=0xc420712f78 sp=0xc420712f38
runtime.mapassign(0x1af95e0, 0xc4204fa060, 0xc420713078, 0x2fc0ca0)
    /usr/local/go/src/runtime/hashmap.go:560 +0x375 fp=0xc420713018 sp=0xc420712f78
github.com/cockroachdb/cockroach/vendor/github.com/olekukonko/tablewriter.(*Table).parseDimension(0xc4206ba000, 0xc6203f1f10, 0x8, 0x0, 0x680000, 0xc5b4e064f0, 0x13, 0x40)
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/olekukonko/tablewriter/table.go:658 +0x2ce fp=0xc4207130b0 sp=0xc420713018
github.com/cockroachdb/cockroach/vendor/github.com/olekukonko/tablewriter.(*Table).Append(0xc4206ba000, 0xc5b4da8700, 0x10, 0x10)
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/olekukonko/tablewriter/table.go:236 +0xdd fp=0xc420713158 sp=0xc4207130b0
github.com/cockroachdb/cockroach/pkg/cli.printQueryOutput(0x2aa2500, 0xc42000e018, 0xc42049a300, 0x10, 0x10, 0x2aa68c0, 0xc4201dd8c0, 0x1cf47fa, 0x2, 0x0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/format_table.go:125 +0x1f3b fp=0xc420713798 sp=0xc420713158
github.com/cockroachdb/cockroach/pkg/cli.runQueryAndFormatResults(0xc420523580, 0x2aa2500, 0xc42000e018, 0xc420394360, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_util.go:494 +0x254 fp=0xc420713888 sp=0xc420713798
github.com/cockroachdb/cockroach/pkg/cli.(*cliState).doRunStatement(0xc420514f00, 0x2, 0x4)
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:971 +0xb5 fp=0xc4207138e8 sp=0xc420713888
github.com/cockroachdb/cockroach/pkg/cli.runInteractive(0xc420523580, 0xc42000a600, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1087 +0x6df fp=0xc420713a98 sp=0xc4207138e8
github.com/cockroachdb/cockroach/pkg/cli.runTerm(0x2a8d900, 0xc4201f54c0, 0x0, 0x1, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1148 +0x171 fp=0xc420713c18 sp=0xc420713a98
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x2a8d900, 0xc4201f54c0, 0x0, 0x1, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:35 +0x5a fp=0xc420713c90 sp=0xc420713c18
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x2a8d900, 0xc4201f5490, 0x1, 0x1, 0x2a8d900, 0xc4201f5490)
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:644 +0x3f8 fp=0xc420713d48 sp=0xc420713c90
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2a897c0, 0x5d876e, 0xc420054120, 0xc4206e7f00)
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:734 +0x339 fp=0xc420713e98 sp=0xc420713d48
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0x2a897c0, 0xc4206e7ef0, 0xc4200540f0)
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:693 +0x2b fp=0xc420713ec8 sp=0xc420713e98
github.com/cockroachdb/cockroach/pkg/cli.Run(0xc420010130, 0x2, 0x2, 0xc420014450, 0xc420432000)
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:155 +0x6d fp=0xc420713ef0 sp=0xc420713ec8
github.com/cockroachdb/cockroach/pkg/cli.Main()
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:52 +0x190 fp=0xc420713f78 sp=0xc420713ef0
main.main()
    /go/src/github.com/cockroachdb/cockroach/main.go:26 +0x20 fp=0xc420713f88 sp=0xc420713f78
runtime.main()
    /usr/local/go/src/runtime/proc.go:185 +0x20a fp=0xc420713fe0 sp=0xc420713f88
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420713fe8 sp=0xc420713fe0

    goroutine 17 [syscall, 12 minutes, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

    goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x2f7c200)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:998 +0x77
    created by github.com/cockroachdb/cockroach/pkg/util/log.init.1
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:575 +0xd9

    goroutine 9 [syscall, 12 minutes]:
os/signal.signal_recv(0x0)
    /usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
    created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

    goroutine 12 [select, 12 minutes]:
github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline.(*CancelableStdin).ioloop(0xc4205a5bc0)
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline/std.go:93 +0x247
    created by github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline.NewCancelableStdin
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline/std.go:86 +0xf1

    goroutine 13 [select, 12 minutes]:
github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline.(*Terminal).ioloop(0xc420292d20)
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline/terminal.go:129 +0x270
    created by github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline.NewTerminal
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline/terminal.go:38 +0x186

    goroutine 14 [select, 12 minutes, locked to thread]:
runtime.gopark(0x1ddc9d0, 0x0, 0x1cf8d8f, 0x6, 0x18, 0x2)
    /usr/local/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc420021f50, 0x0, 0x18)
    /usr/local/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc420021f50)
    /usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
    /usr/local/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

    goroutine 15 [chan receive, 12 minutes]:
github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline.DefaultOnWidthChanged.func1.1(0xc4205a5ec0)
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline/utils_unix.go:75 +0x53
    created by github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline.DefaultOnWidthChanged.func1
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline/utils_unix.go:81 +0xbc

    goroutine 16 [chan receive, 12 minutes]:
github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline.(*Operation).ioloop(0xc4205a5e60)
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline/operation.go:102 +0x61
    created by github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline.NewOperation
    /go/src/github.com/cockroachdb/cockroach/vendor/github.com/chzyer/readline/operation.go:86 +0x3b7
   Connection to cockroach-navy-0001.crdb.io closed.
```

**Comment by jordanlewis** [comment]
For what it's worth, this OOM is caused by `cockroach cli`, not the database itself.

**Comment by petermattis** [comment]
I don't think there is anything to do here for 1.1. I believe `--format=raw`, `--format=records` or `--format=sql` would avoid the crash by not buffering all of the rows. Would be good to verify that.

**Comment by jordanlewis** [comment]
The problem is that the CLI's pretty formatter buffers all rows in memory in order to determine the correct column padding to produce a nice looking output. One way to fix this would be to stop buffering rows once a threshold has been hit. Subsequent rows would then possibly be less pretty, but at least there'd be no OOM.

In the meantime, @asubiotto you can get around this by setting a different display_format like `csv` or `records`.

**Comment by jordanlewis** [comment]
Err, `csv` will definitely have the same problem.

**Comment by petermattis** [comment]
@jordanlewis `--format=csv` is going to have the same problem.

**Comment by jordanlewis** [comment]
`records`, `html`, `raw`, and `sql` are unaffected, though.

**Comment by knz** [comment]
I'll fix csv/tsv and I plan to replace the current tablewriter by a paging printer that supports streamed results.

**Comment by yiv** [comment]
same issue

**Comment by yiv** [comment]
same issue happened on v2.0.1

**Comment by knz** [comment]
Yes this is still a known issue. You can use `\set display_format csv` to work around.
