### ISSUE TITLE
server:Can this database be used on Windows server 2008?

### ISSUE THREAD

**Issue by skyformat99** [cockroachdb/cockroach#18504]
I want to test it and develop in Windows environment.
I tried it on windows server 2008 R2, but there was a lot of error.
So how do I solve this problem,thanks.
or，tell me build method in Windows。

C:\cockDB>.\cockroach.exe version
panic: CockroachDB requires Windows 8 or higher: Failed to find GetSystemTimePreciseAsFileTime
: The specified procedure could not be found.
goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/timeutil.init.1()
/go/src/github.com/cockroachdb/cockroach/pkg/util/timeutil/now_windows.go:27 +0x85
github.com/cockroachdb/cockroach/pkg/util/timeutil.init()
/go/src/github.com/cockroachdb/cockroach/pkg/util/timeutil/zoneinfo.go:48 +0xab
github.com/cockroachdb/cockroach/pkg/util/hlc.init()
/go/src/github.com/cockroachdb/cockroach/pkg/util/hlc/timestamp.pb.go:421 +0x66
github.com/cockroachdb/cockroach/pkg/storage/engine/enginepb.init()
/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/enginepb/rocksdb.pb.go:591
github.com/cockroachdb/cockroach/pkg/roachpb.init()
/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/method_string.go:17 +0x84
github.com/cockroachdb/cockroach/pkg/util/stop.init()
/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:521 +0x70
github.com/cockroachdb/cockroach/pkg/cli.init()
github.com/cockroachdb/cockroach/pkg/cli/_obj/_cgo_import.go:79 +0x69
main.init()
/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach-oss/main.go:26 +0x4b

**Comment by skyformat99** [comment]
hi,   Can you tell me the build method on windows?
thanks.

**Comment by petermattis** [comment]
@BramGruneir There is a comment in this code that the usage of `GetSystemTimePreciseAsFileTime` might not be needed with go1.9. I'm not sure if that removes the Windows 8 requirement. 

@skyformat99 I believe windows builds are performed using `build/builder.sh make build TYPE=release-windows`. This uses Docker on Mac/Linux to build a Windows binary. I'm not terribly familiar with the internals of what is going on there, but perhaps that provides you a starting point.

**Comment by skyformat99** [comment]
@petermattis thank you。
I want to use other function for replace GetSystemTimePreciseAsFileTime function.
