### ISSUE TITLE
sql: panic: unsupported result type: tuple{}

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18745]
```
CREATE DATABASE IF NOT EXISTS ident; CREATE TABLE IF NOT EXISTS ident.ident (ident decimal);
USE ident;
SELECT ARRAY[ROW()] AS "position" FROM ident;
```

Panics with:
```
panic while executing "SELECT ARRAY[ROW()] AS \"position\" FROM ident;": unsupported result type: tuple{}

goroutine 168 [running]:
runtime/debug.Stack(0x29dd3c0, 0xc420744090, 0xc420092000)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x29dd3c0, 0xc420744090, 0xc420092000, 0x19e8e80, 0xc4210cc5e0, 0x1)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:132 +0x155
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4200ae360, 0x29dd3c0, 0xc420744090)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:181 +0xf3
panic(0x19e8e80, 0xc4210cc5e0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc42050a600, 0x29dd3c0, 0xc420add4a0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:423 +0xa1
panic(0x19e8e80, 0xc4210cc5e0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc420afe000, 0x1bafa43, 0x9, 0xc420226075, 0x2d)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1382 +0x262
panic(0x1af5540, 0xc420dec900)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.getTypesForPlanResult(0x29ddd00, 0xc420b399e0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc4212ba340)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1712 +0x4b0
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).selectRenders(0xc420523800, 0xc42130d300, 0xc420b399e0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1178 +0x56
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createPlanForNode(0xc420523800, 0xc42130df18, 0x29ddd00, 0xc420b399e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2076 +0x5b4
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).PlanAndRun(0xc420523800, 0x29dd300, 0xc420c98f40, 0xc420d42580, 0x29ddd00, 0xc420b399e0, 0xc420e6c1e0, 0xa4fcf351bf47b9f, 0xf3c4bad7a9d7f194, 0x1, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:441 +0x138
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execDistSQL(0xc4200bf440, 0xc420afe210, 0x29ddd00, 0xc420b399e0, 0x29e9240, 0xc42050a600, 0x0, 0x14e7aaebfcc2ec48)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1863 +0x2ae
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc4200bf440, 0x29dfc40, 0xc420e910b0, 0x0, 0x0, 0x0, 0x14e7aaebfcc2ec48, 0x1, 0xc420af8f60, 0xc420afe210, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2055 +0x3bb
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc4200bf440, 0xc420afe000, 0x29dfc40, 0xc420e910b0, 0x0, 0x0, 0x0, 0x14e7aaebfcc2ec48, 0x1, 0xc420af8f60, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1745 +0x659
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc4200bf440, 0xc420afe000, 0x29dfc40, 0xc420e910b0, 0x0, 0x0, 0x0, 0x14e7aaebfcc2ec48, 0x1, 0xc420af8f60, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1311 +0x6a5
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc4200bf440, 0xc420afe000, 0xc420c98ec0, 0x1, 0x1, 0x0, 0x1, 0x1c80001, 0x0, 0x29e26a0, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1186 +0x3e5
github.com/cockroachdb/cockroach/pkg/sql.runWithAutoRetry(0xc4200bf440, 0xc420afe000, 0xc420c98ec0, 0x1, 0x1, 0xed15b0101, 0x0, 0x0, 0x3ff0000000000000, 0xc4212cb1e0, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1012 +0x350
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc4200bf440, 0xc420afe000, 0xc420c98ec0, 0x1, 0x1, 0x0, 0x0, 0xc420dec6c0, 0x7035e6f)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:831 +0x130
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4200bf440, 0xc420afe000, 0xc420226075, 0x2d, 0x0, 0x0, 0x2d, 0xc420226075)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:757 +0x50c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4200bf440, 0xc420afe000, 0xc420226075, 0x2d, 0x0, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:638 +0x1bd
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc42050a600, 0xc42050a628, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:612 +0x1d0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc42050a600, 0x29dd3c0, 0xc420add4a0, 0xc42024c7d0, 0x5400, 0xc420308168, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:503 +0x8ae
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420308000, 0x29dd300, 0xc420d46740, 0x29e9420, 0xc420ca23c0, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x929
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x29e9420, 0xc420ca23c0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/server/server.go:747 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4200ae360, 0x29dd3c0, 0xc420744090, 0xc42020e008, 0x29e9420, 0xc420ca23c0, 0xc4202ac600)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137 +0x263
```

Doesn't appear to be present on 1.1.

https://teamcity.cockroachdb.com/viewLog.html?buildId=359246&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Found with RSG.

**Comment by knz** [comment]
@justinj @lego not sure which of you two is more knowledgeable currently. Please take ownership as appropriate.

Context: empty tuples are a thing. Please check this specific expression but also other places where tuples are considered in the typing/eval logic.

**Comment by justinj** [comment]
I will investigate
