### ISSUE TITLE
Panic on Digital Ocean node

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#18813]
Background: I was running a 3-node cluster on Digital Ocean, with each node in a different data center, and tpcc running first through haproxy and then just against one node. The cluster did fine for ~12 hours. I then didn't look at it for a day or so. When I did look, node 2 had died with an out of memory error and node 1 was deadlocked. 

This issue covers the panic on node 2. @tschottdorf looked at this with me and asked me to open an issue with this panic.

Here's the version:

```
root@docs-1:~# cockroach version
Build Tag:    v1.1-beta.20170921
Build Time:   2017/09/21 15:48:53
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  be60cc5a4ccfb6a597a47f5eb9d0a88a0e1b1289
Build Type:   release-gnu
```

And here's the panic:

```
goroutine 224 [semacquire, 5797 minutes]:
sync.runtime_SemacquireMutex(0x2f7e228)
	/usr/local/go/src/runtime/sema.go:62 +0x34
sync.(*Mutex).Lock(0x2f7e224)
	/usr/local/go/src/sync/mutex.go:87 +0x9d
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*Mutex).Lock(0x2f7e224)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/mutex_sync.go:32 +0x2d
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2f7e200, 0xc400000003, 0x27b27e0, 0xe, 0x537, 0xc43049a500, 0x45)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:728 +0x12b
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f7fc9b809c8, 0xc42baa9640, 0x3, 0x2, 0x0, 0x0, 0xc421052660, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:162 +0x48f
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f7fc9b809c8, 0xc42baa9640, 0x1, 0xc400000003, 0x0, 0x0, 0xc421052660, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:54 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Shout(0x7f7fc9b809c8, 0xc42baa9640, 0x3, 0xc421052660, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:60 +0x9a
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc420f78000, 0x1cfe948, 0x9, 0xc42e1efa9b, 0x23)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1335 +0x25b
panic(0x1ae86c0, 0xc43cb06db0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputToStderr(0x2f7e200, 0x4, 0x14e6ccd48ec3380f, 0xe0, 0x27bbf29, 0x16, 0x2f0, 0xc426e61ce0, 0x150, 0xc424b50000, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:788 +0x11a
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2f7e200, 0xc400000004, 0x27bbf29, 0x16, 0x2f0, 0xc426e61ce0, 0x150)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:749 +0x227
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f7fc9b809c8, 0xc42baa9640, 0x4, 0x2, 0x1d5f684, 0x3c, 0xc421052cc8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:162 +0x48f
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f7fc9b809c8, 0xc42baa9640, 0x1, 0xc400000004, 0x1d5f684, 0x3c, 0xc421052cc8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:54 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x7f7fc9b809c8, 0xc42baa9640, 0x1d5f684, 0x3c, 0xc421052cc8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:148 +0x7e
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc429e9b4a0, 0x7f7fc9b809c8, 0xc42baa9640, 0x0, 0xc4246f6cb0, 0x1344158, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:752 +0x17f
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc4200ad200, 0xc420f78000, 0xc420d06e00, 0x1, 0x1, 0x0, 0x0, 0xc42001f300, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:861 +0x421
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4200ad200, 0xc420f78000, 0xc42e1efa9b, 0x23, 0x0, 0x0, 0x23, 0x565)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:748 +0x489
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4200ad200, 0xc420f78000, 0xc42e1efa9b, 0x23, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:629 +0x129
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc4206f2300, 0xc4206f2328, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:612 +0x148
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc4206f2300, 0x7f7fc9b805e8, 0xc4202dddd0, 0xc420271040, 0x5400, 0xc420709168, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:503 +0xbd0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420709000, 0x7f7fc9b809c8, 0xc420f575c0, 0x2ac49e0, 0xc420200d20, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x96c
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x2ac49e0, 0xc420200d20)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:746 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4203a65a0, 0x7f7fc9b805e8, 0xc4203e68a0, 0xc4201a2028, 0x2ac49e0, 0xc420200d20, 0xc420339a40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0x267
```

**Comment by tschottdorf** [comment]
Closing since @benesch has since worked on the logging mutexes.
