### ISSUE TITLE
stability: state diverged panics after disk full.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#18831]
`cyan` ran out of disk on all nodes.
Some nodes (eg: `cockroach-cyan-0004`) are shutting down soon after startup due to out-of-disk errors:
```
E170927 18:01:47.830056 1 cli/error.go:74  cockroach server exited with error: failed to create engines: could not open rocksdb instance: IO error: No space left on device/mnt/data1/614543.sst: No space left on device
Error: cockroach server exited with error: failed to create engines: could not open rocksdb instance: IO error: No space left on device/mnt/data1/614543.sst: No space left on device
```

But others (eg: `cockroach-cyan-0001`) are dying with "state diverged" panics:
```
I170927 18:00:39.183303 65 gossip/client.go:129  [n2] started gossip client to 192.168.1.6:26257
E170927 18:00:41.755661 144 storage/replica.go:1713  [n2,s2,r1/5:/{Min-System/}] on-disk and in-memory state diverged:
[GCThreshold.WallTime: 1505990704289372384 != 0 TxnSpanGCThreshold.WallTime: 1506077104289372384 != 0]
F170927 18:00:41.756234 144 storage/replica.go:1715  [n2,s2,r1/5:/{Min-System/}] {on-disk and in-memory state diverged: [GCThreshold.WallTime: 1505990704289372384 != 0 TxnSpanGCThreshold.WallTime: 1506077104289372384 != 0]}
goroutine 144 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x300b701, 0x14e849d2067cd35c, 0x283a12a, 0x12)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:833 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x300b780, 0xc400000004, 0x283a12a, 0x12, 0x6b3, 0xc42107e160, 0xaa)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:738 +0x5fc
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2b3d300, 0xc420730b10, 0x100000004, 0x2, 0x0, 0x0, 0xc4220a08c8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:153 +0x2fc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2b3d300, 0xc420730b10, 0x1, 0x4, 0x0, 0x0, 0xc4220a08c8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:54 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x2b3d300, 0xc420730b10, 0xc4220a08c8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:157 +0x76
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).assertStateLocked(0xc420199180, 0x2b3d300, 0xc420730b10, 0x2b46d20, 0xc4204803c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1715 +0x5c5
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleEvalResultRaftMuLocked(0xc420199180, 0x2b3d300, 0xc420730b10, 0x0, 0x30522c8, 0x0, 0x0, 0xc422505020, 0x1, 0x8, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:1027 +0x14b
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc420199180, 0x2b3d300, 0xc420730b10, 0xc422504f98, 0x8, 0xf124, 0x3e676, 0x200000002, 0x5, 0x14e7fa26f54ca2f9, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4465 +0x7f0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc420199180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3499 +0x1863
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc420199180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3192 +0xf8
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4204bd000, 0x2b3d300, 0xc42195c030, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3581 +0xda
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42072c090, 0x2b3d300, 0xc42195c030)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:216 +0x259
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2b3d300, 0xc42195c030)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc422052de0, 0xc42008a360, 0xc422052dd0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:198 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:191 +0xad
```

This is most likely a result of running out of disk, but should be checked.

**Comment by petermattis** [comment]
The state diverged might be fallout from #18689 which made `ReplicaState.{GCThreshold,TxnSpanGCThreshold}` nullable.

Cc @tschottdorf

**Comment by petermattis** [comment]
Ah, I think I see the problem. And yes, this was caused by #18689. Should be easy to fix.
