### ISSUE TITLE
sql, storage: errors on ROLLBACK lead to panics

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#18853]
A client gave us a panic:

```
E170927 14:50:01.485045 1104 util/log/crash_reporting.go:114  [n1] a panic has occurred!
panic: unexpected txnState when cleaning up: NoTxn [recovered]
        panic: panic while executing "ROLLBACK": unexpected txnState when cleaning up: NoTxn [recovered]
        panic: panic while executing "ROLLBACK": unexpected txnState when cleaning up: NoTxn [recovered]
        panic: panic while executing "ROLLBACK": unexpected txnState when cleaning up: NoTxn
goroutine 1104 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4205279e0, 0x7fe47bf3fbc0, 0xc4203f4360)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0xb2
panic(0x1b3b340, 0xc423209380)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc422b90300, 0x7fe47bf3fbc0, 0xc422ba4090)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:423 +0xa1
panic(0x1b3b340, 0xc423209380)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc422baf000, 0x1cfe948, 0x9, 0xc422eae392, 0x8)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1346 +0x28d
panic(0x1a7fc40, 0xc42326d500)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn.func1(0xc422a22598, 0xc422baf088, 0xc4206b8000, 0x0, 0xc42295d680, 0xc422baf000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1407 +0x1f8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc4206b8000, 0xc422baf000, 0x2abc2c0, 0x2fc1a60, 0x0, 0x0, 0x0, 0x14e856558a9a3a1e, 0x1d600000001, 0xc42309f260, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1496 +0xdd8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc4206b8000, 0xc422baf000, 0x2abc2c0, 0x2fc1a60, 0x0, 0x0, 0x0, 0x14e856558a9a3a1e, 0x1d600000001, 0xc42309f260, ...)
```

And a log message.

``` 
sql/executor.go:1651  [client=172.31.7.52:49144,user=root,n1] txn rollback failed: HandledRetryableTxnError: TransactionAbortedError: txn aborted "sql txn" id=3dd8473e key=/Table/54/1/"job_node12_145"/16/0 rw=true pri=0.09419308 iso=SERIALIZABLE stat=PENDING epo=1 ts=1506546759.929383122,0 orig=1506546759.929383122,0 max=1506546757.485196014,0 wto=false rop=false seq=2
```

I think we have a problem in the Executor because an error on Rollback is handled particularly and transitions the state to `NoTxn` in an unexpected place (`RollbackSQLTxn()`). It may be an artifact of the fact that `RollbackSQLTxn()` is called from multiple states.

Separately, it seems funky to me that we can get a retriable error from an `EndTransaction` request.

**Comment by andreimatei** [comment]
The SQL-level problem has been introduced in the change that introduced result streaming. `Executor.rollbackSQLTxn()` no longer respects its stated contract of not returning errors.
