### ISSUE TITLE
logging: panic not printed to log file

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#18907]
I'm running with `--logtostderr`. A panic seems to make it to the console but not to the log file.

The log file ends like this:
```
[andrei:~/work/src/github.com/cockroachdb/cockroach] e915821(+13/-1)+ 4s ± tail cockroach-data/logs/cockroach.log

E170929 03:09:41.434035 543 sql/session.go:1370  [client=[::1]:59084,user=root,n1] a SQL panic has occurred!
E170929 03:09:41.434211 543 util/log/crash_reporting.go:117  [n1] a panic has occurred!
```

The console shows:
```
E170929 03:09:41.434035 543 sql/session.go:1370  [client=[::1]:59084,user=root,n1] a SQL panic has occurred!
E170929 03:09:41.434211 543 util/log/crash_reporting.go:117  [n1] a panic has occurred!
panic: unexpected txnState when cleaning up: NoTxn [recovered]
	panic: panic while executing "ROLLBACK": unexpected txnState when cleaning up: NoTxn [recovered]
	panic: panic while executing "ROLLBACK": unexpected txnState when cleaning up: NoTxn [recovered]
	panic: panic while executing "ROLLBACK": unexpected txnState when cleaning up: NoTxn

goroutine 543 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4207b0000, 0x63508e0, 0xc42052cc60)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0x131
panic(0x5596540, 0xc422152400)
"cockroach-data/logs/cockroach.log" 27693L, 10387088C
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc421520c00, 0x63508e0, 0xc421453d10)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:423 +0xa1
panic(0x5596540, 0xc422152400)
	/Users/andrei/work/src/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc42156b000, 0x575e951, 0x9, 0xc42109b67c, 0x8)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1382 +0x262
panic(0x54dad00, 0xc420b537c0)
	/Users/andrei/work/src/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn.func1(0xc42303aae8, 0xc42156b090, 0xc420012fc0, 0x0, 0xc4241fe500, 0xc42156b000)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1559 +0x558
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc420012fc0, 0xc42156b000, 0x63530a0, 0x686e348, 0x0, 0x0, 0x0, 0x14e8b65bf58a4bea, 0x1, 0xc4241c9680, ...)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1649 +0xd58
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc420012fc0, 0xc42156b000, 0x63530a0, 0x686e348, 0x0, 0x0, 0x0, 0x14e8b65bf58a4bea, 0x1, 0xc4241c9680, ...)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1320 +0x6a5
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc420012fc0, 0xc42156b000, 0xc4241fe440, 0x1, 0x1, 0x0, 0x2, 0x6350000, 0x0, 0x6355b00, ...)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1195 +0x3e5
github.com/cockroachdb/cockroach/pkg/sql.runWithAutoRetry(0xc420012fc0, 0xc42156b000, 0xc4241fe440, 0x1, 0x1, 0x0, 0x0, 0x0, 0xfffffffe11293d00, 0xc4239e2b48, ...)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1021 +0x350
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc420012fc0, 0xc42156b000, 0xc4241fe440, 0x1, 0x1, 0x0, 0x0, 0xc424a10000, 0x9)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:840 +0x130
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420012fc0, 0xc42156b000, 0xc42109b67c, 0x8, 0x0, 0x0, 0x8, 0xc42109b67c)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:752 +0x49c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420012fc0, 0xc42156b000, 0xc42109b67c, 0x8, 0x0, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:638 +0x1bd
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc421520c00, 0xc421520c28, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:612 +0x1d0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc421520c00, 0x63508e0, 0xc421453d10, 0xc4202bf780, 0x5400, 0xc42072c368, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:503 +0x8ae
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42072c200, 0x6350820, 0xc421540300, 0x635ca00, 0xc4207d5a40, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x929
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x635ca00, 0xc4207d5a40)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/server/server.go:748 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4207b0000, 0x63508e0, 0xc42052cc60, 0xc42000e048, 0x635ca00, 0xc4207d5a40, 0xc420f9a060)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137 +0x263
```

**Comment by lego** [comment]
Possibly related, when using `--logtostderr=WARNING` panics don't go to stderr but instead go to logs.
