### ISSUE TITLE
stability: cyan unavailability after upgrade

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#18940]
`cyan` was upgraded from 8ec7c2b to 081f0ba on 2017-09-30-02:00:00 (rolling upgrade by continuous deployment).

During the upgrade process, cyan went from healthy to complete range unavailability:
![cyan_summary](https://user-images.githubusercontent.com/5901480/31085122-530d4db2-a764-11e7-9e18-bb479b4f1f3f.png)

The following days had multiple failures (most recent were OOM, have not looked at older ones yet), multiple other upgrade cycles by continuous deployment, but health remains the same:
![cyan_symmary_4d](https://user-images.githubusercontent.com/5901480/31085240-96463008-a764-11e7-82e9-ce6bb54e17b2.png)

Grabbing logs now before they get GCed. Will investigate further.
Pausing Continuous deployment.

**Comment by mberhault** [comment]
This did trigger `InstanceDown|Dead` alerts, but no other stable alerts. Some testing alerts went off (`UnavailableRanges`, `LivenessMismatch`) which should probably be upgraded to stable alerts.

**Comment by petermattis** [comment]
1eead4839153e660abb35bef386373cdd0af5ae1 looks like the more likely candidate of causing problems. Changing protos is fraught!

**Comment by mberhault** [comment]
Directly after restart, we're seeing a lot of `heartbeat failed on epoch increment` errors:
```
I170930 02:02:35.770185 50 server/server.go:945  [n5] starting https server at cockroach-cyan-05:8080
I170930 02:02:35.770492 50 server/server.go:946  [n5] starting grpc/postgres server at cockroach-cyan-05:26257
I170930 02:02:35.770516 50 server/server.go:947  [n5] advertising CockroachDB node at cockroach-cyan-05:26257
I170930 02:02:35.816981 106 gossip/client.go:129  [n5] started gossip client to cockroach-cyan-02:26257
I170930 02:02:35.823129 285 storage/raft_transport.go:455  [n5] raft transport stream to node 3 established
I170930 02:02:35.823736 283 storage/raft_transport.go:455  [n5] raft transport stream to node 2 established
I170930 02:02:35.824739 418 storage/raft_transport.go:455  [n5] raft transport stream to node 4 established
I170930 02:02:35.828979 284 storage/raft_transport.go:455  [n5] raft transport stream to node 6 established
I170930 02:02:35.841340 217 storage/node_liveness.go:355  [n5,hb] heartbeat failed on epoch increment; retrying
I170930 02:02:35.841703 50 server/server.go:1089  [n5] done ensuring all necessary migrations have run
I170930 02:02:35.841739 50 server/server.go:1091  [n5] serving sql connections
I170930 02:02:35.841976 50 cli/start.go:577  node startup completed:
I170930 02:02:35.848046 414 storage/raft_transport.go:455  [n5] raft transport stream to node 1 established
I170930 02:02:35.906848 217 storage/node_liveness.go:355  [n5,hb] heartbeat failed on epoch increment; retrying
I170930 02:02:36.104180 217 storage/node_liveness.go:355  [n5,hb] heartbeat failed on epoch increment; retrying
I170930 02:02:36.348093 217 storage/node_liveness.go:355  [n5,hb] heartbeat failed on epoch increment; retrying
I170930 02:02:36.753493 217 storage/node_liveness.go:355  [n5,hb] heartbeat failed on epoch increment; retrying
```

Missing quite a few logs due to log GC. This is from node 5.

**Comment by mberhault** [comment]
Given the complete lack of logs (except for node 5), I tried stopping the cluster and restarting it with the last good version deployed: 8ec7c2b
Cluster started happily, all ranges are available and traffic is flowing.
Will try to re-upgrade to see if I can get more details on what breaks.

**Comment by mberhault** [comment]
Upgraded a single node (`cockroach-cyan-0001`) to 081f0ba, other nodes still running 8ec7c2b.
Here's a sample failed heartbeat:
```
2017/10/02 16:58:01.674960 | 2.252176 | heartbeat
-- | -- | --
16:58:01.687361 | . 12401 | ... txnID:38af04ca-33e7-489d-a6bd-d37e27b5c93d
16:58:01.687404 | .    44 | ... [hb,n1] querying next range at /System/NodeLiveness/1
16:58:01.687447 | .    43 | ... [hb,n1] r3: sending batch 1 CPut, 1 BeginTxn, 1 EndTxn to (n3,s3):6
16:58:01.687463 | .    16 | ... [hb,n1] sending request to cockroach-cyan-03:26257
16:58:01.690015 | .  2551 | ... [hb,n1] reply error [txn: 38af04ca], BeginTransaction [/System/NodeLiveness/1,/Min), ConditionalPut [/System/NodeLiveness/1,/Min), EndTransaction [/System/NodeLiveness/1,/Min): unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 logical:0 >
16:58:01.690051 | .    37 | ... [hb,n1] error: unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 >
16:58:01.690063 | .    12 | ... [n1,hb] rolling back transaction
16:58:01.690085 | .    22 | ... storage/node_liveness.go:355 [n1,hb] heartbeat failed on epoch increment; retrying
16:58:01.762676 | . 72592 | ... txnID:20d70e68-9686-474e-be38-8f5877f763ad
16:58:01.762703 | .    26 | ... [hb,n1] querying next range at /System/NodeLiveness/1
16:58:01.762742 | .    40 | ... [hb,n1] r3: sending batch 1 CPut, 1 BeginTxn, 1 EndTxn to (n3,s3):6
16:58:01.762758 | .    16 | ... [hb,n1] sending request to cockroach-cyan-03:26257
16:58:01.764324 | .  1566 | ... [hb,n1] reply error [txn: 20d70e68], BeginTransaction [/System/NodeLiveness/1,/Min), ConditionalPut [/System/NodeLiveness/1,/Min), EndTransaction [/System/NodeLiveness/1,/Min): unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 logical:0 >
16:58:01.764361 | .    36 | ... [hb,n1] error: unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 >
16:58:01.764368 | .     7 | ... [n1,hb] rolling back transaction
16:58:01.764389 | .    22 | ... storage/node_liveness.go:355 [n1,hb] heartbeat failed on epoch increment; retrying
16:58:01.888523 | .124133 | ... txnID:3a35ee77-7f4a-4bed-becb-08d7d9495f13
16:58:01.888562 | .    39 | ... [hb,n1] querying next range at /System/NodeLiveness/1
16:58:01.888603 | .    41 | ... [hb,n1] r3: sending batch 1 CPut, 1 BeginTxn, 1 EndTxn to (n3,s3):6
16:58:01.888619 | .    16 | ... [hb,n1] sending request to cockroach-cyan-03:26257
16:58:01.893327 | .  4708 | ... [hb,n1] reply error [txn: 3a35ee77], BeginTransaction [/System/NodeLiveness/1,/Min), ConditionalPut [/System/NodeLiveness/1,/Min), EndTransaction [/System/NodeLiveness/1,/Min): unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 logical:0 >
16:58:01.893365 | .    38 | ... [hb,n1] error: unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 >
16:58:01.893373 | .     7 | ... [n1,hb] rolling back transaction
16:58:01.893395 | .    23 | ... storage/node_liveness.go:355 [n1,hb] heartbeat failed on epoch increment; retrying
16:58:02.139088 | .245693 | ... txnID:8b01fd59-2916-4ad9-a5c2-39941ffebbce
16:58:02.139135 | .    47 | ... [hb,n1] querying next range at /System/NodeLiveness/1
16:58:02.139177 | .    42 | ... [hb,n1] r3: sending batch 1 CPut, 1 BeginTxn, 1 EndTxn to (n3,s3):6
16:58:02.139193 | .    17 | ... [hb,n1] sending request to cockroach-cyan-03:26257
16:58:02.143004 | .  3811 | ... [hb,n1] reply error [txn: 8b01fd59], BeginTransaction [/System/NodeLiveness/1,/Min), ConditionalPut [/System/NodeLiveness/1,/Min), EndTransaction [/System/NodeLiveness/1,/Min): unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 logical:0 >
16:58:02.143044 | .    39 | ... [hb,n1] error: unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 >
16:58:02.143051 | .     7 | ... [n1,hb] rolling back transaction
16:58:02.143072 | .    22 | ... storage/node_liveness.go:355 [n1,hb] heartbeat failed on epoch increment; retrying
16:58:02.564920 | .421847 | ... txnID:70d2e98c-b096-4edd-a201-d3db7313252b
16:58:02.564962 | .    43 | ... [hb,n1] querying next range at /System/NodeLiveness/1
16:58:02.565037 | .    75 | ... [hb,n1] r3: sending batch 1 CPut, 1 BeginTxn, 1 EndTxn to (n3,s3):6
16:58:02.565057 | .    20 | ... [hb,n1] sending request to cockroach-cyan-03:26257
16:58:02.572322 | .  7265 | ... [hb,n1] reply error [txn: 70d2e98c], BeginTransaction [/System/NodeLiveness/1,/Min), ConditionalPut [/System/NodeLiveness/1,/Min), EndTransaction [/System/NodeLiveness/1,/Min): unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 logical:0 >
16:58:02.572358 | .    36 | ... [hb,n1] error: unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 >
16:58:02.572365 | .     7 | ... [n1,hb] rolling back transaction
16:58:02.572386 | .    21 | ... storage/node_liveness.go:355 [n1,hb] heartbeat failed on epoch increment; retrying
16:58:03.492051 | .919665 | ... txnID:3598f2fd-59f2-4526-b30b-9785e774c6dc
16:58:03.492107 | .    56 | ... [hb,n1] querying next range at /System/NodeLiveness/1
16:58:03.492162 | .    55 | ... [hb,n1] r3: sending batch 1 CPut, 1 BeginTxn, 1 EndTxn to (n3,s3):6
16:58:03.492180 | .    18 | ... [hb,n1] sending request to cockroach-cyan-03:26257
16:58:03.497115 | .  4934 | ... [hb,n1] reply error [txn: 3598f2fd], BeginTransaction [/System/NodeLiveness/1,/Min), ConditionalPut [/System/NodeLiveness/1,/Min), EndTransaction [/System/NodeLiveness/1,/Min): unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 logical:0 >
16:58:03.497154 | .    40 | ... [hb,n1] error: unexpected value: raw_bytes:"\207\361\325\230\003\010\001\0204\032\014\010\226\253\336\230\361\343\363\364\024\020\000 \001" timestamp:<wall_time:1506963471108565261 >
16:58:03.497161 | .     7 | ... [n1,hb] rolling back transaction
16:58:03.497184 | .    23 | ... storage/node_liveness.go:355 [n1,hb] heartbeat failed on epoch increment; retrying
```

**Comment by petermattis** [comment]
`NodeLiveness` does a `CPut` where it expects the old liveness record, which contains a timestamp, to have an expected value. So this uncovered another area of fragility with changing proto encoding: conditional puts.

**Comment by mberhault** [comment]
The `cockroach-cyan-0001` upgrade occurred at 171002 16:55:36.
Within minutes, two nodes crashed with checksum errors:

`cockroach-cyan-0002`:
```
E171002 16:56:42.850354 2309726 storage/replica_command.go:2294  [replica consistency checker,n2,s2,r427/3:/Table/51/1/-{228352…-192453…}] replica (n1,s1):1 is inconsistent: expected checksum 609aab499fb4e3bbde2a0badad65a213f780c8e551b47b6d9add80ebf293d8942fc878c7c2f50cb983e51c0ecd4102459b95041d852f9d374abb66f745415180, got 76b90ec244f194726424bdf301e8b9d43b1ab396012e901ed3690e9c44b29994812961306f4310afe23c231dd7bc18e42918865c6c67fd054d229d339554bbfb
E171002 16:56:42.851888 2309728 storage/replica_command.go:2314  [n2,s2,r427/3:/Table/51/1/-{228352…-192453…}] consistency check failed with 1 inconsistent replicas; fetching details
E171002 16:56:51.623005 2318192 storage/replica_command.go:2294  [n2,s2,r427/3:/Table/51/1/-{228352…-192453…}] replica (n1,s1):1 is inconsistent: expected checksum 9d0299013f2ec1fb33e3b4b241650de41f2878d979d6f6e6c8641d7293f7a6dd1abffbbd0af79fad69aa156d286637417b9b97d8dee8e42f22ef863e735987f1, got 76645b93aa7c02eaa7a531bd48147a8b6f016e6f5a3fd904d85a4313aad72ef7e8073b9f8fc97c4326f852fd023a60b17dd307cd93c415c8f053030f69935799
--- leaseholder
+++ follower
F171002 16:56:51.623093 2310322 storage/replica_command.go:2310  [n2,s2,r427/3:/Table/51/1/-{228352…-192453…}] consistency check failed with 1 inconsistent replicas
goroutine 2310322 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x2ff1901, 0x14e9cf3d174e2540, 0x2837f49, 0x1a)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:833 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2ff1940, 0xc400000004, 0x2837f49, 0x1a, 0x906, 0xc435478070, 0x67)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:738 +0x5fc
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2b3b280, 0xc42b6ddd10, 0x4, 0x2, 0x1d16899, 0x36, 0xc4237f6c00, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:153 +0x2fc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2b3b280, 0xc42b6ddd10, 0x1, 0xc400000004, 0x1d16899, 0x36, 0xc4237f6c00, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:54 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2b3b280, 0xc42b6ddd10, 0x1d16899, 0x36, 0xc4237f6c00, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:148 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc420939880, 0x2b3b280, 0xc42b6ddd10, 0xc4203e7050, 0xb, 0x10, 0xc4203e7070, 0xb, 0x10, 0x1, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:2310 +0x8f2
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeAdminBatch(0xc420939880, 0x2b3b280, 0xc42b6ddd10, 0x14e9cf3b0c86b961, 0x0, 0x200000002, 0x3, 0x1ab, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2370 +0x6e9
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc420939880, 0x2b3b280, 0xc42b6ddd10, 0x14e9cf3b0c86b961, 0x0, 0x200000002, 0x3, 0x1ab, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1798 +0x6ee
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc4206f8400, 0x2b3b280, 0xc42b6ddc50, 0x14e9cf3b0c86b961, 0x0, 0x200000002, 0x3, 0x1ab, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2574 +0x685
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc4206b9080, 0x2b3b280, 0xc42b6ddb90, 0x0, 0x0, 0x200000002, 0x3, 0x1ab, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:186 +0x22f
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x2b3b280, 0xc42b6ddb90, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:853 +0x1a7
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc420010360, 0x2b3b280, 0xc42b6ddb30, 0x1ccb964, 0x10, 0xc43468b8e8, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:248 +0xf7
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc4204f9800, 0x2b3b280, 0xc42b6ddb30, 0xc43244cde8, 0xc42b6ddb30, 0xd9bf4e, 0x2b3b1c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:840 +0x152
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc4204f9800, 0x2b3b280, 0xc42b6ddb30, 0xc43244cde8, 0x1f, 0xc42045ebf0, 0x5c0218)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:881 +0x9c
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1.1(0xc42c2720e0, 0xc43244cdc0, 0x2b3b1c0, 0xc421bf6c40, 0xce03b6, 0x2b3b280, 0xc42093fc50)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:224 +0x47b
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1(0xc42c2720e0, 0xc43244cdc0, 0x2b3b1c0, 0xc421bf6c40, 0xc424c1a960)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:237 +0xad
created by github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:200 +0x19a
```

`cockroach-cyan-0005`:
```
E171002 16:57:46.684885 2448450 storage/replica_command.go:2294  [replica consistency checker,n5,s5,r514/2:/Table/51/1/-5{12221…-08616…}] replica (n1,s1):1 is inconsistent: expected checksum 899caa9d257b3fd675a6a237565480ef36bff7d98a860dc9fcf8cff68f59fc9bc8d3d99c1c666909eaa98d502ed0207abfd096164743d37dec1239aa6df4a5a5, got 474a1351845ff2af5c8a3db38dee04becb36e70044ec96e544fa062f0bef5af0adc7211a8929ad7708353ef2be4a7233fcacb022b34bdcc783862e629a4ce5ce
E171002 16:57:46.685748 2453078 storage/replica_command.go:2314  [n5,s5,r514/2:/Table/51/1/-5{12221…-08616…}] consistency check failed with 1 inconsistent replicas; fetching details
E171002 16:57:53.271485 2455095 storage/replica_command.go:2294  [n5,s5,r514/2:/Table/51/1/-5{12221…-08616…}] replica (n1,s1):1 is inconsistent: expected checksum 38a88ca9f7c85c6bf871933944b7257da30f991b8c1a950c98ece1d82101db404f8e598ff38fe4b1d16e8c5bad97576ef84d1973fb942292580e0fbbac38cb0e, got 02b2f1747a688a544165eb773523f9b866c15c14f007faaf03b309b07a7662af064150cb9cdad5ea7d0b9cfc0dacee58f390aa96cd1d5a3a86ffab01fac014ba
--- leaseholder
+++ follower
F171002 16:57:53.271613 2453098 storage/replica_command.go:2310  [n5,s5,r514/2:/Table/51/1/-5{12221…-08616…}] consistency check failed with 1 inconsistent replicas
# Same stack trace as above.
```

**Comment by mberhault** [comment]
Flipped `cockroach-cyan-0001` back to 8ec7c2b (the "good" sha) and started the other two nodes again. All good so far, doesn't look like that state was persisted. Will wait some more.

**Comment by petermattis** [comment]
Heh, the consistency checker does:

```
		timestamp, err := protoutil.Marshal(&key.Timestamp)
		if err != nil {
			return nil, err
		}
```

This isn't a below Raft proto, but it does require we maintain the legacy timestamp format.

**Comment by mberhault** [comment]
Performed rolling upgrade to 051ca84caba334e1f5b62668ca7d71abbab23486. Things look good. Will keep an eye and reopen (or file new one) if problems crop up.
