### ISSUE TITLE
sql: panic - decoding unset EncDatum when running SHOW TRACE FOR SELECT COUNT(*)

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#18990]
## tl;dr

`SHOW [KV] TRACE SELECT COUNT(*) ...` panics with the stack trace 

```
panic while executing "SHOW TRACE FOR SELECT COUNT(*) FROM bar;": decoding unset EncDatum

goroutine 320 [running]:
runtime/debug.Stack(0x6399040, 0xc42053f170, 0xc4204f8c00)
        /usr/local/Cellar/go/1.9/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6399040, 0xc42053f170, 0xc4204f8c00, 0x55ace40, 0xc4202e4540, 0x1)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:133 +0x155
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4207445a0, 0x6399040, 0xc42053f170)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:181 +0xf3
panic(0x55ace40, 0xc4202e4540)
        /usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc420944300, 0x6399040, 0xc421047890)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:423 +0xa1
panic(0x55ace40, 0xc4202e4540)
        /usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc420684000, 0x5775a29, 0x9, 0xc4204472f8, 0x28)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1381 +0x262
panic(0x54f1040, 0x5a36600)
        /usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*EncDatum).EnsureDecoded(0xc420cb7bf0, 0xc420cb7cd0, 0x0, 0x0)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:175 +0x4ff
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.prettyEncDatums(0xc42047e070, 0x1, 0x1, 0x1, 0x2)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:305 +0x1bd
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).processKV(0xc420944728, 0x6398f80, 0xc42078be40, 0xc4203cc800, 0x4, 0x5, 0xc4203cc805, 0xc, 0xc, 0x14ea207369f8e5a4, ...)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:326 +0xdb5
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc420944728, 0x6398f80, 0xc42078be40, 0x1, 0xc420c50b01, 0x0, 0xc420cb8201, 0x0, 0x0)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:584 +0xae
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRowDecoded(0xc420944728, 0x6398f80, 0xc42078be40, 0x1, 0x0, 0xc4205b0e40, 0x72bfa88, 0x0, 0x576e101)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:606 +0x4c
github.com/cockroachdb/cockroach/pkg/sql.(*scanNode).Next(0xc420944600, 0x6398f80, 0xc42078be40, 0xc420684210, 0x30, 0x5693b80, 0xc420db4101)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/scan.go:174 +0x93
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).Next(0xc420508240, 0x6398f80, 0xc42078be40, 0xc420684210, 0x557d2e0, 0x68b8268, 0xc420cb8318)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:106 +0x56
github.com/cockroachdb/cockroach/pkg/sql.(*groupNode).Next(0xc420aec780, 0x6398f80, 0xc42078be40, 0xc420684210, 0x0, 0xc4205b0e00, 0x63a7fe0)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/group.go:356 +0x7c0
github.com/cockroachdb/cockroach/pkg/sql.(*traceNode).Next.func1(0x6398f80, 0xc42078be40, 0xc420684210, 0xc420cf5560)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/trace.go:109 +0x21b
github.com/cockroachdb/cockroach/pkg/sql.(*traceNode).Next(0xc420cf5560, 0x6398f80, 0xc42078be40, 0xc420684210, 0x0, 0x0, 0xc420684148)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/trace.go:129 +0xb1
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).Next(0xc420508120, 0x6398f80, 0xc42078be40, 0xc420684210, 0x1, 0xc420cf2880, 0xc420cb8618)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:106 +0x56
github.com/cockroachdb/cockroach/pkg/sql.(*windowNode).Next(0xc420ce8280, 0x6398f80, 0xc42078be40, 0xc420684210, 0x7257260, 0x0, 0xc420cf2880)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/window.go:473 +0x98
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).Next(0xc420508000, 0x6398f80, 0xc42078be40, 0xc420684210, 0x0, 0xc420780000, 0xc420cb8648)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:106 +0x56
github.com/cockroachdb/cockroach/pkg/sql.(*windowNode).Next(0xc420ce8500, 0x6398f80, 0xc42078be40, 0xc420684210, 0x0, 0xc420cf2880, 0xc420cb86b8)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/window.go:473 +0x98
github.com/cockroachdb/cockroach/pkg/sql.(*sortNode).Next(0xc42029b8f0, 0x6398f80, 0xc42078be40, 0xc420684210, 0x0, 0x0, 0x0)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/sort.go:453 +0xda
github.com/cockroachdb/cockroach/pkg/sql.forEachRow(0x6398f80, 0xc42078be40, 0xc420684210, 0x6399b40, 0xc42029b8f0, 0xc420cb8770, 0x0, 0xc420cb8798)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2027 +0x53
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execClassic(0xc420980000, 0xc420684210, 0x6399b40, 0xc42029b8f0, 0x63a4980, 0xc420944300, 0x0, 0x0)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2004 +0x2d2
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc420980000, 0x639be00, 0xc42028cb40, 0x0, 0x0, 0x0, 0x14ea209bc2d2e64a, 0x1, 0xc420cf4840, 0xc420684210, ...)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2158 +0x650
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc420980000, 0xc420684000, 0x639be00, 0xc42028cb40, 0x0, 0x0, 0x0, 0x14ea209bc2d2e64a, 0x1, 0xc420cf4840, ...)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1797 +0x6a1
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc420980000, 0xc420684000, 0x639be00, 0xc42028cb40, 0x0, 0x0, 0x0, 0x14ea209bc2d2e64a, 0x1, 0xc420cf4840, ...)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1322 +0x6a5
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc420980000, 0xc420684000, 0xc42078bd80, 0x1, 0x1, 0x0, 0x1, 0x5850001, 0x0, 0x639e260, ...)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1197 +0x3e5
github.com/cockroachdb/cockroach/pkg/sql.runWithAutoRetry(0xc420980000, 0xc420684000, 0xc42078bd80, 0x1, 0x1, 0xed1650101, 0x0, 0x0, 0x3ff0000000000000, 0xc420602248, ...)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1023 +0x39c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc420980000, 0xc420684000, 0xc42078bd80, 0x1, 0x1, 0x0, 0x0, 0xc420ac82a0, 0x29)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:840 +0x130
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420980000, 0xc420684000, 0xc4204472f8, 0x28, 0x0, 0x0, 0x28, 0xc4204472f8)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:752 +0x49c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420980000, 0xc420684000, 0xc4204472f8, 0x28, 0x0, 0x0, 0x0)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:638 +0x1bd
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc420944300, 0xc420944328, 0x0, 0x0)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:612 +0x1d0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420944300, 0x6399040, 0xc421047890, 0xc42028e070, 0x5400, 0xc4206ce168, 0x0, 0x0)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:503 +0x8ae
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4206ce000, 0x6398f80, 0xc42072ff00, 0x63a4b60, 0xc420eb0320, 0x0, 0x0)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x929
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x63a4b60, 0xc420eb0320)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:749 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4207445a0, 0x6399040, 0xc42053f170, 0xc420686000, 0x63a4b60, 0xc420eb0320, 0xc4205e33e0)
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /Users/richardwu/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137 +0x263
```

## Reproduction
```
CREATE DATABASE foo;

CREATE TABLE IF NOT EXISTS foo.bar (id INT PRIMARY KEY, data string);

INSERT INTO foo.bar VALUES (1, 'hello');

SHOW TRACE FOR SELECT COUNT(*) FROM foo.bar;
```

## Notes

- This only seems to affect `COUNT(*)` (that is, `COUNT(id)` or any other aggregate selects are not affect).
- `COUNT(*)` without `SHOW TRACE` is unaffected
- There must be at least one row for this to surface

cc: @jordanlewis

**Comment by jordanlewis** [comment]
Woop, definitely my bad.
