### ISSUE TITLE
sql: adminServer.RangeLog can trigger BytesMonitor panic

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#19110]
I've seen this panic twice, the first time with `3420` leftover bytes:

```
panic: session: unexpected 4887 leftover bytes

goroutine 2711187 [running]:
github.com/cockroachdb/cockroach/pkg/sql/mon.(*BytesMonitor).doStop(0xc453512d28, 0x2ecdb60, 0xc43630a240, 0xc453512101)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/mon/bytes_usage.go:388 +0x3af
github.com/cockroachdb/cockroach/pkg/sql/mon.(*BytesMonitor).Stop(0xc453512d28, 0x2ecdb60, 0xc43630a240)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/mon/bytes_usage.go:375 +0x44
github.com/cockroachdb/cockroach/pkg/sql.(*Session).Finish(0xc453512000, 0xc4200c86c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:551 +0x1cc
github.com/cockroachdb/cockroach/pkg/server.(*adminServer).RangeLog(0xc4202e1ae0, 0x2ecdc20, 0xc43b55b380, 0xc45a66efc0, 0xc4535e2420, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/admin.go:843 +0x1827
github.com/cockroachdb/cockroach/pkg/server/serverpb._Admin_RangeLog_Handler.func1(0x2ecdc20, 0xc440453d40, 0x1e16360, 0xc45a66efc0, 0x1e16360, 0xc45a66efc0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go:1591 +0x89
```

@knz wasn't the plan to disable these panics in production builds?

**Comment by BramGruneir** [comment]
A client had this happen as well.  Promoting it to a 2.0 issue.

**Comment by BramGruneir** [comment]
In our v2.0-alpha.20180129

```
goroutine 47355 [running]:
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc4269bda18, 0x34e0e00, 0xc425677040, 0xc429559101)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:387 +0x3af
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(0xc4269bda18, 0x34e0e00, 0xc425677040)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:374 +0x44
github.com/cockroachdb/cockroach/pkg/sql.(*Session).Finish(0xc4269bcc00, 0xc420095c00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:498 +0x1d0
github.com/cockroachdb/cockroach/pkg/server.(*adminServer).RangeLog(0xc4208c64d0, 0x34e0ec0, 0xc42607ae10, 0xc4264dab80, 0xc429089840, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/admin.go:844 +0x18f1
github.com/cockroachdb/cockroach/pkg/server/serverpb._Admin_RangeLog_Handler.func1(0x34e0ec0, 0xc42607ad20, 0x2238ba0, 0xc4264dab80, 0x2238ba0, 0xc4264dab80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go:1662 +0x89
github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x34e0ec0, 0xc42607ad20, 0x2238ba0, 0xc4264dab80, 0xc4264b8340, 0xc4264b8360, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:48 +0xa54
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func1(0x34e0ec0, 0xc42607ad20, 0x2238ba0, 0xc4264dab80, 0xc4264b8340, 0xc4264b8360, 0x346faec200000006, 0xc428975968, 0x6e4848, 0x70)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:166 +0xb9
github.com/cockroachdb/cockroach/pkg/server/serverpb._Admin_RangeLog_Handler(0x2334e80, 0xc4208c64d0, 0x34e0ec0, 0xc42607ad20, 0xc42ac481c0, 0xc4202f93a0, 0x0, 0x0, 0x873c3e, 0x730791)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go:1664 +0x16d
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4208e22c0, 0x34ec540, 0xc420568780, 0xc42babef00, 0xc4206cc000, 0x34a6518, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x96e
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4208e22c0, 0x34ec540, 0xc420568780, 0xc42babef00, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1143 +0x1528
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42027ca60, 0xc4208e22c0, 0x34ec540, 0xc420568780, 0xc42babef00)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:636 +0xa1
```

**Comment by jordanlewis** [comment]
@BramGruneir please add the executed SQL to this issue.

**Comment by BramGruneir** [comment]
```sql
SELECT timestamp, rangeID, storeID, eventType, otherRangeID, info 
FROM system.public.rangelog 
WHERE (rangeID = 1) OR (otherRangeID = 1) 
```

**Comment by vivekmenezes** [comment]
@BramGruneir I'd consider closing this issue.

**Comment by BramGruneir** [comment]
I don't think we've found the root of the problem.  But it is hard to reproduce without an cluster that is actively failing on the query.  At least now, it won't crash the node.  I'm cool with moving this later, but I'm uncomfortable closing it just yet.
