### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jethrogb** [cockroachdb/cockroach#19169]
I'm sometimes getting segmentation faults on nodes of one cluster. I haven't seen them on other clusters with the same DB schema. I've seen it on 1.0.3 and 1.0.6. It's always on SELECT queries on the same table.

```
I171010 17:00:27.294262 1 util/log/clog.go:1013  [config] file created at: 2017/10/10 17:00:27
I171010 17:00:27.294262 1 util/log/clog.go:1013  [config] running on machine: node2
I171010 17:00:27.294262 1 util/log/clog.go:1013  [config] binary: CockroachDB CCL v1.0.6 (linux amd64, built 2017/09/14 15:15:48, go1.8.3)
I171010 17:00:27.294262 1 util/log/clog.go:1013  [config] arguments: [/opt/cockroachdb/cockroach start --insecure --store /data/cockroachdb --advertise-host 10.197.65.2 --join 10.197.65.3 --join 10.197.65.4 --join 10.197.65.5 --join 10.197.65.1 --join 10.197.65.6]
```

Panic message:
```
E171010 18:10:35.724559 292046 util/log/crash_reporting.go:88  [n4] a panic has occurred!
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: SELECT * FROM public.__diesel_schema_migrations;: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: SELECT * FROM public.__diesel_schema_migrations;: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: SELECT * FROM public.__diesel_schema_migrations;: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11edcb5]

goroutine 292046 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42037e280, 0x7f02acec69a8, 0xc4204a4540)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xb1
panic(0x1903640, 0xc42018b880)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc423c86400, 0x7f02acec69a8, 0xc420c45a70)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:353 +0x74
panic(0x1903640, 0xc42018b880)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc42057904c, 0x30)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:499 +0x131
panic(0x192fbe0, 0x274dea0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).partitionSpans(0xc4203947e0, 0xc42284da98, 0xc4229efb60, 0x1, 0x1, 0x0, 0x0, 0xc420beb380, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:433 +0x5f5
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createTableReaders(0xc4203947e0, 0xc42284da98, 0xc42113c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:580 +0x128
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).createPlanForNode(0xc4203947e0, 0xc42284da98, 0x2796540, 0xc42113c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1436 +0x811
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).PlanAndRun(0xc4203947e0, 0x7f02acec69a8, 0xc422a47c20, 0xc420f769a0, 0x2796540, 0xc42113c000, 0xc423092600, 0x4, 0xed16f668b, 0x1b7daac6, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:402 +0x120
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execDistSQL(0xc420154c40, 0xc42059d980, 0x2796540, 0xc42113c000, 0xc422852280, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1448 +0x240
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc420154c40, 0x278d5a0, 0xc422a47b60, 0xc42059d980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1601 +0x41f
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc420154c40, 0xc420597b00, 0x278d5a0, 0xc422a47b60, 0x0, 0x101, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1340 +0x463
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc420154c40, 0xc420597b00, 0xc420467fb0, 0x1, 0x1, 0x0, 0x101, 0x0, 0x0, 0xc4249dcbf8, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:955 +0x818
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc420154c40, 0xc420597b00, 0xc420467fb0, 0x1, 0x1, 0x0, 0x1, 0xc420467fc0, 0xc4249dcd00, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:863 +0xd1
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func1(0x7f02acec69a8, 0xc422a47c20, 0xc420f769a0, 0xc420467fc0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:695 +0x1df
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc420f769a0, 0x7f02acec69a8, 0xc422a47c20, 0x10101, 0xc422aa0000, 0x1b7d24ca, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:641 +0xb6
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420154c40, 0xc420597b00, 0xc42057904c, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420579000)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:717 +0x66d
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420154c40, 0xc420597b00, 0xc42057904c, 0x30, 0x0, 0x0, 0x0, 0x0, 0xc420579000)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:505 +0x11b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc423c86400, 0xc42057904c, 0x30, 0x0, 0x0, 0x0, 0x0, 0x99fa01, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:836 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc423c86400, 0xc423c86428, 0xc424a32300, 0x51)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:504 +0xa9
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc423c86400, 0x7f02acec69a8, 0xc420c45a70, 0xc4203066d0, 0x5400, 0xc420227490, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:432 +0x8bd
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420227340, 0x7f02acec6bc8, 0xc422934f80, 0x2795300, 0xc4212560a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x926
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x2795300, 0xc4212560a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:615 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc42037e280, 0x7f02acec69a8, 0xc4204a4540, 0xc42000e068, 0x2795300, 0xc4212560a0, 0xc4232b3800)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x267
```

Other config I've seen it on:
```
I171007 13:08:47.698282 1 util/log/clog.go:1011  [config] file created at: 2017/10/07 13:08:47
I171007 13:08:47.698282 1 util/log/clog.go:1011  [config] running on machine: test1
I171007 13:08:47.698282 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0.3 (linux amd64, built 2017/07/06 17:46:06, go1.8.3)
I171007 13:08:47.698282 1 util/log/clog.go:1011  [config] arguments: [/opt/cockroachdb/cockroach start --insecure --store /data/cockroachdb --advertise-host 10.197.65.1 --join 10.197.65.3 --join 10.197.65.4 --join 10.197.65.5 --join 10.197.65.2 --join 10.197.65.6]
```

Other query I've seen it on:
```sql
SELECT "__diesel_schema_migrations"."version" FROM "__diesel_schema_migrations"
```

Table schema:
```sql
CREATE TABLE __diesel_schema_migrations (
    version VARCHAR PRIMARY KEY NOT NULL
)
```

After a restart, doing such a query takes a long time (but I assume it eventually finishes because our infrastructure comes back up at some point).

Let me know if I can provide more information. I have 10 log files of about 10MB of different nodes having this panic.

**Comment by vivekmenezes** [comment]
The panic is happening at

```
nodeID := replInfo.NodeDesc.NodeID
```

**Comment by RaduBerinde** [comment]
This is #16127 which should be fixed in 1.1.

**Comment by RaduBerinde** [comment]
@jethrogb please try v1.1.0-rc.1 (or wait a bit for the final v1.1 release).

**Comment by jethrogb** [comment]
Will do. It's intermittent, so I guess this might take a while. If I notice the panics again I will let you know.
