### ISSUE TITLE
stability: crash on startup.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#19559]
`cyan` (continuous deployment) was just upgraded from 15b18a4 to 0224ad4.
Two nodes crashed on startup: `cockroach@cockroach-cyan-0002.crdb.io` and `cockroach@cockroach-cyan-0003.crdb.io`.
There are 6 merges between those two PRs, but all 6 failed to build so were never pushed.

```
I171026 14:02:38.790478 21 storage/engine/rocksdb.go:411  opening rocksdb instance at "/mnt/data1/cockroach-temp158446832"
W171026 14:02:38.849368 21 gossip/gossip.go:1277  [n?] no incoming or outgoing connections
I171026 14:02:38.849467 21 storage/engine/rocksdb.go:411  opening rocksdb instance at "/mnt/data1"
I171026 14:02:38.904256 51 gossip/client.go:129  [n?] started gossip client to 192.168.1.4:26257
I171026 14:02:40.951483 21 server/config.go:512  [n?] 1 storage engine initialized
I171026 14:02:40.951536 21 server/config.go:515  [n?] RocksDB cache size: 3.4 GiB
I171026 14:02:40.951555 21 server/config.go:515  [n?] store 0: RocksDB, max size 0 B, max open file limit 60536
F171026 14:02:41.398505 600 util/log/log.go:39  unexpected panic: runtime error: invalid memory address or nil pointer dereference
goroutine 600 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x344bb01, 0x14f123a994c97fc2, 0x2c40c78, 0xf)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:833 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x344bae0, 0xc400000004, 0x2c40c78, 0xf, 0x27, 0xc4208c1860, 0x52)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:738 +0x5fc
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2f54d40, 0xc42001c018, 0x4, 0x2, 0x1f6c2a2, 0x14, 0xc420da58d8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:153 +0x2fc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2f54d40, 0xc42001c018, 0x1, 0x4, 0x1f6c2a2, 0x14, 0xc420da58d8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:56 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2f54d40, 0xc42001c018, 0x1f6c2a2, 0x14, 0xc420da58d8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:150 +0x7e
github.com/cockroachdb/cockroach/pkg/util/log.FatalOnPanic()
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:39 +0xb1
panic(0x1d2d840, 0x2f0b5e0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/util/metric.(*Registry).getLabels(0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/metric/registry.go:67 +0x41
github.com/cockroachdb/cockroach/pkg/util/metric.(*PrometheusExporter).ScrapeRegistry(0xc42009e988, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/metric/prometheus_exporter.go:70 +0x32
github.com/cockroachdb/cockroach/pkg/server/status.(*MetricsRecorder).scrapePrometheusLocked(0xc42009e960)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/status/recorder.go:217 +0x5f
github.com/cockroachdb/cockroach/pkg/server/status.(*MetricsRecorder).PrintAsText(0xc42009e960, 0x7fad28e71e40, 0xc4201cc180, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/status/recorder.go:227 +0x80
github.com/cockroachdb/cockroach/pkg/server.(*statusServer).handleVars(0xc42016cc60, 0x2f4a800, 0xc4201cc180, 0xc420bf1300)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:879 +0xd0
github.com/cockroachdb/cockroach/pkg/server.(*statusServer).(github.com/cockroachdb/cockroach/pkg/server.handleVars)-fm(0x2f4a800, 0xc4201cc180, 0xc420bf1300)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1028 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4202a2580, 0x2f4a800, 0xc4201cc180, 0xc420bf1300)
        /usr/local/go/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420598e40, 0x2f4a800, 0xc4201cc180, 0xc420bf1300)
        /usr/local/go/src/net/http/server.go:2254 +0x130
github.com/cockroachdb/cockroach/pkg/server.(*Server).ServeHTTP(0xc420450f00, 0x2f535c0, 0xc420f1f880, 0xc420bf1300)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1389 +0x11d
net/http.serverHandler.ServeHTTP(0xc4205d3040, 0x2f535c0, 0xc420f1f880, 0xc420bf1300)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420dadea0, 0x2f54d00, 0xc4207291c0)
        /usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x288
```

**Comment by mberhault** [comment]
This seems to happen when `/_status/vars` is being scraped too soon after node startup.
I can reproduce this by running: `while /bin/true; do curl -O /dev/null http://localhost:8080/_status/vars; done`

in a terminal and `cockroach start --inscure` in another.

**Comment by mberhault** [comment]
This is related to #19493. The metrics handler really wants stores to be initialized before returning metrics, but we should definitely not crash here.

**Comment by mberhault** [comment]
Restart crashed `cyan` nodes.

**Comment by tschottdorf** [comment]
I'll whip up a PR.
