### ISSUE TITLE
sqlmigrations: fatal error on CTRL+C during startup

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19579]
Run `rm -rf cockroach-data/; ./cockroach start --insecure --logtostderr` a few times, CTRL+C within the first hundred milliseconds to a second

```
F171026 20:29:57.862364 11 server/server.go:1169  [n1] failed to persist record of completing migration "populate initial version cluster setting table entry": node unavailable; try another peer
goroutine 11 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x6c8c201, 0x14f138cbbdf616d7, 0x666ceca, 0x10)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:833 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x6c8c2c0, 0xc400000004, 0x666ceca, 0x10, 0x491, 0xc4200a4990, 0x90)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:738 +0x5fc
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x6766860, 0xc4206d5710, 0x4, 0x2, 0x0, 0x0, 0xc420f95330, 0x1, 0x1)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:153 +0x2fc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x6766860, 0xc4206d5710, 0x1, 0x4, 0x0, 0x0, 0xc420f95330, 0x1, 0x1)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:56 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x6766860, 0xc4206d5710, 0xc420f95330, 0x1, 0x1)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:159 +0x76
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start(0xc4201fcf00, 0x6766860, 0xc4206d5710, 0x0, 0x0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1169 +0x3243
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1.2(0x6766860, 0xc42074efc0, 0xc4207ca028, 0xc4207ac5a0, 0xc42026e1a0, 0x27d950ae, 0xed1843cc5, 0x0, 0x0, 0x0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:574 +0x1b6
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1(0xc4207ca028, 0x6766860, 0xc42074efc0, 0x6775f00, 0xc42078ac30, 0xc4207ac5a0, 0xc42026e1a0, 0x27d950ae, 0xed1843cc5, 0x0, ...)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:642 +0x11c
created by github.com/cockroachdb/cockroach/pkg/cli.runStart
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:541 +0x467

goroutine 1 [select]:
github.com/cockroachdb/cockroach/pkg/cli.runStart(0x6c701e0, 0xc4202af460, 0x0, 0x2, 0x0, 0x0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:722 +0xa76
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x6c701e0, 0xc4202af460, 0x0, 0x2, 0xc4206b3ca0, 0x51a5830)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:35 +0x57
github.com/cockroachdb/cockroach/pkg/cli.MaybeShoutError.func1(0x6c701e0, 0xc4202af460, 0x0, 0x2, 0x0, 0x0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:66 +0x51
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x6c701e0, 0xc4202af420, 0x2, 0x2, 0x6c701e0, 0xc4202af420)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x6c72820, 0x402e7b9, 0xc420260080, 0xc4206b3ef0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0x6c72820, 0xc4206b3ee8, 0x0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/cockroachdb/cockroach/pkg/cli.Run(0xc420010150, 0x3, 0x3, 0xc420014088, 0xc420028c00)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:159 +0x6d
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:52 +0x16c
main.main()
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/main.go:26 +0x20
```

**Comment by tschottdorf** [comment]
I'll fix this and post it with the repro acceptance test.
