### ISSUE TITLE
OOM error on start-up

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19746]
```temp dir:   /root/cockroach-data/cockroach-temp622938337
store[0]:   path=/root/cockroach-data
status:     restarted pre-existing node
clusterID:  55a5c72f-7a41-4755-b827-0a00f105c876
nodeID:     2
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1f83654, 0x16)
        /usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc465a30000, 0x20000000, 0xc42045c700, 0x34ba498)
        /usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x347b480, 0x20000000, 0x7f7bd5e5a9e8)
        /usr/local/go/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0x347b480, 0x10000, 0x0)
        /usr/local/go/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0x347b480, 0x10000, 0x34ba4a8, 0x0)
        /usr/local/go/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0x347b480, 0x10000, 0xffffffffffff0101, 0xc42045c780)
        /usr/local/go/src/runtime/mheap.go:666 +0x118
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0x7f7bd5e5aad0)
        /usr/local/go/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0x347b480, 0x10000, 0xc422010101, 0x7f7bd5e5ab38)
        /usr/local/go/src/runtime/mheap.go:732 +0xa1
runtime.largeAlloc(0x20000000, 0x7f7bd9be0101, 0x10000000000002a)
        /usr/local/go/src/runtime/malloc.go:827 +0x98
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:722 +0x46
runtime.systemstack(0xc420019300)
        /usr/local/go/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1125
goroutine 2808 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:298 fp=0xc42504a4c8 sp=0xc42504a4c0 pc=0x636370
runtime.mallocgc(0x20000000, 0x1c92d80, 0x1, 0xc455a10000)
        /usr/local/go/src/runtime/malloc.go:721 +0x7b8 fp=0xc42504a570 sp=0xc42504a4c8 pc=0x5ecdd8
runtime.makeslice(0x1c92d80, 0xff7d70d, 0x20000000, 0xc455a10000, 0x7ffdf0a, 0x10000000)
        /usr/local/go/src/runtime/slice.go:54 +0x77 fp=0xc42504a5a0 sp=0xc42504a570 pc=0x61f947
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDBBatchBuilder).grow(0xc4241e40f8, 0x2193cc)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/batch.go:131 +0x6b fp=0xc42504a600 sp=0xc42504a5a0 pc=0xf67feb
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDBBatchBuilder).ApplyRepr(0xc4241e40f8, 0xc43f046000, 0x2193d8, 0x21a000, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/batch.go:247 +0x67 fp=0xc42504a680 sp=0xc42504a600 pc=0xf689c7
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).ApplyBatchRepr(0xc4241e4000, 0xc43f046000, 0x2193d8, 0x21a000, 0x2f86f00, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1261 +0x5e fp=0xc42504a6c0 sp=0xc42504a680 pc=0xf8654e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applySnapshot(0xc4205ec380, 0x2f740e0, 0xc420628180, 0x9a4451a88fef287c, 0xd3dfa48e4dd2a3a0, 0xc42b7f0000, 0x263, 0x400, 0xc420557000, 0xed, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raftstorage.go:762 +0x6a1 fp=0xc42504aac0 sp=0xc42504a6c0 pc=0x10dd2d1
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4205ec380, 0x9a4451a88fef287c, 0xd3dfa48e4dd2a3a0, 0xc42b7f0000, 0x263, 0x400, 0xc420557000, 0xed, 0x100, 0xc42121efc0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3376 +0x2028 fp=0xc42504b300 sp=0xc42504aac0 pc=0x10a22e8
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest.func1(0x2f740e0, 0xc422225980, 0xc4205ec380, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3244 +0x8ba fp=0xc42504b9d0 sp=0xc42504b300 pc=0x112873a
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc42063ac00, 0x2f740e0, 0xc422225980, 0xc42121f000, 0xc4233f3a68, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2969 +0x135 fp=0xc42504ba38 sp=0xc42504b9d0 pc=0x1100255
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest(0xc42063ac00, 0x2f740e0, 0xc423fc6ae0, 0xc42121f000, 0x9a4451a88fef287c, 0xd3dfa48e4dd2a3a0, 0xc42b7f0000, 0x263, 0x400, 0xc420557000, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3035 +0xd3 fp=0xc42504bae8 sp=0xc42504ba38 pc=0x11009b3
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc42063ac00, 0xc42121efc0, 0x7f7bd8cb79c0, 0xc421d30e60, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2838 +0x686 fp=0xc42504bd00 sp=0xc42504bae8 pc=0x10fecb6
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x2f80420, 0xc421d30e60, 0xc4204b3950, 0x2f740e0, 0xc423fc69f0, 0x10, 0xd3dab5)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:386 +0x13a fp=0xc42504bf08 sp=0xc42504bd00 pc=0x11199ba
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x2f740e0, 0xc423fc69f0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:387 +0x5d fp=0xc42504bf68 sp=0xc42504bf08 pc=0x1119c3d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4206da1b0, 0x2f740e0, 0xc423fc69f0, 0xc42140c040, 0x32, 0x0, 0x0, 0xc423fc6a50)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:267 +0xe6 fp=0xc42504bfa0 sp=0xc42504bf68 pc=0xd3dad6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42504bfa8 sp=0xc42504bfa0 pc=0x638fa1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:262 +0x133```

**Comment by petermattis** [comment]
There seems to be some sort of range-of-death which causes an OOM whenever we try to apply the snapshot. Looks like range 1360, but I'm not sure about that. I turned on periodic memprof dumps but haven't caught anything so far.

**Comment by petermattis** [comment]
The reason I suspect range 1360 is that prior to two of the crashes I see:

`I171102 18:33:56.324400 22155 storage/replica_raftstorage.go:733  [n2,s2,r1360/?:{-}] applying preemptive snapshot at index 481 (id=83848ce4, encoded size=49998404, 189 rocksdb batches, 17 log entries)`

47MB in size spread across 189 batches is quite reasonable.

**Comment by petermattis** [comment]
@tschottdorf Can I loop you in here for additional triaging?

**Comment by tschottdorf** [comment]
Sure, but it'll be next week since I'm working on the release.

**Comment by petermattis** [comment]
Hmm, well that probably won't be satisfying for this user. Let me see if anyone else is available.

**Comment by dianasaur323** [comment]
well, I'm OOO tomorrow, so I doubt I'll do anything?

**Comment by nvanbenschoten** [comment]
@dianasaur323 could you walk me through the steps you took to arrive here? Was this a fresh cluster or had it been running for some time? I assume the latter, in which case I'm curious about the first time that you saw the crash. Was it during a rolling upgrade?

**Comment by dianasaur323** [comment]
@nvanbenschoten This was an existing cluster that gets a rolling upgrade at 6AM UTC every day to the most recent master. It is distributed across 4 nodes (2 in NYC, 1 in AMS, 1 in SFO). Each node has a local instance of TPC-C running, for different periods of time, so that load is hitting different regions at different times. We realized that we weren't observing the lease rebalancing we should have been seeing, because we didn't have localities set. That is when I went in, and made 3 localities (NYC, AMS, SFO). It was after this change, and when load starting running again on NYC that this started to occur.

**Comment by nvanbenschoten** [comment]
I'm able to reproduce this pretty easily by stopping one node for a little while before bringing it back to life and then letting it try to catch up. The last few crashes I've seen look like what @petermattis was observing, except they're related to range 349:

```
I171106 22:26:35.203081 143633 storage/replica_raftstorage.go:733  [n2,s2,r349/?:{-}] applying preemptive snapshot at index 32715 (id=4a5dd338, encoded size=111131297, 49 rocksdb batches, 2 log entries)
```

Notice that the encoded size of the snapshot is `111MB`, about twice as large as the largest snapshots we would like to be creating.

After a few tries, I was finally able to capture a memory profile close enough to a crash to show the `SnapshotRequest`

```
(pprof) top
Showing nodes accounting for 232.90MB, 91.21% of 255.33MB total
Dropped 127 nodes (cum <= 1.28MB)
Showing top 10 nodes out of 173
      flat  flat%   sum%        cum   cum%
  152.95MB 59.90% 59.90%   158.63MB 62.13%  github.com/cockroachdb/cockroach/pkg/storage.(*SnapshotRequest).Unmarshal /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go
   22.33MB  8.74% 68.65%    22.33MB  8.74%  github.com/cockroachdb/cockroach/pkg/roachpb.(*RangeDescriptor).Unmarshal /go/src/github.com/cockroachdb/cockroach/pkg/roachpb/metadata.pb.go
   20.32MB  7.96% 76.60%    22.82MB  8.94%  github.com/cockroachdb/cockroach/pkg/storage.makeTSCacheRequest /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go
    8.20MB  3.21% 79.81%     8.20MB  3.21%  github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raftpb.(*Entry).Unmarshal /go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raftpb/raft.pb.go
    6.73MB  2.64% 82.45%     6.73MB  2.64%  github.com/cockroachdb/cockroach/pkg/util/encoding.EncodeBytesAscending /go/src/github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go
    6.65MB  2.61% 85.06%     6.65MB  2.61%  github.com/cockroachdb/cockroach/pkg/storage.encodeRaftCommand /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raftstorage.go
```

Each OOM error is being triggered by the `oom_killer` when cockroach's Anon RSS size of about 1.8 GB (out of the machine's 2 GB). While the memory profile only shows about 20% of this RSS, I suspect it's missing a lot, probably beneath the CGo border.

Interestingly, range 349 is also part of table 60, like range 1360. The start key of the range looks like a SQL query (`/Table/60/1/"SELECT _._, _._, _._, _._, _._ FROM _ AS _ WHERE (_._, _._, _._) IN ((_, _, _), ...`) and is about 2MB in size. I don't think this is a coincidence. I doubt we're doing a good job handling snapshots for ranges with very large keys, as https://github.com/cockroachdb/cockroach/issues/19751 suggests. There could be a number of reasons for this, including that we're sending uncompressed `BatchReprs` that don't benefit from prefix key encoding.

We can try to handle large keys better in a few ways:
- increase the amount we stream when sending snapshots so an entire snapshot is never held in memory.
- limit the size of keys allowed in SQL tables by enforcing limits on datum lengths used in indices. For instance, we could say that any `STRING` column used a primary key (or unique secondary index) has a maximum length of something like `2^20`. So `CREATE TABLE t (a STRING PRIMARY KEY)` would transparently become `CREATE TABLE t (a STRING(1048576) PRIMARY KEY)`. This would leverage SQL to prevent user error/misuse.
- limit the size of keys selected as range boundaries by adjusting the logic in `IsValidSplitKey`. This would have to be handled with care, as it could make arbitrary numbers of keys unsplittable from each other, which would cause ranges to grow without bound.

At it's extreme though, I don't think we can ever fully prevent this from being an issue. Similar to the issue of rows that are too large, I think we'll just need to document that the values stored in indices have a practical limit.

**Comment by bdarnell** [comment]
Most databases have limits on the size of columns that can be used as keys (for example, mysql doesn't allow indexing columns larger than 768 bytes IIRC), so there is ample precedent for enforcing some limit there. The sub-kilobyte limits of other DBs can be annoying but I think a more reasonable limit would be fine (I'd suggest something like 64KB. Maybe a smaller limit for primary keys than for secondaries since those get duplicated more). 

> At it's extreme though, I don't think we can ever fully prevent this from being an issue. Similar to the issue of rows that are too large, I think we'll just need to document that the values stored in indices have a practical limit.

Whenever the consequences of oversized values are this severe, we should work to turn a documented "practical limit" into an enforced hard limit so users will get errors instead of wedging their database.

**Comment by tschottdorf** [comment]
Just curious, would we also be limiting the total key size somehow? For example, what about

`CREATE TABLE foo (a STRING(1mb), b STRING(1mb), ..., z STRING(1mb)) PRIMARY KEY(a, b, c, ..., z)`?

**Comment by bdarnell** [comment]
Yeah, the limit would need to be on the worst-case total size of all columns that make up the key, instead of individual columns.

**Comment by dianasaur323** [comment]
@nvanbenschoten after rebooting everything, I'm still seeing the NYC2 node die. Interesting thing is that it died before I added in the data that I think might have huge primary keys, so I have a suspicion that something else is wrong.

**Comment by nvanbenschoten** [comment]
@dianasaur323 what do you mean by "it died before I added in the data that I think might have huge primary keys"? An empty cluster is still crashing with an OOM?

**Comment by dianasaur323** [comment]
@nvanbenschoten nope, my assumption was the restored registration data might have had the primary keys that we thought were too big. However, I was just running simple tpcc on that cluster when it crashed. The error messages on NYC2 also looked different from before.

**Comment by nvanbenschoten** [comment]
@dianasaur323 it looks like NYC1 and NYC2 crashed from a consistency check failure. This looks like the same issue we saw yesterday on Cyan (https://sentry.io/cockroach-labs/cockroachdb/issues/401514091/). Just like we saw on Cyan, all `debug check-store` calls succeed except for one (NYC1 in this case), which gets stuck. I wasn't able to track down whether there was any resolution on what caused the check failure, but @danhhz or @tschottdorf might know.

Are you sure the cluster was wiped before this though? Regardless of the consistency issue, I'm still seeing those huge range start keys. Let's chat in person whenever you're free.

**Comment by tschottdorf** [comment]
@mberhault just mentioned that some nightlies also failed with the same error, so I'm inclined to believe that there's still a systematic problem with the last RocksDB update.

**Comment by dianasaur323** [comment]
@nvanbenschoten so I mis-followed your instructions and did a restore instead of a dump, so I think that's where the range is coming from. that being said, the cluster now has worse issues. I'll come find you when you get in later.

**Comment by nvanbenschoten** [comment]
The change to remove the key bounds from the ReplicaEvalResult proto should improve the situational when operating on extremely large keys. Still, I expect there to be a lot of issues with doing so.

The rest of this issue concentrates on enforcing a size limit on variable length data types that are used for SQL keys. This limit is already implicitly enforced by the new `TimestampCache`, which won't allow keys larger than 1MB by default, but it would be much better to push this limit up into the SQL domain itself. This won't be addressed in the 2.0 cycle, so I'm going to push this to 2.1.

**Comment by nvanbenschoten** [comment]
@knz unassigning myself from this as the work items aren't on the near-term roadmap and the remaining ones (namely mandatory SQL length qualifiers on indexed columns) fall in the SQL world.

**Comment by knz** [comment]
:+1:

**Comment by jordanlewis** [comment]
We still need something like this.

Though, I think the situation might have been improved recently thanks to @michae2's guardrail PR... thoughts?

**Comment by knz** [comment]
default max_row_size at 512MB seems a little excessive, since that's also the configured max range size. What prompted this choice?  Naively, a row size of 10MB already seems excessive to me. But I'm not sure.

Then, separately, yes a per-key (for STRING/BYTES/ARRAY columns) limit is also desirable.  It feels to me that 1-10MB for this would be _far_ beyond what folk find reasonable already, yet lower than what we effectively support, so maybe a good choice.

@bdarnell may have additional ideas.

**Comment by michae2** [comment]
> default max_row_size at 512MB seems a little excessive, since that's also the configured max range size. What prompted this choice? Naively, a row size of 10MB already seems excessive to me. But I'm not sure.

Because this was a new limitation in 21.1, I wanted something excessively high at first to avoid breaking any existing workloads. We also added `sql.guardrails.max_row_size_log` at the same time, which defaults to 64 MiB. Maybe now that we've had these guardrails for a couple releases we could "boil the frog" and lower their defaults.

**Comment by bdarnell** [comment]
Yes, we should have a separate size limit for keys. If not for backwards compatibility concerns I'd use something like 64k (as I said in https://github.com/cockroachdb/cockroach/issues/19746#issuecomment-342547526). We might be able to get away with something like 1MB if we're imposing the limit now (as long as it behaves "reasonably" for existing data that exceeds the limit and doesn't for example cause existing rows to become undeletable). How big were the problematic keys in the recent postmortem? I know in the past 4MB keys were enough to cause severe problems; I'm not sure if that's still current.

As for the row size limit, remember that we have a default limit of 16MB on pgwire messages, so it's not straightforward to generate rows bigger than 16MB (you can't simply INSERT them as values directly), so we could probably get away with lowering that limit significantly.

**Comment by michae2** [comment]
One way to gain confidence about key and row size limits would be to add telemetry for the distribution of key and row sizes.

**Comment by rytaft** [comment]
We need a priority label for this issue. Seems like a P-3 given that this has been around for years and hasn't been prioritized. Thoughts, @michae2?

**Comment by michae2** [comment]
See https://github.com/cockroachdb/pebble/issues/1741 about the kinds of problems large keys can have in Pebble.
