### ISSUE TITLE
sqlccl: possible memory blowup in IMPORT CSV

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#19968]
In https://forum.cockroachlabs.com/t/one-node-is-dead-agter-import-csv-into-cockroachdb-cluster, a user imported around 70GB of csv data into a new 3 node cluster. The nodes were run with `--cache=25% --max-sql-memory=25%`. The data was tpcc and generated by `benchmarksql`. No other load was on the cluster. During this process, one of the nodes died with

```
I171107 18:42:13.660024 409 server/status/runtime.go:223  [n3] runtime stats: 55 GiB RSS, 634 goroutines, 131 MiB/94 MiB/379 MiB GO alloc      /idle/total, 50 GiB/55 GiB CGO alloc/total, 434.64cgo/sec, 0.15/0.06 %(u/s)time, 0.00 %gc (1x)
10094 terminate called after throwing an instance of 'std::bad_alloc'
10095   what():  std::bad_alloc
10096 SIGABRT: abort
10097 PC=0x7fdc4b59c5d7 m=15 sigcode=18446744073709551610
10098 signal arrived during cgo execution
10099             
10100 goroutine 221579 [syscall, locked to thread]:
10101 non-Go function
10102     pc=0x7fdc4b59c5d7
10103 non-Go function
10104     pc=0x7fdc4b59dcc7
10105 non-Go function
10106     pc=0x19781d2
10107 non-Go function
10108     pc=0x18ecdb0
10109 non-Go function
10110     pc=0x18ecdd3
10111 non-Go function
10112     pc=0x18e9dc6
10113 non-Go function
10114     pc=0x18ea2ea
10115 non-Go function
10116     pc=0x18e91ba
10117 non-Go function
10118     pc=0x17ee177
10119 runtime.cgocall(0x1666810, 0xc430ca4b28, 0x1d431a7)
10120     /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc430ca4ae8 sp=0xc430ca4aa8
10121 github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBIterNext(0x7fdbe7a36758, 0x7fdbe7a36700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,       0x0, ...)
10122     github.com/cockroachdb/cockroach/pkg/storage/engine/_obj/_cgo_gotypes.go:453 +0x69 fp=0xc430ca4b28 sp=0xc430ca4ae8
10123 github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).Next.func1(0x7fdbe7a36758, 0x275bf3f5199dbe00, 0x0, 0x0, 0x0, 0x0,       0x0, 0x0, 0x0, 0x0, ...)
10124     /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1663 +0xae fp=0xc430ca4bd8 sp=0xc430ca4b28
10125 github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).Next(0xc43c71e000)                                                
10126     /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1663 +0x5a fp=0xc430ca4c88 sp=0xc430ca4bd8
10127 github.com/cockroachdb/cockroach/pkg/storage.(*ReplicaDataIterator).Next(0xc43041c1e0)
 /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_data_iter.go:107 +0x34 fp=0xc430ca4ca0 sp=0xc430ca4c88
10129 github.com/cockroachdb/cockroach/pkg/storage.(*Replica).sha512(0xc421ebdc00, 0x162, 0xc42029e230, 0xa, 0x10, 0xc4212fbda0, 0x9, 0x10, 0xc      4222619b0, 0x3, ...)
10130     /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:2416 +0x3a7 fp=0xc430ca4e70 sp=0xc430ca4ca0
10131 github.com/cockroachdb/cockroach/pkg/storage.(*Replica).computeChecksumPostApply.func1(0x7fdc4c18f000, 0xc4224219e0)
10132     /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:424 +0x101 fp=0xc430ca4f68 sp=0xc430ca4e70
10133 github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4208a8bd0, 0x7fdc4c18f000, 0xc4224219e0, 0xc422421ce0, 0x      2b, 0x2adb4a0, 0xc42023d5c0, 0xc42fe4e000)
10134     /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:269 +0xe6 fp=0xc430ca4fa0 sp=0xc430ca4f68
10135 runtime.goexit()
10136     /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc430ca4fa8 sp=0xc430ca4fa0
10137 created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
10138     /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:270 +0x133
```

The user has been unblocked by using the `-load flag` to our tpcc load generator, but we should probably see if this repros.

**Comment by louishust** [comment]
I got the same error, when loading big data using sysbench with a 3 node crdb cluster.

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
SIGABRT: abort
PC=0x7f8961bb35d7 m=36 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 7221714 [syscall, locked to thread]:
non-Go function
        pc=0x7f8961bb35d7
non-Go function
        pc=0x7f8961bb4cc7
non-Go function
        pc=0x1ab0e52
non-Go function
        pc=0x1a25a30
non-Go function
        pc=0x1a25a53
non-Go function
        pc=0x1a22a46
non-Go function
        pc=0x1a22f6a
non-Go function
        pc=0x1a84151
non-Go function
        pc=0x1a83cf6
non-Go function
        pc=0x1a7f0e7
non-Go function
        pc=0x1a7f7e7
non-Go function
        pc=0x1a82374
non-Go function
        pc=0x18dc5d0
runtime.cgocall(0x179ef10, 0xc4a243bcf0, 0x7f886fbf9070)
        /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc4a243bca0 sp=0xc4a243bc60
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBApplyBatchRepr(0x7f886fbf9070, 0xc4c7c7a000, 0x2289441, 0x0, 0x0, 0x0)
        github.com/cockroachdb/cockroach/pkg/storage/engine/_obj/_cgo_gotypes.go:202 +0x57 fp=0xc4a243bcf0 sp=0xc4a243bca0
github.com/cockroachdb/cockroach/pkg/storage/engine.dbApplyBatchRepr.func1(0x7f886fbf9070, 0xc4c7c7a000, 0x2289441, 0x1500, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1905 +0x89 fp=0xc4a243bd40 sp=0xc4a243bcf0
github.com/cockroachdb/cockroach/pkg/storage/engine.dbApplyBatchRepr(0x7f886fbf9070, 0xc4c7c7a000, 0x2289441, 0x4000000, 0xed19e5200, 0xc43470c253, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1905 +0x70 fp=0xc4a243bdb0 sp=0xc4a243bd40
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).flushMutations(0xc4cf51bb00)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1534 +0xc5 fp=0xc4a243bdf8 sp=0xc4a243bdb0
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc4cf51bb00, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1465 +0x477 fp=0xc4a243bf38 sp=0xc4a243bdf8
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc4cf51bb00, 0xc420744001, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1413 +0x815 fp=0xc4a243c040 sp=0xc4a243bf38
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applySnapshot(0xc4d9598c00, 0x7f8961b0ccb0, 0xc4725f78f0, 0x274b54a83f16d800, 0x87b632fb77e67980, 0xc496a83000, 0x8b, 0x100, 0xc4b31ef300, 0x5, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raftstorage.go:818 +0xaa1 fp=0xc4a243c568 sp=0xc4a243c040
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4d9598c00, 0x274b54a83f16d800, 0x87b632fb77e67980, 0xc496a83000, 0x8b, 0x100, 0xc4b31ef300, 0x5, 0x5, 0xc4e3d7cfc0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3267 +0x24dd fp=0xc4a243d388 sp=0xc4a243c568
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc4206a1400, 0x7f8961b0ccb0, 0xc430963d70, 0xc4e3d7d078, 0x274b54a83f16d800, 0x87b632fb77e67980, 0xc496a83000, 0x8b, 0x100, 0xc4b31ef300, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3183 +0xca2 fp=0xc4a243db30 sp=0xc4a243d388
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc4206a1400, 0xc4e3d7cfc0, 0x7f894079f2a0, 0xc45de65670, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2819 +0x6af fp=0xc4a243dd00 sp=0xc4a243db30
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x2d7b5a0, 0xc45de65670, 0xc42074c0f0, 0x7f8961b0ccb0, 0xc4401b0960, 0x10, 0xd2b495)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:386 +0x13d fp=0xc4a243df08 sp=0xc4a243dd00
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x7f8961b0ccb0, 0xc4401b0960)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:387 +0x5d fp=0xc4a243df68 sp=0xc4a243df08
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc420011050, 0x7f8961b0ccb0, 0xc4401b0960, 0xc47af71bc0, 0x32, 0x0, 0x0, 0xc4401b09f0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:267 +0xe6 fp=0xc4a243dfa0 sp=0xc4a243df68
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4a243dfa8 sp=0xc4a243dfa0
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:268 +0x133
```

**Comment by dianasaur323** [comment]
@mjibson I triaged this in the bulkio project alongside this other import csv memory issue https://github.com/cockroachdb/cockroach/issues/19635

**Comment by mjibson** [comment]
Thanks for the reports. I'll look into this soon.

**Comment by mjibson** [comment]
@louishust If you still have the data or cluster available, can you paste the output of `show jobs` here? I'm trying to figure out where in the process the failure occurred.

**Comment by louishust** [comment]
@mjibson  the cluster have been cleaned up, you can use sysbench to load data to repeat the bug

**Comment by mjibson** [comment]
I attempted to reproduce this using `cockroach load csv` but failed. During the ~40m it took to complete stage 1 the heap size was generally below 300MB. Stage 2 it drops to < 30MB. Will try again with IMPORT. But it's clear that main csv code doesn't appear to have a memory blowup or leak. It is possible the configured rocksdb used by IMPORT is causing an issue, like maybe not cleaning up after itself correctly.

**Comment by mjibson** [comment]
I think this has been fixed.
