### ISSUE TITLE
core: starting a 1.0.6 binary after a (single node) cluster has been initialized at 1.1.2 panics

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#20188]
I started a node with a 1.1.2 binary. Don't know if it matters, but I then ran
```
root@:26100/> create table t.t (x int primary key);
root@:26100/> alter table t.t split at values(1);
```
I then killed the node and restarted with a 1.0.6 binary and I got the panic below.
I guess the theory is that the cluster version check is not enforced in this case for some reason.

```
^[[A[andrei:~/work2/src/github.com/cockroachdb/cockroach] park+ 1 ± ~/crdb1.0 start --insecure --logtostderr --port=26100 --http-port=8000
W171120 18:28:24.403457 1 cli/start.go:587  RUNNING IN INSECURE MODE!

- Your cluster is open for any client that can access <all your IP addresses>.
- Any user, even root, can log in without providing a password.
- Any user, connecting as root, can read or write any data in your cluster.
- There is no network encryption nor authentication, and thus no confidentiality.

Check out how to secure your cluster: https://www.cockroachlabs.com/docs/secure-a-cluster.html
I171120 18:28:24.403902 1 cli/start.go:593  CockroachDB CCL v1.0.6 (darwin amd64, built 2017/09/14 15:13:51, go1.8.3)
I171120 18:28:24.506879 1 server/config.go:375  system total memory: 16 GiB
I171120 18:28:24.507126 1 server/config.go:377  server configuration:
max offset                   500ms
cache size                   4.0 GiB
SQL memory pool size         4.0 GiB
scan interval                10m0s
scan max idle time           200ms
consistency check interval   24h0m0s
metrics sample interval      10s
time until store dead        5m0s
send next timeout            10m0s
event log enabled            true
linearizable                 false
I171120 18:28:24.507360 15 cli/start.go:340  starting cockroach node
W171120 18:28:24.510218 15 server/config_unix.go:106  soft open file descriptor limit 10240 is under the recommended limit 15000; this may decrease performance
please see https://www.cockroachlabs.com/docs/recommended-production-settings.html for more details
I171120 18:28:24.510423 15 storage/engine/rocksdb.go:380  opening rocksdb instance at "/Users/andrei/work2/src/github.com/cockroachdb/cockroach/cockroach-data"
I171120 18:28:24.546093 15 server/config.go:475  [n?] 1 storage engine initialized
I171120 18:28:24.546128 15 server/config.go:477  [n?] RocksDB cache size: 4.0 GiB
I171120 18:28:24.546143 15 server/config.go:477  [n?] store 0: RocksDB, max size 0 B, max open file limit 9984
I171120 18:28:24.546646 15 server/server.go:672  [n?] sleeping for 463.071853ms to guarantee HLC monotonicity
I171120 18:28:25.015366 15 storage/store.go:1253  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
W171120 18:28:25.015484 118 storage/store.go:1340  [n1,s1,r7/1:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r7: replica (n1,s1):1 not lease holder; lease holder unknown
I171120 18:28:25.015524 15 server/node.go:467  [n1] initialized store [n1,s1]: {Capacity:249678528512 Available:164864999424 RangeCount:22 LeaseCount:0}
I171120 18:28:25.015567 15 server/node.go:351  [n1] node ID 1 initialized
E171120 18:28:25.015686 121 vendor/github.com/coreos/etcd/raft/raft.go:1196  [n1,s1,r1/1:/{Min-System/}] 1 state.commit 81 is out of range [23, 23]
I171120 18:28:25.015705 15 gossip/gossip.go:297  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"Andreis-MBP:26100" > attrs:<> locality:<>
E171120 18:28:25.015714 121 util/log/crash_reporting.go:88  a panic has occurred!
E171120 18:28:25.015999 130 vendor/github.com/coreos/etcd/raft/raft.go:1196  [n1,s1,r3/1:/System/NodeLiveness{-Max}] 1 state.commit 45 is out of range [10, 10]
E171120 18:28:25.016029 130 util/log/crash_reporting.go:88  a panic has occurred!
panic: 1 state.commit 81 is out of range [23, 23] [recovered]
	panic: 1 state.commit 81 is out of range [23, 23]

goroutine 121 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420712000, 0x6e76918, 0xc420016498)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xb1
panic(0x52b1080, 0xc4201c4e50)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/storage.(*raftLogger).Panicf(0xc4201c4db0, 0x552f4ee, 0x2b, 0xc42034ae40, 0x4, 0x4)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.go:117 +0x183
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).loadState(0xc42055a0f0, 0x7, 0x1, 0x51, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1196 +0x1c7
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.newRaft(0xc420ab75d0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:303 +0xbc6
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.NewRawNode(0xc420ab75d0, 0x0, 0x0, 0x0, 0xc420275a40, 0xc42018b090, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:79 +0x71
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc42035a600, 0x55c8000, 0x55c7bd0, 0x63c8490, 0xc420494400)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:451 +0x337
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).maybeInitializeRaftGroup(0xc42035a600, 0x6eaad80, 0xc420180d80)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1399 +0x16f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc42035a600, 0x6eaad80, 0xc420180d80, 0x14f8ef0ae2bdcd77, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1425 +0x17d
github.com/cockroachdb/cockroach/pkg/storage.(*pendingLeaseRequest).requestLeaseAsync.func1(0x6eaad80, 0xc420275a40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go:212 +0x599
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc420712000, 0x6e76918, 0xc420016498, 0x54f208f, 0x3, 0x1, 0x0, 0x0, 0xc42070f8c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:294 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:295 +0x14a
panic: 1 state.commit 45 is out of range [10, 10] [recovered]
	panic: 1 state.commit 45 is out of range [10, 10]

goroutine 130 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420712000, 0x6e76918, 0xc420016498)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xb1
panic(0x52b1080, 0xc4201fa000)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/storage.(*raftLogger).Panicf(0xc4201ea000, 0x552f4ee, 0x2b, 0xc420257a00, 0x4, 0x4)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.go:117 +0x183
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).loadState(0xc420648000, 0x6, 0x1, 0x2d, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1196 +0x1c7
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.newRaft(0xc420ab95d0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:303 +0xbc6
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.NewRawNode(0xc420ab95d0, 0x0, 0x0, 0x0, 0xc420250b40, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:79 +0x71
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc42035ac00, 0x55c8000, 0x55c7bd0, 0x63c8490, 0xc420462000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:451 +0x337
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).maybeInitializeRaftGroup(0xc42035ac00, 0x6eaad80, 0xc4204bb140)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1399 +0x16f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc42035ac00, 0x6eaad80, 0xc4204bb140, 0x14f8ef0ae2bc2334, 0x0, 0x0, 0x0, 0x3, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1425 +0x17d
github.com/cockroachdb/cockroach/pkg/storage.(*pendingLeaseRequest).requestLeaseAsync.func1(0x6eaad80, 0xc420250b40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go:212 +0x599
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc420712000, 0x6e76918, 0xc420016498, 0x54f208f, 0x3, 0x1, 0x0, 0x0, 0xc4200b1130)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:294 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:295 +0x14a
```

**Comment by andreimatei** [comment]
Upon talking to Tobi, I guess there's nothing unexpected here. 1.0 nodes don't have the nicer handling of illegal downgrades.
