### ISSUE TITLE
core: crash on insert (after nodes from different cluster attempt to join)

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#20207]
On a single-node cluster at SHA 98fad6feeb9d223f5d0e342fcbcafba80709864f:

SQL Shell:

```
root@:26257/test> create table a (a int, primary key (a, a));
CREATE TABLE

Time: 4.654443ms

root@:26257/test> insert into a values (2);
driver: bad connection
```

Server stderr:

```
vilterp@Petes-MBP:cockroach$ [master] cockroach start --insecure
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v1.2/secure-a-cluster.html
*
CockroachDB node starting at 2017-11-21 16:36:41.260580943 +0000 UTC (took 0.7s)
build:               CCL v1.2-alpha.20171113-548-g98fad6fee @ 2017/11/21 16:35:42 (go1.9)
admin:               http://Petes-MBP:8080
sql:                 postgresql://root@Petes-MBP:26257?application_name=cockroach&sslmode=disable
logs:                /Users/vilterp/go/src/github.com/cockroachdb/cockroach/cockroach-data/logs
temp dir:            /Users/vilterp/go/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp936033835
external I/O path:   /Users/vilterp/go/src/github.com/cockroachdb/cockroach/cockroach-data/extern
store[0]:            path=/Users/vilterp/go/src/github.com/cockroachdb/cockroach/cockroach-data
status:              restarted pre-existing node
clusterID:           10b146f6-1f3c-4b99-9d42-ec6fbe18f834
nodeID:              1
*
* ERROR: [n1,s1,r51/1:/{Table/56-Max}] Reported as error 1e105f9e6a6443a39d0c24eeee457632
*
F171121 17:46:19.892748 210 storage/store.go:1823  [n1,s1,r51/1:/{Table/56-Max}] raft group deleted
goroutine 210 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x6e5b300, 0x14f92af49364b0d5, 0x6840994, 0x10)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:831 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x6e5b3c0, 0xc400000004, 0x6840994, 0x10, 0x71f, 0xc4215b9da0, 0x30)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:734 +0x620
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x694fca0, 0xc4222d0150, 0x4, 0x2, 0x0, 0x0, 0xc420e81e20, 0x1, 0x1)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:153 +0x308
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x694fca0, 0xc4222d0150, 0x1, 0x4, 0x0, 0x0, 0xc420e81e20, 0x1, 0x1)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:56 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x694fca0, 0xc4222d0150, 0xc420e81e20, 0x1, 0x1)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:159 +0x76
github.com/cockroachdb/cockroach/pkg/storage.splitPostApply(0x694fca0, 0xc4222d0150, 0x0, 0x14f92af492f4772d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1823 +0x204
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleReplicatedEvalResult(0xc4207b4900, 0x694fca0, 0xc4222d0150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:450 +0x187e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleEvalResultRaftMuLocked(0xc4207b4900, 0x694fca0, 0xc4222d0150, 0xc4217a0dc0, 0xc420311b50, 0x1, 0x8, 0xc420311b58, 0x2, 0x8, ...)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:740 +0xaa
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc4207b4900, 0x694fca0, 0xc4222d0150, 0xc420311ac8, 0x8, 0x6, 0xf, 0x100000001, 0x1, 0x0, ...)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4691 +0xa46
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4207b4900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3608 +0x13d4
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc4207b4900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3339 +0xf8
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4207a6800, 0x694fca0, 0xc4208383c0, 0x33)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3664 +0xda
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4208a6120, 0x694fca0, 0xc4208383c0)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:216 +0x259
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x694fca0, 0xc4208383c0)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202f4590, 0xc4208a6000, 0xc4202f4580)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad
```

Restarted server:

```
vilterp@Petes-MBP:cockroach$ [master] cockroach start --insecure
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v1.2/secure-a-cluster.html
*
CockroachDB node starting at 2017-11-21 17:47:11.373731154 +0000 UTC (took 4.4s)
build:               CCL v1.2-alpha.20171113-548-g98fad6fee @ 2017/11/21 16:35:42 (go1.9)
admin:               http://Petes-MBP:8080
sql:                 postgresql://root@Petes-MBP:26257?application_name=cockroach&sslmode=disable
logs:                /Users/vilterp/go/src/github.com/cockroachdb/cockroach/cockroach-data/logs
temp dir:            /Users/vilterp/go/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp233454172
external I/O path:   /Users/vilterp/go/src/github.com/cockroachdb/cockroach/cockroach-data/extern
store[0]:            path=/Users/vilterp/go/src/github.com/cockroachdb/cockroach/cockroach-data
status:              restarted pre-existing node
clusterID:           10b146f6-1f3c-4b99-9d42-ec6fbe18f834
nodeID:              1
*
* ERROR: [replicate,n1,s1,r52/1:/{Table/57-Max}] a panic has occurred!
*
*
* ERROR: [replicate,n1,s1,r52/1:/{Table/57-Max}] Reported as error 349397ecc0304467b7a9f2e73467e26c
*
1 state.commit 0 is out of range [10, 10]

goroutine 248 [running]:
runtime/debug.Stack(0x694fc60, 0xc4208ea540, 0xc42002ac00)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x694fc60, 0xc4208ea540, 0xc42002ac00, 0x58b6e20, 0xc420367c80, 0x1)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:135 +0x155
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4208205a0, 0x694fc60, 0xc4208ea540)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:179 +0xfb
panic(0x58b6e20, 0xc420367c80)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/storage.(*raftLogger).Panicf(0xc420367930, 0x5bdc0e3, 0x2b, 0xc420e485c0, 0x4, 0x4)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.go:115 +0x1dc
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).loadState(0xc4207643c0, 0x28, 0x7, 0x0, 0x0, 0x0, 0x0)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1239 +0x1c7
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.newRaft(0xc4210eb5c0, 0x45de9f6)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:320 +0xc5b
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.NewRawNode(0xc4210eb5c0, 0x0, 0x0, 0x0, 0xc4202b3140, 0x0, 0x0)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:79 +0x71
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc42021ef00, 0x5c80f00, 0x5c809f8, 0x0, 0x9)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:544 +0x300
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).maybeInitializeRaftGroup(0xc42021ef00, 0x694fca0, 0xc420eaab40)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1797 +0x185
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc42021ef00, 0x694fca0, 0xc420eaab40, 0x14f92b00a6b765c4, 0x0, 0x0, 0x0, 0x34, 0x0, 0x0, ...)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1821 +0x136
github.com/cockroachdb/cockroach/pkg/storage.(*pendingLeaseRequest).requestLeaseAsync.func1(0x694fc60, 0xc4208ea540)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go:213 +0x4a9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4208205a0, 0x694fc60, 0xc4208ea540, 0xc420e3c080, 0x35, 0x695f800, 0xc4203e4400, 0xc4207ba100)
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:267 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/Users/vilterp/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:262 +0x133
```

Then I did a `rm -rf cockroach-data`, started up the server again, did the same thing in the shell again, and it worked. Not really sure if this had anything to do with the SQL I was running or not.

**Comment by cuongdo** [comment]
What did you do prior to the crash? Was there other load on the node prior to that?

**Comment by vilterp** [comment]
My memory is a little hazy, but this is probably a "nodes thinking they're in the same cluster when they're actually in different clusters" issue. I think I did something like this:

1. start a roachdemo cluster with data directory A
2. shut it down
3. start an individual cockroach process with data directory B
5. `git pull && make`
6. restart the roachdemo cluster, forgetting about the other process. see that its processes are failing to start up.
7. kill the roachdemo
8. restart the single process
9. run the SQL statements in the issue

My guess is that the raft state of the single process was corrupted by the roachdemo (with a different data directory) trying to start up and join it.

**Comment by a-robinson** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/20537 and https://github.com/cockroachdb/cockroach/issues/15898
