### ISSUE TITLE
distsqlrun: panic when calling date_trunc in a distSQL plan

### ISSUE THREAD

**Issue by lego** [cockroachdb/cockroach#20464]
The following schema and statements will cause a panic.
```sql
CREATE TABLE topics (created_at TIMESTAMP NULL);

INSERT INTO topics VALUES ('2017-12-05 04:04:04.913231+00:00');

SELECT date_trunc('month', created_at) AS date_trunc_month_created_at FROM "topics";
```

When running in the local execution engine, everything is fine.

```sql
panic: invalid datum type given: timestamptz, expected timestamp

goroutine 23358 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x69ef300, 0xc4271d65a0, ...)
	/Users/joey/.go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:122 +0x26e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcOutputHelper).ProcessRow(0xc4257f4a00, 0x69defc0, 0xc4239de300, 0xc4244b1c00, 0x12, 0x12, 0x80, 0x14fd4a35d3c48708, 0x0, 0x0, ...)
	/Users/joey/.go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:330 +0x7ae
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcOutputHelper).EmitRow(0xc4257f4a00, 0x69defc0, 0xc4239de300, 0xc4244b1c00, 0x12, 0x12, 0xc42290ab00, 0xc42290ab70, 0x0)
	/Users/joey/.go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:264 +0x8e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Run(0xc4257f4a00, 0x69defc0, 0xc4239de300, 0xc42290aa88)
	/Users/joey/.go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:171 +0x3f9
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
	/Users/joey/.go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:419 +0x3d7
```

(yours truly, the gift that keeps giving: 💎-🛤 testing)

**Comment by lego** [comment]
Aha! Looks like the error is that `date_truct` function always returns a `TimestampTZ` while the signature is an identity of the inputs it's defined on, `Date`, `Time`, and `Timestamp`.
