### ISSUE TITLE
jepsen: `JSchException: channel is not opened`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#20493]
```
[09:45:18][/start-kill-2] INFO [2017-11-21 09:45:16,762] jepsen node 35.196.69.217 - jepsen.cockroach 35.196.69.217 Clearing the logs...
[09:45:18][/start-kill-2] ERROR [2017-11-21 09:45:17,839] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
[09:45:18][/start-kill-2] java.util.concurrent.ExecutionException: com.jcraft.jsch.JSchException: channel is not opened.
[09:45:18][/start-kill-2] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_151]
[09:45:18][/start-kill-2] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_151]
[09:45:18][/start-kill-2] 	at clojure.core$deref_future.invokeStatic(core.clj:2208) ~[clojure-1.8.0.jar:na]
[09:45:18][/start-kill-2] 	at clojure.core$future_call$reify__6962.deref(core.clj:6688) ~[clojure-1.8.0.jar:na]
```

This was previously seen in #19994 and thought to be another manifestation of the same problem, but it was not fixed by disabling sshguard in #20019 so it appears to be a separate issue.

**Comment by bdarnell** [comment]
I believe this has only been seen in conjunction with the `start-kill-2` nemesis. It appears to occur much more often on `JepsenBank-multitable/start-kill-2` than other tests.

**Comment by bdarnell** [comment]
#20733 collected `/var/log` from the controller, not from the workers, so it hasn't provided useful information. I've added another patch to jepsen to collect `auth.log` from the workers instead (which should help with this and the less-frequent #20492). 

I don't have any idea why this happens so consistently for bank-multitable/start-kill-2 (since we've been collecting issue links here, the only time it hit a different test was g2/start-kill-2). It could be timing-related: this test runs reliably at ~8:45am UTC (the g2 failure was at 9:45). I don't think we've observed a failure in manual runs at different times, although I'm not sure.

**Comment by tschottdorf** [comment]
Is this an uninteresting test? It's been skipped for months now. Is this worth investigating anytime soon?

**Comment by bdarnell** [comment]
I never copied the logic to disable this test over to the roachtest version, and it hasn't been a problem there. So apparently whatever was happening here isn't happening any more, or for some inscrutable reason it was specific to the terraform environment.
