### ISSUE TITLE
sql: SCRUB runtime: out of memory

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#20533]
While running the following SCRUB, got an OOM. cockroach invoked with `--max-sql-memory 8G --cache 1G`. The scrubbed table is reported in the ui as 9.6G and has 37M rows.

```
root@:26257/hots> EXPERIMENTAL SCRUB TABLE players WITH OPTIONS INDEX (players_battletag_idx);
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1fdf973, 0x16)
        /usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc5581f0000, 0x7e60000, 0x0, 0x354f9b8)
        /usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x350e640, 0x7e60000, 0x1)
        /usr/local/go/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0x350e640, 0x3f2c, 0x0)
        /usr/local/go/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0x350e640, 0x3f2c, 0x354f9c8, 0x7f8652902368)
        /usr/local/go/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0x350e640, 0x3f2c, 0x7f8659ff0100, 0x7f865f396000)
        /usr/local/go/src/runtime/mheap.go:666 +0x118
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0x7f8659ffea90)
        /usr/local/go/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0x350e640, 0x3f2c, 0x7f8659010100, 0x5f01d4)
        /usr/local/go/src/runtime/mheap.go:732 +0xa1
runtime.largeAlloc(0x7e58000, 0x7f865f390001, 0xc4e5d83911)
        /usr/local/go/src/runtime/malloc.go:827 +0x98
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:722 +0x46
runtime.systemstack(0xc420027900)
        /usr/local/go/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1125

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:298 fp=0xc4209ad5f0 sp=0xc4209ad5e8 pc=0x635de0
runtime.mallocgc(0x7e58000, 0x1cae800, 0x1, 0xc48b7e5c80)
        /usr/local/go/src/runtime/malloc.go:721 +0x7b8 fp=0xc4209ad698 sp=0xc4209ad5f0 pc=0x5ec858
runtime.growslice(0x1cae800, 0xc50c6e0000, 0x436155, 0x436155, 0x436156, 0xc4ecb467d0, 0x1, 0x1)
        /usr/local/go/src/runtime/slice.go:147 +0x139 fp=0xc4209ad700 sp=0xc4209ad698 pc=0x61f589
github.com/cockroachdb/cockroach/vendor/github.com/olekukonko/tablewriter.(*Table).Append(0xc42046e780, 0xc548756d80, 0x8, 0x8)
        /home/mjibson/src/github.com/cockroachdb/cockroach/vendor/github.com/olekukonko/tablewriter/table.go:284 +0x28b fp=0xc4209ad7c8 sp=0xc4209ad700 pc=0x181c31b
github.com/cockroachdb/cockroach/pkg/cli.(*prettyReporter).iter(0xc42028ea20, 0x2fd34a0, 0xc42000e018, 0x436155, 0xc548756d80, 0x8, 0x8, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/cli/format_table.go:190 +0xed fp=0xc4209ad808 sp=0xc4209ad7c8 pc=0x1853a5d
github.com/cockroachdb/cockroach/pkg/cli.render(0x2ff0fc0, 0xc42028ea20, 0x2fd34a0, 0xc42000e018, 0xc42030a200, 0x8, 0x8, 0x2fd8520, 0xc42024b860, 0xc42028ea00, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/cli/format_table.go:144 +0x151 fp=0xc4209ad890 sp=0xc4209ad808 pc=0x18535d1
github.com/cockroachdb/cockroach/pkg/cli.runQueryAndFormatResults(0xc42030ae80, 0x2fd34a0, 0xc42000e018, 0xc4207e4300, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/cli/sql_util.go:563 +0x286 fp=0xc4209ad988 sp=0xc4209ad890 pc=0x18676f6
github.com/cockroachdb/cockroach/pkg/cli.(*cliState).doRunStatement(0xc4207ee000, 0x2, 0x4)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:949 +0xb8 fp=0xc4209ad9f0 sp=0xc4209ad988 pc=0x1863018
github.com/cockroachdb/cockroach/pkg/cli.runInteractive(0xc42030ae80, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1074 +0x19f fp=0xc4209adbd0 sp=0xc4209ad9f0 pc=0x186365f
github.com/cockroachdb/cockroach/pkg/cli.runTerm(0x2fbc160, 0xc42024a040, 0x0, 0x1, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1131 +0x14e fp=0xc4209adc38 sp=0xc4209adbd0 pc=0x186416e
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x2fbc160, 0xc42024a040, 0x0, 0x1, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:38 +0x61 fp=0xc4209adcb0 sp=0xc4209adc38 pc=0x1877691
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x2fbc160, 0xc42024a020, 0x1, 0x1, 0x2fbc160, 0xc42024a020)
        /home/mjibson/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:698 +0x47a fp=0xc4209add58 sp=0xc4209adcb0 pc=0x181169a
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2fb83c0, 0x605d39, 0xc42007e260, 0xc42069fef0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:783 +0x30e fp=0xc4209ade88 sp=0xc4209add58 pc=0x1811e6e
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0x2fb83c0, 0xc42069fee8, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:736 +0x2b fp=0xc4209adeb8 sp=0xc4209ade88 pc=0x1811b3b
github.com/cockroachdb/cockroach/pkg/cli.Run(0xc4200100a0, 0x2, 0x2, 0xc420014120, 0xc4201c8600)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:159 +0x6d fp=0xc4209adee0 sp=0xc4209adeb8 pc=0x18422ed
github.com/cockroachdb/cockroach/pkg/cli.Main()
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:52 +0x16c fp=0xc4209adf70 sp=0xc4209adee0 pc=0x1841e3c
main.main()
        /home/mjibson/src/github.com/cockroachdb/cockroach/main.go:27 +0x20 fp=0xc4209adf80 sp=0xc4209adf70 pc=0x188a590
runtime.main()
        /usr/local/go/src/runtime/proc.go:185 +0x20d fp=0xc4209adfe0 sp=0xc4209adf80 pc=0x608b3d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4209adfe8 sp=0xc4209adfe0 pc=0x638a11

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x34ff380)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1003 +0x81
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:579 +0xbf

goroutine 11 [syscall, 42 minutes]:
os/signal.signal_recv(0xc4201a2460)
        /usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
```

**Comment by lego** [comment]
Uh oh. I'm not quite sure why this would happen or what exactly failed here. My best guess is that the distSQL sorter did not correctly handle memory limits.

I also am trying to reproduce it locally and I'm not having any luck. I did a 700mb dataset (id, name) that became 1.3gb on disk, with the default sql and cache limits (128mb). Maybe it got an out of memory error _because_ you allowed CockroachDB to use too much memory?

**Comment by lego** [comment]
I gave this a try with a 70mil row CSV (two columns). The reported imported bytes was about 9.9GB. I just tried running this with default SQL and cache memory limits (128mb) and had no problems.

Could you give it a shot with lower/default limits, maybe locally?

Another possible cause might be that there are so many results that the plan executor is getting OOM. None of the scrub results get streamed, so if there is a huge amount of errors it could OOM there.

**Comment by mjibson** [comment]
It's probably that then. My SCRUB produced 14M results.

**Comment by lego** [comment]
Did lowering the SQL or cache memory make it work?

I'm pretty sure it does account for memory, but I'll look into why this was a problem or how to stream results. Thanks Matt!

**Comment by mjibson** [comment]
I didn't test it with lower memory limits and the data is gone now, sorry. But if it wasn't streaming the results, it's almost certainly the 14 million results that were causing it.

**Comment by lego** [comment]
NP, it's clear what the problem is: the `RowContainer` blew over the memory limit.

**Comment by lego** [comment]
I mentioned earlier that a solution to this would be using the `DiskRowContainer`, but I just realized that it is only usable inside distSQL (or at least that is my assumption, between not being exported and use of temp storage and monitors set up in a flow).

Because of this, it may be easier to create a short `rowResultWriter` implementor that will stream. Whether by a channel or with a buffer, who knows, but it also doesn't seem great to go to this extent for something specific. cc: @knz

**Comment by yiv** [comment]
same issue happened on v2.0.1

**Comment by dt** [comment]
this is very old and sql exec has memory accounting now
