### ISSUE TITLE
Crash on INSERT with COLLATE & NULL

### ISSUE THREAD

**Issue by idubrov** [cockroachdb/cockroach#20636]
**BUG REPORT**

I171211 22:08:45.014336 1 util/log/clog.go:992  [config] file created at: 2017/12/11 22:08:45
I171211 22:08:45.014336 1 util/log/clog.go:992  [config] running on machine: Ivans-MacBook-Pro
I171211 22:08:45.014336 1 util/log/clog.go:992  [config] binary: CockroachDB CCL v1.1.3 (darwin amd64, built 2017/11/27 14:50:50, go1.9.2)
I171211 22:08:45.014336 1 util/log/clog.go:992  [config] arguments: [cockroach start --insecure --host 127.0.0.1]

Here is what happened (the value of $5 happened to be NULL, 'value' column has COLLATE en_u_ks_level2):

```
*
* ERROR: [client=127.0.0.1:49495,user=bend,n1] a SQL panic has occurred!
*
*
* ERROR: [n1] a panic has occurred!
*
*
* ERROR: [n1] Reported as error 17882c5837394caea1c4460d26c5f5f0
*
panic while executing "INSERT INTO resources_search_params(resource_type, id, search_param, idx, value, reference_resource_type, reference_id) VALUES ($1, $2, $3, $4, $5 COLLATE en_u_ks_level2, $6, $7)": invalid argument to COLLATE: NULL

goroutine 1208 [running]:
runtime/debug.Stack(0x65a5200, 0xc4207f3ad0, 0xc420582600)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x65a5200, 0xc4207f3ad0, 0xc420582600, 0x56a5660, 0xc4202f7820, 0x1)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:129 +0x155
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420420120, 0x65a5200, 0xc4207f3ad0)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:179 +0xfb
panic(0x56a5660, 0xc4202f7820)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc4210acc00, 0x65a5200, 0xc42135c360)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:423 +0xa1
panic(0x56a5660, 0xc4202f7820)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc4203b6000, 0x5890a4e, 0x9, 0xc4218884e4, 0xb2)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1381 +0x262
panic(0x55caac0, 0xc4203c9d50)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/parser.(*CollateExpr).Eval(0xc42186cf60, 0xc4203b6260, 0xc42186cf60, 0x65ac700, 0xc42186cf60, 0xc42186cf00)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/parser/eval.go:2692 +0x30b
github.com/cockroachdb/cockroach/pkg/sql/parser.(*normalizeVisitor).VisitPost(0xc4203b6918, 0x65a66c0, 0xc42186cf60, 0x65a66c0, 0xc42186cf60)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/parser/normalize.go:629 +0x106
github.com/cockroachdb/cockroach/pkg/sql/parser.WalkExpr(0x6594040, 0xc4203b6918, 0x65a66c0, 0xc42186cf30, 0xc42186cf30, 0xc42186cf30, 0x0)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/parser/walk.go:578 +0x182
github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).NormalizeExpr(0xc4203b6458, 0xc4203b6260, 0x65ac700, 0xc42186cf30, 0xc4203c9d30, 0x65ac700, 0xc42186cf30, 0x0)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:124 +0xd3
github.com/cockroachdb/cockroach/pkg/sql.(*planner).analyzeExpr(0xc4203b6208, 0x65a5140, 0xc42144e180, 0x65a66c0, 0xc42186c8a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:1673 +0x18e
github.com/cockroachdb/cockroach/pkg/sql.(*planner).ValuesClause(0xc4203b6208, 0x65a5140, 0xc42144e180, 0xc4202f7680, 0xc42015a000, 0x7, 0x7, 0x0, 0x0, 0x0, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/values.go:111 +0x457
github.com/cockroachdb/cockroach/pkg/sql.(*planner).newPlan(0xc4203b6208, 0x65a5140, 0xc42144e180, 0x65a83c0, 0xc4202f7680, 0xc42015a000, 0x7, 0x7, 0x0, 0x0, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:456 +0x1d74
github.com/cockroachdb/cockroach/pkg/sql.(*planner).Insert(0xc4203b6208, 0x65a5140, 0xc42144e180, 0xc420fd3040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/insert.go:155 +0x446
github.com/cockroachdb/cockroach/pkg/sql.(*planner).newPlan(0xc4203b6208, 0x65a5140, 0xc42144e180, 0x65a7300, 0xc420fd3040, 0x0, 0x0, 0x0, 0xc40a67d9cb, 0x5470472ad1, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:375 +0x2c10
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc4203b6208, 0x65a5140, 0xc42144e180, 0x65a7300, 0xc420fd3040, 0x0, 0x0, 0x0, 0x14ff5d366dfb2ea6, 0x1, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:190 +0x8f
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc4200a1200, 0x65a7300, 0xc420fd3040, 0x0, 0x0, 0x0, 0x14ff5d366dfb2ea6, 0x1, 0xc4216270e0, 0xc4203b6208, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2127 +0x11a
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc4200a1200, 0xc4203b6000, 0x65a7300, 0xc420fd3040, 0x0, 0x0, 0x0, 0x14ff5d366dfb2ea6, 0x1, 0xc4216270e0, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1793 +0x69e
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc4200a1200, 0xc4203b6000, 0x65a7300, 0xc420fd3040, 0x0, 0x0, 0x0, 0x14ff5d366dfb2ea6, 0x1, 0xc4216270e0, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1318 +0x6a5
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc4200a1200, 0xc4203b6000, 0xc42144e100, 0x1, 0x1, 0xc42140b4b8, 0x1, 0x5970001, 0x0, 0x65aa420, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1188 +0x3e5
github.com/cockroachdb/cockroach/pkg/sql.runWithAutoRetry(0xc4200a1200, 0xc4203b6000, 0xc42144e100, 0x1, 0x1, 0xed1c00101, 0x0, 0xc42140b4b8, 0x3ff0000000000000, 0xc42140b1d0, ...)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1014 +0x39c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc4200a1200, 0xc4203b6000, 0xc42144e100, 0x1, 0x1, 0xc42140b4b8, 0x0, 0x4573256, 0xbe83deb60a67936f)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:831 +0x130
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execPrepared(0xc4200a1200, 0xc4203b6000, 0xc4212b1a00, 0xc42140b4b8, 0x9, 0xc4218884e4)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:685 +0x159
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecutePreparedStatement(0xc4200a1200, 0xc4203b6000, 0xc4212b1a00, 0xc42140b4b8, 0x0, 0x0)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:663 +0x134
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc4210acc00, 0xc4210acc28, 0x0, 0x0)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:958 +0x2ee
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc4210acc00, 0x65a5200, 0xc42135c360, 0xc4203c81d0, 0x5400, 0xc420658568, 0x0, 0x0)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:526 +0xb6c
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420658400, 0x65a5140, 0xc420764480, 0x65b1260, 0xc421060000, 0x0, 0x0)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x929
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x65b1260, 0xc421060000)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/server/server.go:749 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc420420120, 0x65a5200, 0xc4207f3ad0, 0xc42036c110, 0x65b1260, 0xc421060000, 0xc42029ba40)
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/private/tmp/cockroach-20171127-5929-s2opg0/cockroach-v1.1.3/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137 +0x263
```

**Comment by jordanlewis** [comment]
Thanks for the report. I can confirm this is easily reproducible:

```
root@:26257/test> create table foo(a string collate en_u_ks_level2);
CREATE TABLE
root@:26257/test> prepare x as insert into foo values ($1 collate en_u_ks_level2);
PREPARE
root@:26257/test> execute x(null);
driver: bad connection
```

Looks like the check for null inputs to collate happens in the wrong place, as this problem doesn't happen if the `collate en_u_ks_level2` occurs outside of a prepared statement.

**Comment by jordanlewis** [comment]
Hi @idubrov,

As a workaround, you can detect whether the value is null before running `collate` on it. 

For example,

`SELECT CASE $1 WHEN NULL THEN NULL ELSE $1 COLLATE en_u_ks_level2 END`.
