### ISSUE TITLE
sql: crash in nightlies with schema changes

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#21326]
[Schema change 3 to 5 nodes](https://teamcity.cockroachdb.com/viewLog.html?buildId=469406&buildTypeId=Cockroach_Nightlies_SchemaChangeTest3to510g&tab=buildLog) and [steady 6 nodes](https://teamcity.cockroachdb.com/viewLog.html?buildId=470235&buildTypeId=Cockroach_Nightlies_Steady_6Medium&tab=buildLog)  have been failing consistently since at least early December.

Node 1 is crashing with this error:

```
panic while executing 1 statements: EXPERIMENTAL SCRUB TABLE _._; caused by txn: no bytes to release, current 0, free 133048320

goroutine 5814024 [running]:
runtime/debug.Stack(0x33a9380, 0xc422b530b0, 0x3)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x33a9380, 0xc422b530b0, 0xc4201c6600, 0x21ab5c0, 0xc428af63f0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:184 +0xaf
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4206c41b0, 0x33a9380, 0xc422b530b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:178 +0xfb
panic(0x21ab5c0, 0xc428af63f0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc42c0ac780, 0x33a9380, 0xc4337d45a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:426 +0xa1
panic(0x21ab5c0, 0xc428af63f0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc42a93b000, 0x22a18d0, 0x9, 0xc429b67000, 0x2a)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1455 +0x357
panic(0x1f9dc00, 0xc4318ddcb0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc42a93b150, 0x33a92c0, 0xc43824df80, 0x7ee2800)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:569 +0x3e2
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc427f703d0, 0x33a92c0, 0xc43824df80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:468 +0x66
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowContainer).Close(0xc427f70360, 0x33a92c0, 0xc43824df80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go:223 +0x93
github.com/cockroachdb/cockroach/pkg/sql.(*physicalCheckOperation).Close(0xc42c2213e0, 0x33a92c0, 0xc43824df80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/scrub_physical.go:195 +0x52
github.com/cockroachdb/cockroach/pkg/sql.(*scrubNode).Close(0xc42b3dd400, 0x33a92c0, 0xc43824df80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/scrub.go:167 +0x65
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc4200c86c0, 0x33ab800, 0xc425b894f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1507cf5aa91c1341, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2219 +0x592
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc4200c86c0, 0xc42a93b000, 0x33ab800, 0xc425b894f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1507cf5aa91c1341, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1842 +0x758
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc4200c86c0, 0xc42a93b000, 0x33ab800, 0xc425b894f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1507cf5aa91c1341, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1318 +0x6c8
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc4200c86c0, 0xc42a93b000, 0xc425b89540, 0x1, 0x1, 0x0, 0x1, 0x1, 0x1, 0x33adfe0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1194 +0x41f
github.com/cockroachdb/cockroach/pkg/sql.runWithAutoRetry(0xc4200c86c0, 0xc42a93b000, 0xc425b89540, 0x1, 0x1, 0xed1e50101, 0x0, 0x0, 0x3ff0000000000000, 0xc430e45d00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1019 +0x3aa
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc4200c86c0, 0xc42a93b000, 0xc425b89540, 0x1, 0x1, 0x0, 0x0, 0xc42b5ffd40, 0xb2d35201a26)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:835 +0x138
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4200c86c0, 0xc42a93b000, 0xc429b67000, 0x2a, 0x0, 0x0, 0x2a, 0xc429b67000)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:744 +0x49c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4200c86c0, 0xc42a93b000, 0xc429b67000, 0x2a, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:629 +0x1bd
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc42c0ac780, 0xc42c0ac7a8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:615 +0x1d0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc42c0ac780, 0x33a9380, 0xc4337d45a0, 0xc42675ec60, 0x5400, 0x15000, 0xc4200c8a78, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:506 +0x8b1
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4200c8900, 0x33a92c0, 0xc42cfd3e80, 0x33b5420, 0xc424d02f00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0xbae
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func17.1(0x33b5420, 0xc424d02f00)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1249 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4206c41b0, 0x33a9380, 0xc422b530b0, 0xc420574108, 0x33b5420, 0xc424d02f00, 0xc422b530e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137 +0x263

*
* ERROR: [n1] Reported as error 84fe2a7ef85c4de1824c192e391ef315
*
```

**Comment by cuongdo** [comment]
@vivekmenezes please triage

**Comment by vivekmenezes** [comment]
@lego have you ever seen this?

**Comment by tschottdorf** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/435584438/
