### ISSUE TITLE
Panic with ON DELETE CASCADE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#21563]
Panic with `ON DELETE CASCADE`

```
~/src/github.com/cockroachdb/cockroach$ cockroach start --insecure --store=drop-table
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/dev/secure-a-cluster.html
*
CockroachDB node starting at 2018-01-18 16:04:07.002777 +0000 UTC (took 0.5s)
build:               CCL up-971-g833b5609e @ 2018/01/11 23:52:31 (go1.9)
admin:               http://JESSEs-MBP:8080
sql:                 postgresql://root@JESSEs-MBP:26257?application_name=cockroach&sslmode=disable
logs:                /Users/jesseseldess/src/github.com/cockroachdb/cockroach/drop-table/logs
temp dir:            /Users/jesseseldess/src/github.com/cockroachdb/cockroach/drop-table/cockroach-temp801942329
external I/O path:   /Users/jesseseldess/src/github.com/cockroachdb/cockroach/drop-table/extern
store[0]:            path=/Users/jesseseldess/src/github.com/cockroachdb/cockroach/drop-table
status:              initialized new cluster
clusterID:           e5f73374-7dc0-459b-9070-56d66b79c51a
nodeID:              1
*
* ERROR: [client=127.0.0.1:53651,user=root,n1] a SQL panic has occurred while executing "delete from customers where id > 0;": txn: no bytes to release, current 0, free 10240
*
*
* ERROR: [n1] a panic has occurred!
*
panic while executing 1 statements: DELETE FROM _ WHERE _ > _; caused by txn: no bytes to release, current 0, free 10240

goroutine 534 [running]:
runtime/debug.Stack(0x6c5fb80, 0xc42a2d0e10, 0x3)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6c5fb80, 0xc42a2d0e10, 0xc4201c4600, 0x5cb6800, 0xc42a302510, 0x1)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:184 +0xaf
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420725dd0, 0x6c5fb80, 0xc42a2d0e10)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:178 +0xfb
panic(0x5cb6800, 0xc42a302510)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc429e6c960, 0x6c5fb80, 0xc4292af9b0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:429 +0xa1
panic(0x5cb6800, 0xc42a302510)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc429ff0600, 0x5db0ed2, 0x9, 0xc42bd4b457, 0x23)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1462 +0x357
panic(0x5aa4480, 0xc4296deea0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc429ff0778, 0x6c5fac0, 0xc429473800, 0x2800)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:569 +0x3e2
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc42a666a00, 0x6c5fac0, 0xc429473800)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:468 +0x66
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowContainer).Close(0xc42a666990, 0x6c5fac0, 0xc429473800)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go:223 +0x93
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*cascader).close(0xc4294738c0, 0x6c5fac0, 0xc429473800)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/cascader.go:55 +0x9b
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*cascader).cascadeAll(0xc4294738c0, 0x6c5fac0, 0xc429473800, 0xc42e654f00, 0xc428bfb0a0, 0x1, 0x1, 0xc42aab0fc0, 0xc429ff0778, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/cascader.go:540 +0xe86
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowDeleter).DeleteRow(0xc42aa48d20, 0x6c5fac0, 0xc429473800, 0xc42b124a00, 0xc428bfb0a0, 0x1, 0x1, 0xc429ff0778, 0xc420155800, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowwriter.go:923 +0x12d
github.com/cockroachdb/cockroach/pkg/sql.(*tableDeleter).row(0xc42aa48d20, 0x6c5fac0, 0xc429473800, 0xc428bfb0a0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go:687 +0x8e
github.com/cockroachdb/cockroach/pkg/sql.(*deleteNode).Next(0xc42aa48d00, 0x6c5fac0, 0xc429473800, 0xc429ff08c8, 0xc429ff0850, 0x5c1be01, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/delete.go:175 +0x247
github.com/cockroachdb/cockroach/pkg/sql.forEachRow(0x6c5fac0, 0xc429473800, 0xc429ff08c8, 0xc429ff0850, 0x6c56900, 0xc42aa48d00, 0xc4299147f0, 0xc429ff0850, 0x6c56900)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2076 +0xaa
github.com/cockroachdb/cockroach/pkg/sql.countRowsAffected(0x6c5fac0, 0xc429473800, 0xc429ff08c8, 0xc429ff0850, 0x6c56900, 0xc42aa48d00, 0x0, 0x0, 0xc429ff1600)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2099 +0xd7
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execClassic(0xc42009a6c0, 0xc429ff0850, 0x6c56900, 0xc42aa48d00, 0x6c6bce0, 0xc429e6c960, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2049 +0x30c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc42009a6c0, 0x6c61540, 0xc42e372370, 0x0, 0x0, 0x0, 0x0, 0x0, 0x150af490d28af418, 0x1, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2217 +0x709
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc42009a6c0, 0xc429ff0600, 0x6c61540, 0xc42e372370, 0x0, 0x0, 0x0, 0x0, 0x0, 0x150af490d28af418, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1850 +0x758
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc42009a6c0, 0xc429ff0600, 0x6c61540, 0xc42e372370, 0x0, 0x0, 0x0, 0x0, 0x0, 0x150af490d28af418, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1319 +0x6c8
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc42009a6c0, 0xc429ff0600, 0xc42e3723c0, 0x1, 0x1, 0x0, 0x1, 0x4000001, 0x0, 0x6c648a0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1195 +0x41f
github.com/cockroachdb/cockroach/pkg/sql.runWithAutoRetry(0xc42009a6c0, 0xc429ff0600, 0xc42e3723c0, 0x1, 0x1, 0xed1f20101, 0x0, 0x0, 0x3ff0000000000000, 0xc429915300, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1020 +0x3aa
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc42009a6c0, 0xc429ff0600, 0xc42e3723c0, 0x1, 0x1, 0x0, 0x0, 0xc429653aa0, 0x5a60cc07)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:836 +0x138
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc42009a6c0, 0xc429ff0600, 0xc42bd4b457, 0x23, 0x0, 0x0, 0x23, 0xc42bd4b457)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:745 +0x49c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc42009a6c0, 0xc429ff0600, 0xc42bd4b457, 0x23, 0x0, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:630 +0x1bd
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc429e6c960, 0xc429e6c988, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:618 +0x1d0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc429e6c960, 0x6c5fb80, 0xc4292af9b0, 0xc42a6e51d0, 0x5400, 0x15000, 0xc42009aa78, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:509 +0x8b1
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42009a900, 0x6c5fac0, 0xc42aae6280, 0x6c6bec0, 0xc42aae4280, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0xbae
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func17.1(0x6c6bec0, 0xc42aae4280)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1252 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc420725dd0, 0x6c5fb80, 0xc42a2d0e10, 0xc4207f8050, 0x6c6bec0, 0xc42aae4280, 0xc42a2d0e40)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137 +0x263

*
* ERROR: [n1] Reported as error b5fa5c118fe7474fb128a381aacc9bf6
*
```

Steps to reproduce:

1. Start cockroach
2. Start `cockroach sql`

Then:
```
root@:26257> create database test;
CREATE DATABASE

root@:26257> set database = test;
SET DATABASE 

root@:26257/test> create table customers (id int primary key, address string);
CREATE TABLE 

root@:26257/test> create table orders (id int primary key, customer_id int references customers(id) on delete cascade);
CREATE TABLE

Time: 25.176ms

root@:26257/test> insert into customers values (1, 'blah');
INSERT 1

Time: 2.861ms

root@:26257/test> insert into customers values (2, 'blah');
INSERT 1

Time: 948µs

root@:26257/test> insert into orders values (1, 1);
INSERT 1

Time: 2.929ms

root@:26257/test> insert into orders values (1, NULL);
pq: duplicate key value (id)=(1) violates unique constraint "primary"
root@:26257/test> insert into orders values (2, NULL);
INSERT 1

Time: 1.033ms

root@:26257/test> delete from customers;
pq: rejected: DELETE without WHERE clause (sql_safe_updates = true)
root@:26257/test> delete from customers where id > 0;
driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
root@:26257/test> delete from customers where id > 0;
invalid syntax: statement ignored: driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the transaction status: dial tcp 127.0.0.1:26257: getsockopt: connection refused
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the database name: dial tcp 127.0.0.1:26257: getsockopt: connection refused
root@:26257 ?> \q
Error: invalid syntax
Failed running "sql"
~/src/github.com/cockroachdb/cockroach$ cockroach sql --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp 127.0.0.1:26257: getsockopt: connection refused
Failed running "sql"
```

**Comment by vivekmenezes** [comment]
I would really love to hear what is responsible for the 10240 bytes request, because the same number is seen in #21544

**Comment by petermattis** [comment]
> I would really love to hear what is responsible for the 10240 bytes request, because the same number is seen in #21544

The panic indicates a memory accounting bug. 10240 bytes is the default monitoring "chunk" allocation size which is why you see it frequently whenever there is a panic like this.

`util/mon/bytes_usage.go:var DefaultPoolAllocationSize = envutil.EnvOrDefaultInt64("COCKROACH_ALLOCATION_CHUNK_SIZE", 10*1024)`
