### ISSUE TITLE
sql: ADD COLUMN crashes server

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22417]
Found while investigating #21873 but has nothing to do with computed columns:

```
> create table blah(x int);
CREATE TABLE
> alter table blah add column z oid default 'foo'::regclass::oid;
invalid syntax: statement ignored: driver: bad connection
```

Panic log:
```
runtime error: invalid memory address or nil pointer dereference

goroutine 278 [running]:
runtime/debug.Stack(0x35919a0, 0xc420891020, 0x3)
        /data/home/kena/src/go1.9.2/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x35919a0, 0xc420891020, 0xc420034c00, 0x2178dc0, 0x353f7b0, 0x1)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:184 +0xaf
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42017cab0, 0x35919a0, 0xc420891020)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:178 +0xfb
panic(0x2178dc0, 0x353f7b0)
        /data/home/kena/src/go1.9.2/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.performCast(0xc42647f4a0, 0x35a25c0, 0xc4265e2218, 0x3589560, 0x353ed90, 0x0, 0xe50000, 0x35996c0, 0x3592c20)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:2938 +0x32df
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*CastExpr).Eval(0xc4265e2240, 0xc42647f4a0, 0xc4265e2240, 0x35996c0, 0xc4265e2240, 0x1)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:2495 +0xe3
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*NormalizeVisitor).VisitPost(0xc4265cafc0, 0x3592c20, 0xc4265e2240, 0x3592c20, 0xc4265e2240)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/normalize.go:748 +0x111
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr(0x357d920, 0xc4265cafc0, 0x3592c20, 0xc4265e2240, 0x32a00598738, 0x0, 0x22c9020)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:584 +0x182
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*CastExpr).Walk(0xc4265e2280, 0x357d920, 0xc4265cafc0, 0xc4265e2201, 0x3592c20)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:131 +0x4f
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr(0x357d920, 0xc4265cafc0, 0x3592c20, 0xc4265e2280, 0xc4265e2280, 0xc4265e2280, 0xc426599200)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:583 +0x15a
github.com/cockroachdb/cockroach/pkg/sql/sem/transform.(*ExprTransformContext).NormalizeExpr(0xc4265cafc0, 0xc42647f4a0, 0x35996c0, 0xc4265e2280, 0xc426599238, 0x35996c0, 0xc4265e2280, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/transform/expr_transform.go:43 +0x16b
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.MakeDefaultExprs(0xc426549710, 0x1, 0x1, 0xc4265cafc0, 0xc42647f4a0, 0xc426549710, 0x0, 0x1, 0x2, 0xc426391ab8)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/default_exprs.go:67 +0x5ae
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*columnBackfiller).init(0xc4265f7500, 0xc4265f7500, 0x65d14a)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/columnbackfiller.go:92 +0x694
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newColumnBackfiller(0xc4258e38c0, 0x1, 0xc4265987fb, 0x3, 0x320000006b, 0x3, 0x1510c8d1b7317d77, 0x0, 0xc426586fc0, 0x3, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/columnbackfiller.go:66 +0x113
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newProcessor(0xc4258e38c0, 0xc4266026d8, 0xc426602758, 0x0, 0x0, 0x0, 0xc4265fce80, 0x1, 0x1, 0xc4263926a0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:648 +0xb6b
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).makeProcessor(0xc4258e38c0, 0xc4266026c0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x9ddb6652263927b0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:296 +0x57f
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).setup(0xc4258e38c0, 0x35919a0, 0xc4266145a0, 0xc42650d480, 0x8, 0x1)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:371 +0xd11
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ServerImpl).setupFlow(0xc42014fa00, 0x35919a0, 0xc4266145a0, 0x35a1760, 0xc42620dd40, 0xc42650d380, 0x357c660, 0xc426608900, 0x215cdc0, 0xc426393908, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/server.go:358 +0xcca
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ServerImpl).SetupSyncFlow(0xc42014fa00, 0x35918e0, 0xc42659ba40, 0xc42650d380, 0x357c660, 0xc426608900, 0x0, 0x1, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/server.go:375 +0xe3
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc4204cf200, 0xc4263944a8, 0xc42650cd00, 0xc426394568, 0xc426608900, 0xc4257f4800)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:205 +0x9b1
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).distBackfill.func2(0x35918e0, 0xc42659ba40, 0xc42650cd00, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:553 +0x5cb
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x35918e0, 0xc42659ba40, 0xc42650cd00, 0xc4265986f6, 0x0, 0x1510c8d7b6b66e6a)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:510 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc42650cd00, 0x35918e0, 0xc42659ba40, 0xc426500101, 0xc4265ace20, 0xc426317e60, 0xc426390100)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:729 +0xfe
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc4202e4780, 0x35918e0, 0xc42659ba40, 0xc42653df20, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:509 +0x149
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).distBackfill(0xc4262035f0, 0x35919a0, 0xc426317e60, 0xc4257f4800, 0xc426374000, 0xc400000003, 0x1, 0xc8, 0x24ce9e8, 0x3, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:484 +0x635
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).truncateAndBackfillColumns(0xc4262035f0, 0x35919a0, 0xc426317e60, 0xc4257f4800, 0xc426374000, 0x3, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:600 +0x86
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).runBackfill(0xc4262035f0, 0x35919a0, 0xc426317e60, 0xc426374000, 0xc4257f4800, 0x0, 0x145f19b)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:187 +0xbbb
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).runStateMachineAndBackfill(0xc4262035f0, 0x35919a0, 0xc426317e60, 0xc426374000, 0xc4257f4800, 0x0, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:698 +0x1d9
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).exec(0xc4262035f0, 0x35919a0, 0xc426317e60, 0xc4201cd200, 0xc4257f4800, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:458 +0x3ca
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x35919a0, 0xc420891020)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1079 +0x6b3
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420306c70, 0xc42017cab0, 0xc420372300)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad
```

cc @jordanlewis @vivekmenezes @nvanbenschoten

**Comment by knz** [comment]
@vivekmenezes please triage

**Comment by knz** [comment]
I think the root of the issue here is that any default / computed expression should disallow ::regclass or ::regproc casts as "impure functions".

**Comment by jordanlewis** [comment]
The proximal cause is that there's no `Planner` on the eval context, right?

**Comment by knz** [comment]
I don't know.

**Comment by knz** [comment]
Also meanwhile I'm noticing this is susceptible to crash every node in the cluster, because the backfill is distributed.

**Comment by knz** [comment]
Woo that's even worse than that. My ALTER ADD COLUMN was processed successfully and the txn committed, this means that now the backfill is rescheduled (and re-crashes) every time I try to restart the cluster.

**Comment by knz** [comment]
... and the cluster keeps crashing even if I DROP the table (it seems that the DROP cannot be processed until the previous schema change on the table has completed)

**Comment by vivekmenezes** [comment]
Will fix this , but clearly we have more to do here to make it safer.

**Comment by vivekmenezes** [comment]
The EvalPlanner interface is rather large so I'm going to have to do more work here to fix this.

**Comment by knz** [comment]
I think that the backfill should simply fail if the expression needs a planner.

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/issues/22520 for the separate issue of a crash being indefinite.
