### ISSUE TITLE
crash in TestBuildInfo

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22447]
Found in: 
https://teamcity.cockroachdb.com/viewLog.html?buildId=509358&buildTypeId=Cockroach_UnitTests

```
Test ended in panic.

------- Stdout: -------
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13ba1c5]

goroutine 33 [running]:
testing.tRunner.func1(0xc420368f00)
    /usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x1bad1a0, 0x2bb1020)
    /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/acceptance/localcluster.(*Node).advertiseAddrFile(0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/localcluster/cluster.go:647 +0x45
github.com/cockroachdb/cockroach/pkg/acceptance/localcluster.(*Node).AdvertiseAddr(0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/localcluster/cluster.go:667 +0x2f
github.com/cockroachdb/cockroach/pkg/acceptance/localcluster.(*Cluster).joins(0xc4204780c0, 0x6c, 0x1ed, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/localcluster/cluster.go:233 +0xb5
github.com/cockroachdb/cockroach/pkg/acceptance/localcluster.(*Cluster).makeNode(0xc4204780c0, 0x2bf8860, 0xc4200180c0, 0x2, 0xc420594230, 0x43, 0xc420015110, 0x61, 0xc420015180, 0x6c, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/localcluster/cluster.go:302 +0x8f3
github.com/cockroachdb/cockroach/pkg/acceptance/localcluster.(*Cluster).Start(0xc4204780c0, 0x2bf8860, 0xc4200180c0)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/localcluster/cluster.go:177 +0x3a6
github.com/cockroachdb/cockroach/pkg/acceptance.StartCluster(0x2bf8860, 0xc4200180c0, 0xc420368f00, 0xc420487e90, 0x9, 0xc4200c0a00, 0x4, 0x4, 0x12a05f200, 0x0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/util_cluster.go:173 +0x11e0
github.com/cockroachdb/cockroach/pkg/acceptance.runTestWithCluster(0xc420368f00, 0x1e6eb08, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/util_cluster.go:79 +0x13b
github.com/cockroachdb/cockroach/pkg/acceptance.TestBuildInfo.func1(0xc420368f00)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/build_info_test.go:34 +0x52
testing.tRunner(0xc420368f00, 0x1e6e950)
    /usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:789 +0x2de
```

**Comment by knz** [comment]
Nikhil please triage

**Comment by benesch** [comment]
Not sure what caused this, but both `acceptance` and `TestBuildInfo` are going away soon and we've only seen this once. Closing optimistically!
