### ISSUE TITLE
Deadlock during shutdown in TestReplicateAddAndRemove

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2255]
The following test appears to have failed:

[#6455](https://circleci.com/gh/cockroachdb/cockroach/6455):

```
I0825 10:02:25.252282 948 storage/replica.go:995  gossiping cluster id  from store 1, range 1
I0825 10:02:25.252719 948 storage/replica.go:1005  gossiping sentinel from store 1, range 1
I0825 10:02:25.252981 948 storage/replica.go:1011  gossiping first range from store 1, range 1
I0825 10:02:25.273029 948 storage/replica.go:995  gossiping cluster id  from store 3, range 1
I0825 10:02:25.274031 948 storage/replica.go:995  gossiping cluster id  from store 4, range 1
panic: test timed out after 5m0s

goroutine 74910 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x14b3938, 0x1a256c0, 0xb6, 0xb6, 0x834501)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/tmp/workdir/go/src/sync/mutex.go:82 +0x1ee
net/rpc.(*Client).input(0xc820522480)
	/usr/local/go/src/net/rpc/client.go:149 +0x1cc
created by net/rpc.NewClientWithCodec
	/usr/local/go/src/net/rpc/client.go:201 +0x126
FAIL	github.com/cockroachdb/cockroach/storage	300.046s
=== RUN   TestBatchBasics
I0825 09:58:17.953833 942 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0825 09:58:17.957997 942 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I0825 09:58:17.963619 942 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
is this just a multi-node cluster in which a majority has already shut down, while some others require it to finish outstanding tasks?

**Comment by bdarnell** [comment]
I'm not sure what's going on. The stopper made it from the Quiesce phase to the Stop phase, so there are no outstanding tasks. I don't see any obvious problems in the goroutine list. I do, however, see signs of problems related to replica tombstones ("got message for unknown group 1; creating it" on the node that has already removed the range), so it might be related. Since TestReplicateAddAndRemove is skipped by #2768, I'm going to close this and we can see if it recurs after replica tombstones are in.
