### ISSUE TITLE
TestTxnCoordSenderCleanupOnAborted failing under stress

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#22617]
`make stress PKG=./pkg/kv TESTS=TestTxnCoordSenderCleanupOnAborted`

```
--- FAIL: TestTxnCoordSenderCleanupOnAborted (45.20s)
	txn_coord_sender_test.go:481: condition failed to evaluate within 45s: expected no heartbeat
		goroutine 41 [running]:
		runtime/debug.Stack(0xa7a358200, 0xc42096fe00, 0x68b6980)
			/Users/andrei/go/src/runtime/debug/stack.go:24 +0xa7
		github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x68e84e0, 0xc4201c4780, 0xc42096fe00)
			/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:38 +0x7d
		github.com/cockroachdb/cockroach/pkg/kv.verifyCleanup(0xc4202527b0, 0x1, 0x8, 0x68eb6e0, 0xc420459980, 0xc4201c4780, 0xc42096fee8, 0x2, 0x2)
			/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender_test.go:481 +0xda
		github.com/cockroachdb/cockroach/pkg/kv.TestTxnCoordSenderCleanupOnAborted(0xc4201c4780)
			/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender_test.go:678 +0x6d2
		testing.tRunner(0xc4201c4780, 0x5c39210)
			/Users/andrei/go/src/testing/testing.go:746 +0xd0
		created by testing.(*T).Run
			/Users/andrei/go/src/testing/testing.go:789 +0x2de
FAIL


ERROR: exit status 1

1946 runs completed, 1 failures, over 46s
context canceled
```

**Comment by spencerkimball** [comment]
Isn’t this more likely to be the result of one of the more recent changes to the txn stuff? +cc @nvanbenschoten

**Comment by nvanbenschoten** [comment]
I just bisected this and the flake seems to have been introduced in dc22c39cb98ebd3ddd8a021e74fb85526e9f16da.

**Comment by spencerkimball** [comment]
Damn ok will take a look.
