### ISSUE TITLE
storage: panic on full disk

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#22677]
Not sure if this is known or not. I ran:

```
import table lineitem create using 'gs://cockroach-fixtures/tpch-csv/schema/lineitem.sql' CSV DATA (
'gs://cockroach-fixtures/tpch-csv/sf-10/lineitem.tbl.1',
'gs://cockroach-fixtures/tpch-csv/sf-10/lineitem.tbl.2',
'gs://cockroach-fixtures/tpch-csv/sf-10/lineitem.tbl.3',
'gs://cockroach-fixtures/tpch-csv/sf-10/lineitem.tbl.4',
'gs://cockroach-fixtures/tpch-csv/sf-10/lineitem.tbl.5',
'gs://cockroach-fixtures/tpch-csv/sf-10/lineitem.tbl.6',
'gs://cockroach-fixtures/tpch-csv/sf-10/lineitem.tbl.7',
'gs://cockroach-fixtures/tpch-csv/sf-10/lineitem.tbl.8'
) WITH  delimiter='|';
```

on a 3-node GCE cluster with 10G persistent SSDs attached. It paniced with:

```
F180214 07:21:18.691716 177 storage/store.go:3775  [n1,s1] during sideloading: during sideloading: write /mnt/data1/cockroach/auxiliary/sideloading/327/327.1/i16.t6: no space left on device
goroutine 177 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x3b0c700, 0x1513202d64db8e28, 0x3264054, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:904 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x3b0c700, 0xc400000004, 0x3264054, 0x10, 0xe
==> cockroach.stderr <==
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc42046bc00, 0x35dfc20, 0xc4204181b0, 0x147)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3775 +0x5b2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420742000, 0x35dfc20, 0xc4204181b0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:215 +0x259
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x35dfc20, 0xc4204181b0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420274980, 0xc420743ef0, 0xc420274970)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad
```

Assigning for triage.

**Comment by a-robinson** [comment]
Yeah, this is basically the expected behavior. If you run out of space, a panic with a clear error message is all we ever give you.

If anything, it seems like the action item here would not be to do an import that will take up more space than is available in the cluster. Otherwise, I'm not sure if there's anything to do for this.

**Comment by mjibson** [comment]
Ok. Just checking that it was known.
