### ISSUE TITLE
sql: panic in makeDistSQLReceiver

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#22835]
This is on the release-2.0 branch.

```
panic: sync/atomic: store of inconsistently typed value into Value [recovered]
        panic: sync/atomic: store of inconsistently typed value into Value

goroutine 1046293 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4207f2120, 0x3550940, 0xc458cf1440)
        /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:180 +0x136
panic(0x20301e0, 0x26a9a40)
        /home/jordan/go1.9/src/runtime/panic.go:491 +0x283
sync/atomic.(*Value).Store(0xc462d80068, 0x227a600, 0xc451718fc0)
        /home/jordan/go1.9/src/sync/atomic/value.go:79 +0x10d
github.com/cockroachdb/cockroach/pkg/sql.makeDistSQLReceiver.func1(0x352e340, 0xc451718fc0)
        /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:340 +0x4d
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).cleanupTxnLocked(0xc45c562540, 0x3550940, 0xc458cf15c0, 0x2)
        /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:916 +0x1f5
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).tryAsyncAbort(0xc45c562540, 0x3550940, 0xc458cf15c0)
        /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:1019 +0x15f
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).heartbeat(0xc45c562540, 0x3550940, 0xc458cf15c0, 0x0)
        /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:1130 +0x667
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).heartbeatLoop(0xc45c562540, 0x3550940, 0xc458cf15c0)
        /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:990 +0x34f
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).updateState.func1(0x3550940, 0xc458cf1440)
        /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:1308 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4207f2120, 0x3550940, 0xc458cf1440, 0xc497ee8d20, 0x29, 0x3561460, 0xc43cb0ba00, 0xc49c1aa8b0)
        /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:266 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:261 +0x133
```

**Comment by nvanbenschoten** [comment]
I just saw this as well, but with a different stack trace:

```
* ERROR: [n1,client=35.190.170.5:59306,user=root] a SQL panic has occurred while executing "SELECT sum(ol_amount) FROM order_line WHERE ((ol_w_id = $1) AND (ol_d_id = $2)) AND (ol_o_id = $3)": sync/atomic: store of inconsistently typed value into Value
*
*
* ERROR: [n1,client=35.190.170.5:59306,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT sum(_) FROM _ WHERE ((_ = $1) AND (_ = $2)) AND (_ = $3); caused by sync/atomic: store of inconsistently typed value into Value

goroutine 483782 [running]:
runtime/debug.Stack(0x25de2a0, 0xc434f54ac0, 0xc400000003)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x25de2a0, 0xc434f54ac0, 0xc420664000, 0x21ebd80, 0xc42ca0f020, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:192 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc434d67000, 0x25de2a0, 0xc434f54ac0, 0x1fb9200, 0x25b9ed0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:517 +0x2d5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2(0xc434d67000, 0x25de2a0, 0xc434f54ac0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:485 +0x61
panic(0x1fb9200, 0x25b9ed0)
        /usr/local/go/src/runtime/panic.go:505 +0x229
sync/atomic.(*Value).Store(0xc441778728, 0x2209c80, 0xc42abf8000)
        /usr/local/go/src/sync/atomic/value.go:77 +0x10d
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLReceiver).SetCanceled(0xc4417786c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:463 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).cancel(0xc42b382b00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:544 +0x27d
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Wait(0xc42b382b00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:484 +0x159
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc4207b8a80, 0xc42d0ad488, 0xc4341c4000, 0xc42d0ad4b8, 0xc4417786c0, 0xc434d67440)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:215 +0xa45
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc4207b8a80, 0x25de2a0, 0xc43eedf800, 0xc4341c4000, 0x25d4720, 0xc43aa41600, 0xc4417786c0, 0xc434d67440)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:515 +0x255
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc434d67000, 0x25de2a0, 0xc43eedf800, 0xc434d673d0, 0x3, 0x7f9eebb9b878, 0xc43fe98bd0, 0x0, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:626 +0x175
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc434d67000, 0x25de2a0, 0xc43eedf800, 0x25e0be0, 0xc43dfdfc80, 0xc425fd4de0, 0x1, 0x1, 0xc425d73e30, 0x62, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:535 +0x58c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc434d67000, 0x25de2a0, 0xc43eedf800, 0x25e0be0, 0xc43dfdfc80, 0xc425fd4de0, 0x1, 0x1, 0xc425d73e30, 0x62, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:333 +0x8c8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc434d67000, 0x25de2a0, 0xc43eedf800, 0x25e0be0, 0xc43dfdfc80, 0xc425fd4de0, 0x1, 0x1, 0xc425d73e30, 0x62, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:82 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc434d67000, 0x25de2a0, 0xc434f54ac0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:958 +0x10ad
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420273880, 0x25de2a0, 0xc434f54ac0, 0xc43e1cc00d, 0x4, 0xc43e1cc017, 0x4, 0x0, 0x0, 0x25c79a0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:487 +0xf31
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc420273880, 0x25de2a0, 0xc434f54ac0, 0xc42eca8700, 0x5400, 0x15000, 0xc420b00190, 0xc4307f61e0, 0xc43e2c3850, 0xc4307f61d0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:255 +0xfc
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:254 +0xf14
```

**Comment by andreimatei** [comment]
I've got no idea why this error is occuring, since we always seem to be storing `error` in the atomic, but in any case #22908 gets rid of one of the setters, so hopefully that'll fix it.

**Comment by jordanlewis** [comment]
I added some logging around this. It is complaining that we're trying to store a `*roachpb.HandledRetryableTxnError` in the `Value`, which already contains a `*pgerror.Error`.

Specifically, the error is `HandledRetryableTxnError: TransactionAbortedError: txn aborted "sql txn" id=534b6981 key=/Table/55/1/20/1/-2133/0 rw=true pri=0.06326698 iso=SERIALIZABLE stat=PENDING epo=0 ts=1519759315.691721388,0 orig=1519759315.691721388,0 max=1519759316.191721388,0 wto=false rop=false seq=4`. It's getting stored over a `query execution canceled` pgerror. It seems funky that these both are getting stored, but what do I know.


It's very easy to reproduce. Just run the TPCC load generator on a cluster, and then cancel the TPCC load generator with control C. That will trigger the panic about half of the time.

**Comment by jordanlewis** [comment]
It seems fundamentally that `atomic.Value` *does* in fact care about the underlying type of the error, though, so we need to be more careful with this.

**Comment by jordanlewis** [comment]
We should have just read the docs on `atomic.Value`.

https://golang.org/pkg/sync/atomic/#Value

>  All calls to Store for a given Value must use values of the same concrete type. 

This is just not an appropriate use of `atomic.Value.

**Comment by nvanbenschoten** [comment]
Take a look at https://github.com/hashicorp/terraform/pull/11761. The `errWrap struct { E error }` approach they use there is probably the most straightforward way to get around this.
