### ISSUE TITLE
sql: panic due to isRole not properly backfilled

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22929]
Found by RSG in https://teamcity.cockroachdb.com/viewLog.html?buildId=530929&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests:

```
E180222 07:03:32.878257 2303 sql/conn_executor.go:496  [n1,client=127.0.0.1:38046,user=root] a SQL panic has occurred while executing "DROP USER 'placeholder', 'string', 'placeholder', 'placeholder'": Non-nullable column "users:isRole" with no value! Index scanned was "primary" with the index key columns (username) and the values ('placeholder')
E180222 07:03:32.878331 2303 util/log/crash_reporting.go:181  [n1,client=127.0.0.1:38046,user=root] a panic has occurred!
E180222 07:03:32.879829 2303 util/log/crash_reporting.go:445  [n1,client=127.0.0.1:38046,user=root] Reported as error 1445b9ad8ca74a3ca7f8c12d0e8780f3
panic: Non-nullable column "users:isRole" with no value! Index scanned was "primary" with the index key columns (username) and the values ('placeholder') [recovered]
	panic: panic while executing 1 statements: DROP USER _, _, _, _; caused by Non-nullable column "users:isRole" with no value! Index scanned was "primary" with the index key columns (username) and the values ('placeholder')

goroutine 2303 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc420e8d000, 0x2186a40, 0xc421c634c0, 0x1c1fb20, 0xc4203d2880)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:510 +0x365
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2(0xc420e8d000, 0x2186a40, 0xc421c634c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:471 +0x61
panic(0x1c1fb20, 0xc4203d2880)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).finalizeRow(0xc4206dea88, 0x2186a40, 0xc420d104c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:1146 +0x8f8
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc4206dea88, 0x2186a40, 0xc420d104c0, 0x1, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:916 +0x183
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRowDecoded(0xc4206dea88, 0x2186a40, 0xc420d104c0, 0xc421b0c070, 0xc421b0c000, 0x0, 0x0, 0xc421906580, 0x16f3493, 0xc421b0c000)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:930 +0x5a
github.com/cockroachdb/cockroach/pkg/sql.(*scanNode).Next(0xc4206de900, 0x2186a40, 0xc420d104c0, 0xc421b0c070, 0xc421b0c000, 0x217da80, 0xc4204bef20, 0xc420d104c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/scan.go:190 +0x75
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).Next(0xc4204bef20, 0x2186a40, 0xc420d104c0, 0xc421b0c070, 0xc421b0c000, 0xc420d104c0, 0x7eb44d, 0xc420e56000)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:338 +0x60
github.com/cockroachdb/cockroach/pkg/sql.(*deleteNode).Next(0xc4211396c0, 0x2186a40, 0xc420d104c0, 0xc421b0c070, 0xc421b0c000, 0x1dacea0, 0xc421139601, 0x2ad81d43ea38)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/delete.go:167 +0xaa
github.com/cockroachdb/cockroach/pkg/sql.forEachRow(0x2186a40, 0xc420d104c0, 0xc421b0c070, 0xc421b0c000, 0x217d540, 0xc4211396c0, 0xc4219066f0, 0xc421b0c000, 0x217d540)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2016 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.countRowsAffected(0x2186a40, 0xc420d104c0, 0xc421b0c070, 0xc421b0c000, 0x217d540, 0xc4211396c0, 0x0, 0x344795d8, 0xed2206244)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2040 +0xd7
github.com/cockroachdb/cockroach/pkg/sql.(*planner).exec(0xc421b0c000, 0x2186a40, 0xc420d104c0, 0x1f4597f, 0x3c, 0xc421b82720, 0x2, 0x2, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:453 +0x344
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).ExecuteStatementInTransaction(0xc4219069f8, 0x2186a40, 0xc420d104c0, 0x1ee10eb, 0x9, 0xc421139520, 0x1f4597f, 0x3c, 0xc421b82720, 0x2, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:51 +0x161
github.com/cockroachdb/cockroach/pkg/sql.(*DropUserNode).startExec(0xc42164dd60, 0x2186a40, 0xc420d104c0, 0xc420e8d3e0, 0xc420e8d370, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/drop_user.go:180 +0xc7c
```

Working theory: the migration added the column but the backfill hasn't completed yet by the time the test issues the command.

**Comment by vivekmenezes** [comment]
probably related to https://github.com/cockroachdb/cockroach/issues/22386

**Comment by knz** [comment]
yeah it's clearly a dup. Thanks
