### ISSUE TITLE
teamcity: failed tests on master: acceptance/TestInitModeBootstrapNodeZero, acceptance/TestGossipRestart

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#23380]
The following tests appear to have failed:

[#542653](https://teamcity.cockroachdb.com/viewLog.html?buildId=542653):

```
--- FAIL: acceptance/TestGossipRestart: TestGossipRestartFirstNodeNeedsIncoming: TestInitModeBootstrapNodeZero/runMode=docker (0.000s)
Test ended in panic.

------- Stdout: -------
panic: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:284: applying cgroup configuration for process caused \"failed to write 29807 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/25e9cfb1781ecb26b9aea3123094859933f006f7f30580b7567014a65bd93573/cgroup.procs: invalid argument\""

goroutine 1466 [running]:
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.maybePanic(0x1f87dc0, 0xc420299df0)
	/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/docker.go:245 +0x4a
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*DockerCluster).startNode(0xc420b78200, 0x1fa6460, 0xc4200420c0, 0xc4207b37a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/dockercluster.go:516 +0x720
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*DockerCluster).Start.func1(0xc420b78200, 0x1fa6460, 0xc4200420c0, 0xc4204ac220, 0xc4207b37a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/dockercluster.go:693 +0x49
created by github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*DockerCluster).Start
	/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/dockercluster.go:692 +0x41e
--- FAIL: acceptance/TestInitModeBootstrapNodeZero (0.000s)
Test ended in panic.

--- FAIL: acceptance/TestGossipRestart: TestGossipRestartFirstNodeNeedsIncoming: TestInitModeBootstrapNodeZero/runMode=docker (0.000s)
Test ended in panic.

------- Stdout: -------
panic: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:284: applying cgroup configuration for process caused \"failed to write 29807 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/25e9cfb1781ecb26b9aea3123094859933f006f7f30580b7567014a65bd93573/cgroup.procs: invalid argument\""

goroutine 1466 [running]:
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.maybePanic(0x1f87dc0, 0xc420299df0)
	/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/docker.go:245 +0x4a
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*DockerCluster).startNode(0xc420b78200, 0x1fa6460, 0xc4200420c0, 0xc4207b37a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/dockercluster.go:516 +0x720
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*DockerCluster).Start.func1(0xc420b78200, 0x1fa6460, 0xc4200420c0, 0xc4204ac220, 0xc4207b37a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/dockercluster.go:693 +0x49
created by github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*DockerCluster).Start
	/go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/dockercluster.go:692 +0x41e
--- FAIL: acceptance/TestInitModeBootstrapNodeZero (0.000s)
Test ended in panic.


```

Please assign, take a look and update the issue accordingly.

**Comment by benesch** [comment]
Testing the issue poster.
