### ISSUE TITLE
build: broken `master` builds don't post issues any more

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#23447]
https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_UnitTests&branch_Cockroach=%3Cdefault%3E&tab=buildTypeStatusDiv

**Comment by tschottdorf** [comment]
[02:38:46]Step 2/3: Post failures to GitHub (Command Line) (3s)
[02:38:46]Starting: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/build/teamcity-post-failures.py
[02:38:46]in directory: /home/agent/work/.go/src/github.com/cockroachdb/cockroach
[02:38:49]Traceback (most recent call last):
[02:38:49]  File "/home/agent/work/.go/src/github.com/cockroachdb/cockroach/build/teamcity-post-failures.py", line 139, in <module>
[02:38:49]    issue = create_issue(build_id, failed_tests)
[02:38:49]  File "/home/agent/work/.go/src/github.com/cockroachdb/cockroach/build/teamcity-post-failures.py", line 114, in create_issue
[02:38:49]    'milestone': get_probable_milestone(),
[02:38:49]  File "/home/agent/work/.go/src/github.com/cockroachdb/cockroach/build/teamcity-post-failures.py", line 79, in get_probable_milestone
[02:38:49]    milestones = json.load(res)
[02:38:49]  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
[02:38:49]    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
[02:38:49]  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
[02:38:49]    s.__class__.__name__))
[02:38:49]TypeError: the JSON object must be str, not 'bytes'
[02:38:49]Process exited with code 1
[02:38:49]Process exited with code 1
[02:38:49]Step Post failures to GitHub (Command Line) failed

**Comment by benesch** [comment]
Urgh, thanks. Looks like a bytes/unicode issue.
