### ISSUE TITLE
distsqlrun: panic in newSortAllProcessor

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#23505]
```
[16:11:2]% make testlogic FILES=select TESTFLAGS='-verbosity=3'                                                                                                                                                                                                       jordan@Termato:~/repo/src/github.com/cockroachdb/cockroach on master -> origin/master
GOPATH set to /Users/jordan/repo
Running make with -j8
cd pkg/sql/logictest && ./logictest.test -test.run "Test(CCL)?Logic//^select$/" -test.timeout 4m -verbosity=3
I180306 21:11:20.318839 1 rand.go:74  Random seed: 3760204094961506845
--- done: testdata/logic_test/select with config default: 103 tests, 0 failures
--- done: testdata/logic_test/select with config parallel-stmts: 103 tests, 0 failures
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4573266]

goroutine 2184 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.contextBottomTag(0x0, 0x0, 0x584baa0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/log_context.go:45 +0x26
github.com/cockroachdb/cockroach/pkg/util/log.contextLogTags(0x0, 0x0, 0xc421c18e28, 0x0, 0x8, 0xc4221dcee8, 0x452cc90, 0xc4201a6b80)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/log_context.go:55 +0x39
github.com/cockroachdb/cockroach/pkg/util/log.formatTags(0x0, 0x0, 0xc421c18dc0, 0x453301a)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:109 +0x66
github.com/cockroachdb/cockroach/pkg/util/log.MakeMessage(0x0, 0x0, 0x5a2b983, 0x2a, 0xc4221dd200, 0x3, 0x3, 0xf, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:127 +0x58
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x0, 0x0, 0x1, 0x3, 0x5a2b983, 0x2a, 0xc4221dd200, 0x3, 0x3)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:142 +0xc9
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x0, 0x0, 0x2, 0xc400000001, 0x5a2b983, 0x2a, 0xc4221dd200, 0x3, 0x3)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:55 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.InfofDepth(0x0, 0x0, 0x1, 0x5a2b983, 0x2a, 0xc4221dd200, 0x3, 0x3)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:90 +0x89
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Start(0xc421a2dc20, 0x0, 0x0, 0xc421a2db80, 0x0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:341 +0x225
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newSortAllProcessor(0xc420ec5680, 0xc4203a8200, 0x5c9ca20)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:150 +0x309
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newSorter(0xc420652580, 0xc4203a8200, 0x5c9ca20, 0xc4219dd500, 0xc4219dba68, 0x5c844e0, 0xc420652840, 0x1, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:87 +0xaf
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newProcessor(0xc420652580, 0xc4219db9f0, 0xc4219dba68, 0xc421c04480, 0x1, 0x1, 0xc421c044a0, 0x1, 0x1, 0x5c846a0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:609 +0x1286
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).makeProcessor(0xc420652580, 0xc4219db9d8, 0xc421c04480, 0x1, 0x1, 0x5c84601, 0xc4219dd500, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:296 +0x4d8
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).setup(0xc420652580, 0x5c9bc20, 0xc420e93470, 0xc4219e05e8, 0x8, 0x2)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:371 +0xba5
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ServerImpl).setupFlow(0xc4211ff040, 0x5c9bc20, 0xc420e93470, 0x0, 0x0, 0xc4219e04e0, 0x0, 0x0, 0xc421543640, 0x4013883, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/server.go:362 +0xa70
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ServerImpl).SetupFlow(0xc4211ff040, 0x5c9bc20, 0xc421ba13b0, 0xc4219e04e0, 0xc4211ff040, 0xc420c36210, 0xc420b3f400)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/server.go:428 +0xda
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun._DistSQL_SetupFlow_Handler.func1(0x5c9bc20, 0xc421ba13b0, 0x58dc880, 0xc4219e04e0, 0x58dc880, 0xc4219e04e0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/api.pb.go:362 +0x86
github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x5c9bc20, 0xc421ba13b0, 0x58dc880, 0xc4219e04e0, 0xc4203a8260, 0xc4203a8360, 0x0, 0x0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:48 +0x9ea
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func1(0x5c9bc20, 0xc421ba13b0, 0x58dc880, 0xc4219e04e0, 0xc4203a8260, 0xc4203a8360, 0xc421167a40, 0x4015a38, 0x70, 0x5970640)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:165 +0xb0
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun._DistSQL_SetupFlow_Handler(0x59911c0, 0xc4211ff040, 0x5c9bc20, 0xc421ba13b0, 0xc420e06150, 0xc4202ea8e0, 0x0, 0x0, 0x19, 0xc421167b00)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/api.pb.go:364 +0x167
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420dfc9a0, 0x5caa6e0, 0xc420887c80, 0xc421c84780, 0xc4206d6930, 0x68c7ba0, 0x0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x8a3
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420dfc9a0, 0x5caa6e0, 0xc420887c80, 0xc421c84780, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1143 +0x12f1
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4203d4240, 0xc420dfc9a0, 0x5caa6e0, 0xc420887c80, 0xc421c84780)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:636 +0xa1
make: *** [testlogic] Error 2
```

**Comment by jordanlewis** [comment]
@arjunravinarayan matching you based on `sort`, but feel free to reassign.

**Comment by arjunravinarayan** [comment]
The problem is that the sorter starts a memory monitor with
`		limitedMon.Start(s.flowCtx.Ctx, s.flowCtx.EvalCtx.Mon, mon.BoundAccount{})`

In logic tests, `s.flowCtx.Ctx` is nil. Setting a nonzero verbosity flag triggers a `logWithContext` call, and that panics.

**Comment by arjunravinarayan** [comment]
What's wrong with running all the logic tests with `verbosity=10` in our nightly CI? That would catch all of these.

**Comment by jordanlewis** [comment]
Nothing! I think we should do that for sure. #23503.
