### ISSUE TITLE
sql: panic with nullable repeated projections in full outer joins

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#23609]
This query causes the database to crash:

`SELECT *, pg_typeof(column1) FROM (SELECT * FROM (VALUES (NULL, NULL)) NATURAL FULL OUTER JOIN (SELECT * FROM (VALUES (1, 1))));`

There is no error message. The server process ends, and the client says "connection lost".

**Comment by jordanlewis** [comment]
Thanks for the report! This usually means the server has panicked - you should be able to find that message in the server logs.

I went ahead and reproduced it locally. Here's the panic:

```
panic: invalid datum type given: int, expected unknown

goroutine 238 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6097940, 0xc425bca080, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:140 +0x23f
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcOutputHelper).ProcessRow(0xc425ef8400, 0x6077aa0, 0xc425ede740, 0xc425cccc30, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:330 +0x6c6
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*noopProcessor).Next(0xc425ef8400, 0x0, 0x0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:543 +0xca
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x6077aa0, 0xc425ede740, 0x6078860, 0xc425ef8400, 0x605e0e0, 0xc425ebc900)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:146 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*noopProcessor).Run(0xc425ef8400, 0xc42001ddf8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:499 +0x6b
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:466 +0x38b
```

**Comment by rytaft** [comment]
Thanks! Good to know - I see that message in my log too.

**Comment by jordanlewis** [comment]
This panic has nothing to do with `pg_typeof`, unfortunately. It happens any time there's a repeated projection that has an operator on it:

```
root@:26257/> SELECT column1 FROM (SELECT * FROM (VALUES (NULL, NULL)) NATURAL FULL OUTER JOIN (SELECT * FROM (VALUES (1, 1))));
+---------+
| column1 |
+---------+
|       1 |
| NULL    |
+---------+
(2 rows)

Time: 1.336717ms

root@:26257/> SELECT column1, column1 + 1 FROM (SELECT * FROM (VALUES (NULL, NULL)) NATURAL FULL OUTER JOIN (SELECT * FROM (VALUES (1, 1))));
driver: bad connection
warning: connection lost!
```

**Comment by jordanlewis** [comment]
Interestingly, Postgres won't even plan this query:

```
tpcc=# SELECT column1, column1 + 1 FROM (SELECT * FROM (VALUES (NULL, NULL)) as t NATURAL FULL OUTER JOIN (SELECT * FROM (VALUES (1, 1)) as u) as v) as w;
ERROR:  42804: JOIN/USING types text and integer cannot be matched
LOCATION:  select_common_type, parse_coerce.c:1284
Time: 5.691 ms
tpcc=# SELECT column1, column1 + 1 FROM (SELECT * FROM (VALUES (2,2)) as t NATURAL FULL OUTER JOIN (SELECT * FROM (VALUES (1, 1)) as u) as v) as w;
 column1 | ?column?
---------+----------
       2 |        3
       1 |        2
(2 rows)

Time: 23.471 ms
```

**Comment by jordanlewis** [comment]
If I cast the nulls to `int`, it works:

```
tpcc=# SELECT column1, column1 + 1 FROM (SELECT * FROM (VALUES (NULL::int, NULL::int)) as t NATURAL FULL OUTER JOIN (SELECT * FROM (VALUES (1, 1)) as u) as v) as w;
 column1 | ?column?
---------+----------
         |
       1 |        2
(2 rows)

Time: 5.684 ms
```

Interestingly, this seems to expose another bug in our `FULL OUTER JOIN` handling...

root@:26257/> SELECT column1+1 FROM (SELECT * FROM (VALUES (NULL, NULL)) NATURAL FULL OUTER JOIN (SELECT * FROM (VALUES (1, 1))));
+-------------+
| column1 + 1 |
+-------------+
| NULL        |
| NULL        |
+-------------+
(2 rows)

Time: 1.244656ms

One of the values should be `2`, not `NULL`.

**Comment by jordanlewis** [comment]
Hmm, although neither of these particular bugs reproduces on actual tables. This seems to be a problem with either subqueries or the values clauses.

```
root@:26257/test> create table a (a int, b int);
CREATE TABLE
root@:26257/test> create table b (a int, b int);
CREATE TABLE
root@:26257/test> insert into a values(null,null);
INSERT 1
root@:26257/test> insert into b values(1,1);
INSERT 1
root@:26257/test> select a,a+1 from a natural full outer join b;
+------+-------+
|  a   | a + 1 |
+------+-------+
| NULL |  NULL |
|    1 |     2 |
+------+-------+
(2 rows)
```

**Comment by jordanlewis** [comment]
@RaduBerinde any chance you can get to this this week?

**Comment by RaduBerinde** [comment]
I'll try.

I believe the problem has to do with mismatched types (`Unknown` vs `Int`) on the USING columns. That explains why the last example works.

**Comment by RaduBerinde** [comment]
Easy fix, I'll have a PR tomorrow.

> Interestingly, this seems to expose another bug in our FULL OUTER JOIN handling [..] One of the values should be 2, not NULL.

It is actually the same underlying cause - we type `column1` as null which makes `column1+1` be treated as a NULL constant
