### ISSUE TITLE
Test timeout on `TestStoreRangeMergeNonConsecutive`

### ISSUE THREAD

**Issue by thundercw** [cockroachdb/cockroach#2363]
```
E0904 22:35:39.316859 8476 storage/store.go:1581  storage/store.go:1580: got committed raft command for 3 but have no range with that ID: {RangeID:3 OriginNodeID:100000001 Cmd:{Get:<nil> Put:<nil> ConditionalPut:<nil> Increment:<nil> Delete:<nil> DeleteRange:<nil> Scan:<nil> EndTransaction:<nil> RangeLookup:<nil> HeartbeatTxn:<nil> GC:<nil> PushTxn:header:<timestamp:<wall_time:0 logical:37 > cmd_id:<wall_time:0 random:0 > key:"b" replica:<node_id:1 store_id:1 replica_id:1 > range_id:3 txn:<name:"storage/replica_command.go:1098 (*Replica).AdminSplit" key:"b" id:"M#\262\314\251\316G\364\261*v\220\262o4H" priority:692384610 isolation:SERIALIZABLE status:PENDING epoch:0 timestamp:<wall_time:0 logical:37 > orig_timestamp:<wall_time:0 logical:37 > max_timestamp:<wall_time:0 logical:37 > certain_nodes:<> Writing:true > read_consistency:CONSISTENT > pushee_txn:<name:"storage/replica_command.go:1098 (*Replica).AdminSplit" key:"b" id:"M#\262\314\251\316G\364\261*v\220\262o4H" priority:692384610 isolation:SERIALIZABLE status:PENDING epoch:0 timestamp:<wall_time:0 logical:37 > orig_timestamp:<wall_time:0 logical:37 > max_timestamp:<wall_time:0 logical:37 > certain_nodes:<> Writing:true > now:<wall_time:0 logical:68 > push_type:CLEANUP_TXN range_lookup:false  ResolveIntent:<nil> ResolveIntentRange:<nil> MergeResponse:<nil> TruncateLog:<nil> Lease:<nil> ReverseScan:<nil> Batch:<nil>}}
panic: test timed out after 30s

goroutine 1 [chan receive]:
testing.RunTests(0x12196c0, 0x174d0a0, 0xba, 0xba, 0x7dff01)
        /usr/local/go/src/testing/testing.go:561 +0x8ad
testing.(*M).Run(0xc820183ef8, 0x7e04b2)
        /usr/local/go/src/testing/testing.go:493 +0x70
github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck(0xc820183ef8)
        /home/thunder/go/path/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x21
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc820183ef8)
        /home/thunder/go/path/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x21
main.main()
        github.com/cockroachdb/cockroach/storage/_test/_testmain.go:432 +0x113

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 2818 [semacquire]:
sync.runtime_Syncsemacquire(0xc8207c20d0)
        /usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8207c20c0)
        /usr/local/go/src/sync/cond.go:62 +0x9b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Quiesce(0xc8200d82a0)
        /home/thunder/go/path/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:231 +0x1da
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc8200d82a0)
        /home/thunder/go/path/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:191 +0x25
github.com/cockroachdb/cockroach/storage_test.TestStoreRangeMergeNonConsecutive(0xc820086000)
        /home/thunder/go/path/src/github.com/cockroachdb/cockroach/storage/client_merge_test.go:271 +0x173e
testing.tRunner(0xc820086000, 0x174dee0)
        /usr/local/go/src/testing/testing.go:455 +0x98
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:560 +0x86d
```
The test script (come from  @tschottdorf :) )
```
make test TESTFLAGS=-c PKG=./storage &&
while [ $? -eq 0 ]; do echo -n . && ./storage.test  -test.run TestStoreRangeMergeNonConsecutive -test.timeout 30s --verbosity=1 &> boom; done;
less boom
```

**Comment by bdarnell** [comment]
Part of the problem with this test is that it predates ChangeReplicas and multiTestContext, so it does a lot of dodgy things to simulate a scenario with non-adjacent replicas. I have a branch in which I have updated the test to use ChangeReplicas to create this scenario in a more realistic way. This fixes some of the issues, but I still see deadlocks at shutdown, and all my attempts to fix this have been futile.  A big part of the problem is that `multiTestContext.Send` isn't quite the same as `DistSender`, so rather than improve `multiTestContext.Send` I'm going to table this issue until #2406 is in and we can convert `multiTestContext` to use a `DistSender`.
