### ISSUE TITLE
sql: panic in lastval

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#23808]
Found by `sqlsmith`.

```
SELECT CAST(NULLIF(ref_0.s_order_cnt, ref_0.s_i_id) AS INT8) AS c0 FROM public.stock AS ref_0 WHERE pg_catalog.set_masklen(CAST(pg_catalog.inet_client_addr() AS INET), CAST(pg_catalog.lastval() AS INT8)) > pg_catalog.inet_server_addr() LIMIT 65
```

```
I180313 19:10:14.144817 439 sql/conn_executor.go:1805  [n1,client=127.0.0.1:55225,user=root] [Open pos:105657] executing Sync
I180313 19:10:14.145112 439 sql/conn_executor.go:1805  [n1,client=127.0.0.1:55225,user=root] [Open pos:105658] executing ExecStmt: SELECT CAST(NULLIF(ref_0.s_order_cnt, ref_0.s_i_id) AS INT8) AS c0 FROM public.stock AS ref_0 WHERE pg_catalog.set_masklen(CAST(pg_catalog.inet_client_addr() AS INET), CAST(pg_catalog.lastval() AS INT8)) > pg_catalog.inet_server_addr() LIMIT 65
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x480a637]

goroutine 23714 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sessiondata.(*SequenceState).GetLastValue(0x0, 0x0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sessiondata/sequence_state.go:63 +0x37
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func76(0xc433617600, 0x7265ed0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc435424154)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:1087 +0x36
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval(0xc429425b60, 0xc433617600, 0xc429425b60, 0x60c3060, 0xc429425b60, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3307 +0x314
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval(0xc429425bc0, 0xc433617600, 0xc429425bc0, 0x60c3060, 0xc429425bc0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3297 +0x13a
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr).Eval(0xc425c02120, 0xc433617600, 0x0, 0x0, 0xc426195350, 0x4c705e5)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3256 +0x7d
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.RunFilter(0x60c2880, 0xc425c02120, 0xc433617600, 0x0, 0x1, 0xc426195350)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/expr_filter.go:26 +0x48
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*exprHelper).evalFilter(0xc42a388e00, 0xc433977c00, 0x11, 0x11, 0xabbd, 0xc435424160, 0x142)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/expr.go:153 +0x10c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcOutputHelper).ProcessRow(0xc42758f500, 0x60b6ca0, 0xc42c1dec00, 0xc433977c00, 0x11, 0x11, 0xc42758f8d0, 0xc42758f940, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:304 +0x8a7
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Next(0xc42758f500, 0xc42080a790, 0x47735c6, 0x60b6be0, 0xc4270828c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:207 +0x2fc
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x60b6be0, 0xc425d0ce80, 0x60b7b20, 0xc42758f500, 0x609d1a0, 0xc429711680)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:135 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Run(0xc42758f500, 0xc425269df8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:132 +0x6b
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:466 +0x38b
```

**Comment by vilterp** [comment]
Fairly swamped with UI work so assigning back to you @jordanlewis. Guessing from the topmost line in the traceback, looks like something in the session state (or the session state itself) is nil: https://github.com/cockroachdb/cockroach/blob/d157212a3a5113b63000c16a258af6b04033c76b/pkg/sql/sessiondata/sequence_state.go#L63

@andreimatei refactored this after me and may have more thoughts if it's not obvious with a little digging.

**Comment by jordanlewis** [comment]
Simpler repro:

```
CREATE TABLE a (a INT PRIMARY KEY);
INSERT INTO a VALUES(1);
SELECT lastval() FROM a;
```

**Comment by vilterp** [comment]
Added this repro as a logic test in the PR above (#23815). A couple things to note:

- It only fails in the distsql configuration. Maybe the `SequenceState` gets initialized differently in the distsql context? I'm not very familiar with how this works.
- It only fails if there is a `FROM` clause in the SELECT with `lastval`; i.e. `SELECT lastval()` by itself is fine.
- Aside: The `FROM` clause is pretty meaningless; it merely has the effect of calling `lastval()` for each row in the table. `lastval` will always return the same thing, since it is session-scoped. Of course, this should still not cause it to panic.

**Comment by andreimatei** [comment]
What's surely going on here is that the `SequenceState` is not correctly initialized on anything but the gateway node. When it gets run through DistSQL on a different node, it crashes. The difference between `SELECT lastval()` and `SELECT lastval() FROM a` is that only the former runs on other nodes.

I'll take a look.

**Comment by vilterp** [comment]
That sounds right; thanks Andrei! Can we just force anything that reads or writes to `SessionState` (i.e. lastval, nextval, and currval) to run on the gateway node? Doesn't seem to make sense to propagate that data out to other nodes with distsql.
