### ISSUE TITLE
the Flush command isn't handled in connExecutor.updateTxnRewindPosMaybe()

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#24101]
https://sentry.io/cockroach-labs/cockroachdb/issues/499638124/

```
*log.safeError: conn_executor.go:521: panic while executing 0 statements: : caused by <redacted>
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 489, in func2
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 1167, in updateTxnRewindPosMaybe
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 1089, in run
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 491, in ServeConn
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go", line 260, in func3
...
(2 additional frame(s) were not displayed)

conn_executor.go:521: panic while executing 0 statements: : caused by <redacted>
```

**Comment by ryanckoch** [comment]
Would this be the cause of the following (on v2.0-beta.20180319)?
```
 *
 * ERROR: [n1,client=172.20.0.1:56098,user=root] a SQL panic has occurred while executing "": unsupported cmd: sql.Flush
 *
 *
 * ERROR: [n1,client=172.20.0.1:56098,user=root] a panic has occurred!
 *
 panic while executing 0 statements: ; caused by unsupported cmd: sql.Flush

 goroutine 344 [running]:
 runtime/debug.Stack(0x25e99a0, 0xc4258621c0, 0x3)
 	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
 github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x25e99a0, 0xc4258621c0, 0xc4206f0000, 0x21f3840, 0xc425857e60, 0x1)
 	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:192 +0xa5
 github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc42587a000, 0x25e99a0, 0xc4258621c0, 0x1fc0a80, 0xc4203c89b0)
 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:521 +0x2d5
 github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2(0xc42587a000, 0x25e99a0, 0xc4258621c0)
 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:489 +0x61
 panic(0x1fc0a80, 0xc4203c89b0)
 	/usr/local/go/src/runtime/panic.go:505 +0x229
 github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).updateTxnRewindPosMaybe(0xc42587a000, 0x25e99a0, 0xc425021500, 0x25d4120, 0x39e3fc8, 0x20, 0x2, 0x0, 0x0, 0x0, ...)
 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1167 +0xa9c
 github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc42587a000, 0x25e99a0, 0xc4258621c0, 0x0, 0x0)
 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1089 +0x2b5
 github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420308000, 0x25e99a0, 0xc4258621c0, 0xc425875017, 0x7, 0xc425875009, 0x4, 0x0, 0x0, 0x25d2e20, ...)
 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:491 +0xf9e
 github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc420308000, 0x25e99a0, 0xc4258621c0, 0xc424f228c0, 0x5400, 0x15000, 0xc420773810, 0xc4203ad880, 0xc420443080, 0xc4203ad870)
 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:260 +0xfc
 created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:259 +0xf14

 *
 * ERROR: [n1,client=172.20.0.1:56098,user=root] Reported as error e9440d78416f4d1caaa78d508e27be7b
 *
```
Testing using postgrex_cdb with ecto. Is caused by `mix ecto.migrate`

**Comment by andreimatei** [comment]
> Would this be the cause of the following (on v2.0-beta.20180319)?

Yes. I've sent out a fix in https://github.com/cockroachdb/cockroach/pull/24119
Once that merges, you can build a binary from head or wait until the next beta release or the one after that.
Sorry for the trouble.

**Comment by andreimatei** [comment]
@ryanckoch the fix will be in the beta expected to go out next Monday

**Comment by ryanckoch** [comment]
Awesome thanks @andreimatei !

Sorry for the barage of bug reports. I figured it may have been related as I saw this issue open not long after I hit the issue.
