### ISSUE TITLE
sql/opt: panic in buildTable

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#24171]
Found with sqlsmith (#21852). @andy-kimball I know this is still under development so do let me know if this is irritating - I'm trying to get `sqlsmith` ready for nightly runs and its digging this stuff up in the meantime.

```
root@:26257/tpcc> SELECT * FROM  a WHERE CAST(COALESCE((SELECT 'a' FROM crdb_internal.zones LIMIT 1 OFFSET 5), (SELECT 'b' FROM pg_catalog.pg_trigger)) AS BYTEA) <= 'a';
driver: bad connection
warning: connection lost!
```

```
E180323 03:54:27.675971 253 sql/conn_executor.go:514  [n1,client=127.0.0.1:62227,user=root] a SQL panic has occurred while executing "SELECT * FROM a WHERE CAST(COALESCE((SELECT 'a' FROM crdb_internal.zones LIMIT 1 OFFSET 5), (SELECT 'b' FROM pg_catalog.pg_trigger)) AS BYTEA) <= '\\x61'": runtime error: invalid memory address or nil pointer dereference
I180323 03:54:27.676003 253 sql/conn_executor.go:1816  [n1,client=127.0.0.1:62227,user=root] finishing connExecutor
E180323 03:54:27.676167 253 util/log/crash_reporting.go:185  [n1,client=127.0.0.1:62227,user=root] a panic has occurred!
E180323 03:54:27.679151 253 util/log/crash_reporting.go:451  [n1,client=127.0.0.1:62227,user=root] Reported as error 20099dd70d554ed9aba636d3e7b993a0
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: panic while executing 1 statements: SELECT * FROM _ WHERE CAST(COALESCE((SELECT _ FROM _._ LIMIT _ OFFSET _), (SELECT _ FROM _._)) AS BYTEA) <= _; caused by runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5062210]

goroutine 253 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc4207b7000, 0x606de00, 0xc420a24b40, 0x5aed6c0, 0x7197130)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:528 +0x365
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2(0xc4207b7000, 0x606de00, 0xc420a24b40)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:489 +0x61
panic(0x5aed6c0, 0x7197130)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*ScalarBuilder).Build.func1(0xc424cfe030)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:416 +0xc7
panic(0x5aed6c0, 0x7197130)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildTable(0xc42505d400, 0x60555c0, 0xc4204d1dc0, 0xc42505d468, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:54 +0x190
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildTable(0xc42505d400, 0x60552c0, 0xc42601c3c0, 0xc42505d468, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:40 +0x33d
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFrom(0xc42505d400, 0xc425feede0, 0x0, 0xc42505d468, 0x45a8adf, 0xc4202f64a0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:261 +0xc4
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause(0xc42505d400, 0xc42503fe00, 0xc42505d468, 0xc425f59e10, 0x9)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:212 +0x87
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc42505d400, 0xc42503fe00, 0xc42505d468, 0xc424cfd7a0, 0x4055ecd)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:167 +0x1a2
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc42505d400, 0x6070240, 0xc420646c18, 0xc42505d468, 0xc420646c18, 0x10010cfc0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:164 +0x8f
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).replaceSubquery(0xc42505d468, 0xc425feee10, 0x0, 0xffffffffffffffff, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:522 +0x97
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).VisitPre(0xc42505d468, 0x6071000, 0xc425feee10, 0x4005077, 0x40116ad, 0xc424c94000)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:505 +0x113
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr(0x6054ec0, 0xc42505d468, 0x6071000, 0xc425feee10, 0x7233be0, 0xc424cfda00, 0x4012aa8)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:580 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*CoalesceExpr).Walk(0xc426028e80, 0x6054ec0, 0xc42505d468, 0x1, 0x606f300)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:162 +0xb7
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr(0x6054ec0, 0xc42505d468, 0x606f300, 0xc426028e80, 0x7233be0, 0x7233be0, 0x1)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:583 +0x15a
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).resolveType(0xc42505d468, 0x606f300, 0xc426028e80, 0x607bd80, 0x7233be0, 0x607c140, 0x7233be0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:90 +0x5a
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar(0xc42505d400, 0x6079920, 0xc426028ec0, 0xc42505d468, 0xc426028ec0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:144 +0x92c
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar(0xc42505d400, 0x6079aa0, 0xc4254f3830, 0xc42505d468, 0xc4254f3950)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:159 +0x188c
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*ScalarBuilder).Build(0xc42505d400, 0x6079aa0, 0xc4254f3830, 0xc400000000, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:421 +0x84
github.com/cockroachdb/cockroach/pkg/sql.(*planner).selectIndex(0xc4207b73e8, 0x606dec0, 0xc425fef080, 0xc42603cc00, 0x0, 0x9e0e100, 0xc420646c20, 0x6070201, 0xc420646c20, 0x5bc5701)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_index_selection.go:148 +0x1663
github.com/cockroachdb/cockroach/pkg/sql.expandScanNode(0x606dec0, 0xc425fef080, 0xc4207b73e8, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0xc42603cc00, 0xc425feeea0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:433 +0x10e
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x606dec0, 0xc425fef080, 0xc4207b73e8, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x6064500, 0xc42603cc00, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:271 +0x1dab
github.com/cockroachdb/cockroach/pkg/sql.expandRenderNode(0x606dec0, 0xc425fef080, 0xc4207b73e8, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0xc424f78f20, 0xc42603cc00, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:446 +0x103
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x606dec0, 0xc425fef080, 0xc4207b73e8, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x6064400, 0xc424f78f20, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:274 +0x18d6
github.com/cockroachdb/cockroach/pkg/sql.(*planner).expandPlan(0xc4207b73e8, 0x606dec0, 0xc425fef080, 0x6064400, 0xc424f78f20, 0x6064400, 0xc424f78f20, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:34 +0xce
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optimizePlan(0xc4207b73e8, 0x606dec0, 0xc425fef080, 0x6064400, 0xc424f78f20, 0xc4260405c2, 0x1, 0x1, 0x6064400, 0xc424f78f20, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/optimize.go:47 +0xeb
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc4207b73e8, 0x606dec0, 0xc425fef080, 0x6070700, 0xc42503ff80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:323 +0x2ea
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc4207b7000, 0x606dec0, 0xc425fef080, 0x6070700, 0xc42503ff80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:552 +0xb1b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc4207b7000, 0x606dec0, 0xc425fef080, 0x6070700, 0xc42503ff80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:369 +0xa8c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc4207b7000, 0x606dec0, 0xc425fef080, 0x6070700, 0xc42503ff80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:84 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc4207b7000, 0x606de00, 0xc420a24b40, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:911 +0x1d2b
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4202ee000, 0x606de00, 0xc420a24b40, 0x0, 0x0, 0xc42514a024, 0x4, 0xc42514a015, 0x9, 0x6057340, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:491 +0xf80
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc4202ee000, 0x606de00, 0xc420a24b40, 0xc42032b340, 0x5400, 0x15000, 0xc420b40610, 0xc4202e84e0, 0xc4202dcdb0, 0xc4202e84d0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:260 +0xfc
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:259 +0xf14
```

**Comment by andy-kimball** [comment]
Adding @rytaft, who would be the one to fix.

**Comment by rytaft** [comment]
cc @RaduBerinde. This is happening because the `ScalarBuilder` has a nil `catalog`.

The quick fix to this issue is to just disable subqueries for now by passing them as an unsupported expression.  I've created PR #24185 for this purpose. In the longer term, we'll need to make a few changes to make this work (also outlined in the PR):
- `ScalarBuilder` will need to take a `catalog` argument
- We'll need to update our testing infrastructure to handle subqueries in scalar expressions (`ParseScalarExpr` does not handle subqueries)
- Update the exec builder and index constraints code to handle subqueries

**Comment by RaduBerinde** [comment]
Hm.. I had thought that the current planner replaces subqueries with `sql.subquery` nodes, as per this comment:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/subquery.go#L245

But I don't see `VisitPre` returning a `*subquery` (or `*subquery` implementing Expr..)

@jordanlewis, @knz is this no longer what's going on?  Any way to generically detect at the time of index selection that any`Subquery` node in the filter has been "processed"? Maybe checking `Subquery.Idx`?

**Comment by knz** [comment]
Idx<Len(planner.curplan.subqueryplans) indeed 

RaduBerinde <notifications@github.com> schreef op 23 maart 2018 20:40:04 CET:
>Hm.. I had thought that the current planner replaces subqueries with
>`sql.subquery` nodes, as per this comment:
>https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/subquery.go#L245
>
>But I don't see `VisitPre` returning a `*subquery` (or `*subquery`
>implementing Expr..)
>
>@jordanlewis, @knz is this no longer what's going on?  Any way to
>generically detect at the time of index selection that any`Subquery`
>node in the filter has been "processed"? Maybe checking `Subquery.Idx`?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cockroachdb/cockroach/issues/24171#issuecomment-375777166

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
