### ISSUE TITLE
Problem with inverted indexes (runtime error: index out of range)

### ISSUE THREAD

**Issue by plievone** [cockroachdb/cockroach#24181]
**BUG REPORT**

```
I180323 16:31:50.907686 1 util/log/clog.go:1085  [config] running on machine: MPB
I180323 16:31:50.907686 1 util/log/clog.go:1085  [config] binary: CockroachDB CCL v2.0-beta.20180319 (darwin amd64, built 2018/03/19 18:54:14, go1.10)
```

Single node setup

```
root@:26260/> use test;
SET

Time: 327.303µs

root@:26260/test> CREATE TABLE tbl (key STRING PRIMARY KEY, val JSON, INVERTED INDEX idx (val));
CREATE TABLE

Time: 3.773416ms

root@:26260/test> UPSERT INTO tbl (key, val) VALUES ('key', '{"a":1}');
INSERT 1

Time: 3.821689ms

root@:26260/test> UPSERT INTO tbl (key, val) VALUES ('key', '{"b":1}');
INSERT 1

Time: 1.128678ms

root@:26260/test> UPSERT INTO tbl (key, val) VALUES ('key', '{"a":1, "b":2}');
driver: bad connection
warning: connection lost!
```

Node died:
```
panic while executing 1 statements: UPSERT INTO _(_, _) VALUES (_, _); caused by runtime error: index out of range

goroutine 310 [running]:
runtime/debug.Stack(0x5fa4bc0, 0xc424c41040, 0xc400000003)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x5fa4bc0, 0xc424c41040, 0xc42022e000, 0x5bae8a0, 0xc4290493b0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:192 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc420207000, 0x5fa4bc0, 0xc424c41040, 0x5a38920, 0x7070130)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:521 +0x2d5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2(0xc420207000, 0x5fa4bc0, 0xc424c41040)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:489 +0x61
panic(0x5a38920, 0x7070130)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowUpdater).UpdateRow(0xc4290a43a8, 0x5fa4bc0, 0xc428dca6c0, 0xc4290b2000, 0xc42906c880, 0x2, 0x2, 0xc426467480, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowwriter.go:835 +0x2b0b
github.com/cockroachdb/cockroach/pkg/sql.(*tableUpserter).finalize(0xc4290a4000, 0x5fa4bc0, 0xc428dca6c0, 0x1, 0xc420207300, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go:495 +0x8a0
github.com/cockroachdb/cockroach/pkg/sql.(*upsertNode).internalNext(0xc428b6e240, 0x5fa4bc0, 0xc428dca6c0, 0xc420207450, 0xc4202073e0, 0xc428b6e201, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/upsert.go:317 +0x12e
github.com/cockroachdb/cockroach/pkg/sql.(*upsertNode).startExec(0xc428b6e240, 0x5fa4bc0, 0xc428dca6c0, 0xc420207450, 0xc4202073e0, 0xc42906c601, 0xc428b60ba0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/upsert.go:280 +0x575
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x5cbb0f0, 0x6, 0x5f9b800, 0xc428b6e240, 0xc425126da8, 0xc428b60bb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:475 +0x90
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit.func1(0xc428dca8c0, 0x5cbb0f0, 0x6, 0x5f9b800, 0xc428b6e240)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:90 +0x5f
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc428dca8c0, 0x5f9b800, 0xc428b6e240)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:474 +0x3a8
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x5fa4bc0, 0xc428dca6c0, 0x5f9b800, 0xc428b6e240, 0x5dafbf0, 0x0, 0x0, 0xc429048d80, 0x0, 0x5ba3c40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:53 +0x133
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x5fa4bc0, 0xc428dca6c0, 0xc420207450, 0xc4202073e0, 0x5f9b800, 0xc428b6e240, 0x7e14458, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:480 +0xbf
github.com/cockroachdb/cockroach/pkg/sql.startPlan(0x5fa4bc0, 0xc428dca6c0, 0xc420207450, 0xc4202073e0, 0x5f9b800, 0xc428b6e240, 0x0, 0xc428b61608)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:419 +0x61
github.com/cockroachdb/cockroach/pkg/sql.(*planTop).start(0xc420207658, 0x5fa4bc0, 0xc428dca6c0, 0xc420207450, 0xc4202073e0, 0x4003c2e, 0xc428b61808)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:392 +0xc0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithLocalEngine(0xc420207000, 0x5fa4bc0, 0xc428dca6c0, 0xc4202073e0, 0x2, 0x8f0cff0, 0xc42906e400, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:588 +0x106
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc420207000, 0x5fa4bc0, 0xc428dca6c0, 0x5fa6e40, 0xc42906ba40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:552 +0x909
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc420207000, 0x5fa4bc0, 0xc428dca6c0, 0x5fa6e40, 0xc42906ba40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:342 +0x9c7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc420207000, 0x5fa4bc0, 0xc428dca6c0, 0x5fa6e40, 0xc42906ba40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:83 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc420207000, 0x5fa4bc0, 0xc424c41040, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:910 +0x1cc8
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420265340, 0x5fa4bc0, 0xc424c41040, 0x0, 0x0, 0xc424eac039, 0x4, 0xc424eac02a, 0x9, 0x5f8e080, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:491 +0xf9e
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc420265340, 0x5fa4bc0, 0xc424c41040, 0xc4204dda40, 0x5400, 0x15000, 0xc4207d7a50, 0xc4202d9ba0, 0xc420405ed0, 0xc4202d9b90)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:260 +0xfc
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:259 +0xf14
```

If that specific combination didn't crash, one can fiddle with properties a few times to induce a crash. Also some combination of having only one property in json resulted in `Error: pq: duplicate key value (val)=(NULL) violates unique constraint "idx"`

**Comment by jordanlewis** [comment]
Hi @plievone,

Thanks for the report! These bugs have been fixed and will be present in the next beta release. See #23318 for more details.
