### ISSUE TITLE
upgrade from 1.1.5 to 2.0-beta makes old node think that descriptors are invalid because of priviledges

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#24235]
Start a 1.1.5 node, then start a 2.0-beta node. I believe the 2.0 node runs some migrations that then causes descriptor validation to fail for the 1.1.5 node. The errors can be seen clearly and repeatedly if you restart the 1.1.5 node. 
The error message at 1.1.5 time did not include the error (one of the two places with that error have been fixed in the meantime); I've patched it locally to see what the error is and the answer is: 
```
sql/schema_changer.go:1027 /Table/3/1/23/2/1: received invalid table descriptor (err: no allowed privileges found for system object with ID=23): ...
```

Not sure what consequences this has, but I'm guessing catastrophic.

We have a notion of "backwards incompatible migrations". Maybe one was misclassified?

@mberhault would you happen to know something about this?
cc @benesch

**Comment by mberhault** [comment]
Uh. Not I'm wondering how adding a new system table every worked. The Validate call on the table descriptor ends up doing:
```
		allowedPrivileges, ok := SystemAllowedPrivileges[id]
		if !ok {
			return fmt.Errorf("no allowed privileges found for system object with ID=%d", id)
		}
```

But `SystemAllowedPrivileges` is a hard-coded map, so it will never ever know about a new system table being created through a migration. How do we normally get around this? Do we gate those on version upgrades?

**Comment by andreimatei** [comment]
I don't know anything about anything, but when I briefly looked yesterday I saw that there was a list of "backwards compatible migrations" and presumably a list of backwards in compatible ones.

**Comment by mberhault** [comment]
No, they're all supposed to be backwards compatible, we don't have a concept of backwards incompatible migration (at least not between consecutive versions).

**Comment by mberhault** [comment]
btw: what were the steps to get this error, and where did it occur? If it's a crash, I agree it's bad. Otherwise, it really isn't (eg: I can get this error by just running `select * from system.role_members` against a 1.1.7 node running alonside a 2.0 node).

**Comment by andreimatei** [comment]
As I was telling you, the error is just continuous spam log. Happens after upgrading one node from 1.1.5 to 2.0 in a 2-node cluster.
I see the error for at least 3 tables: locations, members, table_statistics, reported by both schema_changer.go and lease.go.

**Comment by mberhault** [comment]
Ok, so far so good, those three tables were added between 1.1 and 2.0. I'll rerun to see if I can find more details on the code paths that trigger these errors. Any use of those tables by a 1.1 node is supposed to be non-critical.

**Comment by mberhault** [comment]
Replicated error spam by:
1) starting a 1.1.7 node
2) starting a 2.0 node with `--join=<first node>`

One failure occurs inside [SchemaChangeManager::Start](https://github.com/cockroachdb/cockroach/blob/release-1.1/pkg/sql/schema_changer.go#L973):

```
E180327 16:55:44.396154 188 sql/schema_changer.go:1027  [n1] /Table/3/1/23/2/1: received invalid table descriptor: name:"role_members" id:23 parent_id:1 version:1 up_version:false modification_time:<wall_time:0 logical:0 > columns:<name:"role" id:1 type:<semantic_type:STRING width:0 precision:0 visible_type:NONE > nullable:false hidden:false > columns:<name:"member" id:2 type:<semantic_type:STRING width:0 precision:0 visible_type:NONE > nullable:false hidden:false > columns:<name:"isAdmin" id:3 type:<semantic_type:BOOL width:0 precision:0 visible_type:NONE > nullable:false hidden:false > next_column_id:4 families:<name:"primary" id:0 column_names:"role" column_names:"member" column_ids:1 column_ids:2 default_column_id:0 > families:<name:"fam_3_isAdmin" id:3 column_names:"isAdmin" column_ids:3 default_column_id:3 > next_family_id:4 primary_index:<name:"primary" id:1 unique:true column_names:"role" column_names:"member" column_directions:ASC column_directions:ASC column_ids:1 column_ids:2 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 > interleave:<> > indexes:<name:"role_members_role_idx" id:2 unique:false column_names:"role" column_directions:ASC column_ids:1 extra_column_ids:2 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 > interleave:<> > indexes:<name:"role_members_member_idx" id:3 unique:false column_names:"member" column_directions:ASC column_ids:2 extra_column_ids:1 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 > interleave:<> > next_index_id:4 privileges:<users:<user:"admin" privileges:496 > users:<user:"root" privileges:496 > > next_mutation_id:1 format_version:InterleavedFormatVersion state:PUBLIC view_query:"" 
goroutine 188 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x322e800, 0x2a75d9d, 0x15, 0x403)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:872 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x322e7a0, 0xc400000003, 0x2a75d9d, 0x15, 0x403, 0xc420fe1800, 0x691)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:763 +0x608
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f427b1e0bf8, 0xc4202469f0, 0x7f4200000003, 0x2, 0x1ee6178, 0x29, 0xc420c256f8, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:153 +0x28c
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f427b1e0bf8, 0xc4202469f0, 0x1, 0xc400000003, 0x1ee6178, 0x29, 0xc420c256f8, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:54 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Errorf(0x7f427b1e0bf8, 0xc4202469f0, 0x1ee6178, 0x29, 0xc420c256f8, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:122 +0x7e
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x7f427b1e0bf8, 0xc4202469f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1027 +0xb04
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420273710, 0xc4207b0e10, 0xc4202a7340)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0xad
```

The other is in [LeaseManager::RefreshLeases](https://github.com/cockroachdb/cockroach/blob/release-1.1/pkg/sql/lease.go#L1337):

```
E180327 17:05:07.180737 40 sql/lease.go:1370  /Table/3/1/23/2/1: received invalid table descriptor: name:"role_members" id:23 parent_id:1 version:1 up_version:false modification_time:<wall_time:0 logical:0 > columns:<name:"role" id:1 type:<semantic_type:STRING width:0 precision:0 visible_type:NONE > nullable:false hidden:false > columns:<name:"member" id:2 type:<semantic_type:STRING width:0 precision:0 visible_type:NONE > nullable:false hidden:false > columns:<name:"isAdmin" id:3 type:<semantic_type:BOOL width:0 precision:0 visible_type:NONE > nullable:false hidden:false > next_column_id:4 families:<name:"primary" id:0 column_names:"role" column_names:"member" column_ids:1 column_ids:2 default_column_id:0 > families:<name:"fam_3_isAdmin" id:3 column_names:"isAdmin" column_ids:3 default_column_id:3 > next_family_id:4 primary_index:<name:"primary" id:1 unique:true column_names:"role" column_names:"member" column_directions:ASC column_directions:ASC column_ids:1 column_ids:2 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 > interleave:<> > indexes:<name:"role_members_role_idx" id:2 unique:false column_names:"role" column_directions:ASC column_ids:1 extra_column_ids:2 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 > interleave:<> > indexes:<name:"role_members_member_idx" id:3 unique:false column_names:"member" column_directions:ASC column_ids:2 extra_column_ids:1 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 > interleave:<> > next_index_id:4 privileges:<users:<user:"admin" privileges:496 > users:<user:"root" privileges:496 > > next_mutation_id:1 format_version:InterleavedFormatVersion state:PUBLIC view_query:"" 
goroutine 40 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x322e800, 0x2a76357, 0xc, 0x55a)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:872 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x322e7a0, 0xc400000003, 0x2a76357, 0xc, 0x55a, 0xc42112c300, 0x68c)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:763 +0x608
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7ff408c29c80, 0xc42011fe30, 0x7ff400000003, 0x2, 0x1ee6178, 0x29, 0xc420b05db8, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:153 +0x28c
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7ff408c29c80, 0xc42011fe30, 0x1, 0xc400000003, 0x1ee6178, 0x29, 0xc420b05db8, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:54 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Errorf(0x7ff408c29c80, 0xc42011fe30, 0x1ee6178, 0x29, 0xc420b05db8, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:122 +0x7e
github.com/cockroachdb/cockroach/pkg/sql.(*LeaseManager).RefreshLeases.func1(0x7ff408c29c80, 0xc42011fe30)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:1370 +0x4a0
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420266060, 0xc4207b4cf0, 0xc420453380)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0xad
```

Both methods loop over all table descriptors and call `Validate`. Upon failure, the error is logged but the loop continues to the next table descriptor. This seems like the reasonable thing to do in this case: any descriptor that fails to validate will be left alone.

I'll keep running to see if I can catch further errors.

**Comment by mberhault** [comment]
No other errors encountered, and these are benign. Closing for now.
