### ISSUE TITLE
storage: tocommit is out of range

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#24337]
backup2tb crashed in this nightly run: https://teamcity.cockroachdb.com/viewLog.html?buildId=586079&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=buildLog

At 11:40, we see a very concerning raft problem on n10 that brings the node down.

```
E180329 11:40:01.157113 263 util/log/crash_reporting.go:451  [n1,s1] Reported as error a24b491ae75e4888b3ee0f3b35da4a1b
panic: tocommit(26) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost? [recovered]
	panic: tocommit(26) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?

goroutine 263 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42002a240, 0x26120a0, 0xc427505470)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:177 +0x11f
panic(0x1fddd20, 0xc426b888d0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*raftLogger).Panicf(0xc4267fe900, 0x23a90b0, 0x5d, 0xc44b994260, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.go:106 +0xfe
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc430c9b110, 0x1a)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/log.go:191 +0x15c
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc42e1a4400, 0x8, 0x4, 0x1, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1232 +0x54
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.stepFollower(0xc42e1a4400, 0x8, 0x4, 0x1, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1177 +0x44c
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc42e1a4400, 0x8, 0x4, 0x1, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:898 +0x1308
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*RawNode).Step(0xc442924fc0, 0x8, 0x4, 0x1, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:195 +0xdd
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).stepRaftGroup.func1(0xc442924fc0, 0x2612020, 0xc4200400c0, 0x26120a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3329 +0xa8
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc44ac34000, 0x2418800, 0xc42c4e1b88, 0xc42c4e1b70, 0x6fe709)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:607 +0x10f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroup(0xc44ac34000, 0xc42c4e1b88, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:624 +0x88
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).stepRaftGroup(0xc44ac34000, 0xc4568b36c0, 0x2099860, 0x30)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3324 +0x50
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequestWithReplica(0xc420819000, 0x26120a0, 0xc43dbf5a10, 0xc44ac34000, 0xc4568b36c0, 0xc43dbf5a10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3175 +0xeb
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x26120a0, 0xc43dbf5a10, 0xc44ac34000, 0x26120a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3793 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc420819000, 0x26120a0, 0xc43dbf5a10, 0xc4568b36c0, 0xc42c4e1ed0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3121 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc420819000, 0x26120a0, 0xc427505470, 0x706c)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3787 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420b80000, 0x26120a0, 0xc427505470)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:226 +0x21b
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x26120a0, 0xc427505470)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4262f8ec0, 0xc42002a240, 0xc4262f8eb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xad
```

https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/586079:id/20180328-586079/backup2TB/10.logs/cockroach.log

Two minutes later, the SSH connection to n1, the node coordinating the backup, gets OOM killed (!).

```
[11:42:11]	[Step 3/3] 	cluster.go:642,backup.go:52,cluster.go:784,errgroup.go:58: roachprod ssh teamcity-586079-backup2tb:1 -- ./cockroach sql --insecure -e "
[11:42:11]	[Step 3/3] 						BACKUP bank.bank TO 'gs://cockroachdb-backup-testing/teamcity-586079-backup2tb'": signal: killed
```

There's not a whole lot in n1's logs:

```
I180329 11:40:01.353808 1350 storage/store.go:3470  [n1,s1,r349/5:/Table/51/1/470{0456/0-3729}] added to replica GC queue (contacted deleted peer)
W180329 11:40:01.565404 308031 vendor/google.golang.org/grpc/server.go:961  grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
W180329 11:40:01.568787 429 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {teamcity-586079-backup2tb-0010:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W180329 11:40:01.568830 429 vendor/google.golang.org/grpc/clientconn.go:1277  grpc: addrConn.transportMonitor exits due to: context canceled
W180329 11:40:01.674317 848092 vendor/google.golang.org/grpc/server.go:625  grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: EOF"
```

https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/586079:id/20180328-586079/backup2TB/1.logs/cockroach.log

/cc @vilterp

**Comment by benesch** [comment]
@bdarnell, Nathan mentioned you'd be very interested in this.

**Comment by nvanbenschoten** [comment]
This looks just like https://github.com/cockroachdb/cockroach/issues/20764 and like a privately reported issue.

**Comment by benesch** [comment]
Hmm, I might have generated invalid fixtures (!). I can help look into this, @danhhz, since I touched the test last.
