### ISSUE TITLE
workload: partitioning is broken for TPCC

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#24607]
I encountered a panic when attempting to partition a 30 node 
```
panic: Couldn't exec ALTER TABLE history PARTITION BY RANGE (rowid) (
  PARTITION p0 VALUES FROM ('00000000-0000-0000-0000-000000000000') to ('00000000-0000-0000-0000-000000000000'),
  PARTITION p1 VALUES FROM ('00000000-0000-0000-0000-000000000000') to ('00000000-0000-0000-0000-000000000000'),
  PARTITION p2 VALUES FROM ('00000000-0000-0000-0000-000000000000') to ('00000000-0000-0000-0000-000000000000'),
  PARTITION p3 VALUES FROM ('00000000-0000-0000-0000-000000000000') to ('00000000-0000-0000-0000-000000000000'),
  PARTITION p4 VALUES FROM ('00000000-0000-0000-0000-000000000000') to ('00000000-0000-0000-0000-000000000000'),
  PARTITION p5 VALUES FROM ('00000000-0000-0000-0000-000000000000') to ('00000000-0000-0000-0000-000000000000'),
  PARTITION p6 VALUES FROM ('00000000-0000-0000-0000-000000000000') to ('00000000-0000-0000-0000-000000000000'),
  PARTITION p7 VALUES FROM ('00000000-0000-0000-0000-000000000000') to ('00000000-0000-0000-0000-000000000000'),
  PARTITION p8 VALUES FROM ('00000000-0000-0000-0000-000000000000') to ('00000000-0000-0000-0000-000000000000'),
  PARTITION p9 VALUES FROM ('00000000-0000-0000-0000-000000000000') to ('ffffffff-ffff-ffff-ffff-ffffffffffff')
)
: pq: PARTITION p0: empty range: lower bound ('00000000-0000-0000-0000-000000000000') is equal to upper bound ('00000000-0000-0000-0000-000000000000')


goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/workload/tpcc.partitionHistory(0xc42054e640, 0xc420520180, 0xb, 0xb, 0xa)
    /home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/workload/tpcc/partition.go:253 +0xe3d
github.com/cockroachdb/cockroach/pkg/workload/tpcc.partitionTables(0xc42054e640, 0x2710, 0xa)
    /home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/workload/tpcc/partition.go:329 +0x25d
github.com/cockroachdb/cockroach/pkg/workload/tpcc.(*tpcc).Ops(0xc4201d4d80, 0xc420550000, 0x1e, 0x23, 0xc4202c83c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/workload/tpcc/tpcc.go:353 +0xc48
main.runRun(0xcb6a60, 0xc4201d4d80, 0xc420550000, 0x1e, 0x23, 0xbd721b, 0x4, 0xbd721b, 0x4)
    /home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/cmd/workload/run.go:228 +0x26d
main.cmdHelper.func1(0xc420544d80, 0xc420550000, 0x1e, 0x23, 0x4, 0xbd6def)
    /home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/cmd/workload/run.go:127 +0x19e
main.handleErrs.func1(0xc420544d80, 0xc420550000, 0x1e, 0x23)
    /home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/cmd/workload/main.go:41 +0x57
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0xc420544d80, 0xc420545d40, 0x23, 0x24, 0xc420544d80, 0xc420545d40)
    /home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x127bca0, 0x0, 0xbdc19d, 0x9)
    /home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0x127bca0, 0x53, 0xc4200bc058)
    /home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
    /home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/cmd/workload/main.go:31 +0x2d
```

There's something wrong with the UUID usage, which I am investigating now. Will send a fix shortly.

**Comment by jordanlewis** [comment]
This is done, right?

**Comment by arjunravinarayan** [comment]
Yup. The github auto-closing was broken by bors rewriting the merge commit, or something. I messed something up. I'll be sure to include it in the PR description as well in the future.
