### ISSUE TITLE
org.postgresql.util.PSQLException: The fastpath function lo_creat is unknown.

### ISSUE THREAD

**Issue by cristhiank** [cockroachdb/cockroach#24794]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
Build Tag:    v2.0.0
Build Time:   2018/04/03 20:56:09
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10
C Compiler:   gcc 6.3.0
Build SHA-1:  a6b498b7aff14234bcde23107b9e7fa14e6a34a8
Build Type:   release

2. Please describe the issue you observed:

- What did you do?
I'm migrating a Java application to use CockroachDB and I'm getting the following error when trying to save a BLOB using the standard PostgreSQL Driver

`Caused by: org.postgresql.util.PSQLException: The fastpath function lo_creat is unknown.
at org.postgresql.fastpath.Fastpath.getID(Fastpath.java:302)
at org.postgresql.fastpath.Fastpath.fastpath(Fastpath.java:142)
at org.postgresql.fastpath.Fastpath.getInteger(Fastpath.java:154)
at org.postgresql.fastpath.Fastpath.getOID(Fastpath.java:205)`

I found out that lo_creat is a function used by PostgreSQL to create the "Large Object Id (OID)" https://www.postgresql.org/docs/9.2/static/lo-interfaces.html

What's the right way to store CockroachDB BLOBs using Java? Am I doing something wrong?

**Comment by cristhiank** [comment]
Hi! 

Thanks for the answer. 
Actually, the data in that column is not huge, it's max 1mb.
I just fixed it, I am using JPA, and I had the column annotated with [@javax.persistence.Lob](https://docs.oracle.com/javaee/6/api/javax/persistence/Lob.html) and I think that annotation made the driver tried to store it as a Large Object even if the column was BYTEA. I removed the annotation and it's working fine.

Thanks!
