### ISSUE TITLE
workload: seg fault on init tpch

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#24913]
I ran `make bin/workload` followed by `./bin/workload init tpch`, and I got a segfault:

```
Rebeccas-MacBook-Pro:cockroach becca$ ./bin/workload init tpch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x453411e]

goroutine 55 [running]:
github.com/cockroachdb/cockroach/pkg/workload.Tuples.func1(0xf, 0x0, 0x4, 0x4)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/workload/workload.go:163 +0x2e
github.com/cockroachdb/cockroach/pkg/workload.Setup.func1(0x2236a2f300000008, 0x4865818)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/workload/workload.go:318 +0x5a9
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc4203f6080, 0xc4203acb90)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/Users/becca/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

I tried the same thing with tpcc and it loaded successfully.

cc @arjunravinarayan, @danhhz

**Comment by danhhz** [comment]
The error message here is awful, but this is because we don't have a golang port of the tpch data generator. In the meantime, you have to construct an `IMPORT CSV` manually for the data in `gs://cockroach-fixtures/tpch-csv/`
