### ISSUE TITLE
sql: alter big table gave jdbc SQLSTATE(08006)

### ISSUE THREAD

**Issue by achoice** [cockroachdb/cockroach#24931]
## 1. Config
I180419 11:23:45.807579 405 util/log/clog.go:1001  [config] file created at: 2018/04/19 11:23:45
I180419 11:23:45.807579 405 util/log/clog.go:1001  [config] running on machine: crdb5306
I180419 11:23:45.807579 405 util/log/clog.go:1001  [config] binary: CockroachDB CCL v2.0.0 (x86_64-unknown-linux-gnu, built 2018/04/03 20:56:09, go1.10)

### - What did you do?
Ran Liquibase that dropped a column from a "big table".

### - What did you expect to see?
Column dropped, no exceptions.

### - What did you see instead?
Exception after just 5 seconds.
Suspect some low level issue at JDBC or below.
When I looked the column WAS dropped, but Liquibase bugged out before.
_(end result is that Liquibase thinks that the change failed when it did succeed, just took time)_

For future I think we need to test how to configure JDBC when doing long-running schema changes.
(i.e. different timeouts, no need to pool etc. but perhaps also requires some Postgre-JDBC-config)

`2018-04-19T14:00:23.617+02:00 [DEBUG] liquibase [thread=main] [] - classpath:database/wallet-master.xml: 1.0/wallet-init-data.xml::TS-8417::bencam: Executing EXECUTE database command: ALTER TABLE public.TRANSACTION DROP COLUMN TIMESTAMP
2018-04-19T14:00:23.626+02:00 [DEBUG] ttddyy [thread=main] [] - Name:, Connection:5, Time:8, Success:True, Type:Statement, Batch:False, QuerySize:1, BatchSize:0, Query:["ALTER TABLE public.TRANSACTION DROP COLUMN TIMESTAMP"], Params:[]
2018-04-19T14:00:23.626+02:00 [INFO] liquibase [thread=main] [] - classpath:database/wallet-master.xml: 1.0/wallet-init-data.xml::TS-8417::bencam: Column TRANSACTION.TIMESTAMP dropped
2018-04-19T14:00:23.626+02:00 [DEBUG] o.s.j.d.LazyConnectionDataSourceProxy [thread=main] [] - Using existing database connection for operation 'getAutoCommit'
2018-04-19T14:00:23.626+02:00 [DEBUG] o.s.j.d.LazyConnectionDataSourceProxy [thread=main] [] - Using existing database connection for operation 'commit'
2018-04-19T14:00:23.705+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@6948face
2018-04-19T14:00:23.850+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@5b6523dd
2018-04-19T14:00:23.987+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@1fec54aa
2018-04-19T14:00:24.127+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@7b9431e5
2018-04-19T14:00:24.294+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@55a43ad3
2018-04-19T14:00:24.447+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@272d8071
2018-04-19T14:00:24.582+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@5a19d93a
2018-04-19T14:00:24.717+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@58c085
2018-04-19T14:00:24.849+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@745e00ff
2018-04-19T14:00:25.031+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@3fbb380d
2018-04-19T14:00:25.318+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@2b7fe6c9
2018-04-19T14:00:25.574+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@6d6557cb
2018-04-19T14:00:25.820+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@6938fb60
2018-04-19T14:00:26.029+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@fa5dd1a
2018-04-19T14:00:26.156+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@5b382b89
2018-04-19T14:00:26.282+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@1ca4f42a
2018-04-19T14:00:26.420+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@32e9ef25
2018-04-19T14:00:26.542+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@1305b96f
2018-04-19T14:00:26.664+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@9fbbce5
2018-04-19T14:00:26.793+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@32c50c54
2018-04-19T14:00:26.924+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@4fa84dee
2018-04-19T14:00:27.061+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@71584bb5
2018-04-19T14:00:27.192+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@2510cdef
2018-04-19T14:00:27.312+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@3f2dc2b5
2018-04-19T14:00:27.439+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@32e72f83
2018-04-19T14:00:27.587+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@151df89
2018-04-19T14:00:27.721+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@228d15f9
2018-04-19T14:00:27.902+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@73645377
2018-04-19T14:00:28.033+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@7874f1af
2018-04-19T14:00:28.153+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@7756d4bf
2018-04-19T14:00:28.271+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@3dbe2571
2018-04-19T14:00:28.396+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@6c10265a
2018-04-19T14:00:28.529+02:00 [DEBUG] c.z.h.p.HikariPool [thread=ledgerPool connection adder] [] - ledgerPool - Added connection org.postgresql.jdbc.PgConnection@33b64bfe
2018-04-19T14:00:28.634+02:00 [WARN] c.z.h.p.ProxyConnection [thread=main] [] - ledgerPool - Connection org.postgresql.jdbc.PgConnection@44be0077 marked as broken because of SQLSTATE(08006), ErrorCode(0)
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:739)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:760)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:368)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.ttddyy.dsproxy.proxy.ConnectionProxyLogic.invoke(ConnectionProxyLogic.java:87)
	at net.ttddyy.dsproxy.proxy.jdk.ConnectionInvocationHandler.invoke(ConnectionInvocationHandler.java:27)
	at com.sun.proxy.$Proxy64.commit(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:384)
	at com.sun.proxy.$Proxy71.commit(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:236)
	at com.sun.proxy.$Proxy71.commit(Unknown Source)
	at liquibase.database.jvm.JdbcConnection.commit(JdbcConnection.java:123)
	at liquibase.database.AbstractJdbcDatabase.commit(AbstractJdbcDatabase.java:1157)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:593)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
	at liquibase.Liquibase.update(Liquibase.java:214)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1698)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at com.kindred.ledger.Application.main(Application.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:288)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1962)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	... 56 common frames omitted
2018-04-19T14:00:28.637+02:00 [DEBUG] c.z.h.pool.PoolBase [thread=ledgerPool connection closer] [] - ledgerPool - Closing connection org.postgresql.jdbc.PgConnection@44be0077: (connection is broken)
2018-04-19T14:00:28.637+02:00 [DEBUG] o.s.j.d.LazyConnectionDataSourceProxy [thread=main] [] - Using existing database connection for operation 'getAutoCommit'
2018-04-19T14:00:28.638+02:00 [DEBUG] liquibase [thread=main] [] - 1.0/wallet-init-data.xml::TS-8417::bencam: Release Database Lock
2018-04-19T14:00:28.638+02:00 [DEBUG] o.s.j.d.LazyConnectionDataSourceProxy [thread=main] [] - Using existing database connection for operation 'getAutoCommit'
2018-04-19T14:00:28.638+02:00 [INFO] liquibase [thread=main] [] - 1.0/wallet-init-data.xml::TS-8417::bencam: Successfully released change log lock
2018-04-19T14:00:28.638+02:00 [DEBUG] o.s.j.d.LazyConnectionDataSourceProxy [thread=main] [] - Using existing database connection for operation 'getAutoCommit'
2018-04-19T14:00:28.639+02:00 [ERROR] liquibase [thread=main] [] - 1.0/wallet-init-data.xml::TS-8417::bencam: Could not release lock
liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.sql.SQLException: Connection is closed
	at liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:283)
	at liquibase.Liquibase.update(Liquibase.java:218)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1698)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at com.kindred.ledger.Application.main(Application.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.sql.SQLException: Connection is closed
	at liquibase.database.AbstractJdbcDatabase.rollback(AbstractJdbcDatabase.java:1168)
	at liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:266)
	... 28 common frames omitted
Caused by: liquibase.exception.DatabaseException: java.sql.SQLException: Connection is closed
	at liquibase.database.jvm.JdbcConnection.rollback(JdbcConnection.java:340)
	at liquibase.database.AbstractJdbcDatabase.rollback(AbstractJdbcDatabase.java:1166)
	... 29 common frames omitted
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:490)
	at com.sun.proxy.$Proxy65.getAutoCommit(Unknown Source)
	at com.zaxxer.hikari.pool.HikariProxyConnection.getAutoCommit(HikariProxyConnection.java)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.ttddyy.dsproxy.proxy.ConnectionProxyLogic.invoke(ConnectionProxyLogic.java:87)
	at net.ttddyy.dsproxy.proxy.jdk.ConnectionInvocationHandler.invoke(ConnectionInvocationHandler.java:27)
	at com.sun.proxy.$Proxy64.getAutoCommit(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:384)
	at com.sun.proxy.$Proxy71.getAutoCommit(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:236)
	at com.sun.proxy.$Proxy71.getAutoCommit(Unknown Source)
	at liquibase.database.jvm.JdbcConnection.rollback(JdbcConnection.java:336)
	... 30 common frames omitted
14:00:28,640 |-INFO in c.q.l.co.rolling.helper.RenameUtil - Renaming file [/opt/ub-ledger-server/logs/liquibase_error.log] to [/opt/ub-ledger-server/logs/liquibase_error.log-2018-04-19-13.0] `

**Comment by achoice** [comment]
Yes, found we call setSocketTimeout in our init. Thanks for help, we will change and test again when next schema change comes along.

`// probably this setting can be removed when this fix https://github.com/pgjdbc/pgjdbc/pull/849 is released
dataSource.setConnectTimeout(5);
dataSource.setSocketTimeout(5);`
