### ISSUE TITLE
roachtest: fix version test

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#24980]
```
F180422 14:47:59.246403 13 server/server.go:1532  [n1] failed to run migration "add root user": column "isRole" does not exist
goroutine 13 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc420056900, 0xc420056900, 0x34e5100, 0x10)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:932 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x3d81440, 0xc400000004, 0x34e512f, 0x10, 0x5fc, 0xc425c39ea0, 0x4c)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:808 +0x753
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x28b9a80, 0xc42023aa50, 0x4, 0x2, 0x0, 0x0, 0xc4258feea8, 0x1, 0x1)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:154 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x28b9a80, 0xc42023aa50, 0x1, 0xc400000004, 0x0, 0x0, 0xc4258feea8, 0x1, 0x1)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:55 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x28b9a80, 0xc42023aa50, 0xc4258feea8, 0x1, 0x1)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:158 +0x6c
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start(0xc4201eb800, 0x28b9a80, 0xc42023aa50, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1532 +0x31f3
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1.2(0xc4201c0cf0, 0xc42000e0a8, 0xc4202d6270, 0x28b9a80, 0xc42081c060, 0x3a5d2009, 0xed26e979b, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:517 +0x116
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1(0xc42000e0a8, 0x28b9a80, 0xc42081c060, 0x28db840, 0xc420815110, 0xc4201c0cf0, 0xc4202d6270, 0x3a5d2009, 0xed26e979b, 0x0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:600 +0x11c
created by github.com/cockroachdb/cockroach/pkg/cli.runStart
    /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:473 +0x55e
```

something is weird with this test now. Our `master` branch corresponds to what will be v2.1, but the test runs a cluster that mixes v1.1.5 and `master`. This is illegal to begin with but somehow the test makes it far enough to fail as above.

**Comment by tschottdorf** [comment]
@windchan7 could you take a look at this next (this test is broken). The "fix" is straightforward: the "base version" needs to be 2.0, not 1.1.

I was confused above why this test doesn't fail eagerly (after all, we're kind of mixing a 1.1 binary with a 2.1 binary) but I realized that to the test the "2.1" binary doesn't look like a 2.1 binary. It looks like a very new 2.0 binary and that's allowed to upgrade into. So the above fix is all that's needed.
