### ISSUE TITLE
bulkio: backup2TB roachtest failed

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#25219]
Test log is [here](https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/633729:id/backup2TB/test.log):

```
Error: pq: exporting 43777 ranges: cannot update progress on succeeded job (id 344335717314592769)
Failed running "sql"
Error:  Process exited with status 1
```

**Comment by mjibson** [comment]
One node has in its log (from another day):

```
I180503 07:40:58.072950 564233 storage/replica_command.go:1784  [replicate,n1,s1,r34128/2:/Table/51/1/55082545{-/0}] change replicas (REMOVE_REPLICA (n5,s5):3): read existing descriptor r34128:/Table/51/1/55082545{-/0} [(n7,s7):1, (n1,s1):2, (n5,s5):3, (n4,s4):4, next=5]
I180503 07:40:58.206642 564294 storage/replica.go:3222  [n1,s1,r34128/2:/Table/51/1/55082545{-/0}] proposing REMOVE_REPLICA((n5,s5):3): updated=[(n7,s7):1 (n1,s1):2 (n4,s4):4] next=5
I180503 07:40:59.360243 564348 storage/replica_raftstorage.go:520  [replicate,n1,s1,r40332/2:/Table/51/1/5865{5250…-7399}] generated preemptive snapshot f58dee52 at index 34
I180503 07:40:59.523867 242 storage/replica_proposal.go:201  [n1,s1,r35311/2:/Table/51/1/5082{5155…-7899}] new range lease repl=(n1,s1):2 seq=16 start=1525333259.514205170,0 epo=3 pro=1525333259.514206949,0 following repl=(n10,s10):3 seq=15 start=1525328465.392728670,0 epo=2 pro=1525328465.392747488,0
I180503 07:40:59.685555 262 storage/replica_proposal.go:201  [n1,s1,r713/2:/Table/51/1/25288{53/0-69}] new range lease repl=(n1,s1):2 seq=13 start=1525333259.673957939,0 epo=3 pro=1525333259.673961689,0 following repl=(n5,s5):3 seq=12 start=1525326052.091216507,0 epo=2 pro=1525326389.913500600,0
E180503 07:40:59.721516 247 vendor/github.com/coreos/etcd/raft/log.go:191  [n1,s1,r15402/4:{-}] tocommit(28) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
E180503 07:40:59.721540 247 util/log/crash_reporting.go:185  [n1,s1] a panic has occurred!
I180503 07:40:59.799568 350 gossip/gossip.go:487  [n1] gossip status (ok, 9 nodes)
gossip client (1/3 cur/max conns)
  4: teamcity-638058-backup2tb-0007:26257 (2h0m0s: infos 32096/64436 sent/received, bytes 8544682B/16205005B sent/received)
gossip server (2/3 cur/max conns, infos 87890/158266 sent/received, bytes 31302304B/41779455B sent/received)
  9: teamcity-638058-backup2tb-0002:26257 (2h0m6s)
  5: teamcity-638058-backup2tb-0008:26257 (2h0m4s)
I180503 07:40:59.801403 350 gossip/gossip.go:332  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"teamcity-638058-backup2tb-0001:26257" > attrs:<> locality:<tiers:<key:"cloud" value:"gce" > tiers:<key:"region" value:"us-central1" > tiers:<key:"zone" value:"us-central1-b" > > ServerVersion:<major_val:2 minor_val:0 patch:0 unstable:0 > 
I180503 07:40:59.810878 353 server/status/runtime.go:219  [n1] runtime stats: 5.6 GiB RSS, 386 goroutines, 676 MiB/315 MiB/1.0 GiB GO alloc/idle/total, 3.9 GiB/4.8 GiB CGO alloc/total, 2056.37cgo/sec, 0.23/0.04 %(u/s)time, 0.00 %gc (0x)
I180503 07:40:59.857591 251 storage/replica_proposal.go:201  [n1,s1,r35868/4:/Table/51/1/51495606{-/0}] new range lease repl=(n1,s1):4 seq=16 start=1525333259.849490151,0 epo=3 pro=1525333259.849492857,0 following repl=(n3,s3):1 seq=15 start=1525328306.440888401,0 epo=2 pro=1525328306.440907634,0
I180503 07:40:59.945870 564419 ccl/storageccl/export.go:128  [n1,s1,r33664/2:/Table/51/1/53801321{-/0}] export [/Table/51/1/53801321,/Table/51/1/53801321/0)
I180503 07:40:59.946536 564379 ccl/storageccl/export.go:128  [n1,s1,r33697/2:/Table/51/1/5380{1321…-4593}] export [/Table/51/1/53801321/0,/Table/51/1/53804593)
E180503 07:40:59.951501 247 util/log/crash_reporting.go:451  [n1,s1] Reported as error f6ef270222ff4b95b84c303cc5f0db54
panic: tocommit(28) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost? [recovered]
	panic: tocommit(28) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?

goroutine 247 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4208059e0, 0x27780c0, 0xc4282eb380)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:177 +0x11f
panic(0x20ceba0, 0xc42508b800)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*raftLogger).Panicf(0xc42558e370, 0x24c93a5, 0x5d, 0xc42ea0ef00, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.go:106 +0xfe
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc43a640700, 0x1c)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/log.go:191 +0x15c
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc446c17e00, 0x8, 0x4, 0x3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1232 +0x54
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.stepFollower(0xc446c17e00, 0x8, 0x4, 0x3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:1177 +0x44c
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc446c17e00, 0x8, 0x4, 0x3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:898 +0x1308
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*RawNode).Step(0xc431cbd100, 0x8, 0x4, 0x3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:195 +0xdd
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).stepRaftGroup.func1(0xc431cbd100, 0x2778040, 0xc4200400c0, 0x27780c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3336 +0xa8
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc4376eb500, 0x256a600, 0xc42bb33b88, 0xc42bb33b70, 0x6fe809)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:607 +0x10f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroup(0xc4376eb500, 0xc42bb33b88, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:624 +0x88
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).stepRaftGroup(0xc4376eb500, 0xc42b3a0d10, 0x2191600, 0x30)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3331 +0x50
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequestWithReplica(0xc42090ec00, 0x27780c0, 0xc445008cc0, 0xc4376eb500, 0xc42b3a0d10, 0xc445008cc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3238 +0xeb
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x27780c0, 0xc445008cc0, 0xc4376eb500, 0x27780c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3856 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc42090ec00, 0x27780c0, 0xc445008cc0, 0xc42b3a0d10, 0xc42bb33ed0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3184 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc42090ec00, 0x27780c0, 0xc4282eb380, 0x3c2a)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3850 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42002ebd0, 0x27780c0, 0xc4282eb380)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:226 +0x21b
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x27780c0, 0xc4282eb380)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc427aaad70, 0xc4208059e0, 0xc427aaad60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xad
```

**Comment by tschottdorf** [comment]
@bdarnell, this is from this range and there's no other log message about it:

> E180503 07:40:59.721516 247 vendor/github.com/coreos/etcd/raft/log.go:191  [n1,s1,r15402/4:{-}] tocommit(28) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?

Any ideas?

**Comment by bdarnell** [comment]
It's a test-only issue: the data was generated incorrectly and has two nodes that believes they are node 1. @benesch is going to regenerate the data.

**Comment by mjibson** [comment]
The comment I wrote is #24337. I shouldn't have pasted that here since it already existed.

**Comment by petermattis** [comment]
Duplicate of #25645.
