### ISSUE TITLE
sql: tuple-typed placeholders panic the server

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#25254]
```
root@127.0.0.1:53577/demo> prepare x as select $1 = (1, 2);
*
* ERROR: [n1,client=127.0.0.1:53579,user=root] a SQL panic has occurred while executing "PREPARE x AS SELECT $1 = (1, 2)": value type tuple cannot be used for table columns
*
*
* ERROR: [n1,client=127.0.0.1:53579,user=root] a panic has occurred!
*
panic while executing 1 statements: PREPARE _ AS SELECT $1 = (_, _); caused by value type tuple cannot be used for table columns

goroutine 509 [running]:
runtime/debug.Stack(0x6406c00, 0xc4215971c0, 0x3)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6406c00, 0xc4215971c0, 0xc4206e9980, 0x5f72680, 0xc421417c50, 0x1)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc421373000, 0x6406c00, 0xc4215971c0, 0x5f93720, 0xc420ed71a0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:562 +0x2be
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2(0xc421373000, 0x6406c00, 0xc4215971c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:493 +0x61
panic(0x5f93720, 0xc420ed71a0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode(0xc421158120, 0x63e3600, 0xc4203ab700)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:286 +0x4ac
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.exprFmtWithParen(0xc421158120, 0x6408f80, 0xc4203ab700)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:112 +0xfc
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.binExprFmtWithParen(0xc421158120, 0x6408f80, 0xc4203ab700, 0x609e3e7, 0x1, 0x64087c0, 0xc420414080, 0xc421373401)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:144 +0x43
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr).Format(0xc4211587e0, 0xc421158120)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:411 +0x129
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants(0xc421158120, 0x63e2b40, 0xc4211587e0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:43 +0x71
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode(0xc421158120, 0x63e2b40, 0xc4211587e0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:266 +0x8d
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.AsStringWithFlags(0x63e2b40, 0xc4211587e0, 0x6000, 0x63e2b40, 0xc4211587e0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:296 +0x54
github.com/cockroachdb/cockroach/pkg/sql.symbolicExprStr(0x6408000, 0xc4211587e0, 0xc4211587e0, 0x6408000)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/targets.go:147 +0x58
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).addOrReuseRender(0xc420ef34a0, 0xc4203362d0, 0xb, 0x64164a0, 0x76ee420, 0x0, 0x6413e60, 0xc4211587e0, 0xc421417b00, 0xc4203362d0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/targets.go:110 +0x67
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).addOrReuseRenders(0xc420ef34a0, 0xc421417b90, 0x1, 0x1, 0xc42038b170, 0x1, 0x1, 0x6416400, 0x76ee420, 0xc420bd2100, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/targets.go:138 +0x147
github.com/cockroachdb/cockroach/pkg/sql.(*planner).initTargets(0xc4213733e8, 0x6406cc0, 0xc421417950, 0xc420ef34a0, 0xc4203ab780, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:403 +0x23b
github.com/cockroachdb/cockroach/pkg/sql.(*planner).SelectClause(0xc4213733e8, 0x6406cc0, 0xc421417950, 0xc421158360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:200 +0x1aa
github.com/cockroachdb/cockroach/pkg/sql.(*planner).Select(0xc4213733e8, 0x6406cc0, 0xc421417950, 0xc4209f2e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421229148, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:120 +0x54b
github.com/cockroachdb/cockroach/pkg/sql.(*planner).doPrepare(0xc4213733e8, 0x6406cc0, 0xc421417950, 0x6409380, 0xc4209f2e00, 0xc420bfa9a0, 0x0, 0x152aed0815514b66, 0x18)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:839 +0x6ae
github.com/cockroachdb/cockroach/pkg/sql.(*planner).prepare(0xc4213733e8, 0x6406cc0, 0xc421417950, 0x6409380, 0xc4209f2e00, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:800 +0xc8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare.func1(0xc421373000, 0x6406cc0, 0xc421417950, 0xc420d6a9c0, 0xc421417a10, 0xc4211586c0, 0x6409380, 0xc4209f2e00, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:197 +0x2bf
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare(0xc421373000, 0x6406cc0, 0xc421417950, 0x6409380, 0xc4209f2e00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:214 +0x2dd
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).addPreparedStmt(0xc421373000, 0x6406cc0, 0xc421417950, 0xc4203362a9, 0x1, 0x6409380, 0xc4209f2e00, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:122 +0xdf
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc421373000, 0x6406cc0, 0xc421417950, 0x6408fc0, 0xc4209f2e40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:273 +0x1ed1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc421373000, 0x6406cc0, 0xc421417950, 0x6408fc0, 0xc4209f2e40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:83 +0x33e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc421373000, 0x6406c00, 0xc4215971c0, 0xc420410be0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:961 +0x1c79
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4205edb00, 0x6406c00, 0xc4215971c0, 0xc42070904a, 0x4, 0xc420709054, 0x4, 0x0, 0x0, 0x63ee9c0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:495 +0xee3
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc4205edb00, 0x6406c00, 0xc4215971c0, 0xc420c4ba40, 0x5400, 0x15000, 0xc4207edec8, 0xc420410be0, 0xc420410bc0, 0xc4202f1080, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:260 +0x10c
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:259 +0xebe

*
* ERROR: [n1,client=127.0.0.1:53579,user=root] Reported as error 611676929b5e44c4b4cc76398f517f3d
*
```

**Comment by knz** [comment]
@BramGruneir could you look into this while you are paged in on tuples?

**Comment by jordanlewis** [comment]
I already have an open PR that fixes this.

**Comment by knz** [comment]
oh I'm sorry I hadn't seen it. carry on.
