### ISSUE TITLE
storage/engine: segfault in RocksDBIterator

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#25289]
We just upgraded RocksDB, but this seems to be on the go side... @petermattis what do you make of this?
Happened to me on the first run, didn't happen on a 2nd.
```
make bench PKG=./pkg/bench BENCHES='/^Cockroach' TESTFLAGS='-count 5 -logtostderr=NONE' TESTTIMEOUT=200m
```

```
BenchmarkSQL/Cockroach/Delete/count=10-8        	unexpected fault address 0xfe00000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xfe00000 pc=0x4b7e8a4]

goroutine 252477 [running]:
runtime.throw(0x5bf0d17, 0x5)
	/Users/andrei/go/src/runtime/panic.go:619 +0x81 fp=0xc42207e190 sp=0xc42207e170 pc=0x402eb51
runtime.sigpanic()
	/Users/andrei/go/src/runtime/signal_unix.go:395 +0x211 fp=0xc42207e1e0 sp=0xc42207e190 pc=0x4044631
github.com/cockroachdb/cockroach/pkg/storage/engine.gobytes(0xfe00000, 0x0, 0xbe8e0d8, 0x4, 0x472437d)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/engine/slice.go:30 +0x34 fp=0xc42207e228 sp=0xc42207e1e0 pc=0x4b7e8a4
github.com/cockroachdb/cockroach/pkg/storage/engine.cSliceToGoBytes(0xfe00000, 0x0, 0x4, 0x4, 0x1)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2261 +0x3a fp=0xc42207e260 sp=0xc42207e228 pc=0x4b8e9fa
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).Value(0xc4220037b0, 0x0, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1997 +0x2f fp=0xc42207e298 sp=0xc42207e260 pc=0x4b8c66f
github.com/cockroachdb/cockroach/pkg/storage/engine.mvccGetInternal(0x5f0f6c0, 0xc421f03c20, 0x5f35140, 0xc4220037b0, 0xc4202d5700, 0x4, 0x4, 0x0, 0x0, 0x152b37bb344fb1a6, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:952 +0x782 fp=0xc42207e5d0 sp=0xc42207e298 pc=0x4b71bc2
github.com/cockroachdb/cockroach/pkg/storage/engine.maybeGetValue(0x5f0f6c0, 0xc421f03c20, 0x5f35140, 0xc4220037b0, 0xc4202d5700, 0x4, 0x4, 0x0, 0x0, 0x0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:1140 +0x1dd fp=0xc42207e698 sp=0xc42207e5d0 pc=0x4b738bd
github.com/cockroachdb/cockroach/pkg/storage/engine.mvccPutInternal(0x5f0f6c0, 0xc421f03c20, 0x99a0bd0, 0xc4220037a8, 0x5f35140, 0xc4220037b0, 0xc421be58f0, 0xc4202d5700, 0x4, 0x4, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:1297 +0x131f fp=0xc42207ebb8 sp=0xc42207e698 pc=0x4b74ccf
github.com/cockroachdb/cockroach/pkg/storage/engine.mvccPutUsingIter(0x5f0f6c0, 0xc421f03c20, 0x99a0bd0, 0xc4220037a8, 0x5f35140, 0xc4220037b0, 0xc421be58f0, 0xc4202d5700, 0x4, 0x4, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:1109 +0x15a fp=0xc42207ec98 sp=0xc42207ebb8 pc=0x4b735ea
github.com/cockroachdb/cockroach/pkg/storage/engine.mvccConditionalPutUsingIter(0x5f0f6c0, 0xc421f03c20, 0x99a0bd0, 0xc4220037a8, 0x5f35140, 0xc4220037b0, 0xc421be58f0, 0xc4202d5700, 0x4, 0x4, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:1460 +0x191 fp=0xc42207ed88 sp=0xc42207ec98 pc=0x4b75aa1
github.com/cockroachdb/cockroach/pkg/storage/engine.MVCCConditionalPut(0x5f0f6c0, 0xc421f03c20, 0x5f2ee20, 0xc4220037a8, 0xc421be58f0, 0xc4202d5700, 0x4, 0x4, 0x152b37bb344fb1a6, 0xc400000000, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:1428 +0x1a8 fp=0xc42207ee50 sp=0xc42207ed88 pc=0x4b75768
github.com/cockroachdb/cockroach/pkg/storage/batcheval.ConditionalPut(0x5f0f6c0, 0xc421f03c20, 0x5f2ee20, 0xc4220037a8, 0x5f381a0, 0xc4209d0e00, 0x152b37bb344fb1a6, 0x0, 0x100000001, 0x1, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/batcheval/cmd_conditional_put.go:50 +0x33b fp=0xc42207efa8 sp=0xc42207ee50 pc=0x4bb792b
github.com/cockroachdb/cockroach/pkg/storage.evaluateCommand(0x5f0f6c0, 0xc421f03c20, 0xc4202d5c20, 0x8, 0x0, 0x99a0750, 0xc422003680, 0x5f381a0, 0xc4209d0e00, 0xc421be58f0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:101 +0x30c fp=0xc42207f7a8 sp=0xc42207efa8 pc=0x4d5810c
github.com/cockroachdb/cockroach/pkg/storage.evaluateBatch(0x5f0f6c0, 0xc421f03c20, 0xc4202d5c20, 0x8, 0x99a0750, 0xc422003680, 0x5f381a0, 0xc4209d0e00, 0xc421be58f0, 0x152b37bb344fb1a6, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5543 +0x3ad fp=0xc4220804f8 sp=0xc42207f7a8 pc=0x4d52b8d
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).evaluateWriteBatchWithLocalRetries(0xc4209d0e00, 0x5f0f6c0, 0xc421f03c20, 0xc4202d5c20, 0x8, 0x5f381a0, 0xc4209d0e00, 0xc421be58f0, 0x152b37bb344fb1a6, 0x0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5320 +0x1da fp=0xc4220808d0 sp=0xc4220804f8 pc=0x4d5164a
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).evaluateWriteBatch(0xc4209d0e00, 0x5f0f6c0, 0xc421f03c20, 0xc4202d5c20, 0x8, 0x152b37bb344fb1a6, 0x0, 0x100000001, 0x1, 0x27, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5239 +0x55e fp=0xc422081940 sp=0xc4220808d0 pc=0x4d5051e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).evaluateProposal(0xc4209d0e00, 0x5f0f6c0, 0xc421f03c20, 0xc4202d5c20, 0x8, 0x152b37bb344fb1a6, 0x0, 0x100000001, 0x1, 0x27, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2926 +0x16d fp=0xc422082300 sp=0xc422081940 pc=0x4d4357d
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).requestToProposal(0xc4209d0e00, 0x5f0f6c0, 0xc421f03c20, 0xc4202d5c20, 0x8, 0x152b37bb344fb1a6, 0x0, 0x100000001, 0x1, 0x27, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2874 +0xea fp=0xc422082400 sp=0xc422082300 pc=0x4d430fa
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).propose(0xc4209d0e00, 0x5f0f6c0, 0xc421f03c20, 0x152b37b6bc23847a, 0x0, 0x0, 0x100000001, 0x1, 0x0, 0xc4203da6a0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3135 +0x456 fp=0xc4220829c0 sp=0xc422082400 pc=0x4d44a96
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc4209d0e00, 0x5f0f6c0, 0xc421f03c20, 0x152b37bb344fb1a6, 0x0, 0x100000001, 0x1, 0x27, 0x3ff0000000000000, 0xc421cc0500, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2779 +0x480 fp=0xc422083018 sp=0xc4220829c0 pc=0x4d420b0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc4209d0e00, 0x5f0f6c0, 0xc421f03c20, 0x152b37bb344fb1a6, 0x0, 0x100000001, 0x1, 0x27, 0x3ff0000000000000, 0xc421cc0500, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2628 +0xae fp=0xc422083140 sp=0xc422083018 pc=0x4d418ae
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc4209d0e00, 0x5f0f6c0, 0xc421f03c20, 0x152b37bb344fb1a6, 0x0, 0x100000001, 0x1, 0x27, 0x3ff0000000000000, 0xc421cc0500, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1867 +0x69d fp=0xc4220832a0 sp=0xc422083140 pc=0x4d3bf4d
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc42048d000, 0x5f0f6c0, 0xc421f03bf0, 0x152b37bb344fb1a6, 0x0, 0x100000001, 0x1, 0x27, 0x3ff0000000000000, 0xc421cc0500, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2749 +0x623 fp=0xc422083b60 sp=0xc4220832a0 pc=0x4d92713
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc42108e630, 0x5f0f6c0, 0xc421f03b90, 0x0, 0x0, 0x100000001, 0x1, 0x27, 0x3ff0000000000000, 0xc421cc0500, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:185 +0xce fp=0xc422083c40 sp=0xc422083b60 pc=0x4da375e
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x5f0f6c0, 0xc421f03b90, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/server/node.go:899 +0x185 fp=0xc422083d40 sp=0xc422083c40 pc=0x5267ad5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc420444c60, 0x5f0f6c0, 0xc421f03b90, 0x5c0279c, 0x10, 0xc422083df8, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:243 +0xed fp=0xc422083d78 sp=0xc422083d40 pc=0x47c022d
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc4222e0c00, 0x5f0f6c0, 0xc421f03b90, 0xc421f71a50, 0xc421f03b90, 0x47f533e, 0x5f0f6c0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/server/node.go:886 +0x201 fp=0xc422084028 sp=0xc422083d78 pc=0x5246071
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc4222e0c00, 0x5f0f6c0, 0xc421f03b90, 0xc421f71a50, 0x1f, 0x68, 0x5b20320)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/server/node.go:927 +0x99 fp=0xc4220840a8 sp=0xc422084028 pc=0x52463e9
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).send.func1(0xc421ccc850, 0xc421f71a40, 0x5f0f6c0, 0xc421f03b00, 0x0, 0xc4220842e8, 0x4014958)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:242 +0x6df fp=0xc422084290 sp=0xc4220840a8 pc=0x4a270ef
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).send(0xc421ccc850, 0x5f0f6c0, 0xc421f03b00, 0xc420377fb0, 0xf, 0x0, 0x0, 0x100000001, 0x1, 0x27, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:273 +0x90 fp=0xc4220842f8 sp=0xc422084290 pc=0x4a1b1a0
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext(0xc421ccc850, 0x5f0f6c0, 0xc421f03b00, 0xc4212fd740)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:207 +0x2bb fp=0xc422084408 sp=0xc4220842f8 pc=0x4a1b06b
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc4201c7860, 0x5f0f6c0, 0xc421f03b00, 0xc4201c78b0, 0x27, 0xc4202e0680, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1289 +0x386 fp=0xc422084870 sp=0xc422084408 pc=0x4a12ad6
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc4201c7860, 0x5f0f6c0, 0xc421f03b00, 0x27, 0xc4202e0680, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:393 +0x242 fp=0xc422084978 sp=0xc422084870 pc=0x4a0ce62
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc4201c7860, 0x5f0f6c0, 0xc421f03b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3ff0000000000000, 0xc421cc0500, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:460 +0x21a fp=0xc422084a90 sp=0xc422084978 pc=0x4a0d3ca
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc4201c7860, 0x5f0f6c0, 0xc421f03b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3ff0000000000000, 0xc421cc0500, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1067 +0x325 fp=0xc4220850d0 sp=0xc422084a90 pc=0x4a10b35
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc4201c7860, 0x5f0f6c0, 0xc421f03b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3ff0000000000000, 0xc421cc0500, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:739 +0x15e6 fp=0xc422085968 sp=0xc4220850d0 pc=0x4a10456
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc4201c7860, 0x5f0f6c0, 0xc421f03b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3ff0000000000000, 0xc421cc0400, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:655 +0x415 fp=0xc422085bc0 sp=0xc422085968 pc=0x4a0e645
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc421c4d500, 0x5f0f6c0, 0xc421f03a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3ff0000000000000, 0xc421cc0400, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:490 +0x1ec fp=0xc422085fa0 sp=0xc422085bc0 pc=0x4a1d9fc
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).sendUsingSender(0xc420e258f0, 0x5f0f6c0, 0xc421f03680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3ff0000000000000, 0xc421cc0400, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:553 +0x118 fp=0xc422086060 sp=0xc422085fa0 pc=0x4872868
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Send(0xc421910b60, 0x5f0f6c0, 0xc421f03680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:959 +0x3a8 fp=0xc4220863a0 sp=0xc422086060 pc=0x487c9c8
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Send-fm(0x5f0f6c0, 0xc421f03680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:505 +0x76 fp=0xc422086448 sp=0xc4220863a0 pc=0x4880fe6
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0x5f0f6c0, 0xc421f03680, 0xc422086590, 0xc421cc6700, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:468 +0xf8 fp=0xc422086560 sp=0xc422086448 pc=0x4872228
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Run(0xc421910b60, 0x5f0f6c0, 0xc421f03680, 0xc421cc6700, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:505 +0xc7 fp=0xc4220865b0 sp=0xc422086560 pc=0x487aab7
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).CommitInBatch(0xc421910b60, 0x5f0f6c0, 0xc421f03680, 0xc421cc6700, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:558 +0x13d fp=0xc422086628 sp=0xc4220865b0 pc=0x487b02d
github.com/cockroachdb/cockroach/pkg/sql.(*tableWriterBase).finalize(0xc4226e45a8, 0x5f0f6c0, 0xc421f03680, 0x1, 0xc421819880, 0xc42115d220, 0xc4202e0500)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go:160 +0x5e fp=0xc422086668 sp=0xc422086628 pc=0x515bd0e
github.com/cockroachdb/cockroach/pkg/sql.(*tableInserter).finalize(0xc4226e45a8, 0x5f0f6c0, 0xc421f03680, 0x1, 0xc420fd8300, 0xc422001200, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter_insert.go:57 +0x52 fp=0xc4220866b0 sp=0xc422086668 pc=0x515ecc2
github.com/cockroachdb/cockroach/pkg/sql.(*insertNode).BatchedNext(0xc4226e4580, 0x5f0f6c0, 0xc421f03680, 0xc420fd8458, 0xc420fd83e8, 0x5a5ce00, 0x4011101, 0x9960cc8)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/insert.go:461 +0x202 fp=0xc422086718 sp=0xc4220866b0 pc=0x50cdcb2
github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode).startExec(0xc4202e04e0, 0x5f0f6c0, 0xc421f03680, 0xc420fd8458, 0xc420fd83e8, 0x1, 0xc4220867e8)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:173 +0xd0 fp=0xc422086768 sp=0xc422086718 pc=0x5106440
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x5bf0c04, 0x5, 0x5f06080, 0xc4202e04e0, 0xc4215d6f28, 0xc4220867f8)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:513 +0x90 fp=0xc4220867b8 sp=0xc422086768 pc=0x51a9c70
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit.func1(0xc421308e80, 0x5bf0c04, 0x5, 0x5f06080, 0xc4202e04e0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:90 +0x5f fp=0xc4220867f8 sp=0xc4220867b8 pc=0x51b739f
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc421308e80, 0x5f06080, 0xc4202e04e0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:513 +0x3cf fp=0xc422087138 sp=0xc4220867f8 pc=0x5179cbf
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x5f0f6c0, 0xc421f03680, 0x5f06080, 0xc4202e04e0, 0x5d0c390, 0x0, 0x0, 0xc421f03920, 0x0, 0x5ae9100)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:53 +0x133 fp=0xc4220871e8 sp=0xc422087138 pc=0x5179893
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x5f0f6c0, 0xc421f03680, 0xc420fd8458, 0xc420fd83e8, 0x5f06080, 0xc4202e04e0, 0x742f000, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:518 +0xbf fp=0xc422087248 sp=0xc4220871e8 pc=0x510022f
github.com/cockroachdb/cockroach/pkg/sql.startPlan(0x5f0f6c0, 0xc421f03680, 0xc420fd8458, 0xc420fd83e8, 0x5f06080, 0xc4202e04e0, 0x0, 0xc4220872f0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:450 +0x61 fp=0xc422087298 sp=0xc422087248 pc=0x5100101
github.com/cockroachdb/cockroach/pkg/sql.(*planTop).start(0xc420fd8650, 0x5f0f6c0, 0xc421f03680, 0xc420fd8458, 0xc420fd83e8, 0x4003f5e, 0xc4220874f0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:423 +0xc0 fp=0xc4220872e8 sp=0xc422087298 pc=0x50ffae0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithLocalEngine(0xc420fd8000, 0x5f0f6c0, 0xc421f03680, 0xc420fd83e8, 0x2, 0x77117d0, 0xc4216d2a00, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:645 +0x106 fp=0xc422087390 sp=0xc4220872e8 pc=0x5052146
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc420fd8000, 0x5f0f6c0, 0xc421f03680, 0x5f11500, 0xc420f35a40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:609 +0x870 fp=0xc4220874a0 sp=0xc422087390 pc=0x5051c90
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc420fd8000, 0x5f0f6c0, 0xc421f03680, 0x5f11500, 0xc420f35a40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:375 +0xa8c fp=0xc422087c08 sp=0xc4220874a0 pc=0x504ee2c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc420fd8000, 0x5f0f6c0, 0xc421f03680, 0x5f11500, 0xc420f35a40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:87 +0x358 fp=0xc422087d58 sp=0xc422087c08 pc=0x504e018
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc420fd8000, 0x5f0f600, 0xc4207c73c0, 0xc4204a8c00, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:961 +0x1d7a fp=0xc422088468 sp=0xc422087d58 pc=0x50473ca
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420f4d700, 0x5f0f600, 0xc4207c73c0, 0xc42022f045, 0x5, 0xc42022f00d, 0x4, 0x0, 0x0, 0x5ef99c0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:495 +0xf8c fp=0xc422089e90 sp=0xc422088468 pc=0x504404c
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc420f4d700, 0x5f0f600, 0xc4207c73c0, 0xc420ea5dc0, 0x5400, 0x15000, 0xc4211d8188, 0xc4204a8c00, 0xc4204a8bf0, 0xc42027b770, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:260 +0x10c fp=0xc422089f88 sp=0xc422089e90 pc=0x521ceac
runtime.goexit()
	/Users/andrei/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc422089f90 sp=0xc422089f88 pc=0x405d801
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:259 +0xf27
```

**Comment by jordanlewis** [comment]
Reminds me of #24588.

**Comment by petermattis** [comment]
@andreimatei Can you reproduce this? I've run your `make bench` command many times and failed to reproduce.

**Comment by andreimatei** [comment]
Didn't reproduce for me either

**Comment by petermattis** [comment]
I got a reproduction (I think, only a partial stacktrace).

**Comment by benesch** [comment]
There's also a non-zero chance this is a build problem. @andreimatei's multiple Git workdirs definitely seem to be confusing the build system.

**Comment by petermattis** [comment]
Got another repro. It is only a matter of time until I track down what is going on. Interestingly, the stack trace is exactly the same as the one @andreimatei posted. That's a bit surprising as if there was a problem with `engine.gobytes` I'd expect it to hit a number of different stack traces. 

```
BenchmarkSQL/Cockroach/Delete/count=100-8               unexpected fault address 0x13600000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x13600000 pc=0x4b80424]

goroutine 252565 [running]:
runtime.throw(0x5bee33a, 0x5)
        /Users/pmattis/Development/go1.10/src/runtime/panic.go:619 +0x81 fp=0xc42318c1e0 sp=0xc42318c1c0 pc=0x402e431
runtime.sigpanic()
        /Users/pmattis/Development/go1.10/src/runtime/signal_unix.go:395 +0x211 fp=0xc42318c230 sp=0xc42318c1e0 pc=0x4043f11
github.com/cockroachdb/cockroach/pkg/storage/engine.gobytes(0x13600000, 0x0, 0xb6458d8, 0x4, 0x472460d)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/slice.go:30 +0x34 fp=0xc42318c278 sp=0xc42318c230 pc=0x4b80424
github.com/cockroachdb/cockroach/pkg/storage/engine.cSliceToGoBytes(0x13600000, 0x0, 0x4, 0x4, 0x1)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2261 +0x3a fp=0xc42318c2b0 sp=0xc42318c278 pc=0x4b9057a
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).Value(0xc4207e1e70, 0x0, 0x0, 0x0)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1997 +0x2f fp=0xc42318c2e8 sp=0xc42318c2b0 pc=0x4b8e1ef
github.com/cockroachdb/cockroach/pkg/storage/engine.mvccGetInternal(0x5f10360, 0xc42093e4e0, 0x5f35ea0, 0xc4207e1e70, 0xc4203dd53c, 0x4, 0x4, 0x0, 0x0, 0x152b963eec11e26b, ...)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:952 +0x782 fp=0xc42318c620 sp=0xc42318c2e8 pc=0x4b73742
github.com/cockroachdb/cockroach/pkg/storage/engine.maybeGetValue(0x5f10360, 0xc42093e4e0, 0x5f35ea0, 0xc4207e1e70, 0xc4203dd53c, 0x4, 0x4, 0x0, 0x0, 0x0, ...)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:1140 +0x1dd fp=0xc42318c6e8 sp=0xc42318c620 pc=0x4b7543d
```

**Comment by petermattis** [comment]
And here is a trivial reproduction:

```
func TestGoBytes(t *testing.T) {
	_ = gobytes(nil, 0)
}
```

The segfault is occurring on this line when `ptr` is invalid.

```
	src := (*[maxArrayLen]byte)(ptr)[:len:len]
```

Somewhat surprisingly, the above reads memory at at `ptr`. I'm not sure exactly why and I haven't had a chance to look at the assembly yet. The fix is super easy: we just need to check if `len == 0` at the start of `gobytes`. We can see from the stack traces above that this is only happening when the second parameter is 0. I'm not sure why this isn't happening more often. Perhaps something to do with the memory address needing to be invalid.
