### ISSUE TITLE
distsql: "inconsistent post-processing" panic.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#25611]
Caught by sentry in 2.0.1.
The panic message is redacted, but comes from https://github.com/cockroachdb/cockroach/blob/c92bc6e912880c28c0784d3208583fb27f482f76/pkg/sql/distsqlplan/physical_plan.go#L256

https://sentry.io/cockroach-labs/cockroachdb/issues/558411117/

```
*log.safeError: conn_executor.go:521: panic while executing 1 statements: SELECT _, _, _, _, _, _, _ FROM (SELECT _, _, _, _, _, _, _ FROM _._._ WHERE ((_ >= _) AND (_ = _)) AND (_ = _) ORDER BY _ ASC, _ ASC LIMIT _) UNION ALL (SELECT _, _, _, _, _, _, _ FROM _._._ WHERE ((_ < _) AND (_ = _)) AND (_ = _) ORDER BY _ DESC, _ ASC LIMIT _) LIMIT _: caused by <redacted>
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 489, in func2
  File "github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/physical_plan.go", line 256, in GetLastStagePost
  File "github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/physical_plan.go", line 627, in AddLimit
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 1994, in createPlanForNode
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go", line 526, in PlanAndRun
...
(9 additional frame(s) were not displayed)

conn_executor.go:521: panic while executing 1 statements: SELECT _, _, _, _, _, _, _ FROM (SELECT _, _, _, _, _, _, _ FROM _._._ WHERE ((_ >= _) AND (_ = _)) AND (_ = _) ORDER BY _ ASC, _ ASC LIMIT _) UNION ALL (SELECT _, _, _, _, _, _, _ FROM _._._ WHERE ((_ < _) AND (_ = _)) AND (_ = _) ORDER BY _ DESC, _ ASC LIMIT _) LIMIT _: caused by <redacted>
```

**Comment by RaduBerinde** [comment]
Looking at the code, I think this is a symptom of a bigger issue. The assumption in a bunch of places in the planning code is that all the last processors are parallel instances of the same node, and thus have the same `PostProcessingSpec`. Once we implemented `UNION ALL` by merging two plans, this assumption is no longer true. We need to either:
 - change the union-all implementation to add some no-op processors if necessary to make the post processing specs the same (contained change, less efficient)
 - audit the code for calls to `GetLastStagePost` and rework the code to allow different specs. There are a handful of instances to handle.

I think most of the work was done by Abhishek. @solongordon did some related work I think for UNION.

Assigning to @jordanlewis to figure out who can work on this.

**Comment by jordanlewis** [comment]
The first solution seems fine to me - adding a single no op processor isn't very expensive.

That being said, I can't figure out how to reproduce this. I thought it would be sufficient to have a `UNION ALL` that had a filter on one side and not on the other, but that didn't seem to do it:

```
root@127.0.0.1:50861/demo> create table a (a int primary key, b int);
CREATE TABLE

Time: 5.646957ms

root@127.0.0.1:50861/demo> create table b (a int primary key);
CREATE TABLE

Time: 3.421318ms

root@127.0.0.1:50861/demo> select a from a where a > 2 and b > 2 union all select a from b;
+---+
| a |
+---+
+---+
(0 rows)
```

**Comment by RaduBerinde** [comment]
The crash happens when some higher level node is trying to use the result of union all (and just for specific cases). Try adding a LIMIT (that applies to the UNION ALL result).

**Comment by jordanlewis** [comment]
```
explain(distsql) select a from a where a > 2 and b > 2 union all (select a from b) limit 1;

panic while executing 1 statements: EXPLAIN (DISTSQL) SELECT _ FROM _ WHERE (_ > _) AND (_ > _) UNION ALL (SELECT _ FROM _) LIMIT _; caused by inconsistent post-processing: {{ @2 > 2:::INT} true [0] [] 0 0} vs filter:<version:"" expr:"" > projection:false offset:0 limit:0

goroutine 493 [running]:
runtime/debug.Stack(0x6320260, 0xc420a26b00, 0x3)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6320260, 0xc420a26b00, 0xc420701980, 0x5e7d8e0, 0xc4212446c0, 0x1)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc42104e000, 0x6320260, 0xc420a26b00, 0x5c05520, 0xc420460c10)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:642 +0x2d7
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc42104e000, 0x6320260, 0xc420a26b00)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:399 +0x61
panic(0x5c05520, 0xc420460c10)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan.(*PhysicalPlan).GetLastStagePost(0xc421a52ac0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/physical_plan.go:272 +0x4ae
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan.(*PhysicalPlan).AddLimit(0xc421a52ac0, 0x1, 0x0, 0x1, 0xc420e48c80, 0x2)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/physical_plan.go:664 +0x1df
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc4206b51e0, 0xc421a534a8, 0x6315d60, 0xc420db6690, 0xc420e48c80, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2102 +0xe4d
```

The crash doesn't occur without the explain for some reason, but that's good enough to go on.

**Comment by RaduBerinde** [comment]
> The crash doesn't occur without the explain for some reason
Hmm, maybe the query is not being run in distsql in the default auto mode, I'd try `SET DISTSQL=ON`
