### ISSUE TITLE
panic: range for Range ID already exists on store

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#2595]
This occurred on a six-node cluster which was under constant insertion load; splits were occuring and ranges were being rebalanced. At some point the node which was receiving the insertion load crashed with this panic, and it re-occured immediately on every attempt to restart the node (node was permanently broken).

Unfortunately, I do not have a test which currently reproduces this; working on that. 

Detailed stack:

```
W0919 00:55:53.786231 9793 kv/dist_sender.go:569 failed to invoke *proto.ConditionalPutRequest ["\xff\v\x03\xe9\n\x01e1795f9b-8077-45f2-94af-bc292933ae48\x00\x01",""), *proto.ConditionalPutRequest ["\xff\v\x03\xe9\n\x01e1795f9b-8077-45f2-94af-bc292933ae48\x00\x01\n\x02",""): range 21: replica node_id:3 store_id:3 replica_id:3 not leader; leader is <nil>
W0919 00:55:53.786763 9793 kv/dist_sender.go:569 failed to invoke *proto.ConditionalPutRequest ["\xff\v\x03\xe9\n\x01e1795f9b-8077-45f2-94af-bc292933ae48\x00\x01",""), *proto.ConditionalPutRequest ["\xff\v\x03\xe9\n\x01e1795f9b-8077-45f2-94af-bc292933ae48\x00\x01\n\x02",""): range 21: replica node_id:3 store_id:3 replica_id:3 not leader; leader is <nil>
E0919 00:55:53.787011 9793 server/raft_transport.go:176 raft message to node 1 failed: connection is shut down
W0919 00:55:53.792860 9793 kv/dist_sender.go:569 failed to invoke *proto.EndTransactionRequest ["\xff\n\x02\n\x01\tbigdata\x00\x01\n\x03",""): retry txn "sql/executor.go:209 Executor.execStmt" id=8453e1dd key="\xff\n\x02\n\x01\tbigdata\x00\x01\n\x03" rw=true pri=42.50778334 iso=SERIALIZABLE stat=PENDING epo=0 ts=1442638552.700642824,1 orig=1442638552.230866671,0 max=1442638552.480866909,0
W0919 00:55:53.810999 9793 rpc/client.go:227 dial tcp 127.0.0.1:8081: getsockopt: connection refused
E0919 00:55:54.087213 9793 server/raft_transport.go:176 raft message to node 1 failed: connection is shut down
panic: range for Range ID 21 already exists on store

goroutine 11 [running]:
github.com/cockroachdb/cockroach/multiraft.(*writeTask).start.func1()
/Users/matt/go/src/github.com/cockroachdb/cockroach/multiraft/storage.go:177 +0x8b8
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200dcae0, 0xc8205d4000)
/Users/matt/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
/Users/matt/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x62
```

**Comment by bdarnell** [comment]
This is probably #768 and will be fixed by replica tombstones.

**Comment by bdarnell** [comment]
Closing now that replica tombstones are in; reopen if you see it again.
