### ISSUE TITLE
CockroachDB crashed when import data from mysql dump to a table with default value from sequence 

### ISSUE THREAD

**Issue by swanwish** [cockroachdb/cockroach#26850]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

```
I180620 07:21:30.063721 1 util/log/clog.go:1131  [config] file created at: 2018/06/20 07:21:30
I180620 07:21:30.063721 1 util/log/clog.go:1131  [config] running on machine: Stephen-Work
I180620 07:21:30.063721 1 util/log/clog.go:1131  [config] binary: CockroachDB CCL v2.1.0-alpha.20180604 (x86_64-apple-darwin13, built 2018/06/04 14:36:09, go1.10)
I180620 07:21:30.063721 1 util/log/clog.go:1131  [config] arguments: [cockroach start --insecure]
I180620 07:21:32.359040 23 cli/start.go:606  [config] clusterID: c94d0f5f-4adc-4436-8ed3-7c9b3ee924b5
```

Error message from `cockroach.log`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x52aea7f]

goroutine 2153 [running]:
github.com/cockroachdb/cockroach/pkg/sql.maybeAddSequenceDependencies(0x0, 0x0, 0xc42953a300, 0xc4285f8900, 0x634d1c0, 0xc4262e0070, 0xc42918fce0, 0x0, 0x0, 0xc429aa1b18, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sequence.go:295 +0x10f
github.com/cockroachdb/cockroach/pkg/sql.MakeTableDesc(0x633f300, 0xc426290bd0, 0x0, 0x0, 0x0, 0xc42071c000, 0xc425ef5260, 0x350000019a, 0x1539cd5bb7b891ae, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/create_table.go:1060 +0x610
github.com/cockroachdb/cockroach/pkg/ccl/importccl.MakeSimpleTableDescriptor(0x633f300, 0xc426290bd0, 0xc42071c000, 0xc425ef5260, 0x350000019a, 0x1539cd5bb7b891ae, 0x4, 0xc42028ebb0, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:146 +0x66f
github.com/cockroachdb/cockroach/pkg/ccl/importccl.importPlanHook.func1(0x633f300, 0xc426290bd0, 0x0, 0x0, 0x0, 0xc427c60f60, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:435 +0x4c6
github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1(0xc425ef5200, 0x633f300, 0xc4262909c0, 0xc428935d98, 0xc428935d28)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/planhook.go:138 +0x65
created by github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/planhook.go:137 +0x188
```

2. Please describe the issue you observed:

- What did you do?

I want to create a table with default value get from sequence, and import data from mysql dump, the test script is like below:
```
create sequence if not exists col_id;

import table t_test (
    col_id int default nextval('col_id') not null,
    col_name string not null,
    primary key (col_id)
) MYSQLDUMP DATA ('nodelocal:///test_t_test.sql');
```

- What did you expect to see?

I expect the data can imported to the new table without crash.

- What did you see instead?

The Cockroach instance crashed.

**Comment by tschottdorf** [comment]
Thanks for your report, @swanwish.
@vilterp, could you take a look?

**Comment by mjibson** [comment]
This is probably an IMPORT bug because we don't give out a real evalCtx here.
