### ISSUE TITLE
sql: bug in executor crashes server upon graceful shutdown with --verbosity 2

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26887]
Found on `master` while working on a test.
Steps to reproduce:

1. start server with `--verbosity 2`
2. initiate graceful shutdown
3. observe panic

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x21a8d46]

goroutine 104 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.contextBottomTag(0x0, 0x0, 0x519dc0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_context.go:45 +0x26
github.com/cockroachdb/cockroach/pkg/util/log.contextLogTags(0x0, 0x0, 0xc426547d48, 0x0, 0x8, 0xc424e71b48, 0x1d625b0, 0xc42025f180)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_context.go:55 +0x39
github.com/cockroachdb/cockroach/pkg/util/log.formatTags(0x0, 0x0, 0xc426547ce0, 0x2165e6a)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:109 +0x66
github.com/cockroachdb/cockroach/pkg/util/log.MakeMessage(0x0, 0x0, 0x777c54, 0x16, 0xc424e71e00, 0x2, 0x2, 0xc400000001, 0x189c5f6)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:127 +0x58
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x0, 0x0, 0x1, 0x3, 0x777c54, 0x16, 0xc424e71e00, 0x2, 0x2)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:142 +0xc9
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x0, 0x0, 0x2, 0xc400000001, 0x777c54, 0x16, 0xc424e71e00, 0x2, 0x2)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:55 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.InfofDepth(0x0, 0x0, 0x1, 0x777c54, 0x16, 0xc424e71e00, 0x2, 0x2)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:99 +0x89
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc424e40780, 0x0, 0x0, 0x1)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:391 +0x3ae
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(0xc424e40780, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:384 +0x44
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).finishExternalTxn(0xc425223388)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/txn_state.go:270 +0x48
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close(0xc425223300, 0xc25d40, 0xc42081e4b0, 0x2)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:700 +0x4a7
github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx.func1(0xc425223300, 0xc25d40, 0xc42081e4b0, 0xc4203c9280, 0xc424e9f040, 0xc420430e10)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:218 +0xcf
created by github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:200 +0x275
```

**Comment by tschottdorf** [comment]
I saw that this was added to CF&S triage -- I'll remove it as it doesn't seem to be the appropriate home for it (the "Stability" in core is only for core stability - not every stability issue needs to go there).

**Comment by awoods187** [comment]
Jordan to investigate and close.

**Comment by jordanlewis** [comment]
I can't reproduce this.
