### ISSUE TITLE
panic: stopper.go:176: runtime.errorString: runtime error: invalid memory address or nil pointer derefer...

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#26995]
https://sentry.io/cockroach-labs/cockroachdb/issues/591033321/

```
*log.safeError: stopper.go:176: runtime.errorString: runtime error: invalid memory address or nil pointer dereference
  File "github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go", line 583, in 1
  File "github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go", line 426, in processQueue
  File "github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go", line 589, in func1
  File "github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go", line 193, in func1
...
(7 additional frame(s) were not displayed)

stopper.go:176: runtime.errorString: runtime error: invalid memory address or nil pointer dereference
```

**Comment by RaduBerinde** [comment]
This crash was seen on cyan (2 and 4).

```
W180626 23:08:40.294230 3268 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {cockroach-cyan-05:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W180626 23:08:40.297999 3354 storage/raft_transport.go:590  [n2] while processing outgoing Raft queue to node 5: EOF:
W180626 23:08:40.298486 2788 storage/raft_transport.go:559  [n2] process new queue to n5
W180626 23:08:40.303413 3268 vendor/google.golang.org/grpc/clientconn.go:1429  grpc: addrConn.transportMonitor exits due to: context canceled
W180626 23:08:40.303804 235862 storage/raft_transport.go:586  [n2] creating batch client for node 5 failed: rpc error: code = Canceled desc = grpc: the client connection is closing
E180626 23:08:40.303879 235862 util/log/crash_reporting.go:203  [n2] a panic has occurred!
runtime error: invalid memory address or nil pointer dereference

goroutine 235862 [running]:
runtime/debug.Stack(0x41ab960, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).printPanicToFile(0x41ab960, 0x2431f20, 0x3c09d30)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:921 +0x137
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x2c14ae0, 0xc42b048780, 0xc420493980, 0x2431f20, 0x3c09d30, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:218 +0x239
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420826000, 0x2c14ae0, 0xc42b048780)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:176 +0xe4
panic(0x2431f20, 0x3c09d30)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).startProcessNewQueue.func1.1(0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:583 +0x22
panic(0x2431f20, 0x3c09d30)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).processQueue(0xc4208ffee0, 0xc400000005, 0xc42f545380, 0xc427241300, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:426 +0x68
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).startProcessNewQueue.func1(0x2c14ae0, 0xc42b048780)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:589 +0x304
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4262a2a30, 0xc420826000, 0xc42b048750)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:186 +0xad
```

**Comment by RaduBerinde** [comment]
[cyan-2.log](https://github.com/cockroachdb/cockroach/files/2139636/cyan-2.log)
[cyan-4.log](https://github.com/cockroachdb/cockroach/files/2139637/cyan-4.log)

**Comment by RaduBerinde** [comment]
This looks like new code, from #26977.
