### ISSUE TITLE
3 Node Cluster becomes unavailable after losing access to liveness table

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#27076]
Reported by @derkan on Gitter:

```
Erkan Durmuş @derkan 10:48
Hi, I have critical problem. My 3 nodes cluster lost its node3 suddenly and other nodes became unaccessible. Here is a repeating log from node2:
 W180629 14:45:33.436861 206 storage/replica_range_lease.go:463  can't determine lease status due to node liveness error: node not in the liveness table
W180629 14:45:33.631787 556 storage/node_liveness.go:501  [n3,hb] slow heartbeat took 4.5s
W180629 14:45:33.631810 556 storage/node_liveness.go:438  [n3,hb] failed node liveness heartbeat: context deadline exceeded
W180629 14:45:34.282845 538 storage/store.go:1456  [n3,s3,r7/2:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r7: replica (n3,s3):2 not lease holder; lease holder unknown
But I can not start node 3, it waits at line:
I180629 14:35:33.143610 24 storage/engine/rocksdb.go:552  opening rocksdb instance at "/DB/CRDB/data"
I upgraded to 2.0.3 (pre version: 2.0.2) but same problem is going on.
Node1 is also waits forever at :
I180629 14:34:26.751220 8 storage/engine/rocksdb.go:552  opening rocksdb instance at "/db/CRDB/data"
DB cluster is completely not worlking, what do you suggest?

Erkan Durmuş @derkan 10:55
Any help is appreciated. @knz ? @mberhault?

tim-o @tim-o 11:12
@derkan - which version are you running? Let’s get a ticket open to investigate. One second.

Erkan Durmuş @derkan 11:13
Hi Tim, thanks for response. All 3 instances were waiting for about 40 minutes, and suddenly they began to communicate each other and cluster is stable for now.
There wasn't a network problem, I cross checked among nodes.
Even run telnet to 25762 ports to check connectivity. There was no problem.

tim-o @tim-o 11:14
Hey @derkan - glad to hear it’s back up and stable, though this sounds like a bad bug. Are you on 2.0.3?

Erkan Durmuş @derkan 11:15
Yes

tim-o @tim-o 11:16
ah, just saw the line sorry - so you upgraded the cluster while n3 was down?

Erkan Durmuş @derkan 11:16
But 3rd node was down while it was 2.0.2. I also upgraded exe to 2.0.3 after failed to start node3.

tim-o @tim-o 11:17
Are all nodes now at 2.0.3? Or just n3?

Erkan Durmuş @derkan 11:17
Node2 claimed not to gossip about 40 min although all nodes were up & waiting.
Yes all nodes are now 2.0.3
```

**Comment by tim-o** [comment]
```
Second node was only complaining that it can not gossip to node3. But node2&node1 was up and waiting at log line(..rocksdb.go:552 opening rocksdb instance at "/db/CRDB/data"). They waited about 40 min. and after suddenly began to speak each other
```

**Comment by derkan** [comment]
[crdblogs.tar.gz](https://github.com/cockroachdb/cockroach/files/2149957/crdblogs.tar.gz)
Node DB logs are here.

**Comment by derkan** [comment]
I found that node3 had log rollover after successfully recovered. This is previous log file:
[node3-pre.log](https://github.com/cockroachdb/cockroach/files/2149990/node3-pre.log)

**Comment by tim-o** [comment]
Thanks @derkan  - it looks like these are from after the incident (15:12 onward). Do you have the logs from ~14:30 - 15:00?

**Comment by tim-o** [comment]
Looks like we had the same thought - if you can get logs from all nodes while the issue was ongoing, it'd be really helpful.

**Comment by derkan** [comment]
OK, all logs of today: 
[CRDB_logs.tar.gz](https://github.com/cockroachdb/cockroach/files/2150022/CRDB_logs.tar.gz)

**Comment by derkan** [comment]
I forgot to mention, node3 was complaining about soft file limit, I've increased it with:
`fs.file-max=500000`
just before last run( that after~40mins cluster started)

**Comment by tim-o** [comment]
Hey @derkan - These logs seem to indicate that ~13:50, when node2's logs start, that n1 was also down. Is that right? From `cockroach.db1.root.2018-06-29T13_49_15Z.003662.log`:
```
I180629 13:49:15.740449 1 cli/start.go:923  CockroachDB CCL v2.0.3 (x86_64-unknown-linux-gnu, built 2018/06/18 16:11:33, go1.10)
I180629 13:49:15.841988 1 server/config.go:330  available memory from cgroups (8.0 EiB) exceeds system memory 126 GiB, using system memory
I180629 13:49:15.842001 1 server/config.go:430  system total memory: 126 GiB
I180629 13:49:15.842057 1 server/config.go:432  server configuration:
max offset             500000000
cache size             128 MiB
SQL memory pool size   128 MiB
scan interval          10m0s
scan max idle time     200ms
event log enabled      true
I180629 13:49:15.842075 1 cli/start.go:796  process identity: uid 0 euid 0 gid 0 egid 0
I180629 13:49:15.842085 1 cli/start.go:461  starting cockroach node
I180629 13:49:15.844528 69 storage/engine/rocksdb.go:552  opening rocksdb instance at "/db/CRDB/data/cockroach-temp833747756"
I180629 13:49:15.900509 69 server/server.go:734  [n?] monitoring forward clock jumps based on server.clock.forward_jump_check_enabled
I180629 13:49:15.901603 69 storage/engine/rocksdb.go:552  opening rocksdb instance at "/db/CRDB/data"
E180629 13:49:16.581406 128 server.go:2921  http: TLS handshake error from 185.92.12.7:37114: EOF
I180629 14:00:22.670231 1 cli/start.go:655  received signal 'terminated'
```
It looks like you're trying to start the node, it hangs for a few minutes and is then manually killed.

**Comment by tim-o** [comment]
So from what we can glean from the logs so far, it looks like two nodes (n1 and n3) were down at the same time - that's what lead to the loss of quorum. It doesn't explain why initiating RocksDB took so long, though.

@derkan - when did the cluster start running into issues? The earliest logs from n3 at 12:49 and n1 at 13:17 indicate that the cluster was already unhealthy at that point.

**Comment by derkan** [comment]
@tim-o  you are right. That was at 1 day before! But we realized problem when node2 stops serving after loosing other nodes!
# Timeline is: 
`W180627 22:04:45.308924` node1 had an exception. (it was ver 2.0.2 at that time) But this is not related with current problem:
```
W180627 22:04:45.308924 268 storage/engine/rocksdb.go:1755  batch [178/45241/0] commit took 578.931198ms (>500ms):
goroutine 268 [running]:
runtime/debug.Stack(0x2b574d40, 0xed2c600fc, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc42abb2240, 0xc43989bc00, 0x21b, 0x400)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1756 +0x128
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc42abb2240, 0xed2c60001, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1679 +0x6fe
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4252fe700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3575 +0x5ae
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc4252fe700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3359 +0xdb
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc420b12c00, 0x2612180, 0xc425874240, 0x84)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3846 +0xda
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420978ab0, 0x2612180, 0xc425874240)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:215 +0x259
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2612180, 0xc425874240)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4258525b0, 0xc42020ecf0, 0xc4258525a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xad
W180627 22:04:45.309365 268 storage/store.go:3857  [n1,s1] handle raft ready: 0.6s [processed=0]
```
## NODE1: Last message appears many times. But node1 continued working normally until this log:
```
I180629 12:29:45.782891 584 server/status/runtime.go:219  [n1] runtime stats: 1.8 GiB RSS, 588 goroutines, 438 MiB/3.1 GiB/3.8 GiB GO alloc/idle/total, 171 MiB/508 MiB CGO alloc/total, 503.77cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (2x)
E180629 12:29:51.627550 1379851340 sql/distsqlrun/server.go:476  [n1] query execution canceled
E180629 12:29:51.627571 1379851413 sql/distsqlrun/server.go:476  [n1] query execution canceled
E180629 12:29:51.627577 1379851414 sql/distsqlrun/server.go:476  [n1] query execution canceled
E180629 12:29:51.627644 1379851339 sql/distsqlrun/server.go:476  [n1] query execution canceled
E180629 12:29:51.627579 1379851388 sql/distsqlrun/server.go:476  [n1] query execution canceled
E180629 12:29:51.627559 1379851386 sql/distsqlrun/server.go:476  [n1] query execution canceled
I180629 12:29:51.649881 1379851444 sql/distsqlrun/hashjoiner.go:213  [client=185.92.12.7:9736,user=faxmax,n1,HashJoiner] buffer phase error [n1] communication error: rpc error: code = Canceled desc = context canceled
I180629 12:29:51.649891 1379851445 sql/distsqlrun/hashjoiner.go:213  [client=185.92.12.7:9736,user=faxmax,n1,HashJoiner] buffer phase error [n1] communication error: rpc error: code = Canceled desc = context canceled
W180629 12:29:51.698923 114617523 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {185.92.12.9:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
```
These errors continued until node1 shutdown itself:
```
29 13:17:19.995192 1380206333 util/stop/stopper.go:291  [drain,n1,s1,r1733/1:/System/tsd/cr.node.sys.cpu.uâ<80>¦] stopper throttling task from storage.Store: draining replica due to semaphore
W180629 13:17:20.074102 1380208333 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {185.92.12.9:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W180629 13:17:20.074404 1380208333 vendor/google.golang.org/grpc/clientconn.go:830  Failed to dial 185.92.12.9:26257: context canceled; please retry.
I180629 13:17:24.181988 1380206334 cli/start.go:725  51 running tasks
I180629 13:17:25.005826 1380206333 util/stop/stopper.go:470  [server drain process] quiescing; tasks left:
50     [async] drain
1      [async] storage.replica consistency checker: processing replica
W180629 13:17:25.005920 1241600439 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {185.92.12.8:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
E180629 13:17:25.006063 759903157 storage/consistency_queue.go:111  [replica consistency checker,n1,s1,r1411/1:/Table/428/1/"\xab{]%Bâ<80>¦-\x8â<80>¦}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I180629 13:17:25.006258 1380206333 util/stop/stopper.go:470  [server drain process] quiescing; tasks left:
44     [async] drain
1      [async] storage.replica consistency checker: processing replica
W180629 13:17:25.006471 1241600439 vendor/google.golang.org/grpc/clientconn.go:1277  grpc: addrConn.transportMonitor exits due to: context canceled
I180629 13:17:25.007032 1380206333 util/stop/stopper.go:470  [server drain process] quiescing; tasks left:
40     [async] drain
1      [async] storage.replica consistency checker: processing replica
I180629 13:17:25.007467 1380206333 util/stop/stopper.go:470  [server drain process] quiescing; tasks left:
33     [async] drain
1      [async] storage.replica consistency checker: processing replica
I180629 13:17:25.044943 1380206333 storage/engine/rocksdb.go:686  closing rocksdb instance at "/db/CRDB/data/cockroach-temp113462760"
I180629 13:17:25.249731 1380206333 storage/engine/rocksdb.go:686  closing rocksdb instance at "/db/CRDB/data"
I180629 13:17:25.323981 1 cli/start.go:769  server drained and shutdown completed
```

This is the all of log file for node1 where it stopped:
[cockroach.db1.root.2018-06-27T12_09_35Z.011976.log.gz](https://github.com/cockroachdb/cockroach/files/2150270/cockroach.db1.root.2018-06-27T12_09_35Z.011976.log.gz)

## NODE3: And this is where node3 has an issue:
```
E180629 12:29:50.619168 1035005857 sql/conn_executor.go:514  [n2,client=185.92.12.7:48128,user=faxmax] a SQL panic has occurred while executing "RELEASE SAVEPOINT cockroach_restart": event TxnReleased{} inappropriate in current state Open{ImplicitTxn:false, RetryIntent:false}
E180629 12:29:50.619298 1035005857 util/log/crash_reporting.go:185  [n2,client=185.92.12.7:48128,user=faxmax] a panic has occurred!
E180629 12:29:51.369321 1035005857 util/log/crash_reporting.go:451  [n2,client=185.92.12.7:48128,user=faxmax] Reported as error 9555a6e7af9342dd9834d5c104e75433
panic: event TxnReleased{} inappropriate in current state Open{ImplicitTxn:false, RetryIntent:false} [recovered]
    panic: panic while executing 1 statements: RELEASE SAVEPOINT cockroach_restart; caused by event TxnReleased{} inappropriate in current state Open{ImplicitTxn:false, RetryIntent:false}

goroutine 1035005857 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc42a481000, 0x26120c0, 0xc425e2df80, 0x216d700, 0xc42519cfa0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:528 +0x365
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2(0xc42a481000, 0x26120c0, 0xc425e2df80)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:489 +0x61
panic(0x216d700, 0xc42519cfa0)
    /usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper(0xc42a481000, 0x25f4060, 0x3a38678, 0x0, 0x0, 0x7f71404bc680, 0xc49f9eb900, 0x2c, 0x0, 0x0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1649 +0x6dc
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc42a481000, 0x26120c0, 0xc425e2df80, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1029 +0xb1e
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420390380, 0x26120c0, 0xc425e2df80, 0xc426dff01d, 0xe, 0xc426dff00d, 0x6, 0xc426dff03d, 0x9, 0x25fb3c0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:491 +0xf9e
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc420390380, 0x26120c0, 0xc425e2df80, 0xc42adc6540, 0x5400, 0x15000, 0xc4208b3150, 0xc436d3d090, 0xc43de18a40, 0xc436d3d080)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:260 +0xfc
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:259 +0xf14
```
And corresponding log file for node3 is: 
[cockroach.db.root.2018-06-28T00_56_44Z.026616.log.gz](https://github.com/cockroachdb/cockroach/files/2150276/cockroach.db.root.2018-06-28T00_56_44Z.026616.log.gz)

# NODE2: This is from log of node2
```
I180629 12:29:48.996105 149309896 util/mon/bytes_usage.go:576  [n3,client=185.92.12.7:57506] conn: bytes usage increases to 4.1 MiB (+107520)
E180629 12:29:51.626722 149309709 sql/distsqlrun/server.go:476  [n3] query execution canceled
E180629 12:29:51.626750 149309829 sql/distsqlrun/server.go:476  [n3] query execution canceled
E180629 12:29:51.626761 149309711 sql/distsqlrun/server.go:476  [n3] query execution canceled
E180629 12:29:51.626775 149309712 sql/distsqlrun/server.go:476  [n3] query execution canceled
E180629 12:29:51.626850 149310384 sql/distsqlrun/server.go:476  [n3] query execution canceled
E180629 12:29:51.626884 149310498 sql/distsqlrun/joinreader.go:347  [n3,JoinReader=428] scan error: context canceled
I180629 12:29:51.630276 149309812 sql/distsqlrun/hashjoiner.go:213  [n3,HashJoiner] buffer phase error [n3] communication error: rpc error: code = Canceled desc = context canceled
I180629 12:29:51.630295 149309813 sql/distsqlrun/hashjoiner.go:213  [n3,HashJoiner] buffer phase error [n3] communication error: rpc error: code = Canceled desc = context canceled
I180629 12:29:51.630301 149310500 sql/distsqlrun/hashjoiner.go:213  [n3,HashJoiner] buffer phase error [n3] communication error: rpc error: code = Canceled desc = context canceled
W180629 12:29:51.646912 11661 storage/raft_transport.go:465  [n3] raft transport stream to node 2 failed: rpc error: code = Unavailable desc = transport is closing
W180629 12:29:51.652436 8072 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {185.92.12.9:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W180629 12:29:51.652457 8072 vendor/google.golang.org/grpc/clientconn.go:1277  grpc: addrConn.transportMonitor exits due to: context canceled
W180629 12:29:52.262927 149310544 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {185.92.12.9:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 185.92.12.9:26257: connect: connection refused". Reconnecting...
```
this is node2 log file: 
[cockroach.db2.root.2018-06-28T10_36_32Z.011122.log.gz](https://github.com/cockroachdb/cockroach/files/2150293/cockroach.db2.root.2018-06-28T10_36_32Z.011122.log.gz)

**Comment by RaduBerinde** [comment]
The initial stack traces are informative, they just show some requests that were slow. 
The panic on node 3 is the big issue here. This looks the same with #24433 except that the fix for that is in v2.0.2. Do we know for sure that the version was 2.0.2 at the time of that panic?

Do we have any idea why node 1 was shut down? AFAIK cockroach itself wouldn't just decide to shutdown on its own.

**Comment by RaduBerinde** [comment]
From this line in the stack trace, I can tell that this build is earlier than v2.0.2:
`/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1649`
v2.0.1: https://github.com/cockroachdb/cockroach/blob/v2.0.1/pkg/sql/conn_executor.go#L1649
v2.0.2: https://github.com/cockroachdb/cockroach/blob/v2.0.2/pkg/sql/conn_executor.go#L1649

As far as we know, this crash is fixed in 2.0.2+

I do wonder how this bug was triggered though - what kind of workload are you running?

**Comment by tim-o** [comment]
Ok, so confirmed that `cockroach.db.root.2018-06-28T00_56_44Z.026616.log` (n3 that delivered the stack trace) was running v2.0.0 at the time. So the upgrade should prevent the crash from happening again.

@derkan, at this point it sounds like there were three issues:
1) Crash on n1, v2.0.0 that was (we presume) fixed by an upgrade to 2.0.3.
2) Long delays restarting nodes due to rocksdb hanging for ~15-20 mins
3) Data unavailability after n3 dropped.

3) is expected given a 3 node cluster and 2 down nodes. 1) should be fixed, though it seems like it'd be easy enough to reproduce if it weren't. If you do end up needing to restart a node for any reason, adding `--vmodule=rocksdb=3` to the start command will add a lot more information about what's going on between `opening rocksdb instance` and `1 storage engine initialized`.

**Comment by derkan** [comment]
@RaduBerinde I've checked syslog, but couldn't find any error or warning for that time or some time before. Work load is low on this system(single active database is used with 60 session) used as backend db for fax system.

**Comment by derkan** [comment]
Is it possible to monitor DB instances at critical problems like this one(loosing a node)? Maybe sentry integration or mailing?

**Comment by tschottdorf** [comment]
@derkan does this long startup time reproduce? We've seen something similar in situations in which a large table or database was dropped (#24029), with fixes coming up in the next 2.0 patch release. Does this by any chance apply to your situation?

**Comment by derkan** [comment]
@tschottdorf  Never reproduced again. 

No large tables created nor DB was dropped. But, we didn't realize that 1st instance was down for a while. We saw the problem when 3rd instance was also down. I think both instances were needing too much synchronization, that made us to wait, and by default not sync rocksdb log is shown, I've assumed that db was stuck. 

Now I've added a simple informer script as @tim-o  suggested to get info when a node is down.

Thanks everyone!
