### ISSUE TITLE
sql: panic: comparing uncomparable type types.TTuple

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#27293]
> Is this a question, feature request, or bug report?

Bug report.

> **BUG REPORT**

>1. Please supply the header (i.e. the first few lines) of your most recent
>   log file **for each node in your cluster**. On most unix-based systems
>   running with defaults, this boils down to the output of
>
>     grep -F '[config]' cockroach-data/logs/cockroach.log

```shell
$ grep -F '[config]' /tmp/node*/logs/cockroach.log                                                                                                        

/tmp/node0/logs/cockroach.log:I180709 18:01:11.481544 1 util/log/clog.go:1131  [config] file created at: 2018/07/09 18:01:11
/tmp/node0/logs/cockroach.log:I180709 18:01:11.481544 1 util/log/clog.go:1131  [config] running on machine: richards-mbp
/tmp/node0/logs/cockroach.log:I180709 18:01:11.481544 1 util/log/clog.go:1131  [config] binary: CockroachDB CCL v2.1.0-alpha.20180702 (x86_64-apple-darwin13, built 2018/07/02 14:40:21, go1.10)
/tmp/node0/logs/cockroach.log:I180709 18:01:11.481544 1 util/log/clog.go:1131  [config] arguments: [/Users/rloveland/work/binaries/v2.1-alpha.20180702/cockroach start --max-sql-memory=0.25 --insecure --store=/tmp/node0 --host=localhost --port=26257 --http-port=8888 --join=localhost:26257,localhost:26258,localhost:26259]
/tmp/node0/logs/cockroach.log:I180709 18:01:14.645470 15 cli/start.go:606  [config] clusterID: 156f9ffb-1912-4180-8e47-e1f4ea215bef
/tmp/node1/logs/cockroach.log:I180709 18:01:11.478448 1 util/log/clog.go:1131  [config] file created at: 2018/07/09 18:01:11
/tmp/node1/logs/cockroach.log:I180709 18:01:11.478448 1 util/log/clog.go:1131  [config] running on machine: richards-mbp
/tmp/node1/logs/cockroach.log:I180709 18:01:11.478448 1 util/log/clog.go:1131  [config] binary: CockroachDB CCL v2.1.0-alpha.20180702 (x86_64-apple-darwin13, built 2018/07/02 14:40:21, go1.10)
/tmp/node1/logs/cockroach.log:I180709 18:01:11.478448 1 util/log/clog.go:1131  [config] arguments: [/Users/rloveland/work/binaries/v2.1-alpha.20180702/cockroach start --max-sql-memory=0.25 --insecure --store=/tmp/node1 --host=localhost --port=26258 --http-port=8889 --join=localhost:26257,localhost:26258,localhost:26259]
/tmp/node1/logs/cockroach.log:I180709 18:01:15.713272 16 cli/start.go:606  [config] clusterID: 156f9ffb-1912-4180-8e47-e1f4ea215bef
/tmp/node2/logs/cockroach.log:I180709 18:01:11.486405 1 util/log/clog.go:1131  [config] file created at: 2018/07/09 18:01:11
/tmp/node2/logs/cockroach.log:I180709 18:01:11.486405 1 util/log/clog.go:1131  [config] running on machine: richards-mbp
/tmp/node2/logs/cockroach.log:I180709 18:01:11.486405 1 util/log/clog.go:1131  [config] binary: CockroachDB CCL v2.1.0-alpha.20180702 (x86_64-apple-darwin13, built 2018/07/02 14:40:21, go1.10)
/tmp/node2/logs/cockroach.log:I180709 18:01:11.486405 1 util/log/clog.go:1131  [config] arguments: [/Users/rloveland/work/binaries/v2.1-alpha.20180702/cockroach start --max-sql-memory=0.25 --insecure --store=/tmp/node2 --host=localhost --port=26259 --http-port=8890 --join=localhost:26257,localhost:26258,localhost:26259]
/tmp/node2/logs/cockroach.log:I180709 18:01:15.709711 52 cli/start.go:606  [config] clusterID: 156f9ffb-1912-4180-8e47-e1f4ea215bef
```

2. Please describe the issue you observed:

- What did you do?

Ran this (possibly ludicrous) query on the "movr" data set, on a local 3-node cluster running on a MacBook:

~~~sql
SELECT *, COUNT(*) OVER (PARTITION BY name ORDER BY "number of rides") AS "total number OF rides" FROM (SELECT distinct(name,users.city) as "name",
            COUNT(*) OVER (PARTITION BY name) AS "number of rides"
     FROM users JOIN rides ON users.id = rides.rider_id) LIMIT 24;
~~~

> - What did you expect to see?

Output returned to the SQL prompt - either a result, or a user-level error message.

> - What did you see instead?

A SQL panic about "comparing uncomparable type types.TTuple" (full output below), followed by a dead node.

```
* ERROR: [n1,client=127.0.0.1:62793,user=root] a SQL panic has occurred while executing "SELECT *, count(*) OVER (PARTITION BY name ORDER BY \"number of rides\") AS \"total number OF rides\" FROM (SELECT DISTINCT (name, users.city) AS name, count(*) OVER (PARTITION BY name) AS \"number of rides\" FROM users JOIN rides ON users.id = rides.rider_id) LIMIT 24": runtime error: comparing uncomparable type types.TTuple
*
*
* ERROR: [n1,client=127.0.0.1:62793,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT *, count(*) OVER (PARTITION BY _ ORDER BY _) AS _ FROM (SELECT DISTINCT (_, _._) AS _, count(*) OVER (PARTITION BY _) AS _ FROM _ JOIN _ ON _._ = _._) LIMIT _; caused by runtime error: comparing uncomparable type types.TTuple

goroutine 5381 [running]:
runtime/debug.Stack(0x65549a0, 0xc42923e580, 0x3)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x65549a0, 0xc42923e580, 0xc4205f7980, 0x5f31c60, 0xc429c74540, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc42ee7c000, 0x65549a0, 0xc42923e580, 0x5d766e0, 0xc4204299e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:662 +0x2df
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc42ee7c000, 0x65549a0, 0xc42923e580)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:411 +0x61
panic(0x5d766e0, 0xc4204299e0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).addOrReuseRender(0xc433f391e0, 0x607525c, 0x8, 0x65649a0, 0xc429c61ce0, 0x0, 0x6562d80, 0xc42f3ca0c0, 0xc42ee7c401, 0x607525c)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/targets.go:120 +0x16d
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).addOrReuseRenders(0xc433f391e0, 0xc429c74240, 0x1, 0x1, 0xc4204299d0, 0x1, 0x1, 0x6564a01, 0x7895e40, 0xc4204d4a28, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/targets.go:140 +0x147
github.com/cockroachdb/cockroach/pkg/sql.(*planner).constructWindowDefinitions(0xc42ee7c430, 0x6554a60, 0xc429c61a10, 0xc42c22ac60, 0xc429a27c20, 0xc433f391e0, 0x7895e40, 0x6556a20)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/window.go:295 +0x422
github.com/cockroachdb/cockroach/pkg/sql.(*planner).window(0xc42ee7c430, 0x6554a60, 0xc429c61a10, 0xc429a27c20, 0xc433f391e0, 0x0, 0x6548260, 0xc433f391e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/window.go:116 +0x188
github.com/cockroachdb/cockroach/pkg/sql.(*planner).SelectClause(0xc42ee7c430, 0x6554a60, 0xc429c61a10, 0xc429a27c20, 0x0, 0x0, 0x0, 0xc42032a3a0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:280 +0x58c
github.com/cockroachdb/cockroach/pkg/sql.(*planner).Select(0xc42ee7c430, 0x6554a60, 0xc429c61a10, 0xc42fbc1600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:126 +0x580
github.com/cockroachdb/cockroach/pkg/sql.(*planner).newPlan(0xc42ee7c430, 0x6554a60, 0xc429c61a10, 0x6557220, 0xc42fbc1600, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:729 +0xfad
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc42ee7c430, 0x6554a60, 0xc429c61a10, 0x6557220, 0xc42fbc1600, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:299 +0x100
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc42ee7c000, 0x6554a60, 0xc429c61a10, 0x6557220, 0xc42fbc1600, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:706 +0xb5d
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc42ee7c000, 0x6554a60, 0xc429c61a10, 0x6557220, 0xc42fbc1600, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:401 +0xb2b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc42ee7c000, 0x6554a60, 0xc429c61a10, 0x6557220, 0xc42fbc1600, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc42ee7c000, 0x65549a0, 0xc42923e580, 0xc429d825e0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1076 +0x2055
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc42071a000, 0x65549a0, 0xc42923e580, 0xc4349bf01b, 0x4, 0xc4349bf00d, 0x4, 0xc4349bf031, 0x4, 0x6539620, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:413 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc42071a000, 0x65549a0, 0xc42923e580, 0xc420872e00, 0x5400, 0x15000, 0xc4200eaa80, 0xc429d825e0, 0xc429d825d0, 0xc42f71d830, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:267 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:266 +0xf27

*
* ERROR: [n1,client=127.0.0.1:62793,user=root] Reported as error b4cc463aa2244c2aa43c79f8b52d6b19
*
driver: bad connection
Error: driver: bad connection
Failed running "sql"
```

**Comment by justinj** [comment]
I think @yuzefovich is the expert on window functions now?

**Comment by jordanlewis** [comment]
Assigning @knz as he promised to take a look at #27300.

**Comment by knz** [comment]
Please do not use the pronoun "you". 

I have personally no idea nor plans about this.

The position of the issue in the project should tell you all there is to know: It's one step ahead of the black hole "backlog" but it's not in any milestone nor in the active bug pile, so that means "no plan".

I see no reason to look at this right now unless there is further input that pulls it ahead of the many high-priority issues we're dealing with right now. If you have such input available, please share it, then only we can re-arrange the work to do.

**Comment by jordanlewis** [comment]
I think that it would be good to fix this from panicking at the very least before 19.1.

**Comment by jordanlewis** [comment]
Interestingly, I can no longer reproduce the panic from @rmloveland's original query.

**Comment by yuzefovich** [comment]
Here is an easy reproduction:
```
SELECT
    min(a) OVER (PARTITION BY (a, a)) AS min,
    max(a) OVER (PARTITION BY (a, a)) AS max
FROM
    (SELECT 1 AS a);
```

**Comment by jordanlewis** [comment]
```
root@127.0.0.1:61401/defaultdb> SELECT
                             ->     min(a) OVER (PARTITION BY (a, a)) AS min,
                             ->     max(a) OVER (PARTITION BY (a, a)) AS max
                             -> FROM
                             ->     (SELECT 1 AS a);
  min | max
+-----+-----+
    1 |   1
(1 row)
```
