### ISSUE TITLE
teamcity:  TestShowTraceReplica possibly flaky

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#27517]
https://teamcity.cockroachdb.com/viewLog.html?buildId=777160&buildTypeId=Cockroach_UnitTests

```
[/UPSERT_INTO_d.t2_VALUES_(1)] show_trace_replica_test.go:101: condition failed to evaluate within 45s: UPSERT INTO d.t2 VALUES (1): got [[4 4]] expected [[2 2]]
	goroutine 160767 [running]:
	runtime/debug.Stack(0xa7a358200, 0xc4254cbf78, 0x2936b40)
		/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
	github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x29837e0, 0xc423792000, 0xc424d85f78)
		/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:38 +0x7d
	github.com/cockroachdb/cockroach/pkg/sql_test.TestShowTraceReplica.func2(0xc423792000)
		/go/src/github.com/cockroachdb/cockroach/pkg/sql/show_trace_replica_test.go:101 +0x64
	testing.tRunner(0xc423792000, 0xc42494ca20)
		/usr/local/go/src/testing/testing.go:777 +0xd0
	created by testing.(*T).Run
		/usr/local/go/src/testing/testing.go:824 +0x2e0
```

may be related to #27497  which was causing a bunch of failure in that specific test last night.

cc @petermattis @a-robinson

**Comment by tschottdorf** [comment]
Closing for https://github.com/cockroachdb/cockroach/issues/27599
