### ISSUE TITLE
storage: abort: UncollapsedRangeDelMap::ShouldDeleteRange unimplemented

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#27522]
The above abort is coming out of a new RocksDB code path I just added this is supposed to never fire. Thankfully, we have a stacktrace:

```
goroutine 168 [syscall]:
non-Go function
        pc=0x7f2969260428
non-Go function
        pc=0x7f2969262029
_ZN7rocksdb22UncollapsedRangeDelMap17ShouldDeleteRangeERKNS_5SliceES3_m
        /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/range_del_aggregator.cc:73 pc=0x1f16e73
_ZN7rocksdb18RangeDelAggregator17ShouldDeleteRangeERKNS_5SliceES3_m
        /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/range_del_aggregator.cc:489 pc=0x1f1563d
NewFileIterator
        /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/version_set.cc:546 pc=0x1f296d8
InitFileIterator
        /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/version_set.cc:727 pc=0x1f296d8
SkipEmptyFileForward
        /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/version_set.cc:668 pc=0x1f29c52
OverlapWithIterator
        /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/version_set.cc:88 pc=0x1f228cf
_ZN7rocksdb7Version24OverlapWithLevelIteratorERKNS_11ReadOptionsERKNS_10EnvOptionsERKNS_5SliceES9_iPb
        /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/version_set.cc:1109 pc=0x1f35631
runtime.cgocall(0x1d63110, 0xc426cfc800, 0x29)
        /usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc426cfc7c0 sp=0xc426cfc788 pc=0x6ab514
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBIngestExternalFiles(0x7f2961f04850, 0xc4204eac58, 0x1, 0x101, 0x0, 0x0)
        _cgo_gotypes.go:653 +0x4d fp=0xc426cfc800 sp=0xc426cfc7c0 pc=0x113d7ad
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).IngestExternalFiles.func2(0xc4204eac58, 0x1, 0x1, 0x7f2961f04850, 0xc4204eac58, 0x1, 0x1800101, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2672 +0x14b fp=0xc426cfc870 sp=0xc426cfc800 pc=0x1156d2b
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).IngestExternalFiles(0xc4201ad6c0, 0x2cabac0, 0xc4250b89f0, 0xc42038e800, 0x1, 0x1, 0x18b8001, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2672 +0x178 fp=0xc426cfc8f8 sp=0xc426cfc870 pc=0x114fe18
github.com/cockroachdb/cockroach/pkg/storage.addSSTablePreApply(0x2cabac0, 0xc4250b89f0, 0xc42049f980, 0x2cdcb40, 0xc4201ad6c0, 0x2cbe9e0, 0xc42719fac0, 0x6, 0x10, 0xc43f9a2000, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:434 +0x2b9 fp=0xc426cfcc60 sp=0xc426cfc
```

I'll get to this ASAP (though perhaps not tonight). Filing an issue in case anyone else stumbles across it. Likely only happens for restore/import (given the stacktrace).

Cc @benesch

**Comment by petermattis** [comment]
Removing the abort reduces the severity to "I-should-do-this-before-2.1-is-released".

**Comment by petermattis** [comment]
I took another look at this and I've decided not to do it at all. `UncollapsedRangeDelMap::ShouldDeleteRange` is only used from the sstable ingestion path which is both a rare occurrence and one that isn't worth optimizing even when it happens.
