### ISSUE TITLE
storage: asyncGossipStore called before gossip connected

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#27705]
Introduced in https://github.com/cockroachdb/cockroach/pull/26907 and observed in https://github.com/cockroachdb/cockroach/issues/27629#issuecomment-405946227. It seems that the compactor calls into `(*Store).asyncGossipStore` too early:

```
I180718 14:12:00.336707 21 storage/stores.go:222  [n1] read 4 node addresses from persistent storage
I180718 14:12:00.336932 21 server/node.go:707  [n1] connecting to gossip network to verify cluster ID...
I180718 14:12:00.869702 227 gossip/client.go:129  [n1] started gossip client to 127.0.0.1:26259
I180718 14:12:15.340966 219 storage/compactor/compactor.go:325  [n1,s1,compactor] purging suggested compaction for range /Min - /System/"" that contains live data
I180718 14:12:15.342723 219 storage/compactor/compactor.go:370  [n1,s1,compactor] processing compaction #1-6/6 (/Table/SystemConfigSpan/Start-/Table/22) for 59 KiB (reasons: size=false used=true avail=false)
I180718 14:12:15.344611 219 storage/compactor/compactor.go:386  [n1,s1,compactor] processed compaction #1-6/6 (/Table/SystemConfigSpan/Start-/Table/22) for 59 KiB in 0.0s
F180718 14:12:15.344913 241 storage/store.go:1693  [n1,s1,compactor] not connected to gossip
goroutine 241 [running]:
```

Honestly I don't think many of the callers are even aware that they're not supposed to be calling this that early:

```
$ git grep asyncGossipStore
pkg/storage/store.go:                   s.asyncGossipStore(ctx, "compactor-initiated rocksdb compaction", false /* useCached */)
pkg/storage/store.go:func (s *Store) asyncGossipStore(ctx context.Context, reason string, useCached bool) {
pkg/storage/store.go:           s.asyncGossipStore(ctx, "capacity change", true /* useCached */)
pkg/storage/store.go:           s.asyncGossipStore(context.TODO(), "writes-per-second change", false /* useCached */)
```

In `*server.Node`, we start the stores before waiting for gossip to connect. Which probably makes sense, but then we shouldn't have a random Fatal in Store in code that's opportunistically called from various moving parts.

We could just fix the compactor callsite and call it a day, but this code seems spaghetti enough to do something about it or it'll turn around and bite us again.

**Comment by tschottdorf** [comment]
Ben for figuring out what to do.

**Comment by bdarnell** [comment]
I think this just shouldn't be a Fatal in GossipStore; just make it a no-op if we try to gossip the store too early.
