### ISSUE TITLE
raft_transport gets confused

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2771]
The following test appears to have failed:

[#8281](https://circleci.com/gh/cockroachdb/cockroach/8281):

```
E1005 20:45:43.429656 15532 acceptance/localcluster/localcluster.go:360  node=1 status=start
E1005 20:45:43.429735 15532 acceptance/localcluster/localcluster.go:360  node=2 status=create
E1005 20:45:43.429753 15532 acceptance/localcluster/localcluster.go:360  node=2 status=start
I1005 20:45:48.495805 15532 acceptance/gossip_peerings_test.go:147  waiting for range replication
I1005 20:45:48.496683 15532 acceptance/replication_test.go:53  waiting for first range to have 3 replicas
panic: test timed out after 5m0s

goroutine 90 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0xb413d0, 0xf0dfc0, 0x7, 0x7, 0xa50c01)
	/usr/local/go/src/testing/testing.go:562 +0x8ad

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
not much to be done, server simply doesn't respond and we don't have its logs (yet).

**Comment by bdarnell** [comment]
The logs are there, it's just user-hostile to do anything with them right now. The raft transport is getting confused. I think it's been broken since my change to split up node/store/replica IDs and it fails whenever the first range ends up with those values mismatched.

```
E1005 16:45:43.155711 1 storage/queue.go:360  failure processing replica range=1 [""-"\xff\xff") from replicate queue: storage/allocator.go:206: unable to allocate a target store; no candidates available
E1005 16:45:43.356047 1 storage/queue.go:360  failure processing replica range=1 [""-"\xff\xff") from replicate queue: storage/allocator.go:206: unable to allocate a target store; no candidates available
E1005 16:45:43.556551 1 storage/queue.go:360  failure processing replica range=1 [""-"\xff\xff") from replicate queue: storage/allocator.go:206: unable to allocate a target store; no candidates available
I1005 16:45:43.566741 1 gossip/server.go:106  gossip: received 2 info(s) from 172.17.0.19:26257
I1005 16:45:43.567681 1 gossip/server.go:106  gossip: received 2 info(s) from 172.17.0.20:26257
E1005 16:45:43.778693 1 server/raft_transport.go:175  raft message to node 3 failed: server/raft_transport.go:87: Unable to proxy message to node: 2
E1005 16:45:43.923870 1 server/raft_transport.go:175  raft message to node 3 failed: server/raft_transport.go:87: Unable to proxy message to node: 2
E1005 16:45:44.223829 1 server/raft_transport.go:175  raft message to node 3 failed: server/raft_transport.go:87: Unable to proxy message to node: 2
E1005 16:45:44.523671 1 server/raft_transport.go:175  raft message to node 3 failed: server/raft_transport.go:87: Unable to proxy message to node: 2
E1005 16:45:44.823885 1 server/raft_transport.go:175  raft message to node 3 failed: server/raft_transport.go:87: Unable to proxy message to node: 2
E1005 16:45:45.123783 1 server/raft_transport.go:175  raft message to node 3 failed: server/raft_transport.go:87: Unable to proxy message to node: 2
E1005 16:45:45.424219 1 server/raft_transport.go:175  raft message to node 3 failed: server/raft_transport.go:87: Unable to proxy message to node: 2
E1005 16:45:45.723743 1 server/raft_transport.go:175  raft message to node 3 failed: server/raft_transport.go:87: Unable to proxy message to node: 2
```
