### ISSUE TITLE
opt: crash with null in generate_series

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#28237]
Assigning to @rytaft for triage based on `git blame`

```
root@127.0.0.1:59725/defaultdb> select * from generate_series(1, null);
*
* ERROR: [n1,client=127.0.0.1:59727,user=root] a SQL panic has occurred while executing "SELECT * FROM ROWS FROM (generate_series(1, NULL))": interface conversion: interface {} is types.tUnknown, not *memo.FuncOpDef
*
*
* ERROR: [n1,client=127.0.0.1:59727,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT * FROM ROWS FROM (generate_series(_, _)); caused by interface conversion: interface {} is types.tUnknown, not *memo.FuncOpDef

goroutine 671 [running]:
runtime/debug.Stack(0x6784600, 0xc421406440, 0x3)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6784600, 0xc421406440, 0xc4204a2c80, 0x61229a0, 0xc4215f1770, 0x1)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc4212ed300, 0x6784600, 0xc421406440, 0x5f60520, 0xc421556880)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:666 +0x2df
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc4212ed300, 0x6784600, 0xc421406440)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:413 +0x61
panic(0x5f60520, 0xc421556880)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).initZipBuild(0xc421556800, 0xc420e606c0, 0x2500000002, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:846 +0x786
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildZip(0xc421556800, 0xc420e606c0, 0x2500000002, 0x0, 0x0, 0x0, 0x0, 0x0, 0x52cfc35, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:872 +0xdf
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildRelational(0xc421556800, 0xc420e606c0, 0x2500000002, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc4216d6938)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:138 +0x11dc
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).build(0xc421556800, 0xc420e606c0, 0x2500000002, 0x52a4424, 0xc4216d6968, 0x40144b8, 0x40)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:57 +0xb1
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).Build(0xc421556800, 0xc421556800, 0xc420e60a98, 0xc420e606c0, 0x2500000002)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:46 +0x51
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc4212ed738, 0x67846c0, 0xc4215f12f0, 0x6787740, 0xc4215566c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:405 +0x631
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optionallyUseOptimizer(0xc4212ed738, 0x67846c0, 0xc4215f12f0, 0xc42025a05c, 0xe, 0x627651c, 0x9, 0x0, 0x1, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:528 +0xdb
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc4212ed300, 0x67846c0, 0xc4215f12f0, 0x6787740, 0xc4215566c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:728 +0x19e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc4212ed300, 0x67846c0, 0xc4215f12f0, 0x6787740, 0xc4215566c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:401 +0xb7e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc4212ed300, 0x67846c0, 0xc4215f12f0, 0x6787740, 0xc4215566c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc4212ed300, 0x6784600, 0xc421406440, 0xc420391330, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1080 +0x20f8
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc42022ac60, 0x6784600, 0xc421406440, 0x0, 0x0, 0xc42025a009, 0x4, 0xc42025a05c, 0xe, 0x6765380, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:415 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc42022ac60, 0x6784600, 0xc421406440, 0xc4207948c0, 0x5400, 0x15000, 0xc4208a6a80, 0xc420391330, 0xc420391320, 0xc4202f5460, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:267 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:266 +0xf04
```

**Comment by jordanlewis** [comment]
Found a fix for this in type checking
