### ISSUE TITLE
sql: how to use the Hibernate @Id column spec with `int default unique_rowid()` columns?

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#28499]
Asked on the forum here:

https://forum.cockroachlabs.com/t/hibernate-sequence-generator-returns-negative-number-and-ignore-unique-rowid/1885

```
my class now looks like this
{code}
@Entity
@Table(name = “Issue”)
data class IssueEntity(
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
val id: Long? = null,
val siteId: UUID,
val name: String)
{code}

When I ran it i I had this exception thrown
{code}
Caused by: org.postgresql.util.PSQLException: ERROR: currval(): relation “issue_id_seq” does not exist
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
{code}
which took me to the path of creating manual sequence etc.

[...]
This worked on non @Id field.
@GeneratedValue(strategy = GenerationType.IDENTITY)
@Column( insertable = false, updatable = false, nullable = false)
val autoId: Long? = null

So I don’t know how to get it to work on @Id field
```

**Comment by knz** [comment]
This issue will be alleviated with the new SERIAL normalization introduced by #28575 . This remains to be tested though.

**Comment by BramGruneir** [comment]
So this is now mostly a documentation issue.  

I ran the hibernate test suite against master using the sql.defaults.serial_normalization = sql_sequences and it passed 11 more tests than with the other options.  When it was run with virtual_sequences or row_id, the result remained the same.
```
--- PASS: org.hibernate.id.QuotedIdentifierTest.testDirectIdPropertyAccess (unexpected)
--- PASS: org.hibernate.test.annotations.manytoone.referencedcolumnname.ManyToOneReferencedColumnNameTest.testReoverableExceptionInFkOrdering (unexpected)
--- PASS: org.hibernate.test.annotations.xml.hbm.HbmWithIdentityTest.testManyToOneAndInterface (unexpected)
--- PASS: org.hibernate.test.generated.DefaultGeneratedValueIdentityTest.testGenerationWithIdentityInsert (unexpected)
--- PASS: org.hibernate.test.idgen.identity.hhh10429.IdentityGeneratorExtendsTest.testIdentifierGeneratorExtendsIdentityGenerator (unexpected)
--- PASS: org.hibernate.test.joinedsubclassbatch.IdentityJoinedSubclassBatchingTest.doBatchInsertUpdateJoinedSubclassNrBiggerThenBatch (unexpected)
--- PASS: org.hibernate.test.joinedsubclassbatch.IdentityJoinedSubclassBatchingTest.doBatchInsertUpdateJoinedSubclassNrEqualWithBatch (unexpected)
--- PASS: org.hibernate.test.joinedsubclassbatch.IdentityJoinedSubclassBatchingTest.doBatchInsertUpdateJoinedSubclassNrLessThenBatch (unexpected)
--- PASS: org.hibernate.test.joinedsubclassbatch.IdentityJoinedSubclassBatchingTest.testBatchInsertUpdateSizeEqJdbcBatchSize (unexpected)
--- PASS: org.hibernate.test.joinedsubclassbatch.IdentityJoinedSubclassBatchingTest.testBatchInsertUpdateSizeGtJdbcBatchSize (unexpected)
--- PASS: org.hibernate.test.joinedsubclassbatch.IdentityJoinedSubclassBatchingTest.testBatchInsertUpdateSizeLtJdbcBatchSize (unexpected)
```

@knz I'm going to close this, but feel free to open it back up if you think we should investigate further.
