### ISSUE TITLE
Races in `TestRaftRemoveRace`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2878]
Unexplained failures have been observed in `TestRaftRemoveRace` with very high iteration counts (> 5k). The most common issue is a timeout (may be related to the fact that we don't truncate logs; see #2877 ); other issues include "applied index out of range" and a panic in `Store.processRaft`. This is related to #2815 but is filed as a separate issue because the panics tracked there are believed to have been accounted for by #2868. This issue is for the less-common failures that remain.

**Comment by tschottdorf** [comment]
[Here's another NPE in `TestRaftRemoveRace`](https://circleci.com/gh/cockroachdb/cockroach/8892#tests):

```
I1104 02:43:30.040404 924 raft/raft.go:409  [group 1] c became follower at term 1
I1104 02:43:30.041451 924 raft/raft.go:503  [group 1] c [term: 1] received a MsgApp message with higher term from 1 [term: 6]
I1104 02:43:30.041551 924 raft/raft.go:409  [group 1] c became follower at term 6
W1104 02:43:30.041836 924 multiraft/multiraft.go:1041  failed to look up replica ID for range 1 (disabling replica ID check): storage/store.go:1569: store 3 not found as replica of range 1
I1104 02:43:30.046029 924 storage/store.go:1472  got an event membership change committed event: EndTransaction ["\x00\x00\x00k1\x00\x01rdsc","")
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xdcd6d0]

goroutine 6552 [running]:
github.com/coreos/etcd/raft.stepLeader(0xc8203612b0, 0xb, 0x0, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:590 +0x20e0
github.com/coreos/etcd/raft.(*raft).Step(0xc8203612b0, 0xb, 0x0, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:511 +0x380
github.com/coreos/etcd/raft.(*multiNode).run(0xc8202f6e40)
	/go/src/github.com/coreos/etcd/raft/multinode.go:258 +0x1667
created by github.com/coreos/etcd/raft.StartMultiNode
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:287 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202f6720, 0xc82038cc40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	19.766s
```

**Comment by tamird** [comment]
One more: https://circleci.com/gh/cockroachdb/cockroach/8933

**Comment by kkaneda** [comment]
Not sure that's the same issue, but I got https://circleci.com/gh/cockroachdb/cockroach/8939#tests in my branch for #2981.

TestReplicateRogueRemovedNode:

```
I1105 03:57:15.982617 955 storage/store.go:1475  changing raft replica {3 3 3} for range 1
I1105 03:57:15.997162 955 storage/store.go:1475  changing raft replica {2 2 2} for range 1
I1105 03:57:16.019129 955 storage/replica_gc_queue.go:125  destroying local data from range 1
E1105 03:57:16.019938 955 storage/store.go:1543  storage/store.go:1542: got committed raft command for 1 but have no range with that ID: {RangeID:1 OriginReplica:{NodeID:1 StoreID:1 ReplicaID:1} Cmd:EndTransaction ["\x00\x00\x00k1\x00\x01rdsc","")}
W1105 03:57:16.020666 955 multiraft/multiraft.go:1151  aborting configuration change: storage/store.go:1542: got committed raft command for 1 but have no range with that ID: {RangeID:1 OriginReplica:{NodeID:1 StoreID:1 ReplicaID:1} Cmd:EndTransaction ["\x00\x00\x00k1\x00\x01rdsc","")}
```

**Comment by tschottdorf** [comment]
one more: https://circleci.com/gh/tschottdorf/cockroach/1620?utm_campaign=build-failed&utm_medium=email&utm_source=notification
