### ISSUE TITLE
opt: panic in InlineProjections

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#28819]
```
SELECT subq_1.c2 AS c0 FROM crdb_internal.node_queries AS ref_0 INNER JOIN (SELECT ref_1.updated_at AS c0, ref_1.draining AS c1, ref_1.decommissioning AS c2 FROM crdb_internal.gossip_liveness AS ref_1 WHERE true) AS subq_0 ON ((((CAST(NULL AS DATE[]) IS DISTINCT FROM CAST(NULL AS DATE[])) OR ((SELECT created FROM information_schema.routines LIMIT 1 OFFSET 39) != ref_0.start)) AND ((CAST(NULL AS TIMESTAMP WITH TIME ZONE) IS NOT DISTINCT FROM (SELECT created FROM information_schema.routines LIMIT 1 OFFSET 5)) OR ((subq_0.c2 IS NOT NULL) OR ((SELECT pg_catalog.min(mod_time_logical) FROM crdb_internal.tables) <= CAST(NULL AS FLOAT8))))) AND ((SELECT pg_catalog.max(rows_avg) FROM crdb_internal.node_statement_statistics) IS NOT DISTINCT FROM (SELECT reltuples FROM pg_catalog.pg_class LIMIT 1 OFFSET 4))) LEFT JOIN (SELECT ref_2.result_cast_char_set_catalog AS c0, ref_2.result_cast_scope_catalog AS c1, ref_2.to_sql_specific_name AS c2, CAST(COALESCE(ref_2.result_cast_interval_type, ref_2.collation_name) AS TEXT) AS c3, ref_2.datetime_precision AS c4, ref_2.result_cast_maximum_cardinality AS c5, ref_2.result_cast_char_set_catalog AS c6, ref_2.type_udt_name AS c7, 94 AS c8, ref_2.to_sql_specific_name AS c9 FROM information_schema.routines AS ref_2 WHERE (ref_2.created != ref_2.created) AND (EXISTS (SELECT ref_3.refclassid AS c0, (SELECT rngsubdiff FROM pg_catalog.pg_range LIMIT 1 OFFSET 1) AS c1, ref_3.classid AS c2, ref_3.refobjsubid AS c3 FROM pg_catalog.pg_depend AS ref_3 WHERE (CAST(NULL AS DATE[]) = CAST(NULL AS DATE[])) OR (ref_2.routine_catalog IS NOT NULL)))) AS subq_1 ON (CAST(COALESCE(CAST(NULL AS TIME[]), CAST(NULL AS TIME[])) AS TIME[]) != CASE WHEN false THEN pg_catalog.array_remove(CAST(CAST(NULL AS TIME[]) AS TIME[]), CAST(CAST(NULL AS TIME) AS TIME)) ELSE pg_catalog.array_remove(CAST(CAST(NULL AS TIME[]) AS TIME[]), CAST(CAST(NULL AS TIME) AS TIME)) END) WHERE CASE WHEN (CAST(NULL AS DECIMAL) < CASE WHEN (SELECT value FROM crdb_internal.gossip_alerts LIMIT 1 OFFSET 1) != (SELECT mod_time_logical FROM crdb_internal.tables LIMIT 1 OFFSET 1) THEN (SELECT pg_catalog.variance(procost) FROM pg_catalog.pg_proc) ELSE (SELECT pg_catalog.variance(procost) FROM pg_catalog.pg_proc) END) AND (ref_0.phase IS NOT NULL) THEN CASE WHEN pg_catalog.uuid_v4() = CASE WHEN EXISTS (SELECT subq_0.c2 AS c0, subq_1.c0 AS c1, subq_0.c2 AS c2, ref_5.numeric_precision_radix AS c3, subq_0.c0 AS c4, ref_0.client_address AS c5, ref_5.scope_name AS c6, subq_0.c0 AS c7, ref_0.start AS c8, ref_5.parameter_mode AS c9, subq_1.c6 AS c10, subq_0.c2 AS c11, subq_0.c2 AS c12, ref_0.start AS c13, ref_5.scope_schema AS c14, ref_5.character_set_catalog AS c15, subq_1.c9 AS c16, ref_5.udt_catalog AS c17, ref_5.parameter_default AS c18, (SELECT create_nofks FROM crdb_internal.create_statements LIMIT 1 OFFSET 1) AS c19, subq_1.c2 AS c20, ref_5.collation_catalog AS c21, subq_1.c8 AS c22 FROM information_schema.parameters AS ref_5 WHERE subq_0.c1 != subq_0.c2 LIMIT 87) THEN (SELECT config_yaml FROM crdb_internal.zones LIMIT 1 OFFSET 5) ELSE (SELECT config_yaml FROM crdb_internal.zones LIMIT 1 OFFSET 5) END THEN CAST(NULL AS TIME[]) ELSE CAST(NULL AS TIME[]) END ELSE CASE WHEN pg_catalog.uuid_v4() = CASE WHEN EXISTS (SELECT subq_0.c2 AS c0, subq_1.c0 AS c1, subq_0.c2 AS c2, ref_5.numeric_precision_radix AS c3, subq_0.c0 AS c4, ref_0.client_address AS c5, ref_5.scope_name AS c6, subq_0.c0 AS c7, ref_0.start AS c8, ref_5.parameter_mode AS c9, subq_1.c6 AS c10, subq_0.c2 AS c11, subq_0.c2 AS c12, ref_0.start AS c13, ref_5.scope_schema AS c14, ref_5.character_set_catalog AS c15, subq_1.c9 AS c16, ref_5.udt_catalog AS c17, ref_5.parameter_default AS c18, (SELECT create_nofks FROM crdb_internal.create_statements LIMIT 1 OFFSET 1) AS c19, subq_1.c2 AS c20, ref_5.collation_catalog AS c21, subq_1.c8 AS c22 FROM information_schema.parameters AS ref_5 WHERE subq_0.c1 != subq_0.c2 LIMIT 87) THEN (SELECT config_yaml FROM crdb_internal.zones LIMIT 1 OFFSET 5) ELSE (SELECT config_yaml FROM crdb_internal.zones LIMIT 1 OFFSET 5) END THEN CAST(NULL AS TIME[]) ELSE CAST(NULL AS TIME[]) END END != CASE WHEN (EXISTS (SELECT subq_1.c7 AS c0, subq_0.c1 AS c1, ref_0.query AS c2, subq_1.c8 AS c3, subq_0.c0 AS c4, subq_1.c9 AS c5, ref_0.client_address AS c6, ref_7.fdwname AS c7, ref_0.query_id AS c8, subq_1.c1 AS c9, subq_0.c0 AS c10, ref_0.query_id AS c11, ref_0.user_name AS c12, subq_1.c9 AS c13, ref_7.fdwhandler AS c14, subq_1.c7 AS c15 FROM pg_catalog.pg_foreign_data_wrapper AS ref_7 WHERE EXISTS (SELECT ref_7.fdwvalidator AS c0, ref_7.fdwhandler AS c1, subq_1.c0 AS c2, (SELECT enumtypid FROM pg_catalog.pg_enum LIMIT 1 OFFSET 6) AS c3, subq_0.c0 AS c4, ref_7.fdwoptions AS c5 FROM crdb_internal.tables AS ref_8 WHERE ref_8.mod_time_logical <= ref_0.node_id) LIMIT 128)) AND (CASE WHEN (SELECT mod_time_logical FROM crdb_internal.tables LIMIT 1 OFFSET 38) != subq_1.c5 THEN CASE WHEN CAST(NULL AS BYTES) IS DISTINCT FROM (SELECT pg_catalog.xor_agg(start_key) FROM crdb_internal.ranges) THEN CAST(NULL AS INET[]) ELSE CAST(NULL AS INET[]) END ELSE CASE WHEN CAST(NULL AS BYTES) IS DISTINCT FROM (SELECT pg_catalog.xor_agg(start_key) FROM crdb_internal.ranges) THEN CAST(NULL AS INET[]) ELSE CAST(NULL AS INET[]) END END != CAST(NULL AS INET[])) THEN CAST(NULL AS TIME[]) ELSE CAST(NULL AS TIME[]) END
```

```
panic: cannot inline references within correlated subqueries [recovered]
        panic: cannot inline references within correlated subqueries [recovered]
        panic: panic while executing 1 statements: SELECT _._ AS _ FROM _._ AS _ INNER JOIN (SELECT _._ AS _, _._ AS _, _._ AS _ FROM _._ AS _ WHERE _) AS _ ON ((((CAST(_ AS DATE[]) IS DISTINCT FROM CAST(_ AS DATE[])) OR ((SELECT _ FROM _._ LIMIT _ OFFSET _) != _._)) AND ((CAST(_ AS TIMESTAMP WITH TIME ZONE) IS NOT DISTINCT FROM (SELECT _ FROM _._ LIMIT _ OFFSET _)) OR ((_._ IS NOT _) OR ((SELECT min(_) FROM _._) <= CAST(_ AS FLOAT8))))) AND ((SELECT max(_) FROM _._) IS NOT DISTINCT FROM (SELECT _ FROM _._ LIMIT _ OFFSET _))) LEFT JOIN (SELECT _ [...]; caused by cannot inline references within correlated subqueries

goroutine 279 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc420118600, 0x68c4de0, 0xc420c4b200, 0x5f54860, 0x688f4a0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:675 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc420118600, 0x68c4de0, 0xc420c4b200)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:414 +0x61
panic(0x5f54860, 0x688f4a0)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1(0xc427abe998)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:130 +0x99
panic(0x5f54860, 0x688f4a0)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0xc4000000ac, 0xc427abace8)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:120 +0x5cd
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Expr).Replace(0xc42741f198, 0xc426112d20, 0xc427abc0e8, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.go:181 +0x9f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExprView.Replace(0xc426112d20, 0xffff00320000011c, 0xc420118ad0, 0xc427abc0e8, 0xc427442180, 0xc427abadc0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr_view.go:201 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0xc40000011c, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:165 +0x49f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Expr).Replace(0xc42741f2d8, 0xc426112d20, 0xc427abc0e8, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.go:181 +0x9f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExprView.Replace(0xc426112d20, 0xffff00650000011e, 0xc420118ad0, 0xc427abc0e8, 0xc426112d20, 0xffff002b00000003)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr_view.go:201 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0x11e, 0x2)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:165 +0x49f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Expr).Replace(0xc42741f418, 0xc426112d20, 0xc427abc0e8, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.go:191 +0x21f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExprView.Replace(0xc426112d20, 0xffff006400000120, 0xc420118ad0, 0xc427abc0e8, 0xc426112d20, 0xffff00670000011b)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr_view.go:201 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0xc400000120, 0xc40000011b)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:165 +0x49f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Expr).Replace(0xc42741f4b8, 0xc426112d20, 0xc427abc0e8, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.go:181 +0x9f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExprView.Replace(0xc426112d20, 0xffff003700000121, 0xc420118ad0, 0xc427abc0e8, 0xc426112d20, 0xffff002a0000002d)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr_view.go:201 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0xc400000121, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:165 +0x49f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Expr).Replace(0xc42741f558, 0xc426112d20, 0xc427abc0e8, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.go:181 +0x9f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExprView.Replace(0xc426112d20, 0xffff006500000122, 0xc420118ad0, 0xc427abc0e8, 0xc426112d20, 0xffff002b00000003)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr_view.go:201 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0x122, 0x2)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:165 +0x49f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Expr).Replace(0xc42741f5f8, 0xc426112d20, 0xc427abc0e8, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.go:191 +0x21f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExprView.Replace(0xc426112d20, 0xffff006400000123, 0xc420118ad0, 0xc427abc0e8, 0xc426112d20, 0xffff00340000011a)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr_view.go:201 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0xc400000123, 0x11a)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:165 +0x49f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Expr).Replace(0xc42741f698, 0xc426112d20, 0xc427abc0e8, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.go:181 +0x9f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExprView.Replace(0xc426112d20, 0xffff006500000124, 0xc420118ad0, 0xc427abc0e8, 0xc426112d20, 0xffff002b00000003)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr_view.go:201 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0x124, 0x2)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:165 +0x49f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Expr).Replace(0xc42741fc38, 0xc426112d20, 0xc427abc0e8, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.go:191 +0x21f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExprView.Replace(0xc426112d20, 0xffff00640000012d, 0xc420118ad0, 0xc427abc0e8, 0xc427abbcb8, 0x52a8e8f)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr_view.go:201 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0x12d, 0xc400000177)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:165 +0x49f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Expr).Replace(0xc427421f38, 0xc426112d20, 0xc427abc0e8, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.go:181 +0x9f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExprView.Replace(0xc426112d20, 0xffff003c00000165, 0xc420118ad0, 0xc427abc0e8, 0x17600000006, 0x177)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr_view.go:201 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0x165, 0x1)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:165 +0x49f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Expr).Replace(0xc427421fd8, 0xc426112d20, 0xc427abc0e8, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.go:191 +0x21f
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExprView.Replace(0xc426112d20, 0xffff003300000166, 0xc420118ad0, 0xc427abc0e8, 0xc420119588, 0xffff006400000075)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr_view.go:201 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections.func1(0xc400000166, 0x53317d7)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:165 +0x49f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).InlineProjections(0xc420119588, 0x17700000166, 0x1)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline.go:168 +0x155
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect(0xc420119578, 0x16600000178, 0xc400000178)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:850 +0x1ae8
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructInnerJoinApply(0xc420119578, 0x1600000004a, 0xc400000166, 0xc426112d20)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:3312 +0x2f64
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).ConstructApplyJoin(0xc420119588, 0x4a00000007, 0x16600000160, 0x1)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:258 +0x6f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).HoistJoinSubquery(0xc420119588, 0x4a00000007, 0x1420000004d, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:147 +0xa9
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructInnerJoin(0xc420119578, 0x4d0000004a, 0xc400000142, 0x400baf3)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:1865 +0x1dea
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.init.0.func7(0xc420119578, 0x4a, 0x4d, 0x142, 0xc425800e40)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:10788 +0x46
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).DynamicConstruct(0xc420119578, 0x14200000007, 0x4a, 0x4d, 0x142, 0xc427abd488)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:11399 +0x5a
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect(0xc420119578, 0x1420000004f, 0x142)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:438 +0x39ad
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect(0xc420119578, 0x14200000051, 0x142)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:406 +0x53d
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect(0xc420119578, 0x1420000007a, 0x142)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:576 +0x2ae6
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFrom(0xc425791340, 0xc428840630, 0xc428850780, 0xc425f96800, 0xc426cbb2b8)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:527 +0x592
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause(0xc425791340, 0xc4288437a0, 0x0, 0x0, 0x0, 0xc425f96800, 0x30)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:429 +0x56
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc425791340, 0xc428848dc0, 0xc425f96800, 0x62d1360)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:387 +0x1a6
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc425791340, 0x68c84a0, 0xc428848dc0, 0xc425f96800, 0x4)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:177 +0xf1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc425791340, 0xc400000000, 0x0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:135 +0x128
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc420118a38, 0x68c4ea0, 0xc428858330, 0x68c84a0, 0xc428848dc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:378 +0x287
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optionallyUseOptimizer(0xc420118a38, 0x68c4ea0, 0xc428858330, 0xc4202b9c10, 0xd, 0xc42070e01b, 0x9, 0x0, 0x1, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:534 +0xdb
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc420118600, 0x68c4ea0, 0xc428858330, 0x68c84a0, 0xc428848dc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:751 +0x192
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc420118600, 0x68c4ea0, 0xc428858330, 0x68c84a0, 0xc428848dc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:401 +0xb82
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc420118600, 0x68c4ea0, 0xc428858330, 0x68c84a0, 0xc428848dc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc420118600, 0x68c4de0, 0xc420c4b200, 0xc4202fd860, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1079 +0x2186
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4201f30e0, 0x68c4de0, 0xc420c4b200, 0xc42070e01b, 0x9, 0xc42070e00d, 0x4, 0x0, 0x0, 0x68a6d60, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:416 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc4201f30e0, 0x68c4de0, 0xc420c4b200, 0xc42551e380, 0x5400, 0x15000, 0xc420785c80, 0xc4202fd860, 0xc4202fd850, 0xc4202b9840, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:267 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:266 +0xf04
```

**Comment by RaduBerinde** [comment]
Same as #28827.
