### ISSUE TITLE
server: must not try to access paths not specified by the user

### ISSUE THREAD

**Issue by korpa** [cockroachdb/cockroach#28888]
- Which version of CockroachDB are you using?

```
Build Tag:    v2.0.5
Build Time:   2018/08/13 17:59:42
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10
C Compiler:   gcc 6.3.0
Build SHA-1:  3f2f0f5eea9b9d552e471eba8c37504a0595342f
Build Type:   release
```

- What did you do?
Installed Ubuntu 18.04
```
adduser --system --disabled-password --disabled-login --no-create-home --shell /bin/false --group cockroach

mkdir -p /var/lib/cockroach
chown cockroach.cockroach /var/lib/cockroach

mkdir -p /etc/cockroach/certs
cp [CERTS] /etc/cockroach/certs
chown cockroach.cockroach /etc/cockroach -R
chmod 600 /etc/cockroach/certs/*

sudo -u cockroach /usr/local/bin/cockroach start --certs-dir=/etc/cockroach/certs --store=/var/lib/cockroach --port=26257 --http-port=7005  --logtostderr=ERROR --join=[OTHER NODES]

````
- What did you expect to see?
CockroachDB to start

- What did you see instead?
```
panic: could not find absolute path for path cockroach-data: stat .: permission denied

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/server.MakeConfig(0x2784040, 0xc420040078, 0xc42051e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/config.go:370 +0x514
github.com/cockroachdb/cockroach/pkg/cli.glob..func3(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/context.go:38 +0xd9
```

If I run cockroach with the same command as root (without sudo), cockroach starts:
```
/usr/local/bin/cockroach start --certs-dir=/etc/cockroach/certs --store=/var/lib/cockroach --port=26257 --http-port=7005  --logtostderr=ERROR --join=[OTHER NODES]
```

- What was the impact?

Jira issue: CRDB-4888

**Comment by tschottdorf** [comment]
@korpa Can you try something like

```
sudo -u cockroach /bin/bash -c "cd /var/lib/cockroach && /usr/local/bin/cockroach start --certs-dir=/etc/cockroach/certs --store=/var/lib/cockroach --port=26257 --http-port=7005  --logtostderr=ERROR --join=[OTHER NODES]"
```

It's possible that we're trying to list the working directory which in your case isn't accessible to the cockroach user.

**Comment by korpa** [comment]
@tschottdorf: Indeed, this works. Thank you very much.

**Comment by knz** [comment]
server team
