### ISSUE TITLE
distsqlrun: avoid using PrettyPrintKey as hash key in joinReader

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#28981]
See #28980 - it's not appropriate to use `PrettyPrintKey` in a hot path, as it's slow and does many allocations. `RowFetcher.IndexKeyString` should be modified to produce a byte array without using `strings.Join` and `strings.Split` on the string produced by `PrettyPrintKey`. There should be plenty of precedent for assembling hash keys from kv keys elsewhere - let's copy that prior art.

**Comment by jordanlewis** [comment]
Turns out this is a correctness problem that produces incorrect join results when doing lookup joins against interleaved indexes, so bumping milestone to 2.1. It can also panic the server.

There are two problems. First, the `PrettyPrintKey` method is incorrect, since the "count the slashes in the key" method doesn't work in the case of interleaved indexes, which add extra slashes for their interleave `#` markers. This causes incorrect join output in some cases.

Second, the method that generates the lookup key given an input doesn't take into account that the number of columns that we desire to include in the lookup key might be fewer than the number of columns in the interleaved prefixes, and some missing bounds checks in that code cause panics.

```
root@127.0.0.1:61736/defaultdb> create table z (a int, b int, primary key(a,b));
CREATE TABLE

Time: 3.81818ms

root@127.0.0.1:61736/defaultdb> create table y (a int, b int, c int, primary key(a,b,c)) interleave in parent z(a,b);
CREATE TABLE

Time: 18.34406ms

root@127.0.0.1:61736/defaultdb> insert into y values(1,2,3);
INSERT 1

Time: 2.118207ms

root@127.0.0.1:61736/defaultdb> select * from c join y on c.a=y.a;
*
* ERROR: [n1,client=127.0.0.1:61738,user=root] a SQL panic has occurred while executing "SELECT * FROM c JOIN y ON c.a = y.a": decoding unset EncDatum
*
*
* ERROR: [n1,client=127.0.0.1:61738,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT * FROM _ JOIN _ ON _._ = _._; caused by decoding unset EncDatum

goroutine 632 [running]:
runtime/debug.Stack(0x69ca420, 0xc4210afc40, 0x3)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x69ca420, 0xc4210afc40, 0xc4200a1300, 0x6323a20, 0xc4213b3e60, 0x1)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc421678600, 0x69ca420, 0xc4210afc40, 0x6052fe0, 0x6994cf0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:668 +0x2df
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc421678600, 0x69ca420, 0xc4210afc40)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:414 +0x61
panic(0x6052fe0, 0x6994cf0)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*EncDatum).EnsureDecoded(0xc4213af860, 0xc420c36cd0, 0xc4214cab98, 0x1, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:210 +0x4f2
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*EncDatum).Encode(0xc4213af860, 0xc420c36cd0, 0xc4214cab98, 0x0, 0xc4203a6508, 0x3, 0x4, 0xc4203a6508, 0x3, 0x4, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:255 +0x17e
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.appendEncDatumsToKey(0xc4203a6508, 0x2, 0x4, 0xc420c36c60, 0x2, 0x3, 0xc42156e3f0, 0x2, 0x3, 0xc4204de2c0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/table.go:414 +0x149
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.MakeKeyFromEncDatums(0xc420c36c60, 0x1, 0x3, 0xc42156e3f0, 0x1, 0x3, 0xc4214ca708, 0xc4214ca778, 0xc4203a64b0, 0x2, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/table.go:464 +0x2ab
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*joinReader).generateKey(0xc4214ca000, 0xc4214cad58, 0x1, 0x1, 0x0, 0x0, 0x1, 0xc4213b3bf0, 0x1)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/joinreader.go:315 +0x514
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*joinReader).readInput(0xc4214ca000, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/joinreader.go:394 +0x4b4
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*joinReader).Next(0xc4214ca000, 0x0, 0x0, 0x0, 0xc42161f1d0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/joinreader.go:336 +0x279
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x69ca4e0, 0xc4213b3320, 0x69d45e0, 0xc4214ca000, 0x69a86a0, 0xc4210d4380)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:170 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc4214ca000, 0x69ca4e0, 0xc4213b3320, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:739 +0x98
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartSync(0xc420343880, 0x69ca4e0, 0xc4213b3320, 0x65d6bd8, 0xc4214ba2a0, 0x69a82a0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:594 +0x191
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc420a9c300, 0xc420fd4480, 0xc4211e6280, 0xc4213b0808, 0xc421056000, 0xc421678ad0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:245 +0x879
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc420a9c300, 0x69ca4e0, 0xc4213b2930, 0xc421678ad0, 0xc420fd4480, 0xc4211e6280, 0x69bd8a0, 0xc420c36420, 0xc421056000)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:735 +0x24c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc421678600, 0x69ca4e0, 0xc4213b2930, 0xc421678a38, 0x3, 0x931e7a0, 0xc421357170, 0x1, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:966 +0x2d8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc421678600, 0x69ca4e0, 0xc4213b2930, 0x69cdb60, 0xc420fb04c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:808 +0x688
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc421678600, 0x69ca4e0, 0xc4213b2930, 0x69cdb60, 0xc420fb04c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:401 +0xb82
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc421678600, 0x69ca4e0, 0xc4213b2930, 0x69cdb60, 0xc420fb04c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc421678600, 0x69ca420, 0xc4210afc40, 0xc4203a9910, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1079 +0x2186
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc42080e120, 0x69ca420, 0xc4210afc40, 0x0, 0x0, 0xc4213de040, 0x4, 0xc4213de02a, 0x10, 0x69ac120, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:416 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc42080e120, 0x69ca420, 0xc4210afc40, 0xc421631880, 0x5400, 0x15000, 0xc420842180, 0xc4203a9910, 0xc4203a9900, 0xc4203658b0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:267 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:266 +0xf04

*
* ERROR: [n1,client=127.0.0.1:61738,user=root] Reported as error b62d27d8f72e443fae0982025b364b92
```
