### ISSUE TITLE
TestBaseQueueProcess failed in PR build

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#28993]
Looks like we have a quiesced replica trying to campaign after it's been merged away? Not sure yet.

```
TestBaseQueueProcess 
Test ended in panic.  ------- Stdout: ------- I180823 02:28:37.948843 9915 storage/store.go:1541  [s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available I180823 02:28:37.950535 9915 storage/store.go:2632  removing replica I180823 02:28:37.950749 9915 storage/replica.go:880  removed 8 (3+5) keys in 0ms [clear=0ms commit=0ms] panic: runtime error: invalid memory address or nil pointer dereference [recovered]     panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10ead20]  goroutine 10041 [running]: github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420b35b00, 0x2bac860, 0xc420ab7c80)     /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:184 +0x11f panic(0x2379aa0, 0x3a80a80)     /usr/local/go/src/runtime/panic.go:502 +0x229 github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*Progress).maybeUpdate(...)     /go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/progress.go:120 github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).appendEntry(0xc420207440, 0xc420cc3770, 0x1, 0x1)     /go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:630 +0xd0 github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).becomeLeader(0xc420207440)     /go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:726 +0x159 github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).campaign(0xc420207440, 0x2661adf, 0x10)     /go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:749 +0x62f github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).campaign(0xc420207440, 0x26673d7, 0x13)     /go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:747 +0x690 github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc420207440, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)     /go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:874 +0x2ff github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*RawNode).Campaign(0xc420267800, 0xc420ab72c0, 0x3)     /go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:140 +0x61 github.com/cockroachdb/cockroach/pkg/storage.(*Replica).maybeCampaignOnWakeLocked(0xc42019f880, 0x2bac860, 0xc420ab72c0)     /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:643 +0x36a github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc42019f880, 0x2793701, 0x2791a70, 0xc420ab7c80, 0x2bd3a80)     /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:575 +0x323 github.com/cockroachdb/cockroach/pkg/storage.(*Replica).maybeInitializeRaftGroup(0xc42019f880, 0x2bac860, 0xc420ab7c80)     /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1967 +0x120 github.com/cockroachdb/cockroach/pkg/storage.(*Replica).sendWithRangeID(0xc42019f880, 0x2bac860, 0xc420ab7c80, 0x3e8, 0x154d62788fcde492, 0x0, 0x0, 0x0, 0x3e8, 0x0, ...)     /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2008 +0x136 github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc42019f880, 0x2bac860, 0xc420ab7c80, 0x154d62788fcde492, 0x0, 0x0, 0x0, 0x3e8, 0x0, 0x0, ...)     /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1980 +0x90 github.com/cockroachdb/cockroach/pkg/storage.(*pendingLeaseRequest).requestLeaseAsync.func2(0x2bac860, 0xc420ab7c80)     /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go:310 +0x5c1 github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc420b35b00, 0x2bac860, 0xc420ab7c80, 0xc4200554c0, 0x35, 0x2bd3a80, 0xc4202f0d20, 0xc420738480)     /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:324 +0xe6 created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask     /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:319 +0x133
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=855788&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

**Comment by benesch** [comment]
This turned out to be nothing at all. The testContext used by most of the tests in replica_test.go just isn't wired up properly for merges. Fixed before the PR in question landed: https://github.com/cockroachdb/cockroach/blame/33092de7061eacb60e45a56c1a5ad7829c839e0b/pkg/storage/replica_test.go#L204.
