### ISSUE TITLE
storage: merge snapshot bug

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#29080]
Looks to be a bad race condition somewhere 😬.

```
I180827 02:02:05.149316 48667 sql/lease.go:345  [n1,client=127.0.0.1:33968,user=root] publish: descID=57 (simple_auto_inc) version=2 mtime=2018-08-27 02:02:05.148099441 +0000 UTC
I180827 02:02:05.150053 48667 sql/lease.go:345  [n1,client=127.0.0.1:33968,user=root] publish: descID=58 (simple) version=2 mtime=2018-08-27 02:02:05.148099441 +0000 UTC
I180827 02:02:05.156674 48667 sql/event_log.go:126  [n1,client=127.0.0.1:33968,user=root] Event: "drop_table", target: 58, info: {TableName:foo.public.simple Statement:DROP TABLE IF EXISTS simple, second, everything User:root CascadeDroppedViews:[]}
I180827 02:02:05.158873 50422 storage/replica_command.go:430  [merge,n3,s3,r57/3:/Table/5{8/1/27-9}] initiating a merge of r58:/{Table/59-Max} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=0] into this range
I180827 02:02:05.159569 50424 storage/replica_command.go:298  [split,n3,s3,r55/3:/Table/5{7-8/1/27}] initiating a split of this range at key /Table/58 [r59]
I180827 02:02:05.164207 48667 sql/lease.go:315  publish (1 leases): desc=[{simple_auto_inc 57 1}]
I180827 02:02:05.168131 50436 sql/lease.go:877  new lease: 57("simple_auto_inc") ver=2:1535335624.341369090,0, refcount=0
I180827 02:02:05.175342 48138 storage/replica_proposal.go:214  [n3,s3,r55/3:/Table/5{7-8/1/27}] new range lease repl=(n3,s3):3 seq=3 start=1535335324.234418235,0 epo=1 pro=1535335324.234420867,0 following repl=(n3,s3):3 seq=3 start=1535335324.234418235,0 epo=1 pro=1535335324.234420867,0
E180827 02:02:05.181351 50458 storage/queue.go:788  [raftsnapshot,n3,s3,r58/3:/{Table/59-Max}] snapshot failed: (n2,s2):2: remote couldn't accept Raft snapshot 683b191b at applied index 11 with error: [n2,s2],r58: cannot apply snapshot: snapshot intersects existing range [n2,s2,r51/2:/{Table/55/1/27-Max}]
I180827 02:02:05.229070 48667 sql/lease.go:345  [n1,client=127.0.0.1:33968,user=root,scExec=] publish: descID=58 (simple) version=3 mtime=2018-08-27 02:02:05.228573346 +0000 UTC
I180827 02:02:05.238534 48667 sql/lease.go:345  [n1,client=127.0.0.1:33968,user=root] publish: descID=57 (simple_auto_inc) version=3 mtime=2018-08-27 02:02:05.237572152 +0000 UTC
I180827 02:02:05.270866 48667 sql/event_log.go:126  [n1,client=127.0.0.1:33968,user=root] Event: "drop_sequence", target: 57, info: {SequenceName:foo.public.simple_auto_inc Statement:DROP SEQUENCE IF EXISTS simple_auto_inc User:root}
I180827 02:02:05.279674 48667 sql/lease.go:345  [n1,client=127.0.0.1:33968,user=root,scExec=] publish: descID=57 (simple_auto_inc) version=4 mtime=2018-08-27 02:02:05.279523481 +0000 UTC
I180827 02:02:05.321555 50450 storage/replica_command.go:298  [n3,s3,r58/3:/{Table/59-Max}] initiating a split of this range at key /Table/60 [r60]
I180827 02:02:05.746024 50497 storage/store_snapshot.go:615  [raftsnapshot,n3,s3,r54/3:/Table/5{5-6}] sending Raft snapshot 50424e38 at applied index 25
I180827 02:02:05.746664 50497 storage/store_snapshot.go:657  [raftsnapshot,n3,s3,r54/3:/Table/5{5-6}] streamed snapshot to (n2,s2):2: kv pairs: 45, log entries: 15, rate-limit: 8.0 MiB/sec, 1ms
F180827 02:02:05.747247 50580 storage/replica.go:5536  [n2,s2,r54/2:/Table/55{-/1/27}] subsumed replicas [[n2,s2,r51/2:/{Table/55/1/27-Max}]] extend past snapshot end key /Table/56
goroutine 50580 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc420536101, 0xc4205361e0, 0x3ca1300, 0x12)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:972 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x4255ca0, 0xc400000004, 0x3ca13f5, 0x12, 0x15a0, 0xc4225ccd80, 0x7d)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:843 +0x7e7
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2eb18c0, 0xc4267b6990, 0x4, 0x2, 0x2a02e1b, 0x34, 0xc4246a4810, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:154 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2eb18c0, 0xc4267b6990, 0x1, 0xc400000004, 0x2a02e1b, 0x34, 0xc4246a4810, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2eb18c0, 0xc4267b6990, 0x2a02e1b, 0x34, 0xc4246a4810, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).maybeAcquireSnapshotMergeLock(0xc4227b2700, 0x2eb18c0, 0xc4267b6990, 0xb34549b4384e4250, 0x178f5bcef9f336b7, 0xc4205033a0, 0x1, 0x1, 0xc421527e00, 0xf, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5536 +0x53f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4227b2700, 0xb34549b4384e4250, 0x178f5bcef9f336b7, 0xc4205033a0, 0x1, 0x1, 0xc421527e00, 0xf, 0x10, 0xc424596200, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4049 +0x1e94
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest.func1(0x2eb18c0, 0xc424ff5830, 0xc4227b2700, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3690 +0x894
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc420b39080, 0x2eb18c0, 0xc424ff5830, 0xc421cf7e48, 0xc424525838, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3438 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest(0xc420b39080, 0x2eb18c0, 0xc4215f1770, 0xc421cf7e00, 0xb34549b4384e4250, 0x178f5bcef9f336b7, 0xc4205033a0, 0x1, 0x1, 0xc421527e00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3487 +0xd9
github.com/cockroachdb/cockroach/pkg/storage.(*Store).receiveSnapshot(0xc420b39080, 0x2eb18c0, 0xc4215f1770, 0xc421cf7e00, 0x7f3f25ab2518, 0xc42052ab00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store_snapshot.go:514 +0x330
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc420b39080, 0xc421cf7e00, 0x7f3f25ab24e8, 0xc42052ab00, 0xc42052ab00, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3316 +0x206
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x2ecc0c0, 0xc42052ab00, 0xc420f7b2c0, 0x2eb18c0, 0xc4215f16b0, 0x911cf9, 0xc4214e8ff0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:386 +0x146
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x2eb18c0, 0xc4215f16b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:387 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc421c2d4d0, 0x2eb18c0, 0xc4215f16b0, 0xc421b2c340, 0x32, 0x0, 0x0, 0xc4215f1710)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:324 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:319 +0x133
```

**Comment by benesch** [comment]
Extracted from TC build 
https://teamcity.cockroachdb.com/viewLog.html?buildId=862181&buildTypeId=Cockroach_UnitTests_Test&tab=buildLog&_focus=182452

**Comment by benesch** [comment]
Full log: https://gist.github.com/benesch/a19578d787b79a1df78c3c1f5232f089
