### ISSUE TITLE
acceptance: TestRapidRestarts CI failures

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#29227]
`TestRapidRestarts` has failed on CI several times recently. For example:

https://teamcity.cockroachdb.com/viewLog.html?buildId=867693&buildTypeId=Cockroach_UnitTests
https://teamcity.cockroachdb.com/viewLog.html?buildId=867685&buildTypeId=Cockroach_UnitTests_Acceptance
https://teamcity.cockroachdb.com/viewLog.html?buildId=864345&buildTypeId=Cockroach_UnitTests

**Comment by petermattis** [comment]
The failures are all timeouts. Usually the test succeeds in 5-10s. I've been able to reproduce failures locally by setting the timeout to 1m and running in a loop.

**Comment by petermattis** [comment]
I fooled myself by setting the 1m timeout and running with `-count 100`. No real local reproduction yet.

But I did find the real error in the failures above: 

```
fatal error: concurrent map read and map write

goroutine 111 [running]:
runtime.throw(0x2a5299c, 0x21)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc420a98a18 sp=0xc420a989f8 pc=0x6dc7d1
runtime.mapaccess2_faststr(0x269f180, 0xc4208a9ef0, 0xc420378ce4, 0xd, 0xd, 0xc420a98ae8)
	/usr/local/go/src/runtime/hashmap_fast.go:270 +0x461 fp=0xc420a98a88 sp=0xc420a98a18 pc=0x6bc591
net/http.(*ServeMux).shouldRedirect(0xc420ab86c0, 0xc4202a21f0, 0x9, 0xc420378ce4, 0xd, 0x0)
	/usr/local/go/src/net/http/server.go:2239 +0x114 fp=0xc420a98b48 sp=0xc420a98a88 pc=0x9d8174
net/http.(*ServeMux).redirectToPathSlash(0xc420ab86c0, 0xc4202a21f0, 0x9, 0xc420378ce4, 0xd, 0xc420a6e400, 0xc420ce0000, 0x0)
	/usr/local/go/src/net/http/server.go:2224 +0x57 fp=0xc420a98b90 sp=0xc420a98b48 pc=0x9d7f47
net/http.(*ServeMux).Handler(0xc420ab86c0, 0xc42079c300, 0xc420260850, 0xc420a98d28, 0x18, 0xc420a98d20)
	/usr/local/go/src/net/http/server.go:2293 +0x118 fp=0xc420a98cd8 sp=0xc420a98b90 pc=0x9d8408
net/http.(*ServeMux).ServeHTTP(0xc420ab86c0, 0x2f4e760, 0xc4202ba000, 0xc42079c300)
	/usr/local/go/src/net/http/server.go:2336 +0xfe fp=0xc420a98d18 sp=0xc420a98cd8 pc=0x9d8b7e
github.com/cockroachdb/cockroach/pkg/server.(*Server).ServeHTTP(0xc4208d0000, 0x2f5cae0, 0xc420382380, 0xc42079c300)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1861 +0x11d fp=0xc420a98d58 sp=0xc420a98d18 pc=0x1eaeb2d
net/http.serverHandler.ServeHTTP(0xc4208851e0, 0x2f5cae0, 0xc420382380, 0xc42079c300)
	/usr/local/go/src/net/http/server.go:2694 +0xbc fp=0xc420a98d88 sp=0xc420a98d58 pc=0x9d9bec
net/http.(*conn).serve(0xc420ab6140, 0x2f5f2e0, 0xc420c28500)
	/usr/local/go/src/net/http/server.go:1830 +0x651 fp=0xc420a98fc8 sp=0xc420a98d88 pc=0x9d5e61
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420a98fd0 sp=0xc420a98fc8 pc=0x70be91
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
```

Seems like we're doing something bad early in startup.

**Comment by petermattis** [comment]
I've probably been staring at the sun too long, but it looks like we're definitely doing something that is not copacetic. `http.ServeMux` does not support having `Handle` called after it has been associated with a server. `ServeMux.ServeHTTP` accesses `ServeMux.m` without a lock. 

Oh, this is apparently a bug in go1.10. Here is the problematic code path in go1.10:

```
func (mux *ServeMux) redirectToPathSlash(host, path string, u *url.URL) (*url.URL, bool) {
	if !mux.shouldRedirect(host, path) {
		return u, false
	}
	path = path + "/"
	u = &url.URL{Path: path, RawQuery: u.RawQuery}
	return u, true
}
```

And here is that same code in go1.11:

```
func (mux *ServeMux) redirectToPathSlash(host, path string, u *url.URL) (*url.URL, bool) {
	mux.mu.RLock()
	shouldRedirect := mux.shouldRedirectRLocked(host, path)
	mux.mu.RUnlock()
	if !shouldRedirect {
		return u, false
	}
	path = path + "/"
	u = &url.URL{Path: path, RawQuery: u.RawQuery}
	return u, true
}
```

See https://github.com/golang/go/commit/2fd1b523952727b91e5eca76ff1f8b8af8746f7a.

I'm not sure what to do in the short term. I suppose we could add our own protection around `ServeMux`, though that is somewhat unfortunate.

**Comment by petermattis** [comment]
I believe this test has been flaky since its introduction almost a year ago. Cc @tschottdorf for tickling bugs in the stdlib.
