### ISSUE TITLE
sql: panic on `EXPORT ... SELECT FROM [...]`

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#29238]
running: `EXPORT INTO CSV 'nodelocal:///jobs' FROM SELECT * FROM [SHOW JOBS];`

The node crashes with:
```
goroutine 310 [running]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newProcessor(0x6a2dae0, 0xc4205ef200, 0xc42559e380, 0x0, 0xc4252eadd8, 0xc4252eae98, 0x0, 0x0, 0x0, 0xc42032fa90, ...)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:1054 +0x2afc
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).makeProcessor(0xc42559e380, 0x6a2dae0, 0xc4205ef200, 0xc4252eadc0, 0x0, 0x0, 0x0, 0x1, 0x6a0b820, 0xc4208abcc0, ...)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:372 +0x5e5
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).setup(0xc42559e380, 0x6a2dae0, 0xc4205ef200, 0xc42028b278, 0x0, 0x1)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:446 +0xb49
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ServerImpl).setupFlow(0xc420708380, 0x6a2dae0, 0xc4205eefc0, 0x6a587e0, 0xc420318d60, 0xc4252c2c80, 0xc42028b260, 0x6a0b4e0, 0xc42071f900, 0x0, ...)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/server.go:431 +0x8e4
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ServerImpl).SetupLocalSyncFlow(0xc420708380, 0x6a2dae0, 0xc4205eefc0, 0xc4252c2c80, 0xc42028b260, 0x6a0b4e0, 0xc42071f900, 0x0, 0x0, 0x0, ...)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/server.go:477 +0xe0
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc420872000, 0xc420ae8de0, 0xc420a35680, 0xc424d79a28, 0xc42071f900, 0xc4201137d0, 0x0)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:234 +0x809
github.com/cockroachdb/cockroach/pkg/sql.PlanAndRunExport(0x6a2dae0, 0xc4205eefc0, 0xc420872000, 0xc42078be00, 0xc420a35680, 0xc4201137d0, 0x6a20ee0, 0xc4203cf340, 0x0, 0x0, ...)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_csv.go:83 +0x3fa
```

**Comment by jordanlewis** [comment]
The problem here is that the distsql merge introduced some fiddling that has to be done on the planCtx that's kind of outside of the distsql API, to determine whether or not a plan can be run locally. Admittedly this isn't great - we should add this stuff to well-known API methods.

Does it make sense for EXPORT to be able to run every possible query, but in some cases constrained to the gateway node? Or should we just fail in that case?

Right now, `planCtx.isLocal` is always set to false (since nobody sets it) regardless of the type of the plan. What we need to do instead is run `checkSupportForNode` and decide what to do at that point. If you're okay making some EXPORTS non-distributed, we just set the `isLocal` flag correctly. If not, we can just return an error if `checkSupportForNode` returns `cannotDistribute`.

**Comment by dt** [comment]
yeah, i'm fine either running them locally or returning an error -- just as long as it doesn't panic.
