### ISSUE TITLE
storage: leaked iterator failure in restore replicas

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#29388]
Tests failure on an unrelated CI run on release-2.1 with
```
panic: 1 leaked iterators [recovered]
	panic: 1 leaked iterators

goroutine 48946 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4216af320, 0x2bbc000, 0xc4200dc058)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:184 +0x11f
panic(0x2396aa0, 0xc420374690)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).Close(0xc420758ea0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:717 +0x32b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc4216af320, 0x2bbc000, 0xc4200dc058)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:488 +0x341
github.com/cockroachdb/cockroach/pkg/storage_test.(*multiTestContext).Stop.func1(0xc420361340, 0xc421c56000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_test.go:347 +0x225
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=873269&buildTypeId=Cockroach_UnitTests_Test&tab=buildLog&_focus=177444

**Comment by dt** [comment]
@tschottdorf for routing

**Comment by tschottdorf** [comment]
I'm stressing this for a bit, but I assume this is just *so* rare; unfortunately the full artifact is long gone and I'm not seeing any goroutine in the build log hold on to an iterator. Closing as inactionable, for now. This is also almost certainly a test-only problem and even if not, it wouldn't matter to a production binary (which just doesn't have this check at shutdown).
