### ISSUE TITLE
sql: panic in INSERT ... ON CONFLICT

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#29495]
```
root@:26257/backboard> *
* ERROR: [n1,client=[::1]:50098,user=root] a SQL panic has occurred while executing "INSERT INTO repos(github_owner, github_repo) VALUES ($1, $2) ON CONFLICT (github_owner, github_repo) DO UPDATE SET github_owner = excluded.github_owner RETURNING id": invalid datum type given: string, expected int
*
*
* ERROR: [n1,client=[::1]:50098,user=root] a panic has occurred!
*
panic while executing 1 statements: INSERT INTO _(_, _) VALUES ($1, $2) ON CONFLICT (_, _) DO UPDATE SET _ = _._ RETURNING _; caused by invalid datum type given: string, expected int

goroutine 177967 [running]:
runtime/debug.Stack(0x6a27780, 0xc42e554bc0, 0x3)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6a27780, 0xc42e554bc0, 0xc42062b980, 0x63736c0, 0xc427d27770, 0x1)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc429716000, 0x6a27780, 0xc42e554bc0, 0x609e3a0, 0xc4262291a0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:668 +0x2df
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc429716000, 0x6a27780, 0xc42e554bc0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:414 +0x61
panic(0x609e3a0, 0xc4262291a0)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:161 +0x281
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc425cfa900, 0x0, 0xc426623ee8, 0x5145530, 0xc420343180)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:207 +0x102
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x6a27840, 0xc425083080, 0x6a30f80, 0xc425cfa900, 0x6a05640, 0xc424ece380)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:170 +0x35
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Run(0xc425cfa900, 0x6a27840, 0xc425083080, 0x0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:264 +0x96
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartSync(0xc42ce96c40, 0x6a27840, 0xc425083080, 0x662f978, 0xc42676e0e0, 0x6a05240)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:594 +0x191
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc420aa8200, 0xc4268d0720, 0xc4264e0320, 0xc426624808, 0xc425e8a780, 0xc4297164d0, 0x0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:245 +0x879
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc420aa8200, 0x6a27840, 0xc425082b10, 0xc4297164d0, 0xc4268d0720, 0xc4264e0320, 0x6a1ac80, 0xc42836eb00, 0xc425e8a780)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:735 +0x24c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc429716000, 0x6a27840, 0xc425082b10, 0xc429716438, 0x3, 0xc200460, 0xc4259b4360, 0xc425e8da00, 0x1, 0x1)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:966 +0x2d8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc429716000, 0x6a27840, 0xc425082b10, 0x6a2a880, 0xc4264e4320, 0xc425e8da40, 0x1, 0x1, 0xc4260d7a20, 0xa4, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:808 +0x688
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc429716000, 0x6a27840, 0xc425082b10, 0x6a2a880, 0xc4264e4320, 0xc425e8da40, 0x1, 0x1, 0xc4260d7a20, 0xa4, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:401 +0xb82
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc429716000, 0x6a27840, 0xc425082b10, 0x6a2a880, 0xc4264e4320, 0xc425e8da40, 0x1, 0x1, 0xc4260d7a20, 0xa4, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc429716000, 0x6a27780, 0xc42e554bc0, 0xc42d6d2960, 0x0, 0x0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1135 +0x13cd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420972360, 0x6a27780, 0xc42e554bc0, 0xc4251a7022, 0x9, 0xc4251a7031, 0x4, 0x0, 0x0, 0x6a09180, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:416 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc420972360, 0x6a27780, 0xc42e554bc0, 0xc42783a1c0, 0x5400, 0x15000, 0xc4206c1ec0, 0xc42d6d2960, 0xc42d6d2950, 0xc42726c380, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:267 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:266 +0xf04

*
* ERROR: [n1,client=[::1]:50098,user=root] Reported as error eaaf81189bfe4ab496040203c15e1b9b
*

Error: interrupted
Failed running "sql"
```

The full schema/query are:

```sql
CREATE TABLE IF NOT EXISTS repos (
	id serial PRIMARY KEY,
	github_owner string NOT NULL,
	github_repo string NOT NULL,
	UNIQUE (github_owner, github_repo)
);

INSERT INTO repos (github_owner, github_repo)
VALUES ($1, $2)
ON CONFLICT (github_owner, github_repo) DO UPDATE SET github_owner = excluded.github_owner			RETURNING id
```

@knz for triage

**Comment by jordanlewis** [comment]
Yeesh, so many bugs with mutations right now...

This is buggy in both dist and force-local mode, in local mode it doesn't panic but it does return a spurious error (`pq: strconv.ParseInt: parsing "a": invalid syntax`). Almost certainly an issue with the `UPSERT RETURNING` logic.

**Comment by jordanlewis** [comment]
This is the same root cause as #29436. Fix coming.

**Comment by jordanlewis** [comment]
Hmm, I take it back, it's a different root cause.

**Comment by jordanlewis** [comment]
I did confirm that this doesn't happen with `rowid`, by the way. I'm going to unassign myself as @knz is most familiar with the `SERIAL` functionality.

**Comment by knz** [comment]
I just ran this on CockroachDB 2.1 without errors:

```
root@127.0.0.1:17450/defaultdb> CREATE TABLE IF NOT EXISTS repos (
        id serial PRIMARY KEY,
        github_owner string NOT NULL,
        github_repo string NOT NULL,
        UNIQUE (github_owner, github_repo)
);
CREATE TABLE

Time: 2.640411ms

root@127.0.0.1:17450/defaultdb> INSERT INTO repos (github_owner, github_repo) VALUES ('a', 'b');
INSERT 1

Time: 2.959335ms

root@127.0.0.1:17450/defaultdb> select * from repos;
          id         | github_owner | github_repo
+--------------------+--------------+-------------+
  380113675334975489 | a            | b
(1 row)

Time: 1.777864ms


root@127.0.0.1:17450/defaultdb> INSERT INTO repos (github_owner, github_repo) VALUES ('x', 'y') RETURNING id;
          id
+--------------------+
  380113735389249537
(1 row)

Time: 975.648µs

```

@jordanlewis what is the repro case exactly?

**Comment by jordanlewis** [comment]
```
INSERT INTO repos (github_owner, github_repo)
VALUES ('foo', 'bar')
ON CONFLICT (github_owner, github_repo) DO UPDATE SET github_owner = excluded.github_owner
RETURNING id
```

**Comment by pouledodue** [comment]
```
# coding=utf-8

from peewee import *

db = PostgresqlDatabase('defaultdb', host='localhost', user='root',
                        port=26257)

db.connect()


class AB(Model):
    a = CharField()
    b = SmallIntegerField()

    class Meta:
        table_name = 'ab'
        database = db
        indexes = [
            (('a', 'b'), True)
        ]


AB.create_table()

data = [('v', 1), ('a', 1)]

q = AB.insert_many(data, fields=[AB.a, AB.b]).on_conflict('ignore')
# print(q.sql())
q.execute()
```

gives me

```
ERROR: [n1,client=127.0.0.1:55359,user=root] a SQL panic has occurred while executing "INSERT INTO ab(a, b) VALUES ('v', 1), ('a', 1) ON CONFLICT DO NOTHING RETURNING id": invalid datum type given: string, expected int
```
on
`CCL v2.1.0-beta.20180910 @ 2018/09/10 19:49:42 (go1.10.3)`

**Comment by knz** [comment]
@BramGruneir for the record I am 99.999% confident this has nothing to do with serial. However it still needs to be investigated.
