### ISSUE TITLE
distsql: panic in stream_decoder.go

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#29553]
```
make testlogic TESTFLAGS='-verbosity=10 -show-sql -test.v' FILES=aggregate
[...]
SELECT 3 FROM kv HAVING TRUE;
panic: no typing info received yet

goroutine 2947 [running]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*StreamDecoder).Types(0xc42233a380, 0x1, 0x0, 0x0)
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/stream_decoder.go:180 +0x147
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.processProducerMessage(0x27acfc0, 0xc421db84e0, 0x27c28c0, 0xc420449820, 0x2790080, 0xc421593c80, 0xc42233a380, 0xc4214816a0, 0xc420989260, 0xc421db8420, ...)
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/inbound.go:171 +0x425
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.processInboundStreamHelper.func2(0xc421f3a000, 0x27c28c0, 0xc420449820, 0xc4202ffec0, 0xc420989200, 0x27acfc0, 0xc421db84e0, 0x2790080, 0xc421593c80, 0xc42233a380, ...)
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/inbound.go:110 +0x11a
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.processInboundStreamHelper
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/inbound.go:92 +0x1b8
Makefile:864: recipe for target 'testbaselogic' failed
make: *** [testbaselogic] Error 2
```

**Comment by arjunravinarayan** [comment]
Here is a minimal logic test configuration that reproduces this panic:

```
# LogicTest: fakedist

statement ok
CREATE TABLE kv (
  k INT PRIMARY KEY,
  v INT,
  w INT,
  s STRING
)

statement OK
INSERT INTO kv VALUES
(1, 2, 3, 'a'),
(3, 4, 5, 'a'),
(5, NULL, 5, NULL),
(6, 2, 3, 'b'),
(7, 2, 2, 'b'),
(8, 4, 2, 'A')

# Presence of HAVING triggers aggregation, reducing results to one row (even without GROUP BY).
query I rowsort
SELECT 3 FROM kv HAVING TRUE
----
3
```

**Comment by arjunravinarayan** [comment]
This panic is nondeterministic.

**Comment by arjunravinarayan** [comment]
`kv` needs at least 1 row for this panic to trigger, and the chance of reproduction seems to go up the more rows are in `kv`. But I have run these experiments on my laptop with low `n`, so take this with a grain of salt.

**Comment by arjunravinarayan** [comment]
Here is the [distsql plan](https://cockroachdb.github.io/distsqlplan/decode.html#eJyUkDFPwzAQhXd-RfVmS03K5gnGLCmKuqEMJn6KIlJfdHYQqMp_R4kHKFIRjPfO3_usuyCIZ-3OjLDPKNEaTCodYxRdo_yg8u-whcEQpjmtcWvQiRL2gjSkkbA4uZeRDZ2n7gsYeCY3jFvtpMPZ6cfD6xsMjnOyu1oC0S4GMqevyphcT9hyMX_XPva9sndJdF9eWxsGT7W7e2ttVZ9u6g7_0TWMk4TIK9Wt5mJpDeh75ktGmbXjk0q3afJ43Lgt8Iwpb8s8VCGv1g9-h8tf4cMPuF3uPgMAAP__BDehJA==)

I believe the problem is that the aggregator is incorrectly setup when it requires zero rows (since it's rendering only a constant in this case).

**Comment by arjunravinarayan** [comment]
Also seen in test `SELECT EXISTS(SELECT 1 FROM kv AS x WHERE x.k = 1)`, from the `subquery` logic test file. This pretty much confirms that this takes place with constant renders, and isn't related to the aggregator per se.

**Comment by arjunravinarayan** [comment]
Might have to revise this hypothesis, also seen in `SELECT count(*) FROM one AS a, one AS b, two AS c;` from the `distsql_agg` logic test.
