### ISSUE TITLE
Version() was called before having been initialized

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#29675]
@justinj . I am trying to rolling upgrade from v2.1.0-beta.20180827 to v2.1.0-beta.20180904. When I try to restart the first node, I get this error and the node can't be started.

```
root@crdb-01:/home/leo/cockroach# ./cockroach start --cache=25%  --max-sql-memory=35%  --background --locality=region=us-east,datacenter=rs-iad-pc --store=path=d1,attrs=ssd --log-dir=log --certs-dir=certs --advertise-addr=192.168.28.11 --join=192.168.28.15 --max-disk-temp-storage=100GB
*
* WARNING: [n?] listen address "::" not in node certificate (IP=192.168.28.11,192.168.28.8; DNS=localhost,crdb-01; CN=node)
* Secure node-node and SQL connections are likely to fail.
* Consider extending the node certificate or tweak --listen-addr/--advertise-addr.
*
F180906 20:47:16.242588 15 settings/cluster/settings.go:164  Version() was called before having been initialized
goroutine 15 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc420056e00, 0xc420056e40, 0x3e02e00, 0x1c)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:972 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x46d9e80, 0xc400000004, 0x3e02e9c, 0x1c, 0xa4, 0xc4203f8a40, 0x33)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:841 +0x804
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2f5ef60, 0xc4200500c8, 0x4, 0x2, 0x0, 0x0, 0xc420a760c8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:154 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2f5ef60, 0xc4200500c8, 0x1, 0x4, 0x0, 0x0, 0xc420a760c8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x2f5ef60, 0xc4200500c8, 0xc420a760c8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:181 +0x6c
github.com/cockroachdb/cockroach/pkg/settings/cluster.(*ExposedClusterVersion).Version(0xc4200231b0, 0x1551ea8c6c3ff64e, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/settings/cluster/settings.go:164 +0x161
github.com/cockroachdb/cockroach/pkg/settings/cluster.(*ExposedClusterVersion).IsActive(0xc4200231b0, 0x1c, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/settings/cluster/settings.go:199 +0x2b
github.com/cockroachdb/cockroach/pkg/kv.(*txnSpanRefresher).augmentMetaLocked(0xc4204736f0, 0x6c468b68e6dbffe1, 0x8037c9d4bdd7218e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1551ea8c4e72914e, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_span_refresher.go:356 +0x58
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).augmentMetaLocked(0xc420473400, 0x6c468b68e6dbffe1, 0x8037c9d4bdd7218e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1551ea8c4e72914e, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:514 +0x11b
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSenderFactory).TransactionalSender(0xc420a188f0, 0x1, 0x6c468b68e6dbffe1, 0x8037c9d4bdd7218e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1551ea8c4e72914e, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:468 +0x6a8
github.com/cockroachdb/cockroach/pkg/internal/client.NewTxnWithCoordMeta(0xc420790c00, 0xc400000000, 0x1, 0x6c468b68e6dbffe1, 0x8037c9d4bdd7218e, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:141 +0x13f
github.com/cockroachdb/cockroach/pkg/internal/client.NewTxnWithProto(0xc420790c00, 0x0, 0x1, 0x6c468b68e6dbffe1, 0x8037c9d4bdd7218e, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:126 +0x150
github.com/cockroachdb/cockroach/pkg/internal/client.NewTxn(0xc420790c00, 0x0, 0x1, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:116 +0x134
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare(0xc420113300, 0x2f5efe0, 0xc420a1c0f0, 0x2f62620, 0xc42037e9c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:175 +0x291
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).addPreparedStmt(0xc420113300, 0x2f5efe0, 0xc420a1c0f0, 0x0, 0x0, 0x2f62620, 0xc42037e9c0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:122 +0xe1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPrepare(0xc420113300, 0x2f5efe0, 0xc420a1c0f0, 0x0, 0x0, 0x2f62620, 0xc42037e9c0, 0xc420a1c090, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:55 +0x15e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc420113300, 0x2f5efe0, 0xc4208a9dd0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1143 +0x2b44
github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx.func1(0xc420113300, 0x2f5efe0, 0xc4208a9dd0, 0xc42033a3a0, 0x0, 0xc4202fc1b0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:210 +0x8a
created by github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:199 +0x275
*
* ERROR: exit status 255
*
Failed running "start"
```

**Comment by jordanlewis** [comment]
@tschottdorf @vilterp weren't you guys looking at something like this recently? Seems like an issue with startup order. I'm just not sure why it's only intermittently showing up.

**Comment by a-robinson** [comment]
Yeah I saw this yesterday and reported on the old issue - https://github.com/cockroachdb/cockroach/issues/25771#issuecomment-418802483

**Comment by vilterp** [comment]
Yeah, was just going to say that @a-robinson had seen this. @couchand and I haven't been able to repro yet, but good to know others can. Closing as a dup of https://github.com/cockroachdb/cockroach/issues/25771#event-1637644333
