### ISSUE TITLE
restart server and lost node

### ISSUE THREAD

**Issue by learsu** [cockroachdb/cockroach#30108]
i lost one node when restart server and restart cockroachdb node. 
[root@cockroach-212 log]# cat cockroach.cockroach-212.root.2018-09-10T03_40_01Z.010533.log
I180910 03:40:01.192821 1 util/log/clog.go:1134  [config] file created at: 2018/09/10 03:40:01
I180910 03:40:01.192821 1 util/log/clog.go:1134  [config] running on machine: cockroach-212
I180910 03:40:01.192821 1 util/log/clog.go:1134  [config] binary: CockroachDB CCL v2.0.5 (x86_64-unknown-linux-gnu, built 2018/08/13 17:59:42, go1.10)
I180910 03:40:01.192821 1 util/log/clog.go:1134  [config] arguments: [/opt/cockroach/bin/cockroach start --background --host=192.168.1.212 --port=26257 --http-host=0.0.0.0 --htt]
I180910 03:40:01.192821 1 util/log/clog.go:1134  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
[root@cockroach-212 log]# cat cockroach.cockroach-212.root.2018-09-12T01_54_04Z.001383.log
I180912 01:54:04.501265 1 util/log/clog.go:1134  [config] file created at: 2018/09/12 01:54:04
I180912 01:54:04.501265 1 util/log/clog.go:1134  [config] running on machine: cockroach-212
I180912 01:54:04.501265 1 util/log/clog.go:1134  [config] binary: CockroachDB CCL v2.0.5 (x86_64-unknown-linux-gnu, built 2018/08/13 17:59:42, go1.10)
I180912 01:54:04.501265 1 util/log/clog.go:1134  [config] arguments: [/opt/cockroach/bin/cockroach start --background --host=192.168.1.212 --port=26257 --http-host=0.0.0.0 --htt]
I180912 01:54:04.501265 1 util/log/clog.go:1134  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
[root@cockroach-212 log]# cat cockroach.cockroach-212.root.2018-09-12T01_54_04Z.001396.log
I180912 01:54:04.531050 1 util/log/clog.go:1134  [config] file created at: 2018/09/12 01:54:04
I180912 01:54:04.531050 1 util/log/clog.go:1134  [config] running on machine: cockroach-212
I180912 01:54:04.531050 1 util/log/clog.go:1134  [config] binary: CockroachDB CCL v2.0.5 (x86_64-unknown-linux-gnu, built 2018/08/13 17:59:42, go1.10)
I180912 01:54:04.531050 1 util/log/clog.go:1134  [config] arguments: [/opt/cockroach/bin/cockroach start --host=192.168.1.212 --port=26257 --http-host=0.0.0.0 --http-port=8080 -]
I180912 01:54:04.531050 1 util/log/clog.go:1134  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
I180912 01:54:04.531049 1 server/config.go:330  available memory from cgroups (8.0 EiB) exceeds system memory 7.6 GiB, using system memory
I180912 01:54:04.531238 1 server/config.go:330  available memory from cgroups (8.0 EiB) exceeds system memory 7.6 GiB, using system memory
I180912 01:54:04.531597 1 cli/start.go:923  CockroachDB CCL v2.0.5 (x86_64-unknown-linux-gnu, built 2018/08/13 17:59:42, go1.10)
I180912 01:54:04.740084 1 server/config.go:330  available memory from cgroups (8.0 EiB) exceeds system memory 7.6 GiB, using system memory
I180912 01:54:04.740129 1 server/config.go:430  system total memory: 7.6 GiB
I180912 01:54:04.740308 1 server/config.go:432  server configuration:
max offset             500000000
cache size             3.8 GiB
SQL memory pool size   1.9 GiB
scan interval          10m0s
scan max idle time     200ms
event log enabled      true
PID file               /opt/cockroach/pid
I180912 01:54:04.740366 1 cli/start.go:796  process identity: uid 0 euid 0 gid 0 egid 0
I180912 01:54:04.740391 1 cli/start.go:461  starting cockroach node
I180912 01:54:04.767290 36 storage/engine/rocksdb.go:553  opening rocksdb instance at "/opt/cockroach/dat/cockroach-temp027680864"
I180912 01:54:04.964949 36 server/server.go:734  [n?] monitoring forward clock jumps based on server.clock.forward_jump_check_enabled
I180912 01:54:04.966342 36 storage/engine/rocksdb.go:553  opening rocksdb instance at "/opt/cockroach/dat"
I180912 01:54:05.248066 36 server/config.go:538  [n?] 1 storage engine initialized
I180912 01:54:05.248104 36 server/config.go:541  [n?] RocksDB cache size: 3.8 GiB
I180912 01:54:05.248125 36 server/config.go:541  [n?] store 0: RocksDB, max size 0 B, max open file limit 60535
W180912 01:54:05.308747 36 gossip/gossip.go:1293  [n?] no incoming or outgoing connections
I180912 01:54:05.308935 36 server/server.go:784  [n?] Sleeping till wall time 1536717245308884623 to catches up to 1536717245464795885 to ensure monotonicity. Delta: 155.911262ms
F180912 01:54:05.332343 78 server/server.go:219  [n?] clock synchronization error: this node is more than 500ms away from at least half of the known nodes (0 of 1 are within the)
goroutine 78 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc4200a8a00, 0xc4200a8a80, 0x3324100, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:959 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x3bd3a80, 0xc400000004, 0x3324117, 0x10, 0xdb, 0xc42017c120, 0x88)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:835 +0x753
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x27840c0, 0xc420752150, 0x4, 0x2, 0x0, 0x0, 0xc420bffc58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:154 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x27840c0, 0xc420752150, 0x1, 0x4, 0x0, 0x0, 0xc420bffc58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:55 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x27840c0, 0xc420752150, 0xc420bffc58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:158 +0x6c
github.com/cockroachdb/cockroach/pkg/server.NewServer.func1()
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:219 +0xb0
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc4200d0280, 0xc420a8f3b0, 0xc4202a4460, 0x13, 0xc4202bd7a0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:642 +0x667
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.1.1(0x27840c0, 0xc420a8d020)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:508 +0x74
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42031b3a0, 0xc42094a000, 0xc420a8cff0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad
[root@cockroach-212 log]#

**Comment by benesch** [comment]
Hi @learsu! Thanks for your interest in Cockroach.

> F180912 01:54:05.332343 78 server/server.go:219 [n?] clock synchronization error: this node is more than 500ms away from at least half of the known nodes

Looks like your clocks are out of sync. Please see our [What happens when node clocks are not properly synchronized?](https://www.cockroachlabs.com/docs/stable/operational-faqs.html#what-happens-when-node-clocks-are-not-properly-synchronized) FAQ entry.
