### ISSUE TITLE
storage: expected placeholder, got *storage.Replica

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#30110]
While trying to repro https://github.com/cockroachdb/cockroach/issues/29698, I got this stacktrace once out of about a dozen runs:

```
I180907 21:40:56.760549 69711 storage/replica_command.go:430  [merge,n8,s8,r16588/1:/Table/53/1/4611{5029-7455}] initiating a merge of r16623:/Table/53/1/461{17455-27271} [(n8,s8):1, (n4,s4):2, (n10,s10):3, (n3,s3):5, next=6, gen=1] into this range
I180907 21:40:56.994215 69739 storage/replica_raftstorage.go:787  [n8,s8,r16571/?:/Table/53/1/465{56837-62528}] applying preemptive snapshot at index 47 (id=c4c48ba3, encoded size=13071, 1 rocksdb batches, 26 log entries)
I180907 21:40:56.999250 69739 storage/replica_raftstorage.go:793  [n8,s8,r16571/?:/Table/53/1/465{56837-94111}] applied preemptive snapshot in 5ms [clear=0ms batch=0ms entries=0ms commit=4ms]
E180907 21:40:56.999454 69739 util/log/crash_reporting.go:477  [n8,s8,r16571/?:/Table/53/1/465{56837-94111}] Reported as error b4b62ac0e13d4fcf93f4be36ac37dd8d
F180907 21:40:56.999506 69739 storage/store.go:2646  [n8,s8,r16571/?:/Table/53/1/465{56837-94111}] r16571: expected placeholder, got *storage.Replica
goroutine 69739 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc4204ca500, 0xc4204ca540, 0x3e46c00, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:972 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x472df00, 0xc400000004, 0x3e46ce0, 0x10, 0xa56, 0xc42b31fda0, 0x60)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:841 +0x807
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2f97b60, 0xc4261aa000, 0x4, 0x2, 0x2a85ec3, 0x21, 0xc44bbcaf78, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:154 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2f97b60, 0xc4261aa000, 0x1, 0xc400000004, 0x2a85ec3, 0x21, 0xc44bbcaf78, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2f97b60, 0xc4261aa000, 0x2a85ec3, 0x21, 0xc44bbcaf78, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).removePlaceholderLocked(0xc4204c5b80, 0x2f97b60, 0xc4261aa000, 0x40bb, 0x2b9ca00)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2646 +0x1cd
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest.func1.3(0xc4204c5b80, 0xc44bbcb163, 0x2f97b60, 0xc4261aa000, 0xc429266e00, 0xc44bbcb7b8, 0xc44bbcb162, 0xc430f55c00)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3613 +0x13b
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest.func1(0x2f97b60, 0xc4261aa000, 0xc430f55c00, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3746 +0x600
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc4204c5b80, 0x2f97b60, 0xc4261aa000, 0xc429266e48, 0xc427a33838, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3501 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest(0xc4204c5b80, 0x2f97b60, 0xc42617bb60, 0xc429266e00, 0x4f41054ca38bc4c4, 0xe59722c9ace39884, 0xc426c0a580, 0x1, 0x1, 0xc42c89e000, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3550 +0xd9
github.com/cockroachdb/cockroach/pkg/storage.(*Store).receiveSnapshot(0xc4204c5b80, 0x2f97b60, 0xc42617bb60, 0xc429266e00, 0x7f4a5f276038, 0xc425d76e10, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store_snapshot.go:514 +0x330
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc4204c5b80, 0xc429266e00, 0x7f4a5f276008, 0xc425d76e10, 0xc425d76e10, 0x8)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3379 +0x206
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x2fb32e0, 0xc425d76e10, 0xc420726dc0, 0x2f97b60, 0xc42617bad0, 0x6db2e9, 0xc42c732bb0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:386 +0x146
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x2f97b60, 0xc42617bad0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:387 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4201cf290, 0x2f97b60, 0xc42617bad0, 0xc42703ed80, 0x32, 0x0, 0x0, 0xc42617bb00)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:324 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:319 +0x133
```

Scary stuff. Unfortunately the cluster expired before I could save the rest of its logs. Hopefully it reproduces again soon.

**Comment by benesch** [comment]
I'll note that we applied a widening preemptive snapshot to an existing replica:

```
I180907 21:40:56.994215 69739 storage/replica_raftstorage.go:787  [n8,s8,r16571/?:/Table/53/1/465{56837-62528}] applying preemptive snapshot at index 47 (id=c4c48ba3, encoded size=13071, 1 rocksdb batches, 26 log entries)
I180907 21:40:56.999250 69739 storage/replica_raftstorage.go:793  [n8,s8,r16571/?:/Table/53/1/465{56837-94111}] applied preemptive snapshot in 5ms [clear=0ms batch=0ms entries=0ms commit=4ms]
E180907 21:40:56.999454 69739 util/log/crash_reporting.go:477  [n8,s8,r16571/?:/Table/53/1/465{56837-94111}] Reported as error b4b62ac0e13d4fcf93f4be36ac37dd8d
F180907 21:40:56.999506 69739 storage/store.go:2646  [n8,s8,r16571/?:/Table/53/1/465{56837-94111}] r16571: expected placeholder, got *storage.Replica
```

That code path is new and is likely where the bug lies.
