### ISSUE TITLE
workload: fixtures make tpch crashes

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#30155]
```
$ bin/workload fixtures make tpch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x97970c]

goroutine 75 [running]:
github.com/cockroachdb/cockroach/pkg/workload.WriteCSVRows(0xd6a3c0, 0xc4200ce280, 0xd5f9a0, 0xc4201ea5a0, 0xc7d0d8, 0x8, 0xcb2aef, 0x16a, 0xc3500, 0xc3500, ...)
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/workload/csv.go:54 +0x39c
github.com/cockroachdb/cockroach/pkg/ccl/workloadccl.(*groupCSVWriter).groupWriteCSVs.func1.2(0xc420075ad0, 0xc4200ce201)
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/fixture.go:214 +0x438
github.com/cockroachdb/cockroach/pkg/util/retry.WithMaxAttempts(0xd6a3c0, 0xc4200ce280, 0x2faf080, 0x3b9aca00, 0x4000000000000000, 0x2, 0x0, 0x0, 0x3, 0xc4204dfc70, ...)
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:163 +0xfc
github.com/cockroachdb/cockroach/pkg/ccl/workloadccl.(*groupCSVWriter).groupWriteCSVs.func1(0xd6a3c0, 0xc4200ce280, 0xc42008a090, 0xc7d0d8, 0x8, 0xcb2aef, 0x16a, 0xc3500, 0xc3500, 0x0, ...)
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/fixture.go:207 +0x3ef
github.com/cockroachdb/cockroach/pkg/ccl/workloadccl.(*groupCSVWriter).groupWriteCSVs(0xc42008a090, 0xd6a3c0, 0xc4200ce280, 0xc4200348a0, 0xc7d0d8, 0x8, 0xcb2aef, 0x16a, 0xc3500, 0xc3500, ...)
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/fixture.go:235 +0xc6
github.com/cockroachdb/cockroach/pkg/ccl/workloadccl.MakeFixture.func1(0x0, 0x0)
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/fixture.go:365 +0x371
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc4200ce2c0, 0xc420504750)
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/home/arjun/goworkspace/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**Comment by knz** [comment]
@danhhz how should we triage these issues these days? (I've not yet learned who's responsible for maintaining workload over time)

**Comment by danhhz** [comment]
My time for code improvements to workload is sporadic, but I'm happy to manage the issues. Feel free to send them my way.

In this case, the real fix requires a go implementation of the tpch data generation, which I won't get to for a long time. I assume arjun's point in filing it is to get a better error message than a panic. I'll send a PR.
