### ISSUE TITLE
opt: panic with aggregates

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#30166]
Query:

```
SELECT array_agg(generate_series(1, 2))
```

Result:
```
panic: top-level relational expression cannot have outer columns: (1) [recovered]
        panic: panic while executing 1 statements: SELECT array_agg(generate_series(_, _)); caused by top-level relational expression cannot have outer columns: (1)

goroutine 138 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc425564a00, 0x6a67140, 0xc425450bc0, 0x60d3440, 0xc424f3e5a0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:675 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc425564a00, 0x6a67140, 0xc425450bc0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:414 +0x61
panic(0x60d3440, 0xc424f3e5a0)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize(0xc425565980, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:182 +0x200
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc425564e30, 0x6a67200, 0xc424f21e00, 0x6a6a900, 0xc42ad26b80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:460 +0x972
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optionallyUseOptimizer(0xc425564e30, 0x6a67200, 0xc424f21e00, 0xc42573d02a, 0xf, 0xc42039d5fc, 0x4, 0x0, 0x1, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:537 +0xce
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc425564a00, 0x6a67200, 0xc424f21e00, 0x6a6a900, 0xc42ad26b80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:759 +0x182
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc425564a00, 0x6a67200, 0xc424f21e00, 0x6a6a900, 0xc42ad26b80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:403 +0xb42
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc425564a00, 0x6a67200, 0xc424f21e00, 0x6a6a900, 0xc42ad26b80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95 +0x341
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc425564a00, 0x6a67140, 0xc425450bc0, 0xc42034c400, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1079 +0x21a5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4207c1300, 0x6a67140, 0xc425450bc0, 0x0, 0x0, 0xc42573d067, 0x4, 0xc42573d02a, 0xf, 0x6a487c0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:416 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc4207c1300, 0x6a67140, 0xc425450bc0, 0xc425742000, 0x5400, 0x15000, 0xc42095e830, 0xc42034c400, 0xc42034c3f0, 0xc42039d590, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:268 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:267 +0xf1f
```

**Comment by andy-kimball** [comment]
Rebecca, can you take a look? I suspect it's an SRF-related issue.
