### ISSUE TITLE
sql: ARRAY operator returns wrong type

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#30191]
This seems newly broken in 2.1. I would expect the `ARRAY(...)` operator applied to an `int` column to produce an `int[]` type, but instead it produces `tuple{int}[]`.

```
> SELECT ARRAY(VALUES (1), (2)):::INT[];
pq: incompatible type annotation for ARRAY (VALUES (1), (2)) as int[], found type: tuple{int}[]
```

**Comment by solongordon** [comment]
Assigning to @knz for triage

**Comment by solongordon** [comment]
For what it's worth, this is what I was trying to do when I hit the bug. (Works in postgres and 2.0.5.)
```
CREATE TABLE t (x INT);
INSERT INTO t VALUES (1), (2);
CREATE TABLE u (y INT[]);
INSERT INTO u VALUES (ARRAY[1, 2]);
SELECT * FROM u WHERE y = ARRAY(SELECT x FROM t ORDER BY x);

pq: unsupported comparison operator: <int[]> = <tuple{int}[]>
```

**Comment by knz** [comment]
@justinj @rytaft I seem to recall some opt typing rule changed recently, can you double check?

**Comment by jordanlewis** [comment]
@solongordon you could try with `set optimizer=off` to isolate it further.

**Comment by rytaft** [comment]
I just tried that and it caused a panic :)
```
* ERROR: [n1,client=[::1]:51234,user=root] a SQL panic has occurred while executing "SELECT * FROM u WHERE y = ARRAY (SELECT x FROM t ORDER BY x)": interface conversion: tree.Expr is *tree.Subquery, not *optbuilder.subquery
*
*
* ERROR: [n1,client=[::1]:51234,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT * FROM _ WHERE _ = ARRAY (SELECT _ FROM _ ORDER BY _); caused by interface conversion: tree.Expr is *tree.Subquery, not *optbuilder.subquery

goroutine 174 [running]:
runtime/debug.Stack(0x6a71420, 0xc42080fc80, 0x3)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6a71420, 0xc42080fc80, 0xc420255980, 0x63abac0, 0xc4262c5a70, 0x1)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc420826a00, 0x6a71420, 0xc42080fc80, 0x61d4b20, 0xc425cc90c0)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:668 +0x2df
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc420826a00, 0x6a71420, 0xc42080fc80)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:414 +0x61
panic(0x61d4b20, 0xc425cc90c0)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*ScalarBuilder).Build.func1(0xc4270015c0)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:666 +0xc7
panic(0x61d4b20, 0xc425cc90c0)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar(0xc426638b40, 0x6a85a60, 0xc42781f760, 0xc426638c28, 0x0, 0x0, 0x0, 0xc400000001)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:190 +0x3d95
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar(0xc426638b40, 0x6a85d60, 0xc425b98a20, 0xc426638c28, 0x0, 0x0, 0x0, 0x0)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:339 +0x26da
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*ScalarBuilder).Build(0xc426638b40, 0x6a85d60, 0xc425b98a20, 0x0, 0x0)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:671 +0x90
github.com/cockroachdb/cockroach/pkg/sql.(*planner).selectIndex(0xc420826e30, 0x6a714e0, 0xc4262c54d0, 0xc42626c700, 0x0, 0xac7ab00, 0x0, 0xc420b0a400, 0x6a8ae60, 0xac00000)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_index_selection.go:144 +0x14d1
github.com/cockroachdb/cockroach/pkg/sql.expandScanNode(0x6a714e0, 0xc4262c54d0, 0xc420826e30, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0xc42626c700, 0xc427001aa8, ...)
	/Users/becca/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:500 +0x10e
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x6a714e0, 0xc4262c54d0, 0xc420826e30, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x6a649a0, 0xc42626c700, ...)
```
