### ISSUE TITLE
flakiness in TestSplitSnapshotRace_SnapshotWins

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3038]
An unhandled `ConditionFailedError` on a replica change.

```
...
E1106 20:42:23.832435 28896 storage/client_test.go:541  engine 0: missing key "z"
E1106 20:42:23.832494 28896 storage/client_test.go:541  engine 4: missing key "z"
E1106 20:42:23.832518 28896 storage/client_test.go:541  engine 5: missing key "z"
W1106 20:42:23.833490 28896 multiraft/multiraft.go:1226  node 3 failed to send message to 4: multiraft/transport.go:143: unknown peer 4
W1106 20:42:23.833984 28896 multiraft/multiraft.go:1226  node 3 failed to send message to 4: multiraft/transport.go:143: unknown peer 4
I1106 20:42:23.834840 28896 storage/replica_command.go:1191  initiating a split of range=2 ["\x01"-"\xff\xff") at key "m"
--- FAIL: TestSplitSnapshotRace_SnapshotWins (0.48s)
	client_test.go:490: storage/replica_command.go:1588: change replicas of 2 failed: unexpected value: raw_bytes:"\010\002\022\001\001\032\001m\"\006\010\004\020\004\030\004\"\006\010\002\020\002\030\002\"\006\010\003\020\003\030\003(\005" checksum:3738718210 timestamp:<wall_time:2000000002 logical:12 > tag:BYTES
```

**Comment by tamird** [comment]
Another one: https://circleci.com/gh/cockroachdb/cockroach/9113
```
...
--- FAIL: TestSplitSnapshotRace_SnapshotWins (37.71s)
	<autogenerated>:32: storage/client_split_test.go:779: condition failed to evaluate within 3s: storage/client_test.go:559: expected [0 11 11 11 0 0], got [0 11 11 1 0 0]
	client_test.go:270: timed out during shutdown
```

**Comment by bdarnell** [comment]
These look like two separate issues. I used to be able to reproduce the first one, but I'm not seeing it any more. I can reproduce the second easily, though.

**Comment by bdarnell** [comment]
It's a deadlock between the multiraft goroutine and a split in the store's processRaft goroutine. We cannot hold `Store.mu` while calling multiraft methods like `RemoveGroup`. It looks like we need some refactoring of the locks so this conflict doesn't happen. @mrtracy, this is likely the cause of the deadlock you saw.

```
goroutine 996 [semacquire]:
sync.runtime_Semacquire(0xc820092cf4)
	/opt/local/lib/go/src/runtime/sema.go:43 +0x26
sync.(*RWMutex).RLock(0xc820092ce8)
	/opt/local/lib/go/src/sync/rwmutex.go:36 +0x76
github.com/cockroachdb/cockroach/storage.(*Store).GetReplica(0xc820092b40, 0x2, 0x0, 0x0, 0x0)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:776 +0x5b
github.com/cockroachdb/cockroach/storage.(*Store).ReplicaIDForStore(0xc820092b40, 0x2, 0x4, 0xc8204f8948, 0x0, 0x0)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1647 +0x60
github.com/cockroachdb/cockroach/multiraft.(*state).handleWriteReady(0xc8200efc20)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:1074 +0x698
github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:607 +0x12e5
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8205fd260, 0xc820612160)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x70

goroutine 997 [chan send]:
github.com/cockroachdb/cockroach/storage.(*Store).SplitRange(0xc820092b40, 0xc8201ee180, 0xc820536f00, 0x0, 0x0)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:976 +0xc59
github.com/cockroachdb/cockroach/storage.(*Replica).splitTrigger.func1()
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1347 +0x78
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBBatch).Commit(0xc8205b08a0, 0x0, 0x0)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:700 +0x2a3
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommand(0xc8201ee180, 0x6ce29d8, 0xc8205b0870, 0x1f, 0x200000002, 0x2, 0xb2d05e03, 0x11, 0x14157415c4c4a638, 0x6ebe26765872407c, ...)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/storage/replica.go:999 +0x707
github.com/cockroachdb/cockroach/storage.(*Replica).processRaftCommand(0xc8201ee180, 0xc820613ea0, 0x10, 0x1f, 0x2, 0x200000002, 0x2, 0xb2d05e03, 0x11, 0x14157415c4c4a638, ...)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/storage/replica.go:960 +0x30f
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1578 +0xdd3
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8205fd260, 0xc820612170)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x70
```

**Comment by bdarnell** [comment]
The two lock orderings (treating select-loop goroutines as a kind of lock since they are a mutally-exclusive resource) we see in this trace are
* multiraft goroutine -> `store.mu` (in `Store.GetReplica`)
* `processRaft` goroutine -> `raftGroupLocker` -> `store.mu` -> multiraft goroutine (all in `Store.SplitRange`)

The former pattern is very common; the `multiraft.Storage` interface implies a requirement that the multiraft goroutine is acquired before `store.mu`. Elsewhere we have a requirement that the multiraft goroutine is acquired before `raftGroupLocker`, and the processRaft goroutine is acquired before the multiraft goroutine (giving a total order of processRaft goroutine, multiraft goroutine, raftGroupLocker, store.mu). So we'll have to break the deadlock on the other side, by moving the call to `multiraft.RemoveGroup` out of the scope of the two store mutexes. We would *also* have to move the `replicaGCQueue`'s call to `RemoveGroup` out of the scope of `raftGroupLocker`, which defeats the purpose of that lock (a similar deadlock is possible between `multiraft.CreateGroup` and `replicaGCQueue`).

I'm going back to the drawing board on #2868. We need a different solution to lock down a group during splits and GC.

**Comment by bdarnell** [comment]
After talking it over with @BramGruneir, here's the plan:
* Remove `raftGroupLocker`. Keep the `GroupLocker` method (probably under a new name), but have it return `store.mu` instead.
* `multiraft` acquires `store.mu` before calling any methods on the `Storage` interface.
* `Store` methods that implement the `multiraft.Storage` interface can assume `store.mu` is held and no longer acquire this lock for themselves. New pre-locked versions of various methods will be added as necessary.
