### ISSUE TITLE
opt: panic while executing 1 statements: EXPLAIN (DISTSQL) SELECT _ FROM _._._ W...

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#30424]
https://sentry.io/cockroach-labs/cockroachdb/issues/694086358/

```
*log.safeError: conn_executor.go:668: panic while executing 1 statements: EXPLAIN (DISTSQL) SELECT _ FROM _._._ WHERE (SELECT count(_) >= _) GROUP BY _: caused by <redacted>
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 414, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar_builder.go", line 109, in indexedVar
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar_builder.go", line 101, in buildVariable
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar_builder.go", line 87, in buildScalar
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar_builder.go", line 177, in buildComparison
...
(21 additional frame(s) were not displayed)

conn_executor.go:668: panic while executing 1 statements: EXPLAIN (DISTSQL) SELECT _ FROM _._._ WHERE (SELECT count(_) >= _) GROUP BY _: caused by <redacted>
```

**Comment by andy-kimball** [comment]
Rebecca, I have a repro for a crash that looks like this query, though it fails in a different place:
```
CREATE TABLE a (k INT PRIMARY KEY, i INT, f FLOAT NOT NULL, s STRING, j JSON)
SELECT s FROM a WHERE (SELECT COUNT(i) >= 100) GROUP BY s
```
Here's the crash with this query:
```
SELECT s FROM a WHERE (SELECT COUNT(i) >= 100) GROUP BY s
panic: top-level relational expression cannot have outer columns: (7) [recovered]
	panic: top-level relational expression cannot have outer columns: (7) [recovered]
	panic: top-level relational expression cannot have outer columns: (7)

goroutine 16 [running]:
testing.tRunner.func1(0xc4201e9950)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x4c76600, 0xc420255620)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/testutils/datadriven.RunTest.func1.1(0xc42047a720)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/testutils/datadriven/datadriven.go:75 +0x117
panic(0x4c76600, 0xc420255620)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize(0xc42024c000, 0x0, 0xc42024c000)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:182 +0x200
```
I believe it's due to aggregations + correlated subqueries.
