### ISSUE TITLE
production: catrina outage

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#30521]
Catrina had an outage that we discovered today. We can see that on n1 on 9/20, things looked OK:

```
I180920 17:44:17.619174 379 server/status/runtime.go:484  [n1] runtime stats: 332 MiB RSS, 800 goroutines, 178 MiB/304 KiB/204 MiB GO alloc/idle/total, 78 MiB/106 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (12x), 0.0/0.0/2 (%r/%w/q)disk, 2.8 MiB/1.9 MiB (r/w)net
```

but it was having trouble connecting to n2 and n3:

```
W180920 17:44:18.261825 2252 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {cockroach-catrina-0002:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W180920 17:45:58.561565 19252 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {cockroach-catrina-0003:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W180920 17:45:58.561662 19252 vendor/google.golang.org/grpc/clientconn.go:942  Failed to dial cockroach-catrina-0003:26257: context canceled; please retry.
```

Then we saw memory usage and the number of goroutines steadily climb, peaking at 4 million (!) goroutines:

```
I180921 05:34:55.973110 379 server/status/runtime.go:484  [n1] runtime stats: 13 GiB RSS, 4904255 goroutines, 2.9 GiB/65
 MiB/13 GiB GO alloc/idle/total, 92 MiB/137 MiB CGO alloc/total, 259.0 CGO/sec, 19.0/10.6 %(u/s)time, 0.0 %gc (0x), 15.0
/161.7/2 (%r/%w/q)disk, 306 KiB/424 KiB (r/w)net
```

On n2 on 9/20, goroutines were already climbing.

```
I180920 17:28:08.473417 410 server/status/runtime.go:484  [n2] runtime stats: 12 GiB RSS, 4135972 goroutines, 2.1 GiB/746 MiB/11 GiB GO alloc/idle/total, 128 MiB/164 MiB CGO alloc/total, 1010.2 CGO/sec, 57.3/9.5 %(u/s)time, 0.0 %gc (0x), 0.0/116.6/2 (%r/%w/q)disk, 589 KiB/559 KiB (r/w)net
I180920 17:28:13.928901 406 gossip/gossip.go:563  [n2] gossip status (ok, 3 nodes)
gossip client (0/3 cur/max conns)
gossip server (1/3 cur/max conns, infos 2277673/3489497 sent/received, bytes 395463187B/486379797B sent/received)
  1: cockroach-catrina-0001:26257 (2h29m38s)
gossip connectivity
  n1 [sentinel];
  n1 -> n2; n3 -> n1;
```

Similarly on n3:

```
I180920 17:40:48.847993 211 server/status/runtime.go:484  [n3] runtime stats: 3.0 GiB RSS, 847448 goroutines, 744 MiB/30
4 MiB/2.8 GiB GO alloc/idle/total, 92 MiB/132 MiB CGO alloc/total, 1137.2 CGO/sec, 69.4/8.4 %(u/s)time, 0.0 %gc (0x), 0.
0/88.4/0 (%r/%w/q)disk, 792 KiB/940 KiB (r/w)net
```

That's all I know so far. Perhaps the peer ack web app, or whatever else is running against this cluster, is somehow tickling this bug.

**Comment by benesch** [comment]
Brought the cluster back online and the goroutines are already climbing. Yikes!

**Comment by benesch** [comment]
Fascinating. The goroutines are all here:

```
goroutine 9167 [semacquire, 19 minutes]:
sync.runtime_SemacquireMutex(0xc42042426c, 0x0)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420424268)
	/usr/local/go/src/sync/mutex.go:134 +0x108
github.com/cockroachdb/cockroach/vendor/github.com/openzipkin/zipkin-go-opentracing.(*HTTPCollector).send(0xc42a75de60, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/openzipkin/zipkin-go-opentracing/collector-http.go:192 +0x4f
created by github.com/cockroachdb/cockroach/vendor/github.com/openzipkin/zipkin-go-opentracing.(*HTTPCollector).loop
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/openzipkin/zipkin-go-opentracing/collector-http.go:162 +0x3de
```

**Comment by benesch** [comment]
Well, looks like this Zipkin tracing library we use has no protection against spawning too many goroutines. 

I ran `reset cluster setting trace.zipkin.collector` on the assumption that whatever zipkin tracer was previously configured is defunct. Hopefully that takes care of it.

**Comment by tschottdorf** [comment]
https://github.com/openzipkin-contrib/zipkin-go-opentracing/blob/master/collector-http.go#L99

It supposedly uses a HTTP timeout, but likely the goroutines are just piling up at a higher rate than these timeouts fire. But yeah, this code here is pretty bad:

https://github.com/openzipkin-contrib/zipkin-go-opentracing/blob/b85dc675b16b116a00c351d2c41305bf9ae71293/collector-http.go#L158-L163

**Comment by lunevalex** [comment]
go routine proliferation was fixed in v.0.3.5 of zipkin, which is the version we are currently on, release notes https://github.com/openzipkin-contrib/zipkin-go-opentracing/releases/tag/v0.3.5. Closing this issue.
