### ISSUE TITLE
SIGSEGV crash in storage layer

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#30637]
on running  `make stressrace PKG=./pkg/ccl/importccl TESTS=TestImportData` on master

Not sure if it's a core or an IMPORT issue. @tschottdorf to triage.

```
SIGSEGV: segmentation violation
PC=0x65d1cc8 m=12 sigcode=1

goroutine 159 [syscall]:
runtime.cgocall(0x65ff650, 0xc00216ae88, 0x4050100)
	/usr/local/go/src/runtime/cgocall.go:128 +0x6e fp=0xc00216ae40 sp=0xc00216ae08 pc=0x400595e
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBApplyBatchRepr(0xf648e10, 0xc00206b800, 0xc8, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:420 +0x6b fp=0xc00216ae88 sp=0xc00216ae40 pc=0x508edeb
github.com/cockroachdb/cockroach/pkg/storage/engine.dbApplyBatchRepr.func1(0xf648e10, 0xc00206b800, 0xc8, 0xc002069c00, 0x0, 0x0)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2534 +0x8d fp=0xc00216aee8 sp=0xc00216ae88 pc=0x50b557d
github.com/cockroachdb/cockroach/pkg/storage/engine.dbApplyBatchRepr(0xf648e10, 0xc00206b800, 0xc8, 0x400, 0x0, 0xc001b020a8, 0x0)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2534 +0x96 fp=0xc00216af78 sp=0xc00216aee8 pc=0x50aa036
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc002069b00, 0x0, 0x1, 0xc001b020a8)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1897 +0x682 fp=0xc00216b0f8 sp=0xc00216af78 pc=0x50a2822
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc002069b00, 0xed33c4c00, 0x0, 0x0)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1828 +0xba6 fp=0xc00216b258 sp=0xc00216b0f8 pc=0x50a1e86
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyRaftCommand(0xc0019e4000, 0x7dc9060, 0xc001c87ef0, 0xc00273a6c0, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5884 +0x582 fp=0xc00216b908 sp=0xc00216b258 pc=0x57fd4a2
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc0019e4000, 0x7dc9060, 0xc001c87ef0, 0xc00273a6c0, 0x8, 0x6, 0xf, 0x100000001, 0x1, 0x3, ...)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5470 +0x614 fp=0xc00216cd88 sp=0xc00216b908 pc=0x57fa134
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc0019e4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4352 +0x1aee fp=0xc00216dc08 sp=0xc00216cd88 pc=0x57f14ae
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc0019e4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4049 +0x11f fp=0xc00216dd00 sp=0xc00216dc08 pc=0x57ef92f
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc000559b80, 0x7dc9060, 0xc000778570, 0xbe)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3912 +0x138 fp=0xc00216dec8 sp=0xc00216dd00 pc=0x5861f08
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc0004e2ea0, 0x7dc9060, 0xc000778570)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:214 +0x37e fp=0xc00216df48 sp=0xc00216dec8 pc=0x584483e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7dc9060, 0xc000778570)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x56 fp=0xc00216df78 sp=0xc00216df48 pc=0x589fbc6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc000261760, 0xc000190bd0, 0xc000261750)
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0x146 fp=0xc00216dfc8 sp=0xc00216df78 pc=0x4cd90e6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00216dfd0 sp=0xc00216dfc8 pc=0x4061701
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/Users/vivek/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xc4

```

**Comment by tschottdorf** [comment]
@vivekmenezes is this using go1.11? @benesch, if so, is this a cache hit for known problem with go 1.11 under race?

**Comment by vivekmenezes** [comment]
yes this is go1.11

**Comment by tschottdorf** [comment]
Ok. This is likely the reason then, see #30334. I'll wait for @benesch to close this.

**Comment by benesch** [comment]
Yep, I'm afraid this is just a known issue that I haven't had time to dig into further. See https://github.com/golang/go/issues/27660 for details if you're curious.
