### ISSUE TITLE
TPC-C Panic: Couldn't exec ALTER TABLE item Split At Values

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#30659]
3 node 32 CPUSs on a restore of tpc-c 5,000

--- FAIL: tpccbench/nodes=3/cpu=32 (13254.20s)
	test.go:498,cluster.go:1220,tpcc.go:594,tpcc.go:265: failed with output 

`"panic: Couldn't exec ALTER TABLE item SPLIT AT VALUES (9900): pq: split at key /Table/61/1/9900 failed: context deadline exceeded\n\ngoroutine 1 [running]:\ngithub.com/cockroachdb/cockroach/pkg/workload/tpcc.splitTables(0xc420575220, 0x1388)\n\t/go/src/github.com/cockroachdb/cockroach/pkg/workload/tpcc/ddls.go:240 +0x35c\ngithub.com/cockroachdb/cockroach/pkg/workload/tpcc.(*tpcc).Ops(0xc420379900, 0xc4200cd080, 0x1, 0x6, 0xc4202b2370, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/cockroachdb/cockroach/pkg/workload/tpcc/tpcc.go:399 +0xccf\ngithub.com/cockroachdb/cockroach/pkg/workload/cli.runRun(0xd62aa0, 0xc420379900, 0xc4200cd080, 0x1, 0x6, 0xc78bc9, 0x4, 0x0, 0x0)\n\t/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:277 +0x29c\ngithub.com/cockroachdb/cockroach/pkg/workload/cli.CmdHelper.func1(0xc42054d680, 0xc4200cd080, 0x1, 0x6, 0x4, 0xa88835)\n\t/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:146 +0x1b3\ngithub.com/cockroachdb/cockroach/pkg/workload/cli.HandleErrs.func1(0xc42054d680, 0xc4200cd080, 0x1, 0x6)\n\t/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/cli.go:79 +0x57\ngithub.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0xc42054d680, 0xc4200ccfc0, 0x6, 0x6, 0xc42054d680, 0xc4200ccfc0)\n\t/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:702 +0x2c6\ngithub.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420125200, 0x0, 0xc98d25, 0x29)\n\t/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:783 +0x2e4\ngithub.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420125200, 0xc420125200, 0xc4200380b8)\n\t/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:736 +0x2b\nmain.main()\n\t/go/src/github.com/cockroachdb/cockroach/pkg/cmd/workload/main.go:27 +0x34\nError:  exit status 2\n": /Users/andrewwoods/go/bin/roachprod run andy-1537917347-tpccbench-nodes-3-cpu-32:4 -- ulimit -n 32768; ./workload run tpcc --warehouses=5000 --split --scatter  --duration=3m --tolerate-errors {pgurl:1}: exit status 1
FAIL`

**Comment by nvanbenschoten** [comment]
@awoods187 mind updating this issue with the steps you took to find this issue? If this was just a simple `roachtest` invocation, could you post the command you ran (e.g. `roachtest bench ...`).

**Comment by awoods187** [comment]
Updated!

**Comment by petermattis** [comment]
Note that this is a panic in `workload`, not `cockroach`. We should figure out why the split didn't finish, though.

**Comment by awoods187** [comment]
Tried to repro this with the same setup and a node died:

```
   1: done
   2: done
   3: done
   4: ~ scp -r -C -i /Users/andrewwoods/.ssh/google_compute_engine -o StrictHostKeyChecking=no andrewwoods@35.196.34.61:logs artifacts/tpccbench/nodes=3/cpu=32/4.logs
scp: logs: No such file or directory
: exit status 1
2018/09/26 22:38:40 get logs failed
skipping cluster wipe
--- FAIL: tpccbench/nodes=3/cpu=32 (10601.96s)
	test.go:498,cluster.go:1220,tpcc.go:594,tpcc.go:265: unexpected node event: 1: dead
FAIL```

**Comment by nvanbenschoten** [comment]
@awoods187 do have an estimate on how old your `roachprod` binary was when you ran the first test here? I looked at the logs on the nodes and they all look exactly like what we saw in https://github.com/cockroachdb/cockroach/issues/27815, which was fixed in https://github.com/cockroachdb/roachprod/pull/204. Is it possible that your `roachprod` binary was a week old?

Also, Andy and I chatted offline and debugged the second failure. The test was restoring a TPCC 5k dataset into a 3-node cluster and hit a file descriptor limit error beneath Raft when sideloading an sst. In retrospect, this isn't too surprising since we usually run TPC-C 5k on clusters with a lot more nodes. In this case, he was using 32-core machines, but that didn't make a difference to the suprisingly low default open file descriptor limit. This should be avoided in the future by https://github.com/cockroachdb/roachprod/pull/207.

**Comment by awoods187** [comment]
Yeah I think Roachprod was more than a week old. I think we can close this.
