### ISSUE TITLE
orms: sqlalchemy doesn't know how to handle retry errors in DDL statements

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31094]
**Describe the problem**

I followed the Movr instructions (https://github.com/cockroachdb/movr)

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. export FULLNAME="andy-test"
2. export RELEASE_VERSION='v2.1.0-beta.20181001'
3. export COCKROACH_DEV_LICENSE='redacted'
4. ssh-add ~/.ssh/google_compute_engine
5. roachprod create ${FULLNAME} --gce-zones us-west1-b,europe-west2-b,us-east1-b --geo --nodes 9 && crl-stage-binaries ${FULLNAME} all scripts && crl-stage-binaries ${FULLNAME} all release && roachprod start ${FULLNAME} --sequential
6. roachprod pgurl ${FULLNAME} --external
7. cockroach sql --insecure --url postgres://root@104.198.0.224:26257?sslmode=disable -e "create database movr;"
8. docker run -it --rm natestewart/movr --url "postgres://root@104.198.0.224:26257/movr?sslmode=disable" load --enable-geo-partitioning

I see: 
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
(Background on this error at: http://sqlalche.me/e/e3q8)

I checked the logs and see lots of context deadline exceeded:

```
E181008 18:09:46.097805 44085 server/admin.go:173 admi-show-db: context deadline exceeded
E181008 18:09:46.175336 44088 server/admin.go:212 admin-show-grants: context deadline exceeded
E181008 18:09:46.189935 44041 server/admin.go:212 admin-show-grants: context deadline exceeded
E181008 18:09:46.200893 44044 server/admin.go:212 admin-show-grants: context deadline exceeded
E181008 18:09:46.210733 44074 server/admin.go:212 admin-show-grants: context deadline exceeded
```

**Expected behavior**
I expect the command to work and to be able to continue to follow the Movr demo. 

**Environment:**
 - CockroachDB v2.1.0-beta.20181001'

https://github.com/cockroachdb/movr/issues/49

**Comment by awoods187** [comment]
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2457262/cockroach.log)

**Comment by awoods187** [comment]
I can extend the cluster too if needed

**Comment by awoods187** [comment]
Good news: I can repro the above problem by following the exact steps listed above on another cluster.

@piyush-singh and I noticed that when i run the command
`cockroach sql --insecure --url postgres://root@104.198.0.224:26257?sslmode=disable -e "create database movr;"` 

My local cockroach is actually 2.0.5 and doesn't match the 2.1 beta created above. 

I'm attempting to do this a third time but with:
`./cockroach sql --insecure --url postgres://root@104.198.0.224:26257?sslmode=disable -e "create database movr;"`  to see if it works as expected

**Comment by awoods187** [comment]
so it reproduces for the third time with the same:

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
 (Background on this error at: http://sqlalche.me/e/e3q8)

However I don't see any errors in the logs 
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2457416/cockroach.log)

**Comment by awoods187** [comment]
Doesn't repro on 2.0.6!

**Comment by awoods187** [comment]
We tried this locally with:

`docker run -it --rm natestewart/movr --url postgres://root@docker.for.mac.localhost:26257/movr?sslmode=disable --echo-sql load --enable-geo-partitioning` and it worked no problem

**Comment by awoods187** [comment]
So to wrap up, it works locally on 2.1 and distributed on 2.0.6 but not on distributed 2.1. I think we can narrow this down to some sort of core/networking problem cc @tkschmidt

**Comment by tschottdorf** [comment]
Works here, I'm going to try again.

**Comment by tschottdorf** [comment]
Worked twice. I'm going to try another node just for kicks.

**Comment by tschottdorf** [comment]
Worked thrice. I'm going to do this all over again with a new cluster.

**Comment by awoods187** [comment]
Just reprod on 1008

```Andrews-MacBook-Pro-2:cockroach-v2.1.0-beta.20181008.darwin-10.9-amd64 andrewwoods$ docker run -it --rm natestewart/movr --url "postgres://root@35.230.117.113:26257/movr?sslmode=disable" load --enable-geo-partitioning
[INFO] (MainThread) Connected to movr database @ postgres://root@35.230.117.113:26257/movr?sslmode=disable
[INFO] (MainThread) initializing tables
Traceback (most recent call last):
  File "./loadmovr.py", line 206, in <module>
    with MovR(conn_string, init_tables=(not args.skip_reload_tables), echo=args.echo_sql) as movr:
  File "/usr/src/app/movr.py", line 33, in __init__
    Base.metadata.create_all(bind=self.engine)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 796, in visit_table
    self.traverse_single(index)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 823, in visit_index
    self.connection.execute(CreateIndex(index))
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1220, in _execute_context
    self._root._commit_impl(autocommit=True)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 726, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 724, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 462, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
 (Background on this error at: http://sqlalche.me/e/e3q8)```

Logs:
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2480201/cockroach.log)

**Comment by tschottdorf** [comment]
I'm seeing these context canceled errors as well, but more interestingly, I also see `[n1] query execution canceled` from distsqlrun/server.go which seem correlated with it (this might just be the same query, I think these are adminui endpoints being hit and issuing queries):

```
E181015 19:12:52.527165 7161 sql/distsqlrun/server.go:581  [n1] query execution canceled
E181015 19:12:52.527488 7157 server/admin.go:1150  admin-jobs: context deadline exceeded
I181015 19:12:54.170136 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:12:48.343599233 +0000 UTC
I181015 19:13:00.381674 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:12:54.344945713 +0000 UTC
I181015 19:13:00.641210 110 server/status/runtime.go:465  [n1] runtime stats: 384 MiB RSS, 340 goroutines, 164 MiB/129 MiB/328 MiB GO alloc/idle/total, 72 MiB/83 MiB CGO alloc/total, 30.4 CGO/sec, 2.7/1.4 %(u/s)time, 0.0 %gc (0x), 714 KiB/1.2 MiB (r/w)net
I181015 19:13:06.743014 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:13:00.346496798 +0000 UTC
I181015 19:13:10.596830 106 gossip/gossip.go:557  [n1] gossip status (ok, 9 nodes)
gossip client (0/3 cur/max conns)
gossip server (3/3 cur/max conns, infos 11178/3974 sent/received, bytes 3277529B/1177928B sent/received)
  2: andy-test-0002:26257 (7m58s)
  3: andy-test-0003:26257 (7m55s)
  4: andy-test-0004:26257 (7m52s)
I181015 19:13:10.642085 110 server/status/runtime.go:465  [n1] runtime stats: 386 MiB RSS, 340 goroutines, 183 MiB/114 MiB/328 MiB GO alloc/idle/total, 72 MiB/83 MiB CGO alloc/total, 28.2 CGO/sec, 2.7/1.1 %(u/s)time, 0.0 %gc (0x), 694 KiB/1.2 MiB (r/w)net
I181015 19:13:12.956604 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:13:07.34816198 +0000 UTC
I181015 19:13:19.170259 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:13:13.349539677 +0000 UTC
I181015 19:13:20.642948 110 server/status/runtime.go:465  [n1] runtime stats: 326 MiB RSS, 340 goroutines, 202 MiB/98 MiB/328 MiB GO alloc/idle/total, 17 MiB/27 MiB CGO alloc/total, 25.9 CGO/sec, 6.4/1.1 %(u/s)time, 0.0 %gc (0x), 696 KiB/1.2 MiB (r/w)net
E181015 19:13:22.596267 7432 sql/distsqlrun/server.go:581  [n1] query execution canceled
E181015 19:13:22.596553 7415 server/admin.go:1150  admin-jobs: context deadline exceeded
I181015 19:13:25.384763 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:13:19.350924642 +0000 UTC
I181015 19:13:30.643812 110 server/status/runtime.go:465  [n1] runtime stats: 327 MiB RSS, 339 goroutines, 220 MiB/82 MiB/328 MiB GO alloc/idle/total, 17 MiB/27 MiB CGO alloc/total, 28.5 CGO/sec, 2.2/1.5 %(u/s)time, 0.0 %gc (0x), 704 KiB/1.2 MiB (r/w)net
I181015 19:13:31.744983 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:13:25.352422565 +0000 UTC
I181015 19:13:37.959792 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:13:32.354047613 +0000 UTC
I181015 19:13:40.644664 110 server/status/runtime.go:465  [n1] runtime stats: 329 MiB RSS, 344 goroutines, 239 MiB/64 MiB/328 MiB GO alloc/idle/total, 17 MiB/27 MiB CGO alloc/total, 28.0 CGO/sec, 2.6/1.3 %(u/s)time, 0.0 %gc (0x), 709 KiB/1.2 MiB (r/w)net
I181015 19:13:44.173004 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:13:38.355275629 +0000 UTC
I181015 19:13:50.388811 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:13:44.356828506 +0000 UTC
I181015 19:13:50.645549 110 server/status/runtime.go:465  [n1] runtime stats: 330 MiB RSS, 344 goroutines, 258 MiB/46 MiB/328 MiB GO alloc/idle/total, 17 MiB/27 MiB CGO alloc/total, 28.8 CGO/sec, 2.3/1.5 %(u/s)time, 0.0 %gc (0x), 698 KiB/1.2 MiB (r/w)net
E181015 19:13:52.683000 7695 sql/distsqlrun/server.go:581  [n1] query execution canceled
E181015 19:13:52.683339 7660 server/admin.go:1150  admin-jobs: context deadline exceeded
I181015 19:13:56.742960 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:13:50.358254712 +0000 UTC
I181015 19:14:00.646429 110 server/status/runtime.go:465  [n1] runtime stats: 331 MiB RSS, 343 goroutines, 277 MiB/28 MiB/328 MiB GO alloc/idle/total, 17 MiB/27 MiB CGO alloc/total, 26.3 CGO/sec, 2.6/1.3 %(u/s)time, 0.0 %gc (0x), 926 KiB/1.2 MiB (r/w)net
I181015 19:14:02.956573 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:13:57.359905122 +0000 UTC
I181015 19:14:09.169427 5993 sql/lease.go:345  [n1,client=206.252.208.94:59931,user=root,scExec] publish: descID=54 (vehicles) version=5 mtime=2018-10-15 19:14:03.361067132 +0000 UTC
```

Note that this is happening during schema load (at least there are table descriptors publishing in the logs)

I'm not seeing any indication of fundamental badness here. I'm not really sure what to do here. This might be a problem in movr (perhaps an overzealous sqlalchemy connection timeout but I didn't see one) or a hiccup in SQL.

I did manage to "repro" the below, though. @jordanlewis, could you route this issue to someone in SQL-land? @awoods187 should comment on the priority.

```
$ while [ $? -eq 0 ]; do docker run -it --rm natestewart/movr --url "postgres://root@35.230.117.113:26257/movr?sslmode=disable" load --enable-geo-partitioning; done
[INFO] (MainThread) Connected to movr database @ postgres://root@35.230.117.113:26257/movr?sslmode=disable
[INFO] (MainThread) initializing tables
Traceback (most recent call last):
  File "./loadmovr.py", line 206, in <module>
    with MovR(conn_string, init_tables=(not args.skip_reload_tables), echo=args.echo_sql) as movr:
  File "/usr/src/app/movr.py", line 32, in __init__
    Base.metadata.drop_all(bind=self.engine)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 4032, in drop_all
    tables=tables)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 906, in visit_metadata
    table, drop_ok=True, _is_metadata_operation=True)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 951, in visit_table
    self.connection.execute(DropTable(table))
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1220, in _execute_context
    self._root._commit_impl(autocommit=True)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 726, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 724, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 462, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (psycopg2.extensions.TransactionRollbackError) restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=469e1d57 key=/Table/SystemConfigSpan/Start rw=true pri=0.02571209 iso=SERIALIZABLE stat=PENDING epo=0 ts=1539708794.659796952,1 orig=1539708793.921301537,0 max=1539708794.247012999,0 wto=false rop=false seq=30
 (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by jordanlewis** [comment]
This is exactly the same problem that @bobvawter was just about to look into in context of the sqlalchemy ORM test flakiness. SQL Alchemy is not equipped to deal with retryable txn errors during schema change operations.

**Comment by bobvawter** [comment]
The SQLAlchemy Example-ORM tests have been stable for the past couple of weeks, modulo what appear to be some image-pull network glitches.  @awoods187, is this continuing to be a problem for you?

**Comment by awoods187** [comment]
Well has anything changed since I last ran the test?

**Comment by jordanlewis** [comment]
No, this is a CockroachDB problem for sure, unless somebody fixed it by accident. The issue is that DDL statement sometimes return retryable errors. This condition should never happen - they can and should retry internally.

**Comment by knz** [comment]
DDL statements issued inside an explicit txn can hit a retry condition which they cannot retry internally (no stmt inside an explicit txn can retry internally if some data has been returned to the client already). I am not sure what you are suggesting.

**Comment by jordanlewis** [comment]
The DDLs issued by SQL Alchemy aren't inside of an explicit transaction, unless I'm mistaken.

**Comment by knz** [comment]
Well then this needs to be further investigated. Also the issue title is problematic. Neither the original title nor my correction are appropriate.

Jordan since you understand this issue, do you mind authoring a properly descriptive issue title? Then suggest a proper triage (labels + project). I am not sure any more where this should go.

**Comment by bobvawter** [comment]
Working notes for Monday bug-fix session:

* [X] Getting sqlalchemy, crdb extensions updated
* [X] Download pycharm
* [X] Clone examples-orms
* [X] Set up ORM tests locally
  * Follow directions in examples-orms readme.
* [X] Replicate failure
  * Really just need to start-stop the python server process. The failure is when it's trying to set up the db schema.
```go
func TestSQLAlchemyStart(t *testing.T) {
	app := application{
		language: "python",
		orm:      "sqlalchemy",
	}

	_, dbURL, stopDB := initTestDatabase(t, app)
	defer stopDB()

	if stopApp, err := initORMApp(app, dbURL); err == nil {
		if err := stopApp(); err != nil {
			t.Fatal(err)
		}
	} else {
		t.Fatal(err)
	}
}
```

```
ADDR=cockroachdb://root@localhost:49653/company_sqlalchemy?sslmode=disable ./server.py --port=6543
/Library/Python/2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "./server.py", line 61, in <module>
    app = setup_app()
  File "./server.py", line 57, in setup_app
    db.create_all()
  File "/Library/Python/2.7/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/Library/Python/2.7/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1220, in _execute_context
    self._root._commit_impl(autocommit=True)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 726, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 724, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 462, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (psycopg2.extensions.TransactionRollbackError) restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=df3c698b key=/Table/SystemConfigSpan/Start rw=true pri=0.04455098 stat=PENDING epo=0 ts=1546875621.756046000,2 orig=1546875621.726059000,0 max=1546875621.726059000,0 wto=false seq=19
 (Background on this error at: http://sqlalche.me/e/e3q8)
make: *** [start] Error 1
```
* [X] Locate code in sqlalchemy that runs DDLs:
  * `ddl.py` has a class `SchemaGenerator`. It cals `connection.execute()` with a `CreateTable` instance.
* [X] Locate code in sqlalchemy that runs DDLs:
  * `ddl.py` has a class `SchemaGenerator`. It cals `connection.execute()` with a `CreateTable` instance.
* [ ] Determine if we can patch the cockroach dialect to intercept DDL calls to retry them.
* [ ] If not, is it viable to re-run the application init code in a retry loop and update the demo?
