### ISSUE TITLE
Panic when using subqueries with mixed types.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#3167]
Subqueries where the types mismatch are broken. This is best explained using an example.

This is better explained with an example:
```
> create database test;
> set database=test;
> create table test (k int, v string, primary key (k,v));
> insert into test values (0, '1');
> select k from test where (k,v)=(0,'1');
+---+
| k |
+---+
| 0 |
+---+
> select * from test where k=(select k from test where (k,v)=(0,'1'));
I1118 13:30:10.845375 898 http_post.go:106  Post http://localhost:26257/sql/Execute: EOF
```

The crash occurs regardless of the existence of the "0, '1'", row.

The server panics with:
```
I1118 13:30:10.844500 885 server.go:1934  http: panic serving 127.0.0.1:48361: unsupported comparison: string to int
goroutine 541 [running]:
net/http.(*conn).serve.func1(0xc8206b4630, 0x7f789958c240, 0xc82010c260)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/cockroachdb/cockroach/sql/parser.DString.Compare(0xc8201bb340, 0x1, 0x7f78995cc990, 0xc82040e880, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/datum.go:261 +0x302
github.com/cockroachdb/cockroach/sql/parser.(*DString).Compare(0xc82040e890, 0x7f78995cc990, 0xc82040e880, 0x0)
	<autogenerated>:112 +0xac
github.com/cockroachdb/cockroach/sql/parser.DTuple.Less(0xc82037f880, 0x2, 0x2, 0x1, 0x0, 0x85d6e6)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/datum.go:558 +0x77
github.com/cockroachdb/cockroach/sql/parser.(*DTuple).Less(0xc82037fbe0, 0x1, 0x0, 0xfbc806)
	<autogenerated>:143 +0xb5
sort.insertionSort(0x7f78995d4600, 0xc82037fbe0, 0x0, 0x2)
	/usr/local/go/src/sort/sort.go:32 +0x6f
sort.quickSort(0x7f78995d4600, 0xc82037fbe0, 0x0, 0x2, 0x4)
	/usr/local/go/src/sort/sort.go:184 +0x153
sort.Sort(0x7f78995d4600, 0xc82037fbe0)
	/usr/local/go/src/sort/sort.go:199 +0x74
github.com/cockroachdb/cockroach/sql/parser.(*DTuple).Normalize(0xc82037fbe0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/datum.go:567 +0x48
github.com/cockroachdb/cockroach/sql/parser.DTuple.normalize(0xc82037f880, 0x2, 0x2, 0xc82036bdf8, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/normalize.go:295 +0x70
github.com/cockroachdb/cockroach/sql/parser.(*DTuple).normalize(0xc82037f8a0, 0xc82036bdf8, 0x0, 0x0)
	<autogenerated>:146 +0xb7
github.com/cockroachdb/cockroach/sql/parser.(*normalizeVisitor).Visit(0xc82036bdf8, 0x7f78995d4530, 0xc82037f8a0, 0xc82037fb01, 0x0, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/normalize.go:331 +0x116
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7f78984e6ba8, 0xc82036bdf8, 0x7f78995d4530, 0xc82037f8a0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:205 +0x50
github.com/cockroachdb/cockroach/sql/parser.(*ComparisonExpr).Walk(0xc82051d4d0, 0x7f78984e6ba8, 0xc82036bdf8)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:73 +0xc7
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7f78984e6ba8, 0xc82036bdf8, 0x7f789958ce10, 0xc82051d4d0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:210 +0xa1
github.com/cockroachdb/cockroach/sql/parser.(*Parser).NormalizeExpr(0xc8203680e0, 0x1, 0xecddebab2, 0x31ac848c, 0x1f582e0, 0xecddebab2, 0x31ac848c, 0x1f582e0, 0xc82013ba90, 0xc8201bb010, ...)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/parse.go:88 +0xfe
github.com/cockroachdb/cockroach/sql.(*scanNode).initWhere(0xc8201fcf00, 0xc82049a340, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/scan.go:399 +0x2b7
github.com/cockroachdb/cockroach/sql.(*planner).Select(0xc820368000, 0xc8203ee1e0, 0x0, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/select.go:47 +0x169
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc820368000, 0x7f789958cf00, 0xc8203ee1e0, 0x0, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/plan.go:122 +0x136a
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc820368000, 0x7f789958cf30, 0xc8201bb370, 0x0, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/plan.go:108 +0x1032
github.com/cockroachdb/cockroach/sql.(*subqueryVisitor).Visit(0xc8203dde98, 0x7f789958cec0, 0xc8201bb390, 0xc82051d501, 0x0, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/subquery.go:60 +0x2aa
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7f78984e6e38, 0xc8203dde98, 0x7f789958cec0, 0xc8201bb390, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:205 +0x50
github.com/cockroachdb/cockroach/sql/parser.(*ComparisonExpr).Walk(0xc82051d500, 0x7f78984e6e38, 0xc8203dde98)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:73 +0xc7
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7f78984e6e38, 0xc8203dde98, 0x7f789958ce10, 0xc82051d500, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:210 +0xa1
github.com/cockroachdb/cockroach/sql.(*planner).expandSubqueries(0xc8203da000, 0x7f789958ce10, 0xc82051d500, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/subquery.go:28 +0x10f
github.com/cockroachdb/cockroach/sql.(*scanNode).initWhere(0xc8206410e0, 0xc82049a360, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/scan.go:402 +0x383
github.com/cockroachdb/cockroach/sql.(*planner).Select(0xc8203da000, 0xc8203ee280, 0x0, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/select.go:47 +0x169
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc8203da000, 0x7f789958cf00, 0xc8203ee280, 0x0, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/plan.go:122 +0x136a
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt.func1(0xecddebab2, 0xc831ac848c, 0x1f582e0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/executor.go:240 +0x103
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt.func2(0xc8205f8c60, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/executor.go:346 +0x12e
github.com/cockroachdb/cockroach/client.(*Txn).exec(0xc8205f8c60, 0xc8200d6f80, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/txn.go:382 +0x2c1
github.com/cockroachdb/cockroach/client.(*DB).Txn(0xc82008fae0, 0xc8200d6f80, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/db.go:464 +0x169
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc82008fae0, 0x7f789958cf00, 0xc8203ee280, 0xc8203da000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/executor.go:343 +0x677
github.com/cockroachdb/cockroach/sql.(*Executor).execStmts(0xc82008fae0, 0xc82001def0, 0x44, 0xc8203da000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/executor.go:183 +0x300
github.com/cockroachdb/cockroach/sql.(*Executor).Execute(0xc82008fae0, 0xc8201bafe0, 0x4, 0xc8201bb000, 0xa, 0x10, 0xc82001def0, 0x44, 0x0, 0x0, ...)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/executor.go:151 +0x6d2
github.com/cockroachdb/cockroach/sql.Server.ServeHTTP(0xc8201638c0, 0xc82008fae0, 0x7f78984a21b8, 0xc82049a1e0, 0xc8202e80e0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/server.go:99 +0x737
github.com/cockroachdb/cockroach/sql.(*Server).ServeHTTP(0xc82029d730, 0x7f78984a21b8, 0xc82049a1e0, 0xc8202e80e0)
	<autogenerated>:293 +0xb6
net/http.(*ServeMux).ServeHTTP(0xc8202882a0, 0x7f78984a21b8, 0xc82049a1e0, 0xc8202e80e0)
	/usr/local/go/src/net/http/server.go:1699 +0x17d
github.com/cockroachdb/cockroach/server.(*Server).ServeHTTP.func1()
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/server.go:311 +0x206
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc820146c00, 0xc8200db8b8, 0x0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:115 +0x234
github.com/cockroachdb/cockroach/server.(*Server).ServeHTTP(0xc82008f720, 0x7f78984a21b8, 0xc82049a1e0, 0xc8202e80e0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/server.go:312 +0x56
github.com/cockroachdb/cockroach/rpc.(*Server).ServeHTTP(0xc82007aa00, 0x7f78984a2058, 0xc8201e6790, 0xc8202e80e0)
	/home/marc/cockroach/src/github.com/cockroachdb/cockroach/rpc/server.go:157 +0xdb9
net/http.serverHandler.ServeHTTP(0xc82001be00, 0x7f78984a2058, 0xc8201e6790, 0xc8202e80e0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8206b4630)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by mberhault** [comment]
I found this when trying to run the filesystem example.
Anytime we lookup an inode, we perform the following query:
```
SELECT inode FROM fs.inode WHERE id = (SELECT id FROM fs.namespace WHERE (parentID, name) = ($1, $2))`
```

Where fs.inode is:
```
CREATE TABLE IF NOT EXISTS fs.inode (
  id    INT PRIMARY KEY,
  inode STRING
);
```
