### ISSUE TITLE
panic on osx Mojave (10.14) when --background is specified

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#31680]
**Describe the problem**

panic on osx Mojave (10.14) during startup

**To Reproduce**

without `--background` is ok.  

```
$ cockroach start --insecure --background
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.1/secure-a-cluster.html
*
SIGTRAP: trace trap
PC=0x405e9bf m=0 sigcode=1

goroutine 24 [syscall]:
syscall.Syscall6(0x7, 0x53f3, 0xc42056766c, 0x0, 0xc42096e3f0, 0x0, 0x0, 0x90, 0xc42096e3f0, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:41 +0x5 fp=0xc4205675b0 sp=0xc4205675a8 pc=0x408e1b5
syscall.wait4(0x53f3, 0xc42056766c, 0x0, 0xc42096e3f0, 0x90, 0x63855a0, 0x1)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:34 +0x7e fp=0xc420567630 sp=0xc4205675b0 pc=0x408a83e
syscall.Wait4(0x53f3, 0xc4205676bc, 0x0, 0xc42096e3f0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_bsd.go:129 +0x51 fp=0xc420567680 sp=0xc420567630 pc=0x4087a61
os.(*Process).wait(0xc420327d70, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:38 +0x7e fp=0xc4205676f0 sp=0xc420567680 pc=0x40a9cde
os.(*Process).Wait(0xc420327d70, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec.go:123 +0x2b fp=0xc420567720 sp=0xc4205676f0 pc=0x40a920b
os/exec.(*Cmd).Wait(0xc4201158c0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:461 +0x5c fp=0xc420567798 sp=0xc420567720 pc=0x424f0ec
github.com/cockroachdb/cockroach/pkg/util/sdnotify.bgExec.func3(0xc420919c80, 0xc4201158c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/sdnotify/sdnotify_unix.go:92 +0x2b fp=0xc4205677d0 sp=0xc420567798 pc=0x58abacb
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4205677d8 sp=0xc4205677d0 pc=0x405d641
created by github.com/cockroachdb/cockroach/pkg/util/sdnotify.bgExec
	/go/src/github.com/cockroachdb/cockroach/pkg/util/sdnotify/sdnotify_unix.go:91 +0x4f8

goroutine 1 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/sdnotify.bgExec(0xc4201158c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/sdnotify/sdnotify_unix.go:94 +0x51e
github.com/cockroachdb/cockroach/pkg/util/sdnotify.Exec(0xc4201158c0, 0x1c, 0x63dad00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/sdnotify/sdnotify.go:38 +0x2b
github.com/cockroachdb/cockroach/pkg/cli.maybeRerunBackground(0x29210270, 0xed35eaf7f, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start_unix.go:83 +0x31b
github.com/cockroachdb/cockroach/pkg/cli.runStart(0x7e0e6e0, 0xc42033e780, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:403 +0x6d
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x7e0e6e0, 0xc42033e780, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:70 +0x6b
github.com/cockroachdb/cockroach/pkg/cli.maybeShoutError.func1(0x7e0e6e0, 0xc42033e780, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:215 +0x4d
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x7e0e6e0, 0xc42033e760, 0x2, 0x2, 0x7e0e6e0, 0xc42033e760)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:698 +0x46d
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x7e09620, 0x8, 0x0, 0xc420849ec8)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0x7e09620, 0x18, 0xc420849ee0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/cockroachdb/cockroach/pkg/cli.Run(0xc42004c150, 0x3, 0x3, 0xc420052078, 0xc4200f5980)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:193 +0x6d
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:69 +0x223
main.main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:30 +0x20

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa7
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 34 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1203 +0xf1
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:619 +0x126

goroutine 35 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.signalFlusher()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:626 +0xab
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:620 +0x13e

goroutine 8 [select, locked to thread]:
runtime.gopark(0x653bb90, 0x0, 0x63e0271, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc420071750, 0xc4200b1c20)
	/usr/local/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:549 +0x1c6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 22 [select]:
github.com/cockroachdb/cockroach/vendor/go.opencensus.io/stats/view.(*worker).start(0xc4204ae500)
	/go/src/github.com/cockroachdb/cockroach/vendor/go.opencensus.io/stats/view/worker.go:144 +0x11d
created by github.com/cockroachdb/cockroach/vendor/go.opencensus.io/stats/view.init.0
	/go/src/github.com/cockroachdb/cockroach/vendor/go.opencensus.io/stats/view/worker.go:29 +0x58

goroutine 23 [IO wait]:
internal/poll.runtime_pollWait(0xac70e30, 0x72, 0xc420565de8)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42050ed98, 0x72, 0xffffffffffffff00, 0x6909480, 0x7865550)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42050ed98, 0xc420565f00, 0x7, 0x7)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42050ed80, 0xc420565f41, 0x7, 0x7, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x1dc
net.(*netFD).Read(0xc42050ed80, 0xc420565f41, 0x7, 0x7, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc420570298, 0xc420565f41, 0x7, 0x7, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
github.com/cockroachdb/cockroach/pkg/util/sdnotify.listener.wait(0xc42096c6e0, 0x4e, 0xc42096c640, 0x42, 0xc420570298, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/sdnotify/sdnotify_unix.go:128 +0x5d
github.com/cockroachdb/cockroach/pkg/util/sdnotify.bgExec.func2(0xc420919c80, 0xc42096c6e0, 0x4e, 0xc42096c640, 0x42, 0xc420570298)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/sdnotify/sdnotify_unix.go:89 +0x48
created by github.com/cockroachdb/cockroach/pkg/util/sdnotify.bgExec
	/go/src/github.com/cockroachdb/cockroach/pkg/util/sdnotify/sdnotify_unix.go:88 +0x4c9

rax    0x16
rbx    0xc420572d80
rcx    0x405e9bd
rdx    0x14
rdi    0xc420009f48
rsi    0x1e
rbp    0xc420009ab0
rsp    0xc420009a88
r8     0xc420009f48
r9     0x55bed6e16649c245
r10    0xc42096e3f0
r11    0x213
r12    0xffffffffffffffff
r13    0x8
r14    0x7
r15    0x38
rip    0x405e9bf
rflags 0x213
cs     0x2b
fs     0x0
gs     0x0
```
**Environment:**

```
$ cockroach version
Build Tag:    v2.1.0-beta.20181015
Build Time:   2018/10/15 18:29:15
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin13)
Go Version:   go1.10.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  ad11a2508ae2b8b006b0c6c14793a20ce85e5f72
Build Type:   release
```

```
 uname -a
Darwin mbg.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
```

**Comment by knz** [comment]
cc @bdarnell this makes me think Go signal handling on osx Mojave is outright broken.
