### ISSUE TITLE
cli: stuck in grpc.Server.Close() on quit

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#31690]
I was working on the decommissioning roachtest when I had a local (osx mojave) run in which the following happened:

```
./cockroach quit --insecure --port 26257 // likely returned with a "hard shutdown" message, but I can't see that
./cockroach decommission 1 --port 26259 // against other node, hangs with lots of replicas on n1
```

The decommissioning command got stuck (lots of replicas remained on n1). The `./cockroach quit` invocation never returned server-side. It's in the following stack, trying to stop the `*grpc.Server`.

What's concerning is that `./cockroach quit` looks like it announced success, but the process is still running (though with 26257 closed) and in good enough shape to be "live" (though it's "suspect" in the ui and its logs are full of errors).

```
goroutine 15614 [semacquire, 15 minutes]:
sync.runtime_Semacquire(0xc000a1015c)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000a1015c)
	/usr/local/Cellar/go/1.11.1/libexec/src/sync/waitgroup.go:130 +0x64
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Stop.func2(0xc000a10000)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1324 +0x34
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Stop(0xc000a10000)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1358 +0x282
github.com/cockroachdb/cockroach/pkg/server.(*adminServer).Drain(0xc000740c60, 0xc00b9a3400, 0x6e38c00, 0xc00cae9de0, 0xc000740c60, 0x0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/server/admin.go:1301 +0x30e
github.com/cockroachdb/cockroach/pkg/server/serverpb._Admin_Drain_Handler(0x66f7e00, 0xc000740c60, 0x6e35ea0, 0xc009952160, 0x400ea38, 0x20)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go:1877 +0x109
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func2(0x66f7e00, 0xc000740c60, 0x6e35ea0, 0xc009952160, 0xc0308612c0, 0x6890df8, 0x6e1b280, 0xc000369ec0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:214 +0x100
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc000a10000, 0x6e3e8a0, 0xc00d621800, 0xc00d101c00, 0xc0007cf2c0, 0x8a01e80, 0x0, 0x0, 0x0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1167 +0x440
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000a10000, 0x6e3e8a0, 0xc00d621800, 0xc00d101c00, 0x0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1253 +0x12a1
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00039faf0, 0xc000a10000, 0x6e3e8a0, 0xc00d621800, 0xc00d101c00)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:680 +0x9f
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:678 +0xa1
```

Another goroutine is in

```
goroutine 94 [chan receive, 15 minutes]:
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.muxListener.Accept(0x6e16180, 0xc0007383a0, 0xc000aade60, 0xc000c3ae60, 0x18, 0xc000c50a80, 0x4575542)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:184 +0x41
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve(0xc000a10000, 0x6e16f00, 0xc000392ba0, 0x0, 0x0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:544 +0x210
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func7(0x6e1a680, 0xc000866090)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1185 +0x43
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc0002dff80, 0xc0001d7950, 0xc000392c40)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xa8
```

perhaps that's related.

Full goroutine dump here: https://gist.github.com/tschottdorf/a266079d40206e52d286707cb45964aa

**Comment by knz** [comment]
Fixed in #37668
