### ISSUE TITLE
sql: panic: tree.TypedExpr is *tree.CastExpr, not *tree.FuncExpr

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#31755]
`SELECT -MINVALUE AS overlaps FROM ROWS FROM (CAST('string' AS SERIAL2[])) AS ident WHERE (MAXVALUE IS NOT true) IS OF (REGNAMESPACE)`

Found with RSG. Present in 2.1 also.

**Comment by jordanlewis** [comment]
@mjibson would be useful if you could include the stack trace for things like this, since it'll help show what team to route to.

```
goroutine 348 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc000f94000, 0x6dc1c00, 0xc001590940, 0x6393100, 0xc00149f8f0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:678 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc000f94000, 0x6dc1c00, 0xc001590940)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:419 +0x61
panic(0x6393100, 0xc00149f8f0)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1(0xc000e16af0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:137 +0x9a
panic(0x6393100, 0xc00149f8f0)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildZip(0xc000e045a0, 0xc001611570, 0x1, 0x1, 0xc000c87000, 0xc000c870f0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/srfs.go:96 +0x865
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildDataSource(0xc000e045a0, 0x6d9d000, 0xc0003a2500, 0x0, 0xc000c87000, 0xc000763980)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:99 +0x7c0
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildDataSource(0xc000e045a0, 0x6d9cb40, 0xc000e96c80, 0x0, 0xc000c87000, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:49 +0x5b3
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFromTables(0xc000e045a0, 0xc001611580, 0x1, 0x1, 0xc000c87000, 0xed3615b53)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:599 +0x72
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFrom(0xc000e045a0, 0xc00149f5c0, 0xc0003a2580, 0xc000c87000, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:556 +0x534
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause(0xc000e045a0, 0xc0007e2870, 0x0, 0x0, 0x0, 0xc000c87000, 0xab4914bb5ac6f3a5)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:498 +0x67
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc000e045a0, 0xc0014f9cc0, 0xc000c87000, 0xe8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:453 +0x1d1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc000e045a0, 0x6dc53c0, 0xc0014f9cc0, 0xc000c87000, 0x4)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:187 +0xf1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc000e045a0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:144 +0xf6
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc000f94420, 0x6dc1cc0, 0xc00149f710, 0x6dc53c0, 0xc0014f9cc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:425 +0x2cb
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optionallyUseOptimizer(0xc000f94420, 0x6dc1cc0, 0xc00149f710, 0xc001216015, 0x10, 0x66e1009, 0x9, 0x0, 0x1, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:552 +0xc4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc000f94000, 0x6dc1cc0, 0xc00149f710, 0x6dc53c0, 0xc0014f9cc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:766 +0x189
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc000f94000, 0x6dc1cc0, 0xc00149f710, 0x6dc53c0, 0xc0014f9cc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:403 +0xaae
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc000f94000, 0x6dc1cc0, 0xc00149f710, 0x6dc53c0, 0xc0014f9cc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95 +0x333
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc000f94000, 0x6dc1c00, 0xc001590940, 0xc000795bd8, 0x5400, 0x15000, 0xc000795c70, 0xc0003cc480, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1144 +0x2146
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0009483c0, 0x6dc1c00, 0xc001590940, 0xc000f94000, 0x5400, 0x15000, 0xc000795c70, 0xc0003cc480, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:421 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc0009483c0, 0x6dc1c00, 0xc001590940, 0xc000f94000, 0x5400, 0x15000, 0xc000795c70, 0xc0003cc480, 0xc0003cc490, 0xc000446614)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:309 +0x81
```

Looks like this is an opt issue, no?

**Comment by andy-kimball** [comment]
Rebecca, can you look? Looks like an srf related bug.

**Comment by rytaft** [comment]
Yep - should be an easy fix
