### ISSUE TITLE
TestRaftRemoveRace: requested entry at index unavailable in raft.(*raftLog).term

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3178]
found on #3175 

https://circleci.com/gh/tschottdorf/cockroach/1690

```
I1120 03:19:36.775095 1011 storage/replica_command.go:458  auto-gc'ed ec6a6d14 (3 intents)
I1120 03:19:36.776162 1011 storage/store.go:1506  raft: REMOVE_REPLICA {3 3 4} for range 1
I1120 03:19:36.776720 1011 multiraft/multiraft.go:825  node 3: got message for unknown group 1; creating it
I1120 03:19:36.777035 1011 raft/raft.go:409  [group 1] 4 became follower at term 6
I1120 03:19:36.777151 1011 raft/raft.go:218  [group 1] newRaft 4 [peers: [1,2], term: 6, commit: 18, applied: 18, lastindex: 18, lastterm: 6]
W1120 03:19:36.777238 1011 multiraft/multiraft.go:1092  failed to look up replica ID for range 1 (disabling replica ID check): storage/store.go:1655: store 3 not found as replica of range 1
panic: requested entry at index is unavailable

goroutine 6322 [running]:
github.com/coreos/etcd/raft.(*raftLog).term(0xc820198000, 0x12, 0x100, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/log.go:231 +0x1a9
github.com/coreos/etcd/raft.(*raftLog).matchTerm(0xc820198000, 0x12, 0x6, 0x8b4b4b)
	/go/src/github.com/coreos/etcd/raft/log.go:265 +0x2b
github.com/coreos/etcd/raft.(*raftLog).maybeAppend(0xc820198000, 0x12, 0x6, 0x16, 0xc8206557a0, 0x4, 0x4, 0x16, 0xc8202caa00)
	/go/src/github.com/coreos/etcd/raft/log.go:78 +0x5d
github.com/coreos/etcd/raft.(*raft).handleAppendEntries(0xc8204c9ba0, 0x3, 0x4, 0x1, 0x6, 0x6, 0x12, 0xc8206557a0, 0x4, 0x4, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:687 +0x1f1
github.com/coreos/etcd/raft.stepFollower(0xc8204c9ba0, 0x3, 0x4, 0x1, 0x6, 0x6, 0x12, 0xc8206557a0, 0x4, 0x4, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:658 +0x3b9
github.com/coreos/etcd/raft.(*raft).Step(0xc8204c9ba0, 0x3, 0x4, 0x1, 0x6, 0x6, 0x12, 0xc8206557a0, 0x4, 0x4, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:511 +0x2a8
github.com/coreos/etcd/raft.(*multiNode).run(0xc820406a80)
	/go/src/github.com/coreos/etcd/raft/multinode.go:258 +0x11fa
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:71 +0x30d
```

**Comment by tschottdorf** [comment]
and again: https://circleci.com/gh/tschottdorf/cockroach/1689

**Comment by es-chow** [comment]
This race may be the same as https://github.com/cockroachdb/cockroach/pull/3115 commit 2.

**Comment by BramGruneir** [comment]
No longer failing.
