### ISSUE TITLE
Dead node with a failure of consistency check 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31824]
**Describe the problem**

Node died during restore on TPC-C 10k on 9 node 64 cpu cluster. 

```
F181024 14:56:22.095170 201371 storage/replica_consistency.go:152  [n6,consistencyChecker,s6,r37600/3:/Table/60/2/95{117/7…-267/8…}] consistency check failed with 1 inconsistent replicas
goroutine 201371 [running]:
```

**To Reproduce**

```diff
diff --git a/pkg/cmd/roachtest/tpcc.go b/pkg/cmd/roachtest/tpcc.go
index b6fee081e3..45a8821c1d 100644
--- a/pkg/cmd/roachtest/tpcc.go
+++ b/pkg/cmd/roachtest/tpcc.go
@@ -336,9 +336,10 @@ func registerTPCCBenchSpec(r *registry, b tpccBenchSpec) {
        nodes := nodes(numNodes, opts...)
 
        r.Add(testSpec{
-               Name:   name,
-               Nodes:  nodes,
-               Stable: true, // DO NOT COPY to new tests
+               Timeout: 100 * time.Hour,
+               Name:    name,
+               Nodes:   nodes,
+               Stable:  true, // DO NOT COPY to new tests
                Run: func(ctx context.Context, t *test, c *cluster) {
                        runTPCCBench(ctx, t, c, b)
                },
@@ -403,7 +404,7 @@ func loadTPCCBench(
        }
 
        partArgs := ""
-       rebalanceWait := time.Duration(b.LoadWarehouses/100) * time.Minute
+       rebalanceWait := time.Duration(b.LoadWarehouses/25) * time.Minute
        switch b.LoadConfig {
        case singleLoadgen:
                t.l.Printf("splitting and scattering\n")
@@ -677,11 +678,11 @@ func registerTPCCBench(r *registry) {
                        // StoreDirVersion: "2.0-5",
                },
                {
-                       Nodes: 3,
-                       CPUs:  16,
+                       Nodes: 9,
+                       CPUs:  64,
 
-                       LoadWarehouses: 2000,
-                       EstimatedMax:   1300,
+                       LoadWarehouses: 10000,
+                       EstimatedMax:   8000,
```

`bin/roachtest bench '^tpccbench/nodes=9/cpu=64$$' --wipe=false --user=andy`

**Additional data / screenshots**
**Environment:**
 - CockroachDB version 2.1 rc 1

`andy-1540386537-tpccbench-nodes-9-cpu-64`
[logs.zip](https://github.com/cockroachdb/cockroach/files/2512004/logs.zip)

**Comment by awoods187** [comment]
Full errror:
```
F181024 14:56:22.095170 201371 storage/replica_consistency.go:152  [n6,consistencyChecker,s6,r37600/3:/Table/60/2/95{117/7…-267/8…}] consistency check failed with 1 inconsistent replicas
goroutine 201371 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc420057900, 0xc420057920, 0x3ebba00, 0x1e)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:997 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x47ae200, 0xc400000004, 0x3ebba94, 0x1e, 0x98, 0xc4258305a0, 0x7b)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:864 +0x8fe
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2ff6020, 0xc42bbac540, 0x4, 0x2, 0x2b252c9, 0x36, 0xc43e1aa2e0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2ff6020, 0xc42bbac540, 0x1, 0xc400000004, 0x2b252c9, 0x36, 0xc43e1aa2e0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2ff6020, 0xc42bbac540, 0x2b252c9, 0x36, 0xc43e1aa2e0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc42c789500, 0x2ff6020, 0xc42bbac540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_consistency.go:152 +0xc8f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc42c789500, 0x2ff6020, 0xc42bbac540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_consistency.go:161 +0xdd5
github.com/cockroachdb/cockroach/pkg/storage.(*consistencyQueue).process(0xc420ebe2a0, 0x2ff6020, 0xc42bbac540, 0xc42c789500, 0x0, 0x0, 0x0, 0x3, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/consistency_queue.go:117 +0x1bb
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica(0xc4202c6e00, 0x2ff6060, 0xc44087e690, 0xc42c789500, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:749 +0x35d
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1.2(0x2ff6060, 0xc44087e690)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:627 +0xb8
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc420594090, 0x2ff6060, 0xc44087e690, 0xc4268ab4c0, 0x36, 0x0, 0x0, 0xc43d63f520)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:324 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:319 +0x133
```

**Comment by benesch** [comment]
There is absolutely no further information in this cluster. I'm completely baffled. The useful information, if there was any, has been rotated out of the other nodes' log files. And there are no log files besides the one containing the above message.

I have a hand-wavey theory that a `roachprod wipe` could cause this. @tschottdorf do you have any other thoughts?

**Comment by awoods187** [comment]
I think I've just reproduced this on a 21 node cluster `andy-1540472628-tpccbench-nodes-21-cpu-16:4`

```
F181025 13:13:37.891554 21286 storage/replica_consistency.go:152  [n14,consistencyChecker,s14,r6395/2:/Table/55/1/33{0/10/…-4/4/-…}] consistency check failed with 1 inconsistent replicas
goroutine 21286 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc420057200, 0xc4200572c0, 0x3ebba00, 0x1e)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:997 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x47ae200, 0xc400000004, 0x3ebba94, 0x1e, 0x98, 0xc4209ee0a0, 0x7c)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:864 +0x8fe
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2ff6020, 0xc425982000, 0x4, 0x2, 0x2b252c9, 0x36, 0xc442a7e190, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2ff6020, 0xc425982000, 0x1, 0xc400000004, 0x2b252c9, 0x36, 0xc442a7e190, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2ff6020, 0xc425982000, 0x2b252c9, 0x36, 0xc442a7e190, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc431926a80, 0x2ff6020, 0xc425982000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_consistency.go:152 +0xc8f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc431926a80, 0x2ff6020, 0xc425982000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_consistency.go:161 +0xdd5
github.com/cockroachdb/cockroach/pkg/storage.(*consistencyQueue).process(0xc4203ce000, 0x2ff6020, 0xc425982000, 0xc431926a80, 0x0, 0x0, 0x0, 0x2, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/consistency_queue.go:117 +0x1bb
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica(0xc420254e00, 0x2ff6060, 0xc4283fea80, 0xc431926a80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:749 +0x35d
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1.2(0x2ff6060, 0xc4283fea80)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:627 +0xb8
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4201e8f30, 0x2ff6060, 0xc4283fea80, 0xc425a4b8c0, 0x36, 0x0, 0x0, 0xc425a956c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:324 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:319 +0x133
```

**Comment by petermattis** [comment]
[cockroach.andy-1540472628-tpccbench-nodes-21-cpu-16-0004.andrewwoods.2018-10-25T13_13_37Z.003535.log.zip](https://github.com/cockroachdb/cockroach/files/2515076/cockroach.andy-1540472628-tpccbench-nodes-21-cpu-16-0004.andrewwoods.2018-10-25T13_13_37Z.003535.log.zip)

One of the replicas is missing 218672 keys that are present in the other. This could be a manifestation of https://github.com/cockroachdb/cockroach/issues/31752. I'm more suspicious that this is something related to merges, though. (This happened on 2.1-rc1 where merges are still enabled).

Either way, cc @benesch.

**Comment by petermattis** [comment]
I'm not seeing anything merge related in the logs around the time of the consistency failure. The range in question (`r6395`) was split shortly before the consistency failure:

`I181025 13:13:15.978263 20553 storage/replica_command.go:298  [n14,split,s14,r6395/2:/Table/55/1/33{0/10/…-7/6/-…}] initiating a split of this range at key /Table/55/1/334/4/-733/3 [r9022]`
...
`E181025 13:13:35.119503 21286 storage/replica_consistency.go:97  [n14,consistencyChecker,s14,r6395/2:/Table/55/1/33{0/10/…-4/4/-…}] replica (n2,s2):1 is inconsistent: expected checksum c93db4ac93beadb53a059ff3c2d1b1cd22e87d71b8184a86c430fbb125d56abcb4c44f2f11cf484133fe59661b3cc30fd68d42c04017ae9f681801ce3e1d2da5, got 17f88fe4c1254d4da9d20fa4c2a3ff38962914e20a5d31bf6ba21abd502c32191736f3f6751796b3119ae4fbfba1c4cb9f88221892fed247a2c72f319395f6d4`

That could be coincidental, though. 

The range to the left of `6395` (`6394`) currently only has 2 replicas, which is strange. Ditto for the range to the right. Both ranges appear to have a replica on `n14` (which is now dead). Why aren't they being upreplicated? I'm not going to have much time to poke around at this today.

**Comment by awoods187** [comment]
A second node died as well (n15) about 30m after the first
```F181025 13:42:54.703812 96975 storage/replica_consistency.go:152  [n9,consistencyChecker,s9,r9022/3:/Table/55/1/33{4/4/-…-5/10/…}] consistency check failed with 1 inconsistent replicas
goroutine 96975 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc420057200, 0xc4200572c0, 0x3ebba00, 0x1e)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:997 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x47ae200, 0xc400000004, 0x3ebba94, 0x1e, 0x98, 0xc4394f8000, 0x7a)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:864 +0x8fe
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2ff6020, 0xc439470540, 0x4, 0x2, 0x2b252c9, 0x36, 0xc437264000, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2ff6020, 0xc439470540, 0x1, 0xc400000004, 0x2b252c9, 0x36, 0xc437264000, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2ff6020, 0xc439470540, 0x2b252c9, 0x36, 0xc437264000, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc4278a7c00, 0x2ff6020, 0xc439470540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_consistency.go:152 +0xc8f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc4278a7c00, 0x2ff6020, 0xc439470540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_consistency.go:161 +0xdd5
github.com/cockroachdb/cockroach/pkg/storage.(*consistencyQueue).process(0xc4203a2200, 0x2ff6020, 0xc439470540, 0xc4278a7c00, 0x0, 0x0, 0x0, 0x3, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/consistency_queue.go:117 +0x1bb
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica(0xc420254900, 0x2ff6060, 0xc428c7c6c0, 0xc4278a7c00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:749 +0x35d
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1.2(0x2ff6060, 0xc428c7c6c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:627 +0xb8
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc42068a000, 0x2ff6060, 0xc428c7c6c0, 0xc42089c100, 0x36, 0x0, 0x0, 0xc44d9f7540)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:324 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:319 +0x133```

**Comment by benesch** [comment]
> We could've checked the other nodes (on a failed consistency check, all replicas are expected to log something if they disagree with the leader), but it looks like the cluster is gone.

I tried that, but by the time I looked at the cluster all the other nodes had rotated their logs well past the time of the consistency check failure.

Taking a look at Andy's new failure now.

**Comment by awoods187** [comment]
A third node died (n6)
```
I181025 14:40:12.263234 1 util/log/clog.go:1176  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
Error: could not cleanup temporary directories from record file: could not lock temporary directory /mnt/data1/cockroach/cockroach-temp509335024, may still be in use: IO error: While lock file: /mnt/data1/cockroach/cockroach-temp509335024/TEMP_DIR.LOCK: Resource temporarily unavailable
```

**Comment by benesch** [comment]
Yeah, that’s me poking at it. That was one intentional at least.

Are you still running tpccbench? Would you mind killing it?

**Comment by awoods187** [comment]
It's not running--once a node dies it stops itself and denotes a fail
```
--- FAIL: tpccbench/nodes=21/cpu=16 (599.78s)
	test.go:639,cluster.go:1453,tpcc.go:665,tpcc.go:344: unexpected node event: 4: dead
FAIL
```

**Comment by benesch** [comment]
Drat, I left a node down for too long and now it's very hard to tell if things are still inconsistent because all the inconsistent replicas got rebalanced away. I want to try to repro this from scratch. @awoods187 this repro'd when trying to restore the fixture, right? Before we ever even ran TPCC?

**Comment by benesch** [comment]
I'm going to destroy the cluster when I get in (probably 30m or so) unless anyone feels strongly otherwise.

**Comment by awoods187** [comment]
Yeah, that's correct Nikhil. The node crashed very early on in the restore.

**Comment by tschottdorf** [comment]
@benesch has this shown up again?

**Comment by knz** [comment]
@tbg want to reassign? Not sure whether s-0 is still adequate.

**Comment by tbg** [comment]
Closing as inactionable. Thanks for the ping, @knz.
