### ISSUE TITLE
Persistent HTTP health check failure: all SubConns are in TransientFailure

### ISSUE THREAD

**Issue by calder** [cockroachdb/cockroach#31893]
**Describe the problem**

After running a single-node test Cockroach instance in Kubernetes for a few hours and hitting it with a small amount of write traffic, the `/health?ready=1` endpoint began returning:
```json
{
  "error": "all SubConns are in TransientFailure",
  "code": 14
}
```

The SQL interface is still healthy, though the health check failure means Kubernetes removes the node from the service's active endpoints. The pod never recovered.

Log files show the following regularly:

```
W181025 20:02:20.766972 26 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {cockroach-b49b69b7f-6rv2k:26257 0  <nil>}. Err :connection error: desc = "transport: failed to write client preface: io: read/write on closed pipe". Reconnecting...
```

**To Reproduce**

No reliable repro yet.

**Expected behavior**

Health check to remain healthy.

**Additional data / screenshots**

Log sample:

```sh
root@cockroach-b49b69b7f-6rv2k:/cockroach/cockroach-data/logs# tail cockroach.log -f
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.10 GB write, 0.00 MB/s write, 0.08 GB read, 0.00 MB/s read, 297.4 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

estimated_pending_compaction_bytes: 0 B
I181025 20:22:53.153407 252 server/status/runtime.go:219  [n1] runtime stats: 401 MiB RSS, 159 goroutines, 188 MiB/36 MiB/253 MiB GO alloc/idle/total, 122 MiB/176 MiB CGO alloc/total, 64.29cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (0x)
tail: unrecognized file system type 0x794c7630 for 'cockroach.log'. please report this to bug-coreutils@gnu.org. reverting to polling
W181025 20:22:54.638100 26 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {cockroach-b49b69b7f-6rv2k:26257 0  <nil>}. Err :connection error: desc = "transport: failed to write client preface: io: read/write on closed pipe". Reconnecting...
I181025 20:23:03.140917 252 server/status/runtime.go:219  [n1] runtime stats: 401 MiB RSS, 158 goroutines, 193 MiB/32 MiB/253 MiB GO alloc/idle/total, 122 MiB/176 MiB CGO alloc/total, 61.08cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (0x)
I181025 20:23:13.136469 252 server/status/runtime.go:219  [n1] runtime stats: 400 MiB RSS, 158 goroutines, 200 MiB/25 MiB/252 MiB GO alloc/idle/total, 122 MiB/176 MiB CGO alloc/total, 55.73cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (0x)
I181025 20:23:23.139065 249 gossip/gossip.go:488  [n1] gossip status (ok, 1 node)
gossip client (0/3 cur/max conns)
gossip server (0/3 cur/max conns, infos 0/0 sent/received, bytes 0B/0B sent/received)
I181025 20:23:23.156404 252 server/status/runtime.go:219  [n1] runtime stats: 400 MiB RSS, 160 goroutines, 207 MiB/18 MiB/252 MiB GO alloc/idle/total, 122 MiB/176 MiB CGO alloc/total, 63.38cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (0x)
```

Kubernetes pod YAML:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: .../32
  creationTimestamp: 2018-10-24T19:45:21Z
  generateName: cockroach-b49b69b7f-
  labels:
    app: cockroach
    pod-template-hash: "605625639"
  name: cockroach-b49b69b7f-6rv2k
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: cockroach-b49b69b7f
    uid: 5783500b-d7c5-11e8-9964-005056b57c89
  resourceVersion: "42864435"
  selfLink: /api/v1/namespaces/default/pods/cockroach-b49b69b7f-6rv2k
  uid: 578530bb-d7c5-11e8-9964-005056b57c89
spec:
  containers:
  - args:
    - start
    - --insecure
    - --http-port=80
    image: cockroachdb/cockroach
    imagePullPolicy: Always
    name: cockroach
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 26257
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health?ready=1
        port: 80
        scheme: HTTP
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        ephemeral-storage: 20Gi
      requests:
        ephemeral-storage: 20Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-s7rvh
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: ...
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-s7rvh
    secret:
      defaultMode: 420
      secretName: default-token-s7rvh
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-10-24T19:45:21Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-10-25T12:13:36Z
    message: 'containers with unready status: [cockroach]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-10-24T19:45:21Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: cockroachdb/cockroach
    lastState: {}
    name: cockroach
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: 2018-10-24T19:45:22Z
  hostIP: ...
  phase: Running
  podIP: ...
  qosClass: BestEffort
  startTime: 2018-10-24T19:45:21Z
```

**Environment:**

* Cockroach:
```sh
root@cockroach-b49b69b7f-6rv2k:/cockroach/cockroach-data/logs# /cockroach/cockroach version
Build Tag:    v2.0.5
Build Time:   2018/08/13 17:59:42
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10
C Compiler:   gcc 6.3.0
Build SHA-1:  3f2f0f5eea9b9d552e471eba8c37504a0595342f
Build Type:   release
```
* Host:
  * Kubernetes: 1.10.3
  * OS: Ubuntu 16.04.4
  * Kernel: 4.4.0-109-generic
  * Docker: 18.3.1

**Comment by a-robinson** [comment]
Deploying cockroach in a `ReplicaSet` (and deviating so far from the provided https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/cockroachdb-statefulset.yaml config) is a very dangerous game you're playing :)

Also, using ephemeral storage is a deadly game if you care at all about cockroach maintaining your data across pod or node deaths.

> After running a single-node test Cockroach instance in Kubernetes for a few hours and hitting it with a small amount of write traffic, the `/health?ready=1` endpoint began returning:

It looks like the pod got killed and recreated at some point, since the address it's trying to connect to is different from the current pod's name. Can you check out the history of pods that have run in your cluster? Depending on your version of kubectl, `kubectl get pods --show-all` should do the trick.

Also, the full log file (from all cockroach pods that have existed, if possible) would be helpful to determine exactly what's going on.

**Comment by a-robinson** [comment]
And thank you for providing the pod config! It's very helpful.

**Comment by calder** [comment]
Thanks @a-robinson! I'll try switching to the YAML you linked and see if the issue crops up again.

`kubectl get pods --show-all` returns
```sh
Flag --show-all has been deprecated, will be removed in an upcoming release
```

**Comment by calder** [comment]
@a-robinson: Thanks! One last question: What did you mean by this?
> It looks like the pod got killed and recreated at some point, since the address it's trying to connect to is different from the current pod's name.

The pod has
```
  name: cockroach-b49b69b7f-6rv2k
```
and the Cockroach log shows:
```
failed to connect to {cockroach-b49b69b7f-6rv2k:26257 0  <nil>}
```

**Comment by calder** [comment]
Re-opening since this seems like a problem beyond this wacky configuration. Looking back in the log, there are stale heartbeats and liveness failures the node never recovers from. The proximate cause could easily have been temporary CPU exhaustion, but I wouldn't expect this to permanently disable the node.

```
W181024 19:45:23.132763 13 sql/jobs/registry.go:286  [n1] unable to get node liveness: node not in the liveness table
...
W181024 19:45:46.724154 293 storage/node_liveness.go:504  [n1,hb] slow heartbeat took 1.1s
...
W181025 12:13:42.820202 293 storage/node_liveness.go:504  [n1,hb] slow heartbeat took 5.6s
W181025 12:13:42.820258 293 storage/node_liveness.go:441  [n1,hb] failed node liveness heartbeat: context deadline exceeded
W181025 12:13:39.937094 186 storage/store.go:3926  [n1,s1] handle raft ready: 2.2s [processed=1]
W181025 12:13:46.521971 206 storage/engine/rocksdb.go:1805  batch [4/320/0] commit took 2.278310769s (>500ms):
goroutine 206 [running]:
runtime/debug.Stack(0x2a862d2b, 0xed363aa76, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc42084cd80, 0x0, 0x1, 0xc428cae550)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1806 +0x128
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc42084cd80, 0xed363aa00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1724 +0x7c0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyRaftCommand(0xc428ebbc00, 0x2784000, 0xc4292ac940, 0xc42a5c9fe8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5102 +0x4d5
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc428ebbc00, 0x2784000, 0xc4292ac940, 0xc42a5c9fe8, 0x8, 0x6, 0x5599, 0x100000001, 0x1, 0x2, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4807 +0x5a7
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc428ebbc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3706 +0x12c8
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc428ebbc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3404 +0xdb
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4200a5c00, 0x27840c0, 0xc42084a1b0, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3915 +0xda
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204e8630, 0x27840c0, 0xc42084a1b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:215 +0x259
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x27840c0, 0xc42084a1b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420289d20, 0xc4204e8240, 0xc420289d10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad
I181025 12:13:46.522283 252 server/status/runtime.go:219  [n1] runtime stats: 340 MiB RSS, 174 goroutines, 197 MiB/26 MiB/250 MiB GO alloc/idle/total, 81 MiB/121 MiB CGO alloc/total, 27.51cgo/sec, 0.00/0.16 %(u/s)time, 0.00 %gc (0x)
W181025 12:13:47.339007 293 storage/node_liveness.go:504  [n1,hb] slow heartbeat took 4.5s
W181025 12:13:47.339069 293 storage/node_liveness.go:441  [n1,hb] failed node liveness heartbeat: context deadline exceeded
W181025 12:13:52.052460 293 storage/node_liveness.go:504  [n1,hb] slow heartbeat took 4.6s
W181025 12:13:54.155841 293 storage/node_liveness.go:441  [n1,hb] failed node liveness heartbeat: context deadline exceeded
W181025 12:13:53.375068 206 storage/store.go:3926  [n1,s1] handle raft ready: 10.9s [processed=1]
I181025 12:13:55.223032 252 server/status/runtime.go:219  [n1] runtime stats: 340 MiB RSS, 174 goroutines, 198 MiB/26 MiB/250 MiB GO alloc/idle/total, 81 MiB/121 MiB CGO alloc/total, 24.49cgo/sec, 0.00/0.05 %(u/s)time, 0.00 %gc (0x)
I181025 12:13:55.617133 252 server/status/runtime.go:219  [n1] runtime stats: 340 MiB RSS, 175 goroutines, 198 MiB/26 MiB/250 MiB GO alloc/idle/total, 81 MiB/121 MiB CGO alloc/total, 12.03cgo/sec, 0.00/0.12 %(u/s)time, 0.00 %gc (0x)
W181025 12:13:56.521600 235 storage/engine/rocksdb.go:1805  batch [2/311/0] commit took 887.862749ms (>500ms):
goroutine 235 [running]:
runtime/debug.Stack(0x256053de, 0xed363aa83, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc430d81440, 0x0, 0x1, 0xc4202cca40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1806 +0x128
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc430d81440, 0xed363aa01, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1724 +0x7c0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc428ebbc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3623 +0x5ae
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc428ebbc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3404 +0xdb
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4200a5c00, 0x27840c0, 0xc42084a870, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3915 +0xda
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204e8630, 0x27840c0, 0xc42084a870)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:215 +0x259
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x27840c0, 0xc42084a870)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202f4380, 0xc4204e8240, 0xc4202f4360)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad
W181025 12:14:11.855371 26 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {cockroach-b49b69b7f-6rv2k:26257 0  <nil>}. Err :connection error: desc = "transport: failed to write client preface: io: read/write on closed pipe". Reconnecting...
W181025 12:14:11.908651 238528 vendor/google.golang.org/grpc/server.go:863  grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
W181025 12:14:12.010711 451 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {cockroach-b49b69b7f-6rv2k:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W181025 12:14:12.882844 26 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {cockroach-b49b69b7f-6rv2k:26257 0  <nil>}. Err :connection error: desc = "transport: failed to write client preface: io: read/write on closed pipe". Reconnecting...
W181025 12:14:15.326033 294 sql/jobs/registry.go:300  canceling all jobs due to liveness failure
```

Unrelated but curious: Does the gRPC server share a port with the SQL server? How does this work? Asking because this log message:
```
W181025 20:02:20.766972 26 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {cockroach-b49b69b7f-6rv2k:26257 0  <nil>}. Err :connection error: desc = "transport: failed to write client preface: io: read/write on closed pipe". Reconnecting...
```
is a gRPC reconnect error [here](https://github.com/cockroachdb/vendored/blob/f7cc32aa57ffc73df8aff68d1fbdafba802a94d8/google.golang.org/grpc/clientconn.go#L1282-L1295). But the attempted connection is on the SQL port (26257).

**Comment by knz** [comment]
> Unrelated but curious: Does the gRPC server share a port with the SQL server? How does this work?

Yes it does. This works by distinguishing the protocol on the first packet received from the other side. There is a multiplexer entry point ("cmux") which delegates the connection either to the SQL server or to the inter-node communication depending on the sort of data received.

**Comment by knz** [comment]
@calder your issue may be indeed deeper than the health check. We need to determine more generally the health of your cluster.

@tim-o @roncrdb can you accompany this investigation until we have a better picture of what's going on?

**Comment by jamiesonbecker** [comment]
Also having this issue on one node of a bare-metal (no k8s) install. HA Proxy reports that the node is down and the web UI tries to come up but the stats are all throwing 503 - "all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: io: read/write on closed pipe". CPU is 0.2 user, RAM is 309MB used out of 32GB, IO is around 0 to 3KB/s. However, even though this cluster overview won't load, the other two nodes show this node as healthy.

There is literally no data on this server at all except for the test database created during the howto. Does the debug zip contain certs or anything that needs to be sanitized?

**Comment by pkavajin** [comment]
Ran into the same issue with cockroach 2.0.6.
At the time the error happened a batch job processed and slightly increased the load.
(Running on docker without k8s, no container restart happened)

Affected node reported:
```
vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {roach-XX:26258 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
vendor/google.golang.org/grpc/clientconn.go:1277  grpc: addrConn.transportMonitor exits due to: context canceled
server/status/runtime.go:219  [n3] runtime stats: 8.1 GiB RSS, 266 goroutines, 462 MiB/703 MiB/1.2 GiB GO alloc/idle/total, 6.3 GiB/7.8 GiB CGO alloc/total, 116.75cgo/sec, 0.04/0.84 %(u/s)time, 0.00 %gc (3x)
vendor/google.golang.org/grpc/clientconn.go:1277  grpc: addrConn.transportMonitor exits due to: connection error: desc = "transport: authentication handshake failed: io: read/write on closed pipe"
```

At the same time a different node reported the following:
```
storage/node_liveness.go:716  [n4,hb] retrying liveness update after storage.errRetryLiveness: result is ambiguous (error=context deadline exceeded [exhausted])
storage/node_liveness.go:504  [n4,hb] slow heartbeat took 4.5s
storage/node_liveness.go:441  [n4,hb] failed node liveness heartbeat: context deadline exceeded
```

So, it looks like it lost connection for a few seconds.
Our product also reported some connectivity issues to the database for a few seconds, after that it could connect again and it seems to be working.

Healthcheck for the affected node still says: 
```
{
  "error": "all SubConns are in TransientFailure",
  "code": 14
}
```

even tho the dashboard says the node is healthy. All other nodes also report a "healthy" healthcheck.

**Comment by kswathihs** [comment]
We are facing similar issue with cockroach v2.1.4  ,  
```curl http://10.50.86.56:8080/health?ready=1
{
  "error": "all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: io: read/write on closed pipe\"",
  "code": 14
}```
for now, affected node restart is fixing the issue.

But looking for a solution from cockroachdb team.

**Comment by igremmerlb** [comment]
We are experiencing a similar issue in 19.1.4.  I started a 3 node cluster across 3 datacenters (10-30ms apart).  Once started there is no load on the cluster.  After a few hours the health check starts failing.  I see the following from the health endpoint.

{
error: "all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: io: read/write on closed pipe"",
message: "all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: io: read/write on closed pipe"",
code: 14,
details: [ ]
}

**Comment by heidawei** [comment]
we have a similar issue in 19.1.4, I started one node cluster, then I try to show the jobs, and I get an error:
```
{
  "error": "all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: failed to write client preface: io: read/write on closed pipe\"",
  "message": "all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: failed to write client preface: io: read/write on closed pipe\"",
  "code": 14,
  "details": [
  ]
}
```
I retry many times , but the error continue, and the cluster can service for write and read for SQL client

**Comment by knz** [comment]
Folding into #42828. We have a patch in the works.
