### ISSUE TITLE
sequence numbers + early-cached split intent = infinite loop

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3206]
Motivation for this issue is a test failure introduced by a short-lived [bug](https://github.com/cockroachdb/cockroach/pull/3208) which should have been harmless but reliably triggered an infinite loop in `TestTree` (original log below).

What happened is:

* a Split happens and intents are written in the range descriptor span.
* the Split txn tries to do something else, and a `RangeLookup` happens. With the bug referenced above, the intent is returned without being asked for (but in rarer circumstances, it might actually have been requested).
* DistSender now thinks of the (as of yet unsplit Range) as two ranges and splits requests accordingly
* One of the follow-up requests in the Split txn now "spans" ranges, but the sequence number isn't updated in between those, so a retry error occurs.

Since the situation after the last step is the same, this goes into a busy loop.

We'll obviously have to increment sequence numbers between those (right now it happens one level higher, in `chunkingSender`). There are also some outstanding considerations about different sequence counter increments racing (which could in the worst case ruin replay protection) which are worth mentioning in this context.

--

The following test appears to have failed:

[#9540](https://circleci.com/gh/cockroachdb/cockroach/9540):

```
W1123 18:51:03.956516 922 kv/dist_sender.go:563  failed to invoke ConditionalPut [/Local/Range/RangeDescriptor/"l",/Min), Noop [/Min,/Min), Noop [/Min,/Min), Noop [/Min,/Min): retry txn "storage/replica_command.go:1319 (*Replica).AdminSplit" id=ab81e4a1 key=/Local/Range/RangeDescriptor/"l" rw=true pri=99.99955422 iso=SERIALIZABLE stat=PENDING epo=44716 ts=0.000000000,1223 orig=0.000000000,1223 max=0.000000000,1223
I1123 18:51:03.956934 922 client/db.go:483  failed batch: retry txn "storage/replica_command.go:1319 (*Replica).AdminSplit" id=ab81e4a1 key=/Local/Range/RangeDescriptor/"l" rw=true pri=99.99955422 iso=SERIALIZABLE stat=PENDING epo=44716 ts=0.000000000,1223 orig=0.000000000,1223 max=0.000000000,1223
I1123 18:51:03.961054 922 storage/replica.go:1146  found sequence cache entry for ab81e4a1@134175
W1123 18:51:03.962061 922 kv/dist_sender.go:563  failed to invoke ConditionalPut [/Local/Range/RangeDescriptor/"l",/Min), Noop [/Min,/Min), Noop [/Min,/Min), Noop [/Min,/Min): retry txn "storage/replica_command.go:1319 (*Replica).AdminSplit" id=ab81e4a1 key=/Local/Range/RangeDescriptor/"l" rw=true pri=99.99955422 iso=SERIALIZABLE stat=PENDING epo=44717 ts=0.000000000,1223 orig=0.000000000,1223 max=0.000000000,1223
I1123 18:51:03.962474 922 client/db.go:483  failed batch: retry txn "storage/replica_command.go:1319 (*Replica).AdminSplit" id=ab81e4a1 key=/Local/Range/RangeDescriptor/"l" rw=true pri=99.99955422 iso=SERIALIZABLE stat=PENDING epo=44717 ts=0.000000000,1223 orig=0.000000000,1223 max=0.000000000,1223
panic: test timed out after 5m0s

goroutine 7185 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x19fdcb0, 0x2055e20, 0xd8, 0xd8, 0x1687201)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:603 +0x1d1f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8203d67e0, 0xc8202d4ea0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	300.103s
=== RUN   TestBatchBasics
I1123 18:46:15.633003 983 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1123 18:46:15.636151 983 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1123 18:46:15.642074 983 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
looks like an infinite sequence cache retry loop.

**Comment by kkaneda** [comment]
Ok to close this?

**Comment by tschottdorf** [comment]
Yep!
