### ISSUE TITLE
storage: "Invalid lease" on r1 and r2

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#32727]
**Describe the problem**

I have a 3-node cluster running 2.1.1 that reports "invalid leases" for r1 and r2 on the problem range page. 

![image](https://user-images.githubusercontent.com/160562/49240438-250c1d00-f3d3-11e8-9549-2b2019b37d82.png)

![image](https://user-images.githubusercontent.com/160562/49240521-58e74280-f3d3-11e8-9019-441f5a9ed123.png)

In both cases, node 2 has not yet been updated with the current lease information. Node 2 believes itself to still be the raft leader of r1. Despite the error message of "invalid lease", the lease appears to be valid on nodes 1 and 3, but n2 remembers the old invalid state. 

**To Reproduce**

Unclear whether it is reproducible. The cluster was idle except for a periodic cron job running backups when the problem started, and it contains little data. The problem came to our attention because one of these backups hung for several hours (and is still hanging as I write this). The backup is being executed on node 2. 

**Environment:**
 - CockroachDB version 2.1.1
 - Server OS: ubuntu (running on aws)

I can provide full access to this cluster.

**Comment by tbg** [comment]
I'd be happy to take a look. Can you DM details? Won't get to it until
Friday though.

**Comment by tbg** [comment]
Looked at goroutine dump on n2 because logspy claimed an interception was already in progress. Found these beauties:

```
goroutine 11 [syscall, 556 minutes]:
syscall.Syscall(0x1, 0x6, 0xc42a636000, 0x100, 0xc4200ae300, 0xc427e69640, 0xc42010fd58)
    /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.write(0x6, 0xc42a636000, 0x100, 0x40000, 0xc427e69601, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1022 +0x5f
syscall.Write(0x6, 0xc42a636000, 0x100, 0x40000, 0x0, 0x0, 0x0)
    /usr/local/go/src/syscall/syscall_unix.go:181 +0x49
internal/poll.(*FD).Write(0xc427e636d0, 0xc42a636000, 0x100, 0x40000, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:256 +0x142
os.(*File).write(0xc4202b9908, 0xc42a636000, 0x100, 0x40000, 0x95023f46, 0xc420061d00, 0xc420060f00)
    /usr/local/go/src/os/file_unix.go:243 +0x4e
os.(*File).Write(0xc4202b9908, 0xc42a636000, 0x100, 0x40000, 0xc4200ae388, 0xc4297e6478, 0xc4200ae438)
    /usr/local/go/src/os/file.go:144 +0x6f
bufio.(*Writer).Flush(0xc4206fe480, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:573 +0x7e
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushAndSync(0x47d5e80, 0xc42010ff00)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1246 +0x43
github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1210 +0x1c3
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:619 +0x126
```

```
goroutine 106 [syscall, 556 minutes]:
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBSyncWAL(0x7feba3c56eb0, 0x0, 0x0)
    _cgo_gotypes.go:1112 +0x49
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).syncLoop.func1(0x7feba3c56eb0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:679 +0x5b
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).syncLoop(0xc420912480)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:679 +0x273
created by github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:643 +0x418
```

```
goroutine 238 [semacquire, 556 minutes]:
sync.runtime_Semacquire(0xc4210b2234)
    /usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4210b2228)
    /usr/local/go/src/sync/waitgroup.go:129 +0x72
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc4210b2000, 0xed391ba01, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1873 +0x582
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc42c488a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4312 +0x5ae
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x3012440, 0xc42b831770, 0xc42c488a80, 0x3012440)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3852 +0x109
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc420c57080, 0x3012440, 0xc42b831770, 0xc4297701a0, 0xc420c6fed0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3502 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc420c57080, 0x3012440, 0xc420d7a8d0, 0xd7)
```

Looks like disk I/O on this node is a goner.

**Comment by tbg** [comment]
`dd if=/dev/zero of=/mnt/data1/DELETEME bs=10M count=1` never returns on that node. (It returns on the others). This isn't a CRDB bug.

**Comment by bdarnell** [comment]
This would have been caught by the new disk stall detector.
