### ISSUE TITLE
tests: timeout in BenchmarkSelLTInt64Int64ConstOp (sql/exec)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#32781]
Found in CI of #32779
The `bench` CI test fails: https://teamcity.cockroachdb.com/viewLog.html?buildId=1037454&buildTypeId=Cockroach_UnitTests_Bench&tab=buildResultsDiv

```
[12:51:28] :		 [Run Benchmarks] BenchmarkHashJoiner/rows=67108864-8                             	       1	8513042598 ns/op	 504.52 MB/s
[12:51:28] :		 [Run Benchmarks] BenchmarkProjPlusInt64Int64ConstOp-8                            	       1	     96805 ns/op	  84.62 MB/s
[12:51:28] :		 [Run Benchmarks] BenchmarkProjPlusInt64Int64Op-8                                 	       1	     73523 ns/op	 222.84 MB/s
[12:57:16] :		 [Run Benchmarks] SIGQUIT: quit
[12:57:16] :		 [Run Benchmarks] PC=0x45d4f1 m=0 sigcode=0
[12:57:16] :		 [Run Benchmarks] 
[12:57:16] :		 [Run Benchmarks] goroutine 0 [idle]:
[12:57:16] :		 [Run Benchmarks] runtime.futex(0x1cd5268, 0x0, 0x0, 0x0, 0x7fb300000000, 0x10, 0x0, 0x0, 0x7ffe42251998, 0x410fbb, ...)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/sys_linux_amd64.s:530 +0x21
[12:57:16] :		 [Run Benchmarks] runtime.futexsleep(0x1cd5268, 0x100000000, 0xffffffffffffffff)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/os_linux.go:45 +0x4b
[12:57:16] :		 [Run Benchmarks] runtime.notesleep(0x1cd5268)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/lock_futex.go:151 +0x9b
[12:57:16] :		 [Run Benchmarks] runtime.stopm()
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/proc.go:1952 +0xe5
[12:57:16] :		 [Run Benchmarks] runtime.findrunnable(0xc42005a500, 0x0)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/proc.go:2415 +0x50c
[12:57:16] :		 [Run Benchmarks] runtime.schedule()
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/proc.go:2541 +0x13b
[12:57:16] :		 [Run Benchmarks] runtime.park_m(0xc4200a9800)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/proc.go:2604 +0xb6
[12:57:16] :		 [Run Benchmarks] runtime.mcall(0xe6a8d0)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/asm_amd64.s:351 +0x5b
[12:57:16] :		 [Run Benchmarks] 
[12:57:16] :		 [Run Benchmarks] goroutine 1 [chan receive, 5 minutes]:
[12:57:16] :		 [Run Benchmarks] testing.(*B).run1(0xc4204a9980, 0xc4204a9980)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/testing/benchmark.go:216 +0xa1
[12:57:16] :		 [Run Benchmarks] testing.(*B).Run(0xc420488a80, 0x10f48d4, 0x1f, 0x11746d0, 0x4e6f00)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/testing/benchmark.go:511 +0x211
[12:57:16] :		 [Run Benchmarks] testing.runBenchmarks.func1(0xc420488a80)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/testing/benchmark.go:416 +0x60
[12:57:16] :		 [Run Benchmarks] testing.(*B).runN(0xc420488a80, 0x1)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/testing/benchmark.go:141 +0xb2
[12:57:16] :		 [Run Benchmarks] testing.runBenchmarks(0x110678b, 0x2d, 0xc420424540, 0x1a90d40, 0x7, 0x7, 0xc4200c6810)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/testing/benchmark.go:422 +0x46d
[12:57:16] :		 [Run Benchmarks] testing.(*M).Run(0xc420470080, 0x0)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/testing/testing.go:984 +0x366
[12:57:16] :		 [Run Benchmarks] github.com/cockroachdb/cockroach/pkg/sql/exec.TestMain(0xc420470080)
[12:57:16] :		 [Run Benchmarks] 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/main_test.go:26 +0x30
[12:57:16] :		 [Run Benchmarks] main.main()
[12:57:16] :		 [Run Benchmarks] 	_testmain.go:94 +0x151
[12:57:16] :		 [Run Benchmarks] 
[12:57:16] :		 [Run Benchmarks] goroutine 20 [syscall, 5 minutes]:
[12:57:16] :		 [Run Benchmarks] os/signal.signal_recv(0x0)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
[12:57:16] :		 [Run Benchmarks] os/signal.loop()
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
[12:57:16] :		 [Run Benchmarks] created by os/signal.init.0
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
[12:57:16] :		 [Run Benchmarks] 
[12:57:16] :		 [Run Benchmarks] goroutine 7 [chan receive]:
[12:57:16] :		 [Run Benchmarks] github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
[12:57:16] :		 [Run Benchmarks] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1203 +0xf1
[12:57:16] :		 [Run Benchmarks] created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
[12:57:16] :		 [Run Benchmarks] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:619 +0x126
[12:57:16] :		 [Run Benchmarks] 
[12:57:16] :		 [Run Benchmarks] goroutine 8 [chan receive, 5 minutes]:
[12:57:16] :		 [Run Benchmarks] github.com/cockroachdb/cockroach/pkg/util/log.signalFlusher()
[12:57:16] :		 [Run Benchmarks] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:626 +0xab
[12:57:16] :		 [Run Benchmarks] created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
[12:57:16] :		 [Run Benchmarks] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:620 +0x13e
[12:57:16] :		 [Run Benchmarks] 
[12:57:16] :		 [Run Benchmarks] goroutine 24 [select, 5 minutes, locked to thread]:
[12:57:16] :		 [Run Benchmarks] runtime.gopark(0x1176b18, 0x0, 0x10db61d, 0x6, 0x18, 0x1)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/proc.go:291 +0x11a
[12:57:16] :		 [Run Benchmarks] runtime.selectgo(0xc420069750, 0xc4201c6180)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/select.go:392 +0xe50
[12:57:16] :		 [Run Benchmarks] runtime.ensureSigM.func1()
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
[12:57:16] :		 [Run Benchmarks] runtime.goexit()
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1
[12:57:16] :		 [Run Benchmarks] 
[12:57:16] :		 [Run Benchmarks] goroutine 55 [runnable]:
[12:57:16] :		 [Run Benchmarks] github.com/cockroachdb/cockroach/pkg/sql/exec.(*repeatableBatchSource).Next(0xc420272480, 0xc420449000, 0x400)
[12:57:16] :		 [Run Benchmarks] 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/utils_test.go:295 +0xb3
[12:57:16] :		 [Run Benchmarks] github.com/cockroachdb/cockroach/pkg/sql/exec.(*selLTInt64Int64ConstOp).Next(0xc42007ff40, 0xc420272480, 0x0)
[12:57:16] :		 [Run Benchmarks] 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/selection_ops.eg.go:3900 +0x83
[12:57:16] :		 [Run Benchmarks] github.com/cockroachdb/cockroach/pkg/sql/exec.BenchmarkSelLTInt64Int64ConstOp(0xc4204a9980)
[12:57:16] :		 [Run Benchmarks] 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/selection_ops_test.go:118 +0x1e1
[12:57:16] :		 [Run Benchmarks] testing.(*B).runN(0xc4204a9980, 0x1)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/testing/benchmark.go:141 +0xb2
[12:57:16] :		 [Run Benchmarks] testing.(*B).run1.func1(0xc4204a9980)
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/testing/benchmark.go:214 +0x5a
[12:57:16] :		 [Run Benchmarks] created by testing.(*B).run1
[12:57:16] :		 [Run Benchmarks] 	/usr/local/go/src/testing/benchmark.go:207 +0x80
[12:57:16] :		 [Run Benchmarks] 
[12:57:16] :		 [Run Benchmarks] rax    0xca
[12:57:16] :		 [Run Benchmarks] rbx    0x1cd5120
[12:57:16] :		 [Run Benchmarks] rcx    0x45d4f3
[12:57:16] :		 [Run Benchmarks] rdx    0x0
[12:57:16] :		 [Run Benchmarks] rdi    0x1cd5268
[12:57:16] :		 [Run Benchmarks] rsi    0x0
[12:57:16] :		 [Run Benchmarks] rbp    0x7ffe42251960
[12:57:16] :		 [Run Benchmarks] rsp    0x7ffe42251918
[12:57:16] :		 [Run Benchmarks] r8     0x0
[12:57:16] :		 [Run Benchmarks] r9     0x0
[12:57:16] :		 [Run Benchmarks] r10    0x0
[12:57:16] :		 [Run Benchmarks] r11    0x286
[12:57:16] :		 [Run Benchmarks] r12    0x4ccdc5
[12:57:16] :		 [Run Benchmarks] r13    0x0
[12:57:16] :		 [Run Benchmarks] r14    0x0
[12:57:16] :		 [Run Benchmarks] r15    0x0
[12:57:16] :		 [Run Benchmarks] rip    0x45d4f1
[12:57:16] :		 [Run Benchmarks] rflags 0x286
[12:57:16] :		 [Run Benchmarks] cs     0x33
[12:57:16] :		 [Run Benchmarks] fs     0x0
[12:57:16] :		 [Run Benchmarks] gs     0x0
[12:57:16] :		 [Run Benchmarks] *** Test killed with quit: ran too long (6m0s).
```

**Comment by knz** [comment]
cc @jordanlewis for triage

**Comment by jordanlewis** [comment]
I forgot that we run benchmarks on unit tests.

**Comment by jordanlewis** [comment]
Maybe it was just a fluke, we haven't seen it since... I'll deal with this if/when it comes up again.
