### ISSUE TITLE
DOTNET 2.1 with CockroachDB 2.1.1 using Npgsql 4.0.3

### ISSUE THREAD

**Issue by alexevon** [cockroachdb/cockroach#32910]
Just installed cockroachDB 2.1.1 and running .NET core 2.1 with the example code on:

https://www.cockroachlabs.com/docs/stable/build-a-csharp-app-with-cockroachdb.html

Cockroach itself appears fine as we imported a test mariaDB database into with ZERO issues (great job btw!), but trying out the C# code from above results in:

cockroachdb-test-app# dotnet run
Initial balances:

Unhandled Exception: System.InvalidCastException: Can't cast database type bigint to String
at Npgsql.NpgsqlDefaultDataReader.GetFieldValue[T](Int32 column) in C:\projects\npgsql\src\Npgsql\NpgsqlDefaultDataReader.cs:line 154
at Cockroach.MainClass.Simple(String connString) in /root/cockroachdb-test-app/Program.cs:line 45
at Cockroach.MainClass.Main(String[] args) in /root/cockroachdb-test-app/Program.cs:line 16

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RootNamespace>cockroachdb_test_app</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="4.0.3" />
  </ItemGroup>

</Project>

Thank you!

**Comment by alexevon** [comment]
Just as a followup, did some research.. it appears this line:

Console.Write("\taccount {0}: {1}\n", reader.GetString(0), reader.GetString(1));

was causing issues...  however changing the line to this worked:

Console.Write("\taccount {0}: {1}\n", reader.GetValue(0), reader.GetValue(1));

**Comment by alexevon** [comment]
Kena-

My test is just from doing research as I am not a C# developer, so my input
is purely from trials.  However, in my use-case this did work.
