### ISSUE TITLE
sql: panic while executing, caused by invalid datum type given: string, expected int

### ISSUE THREAD

**Issue by dendon** [cockroachdb/cockroach#33012]
**Describe the problem**

```
E181211 11:39:09.712470 27515 sql/conn_executor.go:632  [n3,client=127.0.0.1:38338,user=root] a SQL panic has occurred while executing "INSERT INTO _._._(_, _, _, _) VALUES ($1, $2, __more2__) RETURNING _": invalid datum type given: string, expected int
E181211 11:39:09.712619 27515 util/log/crash_reporting.go:203  [n3,client=127.0.0.1:38338,user=root] a panic has occurred!
panic: invalid datum type given: string, expected int [recovered]
	panic: panic while executing 1 statements: INSERT INTO _._._(_, _, _, _) VALUES ($1, $2, __more2__) RETURNING _; caused by invalid datum type given: string, expected int

goroutine 27515 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc4305c6000, 0x3012380, 0xc4300ef3c0, 0x266cea0, 0xc42559cb60)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:646 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc4305c6000, 0x3012380, 0xc4300ef3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
panic(0x266cea0, 0xc42559cb60)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:161 +0x281
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc431e6ca00, 0xc4305c6418, 0x3005a40, 0xc42850a090, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:213 +0x455
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x3012440, 0xc4284fa180, 0x301bbc0, 0xc431e6ca00, 0x2fef840, 0xc42f267c00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:170 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc431e6ca00, 0x3012440, 0xc4284fa180, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:731 +0x98
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartSync(0xc42d83f180, 0x3012440, 0xc4284fa180, 0x2c12298, 0xc42e8361c0, 0x2fef500)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:602 +0x191
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc420c42000, 0xc425afad80, 0xc432413560, 0xc4360268d8, 0xc42c5b7180, 0xc4305c64b0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:253 +0x879
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc420c42000, 0x3012440, 0xc4285c5080, 0xc4305c64b0, 0xc425afad80, 0xc432413560, 0x3005800, 0xc42a93f1e0, 0xc42c5b7180)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:746 +0x24c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc4305c6000, 0x3012440, 0xc4285c5080, 0xc4305c6418, 0x3, 0x7fd1c2499500, 0xc432413dd0, 0xc4285c4500, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:982 +0x2d8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc4305c6000, 0x3012440, 0xc4285c5080, 0x3015480, 0xc42bbcaa50, 0xc4285c4540, 0x1, 0x1, 0xc420da4300, 0x5b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:824 +0xa8a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc4305c6000, 0x3012440, 0xc4285c5080, 0x3015480, 0xc42bbcaa50, 0xc4285c4540, 0x1, 0x1, 0xc420da4300, 0x5b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xb3b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc4305c6000, 0x3012440, 0xc4285c5080, 0x3015480, 0xc42bbcaa50, 0xc4285c4540, 0x1, 0x1, 0xc420da4300, 0x5b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x341
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc4305c6000, 0x3012380, 0xc4300ef3c0, 0xc4205e0798, 0x5400, 0x15000, 0xc4205e0830, 0xc425e45480, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1169 +0x1400
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4208f70e0, 0x3012380, 0xc4300ef3c0, 0xc4305c6000, 0x5400, 0x15000, 0xc4205e0830, 0xc425e45480, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc4208f70e0, 0x3012380, 0xc4300ef3c0, 0xc4305c6000, 0x5400, 0x15000, 0xc4205e0830, 0xc425e45480, 0xc425e45490, 0xc435705200)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:309 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:308 +0x107c
```

**To Reproduce**

I added a new column and while the job was running, some, either still running inserts, or incoming inserts caused this panic.

**Environment:**
CockroachDB CCL v2.1.1 (x86_64-unknown-linux-gnu, built 2018/11/19 18:24:21, go1.10.3)

**Additional context**
The node crashed and I had to truncate the table.

**Comment by vivekmenezes** [comment]
The fix is in v2.1.3 . Thanks for reporting this issue!
