### ISSUE TITLE
TestReplicateRogueRemovedNode: (*raftLog).term: requested entry at index unavailable 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3371]
The following test appears to have failed:

[#9994](https://circleci.com/gh/cockroachdb/cockroach/9994):

```
I1209 19:38:40.675783 965 storage/replica_command.go:451  auto-gc'ed f95b33c8 (3 intents)
I1209 19:38:40.685974 965 storage/replica_gc_queue.go:126  destroying local data from range 1
I1209 19:38:40.686249 965 multiraft/multiraft.go:863  node 2: got message for unknown group 1; creating it
I1209 19:38:40.686922 965 raft/raft.go:441  [group 1] 2 became follower at term 6
I1209 19:38:40.687189 965 raft/raft.go:234  [group 1] newRaft 2 [peers: [1,2], term: 6, commit: 20, applied: 20, lastindex: 21, lastterm: 6]
panic: requested entry at index is unavailable

goroutine 7650 [running]:
github.com/coreos/etcd/raft.(*raftLog).term(0xc8202e0380, 0x15, 0xc8203c4001, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/log.go:241 +0x1fe
github.com/coreos/etcd/raft.(*raftLog).matchTerm(0xc8202e0380, 0x15, 0x6, 0xb66134)
	/go/src/github.com/coreos/etcd/raft/log.go:275 +0x39
github.com/coreos/etcd/raft.(*raftLog).maybeAppend(0xc8202e0380, 0x15, 0x6, 0x15, 0x0, 0x0, 0x0, 0x15, 0x1725d20)
	/go/src/github.com/coreos/etcd/raft/log.go:78 +0x6e
github.com/coreos/etcd/raft.(*raft).handleAppendEntries(0xc8201847e0, 0x3, 0x2, 0x1, 0x6, 0x6, 0x15, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:745 +0x2fd
--
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:602 +0x447
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820294ba0, 0xc82053abe0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	25.772s
=== RUN   TestBatchBasics
I1209 19:38:26.591424 1022 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1209 19:38:26.594685 1022 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1209 19:38:26.600319 1022 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment]
No longer reproducible
