### ISSUE TITLE
sql: CockroachDB does not reject placeholders in DEFAULT expressions with a clear error message

### ISSUE THREAD

**Issue by ulfjack** [cockroachdb/cockroach#34127]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
I am trying to migrate some closed-source software to cockroachdb. As part of a database upgrade, it attempts to add a few columns to an existing table. On a certain step, I reliably get an SQL panic from cockroachdb.

```
*
* ERROR: [n1,client=127.0.0.1:48100,user=root] a SQL panic has occurred while executing "ALTER TABLE foods ADD COLUMN preferred_unit_kind_metric VARCHAR(32) DEFAULT $1": assignment to entry in nil map
*
*
* ERROR: [n1,client=127.0.0.1:48100,user=root] a panic has occurred!
*
panic while executing 1 statements: ALTER TABLE _ ADD COLUMN _ VARCHAR(32) DEFAULT $1; caused by assignment to entry in nil map

goroutine 1363 [running]:
runtime/debug.Stack(0x3032640, 0xc4280bbb40, 0x3)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x3032640, 0xc4280bbb40, 0xc4204cb980, 0x2968e20, 0xc4286346c0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc42863a000, 0x3032640, 0xc4280bbb40, 0x2770380, 0x3000310)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:643 +0x2df
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc42863a000, 0x3032640, 0xc4280bbb40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
panic(0x2770380, 0x3000310)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*PlaceholderInfo).SetType(0xc42863a428, 0xc4286441b0, 0x1, 0x3048640, 0xc420336aa0, 0x4854201, 0x3035940)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/placeholders.go:156 +0x24a
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*Placeholder).TypeCheck(0xc42861e280, 0xc42863a428, 0x3048b20, 0x4853b60, 0x0, 0x0, 0x28, 0xc428677290)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1295 +0xff
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheck(0x3035940, 0xc42861e280, 0xc42863a428, 0x3048b20, 0x4853b60, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:256 +0xaa
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.SanitizeVarFreeExpr(0x3035940, 0xc42861e280, 0x3048b20, 0x4853b60, 0x2ad8e14, 0x7, 0xc42863a428, 0xc4290e6380, 0x1, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/table.go:58 +0x181
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.MakeColumnDefDescs(0xc4290a0d00, 0xc42863a428, 0xc4290e6380, 0xc4290a0d00, 0xc429089380, 0xc4290a0d00, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/table.go:130 +0x613
github.com/cockroachdb/cockroach/pkg/sql.(*alterTableNode).startExec(0xc42861e500, 0x3032700, 0xc4286345d0, 0xc4290e6380, 0xc42863a418, 0x1, 0xc428679250)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:125 +0x15cf
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x2ae2087, 0xb, 0x3024bc0, 0xc42861e500, 0xc4258e44a8, 0xc428679260)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:640 +0x90
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc429056190, 0x2ae2087, 0xb, 0x3024bc0, 0xc42861e500)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:134 +0x5f
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc429056190, 0x3024bc0, 0xc42861e500, 0x2ae2087, 0xb)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:543 +0x378
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc429056190, 0x3024bc0, 0xc42861e500, 0xc428679de8, 0x6c4069)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:101 +0x8f
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x3032700, 0xc4286345d0, 0x3024bc0, 0xc42861e500, 0x0, 0x2c316f8, 0x0, 0x0, 0xc428634630, 0x3032640, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:65 +0x193
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x3032700, 0xc4286345d0, 0xc4290e6380, 0xc42863a418, 0x3024bc0, 0xc42861e500, 0xc420377a40, 0x3032700)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:645 +0x10e
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc4284baa00, 0x3032700, 0xc4286345d0, 0xc4292fcf68, 0x2687c40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:139 +0xe8
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc4284baa00, 0x3032700, 0xc4286345d0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:730 +0x58
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartSync(0xc4290e6700, 0x3032700, 0xc4286345d0, 0x2c30f10, 0xc4274ef260, 0x300f380)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:607 +0x191
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc4209abe00, 0xc428626480, 0xc425644750, 0xc42867a8d8, 0xc428628780, 0xc42863a4b0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:253 +0x879
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc4209abe00, 0x3032700, 0xc428634360, 0xc42863a4b0, 0xc428626480, 0xc425644750, 0x3024bc0, 0xc42861e500, 0xc428628780)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:758 +0x24c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc42863a000, 0x3032700, 0xc428634360, 0xc42863a418, 0x1, 0x7ff6abe9a2e0, 0xc4290ea480, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:982 +0x2d8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc42863a000, 0x3032700, 0xc428634360, 0x3034540, 0xc428634120, 0x0, 0x0, 0x0, 0xc42817b590, 0x4e, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:824 +0xa8a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc42863a000, 0x3032700, 0xc428634360, 0x3034540, 0xc428634120, 0x0, 0x0, 0x0, 0xc42817b590, 0x4e, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xb3b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc42863a000, 0x3032700, 0xc428634360, 0x3034540, 0xc428634120, 0x0, 0x0, 0x0, 0xc42817b590, 0x4e, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x341
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc42863a000, 0x3032640, 0xc4280bbb40, 0xc4207b1e18, 0x5400, 0x15000, 0xc4207b1eb0, 0xc4256d5b10, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1173 +0x1400
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420902960, 0x3032640, 0xc4280bbb40, 0xc42863a000, 0x5400, 0x15000, 0xc4207b1eb0, 0xc4256d5b10, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc420902960, 0x3032640, 0xc4280bbb40, 0xc42863a000, 0x5400, 0x15000, 0xc4207b1eb0, 0xc4256d5b10, 0xc4256d5b20, 0xc428642010)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:313 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:312 +0x107c

*
* ERROR: [n1,client=127.0.0.1:48100,user=root] Reported as error a9b9600106e9417a981398048ff8068c
*
```

**To Reproduce**

What did you do? Describe in your own words.

I have a test program that creates some tables and then performs a sequence of database upgrades. The code is working with sqlite, which allows database upgrades inside of transactions. I have read the documentation (https://www.cockroachlabs.com/docs/stable/online-schema-changes.html), and I suppose I may have to rewrite this part of the software, but the SQL panic is concerning.

If possible, provide steps to reproduce the behavior:
```
rm -rf cockroach-data/ && cockroach start --insecure --listen-addr=localhost
```

```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Properties;

public final class TestMain {
  public static void main(String[] args) throws Exception {
    Properties props = new Properties();
    props.setProperty("user", "root");
    props.setProperty("sslmode", "disable");
    try (Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:26257/defaultdb", props)) {
      try (Statement s = conn.createStatement()) {
        s.execute("create table if not exists foods (id integer primary key)");
      }
      try (PreparedStatement s = conn.prepareStatement("alter table foods add column name varchar(32) default ?")) {
        s.setObject(1, "foo");
        s.executeUpdate();
      }
    }
  }
}
```

Using the latest postgresql Java driver from:
https://jdbc.postgresql.org/download/postgresql-42.2.5.jar

**Expected behavior**
It should correctly add the column to the table.

**Environment:**
Build Tag:    v2.1.3
Build Time:   2018/12/17 19:15:31
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10.3
C Compiler:   gcc 6.3.0
Build SHA-1:  0c87b11cb99ba5c677c95ded55dcba385928474e
Build Type:   release

[cockroach.dwarf.ulfjack.2019-01-20T00_01_07Z.005007.log](https://github.com/cockroachdb/cockroach/files/2776115/cockroach.dwarf.ulfjack.2019-01-20T00_01_07Z.005007.log)

**Comment by ulfjack** [comment]
Also happens with 2.1.4.

**Comment by ulfjack** [comment]
It looks like it's specific to prepared statements. If I replace the ```?``` with ```'foo'```, it doesn't crash.

**Comment by knz** [comment]
@ulfjack you've found the limitation indeed. CockroachDB does not (currently) support placeholders in DEFAULT expressions, although it does not properly reject them with an error either (and crashes instead).

We will fix this bug but we kindly request that you avoid placeholders for the time being. Thank you for your report!

**Comment by knz** [comment]
From #34134:

> the error reported to the client will be about a mismatch in the number of placeholders vs types, but really we expect something about placeholders not supported in DEFAULT.

**Comment by knz** [comment]
this has been addressed since it was filed
