### ISSUE TITLE
sql: panic: caused by interface conversion: interface is nil, not opt.ScalarExpr

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#34262]
```
create table t (s interval);

values ((cluster_logical_timestamp() // lastval()), (select 'c102:be4:6c95:15d5:b776:6714:2397:6cde/92' from t as tab_1 join [insert into t (s) select '3 years 8 mons 634 days 00:14:23.410791675' from t as tab_3 limit 81 returning 86976104001386.68532, 'bd7589c6-1b6f-4584-a8ba-1d917ff3d9c8', t.s, NULL] on (ARRAY['114.179.121.186/25'] = ARRAY['ef97:1603:377e:886e:9f5:ffd:512a:c33f/43','20c2:da0c:480f:a103:f2a3:7aa7:eb52:2df1/26']) where exists(select NULL, '1970-01-02 20:21:49.000103+00:00', '1970-01-02 14:55:48.000255+00:00', B'11101011', NULL, '\x59765ba48ee4', '1970-01-11 17:21:06.00024+00:00', -0.8412761939437914, -7480545794983527981, 1.5388442758178824 from t as tab_11 where exists(select -4840158514933766648, '1993-10-03', e'{" b=\'YuMA": "4JE6[4>Z", "sNAQ": {" Y MJ]DWW": {"c": null, "r>u)^Z`y": true}, "D<<a": [], "a": {"b": {}}, "foobar": {"b": {}, "baz": null, "foobar": {}, "v}-88.?L{C": "b"}}}', true, e'[[], [], {"[Sr": {}, "baz": {"f{7-o!e]n2": {}}}, [[{}], {"foo": {}}], {"baz": {"1%`p~Udm9p": null, "3WS#+u?MiiY": []}, "vij@\'^Kdk\'": "-n0-eZ"}]', '1970-01-09 14:51:50.000766+00:00', NULL, 'f5752aa8-1a58-4b16-873b-9028b343cf60', '1984-09-06' from t as tab_12) limit 13) limit 1), case when ((NULL || lastval()) IS NOT DISTINCT FROM ARRAY[6620151667168402519,-506368577739444687]) then NULL else cast(coalesce(case when false then false else false end, false) as boolean) end, e'{">b<;gu": [[], []], "LF3#W09/gwP": {"\\\\TL|K|S": [{}, [], {}, [null], []], "bar": [{"/#9?tDE9B": {}, "baz": {}}]}, "S2aCg`_1*%-": [{"bIDjLH:": null}]}', 1340054, B'0110100111000101000110010010111100', (select false from t as tab_13 join t as tab_14 join t as tab_15 join [insert into t (s) select '-38 years -11 mons -419 days -15:02:45.835794108' from t as tab_17 limit 44 returning 1420980615, '1986-07-17', 2134564045, B'11100000010101001100101111010101110000101011111011', NULL, NULL, NULL, 9117433332002694101, 6.714380253129914007E+28, '1970-01-10 02:54:55.000343+00:00', t.s] on true on exists(select NULL, -2786450272812932513, '22727229-e979-41cf-8d13-51d9f55467a0', -864206.8071686418047 from t as tab_18 join t as tab_19 join t as tab_20 on (() = ()) on NULL limit 54) join t as tab_21 join t as tab_22 on exists(select '1970-01-04 05:12:09.000561+00:00', 773904237, '\xe5da99', false from t as tab_23 where (B'010110001000000110001111011111110011010010011010101000101011011101110000' IS NOT DISTINCT FROM B'10100001100') limit 34) on (NULL IS DISTINCT FROM '27 years 3 mons 87 days 06:18:14.371031757') on false where true limit 1));
```

Panic:

```
panic while executing 1 statements: VALUES ((cluster_logical_timestamp() // lastval()), (SELECT _ FROM _ AS _ JOIN [INSERT INTO _(_) SELECT _ FROM _ AS _ LIMIT _ RETURNING _, _, _._, _] ON (ARRAY[_] = ARRAY[_, _]) WHERE EXISTS (SELECT _, _, _, _, _, _, _, _, _, _ FROM _ AS _ WHERE EXISTS (SELECT _, _, _, _, _, _, _, _, _ FROM _ AS _) LIMIT _) LIMIT _), CASE WHEN ((_ || lastval()) IS NOT DISTINCT FROM ARRAY[_, _]) THEN _ ELSE CAST(COALESCE(CASE WHEN _ THEN _ ELSE _ END, _) AS BOOL) END, _, _, _, (SELECT _ FROM _ AS _ JOIN _ AS _ JO [...]; caused by interface conversion: interface is nil, not opt.ScalarExpr

goroutine 14362 [running]:
runtime/debug.Stack(0x37d66a0, 0xc007e15000, 0xc000000003)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x37d66a0, 0xc007e15000, 0xc000159300, 0x2e87960, 0xc005affbc0, 0x1)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:212 +0xa6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc008038000, 0x37d66a0, 0xc007e15000, 0x2c7aa40, 0xc005afef30)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:704 +0x2dd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc008038000, 0x37d66a0, 0xc007e15000)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:423 +0x61
panic(0x2c7aa40, 0xc005afef30)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1(0xc00924e8e8)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:141 +0x9a
panic(0x2c7aa40, 0xc005afef30)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructEq(0xc008038b68, 0x37f2640, 0xc005afeea0, 0x37f2640, 0xc005afeea0, 0xc00924c488, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:8141 +0x153
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).constructComparison(0xc005657a40, 0x0, 0x37f2640, 0xc005afeea0, 0x37f2640, 0xc005afeea0, 0x0, 0x37f2640)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:562 +0x16e
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar(0xc005657a40, 0x37f3360, 0xc005b4b040, 0xc0055ba8f0, 0x0, 0x0, 0x0, 0xc008530d00, 0x37f25e0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:257 +0x2376
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildJoin(0xc005657a40, 0xc008c04280, 0xc0055ba4f0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/join.go:69 +0x5d8
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildDataSource(0xc005657a40, 0x37b1fe0, 0xc008c04280, 0x0, 0xc0055ba4f0, 0xc0055ba5e0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:68 +0x8f3
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildJoin(0xc005657a40, 0xc008c042c0, 0xc0055ba4f0, 0xc00003a000)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/join.go:36 +0xc1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildDataSource(0xc005657a40, 0x37b1fe0, 0xc008c042c0, 0x0, 0xc0055ba4f0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:68 +0x8f3
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFromTables(0xc005657a40, 0xc008a88330, 0x1, 0x1, 0xc0055ba4f0, 0x37db0e0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:737 +0x72
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFrom(0xc005657a40, 0xc00507aa80, 0xc0055ba4f0, 0x692027)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:686 +0x259
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause(0xc005657a40, 0xc008c06000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0055ba4f0, 0x203001)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:627 +0x5e
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc005657a40, 0xc008c04300, 0x0, 0x0, 0x0, 0xc0055ba4f0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:582 +0x201
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc005657a40, 0x37dbca0, 0xc000ca3498, 0xc0055ba4f0, 0xc000ca3498)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:200 +0x2de
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).replaceSubquery(0xc0055ba4f0, 0xc00507aab0, 0x1, 0xffffffffffffffff, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:1090 +0x1ac
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).VisitPre(0xc0055ba4f0, 0x37dc9e0, 0xc00507aab0, 0xc, 0x1, 0xc00924d4f0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:864 +0xc5
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr(0x37b16a0, 0xc0055ba4f0, 0x37dc9e0, 0xc00507aab0, 0xc008510800, 0xc, 0xc00924d570)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:680 +0x56
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).walkExprTree(0xc0055ba4f0, 0x37dc9e0, 0xc00507aab0, 0xc000746a00, 0xc)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:254 +0x5a
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).resolveAndRequireType(0xc0055ba4f0, 0x37dc9e0, 0xc00507aab0, 0x37f5b20, 0x56513e0, 0xc0055ba400, 0xc0055b6400)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:309 +0x49
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildJoin(0xc005657a40, 0xc008c04340, 0xc008533000, 0xc008533d00)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/join.go:70 +0x595
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildDataSource(0xc005657a40, 0x37b1fe0, 0xc008c04340, 0x0, 0xc008533000, 0x7f8d719b1d80)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:68 +0x8f3
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildJoin(0xc005657a40, 0xc008c045c0, 0xc008533000, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/join.go:35 +0x73
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildDataSource(0xc005657a40, 0x37b1fe0, 0xc008c045c0, 0x0, 0xc008533000, 0xc008533cf0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:68 +0x8f3
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildJoin(0xc005657a40, 0xc008c04600, 0xc008533000, 0xa)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/join.go:36 +0xc1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildDataSource(0xc005657a40, 0x37b1fe0, 0xc008c04600, 0x0, 0xc008533000, 0x16)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:68 +0x8f3
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFromTables(0xc005657a40, 0xc008a88450, 0x1, 0x1, 0xc008533000, 0x1d70502)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:737 +0x72
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFrom(0xc005657a40, 0xc00507abd0, 0xc008533000, 0x2df9e80)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:686 +0x259
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause(0xc005657a40, 0xc008c06120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc008533000, 0x203001)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:627 +0x5e
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc005657a40, 0xc008c04640, 0x0, 0x0, 0x0, 0xc008533000, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:582 +0x201
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc005657a40, 0x37dbca0, 0xc000ca34a8, 0xc008533000, 0xc000ca34a8)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:200 +0x2de
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).replaceSubquery(0xc008533000, 0xc00507ac00, 0x2d39400, 0x1, 0x5651300, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:1090 +0x1ac
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).VisitPre(0xc008533000, 0x37dc9e0, 0xc00507ac00, 0x5651b01, 0x37db0a0, 0xc00044f8e0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:866 +0x130
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr(0x37b16a0, 0xc008533000, 0x37dc9e0, 0xc00507ac00, 0xc00044f8e0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:680 +0x56
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).walkExprTree(0xc008533000, 0x37dc9e0, 0xc00507ac00, 0x56513e0, 0x5651301)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:254 +0x5a
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).resolveType(0xc008533000, 0x37dc9e0, 0xc00507ac00, 0x37f5a60, 0x56513e0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:290 +0x43
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildValuesClause(0xc005657a40, 0xc00040a220, 0x0, 0x0, 0x0, 0xc008533000, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/values.go:66 +0x2e3
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc005657a40, 0xc008c04680, 0x0, 0x0, 0x0, 0xc008533000, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:588 +0x6cc
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc005657a40, 0x37dc120, 0xc008c04680, 0xc008533000, 0x4)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:203 +0x10e
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc005657a40, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:148 +0xf6
github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo(0xc0051721a0, 0x37d6760, 0xc005afe0c0, 0xc008c04680, 0xc00519d1a5, 0x9f7, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:337 +0x185
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc008038450, 0x37d6760, 0xc005afe0c0, 0x37dc120, 0xc008c04680, 0xc00519d1a5, 0x9f7, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:132 +0xeb
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan(0xc008038000, 0x37d6760, 0xc005afe0c0, 0x37dc120, 0xc008c04680, 0xc00519d1a5, 0x9f7, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:888 +0x162
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc008038000, 0x37d6760, 0xc005afe0c0, 0x37dc120, 0xc008c04680, 0xc00519d1a5, 0x9f7, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:800 +0x170
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc008038000, 0x37d6760, 0xc005afe0c0, 0x37dc120, 0xc008c04680, 0xc00519d1a5, 0x9f7, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:437 +0xe85
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc008038000, 0x37d6760, 0xc005afe0c0, 0x37dc120, 0xc008c04680, 0xc00519d1a5, 0x9f7, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:93 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc008038000, 0x37d66a0, 0xc007e15000, 0xc0001129f8, 0x5400, 0x15000, 0xc000112a90, 0xc005987340, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1172 +0x21e5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000183a00, 0x37d66a0, 0xc007e15000, 0xc008038000, 0x5400, 0x15000, 0xc000112a90, 0xc005987340, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:425 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000183a00, 0x37d66a0, 0xc007e15000, 0xc008038000, 0x5400, 0x15000, 0xc000112a90, 0xc005987340, 0xc005987350, 0xc008bf3934)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:319 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:318 +0x1033
```

Found with sqlsmith. Assigning for triage cuz I see a lot of opt stacks.

**Comment by mjibson** [comment]
Single statement repro:

```
values ('wku[e^#hV', B'111100100010101001011011010110000100011010001010', (B'0011001011101100000101001001101000101010000011101' || B'0001001000000011110011101100100010010001101110110001110000010110110000100111011001100000000'), '\xb26920037d', '1970-12-25', -0.7450429683506387, B'11000010111001000001010100010101010100000010011', (() = ()), case when true then '1996-03-23' else '1971-06-04' end, 6925768563564825325), (e'&Z`g\x1d\x1c0\x0e', B'110001001101', B'0000000010010111000100111111110110110110110101110000011101110001101100101011111', ('\xc9c2d2' || ('\x5c70094f15' || '\xac782a')), '1970-12-06', pi(), B'010101001100111010101111011111111101101000100010011100011111100111011001011110', NULL, ('1970-11-29' + -937703993382013743), -1298854281291894668), (e'd/u\b', B'110', B'110000011000001000000100100011101100111001101101010010101001100111001101010', '\x5657', NULL, -0.8014573344321142, case when false then B'1100111110001101100101000110011000001000011' else B'101101110011101111110000100001011011010100011010000111001110000000101' end, true, '1987-03-13', case when NULL then inet_server_port() else -6859603288957317254 end), (e'\x13\x15H\x10<n\x1fsc', (B'01101001100100001000100110010000001000' # case when false then B'0001111001000110000011110110110001000100111010000010111110111110110001110001110110000' else NULL end), B'00001111000101011', '\x1a147dc66b', current_date(), -0.9790988477795877, B'0100111111101111000', false, '1974-11-15', -5132551059795810117), (e'\x040\x18DIS$<', B'01011101001', B'111101011110010100011110101011001101110110110110000001011011011010110010000100100111110111110', case when true then (uuid_v4() || (NULL || '\x86128c5cc5869bc038')) else '\x7a5b2825a4c7' end, ('1997-03-20' - 6466574545895202330), 0.7706902972476934, B'0011001010010011101001000110100000010101011100111010001111000100011', case when false then false else false end, '1994-03-16', -149090758460854820), (current_user(), NULL, B'0011001101111001011111010100011110100110111011101000001011001', '\x34', NULL, (2.1092542720105607 // NULL), B'000101001001001101110110100101011101000100000110110110111', cast(coalesce(false, true) as boolean), '1986-06-19', -1311869513860528548)
```
