### ISSUE TITLE
sql: panic: could not find overload for binary expression concat

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#34270]
```
values (e'Z:\x19', '3f0d8f55-ded1-45e0-b746-5edaabc6d325'), ('+_K;', '3d4ceb69-ff15-4efe-8afc-97ed5774922c'), (((e'{"#e`|&cu!": {}, "bar": {"c": {"*RA": {}, "baz": {"/ Akqs rZ": []}}}, "baz": [{"]0~#i<dz+": 1.092928899163599, "{+[wqMhe": {"&B7TJAR6>h": false, "Mm\\\\MG*\\"~&+/": null}}, {"bar": {}}], "u*J}": {"Ku~W6D": false, "}eX]wNC0o": []}}' ->> 5479486423298198472) || ((e'[{"#|-=$_J": [false], "baz": [], "c": [], "foo": []}, {"Qx&{2": ["(\\\\nXHLsi^QJ"], "bar": false, "jl)^o5;`vuL": {}}, true, null]' - ARRAY[e'p;HEpL\x06Y%',e'$o\b\\',e'ELF\x117_\x07']) #>> ARRAY['e1Tpu'])), case when true then '90ca4e42-291a-40e5-9556-a6a3e33771a5' else '73b62f30-8c8d-4dca-8484-649ff2691136' end), (cast(coalesce(NULL, 'd') as text), '2b5ed14f-b3cb-4163-bf9e-c6855636f4a8'), (e'\x04- :\x12aY14', '141b0458-772d-40ae-b0dc-546ff907e17d'), ('-v+d', gen_random_uuid())
```

```
panic while executing 1 statements: VALUES (_, _), (__more5__); caused by could not find overload for binary expression concat

goroutine 290 [running]:
runtime/debug.Stack(0x37bd340, 0xc0057018c0, 0xc000000003)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x37bd340, 0xc0057018c0, 0xc000035300, 0x2e679a0, 0xc008b175f0, 0x1)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:212 +0xa6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00585a000, 0x37bd340, 0xc0057018c0, 0x2b2b1e0, 0xc008b14780)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:704 +0x2dd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc00585a000, 0x37bd340, 0xc0057018c0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:423 +0x61
panic(0x2b2b1e0, 0xc008b14780)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1(0xc0058448e8)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:141 +0x9a
panic(0x2b2b1e0, 0xc008b14780)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.BinaryAllowsNullArgs(0x577001a, 0x37dce80, 0x57d40a0, 0x37dce80, 0x57d40a0, 0xc008b1c0c0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/typing.go:80 +0x132
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).AllowNullArgs(0xc00585ab78, 0x57d001a, 0x37d8d40, 0x5779840, 0x37d8d40, 0x5779840, 0xc008b1a760)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/custom_funcs.go:1074 +0x93
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructConcat(0xc00585ab68, 0x37d8d40, 0x5779840, 0x37d8d40, 0x5779840, 0xc005844101, 0x0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:11920 +0x4bd
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).constructBinary(0xc008aeec30, 0xa, 0x37d8d40, 0x5779840, 0x37d8d40, 0x5779840, 0x37dcca0, 0x57d40a0, 0x5779840, 0xc005844260)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:641 +0x4d8
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar(0xc008aeec30, 0x37d9e80, 0xc008b1c140, 0xc008b19400, 0x0, 0x0, 0x0, 0xc008b170b0, 0xc008b1a720)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:195 +0xc3c
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildValuesClause(0xc008aeec30, 0xc008b1a1c0, 0x0, 0x0, 0x0, 0xc008b19400, 0x0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/values.go:68 +0x361
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc008aeec30, 0xc008b1c3c0, 0x0, 0x0, 0x0, 0xc008b19400, 0x0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:588 +0x6cc
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc008aeec30, 0x37c2dc0, 0xc008b1c3c0, 0xc008b19400, 0x4)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:203 +0x10e
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc008aeec30, 0x0, 0x0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:148 +0xf6
github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo(0xc008ac1e10, 0x37bd400, 0xc008b16f30, 0xc008b1c3c0, 0xc008abf940, 0x35c, 0x0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:337 +0x185
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc00585a450, 0x37bd400, 0xc008b16f30, 0x37c2dc0, 0xc008b1c3c0, 0xc008abf940, 0x35c, 0x0, 0x0, 0x0, ...)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:132 +0xeb
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan(0xc00585a000, 0x37bd400, 0xc008b16f30, 0x37c2dc0, 0xc008b1c3c0, 0xc008abf940, 0x35c, 0x0, 0x0, 0x0, ...)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:888 +0x162
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00585a000, 0x37bd400, 0xc008b16f30, 0x37c2dc0, 0xc008b1c3c0, 0xc008abf940, 0x35c, 0x0, 0x0, 0x0, ...)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:800 +0x170
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00585a000, 0x37bd400, 0xc008b16f30, 0x37c2dc0, 0xc008b1c3c0, 0xc008abf940, 0x35c, 0x0, 0x0, 0x0, ...)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:437 +0xe85
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00585a000, 0x37bd400, 0xc008b16f30, 0x37c2dc0, 0xc008b1c3c0, 0xc008abf940, 0x35c, 0x0, 0x0, 0x0, ...)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:93 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00585a000, 0x37bd340, 0xc0057018c0, 0xc000eea0f8, 0x5400, 0x15000, 0xc000eea190, 0xc0005029b0, 0x0, 0x0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1172 +0x21e5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000ef4000, 0x37bd340, 0xc0057018c0, 0xc00585a000, 0x5400, 0x15000, 0xc000eea190, 0xc0005029b0, 0x0, 0x0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:425 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000ef4000, 0x37bd340, 0xc0057018c0, 0xc00585a000, 0x5400, 0x15000, 0xc000eea190, 0xc0005029b0, 0xc0005029c0, 0xc0003c9784)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:319 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:318 +0x1033
```

Found with sqlsmith.

**Comment by mjibson** [comment]
See also, with a slighty different error message:

```
VALUES (current_database(), -5793.732998453366032), (NULL, (CASE WHEN NULL THEN -3213783279.82765628 ELSE NULL END ^ CASE WHEN true THEN NULL ELSE 5508661910654127100 END))
```

> could not find overload for binary expression pow
