### ISSUE TITLE
distsql: panic when ctrl-c'ing a tpch query

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#34405]
Running TPCH query 5:

```
SELECT
    n_name,
    sum(l_extendedprice * (1 - l_discount)) AS revenue
FROM
    customer,
    orders,
    lineitem,
    supplier,
    nation,
    region
WHERE
    c_custkey = o_custkey
    AND l_orderkey = o_orderkey
    AND l_suppkey = s_suppkey
    AND c_nationkey = s_nationkey
    AND s_nationkey = n_nationkey
    AND n_regionkey = r_regionkey
    AND r_name = 'ASIA'
    AND o_orderDATE >= DATE '1994-01-01'
    AND o_orderDATE < DATE '1994-01-01' + INTERVAL '1' YEAR
GROUP BY
    n_name
ORDER BY
    revenue DESC;
```

on my laptop, ctrl-c'ing the `cockroach sql` shell while this query is running causes my cockroach server to panic:

```
 ERROR: [n1,client=[::1]:63338,user=root] a SQL panic has occurred while executing "SELECT n_name, sum(l_extendedprice * (1 - l_discount)) AS revenue FROM customer, orders, lineitem, supplier, nation, region WHERE
 ((((((((c_custkey = o_custkey) AND (l_orderkey = o_orderkey)) AND (l_suppkey = s_suppkey)) AND (c_nationkey = s_nationkey)) AND (s_nationkey = n_nationkey)) AND (n_regionkey = r_regionkey)) AND (r_name = 'ASIA'))
AND (o_orderdate >= DATE '1994-01-01')) AND (o_orderdate < ('1994-01-01' + '1 year')) GROUP BY n_name ORDER BY revenue DESC": hashjoiner-limited: unexpected 1484800 leftover bytes
*
*
* ERROR: [n1,client=[::1]:63338,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT _, sum(_ * (_ - _)) AS _ FROM _, _, _, _, _, _ WHERE ((((((((_ = _) AND (_ = _)) AND (_ = _)) AND (_ = _)) AND (_ = _)) AND (_ = _)) AND (_ = _)) AND (_ >= DATE _)) AND (_
 < (_ + _)) GROUP BY _ ORDER BY _ DESC; caused by hashjoiner-limited: unexpected 1484800 leftover bytes

goroutine 234 [running]:
runtime/debug.Stack(0x73afd00, 0xc005166f80, 0xc000000003)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x73afd00, 0xc005166f80, 0xc00058b300, 0x6a77300, 0xc0056b3fb0, 0x1)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:212 +0xa6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc005bda000, 0x73afd00, 0xc005166f80, 0x6738c00, 0xc00042b330)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:704 +0x2dd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc005bda000, 0x73afd00, 0xc005166f80)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:423 +0x61
panic(0x6738c00, 0xc00042b330)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/util/log.ReportOrPanic(0x73afdc0, 0xc006e5da10, 0xc00058b300, 0xc0002df500, 0x35, 0x0, 0x0, 0x0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:493 +0x207
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc006e50640, 0x73afdc0, 0xc006e5da10, 0xc006e5da01)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:397 +0x25d
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(0xc006e50640, 0x73afdc0, 0xc006e5da10)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:383 +0x44
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).close(0xc006d77100)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:611 +0xe7
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newHashJoiner.func1(0x73afdc0, 0xc006e5da10, 0x0, 0x0, 0x0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:167 +0x2a
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).moveToTrailingMeta(0xc006d77100)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:764 +0x132
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).DrainHelper(0xc006d77100, 0x7)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:698 +0x1bd
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).Next(0xc006d77100, 0x1, 0x1, 0x0, 0x0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:260 +0x2ae
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).DrainHelper(0xc006e98000, 0x0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:694 +0x9e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).Next(0xc006e98000, 0x0, 0x0, 0x0, 0xc000b5e8c0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:260 +0x2ae
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).DrainHelper(0xc006e9e000, 0xc000b5e8c0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:694 +0x9e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashAggregator).Next(0xc006e9e000, 0x54ac8d3, 0xc0058fa580, 0x0, 0x0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:711 +0x17c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).DrainHelper(0xc006e0aa00, 0x0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:694 +0x9e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sorterBase).Next(0xc006e0aa00, 0x0, 0x0, 0x0, 0x0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:132 +0x166
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x73afdc0, 0xc006e5da10, 0x73bc0c0, 0xc006e0aa00, 0x73a1340, 0xc006e91c00)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:174 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc006e0aa00, 0x73afdc0, 0xc006e5da10)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:802 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc006e543c0, 0x73afdc0, 0xc006e5da10, 0x6d75a80, 0x0, 0x0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:657 +0x209
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00063a8c0, 0xc006e402a0, 0xc006c15320, 0xc006e869a0, 0xc0058fa580, 0xc005bda520, 0x0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:251 +0x8a0
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00063a8c0, 0x73afdc0, 0xc006c17470, 0xc005bda520, 0xc006e402a0, 0xc006c15320, 0x73b1c40, 0xc006d55f80, 0xc0058fa580)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:794 +0x200
```

**Comment by jordanlewis** [comment]
You are hero!

**Comment by jordanlewis** [comment]
@yuzefovich can you try this before and after your recent change?
