### ISSUE TITLE
Cockroach crash in JOIN

### ISSUE THREAD

**Issue by brentbrent** [cockroachdb/cockroach#34464]
**Describe the problem**

A dev on my team found a query that always crashes the cockroach server. It's a pretty simply join, nothing fancy going on here.  Queries, logs from the cockroach box, and table schema are in the "additional data" section.

`panic: panic while executing 1 statements: SELECT _._ FROM _ AS _ JOIN _ AS _ ON _._ = _._ LEFT JOIN _ AS _ ON (_._ = _._) AND (_._ = _._) WHERE (((_._ = _) AND (_._ = _)) AND (_._ > _)) AND (_._ < _) ORDER BY _._ DESC; caused by runtime error: index out of range`

**To Reproduce**

Run the query via the psql command line or via the `lib/pq` golang postgres library.

**Expected behavior**
Server doesn't crash.

**Additional data / screenshots**

Logs from the box that panic'd:

```
E190131 20:53:28.799376 22272 sql/conn_executor.go:636  [n1,client=130.211.2.40:50668,user=brent] a SQL panic has occurred while executing "SELECT b.b_key FROM blobjects AS b JOIN blobject_user_subscribers AS u ON b.b_key = u.b_key LEFT JOIN blobject_user_metadata AS m ON (b.b_key = m.b_key) AND (u.user_key = m.user_key) WHERE (((u.user_key = 'd7d07424-4102-45a2-89b9-52703f81f301') AND (u.removed = false)) AND (b.updated_at > '2019-01-28')) AND (b.updated_at < '2019-02-01') ORDER BY b.updated_at DESC": runtime error: index out of range
E190131 20:53:28.801212 22272 util/log/crash_reporting.go:203  [n1,client=130.211.2.40:50668,user=brent] a panic has occurred!
E190131 20:53:29.137692 22272 util/log/crash_reporting.go:477  [n1,client=130.211.2.40:50668,user=brent] Reported as error 7c41cbc375874025bef9cdec404cd21e
panic: runtime error: index out of range [recovered]
        panic: panic while executing 1 statements: SELECT _._ FROM _ AS _ JOIN _ AS _ ON _._ = _._ LEFT JOIN _ AS _ ON (_._ = _._) AND (_._ = _._) WHERE (((_._ = _) AND (_._ = _)) AND (_._ > _)) AND (_._ < _) ORDER BY _._ DESC; caused by runtime error: index out of range

goroutine 22272 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc4272c2000, 0x3032640, 0xc427306fc0, 0x2770200, 0x4231d70)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:650 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc4272c2000, 0x3032640, 0xc427306fc0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
panic(0x2770200, 0x4231d70)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).convertOrdering(0xc42097de00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:935 +0x27a
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForLookupJoin(0xc42097de00, 0xc429f07260, 0xc4284f4ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1918 +0x964
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc42097de00, 0xc429f07260, 0x3025380, 0xc4284f4ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2273 +0x1284
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForJoin(0xc42097de00, 0xc429f07260, 0xc42a3f7e40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1998 +0x1d3
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc42097de00, 0xc429f07260, 0x30252c0, 0xc42a3f7e40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2276 +0x1924
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc42097de00, 0xc429f07260, 0x3025700, 0xc4296e6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2279 +0xccd
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc42097de00, 0xc429f07260, 0x3025bc0, 0xc42a403960, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2299 +0x681
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc42097de00, 0xc429f07260, 0x3025700, 0xc4296e62c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2279 +0xccd
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc42097de00, 0x3032700, 0xc42b7049f0, 0xc4272c24b0, 0xc429f07260, 0xc42adbed80, 0x3025700, 0xc4296e62c0, 0xc4296e8000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:752 +0x126
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc4272c2000, 0x3032700, 0xc42b7049f0, 0xc4272c2418, 0x3, 0x7f1ed38d5808, 0xc42adbee10, 0x1, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:982 +0x2d8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc4272c2000, 0x3032700, 0xc42b7049f0, 0x3035d80, 0xc42ad87c40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:824 +0xa8a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc4272c2000, 0x3032700, 0xc42b7049f0, 0x3035d80, 0xc42ad87c40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xb3b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc4272c2000, 0x3032700, 0xc42b7049f0, 0x3035d80, 0xc42ad87c40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x341
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc4272c2000, 0x3032640, 0xc427306fc0, 0xc420987bd8, 0x5400, 0x15000, 0xc420987c70, 0xc425204880, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1116 +0x21aa
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420a24ff0, 0x3032640, 0xc427306fc0, 0xc4272c2000, 0x5400, 0x15000, 0xc420987c70, 0xc425204880, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc420a24ff0, 0x3032640, 0xc427306fc0, 0xc4272c2000, 0x5400, 0x15000, 0xc420987c70, 0xc425204880, 0xc425204890, 0xc4250a7ce0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:313 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:312 +0x107c
```

Table Schemas:

```
CREATE TABLE blobjects (
	b_key UUID NOT NULL DEFAULT gen_random_uuid(),
	wrapped_key UUID NOT NULL,
	wrapped_type STRING NOT NULL,
	name STRING NOT NULL DEFAULT '':::STRING,
	updated_at TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
	description STRING NOT NULL DEFAULT '':::STRING,
	avatar STRING NOT NULL DEFAULT '':::STRING,
	CONSTRAINT "primary" PRIMARY KEY (b_key ASC),
	UNIQUE INDEX blobjects_wrapped_key_key (wrapped_key ASC),
	INDEX blobjects_wrapped_key_wrapped_type_idx (wrapped_key ASC, wrapped_type ASC),
	INDEX blobjects_updated_at_wrapped_type_idx (updated_at ASC, wrapped_type ASC),
	INDEX blobjects_updated_at_idx (updated_at ASC),
	FAMILY "primary" (b_key, wrapped_key, wrapped_type, name, updated_at, description, avatar)
)

CREATE TABLE blobject_user_subscribers (
	b_key UUID NOT NULL,
	user_key UUID NOT NULL,
	removed BOOL NOT NULL DEFAULT false,
	updated_at TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT "primary" PRIMARY KEY (b_key ASC, user_key ASC),
	CONSTRAINT fk_user_key FOREIGN KEY (user_key) REFERENCES cr_users (user_key) ON DELETE CASCADE ON UPDATE CASCADE,
	INDEX blobject_user_subscribers_auto_index_fk_user_key (user_key ASC),
	INDEX blobject_user_subscribers_user_key_removed_idx (user_key ASC, removed ASC),
	CONSTRAINT fk_b_key FOREIGN KEY (b_key) REFERENCES blobjects (b_key) ON DELETE CASCADE ON UPDATE CASCADE,
	FAMILY "primary" (b_key, user_key, removed, updated_at)
) INTERLEAVE IN PARENT blobjects (b_key)

CREATE TABLE blobject_user_metadata (
	b_key UUID NOT NULL,
	user_key UUID NOT NULL,
	seen_time TIMESTAMP NOT NULL DEFAULT '0001-01-01 00:00:00+00:00':::TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT "primary" PRIMARY KEY (b_key ASC, user_key ASC),
	CONSTRAINT fk_user_key FOREIGN KEY (user_key) REFERENCES cr_users (user_key) ON DELETE CASCADE ON UPDATE CASCADE,
	INDEX blobject_user_metadata_auto_index_fk_user_key (user_key ASC),
	INDEX blobject_user_metadata_user_key_idx (user_key ASC),
	CONSTRAINT fk_b_key FOREIGN KEY (b_key) REFERENCES blobjects (b_key) ON DELETE CASCADE ON UPDATE CASCADE,
	FAMILY "primary" (b_key, user_key, seen_time, updated_at)
) INTERLEAVE IN PARENT blobjects (b_key)
```

**Environment:**
 - CockroachDB version: v2.1.3
 - Server OS: Debian 9

**Comment by jordanlewis** [comment]
Hey @brentbrent, thanks so much for the report. We actually tracked this down already - it's fixed in 2.1.4. The PR in question was #33522. I'm going to go ahead and close this, but if you see it again in 2.1.4 please let us know.

Thanks!
