### ISSUE TITLE
sql: panic in auto create statistics on views

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#34722]
I started my local node that I used for testing that has a lot of data in it, and it panicked pretty soon after startup:

```
I190207 19:42:13.430763 3591 sql/conn_executor.go:1147  [intExec=create-stats] [NoTxn pos:0] executing ExecStmt: CREATE STATISTICS __auto__ FROM [484] AS OF SYSTEM TIME '-30s'
I190207 19:42:13.430829 3591 sql/conn_executor.go:1147  [intExec=create-stats] [Open pos:0] executing ExecStmt: CREATE STATISTICS __auto__ FROM [484] AS OF SYSTEM TIME '-30s'
I190207 19:42:13.430952 3591 sql/distsqlrun/flow.go:555  [intExec=create-stats] starting (0 processors, 0 startables)
I190207 19:42:13.430970 3591 sql/distsqlrun/flow.go:581  [intExec=create-stats] registered flow 00000000
I190207 19:42:13.431575 3594 sql/conn_executor.go:1147  [intExec=lease-insert] [Open pos:0] executing ExecStmt: INSERT INTO system.public.lease("descID", version, "nodeID", expiration) VALUES (484, 1, 1, '2019-02-07 19:46:50.807633+00:00')
I190207 19:42:13.432391 3594 sql/distsqlrun/flow.go:555  [intExec=lease-insert] starting (0 processors, 0 startables)
I190207 19:42:13.432410 3594 sql/distsqlrun/flow.go:581  [intExec=lease-insert] registered flow 00000000
I190207 19:42:13.432752 3594 sql/distsqlrun/flow.go:699  [intExec=lease-insert] cleaning up
I190207 19:42:13.432799 3594 sql/conn_executor.go:1147  [intExec=lease-insert] [Open pos:1] executing Sync
I190207 19:42:13.432824 3594 sql/conn_executor.go:719  [intExec=lease-insert] finishing connExecutor
panic: runtime error: index out of range

goroutine 3592 [running]:
github.com/cockroachdb/cockroach/pkg/sql.createStatsDefaultColumns(0xc007786c00, 0x73de700, 0xc00788c3f0, 0x7413440, 0xc007786c00, 0xc000000005)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:188 +0x5a9
github.com/cockroachdb/cockroach/pkg/sql.(*createStatsNode).startJob(0xc00745a8a0, 0x73de700, 0xc00788c3f0, 0xc0054e88a0, 0x0, 0xffffffffffffffff)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:124 +0x122
github.com/cockroachdb/cockroach/pkg/sql.(*createStatsNode).startExec.func1(0xc00745a8a0, 0x73de700, 0xc00788c3f0, 0xc009040f00, 0xc0052ce458)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:64 +0x63
created by github.com/cockroachdb/cockroach/pkg/sql.(*createStatsNode).startExec
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:63 +0xcc
```

The panic was on the last line here:

```
func createStatsDefaultColumns(
	desc *ImmutableTableDescriptor,
) ([]jobspb.CreateStatsDetails_ColList, error) {
	columns := make([]jobspb.CreateStatsDetails_ColList, 0, len(desc.Indexes)+1)

	var requestedCols util.FastIntSet

	// If the primary key is not the hidden rowid column, collect stats on it.
	pkCol := desc.PrimaryIndex.ColumnIDs[0]
```

Investigating what table [484] is, I determined that it's a view. Sure enough, create a new view and running statistics over it using the special [] syntax panics the node.

**Comment by rytaft** [comment]
This was fixed by #34726.
