### ISSUE TITLE
Hung cluster while running tpcc 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34760]
**Describe the problem**

I have a cluster that appears healthy (no dead nodes) but tpcc is stuck and not running in the shell. 
![image](https://user-images.githubusercontent.com/22278911/52521610-91af5d80-2c47-11e9-98f3-db2439692341.png)

First I hit:
```
Error: error in stockLevel: ERROR: rpc error: code = Unavailable desc = transport is closing (SQLSTATE XX000)
Error:  exit status 1
```
then i ran it again and its looked like this for 6 hrs
```
Andrews-MBP-2:~ andrewwoods$ roachprod run $CLUSTER:10 "./workload run tpcc --ramp=10m --warehouses=10000 --active-warehouses=10000 --partitions=3 --duration=15m --split --scatter {pgurl:1-9}"
Tables are not being partitioned because they've been previously partitioned
```
which is normally what it looks like just before numbers pop out in the shell.

I also see a create statistics job that looks hung:
![image](https://user-images.githubusercontent.com/22278911/52521604-7cd2ca00-2c47-11e9-814f-ae2cafa7238e.png)

**To Reproduce**
roachprod create $CLUSTER -n 10 --clouds=aws  --aws-machine-type-ssd=c5d.18xlarge
roachprod run $CLUSTER -- 'sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier /dev/md0 /mnt/data1/; mount | grep /mnt/data1'
roachprod stage $CLUSTER:1-9 cockroach
roachprod stage $CLUSTER:10 workload
roachprod start $CLUSTER:1-9 --racks=3
roachprod adminurl --open $CLUSTER:1
roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=10000 --db=tpcc"
roachprod run $CLUSTER:10 "./workload run tpcc --warehouses=10000 --partitions=3 --duration=1s --split --scatter {pgurl:1}"
roachprod sql $CLUSTER:1
SET CLUSTER SETTING kv.snapshot_rebalance.max_rate='64MiB';
Wait for replication queue to go to zero
SET CLUSTER SETTING kv.snapshot_rebalance.max_rate='2MiB';
roachprod run $CLUSTER:10 "./workload run tpcc --ramp=10m --warehouses=10000 --active-warehouses=10000 --partitions=3 --duration=15m --split --scatter {pgurl:1-9}"

**Environment:**
v2.2.0-alpha.20181217-1144-ge3e4f96

**Comment by awoods187** [comment]
[cockroach.ip-172-31-37-22.ubuntu.2019-02-08T22_39_25Z.004996.log](https://github.com/cockroachdb/cockroach/files/2847859/cockroach.ip-172-31-37-22.ubuntu.2019-02-08T22_39_25Z.004996.log)
[cockroach.ip-172-31-37-22.ubuntu.2019-02-08T21_18_32Z.004996.log](https://github.com/cockroachdb/cockroach/files/2847860/cockroach.ip-172-31-37-22.ubuntu.2019-02-08T21_18_32Z.004996.log)
[cockroach.ip-172-31-37-22.ubuntu.2019-02-08T16_47_26Z.004996.log](https://github.com/cockroachdb/cockroach/files/2847861/cockroach.ip-172-31-37-22.ubuntu.2019-02-08T16_47_26Z.004996.log)

**Comment by awoods187** [comment]
I have a debug.zip but it's too large to post

**Comment by awoods187** [comment]
![image](https://user-images.githubusercontent.com/22278911/52526287-5a12d680-2c84-11e9-86b2-8aab480d087d.png)

**Comment by awoods187** [comment]
Lots of stuck goroutines:
```
goroutine 4675864 [running]:
runtime/pprof.writeGoroutineStacks(0x7fde075530c8, 0xc04008e000, 0x6e8b1f, 0xc085b3a5a0)
	/usr/local/go/src/runtime/pprof/pprof.go:678 +0xa7
runtime/pprof.writeGoroutine(0x7fde075530c8, 0xc04008e000, 0x2, 0xc012491180, 0x0)
	/usr/local/go/src/runtime/pprof/pprof.go:667 +0x44
runtime/pprof.(*Profile).WriteTo(0x54cf500, 0x7fde075530c8, 0xc04008e000, 0x2, 0xc04008e000, 0x31327fe)
	/usr/local/go/src/runtime/pprof/pprof.go:328 +0x3e4
net/http/pprof.handler.ServeHTTP(0xc01a540011, 0x9, 0x38c04a0, 0xc04008e000, 0xc00bfd8600)
	/usr/local/go/src/net/http/pprof/pprof.go:245 +0x210
net/http/pprof.Index(0x38c04a0, 0xc04008e000, 0xc00bfd8600)
	/usr/local/go/src/net/http/pprof/pprof.go:268 +0x723
net/http.HandlerFunc.ServeHTTP(0x328e1f8, 0x38c04a0, 0xc04008e000, 0xc00bfd8600)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/cockroachdb/cockroach/pkg/server/debug.(*Server).ServeHTTP(0xc00053dfe0, 0x38c04a0, 0xc04008e000, 0xc00bfd8600)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/debug/server.go:142 +0x91
net/http.(*ServeMux).ServeHTTP(0xc000907f18, 0x38c04a0, 0xc04008e000, 0xc00bfd8600)
	/usr/local/go/src/net/http/server.go:2361 +0x127
github.com/cockroachdb/cockroach/pkg/server.(*safeServeMux).ServeHTTP(0xc000907f00, 0x38c04a0, 0xc04008e000, 0xc00bfd8600)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:146 +0x5d
github.com/cockroachdb/cockroach/pkg/server.(*Server).ServeHTTP(0xc000907c00, 0x38cfb60, 0xc014c9a000, 0xc00bfd8600)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1993 +0x120
net/http.serverHandler.ServeHTTP(0xc000e3e4e0, 0x38cfb60, 0xc014c9a000, 0xc00bfd8600)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc01b02d720, 0x38d4560, 0xc0a6d26980)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5

goroutine 1 [select, 1697 minutes]:
github.com/cockroachdb/cockroach/pkg/cli.runStart(0x54f2400, 0xc000c9a080, 0x0, 0x8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:737 +0x89a
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x54f2400, 0xc000c9a080, 0x0, 0x8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:69 +0x6b
github.com/cockroachdb/cockroach/pkg/cli.maybeShoutError.func1(0x54f2400, 0xc000c9a080, 0x0, 0x8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:214 +0x4d
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x54f2400, 0xc000c9a000, 0x8, 0x8, 0x54f2400, 0xc000c9a000)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x54ec500, 0x8, 0x0, 0xc000993ed8)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0x54ec500, 0x18, 0xc000993ef0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/cockroachdb/cockroach/pkg/cli.Run(0xc000176010, 0x9, 0x9, 0xc00016c010, 0xc00076b300)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:194 +0x65
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:69 +0x222
main.main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:30 +0x20

goroutine 20 [syscall, 1697 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 113 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1222 +0xf2
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:627 +0x11e

goroutine 114 [chan receive, 1697 minutes]:
github.com/cockroachdb/cockroach/pkg/util/log.signalFlusher()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:634 +0xab
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:628 +0x136
```

https://gist.github.com/awoods187/8798850d61f4d0ff7ddd6df1136379de

**Comment by jordanlewis** [comment]
Looks like a scatter command hung, maybe?

```
goroutine 3010203 [chan receive, 808 minutes]:
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges.func1(0xc06f786900, 0xc0bac04bf0, 0xc0bac04b30, 0xc0bac04be8, 0xc0bac04867, 0xc0bac048e8, 0xc0bac0486c)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:833 +0xea
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc000926000, 0x38d4620, 0xc02578e300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1030 +0x7bf
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc000926000, 0x38d4620, 0xc02578e300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:710 +0x48b
github.com/cockroachdb/cockroach/pkg/internal/client.(*CrossRangeTxnWrapperSender).Send(0xc000371c60, 0x38d4620, 0xc02578e300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:212 +0xaf
github.com/cockroachdb/cockroach/pkg/internal/client.SendWrappedWith(0x38d4620, 0xc02578e300, 0x389b400, 0xc000371c60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/sender.go:445 +0x122
github.com/cockroachdb/cockroach/pkg/internal/client.SendWrapped(0x38d4620, 0xc02578e300, 0x389b400, 0xc000371c60, 0x3900aa0, 0xc0aa7122c0, 0xc0508340e0, 0x0, 0xc0d54aa000)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/sender.go:462 +0xa6
github.com/cockroachdb/cockroach/pkg/sql.(*scatterNode).startExec(0xc09578e070, 0x38d4620, 0xc02578e300, 0xc0b3e84d20, 0xc06cd8e458, 0x308e4a0, 0xc0192f3200)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/scatter.go:139 +0xe7
```

**Comment by jordanlewis** [comment]
Andy, it takes practice to interpret if goroutines are stuck. Just because something has a large number of minutes on it doesn't really mean that it's stuck, unfortunately. For example, the 1697 minute "stuck" one is the goroutine that is the `./cockroach start` goroutine - it'll sit there being "stuck" until the server ends, not because it's actually hung or anything.


It looks like the loadgen didn't start because it was waiting for the scatter command to finish, which it never did.

**Comment by awoods187** [comment]
Tried to run this cluster again. I can't complete tpc-c because I consistently hit:
```
Error: error in newOrder: ERROR: rpc error: code = Unavailable desc = transport is closing (SQLSTATE XX000)
Error:  exit status 1
```

**Comment by awoods187** [comment]
it never makes it more than 5m even if latency isn't bad 
```
   5m16s        0           75.0           58.7      5.0     33.6     92.3     96.5 orderStatus
   5m16s        0          586.7          589.5     10.5     39.8    100.7    134.2 payment
   5m16s        0           89.0           58.5     18.9     60.8    130.0    130.0 stockLevel
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
   5m17s        0           85.1           58.3     48.2    184.5    302.0    302.0 delivery
   5m17s        0          503.5          550.2     30.4    201.3    268.4    335.5 newOrder
   5m17s        0           91.1           58.8      5.0     18.9     37.7     39.8 orderStatus
   5m17s        0          628.7          589.6     15.2    176.2    251.7    318.8 payment
   5m17s        0           87.1           58.6     22.0     48.2     71.3     75.5 stockLevel
Error: error in newOrder: ERROR: rpc error: code = Unavailable desc = transport is closing (SQLSTATE XX000)
Error:  exit status 1
```

**Comment by tbg** [comment]
re: https://github.com/cockroachdb/cockroach/issues/34760#issuecomment-462079564,
this goroutine below looks suspicious, though perhaps it got caught in a retry loop by accident.
There isn't a single goroutine in `(*Node).Batch` (let alone on `*Replica`), so it doesn't seem that anything's stuck server-side. Perhaps the scatter got stuck in an infinite loop as @jordanlewis suggested.

```
goroutine 3017223 [select]:
github.com/cockroachdb/cockroach/pkg/util/retry.(*Retry).Next(0xc07e325ac0, 0x38d4620)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:120 +0x13a
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc000926000, 0x38d4620, 0xc02578e300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1121 +0x16a
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatchAsync.func1(0x38d4620, 0xc02578e300)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1061 +0x175
```

At the very least, we need to log something if a request stays in https://github.com/cockroachdb/cockroach/blob/70be833b48d79a7ead1608f30d30e4b38765e8e4/pkg/kv/dist_sender.go#L1121 for too long (and it will need to be rate limited, for in unavailable clusters requests can spend lots of time there).

**Comment by drewdeally** [comment]
I ran into this same error

Error: error in stockLevel: ERROR: rpc error: code = Unavailable desc = transport is closing (SQLSTATE XXUUU

testing with 19.2.6 cockroach on db nodes and client.   if its worth investigating I can upload logs

**Comment by irfansharif** [comment]
@drewdeally: that error could be due to a whole host of reasons, and I encourage you to file separately if you have a repro for something we could take a closer look at. I'm going to go ahead and close out the original issue due to age, we run TPC-C pretty regularly now and to my knowledge don't run into this behavior. I'm unsure what happened originally, but I doubt this is actionable anymore.

**Comment by drewdeally** [comment]
understood
