### ISSUE TITLE
adriatic crashed with 2.1.5 candidate

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#34915]
```
W190214 14:39:14.922943 225998271 util/log/clog.go:1400  log traffic is now intercepted; log files will be incomplete
panic: runtime error: index out of range

goroutine 226007656 [running]:
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).addEvent(0xc43edd91e0, 0x2735280, 0xc42b4bfb90, 0xc442220000)
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:772 +0x734
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).LazyPrintf(0xc43edd91e0, 0x2ad856f, 0x2, 0xc44222b8c0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:801 +0xa0
github.com/cockroachdb/cockroach/pkg/util/tracing.(*span).LogFields(0xc44509cb60, 0xc43fab9c80, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tracer_span.go:389 +0x65e
github.com/cockroachdb/cockroach/pkg/util/log.eventInternal(0x305a6a0, 0xc42b4bf890, 0x2680000, 0x2ae0906, 0x8, 0xc446599b10, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:132 +0x21c
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x305a6a0, 0xc42b4bf890, 0x1, 0x2, 0x2b1f9a4, 0x22, 0xc446599c40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:84 +0x298
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x305a6a0, 0xc42b4bf890, 0x1, 0xc400000001, 0x2b1f9a4, 0x22, 0xc446599c40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Infof(0x305a6a0, 0xc42b4bf890, 0x2b1f9a4, 0x22, 0xc446599c40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:87 +0x7e
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBudget(0xc447768be0, 0x305a6a0, 0xc42b4bf890)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:680 +0x134
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc447768be0, 0x305a6a0, 0xc42b4bf890, 0xc42b4bf801)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:405 +0x94
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(0xc447768be0, 0x305a6a0, 0xc42b4bf890)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:384 +0x44
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sorterBase).close(0xc43921e000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:145 +0xfc
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newSortAllProcessor.func1(0x305a6a0, 0xc42b4bf890, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:262 +0x2c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).moveToTrailingMeta(0xc43921e000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:693 +0x140
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).DrainHelper(0xc43921e000, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:640 +0x14f
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sorterBase).Next(0xc43921e000, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:132 +0x163
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x305a6a0, 0xc42b4bf890, 0x30639a0, 0xc43921e000, 0x30377e0, 0xc42f46dc00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:172 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc43921e000, 0x305a6a0, 0xc4491a14d0, 0xc4420f4888)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:731 +0x98
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartAsync
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:587 +0x1e3
```

**Comment by RaduBerinde** [comment]
The crash inside `x/net/trace` is indicative of a span being used after `Finish`.

**Comment by RaduBerinde** [comment]
```
func (s *sorterBase) close() {
	// We are done sorting rows, close the iterator we have open.
	if s.InternalClose() {
		if s.i != nil {
			s.i.Close()
		}
		ctx := s.evalCtx.Ctx()
		s.rows.Close(ctx)
		s.MemMonitor.Stop(ctx)    <---- here ctx has an unfinished span
		if s.diskMonitor != nil {
			s.diskMonitor.Stop(ctx)
		}
	}
}
```
CC @asubiotto @jordanlewis

**Comment by RaduBerinde** [comment]
CC @andreimatei as well, it looks like this should be the session's context.

**Comment by andreimatei** [comment]
Yeah; using the `evalCtx` here is atrocious.
What I believe should be used is `sorterBase.Ctx`.

**Comment by RaduBerinde** [comment]
I'll restart the node since we know the problem.

**Comment by RaduBerinde** [comment]
I don't think this should hold up v2.1.5 since it's a much older issue. The fix should be backported though.
@jordanlewis please reassign to someone in the sql exec team.

**Comment by jordanlewis** [comment]
Thanks, hopefully linked patch will take care of this and another couple of related issue.
