### ISSUE TITLE
sql: panic: caused by invalid

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#34927]
```
create table t();
EXPLAIN ANALYZE DELETE FROM FAMILY @ SESSION_USER where true;
```

trace:

```
E190214 20:27:19.215666 206 sql/conn_executor.go:707  [n1,client=127.0.0.1:45348,user=root] a SQL panic has occurred while executing "EXPLAIN ANALYZE (DISTSQL) DELETE FROM t@session_user WHERE true": invalid
E190214 20:27:19.215726 206 util/log/crash_reporting.go:202  [n1,client=127.0.0.1:45348,user=root] a panic has occurred!
E190214 20:27:19.216677 206 util/log/crash_reporting.go:476  [n1,client=127.0.0.1:45348,user=root] Reported as error 61cbda6edb2e43d4aef9906f38a06d52
panic: invalid [recovered]
	panic: panic while executing 1 statements: EXPLAIN ANALYZE (DISTSQL) DELETE FROM _@_ WHERE _; caused by invalid

goroutine 206 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc001844000, 0x390c420, 0xc001604e00, 0x2c76f00, 0x38c50e0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:721 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc001844000, 0x390c420, 0xc001604e00)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:427 +0x61
panic(0x2c76f00, 0x38c50e0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql.(*deleteRangeNode).Next(0xc00154e000, 0x390c4e0, 0xc00178d680, 0xc000211a40, 0xc001844458, 0x32be088, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/delete_range.go:214 +0x39
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc0007dea00, 0xc001844458, 0x390d8e0, 0xc00154e000, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:190 +0x48c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x390c4e0, 0xc00178d680, 0x3917a20, 0xc0007dea00, 0x38fdba0, 0xc0016f3880)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:175 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc0007dea00, 0x390c4e0, 0xc00178d680)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:801 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc0015c4540, 0x390c4e0, 0xc00178d680, 0x32bd7b8, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:649 +0x209
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0005b88c0, 0xc00097a900, 0xc0016c4120, 0xc0012d0fb0, 0xc001694580, 0xc000211c20, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8a0
github.com/cockroachdb/cockroach/pkg/sql.(*explainDistSQLNode).startExec(0xc00145a3f0, 0x390c4e0, 0xc00178d2c0, 0xc000211860, 0xc001844458, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/explain_distsql.go:208 +0x9c0
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x316b91c, 0xf, 0x390db20, 0xc00145a3f0, 0xc00106c2a0, 0xc0012d11e8)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:514 +0x55
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc0004edbd0, 0x316b91c, 0xf, 0x390db20, 0xc00145a3f0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:141 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc0004edbd0, 0x390db20, 0xc00145a3f0, 0x316b91c, 0xf)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:146 +0x5841
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc0004edbd0, 0x390db20, 0xc00145a3f0, 0xc0017c8f40, 0x10)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:108 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x390c4e0, 0xc00178d2c0, 0x390db20, 0xc00145a3f0, 0x0, 0x32be088, 0x0, 0x0, 0xc00178d320, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:72 +0x15f
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x390c4e0, 0xc00178d2c0, 0xc000211860, 0xc001844458, 0x390db20, 0xc00145a3f0, 0xc0017c8f38, 0xc0017c8f30)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:517 +0xfd
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc0007de500, 0x390c4e0, 0xc00178d2c0, 0x59c38c0, 0x2c76180)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:124 +0xd9
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc0007de500, 0x390c4e0, 0xc00178d2c0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:800 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc0015c41c0, 0x390c4e0, 0xc00178d2c0, 0x32bd7b8, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:649 +0x209
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0005b88c0, 0xc00097a8a0, 0xc0016c4120, 0xc0012d2990, 0xc000385600, 0xc001844518, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8a0
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc0005b88c0, 0x390c4e0, 0xc0017fa4b0, 0xc001844518, 0xc00097a8a0, 0xc0016c4120, 0x390e020, 0xc0015551e0, 0xc000385600)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:795 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001844000, 0x390c4e0, 0xc0017fa4b0, 0xc001844458, 0x3, 0x7f3bc0346ff8, 0xc0007d8370, 0x0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1044 +0x26e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001844000, 0x390c4e0, 0xc0017fa4b0, 0xc001844458, 0x7f3bc0346ff8, 0xc0007d8370, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:900 +0x644
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001844000, 0x390c4e0, 0xc0017fa4b0, 0x3911620, 0xc0017fa390, 0xc00113d12e, 0x37, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:438 +0xe49
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001844000, 0x390c4e0, 0xc0017fa4b0, 0x3911620, 0xc0017fa390, 0xc00113d12e, 0x37, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:93 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001844000, 0x390c420, 0xc001604e00, 0xc000113538, 0x5400, 0x15000, 0xc0001135d0, 0xc000408560, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1182 +0x21e5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000626000, 0x390c420, 0xc001604e00, 0xc001844000, 0x5400, 0x15000, 0xc0001135d0, 0xc000408560, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:429 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000626000, 0xc001170000, 0xc00039cbe4, 0xc000408560, 0x390c420, 0xc001604e00, 0xc001844000, 0x5400, 0x15000, 0xc0001135d0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:331 +0xcf
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:314 +0x1040
```

Found with RSG.

**Comment by jordanlewis** [comment]
This bug is caused by an important but subtle omission by the CBO's exec build phase, which doesn't set the StatementType field on the `explainDistSQLNode` that it produces when planning such a node. This field is used to determine whether or not the "fast path" is enabled when running plans that include top level wrapped planNodes - if the fast path isn't enabled, then the code will try to `Next` those planNodes which will panic in cases like this one where the node only supports fast path evaluation and not ordinary `Next`ing.

I didn't see an immediate way to fix this in execbuild by getting the statement type, since the statement (AST node) for the thing being explained is long gone by the time execbuild starts.

@RaduBerinde any ideas here?

**Comment by RaduBerinde** [comment]
We would need to make it a field of ExplainPrivate and set it during optbuild.

**Comment by RaduBerinde** [comment]
I can take this.
