### ISSUE TITLE
Failed tests (10288): TestGossipPeerings 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3492]
The following test appears to have failed:

[#10288](https://circleci.com/gh/cockroachdb/cockroach/10288):

```
E1218 16:34:25.720517 18652 acceptance/cluster/localcluster.go:396  node=1 status=stop
E1218 16:34:25.869202 18652 acceptance/cluster/localcluster.go:396  node=1 status=start
E1218 16:34:28.358859 18652 acceptance/cluster/localcluster.go:396  node=1 status=restart
I1218 16:34:29.374312 18652 acceptance/main_test.go:166  invalid character 'p' after top-level value
I1218 16:34:29.474676 18652 acceptance/cluster/localcluster.go:523  stopping
--- FAIL: TestGossipPeerings (20.70s)
panic: interface conversion: interface {} is nil, not map[string]interface {} [recovered]
	panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 79 [running]:
testing.tRunner.func1(0xc8200b8c60)
	/usr/local/go/src/testing/testing.go:450 +0x171
github.com/cockroachdb/cockroach/acceptance.checkGossip.func1(0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/gossip_peerings_test.go:55 +0x4ec
github.com/cockroachdb/cockroach/util.SucceedsWithinDepth(0x1, 0x7fc595d766f8, 0xc8200b8c60, 0x4a817c800, 0xc823f0de30)
	/go/src/github.com/cockroachdb/cockroach/util/testing.go:148 +0x18f
github.com/cockroachdb/cockroach/util.SucceedsWithin(0x7fc595d766f8, 0xc8200b8c60, 0x4a817c800, 0xc823f0de30)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
this is fixed in 7b4a2ed2.
