### ISSUE TITLE
node crashed in the early stage of booting up

### ISSUE THREAD

**Issue by donga2** [cockroachdb/cockroach#34976]
**Describe the problem**
I have 3 nodes cluster, but after one of the nodes reboot, it was struggling to come back. The whole log was as below. What catches my eye is: "0 of 1 are within the offset".  It seems it recognize itself as the only one node in the cluster. 

```
I190130 22:50:54.287097 1 util/log/clog.go:1134  [config] file created at: 2019/01/30 22:50:54
I190130 22:50:54.287097 1 util/log/clog.go:1134  [config] running on machine: tipirr1-sc-VSO-static-N2
I190130 22:50:54.287097 1 util/log/clog.go:1134  [config] binary: CockroachDB CCL v2.0.6 (x86_64-unknown-linux-gnu, built 2018/10/01 13:59:40, go1.10)
I190130 22:50:54.287097 1 util/log/clog.go:1134  [config] arguments: [/ddr/dds/cockroach-latest.linux-amd64/cockroach start --certs-dir=/ddr/dds/.certs --host=d:d:d:d:d::fe22 --port=5432 --join=[d:d:d:d:d::fe20]:5432 --store=path=/ddr/ext/ddr/cockroach_data,size=640Mib --http-port=8080]
I190130 22:50:54.287097 1 util/log/clog.go:1134  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
I190130 22:50:54.287096 1 server/config.go:311  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory), using system memory 79 GiB instead
W190130 22:50:54.287255 1 cli/start.go:812  Using the default setting for --cache (128 MiB).
  A significantly larger value is usually needed for good performance.
  If you have a dedicated server a reasonable setting is --cache=.25 (20 GiB).
I190130 22:50:54.287325 1 server/config.go:311  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory), using system memory 79 GiB instead
W190130 22:50:54.287337 1 cli/start.go:825  Using the default setting for --max-sql-memory (128 MiB).
  A significantly larger value is usually needed in production.
  If you have a dedicated server a reasonable setting is --max-sql-memory=.25 (20 GiB).
I190130 22:50:54.287346 1 cli/start.go:923  CockroachDB CCL v2.0.6 (x86_64-unknown-linux-gnu, built 2018/10/01 13:59:40, go1.10)
I190130 22:50:54.390510 1 server/config.go:311  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory), using system memory 79 GiB instead
I190130 22:50:54.390526 1 server/config.go:430  system total memory: 79 GiB
I190130 22:50:54.390558 1 server/config.go:432  server configuration:
max offset             500000000
cache size             128 MiB
SQL memory pool size   128 MiB
scan interval          10m0s
scan max idle time     200ms
event log enabled      true
I190130 22:50:54.390575 1 cli/start.go:796  process identity: uid 997 euid 997 gid 1000 egid 1000
I190130 22:50:54.390584 1 cli/start.go:461  starting cockroach node
I190130 22:50:54.392131 15 storage/engine/rocksdb.go:553  opening rocksdb instance at "/ddr/ext/ddr/cockroach_data/cockroach-temp049082402"
I190130 22:50:54.426600 15 server/server.go:734  [n?] monitoring forward clock jumps based on server.clock.forward_jump_check_enabled
W190130 22:50:54.426903 15 server/config_unix.go:92  soft open file descriptor limit 4096 is under the recommended limit 15000; this may decrease performance
please see https://www.cockroachlabs.com/docs/v2.0/recommended-production-settings.html for more details
I190130 22:50:54.426933 15 storage/engine/rocksdb.go:553  opening rocksdb instance at "/ddr/ext/ddr/cockroach_data"
I190130 22:50:54.459871 15 server/config.go:538  [n?] 1 storage engine initialized
I190130 22:50:54.459883 15 server/config.go:541  [n?] RocksDB cache size: 128 MiB
I190130 22:50:54.459894 15 server/config.go:541  [n?] store 0: RocksDB, max size 640 MiB, max open file limit 3840
W190130 22:50:54.461520 15 gossip/gossip.go:1293  [n?] no incoming or outgoing connections
I190130 22:50:54.461610 15 server/server.go:784  [n?] Sleeping till wall time 1548888654461587609 to catches up to 1548888654926557650 to ensure monotonicity. Delta: 464.970041ms
F190130 22:50:54.470201 141 server/server.go:219  [n?] clock synchronization error: this node is more than 500ms away from at least half of the known nodes (0 of 1 are within the offset)
goroutine 141 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc420546400, 0xc420546420, 0x3328800, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:959 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x3bd7aa0, 0xc400000004, 0x33288ef, 0x10, 0xdb, 0xc4200ea510, 0x88)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:835 +0x753
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2787660, 0xc4207ec030, 0x4, 0x2, 0x0, 0x0, 0xc420cb1c58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:154 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2787660, 0xc4207ec030, 0x1, 0x4, 0x0, 0x0, 0xc420cb1c58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:55 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x2787660, 0xc4207ec030, 0xc420cb1c58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:158 +0x6c
github.com/cockroachdb/cockroach/pkg/server.NewServer.func1()
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:219 +0xb0
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc42035f680, 0xc4203f1630, 0xc420284e60, 0x16, 0xc420547860, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:698 +0x667
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.1.1(0x2787660, 0xc420bdd1a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:564 +0x74
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42027bd20, 0xc4205cc2d0, 0xc420bdd170)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad
```

**To Reproduce**
There is no steps to consistently reproduce it

**Expected behavior**
It should check the rest nodes to determine if it was the drifted one.

**Environment:**
 - CockroachDB version 2.0.6
 - Server OS: Linux

**Comment by donga2** [comment]
Here is another full log for this issue.  I originally thought the issue might be related to delta for ensuring monotonicity exceeding the time offset threshold. But the in log below, the delta is 245.793767ms which is supposed to within the threshold. 

```
I190203 09:40:06.792350 1 util/log/clog.go:1134  [config] file created at: 2019/02/03 09:40:06
I190203 09:40:06.792350 1 util/log/clog.go:1134  [config] running on machine: tipirr1-sc-VSO-static-N2
I190203 09:40:06.792350 1 util/log/clog.go:1134  [config] binary: CockroachDB CCL v2.0.6 (x86_64-unknown-linux-gnu, built 2018/10/01 13:59:40, go1.10)
I190203 09:40:06.792350 1 util/log/clog.go:1134  [config] arguments: [/ddr/dds/cockroach-latest.linux-amd64/cockroach start --certs-dir=/ddr/dds/.certs --host=d:d:d:d:d::fe22 --port=5432 --join=[d:d:d:d:d::fe20]:5432 --store=path=/ddr/ext/ddr/cockroach_data,size=640Mib --http-port=8080]
I190203 09:40:06.792350 1 util/log/clog.go:1134  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
I190203 09:40:06.792349 1 server/config.go:311  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory), using system memory 79 GiB instead
W190203 09:40:06.792553 1 cli/start.go:812  Using the default setting for --cache (128 MiB).
  A significantly larger value is usually needed for good performance.
  If you have a dedicated server a reasonable setting is --cache=.25 (20 GiB).
I190203 09:40:06.792626 1 server/config.go:311  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory), using system memory 79 GiB instead
W190203 09:40:06.792640 1 cli/start.go:825  Using the default setting for --max-sql-memory (128 MiB).
  A significantly larger value is usually needed in production.
  If you have a dedicated server a reasonable setting is --max-sql-memory=.25 (20 GiB).
I190203 09:40:06.792649 1 cli/start.go:923  CockroachDB CCL v2.0.6 (x86_64-unknown-linux-gnu, built 2018/10/01 13:59:40, go1.10)
I190203 09:40:06.896569 1 server/config.go:311  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory), using system memory 79 GiB instead
I190203 09:40:06.896589 1 server/config.go:430  system total memory: 79 GiB
I190203 09:40:06.896632 1 server/config.go:432  server configuration:
max offset             500000000
cache size             128 MiB
SQL memory pool size   128 MiB
scan interval          10m0s
scan max idle time     200ms
event log enabled      true
I190203 09:40:06.896650 1 cli/start.go:796  process identity: uid 997 euid 997 gid 1000 egid 1000
I190203 09:40:06.896658 1 cli/start.go:461  starting cockroach node
I190203 09:40:06.898537 26 storage/engine/rocksdb.go:553  opening rocksdb instance at "/ddr/ext/ddr/cockroach_data/cockroach-temp365234112"
I190203 09:40:06.933922 26 server/server.go:734  [n?] monitoring forward clock jumps based on server.clock.forward_jump_check_enabled
W190203 09:40:06.934227 26 server/config_unix.go:92  soft open file descriptor limit 4096 is under the recommended limit 15000; this may decrease performance
please see https://www.cockroachlabs.com/docs/v2.0/recommended-production-settings.html for more details
I190203 09:40:06.934263 26 storage/engine/rocksdb.go:553  opening rocksdb instance at "/ddr/ext/ddr/cockroach_data"
I190203 09:40:07.185200 26 server/config.go:538  [n?] 1 storage engine initialized
I190203 09:40:07.185216 26 server/config.go:541  [n?] RocksDB cache size: 128 MiB
I190203 09:40:07.185230 26 server/config.go:541  [n?] store 0: RocksDB, max size 640 MiB, max open file limit 3840
W190203 09:40:07.188022 26 gossip/gossip.go:1293  [n?] no incoming or outgoing connections
I190203 09:40:07.188109 26 server/server.go:784  [n?] Sleeping till wall time 1549186807188082639 to catches up to 1549186807433876406 to ensure monotonicity. **Delta: 245.793767ms**
F190203 09:40:07.197481 81 server/server.go:219  [n?] clock synchronization error: this node is more than 500ms away from at least half of the known nodes (0 of 1 are within the offset)
goroutine 81 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc4200a4b00, 0xc4200a4b40, 0x3328800, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:959 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x3bd7aa0, 0xc400000004, 0x33288ef, 0x10, 0xdb, 0xc420d06090, 0x88)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:835 +0x753
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2787660, 0xc42093c7b0, 0x4, 0x2, 0x0, 0x0, 0xc420d19c58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:154 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2787660, 0xc42093c7b0, 0x1, 0x4, 0x0, 0x0, 0xc420d19c58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:55 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x2787660, 0xc42093c7b0, 0xc420d19c58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:158 +0x6c
github.com/cockroachdb/cockroach/pkg/server.NewServer.func1()
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:219 +0xb0
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc4200e5680, 0xc4208f4960, 0xc420330460, 0x16, 0xc4204c51a0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:698 +0x667
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.1.1(0x2787660, 0xc420b7aae0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:564 +0x74
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202fdcf0, 0xc42082e090, 0xc420b7aab0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad
```

**Comment by donga2** [comment]
close it as I found it's caused by the huge time diff between the advertising node and the node to join cluster
