### ISSUE TITLE
sql: panic: invalid datum type given: int, expected decimal

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#35113]
`select 0::int8 + 3989212821610048162::decimal // 8965304063540790833::int8`

```
panic: invalid datum type given: int, expected decimal [recovered]
        panic: panic while executing 1 statements: SELECT _::INT8 + (_::DECIMAL // _::INT8); caused by invalid datum type given: int, expected decimal

goroutine 410 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00083c000, 0x37e69a0, 0xc001416180, 0x2b51e40, 0xc0002b2660)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:721 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc00083c000, 0x37e69a0, 0xc001416180)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:427 +0x61
panic(0x2b51e40, 0xc0002b2660)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:170 +0x25d
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc0007eea00, 0xc00083c460, 0x37e8c20, 0xc000c3ed70, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:190 +0x593
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x37e6a60, 0xc001535800, 0x37f1fe0, 0xc0007eea00, 0x37d8460, 0xc0014c8380)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:175 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc0007eea00, 0x37e6a60, 0xc001535800)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:801 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc00140c380, 0x37e6a60, 0xc001535800, 0x3198718, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:649 +0x209
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0007d5900, 0xc0005b1b60, 0xc000a6ad80, 0xc0016fa990, 0xc000457080, 0xc00083c520, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8a0
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc0007d5900, 0x37e6a60, 0xc001535320, 0xc00083c520, 0xc0005b1b60, 0xc000a6ad80, 0x37e8c20, 0xc000c3ed70, 0xc000457080)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:795 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc00083c000, 0x37e6a60, 0xc001535320, 0xc00083c460, 0x3, 0x7fc6b3e2a290, 0xc000fc0630, 0x0, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1051 +0x26e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00083c000, 0x37e6a60, 0xc001535320, 0xc00083c460, 0x7fc6b3e2a290, 0xc000fc0630, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:900 +0x644
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00083c000, 0x37e6a60, 0xc001535320, 0x37ec560, 0xc0018b1ac0, 0xc000fa20e9, 0x4a, 0x0, 0x0, 0x0, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:438 +0xe49
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00083c000, 0x37e6a60, 0xc001535320, 0x37ec560, 0xc0018b1ac0, 0xc000fa20e9, 0x4a, 0x0, 0x0, 0x0, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:93 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00083c000, 0x37e69a0, 0xc001416180, 0xc0007da578, 0x5400, 0x15000, 0xc0007da610, 0xc000408380, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1182 +0x21e5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000a22000, 0x37e69a0, 0xc001416180, 0xc00083c000, 0x5400, 0x15000, 0xc0007da610, 0xc000408380, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:429 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000a22000, 0xc000465b00, 0xc000381ac4, 0xc000408380, 0x37e69a0, 0xc001416180, 0xc00083c000, 0x5400, 0x15000, 0xc0007da610, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:331 +0xcf
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:314 +0x1040
```

**Comment by jordanlewis** [comment]
@yuzefovich could you take a look please?

**Comment by jordanlewis** [comment]
@yuzefovich and I investigated this. We think it's a problem with the constant folding mechanism in the optimizer.

We noticed that this does not panic if the denominator is smaller, forcing the result of the division to be non-zero. We also noticed that this crashes with the optimizer on, but not without, and that the explain plan for these queries has a constant folded result:

```
root@127.0.0.1:56956/defaultdb> explain(opt) select 0::int8 + (3989212821610048162::decimal // 63333833::int8);
         text
+---------------------+
  values
   └── (62987073932,)
(2 rows)

root@127.0.0.1:56994/defaultdb> explain(opt,verbose) select 0::int8 + (3989212821610048162::decimal // 6354033733903333833::int8);
             text
+----------------------------+
  values
   ├── columns: "?column?":1
   ├── cardinality: [1 - 1]
   ├── stats: [rows=1]
   ├── cost: 0.02
   ├── key: ()
   ├── fd: ()-->(1)
   ├── prune: (1)
   └── (0,)
(9 rows)

Time: 598µs
```

Our guess is that what's happening is that the constant folding phase doesn't properly preserve the `decimal` type of the result when the result is 0. Instead, the constant folded result is integer 0, but the resultant plan expects a decimal 0, which panics at runtime.

Does this make sense?

**Comment by andy-kimball** [comment]
@rytaft, can you take a look?
