### ISSUE TITLE
sql: PGAssertionError: schema for virtual table not found

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#35145]
Run the [sequelize example](https://github.com/cockroachdb/examples-orms/blob/master/node/sequelize/Makefile) against `master`:

```
$ npm install
$ make
> sequelize-cockroachdb-test@1.0.0 start /Users/tschottdorf/go/src/github.com/cockroachdb/examples-orms/node/sequelize
> node ./app.js

body-parser deprecated bodyParser: use individual json/urlencoded middlewares app.js:12:9
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:105:29
(node:94685) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
Unhandled rejection error: internal error: schema for virtual table not found
    at Connection.parseE (/Users/tschottdorf/go/src/github.com/cockroachdb/examples-orms/node/sequelize/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/tschottdorf/go/src/github.com/cockroachdb/examples-orms/node/sequelize/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/tschottdorf/go/src/github.com/cockroachdb/examples-orms/node/sequelize/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:638:20)
```
I'm not sure if this works against past versions (haven't checked), but since this is an "assertion error" it seems that an example shouldn't be able to trigger it.

**Comment by jordanlewis** [comment]
It looks like this might be new / changed in the optimizer. Now that I think about it, I've started to see this error when there's a missing database for someone who expects one.

Here's a quick repro. Start a server, and then in another window, open a connection to a non-existant database.

```
[8:33]% ./cockroach sql --insecure --database=foo 
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
warning: unable to retrieve the server's version: pq: internal error: schema for virtual table not found
#
# Enter \? for a brief introduction.
#
warning: error retrieving the database name: pq: database "foo" does not exist
root@:26257/?>
```

**Comment by jordanlewis** [comment]
@RaduBerinde you might know more about this.

**Comment by knz** [comment]
I think I know how to fix the internal error, but the sequelize example must be updated too.
