### ISSUE TITLE
sql: panic when inserting into column with a check referencing a column created in the same transaction

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#35193]
```
create table t (a int);
begin;
alter table t add column b int;
alter table t add check (a > b);
insert into t (a) values (1);
commit;
```
We should be returning some reasonable error here, since `b` hasn't been created yet (even though we _do_ allow adding the check constraint), but this panics.
```
E190225 23:29:34.400802 423 sql/conn_executor.go:707  [n1,client=127.0.0.1:49528,user=root] a SQL panic has occurred while executing "INSERT INTO t(a) VALUES (1)": could not find return column
E190225 23:29:34.401522 423 util/log/crash_reporting.go:202  [n1,client=127.0.0.1:49528,user=root] a panic has occurred!
E190225 23:29:34.407584 423 util/log/crash_reporting.go:476  [n1,client=127.0.0.1:49528,user=root] Reported as error decdd91badac4695ad31330f9e452e17
panic: could not find return column [recovered]
	panic: could not find return column [recovered]
	panic: panic while executing 1 statements: INSERT INTO _(_) VALUES (_); caused by could not find return column

goroutine 423 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0017d8000, 0x742eac0, 0xc00174f980, 0x678a600, 0x73e92f0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:721 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0017d8000, 0x742eac0, 0xc00174f980)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:427 +0x61
panic(0x678a600, 0x73e92f0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1(0xc001732998)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:142 +0x9a
panic(0x678a600, 0x73e92f0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).mapToReturnColID(...)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder.go:477
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).disambiguateColumns(0xc001260580)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder.go:409 +0x369
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).addCheckConstraintCols(0xc001260580)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder.go:379 +0x72
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).buildInsert(0xc001260580, 0x0, 0x0, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:592 +0x2f
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildInsert(0xc0013e54a0, 0xc001522820, 0xc00186d800, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:242 +0x606
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc0013e54a0, 0x7434040, 0xc001522820, 0xc00186d800, 0x4)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:205 +0x3b2
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc0013e54a0, 0x0, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:156 +0x111
github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo(0xc000bc9b90, 0x742eb80, 0xc001178930, 0xc001522820, 0x742eb80, 0xc001178930, 0x4060500)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:384 +0x188
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc0017d8460, 0x742eb80, 0xc001178930, 0x6c9f60d, 0x19, 0xb1379ec2866e, 0xe17e25588)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:146 +0xc8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan(0xc0017d8000, 0x742eb80, 0xc001178930, 0xc0017d8460, 0x6, 0x400e3af)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:928 +0x11b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0017d8000, 0x742eb80, 0xc001178930, 0xc0017d8460, 0xf498098, 0xc001510840, 0x0, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:823 +0x148
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0017d8000, 0x742eb80, 0xc001178930, 0x7434040, 0xc001522820, 0xc0018045f7, 0x1c, 0x0, 0x0, 0x0, ...)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:436 +0xd8c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0017d8000, 0x742eb80, 0xc001178930, 0x7434040, 0xc001522820, 0xc0018045f7, 0x1c, 0x0, 0x0, 0x0, ...)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:93 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0017d8000, 0x742eac0, 0xc00174f980, 0xc000dfc0f8, 0x5400, 0x15000, 0xc000dfc190, 0xc00174a730, 0x0, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1182 +0x21e5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000e0a000, 0x742eac0, 0xc00174f980, 0xc0017d8000, 0x5400, 0x15000, 0xc000dfc190, 0xc00174a730, 0x0, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:429 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000e0a000, 0xc000505b00, 0xc00047a944, 0xc00174a730, 0x742eac0, 0xc00174f980, 0xc0017d8000, 0x5400, 0x15000, 0xc000dfc190, ...)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:331 +0xcf
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:314 +0x1040
```
This is probably ultimately caused by the fact that we add check constraints to the table descriptor immediately, even when the columns they refer to are not yet public. We account for this in parts of the code by looking at columns in the mutations list in addition to public columns, but not everywhere.

edit: This only happens with the optimizer turned on. Otherwise, we get the error `pq: column "b" does not exist` on the insert, which is better (though cryptic-seeming).

**Comment by lucy-zhang** [comment]
I wrote some tests with the schema changer testing knobs to figure out the scope of this problem. I was only able to cause this panic for INSERTs, and only when the non-public column is in the `DELETE_ONLY` state, presumably because of https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/optbuilder/mutation_builder.go#L329. In all other states, the non-backfilled values in `b` are just treated as NULLs, so writes go through without errors (unless the constraint specifically requires that `b` is non-null).

The heuristic planner's behavior is different: it just rejects all writes to `a` before `b` is public, with an error that `b` doesn't exist.

At this point, I think the best short-term fix might be just to have all writes to `a` treat `b` as a public column solely for enforcing the check constraint (which is what UPDATEs with the optimizer are accidentally doing), with all non-backfilled values treated as NULL. (I'm assuming that a partially-backfilled table would actually be safe to read for this purpose, which may not be true...) Any values written to `a` that would violate the constraint will still be caught by the final check validation.

The alternative would be what I originally thought of, which is to make the optimizer match the heuristic planner in rejecting all writes to `a`, but that's a significant cost even if it's safer/easier to reason about.

I'm filing another issue shortly for the long-term fix, which is to hold off on adding the check constraint until the backfill has been completed.

cc @dt
