### ISSUE TITLE
sql: panic: could not find overload for binary expression minus

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#35277]
```
VALUES
    (
        inet_server_addr()
        - CASE WHEN true THEN NULL ELSE -3036236087517311912 END
        - hostmask('3079:b62c:4fb0:7738:6f8c:9f3f:38c6:91f9/51'),
        '2e28:ed20:8cb7:e838:b521:b381:6971:4757/62'
    );
```

```
panic: could not find overload for binary expression minus [recovered]
	panic: could not find overload for binary expression minus [recovered]
	panic: panic while executing 1 statements: VALUES ((inet_server_addr() - CASE WHEN _ THEN _ ELSE _ END) - hostmask(_), _); caused by could not find overload for binary expression minus

goroutine 434 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00063b000, 0x3943fe0, 0xc00154f300, 0x2c9c9e0, 0xc0004081c0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:722 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc00063b000, 0x3943fe0, 0xc00154f300)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:427 +0x61
panic(0x2c9c9e0, 0xc0004081c0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1(0xc0014de8b0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:142 +0x9a
panic(0x2c9c9e0, 0xc0004081c0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.BinaryAllowsNullArgs(0xc000ad005f, 0x3961300, 0x5896d20, 0x39612a0, 0x5896d20, 0xc0014ddfc0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/typing.go:80 +0x132
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).AllowNullArgs(0xc00063bba0, 0x589005f, 0x3965c20, 0xc00039e800, 0x3965080, 0xc000ada5a0, 0x18)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/custom_funcs.go:1090 +0x93
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructMinus(0xc00063bb90, 0x3965c20, 0xc00039e800, 0x3965080, 0xc000ada5a0, 0xc0014de001, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:12019 +0x4d6
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).constructBinary(0xc00154c000, 0x4, 0x3965c20, 0xc00039e800, 0x3965080, 0xc000ada5a0, 0x3961300, 0x5896d20, 0xc000ada5a0, 0x2)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:629 +0x248
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar(0xc00154c000, 0x395e660, 0xc0015343c0, 0xc0015d4400, 0x0, 0x0, 0x0, 0x0, 0x3188e70)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:195 +0xc7e
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildValuesClause(0xc00154c000, 0xc00039e620, 0x0, 0x0, 0x0, 0xc0015d4400, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/values.go:68 +0x361
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc00154c000, 0xc001534300, 0x0, 0x0, 0x0, 0xc0015d4400, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:587 +0x6cc
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc00154c000, 0x3949ba0, 0xc001534300, 0xc0015d4400, 0x4)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:211 +0x10e
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc00154c000, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:156 +0x111
github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo(0xc0014b0000, 0x39440a0, 0xc0016147b0, 0xc001534300, 0x39440a0, 0xc0016147b0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:399 +0x188
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc00063b460, 0x39440a0, 0xc0016147b0, 0x31b30aa, 0x19, 0xf546c87fe4, 0x2acf544e)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:147 +0xc8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan(0xc00063b000, 0x39440a0, 0xc0016147b0, 0xc00063b460, 0x6, 0x6c534f)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:939 +0x11b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00063b000, 0x39440a0, 0xc0016147b0, 0xc00063b460, 0x7f55a106c430, 0xc0007934a0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:834 +0x148
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00063b000, 0x39440a0, 0xc0016147b0, 0x3949ba0, 0xc001534300, 0xc001808378, 0x127, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:447 +0xd8c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00063b000, 0x39440a0, 0xc0016147b0, 0x3949ba0, 0xc001534300, 0xc001808378, 0x127, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:103 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00063b000, 0x3943fe0, 0xc00154f300, 0xc0007c89f8, 0x5400, 0x15000, 0xc0007c8a90, 0xc000361a20, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1183 +0x21e5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0009b69c0, 0x3943fe0, 0xc00154f300, 0xc00063b000, 0x5400, 0x15000, 0xc0007c8a90, 0xc000361a20, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:429 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc0009b69c0, 0xc00011ed00, 0xc0002fc674, 0xc000361a20, 0x3943fe0, 0xc00154f300, 0xc00063b000, 0x5400, 0x15000, 0xc0007c8a90, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:331 +0xcf
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:314 +0x1040
```

**Comment by jordanlewis** [comment]
Isn't this a dupe of that other one? #34270

**Comment by jordanlewis** [comment]
I mean #35246.

**Comment by mjibson** [comment]
Yes thanks. Didn't see that.
