### ISSUE TITLE
sql: panic:  columns required of root must be subset of output columns

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#35437]
This was found while running the SQL Alchemy unit tests, specifically `test/orm/test_eager_relations.py::CorrelatedSubqueryTest::test_labeled_on_limitid_alias`

Here's the SQL execution log leading up to it:
```
I190305 21:57:00.905429 2433 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root,intExec=log-event] 1175 exec "$ internal-log-event" {} "INSERT INTO system.eventlog(\"timestamp\", \"eventType\", \"targetID\", \"reportingID\", info) VALUES (now(), $1, $2, $3, $4)" {$1:"'create_table'", $2:"634", $3:"1", $4:"'{\"TableName\":\"bah.public.users\",\"Statement\":\"CREATE TABLE users (id INT8 NOT NULL DEFAULT unique_rowid(), name VARCHAR(50), PRIMARY KEY (id))\",\"User\":\"root\"}'"} 1.579 1 ""
I190305 21:57:00.905542 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1176 exec "" {} "CREATE TABLE users (id INT8 NOT NULL DEFAULT unique_rowid(), name VARCHAR(50), PRIMARY KEY (id))" {} 10.351 0 ""
I190305 21:57:00.919074 2317 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root,intExec=log-event] 1177 exec "$ internal-log-event" {} "INSERT INTO system.eventlog(\"timestamp\", \"eventType\", \"targetID\", \"reportingID\", info) VALUES (now(), $1, $2, $3, $4)" {$1:"'create_table'", $2:"635", $3:"1", $4:"'{\"TableName\":\"bah.public.stuff\",\"Statement\":\"CREATE TABLE stuff (id INT8 NOT NULL DEFAULT unique_rowid(), date DATE, user_id INT8, PRIMARY KEY (id), FOREIGN KEY (user_id) REFERENCES users (id))\",\"User\":\"root\"}'"} 2.007 1 ""
I190305 21:57:00.919153 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1178 exec "" {} "CREATE TABLE stuff (id INT8 NOT NULL DEFAULT unique_rowid(), date DATE, user_id INT8, PRIMARY KEY (id), FOREIGN KEY (user_id) REFERENCES users (id))" {} 10.284 0 ""
I190305 21:57:00.920786 924 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root,intExec=count-leases] 1179 exec "$ internal-count-leases" {} "SELECT count(1) FROM system.public.lease AS OF SYSTEM TIME 1551823020908766000.0000000000 WHERE (((\"descID\" = 634) AND (version = 0)) AND (expiration > $1))" {$1:"'2019-03-05 21:57:00.908766+00:00'"} 1.250 0 ""
I190305 21:57:00.922768 2336 sql/exec_log.go:162  [n1,split,s1,r621/1:/{Table/633-Max},intExec=log-range-event] 1180 exec "$ internal-log-range-event" {} "INSERT INTO system.rangelog(\"timestamp\", \"rangeID\", \"storeID\", \"eventType\", \"otherRangeID\", info) VALUES ($1, $2, $3, $4, $5, $6)" {$1:"'2019-03-05 21:57:00.916168+00:00'", $2:"621", $3:"1", $4:"'split'", $5:"631", $6:"'{\"UpdatedDesc\":{\"range_id\":621,\"start_key\":\"9wJ5\",\"end_key\":\"9wJ6\",\"replicas\":[{\"node_id\":1,\"store_id\":1,\"replica_id\":1}],\"next_replica_id\":2,\"generation\":1},\"NewDesc\":{\"range_id\":631,\"start_key\":\"9wJ6\",\"end_key\":\"//8=\",\"replicas\":[{\"node_id\":1,\"store_id\":1,\"replica_id\":1}],\"next_replica_id\":2}}'"} 3.546 1 ""
I190305 21:57:00.923808 2547 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root,scExec,intExec=count-leases] 1181 exec "$ internal-count-leases" {} "SELECT count(1) FROM system.public.lease AS OF SYSTEM TIME 1551823020922529000.0000000000 WHERE (((\"descID\" = 634) AND (version = 1)) AND (expiration > $1))" {$1:"'2019-03-05 21:57:00.922529+00:00'"} 1.256 0 ""
I190305 21:57:00.925482 2548 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root,scExec,intExec=count-leases] 1182 exec "$ internal-count-leases" {} "SELECT count(1) FROM system.public.lease AS OF SYSTEM TIME 1551823020923917000.0000000000 WHERE (((\"descID\" = 635) AND (version = 0)) AND (expiration > $1))" {$1:"'2019-03-05 21:57:00.923917+00:00'"} 1.543 0 ""
I190305 21:57:00.928760 106 sql/exec_log.go:162  [n1,split,s1,r631/1:/{Table/634-Max},intExec=log-range-event] 1183 exec "$ internal-log-range-event" {} "INSERT INTO system.rangelog(\"timestamp\", \"rangeID\", \"storeID\", \"eventType\", \"otherRangeID\", info) VALUES ($1, $2, $3, $4, $5, $6)" {$1:"'2019-03-05 21:57:00.926451+00:00'", $2:"631", $3:"1", $4:"'split'", $5:"632", $6:"'{\"UpdatedDesc\":{\"range_id\":631,\"start_key\":\"9wJ6\",\"end_key\":\"9wJ7\",\"replicas\":[{\"node_id\":1,\"store_id\":1,\"replica_id\":1}],\"next_replica_id\":2,\"generation\":1},\"NewDesc\":{\"range_id\":632,\"start_key\":\"9wJ7\",\"end_key\":\"//8=\",\"replicas\":[{\"node_id\":1,\"store_id\":1,\"replica_id\":1}],\"next_replica_id\":2}}'"} 1.365 1 ""
I190305 21:57:00.929140 926 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root,scExec,intExec=count-leases] 1184 exec "$ internal-count-leases" {} "SELECT count(1) FROM system.public.lease AS OF SYSTEM TIME 1551823020927843000.0000000000 WHERE (((\"descID\" = 635) AND (version = 1)) AND (expiration > $1))" {$1:"'2019-03-05 21:57:00.927843+00:00'"} 1.271 0 ""
I190305 21:57:00.930410 927 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root,scExec,intExec=count-leases] 1185 exec "$ internal-count-leases" {} "SELECT count(1) FROM system.public.lease AS OF SYSTEM TIME 1551823020929295000.0000000000 WHERE (((\"descID\" = 634) AND (version = 1)) AND (expiration > $1))" {$1:"'2019-03-05 21:57:00.929295+00:00'"} 1.096 0 ""
I190305 21:57:00.932652 1489 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root,intExec=lease-insert] 1186 exec "$ internal-lease-insert" {} "INSERT INTO system.public.lease(\"descID\", version, \"nodeID\", expiration) VALUES (634, 2, 1, '2019-03-05 22:02:40.442719+00:00')" {} 0.693 1 ""
I190305 21:57:00.934694 2564 sql/exec_log.go:162  [intExec=get-table-statistics] 1187 exec "$ internal-get-table-statistics" {} "SELECT \"tableID\", \"statisticID\", name, \"columnIDs\", \"createdAt\", \"rowCount\", \"distinctCount\", \"nullCount\", histogram FROM system.table_statistics WHERE \"tableID\" = $1 ORDER BY \"createdAt\" DESC" {$1:"634"} 1.081 0 ""
I190305 21:57:00.934973 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1188 exec "" {} "INSERT INTO users(id, name) VALUES (1, 'user1')" {} 3.361 1 ""
I190305 21:57:00.935426 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1189 exec "" {} "INSERT INTO users(id, name) VALUES (2, 'user2')" {} 0.295 1 ""
I190305 21:57:00.935731 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1190 exec "" {} "INSERT INTO users(id, name) VALUES (3, 'user3')" {} 0.207 1 ""
I190305 21:57:00.938548 2551 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root,intExec=lease-insert] 1191 exec "$ internal-lease-insert" {} "INSERT INTO system.public.lease(\"descID\", version, \"nodeID\", expiration) VALUES (635, 2, 1, '2019-03-05 22:01:54.38101+00:00')" {} 0.642 1 ""
I190305 21:57:00.940221 2579 sql/exec_log.go:162  [intExec=get-table-statistics] 1192 exec "$ internal-get-table-statistics" {} "SELECT \"tableID\", \"statisticID\", name, \"columnIDs\", \"createdAt\", \"rowCount\", \"distinctCount\", \"nullCount\", histogram FROM system.table_statistics WHERE \"tableID\" = $1 ORDER BY \"createdAt\" DESC" {$1:"635"} 0.915 0 ""
I190305 21:57:00.941241 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1193 exec "" {} "INSERT INTO stuff(id, date, user_id) VALUES (1, '2007-10-15'::DATE, 1)" {} 3.693 1 ""
I190305 21:57:00.941769 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1194 exec "" {} "INSERT INTO stuff(id, date, user_id) VALUES (2, '2007-12-15'::DATE, 1)" {} 0.379 1 ""
I190305 21:57:00.942258 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1195 exec "" {} "INSERT INTO stuff(id, date, user_id) VALUES (3, '2007-11-15'::DATE, 1)" {} 0.376 1 ""
I190305 21:57:00.942645 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1196 exec "" {} "INSERT INTO stuff(id, date, user_id) VALUES (4, '2008-01-15'::DATE, 2)" {} 0.303 1 ""
I190305 21:57:00.943058 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1197 exec "" {} "INSERT INTO stuff(id, date, user_id) VALUES (5, '2007-06-15'::DATE, 3)" {} 0.314 1 ""
I190305 21:57:00.943427 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1198 exec "" {} "INSERT INTO stuff(id, date, user_id) VALUES (6, '2007-03-15'::DATE, 3)" {} 0.283 1 ""
I190305 21:57:00.958818 2209 sql/exec_log.go:162  [n1,client=[::1]:59734,user=root] 1199 exec "" {} "SELECT users.id AS users_id, users.name AS users_name, stuff_1.id AS stuff_1_id, stuff_1.date AS stuff_1_date, stuff_1.user_id AS stuff_1_user_id FROM users LEFT JOIN stuff AS stuff_1 ON (users.id = stuff_1.user_id) AND (stuff_1.id = (SELECT stuff_2.id FROM stuff AS stuff_2 WHERE stuff_2.user_id = users.id ORDER BY stuff_2.date DESC LIMIT 1)) ORDER BY users.name" {} 5.935 0 ""
```

And the panic itself:
```

* ERROR: [n1,client=[::1]:59734,user=root] a SQL panic has occurred while executing "SELECT users.id AS users_id, users.name AS users_name, stuff_1.id AS stuff_1_id, stuff_1.date AS stuff_1_date, stuff_1.user_id AS stuff_1_user_id FROM users LEFT JOIN stuff AS stuff_1 ON (users.id = stuff_1.user_id) AND (stuff_1.id = (SELECT stuff_2.id FROM stuff AS stuff_2 WHERE stuff_2.user_id = users.id ORDER BY stuff_2.date DESC LIMIT 1)) ORDER BY users.name": columns required of root must be subset of output columns
*
*
* ERROR: [n1,client=[::1]:59734,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _ FROM _ LEFT JOIN _ AS _ ON (_._ = _._) AND (_._ = (SELECT _._ FROM _ AS _ WHERE _._ = _._ ORDER BY _._ DESC LIMIT _)) ORDER BY _._; caused by columns required of root must be subset of output columns

goroutine 2209 [running]:
runtime/debug.Stack(0x75ab5e0, 0xc009a72140, 0x3)
	/Users/bram/go1.12/src/runtime/debug/stack.go:24 +0x9d
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x75ab5e0, 0xc009a72140, 0xc0005f4000, 0x6c19f80, 0xc0079d5ec0, 0x1)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:212 +0xa3
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0094ab600, 0x75ab5e0, 0xc009a72140, 0x68ca080, 0x74f4240)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:708 +0x2a0
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0094ab600, 0x75ab5e0, 0xc009a72140)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:427 +0x61
panic(0x68ca080, 0x74f4240)
	/Users/bram/go1.12/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeRootWithProps(0xc008e754a8)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:722 +0x71a
github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize(0xc008e754a8, 0x76000a0, 0xc003d9c3b0)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:190 +0x80
github.com/cockroachdb/cockroach/pkg/sql.(*applyJoinNode).Next(0xc008e754a0, 0x75ab6a0, 0xc0079d5440, 0xc008e75680, 0xc0094ab950, 0x6dc5c39, 0xa, 0x90)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:262 +0x57f
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc000457900, 0x0, 0x6f26e38, 0x0, 0xc00a3c7cc8)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:178 +0x469
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).fill(0xc0086b2000, 0x75ab6a0, 0xc0079d5440, 0x6dc02c6)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:305 +0x74
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).Start(0xc0086b2000, 0x75ab6a0, 0xc0079d5440, 0x9560380, 0x68c8f40)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:286 +0xab
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc0086b2000, 0x75ab6a0, 0xc0079d5440)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:800 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc000a5ddc0, 0x75ab6a0, 0xc0079d5440, 0x6f26550, 0x0, 0x0)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:624 +0x1ec
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000117540, 0xc006e52cc0, 0xc0074c5ef0, 0xc00a3c8810, 0xc003ffa2c0, 0xc0094aba10, 0x0)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8fe
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc000117540, 0x75ab6a0, 0xc0079d4480, 0xc0094aba10, 0xc006e52cc0, 0xc0074c5ef0, 0x75ad5e0, 0xc007d417c0, 0xc003ffa2c0)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:839 +0x1fb
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc0094ab600, 0x75ab6a0, 0xc0079d4480, 0xc0094ab950, 0x3, 0xb6e0dc0, 0xc008952bb0, 0xc00a3c8a00, 0x0, 0x0)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1094 +0x284
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0094ab600, 0x75ab6a0, 0xc0079d4480, 0xc0094ab950, 0xb6e0dc0, 0xc008952bb0, 0x0, 0x0)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:939 +0x6c1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0094ab600, 0x75ab6a0, 0xc0079d4480, 0x75b1160, 0xc009818740, 0xc009a6a91b, 0x173, 0x0, 0x0, 0x0, ...)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:457 +0xefc
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0094ab600, 0x75ab6a0, 0xc0079d4480, 0x75b1160, 0xc009818740, 0xc009a6a91b, 0x173, 0x0, 0x0, 0x0, ...)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:103 +0x638
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0094ab600, 0x75ab5e0, 0xc009a72140, 0xc0004989f8, 0x5400, 0x15000, 0xc000498a90, 0xc006e41920, 0x0, 0x0)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1178 +0x2145
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc00089d1e0, 0x75ab5e0, 0xc009a72140, 0xc0094ab600, 0x5400, 0x15000, 0xc000498a90, 0xc006e41920, 0x0, 0x0)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:429 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc00089d1e0, 0xc008530000, 0xc0071eae30, 0xc006e41920, 0x75ab5e0, 0xc009a72140, 0xc0094ab600, 0x5400, 0x15000, 0xc000498a90, ...)
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:331 +0xcf
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/Users/bram/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:314 +0x1121

*
* ERROR: [n1,client=[::1]:59734,user=root] Reported as error 06acbcbff173461a9b7cc0d0a12d8f43
*
```

Assigning to @andy-kimball for triage.

**Comment by andy-kimball** [comment]
@jordanlewis, this looks like an `apply-join` issue. The assert fires when the presentation column IDs are not present in the query being optimized. Also, as an aside, looking at `apply_join.go`, I noticed that this line still exists when it looks redundant:
```
a.optimizer.Memo().SetRoot(a.optimizer.Memo().RootExpr().(memo.RelExpr), a.rightProps)
```

Here is a cleaned up logic-test repro:
```
# LogicTest: local-opt

statement ok
CREATE TABLE users (
	id INT8 NOT NULL DEFAULT unique_rowid(),
	name VARCHAR(50),
	PRIMARY KEY (id)
);
INSERT INTO users(id, name) VALUES (1, 'user1');
INSERT INTO users(id, name) VALUES (2, 'user2');
INSERT INTO users(id, name) VALUES (3, 'user3');

statement ok
CREATE TABLE stuff (
	id INT8 NOT NULL DEFAULT unique_rowid(),
	date DATE,
	user_id INT8,
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES users (id)
);
INSERT INTO stuff(id, date, user_id) VALUES (1, '2007-10-15'::DATE, 1);
INSERT INTO stuff(id, date, user_id) VALUES (2, '2007-12-15'::DATE, 1);
INSERT INTO stuff(id, date, user_id) VALUES (3, '2007-11-15'::DATE, 1);
INSERT INTO stuff(id, date, user_id) VALUES (4, '2008-01-15'::DATE, 2);
INSERT INTO stuff(id, date, user_id) VALUES (5, '2007-06-15'::DATE, 3);
INSERT INTO stuff(id, date, user_id) VALUES (6, '2007-03-15'::DATE, 3);

query ITITI
SELECT
	users.id AS users_id,
	users.name AS users_name,
	stuff_1.id AS stuff_1_id,
	stuff_1.date AS stuff_1_date,
	stuff_1.user_id AS stuff_1_user_id
FROM
	users
	LEFT JOIN stuff AS stuff_1
	ON
		users.id = stuff_1.user_id
		AND stuff_1.id
			= (
					SELECT
						stuff_2.id
					FROM
						stuff AS stuff_2
					WHERE
						stuff_2.user_id = users.id
					ORDER BY
						stuff_2.date DESC
					LIMIT
						1
				)
ORDER BY
	users.name;
----
```

**Comment by jordanlewis** [comment]
The presentation that gets generated is:

```
presentation: [presentation: id:3,date:4,user_id:5,id:6,date:7]
```

Whereas the re-planned RHS has columns:

```
 ├── columns: stuff_1.id:3(int!null) stuff_1.date:4(date) stuff_1.user_id:5(int) stuff_2.id:6(int)
```

Looks like there's a second date column in the expected presentation that gets generated for some reason.

I then went and printed the RHS when we plan it during the null-replacement portion. It, too, has no extra columns. I discovered that the columns get added during execbuild. After we call `buildRelational`, the resultant output columns include a new one, column 7.

```
Fake right expr distinct-on
 ├── columns: stuff_1.id:3(int!null) stuff_1.date:4(date) stuff_1.user_id:5(int) stuff_2.id:6(int)

Fake right  map[3:0 4:1 5:2 6:3 7:4]
```

Is this expected? @andy-kimball

**Comment by andy-kimball** [comment]
@RaduBerinde, I'm looking at `execbuilder.Builder.buildDistinct`. It passes through the input columns as output columns:
```
return execPlan{root: node, outputCols: input.outputCols}, nil
```
That doesn't seem right when some of the input columns are used purely for ordering the groups, and are not projected by the distinct operator. Do you agree?

Note that the HP also seems to have the same issue, in `getPlanColumns`:
```
	// Nodes that have the same schema as their source or their
	// valueNode helper.
	case *distinctNode:
		return getPlanColumns(n.plan, mut)
```
That makes me wonder if it's a deliberate choice to always project the ordering columns...

**Comment by RaduBerinde** [comment]
Hm, indeed, in `buildDistinct` it seems that we need to add a post-projection according to the aggregations.

**Comment by RaduBerinde** [comment]
The `distinctNode` itself always has the same output columns as the input.
