### ISSUE TITLE
Bursts of distsql queries can starve node liveness

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#35535]
A cluster recently experienced an incident where seemingly a burst of distsql traffic lead to a spike in CPU utilization which resulting in node liveness heartbeat failures that ultimately left the cluster in a sorry state. 

This issue is being left as a placeholder for further details about the specific incident as well as a discussion about ways to mitigate such failures.

**Comment by ajwerner** [comment]
Some simplistic but potentially effective short term solutions might be as simple as providing cluster settings to lengthen to node liveness timeout in cases where it is known that a cluster under provisioned.

Possibly this is a case where we should dramatically lower the number of concurrent distsql queries to something on the order of number of cores of the machines. This will have its own bad implications.

**Comment by tim-o** [comment]
Zendesk ticket #[3070](https://cockroachdb.zendesk.com/agent/tickets/3070) has been linked to this issue.

**Comment by tim-o** [comment]
Zendesk ticket #[3195](https://cockroachdb.zendesk.com/agent/tickets/3195) has been linked to this issue.

**Comment by jordanlewis** [comment]
Revisiting this based on recent investigations related to issues around #35859.

My current theory is that the grpc+http/2 flow control stuff isn't doing a good job at preventing distsql traffic from starving other queries. In fact, distsql traffic can be heavy enough to have grpc's own liveness pings fail to go through and shut down the entire transport, which will doom all requests in between the nodes that the transport is connected between.

I'd like to experiment with creating a separate set of connections just for distsql.

**Comment by petermattis** [comment]
> My current theory is that the grpc+http/2 flow control stuff isn't doing a good job at preventing distsql traffic from starving other queries. In fact, distsql traffic can be heavy enough to have grpc's own liveness pings fail to go through and shut down the entire transport, which will doom all requests in between the nodes that the transport is connected between.

This is a bit surprising to me and doesn't match my mental model. If this is true, it should be straightforward to create a simple grpc test that demonstrates this badness (completely independent of Cockroach).

**Comment by asubiotto** [comment]
I don't think DistSQL traffic affects GRPC liveness pings (they are written directly to the framer):
https://github.com/grpc/grpc-go/blob/ed10349f451e96cf671d270545c99ff0041fea7c/internal/transport/controlbuf.go#L643

**Comment by petermattis** [comment]
We do have our own heartbeat pings (in `pkg/rpc`). Are those being starved by DistSQL traffic causing the connection to be closed?

**Comment by asubiotto** [comment]
They could be. I don't see any code that closes connections due to a timed out heartbeat though, but I might be reading the code in `runHeartbeat` wrong: https://github.com/cockroachdb/cockroach/blob/38c26af20ed4229edcf1340333c6e57282ff7b7d/pkg/rpc/context.go#L741

**Comment by jordanlewis** [comment]
The problem in these tests was the GRPC pings. GRPC was closing the underlying transport because the pings couldn't get through in our very short 3 second window that we've configured.

**Comment by asubiotto** [comment]
Yes, but I think that was caused by GC pauses. We saw individual pauses cause `SetupFlow` handler goroutines to not be scheduled for >1s, sometimes resulting the call taking multiple seconds, which is why I think the GRPC keepalives were failing (this might also be related to good ol' #31361). DistSQL streams starving other traffic from going through is definitely a problem though. I've been planning on writing tests to get a better idea of what happens in these cases. A separate DistSQL connection would definitely be nice to experiment with.

**Comment by petermattis** [comment]
@asubiotto Where are we seeing significant GC pauses? Actual GC pauses should be on the order of milliseconds or less. (I'm talking about pauses here, not how long GC runs for).

**Comment by jordanlewis** [comment]
We were seeing hundreds of milliseconds up to a second of actual pause during processing of these workloads. That GC pauses in Go are milliseconds are less is a misconception, as far as I can tell.

**Comment by petermattis** [comment]
@jordanlewis I have never seen a GC pause of hundreds of milliseconds in Go. Can you show your evidence? Is this reproducible? I'm pretty confident the Go team would be very interested in this.

**Comment by jordanlewis** [comment]
When you say "GC pause" are you talking about an STW pause or a single goroutine not getting scheduled for a certain amount of time during garbage collection?

I'm talking about seeing a goroutine not get scheduled for hundreds of milliseconds. Perhaps that's distinct from what you're talking about.

```
gc 26 @60.351s 4%: 0.048+596+0.37 ms clock, 0.19+312/590/0+1.5 ms cpu, 1680->1824->1646 MB, 1760 MB goal, 4 P
```

I saw that output combined with some instrumentation saying that a goroutine took 2 seconds to do a struct heap allocation. I can reproduce this with a small amount of effort.

**Comment by petermattis** [comment]
Yes, my definition of "GC pause" is the STW pause the freezes all goroutine activity. It is certainly possible that there is some other badness with goroutine scheduling, perhaps badness that gets exacerbated during GC when 25% of the CPU is consumed doing GC. There have also been "bugs" in previous releases of Go where there was overaggressive GC assist. It is certainly possible that problems still exist with GC assist, though it is interesting/suspicious that the place we're continually seeing badness is in sending the grpc keepalive messages.

**Comment by petermattis** [comment]
@jordan and @asubiotto: in your reproduce scenario do either of you happen to know whether it is the client or server side of the grpc connection was is closing due to inactivity (i.e. not receiving a keepalive response)?

**Comment by jordanlewis** [comment]
We saw instances of both. Both the client and the server send keepalives every 3 seconds and expect responses within that same 3 second duration (the network timeout constant we use all over the place for various different use cases).

**Comment by petermattis** [comment]
Hmm, ok. I was wondering if there was a specific client or server problem (as those are separate code paths in grpc).

Can you describe how to reproduce this problem?

**Comment by jordanlewis** [comment]
Follow the instructions here to restore the data. Once the the data is restored, instead of using `querylog`, use `querybench` with a file containing the queries in https://github.com/cockroachdb/cockroach/issues/34060. Run `querybench` with concurrency high - maybe 1000.
 https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/74777114/DRAFT+Testing+with+querylog+workload

**Comment by petermattis** [comment]
@jordanlewis Which queries in #34060? There are two queries in the original comment, but one of them specifies `@take` and `@skip` which isn't valid SQL. I'm probably doing something dumb, but it would helpful to have a file and an explicit `querybench` command line.

**Comment by petermattis** [comment]
Ok, with offline help from @jordanlewis I've reproduced badness. I haven't seen the `no inbound stream` error yet. But I managed to have cockroach run out of memory when running with `run querybench --concurrency=8`.

**Comment by petermattis** [comment]
@jordanlewis Hmm, actually the earlier crash seems to have been a panic:

```
* ERROR: ... Cannot convert nil datum to EncDatum
```

This is from the `WITH` query in #34060. The stack is:

```
goroutine 1509 [running]:
runtime/debug.Stack(0x3a21cc0, 0xc005e9a840, 0xc000000003)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x3a21cc0, 0xc005e9a840, 0xc000487300, 0x3118280, 0xc0059e64
e0, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:214 +0xa6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0008a1600, 0x3a21cc0, 0xc005e9a840, 0x2da9280
, 0x39dbea0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:715 +0x2dd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0008a1600, 0x3a21cc0, 0xc005e9a840)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:434 +0x61
panic(0x2da9280, 0x39dbea0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0x2000000001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:166 +0x27b
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*MemRowContainer).EncRow(0xc1f288e2c0, 0x296b2d, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/row_container.go:177 +0x161
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*hashMemRowIterator).computeKey(0xc005ebb620, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/hash_row_container.go:412 +0x4f
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*HashDiskBackedRowContainer).computeKeysForAllRowsIterators(0xc075168840, 0x3a21d80, 0xc00815f770)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/hash_row_container.go:1015 +0x8b
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*HashDiskBackedRowContainer).SpillToDisk(0xc075168840, 0x3a21d80, 0xc00815f770, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/hash_row_container.go:900 +0x15b
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).spillAllRowsToDisk(0xc075eb6800, 0xc072811ee0, 0xc00815f701)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:391 +0xc6
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).growMemAccount(0xc075eb6800, 0xc075eb6e70, 0x296b2e8, 0x3a21d80, 0xc00815f770)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:415 +0xab
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).processPartition(0xc075eb6800, 0x3a21d80, 0xc00815f770, 0xc006a8fa00, 0xc0ca38d200, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:567 +0x670
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).computeWindowFunctions(0xc075eb6800, 0x3a21d80, 0xc00815f770, 0xc006a8fa00, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:737 +0xbb3
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).emitRow(0xc075eb6800, 0x2, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:361 +0xa3
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).Next(0xc075eb6800, 0x0, 0x0, 0x0, 0xc006c0c528)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:279 +0x54
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashAggregator).accumulateRows(0xc0077c3400, 0x1, 0x0, 0x0, 0x0, 0xc006c0c528)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:471 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashAggregator).Next(0xc0077c3400, 0x0, 0x0, 0x0, 0xc006c0c528)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:700 +0x146
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).fill(0xc005ea9400, 0x3a21d80, 0xc00815f770, 0x32a35bb)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:308 +0x73
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).Start(0xc005ea9400, 0x3a21d80, 0xc00815f770, 0xc110662e50, 0x2da8500)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:289 +0xab
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc005ea9400, 0x3a21d80, 0xc00815f770)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:801 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc005e834a0, 0x3a21d80, 0xc00815f770, 0x340f830, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:627 +0x1e9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00004ea00, 0xc131c35f20, 0xc0c9d06990, 0xc0acc66818, 0xc005928000, 0xc0008a1a10, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8ad
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00004ea00, 0x3a21d80, 0xc006299b90, 0xc0008a1a10, 0xc131c35f20, 0xc0c9d06990, 0x3a23dc0, 0xc0063276d0, 0xc005928000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:840 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc0008a1600, 0x3a21d80, 0xc006299b90, 0xc0008a1950, 0x3, 0x7ff926dc82a0, 0xc007eca2c0, 0x1, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1121 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0008a1600, 0x3a21d80, 0xc006299b90, 0xc0008a1950, 0x7ff926dc82a0, 0xc007eca2c0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:957 +0x658
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0008a1600, 0x3a21d80, 0xc006299b90, 0x3a27980, 0xc007b2d480, 0xc0082fa1ae, 0x18b, 0x0, 0xc006641400, 0x2, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:459 +0xe03
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0008a1600, 0x3a21d80, 0xc006299b90, 0x3a27980, 0xc007b2d480, 0xc0082fa1ae, 0x18b, 0x0, 0xc006641400, 0x2, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:101 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0008a1600, 0x3a21cc0, 0xc005e9a840, 0xc000eb20f8, 0x5400, 0x15000, 0xc000eb2190, 0xc00b0ad810, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1248 +0x1418
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000a71340, 0x3a21cc0, 0xc005e9a840, 0xc0008a1600, 0x5400, 0x15000, 0xc000eb2190, 0xc00b0ad810, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:436 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00b0d9bb1, 0xc005d96a20, 0x3a21cc0, 0xc005e9a840, 0xc00b0ad810, 0xc000a71340, 0xc005e72400, 0x3a25980, 0xc005d96a00, 0xc005ea7c20, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:581 +0x21f
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:516 +0x17b
```

Is this a separate issue?

**Comment by petermattis** [comment]
@jordanlewis and @asubiotto given that `--concurrency=8` can bring a cluster to its knees, it strikes me that `--concurrency=1000` is just complete overload. Is that your expectation? We still shouldn't see grpc spuriously closing connections, but I just want to make sure I'm understanding what is being done to the system.

**Comment by asubiotto** [comment]
> given that --concurrency=8 can bring a cluster to its knees, it strikes me that --concurrency=1000 is just complete overload

Yeah, I don't think we tested with lower concurrency (at least I haven't), the initial goal was to reproduce some deadlocks we were seeing which `--concurrency=1000` did successfully, not to have a passing workload.

I believe we were also able to reproduce this badness by just using one query and removing window functions as a variable: `SELECT platform_id, user_id, username AS player_name, country_code, avatar_url, twitter, twitch, supporter_end_date, total_games_played AS matches, kills AS stat_value FROM bo4_careerstats AS tbl INNER JOIN bo4_account AS acttbl ON tbl.id = acttbl.id AS OF SYSTEM TIME '-1s' WHERE 1 = 1 AND acttbl.is_banned = false ORDER BY user_id LIMIT 100 OFFSET 100;`

**Comment by petermattis** [comment]
> I believe we were also able to reproduce this badness

Which badness are you referring to. The overload, or the `no inbound stream connection` error. I have been able to reproduce the `no inbound stream connection` error, but I'm not seeing any grpc connections being closed. Possible I'm just missing where that is happening right now.

**Comment by asubiotto** [comment]
> Which badness are you referring to. The overload, or the no inbound stream connection error.

Both. My conclusion was that the `no inbound stream connection` was caused by overload observed by `SetupFlow` RPCs not being scheduled in places for >1s (observed by peppering the handler with `time.Now` calls) and the gateway giving up waiting for connection establishment.

cc @jordanlewis re: GRPC connection closing, I think this is something he observed in his testing so will probably be better able to speak to it. My thinking here is that GRPC keepalives are not getting through because of the same overload issue and a connection is being closed. I would have disregarded this theory given that keepalives should only be sent when there is no traffic, but I've observed keepalives on a cluster under load (https://github.com/cockroachdb/cockroach/issues/31361#issuecomment-457873272). The symptom would still be `no inbound stream connection` errors if the connection is closed after sending the `SetupFlow` RPCs but before a stream can be established back to the gateway node. I think we'll probably spend some time reproducing this on our end to save you the back and forth.

**Comment by petermattis** [comment]
Looking at this again today, I'm not seeing any spurious grpc connection closing. What I am seeing is that the cluster is overloaded and a bad interaction between running with `1000` concurrent queries when `sql.distsql.max_running_flows` is set to `500`. In this workload, each query takes 10-20s to complete, making it really easy to run into situations where waiting for a flow running on one node times out waiting for an inbound stream. The first scenario that I've seen that causes this is simple overload resulting in an outbound stream setup happening just a little too late. The solution to this problem is admission control.

The second scenario is the bad interaction with the max concurrent flows. The flow scheduler only allows `sql.distsql.max_running_flows` to be running concurrently on a node. The workload in question creates a flow on every node for each query. So what happens if we run 1000 concurrent queries but only allow 500 concurrent flows per node? Badness. Consider the following scenario where there are already 499 concurrent queries running and we send 2 more queries:

1. `n1`: query A and B send out their setup flow requests to `n2` and `n3`
2. `n2`: sets up the flow for query A (now there are 500 concurrent flows on the node)
3. `n3`: sets up the flow for query B (now there are 500 concurrent flows on the node)
4. `n2`: queues the flow for query B because there are too many concurrent flows
5. `n3`: queues the flow for query A because there are too many concurrent flows

At this point, neither query A or query B will make progress until one of the other flows completes. But note that the queries in this workload take 10-20s to run. The most likely outcome for query A is that the flow setup on `n2` will time out after 10s (`sql.distsql.flow_stream_timeout`) waiting for inbound streams (this can also occur on `n1` which is running a local flow). A similar situation for query B.

Cc @jordanlewis, @andreimatei, @RaduBerinde, @ajwerner. Am I misunderstanding something about the way this is supposed to be working?

**Comment by andreimatei** [comment]
Yes, the 10s deadlock you describe is a known problem (#34229) - and the reason why I think that flow limit does more harm than good.
This issue is specifically about liveness failures, which we have seen at least once in an experiment involving heavy DistSQL usage.
