### ISSUE TITLE
sql: failure in TestStoreRangeRemoveDead 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#35551]
Found in https://teamcity.cockroachdb.com/viewLog.html?buildId=1168196&buildTypeId=Cockroach_UnitTests

```
I190308 17:23:45.381161 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:46.381755 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:47.382156 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:48.382681 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:49.383294 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:50.384151 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:51.384713 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:52.385862 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:53.386413 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:54.387334 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:55.388553 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:56.389117 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:57.389943 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:58.391114 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:23:59.391766 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:00.392484 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:01.393025 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:02.393514 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:03.394353 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:04.394957 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:05.395504 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:06.396100 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:07.396768 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:08.400594 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:09.401952 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:10.403274 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:11.403919 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:12.408922 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:13.409465 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:14.409973 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:15.410521 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:16.418444 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:17.419062 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:18.419688 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:19.420479 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:20.421386 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:21.422045 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:22.422679 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:23.423279 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:24.423893 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:25.424810 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:26.425368 63836 storage/client_raft_test.go:2944  SucceedsSoon: expected 5 replicas; have [(n1,s1):1]
I190308 17:24:27.425639 64756 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190308 17:24:27.425664 64690 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190308 17:24:27.425692 64755 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190308 17:24:27.425695 64690 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
I190308 17:24:27.425712 64688 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190308 17:24:27.425695 64687 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190308 17:24:27.425706 64756 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_gc_batcher
I190308 17:24:27.425733 64689 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190308 17:24:27.425757 64688 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
    client_raft_test.go:2944: condition failed to evaluate within 45s: expected 5 replicas; have [(n1,s1):1]
        goroutine 63836 [running]:
        runtime/debug.Stack(0xa7a358200, 0xc004f5a390, 0x345bec0)
        	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x34c20c0, 0xc0012c0a00, 0xc004f5a360)
        	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:49 +0x103
        github.com/cockroachdb/cockroach/pkg/storage_test.TestStoreRangeRemoveDead(0xc0012c0a00)
        	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_raft_test.go:2944 +0x580
        testing.tRunner(0xc0012c0a00, 0x2e149c8)
        	/usr/local/go/src/testing/testing.go:827 +0xbf
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:878 +0x35c
```

**Comment by knz** [comment]
cc @andreimatei @tbg for triage

**Comment by tbg** [comment]
34081

**Comment by tbg** [comment]
#34081
