### ISSUE TITLE
panic: flow: no bytes to release, current 43130, free 52748

### ISSUE THREAD

**Issue by hongbin0908** [cockroachdb/cockroach#35740]
[ct-closer] unable to move closed timestamp forward: not live
panic: flow: no bytes to release, current 43130, free 52748

goroutine 404725 [running]:
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc4330ce500, 0x30579a0, 0xc42a57de00, 0xce0c)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:629 +0x3c4
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc42ecab0f0, 0x30579a0, 0xc42a57de00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:513 +0x66
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowContainer).Close(0xc42ecab080, 0x30579a0, 0xc42a57de00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go:235 +0x7e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*diskBackedRowContainer).Close(0xc432299750, 0x30579a0, 0xc42a57de00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/row_container.go:405 +0x4e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*routerBase).start.func1(0x30579a0, 0xc42a57de00, 0xc42b525680, 0xc432299580, 0xc430c14188)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/routers.go:358 +0x2fb
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*routerBase).start
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/routers.go:278 +0x9f

**Comment by jordanlewis** [comment]
@hongbin0908 can you include more details from the log please? There should be more info above.

**Comment by hongbin0908** [comment]
W190313 13:21:13.694654 324269 storage/raft_transport.go:584  [n2] while processing outgoing Raft queue to node 8: rpc error: code = Unavailable desc = node waiting for init; /cockroach.storage.MultiRaft/RaftMessageBatch not available:
W190313 13:21:13.712812 324052 storage/raft_transport.go:584  [n2] while processing outgoing Raft queue to node 8: rpc error: code = Unavailable desc = node waiting for init; /cockroach.storage.MultiRaft/RaftMessageBatch not available:
W190313 13:21:13.794900 324254 storage/raft_transport.go:584  [n2] while processing outgoing Raft queue to node 8: rpc error: code = Unavailable desc = node waiting for init; /cockroach.storage.MultiRaft/RaftMessageBatch not available:
W190313 13:21:13.912792 323228 storage/raft_transport.go:584  [n2] while processing outgoing Raft queue to node 8: rpc error: code = Unavailable desc = node waiting for init; /cockroach.storage.MultiRaft/RaftMessageBatch not available:
W190313 13:21:14.112801 324235 storage/raft_transport.go:584  [n2] while processing outgoing Raft queue to node 8: rpc error: code = Unavailable desc = node waiting for init; /cockroach.storage.MultiRaft/RaftMessageBatch not available:
W190313 13:21:14.192464 324563 storage/raft_transport.go:584  [n2] while processing outgoing Raft queue to node 8: rpc error: code = Unavailable desc = node waiting for init; /cockroach.storage.MultiRaft/RaftMessageBatch not available:
W190313 13:21:14.312828 324054 storage/raft_transport.go:584  [n2] while processing outgoing Raft queue to node 8: rpc error: code = Unavailable desc = node waiting for init; /cockroach.storage.MultiRaft/RaftMessageBatch not available:
W190313 13:21:14.354099 323343 storage/raft_transport.go:584  [n2] while processing outgoing Raft queue to node 8: rpc error: code = Unavailable desc = node waiting for init; /cockroach.storage.MultiRaft/RaftMessageBatch not available:
W190313 13:21:15.599873 335 server/node.go:886  [n2,summaries] health alerts detected: {Alerts:[{StoreID:2 Category:METRICS Description:ranges.underreplicated Value:2081}]}
panic: flow: no bytes to release, current 103117, free 317440

goroutine 429051 [running]:
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc42b1930e0, 0x30579a0, 0xc450149200, 0x4d800)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:629 +0x3c4
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink(0xc4323500b8, 0x30579a0, 0xc450149200, 0x4d800)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:570 +0xa0
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).adjustBudget(0xc4323500a0, 0x30579a0, 0xc450149200)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:700 +0x86
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc4323500a0, 0x30579a0, 0xc450149200, 0x4d800)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:636 +0xd7
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc4314a8550, 0x30579a0, 0xc450149200)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:513 +0x66
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowContainer).Close(0xc4314a84e0, 0x30579a0, 0xc450149200)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go:235 +0x7e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).close(0xc4314a7b00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:613 +0x9e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newHashJoiner.func1(0x30579a0, 0xc450149200, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:173 +0x2a
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).moveToTrailingMeta(0xc4314a7b00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:693 +0x140
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).DrainHelper(0xc4314a7b00, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:640 +0x14f
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).readProbeSide(0xc4314a7b00, 0x3, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:463 +0x4d9
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).Next(0xc4314a7b00, 0xc438327300, 0x19, 0x19, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:247 +0x281
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x30579a0, 0xc450149200, 0x30608e0, 0xc4314a7b00, 0x30349e0, 0xc42ff9dc00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:172 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc4314a7b00, 0x30579a0, 0xc450149200, 0xc42e3ae188)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:731 +0x98
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).startInternal
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:558 +0x308
@jordanlewis

**Comment by jordanlewis** [comment]
What version of Cockroach are you running? Were you running any queries with text manipulation builtins like `concat`? there's a known bug around those.

**Comment by jordanlewis** [comment]
See #34935.

**Comment by hongbin0908** [comment]
2.1.4
@jordanlewis

**Comment by hongbin0908** [comment]
2019-03-14 22:55:19 | WARNING | batch [1/251/0] commit took 628.14231ms (>500ms): goroutine 4408 [running]: runtime/debug.Stack(0xeb92247, 0xed41cd2d7, 0x0) 	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7 github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc49c3a2b40, 0x0, 0x1, 0xc46f8da208) 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1911 +0x1b3 github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc49c3a2b40, 0xed41cd201, 0x0, 0x0) 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1827 +0x7ed github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc43bfef200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...) 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4233 +0x5b1 github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x3057a60, 0xc464fe9530, 0xc43bfef200, 0x3057a60) 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3873 +0x109 github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc420656580, 0x3057a60, 0xc464fe9530, 0xc42023cd00, 0xc48ae21ed0, 0x0) 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3519 +0x135 github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc420656580, 0x3057a60, 0xc447f4ac90, 0xb6ba) 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3861 +0x229 github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420025d80, 0x3057a60, 0xc447f4ac90) 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:225 +0x21b github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x3057a60, 0xc447f4ac90) 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x3e github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc43eb8b7b0, 0xc420c76000, 0xc43eb8b7a0) 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0xe9 created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xad | storage/engine/rocksdb.go:1910
-- | -- | -- | --
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.6s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:19 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:55:31 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:51736": EOF | vendor/google.golang.org/grpc/server.go:603
2019-03-14 22:55:53 | ERROR | [n2,s6,store-rebalancer,r63461/2:/Table/181/2/2019-03-1{4…-5…}] unable to relocate range to [n2,s9 n1,s5 n6,s26]: none of the remaining targets [(n2,s9):?] are legal additions to [(n6,s26):1 (n2,s6):2 (n1,s5):3] | storage/store_rebalancer.go:326
2019-03-14 22:56:01 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:51888": EOF | vendor/google.golang.org/grpc/server.go:603
2019-03-14 22:56:03 | WARNING | [n2,s8] handle raft ready: 0.6s [processed=0] | storage/store.go:3931
2019-03-14 22:56:03 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:56:03 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:56:03 | WARNING | [n2,s8] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:56:03 | WARNING | [n2,s7] handle raft ready: 0.7s [processed=0] | storage/store.go:3931
2019-03-14 22:56:03 | WARNING | [n2,s7] handle raft ready: 0.7s [processed=0] | storage/store.go:3931
2019-03-14 22:56:03 | WARNING | [n2,s7] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:56:03 | WARNING | [n2,s7] handle raft ready: 0.5s [processed=0] | storage/store.go:3931
2019-03-14 22:56:13 | ERROR | [n2,s6,store-rebalancer,r62283/2:/Table/181/2/2019-03-14T1…] unable to relocate range to [n2,s9 n1,s5 n6,s26]: none of the remaining targets [(n2,s9):?] are legal additions to [(n6,s26):1 (n2,s6):2 (n1,s5):3] | storage/store_rebalancer.go:326
2019-03-14 22:56:13 | ERROR | [n2,s6,store-rebalancer,r32403/1:/Table/181/1/"c{9b953…-ab71c…}] unable to relocate range to [n2,s10 n4,s19 n1,s3]: none of the remaining targets [(n2,s10):? (n1,s3):?] are legal additions to [(n2,s6):1 (n4,s19):5 (n1,s2):3] | storage/store_rebalancer.go:326
2019-03-14 22:56:13 | ERROR | [n2,s6,store-rebalancer,r41651/1:/Table/153/1/124{8921…-9488…}] unable to relocate range to [n2,s9 n1,s1 n4,s19]: none of the remaining targets [(n2,s9):?] are legal additions to [(n2,s6):1 (n4,s19):2 (n1,s1):4] | storage/store_rebalancer.go:326
2019-03-14 22:56:31 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:52142": EOF | vendor/google.golang.org/grpc/server.go:603
2019-03-14 22:57:01 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:52298": EOF | vendor/google.golang.org/grpc/server.go:603
2019-03-14 22:57:31 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:52552": EOF | vendor/google.golang.org/grpc/server.go:603
2019-03-14 22:58:01 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:52714": EOF | vendor/google.golang.org/grpc/server.go:603
2019-03-14 22:58:31 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:52950": EOF | vendor/google.golang.org/grpc/server.go:603
2019-03-14 22:58:32 | WARNING | [n2,s9] handle raft ready: 0.6s [processed=0] | storage/store.go:3931
2019-03-14 22:59:01 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:53114": EOF | vendor/google.golang.org/grpc/server.go:603
2019-03-14 22:59:31 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:53366": EOF | vendor/google.golang.org/grpc/server.go:603
2019-03-14 22:59:39 | ERROR | [n2,replicate,s9,r17227/2:/Table/186/2/2019-02-19T10:…] failed to replicate after 5 retries | storage/queue.go:846
2019-03-14 22:59:48 | WARNING | [n2,summaries] health alerts detected: {Alerts:[{StoreID:9 Category:METRICS Description:queue.replicate.process.failure Value:1}]} | server/node.go:886
2019-03-14 23:00:01 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:53534": EOF | vendor/google.golang.org/grpc/server.go:603
2019-03-14 23:00:33 | WARNING | grpc: Server.Serve failed to complete security handshake from "127.0.0.1:53774": EOF panic: flow: no bytes to release, current 111880, free 256000  goroutine 774362 [running]: github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc45329eb40, 0x30579a0, 0xc4642f6780, 0x3e800) 	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:629 +0x3c4 github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink(0xc45329f918, 0x30579a0, 0xc4642f6780, 0x3e800) 	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:570 +0xa0 github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).adjustBudget(0xc45329f900, 0x30579a0, 0xc4642f6780) 	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:700 +0x86 github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc45329f900, 0x30579a0, 0xc4642f6780, 0x32000) 	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:636 +0xd7 github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc465904550, 0x30579a0, 0xc4642f6780) 	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:513 +0x66 github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowContainer).Close(0xc4659044e0, 0x30579a0, 0xc4642f6780) 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go:235 +0x7e github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).close(0xc465903b00) 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:613 +0x9e github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newHashJoiner.func1(0x30579a0, 0xc4642f6780, 0x0, 0x0, 0x0) 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:173 +0x2a github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).moveToTrailingMeta(0xc465903b00) 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:693 +0x140 github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).DrainHelper(0xc465903b00, 0x0) 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:640 +0x14f github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).readProbeSide(0xc465903b00, 0x19, 0x19, 0x0, 0x0, 0x19) 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:463 +0x4d9 github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).Next(0xc465903b00, 0xc464a0e600, 0x19, 0x19, 0x0) 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:247 +0x281 github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x30579a0, 0xc4642f6780, 0x30608e0, 0xc465903b00, 0x30349e0, 0xc45d215180) 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:172 +0x35 github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc465903b00, 0x30579a0, 0xc4642f6780, 0xc469734188) 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:731 +0x98 created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).startInternal 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:558 +0x308

@jordanlewis may you read this logs?

**Comment by jordanlewis** [comment]
Try again on the newest version of 2.1 please.
