### ISSUE TITLE
server: crash when CTRL-C during startup

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#35753]
Got this crash after I sent a SIGINT to a node while, I think, that node was still starting up. This was a 3 node cluster, and another node was already down (although that probably doesn't matter).
@vivekmenezes is this you?

```
F190314 20:02:00.816669 24 server/server.go:1646  [n2] failed to get list of completed migrations: aborted during DistSender.Send: context canceled
goroutine 24 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc00005fb00, 0xc00005fb60, 0x8d19a00, 0x10)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1018 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x92e8c00, 0xc000000004, 0x8d19a2e, 0x10, 0x66e, 0xc0057b0690, 0x61)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:874 +0x95a
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x74a5e20, 0xc0006365d0, 0xc000000004, 0x2, 0x0, 0x0, 0xc000caed10, 0x1, 0x1)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2d5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x74a5e20, 0xc0006365d0, 0x1, 0xc000000004, 0x0, 0x0, 0xc000caed10, 0x1, 0x1)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x74a5e20, 0xc0006365d0, 0xc000caed10, 0x1, 0x1)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:191 +0x6c
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start(0xc0008a5c00, 0x74a5e20, 0xc0006365d0, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1646 +0x2c53
github.com/cockroachdb/cockroach/pkg/cli.runStart.func3.2(0xc0004cc240, 0xc00000e0c8, 0xc0002a27d0, 0x74a5e20, 0xc000808720, 0x48afaa8, 0xed41caa2f, 0x0, 0x0, 0x0)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:611 +0x10e
github.com/cockroachdb/cockroach/pkg/cli.runStart.func3(0xc00000e0c8, 0x74a5e20, 0xc000808720, 0x74dbda0, 0xc000818000, 0xc0004cc240, 0xc0002a27d0, 0x48afaa8, 0xed41caa2f, 0x0, ...)
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:716 +0x11c
created by github.com/cockroachdb/cockroach/pkg/cli.runStart
	/Users/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:567 +0x710
```

**Comment by jordanlewis** [comment]
There's lots of `Fatal` errors in the server start sequence - this one doesn't seem unique. Things crash on purpose during startup if they don't get what they need, it seems. Closing.

**Comment by nvanbenschoten** [comment]
We actually just saw this again in `acceptance/rapid-restart` (https://github.com/cockroachdb/cockroach/issues/19579), so I'm going to re-open. Fixing this for real should be straightforward.

**Comment by jordanlewis** [comment]
Heh, okay. But do you see what I mean about there being a ton of `Fatal` errors scattered throughout server startup? Should we fix all of those? I don't quite understand what the desired outcome is here.

**Comment by nvanbenschoten** [comment]
Yep, I see what you mean. I don't think any of those need to be fatals. They can all just return an error and let that be handled by the caller.
