### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by idubrov** [cockroachdb/cockroach#35780]
**Describe the problem**

I have a piece of Rust code that runs two SQL statements. These two statements, when executed, cause CockroachDB to crash.

**To Reproduce**

Unfortunately, I wasn't able to reproduce it outside of our code.

Table structure:
```
CREATE TABLE sample(key STRING NOT NULL, value BOOL NOT NULL);
```

Two statements (they are executed inside single transaction, one after another):

```
UPDATE sample SET value = true WHERE key NOT IN ('123') RETURNING NOTHING;
INSERT INTO sample(key) VALUES ('123') ON CONFLICT (key) DO UPDATE SET value = false WHERE value = true;
```

There is an error in the second statement (in WHERE clause, should be `sample.value`) which, I think, triggers the crash. If this error is fixed, everything works fine.

**Additional data / screenshots**

From logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4960ace]

goroutine 314 [running]:
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).ID(0x0, 0x0, 0x0)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:163 +0x2e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).synchronizeParallelStmts(0xc005ee3500, 0x6d19900, 0xc005f0e200, 0x0, 0x0)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1631 +0xda
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close(0xc005ee3500, 0x6d19900, 0xc005f0e200, 0x0)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:673 +0xb3
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc005ee3500, 0x6d19900, 0xc005f0e200, 0x0, 0x0)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:654 +0x70
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc005ee3500, 0x6d19900, 0xc005f0e200)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0007b9ef0, 0x6d19900, 0xc005f0e200, 0xc005ee3500, 0x5400, 0x15000, 0xc0009fca70, 0xc0003e3d40, 0x0, 0x0)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xe9
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc0007b9ef0, 0x6d19900, 0xc005f0e200, 0xc005ee3500, 0x5400, 0x15000, 0xc0009fca70, 0xc0003e3d40, 0xc0003e3d50, 0xc005ba3d14)
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:313 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /private/tmp/cockroach-20190219-43186-1p8lwnc/cockroach-v2.1.5/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:312 +0x1018
```

**Environment:**
 - CockroachDB version: `CCL v2.1.5 @ 2019/02/19 16:38:43 (go1.11.5)`
 - Server OS: macOS
 - Client app: Rust postgres driver

**Comment by jordanlewis** [comment]
Hi @idubrov, thanks for the report. You can work around this problem by removing use of `RETURNING NOTHING`, which we're going to remove soon anyway. The performance benefits of `RETURNING NOTHING` are getting pulled into core CockroachDB, so you won't need to use it to get optimal performance.

cc @nvanbenschoten
