### ISSUE TITLE
distsql: panic in rowcontainer

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#35970]
Found via sqlsmith.

```
CREATE TABLE table0 (
    col0 INET NULL,
    col1 OID NOT NULL,
    col2 INT8[] NULL,
    col3 OID NULL,
    col4 NAME NOT NULL,
    col5 INT8 NULL,
    CONSTRAINT "primary" PRIMARY KEY (col4 ASC),
    INDEX table0_col3_col1_col4_idx (col3 ASC, col1 ASC, col4 ASC),
    UNIQUE INDEX table0_col4_col0_col3_col1_col5_key (col4 DESC, col0 ASC, col3 ASC, col1 ASC, col5 ASC),
    UNIQUE INDEX table0_col4_key (col4 DESC),
    FAMILY fam0 (col1, col4),
    FAMILY fam1 (col0, col2),
    FAMILY fam2 (col3),
    FAMILY fam3 (col5)
);

insert into table0 values ('18.207.242.214/21', 3756592763, '{-9012748206074517837,2135002264725534957,7062546603827504816}'::int8[], 815128657, 'RbWl', null);

set sql_safe_updates = false;

SELECT
    tab_3154.col1 AS col_8084,
    (ret_1055::DATE - ret_1064::INT8)::DATE + ret_1056::INTERVAL AS col_8085,
    tab_3154.col3 AS col_8086,
    tab_3154.col0 AS col_8087,
    ret_1054 AS col_8088,
    ret_1062 AS col_8089,
    ret_1053 AS col_8090,
    ret_1058 AS col_8091,
    ret_1058 AS col_8092,
    ret_1058 AS col_8093
FROM
    table0 AS tab_3154,
    [
        UPDATE
            table0 AS tab_3155
        SET
            col2 = tab_3155.col2
        ORDER BY
            tab_3155.col5 DESC
        LIMIT
            14:::INT8
        RETURNING
            col5 AS ret_1053,
            NULL AS ret_1054,
            '1980-12-17':::DATE AS ret_1055,
            '-52 years -7 mons -237 days -21:38:04.946374':::INTERVAL AS ret_1056,
            B'11110101010110111100100001000011011111001011010110111011011111111111111010000010101'
                AS ret_1057,
            'Jl,':::STRING AS ret_1058,
            true AS ret_1059,
            e'\\\\xafd77355':::BYTES AS ret_1060,
            col0 AS ret_1061,
            (
                (-0.49306941088845424):::FLOAT8::FLOAT8
                - (
                        0.699693567492208::FLOAT8
                        ^ (
                                (-1.0193603544212397):::FLOAT8::FLOAT8
                                // (
                                        (
                                            (-0.2757256427579069):::FLOAT8::FLOAT8
                                            * (
                                                    (-0.5669869225119845):::FLOAT8::FLOAT8
                                                    * NULL::FLOAT8
                                                )::FLOAT8
                                        )::FLOAT8
                                        + (
                                                (
                                                    (
                                                        (
                                                            (
                                                                NULL::FLOAT8
                                                                // 0.2817173016993893::FLOAT8
                                                            )::FLOAT8
                                                            // 0.001090723010643474::FLOAT8
                                                        )::FLOAT8
                                                        - (-0.19572720555971812):::FLOAT8::FLOAT8
                                                    )::FLOAT8
                                                    * (-0.16159238961203115):::FLOAT8::FLOAT8
                                                )::FLOAT8
                                                ^ 0.016038642268222936::FLOAT8
                                            )::FLOAT8
                                    )::FLOAT8
                            )::FLOAT8
                    )::FLOAT8
            )::FLOAT8
            - NULL::FLOAT8
                AS ret_1062,
            '1995-12-17':::DATE AS ret_1063,
            3439264210986109603::INT8 * col5::INT8 AS ret_1064
    ]
ORDER BY
    ret_1059 ASC
LIMIT
98:::INT8;
```

```
panic while executing 1 statements: SELECT _._ AS _, (_::DATE - _::INT8)::DATE + _::INTERVAL AS _, _._ AS _, _._ AS _, _ AS _, _ AS _, _ AS _, _ AS _, _ AS _, _ AS _ FROM _ AS _, [UPDATE _ AS _ SET _ = _._ ORDER BY _._ DESC LIMIT _:::INT8 RETURNING _ AS _, _ AS _,
_:::DATE AS _, _:::INTERVAL AS _, _ AS _, _:::STRING AS _, _ AS _, _:::BYTES AS _, _ AS _, ((_):::FLOAT8::FLOAT8 - (_::FLOAT8 ^ ((_):::FLOAT8::FLOAT8 // (((_):::FLOAT8::FLOAT8 * ((_):::FLOAT8::FLOAT8 * _::FLOAT8)::FLOAT8)::FLOAT8 + (((((_::FLOAT8 // _::FLOAT8)::FLO
AT8 // _::FLOAT8)::FLOAT8 - (_):::FLOAT8::FLOAT8)::FLOAT8 * (_):::FLOAT8::FLOAT8)::FLOAT8 ^ _::FLOAT8)::FLOAT8)::FLOAT8)::FLOAT8)::FLOAT8)::FLOAT8 - _::FLOAT8 AS _, _:::DATE AS _, _::INT8 * _::INT8 AS _] ORDER BY _ ASC LIMIT _:::INT8

goroutine 128 [running]:
runtime/debug.Stack(0x7454d20, 0xc0054fd080, 0xc000000003)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x7454d20, 0xc0054fd080, 0xc0000e9300, 0x6b5d420, 0xc006750cc0, 0x1)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:226 +0xa6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00568b600, 0x7454d20, 0xc0054fd080, 0x68f9260, 0x924ca60)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:707 +0x2dd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc00568b600, 0x7454d20, 0xc0054fd080)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:426 +0x61
panic(0x68f9260, 0x924ca60)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*RowContainer).rowSize(0xc0066c5b00, 0xc0066751a0, 0x6, 0x6, 0xc0066f58c0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/datum_row_container.go:202 +0x61
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*RowContainer).AddRow(0xc0066c5b00, 0x7454de0, 0xc0066f58c0, 0xc0066751a0, 0x6, 0x6, 0xc0066cac90, 0x1, 0x1, 0x0, ...)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/datum_row_container.go:227 +0x7c
github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).processSourceRow(0xc0062e4000, 0x7454de0, 0xc0066f58c0, 0xc00745c000, 0xc00568b950, 0xc006715340, 0x4, 0x4, 0x4e7feb8, 0x40043e9)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go:704 +0x8f4
github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).BatchedNext(0xc0062e4000, 0x7454de0, 0xc0066f58c0, 0xc00745c000, 0xc00568b950, 0xc00700f801, 0xc00673ed18, 0x4010016)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go:546 +0x154
github.com/cockroachdb/cockroach/pkg/sql.(*serializeNode).Next(0xc0066f5530, 0x7454de0, 0xc0066f58c0, 0xc00745c000, 0xc00568b950, 0xc00673ee00, 0x4aa9476, 0x689c2c0)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:123 +0xa1
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc00671e500, 0x0, 0x0, 0x0, 0x6)
        /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:178 +0x447
```

**Comment by jordanlewis** [comment]
The problem here is that `updateNode` is producing a row with some `nil` values inside of it, which is not permitted. Not sure why this is happening yet.

**Comment by yuzefovich** [comment]
Reduced reproduction is
```
CREATE TABLE table0 (
    col0 INET NULL,
    col1 OID NOT NULL,
    col2 INT8[] NULL,
    col3 OID NULL,
    col4 NAME NOT NULL,
    col5 INT8 NULL,
    CONSTRAINT "primary" PRIMARY KEY (col4 ASC),
    INDEX table0_col3_col1_col4_idx (col3 ASC, col1 ASC, col4 ASC),
    CONSTRAINT table0_col4_col0_col3_col1_col5_key UNIQUE (col4 DESC, col0 ASC, col3 ASC, col1 ASC, col5 ASC),
    CONSTRAINT table0_col4_key UNIQUE (col4 DESC),
    FAMILY fam0 (col1, col4),
    FAMILY fam1 (col0, col2),
    FAMILY fam2 (col3),
    FAMILY fam3 (col5)
);

INSERT
INTO
    table0
VALUES
    (
        '18.207.242.214/21',
        3756592763,
        '{-9012748206074517837,2135002264725534957,7062546603827504816}'::INT8[],
        815128657,
        'RbWl',
        NULL
    );

SET sql_safe_updates = false;

UPDATE
    table0 AS tab_3155
SET
    col2 = tab_3155.col2
RETURNING
    col5 AS ret_1053;
```
Note that this panic doesn't occur with the optimizer off. I tried to trace where the code to see where the divergence between CBO and HP happens and got to https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/update.go#L602. With CBO, `len(sourceVals) == 4` and `FetchCols == 3` whereas with HP `len(sourceVals) == 6` and `FetchCols == 6`, I think the latter is correct but don't know where to go next.

**Comment by justinj** [comment]
@yuzefovich thanks for doing that investigation! Sounds indeed like it might be an optimizer bug, I can investigate further.
