### ISSUE TITLE
sql: psychopg: investigate how `'infinity'::timestamp` is presented

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#36116]
Need to cross-check what PG actually sends out on the wire.  Looks like the python adapter doesn't like the value it's being asked to reconstitute into the in-memory representation.

```
ERROR: test_adapt_infinity_tz (psycopg2.tests.test_dates.DatetimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/data1/psycopg/build/lib.2.7/psycopg2/tests/test_dates.py", line 403, in test_adapt_infinity_tz
    t = self.execute("select 'infinity'::timestamp")
  File "/mnt/data1/psycopg/build/lib.2.7/psycopg2/tests/test_dates.py", line 40, in execute
    return self.curs.fetchone()[0]
ValueError: year is out of range
```

**Comment by jordanlewis** [comment]
Hey @mjibson, is this affected by your recent date work? I assume not, since it's timestamps, but just thought I'd ask.

**Comment by mjibson** [comment]
Correct, not related.

**Comment by rafiss** [comment]
superseded by https://github.com/cockroachdb/cockroach/issues/41564
