### ISSUE TITLE
Failed tests (10599): TestGossip{Peerings,Restart}: newRaft: applied(10) is out of range (...)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3611]
The following test appears to have failed:

[#10599](https://circleci.com/gh/cockroachdb/cockroach/10599):

```
I0105 14:29:46.233607 1 server/context.go:181  initialized 1 storage engine(s)
I0105 14:29:46.233663 1 cli/start.go:176  starting cockroach cluster
I0105 14:29:46.236317 1 storage/engine/rocksdb.go:106  opening rocksdb instance at "/data2.0"
I0105 14:29:46.237581 1 gossip/gossip.go:738  starting client to roach0.local:26257
E0105 14:29:46.253311 1 raft/log.go:205  [group 3] applied(10) is out of range [prevApplied(27), committed(30)]
panic: [group 3] applied(10) is out of range [prevApplied(27), committed(30)]

goroutine 1 [running]:
github.com/cockroachdb/cockroach/storage.(*raftLogger).Panicf(0xc8203e0b00, 0x160a000, 0x3c, 0xc8203cfaa0, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/storage/raft.go:124 +0x1a2
github.com/coreos/etcd/raft.(*raftLog).appliedTo(0xc8203e80e0, 0xa)
	/go/src/github.com/coreos/etcd/raft/log.go:205 +0x1f7
github.com/coreos/etcd/raft.newRaft(0xc820256828, 0x7f8cd956e7e8)
	/go/src/github.com/coreos/etcd/raft/raft.go:224 +0x939
github.com/coreos/etcd/raft.NewRawNode(0xc820256828, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/rawnode.go:76 +0xba
I0105 14:29:46.224917 18465 acceptance/gossip_peerings_test.go:180  waiting for gossip to be connected
E0105 14:29:46.225906 18465 acceptance/cluster/localcluster.go:406  node=2 status=restart
E0105 14:29:46.313702 18465 acceptance/cluster/localcluster.go:406  node=2 status=die
I0105 14:30:06.351488 18465 acceptance/cluster/localcluster.go:533  stopping
I0105 14:30:06.910577 18465 acceptance/cluster/localcluster.go:572  node 2: stderr at /tmp/circle-artifacts.Tft7Deb/acceptance/roach2.local/stderr.2016-01-05T14_30_06Z.log
--- FAIL: TestGossipRestart (35.99s)
	testing.go:145: acceptance/gossip_peerings_test.go:68: condition failed to evaluate within 20s: acceptance/gossip_peerings_test.go:63: node 0: acceptance/gossip_peerings_test.go:82: expected 3 peers, found 2
	localcluster.go:510: unexpected extra event &{2 die} (after [{0 die} {1 die} {2 die} {0 restart} {1 restart} {2 restart}])
=== RUN   TestPut
I0105 14:30:07.878445 18465 acceptance/cluster/localcluster.go:213  started docker-spy: 172.17.0.33
I0105 14:30:07.878470 18465 acceptance/cluster/localcluster.go:220  initializing cluster
I0105 14:30:09.021700 18465 acceptance/cluster/localcluster.go:331  creating ca (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.919478579
I0105 14:30:09.062160 18465 acceptance/cluster/localcluster.go:336  creating node (1024bit) certs in: /home/ubuntu/cockroach/.localcluster.certs.919478579
I0105 14:30:10.468895 18465 acceptance/cluster/localcluster.go:389  *** started roach0.local ***
  ui:    https://0.0.0.0:32790
  trace: https://0.0.0.0:32790/debug/requests
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:32: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	main_test.go:56: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
ping @bdarnell. This is, at least in that location, new with the raft changes.

**Comment by tschottdorf** [comment]
same happens on TestGossipPeerings https://circle-artifacts.com/gh/tschottdorf/cockroach/1940/artifacts/0/tmp/circle-artifacts.XxI2Pbj/acceptance/TestGossipPeerings/roach1.local/stderr.2016-01-06T10_57_58Z.log
