### ISSUE TITLE
Failed tests (10606): TestGossipCullNetwork: no culling in 10s

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3618]
The following test appears to have failed:

[#10606](https://circleci.com/gh/cockroachdb/cockroach/10606):

```
I0105 15:49:41.050779 513 gossip/server.go:138  received map[node:2:value:<raw_bytes:"\330\376\205f\003\010\002\022\022\n\003tcp\022\013127.0.0.1:0\032\000" timestamp:<wall_time:1452008981029680057 logical:0 > > orig_stamp:1452008981029697332 ttl_stamp:9223372036854775807 hops:1 node_id:2 peer_id:2 ] from node 1 (1 fresh)
I0105 15:49:41.050879 513 gossip/server.go:211  @3: distantHops: 2 from 2
I0105 15:49:41.051130 513 gossip/gossip.go:641  closing least useful client to node 3 to tighten network graph
I0105 15:49:41.051254 513 gossip/client.go:161  sent 1 info(s) to node 3
W0105 15:49:41.052269 513 rpc/server.go:309  rpc: write response failed: write tcp 127.0.0.1:55015->127.0.0.1:50186: write: broken pipe
--- FAIL: TestGossipCullNetwork (10.11s)
	<autogenerated>:32: gossip/gossip_test.go:141: condition failed to evaluate within 10s: no network culling occurred
=== RUN   TestExpired
--- PASS: TestExpired (0.00s)
=== RUN   TestIsFresh
--- PASS: TestIsFresh (0.00s)
=== RUN   TestZeroDuration
--- PASS: TestZeroDuration (0.00s)
=== RUN   TestNewInfo
--- PASS: TestNewInfo (0.00s)
=== RUN   TestInfoStoreGetInfo
--
I0105 15:49:51.864636 513 gossip/client.go:75  closing client to node 2 (127.0.0.1:39065): gossip/client.go:251: client closed
I0105 15:49:51.865201 513 gossip/client.go:75  closing client to node 4 (127.0.0.1:33522): read tcp 127.0.0.1:49050->127.0.0.1:33522: use of closed network connection
I0105 15:49:51.865314 513 gossip/client.go:75  closing client to node 1 (127.0.0.1:59253): gossip/client.go:251: client closed
I0105 15:49:51.865476 513 gossip/client.go:75  closing client to node 4 (127.0.0.1:33522): gossip/client.go:251: client closed
--- PASS: TestConvergence (0.62s)
FAIL
FAIL	github.com/cockroachdb/cockroach/gossip	11.005s
=== RUN   TestParseResolverSpec
--- PASS: TestParseResolverSpec (0.00s)
=== RUN   TestGetAddress
--- PASS: TestGetAddress (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/gossip/resolver	1.024s
?   	github.com/cockroachdb/cockroach/gossip/simulation	[no test files]
=== RUN   TestKeySorting
--- PASS: TestKeySorting (0.00s)
=== RUN   TestMakeKey
--
W0105 15:55:11.609329 760 kv/dist_sender.go:572  no replica node addresses available via gossip
I0105 15:55:45.864953 760 kv/range_cache.go:128  lookup range descriptor: key=/Table/501/0
I0105 15:55:45.865108 760 kv/range_cache.go:128  lookup range descriptor: key=/Meta2/"\xf9\x01\xf5\x88"
I0105 15:55:45.865276 760 kv/replica_slice.go:54  node 1 is not gossiped: gossip/gossip.go:222: unable to lookup descriptor for node 1: gossip/gossip.go:319: key "node:1" does not exist or has expired
W0105 15:55:45.865363 760 kv/dist_sender.go:572  no replica node addresses available via gossip
panic: test timed out after 5m0s

goroutine 1814 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x1a46980, 0x2107e40, 0x1f, 0x1f, 0x16ce501)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/go/src/github.com/cockroachdb/cockroach/util/feed.go:61 +0x1b6
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820218bd0, 0xc820528880)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70
FAIL	github.com/cockroachdb/cockroach/server	300.072s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.01s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.03s)
=== RUN   TestRuntimeStatRecorder
I0105 15:50:58.012446 766 server/status/runtime.go:137  runtime stats: 11 goroutines, 3.04MiB active, 50000000.00cgo/sec, 670550.00/260770.00 %(u/s)time, 11625.90 %gc (2x)
--- PASS: TestRuntimeStatRecorder (0.01s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.00s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
#3620
