### ISSUE TITLE
sql: panic: conn: no bytes to release, current 0, free 107520

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#36190]
Found while running sqlsmith. Not sure what queries were running at the time.

```
panic: conn: no bytes to release, current 0, free 107520

goroutine 27568 [running]:
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc0007935a8, 0x44b1fa0, 0xc0021db5c0, 0x1a400)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:628 +0x4a4
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc001fdd4a0, 0x44b1fa0, 0xc0021db5c0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:510 +0xc9
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1.1(0xc001fdd4a0, 0x44b1fa0, 0xc0021db5c0, 0xc005214d30, 0xc0006ba000, 0xc00ace9f50, 0xc00387e900, 0xc00ace9f47, 0x44b5920, 0xc001fdd480, ...)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:520 +0x9f
panic(0x33beb40, 0xc0096520c0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc0007935a8, 0x44b1fa0, 0xc0021db5c0, 0x1a400)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:628 +0x4a4
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc000d33e58, 0x44b1fa0, 0xc0021db5c0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:510 +0xc9
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Clear(0xc000d33e58, 0x44b1fa0, 0xc0021db5c0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:497 +0x6c
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc000d33e00, 0x44b1fa0, 0xc0021db5c0, 0x1)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:417 +0x118
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(0xc000d33e00, 0x44b1fa0, 0xc0021db5c0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:383 +0x52
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close(0xc002b0e000, 0x44b1fa0, 0xc0021db5c0, 0x0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:782 +0x333
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc002b0e000, 0x44b1fa0, 0xc0021db5c0, 0x0, 0x0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:724 +0x81
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc002b0e000, 0x44b1fa0, 0xc0021db5c0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:434 +0x6f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0006ba000, 0x44b1fa0, 0xc0021db5c0, 0xc002b0e000, 0x5400, 0x15000, 0xc0007935a8, 0xc005214d30, 0x0, 0x0)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:436 +0x10b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc001fdd4a0, 0x44b1fa0, 0xc0021db5c0, 0xc005214d30, 0xc0006ba000, 0xc00387e900, 0x44b5920, 0xc001fdd480, 0xc009d743c0, 0x0, ...)
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:577 +0x217
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:513 +0x1a9
```

**Comment by andreimatei** [comment]
SHA for posterity ff7ccb5bfb4980ddbb3e18e55a591a42b1fd8c03.

The crash is on a session closing it's monitor. As things are I don't think this is actionable. But if this happens again we could add a bunch of instrumentation to the memory accounts and such to trace it.

**Comment by jordanlewis** [comment]
I was going to say, this is somewhat of a white whale issue. very interested in better repros of it. as it is, i don't understand why it's not happening on the main query path. are there things that allocate on the session that aren't allocated by queries?

**Comment by mjibson** [comment]
Bam.

```
CREATE TABLE t (
    _bool BOOL,
    _bytes BYTES,
    _date DATE,
    _decimal DECIMAL,
    _float4 FLOAT4,
    _float8 FLOAT8,
    _inet INET,
    _int4 INT4,
    _int8 INT8,
    _interval INTERVAL,
    _jsonb JSONB,
    _string STRING,
    _time TIME,
    _timestamp TIMESTAMP,
    _timestamptz TIMESTAMPTZ,
    _uuid UUID
);

INSERT INTO t DEFAULT VALUES;

SELECT
    CASE WHEN false THEN 2240361376:::OID ELSE NULL END AS col_85221,
    '1970-01-03 01:56:16.000547+00:00':::TIMESTAMP AS col_85222
FROM
    defaultdb.public.t AS tab_27927
WHERE
    EXISTS(
        SELECT
            tab_27929._string AS col_85223
        FROM
            defaultdb.public.t AS tab_27928,
            defaultdb.public.t AS tab_27929,
            defaultdb.public.t AS tab_27930
            RIGHT JOIN defaultdb.public.t AS tab_27931
            ON
                NOT
                    (
                        tab_27927._float8
                        IN (
                                CASE
                                WHEN NULL
                                THEN div(
                                    tab_27927._float4::FLOAT8,
                                    tab_27927._float4::FLOAT8
                                )::FLOAT8
                                ELSE tab_27927._float4
                                END,
                                tab_27927._float4,
                                tab_27927._float8::FLOAT8
                                + NULL::FLOAT8,
                                tab_27927._float4
                            )
                    )
        WHERE
            EXISTS(
                SELECT
                    2470039497:::OID AS col_85224
                FROM
                    defaultdb.public.t AS tab_27932
                ORDER BY
                    tab_27932._string ASC,
                    tab_27932._interval DESC,
                    tab_27932._uuid DESC
                LIMIT
                    37:::INT8
            )
        LIMIT
            11:::INT8
    )
LIMIT
    89:::INT8;
```

```
panic: runtime error: index out of range [recovered]
        panic: panic while executing 1 statements: SELECT CASE WHEN _ THEN _:::OID ELSE _ END AS _, _:::TIMESTAMP AS _ FROM _._._ AS _ WHERE EXISTS (SELECT _._ AS _ FROM _._._ AS _, _._._ AS _, _._._ AS _ RIGHT JOIN _._._ AS _ ON (NOT (_._ IN (CASE WHEN _ THEN div(_._::FLOAT8, _._::FLOAT8)::FLOAT8 ELSE _._ END, _._, (_._::FLOAT8 + _::FLOAT8), _._))) WHERE EXISTS (SELECT _:::OID AS _ FROM _._._ AS _ ORDER BY _._ ASC, _._ DESC, _._ DESC LIMIT _:::INT8) LIMIT _:::INT8) LIMIT _:::INT8; caused by runtime error: index out of range
        panic: conn: no bytes to release, current 0, free 107520

goroutine 346 [running]:
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc000840f10, 0x3930020, 0xc0011edac0, 0x1a400)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:628 +0x3af
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc0003f95e0, 0x3930020, 0xc0011edac0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:510 +0x63
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1.1(0xc0003f95e0, 0x3930020, 0xc0011edac0, 0xc00043a2d0, 0xc000b04b00, 0xc00196bf50, 0xc000465b00, 0xc00196bf47, 0x3933ce0, 0xc0003f95c0, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:520 +0x74
panic(0x302d640, 0xc000fbf5f0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc000b00880, 0x3930020, 0xc0011edac0, 0x2dc6b60, 0x55c74b0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:722 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc000b00880, 0x3930020, 0xc0011edac0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:434 +0x61
panic(0x2dc6b60, 0x55c74b0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*RowContainer).At(...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/datum_row_container.go:255
github.com/cockroachdb/cockroach/pkg/sql.(*applyJoinNode).Next(0xc0017a1600, 0x39300e0, 0xc00141d410, 0xc0017a1c00, 0xc000b00bd0, 0x0, 0xc00141d530, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:161 +0xde7
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc00123f900, 0xc000b00bd0, 0x39311a0, 0xc0017a1600, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:178 +0x447
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x39300e0, 0xc00141d410, 0x393ba60, 0xc00123f900, 0x39214a0, 0xc000b72700)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:174 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc00123f900, 0x39300e0, 0xc00141d410)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:802 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc0017b65a0, 0x39300e0, 0xc00141d410, 0x3323f60, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:627 +0x1e9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000449b80, 0xc000e9d560, 0xc001827b00, 0xc00196a828, 0xc000583340, 0xc000b00c90, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8ad
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc000449b80, 0x39300e0, 0xc0011b13b0, 0xc000b00c90, 0xc000e9d560, 0xc001827b00, 0x3931d60, 0xc000c56480, 0xc000583340)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:840 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc000b00880, 0x39300e0, 0xc0011b13b0, 0xc000b00bd0, 0x3, 0x7f30826c9338, 0xc000704790, 0x0, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1121 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc000b00880, 0x39300e0, 0xc0011b13b0, 0xc000b00bd0, 0x7f30826c9338, 0xc000704790, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:957 +0x658
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc000b00880, 0x39300e0, 0xc0011b13b0, 0x3935ce0, 0xc001486d40, 0xc0005bf6d4, 0x32d, 0x0, 0x0, 0x0, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:459 +0xe03
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc000b00880, 0x39300e0, 0xc0011b13b0, 0x3935ce0, 0xc001486d40, 0xc0005bf6d4, 0x32d, 0x0, 0x0, 0x0, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:101 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc000b00880, 0x3930020, 0xc0011edac0, 0xc000840e78, 0x5400, 0x15000, 0xc000840f10, 0xc00043a2d0, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1189 +0x21c8
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000b04b00, 0x3930020, 0xc0011edac0, 0xc000b00880, 0x5400, 0x15000, 0xc000840f10, 0xc00043a2d0, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:436 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc0003f95e0, 0x3930020, 0xc0011edac0, 0xc00043a2d0, 0xc000b04b00, 0xc000465b00, 0x3933ce0, 0xc0003f95c0, 0xc000969260, 0x0, ...)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:577 +0x1ec
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:513 +0x14e
```

**Comment by jordanlewis** [comment]
Nice - so the trouble with recovering from panics begins. We're failing during a recover... This is great, thanks for finding this case. Two problems to solve.

**Comment by jordanlewis** [comment]
Ah, well, the `no bytes to release` was introduced by #35776 after all - before that, the second panic is not thrown. I commented on the PR, and retitling this one to be about the actual causing panic.

**Comment by jordanlewis** [comment]
Actually, renaming because the original panic is still a different stack trace.
