### ISSUE TITLE
Failed tests (10608): TestMetricsRecording 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3619]
The following test appears to have failed:

[#10608](https://circleci.com/gh/cockroachdb/cockroach/10608):

```
1      ts/db.go:98
1      storage/queue.go:335
I0105 15:56:56.603855 742 stopper.go:264  draining; tasks left:
1      ts/db.go:98
I0105 15:56:56.703426 742 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestMetricsRecording (1.36s)
	status_test.go:555: server/testserver.go:249: had 2 ranges at startup, expected 3
FAIL
FAIL	github.com/cockroachdb/cockroach/server	28.976s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.02s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.03s)
=== RUN   TestRuntimeStatRecorder
I0105 15:56:44.095465 770 server/status/runtime.go:137  runtime stats: 11 goroutines, 4.56MiB active, 50000000.00cgo/sec, 782010.00/195500.00 %(u/s)time, 47621.34 %gc (2x)
--- PASS: TestRuntimeStatRecorder (0.02s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.01s)
=== RUN   TestServerNodeEventFeed
--
I0105 15:58:13.315257 921 storage/replica_command.go:1199  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1.000s
I0105 15:58:13.315456 921 storage/replica.go:1618  gossiping system config from store 1, range 1
I0105 15:58:13.316172 921 storage/replica.go:1567  gossiping sentinel from store 1, range 1
I0105 15:58:13.316424 921 storage/replica.go:1573  gossiping first range from store 1, range 1
I0105 15:58:13.317604 921 storage/replica.go:1112  reproposing 1 commands after empty entry
panic: test timed out after 5m0s

goroutine 1025 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x1a691b0, 0x21162a0, 0xdb, 0xdb, 0x1)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/go/src/github.com/cockroachdb/cockroach/storage/replica_test.go:1285 +0x56c
testing.tRunner(0xc820142000, 0x2116870)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4
FAIL	github.com/cockroachdb/cockroach/storage	300.087s
=== RUN   TestBatchBasics
I0105 15:58:29.721577 979 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0105 15:58:29.724919 979 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I0105 15:58:29.730475 979 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
this is #3621.
