### ISSUE TITLE
TestGossipCullNetwork is flaky: double-close of client's closer

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3620]
The following test appears to have failed:

[#10609](https://circleci.com/gh/cockroachdb/cockroach/10609):

```
I0105 16:02:51.771030 515 gossip/server.go:211  @2: distantHops: 2 from 3
I0105 16:02:51.771834 515 gossip/client.go:154  received map[node:2:value:<raw_bytes:"\330\376\205f\003\010\002\022\022\n\003tcp\022\013127.0.0.1:0\032\000" timestamp:<wall_time:1452009771725159637 logical:0 > > orig_stamp:1452009771725174497 ttl_stamp:9223372036854775807 node_id:2 ] from node 2 (1 fresh)
I0105 16:02:51.772013 515 gossip/server.go:211  @1: distantHops: 1 from 4
I0105 16:02:51.772579 515 gossip/client.go:161  sent 2 info(s) to node 2
I0105 16:02:51.772776 515 gossip/gossip.go:641  closing least useful client to node 4 to tighten network graph
panic: close of closed channel

goroutine 264 [running]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).closeClient(0xc82066c270, 0x4)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:750 +0xa5
github.com/cockroachdb/cockroach/gossip.(*Gossip).cullNetwork(0xc82066c270)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:642 +0x2e7
github.com/cockroachdb/cockroach/gossip.(*Gossip).manage.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:591 +0x344
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820104000, 0xc82000f460)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
--
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:214 +0xc1
github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks.func1(0xc8200f8700, 0x4, 0x4, 0xc820158140, 0x6, 0xc820160fc0, 0x1d, 0x20, 0x14269331be12fcd5, 0x1f7b305800000000)
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:243 +0xd6
created by github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:245 +0x300
FAIL	github.com/cockroachdb/cockroach/gossip	0.296s
=== RUN   TestParseResolverSpec
--- PASS: TestParseResolverSpec (0.00s)
=== RUN   TestGetAddress
--- PASS: TestGetAddress (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/gossip/resolver	1.022s
?   	github.com/cockroachdb/cockroach/gossip/simulation	[no test files]
=== RUN   TestKeySorting
--- PASS: TestKeySorting (0.00s)
=== RUN   TestMakeKey
--
W0105 16:08:09.589353 753 kv/dist_sender.go:572  no replica node addresses available via gossip
I0105 16:08:39.650692 753 kv/range_cache.go:128  lookup range descriptor: key=/Table/501/0
I0105 16:08:39.650844 753 kv/range_cache.go:128  lookup range descriptor: key=/Meta2/"\xf9\x01\xf5\x88"
I0105 16:08:39.651062 753 kv/replica_slice.go:54  node 1 is not gossiped: gossip/gossip.go:222: unable to lookup descriptor for node 1: gossip/gossip.go:319: key "node:1" does not exist or has expired
W0105 16:08:39.651161 753 kv/dist_sender.go:572  no replica node addresses available via gossip
panic: test timed out after 5m0s

goroutine 2077 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x1a467c0, 0x2107e40, 0x1f, 0x1f, 0x16ce301)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/go/src/github.com/cockroachdb/cockroach/util/net.go:76 +0x21d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820795030, 0xc8204363f0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70
FAIL	github.com/cockroachdb/cockroach/server	300.077s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.01s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.03s)
=== RUN   TestRuntimeStatRecorder
I0105 16:04:07.454721 773 server/status/runtime.go:137  runtime stats: 11 goroutines, 5.03MiB active, 50000000.00cgo/sec, 654630.00/269550.00 %(u/s)time, 29351.80 %gc (2x)
--- PASS: TestRuntimeStatRecorder (0.01s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.01s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
this is because
```go
// closeClient finds and removes a client from the clients slice.
func (g *Gossip) closeClient(nodeID roachpb.NodeID) {
	c := g.findClient(func(c *client) bool { return c.peerID == nodeID })
	if c != nil {
		c.close()
	}
}
```

is called by the cull-tightening. But there's no protection against double-close. That callpath is also the **only** caller of `closeClient`. I'm not sure what's going on there, but `closeClient` isn't removing the outgoing client. It should probably do that and needs to hold `g.clientsMu` atomically over the call to `findClient` (which also obtains it). So there's some clean-up to do here. I'm going to disable this test for now.

**Comment by spencerkimball** [comment]
I've fixed this in a pending changelist.
