### ISSUE TITLE
importccl: panic when running workload fixtures import ycsb

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#36242]
Our mock inserter we ingest into the `sql` row encoding helpers --  which just appends to our slice of KVs -- implements `put` and `initput`, but not `del`.  However the logic in some insert paths for handling column families assumes there may be an old value that has to be deleted and thus calls `del`.

To reproduce, import csv data with a table using column families, e.g. `fixtures import ycsb`
```
./cockroach start --insecure
workload fixtures import ycsb
```

Output from the logs:
```
panic: unimplemented

goroutine 468 [running]:
panic(0x2d9ca20, 0x39bfb80)
        /usr/local/go/src/runtime/panic.go:556 +0x2cb fp=0xc00765f3d0 sp=0xc00765f340 pc=0x72b49b
github.com/cockroachdb/cockroach/pkg/ccl/importccl.inserter.Del(0xc0003d72a0, 0xc0003d72b0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/load.go:339 +0x39 fp=0xc00765f3f0 sp=0xc00765f3d0 pc=0x22c3789
github.com/cockroachdb/cockroach/pkg/sql/row.insertDelFn(0x3a08ca0, 0xc000d0b140, 0x3a10720, 0xc0003d72a0, 0xc000100368, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/row/writer.go:117 +0x93 fp=0xc00765f458 sp=0xc00765f3f0 pc=0x1c3ef13
github.com/cockroachdb/cockroach/pkg/sql/row.prepareInsertOrUpdateBatch(0x3a08ca0, 0xc000d0b140, 0x3a10720, 0xc0003d72a0, 0xc000100290, 0xc00068cb00, 0x1d, 0x1d, 0xc000ca8000, 0xb, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/row/writer.go:273 +0xb62 fp=0xc00765f708 sp=0xc00765f458 pc=0x1c404b2
github.com/cockroachdb/cockroach/pkg/sql/row.(*Inserter).InsertRow(0xc000100290, 0x3a08ca0, 0xc000d0b140, 0x3a10720, 0xc0003d72a0, 0xc00548c0b0, 0xb, 0xb, 0x1, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/row/writer.go:182 +0x3b0 fp=0xc00765f8c8 sp=0xc00765f708 pc=0x1c3f540
github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*rowConverter).row(0xc000100240, 0x3a08ca0, 0xc000d0b140, 0x0, 0x1, 0x3a43700, 0xc0003d7290)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/read_import_proc.go:313 +0x238 fp=0xc00765fcb0 sp=0xc00765f8c8 pc=0x22d5808
github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*csvInputReader).convertRecordWorker(0xc00099e580, 0x3a08ca0, 0xc000d0b140, 0xc0007c9900, 0xc000ad6f78)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/read_import_csv.go:188 +0x3d1 fp=0xc00765ff20 sp=0xc00765fcb0 pc=0x22c4bc1
github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*csvInputReader).start.func1.1(0x3a08ca0, 0xc000d0b140, 0x3a08d60, 0xc000ad6f90)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/read_import_csv.go:65 +0x3e fp=0xc00765ff58 sp=0xc00765ff20 pc=0x22dfece
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1(0x8, 0x34047c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:170 +0x3a fp=0xc00765ff88 sp=0xc00765ff58 pc=0x156d71a
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0009455f0, 0xc0009456b0)
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57 fp=0xc00765ffd0 sp=0xc00765ff88 pc=0x156d2b7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00765ffd8 sp=0xc00765ffd0 pc=0x75bd81
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

**Comment by knz** [comment]
Ran into this today while trying to benchmark ycsb.

**Comment by dt** [comment]
I think this was fixed at some point -- doesn't repro now: 
```
./cockroach workload fixtures import ycsb
I200826 21:24:00.850769 1 ccl/workloadccl/fixture.go:316  starting import of 1 tables
I200826 21:24:01.862513 23 ccl/workloadccl/fixture.go:446  imported 13 MiB in usertable table (10000 rows, 0 index entries, took 1.009111s, 13.12 MiB/s)
I200826 21:24:01.862568 1 ccl/workloadccl/fixture.go:325  imported 13 MiB bytes in 1 tables (took 1.011081s, 13.10 MiB/s)
```
