### ISSUE TITLE
Failed tests (10624): TestCorruptedClusterID stuck on (clean) stopper.Stop() b/c split queue can't finish

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3626]
The following test appears to have failed:

[#10624](https://circleci.com/gh/cockroachdb/cockroach/10624):

```
W0105 18:34:24.610237 741 storage/store.go:643  error gossiping system config: storage/replica.go:1527: node is stopping
I0105 18:34:45.342713 741 kv/range_cache.go:128  lookup range descriptor: key=/Table/501/0
I0105 18:34:45.342880 741 kv/range_cache.go:128  lookup range descriptor: key=/Meta2/"\xf9\x01\xf5\x88"
I0105 18:34:45.343093 741 kv/replica_slice.go:54  node 1 is not gossiped: gossip/gossip.go:222: unable to lookup descriptor for node 1: gossip/gossip.go:319: key "node:1" does not exist or has expired
W0105 18:34:45.343202 741 kv/dist_sender.go:572  no replica node addresses available via gossip
panic: test timed out after 5m0s

goroutine 1950 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x1a467c0, 0x2107e40, 0x1f, 0x1f, 0x16ce301)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1612 +0xb0c
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820880e70, 0xc820189b30)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70
FAIL	github.com/cockroachdb/cockroach/server	300.095s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.01s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.02s)
=== RUN   TestRuntimeStatRecorder
I0105 18:30:25.038397 761 server/status/runtime.go:137  runtime stats: 11 goroutines, 4.12MiB active, 50000000.00cgo/sec, 670090.00/268030.00 %(u/s)time, 9975.60 %gc (2x)
--- PASS: TestRuntimeStatRecorder (0.01s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.00s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
this looks like a clean test run and then mayhem on the (clean) call to `stopper.Stop` in `server/node_test.go:278` because the split queue can't finish. Maybe this is the scannerStopper thing, @bdarnell?

**Comment by bdarnell** [comment]
It's not `ScannerStopper`; that was only used for `storage/client_*_test.go` so it can't affect tests in package `server`.

**Comment by tschottdorf** [comment]
yeah, I've seen the issue here before: the split queue has an active transaction, but the node drains and so `DistSender` retries indefinitely since it doesn't know about the stopper.

**Comment by tschottdorf** [comment]
More precisely, the issue here is that this test tests a failing `node.Start()`, and even more precisely the failure is returned after starting the store. So the Store can have its queues start work that requires a fully functioning node, but of course that never happens. I should probably mock out the sender so that all requests error immediately.
