### ISSUE TITLE
sql: panic: invalid datum type given: timestamp, expected int[]

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#36305]
```
E190328 20:41:49.244350 14711 sql/conn_executor.go:708  [n1,client=127.0.0.1:58090,user=root] a SQL panic has occurred while executing "SELECT (e'[{\"6ap\": true, \"hktt \\'I] q\": {\"foo\": {\"Ef&4.nE9f1\": [], \"a\": 1.2955939510175059}}}, 1.2376349725051339, \"bar\", [[]]]'::JSONB->1173786358153560306::INT8) AS col_221628, to_ip(tab_34985.col13::STRING)::BYTES AS col_221629, CASE WHEN inet_same_family((SELECT ret_148 AS col_221639 FROM [UPDATE defaultdb.public.table7 AS tab_34991 SET col1 = e'V6C{h\\x07':::STRING:::NAME WHERE EXISTS (WITH with_27978 (col_221630, col_221631, col_221632, col_221633) AS (SELECT (-4845509963714139878):::INT8 AS col_221630, e'\\\\x47991d4a1554702f':::BYTES AS col_221631, tab_34994.col3 AS col_221632, false AS col_221633 FROM defaultdb.public.table5 AS tab_34992, [UPDATE defaultdb.public.table9 AS tab_34993 SET col10 = tab_34993.col10, col4 = tab_34993.col9, col0 = 'c8a3:ec53:7b7d:7616:81ac:8e3c:ed8a:730d/17':::INET LIMIT 68:::INT8 RETURNING '13:51:47.604097':::TIME AS ret_140], defaultdb.public.table8 AS tab_34994 WHERE true) SELECT with_27978.col_221632 AS col_221634, '1970-07-27':::DATE AS col_221635, with_27978.col_221632 AS col_221636, '187.72.61.68/20':::INET AS col_221637, '-44 years -5 mons -964 days -19:33:35.505535':::INTERVAL AS col_221638 FROM defaultdb.public.table4 AS tab_34995, with_27978 WHERE with_27978.col_221633 ORDER BY tab_34995.col2 DESC LIMIT 40:::INT8) RETURNING col2 AS ret_141, '21:47:56.426333':::TIME AS ret_142, false AS ret_143, '[[{\"H-|X\": null, \"c\": {\"q$j5R\": true}}, {}, {}], null, {\")dt\": []}]':::JSONB AS ret_144, col5 AS ret_145, true AS ret_146, col0 AS ret_147, '193.100.195.221/10':::INET AS ret_148, NULL AS ret_149, NULL AS ret_150, '167.220.236.30/27':::INET AS ret_151, '1992-04-09':::DATE AS ret_152, B'1111100100001000101110010101111010' AS ret_153, col5 AS ret_154, NULL AS ret_155, 'a4ef:578a:99fc:d44c:121:11c8:20df:4962/50':::INET AS ret_156, NULL AS ret_157, '1970-01-10 23:40:01.000158+00:00':::TIMESTAMPTZ AS ret_158, '11:34:32.025039':::TIME AS ret_159, '1970-01-06 10:17:40.000919+00:00':::TIMESTAMP AS ret_160] WHERE ret_143 ORDER BY ret_147 ASC LIMIT 1:::INT8)::INET, '179.172.241.60/28'::INET)::BOOL THEN tab_34990.col8 ELSE '1985-11-09':::DATE END AS col_221640, tab_34990.col5 AS col_221641, tab_34983.col9 AS col_221642, tab_34983.col9 AS col_221643, '418e:32e9:7cb6:84c:42ef:e0ef:ed97:49e3/32':::INET AS col_221644, tab_34982.col5 AS col_221645, '23:33:48.478323':::TIME AS col_221646, '120.115.164.246/8':::INET AS col_221647, tab_34984.col10 AS col_221648, '40.82.196.11/7':::INET AS col_221649 FROM defaultdb.public.table2 AS tab_34982, defaultdb.public.table3 AS tab_34983 CROSS JOIN defaultdb.public.table3 AS tab_34984 LEFT JOIN defaultdb.public.table2 AS tab_34985 ON true INNER JOIN defaultdb.public.table4 AS tab_34986 ON (true OR (((NULL::JSONB#>>ARRAY[e'\\x10=I:i']::STRING[]) NOT LIKE e'\"%0:Q?\\x16':::STRING) AND ('c2b4:f0fd:320a:659b:ce2e:c310:6aab:3c9c/65'::INET NOT IN (SELECT 'f6dc:abe6:7c57:56fd:56de:89b4:e064:a8f0/50'::INET AS col_221627 FROM defaultdb.public.table2 AS tab_34987 RIGHT JOIN defaultdb.public.tab_34849 AS tab_34988 ON true, defaultdb.public.table3 AS tab_34989 LIMIT 96:::INT8)))), defaultdb.public.table2 AS tab_34990": invalid datum type given: timestamp, expected int[]
E190328 20:41:49.244955 14711 util/log/crash_reporting.go:204  [n1,client=127.0.0.1:58090,user=root] a panic has occurred!
panic: invalid datum type given: timestamp, expected int[] [recovered]
	panic: panic while executing 1 statements: SELECT (_::JSONB->_::INT8) AS _, to_ip(_._::STRING)::BYTES AS _, CASE WHEN inet_same_family((SELECT _ AS _ FROM [UPDATE _._._ AS _ SET _ = _:::STRING:::NAME WHERE EXISTS (WITH _ (_, _, _, _) AS (SELECT (_):::INT8 AS _, _:::BYTES AS _, _._ AS _, _ AS _ FROM _._._ AS _, [UPDATE _._._ AS _ SET _ = _._, _ = _._, _ = _:::INET LIMIT _:::INT8 RETURNING _:::TIME AS _], _._._ AS _ WHERE _) SELECT _._ AS _, _:::DATE AS _, _._ AS _, _:::INET AS _, _:::INTERVAL AS _ FROM _._._ AS _, _ WHERE _._ ORDER BY _._ DESC LIMIT _:::INT8) RETURNING _ AS _, _:::TIME AS _, _ AS _, _:::JSONB AS _, _ AS _, _ AS _, _ AS _, _:::INET AS _, _ AS _, _ AS _, _:::INET AS _, _:::DATE AS _, _ AS _, _ AS _, _ AS _, _:::INET AS _, _ AS _, _:::TIMESTAMPTZ AS _, _:::TIME AS _, _:::TIMESTAMP AS _] WHERE _ ORDER BY _ ASC LIMIT _:::INT8)::INET, _::INET)::BOOL THEN _._ ELSE _:::DATE END AS _, _._ AS _, _._ AS _, _._ AS _, _:::INET AS _, _._ AS _, _:::TIME AS _, _:::INET AS _, _._ AS _, _:::INET AS _ FROM _._._ AS _, _._._ AS _ CROSS JOIN _._._ AS _ LEFT JOIN _._._ AS _ ON _ INNER JOIN _._._ AS _ ON (_ OR (((_::JSONB#>>ARRAY[_]::STRING[]) NOT LIKE _:::STRING) AND (_::INET NOT IN (SELECT _::INET AS _ FROM _._._ AS _ RIGHT JOIN _._._ AS _ ON _, _._._ AS _ LIMIT _:::INT8)))), _._._ AS _; caused by invalid datum type given: timestamp, expected int[]
	panic: conn: no bytes to release, current 0, free 107520

goroutine 14711 [running]:
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc000a2e610, 0x38237c0, 0xc0028cce00, 0x1a400)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:628 +0x3af
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc0025cf860, 0x38237c0, 0xc0028cce00)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:510 +0x63
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1.1(0xc0025cf860, 0x38237c0, 0xc0028cce00, 0xc000342ba0, 0xc0009e7080, 0xc006f35f50, 0xc001081600, 0xc006f35f47, 0x38273c0, 0xc0025cf800, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:520 +0x74
panic(0x2f58c20, 0xc00594fd70)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc001648000, 0x38237c0, 0xc0028cce00, 0x2bfee20, 0xc0003967a0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:722 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc001648000, 0x38237c0, 0xc0028cce00)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:434 +0x61
panic(0x2bfee20, 0xc0003967a0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc007f9350c, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:172 +0x25d
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc001041400, 0x0, 0x0, 0x0, 0xa)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:186 +0x54e
github.com/cockroachdb/cockroach/pkg/sql.(*rowSourceToPlanNode).Next(0xc002ef7d40, 0x3823880, 0xc003463110, 0xc001e1be00, 0xc001648350, 0xb, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/row_source_to_plan_node.go:78 +0x63
github.com/cockroachdb/cockroach/pkg/sql.(*spoolNode).startExec(0xc0020b84e0, 0x3823880, 0xc003463110, 0xc001e1be00, 0xc001648350, 0xc002ef7d40, 0xc006f32b40)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/spool.go:62 +0x18b
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x30d5f04, 0x5, 0x3825880, 0xc0020b84e0, 0xc001037c80, 0xc006f32b50)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:495 +0x55
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc003c6d980, 0x30d5f04, 0x5, 0x3825880, 0xc0020b84e0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:145 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc003c6d980, 0x3825880, 0xc0020b84e0, 0x30d5f04, 0x5)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:616 +0x1c4
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc003c6d980, 0x3825880, 0xc0020b84e0, 0x203000, 0x6b7ac3)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:112 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x3823880, 0xc003463110, 0x3825880, 0xc0020b84e0, 0x0, 0x322d1b8, 0x0, 0x0, 0x0, 0xc003463290, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:76 +0x1a4
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x3823880, 0xc003463110, 0xc001e1be00, 0xc001648350, 0x3825880, 0xc0020b84e0, 0xc006f339b8, 0x2)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:498 +0x116
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc00013af00, 0x3823880, 0xc003463110, 0x0, 0xc0003da3c0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:124 +0xd9
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).Start(0xc000968380, 0x3823880, 0xc003463110, 0x56f6c80, 0x2bfe0a0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:222 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc000968380, 0x3823880, 0xc003463110)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:801 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc001cb9e00, 0x3823880, 0xc003463110, 0x322c8b8, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:627 +0x1e9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000447180, 0xc003c6d3e0, 0xc00105eb40, 0xc006f346f8, 0xc0030b22c0, 0xc001e1b800, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8ad
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunSubquery(0xc000447180, 0x3823880, 0xc003ed6690, 0x0, 0xc0020b85d0, 0x1, 0x1, 0x3825100, 0xc0021f90a0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:762 +0x81f
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries(0xc000447180, 0x3823880, 0xc003ed6690, 0xc001648350, 0xc008bfd380, 0xc0020f5f10, 0x2, 0x2, 0xc0030b2000, 0xc001648101, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:666 +0x1ba
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001648000, 0x3823880, 0xc003ed6690, 0xc001648350, 0x3, 0x7f2758653398, 0xc0012c6160, 0x1, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1112 +0x3d4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001648000, 0x3823880, 0xc003ed6690, 0xc001648350, 0x7f2758653398, 0xc0012c6160, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:957 +0x658
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001648000, 0x3823880, 0xc003ed6690, 0x38293c0, 0xc0028cc800, 0xc008eaa000, 0xc78, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:459 +0xe03
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001648000, 0x3823880, 0xc003ed6690, 0x38293c0, 0xc0028cc800, 0xc008eaa000, 0xc78, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:101 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001648000, 0x38237c0, 0xc0028cce00, 0xc000a2e578, 0x5400, 0x15000, 0xc000a2e610, 0xc000342ba0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1189 +0x21c8
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0009e7080, 0x38237c0, 0xc0028cce00, 0xc001648000, 0x5400, 0x15000, 0xc000a2e610, 0xc000342ba0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:436 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc0025cf860, 0x38237c0, 0xc0028cce00, 0xc000342ba0, 0xc0009e7080, 0xc001081600, 0x38273c0, 0xc0025cf800, 0xc004b101e0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:577 +0x1ec
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:513 +0x14e
```

Not really sure what to do about this one. Filing it here for searchability.
cc @jordanlewis

**Comment by mjibson** [comment]
Closing until we have repro SQL.
