### ISSUE TITLE
sql: nil pointer deference in RowContainer with TPC-C + column families

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#36323]
`cockroach` SHA: d03a34e92d2ee558fb6aedb0709b733a1fab97f4

Reproduction steps:
```
export cluster = <user>-tpcc
roachprod create --nodes=4 $cluster
roachprod stage $cluster:1-3 cockroach d03a34e92d2ee558fb6aedb0709b733a1fab97f4

# build a Linux workload binary from https://github.com/cockroachdb/cockroach/pull/30624
roachprod put $cluster:4 workload

# should crash immediately
roachprod start $cluster:1-3
roachprod run $cluster:4 -- './workload init tpcc {pgurl:1}'
roachprod run $cluster:4 -- './workload run tpcc --mix='newOrder=1' --max-rate=1 --wait=false {pgurl:1}'

# should not crash if optimizer is disabled
roachprod stop $cluster:1-3
roachprod start $cluster:1-3
roachprod run $cluster:1 -- './cockroach sql --insecure -e "set cluster setting sql.defaults.optimizer = 0;"'
roachprod run $cluster:4 -- './workload run tpcc --mix='newOrder=1' --max-rate=1 --wait=false {pgurl:1}'
```

Reliably results in the following panic:

```
E190329 04:13:12.861892 2287 sql/conn_executor.go:708  [n1,client=10.142.0.4:47566,user=root] a SQL panic has occurred while executing "UPDATE district SET d_next_o_id = d_next_o_id + 1 WHERE (d_w_id = $1) AND (d_id = $2) RETURNING d_tax, d_next_o_id": runtime error: invalid memory address or nil pointer dereference
E190329 04:13:12.862063 2287 util/log/crash_reporting.go:204  [n1,client=10.142.0.4:47566,user=root] a panic has occurred!
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: panic while executing 1 statements: UPDATE _ SET _ = _ + _ WHERE (_ = $1) AND (_ = $2) RETURNING _, _; caused by runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x1c05861]

goroutine 2287 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00ad88880, 0x3a22620, 0xc006c39780, 0x2eb1a00, 0x5701210)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:722 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc00ad88880, 0x3a22620, 0xc006c39780)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:434 +0x61
panic(0x2eb1a00, 0x5701210)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*RowContainer).rowSize(0xc0091fc1b0, 0xc028082d10, 0xb, 0xb, 0xc006fdabd0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/datum_row_container.go:202 +0x61
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*RowContainer).AddRow(0xc0091fc1b0, 0x3a226e0, 0xc006fdabd0, 0xc028082d10, 0xb, 0xb, 0xc0097f6850, 0x1, 0x1, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/datum_row_container.go:227 +0x7c
github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).processSourceRow(0xc0097fc500, 0x3a226e0, 0xc006fdabd0, 0xc01030bc00, 0xc00ad88bd0, 0xc0097f8a40, 0x4, 0x4, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go:703 +0x8f9
github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).BatchedNext(0xc0097fc500, 0x3a226e0, 0xc006fdabd0, 0xc01030bc00, 0xc00ad88bd0, 0xc006fdaf00, 0x0, 0x3a226e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go:546 +0x154
github.com/cockroachdb/cockroach/pkg/sql.(*serializeNode).Next(0xc006fda4b0, 0x3a226e0, 0xc006fdabd0, 0xc01030bc00, 0xc00ad88bd0, 0x0, 0xc006fdaf00, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:123 +0xa1
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc0097fca00, 0xc00ad88bd0, 0x3a24520, 0xc006fda4b0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:178 +0x447
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x3a226e0, 0xc006fdabd0, 0x3a2e060, 0xc0097fca00, 0x3a13aa0, 0xc0134e1180)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:174 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc0097fca00, 0x3a226e0, 0xc006fdabd0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:802 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc0134e81e0, 0x3a226e0, 0xc006fdabd0, 0x3410170, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:627 +0x1e9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00004f540, 0xc0158c9ec0, 0xc00f04fa70, 0xc011e24818, 0xc005ddc840, 0xc00ad88c90, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8ad
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00004f540, 0x3a226e0, 0xc0293f1590, 0xc00ad88c90, 0xc0158c9ec0, 0xc00f04fa70, 0x3a24360, 0xc00d6d0ea0, 0xc005ddc840)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:840 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc00ad88880, 0x3a226e0, 0xc0293f1590, 0xc00ad88bd0, 0x3, 0x7f07c8b6f950, 0xc028082c60, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1121 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00ad88880, 0x3a226e0, 0xc0293f1590, 0xc00ad88bd0, 0x7f07c8b6f950, 0xc028082c60, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:957 +0x658
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00ad88880, 0x3a226e0, 0xc0293f1590, 0x3a28de0, 0xc0210f4070, 0xc0095822ec, 0x74, 0x2, 0xc0094eacd0, 0x2, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:459 +0xe03
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00ad88880, 0x3a226e0, 0xc0293f1590, 0x3a28de0, 0xc0210f4070, 0xc0095822ec, 0x74, 0x2, 0xc0094eacd0, 0x2, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:101 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00ad88880, 0x3a22620, 0xc006c39780, 0xc00011b0b8, 0x5400, 0x15000, 0xc00011b150, 0xc00f64b9a0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1248 +0x1418
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0009ea580, 0x3a22620, 0xc006c39780, 0xc00ad88880, 0x5400, 0x15000, 0xc00011b150, 0xc00f64b9a0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:436 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc011b48e2e, 0xc00e07ece0, 0x3a22620, 0xc006c39780, 0xc00f64b9a0, 0xc0009ea580, 0xc00880cd00, 0x3a262e0, 0xc00e07ecc0, 0xc00608f2c0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:581 +0x21f
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:516 +0x17b
```

cc. @andy-kimball for triage because we only hit the panic with `optimizer = on`.

**Comment by andy-kimball** [comment]
This is most likely a duplicate of https://github.com/cockroachdb/cockroach/issues/35970, which is fixed by https://github.com/cockroachdb/cockroach/pull/36103 (will be merged today).

**Comment by nvanbenschoten** [comment]
I just confirmed that #36103 did fix this. Thanks @justinj!
