### ISSUE TITLE
panic: cannot convert nil datum to EncDatum

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#36331]
The symptom here looks similar to #25197, but the stack trace is different. Also mentioned in https://github.com/cockroachdb/cockroach/issues/35535#issuecomment-477834625:

```
panic while executing 1 statements: WITH _ AS (SELECT _ AS _, CASE WHEN (cume_dist() OVER (ORDER BY _ DESC)) < _ THEN ceiling((cume_dist() OVER (ORDER BY _ DESC) * _) * _) / _ ELSE ceiling(cume_dist() OVER (ORDER BY _ DESC) * _) END AS _ FROM _ AS OF SYSTEM TIME _ WHERE _ = _) SELECT _ AS _, min(_) AS _ FROM _ AS OF SYSTEM TIME _ GROUP BY _ ORDER BY _ DESC

goroutine 1509 [running]:
runtime/debug.Stack(0x3a21cc0, 0xc005e9a840, 0xc000000003)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x3a21cc0, 0xc005e9a840, 0xc000487300, 0x3118280, 0xc0059e64e0, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:214 +0xa6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0008a1600, 0x3a21cc0, 0xc005e9a840, 0x2da9280, 0x39dbea0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:715 +0x2dd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0008a1600, 0x3a21cc0, 0xc005e9a840)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:434 +0x61
panic(0x2da9280, 0x39dbea0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0x2000000001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:166 +0x27b
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*MemRowContainer).EncRow(0xc1f288e2c0, 0x296b2d, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/row_container.go:177 +0x161
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*hashMemRowIterator).computeKey(0xc005ebb620, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/hash_row_container.go:412 +0x4f
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*HashDiskBackedRowContainer).computeKeysForAllRowsIterators(0xc075168840, 0x3a21d80, 0xc00815f770)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/hash_row_container.go:900 +0x15b
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).spillAllRowsToDisk(0xc075eb6800, 0xc072811ee0, 0xc00815f701)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:391 +0xc6
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).growMemAccount(0xc075eb6800, 0xc075eb6e70, 0x296b2e8, 0x3a21d80, 0xc00815f770)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:415 +0xab
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).processPartition(0xc075eb6800, 0x3a21d80, 0xc00815f770, 0xc006a8fa00, 0xc0ca38d200, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:567 +0x670
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).computeWindowFunctions(0xc075eb6800, 0x3a21d80, 0xc00815f770, 0xc006a8fa00, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:737 +0xbb3
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).emitRow(0xc075eb6800, 0x2, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:361 +0xa3
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).Next(0xc075eb6800, 0x0, 0x0, 0x0, 0xc006c0c528)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:279 +0x54
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashAggregator).accumulateRows(0xc0077c3400, 0x1, 0x0, 0x0, 0x0, 0xc006c0c528)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:471 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashAggregator).Next(0xc0077c3400, 0x0, 0x0, 0x0, 0xc006c0c528)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:700 +0x146
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).fill(0xc005ea9400, 0x3a21d80, 0xc00815f770, 0x32a35bb)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:308 +0x73
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).Start(0xc005ea9400, 0x3a21d80, 0xc00815f770, 0xc110662e50, 0x2da8500)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:289 +0xab
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc005ea9400, 0x3a21d80, 0xc00815f770)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:801 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc005e834a0, 0x3a21d80, 0xc00815f770, 0x340f830, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:627 +0x1e9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00004ea00, 0xc131c35f20, 0xc0c9d06990, 0xc0acc66818, 0xc005928000, 0xc0008a1a10, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8ad
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00004ea00, 0x3a21d80, 0xc006299b90, 0xc0008a1a10, 0xc131c35f20, 0xc0c9d06990, 0x3a23dc0, 0xc0063276d0, 0xc005928000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:840 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc0008a1600, 0x3a21d80, 0xc006299b90, 0xc0008a1950, 0x3, 0x7ff926dc82a0, 0xc007eca2c0, 0x1, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1121 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0008a1600, 0x3a21d80, 0xc006299b90, 0xc0008a1950, 0x7ff926dc82a0, 0xc007eca2c0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:957 +0x658
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0008a1600, 0x3a21d80, 0xc006299b90, 0x3a27980, 0xc007b2d480, 0xc0082fa1ae, 0x18b, 0x0, 0xc006641400, 0x2, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:459 +0xe03
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0008a1600, 0x3a21d80, 0xc006299b90, 0x3a27980, 0xc007b2d480, 0xc0082fa1ae, 0x18b, 0x0, 0xc006641400, 0x2, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:101 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0008a1600, 0x3a21cc0, 0xc005e9a840, 0xc000eb20f8, 0x5400, 0x15000, 0xc000eb2190, 0xc00b0ad810, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1248 +0x1418
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000a71340, 0x3a21cc0, 0xc005e9a840, 0xc0008a1600, 0x5400, 0x15000, 0xc000eb2190, 0xc00b0ad810, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:436 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00b0d9bb1, 0xc005d96a20, 0x3a21cc0, 0xc005e9a840, 0xc00b0ad810, 0xc000a71340, 0xc005e72400, 0x3a25980, 0xc005d96a00, 0xc005ea7c20, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:581 +0x21f
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:516 +0x17b
```

The reproduction instructions for #35535 are what I used, but instead of `--concurrency=1000` I used `--concurrency=8`. 

Note I was running a `master` build:

```
pmattis@peter-test-0001:~$ ./cockroach version
Build Tag:    v19.1.0-beta.20190318-488-gd03a34e
Build Time:   2019/03/29 00:20:50
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.11.6
C Compiler:   gcc 6.3.0
Build SHA-1:  d03a34e92d2ee558fb6aedb0709b733a1fab97f4
Build Type:   release
```

**Comment by jordanlewis** [comment]
@yuzefovich could you take a look at this when you have a moment?
