### ISSUE TITLE
panic in SchemaChangeManager

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36348]
I was running this experiment https://github.com/cockroachdb/cockroach/issues/35923 when at the end I tried to drop the index:
```
root@localhost:26257/tpcc> drop index item@us_e_idx;
driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the transaction status: read tcp 127.0.0.1:55066->127.0.0.1:26257: read: connection reset by peer
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the database name: dial tcp 127.0.0.1:26257: connect: connection refused
root@localhost:26257/? ?>
Error: interrupted
Failed running "sql"
Connection to 35.246.116.84 closed.
```
It turns out this registered on the entire cluster:
Node 1
```
* ERROR: [n1] a panic has occurred!
*
runtime error: invalid memory address or nil pointer dereference

goroutine 49 [running]:
runtime/debug.Stack(0x3a226e0, 0xc000c60ea0, 0x7fd800000003)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x3a226e0, 0xc000c60ea0, 0xc0004a9300, 0x2eb1a00, 0x5701210, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:214 +0xa6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000aac000, 0x3a226e0, 0xc000c60ea0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0xe4
panic(0x2eb1a00, 0x5701210)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1.3(0xc012bd03e0, 0x5, 0x8, 0xc008c4ea00, 0x1f5, 0x200, 0x15908684f13b0ba8, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1830 +0xc5e
github.com/cockroachdb/cockroach/pkg/gossip.(*SystemConfigDeltaFilter).ForModified(0xc006533a00, 0xc02ffd8a00, 0xc006533b88)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/util.go:90 +0x313
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x3a226e0, 0xc000c60ea0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1788 +0x9b4
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc000367d80, 0xc000aac000, 0xc000377320)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8
```
Node 2
```
* ERROR: [n2] a panic has occurred!
*
runtime error: invalid memory address or nil pointer dereference

goroutine 362 [running]:
runtime/debug.Stack(0x3a226e0, 0xc0006fcff0, 0x7f4c00000003)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x3a226e0, 0xc0006fcff0, 0xc000249300, 0x2eb1a00, 0x5701210, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:214 +0xa6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000ab8000, 0x3a226e0, 0xc0006fcff0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0xe4
panic(0x2eb1a00, 0x5701210)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1.3(0xc024eec170, 0x5, 0x8, 0xc393d17c00, 0x1f5, 0x200, 0x15908684f13b0ba8, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1830 +0xc5e
github.com/cockroachdb/cockroach/pkg/gossip.(*SystemConfigDeltaFilter).ForModified(0xc01eda1a00, 0xc03f65e870, 0xc01eda1b88)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/util.go:90 +0x313
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x3a226e0, 0xc0006fcff0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1788 +0x9b4
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc0004289e0, 0xc000ab8000, 0xc00034bfe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8
```
and the final node:
```
* ERROR: [n3] a panic has occurred!
*
runtime error: invalid memory address or nil pointer dereference

goroutine 305 [running]:
runtime/debug.Stack(0x3a226e0, 0xc000b64c30, 0x7f7a00000003)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x3a226e0, 0xc000b64c30, 0xc000543300, 0x2eb1a00, 0x5701210, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:214 +0xa6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc0001e0360, 0x3a226e0, 0xc000b64c30)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0xe4
panic(0x2eb1a00, 0x5701210)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1.3(0xc024a84868, 0x5, 0x8, 0xc00b09b000, 0x1f5, 0x200, 0x15908684f13b0ba8, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1830 +0xc5e
github.com/cockroachdb/cockroach/pkg/gossip.(*SystemConfigDeltaFilter).ForModified(0xc02f4d1a00, 0xc0703d4aa0, 0xc02f4d1b88)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/util.go:90 +0x313
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x3a226e0, 0xc000b64c30)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1788 +0x9b4
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00042a420, 0xc0001e0360, 0xc000325b40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8
```
This is on today's master. v19.1.0-beta.20190318-503-g5996d50

**Comment by awoods187** [comment]
[cockroach.log](https://github.com/cockroachdb/cockroach/files/3024396/cockroach.log)
[cockroach.log](https://github.com/cockroachdb/cockroach/files/3024397/cockroach.log)


[cockroach.log](https://github.com/cockroachdb/cockroach/files/3024395/cockroach.log)
