### ISSUE TITLE
Failed tests (10667): cgo panic from DBNewIter in TestNodeJoin

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3639]
The following test appears to have failed:

[#10667](https://circleci.com/gh/cockroachdb/cockroach/10667):

```
runtime.throw(0x1912700, 0x2a)
	/tmp/workdir/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1826 [syscall, locked to thread]:
runtime.cgocall(0x1148f90, 0xc820265340, 0x0)
	/tmp/workdir/go/src/runtime/cgocall.go:120 +0xc2 fp=0xc8202652f8 sp=0xc8202652d0
github.com/cockroachdb/cockroach/storage/engine._Cfunc_DBNewIter(0x0, 0xc820028900, 0x0)
	??:0 +0x58 fp=0xc820265340 sp=0xc8202652f8
github.com/cockroachdb/cockroach/storage/engine.newRocksDBIterator(0x0, 0x5e3200, 0xc8202653a0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:512 +0x3c fp=0xc820265370 sp=0xc820265340
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).NewIterator(0xc820b505f0, 0xc820265300, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:262 +0x59 fp=0xc8202653a0 sp=0xc820265370
github.com/cockroachdb/cockroach/storage/engine.InMem.NewIterator(0xc820b505f0, 0x1a47a00, 0x0, 0x0)
	<autogenerated>:75 +0x5a fp=0xc8202653d8 sp=0xc8202653a0
--
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820267f78 sp=0xc820267f70
created by github.com/cockroachdb/cockroach/rpc.syncAdapter.exec
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:51 +0x61

goroutine 1 [chan receive]:
testing.RunTests(0x1a472d0, 0x21084c0, 0x1f, 0x1f, 0x16cf101)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc820539f10, 0x8418f5d384f21f15)
	/tmp/workdir/go/src/testing/testing.go:494 +0xe5
github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck(0xc820539f10)
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x2f
github.com/cockroachdb/cockroach/server_test.TestMain(0xc820539f10)
	/go/src/github.com/cockroachdb/cockroach/server/main_test.go:34 +0x2f
main.main()
	github.com/cockroachdb/cockroach/server/_test/_testmain.go:114 +0x20a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 20 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2455120)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1029 +0x76
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:610 +0x117

goroutine 1804 [chan receive]:
github.com/cockroachdb/cockroach/rpc.(*Server).sendResponses(0xc820a00120, 0x7f6886975918, 0xc820568180, 0xc820a00840)
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:300 +0xb5
github.com/cockroachdb/cockroach/rpc.(*Server).ServeHTTP.func1(0xc820a00120, 0x7f6886975918, 0xc820568180, 0xc820a00840)
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:207 +0x4d
created by github.com/cockroachdb/cockroach/rpc.(*Server).ServeHTTP
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:208 +0xa6c

goroutine 1753 [runnable]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc820b505f0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:123 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:124 +0x581

goroutine 1777 [runnable]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc820512550)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:123 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:124 +0x581

goroutine 1805 [semacquire]:
sync.runtime_Semacquire(0xc8201c922c)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8201c9220)
	/tmp/workdir/go/src/sync/waitgroup.go:126 +0x118
github.com/cockroachdb/cockroach/rpc.(*Server).readRequests.func1(0xc8201c9220, 0xc8202e7e07, 0xc820a00120, 0x7f6886972ff8, 0xc820586000, 0xc820a00840)
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:225 +0x2f
github.com/cockroachdb/cockroach/rpc.(*Server).readRequests(0xc820a00120, 0x7f6886972ff8, 0xc820586000, 0x7f6886975918, 0xc820568180, 0xc8201c9170, 0xc820a00840)
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:238 +0x27e
github.com/cockroachdb/cockroach/rpc.(*Server).ServeHTTP.func2(0xc820a00120, 0x7f6886972ff8, 0xc820586000, 0x7f6886975918, 0xc820568180, 0xc8201c9170, 0xc820a00840)
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:210 +0x6f
created by github.com/cockroachdb/cockroach/rpc.(*Server).ServeHTTP
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:213 +0xadc

goroutine 1752 [semacquire]:
runtime.Stack(0xc820b52000, 0x200000, 0x200000, 0xc820b52001, 0x200000)
	/tmp/workdir/go/src/runtime/mprof.go:564 +0x3a
github.com/cockroachdb/cockroach/util/leaktest.interestingGoroutines(0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:43 +0xb0
github.com/cockroachdb/cockroach/util/leaktest.AfterTest(0x7f688696c418, 0xc82045e000)
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:131 +0x24f
github.com/cockroachdb/cockroach/server.TestNodeJoin(0xc82045e000)
	/go/src/github.com/cockroachdb/cockroach/server/node_test.go:247 +0x1145
testing.tRunner(0xc82045e000, 0x2108598)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4
FAIL	github.com/cockroachdb/cockroach/server	10.606s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.03s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.03s)
=== RUN   TestRuntimeStatRecorder
I0106 10:43:59.585661 780 server/status/runtime.go:137  runtime stats: 12 goroutines, 3.04MiB active, 50000000.00cgo/sec, 711790.00/293090.00 %(u/s)time, 13941.15 %gc (2x)
--- PASS: TestRuntimeStatRecorder (0.01s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.01s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment]
Looks like `TestNodeJoin` had finished and was sitting in `leaktest.AfterTest()` when an RPC was received. Since the stopper had been stopped, the `engine.RocksDB` had been closed. Is there nothing at higher levels of the server that prevent trying to run an RPC once the stopper has stopped? @bdarnell?

**Comment by petermattis** [comment]
FYI, I managed to reproduce this locally after 8987 runs using `make stressrace PKG=./server TESTS=TestNodeJoin`.

**Comment by bdarnell** [comment]
RPCs supposed to be guarded by `Stopper.Run{Async,}Task` to stop them from running during shutdown. I'm not sure whether we should be calling `RunTask` from `rpc/server.go` or `server/node.go` The RPC layer has a `Stopper` but it looks like it's only used on the client, not the server. It would be easy to hook this up in the RPC layer now but we might have to rip it out later in the move to GRPC. If we don't do it at the rpc layer we'll need to individually patch all our rpc handlers to use tasks (there are not too many of them since everything is batched now, but we have a handful)

**Comment by petermattis** [comment]
@bdarnell Do you want me to take a go at fixing this or do you want to do it?

**Comment by bdarnell** [comment]
My queue is pretty full right now, so it's probably best for someone else to take this one.

**Comment by tschottdorf** [comment]
maybe #3239 is related.

**Comment by petermattis** [comment]
Ok, I'll take a crack at it.
