### ISSUE TITLE
Failed tests (10668): TestChaos: raft.loadState: state.commit out of range

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3640]
The following test appears to have failed:

[#10668](https://circleci.com/gh/cockroachdb/cockroach/10668):

```
I0106 10:54:10.722969 1 cli/start.go:176  starting cockroach cluster
I0106 10:54:10.726017 1 storage/engine/rocksdb.go:106  opening rocksdb instance at "/data2.0"
I0106 10:54:10.730123 1 gossip/gossip.go:738  starting client to roach0.local:26257
W0106 10:54:10.743875 1 rpc/client.go:300  EOF
E0106 10:54:10.747757 1 raft/raft.go:843  [group 2] 3 state.commit 10 is out of range [23, 10]
panic: [group 2] 3 state.commit 10 is out of range [23, 10]

goroutine 1 [running]:
github.com/cockroachdb/cockroach/storage.(*raftLogger).Panicf(0xc820464210, 0x15c2d40, 0x2b, 0xc82045a500, 0x4, 0x4)
	/go/src/github.com/cockroachdb/cockroach/storage/raft.go:124 +0x1a2
github.com/coreos/etcd/raft.(*raft).loadState(0xc82009a380, 0x5, 0x0, 0xa, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/raft.go:843 +0x2b3
github.com/coreos/etcd/raft.newRaft(0xc820264828, 0x7f7570e814c8)
	/go/src/github.com/coreos/etcd/raft/raft.go:221 +0x905
github.com/coreos/etcd/raft.NewRawNode(0xc820264828, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/rawnode.go:76 +0xba
github.com/cockroachdb/cockroach/storage.(*Replica).setReplicaID(0xc82005fd40, 0xc800000003, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:291 +0x2d6
--
github.com/cockroachdb/cockroach/cli.Run(0xc82000a0b0, 0x9, 0x9, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/cli/cli.go:83 +0x7c
main.main()
	/go/src/github.com/cockroachdb/cockroach/main.go:37 +0xe6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 8 [select]:
github.com/cockroachdb/cockroach/util/retry.(*Retry).Next(0xc820049e18, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/retry/retry.go:106 +0x176
github.com/cockroachdb/cockroach/rpc.(*Client).runHeartbeat(0xc8200ced10, 0x3b9aca00, 0x6fc23ac00, 0x4000000000000000, 0x0, 0x0, 0xc820100f60)
	/go/src/github.com/cockroachdb/cockroach/rpc/client.go:282 +0x371
github.com/cockroachdb/cockroach/rpc.NewClient.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/client.go:148 +0x36
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc820015780)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 7 [select]:
github.com/cockroachdb/cockroach/gossip.(*client).start.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:60 +0x5f1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc8200fb200)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 21 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x204fa00)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1029 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:610 +0xbc

goroutine 23 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 24 [select]:
github.com/cockroachdb/cockroach/rpc.(*RemoteClockMonitor).MonitorRemoteOffsets(0xc82027fa60, 0xc8201deaf0)
	/go/src/github.com/cockroachdb/cockroach/rpc/clock_offset.go:156 +0x742
github.com/cockroachdb/cockroach/server.NewServer.func1()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:120 +0x31
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82027fa80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 25 [select]:
github.com/cockroachdb/cockroach/storage.(*StorePool).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:213 +0x1b6
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82027fb60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 26 [runnable]:
github.com/cockroachdb/cockroach/util.NewFeed.func1()
	/go/src/github.com/cockroachdb/cockroach/util/feed.go:61 +0x157
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82026b5f0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 27 [select]:
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).startStats(0xc82024c5a0)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:214 +0xca5
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).(github.com/cockroachdb/cockroach/kv.startStats)-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:201 +0x20
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82026b640)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 28 [select]:
github.com/cockroachdb/cockroach/sql.(*LeaseManager).RefreshLeases.func1()
	/go/src/github.com/cockroachdb/cockroach/sql/lease.go:617 +0xe0f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82027bda0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 29 [select]:
github.com/cockroachdb/cockroach/sql.newExecutor.func1()
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:97 +0x134
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82027bef0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 30 [IO wait]:
net.runtime_pollWait(0x7f756e62ded8, 0x72, 0xc820016150)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202679c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202679c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820267960, 0x0, 0x7f7570e80968, 0xc8203d0ee0)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200f65d8, 0xc800000000, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc820302210)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 31 [chan receive]:
github.com/cockroachdb/cockroach/util.ListenAndServe.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:88 +0x5b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82027fea0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 32 [chan receive]:
github.com/cockroachdb/cockroach/gossip.(*server).start.func2()
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:270 +0x5e
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82027ff20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 33 [select]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).bootstrap.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:549 +0x2b5
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82027ff40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 34 [select]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).manage.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:583 +0x32d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82027ff60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 35 [select]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).maybeWarnAboutInit.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:689 +0x555
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201deaf0, 0xc82027ff80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 11 [IO wait]:
net.runtime_pollWait(0x7f756e62de18, 0x72, 0xc820016150)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203d8220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203d8220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203d81c0, 0xc820093400, 0x400, 0x400, 0x0, 0x7f7570e7c050, 0xc820016150)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026188, 0xc820093400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*conn).serve(0xc8203ad3f0)
	/usr/local/go/src/net/http/server.go:1303 +0x31a
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 12 [runnable]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8201ba780)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:122
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:124 +0x490
W0106 10:54:17.791322 17171 rpc/client.go:300  dial tcp 0.0.0.0:32774: getsockopt: connection refused
I0106 10:54:18.985216 17171 acceptance/chaos_test.go:103  client 1 shutting down
I0106 10:54:18.985346 17171 acceptance/chaos_test.go:211  6 0.5/sec
I0106 10:54:18.985643 17171 acceptance/cluster/localcluster.go:537  stopping
I0106 10:54:19.852425 17171 acceptance/cluster/localcluster.go:576  node 2: stderr at /tmp/circle-artifacts.89V6zfc/acceptance/TestChaos/roach2.local/stderr.2016-01-06T10_54_19Z.log
--- FAIL: TestChaos (23.12s)
	localcluster.go:509: expected event &{0 restart}, got &{2 die} (after [{2 die} {2 restart} {0 die}])
=== RUN   TestGossipPeerings
I0106 10:54:22.111884 17171 acceptance/cluster/localcluster.go:213  started docker-spy: 172.17.0.17
I0106 10:54:22.111909 17171 acceptance/cluster/localcluster.go:220  initializing cluster
I0106 10:54:24.251002 17171 acceptance/cluster/localcluster.go:337  creating ca (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.704649997
I0106 10:54:24.292254 17171 acceptance/cluster/localcluster.go:342  creating node (1024bit) certs in: /home/ubuntu/cockroach/.localcluster.certs.704649997
I0106 10:54:26.858458 17171 acceptance/cluster/localcluster.go:393  *** started roach0.local ***
  ui:    https://0.0.0.0:32777
  trace: https://0.0.0.0:32777/debug/requests
  logs:  /tmp/circle-artifacts.89V6zfc/acceptance/TestGossipPeerings/roach0.local/cockroach.INFO
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:32: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	main_test.go:57: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
one more in the "new or rediscovered raft races" category, though it's probably easier to fix the others first.
