### ISSUE TITLE
storage: deadlocks due to invalid lock ordering

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#36413]
Follow-up to https://github.com/cockroachdb/cockroach/pull/36401#issuecomment-478925080. We saw a deadlock in the decommissioning roachtest in which one node permanently refused snapshots (due to already applying one). Digging in the goroutines we found the following:

Thanks to the `debug zip`, we get to look at a stack dump of n1. Look at this:

```
goroutine 142 [semacquire, 9 minutes]:
sync.runtime_SemacquireMutex(0xc00588608c, 0xc006243900)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc005886088)
	/usr/local/go/src/sync/mutex.go:134 +0xff
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).maybeInitializeRaftGroup(0xc005886000, 0x3b07840, 0xc007f564e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_init.go:272 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).maybeAddLocked(0xc000101800, 0x3b07840, 0xc007f564e0, 0xc005886000, 0x15917d314376d5a9, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:438 +0x56b
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).MaybeAdd(0xc000101800, 0xc005886000, 0x15917d314376d5a9, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:412 +0xe1
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).waitAndProcess(0xc000c18000, 0x3b07840, 0xc000a18090, 0xc0009a8000, 0x3735e464, 0xed4349464, 0x0, 0xc005886000, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:235 +0x2f4
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1.1(0xc005886000, 0xc00081e701)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:283 +0x81
github.com/cockroachdb/cockroach/pkg/storage.(*storeReplicaVisitor).Visit(0xc00081e7b0, 0xc007eb6840)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:340 +0x1b8
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1(0x3b07840, 0xc000a18090)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:281 +0x1ad
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc0002fa0d0, 0xc0009a8000, 0xc000368140)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8
```

This is trying to get the `raftMu`. Shouldn't take 9 minutes.

```
goroutine 3638 [semacquire, 1 minutes]:
sync.runtime_SemacquireMutex(0xc0009a7064, 0x9e5600)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0009a7060)
	/usr/local/go/src/sync/mutex.go:134 +0xff
sync.(*RWMutex).Lock(0xc0009a7060)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/cockroachdb/cockroach/pkg/storage.(*Store).canApplySnapshot(0xc0009a6c00, 0x3b07840, 0xc006a36420, 0xc00010fd40, 0xc000324e00, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store_snapshot.go:414 +0x54
github.com/cockroachdb/cockroach/pkg/storage.(*Store).receiveSnapshot(0xc0009a6c00, 0x3b07840, 0xc006a36420, 0xc00010fd40, 0x7f300496d880, 0xc006289970, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store_snapshot.go:628 +0xf6
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc0009a6c00, 0xc00010fd40, 0x7f300496d850, 0xc006289970, 0xc006289970, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3147 +0x203
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x3b2c280, 0xc006289970, 0xc000a342c0, 0x3b07840, 0xc006a362d0, 0x99a702, 0xc0074c1030)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:386 +0x13b
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x3b07840, 0xc006a362d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:387 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0009a8000, 0x3b07840, 0xc006a362d0, 0xc00690bc80, 0x32, 0x0, 0x0, 0xc006a36300)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:325 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320 +0x134
```

This is trying to get `Store.mu`. Shouldn't take a minute. We see more stacks like that with higher wait times; I think we get a new one each time a new snapshot comes in.

I also suspect that explains this goroutine

```
goroutine 1652 [select, 9 minutes]:
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot(0xc000a342c0, 0x3b2c280, 0xc0073eaef0, 0x3ae2940, 0xc000a342c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:391 +0x1ce
github.com/cockroachdb/cockroach/pkg/storage._MultiRaft_RaftSnapshot_Handler(0x32ef540, 0xc000a342c0, 0x3b243c0, 0xc0077f4bb0, 0x97b9f8, 0x20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go:695 +0xad
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func3(0x32ef540, 0xc000a342c0, 0x3b243c0, 0xc0077f4bb0, 0xc007e78ba0, 0x34fec98, 0x3b085c0, 0xc000444ac0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:239 +0x100
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc0009ae1c0, 0x3b30840, 0xc00527c600, 0xc0063cd700, 0xc0006414d0, 0x57d1e20, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1167 +0x440
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0009ae1c0, 0x3b30840, 0xc00527c600, 0xc0063cd700, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1253 +0x12aa
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc005c6ae30, 0xc0009ae1c0, 0x3b30840, 0xc00527c600, 0xc0063cd700)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:680 +0x9f
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:678 +0xa1
```

and this

```
goroutine 667 [semacquire, 9 minutes]:
sync.runtime_SemacquireMutex(0xc0001018c4, 0x3ada900)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0001018c0)
	/usr/local/go/src/sync/mutex.go:134 +0xff
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).Add(0xc000101800, 0xc006704f00, 0x0, 0x3b07800, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:397 +0x50
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleRaftResponse(0xc0009a6c00, 0x3b07840, 0xc006532e10, 0xc007ab9880, 0x1, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3573 +0x7ff
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).processQueue.func1.1.1(0x3b2c160, 0xc005d67940, 0xc0008873c0, 0xc000a342c0, 0x3b07840, 0xc0066db290, 0x99a702, 0xc000000008)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:440 +0x16a
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).processQueue.func1.1(0x3b07840, 0xc0066db290)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:444 +0x66
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc005d67960, 0xc0009a8000, 0xc0066db260)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8
```

Now where it gets interesting is this goroutine. This is also stuck on the store mutex, but it holds a replica's raftMu already. (This is the correct locking order, but still). The question is basically, who holds the store mutex?

```
goroutine 1635 [semacquire, 9 minutes]:
sync.runtime_SemacquireMutex(0xc0009a7064, 0xc007df0b00)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0009a7060)
	/usr/local/go/src/sync/mutex.go:134 +0xff
sync.(*RWMutex).Lock(0xc0009a7060)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/cockroachdb/cockroach/pkg/storage.(*Store).removeReplicaImpl(0xc0009a6c00, 0x3b07800, 0xc007ef6900, 0xc005886000, 0x100000008, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2520 +0x54d
github.com/cockroachdb/cockroach/pkg/storage.(*Store).RemoveReplica(0xc0009a6c00, 0x3b07800, 0xc007ef6900, 0xc005886000, 0x100000008, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2446 +0xa8
github.com/cockroachdb/cockroach/pkg/storage.(*replicaGCQueue).process(0xc00034a240, 0x3b07800, 0xc007ef6900, 0xc005886000, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_gc_queue.go:291 +0x306
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica.func1(0x3b07800, 0xc007ef6900, 0xdf8475800, 0x3b07800)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:753 +0x24e
github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout(0x3b07800, 0xc007ef6900, 0xc0063f96e0, 0x22, 0xdf8475800, 0xc0062a7e90, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:90 +0xb5
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica(0xc000101800, 0x3b07840, 0xc007eb92c0, 0xc005886000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:719 +0x215
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1.2(0x3b07840, 0xc007eb9290)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:646 +0xb8
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0009a8000, 0x3b07840, 0xc007eb9290, 0xc0063f96b0, 0x2d, 0x0, 0x0, 0xc007f3a1e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:325 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320 +0x134
```

It's not this snapshot application, because that too wants the store mu (but this goroutine explains why we're "busy applying snapshots" all the time):

```
goroutine 1651 [semacquire, 9 minutes]:
sync.runtime_SemacquireMutex(0xc0009a7064, 0x149fc2600)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0009a7060)
	/usr/local/go/src/sync/mutex.go:134 +0xff
sync.(*RWMutex).Lock(0xc0009a7060)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applySnapshot(0xc007d8d400, 0x3b07840, 0xc007f56780, 0x1f42ce2b7b80c2a3, 0x20524b652b0df489, 0xc007f54580, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raftstorage.go:967 +0xf30
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest.func1(0x3b07840, 0xc007f56780, 0xc007d8d400, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3481 +0x581
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc0009a6c00, 0x3b07840, 0xc007f56780, 0xc006387248, 0xc007bbb7c8, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3269 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest(0xc0009a6c00, 0x3b07840, 0xc007f3cba0, 0xc006387200, 0x1f42ce2b7b80c2a3, 0x20524b652b0df489, 0xc007f54580, 0x1, 0x1, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3325 +0xd5
github.com/cockroachdb/cockroach/pkg/storage.(*Store).receiveSnapshot(0xc0009a6c00, 0x3b07840, 0xc007f3cba0, 0xc006387200, 0x7f300496d880, 0xc0073eae20, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store_snapshot.go:661 +0x313
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc0009a6c00, 0xc006387200, 0x7f300496d850, 0xc0073eae20, 0xc0073eae20, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3147 +0x203
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x3b2c280, 0xc0073eae20, 0xc000a342c0, 0x3b07840, 0xc007f3cb10, 0x99a702, 0xc0054ce130)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:386 +0x13b
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x3b07840, 0xc007f3cb10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:387 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0009a8000, 0x3b07840, 0xc007f3cb10, 0xc007f62440, 0x32, 0x0, 0x0, 0xc007f3cb40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:325 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320 +0x134
```

Aha! This one holds the store mu, and it's in turn blocked on the `baseQueue.mu`:

```
goroutine 1653 [semacquire, 9 minutes]:
sync.runtime_SemacquireMutex(0xc0001018c4, 0x0)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0001018c0)
	/usr/local/go/src/sync/mutex.go:134 +0xff
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).Add(0xc000101800, 0xc005886000, 0x3ff0000000000000, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:397 +0x50
github.com/cockroachdb/cockroach/pkg/storage.(*Store).canApplySnapshotLocked(0xc0009a6c00, 0x3b07840, 0xc007f3ce40, 0xc006387680, 0x99a700, 0x0, 0xc007806480, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store_snapshot.go:592 +0x5d3
github.com/cockroachdb/cockroach/pkg/storage.(*Store).canApplySnapshot(0xc0009a6c00, 0x3b07840, 0xc007f3ce40, 0xc006387680, 0xc007e78b00, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store_snapshot.go:416 +0xaf
github.com/cockroachdb/cockroach/pkg/storage.(*Store).receiveSnapshot(0xc0009a6c00, 0x3b07840, 0xc007f3ce40, 0xc006387680, 0x7f300496d880, 0xc0073eaef0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store_snapshot.go:628 +0xf6
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc0009a6c00, 0xc006387680, 0x7f300496d850, 0xc0073eaef0, 0xc0073eaef0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3147 +0x203
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x3b2c280, 0xc0073eaef0, 0xc000a342c0, 0x3b07840, 0xc007f3cdb0, 0x99a702, 0xc0059189f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:386 +0x13b
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x3b07840, 0xc007f3cdb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:387 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0009a8000, 0x3b07840, 0xc007f3cdb0, 0xc007f624c0, 0x32, 0x0, 0x0, 0xc007f3cde0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:325 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320 +0x134
```

We've already seen a goroutine (the first posted here) that is in `(*baseQueue).maybeAddLocked`, so it presumably holds that very mutex. That goroutine itself wants the replica raft mu. We've also seen another goroutine that already holds that raftMu and was itself blocked for the store mu. Deadlock!

The lock order is

https://github.com/cockroachdb/cockroach/blob/039f754fe6a748c4d6ff09c054bd7c90750e5e6b/pkg/storage/store.go#L442-L448

and guess what, it doesn't talk about `baseQueue.mu` at all. In fact, we've found that one goroutine uses `baseQueue.mu < raftMu` and another one with `store.mu < baseQueue.mu` but that is only legit if `store.mu < raftMu` but that's just not true, it's the other way around, and so the goroutine we also see which tries to employ `raftMu < store.mu` (`applySnapshot`) deadlocks.

It gets better - we have a tool for this job, the deadlock detector:

`make test PKG=./pkg/storage/ TESTFLAGS=-v TAGS=deadlock` immediately finds deadlocks. Even better, it finds this **exact** deadlock and all it took was 20s.

```
POTENTIAL DEADLOCK: Inconsistent locking. saw this ordering in one goroutine:
happened before
store.go:3948 storage.(*Store).tryGetOrCreateReplica { repl.raftMu.Lock() // not unlocked } <<<<<
store.go:3917 storage.(*Store).getOrCreateReplica { r, created, err := s.tryGetOrCreateReplica( }
store.go:3257 storage.(*Store).withReplicaForRequest { r, _, err := s.getOrCreateReplica( }
store.go:3610 storage.(*Store).processRequestQueue { pErr := s.withReplicaForRequest(info.respStream.Context(), info.req, }
scheduler.go:225 storage.(*raftScheduler).worker { s.processor.processRequestQueue(ctx, id) }
scheduler.go:165 storage.(*raftScheduler).Start.func2 { s.worker(ctx) }
../util/stop/stopper.go:200 stop.(*Stopper).RunWorker.func1 { f(ctx) }

happened after
queue.go:397 storage.(*baseQueue).Add { bq.mu.Lock() } <<<<<
replica_proposal.go:689 storage.(*Replica).handleReplicatedEvalResult { if _, err := r.store.replicaGCQueue.Add(r, replicaGCPriorityRemoved); err != nil { }
replica_proposal.go:793 storage.(*Replica).handleEvalResultRaftMuLocked { shouldAssert := r.handleReplicatedEvalResult(ctx, rResult, raftAppliedIndex, leaseAppliedIndex) }
replica_raft.go:2002 storage.(*Replica).processRaftCommand { r.handleEvalResultRaftMuLocked(ctx, lResult, }
replica_raft.go:850 storage.(*Replica).handleRaftReadyRaftMuLocked { if changedRepl := r.processRaftCommand( }
store.go:3622 storage.(*Store).processRequestQueue.func1 { if _, expl, err := r.handleRaftReadyRaftMuLocked(ctx, noSnap); err != nil { }
store.go:3269 storage.(*Store).withReplicaForRequest { return f(ctx, r) }
store.go:3610 storage.(*Store).processRequestQueue { pErr := s.withReplicaForRequest(info.respStream.Context(), info.req, }
scheduler.go:225 storage.(*raftScheduler).worker { s.processor.processRequestQueue(ctx, id) }
scheduler.go:165 storage.(*raftScheduler).Start.func2 { s.worker(ctx) }
../util/stop/stopper.go:200 stop.(*Stopper).RunWorker.func1 { f(ctx) }
```

It's unfortunate that we stopped running that. We need to bring it back.

**Comment by nvanbenschoten** [comment]
@tbg did you mean to close this from https://github.com/cockroachdb/cockroach/pull/36415?

**Comment by tbg** [comment]
Yep, thanks!
