### ISSUE TITLE
invalid cast causes service panic

### ISSUE THREAD

**Issue by Dmole** [cockroachdb/cockroach#36594]
**Describe the problem**
Invalid cast causes service panic

**To Reproduce**
Connect a PG app to cockroach
(I can make a minimal test case if it would help but I suspect the stack trace below is all that is required to fix the issue)

**Expected behavior**
Server do the requested action or return an error code

**Actual behavior**
Crash

**Additional data**
client:
```
 java.sql.SQLException: An I/O error occured while sending to the backend. (UPDATE CONTENT_TYPES SET  SMALL_ICON = ? WHERE CONTENT_TYPES.SITE_OID = ? AND ( CONTENT_TYPES.object_id = ? ))
 	...
 Caused by: org.postgresql.util.PSQLException: An I/O error occured while sending to the backend.
 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:281)
 	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
 	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:410)
 	...
 	... 4 more
 Caused by: java.io.EOFException
 	at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:271)
 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1700)
 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
 	... 8 more
```

server:
```
*
* ERROR: [n1,client=192.168.0.112:44344,user=user] a SQL panic has occurred while executing "UPDATE content_types SET small_icon = $1 WHERE (content_types.site_oid = $2) AND (content_types.object_id = $3)": failed to serialize placeholder: invalid cast: bytes -> OID
*
*
* ERROR: [n1,client=192.168.0.112:44344,user=user] a panic has occurred!
*
panic while executing 1 statements: UPDATE _ SET _ = $1 WHERE (_._ = $2) AND (_._ = $3); caused by failed to serialize placeholder: invalid cast: bytes -> OID

goroutine 3162 [running]:
runtime/debug.Stack(0x305ac80, 0xc4274d3c80, 0x3)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x305ac80, 0xc4274d3c80, 0xc420245980, 0x296e980, 0xc427ff2a20, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc427fc0000, 0x305ac80, 0xc4274d3c80, 0x268ddc0, 0xc42775c450)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:645 +0x2df
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc427fc0000, 0x305ac80, 0xc4274d3c80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
panic(0x268ddc0, 0xc42775c450)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan.exprFmtCtxBase.func1(0xc427ff2840, 0xc420320280)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/expression.go:40 +0x105
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*Placeholder).Format(0xc420320280, 0xc427ff2840)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:721 +0x3e
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants(0xc427ff2840, 0x302df40, 0xc420320280)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:47 +0xa4
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode(0xc427ff2840, 0x302df40, 0xc420320280)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:276 +0x8d
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan.MakeExpression(0x306fd20, 0xc420320280, 0xc427fc04b0, 0xc4264ccdc0, 0x8, 0x8, 0x0, 0x0, 0xc428e0ff70, 0x2, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/expression.go:84 +0x1d2
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan.(*PhysicalPlan).AddRendering(0xc426e3f070, 0xc427b6d4d0, 0x9, 0x9, 0xc427fc04b0, 0xc4264ccdc0, 0x8, 0x8, 0xc428985c00, 0x9, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/physical_plan.go:490 +0x225
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).selectRenders(0xc4208cd700, 0xc426e3f070, 0xc42566eb00, 0xc427fc04b0, 0xc4293d3380, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1160 +0x2e1
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc4208cd700, 0xc42633e0c0, 0x304dd40, 0xc42566eb00, 0xc4293d3380, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2283 +0xd8b
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).wrapPlan.func1(0x305ad40, 0xc4292fbaa0, 0x2ade161, 0x6, 0x304dd40, 0xc42566eb00, 0x1, 0xdcb4717800000000, 0xc426e3f110)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2437 +0x1c4
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc4203dda40, 0x304dd40, 0xc42566eb00, 0x2ade161, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:124 +0x4e5e
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc4203dda40, 0x304dd40, 0xc42566eb00, 0x6, 0x304e480)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:101 +0x8f
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc4203dda40, 0x304e480, 0xc42920c000, 0x2ade5a5, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:455 +0x1f9c
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitConcrete(0xc4203dda40, 0x304e480, 0xc42920c000)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:114 +0x83
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc4203dda40, 0x304ddc0, 0xc429b7e0e0, 0x2adbb23, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:468 +0x3991
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc4203dda40, 0x304ddc0, 0xc429b7e0e0, 0xc426e41348, 0x6c4079)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:101 +0x8f
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x305ad40, 0xc4292fbaa0, 0x304ddc0, 0xc429b7e0e0, 0x0, 0xc4256551c0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:65 +0x193
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).wrapPlan(0xc4208cd700, 0xc42633e0c0, 0x304ddc0, 0xc429b7e0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2412 +0x205
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc4208cd700, 0xc42633e0c0, 0x304ddc0, 0xc429b7e0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2366 +0x15e
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc4208cd700, 0x305ad40, 0xc4292fbaa0, 0xc427fc04b0, 0xc42633e0c0, 0xc4295d3560, 0x304ddc0, 0xc429b7e0e0, 0xc424fd1b80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:752 +0x126
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc427fc0000, 0x305ad40, 0xc4292fbaa0, 0xc427fc0418, 0x2, 0x7f033af04b30, 0xc427b6d290, 0x4880300, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:982 +0x2d8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc427fc0000, 0x305ad40, 0xc4292fbaa0, 0x305ee80, 0xc4261b47e0, 0x48803c8, 0x0, 0x0, 0xc427b6b5e0, 0x6f, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:824 +0xa8a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc427fc0000, 0x305ad40, 0xc4292fbaa0, 0x305ee80, 0xc4261b47e0, 0x48803c8, 0x0, 0x0, 0xc427b6b5e0, 0x6f, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xb3b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc427fc0000, 0x305ad40, 0xc4292fbaa0, 0x305ee80, 0xc4261b47e0, 0x48803c8, 0x0, 0x0, 0xc427b6b5e0, 0x6f, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x341
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc427fc0000, 0x305ac80, 0xc4274d3c80, 0xc4201152d8, 0x5400, 0x15000, 0xc420115370, 0xc425391e50, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1175 +0x1400
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420954ff0, 0x305ac80, 0xc4274d3c80, 0xc427fc0000, 0x5400, 0x15000, 0xc420115370, 0xc425391e50, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc420954ff0, 0x305ac80, 0xc4274d3c80, 0xc427fc0000, 0x5400, 0x15000, 0xc420115370, 0xc425391e50, 0xc425391e60, 0xc4203f4720)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:313 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:312 +0x107c

*
* ERROR: [n1,client=192.168.0.112:44344,user=user] Reported as error f793c772f1d14d7a97c53ffd22933c66
*

[1]+  Exit 2                  /opt/cockroach-v2.1.6.linux-amd64/cockroach start --insecure --listen-addr=192.168.0.112
```

**Environment:**
 - CockroachDB version: 2.1.6
 - Server OS: Linux/Ubuntu 18.04.2
 - Client app: JDBC

**Additional context**
impact = service crash

**Comment by Dmole** [comment]
This is fixed in v19.1.0-rc.1 but something should be back-ported to v2.1.6 as it's still the "stable" version.

**Comment by tbg** [comment]
@jordanlewis threw this in your project, please reassign if it's not sql exec

**Comment by jordanlewis** [comment]
@solongordon could you PTAL at this bug?

**Comment by solongordon** [comment]
This looks closely related to #34429, which we closed as wontfix for 2.1. Unfortunately I don't think there is a self-contained fix we can easily backport so I'm going to do the same for this issue.

Thank you @Dmole for the report.

**Comment by Dmole** [comment]
Please do one of the following;

A) Retire 2.1 and release 19.1
B) Fix this bug
C) Remove "CockroachDB is production-ready." from the README.md

Not doing any of the above leads to brand notoriety.

**Comment by jordanlewis** [comment]
Hey @Dmole, thanks for the feedback. 19.1 is in GA - please feel free to check it out: https://www.cockroachlabs.com/docs/stable/install-cockroachdb-linux.html

**Comment by Dmole** [comment]
Thanks for retiring 2.1.
