### ISSUE TITLE
Timeout error in TestSSLEnforcement

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#3663]
Found in ebbda700220533a4e0b4b0865ddcfe6c4f808d21:
 
```
=== RUN   TestSSLEnforcement
I0107 00:54:26.334530 9132 storage/replica_command.go:1198  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1452124467.334s
I0107 00:54:26.335519 9132 server/node.go:293  initialized store store=1:1 ([]=): {Capacity:243360915456 Available:197438132224 RangeCount:0}
I0107 00:54:26.335536 9132 server/node.go:220  node ID 1 initialized
I0107 00:54:26.335587 9132 gossip/gossip.go:193  setting node descriptor node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:48623" > attrs:<> 
I0107 00:54:26.335612 9132 server/node.go:383  connecting to gossip network to verify cluster ID...
I0107 00:54:26.335688 9132 server/node.go:400  node connected via gossip and verified as part of cluster "cluster-1"
I0107 00:54:26.335767 9132 server/node.go:258  Started node with [[]=] engine(s) and attributes []
I0107 00:54:26.335811 9132 server/server.go:250  starting https server at 127.0.0.1:48623
I0107 00:54:26.335910 9132 storage/split_queue.go:97  splitting range=1 [/Min-/Max) at keys [/Table/501/0 /Table/502/0]
I0107 00:54:26.357561 9132 storage/replica_command.go:1275  initiating a split of range=1 [/Min-/Max) at key /Table/501
I0107 00:54:26.365451 9132 storage/replica_command.go:1198  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1452124467.385s
I0107 00:54:26.365554 9132 storage/replica_command.go:1275  initiating a split of range=2 [/Table/501-/Max) at key /Table/502
I0107 00:54:29.455205 9132 stopper.go:264  draining; tasks left:
1      server/server.go:365
--- FAIL: TestSSLEnforcement (3.52s)
        authentication_test.go:149: [0]: expected success=true, got err=Get https://127.0.0.1:48623/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by knz** [comment]
Note that the error is not deterministic, sometime the test passes without issues.

**Comment by tschottdorf** [comment]
Can't repro that one, but got the below after 900+ iters in `make stress PKG=./server TESTS=SSLEnforcement`

```
I0107 11:22:52.103855 91873 storage/replica_command.go:1236  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1452183773.103s
I0107 11:22:52.105592 91873 server/node.go:293  initialized store store=1:1 ([]=): {Capacity:249821663232 Available:67777568768 RangeCount:0}
I0107 11:22:52.105625 91873 server/node.go:220  node ID 1 initialized
I0107 11:22:52.105779 91873 gossip/gossip.go:193  setting node descriptor node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:53331" > attrs:<> 
I0107 11:22:52.105812 91873 server/node.go:383  connecting to gossip network to verify cluster ID...
I0107 11:22:52.106403 91873 server/node.go:400  node connected via gossip and verified as part of cluster "cluster-1"
I0107 11:22:52.106772 91873 server/node.go:258  Started node with [[]=] engine(s) and attributes []
I0107 11:22:52.106910 91873 storage/split_queue.go:97  splitting range=1 [/Min-/Max) at keys [/Table/501/0 /Table/502/0]
I0107 11:22:52.107014 91873 server/server.go:250  starting https server at 127.0.0.1:53331
I0107 11:22:52.134695 91873 storage/replica_command.go:1313  initiating a split of range=1 [/Min-/Max) at key /Table/501
I0107 11:22:52.144361 91873 storage/replica_command.go:1236  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1452183773.155s
I0107 11:22:52.144471 91873 storage/replica_command.go:1313  initiating a split of range=2 [/Table/501-/Max) at key /Table/502
I0107 11:22:52.285841 91873 context.go:121  no certificates directory specified: using insecure TLS
I0107 11:22:52.307085 91873 context.go:168  running in insecure mode, this is strongly discouraged. See --insecure and --certs.
I0107 11:22:52.308302 91873 server.go:1934  http: TLS handshake error from 127.0.0.1:53393: tls: first record does not look like a TLS handshake
I0107 11:22:52.416226 91873 server.go:1934  http: TLS handshake error from 127.0.0.1:53424: tls: first record does not look like a TLS handshake
I0107 11:22:52.572954 91873 server.go:1934  http: TLS handshake error from 127.0.0.1:53473: tls: first record does not look like a TLS handshake
I0107 11:22:52.716697 91873 server.go:1934  http: TLS handshake error from 127.0.0.1:53510: tls: first record does not look like a TLS handshake
I0107 11:22:52.887252 91873 server.go:1934  http: TLS handshake error from 127.0.0.1:53555: tls: first record does not look like a TLS handshake
panic: test timed out after 1m10s

goroutine 358 [running]:
testing.startAlarm.func1()
	/usr/local/Cellar/go/1.5.2/libexec/src/testing/testing.go:703 +0x132
created by time.goFunc
	/usr/local/Cellar/go/1.5.2/libexec/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0x50e85d0, 0x58206a0, 0x1f, 0x1f, 0x4013f01)
	/usr/local/Cellar/go/1.5.2/libexec/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc82023ef08, 0x4014462)
	/usr/local/Cellar/go/1.5.2/libexec/src/testing/testing.go:494 +0x70
github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck(0xc82023ef08)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x21
github.com/cockroachdb/cockroach/server_test.TestMain(0xc82023ef08)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/server/main_test.go:34 +0x21
main.main()
	github.com/cockroachdb/cockroach/server/_test/_testmain.go:114 +0x113

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 36 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x582e360)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1029 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:610 +0xbc

goroutine 38 [semacquire]:
sync.runtime_Semacquire(0xc8201ed8a4)
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8201ed898)
	/usr/local/Cellar/go/1.5.2/libexec/src/sync/waitgroup.go:126 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc8201ed880)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:214 +0x1af
github.com/cockroachdb/cockroach/server.(*Server).Stop(0xc8202bc000)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/server/server.go:340 +0x28
github.com/cockroachdb/cockroach/server.(*TestServer).Stop(0xc8201834a0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/server/testserver.go:271 +0x5d
runtime.Goexit()
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/panic.go:320 +0xfb
testing.(*common).FailNow(0xc820178fc0)
	/usr/local/Cellar/go/1.5.2/libexec/src/testing/testing.go:336 +0x36
testing.(*common).Fatalf(0xc820178fc0, 0x4fe2980, 0x25, 0xc8204f35b0, 0x3, 0x3)
	/usr/local/Cellar/go/1.5.2/libexec/src/testing/testing.go:379 +0x83
github.com/cockroachdb/cockroach/server.TestSSLEnforcement(0xc820178fc0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/server/authentication_test.go:149 +0x1a88
testing.tRunner(0xc820178fc0, 0x58206e8)
	/usr/local/Cellar/go/1.5.2/libexec/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/Cellar/go/1.5.2/libexec/src/testing/testing.go:561 +0x86d

goroutine 45 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8202be140)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:123 +0x3a
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:124 +0x490

goroutine 20 [semacquire]:
sync.runtime_Semacquire(0xc82052d098)
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/sema.go:43 +0x26
sync.(*Mutex).Lock(0xc82052d094)
	/usr/local/Cellar/go/1.5.2/libexec/src/sync/mutex.go:82 +0x1c4
crypto/tls.(*Conn).Close(0xc82052d080, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:947 +0x4d
github.com/cockroachdb/cockroach/util.ListenAndServe.func1()
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/net.go:82 +0x311
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201ed880, 0xc82040c000)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62

goroutine 345 [chan receive]:
net/http.(*Transport).getConn.func2.1(0xc8200a4840, 0xc8205c5d40, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:536 +0x4c
created by net/http.(*Transport).getConn.func2
	/usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:542 +0x77

goroutine 298 [IO wait]:
net.runtime_pollWait(0x76c20a8, 0x72, 0xc8200101b0)
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8207f4610, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8207f4610, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8207f45b0, 0xc8200a7c00, 0x400, 0x400, 0x0, 0x73a0050, 0xc8200101b0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8205320d0, 0xc8200a7c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820526720, 0x7604c78, 0xc8205320d0, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82052cdc0, 0x16, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).readHandshake(0xc82052cdc0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:776 +0xd3
crypto/tls.(*Conn).clientHandshake(0xc82052cdc0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/handshake_client.go:142 +0xf77
crypto/tls.(*Conn).Handshake(0xc82052cdc0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:974 +0xec
net/http.(*Transport).dialConn.func3(0xc82052cdc0, 0x0, 0xc82049e120)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:662 +0x21
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:667 +0x7bc

goroutine 327 [chan receive]:
net/http.(*Transport).dialConn(0xc8205c5d40, 0x0, 0xc8204d4b10, 0x5, 0xc8204d4b18, 0xf, 0xc8200a4240, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:668 +0x7f8
net/http.(*Transport).getConn.func4(0xc8205c5d40, 0x0, 0xc8204d4b10, 0x5, 0xc8204d4b18, 0xf, 0xc8200a4840)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
	/usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:551 +0x265

goroutine 299 [IO wait]:
net.runtime_pollWait(0x76c2168, 0x72, 0xc8200101b0)
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820afa0d0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820afa0d0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820afa070, 0xc820230000, 0x400, 0x400, 0x0, 0x73a0050, 0xc8200101b0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820532128, 0xc820230000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820526960, 0x7604c78, 0xc820532128, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82052d080, 0x16, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).readHandshake(0xc82052d080, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:776 +0xd3
crypto/tls.(*serverHandshakeState).readClientHello(0xc820277b28, 0xc820632b10, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/handshake_server.go:107 +0x5b
crypto/tls.(*Conn).serverHandshake(0xc82052d080, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/handshake_server.go:48 +0xab
crypto/tls.(*Conn).Handshake(0xc82052d080, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:976 +0x169
net/http.(*conn).serve(0xc820afc0b0)
	/usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1303 +0x31a
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1910 +0x3f6


ERROR: exit status 2

```

**Comment by tschottdorf** [comment]
@mjibson, assigned you for some clean shutdown fun.

this guy here (notice the `RunWorker`) blocks the stopper shutdown (goroutine 38).
```
goroutine 20 [semacquire]:
sync.runtime_Semacquire(0xc82052d098)
    /usr/local/Cellar/go/1.5.2/libexec/src/runtime/sema.go:43 +0x26
sync.(*Mutex).Lock(0xc82052d094)
    /usr/local/Cellar/go/1.5.2/libexec/src/sync/mutex.go:82 +0x1c4
crypto/tls.(*Conn).Close(0xc82052d080, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:947 +0x4d
github.com/cockroachdb/cockroach/util.ListenAndServe.func1()
    /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/net.go:82 +0x311
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201ed880, 0xc82040c000)
    /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
    /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x62
```

I didn't see the timeout error in the initial post locally. @knz, does this easily repro? Could you debug it, for example by panicking the test after `2s` and checking the traces?

**Comment by bdarnell** [comment]
It's shutting down after a faillure, which is always dicy. It's lost the original context so it may have been the same failure that started this thread. (This is why I always check for `t.Failed()` in recovery handlers, although this was just reversed in a66bd57b2 for some other tests. IMHO it's much better to allow the leak even if it causes spurious failures in other tests than to make the primary failure harder to diagnose).

```
    /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/server/server.go:340 +0x28
github.com/cockroachdb/cockroach/server.(*TestServer).Stop(0xc8201834a0)
    /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/server/testserver.go:271 +0x5d
runtime.Goexit()
    /usr/local/Cellar/go/1.5.2/libexec/src/runtime/panic.go:320 +0xfb
testing.(*common).FailNow(0xc820178fc0)
    /usr/local/Cellar/go/1.5.2/libexec/src/testing/testing.go:336 +0x36
testing.(*common).Fatalf(0xc820178fc0, 0x4fe2980, 0x25, 0xc8204f35b0, 0x3, 0x3)
    /usr/local/Cellar/go/1.5.2/libexec/src/testing/testing.go:379 +0x83
github.com/cockroachdb/cockroach/server.TestSSLEnforcement(0xc820178fc0)
    /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/server/authentication_test.go:149 +0x1a88
```

**Comment by tschottdorf** [comment]
Hmm. Both options kind of suck. The main issue with just stalling the test is that we never see to get the original error message, right? It seems that if we rigged things so that `t.{Error,Fatal}f` immediately logged the error, that problem would be gone. Maybe a mild wrapper around `*testing.T` (or reduced to `util.Tester`)? That loses the file:line, but we can at least log the right thing. Not ideal, but preferable (I wish `testing.T` were an interface, then `MainTest` could abstract some of this away).

```go
// in testutils?
type T struct {
  testing.T
}

func (t *T) Errorf(msg string, args ...interface{}) {
   file, line, _ := caller.Lookup(1)
   log.Errorf(file+":"+line+": "+msg, args...)
   t.Errorf(msg, args)
}
```

**Comment by tschottdorf** [comment]
with an extra `log.Warning(err)` before the `t.Fatal`, I can confirm that this is the same bug/timeout.

**Comment by bdarnell** [comment]
Other options include making `leaktest` report at most one failure per process, or making `leaktest` panic instead of `t.Fatal` so we don't even run the rest of the tests (which won't be able to pass anyway due to the leaks). Or we could label bugs with the first test that failed instead of all tests; we didn't care about the imprecise nature of `leaktest` before we started using per-test labels.

**Comment by mjibson** [comment]
I ran

```
make stress 'PKG=./server' 'TESTS=SSLEnforcement' 'STRESSFLAGS=-p 16'
```

for 5600 tests with 0 failures. Are there better ways to try to reproduce this? Maybe it's fixed?

**Comment by petermattis** [comment]
Sometimes a failure might be related to other tests in the package. Try `make stress PKG=./server STRESSFLAGS='-p 16'`.

**Comment by mjibson** [comment]
I tried that but only found failures in other cases. Not working on this issue anymore until it shows up in a repro somewhere.

**Comment by tschottdorf** [comment]
@knz, can you still repro this? If so, how?

**Comment by knz** [comment]
Issue disappeared after upgrading to e6f7281061b5258660a5218e664b8275335a8849.
