### ISSUE TITLE
distsql: panic in apply join

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#36722]
Logic test repro:
```
# LogicTest: fakedist-opt

statement ok 
CREATE TABLE x (a int primary key, b int); CREATE TABLE y (u int primary key, v int) ;INSERT INTO x VALUES (1, 10), (2, 20), (3, 30); INSERT INTO y VALUES (4, 40), (5, 50), (6, 60)

query I
SELECT (SELECT sum(b) FROM y LIMIT 1) FROM x
----
60
```

opt plan:
```
opt
SELECT (SELECT sum(b) FROM y LIMIT 1) FROM x
----
project
 ├── columns: sum:8(decimal)
 ├── left-join-apply
 │    ├── columns: sum:6(decimal) sum:7(decimal)
 │    ├── scalar-group-by
 │    │    ├── columns: sum:6(decimal)
 │    │    ├── project
 │    │    │    ├── columns: b:5(int)
 │    │    │    ├── scan x
 │    │    │    │    └── columns: x.b:2(int)
 │    │    │    └── projections
 │    │    │         └── variable: x.b [type=int]
 │    │    └── aggregations
 │    │         └── sum [type=decimal]
 │    │              └── variable: b [type=int]
 │    ├── project
 │    │    ├── columns: sum:7(decimal)
 │    │    ├── scan y
 │    │    │    └── limit: 1
 │    │    └── projections
 │    │         └── variable: sum [type=decimal]
 │    └── filters (true)
 └── projections
      └── variable: sum [type=decimal]
```

panic:
```
panic: invalid datum type given: decimal, expected unknown [recovered]
	panic: panic while executing 1 statements: SELECT (SELECT sum(_) FROM _ LIMIT _) FROM _; caused by invalid datum type given: decimal, expected unknown

goroutine 1329 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc000c3bb00, 0x6c7a440, 0xc000f4c480, 0x61e9ce0, 0xc002e82930)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:723 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc000c3bb00, 0x6c7a440, 0xc000f4c480)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:435 +0x61
panic(0x61e9ce0, 0xc002e82930)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:172 +0x25d
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc002e77400, 0xc000c3be50, 0x6c7b280, 0xc002ec9200, 0x0)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:186 +0x54e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x6c7a500, 0xc002eed5f0, 0x6c83f80, 0xc002e77400, 0x6c6e680, 0xc002ece700)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:174 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc002e77400, 0x6c7a500, 0xc002eed5f0)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:814 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc0028e0b40, 0x6c7a500, 0xc002eed5f0, 0x6708438, 0x0, 0x0)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:626 +0x1e9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000469400, 0xc002ec2de0, 0xc002e841b0, 0xc0010f8860, 0xc0018b22c0, 0xc000c3bf10, 0x0)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8a0
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc000469400, 0x6c7a500, 0xc002eecbd0, 0xc000c3bf10, 0xc002ec2de0, 0xc002e841b0, 0x6c7be40, 0xc00159cea0, 0xc0018b22c0)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:840 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc000c3bb00, 0x6c7a500, 0xc002eecbd0, 0xc000c3be50, 0x3, 0xde5b430, 0xc001d18e70, 0x0, 0x0, 0x0)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1121 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc000c3bb00, 0x6c7a500, 0xc002eecbd0, 0xc000c3be50, 0xde5b430, 0xc001d18e70, 0x0, 0x0)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:957 +0x658
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc000c3bb00, 0x6c7a500, 0xc002eecbd0, 0x6c7fd00, 0xc0018a2380, 0xc00286f10f, 0x2c, 0x0, 0x0, 0x0, ...)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:459 +0xe03
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc000c3bb00, 0x6c7a500, 0xc002eecbd0, 0x6c7fd00, 0xc0018a2380, 0xc00286f10f, 0x2c, 0x0, 0x0, 0x0, ...)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:101 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc000c3bb00, 0x6c7a500, 0xc002eecba0, 0x0, 0x0)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1221 +0x1acf
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc000c3bb00, 0x6c7a440, 0xc000f4c480, 0xc000448338, 0x5400, 0x15000, 0xc0004483d0, 0xc0002ae250, 0x0, 0x0)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1157 +0x1b4
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0006ca2c0, 0x6c7a440, 0xc000f4c480, 0xc000c3bb00, 0x5400, 0x15000, 0xc0004483d0, 0xc0002ae250, 0x0, 0x0)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:437 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc000270fad, 0xc0002fed80, 0x6c7a440, 0xc000f4c480, 0xc0002ae250, 0xc0006ca2c0, 0xc00077c400, 0x6c7de40, 0xc0002fed60, 0xc000d6fec0, ...)
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:581 +0x21f
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:516 +0x17b
```

I haven't investigated, but I think the opt plan looks correct, so going to assign @jordanlewis for now.

**Comment by jordanlewis** [comment]
Whoops, I gotta take a look at this.

**Comment by jordanlewis** [comment]
This was fixed by the same fix as the other apply join panic - hooray! #37597.
