### ISSUE TITLE
cli: SQL client crashes with "fatal error: unexpected signal during runtime execution"

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#36888]
**Describe the problem**

I was driving `cockroach sql` from Emacs as a comint process to use [SQL Mode](https://www.emacswiki.org/emacs/SqlMode) and crashed the SQL shell process with the message in the title of this issue.

I'm not sure how to reproduce the process-to-process communication between Emacs and CockroachDB processes, but I'll share the steps I performed.

Even though I'm not sure what was sent to `cockroach sql` I definitely didn't expect it to crash :-). However this may be a subtle form of "user error".

**To Reproduce**

1. Check out and build 8c21c8ef41

2. Start a 1-node local insecure cluster

3. In Emacs, enter the following configuration:

```lisp
(setq sql-postgres-program "cockroach")

(setq sql-postgres-options '("sql" "--insecure"))

(setq sql-postgres-login-params
      '((user :default "root")
        (database :default "")
        (server :default "localhost")
        (port :default 26257)))

(sql-set-product-feature 'postgres
                         :sqli-comint-func #'sql-comint-cockroach)

(sql-set-product-feature 'postgres
                         :prompt-regexp "^[a-z]+\@[a-zA-Z0-9\.-_]+:[0-9]+/\\([a-z]+\\)?> ")

(sql-set-product-feature 'postgres
                         :prompt-length 0)

(sql-set-product-feature 'postgres
                         :prompt-cont-regexp "^ +-> ")

(sql-set-product-feature 'postgres
                         :terminator '(";" . ";"))

(sql-set-product-feature 'postgres
                         :list-all "SHOW TABLES;")

(defun sql-comint-cockroach (product options buffer)
  "Create comint buffer and connect to CockroachDB."
  (let ((params
         (append
          (if (not (= 0 sql-port))
              (list "--port" (number-to-string sql-port)))
          (if (not (string= "" sql-user))
              (list "--user" sql-user))
          (if (not (string= "" sql-server))
              (list "--host" sql-server))
          options
          (if (not (string= "" sql-database))
              (list sql-database)))))
    (sql-comint product params)))

(defun sql-cockroach (&optional buffer)
  (interactive "P")
  (sql-postgres (if buffer buffer)))
```

4. Start the SQL shell from Emacs by entering the command `M-x sql-cockroach` defined above

5. Execute a longish-running `IMPORT` statement.

```sql
> IMPORT MYSQLDUMP 'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/employees-db/mysqldump/employees-full.sql.gz';
        job_id       |  status   | fraction_completed |  rows   | index_entries | system_records |   bytes    
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
  443603396363026433 | succeeded |                  1 | 3919015 |        331636 |              0 | 105854165  
(1 row)

Time: 1m26.775001s
```

6. Interact with the SQL shell buffer (I think I hit enter)

7. See the crash (maybe)

```
root@localhost:26257/employees> fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4c pc=0x4043450]

goroutine 0 [idle]:
runtime: unexpected return pc for runtime.sigtramp called from 0x1e
stack: frame={sp:0xc000009a70, fp:0xc000009a80} stack=[0xc000002000,0xc00000a000)
000000c000009970:  000000c000000000  0000000000000000 
000000c000009980:  0000000000000000  0000000000000000 
000000c000009990:  000000000000001e  000000000000001c 
000000c0000099a0:  000000c000009a60  000000000404455c <runtime.sigtrampgo+620> 
000000c0000099b0:  000000c004060c90  000000000000001e 
000000c0000099c0:  000000000000001c  0000000009004160 
000000c0000099d0:  0000000000000000  0000000000000000 
000000c0000099e0:  0000000000000000  0000000000000000 
000000c0000099f0:  0000000000000000  0000000000000000 
000000c000009a00:  0000000000000000  0000000009004160 
000000c000009a10:  000000000000001e  000000000000001c 
000000c000009a20:  0000000000000000  0000000000000000 
000000c000009a30:  0000000000000000  0000000000000000 
000000c000009a40:  0000000000000000  0000000000000000 
000000c000009a50:  0000000000000000  0000000000000000 
000000c000009a60:  000000c000009ab0  0000000004060c63 <runtime.sigtramp+51> 
000000c000009a70: <0000000004060c90 <runtime.cgoSigtramp+0> !000000000000001e 
000000c000009a80: >000000000000001c  0000000000003b00 
000000c000009a90:  0000000009004fa0  0000000000000016 
000000c000009aa0:  0000420100004300  0000000000004300 
000000c000009ab0:  00007fff5fbff340  0000000000000000 
000000c000009ac0:  0000000000000000  0000000000000000 
000000c000009ad0:  0000000000000000  0200013100000085 
000000c000009ae0:  00000000165f6000  0000000000000104 
000000c000009af0:  0000000000003b00  00007fff5fbff2a8 
000000c000009b00:  0000000000003b00  0000000009004fa0 
000000c000009b10:  0000420100004300  00007fff5fbff340 
000000c000009b20:  00007fff5fbff2a8  0000000000000000 
000000c000009b30:  0000000000000060  0000000000000000 
000000c000009b40:  0000000000000246  0000000009004fa0 
000000c000009b50:  0000000000000016  0000420100004300 
000000c000009b60:  0000000000004300  000000000ac29bf2 
000000c000009b70:  0000000000000247  0000000000000007 
runtime.throw(0x6b1a2f4, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2
runtime.(*sigctxt).regs(...)
	/usr/local/go/src/runtime/signal_darwin_amd64.go:16
runtime.(*sigctxt).rip(...)
	/usr/local/go/src/runtime/signal_darwin_amd64.go:37
runtime.(*sigctxt).sigpc(...)
	/usr/local/go/src/runtime/signal_amd64x.go:41
runtime.sighandler(0xc004060c90, 0x1e, 0x1c, 0x9004160)
	/usr/local/go/src/runtime/signal_sighandler.go:55 +0xd0
runtime.sigtrampgo(0x4060c90, 0x1e, 0x1c)
	/usr/local/go/src/runtime/signal_unix.go:351 +0x26c
runtime: unexpected return pc for runtime.sigtramp called from 0x1e
stack: frame={sp:0xc000009a70, fp:0xc000009a80} stack=[0xc000002000,0xc00000a000)
000000c000009970:  000000c000000000  0000000000000000 
000000c000009980:  0000000000000000  0000000000000000 
000000c000009990:  000000000000001e  000000000000001c 
000000c0000099a0:  000000c000009a60  000000000404455c <runtime.sigtrampgo+620> 
000000c0000099b0:  000000c004060c90  000000000000001e 
000000c0000099c0:  000000000000001c  0000000009004160 
000000c0000099d0:  0000000000000000  0000000000000000 
000000c0000099e0:  0000000000000000  0000000000000000 
000000c0000099f0:  0000000000000000  0000000000000000 
000000c000009a00:  0000000000000000  0000000009004160 
000000c000009a10:  000000000000001e  000000000000001c 
000000c000009a20:  0000000000000000  0000000000000000 
000000c000009a30:  0000000000000000  0000000000000000 
000000c000009a40:  0000000000000000  0000000000000000 
000000c000009a50:  0000000000000000  0000000000000000 
000000c000009a60:  000000c000009ab0  0000000004060c63 <runtime.sigtramp+51> 
000000c000009a70: <0000000004060c90 <runtime.cgoSigtramp+0> !000000000000001e 
000000c000009a80: >000000000000001c  0000000000003b00 
000000c000009a90:  0000000009004fa0  0000000000000016 
000000c000009aa0:  0000420100004300  0000000000004300 
000000c000009ab0:  00007fff5fbff340  0000000000000000 
000000c000009ac0:  0000000000000000  0000000000000000 
000000c000009ad0:  0000000000000000  0200013100000085 
000000c000009ae0:  00000000165f6000  0000000000000104 
000000c000009af0:  0000000000003b00  00007fff5fbff2a8 
000000c000009b00:  0000000000003b00  0000000009004fa0 
000000c000009b10:  0000420100004300  00007fff5fbff340 
000000c000009b20:  00007fff5fbff2a8  0000000000000000 
000000c000009b30:  0000000000000060  0000000000000000 
000000c000009b40:  0000000000000246  0000000009004fa0 
000000c000009b50:  0000000000000016  0000420100004300 
000000c000009b60:  0000000000004300  000000000ac29bf2 
000000c000009b70:  0000000000000247  0000000000000007 
runtime.sigtramp(0x1c, 0x3b00, 0x9004fa0, 0x16, 0x420100004300, 0x4300, 0x7fff5fbff340, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/sys_darwin_amd64.s:205 +0x33

goroutine 35 [syscall, 2 minutes]:
runtime.notetsleepg(0x900e800, 0x25401a5c5, 0x0)
	/usr/local/go/src/runtime/lock_sema.go:280 +0x44 fp=0xc000484f58 sp=0xc000484f18 pc=0x400d754
runtime.timerproc(0x900e7e0)
	/usr/local/go/src/runtime/time.go:288 +0x30e fp=0xc000484fd8 sp=0xc000484f58 pc=0x404f23e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000484fe0 sp=0xc000484fd8 pc=0x405f281
created by runtime.(*timersBucket).addtimerLocked
	/usr/local/go/src/runtime/time.go:170 +0x114

goroutine 1 [syscall]:
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix._C2func_go_libedit_gets(0xee40000, 0xf00d000, 0x0, 0x0, 0xc000304758, 0xc00030475c, 0x1, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:178 +0x56
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix.EditLine.GetLine.func1(0xee40000, 0xf00d000, 0x0, 0x0, 0xc000304758, 0xc00030475c, 0x1, 0xf00d000, 0x0, 0xc0004541c8)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix/editline_unix.go:282 +0xc8
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix.EditLine.GetLine(0x0, 0x20, 0x100000000000001, 0x4, 0xc0007d390d)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix/editline_unix.go:282 +0xe1
github.com/cockroachdb/cockroach/pkg/cli.(*cliState).doReadLine(0xc000105000, 0x6, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:862 +0x5ad
github.com/cockroachdb/cockroach/pkg/cli.runInteractive(0xc0004da600, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1333 +0x102
github.com/cockroachdb/cockroach/pkg/cli.runClient(0x8fbbb00, 0xc0004da600, 0xc0004da600, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1434 +0x78
github.com/cockroachdb/cockroach/pkg/cli.runTerm(0x8fbbb00, 0xc0003f64d0, 0x0, 0x7, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1421 +0xa4
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x8fbbb00, 0xc0003f64d0, 0x0, 0x7, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:69 +0x6b
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x8fbbb00, 0xc00009a9c0, 0x7, 0xc, 0x8fbbb00, 0xc00009a9c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x8fb60c0, 0x8, 0x0, 0xc000a89ed8)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0x8fb60c0, 0x18, 0xc000a89ef0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/cockroachdb/cockroach/pkg/cli.Run(0xc0000dc010, 0x8, 0x8, 0xc0000d0008, 0xc000155300)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:195 +0x65
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:70 +0x222
main.main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:30 +0x20

goroutine 20 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 21 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1224 +0xf2
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:627 +0x11e

goroutine 22 [chan receive, 2 minutes]:
github.com/cockroachdb/cockroach/pkg/util/log.signalFlusher()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:634 +0xab
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:628 +0x136

goroutine 36 [select, 2 minutes]:
github.com/cockroachdb/cockroach/vendor/go.opencensus.io/stats/view.(*worker).start(0xc00057a7c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/go.opencensus.io/stats/view/worker.go:152 +0xdd
created by github.com/cockroachdb/cockroach/vendor/go.opencensus.io/stats/view.init.0
	/go/src/github.com/cockroachdb/cockroach/vendor/go.opencensus.io/stats/view/worker.go:29 +0x57

Process SQL exited abnormally with code 2
```

**Comment by jordanlewis** [comment]
I believe this is another issue with `libedit`. @knz any ideas?

I just found this thing: https://github.com/antirez/linenoise I wonder if we can use it

**Comment by knz** [comment]
@rmloveland can you indicate: 1) version of go used to build your `cockroach` binary 2) OS+version

@jordanlewis Interesting. I like their specific scope towards vt100-like terminals, although this comes with the usual caveat that multi-line edition at the bottom of the screen often leads to surprises. Will need testing. Also casual inspection of their doc says that they don't support utf-8, which is a blocker for us.

More generally, @bdarnell and I have been exploring an entire discussion entirely, that would enable us to use GNU readline and settle that discussion for good.

**Comment by knz** [comment]
Oh I see it in the stack trace, that's go 1.11+ on macOS. Yes, I know of this bug and it's been on my radar since 1.11 was released (it's in my `go-libedit` adapter). The problem is going to be even more likely to encounter with go 1.12 builds. I want to fix this in `go-libedit` regardless of whether cockroachdb continues to use it, so thanks for pointing it out.

**Comment by bdarnell** [comment]
We used `linenoise` from #4209 to #4438. 

We've tried several go readline-like libraries and found them all lacking. Our experience suggests that we should stick with the most mature options, either libedit or readline (if we can sort out licensing issues).

**Comment by knz** [comment]
@rmloveland I believe the issue has been addressed on `master`. care to check?

**Comment by rmloveland** [comment]
@knz I'm embarrassed to admit I haven't been able to build from `master` for quite a while :-/ 
 Right now it's dying because it wants node 12, in the recent past it's been other things that would be a bit of a rabbit hole to troubleshoot - IIRC, lots of JS/Protobuf build issues that were far beyond my ken.

That said, I have not encountered this issue in a long time.  Certainly not with any of the recent 19.2 alphas, which are hopefully a decent proxy for the state of `master` (?)

**Comment by knz** [comment]
You can use `make buildshort` to create a binary without the web UI, this will ignore the node dependency.

**Comment by rmloveland** [comment]
Thanks knz - can't reproduce the crash on `master` during approx 5 minutes of testing, using the steps listed in this issue.

**Comment by knz** [comment]
cool thanks!
