### ISSUE TITLE
workload/tpcc: runtime out of memory when partitioning 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36897]
**Describe the problem**

I tried to set up a 15 node cluster to run partitoning schema change test today. 
```
Andrews-MBP-2:scripts andrewwoods$ roachprod run $CLUSTER:16 "./workload run tpcc --warehouses=10000 --partitions=5 --duration=1s --split --scatter {pgurl:1}"
```
After partitioning, I hit the following error:
```
Initializing 20000 connections...
Initializing 100000 workers and preparing statements...
fatal error: runtime: out of memory
```
Followed by a wall of runtime errors:
```
runtime stack:
runtime.throw(0x154d414, 0x16)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0x7f5fddffab30 sp=0x7f5fddffab00 pc=0x437222
runtime.sysMap(0xc730000000, 0x4000000, 0x290b6f8)
	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7 fp=0x7f5fddffab70 sp=0x7f5fddffab30 pc=0x422117
runtime.(*mheap).sysAlloc(0x28f0c60, 0x4000000, 0x0, 0x7f5fddffac58)
	/usr/local/go/src/runtime/malloc.go:619 +0x1c7 fp=0x7f5fddffabf8 sp=0x7f5fddffab70 pc=0x416017
runtime.(*mheap).grow(0x28f0c60, 0x4, 0x0)
	/usr/local/go/src/runtime/mheap.go:920 +0x42 fp=0x7f5fddffac50 sp=0x7f5fddffabf8 pc=0x42e4d2
runtime.(*mheap).allocSpanLocked(0x28f0c60, 0x4, 0x290b720, 0x0)
	/usr/local/go/src/runtime/mheap.go:848 +0x337 fp=0x7f5fddffac90 sp=0x7f5fddffac50 pc=0x42e357
runtime.(*mheap).allocManual(0x28f0c60, 0x4, 0x290b720, 0x289939850)
	/usr/local/go/src/runtime/mheap.go:788 +0x53 fp=0x7f5fddffacc8 sp=0x7f5fddffac90 pc=0x42dec3
runtime.stackpoolalloc(0x2908800, 0xc72fff6000)
	/usr/local/go/src/runtime/stack.go:179 +0x79 fp=0x7f5fddffad10 sp=0x7f5fddffacc8 pc=0x44e479
runtime.stackcacherefill(0x7f602872eb00, 0x100)
	/usr/local/go/src/runtime/stack.go:262 +0x44 fp=0x7f5fddffad40 sp=0x7f5fddffad10 pc=0x44e7b4
runtime.stackalloc(0x800, 0x152b7c0, 0x454e01)
	/usr/local/go/src/runtime/stack.go:364 +0x14d fp=0x7f5fddffadb0 sp=0x7f5fddffad40 pc=0x44ebad
runtime.malg.func1()
	/usr/local/go/src/runtime/proc.go:3292 +0x31 fp=0x7f5fddffade0 sp=0x7f5fddffadb0 pc=0x464251
runtime.malg(0xc000000800, 0x0)
	/usr/local/go/src/runtime/proc.go:3291 +0xa0 fp=0x7f5fddffae20 sp=0x7f5fddffade0 pc=0x440620
runtime.newproc1(0x15f6188, 0xc72fa77c28, 0x10, 0xc670fa2600, 0x814786)
	/usr/local/go/src/runtime/proc.go:3341 +0x45c fp=0x7f5fddffaea0 sp=0x7f5fddffae20 pc=0x440b2c
runtime.newproc.func1()
	/usr/local/go/src/runtime/proc.go:3312 +0x4f fp=0x7f5fddffaed8 sp=0x7f5fddffaea0 pc=0x4642cf
runtime.systemstack(0x7f5fd00008c0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66 fp=0x7f5fddffaee0 sp=0x7f5fddffaed8 pc=0x464ee6
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1229 fp=0x7f5fddffaee8 sp=0x7f5fddffaee0 pc=0x43bb10

goroutine 9925197 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc72fa77bd0 sp=0xc72fa77bc8 pc=0x464e70
runtime.newproc(0xc700000010, 0x15f6188)
	/usr/local/go/src/runtime/proc.go:3311 +0x6e fp=0xc72fa77c18 sp=0xc72fa77bd0 pc=0x4406be
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go(0xc701f3be00, 0xc72fdb5b60)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66 fp=0xc72fa77c48 sp=0xc72fa77c18 pc=0x814786
github.com/cockroachdb/cockroach/pkg/workload.(*MultiConnPool).PrepareEx(0xc000322040, 0x19ab880, 0xc0000400a8, 0xc04a974680, 0xb, 0x1595975, 0x77, 0x0, 0x8, 0x7f602872eb00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/pgx_helpers.go:144 +0x9c fp=0xc72fa77ca8 sp=0xc72fa77c48 pc=0xefe1bc
github.com/cockroachdb/cockroach/pkg/workload.(*SQLRunner).Init(0xc6f31b5d60, 0x19ab880, 0xc0000400a8, 0x153d442, 0x9, 0xc000322040, 0xc000608d50, 0x8, 0x8)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/sql_runner.go:124 +0x231 fp=0xc72fa77d98 sp=0xc72fa77ca8 pc=0xefeab1
github.com/cockroachdb/cockroach/pkg/workload/tpcc.createNewOrder(0x19ab880, 0xc0000400a8, 0xc0000e97c0, 0xc000322040, 0x17, 0xc71315ba40, 0x0, 0x18)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/tpcc/new_order.go:130 +0x3d9 fp=0xc72fa77e38 sp=0xc72fa77d98 pc=0x10f2d69
github.com/cockroachdb/cockroach/pkg/workload/tpcc.newWorker(0x19ab880, 0xc0000400a8, 0xc0000e97c0, 0xc000322040, 0xc701f3bda0, 0x248f, 0xc72fa8c9c0, 0x0, 0x4634d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/tpcc/worker.go:158 +0x23c fp=0xc72fa77ed8 sp=0xc72fa77e38 pc=0x10fdb9c
github.com/cockroachdb/cockroach/pkg/workload/tpcc.(*tpcc).Ops.func2(0x8, 0x15f6f70)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/tpcc/tpcc.go:571 +0x10b fp=0xc72fa77f88 sp=0xc72fa77ed8 pc=0x1106c1b
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0582ce0f0, 0xc670f74f40)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57 fp=0xc72fa77fd0 sp=0xc72fa77f88 pc=0x814867
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc72fa77fd8 sp=0xc72fa77fd0 pc=0x466f51
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```
It continuously prints this error without stopping:
```

goroutine 32319 [semacquire, 8 minutes]:
runtime.gopark(0x15f6dd8, 0x28f6460, 0xc000041911, 0x4)
	/usr/local/go/src/runtime/proc.go:302 +0xeb fp=0xc059570538 sp=0xc059570518 pc=0x438f8b
runtime.goparkunlock(0x28f6460, 0xc001cd1911, 0x4)
	/usr/local/go/src/runtime/proc.go:308 +0x53 fp=0xc059570568 sp=0xc059570538 pc=0x439033
runtime.semacquire1(0xc001cd0efc, 0x44ae00, 0x3)
	/usr/local/go/src/runtime/sema.go:144 +0x1bc fp=0xc0595705d0 sp=0xc059570568 pc=0x4499fc
sync.runtime_SemacquireMutex(0xc001cd0efc, 0x0)
	/usr/local/go/src/runtime/sema.go:71 +0x3d fp=0xc0595705f8 sp=0xc0595705d0 pc=0x44972d
sync.(*Mutex).Lock(0xc001cd0ef8)
	/usr/local/go/src/sync/mutex.go:134 +0xff fp=0xc059570638 sp=0xc0595705f8 pc=0x46f7df
github.com/cockroachdb/cockroach/vendor/github.com/jackc/pgx.(*ConnPool).PrepareEx(0xc001c7a780, 0x19ab880, 0xc0000400a8, 0xc05808d6b0, 0xb, 0x1595975, 0x77, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/jackc/pgx/conn_pool.go:458 +0x63 fp=0xc0595706e8 sp=0xc059570638 pc=0x7fed83
github.com/cockroachdb/cockroach/pkg/workload.(*MultiConnPool).PrepareEx.func1(0x8, 0x15f6f70)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/pgx_helpers.go:145 +0x8d fp=0xc059570788 sp=0xc0595706e8 pc=0xf02a4d
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc058100e10, 0xc05957c1e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57 fp=0xc0595707d0 sp=0xc059570788 pc=0x814867
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0595707d8 sp=0xc0595707d0 pc=0x466f51
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```
**To Reproduce**
```
set -euxo pipefail

export CLUSTER=andy-10k
roachprod create $CLUSTER -n 16 --clouds=aws  --aws-machine-type-ssd=c5d.4xlarge

roachprod run $CLUSTER --  "sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier /mnt/data1/; mount | grep /mnt/data1"

roachprod stage $CLUSTER:1-15 cockroach
roachprod stage $CLUSTER:16 workload

roachprod start $CLUSTER:1-15 --racks=5 

roachprod adminurl --open $CLUSTER:1

roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=10000 --db=tpcc"

roachprod run $CLUSTER:16 "./workload run tpcc --warehouses=10000 --partitions=5 --duration=1s --split --scatter {pgurl:1}"
```
**Environment:**
v19.1.0-beta.20190318-915-g0ae0dfc

**Comment by awoods187** [comment]
After ctrl C, I tried to run a debug.zip and it appears to be hung (without printing anything to the CLI).
`roachprod run $CLUSTER:1 -- ./cockroach debug zip --url {pgurl:1} debug.zip`

**Comment by awoods187** [comment]
[goroutines.txt](https://github.com/cockroachdb/cockroach/files/3087506/goroutines.txt)

**Comment by awoods187** [comment]
Debug.zip eventually completed after ~10m https://drive.google.com/open?id=1HD6j072TJdCcZkowG9tla-1RcnMUYiiA with time extract 

[extract.txt](https://github.com/cockroachdb/cockroach/files/3087536/extract.txt)

**Comment by nvanbenschoten** [comment]
This is on the client, not in the database. I think @RaduBerinde might be interested in taking a look, as it's likely related in some way to https://github.com/cockroachdb/cockroach/pull/36586.

**Comment by RaduBerinde** [comment]
@awoods187 how much RAM did each node have? (interested in the 16th node, but I assume they're the same)

**Comment by RaduBerinde** [comment]
Also, do you typically run `workload` from `master` or `release-19.1`? Just so I know if I need to backport.

**Comment by awoods187** [comment]
I typically run from master but in this case i needed 19.1 because i wanted to test schema changes (which have diverged between the two). So i do think it will need a backport. 

These are all `c5d.4xlarge` nodes which have 32GiB ram https://aws.amazon.com/blogs/aws/ec2-instance-update-c5-instances-with-local-nvme-storage-c5d/

**Comment by RaduBerinde** [comment]
I believe that you were running it from master, the change that added "Initializing 100000 workers and preparing statements" was not backported. Anyway, I'm backporting all the related changes.

**Comment by awoods187** [comment]
Yeah you are right it was master (I had a script setup that I forgot to edit). sounds good on the backport
