### ISSUE TITLE
Failed tests (10817): TestRangeReplication 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3699]
The following test appears to have failed:

[#10817](https://circleci.com/gh/cockroachdb/cockroach/10817):

```
E0108 10:39:33.409630 17266 acceptance/cluster/localcluster.go:420  node=2 status=create
E0108 10:39:33.409639 17266 acceptance/cluster/localcluster.go:420  node=2 status=start
I0108 10:39:33.411385 17266 acceptance/replication_test.go:52  waiting for first range to have 3 replicas
I0108 10:40:20.553213 17266 acceptance/replication_test.go:67  found 2 replicas
I0108 10:40:20.653914 17266 acceptance/cluster/localcluster.go:547  stopping
--- FAIL: TestRangeReplication (57.13s)
	testing.go:145: acceptance/replication_test.go:72: condition failed to evaluate within 20s: expected 3 replicas, only found 2
=== RUN   TestRuby
--- SKIP: TestRuby (0.00s)
	ruby_test.go:32: skip until docker issues fixed
=== RUN   TestSingleKey
I0108 10:40:23.811224 17266 acceptance/cluster/localcluster.go:220  started docker-spy: 172.17.0.20
I0108 10:40:23.811249 17266 acceptance/cluster/localcluster.go:227  initializing cluster
I0108 10:40:26.162731 17266 acceptance/cluster/localcluster.go:347  creating ca (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.614597630
I0108 10:40:26.225892 17266 acceptance/cluster/localcluster.go:352  creating node (1024bit) certs in: /home/ubuntu/cockroach/.localcluster.certs.614597630
I0108 10:40:28.532868 17266 acceptance/cluster/localcluster.go:403  *** started roach0.local ***
--
I0108 10:41:51.947191 17266 acceptance/status_server_test.go:53  could not GET https://0.0.0.0:32793/_status/logfiles/3 - Get https://0.0.0.0:32793/_status/logfiles/3: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I0108 10:41:55.156119 17266 acceptance/status_server_test.go:53  could not GET https://0.0.0.0:32793/_status/logfiles/3 - Get https://0.0.0.0:32793/_status/logfiles/3: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I0108 10:41:58.517057 17266 acceptance/status_server_test.go:53  could not GET https://0.0.0.0:32793/_status/logfiles/3 - Get https://0.0.0.0:32793/_status/logfiles/3: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I0108 10:42:02.269059 17266 acceptance/status_server_test.go:53  could not GET https://0.0.0.0:32793/_status/logfiles/3 - Get https://0.0.0.0:32793/_status/logfiles/3: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I0108 10:42:02.369417 17266 acceptance/cluster/localcluster.go:547  stopping
panic: test timed out after 5m0s

goroutine 187 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 3 minutes]:
testing.RunTests(0xc2dac8, 0x102e020, 0xb, 0xb, 0xde9eca678272fa00)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc82003bf08, 0xc2d390)
	/usr/local/go/src/testing/testing.go:494 +0x70
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc82003bf08)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:133 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:72 +0x113

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x1049f40)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1029 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:610 +0xbc

goroutine 8 [select, 4 minutes, locked to thread]:
runtime.gopark(0xc2e148, 0xc82002a728, 0xb0d718, 0x6, 0x431918, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002a728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002a728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 21 [syscall, 4 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 22 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:124 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:132 +0x30

goroutine 134 [select, 2 minutes]:
net/http.(*persistConn).roundTrip(0xc820426dc0, 0xc8201fbc50, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1164 +0xb0d
net/http.(*Transport).RoundTrip(0xc8201e6b40, 0xc82013dce0, 0xd7, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:235 +0x530
net/http.send(0xc82013dce0, 0x7f1f39f007e0, 0xc8201e6b40, 0xc82045f420, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0xc8204750e0, 0xc82013dce0, 0x70, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0xc8204750e0, 0xc82013dce0, 0xc2dd08, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:380 +0xbc0
--
testing.tRunner(0xc8201e6990, 0x102e0e0)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 25 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f1f37e7ea28, 0x72, 0xc820014200)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82017cd80, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82017cd80, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82017cd20, 0xc820181000, 0x1000, 0x1000, 0x0, 0x7f1f39efc050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200b8598, 0xc820181000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820128420)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 26 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc820128420)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 76 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f1f37e7e7e8, 0x72, 0xc820014200)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820462ed0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820462ed0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820462e70, 0xc8201e8000, 0x1000, 0x1000, 0x0, 0x7f1f39efc050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c098, 0xc8201e8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8205000b0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 77 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc8205000b0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 106 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc820500210)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 105 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f1f37e7e968, 0x72, 0xc820014200)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82017c290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82017c290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82017c230, 0xc8204e4000, 0x1000, 0x1000, 0x0, 0x7f1f39efc050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200b8158, 0xc8204e4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820500210)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 56 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f1f37e7e8a8, 0x72, 0xc820014200)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820446140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820446140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204460e0, 0xc8201f1000, 0x1000, 0x1000, 0x0, 0x7f1f39efc050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200b8310, 0xc8201f1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820501d90)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 57 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc820501d90)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 136 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f1f37e7e728, 0x72, 0xc820014200)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203e7e20, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203e7e20, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203e7dc0, 0xc8201e3000, 0x1000, 0x1000, 0x0, 0x7f1f39efc050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200b83c0, 0xc8201e3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820426dc0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 154 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc8203b2790)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 137 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc820426dc0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 153 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f1f37e7e4e8, 0x72, 0xc820014200)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8204d2a00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204d2a00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204d29a0, 0xc82020c000, 0x2000, 0x2000, 0x0, 0x7f1f39efc050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200b8328, 0xc82020c000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8203b2790)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 157 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f1f37e7e428, 0x72, 0xc820014200)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200afbf0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200afbf0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200afb90, 0xc8201ec000, 0x2000, 0x2000, 0x0, 0x7f1f39efc050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c3b0, 0xc8201ec000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200f0dc0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 158 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc8200f0dc0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
closing since the roachnode logs aren't very detailed and it's going to be hard to track this down to a particular location in the codebase.
