### ISSUE TITLE
importccl: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#37509]
```
IMPORT INTO INDEX (TEXT) TEXT DATA ('s');
```

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: panic while executing 1 statements: IMPORT INTO _(_) TEXT DATA (_); caused by runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1252fa9]

goroutine 713 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0008c0880, 0x3a907a0, 0xc0016e2c00, 0x2f130a0, 0x5596340)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:721 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0008c0880, 0x3a907a0, 0xc0016e2c00)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:434 +0x61
panic(0x2f130a0, 0x5596340)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr(0x3a6f3e0, 0x58aa6e0, 0x0, 0x0, 0x203000, 0x123d3c8, 0xc0012c3640)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:683 +0x209
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.FoldConstantLiterals(0x0, 0x0, 0x734d4f, 0xc0012c3700, 0x40, 0x40)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/constant.go:645 +0x4d
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheck(0x0, 0x0, 0xc0008c0be0, 0x55b72a0, 0x7f2ef37c2880, 0x0, 0xc0012c3658, 0x55b72a0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:263 +0xcf
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheckAndRequire(0x0, 0x0, 0xc0008c0be0, 0x55b72a0, 0x3303988, 0x6, 0x0, 0x1, 0x1, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:277 +0x67
github.com/cockroachdb/cockroach/pkg/sql.(*planner).TypeAsString(0xc0008c0bd0, 0x0, 0x0, 0x3303988, 0x6, 0x6, 0xc0012c3700, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:427 +0x72
github.com/cockroachdb/cockroach/pkg/ccl/importccl.importPlanHook(0x3a90860, 0xc00134c360, 0x3a959a0, 0xc001318dc0, 0x3ad9000, 0xc0008c0bd0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:133 +0x31e
github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybePlanHook(0xc0008c0bd0, 0x3a90860, 0xc00134c360, 0x3a959a0, 0xc001318dc0, 0x3a90860, 0xc00134c360, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:493 +0xd7
github.com/cockroachdb/cockroach/pkg/sql.(*planner).newPlan(0xc0008c0bd0, 0x3a90860, 0xc00134c360, 0x3a959a0, 0xc001318dc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:596 +0x200
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc0008c0bd0, 0x3a90860, 0xc00134c360, 0x3368260, 0x29)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:331 +0x140
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan(0xc0008c0880, 0x3a90860, 0xc00134c360, 0xc0008c0bd0, 0x6, 0x734d4f)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:786 +0x302
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0008c0880, 0x3a90860, 0xc00134c360, 0xc0008c0bd0, 0x7f2eefca0298, 0xc0006dfb80, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:648 +0x148
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0008c0880, 0x3a90860, 0xc00134c360, 0x3a959a0, 0xc001318dc0, 0xc00164412e, 0x2c, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:412 +0xaf1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0008c0880, 0x3a90860, 0xc00134c360, 0x3a959a0, 0xc001318dc0, 0xc00164412e, 0x2c, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:100 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc0008c0880, 0x3a90860, 0xc00134c330, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1200 +0x1ad8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0008c0880, 0x3a907a0, 0xc0016e2c00, 0xc0005670b8, 0x5400, 0x15000, 0xc000567150, 0xc000217cc0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1136 +0x1b4
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000a72840, 0x3a907a0, 0xc0016e2c00, 0xc0008c0880, 0x5400, 0x15000, 0xc000567150, 0xc000217cc0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:436 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00034d4f9, 0xc000332440, 0x3a907a0, 0xc0016e2c00, 0xc000217cc0, 0xc000a72840, 0xc00011d600, 0x3a940a0, 0xc000332400, 0xc00101d980, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:580 +0x21f
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:515 +0x17b

```

Found with RSG.

**Comment by dt** [comment]
fixed once we merged IMPORT INTO impl.
