### ISSUE TITLE
server: TestDiagnosticsResponse leaks a goroutine

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#38174]
It currently fails on master with the following leak. It only seems to fail on OSX, not on Linux.
I've bisected it to #37272
@sploiselle you want it? Or we can pass to @dt.

```
make testshort PKG=./pkg/server TESTS=TestDiagnosticsResponse

    leaktest.go:122: Leaked goroutine: goroutine 807 [chan receive]:
        net/http.(*Transport).getConn.func2.1(0xc000c9b4a0, 0x85fb2e0, 0x0, 0x0, 0x67c4ddd, 0x4, 0xc001160b40, 0x12, 0x68758f8)
        	/Users/andrei/go/src/net/http/transport.go:965 +0x4a
        created by net/http.(*Transport).getConn.func2
        	/Users/andrei/go/src/net/http/transport.go:964 +0xa6


        Leaked goroutine: goroutine 854 [IO wait]:
        internal/poll.runtime_pollWait(0xddc20f0, 0x77, 0xc000dfdb00)
        	/Users/andrei/go/src/runtime/netpoll.go:173 +0x66
        internal/poll.(*pollDesc).wait(0xc001012898, 0x77, 0xc000e39300, 0x403820e, 0xc000e39340)
        	/Users/andrei/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
        internal/poll.(*pollDesc).waitWrite(0xc001012898, 0x0, 0xc000dfdb00, 0x422118f)
        	/Users/andrei/go/src/internal/poll/fd_poll_runtime.go:94 +0x3d
        internal/poll.(*FD).WaitWrite(0xc001012880, 0x68755c0, 0x6e23da0)
        	/Users/andrei/go/src/internal/poll/fd_unix.go:497 +0x37
        net.(*netFD).connect(0xc001012880, 0x6e23da0, 0xc00141bec0, 0x0, 0x0, 0x6df55e0, 0xc001160b60, 0x0, 0x0, 0x0, ...)
        	/Users/andrei/go/src/net/fd_unix.go:152 +0x272
        net.(*netFD).dial(0xc001012880, 0x6e23da0, 0xc00141bec0, 0x6e3b3e0, 0x0, 0x6e3b3e0, 0xc0011783c0, 0x0, 0xc000e39590, 0x423ed6e)
        	/Users/andrei/go/src/net/sock_posix.go:149 +0xff
        net.socket(0x6e23da0, 0xc00141bec0, 0x6728782, 0x3, 0x2, 0x1, 0x0, 0x0, 0x6e3b3e0, 0x0, ...)
        	/Users/andrei/go/src/net/sock_posix.go:70 +0x1ab
        net.internetSocket(0x6e23da0, 0xc00141bec0, 0x6728782, 0x3, 0x6e3b3e0, 0x0, 0x6e3b3e0, 0xc0011783c0, 0x1, 0x0, ...)
        	/Users/andrei/go/src/net/ipsock_posix.go:141 +0x141
        net.(*sysDialer).doDialTCP(0xc001012800, 0x6e23da0, 0xc00141bec0, 0x0, 0xc0011783c0, 0x6404700, 0x8662190, 0x0)
        	/Users/andrei/go/src/net/tcpsock_posix.go:65 +0xc2
        net.(*sysDialer).dialTCP(0xc001012800, 0x6e23da0, 0xc00141bec0, 0x0, 0xc0011783c0, 0xc000e397c8, 0x4213a78, 0xbf392611079ea50c)
        	/Users/andrei/go/src/net/tcpsock_posix.go:61 +0xd7
        net.(*sysDialer).dialSingle(0xc001012800, 0x6e23da0, 0xc00141bec0, 0x6e060e0, 0xc0011783c0, 0x0, 0x0, 0x0, 0x0)
        	/Users/andrei/go/src/net/dial.go:556 +0x348
        net.(*sysDialer).dialSerial(0xc001012800, 0x6e23da0, 0xc00141bec0, 0xc00115a430, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        	/Users/andrei/go/src/net/dial.go:524 +0x227
        net.(*Dialer).DialContext(0xc0000ee2a0, 0x6e23d60, 0xc0000de008, 0x6728782, 0x3, 0xc001160b40, 0x12, 0x0, 0x0, 0x0, ...)
        	/Users/andrei/go/src/net/dial.go:406 +0x639
        net.(*Dialer).DialContext-fm(0x6e23d60, 0xc0000de008, 0x6728782, 0x3, 0xc001160b40, 0x12, 0x40070f3, 0x42bf929, 0xc0000de008, 0x6404820)
        	/Users/andrei/go/src/net/http/transport.go:48 +0x73
        net/http.(*Transport).dial(0x85fb2e0, 0x6e23d60, 0xc0000de008, 0x6728782, 0x3, 0xc001160b40, 0x12, 0xc001728a50, 0xc000e1cc68, 0x424840b, ...)
        	/Users/andrei/go/src/net/http/transport.go:916 +0x20f
        net/http.(*Transport).dialConn(0x85fb2e0, 0x6e23d60, 0xc0000de008, 0x0, 0x67c4ddd, 0x4, 0xc001160b40, 0x12, 0x6e50640, 0xc0002deb80, ...)
        	/Users/andrei/go/src/net/http/transport.go:1240 +0x313
        net/http.(*Transport).getConn.func4(0x85fb2e0, 0x6e23d60, 0xc0000de008, 0xc001178300, 0xc000c9b4a0)
        	/Users/andrei/go/src/net/http/transport.go:999 +0x6e
        created by net/http.(*Transport).getConn
        	/Users/andrei/go/src/net/http/transport.go:998 +0x3d7

        Leaked goroutine: goroutine 855 [select]:
        net.(*netFD).connect.func2(0x6e23da0, 0xc00141bec0, 0xc001012880, 0xc000c9b6e0, 0xc000c9b680)
        	/Users/andrei/go/src/net/fd_unix.go:129 +0xba
        created by net.(*netFD).connect
        	/Users/andrei/go/src/net/fd_unix.go:128 +0x25f
```

**Comment by tbg** [comment]
I just tried to fix this and I give up. Here's what I gave up with: https://gist.github.com/tbg/f2a720631fe388c29432e10133c2ce48

Something about the mock http server or the http client POST is leaking a goroutine. I disabled so many things that I don't know what's left.

**Comment by dt** [comment]
given the bisect points to #37272, I'd guess it isn't the mock server or the reporting thread, but rather the http client used to hit the various cloud metadata providers in that change during the generation of a report i.e. I'd expect it leaks just calling `getReportingInfo` without actually setting up a mock server and reporting it at all?

**Comment by tbg** [comment]
nvm, I kept pulling (thanks for the bisect) and thanks to some Printf and debug.Stack in net/http I see that it's `getInstanceMetadata` creating the stray connection. I still don't understand why, it looks like it's not misused and should be closed.

**Comment by tbg** [comment]
Okay, we're dialing

> tcp instance-data.ec2.internal:80

and I assume that just hangs in a way that is unfortunately leaking a goroutine on osx (but without blocking the client/test). I can probably fix that.
