### ISSUE TITLE
CockroachDB crashes after starting

### ISSUE THREAD

**Issue by basudebpalfreelancer** [cockroachdb/cockroach#38437]
**Describe the problem**

CockroachDB crashes after starting up. Error message below. I am using Windows subsystem for linux. Ubuntu 18.04 is the app name.

*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access localhost.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v19.1/secure-a-cluster.html
*
CockroachDB node starting at 2019-06-26 14:36:50.6350391 +0000 UTC (took 1.5s)
build:               CCL v19.1.2 @ 2019/06/07 17:32:15 (go1.11.6)
webui:               http://localhost:8080
sql:                 postgresql://root@localhost:26257?sslmode=disable
client flags:        cockroach <client cmd> --host=localhost:26257 --insecure
logs:                /home/r3p7i1e/Work/NodeJS/ts-gql-api/cockroach-data/logs
temp dir:            /home/r3p7i1e/Work/NodeJS/ts-gql-api/cockroach-data/cockroach-temp148714724
external I/O path:   /home/r3p7i1e/Work/NodeJS/ts-gql-api/cockroach-data/extern
store[0]:            path=/home/r3p7i1e/Work/NodeJS/ts-gql-api/cockroach-data
status:              initialized new cluster
clusterID:           06a1c48b-db39-40d5-99ce-2bdaaeb2903c
nodeID:              1
*
* ERROR: [n1,s1,r3/1:/System/{NodeLive…-tsd}] Reported as error fff2a7e82aa14388893dae2ae1ba9a28
*
F190626 14:38:01.705051 173 storage/store.go:3695  [n1,s1,r3/1:/System/{NodeLive…-tsd}] while committing batch: while committing batch: IO error: While sync_file_range offset 0 bytes 540672: /home/r3p7i1e/Work/NodeJS/ts-gql-api/cockroach-data/000003.log: Function not implemented
goroutine 173 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc0000afb00, 0xc0000afb00, 0x53daa00, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x5b64b00, 0xc000000004, 0x53daa05, 0x10, 0xe6f, 0xc00081a690, 0xe6)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x95a
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3a495c0, 0xc00982d710, 0x4, 0x2, 0x32c46c2, 0x6, 0xc0095b7eb0, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2d8
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3a495c0, 0xc00982d710, 0x1, 0x4, 0x32c46c2, 0x6, 0xc0095b7eb0, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x3a495c0, 0xc00982d710, 0x32c46c2, 0x6, 0xc0095b7eb0, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:182 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc000d6c000, 0x3a495c0, 0xc00982d710, 0x3)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3695 +0x4f4
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc000709480, 0x3a495c0, 0xc000756630)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:214 +0x258
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x3a495c0, 0xc000756630)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00029eb90, 0xc00076e000, 0xc00029eb70)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8

****************************************************************************

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

Using the instructions in the website
https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html

**Expected behavior**
Should not crash.

**Environment:**
 - CockroachDB version CCL v19.1.2 @ 2019/06/07 17:32:15 (go1.11.6)
 - Server OS: Windows subsystem for linux. Ubuntu 18.04

**Comment by basudebpalfreelancer** [comment]
It seems CockroachDB doesnot support WSL. So, closing this issuse....
