### ISSUE TITLE
make build error after registered new cluster settings

### ISSUE THREAD

**Issue by jiadexin** [cockroachdb/cockroach#38786]
**Describe the problem**

After I registered a new cluster setting, for example:
```
timeoutSetting = settings.RegisterDurationSetting(
		accessTimeout,
		"the timeout access FTP  operations",
		10*time.Minute)

```
Error occur at build time:

```
> E190704 08:49:52.229386 1 util/log/crash_reporting.go:216  a panic has occurred!
> panic: runtime error: index out of range [recovered]
>         panic: runtime error: index out of range
>  
> goroutine 1 [running]:
> github.com/cockroachdb/cockroach/pkg/util/log.RecoverAndReportPanic(0x3b63fe0, 0xc0000e8010, 0xc00081e000)
>         /work/cockroach/pkg/util/log/crash_reporting.go:101 +0x9f
> panic(0x2f993e0, 0x5997490)
>         /opt/tools/go/src/runtime/panic.go:522 +0x1b5
> github.com/cockroachdb/cockroach/pkg/settings.(*Values).settingChanged(0xc00081f980, 0x80)
>         /work/cockroach/pkg/settings/setting.go:89 +0xb3
> github.com/cockroachdb/cockroach/pkg/settings.(*Values).setInt64(...)
>         /work/cockroach/pkg/settings/setting.go:102
> github.com/cockroachdb/cockroach/pkg/settings.(*IntSetting).Override(0xc000957950, 0xc00081f980, 0x2000000)
>         /work/cockroach/pkg/settings/int.go:67 +0x6b
> github.com/cockroachdb/cockroach/pkg/settings.(*IntSetting).set(0xc000957950, 0xc00081f980, 0x2000000, 0x59b9b90, 0xc00007edd0)
>         /work/cockroach/pkg/settings/int.go:74 +0x6a
> github.com/cockroachdb/cockroach/pkg/settings.(*IntSetting).setToDefault(0xc000957950, 0xc00081f980)
>         /work/cockroach/pkg/settings/int.go:79 +0x3e
> github.com/cockroachdb/cockroach/pkg/settings.(*Values).Init(0xc00081f980, 0x30580e0, 0xc00081f980)
>         /work/cockroach/pkg/settings/setting.go:78 +0xc3

```

**Expected behavior**

I studied the error code -pkg/settings/setting.go:
```
func (sv *Values) setInt64(slotIdx int, newVal int64) {
 if atomic.SwapInt64(&sv.intVals[slotIdx-1], newVal) != newVal {
  sv.settingChanged(slotIdx)
 }
}
....
func (sv *Values) settingChanged(slotIdx int) {
 sv.changeMu.Lock()
 funcs := sv.changeMu.onChange[slotIdx]
 sv.changeMu.Unlock()
 for _, fn := range funcs {
  fn()
 }
} 
 
...
func (sv *Values) setOnChange(slotIdx int, fn func()) {
 sv.changeMu.Lock()
 sv.changeMu.onChange[slotIdx] = append(sv.changeMu.onChange[slotIdx], fn)
 sv.changeMu.Unlock()
}
```
I understand that `slotIdx` should start at 1, then we should use `slotIdx-1` to access elements, such as the `setInt64` method.
but the `settingChanged` and `setOnChange` methods directly use `slotIdx`, causing the array to be over bound.
The reason for this error should be because the number of cluster settings we have registered this time reaches the value set by `const maxSettings = 128`. When accessing the largest slotIdx, it is `onChange[128]`, and an array error occurs.

So I modified 2 methods:
```
func (sv *Values) settingChanged(slotIdx int) {
 sv.changeMu.Lock()
 funcs := sv.changeMu.onChange[slotIdx-1]
 sv.changeMu.Unlock()
 for _, fn := range funcs {
  fn()
 }
} 
 
...
func (sv *Values) setOnChange(slotIdx int, fn func()) {
 sv.changeMu.Lock()
 sv.changeMu.onChange[slotIdx-1] = append(sv.changeMu.onChange[slotIdx-1], fn)
 sv.changeMu.Unlock()
}
```

and then i can build it successfully.

**Environment:**
 - CockroachDB version v19.1
 - Server OS: ubuntu 18

**Comment by andreimatei** [comment]
It looks to me like it's indeed an oversight that the `onChange` array is indexed by `slotIdx` when all the others are indexed with `slotIdx-1`. Would you like to send a patch?

Alternatively, I'm not sure why we start these slot indexes from 1 and not 0. 0 doesn't seem to be used as a sentinel. So you can consider starting the indexes from 0 (in the `register()` function), and indexing everything by `slotIdx`.

And separately, if you'd like to also send a patch to increase `maxSettings` (since we're at 119 on master, coming up against the limit), feel free.

cc @tbg
