### ISSUE TITLE
exec: TestDrainingProcessorSwallowsUncertaintyError hangs with vectorized enabled

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#39029]
When vectorized execution is enabled by default, `TestDrainingProcessorSwallowsUncertaintyError` hangs until it times out. To reproduce, change the default `sql.defaults.experimental_vectorize` value to `on` in `exec_util.go` and then run
```
make test PKG=./pkg/sql/distsqlrun TESTS=TestDrainingProcessorSwallowsUncertaintyError TESTFLAGS='-v'
```

**Comment by solongordon** [comment]
```
goroutine 1468 [semacquire]:
sync.runtime_Semacquire(0xc0021a5468)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0021a5460)
        /usr/local/Cellar/go/1.12.6/libexec/src/sync/waitgroup.go:130 +0x65
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Wait.func1(0xc0021a52c0, 0xc0023e7860)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:672 +0x33
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Wait
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:671 +0x91

goroutine 1475 [select]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Wait(0xc0021a52c0)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:676 +0x106
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc0021a52c0, 0x7417b00, 0xc002aecbd0, 0x6dbfb88, 0x0, 0x0)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:660 +0x1fe
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000532240, 0xc002879440, 0xc002948990, 0xc002962878, 0xc001a12840, 0xc001f8ba28, 0x0, 0x0)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:346 +0x368
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc000532240, 0x7417b00, 0xc002953920, 0xc001f8ba28, 0xc002879440, 0xc002948990, 0x7419140, 0xc002908f50, 0xc001a12840, 0xc001f8b7d8)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:933 +0x217
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001f8b600, 0x7417b00, 0xc002953920, 0xc001f8b950, 0x3, 0xd3b6ef8, 0xc00010a668, 0xc002962a01, 0x0, 0x0, ...)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:902 +0x370
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001f8b600, 0x7417b00, 0xc002953920, 0xc001f8b950, 0xd3b6ef8, 0xc00010a668, 0x0, 0x0)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:734 +0x6e5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001f8b600, 0x7417b00, 0xc002953920, 0x741cc80, 0xc002ac8400, 0xc0022fb2f3, 0x4a, 0x0, 0x2, 0xc0023377a0, ...)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417 +0xb64
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001f8b600, 0x7417b00, 0xc002953920, 0x741cc80, 0xc002ac8400, 0xc0022fb2f3, 0x4a, 0x0, 0x2, 0xc0023377a0, ...)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:99 +0x4ec
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc001f8b600, 0x7417a40, 0xc002ac84c0, 0x0, 0x0)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1263 +0xec1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001f8b600, 0x7417a40, 0xc001f4df80, 0xc000105e40, 0x5400, 0x15000, 0xc000105ed8, 0xc002330b10, 0x0, 0x0)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1140 +0x1a3
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0003d7680, 0x7417a40, 0xc001f4df80, 0xc001f8b600, 0x5400, 0x15000, 0xc000105ed8, 0xc002330b10, 0x0, 0x0)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:442 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc000386c15, 0xc002896d00, 0x7417a40, 0xc001f4df80, 0xc002330b10, 0xc0003d7680, 0xc00010a000, 0x741b340, 0xc002896ce0, 0xc002878780, ...)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584 +0x21c
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:513 +0x17b

goroutine 1457 [select]:
github.com/cockroachdb/cockroach/pkg/sql/exec.(*UnorderedSynchronizer).init.func1(0xc002a4f200, 0xc002a69e90, 0x73e3cc0, 0xc000c2bce0, 0x1)
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/unorderedsynchronizer.go:143 +0x2ee
created by github.com/cockroachdb/cockroach/pkg/sql/exec.(*UnorderedSynchronizer).init
        /Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/unorderedsynchronizer.go:105 +0x167
```
Seems like it boils down to the unordered synchronizer getting stuck here:
https://github.com/cockroachdb/cockroach/blob/ec200a6f6dffbe8669b3011697a5b2aa9dc2f1cd/pkg/sql/exec/unorderedsynchronizer.go#L142-L153
I'll keep looking at this but will probably need to pull in @asubiotto to help sort out the correct behavior here.
