### ISSUE TITLE
Failed tests (11557): TestReplicateAddAndRemove

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3906]
The following test appears to have failed:

[#11557](https://circleci.com/gh/cockroachdb/cockroach/11557):

```
I0116 11:01:35.720773 952 storage/replica.go:1633  gossiping sentinel from store 1, range 1
I0116 11:01:35.722002 952 storage/replica.go:1639  gossiping first range from store 1, range 1
I0116 11:01:35.722693 952 storage/split_queue.go:97  splitting range=1 [/Min-/Max) at keys [/Table/11/0]
I0116 11:01:35.723076 952 kv/range_cache.go:128  lookup range descriptor: key=/Table/11/0
I0116 11:01:35.723217 952 kv/range_cache.go:128  lookup range descriptor: key=/Meta2/"\x93\x88"
panic: first Range is not present on any store in the multiTestContext. [recovered]
	panic: first Range is not present on any store in the multiTestContext.

goroutine 6008 [running]:
github.com/cockroachdb/cockroach/util/tracer.(*Trace).Finalize(0xc820053260)
	/go/src/github.com/cockroachdb/cockroach/util/tracer/tracer.go:148 +0x227
github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).FirstRange(0xc82016b680, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/client_test.go:407 +0x3b5
github.com/cockroachdb/cockroach/kv.(*rangeDescriptorCache).LookupRangeDescriptor.func1(0xc8204054d0, 0xc8200ab0d0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/kv/range_cache.go:152 +0x30c
github.com/cockroachdb/cockroach/kv.(*rangeDescriptorCache).LookupRangeDescriptor(0xc8204054d0, 0xc8200ab0d0, 0x3, 0x3, 0x0, 0x1, 0x0)
	/go/src/github.com/cockroachdb/cockroach/kv/range_cache.go:164 +0x2cf
github.com/cockroachdb/cockroach/kv.(*rangeDescriptorCache).LookupRangeDescriptor.func1(0xc8204054d0, 0xc8200aaab0, 0x2, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/kv/range_cache.go:158 +0x475
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc8203f5da0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 1 [chan receive]:
testing.RunTests(0x1ccd2d8, 0x23fb200, 0xe0, 0xe0, 0x1)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc820503f00, 0x1)
	/tmp/workdir/go/src/testing/testing.go:494 +0xe5
github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck(0xc820503f00)
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:37 +0x2f
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc820503f00)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:36 +0x34
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:508 +0x20a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x27431c0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1029 +0x76
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:610 +0x117

goroutine 6009 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:317 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc8203f5e00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 6014 [runnable]:
github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks.func2(0xc8201f0b00)
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:257
created by github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:272 +0x56d

goroutine 5996 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8204839a0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:123 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:124 +0x581

goroutine 5982 [chan receive]:
github.com/cockroachdb/cockroach/util.ListenAndServe.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:88 +0x7b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bbea0, 0xc8203f5620)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 6012 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:317 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc82000e560)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 5985 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:626 +0x3ee
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc8203f5680)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 5994 [select]:
github.com/cockroachdb/cockroach/storage.(*StorePool).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:213 +0x208
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bbea0, 0xc82033cd20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 5983 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1588 +0xb48
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc82044f9f0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 5981 [IO wait]:
net.runtime_pollWait(0x7f0570fb1b98, 0x72, 0xc820037bd0)
	/tmp/workdir/go/src/runtime/netpoll.go:157 +0x63
net.(*pollDesc).Wait(0xc8200526f0, 0x72, 0x0, 0x0)
	/tmp/workdir/go/src/net/fd_poll_runtime.go:73 +0x56
net.(*pollDesc).WaitRead(0xc8200526f0, 0x0, 0x0)
	/tmp/workdir/go/src/net/fd_poll_runtime.go:78 +0x44
net.(*netFD).accept(0xc820052690, 0x0, 0x7f057384f328, 0xc8203f5760)
	/tmp/workdir/go/src/net/fd_unix.go:408 +0x2f6
net.(*TCPListener).AcceptTCP(0xc820026830, 0x61a030, 0x0, 0x0)
	/tmp/workdir/go/src/net/tcpsock_posix.go:254 +0x77
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bbea0, 0xc82041fc50)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 6007 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:317 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc8203f5d80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 5984 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).Start.func3()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:566 +0x15d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc8203f5660)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 6011 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:317 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc8203f5e40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 5993 [runnable]:
sync.runtime_Semacquire(0xc82033f3bc)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc82033f3b0)
	/tmp/workdir/go/src/sync/waitgroup.go:126 +0x118
github.com/cockroachdb/cockroach/storage.(*Store).WaitForInit(0xc82033f200)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:606 +0x3e
github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).addStore(0xc82016b680)
	/go/src/github.com/cockroachdb/cockroach/storage/client_test.go:487 +0xde9
github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).Start(0xc82016b680, 0xc8205c6240, 0x4)
	/go/src/github.com/cockroachdb/cockroach/storage/client_test.go:235 +0x1468
--
testing.tRunner(0xc8205c6240, 0x23fc3b8)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 6002 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:645 +0x3ee
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc8203f56a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 5995 [select]:
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).startStats(0xc8209e3900)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:214 +0xf1a
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).(github.com/cockroachdb/cockroach/kv.startStats)-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:201 +0x2e
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bbea0, 0xc8203f8b30)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 6010 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:317 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc8203f5e20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 6015 [runnable]:
github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks.func2(0xc8201f0b00)
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:257
created by github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:272 +0x56d

goroutine 6013 [runnable]:
sync.runtime_Semacquire(0x2743200)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*Mutex).Lock(0x27431fc)
	/tmp/workdir/go/src/sync/mutex.go:82 +0x1ee
github.com/cockroachdb/cockroach/util/log.VDepth(0x6, 0x1, 0xc8203eb100)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1152 +0x9d
github.com/cockroachdb/cockroach/util/log.V(0x8b00000006, 0xc8202e78c0)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:184 +0x36
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc820245620, 0xece2c1a0f, 0x2b03cc82, 0x2742c40, 0xc8204fdef0, 0xc8200bb500, 0xc8202f9a00, 0x62787c)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:172 +0xeb
--
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:216 +0x2fe
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200bb500, 0xc82000e580)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	8.393s
=== RUN   TestBatchBasics
I0116 11:01:46.909914 1014 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I0116 11:01:46.915120 1014 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I0116 11:01:46.921665 1014 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
same error as #3903, probably not specific to that test.
