### ISSUE TITLE
replicant.db.jdbc.JDBC errors during Data Migration Process

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#39171]
Logging issues related to replicant migrations to CockroachDB

```17:40:59.913 [DEBUG] COCKROACH: active connections: 7 
17:41:00.753 [DEBUG] COCKROACH: buffer saturation: 100% 
17:41:01.599 [ERROR] SOE.CARD_DETAILS : Failed to execute insert batch 
tech.replicant.IStorage$StorageException: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY): "sql txn" id=71ba019c key=/Table/95/1/20769548/0 rw=true pri=0.00489033 stat=PENDING epo=0 ts=1564162861.586616528,1 orig=1564162861.583424543,0 max=1564162861.587696965,0 wto=false seq=101
	at tech.replicant.db.jdbc.JDBCSnapshotApplier$JDBCInsertStmtBatchFactory$JDBCInsertStmtBatch.a(SourceFile:71)
	at tech.replicant.db.DBSnapshotApplier$BatchFactory$DBInsertStmtBatch.close(SourceFile:98)
	at tech.replicant.db.DBSnapshotApplier$StmtBatchPool.a(SourceFile:333)
	at tech.replicant.db.DBSnapshotApplier.a(SourceFile:4210)
	at tech.replicant.ir.oper.InsertBatch.a(SourceFile:87)
	at tech.replicant.db.DBSnapshotApplier.a(SourceFile:679)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY): "sql txn" id=71ba019c key=/Table/95/1/20769548/0 rw=true pri=0.00489033 stat=PENDING epo=0 ts=1564162861.586616528,1 orig=1564162861.583424543,0 max=1564162861.587696965,0 wto=false seq=101
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:755)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:777)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:365)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at tech.replicant.db.jdbc.JDBCConnection.a(SourceFile:57)
	at tech.replicant.db.jdbc.JDBCSnapshotApplier$JDBCInsertStmtBatchFactory$JDBCInsertStmtBatch.a(SourceFile:69)
	... 11 common frames omitted
17:41:01.683 [ERROR] Applier error: 
java.util.concurrent.ExecutionException: tech.replicant.Applier$ApplierException: tech.replicant.IStorage$StorageException: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY): "sql txn" id=71ba019c key=/Table/95/1/20769548/0 rw=true pri=0.00489033 stat=PENDING epo=0 ts=1564162861.586616528,1 orig=1564162861.583424543,0 max=1564162861.587696965,0 wto=false seq=101
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at tech.replicant.util.Util$TaskPool.a(SourceFile:59)
	at tech.replicant.Applier.run(SourceFile:49)
	at tech.replicant.db.DBSnapshotApplier.run(SourceFile:707)
Caused by: tech.replicant.Applier$ApplierException: tech.replicant.IStorage$StorageException: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY): "sql txn" id=71ba019c key=/Table/95/1/20769548/0 rw=true pri=0.00489033 stat=PENDING epo=0 ts=1564162861.586616528,1 orig=1564162861.583424543,0 max=1564162861.587696965,0 wto=false seq=101
	at tech.replicant.db.DBApplier.a(SourceFile:82)
	at tech.replicant.db.DBSnapshotApplier.a(SourceFile:456)
	at tech.replicant.ir.oper.InsertBatch.a(SourceFile:87)
	at tech.replicant.db.DBSnapshotApplier.a(SourceFile:679)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: tech.replicant.IStorage$StorageException: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY): "sql txn" id=71ba019c key=/Table/95/1/20769548/0 rw=true pri=0.00489033 stat=PENDING epo=0 ts=1564162861.586616528,1 orig=1564162861.583424543,0 max=1564162861.587696965,0 wto=false seq=101
	at tech.replicant.db.jdbc.JDBCSnapshotApplier$JDBCInsertStmtBatchFactory$JDBCInsertStmtBatch.a(SourceFile:71)
	at tech.replicant.db.DBSnapshotApplier$BatchFactory$DBInsertStmtBatch.close(SourceFile:98)
	at tech.replicant.db.DBSnapshotApplier$StmtBatchPool.a(SourceFile:333)
	at tech.replicant.db.DBSnapshotApplier.a(SourceFile:4210)
	... 8 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY): "sql txn" id=71ba019c key=/Table/95/1/20769548/0 rw=true pri=0.00489033 stat=PENDING epo=0 ts=1564162861.586616528,1 orig=1564162861.583424543,0 max=1564162861.587696965,0 wto=false seq=101
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:755)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:777)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:365)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at tech.replicant.db.jdbc.JDBCConnection.a(SourceFile:57)
	at tech.replicant.db.jdbc.JDBCSnapshotApplier$JDBCInsertStmtBatchFactory$JDBCInsertStmtBatch.a(SourceFile:69)
	... 11 common frames omitted
17:41:01.685 [DEBUG] SQN: 0, Cursor(commit_SCN=3872035, seq_num=0)(saved) 
```

**Comment by drewdeally** [comment]
Replicant : Gaps in migration - Indexes and Constraints
Replicant would like to explore using native import command Via JDBC

**Comment by dt** [comment]
Is this just a normal "needs client-side retry" case?

**Comment by drewdeally** [comment]
Vendor stated they have client-side retry

**Comment by dt** [comment]
and this is happening on every retry?

**Comment by jordanlewis** [comment]
@drewdeally this couldn't be happening if the vendor really had proper client side retry, so closing this unless you can give more detail, thanks!

**Comment by drewdeally** [comment]
Thanks Jordon, they do have it and the retries are higher than expected.   They have since adjusted and this is no longer an issue.  You can close it as it does seem to be open for.a while

Andrew
