### ISSUE TITLE
storage: proposal quota assertion failure

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#39188]
A cluster deployed from 92fef12128c997233d985d1c19e11faac005073f hit the assertion added in #39135. The cluster had just been deployed and was running the kv50 workload in the following way on a 5 node cluster:

```
workload run kv --init --concurrency 64 --tolerate-errors --min-block-bytes=8 --max-block-bytes=128 --read-percent=50
```

https://github.com/cockroachdb/cockroach/blob/92fef12128c997233d985d1c19e11faac005073f/pkg/storage/replica_proposal_quota.go#L240-L250  

```
F190731 10:16:28.126181 158 storage/replica_proposal_quota.go:246  [n2,s2,r21/3:/Table/53{-/1/-4314…}] proposalQuotaBaseIndex (44321) + quotaReleaseQueueLen (52) = 44373 must equal the applied index (44321)
```

An observation here is that the applied index exactly equal the `proposalQuotaBaseIndex`. In theory we should only append to the `quotaReleaseQueue` when the applied index increases. How did entries make it into the quotaReleaseQueue without incrementing the applied index?

The raft log for range 21 on n2 shows entries up to `44379` and a commit index of `44373` but the `RangeAppliedState` (below) indicates that entries only up to 44321 have been applied. This however might be taken with a grain of salt as the applied state is not durably synced.
The machine did not die so my assumption would be that the write would at least make it to the WAL when the process exits and thus the current reading would reflect the last call to `Commit(false)` but I'm not all that confident in that. 

```
0.000000000,0 /Local/RangeID/21/r/RangeAppliedState (0x01699d727261736b00): raft_applied_index:44321 lease_applied_index:44243 range_stats:<last_update_nanos:1564568187766302979 gc_bytes_age:27521006 live_bytes:521113 live_count:5282 key_bytes:353414 key_count:5282 val_bytes:1761302 val_count:23729 sys_bytes:588 sys_count:4 > 
```

**Comment by ajwerner** [comment]
Okay more intrigue, the failure was actually papering over a different panic. We defer the update of the proposal quota in `handleRaftReadyRaftMuLocked` [here](https://github.com/cockroachdb/cockroach/blob/92fef12128c997233d985d1c19e11faac005073f/pkg/storage/replica_raft.go#L457). Looking at the stack trace from the fatal, we were already panicking here (full stack trace below):

https://github.com/cockroachdb/cockroach/blob/92fef12128c997233d985d1c19e11faac005073f/pkg/storage/replica_application.go#L305

This code near this panic has a nice warning:
```
	NOTE TO DEBUGGERS
		If you are here because your program panicked in this code,
		it is almost definitely the fault of code using this package,
		and very unlikely to be the fault of this code.
		The most likely scenario is that some code elsewhere is using
		a trace.Trace after its Finish method is called.
		You can temporarily set the DebugUseAfterFinish var
		to help discover where that is; do not leave that var set,
		since it makes this package much less efficient.
```
https://github.com/golang/net/blob/ca1201d0de80cfde86cb01aea620983605dfe99b/trace/trace.go#L783-L795

I'm more than happy to catch the panic in the defer and the repanic but that's not a solution. Nevertheless it's pretty clear that this assertion firing is a red herring. 

```
cockroach-cyan-02> F190731 10:16:28.126181 158 storage/replica_proposal_quota.go:246  [n2,s2,r21/3:/Table/53{-/1/-4314…}] proposalQuotaBaseIndex (44321) + quotaReleaseQueueLen (52) = 44373 must equal the applied index (44321)
goroutine 158 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc000440301, 0xc000440360, 0x0, 0xc008fce490)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1016 +0xb1
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x6bdf0c0, 0xc000000004, 0x63b9caa, 0x21, 0xf6, 0xc000b12f30, 0x8d)                                                                      
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:874 +0x92b
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4583800, 0xc009da5b30, 0xffffffff00000004, 0x2, 0x3dab1f1, 0x5e, 0xc00c4362c0, 0x4, 0x4)                                                            
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2cc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4583800, 0xc009da5b30, 0x1, 0x4, 0x3dab1f1, 0x5e, 0xc00c4362c0, 0x4, 0x4)                                                                                
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:180
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).updateProposalQuotaRaftMuLocked(0xc007348c00, 0x4583800, 0xc009da5b30, 0x3)                                                                               
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal_quota.go:246 +0x529
panic(0x38abde0, 0x678abf0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).addEvent(0xc000724b60, 0x3872580, 0xc00913c630, 0xc0069f0000)                                                                             
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:805 +0x704
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).LazyPrintf(0xc000724b60, 0x3cd1367, 0x2, 0xc0069f0a10, 0x1, 0x1)                                                                          
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:834 +0x9a
github.com/cockroachdb/cockroach/pkg/util/tracing.(*span).LogFields(0xc00b6316c0, 0xc00c229640, 0x1, 0x1)                                                                                                         
        /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tracer_span.go:393 +0x723
github.com/cockroachdb/cockroach/pkg/util/log.eventInternal(0x4583800, 0xc0082808d0, 0x100, 0x3cf1626, 0x10, 0x0, 0x0, 0x0)                                                                                       
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:128 +0x267
github.com/cockroachdb/cockroach/pkg/util/log.Event(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:154
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).stageRaftCommand(0xc007348c00, 0x4583800, 0xc0082808d0, 0xc0074f05a8, 0x45e76c0, 0xc00bf75200, 0xc009bb23a0, 0x11c5cecef74ae200)                          
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_application.go:305 +0xda6
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleCommittedEntriesRaftMuLocked(0xc007348c00, 0x4583800, 0xc009da5b30, 0xc0074de000, 0x34, 0x34, 0x0, 0x0, 0x0, 0x0, ...)                              
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_application.go:132 +0x1a1
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc007348c00, 0x4583800, 0xc009da5b30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)                                                
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:722 +0xb3a
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x4583800, 0xc009da5b30, 0xc007348c00, 0x4583800)                                                                                 
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3547 +0x120
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc000f08000, 0x4583800, 0xc009da5b30, 0xc006ba1400, 0xc00c437e98, 0x0)                                                               
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3307 +0x150
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc000f08000, 0x4583800, 0xc000a5a510, 0x15)                                                                                            
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3535 +0x200
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc000675080, 0x4583800, 0xc000a5a510)                                                                                                       
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:238 +0x214
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x4583800, 0xc000a5a510)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:161 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc0003a01b0, 0xc000d16000, 0xc000388310)                                                                                               
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xfb
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xa8
```

**Comment by nvanbenschoten** [comment]
@ajwerner and I talked this over and believe we came to a theory for how this is possible. It looks like this is fallout from aada4fcf3ff410d83a738cf16696e37357cb8d4e. We're seeing the tracing span for a proposal used after it has already been freed. This implies that we're dealing with command reproposals in Raft. Specifically, it implies that a command is finishing its application but `ProposalData.finishApplication` but not removing itself from the replica proposals map, allowing a second version of the proposal (in a later batch) apply with a bound context (with the now-freed tracing span).

The theory for what occurred here is that a command was reproposed twice, once with an old max lease index, due to a refresh of the proposals map, and once with a new max lease index, due to the original command failing to apply due to an IllegalLeaseIndexError (see `Replica.tryReproposeWithNewLeaseIndex`). The first of these reproposals attempts to apply. It doesn't remove the proposal from the proposals map because of https://github.com/cockroachdb/cockroach/blob/dbb44844e683cd28751aaa30f6817e8cb37c37a2/pkg/storage/replica_application.go#L183-L190

However, it does NOT hit an IllegalLeaseIndexError and instead fails for some other error like a NotLeaseholderError. We know that this first reproposal will fail, but we aren't guaranteed that it will fail because of an IllegalLeaseIndexError. This causes us to fail to unbind the proposal in https://github.com/cockroachdb/cockroach/blob/dbb44844e683cd28751aaa30f6817e8cb37c37a2/pkg/storage/replica_application_result.go#L358-L361
So we go on to finish the proposal's application and free the tracing span. The later reproposal at the higher max lease index then attempts to apply and hits the panic when logging with the proposal's context.

The proposed fix is the following. We should never bind the reproposed entry that we know will fail to the local proposal in the first place.
```go
diff --git a/pkg/storage/replica_application.go b/pkg/storage/replica_application.go
index 79494a22ce..712c46448d 100644
--- a/pkg/storage/replica_application.go
+++ b/pkg/storage/replica_application.go
@@ -164,6 +164,16 @@ func (r *Replica) retrieveLocalProposals(ctx context.Context, b *cmdAppBatch) {
        for ok := it.init(&b.cmdBuf); ok; ok = it.next() {
                cmd := it.cur()
                cmd.proposal = r.mu.proposals[cmd.idKey]
+               if cmd.proposedLocally() && cmd.raftCmd.MaxLeaseIndex != cmd.proposal.command.MaxLeaseIndex {
+                       // If this entry does not have the most up-to-date view of the
+                       // corresponding proposal's maximum lease index then the proposal
+                       // must have been reproposed with a higher lease index. (see
+                       // tryReproposeWithNewLeaseIndex). In that case, there's a newer
+                       // version of the proposal in the pipeline, so don't consider this
+                       // entry to have been proposed locally. We entry must necessarily be
+                       // rejected by checkForcedErr.
+                       cmd.proposal = nil
+               }
                if cmd.proposedLocally() {
                        // We initiated this command, so use the caller-supplied context.
                        cmd.ctx = cmd.proposal.ctx
@@ -179,16 +189,7 @@ func (r *Replica) retrieveLocalProposals(ctx context.Context, b *cmdAppBatch) {
        for ok := it.init(&b.cmdBuf); ok; ok = it.next() {
                cmd := it.cur()
                toRelease := int64(0)
-               shouldRemove := cmd.proposedLocally() &&
-                       // If this entry does not have the most up-to-date view of the
-                       // corresponding proposal's maximum lease index then the proposal
-                       // must have been reproposed with a higher lease index. (see
-                       // tryReproposeWithNewLeaseIndex). In that case, there's a newer
-                       // version of the proposal in the pipeline, so don't remove the
-                       // proposal from the map. We expect this entry to be rejected by
-                       // checkForcedErr.
-                       cmd.raftCmd.MaxLeaseIndex == cmd.proposal.command.MaxLeaseIndex
-               if shouldRemove {
+               if cmd.proposedLocally() {
                        // Delete the proposal from the proposals map. There may be reproposals
                        // of the proposal in the pipeline, but those will all have the same max
                        // lease index, meaning that they will all be rejected after this entry
```

@ajwerner is working on a test for this which will include an attempt to recreate this wild series of events.
