### ISSUE TITLE
TestDrainingProcessorSwallowsUncertaintyError fails under stress with short timeout

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#39277]
At the moment, on master branch (with `vectorize=off`), running locally `make stress PKG=./pkg/sql/distsqlrun TESTS=TestDrainingProcessorSwallowsUncertaintyError TESTTIMEOUT=10s` actually times out the test. Usually it takes about 30-60 seconds to repro.

There are quite a few goroutines in the stack trace, but the most suspicious is:
```
goroutine 1476 [chan receive]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*RowChannel).Next(0xc000cd1340, 0x68e6e80, 0xc0003ad618, 0x7526560, 0xc00027a860)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:438 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*noopProcessor).Next(0xc000a45680, 0xc000c7faa0, 0x6d1e915, 0x4, 0x74dfec0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/noop.go:66 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x74dfec0, 0xc000c7faa0, 0x74e9cc0, 0xc000a45680, 0x74c48c0, 0xc00104fc00)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:171 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc000a45680, 0x74dfec0, 0xc000c7faa0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:793 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc00000c3c0, 0x74dfec0, 0xc000c7faa0, 0x6e706f8, 0x0, 0x0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:622 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00011d440, 0xc0008cfaa0, 0xc0015fc900, 0xc00288c948, 0xc001a24840, 0xc000a29f28, 0x0, 0x0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:324 +0x368
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00011d440, 0x74dfec0, 0xc0013e7530, 0xc000a29f28, 0xc0008cfaa0, 0xc0015fc900, 0x74e1840, 0xc00156b8c0, 0xc001a24840, 0xc000a29cd8)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:933 +0x217
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc000a29b00, 0x74dfec0, 0xc0013e7530, 0xc000a29e50, 0x3, 0xf85e988, 0xc001bfa960, 0xc00288cb01, 0x0, 0x0, ...)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:902 +0x370
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc000a29b00, 0x74dfec0, 0xc0013e7530, 0xc000a29e50, 0xf85e988, 0xc001bfa960, 0x0, 0x0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:734 +0x6e5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc000a29b00, 0x74dfec0, 0xc0013e7530, 0x74e5100, 0xc0000b9400, 0xc00077ec01, 0x76, 0x0, 0x1, 0x0, ...)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417 +0xb64
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc000a29b00, 0x74dfec0, 0xc0013e7530, 0x74e5100, 0xc0000b9400, 0xc00077ec01, 0x76, 0x0, 0x1, 0x0, ...)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:99 +0x4ec
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc000a29b00, 0x74dfe00, 0xc0000b94c0, 0x0, 0x0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1211 +0x1aba
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc000a29b00, 0x74dfec0, 0xc0013e7140, 0xc0007781e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1140 +0x1a3
github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx.func1(0xc000a29b00, 0x74dfec0, 0xc0013e7140, 0xc00222ab40, 0xc0026866a0, 0x0, 0xc0002a8fd4)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:201 +0x64
created by github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:200 +0x4bc
```

**Comment by RaduBerinde** [comment]
Hitting this fairly often, this needs an assignee. CC @jordanlewis

**Comment by jordanlewis** [comment]
We disabled this, are you still hitting it?

**Comment by RaduBerinde** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=1425057&buildTypeId=Cockroach_UnitTests

**Comment by RaduBerinde** [comment]
Was that very recent? Maybe I need a rebase.

**Comment by RaduBerinde** [comment]
Ah, duh, the info is above. Yeah, I didn't have that change in my tree.

**Comment by asubiotto** [comment]
This failure isn't caused by the vectorized engine and I would argue is expected. This `noopProcessor` is stuck reading from a remote stream during an internal query. The root cause is that the remote outbox fails to dial the gateway node because the remote node still hasn't received the gateway node's descriptor through gossip:
```
outbox 0xc0015dd180 dial error failed to resolve n3: unable to look up descriptor for n3
```
I would say that in this (and any test), we probably want to wait until the node descriptors have been gossiped. The reason I'm saying that this is expected is because the distsql infrastructure is already equipped to deal with these sorts of failures: with the beloved `no inbound stream connection` error. The `noopProcessor` will eventually time out and return an error as expected, the only thing is that we set the timeout to `10s` in this test, which is exactly the amount of time a noop processor will wait. Just to double check, I'm verifying that this test doesn't fail with a higher timeout.

It's weird to me that disabling vectorized execution had anything to do with improving this test, so I will look into that.

**Comment by asubiotto** [comment]
With vectorized execution default:
```
diff --git a/pkg/sql/distsqlrun/processors_test.go b/pkg/sql/distsqlrun/processors_test.go
index 9fe28630ca..c9d6f85f31 100644
--- a/pkg/sql/distsqlrun/processors_test.go
+++ b/pkg/sql/distsqlrun/processors_test.go
@@ -598,9 +598,6 @@ func TestDrainingProcessorSwallowsUncertaintyError(t *testing.T) {
                }
                // Temporarily disable vectorized execution due to flaky failures.
                // https://github.com/cockroachdb/cockroach/issues/39277
-               if _, err := conn.Exec("set vectorize='off'"); err != nil {
-                       t.Fatal(err)
-               }
                limit := 5
                if dummy {
                        limit = 6
```
I've been running this test under stress with no problem. @RaduBerinde were you running with a timeout?

**Comment by asubiotto** [comment]
@RaduBerinde took a look at your teamcity failure and looks like your branch failed running this test with the vectorized engine. I think what possibly happened there is that this test ran when we enabled streaming but before we put the row count threshold in (which is what I think prevents this test from running with vectorized). This test is known to hang for a different reason under vectorized (because of how the test is written) but we didn't merge the change to fix that because we thought this test was generally broken (hence this issue). I will PR a change to run this test under vectorized explicitly and change the test so that a hang doesn't happen.
