### ISSUE TITLE
Gossip initialization panics if no gossip address was provided

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#3963]
Found in 57f6295e8f133c6fdfd3e9a6f5212ffcc9b7077a.
Running `cockroach init; cockroach start --insecure` without any `--gossip` flag:

```
I0125 22:10:25.603352 16221 server/node.go:293  initialized store store=1:1 ([ssd]=data2): {Capacity:8312655872 Available:6832091136 RangeCount:0}
I0125 22:10:25.603394 16221 server/node.go:220  node ID 1 initialized
I0125 22:10:25.603505 16221 gossip/gossip.go:218  setting node descriptor node_id:1 address:<network_field:"tcp" address_field:"ip-172-31-53-252:26257" > attrs:<> 
I0125 22:10:25.603714 16221 gossip/gossip.go:267  read 0 gossip host(s) for bootstrapping from persistent storage
F0125 22:10:25.603815 16221 gossip/gossip.go:316  no resolvers specified for gossip network
goroutine 1 [running]:
github.com/cockroachdb/cockroach/util/log.stacks(0xece389401, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:877 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x217bae0, 0x3, 0x1b15f92, 0x10, 0x13c, 0x0, 0xc820324370)
        /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:734 +0x12f
github.com/cockroachdb/cockroach/util/log.AddStructured(0x0, 0x0, 0x3, 0x2, 0x16c91c0, 0x29, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/log/structured.go:38 +0x114
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x16c91c0, 0x29, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/log/log.go:64 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x16c91c0, 0x29, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/log/log.go:170 +0x66
github.com/cockroachdb/cockroach/gossip.(*Gossip).SetStorage(0xc8201987e0, 0x7fc044c3b1d0, 0xc820147ec0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:316 +0xabe
github.com/cockroachdb/cockroach/server.(*Node).initStores(0xc8201cb4a0, 0xc820197d10, 0x1, 0x1, 0xc8201d2000, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/server/node.go:305 +0x441
github.com/cockroachdb/cockroach/server.(*Node).start(0xc8201cb4a0, 0xc820015260, 0x7fc0477abaf0, 0xc8202f81c0, 0xc820197d10, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/server/node.go:244 +0x2bb
github.com/cockroachdb/cockroach/server.(*Server).Start(0xc82009c700, 0xc8201d2000, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/server/server.go:239 +0x4f5
github.com/cockroachdb/cockroach/cli.runStart(0x1e2fb40, 0xc820163040, 0x0, 0x2, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/cli/start.go:191 +0xd5b
github.com/spf13/cobra.(*Command).execute(0x1e2fb40, 0xc820162f20, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/spf13/cobra/command.go:565 +0x63b
github.com/spf13/cobra.(*Command).ExecuteC(0x1e2d340, 0x1e2fb40, 0x0, 0x0)
        /go/src/github.com/spf13/cobra/command.go:656 +0x56b
github.com/spf13/cobra.(*Command).Execute(0x1e2d340, 0x0, 0x0)
        /go/src/github.com/spf13/cobra/command.go:615 +0x2d
github.com/cockroachdb/cockroach/cli.Run(0xc82000a1d0, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/cli/cli.go:84 +0x7c
main.main()
        /go/src/github.com/cockroachdb/cockroach/main.go:37 +0xe6
```

I'll take this.

**Comment by knz** [comment]
Fixed with #3964
