### ISSUE TITLE
IMPORT crashes when trying to import 1,272 CSV files

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#40042]
Installed latest master (cockroach-v19.2.0-alpha.20190606-1711-g4c3053c) on a three-node roachprod cluster in AWS. Ran an `IMPORT` operation to import the 1,272 CSV files comprising a table that I'd `EXPORT`ed earlier, and two of the three nodes crashed with the following panic printed to the logs:

**Node 1**
```
panic: too many ProducerDone() calls

goroutine 211310 [running]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*RowChannel).ProducerDone(0xc00895ca80)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:421 +0x69
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.DrainAndClose(0x49856e0, 0xc00331cd40, 0x4960ea0, 0xc00895ce00, 0x4912500, 0xc014684260, 0x41a76a0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:309 +0x1fe
github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Run(0xc00d06d200, 0x49856e0, 0xc00331cd40)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/read_import_proc.go:277 +0x12c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).startInternal.func1(0xc016a5a7e0, 0xc003d966f0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:523 +0x65
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).startInternal
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:522 +0x35b
```

**Node 2**
```
panic: send on closed channel

goroutine 235784 [running]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*RowChannel).Push(0xc018967740, 0x0, 0x0, 0x0, 0xc00cf1d500, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:409 +0x76
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.processProducerMessage(0x49857a0, 0xc014864a80, 0x49cb400, 0xc006d15ad0, 0x4960d60, 0xc018967740, 0xc006a43c00, 0xc017654a96, 0xc008837a40, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/inbound.go:236 +0x1b5
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.processInboundStreamHelper.func2(0xc01472b9e0, 0x49cb400, 0xc006d15ad0, 0xc0180ae040, 0xc017a45b00, 0x49857a0, 0xc014864a80, 0x4960d60, 0xc018967740, 0xc006a43c00, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/inbound.go:164 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.processInboundStreamHelper
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/inbound.go:146 +0x1b3
```

I have the logs from when this crash occurred (plus the IMPORT statement) that I can share if they'd be helpful.

Later, I restarted the nodes that had crashed, and the IMPORT job resumed. Again, two nodes crashed before long, with the same pair of errors.

**Comment by dt** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/39992 I think

**Comment by rolandcrosby** [comment]
Yes, appears to not crash once I run it on a build from that branch. Thanks for the fix.
