### ISSUE TITLE
storage: crash with snapshot widens existing replica, but no replica exists for subsumed key

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#40257]
I was stressing the repartitioning tests, as one does.
@tbg or @nvanbenschoten  do you have any guesses here? If not, I'm as good as any to look, but in a few days.

```
make stress PKG=./pkg/ccl/partitionccl TESTS=TestRepartitioning

=== RUN   TestRepartitioning/single_col_range_partitioning/unpartitioned
....
F190827 18:54:51.894556 264384 storage/replica_raft.go:1486  [n2,s2,r192/3:/Table/94/1/{5-6}] snapshot widens existing replica, but no replica exists for subsumed key /Table/94/1/6
goroutine 264384 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc000424300, 0xc0004243c0, 0x0, 0x6)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1016 +0xb1
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x70bc4e0, 0xc000000004, 0x6a3f13e, 0x17, 0x5ce, 0xc00178c800, 0x77)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:872 +0x948
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x484fa80, 0xc0076bd710, 0xc000000004, 0x2, 0x40095f8, 0x4b, 0xc003dd4b18, 0x1, 0x1)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2cc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x484fa80, 0xc0076bd710, 0x1, 0xc000000004, 0x40095f8, 0x4b, 0xc003dd4b18, 0x1, 0x1)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:180
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).maybeAcquireSnapshotMergeLock(0xc003c49800, 0x484fa80, 0xc0076bd710, 0x664b41c61ec58c54, 0xe3d23aadb1a1dd8d, 0xc0076f8f40, 0x0, 0x0, 0x0, 0xc005f08c80, ...)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:1486 +0x294
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc003c49800, 0x484fa80, 0xc0076bd710, 0x664b41c61ec58c54, 0xe3d23aadb1a1dd8d, 0xc0076f8f40, 0x0, 0x0, 0x0, 0xc005f08c80, ...)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:521 +0x1893
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest.func1(0x484fa80, 0xc0076bd710, 0xc003c49800, 0x0)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3490 +0x19d
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc000ce0700, 0x484fa80, 0xc0076bd710, 0xc005f08a48, 0xc007b1f4d8, 0x0)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3370 +0x150
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftSnapshotRequest(0xc000ce0700, 0x484fa80, 0xc005a90d80, 0xc005f08a00, 0x664b41c61ec58c54, 0xe3d23aadb1a1dd8d, 0xc0076f8f40, 0x0, 0x0, 0x0, ...)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3432 +0x1a4
github.com/cockroachdb/cockroach/pkg/storage.(*Store).receiveSnapshot(0xc000ce0700, 0x484fa80, 0xc005a90d80, 0xc005f08a00, 0x7f3371250df8, 0xc004a2c870, 0x0, 0x0)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/storage/store_snapshot.go:871 +0x6d3
github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc000ce0700, 0xc005f08a00, 0x7f3371250dc8, 0xc004a2c870, 0xc004a2c870, 0x30)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3241 +0x201
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x48a46e0, 0xc004a2c870, 0xc001294e10, 0x484fa80, 0xc005a90cc0, 0x707e7f, 0xc003d695b0)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:415 +0x138
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x484fa80, 0xc005a90cc0)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:416 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc001ca2480, 0x484fa80, 0xc005a90cc0, 0xc005120400, 0x32, 0x0, 0x0, 0xc005a90cf0)
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:321 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/home/andrei/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:316 +0x131


419 runs completed, 1 failures, over 22m10s
```

**Comment by andreimatei** [comment]
test logs:
https://gist.github.com/andreimatei/0fdcbcdbbcae1c33e385a849cb32b801

**Comment by tbg** [comment]
Ugh. Maybe https://github.com/cockroachdb/cockroach/issues/36611? See if you can corroborate or refute this.

Also, does this repro, perhaps on a large roachprod-stress cluster? A reliable repro doubles as a guarantee that we can fix this within at most a week of effort I'd say

**Comment by andreimatei** [comment]
Got another report from Darin, while he was playing around.

**Comment by tbg** [comment]
Just happened on master too: https://github.com/cockroachdb/cockroach/issues/40423

Now that I think about it, this might be the same as https://github.com/cockroachdb/cockroach/issues/40367. To verify this, look at the logs: the node that blows up should have been removed from the range and re-added recently, but without applying the learner snapshot (the snap would still be sent, but we wouldn't see it get applied).

**Comment by ajwerner** [comment]
It does indeed seem like this is #40367. It reproduces readily. In all the cases I've seen we've had a replica get a learner snapshot soon after being added and then removed. 

```
I190903 18:32:50.297745 241003 storage/replica_command.go:1430  [n3,s3,r187/1:/Table/94/1/{5-6}] change replicas (add [(n2,s2):2LEARNER] remove []): existing descriptor r187:/Table/94/1/{5-6} [(n3,s3):1, next=2, gen=142]                                                                                                
I190903 18:32:50.312835 241003 storage/replica_raft.go:291  [n3,s3,r187/1:/Table/94/1/{5-6}] proposing ADD_REPLICA[(n2,s2):2LEARNER]: after=[(n3,s3):1 (n2,s2):2LEARNER] next=3                                                                                                                                             
I190903 18:32:50.315539 241003 storage/store_snapshot.go:995  [n3,s3,r187/1:/Table/94/1/{5-6}] sending LEARNER snapshot 1bbc9d31 at applied index 23
I190903 18:32:50.315693 241003 storage/store_snapshot.go:1038  [n3,s3,r187/1:/Table/94/1/{5-6}] streamed snapshot to (n2,s2):2LEARNER: kv pairs: 8, log entries: 0, rate-limit: 8.0 MiB/sec, 0.00s                                                                                                                          
I190903 18:32:50.316810 241498 storage/replica_raftstorage.go:793  [n2,s2,r187/2:{-}] applying LEARNER snapshot [id=1bbc9d31 index=23]
I190903 18:32:50.329484 241498 storage/replica_raftstorage.go:814  [n2,s2,r187/2:/Table/94/1/{5-6}] applied LEARNER snapshot [total=11ms ingestion=4@11ms id=1bbc9d31 index=23]                                                                                                                                             
I190903 18:32:50.330283 241003 storage/replica_command.go:1430  [n3,s3,r187/1:/Table/94/1/{5-6}] change replicas (add [(n2,s2):2] remove []): existing descriptor r187:/Table/94/1/{5-6} [(n3,s3):1, (n2,s2):2LEARNER, next=3, gen=143]                                                                                     
I190903 18:32:50.336131 241003 storage/replica_raft.go:291  [n3,s3,r187/1:/Table/94/1/{5-6}] proposing ADD_REPLICA[(n2,s2):2]: after=[(n3,s3):1 (n2,s2):2] next=3                                                                                                                                                           
E190903 18:32:50.356208 241406 storage/queue.go:1027  [n2,replicate,s2,r187/2:/Table/94/1/{5-6}] no removable replicas from range that needs a removal: [1:0, 2*:27]                                                                                                                                                        
I190903 18:32:50.469525 241975 storage/replica_command.go:1430  [n2,s2,r187/2:/Table/94/1/{5-6}] change replicas (add [] remove [(n3,s3):1]): existing descriptor r187:/Table/94/1/{5-6} [(n3,s3):1, (n2,s2):2, next=3, gen=144]                                                                                            
I190903 18:32:50.485261 241975 storage/replica_raft.go:291  [n2,s2,r187/2:/Table/94/1/{5-6}] proposing REMOVE_REPLICA[(n3,s3):1]: after=[(n2,s2):2] next=3
I190903 18:32:50.488300 241111 storage/replica_command.go:609  [n2,merge,s2,r186/2:/Table/94/1/{4-5}] initiating a merge of r187:/Table/94/1/{5-6} [(n2,s2):2, next=3, gen=145] into this range (lhs+rhs has (size=0 B+0 B qps=0.00+0.00 --> 0.00qps) below threshold (size=0 B, qps=0.00))                                 
I190903 18:32:50.593128 242769 storage/replica_command.go:609  [n2,merge,s2,r187/2:/Table/94/1/{5-6}] initiating a merge of r188:/{Table/94/1/6-Max} [(n2,s2):3, next=4, gen=150] into this range (lhs+rhs has (size=0 B+0 B qps=0.00+0.00 --> 0.00qps) below threshold (size=0 B, qps=0.00))                               
I190903 18:32:50.656216 1537 storage/store.go:2593  [n2,s2,r187/2:/Table/94/1/{5-6}] removing replica r188/3
I190903 18:32:50.668577 244165 storage/replica_command.go:1430  [n2,s2,r187/2:/{Table/94/1/5-Max}] change replicas (add [(n3,s3):3LEARNER] remove []): existing descriptor r187:/{Table/94/1/5-Max} [(n2,s2):2, next=3, gen=151]                                                                                            
I190903 18:32:50.680770 244165 storage/replica_raft.go:291  [n2,s2,r187/2:/{Table/94/1/5-Max}] proposing ADD_REPLICA[(n3,s3):3LEARNER]: after=[(n2,s2):2 (n3,s3):3LEARNER] next=4                                                                                                                                           
I190903 18:32:50.682048 244165 storage/store_snapshot.go:995  [n2,s2,r187/2:/{Table/94/1/5-Max}] sending LEARNER snapshot f9f0b80c at applied index 35
I190903 18:32:50.682316 244165 storage/store_snapshot.go:1038  [n2,s2,r187/2:/{Table/94/1/5-Max}] streamed snapshot to (n3,s3):3LEARNER: kv pairs: 41, log entries: 0, rate-limit: 8.0 MiB/sec, 0.00s                                                                                                                       
F190903 18:32:50.683220 242722 storage/replica_raft.go:1486  [n3,s3,r187/1:/Table/94/1/{5-6}] snapshot widens existing replica, but no replica exists for subsumed key /Table/94/1/6     
```
[out.1567534743.txt](https://github.com/cockroachdb/cockroach/files/3572858/out.1567534743.txt)
[out.1567535970.txt](https://github.com/cockroachdb/cockroach/files/3572846/out.1567535970.txt)
[out.1567540180.txt](https://github.com/cockroachdb/cockroach/files/3572863/out.1567540180.txt)


I've got more failures. I futzed around trying to come up with a fix. I posted the probably too simple https://github.com/cockroachdb/cockroach/pull/40459. It survives roachprod-stress better but eventually does seem to fail a SucceedsSoon.

**Comment by petermattis** [comment]
FYI, I saw this while running `clearrange/checks=true`. Seems like this is readily reproducible, though.
