### ISSUE TITLE
sql: panic: txn: unexpected 686080 leftover bytes

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#40293]
This *sometimes* triggers a leftover bytes panic. Since it doesn't always happen, I can't run the reducer on it so you get the big one. It has something to do with the statement timeout, since if removed it seems to complete just fine in about 30s on my machine.

```
CREATE TABLE IF NOT EXISTS tab_orig AS
	SELECT
		g::INT8 AS _int8,
		g::FLOAT8 AS _float8,
		'2001-01-01'::DATE + g AS _date,
		g % 2 = 1 AS _bool,
		g::DECIMAL AS _decimal,
		g::STRING AS _string,
		g::STRING::BYTES AS _bytes
	FROM
		generate_series(1, 5) AS g;

SET statement_timeout = '5s';

SELECT
	*
FROM
	(
		SELECT
			(B'0010010101011011010011000101111001010100101011', e'\\\x11}Z\x0bxAtq':::STRING:::NAME, e'-\x17kweF2EC':::STRING)
				AS col_113590,
			COALESCE(tab_36610._float8, tab_36610._float8) AS col_113591,
			CASE
			WHEN EXISTS(
				WITH
					with_7621
						(
							col_113594,
							col_113595,
							col_113596,
							col_113597,
							col_113598,
							col_113599,
							col_113600,
							col_113601,
							col_113602,
							col_113603,
							col_113604,
							col_113605,
							col_113606,
							col_113607,
							col_113608,
							col_113609
						)
						AS (
							SELECT
								1795961161:::OID AS col_113594,
								tab_36620._int8 AS col_113595,
								1779125916:::OID AS col_113596,
								tab_36616._string AS col_113597,
								'22:13:44.59742':::TIME AS col_113598,
								375769534:::OID AS col_113599,
								ARRAY[(-6641755549757797578):::INT8] AS col_113600,
								tab_36621._bool AS col_113601,
								ARRAY[(-7039460667619560176):::INT8,7522941713212469739:::INT8] AS col_113602,
								1186733404:::OID AS col_113603,
								tab_36617._float8 AS col_113604,
								tab_36616._string AS col_113605,
								tab_36619._string AS col_113606,
								tab_36621._float8 AS col_113607,
								B'011101111111000100111100100101001101' AS col_113608,
								tab_36621._string AS col_113609
							FROM
								(
									SELECT
										tab_36612._date AS col_113592
									FROM
										defaultdb.public.tab_orig AS tab_36612
										JOIN defaultdb.public.tab_orig AS tab_36613 ON
												(tab_36612._int8) = (tab_36613._int8)
												AND (tab_36612._date) = (tab_36613._date)
												AND (tab_36612._decimal) = (tab_36613._decimal)
												AND (tab_36612._string) = (tab_36613._string),
										defaultdb.public.tab_orig AS tab_36614
									GROUP BY
										tab_36612._date
								)
									AS tab_36615 (col_113593)
								JOIN defaultdb.public.tab_orig AS tab_36616 ON
										(tab_36615.col_113593) = (tab_36616._date),
								defaultdb.public.tab_orig AS tab_36617,
								defaultdb.public.tab_orig AS tab_36618
								JOIN defaultdb.public.tab_orig AS tab_36619 ON
										(tab_36618._string) = (tab_36619._string)
										AND (tab_36618._bytes) = (tab_36619._bytes),
								defaultdb.public.tab_orig AS tab_36620
								JOIN defaultdb.public.tab_orig AS tab_36621 ON (tab_36620._bool) = (tab_36621._bool)
						)
				SELECT
					tab_36610._int8 AS col_113610, tab_36610._bytes AS col_113611
				FROM
					with_7621
				ORDER BY
					with_7621.col_113598, with_7621.col_113608 ASC
			)
			THEN NULL
			ELSE (e'[[null, {"r3ylD": {}}], [{"bar": [], "foobar": "Hn<dJ%x", "y`$(Xg": []}, {}, {"{^BJt\\\\M": "bar"}, [null]], {}]':::JSONB, e'4\x10#Xiq0B':::STRING:::NAME)
			END
				AS col_113612,
			tab_36608._decimal AS col_113613
		FROM
			defaultdb.public.tab_orig AS tab_36607,
			defaultdb.public.tab_orig AS tab_36608,
			defaultdb.public.tab_orig AS tab_36609,
			defaultdb.public.tab_orig AS tab_36610
			CROSS JOIN defaultdb.public.tab_orig AS tab_36611
		WHERE
			tab_36611._bool
	)
ORDER BY
	col_113590, col_113591, col_113612, col_113613;
```

```
panic: txn: unexpected 686080 leftover bytes [recovered]
        panic: panic while executing 1 statements: SELECT * FROM (SELECT (_, _, __more1__) AS _, COALESCE(_._, _._) AS _, CASE WHEN EXISTS (WITH _ (_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) AS (SELECT _:::OID AS _, _._ AS _, _:::OID AS _, _._ AS _, _:::TIME AS _, _:::OID AS _, ARRAY[(_):::INT8] AS _, _._ AS _, ARRAY[(_):::INT8, _:::INT8] AS _, _:::OID AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _ AS _, _._ AS _ FROM (SELECT _._ AS _ FROM _._._ AS _ JOIN _._._ AS _ ON ((((_._) = (_._)) AND ((_._) = (_._))) AND ((_._) = (_._))) AND ((_._) = (_._)), _._._ AS _ GROUP BY _._) AS _ (_) JOIN _._._ AS _ ON (_._) = (_._), _._._ AS _, _._._ AS _ JOIN _._._ AS _ ON ((_._) = (_._)) AND ((_._) = (_._)), _._._ AS _ JOIN _._._ AS _ ON (_._) = (_._)) SELECT _._ AS _, _._ AS _ FROM _ ORDER BY _._, _._ ASC) THEN _ ELSE (_, _) END AS _, _._ AS _ FROM _._._ AS _, _._._ AS _, _._._ AS _, _._._ AS _ CROSS JOIN _._._ AS _ WHERE _._) ORDER BY _, _, _, _; caused by txn: unexpected 686080 leftover bytes

goroutine 1081 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0014e8000, 0x4b575c0, 0xc000abc900, 0x3c36ae0, 0xc0002c1660)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:730 +0x330
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0014e8000, 0x4b575c0, 0xc000abc900)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:442 +0x61
panic(0x3c36ae0, 0xc0002c1660)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/util/log.ReportOrPanic(0x4b575c0, 0xc000b56580, 0xc000725500, 0xc0000feed0, 0x25, 0x0, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:554 +0x226
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc0018f4be0, 0x4b575c0, 0xc000b56580, 0xc001a31301)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:397 +0x291
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:384
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).finishSQLTxn(0xc0014e8090)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/txn_state.go:230 +0x5f
github.com/cockroachdb/cockroach/pkg/sql.cleanupAndFinish(0x4b57680, 0xc00120f800, 0x4ae57c0, 0xc00044f320, 0x4052cc0, 0xc0014e8090, 0x4ae5660, 0xc0002c1620, 0x3e35060, 0xc0002c1630, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_fsm.go:510 +0xd8
github.com/cockroachdb/cockroach/pkg/util/fsm.Transitions.apply(0xc0003874a0, 0x4b57680, 0xc00120f800, 0x4ae57c0, 0xc00044f320, 0x4052cc0, 0xc0014e8090, 0x4ae5660, 0xc0002c1620, 0x3e35060, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:101 +0x17b
github.com/cockroachdb/cockroach/pkg/util/fsm.(*Machine).ApplyWithPayload(...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:130
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper(0xc0014e8000, 0x4ae5660, 0xc0002c1620, 0x3e35060, 0xc0002c1630, 0x7eff230ebb90, 0xc0014b8668, 0x4, 0x0, 0x0, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1951 +0x1df
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc0014e8000, 0x4b575c0, 0xc000b56580, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1367 +0x94f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0014e8000, 0x4b575c0, 0xc000abc900, 0xc0005e90c0, 0x5400, 0x15000, 0xc0005e9158, 0xc0003f3cf0, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1167 +0x1a3
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000701400, 0x4b575c0, 0xc000abc900, 0xc0014e8000, 0x5400, 0x15000, 0xc0005e9158, 0xc0003f3cf0, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:444 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc0002d746e, 0xc0003f92c0, 0x4b575c0, 0xc000abc900, 0xc0003f3cf0, 0xc000701400, 0xc0014b8000, 0x4b75940, 0xc0003f92a0, 0xc00122e360, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584 +0x21c
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:513 +0x17b
```

**Comment by jordanlewis** [comment]
This seems fixed. Well, I can't repro it anymore. @mjibson can you try to repro yourself and close if you also can't see it?
