### ISSUE TITLE
sql/pgwire: missing support for row count limits in pgwire

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4035]
Following up on #3819, while trying to run the test case at 
https://github.com/cockroachdb/cockroach/issues/3819#issuecomment-171589559

```
ERROR in (a-test) (QueryExecutorImpl.java:2182)
Uncaught exception, not in assertion.
expected: nil
  actual: org.postgresql.util.PSQLException: ERROR: execute row count limits not supported
 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2182)
    org.postgresql.core.v3.QueryExecutorImpl.processResults (QueryExecutorImpl.java:1911)
    org.postgresql.core.v3.QueryExecutorImpl.execute (QueryExecutorImpl.java:173)
    org.postgresql.jdbc2.AbstractJdbc2Statement.execute (AbstractJdbc2Statement.java:616)
    org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags (AbstractJdbc2Statement.java:452)
    org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate (AbstractJdbc2Connection.java:399)
    org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation (AbstractJdbc2Connection.java:922)
```

**Comment by knz** [comment]
Needed for #4036

**Comment by knz** [comment]
While looking more closely at the code and the trace the error appears when jdbc queries the current transaction isolation level. The way the jdbc code works internally seems to be to query the current transaction isolation level, then change it if different from the current one. The backtrace says as much, there is a getTransactionIsolation -> execSQLUpdate -> executeWithFlags call stack reported.

**Comment by knz** [comment]
That said, after upgrading to 4eeb73fa819852fc09b828cba13b8b6a12e64708 this specific error has disappeared, and instead a new one has appeared:

```
ERROR in (a-test) (QueryExecutorImpl.java:2182)
Uncaught exception, not in assertion.
expected: nil
  actual: org.postgresql.util.PSQLException: ERROR: prepare statement not supported: *parser.Show
 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2182)
    org.postgresql.core.v3.QueryExecutorImpl.processResults (QueryExecutorImpl.java:1911)
    org.postgresql.core.v3.QueryExecutorImpl.execute (QueryExecutorImpl.java:173)
    org.postgresql.jdbc2.AbstractJdbc2Statement.execute (AbstractJdbc2Statement.java:616)
    org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags (AbstractJdbc2Statement.java:452)
    org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate (AbstractJdbc2Connection.java:399)
    org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation (AbstractJdbc2Connection.java:922
)
    clojure.java.jdbc$db_transaction_STAR_.doInvoke (jdbc.clj:578)
```

again during the initial "show trans isolation level", this time for a different reason. Now investigating with a network trace.

**Comment by knz** [comment]
Ok after upgrading to 4eeb73fa819852fc09b828cba13b8b6a12e64708 we are back to "Cant prepare SHOW." The network trace:

```

No.     Time           Source                Destination           Protocol Length Info
      6 44.899931      52.91.194.28          172.31.53.252         PGSQL    174    >

Frame 6: 174 bytes on wire (1392 bits), 174 bytes captured (1392 bits)
Ethernet II, Src: 12:98:7b:58:57:9d (12:98:7b:58:57:9d), Dst: 12:62:5d:34:3b:e3 (12:62:5d:34:3b:e3)
Internet Protocol Version 4, Src: 52.91.194.28, Dst: 172.31.53.252
Transmission Control Protocol, Src Port: 44458 (44458), Dst Port: 15432 (15432), Seq: 1, Ack: 1, Len: 108
PostgreSQL
    Type: Startup message
    Length: 108
    Parameter name: user
    Parameter value: psql
    Parameter name: database
    Parameter value: system
    Parameter name: client_encoding
    Parameter value: UTF8
    Parameter name: DateStyle
    Parameter value: ISO
    Parameter name: TimeZone
    Parameter value: Etc/UTC
    Parameter name: extra_float_digits
    Parameter value: 2

No.     Time           Source                Destination           Protocol Length Info
      7 44.899945      172.31.53.252         52.91.194.28          TCP      66     15432 → 44458 [ACK] Seq=1 Ack=109 Win=26880 Len=0 TSval=217925401 TSecr=347887638

Frame 7: 66 bytes on wire (528 bits), 66 bytes captured (528 bits)
Ethernet II, Src: 12:62:5d:34:3b:e3 (12:62:5d:34:3b:e3), Dst: 12:98:7b:58:57:9d (12:98:7b:58:57:9d)
Internet Protocol Version 4, Src: 172.31.53.252, Dst: 52.91.194.28
Transmission Control Protocol, Src Port: 15432 (15432), Dst Port: 44458 (44458), Seq: 1, Ack: 109, Len: 0

No.     Time           Source                Destination           Protocol Length Info
      8 44.900052      172.31.53.252         52.91.194.28          PGSQL    120    <R/S/S

Frame 8: 120 bytes on wire (960 bits), 120 bytes captured (960 bits)
Ethernet II, Src: 12:62:5d:34:3b:e3 (12:62:5d:34:3b:e3), Dst: 12:98:7b:58:57:9d (12:98:7b:58:57:9d)
Internet Protocol Version 4, Src: 172.31.53.252, Dst: 52.91.194.28
Transmission Control Protocol, Src Port: 15432 (15432), Dst Port: 44458 (44458), Seq: 1, Ack: 109, Len: 54
PostgreSQL
    Type: Authentication request
    Length: 8
    Authentication type: Success (0)
PostgreSQL
    Type: Parameter status
    Length: 25
    Parameter name: client_encoding
    Parameter value: UTF8
PostgreSQL
    Type: Parameter status
    Length: 18
    Parameter name: DateStyle
    Parameter value: ISO

No.     Time           Source                Destination           Protocol Length Info
      9 44.900076      172.31.53.252         52.91.194.28          PGSQL    72     <Z

Frame 9: 72 bytes on wire (576 bits), 72 bytes captured (576 bits)
Ethernet II, Src: 12:62:5d:34:3b:e3 (12:62:5d:34:3b:e3), Dst: 12:98:7b:58:57:9d (12:98:7b:58:57:9d)
Internet Protocol Version 4, Src: 172.31.53.252, Dst: 52.91.194.28
Transmission Control Protocol, Src Port: 15432 (15432), Dst Port: 44458 (44458), Seq: 55, Ack: 109, Len: 6
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: Idle (73)

No.     Time           Source                Destination           Protocol Length Info
     10 44.900455      52.91.194.28          172.31.53.252         TCP      66     44458 → 15432 [ACK] Seq=109 Ack=55 Win=27008 Len=0 TSval=347887638 TSecr=217925401

Frame 10: 66 bytes on wire (528 bits), 66 bytes captured (528 bits)
Ethernet II, Src: 12:98:7b:58:57:9d (12:98:7b:58:57:9d), Dst: 12:62:5d:34:3b:e3 (12:62:5d:34:3b:e3)
Internet Protocol Version 4, Src: 52.91.194.28, Dst: 172.31.53.252
Transmission Control Protocol, Src Port: 44458 (44458), Dst Port: 15432 (15432), Seq: 109, Ack: 55, Len: 0

No.     Time           Source                Destination           Protocol Length Info
     11 44.900463      52.91.194.28          172.31.53.252         TCP      66     44458 → 15432 [ACK] Seq=109 Ack=61 Win=27008 Len=0 TSval=347887638 TSecr=217925401

Frame 11: 66 bytes on wire (528 bits), 66 bytes captured (528 bits)
Ethernet II, Src: 12:98:7b:58:57:9d (12:98:7b:58:57:9d), Dst: 12:62:5d:34:3b:e3 (12:62:5d:34:3b:e3)
Internet Protocol Version 4, Src: 52.91.194.28, Dst: 172.31.53.252
Transmission Control Protocol, Src Port: 44458 (44458), Dst Port: 15432 (15432), Seq: 109, Ack: 61, Len: 0

No.     Time           Source                Destination           Protocol Length Info
     12 44.931064      52.91.194.28          172.31.53.252         PGSQL    135    >P/B/E/S

Frame 12: 135 bytes on wire (1080 bits), 135 bytes captured (1080 bits)
Ethernet II, Src: 12:98:7b:58:57:9d (12:98:7b:58:57:9d), Dst: 12:62:5d:34:3b:e3 (12:62:5d:34:3b:e3)
Internet Protocol Version 4, Src: 52.91.194.28, Dst: 172.31.53.252
Transmission Control Protocol, Src Port: 44458 (44458), Dst Port: 15432 (15432), Seq: 109, Ack: 61, Len: 69
PostgreSQL
    Type: Parse
    Length: 40
    Statement: 
    Query: SHOW TRANSACTION ISOLATION LEVEL
    Parameters: 0
PostgreSQL
    Type: Bind
    Length: 12
    Portal: 
    Statement: 
    Parameter formats: 0
    Parameter values: 0
    Result formats: 0
PostgreSQL
    Type: Execute
    Length: 9
    Portal: 
    Returns: 1 rows
PostgreSQL
    Type: Sync
    Length: 4

No.     Time           Source                Destination           Protocol Length Info
     13 44.931223      172.31.53.252         52.91.194.28          PGSQL    125    <E

Frame 13: 125 bytes on wire (1000 bits), 125 bytes captured (1000 bits)
Ethernet II, Src: 12:62:5d:34:3b:e3 (12:62:5d:34:3b:e3), Dst: 12:98:7b:58:57:9d (12:98:7b:58:57:9d)
Internet Protocol Version 4, Src: 172.31.53.252, Dst: 52.91.194.28
Transmission Control Protocol, Src Port: 15432 (15432), Dst Port: 44458 (44458), Seq: 61, Ack: 178, Len: 59
PostgreSQL
    Type: Error
    Length: 58
    Severity: ERROR
    Code: XX000
    Message: prepare statement not supported: SHOW

No.     Time           Source                Destination           Protocol Length Info
     14 44.931250      172.31.53.252         52.91.194.28          PGSQL    72     <Z

Frame 14: 72 bytes on wire (576 bits), 72 bytes captured (576 bits)
Ethernet II, Src: 12:62:5d:34:3b:e3 (12:62:5d:34:3b:e3), Dst: 12:98:7b:58:57:9d (12:98:7b:58:57:9d)
Internet Protocol Version 4, Src: 172.31.53.252, Dst: 52.91.194.28
Transmission Control Protocol, Src Port: 15432 (15432), Dst Port: 44458 (44458), Seq: 120, Ack: 178, Len: 6
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: Idle (73)
```

**Comment by knz** [comment]
Note by the way that the "EXECUTE" part of the postgres command packet specifies a row count of 1  (Returns: 1 rows)

**Comment by jordanlewis** [comment]
I think row count limits are still unsupported, based on [this forum question](https://forum.cockroachlabs.com/t/cockroachdb-feature-request-gui-for-rdbms/266/13).

Here's the unimplemented stub: https://github.com/cockroachdb/cockroach/blob/66c28b512bf8a06e1bcde01c0b337683406b209f/pkg/sql/pgwire/v3.go#L920

**Comment by dianasaur323** [comment]
For those of you who've looked at this issue before, how difficult would this be to implement? Unlikely to make it into 1.2, but would be helpful to know.

**Comment by jordanlewis** [comment]
I think this would be relatively easy to implement.

**Comment by jordanlewis** [comment]
Actually, nevermind. I think this would be a fairly hefty task. The protocol doesn't just permit row count limits - it actually implements a more sophisticated cursor-like interface that pauses a query when the row count limit is hit, permitting resumption of that query when the user is ready. The flow works as follows (copying from a private discussion for posterity):

1. The user prepares a statement, which produces a prepared statement on the server.
2. The user binds parameters to the statement, which produces a "statement portal" on the server.
3. The user executes the statement portal. Normally, when there's no row count limit sent, the statement will execute, return results, and delete the statement portal all at once. If there is a row count limit, and the limit is reached during execution, the results are sent back along with a "portal suspended" message.
4. The user sends another execute statement, this time targeting the in-progress statement portal. The portal resumes execution of the query (it's up to the implementation how that part works exactly, it seems) as in step 3. This flow is repeated until all rows are exhausted or the client stops sending messages.

**Comment by knz** [comment]
I think if we restrict the protocol so that there can be only one open portal executing at a time, and that no new statement can be executed when a portal is still open (or accept that would close the open portal), then we could achieve this still fairly easily (S-sized project). But before we implement that I'd like to know if having at max 1 portal open is acceptable to clients that use this feature.

(The initial use case above would be OK with the limitation, FWIW)

**Comment by bdarnell** [comment]
This is an issue for SOLR, although there is a workaround: set `batchSize` to zero in the solr configuration.

**Comment by knz** [comment]
In response to https://github.com/cockroachdb/cockroach/issues/4035#issuecomment-328341672 @bdarnell states:

> i haven't seen any indication that people are trying to use multiplexing here, they just want streaming results from a single query

this is a good basis to implement the restricted case with a simple flow control solution.

**Comment by knz** [comment]
@jordanlewis @andreimatei since I have seen you discuss this with other users/customers, please note the exchange with ben above -- we may do good by supporting this feature only in the "Simple case" where it's strictly equivalent to flow control, by suspending the currently executing query until the next execute/resume packet is received from the client.

**Comment by jordanlewis** [comment]
The initial work here is done: row count limits are now supported! This allows support for most simple use cases of JDBC streaming. See #39085.

#40195 now tracks the rest of the missing functionality.

**Comment by quaff** [comment]
CockroachDB version: CCL v19.1.5 @ 2019/10/10 02:31:05 (go1.13.1)
PG JDBC driver version: 42.2.8
JDK version: 1.8.0_221
```
String sql = "******";
try (Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:26257/postgres", "root", "")) {
	try (PreparedStatement stmt = conn.prepareStatement(sql)) {
		stmt.setFetchSize(1);
		conn.setAutoCommit(false);
		try (ResultSet rs = stmt.executeQuery()) {
		}
	}
}
```
Error raised if `setFetchSize(1)` with `setAutoCommit(false)`, or just single `setMaxRows(1)`
```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: unimplemented: execute row count limits not supported: 1 of 34
 ：See: https://github.com/cockroachdb/cockroach/issues/4035
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
```

**Comment by mjibson** [comment]
This is only supported in 19.2. The most recent beta is at https://www.cockroachlabs.com/docs/releases/v19.2.0-beta.20191014.html.
