### ISSUE TITLE
sql: internal error: unsupported comparison operator

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#40444]
```
CREATE TABLE IF NOT EXISTS tab_orig AS
	SELECT
		g % 0 = 0 AS _bool, g AS _string
	FROM
		generate_series(NULL, NULL) AS g;

WITH
	with_5066
		AS (
			SELECT
				*
			FROM
				(
					VALUES
						(
							'1970-01-10 10:58:25.000263+00:00':::TIMESTAMP,
							NULL,
							B'011010000001',
							e'\x05\x7f0>',
							0:::OID,
							0:::OID
						),
						(
							'-69 years -8 mons -378 days -18:09:45.930653'
							+ '1970-01-02 17:37:53.000834+00:00'::TIMESTAMP,
							0:::OID,
							B'101100111001',
							NULL,
							0:::OID,
							0:::OID
						)
				)
					AS tab_23694
						(
							col_62961,
							col_62962,
							col_62963,
							col_62964,
							col_62965,
							col_62966
						)
		)
SELECT
	NULL
FROM
	with_5066, tab_orig AS tab_23695
WHERE
	EXISTS(
		WITH
			with_5067
				AS (
					SELECT
						*
					FROM
						(
							VALUES
								(
									(
										SELECT
											NULL
										FROM
											tab_orig
												AS tab_23697
										WHERE
											'1970-01-08 20:14:14.000623+00:00'::TIMESTAMPTZ
											IN (
													SELECT
														NULL
													FROM
														tab_orig
												)
											OR tab_23697._bool
												>= false
										LIMIT
											1
									)
								)
						)
							AS tab_23714 (col_62969)
				)
		SELECT
			with_5066.col_62965, tab_23695._string
	);
```

```
stack trace:
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/expr.go:78: processExpression()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/expr.go:160: init()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:109: Init()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:844: InitWithEvalCtx()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:820: Init()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:112: newTableReader()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:1028: newProcessor()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:321: makeProcessor()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:396: setupProcessors()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:479: setup()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/server.go:457: setupFlow()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/server.go:512: SetupLocalSyncFlow()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:237: setupFlows()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:326: Run()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:880: planAndRunSubquery()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:784: PlanAndRunSubqueries()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:310: runRightSidePlan()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:280: Next()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:171: Next()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:467: accumulateRows()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:704: Next()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/distinct.go:200: Next()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:171: Run()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:793: Run()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:584: Run()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:337: Run()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:962: PlanAndRun()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:816: execWithDistSQLEngine()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:708: dispatchToExecutionEngine()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417: execStmtInOpenState()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:98: execStmt()
/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1238: execCmd()
```

**Comment by rafiss** [comment]
The error message got cutout from above, but here it is:

```
pq: internal error: ('1970-01-08 20:14:14.000623+00:00':::TIMESTAMPTZ = ANY (('1970-01-10 10:58:25.000263+00:00', NULL, B'011010000001', e'\x05\x7f0>', 0, 0), ('1899-04-18 23:28:07.070181+00:00':::TIMESTAMP, 0:::OID, B'101100111001', NULL, 0:::OID, 0:::OID))) OR ("$0" >= false):
unsupported comparison operator: <timestamptz> = <tuple{timestamp, unknown, varbit, string, oid, oid}>
```

it looks like that is coming from the type-checker.

**Comment by jordanlewis** [comment]
I feel like this is a similar problem to #40440 - they both have subqueries that have "unknown" type when you ask for the `explain(types)`, which in this case is:

```
                         tree                         |     field     |                                                                                                                                                                       description                                                                                                                                                                        |                                                                              columns                                                                               | ordering
+-----------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
  root                                                |               |                                                                                                                                                                                                                                                                                                                                                          | ("?column?" unknown)                                                                                                                                               |
   ├── render                                         |               |                                                                                                                                                                                                                                                                                                                                                          | ("?column?" unknown)                                                                                                                                               |
   │    │                                             | render 0      | (NULL)[unknown]                                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                    |
   │    └── filter                                    |               |                                                                                                                                                                                                                                                                                                                                                          | (rowid int, rownum int, any_not_null bool)                                                                                                                         |
   │         │                                        | filter        | ((any_not_null)[bool] IS NOT (NULL)[unknown])[bool]                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                    |
   │         └── group                                |               |                                                                                                                                                                                                                                                                                                                                                          | (rowid int, rownum int, any_not_null bool)                                                                                                                         |
   │              │                                   | aggregate 0   | rowid                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                    |
   │              │                                   | aggregate 1   | rownum                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                    |
   │              │                                   | aggregate 2   | any_not_null(true)                                                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                    |
   │              │                                   | group by      | rowid, rownum                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                    |
   │              └── render                          |               |                                                                                                                                                                                                                                                                                                                                                          | ("true" bool, rowid int, rownum int)                                                                                                                               |
   │                   │                              | render 0      | (true)[bool]                                                                                                                                                                                                                                                                                                                                             |                                                                                                                                                                    |
   │                   │                              | render 1      | (rowid)[int]                                                                                                                                                                                                                                                                                                                                             |                                                                                                                                                                    |
   │                   │                              | render 2      | (rownum)[int]                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                    |
   │                   └── apply-join                 |               |                                                                                                                                                                                                                                                                                                                                                          | (column1 timestamp, column2 oid, column3 varbit, column4 string, column5 oid, column6 oid, rownum int, _string int, rowid[hidden] int, col_62965 oid, _string int) |
   │                        │                         | type          | inner                                                                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                    |
   │                        └── ordinality            |               |                                                                                                                                                                                                                                                                                                                                                          | (column1 timestamp, column2 oid, column3 varbit, column4 string, column5 oid, column6 oid, rownum int)                                                             |
   │                             └── scan buffer node |               |                                                                                                                                                                                                                                                                                                                                                          | (column1 timestamp, column2 oid, column3 varbit, column4 string, column5 oid, column6 oid)                                                                         |
   │                                                  | label         | buffer 1 (with_5066)                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                    |
   ├── subquery                                       |               |                                                                                                                                                                                                                                                                                                                                                          | ("?column?" unknown)                                                                                                                                               |
   │    │                                             | id            | @S1                                                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                    |
   │    │                                             | original sql  | SELECT * FROM (VALUES ('1970-01-10 10:58:25.000263+00:00':::TIMESTAMP, NULL, B'011010000001', e'\x05\x7f0>', 0:::OID, 0:::OID), ('-69 years -8 mons -378 days -18:09:45.930653' + '1970-01-02 17:37:53.000834+00:00', 0:::OID, B'101100111001', NULL, 0:::OID, 0:::OID)) AS tab_23694 (col_62961, col_62962, col_62963, col_62964, col_62965, col_62966) |                                                                                                                                                                    |
   │    │                                             | exec mode     | all rows                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                    |
   │    └── buffer node                               |               |                                                                                                                                                                                                                                                                                                                                                          | (column1 timestamp, column2 oid, column3 varbit, column4 string, column5 oid, column6 oid)                                                                         |
   │         │                                        | label         | buffer 1 (with_5066)                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                    |
   │         └── values                               |               |                                                                                                                                                                                                                                                                                                                                                          | (column1 timestamp, column2 oid, column3 varbit, column4 string, column5 oid, column6 oid)                                                                         |
   │                                                  | size          | 6 columns, 2 rows                                                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                    |
   │                                                  | row 0, expr 0 | ('1970-01-10 10:58:25.000263+00:00')[timestamp]                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                    |
   │                                                  | row 0, expr 1 | (CAST((NULL)[unknown] AS OID))[oid]                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                    |
   │                                                  | row 0, expr 2 | (B'011010000001')[varbit]                                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                    |
   │                                                  | row 0, expr 3 | (e'\x05\x7f0>')[string]                                                                                                                                                                                                                                                                                                                                  |                                                                                                                                                                    |
   │                                                  | row 0, expr 4 | (0)[oid]                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                    |
   │                                                  | row 0, expr 5 | (0)[oid]                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                    |
   │                                                  | row 1, expr 0 | ('1899-04-18 23:28:07.070181+00:00')[timestamp]                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                    |
   │                                                  | row 1, expr 1 | (0)[oid]                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                    |
   │                                                  | row 1, expr 2 | (B'101100111001')[varbit]                                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                    |
   │                                                  | row 1, expr 3 | (CAST((NULL)[unknown] AS STRING))[string]                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                    |
   │                                                  | row 1, expr 4 | (0)[oid]                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                    |
   │                                                  | row 1, expr 5 | (0)[oid]                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                    |
   ├── subquery                                       |               |                                                                                                                                                                                                                                                                                                                                                          | ("?column?" unknown)                                                                                                                                               |
   │    │                                             | id            | @S2                                                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                    |
   │    │                                             | original sql  | (SELECT NULL FROM tab_orig)                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                    |
   │    │                                             | exec mode     | all rows normalized                                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                    |
   │    └── render                                    |               |                                                                                                                                                                                                                                                                                                                                                          | ("?column?" timestamptz)                                                                                                                                           |
   │         │                                        | render 0      | (CAST((NULL)[unknown] AS TIMESTAMPTZ))[timestamptz]                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                    |
   │         └── scan                                 |               |                                                                                                                                                                                                                                                                                                                                                          | ()                                                                                                                                                                 |
   │                                                  | table         | tab_orig@primary                                                                                                                                                                                                                                                                                                                                         |                                                                                                                                                                    |
   │                                                  | spans         | ALL                                                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                    |
   ├── subquery                                       |               |                                                                                                                                                                                                                                                                                                                                                          | ("?column?" unknown)                                                                                                                                               |
   │    │                                             | id            | @S3                                                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                    |
   │    │                                             | original sql  | (SELECT NULL FROM tab_orig AS tab_23697 WHERE ('1970-01-08 20:14:14.000623+00:00'::TIMESTAMPTZ IN (SELECT NULL FROM tab_orig)) OR (tab_23697._bool >= false) LIMIT 1)                                                                                                                                                                                    |                                                                                                                                                                    |
   │    │                                             | exec mode     | one row                                                                                                                                                                                                                                                                                                                                                  |                                                                                                                                                                    |
   │    └── render                                    |               |                                                                                                                                                                                                                                                                                                                                                          | ("?column?" unknown)                                                                                                                                               |
   │         │                                        | render 0      | (NULL)[unknown]                                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                    |
   │         └── limit                                |               |                                                                                                                                                                                                                                                                                                                                                          | (_bool bool)                                                                                                                                                       |
   │              │                                   | count         | (1)[int]                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                    |
   │              └── scan                            |               |                                                                                                                                                                                                                                                                                                                                                          | (_bool bool)                                                                                                                                                       |
   │                                                  | table         | tab_orig@primary                                                                                                                                                                                                                                                                                                                                         |                                                                                                                                                                    |
   │                                                  | spans         | ALL                                                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                    |
   │                                                  | filter        | (((('1970-01-08 20:14:14.000623+00:00')[timestamptz] = ANY (@S2)[tuple{timestamptz}])[bool]) OR (((_bool)[bool] >= (false)[bool])[bool]))[bool]                                                                                                                                                                                                          |                                                                                                                                                                    |
   └── subquery                                       |               |                                                                                                                                                                                                                                                                                                                                                          | ("?column?" unknown)                                                                                                                                               |
        │                                             | id            | @S4                                                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                    |
        │                                             | original sql  | SELECT * FROM (VALUES ((SELECT NULL FROM tab_orig AS tab_23697 WHERE ('1970-01-08 20:14:14.000623+00:00'::TIMESTAMPTZ IN (SELECT NULL FROM tab_orig)) OR (tab_23697._bool >= false) LIMIT 1))) AS tab_23714 (col_62969)                                                                                                                                  |                                                                                                                                                                    |
        │                                             | exec mode     | all rows                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                    |
        └── buffer node                               |               |                                                                                                                                                                                                                                                                                                                                                          | (column1 unknown)                                                                                                                                                  |
             │                                        | label         | buffer 2 (with_5067)                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                    |
             └── values                               |               |                                                                                                                                                                                                                                                                                                                                                          | (column1 unknown)                                                                                                                                                  |
                                                      | size          | 1 column, 1 row                                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                    |
                                                      | row 0, expr 0 | (@S3)[unknown]                                                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                    |
(69 rows)
```

**Comment by yuzefovich** [comment]
I've reduced the query slightly to:
```
CREATE TABLE tabb_orig AS
        SELECT
                g % 0 = 0 AS _bool, g AS _string
        FROM
                generate_series(NULL, NULL) AS g;

WITH with_5066 AS (
                    SELECT *
                      FROM (
                            VALUES (
                                    '1970-01-10 10:58:25.000263+00:00':::TIMESTAMP,
                                    NULL,
                                    B'011010000001',
                                    e'\x05\x7f0>',
                                    0:::OID,
                                    0:::OID
                                   )
                           ) AS tab_23694 (
                                            col_62961,
                                            col_62962,
                                            col_62963,
                                            col_62964,
                                            col_62965,
                                            col_62966
                                          )
                 )
SELECT NULL
  FROM with_5066, tabb_orig AS tab_23695
 WHERE EXISTS(
          WITH with_5067 AS (
                            SELECT *
                              FROM (
                                    VALUES (
                                            (
                                                SELECT NULL
                                                  FROM tabb_orig
                                                        AS tab_23697
                                                 WHERE '1970-01-08 20:14:14.000623+00:00'::TIMESTAMPTZ
                                                       IN (
                                                            SELECT
                                                                NULL
                                                            FROM
                                                                tabb_orig
                                                        )
                                                 LIMIT 1
                                            )
                                           )
                                   ) AS tab_23714 (
                                                    col_62969
                                                  )
                         )
        SELECT with_5066.col_62965, tab_23695._string
       );
```
and it now panics with
```
* ERROR: [n1,client=127.0.0.1:52968,user=root] a SQL panic has occurred while executing "WITH with_5066 AS (SELECT * FROM (VALUES ('1970-01-10 10:58:25.000263+00:00':::TIMESTAMP, NULL, B'011010000001', e'\\x05\\x7f0>', 0:::OID, 0:::OID)) AS tab_23694 (col_62961, col_62962, col_62963, col_62964, col_62965, col_62966)) SELECT NULL FROM with_5066, tabb_orig AS tab_23695 WHERE EXISTS (WITH with_5067 AS (SELECT * FROM (VALUES ((SELECT NULL FROM tabb_orig AS tab_23697 WHERE '1970-01-08 20:14:14.000623+00:00'::TIMESTAMPTZ IN (SELECT NULL FROM tabb_orig) LIMIT 1))) AS tab_23714 (col_62969)) SELECT with_5066.col_62965, tab_23695._string)": invalid datum type given: bool, expected unknown

goroutine 4079 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc002034000, 0x8584a80, 0xc001bfba80, 0x75bf360, 0xc001b91a00)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:730 +0x330
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc002034000, 0x8584a80, 0xc001bfba80)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:442 +0x61
panic(0x75bf360, 0xc001b91a00)
	/usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0xc0013d8900, 0x860b5c0, 0xafdb02e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:167 +0x1e2
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc0020b9400, 0xc002034358, 0x8585c00, 0xc0023f0c90, 0x0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:179 +0x517
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x8584a80, 0xc0018db880, 0x85afcc0, 0xc0020b9400, 0x855e7c0, 0xc001094a80)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:171 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc0020b9400, 0x8584a80, 0xc0018db880)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:793 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc0017bb320, 0x8584b40, 0xc0023f19b0, 0x7d5e150, 0x0, 0x0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:584 +0x1ec
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000139a40, 0xc001043ce0, 0xc0026c2bd0, 0xc002af39a0, 0xc001798dc0, 0xc0020c1b00, 0x0, 0x0)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:337 +0x381
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunSubquery(0xc000139a40, 0x8584a80, 0xc0018da700, 0x2, 0xc0023f0cc0, 0x3, 0x1, 0x8585c00, 0xc0023f0c90, 0x0, ...)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:880 +0x7c8
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries(0xc000139a40, 0x8584a80, 0xc0018da700, 0xc002034358, 0xc002af3c60, 0xc001e32dc0, 0x3, 0x3, 0xc0012d9b80, 0xc002034101, ...)
	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:784 +0x1ba
github.com/cockroachdb/cockroach/pkg/sql.(*applyJoinNode).runRightSidePlan(0xc002143000, 0x8584a80, 0xc0018da700, 0xc002070000, 0xc002034358, 0xc0023ebe00, 0x0, 0x0)
```
I debugged this a little, and it seems to me that Jordan's suspicion about too many "unknowns" has merit here. It appears to me that when running the right side of apply join, the type information on buffer node is not correctly set (the type is of `UnknownFamily`). I think it's a bug in the optimizer. cc @rytaft

**Comment by rytaft** [comment]
I really don't think this is a bug in the optimizer. I've been trying to track this down for a while now, and I think the root cause is likely related to https://github.com/cockroachdb/cockroach/issues/39438 -- subqueries are not being replaced in the enclosing expression after being executed.

I printed out the right side plan for the apply join where the error is occurring:
```
inner-join-apply
 ├── columns: "_string":14(int) rowid:15(int!null) col_62965:25(oid!null) "_string":26(int)
 ├── stats: [rows=1000]
 ├── cost: 2192.6875
 ├── key: (15)
 ├── fd: (15)-->(14,25,26)
 ├── prune: (15)
 ├── scan tab_23695
 │    ├── columns: tab_23695._string:14(int) tab_23695.rowid:15(int!null)
 │    ├── stats: [rows=1000]
 │    ├── cost: 1100.02
 │    ├── key: (15)
 │    ├── fd: (15)-->(14)
 │    └── prune: (14,15)
 ├── with &2 (with_5067)
 │    ├── columns: col_62965:25(oid!null) "_string":26(int)
 │    ├── outer: (14)
 │    ├── cardinality: [1 - 1]
 │    ├── stats: [rows=1]
 │    ├── cost: 1070.14
 │    ├── key: ()
 │    ├── fd: ()-->(25,26)
 │    ├── values
 │    │    ├── columns: column1:24(unknown)
 │    │    ├── cardinality: [1 - 1]
 │    │    ├── stats: [rows=1]
 │    │    ├── cost: 1070.11
 │    │    ├── key: ()
 │    │    ├── fd: ()-->(24)
 │    │    └── tuple [type=tuple{unknown}]
 │    │         └── subquery [type=unknown]
 │    │              └── project
 │    │                   ├── columns: "?column?":23(unknown)
 │    │                   ├── cardinality: [0 - 1]
 │    │                   ├── stats: [rows=1]
 │    │                   ├── cost: 1070.09
 │    │                   ├── key: ()
 │    │                   ├── fd: ()-->(23)
 │    │                   ├── limit
 │    │                   │    ├── cardinality: [0 - 1]
 │    │                   │    ├── stats: [rows=1]
 │    │                   │    ├── cost: 1070.06
 │    │                   │    ├── key: ()
 │    │                   │    ├── select
 │    │                   │    │    ├── stats: [rows=333.333333]
 │    │                   │    │    ├── cost: 1070.04
 │    │                   │    │    ├── scan tab_23697
 │    │                   │    │    │    ├── stats: [rows=1000]
 │    │                   │    │    │    └── cost: 1060.02
 │    │                   │    │    └── filters
 │    │                   │    │         └── exists [type=bool, subquery]
 │    │                   │    │              └── values
 │    │                   │    │                   ├── columns: "?column?":22(timestamptz!null)
 │    │                   │    │                   ├── cardinality: [0 - 0]
 │    │                   │    │                   ├── stats: [rows=0]
 │    │                   │    │                   ├── cost: 0.01
 │    │                   │    │                   ├── key: ()
 │    │                   │    │                   └── fd: ()-->(22)
 │    │                   │    └── const: 1 [type=int]
 │    │                   └── projections
 │    │                        └── null [type=unknown]
 │    └── values
 │         ├── columns: col_62965:25(oid!null) "_string":26(int)
 │         ├── outer: (14)
 │         ├── cardinality: [1 - 1]
 │         ├── stats: [rows=1]
 │         ├── cost: 0.02
 │         ├── key: ()
 │         ├── fd: ()-->(25,26)
 │         └── tuple [type=tuple{oid, int}]
 │              ├── const: 0 [type=oid]
 │              └── variable: tab_23695._string [type=int]
 └── filters (true)
```
From my debugging, it seems like the subquery indexes are getting screwed up. The reason the type is wrong is that the results of the innermost `exists` subquery (type bool) are being used instead of the enclosing subquery (type unknown). My suspicion is that the indexes are wrong because subqueries are not getting replaced correctly. Instead, each subquery is getting executed multiple times.

I'm sure there's more subtlety to it, but regardless, this does not smell like an optimizer problem to me.

**Comment by yuzefovich** [comment]
Thanks for the investigation @rytaft! And sorry for the "wrongful accusation," I'll make sure before sending any more apply join bugs your way that we fixed that issue :)

**Comment by rytaft** [comment]
No worries! I'm sure there are still bugs on the optimizer side, but these "wrong type" errors all seem like they might be more related to this subquery replacement thing

**Comment by mjibson** [comment]
Doesn't repro anymore.
