### ISSUE TITLE
storage: panic due to tracing use after finish

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#40478]
**Describe the problem**

On a testing cluster we observed the following panic several times. It's not clear that anything special was going on. I've deployed a binary which enables DebugUseAfterFinish and will crash when it happen (https://godoc.org/golang.org/x/net/trace#pkg-variables). This issue is to track the panic. 

```
panic: runtime error: index out of range [recovered]
       panic: runtime error: index out of range
goroutine 136 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc0005d2c60, 0x4e5e460, 0xc000220c00)
       /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:181 +0x121
panic(0x3fa4480, 0x77a6c70)
       /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).addEvent(0xc000802340, 0x3f69700, 0xc00868c450, 0xc00c0a0000)
       /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:805 +0x704
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).LazyPrintf(0xc000802340, 0x44a8d46, 0x2, 0xc00c0a8230, 0x1, 0x1)
       /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:834 +0x9a
github.com/cockroachdb/cockroach/pkg/util/tracing.(*span).LogFields(0xc00d61d7a0, 0xc00b7f4cc0, 0x1, 0x1)
       /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tracer_span.go:393 +0x723
github.com/cockroachdb/cockroach/pkg/util/log.eventInternal(0x4e5e460, 0xc00c886e10, 0xc00c0a0100, 0x450b4ae, 0x24, 0xc0035632e0, 0x2, 0x2)
       /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:128 +0x267
github.com/cockroachdb/cockroach/pkg/util/log.Eventf(...)
       /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:161
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).refreshProposalsLocked(0xc0097f7800, 0x0, 0x1)
       /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:997 +0x913
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc0097f7800, 0x4e5e460, 0xc0061f2540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
       /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:786 +0xd2e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x4e5e460, 0xc0061f2540, 0xc0097f7800, 0x4e5e460)
       /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3599 +0x131
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc000c50000, 0x4e5e460, 0xc0061f2540, 0xc009a4f800, 0xc003563e98, 0x0)
       /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3352 +0x150
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc000c50000, 0x4e5e460, 0xc000220c00, 0x16)
       /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3588 +0x1f4
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc00016e500, 0x4e5e460, 0xc000220c00)
       /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:238 +0x214
```

**Environment:**
 - CockroachDB at 58d0fc3676726c7fa3ebaf41e99f54f305f25fa0
 - Server OS: Linux
 - Client app: `workload kv`

**Comment by ajwerner** [comment]
Finally got a repro:
```
Finished at:
goroutine 701289 [running]:
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).Finish(0xc00b784820)
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:405 +0x372
github.com/cockroachdb/cockroach/pkg/util/tracing.(*span).FinishWithOptions(0xc00b78c460, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tracer_span.go:316 +0x131
github.com/cockroachdb/cockroach/pkg/util/tracing.(*span).Finish(0xc00b78c460)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tracer_span.go:300 +0x67
github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x4e5e7c0, 0xc00cc31ce0, 0x447c540, 0xc00c4a6100, 0xc00bc55b00, 0xc00bc55b20, 0x43b9320, 0xc01a056a80, 0x0, 0x0)                                                                            
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:69 +0x343
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func2(0x4e5e7c0, 0xc00cc31ce0, 0x447c540, 0xc00c4a6100, 0xc00bc55b00, 0xc00bc55b20, 0x76c398, 0x20, 0x404e180, 0xc01656b301)                                                                                                                              
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:221 +0xb6
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func4(0x4e5e7c0, 0xc00cc31ce0, 0x447c540, 0xc00c4a6100, 0xc00bc55b00, 0xc00bc55b20, 0xc00b652bc8, 0x84cb7a, 0x42415c0, 0xc00cc31ce0)                                                                                                                      
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:251 +0xac
github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler(0x443f0e0, 0xc0008c6000, 0x4e5e7c0, 0xc00cc31ce0, 0xc01656b3e0, 0xc0003b3c90, 0x4e5e7c0, 0xc00cc31ce0, 0xc00c1b4600, 0x13e)                                                                                                                            
        /go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9984 +0x158
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c9380, 0x4ec2420, 0xc00081ec00, 0xc00b58b100, 0xc000d27800, 0x77a86a0, 0x0, 0x0, 0x0)                                                                                                                                       
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:999 +0x466
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000c9380, 0x4ec2420, 0xc00081ec00, 0xc00b58b100, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1279 +0xda6
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc001070780, 0xc0000c9380, 0x4ec2420, 0xc00081ec00, 0xc00b58b100)                                                                                                                                                            
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:717 +0x9f
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:715 +0xa1

Used at:
goroutine 182 [running]:
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).addEvent(0xc00b784820, 0x3f69880, 0xc00e32cf00, 0xc00f350000)
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:779 +0x5d6
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).LazyPrintf(0xc00b784820, 0x44a8ee6, 0x2, 0xc00f35c630, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:834 +0x9a
github.com/cockroachdb/cockroach/pkg/util/tracing.(*span).LogFields(0xc00b78c460, 0xc0076d3540, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tracer_span.go:393 +0x723
github.com/cockroachdb/cockroach/pkg/util/log.eventInternal(0x4e5e7c0, 0xc00cc31f80, 0xc00f350100, 0x450b69c, 0x24, 0xc00f17d2e0, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:128 +0x267
github.com/cockroachdb/cockroach/pkg/util/log.Eventf(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:161
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).refreshProposalsLocked(0xc00d726000, 0x0, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:997 +0x913
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc00d726000, 0x4e5e7c0, 0xc015070ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)                                                                                                                                                          
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:786 +0xd2e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x4e5e7c0, 0xc015070ea0, 0xc00d726000, 0x4e5e7c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3599 +0x131
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc000f1ca00, 0x4e5e7c0, 0xc015070ea0, 0xc00da28600, 0xc00f17de98, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3352 +0x150
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc000f1ca00, 0x4e5e7c0, 0xc000b3b7d0, 0x16)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3588 +0x1f4
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc000567600, 0x4e5e7c0, 0xc000b3b7d0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:238 +0x214
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x4e5e7c0, 0xc000b3b7d0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:161 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc000385400, 0xc000630240, 0xc0003853d0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xfb
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xa8
```

**Comment by ajwerner** [comment]
Unfortunately it's not the most informative reproduction I've ever seen. It tells us that we've acknowledged a client but still have a pending reproposal.

**Comment by nvanbenschoten** [comment]
Nice job getting a reproduction. I wonder why we're acknowledging the client without removing the proposal from the pending proposals map. The only thing I can think of is that we're hitting the following logic and deciding not to remove the proposal from the map:

https://github.com/cockroachdb/cockroach/blob/18bdfe1a691fa6d785d510e86d27cecdac9c436e/pkg/storage/replica_application_decoder.go#L97-L105

If we hit this and then did ack the client (perhaps with an error) then it would cause such a situation.

We used to handle this case by not even binding the proposal to the command but that was removed in https://github.com/cockroachdb/cockroach/commit/de8b047b32ea6e42108453faa0f598a5f5f05213#diff-0a45bbf0698befec23ad607c98758aefL84. I think I may have missed the main property that we were enforcing with the old approach - that being that we would never allow a proposal to be acknowledged before it was removed from the map. We might need to revert part of that commit.

How were you able to reproduce this? Would you feel comfortable being able to determine whether a change fixes the issue?

**Comment by ajwerner** [comment]
There wasn't any interesting surrounding logging. There had been a snapshot two seconds before which seems like too far in the future to matter.

Looking at the timeseries data we see a number of splits and lease transfers around the same time.

We know that we won't delete the proposal from the map if there exists a reproposal at a higher MLAI. We will acknowledge a client on the first non-reproposable index. So we need a case where we have two outstanding copies of the same proposal at different MLAI such that both will ultimately fail to due to something like NotLeaseHolderError such that the first command which fails is applied in a different batch than the second.

* c1 proposed under lease 1 at LAI1 (c1.1@1)
* c1 reproposed due to raft leadership change (c1.2@1)
* c1.1@1 commits but fails due to lease applied index, reproposed as c1.3@2
* Lease transfer occurs
* c1.2@1 commits but fails due to NotLeaseHolderError, acknowledges client
* c1.3@2 gets reproposed due to a raft leadership change after the command is acknowledged

**Comment by ajwerner** [comment]
> How were you able to reproduce this? Would you feel comfortable being able to determine whether a change fixes the issue?

Just running cyan with a hacked binary. It's not super confidence inspiring. I'll work on writing a test. A simple enough solution is to reset the context on the proposal when we finish it.

**Comment by ajwerner** [comment]
>We used to handle this case by not even binding the proposal to the command but that was removed in de8b047#diff-0a45bbf0698befec23ad607c98758aefL84. I think I may have missed the main property that we were enforcing with the old approach - that being that we would never allow a proposal to be acknowledged before it was removed from the map. We might need to revert part of that commit.

Yeah that's the logic I've been staring at. The problem as I see it is that we sort of do want to return the earliest error we get and it is sort of nice to have proposals attached to all of the committed commands.

We could:

1) delete the proposal from the map if we apply and are not at the highest index. Later proposals which are in the same batch will already have had their contexts forked. Later proposals in later batches will now be gone. 

something like:

```go
diff --git a/pkg/storage/replica_application_state_machine.go b/pkg/storage/replica_application_state_machine.go
index d7c78e376e..eb70a1f570 100644
--- a/pkg/storage/replica_application_state_machine.go
+++ b/pkg/storage/replica_application_state_machine.go
@@ -899,6 +899,14 @@ func (sm *replicaStateMachine) ApplySideEffects(
                        }
                }
                cmd.proposal.applied = true
+               // There exists an outstanding command at a higher MaxLeaseIndex which
+               // cannot apply, delete it from the proposal map to prevent further
+               // reproposals
+               if cmd.raftCmd.MaxLeaseIndex != cmd.proposal.command.MaxLeaseIndex {
+                       sm.r.mu.Lock()
+                       delete(sm.r.mu.proposals, cmd.idKey)
+                       sm.r.mu.Unlock()
+               }
        }
        return cmd, nil
 }

```
2) check the applied flag when looking at reproposals and skip them and also treat already applied commands as non-local

Something like:

```
diff --git a/pkg/storage/replica_application_decoder.go b/pkg/storage/replica_application_decoder.go
index 0f532ff48d..9eb52326e8 100644
--- a/pkg/storage/replica_application_decoder.go
+++ b/pkg/storage/replica_application_decoder.go
@@ -85,6 +85,9 @@ func (d *replicaDecoder) retrieveLocalProposals(ctx context.Context) (anyLocal b
        for it.init(&d.cmdBuf); it.Valid(); it.Next() {
                cmd := it.cur()
                cmd.proposal = d.r.mu.proposals[cmd.idKey]
+               if cmd.proposal != nil && cmd.proposal.applied {
+                       cmd.proposal = nil
+               }
                anyLocal = anyLocal || cmd.IsLocal()
        }
        if !anyLocal && d.r.mu.proposalQuota == nil {
diff --git a/pkg/storage/replica_raft.go b/pkg/storage/replica_raft.go
index 6d5a044657..ccbcfa6d39 100644
--- a/pkg/storage/replica_raft.go
+++ b/pkg/storage/replica_raft.go
@@ -935,7 +935,11 @@ func (r *Replica) refreshProposalsLocked(refreshAtDelta int, reason refreshRaftR
        }

        var reproposals pendingCmdSlice
-       for _, p := range r.mu.proposals {
+       for idKey, p := range r.mu.proposals {
+               if p.applied {
+                       delete(r.mu.proposals, idKey)
+                       continue
+               }
                if p.command.MaxLeaseIndex == 0 {
                        // Commands without a MaxLeaseIndex cannot be reproposed, as they might
                        // apply twice. We also don't want to ask the proposer to retry these
```
