### ISSUE TITLE
crash report in Mac OS 

### ISSUE THREAD

**Issue by Abdukahhor** [cockroachdb/cockroach#40575]
cockroach start --insecure --listen-addr=localhost
*
* WARNING: RUNNING IN INSECURE MODE!
* 
* - Your cluster is open for any client that can access localhost.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
* 
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v19.1/secure-a-cluster.html
*
CockroachDB node starting at 2019-09-06 16:20:41.945841 +0000 UTC (took 0.3s)
build:               CCL v19.1.4 @ 2019/08/06 15:29:00 (go1.11.6)
webui:               http://localhost:8080
sql:                 postgresql://root@localhost:26257?sslmode=disable
client flags:        cockroach <client cmd> --host=localhost:26257 --insecure
logs:                /Users/andyarzykulov/downloads/cockroach-v19.1.4.darwin-10.9-amd64/cockroach-data/logs
temp dir:            /Users/andyarzykulov/downloads/cockroach-v19.1.4.darwin-10.9-amd64/cockroach-data/cockroach-temp300736218
external I/O path:   /Users/andyarzykulov/downloads/cockroach-v19.1.4.darwin-10.9-amd64/cockroach-data/extern
store[0]:            path=/Users/andyarzykulov/downloads/cockroach-v19.1.4.darwin-10.9-amd64/cockroach-data
status:              initialized new cluster
clusterID:           65ddced9-61c6-4ff5-a37f-674382789e2d
nodeID:              1
*
* ERROR: [n1,s1,r4/1:/System{/tsd-tse}] Reported as error 5cbf5f7226ff45a8959b62ddf9c802ad
*
F190906 17:17:12.820709 274 storage/replica_raft.go:1943  [n1,s1,r4/1:/System{/tsd-tse}] could not commit batch: IO error: While open a file for appending: /Users/andyarzykulov/downloads/cockroach-v19.1.4.darwin-10.9-amd64/cockroach-data/000006.log: No such file or directory
goroutine 274 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc0000bdb00, 0xc0000bdb00, 0x8b2d400, 0x17)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x9080d40, 0xc000000004, 0x8b2d481, 0x17, 0x797, 0xc009c94700, 0xd9)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x95a
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x72845c0, 0xc000ac9710, 0x4, 0x2, 0x0, 0x0, 0xc00a65afe0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2d8
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x72845c0, 0xc000ac9710, 0x1, 0x4, 0x0, 0x0, 0xc00a65afe0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x72845c0, 0xc000ac9710, 0xc00a65afe0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:191 +0x6c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc000278f00, 0x72845c0, 0xc000ac9710, 0xc000325870, 0x8, 0x6, 0x337, 0x100000001, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:1943 +0x6c3
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc000278f00, 0x72845c0, 0xc000ac97d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:816 +0x13df
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc000278f00, 0x72845c0, 0xc000ac97d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:505 +0x137
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc0005f0600, 0x72845c0, 0xc000ac97d0, 0x4)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3693 +0x128
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc00080c980, 0x72845c0, 0xc000936000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:214 +0x258
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x72845c0, 0xc000936000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc000299350, 0xc0001c1560, 0xc000299340)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8

****************************************************************************

This node experienced a fatal error (printed above), and as a result the
process is terminating.

Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
problem in CockroachDB. With your help, the support team at Cockroach Labs
will try to determine the root cause, recommend next steps, and we can
improve CockroachDB based on your report.

**Comment by Abdukahhor** [comment]
this is my fault. I started from removed folder.
