### ISSUE TITLE
The testLogic test failed because it lasted more than 10 minutes.

### ISSUE THREAD

**Issue by gaoziqi** [cockroachdb/cockroach#40817]
How to fix it？
How to change timeout？

```
goroutine 459080 [sync.Cond.Wait, 8 minutes]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc035b918d0, 0xc00000000f)
	/usr/local/go/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc035b918c0)
	/usr/local/go/src/sync/cond.go:56 +0x9e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc01486f600, 0x6d03160, 0xc025f237d0)
	/Users/gaoziqi/work/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:196 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x6d03160, 0xc025f237d0)
	/Users/gaoziqi/work/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:*** Test killed: ran too long (10m0s).
FAIL	github.com/cockroachdb/cockroach/pkg/sql/logictest	605.551s
```

**Comment by jordanlewis** [comment]
Try using `TESTTIMEOUT` environment variable for the Makefile.
