### ISSUE TITLE
storage: nil pointer dereference in `execChangeReplicasTxn`

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#40877]
Saw this while roachprod-stressing `TestPartitioning` using @ajwerner's PR (https://github.com/cockroachdb/cockroach/pull/40868).

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x2b1dbda]

goroutine 1071779 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc001b09ef0, 0x4739de0, 0xc014c2bf80)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:181 +0x121
panic(0x399d0e0, 0x6e08660)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/roachpb.(*RangeDescriptor).Replicas(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/roachpb/metadata.go:147
github.com/cockroachdb/cockroach/pkg/storage.execChangeReplicasTxn.func2(0x4739da0, 0xc015434360, 0xc012b84510, 0x0, 0xc015434370)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1569 +0xf4a
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x4739da0, 0xc015434360, 0xc012b84510, 0x0, 0x15c592fdee57cc2f)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:695 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).exec(0xc012b84510, 0x4739da0, 0xc015434360, 0xc01ef581d0, 0x1, 0xc012b84510)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:700 +0xd9
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc002670380, 0x4739da0, 0xc015434360, 0xc01edc8400, 0x4, 0x4)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:694 +0xe4
github.com/cockroachdb/cockroach/pkg/storage.execChangeReplicasTxn(0x4739da0, 0xc015434360, 0xc000b6b500, 0xc01536a770, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1562 +0x278
github.com/cockroachdb/cockroach/pkg/storage.maybeLeaveAtomicChangeReplicas(0x4739da0, 0xc015434360, 0xc000b6b500, 0xc01536a770, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1081 +0x12e
github.com/cockroachdb/cockroach/pkg/storage.(*mergeQueue).process(0xc001d05240, 0x4739da0, 0xc015434360, 0xc01b960800, 0xc015d1cbe0, 0x3e6283c, 0xd)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/merge_queue.go:283 +0x685
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica.func1(0x4739da0, 0xc015434360, 0xdf8475800, 0x4739da0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:901 +0x2ad
github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout(0x4739da0, 0xc015434360, 0xc0138f01e0, 0x1f, 0xdf8475800, 0xc01e58c030, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:135 +0x9d
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica(0xc000072500, 0x4739de0, 0xc01e58c000, 0x47a9480, 0xc01b960800, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:860 +0x26a
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1.2(0x4739de0, 0xc014c2bf80)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:787 +0xd9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc001b09ef0, 0x4739de0, 0xc014c2bf80, 0xc012ea9ec0, 0x29, 0x0, 0x0, 0xc014c2bfb0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:321 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:316 +0x131
```

replica_command.go:1569 corresponds to:

```
		desc, dbDescValue, err := conditionalGetDescValueFromDB(ctx, txn, referenceDesc.StartKey, check)
		if err != nil {
			return err
		}
		if chgs.leaveJoint() && !desc.Replicas().InAtomicReplicationChange() { // <---
			// Nothing to do. See comment in 'check' above for details.
			returnDesc = desc
			return nil
		}
```

@ajwerner care to fill in your hypothesis of how this could happen? I'm not terribly familiar with this code.

**Comment by ajwerner** [comment]
We panic on the second half of the condition here: https://github.com/cockroachdb/cockroach/blob/98159fa6c1c9d86643ca89b03c3a2ee141189686/pkg/storage/replica_command.go#L1569

we'd get there if in the below code we don't find a range descriptor (which can happen if the range has been merged away)

https://github.com/cockroachdb/cockroach/blob/98159fa6c1c9d86643ca89b03c3a2ee141189686/pkg/storage/replica_command.go#L1936

The fix may be as simple as:

```
--- a/pkg/storage/replica_command.go
+++ b/pkg/storage/replica_command.go
@@ -1542,7 +1542,7 @@ func execChangeReplicasTxn(
        descKey := keys.RangeDescriptorKey(referenceDesc.StartKey)
 
        check := func(kvDesc *roachpb.RangeDescriptor) bool {
-               if chgs.leaveJoint() {
+               if kvDesc != nil && kvDesc.RangeID == referenceDesc.RangeID && chgs.leaveJoint() {
                        // If there are no changes, we're trying to leave a joint config,
                        // so that's all we care about. But since leaving a joint config
                        // is done opportunistically whenever one is encountered, this is
```

I think that this is fallout from https://github.com/cockroachdb/cockroach/pull/40370

**Comment by petermattis** [comment]
FWIW, with @ajwerner's patch I no longer saw the nil-pointer dereference. I'll leave it in one of your capable hands to get a test written for this.
