### ISSUE TITLE
 unable to commit Raft entry batch: non-deterministic failure: unable to commit Raft entry batch: Corruption: Out-of-order key insertion into table

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#40918]
**Describe the problem**

I tried reproducing the issue described in #37315.

**To Reproduce**

1. Ran a single node like this:
`cockroach.exe  start-single-node --insecure`
2. Ran the script that is listed in #37315

**Expected behavior**
I expect the script to execute until the end without the server crashing.

**Environment:**
 - CockroachDB version [CCL v19.2.0-alpha.20190606-2275-g16af2ea-dirty @ 2019/09/18 15:49:54 (go1.12.5)]
 - Server OS: [Microsoft Windows [Version 10.0.18362.356]]
 - Client app [JDBC postgres driver 42.2.5]

**Additional context**
The server crashes after few min.

```
CockroachDB node starting at 2019-09-19 17:03:40.9965763 +0000 UTC (took 3.1s)
build:               CCL v19.2.0-alpha.20190606-2275-g16af2ea-dirty @ 2019/09/18 15:49:54 (go1.12.5)
webui:               http://DARINPESHEV0713:8080
sql:                 postgresql://root@DARINPESHEV0713:26257?sslmode=disable
RPC client flags:    cockroach.exe <client cmd> --host=DARINPESHEV0713:26257 --insecure
logs:                F:\cockroach\cockroach-data\logs
temp dir:            F:\cockroach\cockroach-data\cockroach-temp407885011
external I/O path:   F:\cockroach\cockroach-data\extern
store[0]:            path=F:\cockroach\cockroach-data
status:              initialized new cluster
clusterID:           06e495dc-8889-4fac-b10c-34efd0676aa0
nodeID:              1
F190919 17:18:57.396976 88 storage/store.go:3697  [n1,s1,r73/1:/{Table/52/1/1…-Max}] unable to commit Raft entry batch: non-deterministic failure: unable to commit Raft entry batch: Corruption: Out-of-order key insertion into table
goroutine 88 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc000094100, 0xc0000941e0, 0x0, 0x31)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1016 +0xb8
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x73fc840, 0xc000000004, 0x7229f5a, 0x10, 0xe71, 0xc00025d140, 0xb7)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:872 +0x962
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4deb460, 0xc009062ae0, 0xc000000004, 0x2, 0x447e282, 0x7, 0xc009311e38, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2d3
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4deb460, 0xc009062ae0, 0x1, 0xc000000004, 0x447e282, 0x7, 0xc009311e38, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x93
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:180
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc00089ee00, 0x4deb460, 0xc0007c41e0, 0x49)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3697 +0x5c2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc00051dc00, 0x4deb460, 0xc0007c41e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:227 +0x259
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x4deb460, 0xc0007c41e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:161 +0x45
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc000271960, 0xc000575290, 0xc000271950)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x102
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xaf
```

**Comment by petermattis** [comment]
That error was only recently added by @itsbilal. Should be impossible. What the heck is going on? We should print out the keys involved. See `c-deps/rocksdb/table/block_based_table_builder.cc:BlockBasedTableBuilder::Add()`. @ajkr can help with the specifics.

**Comment by darinpp** [comment]
The content of the data folder split into two:
[data.zip](https://github.com/cockroachdb/cockroach/files/3632551/data.zip)
[sst.zip](https://github.com/cockroachdb/cockroach/files/3632552/sst.zip)

**Comment by andy-kimball** [comment]
I'll add this to the Beta Blockers list, since we don't yet know if this might also be a problem on Linux.

**Comment by andy-kimball** [comment]
@darinpp is going to re-run the script that found this issue on Mac, to see if we can get an easier repro.

**Comment by ajkr** [comment]
@darinpp  Here's a small RocksDB patch to get more info for debugging info. It also aborts as soon as we encounter the bug to ensure compaction inputs don't get cleaned up in case we want to inspect them later.

```
diff --git a/table/block_based_table_builder.cc b/table/block_based_table_builder.cc
index 1702bedb9..fa0b797ae 100644
--- a/table/block_based_table_builder.cc
+++ b/table/block_based_table_builder.cc
@@ -502,11 +502,27 @@ void BlockBasedTableBuilder::Add(const Slice& key, const Slice& value) {
   if (IsValueType(value_type)) {
     if (r->props.num_entries > r->props.num_range_deletions) {
       if (r->internal_comparator.Compare(key, Slice(r->last_key)) <= 0) {
+        ParsedInternalKey prev_parsed, curr_parsed;
+        if (!ParseInternalKey(Slice(r->last_key), &prev_parsed)) {
+          fprintf(stderr, "prev key parse failure: %s\n",
+                  Slice(r->last_key).ToString(true /* hex */).c_str());
+        }
+        if (!ParseInternalKey(key, &curr_parsed)) {
+          fprintf(stderr, "curr key parse failure: %s\n",
+                  key.ToString(true /* hex */).c_str());
+        }
         // We were about to insert keys out of order. Abort.
         ROCKS_LOG_ERROR(r->ioptions.info_log,
-                        "Out-of-order key insertion into block based table");
+                        "Out-of-order key insertion into block based table. "
+                        "Prev key: %s; curr key: %s.",
+                        prev_parsed.DebugString(true /* hex */).c_str(),
+                        curr_parsed.DebugString(true /* hex */).c_str());
         r->status =
             Status::Corruption("Out-of-order key insertion into table");
+        // ensure logs are `fflush()`ed so they are pushed down to kernel
+        // before crashing the process
+        r->ioptions.info_log->Flush();
+        abort();
         return;
       }
     }
```

**Comment by ajkr** [comment]
I'm a bit worried about whether this will work since our `DBLogger` implementation doesn't support `Flush()`. If you haven't run it yet, it might be better to change these `ROCKS_LOG_ERROR`s to `ROCKS_LOG_FATAL`s as we flush, sync, and copy to stderr upon seeing a fatal. For error it looks like we do none of these.
