### ISSUE TITLE
sql: ERROR: cached plan must not change result type

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#41445]
The hibernate AutoRollbackTestSuite tests that different types of queries that experience various types of failures are rolled back and can be retried. Sometimes the tests fail with this error:

```
org.postgresql.util.PSQLException: ERROR: cached plan must not change result type
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at org.postgresql.test.jdbc2.AutoRollbackTestSuite.run(AutoRollbackTestSuite.java:328)
```

The test intentionally breaks a prepared statement by executing an `ALTER TABLE` query, but when auto-commit is on, the test expects no exception to occur.

Jira issue: CRDB-5449

**Comment by jordanlewis** [comment]
This is probably a @cockroachdb/sql-planning issue. Can you attempt to find the query that caused the error please?

**Comment by rafiss** [comment]
There are many different test cases this comes up with. I am in the process of adding the list of queries that have issues.

**Comment by rafiss** [comment]
I'm not sure if It is a SQL planning issue. I didn't realize until now since I just made this issue as a placeholder while I was investigating more, but the test breaks the prepared statement on purpose.

**Comment by RaduBerinde** [comment]
This error should only show up if a statement was prepared, and later executed after schema has changed in such a way that the query now returns different types than before. This is consistent with postgres.

If we are returning it in other cases, it's a bug. Try setting the `sql.query_cache.enabled` cluster setting to `false`; if that makes a difference, it's probably a bug related to query caching.

**Comment by knz** [comment]
I think we should check the hibernate test for this and see if the situation has changed.

- if fixed: closed
- if not fixed: reprioritize, there's still a bug

**Comment by rafiss** [comment]
this was fixed by https://github.com/hibernate/hibernate-orm/commit/d767d46d05a9a1f754dca6be870bbf9f17bdb553
