### ISSUE TITLE
sql: PGJDBC encounters "SimpleQuery not allowed while in extended protocol mode"

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#41511]
The PGJDBC driver has a test suite in `AutoRollbackTestSuite.java`.

The following query fails in a lot of the test cases. Note that it fails before any of the rollback logic is tested -- this error happens right at the beginning of the test.

```
insert into rollbacktest(a, str) values (0, 'test')
```
```
org.postgresql.util.PSQLException: ERROR: SimpleQuery not allowed while in extended protocol mode
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)
        at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:246)
        at org.postgresql.test.jdbc2.AutoRollbackTestSuite.run(AutoRollbackTestSuite.java:240)
```

could relate to #33693

**Comment by perezd** [comment]
I was able to produce this failure condition using Elixir/Postgrex as well in a testing context.
