### ISSUE TITLE
sql: PGJDBC encounters "there is already a transaction in progress" error

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#41513]
The pgjdbc driver has a test called `BatchExecuteTest.testBatchWithAlternatingTypes`.

The error happens right at the beginning of the test, and the tests do not share connections with each other. It is not clear how another transaction could be in progress.

The first thing the test does is send a `BEGIN` statement, which fails with

```
org.postgresql.util.PSQLException: ERROR: there is already a transaction in progress
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:269)
	at org.postgresql.test.jdbc2.BatchExecuteTest.testBatchWithAlternatingTypes(BatchExecuteTest.java:743)
```

Jira issue: CRDB-5441

**Comment by rafiss** [comment]
caused by #54954
