### ISSUE TITLE
sql: support regex match backreferences

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#41645]
PostgreSQL supports regex backreferences in SIMILAR TO regex queries, of the form `foo(.*)bar\1`. CockroachDB is missing that feature.

See https://www.postgresql.org/docs/9.3/functions-matching.html#POSIX-ESCAPE-SEQUENCES

**Comment by avinashdhinwa** [comment]
@jordanlewis Can I pick this up?

**Comment by jordanlewis** [comment]
Yes, feel free!

**Comment by avinashdhinwa** [comment]
@jordanlewis Can you point me in the codebase where I should look?

**Comment by timgraham** [comment]
It's still a valid issue that shouldn't be closed as stale. Django sets `DatabaseFeatures.supports_regex_backreferencing = False` in order to skip a test that otherwise crashes:
```
=====================================================================
ERROR: test_regex_backreferencing (lookup.tests.LookupTests.test_regex_backreferencing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.virtualenvs/django312/lib/python3.12/site-packages/psycopg/cursor.py", line 117, in execute
    raise ex.with_traceback(None)
psycopg.errors.InvalidRegularExpression: invalid regular expression: error parsing regexp: invalid escape sequence: `\1`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/django/tests/lookup/tests.py", line 1400, in test_regex_backreferencing
    self.assertQuerySetEqual(
  File "/home/tim/code/django/django/test/testcases.py", line 1302, in assertQuerySetEqual
    return self.assertEqual(list(items), values, msg=msg)
                            ^^^^^^^^^^^
  File "/home/tim/code/django/django/db/models/query.py", line 434, in __iter__
    self._fetch_all()
  File "/home/tim/code/django/django/db/models/query.py", line 2239, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/django/django/db/models/query.py", line 297, in __iter__
    for row in compiler.results_iter(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1573, in results_iter
    results = self.execute_sql(
              ^^^^^^^^^^^^^^^^^
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1624, in execute_sql
    cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/django/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/django/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/tim/code/django/django/db/utils.py", line 94, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/code/django/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.virtualenvs/django312/lib/python3.12/site-packages/psycopg/cursor.py", line 117, in execute
    raise ex.with_traceback(None)
django.db.utils.DataError: invalid regular expression: error parsing regexp: invalid escape sequence: `\1`
```
