### ISSUE TITLE
storage/engine: fix COCKROACH_STORAGE_ENGINE=pebble test failures

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#41987]
The good news is that most packages tests pass when we force usage of Pebble as the storage engine

```
~ COCKROACH_TEST_STORAGE_ENGINE=pebble make test | grep ^ok | wc -l
...
211
```

There are failures in a handful of packages:

```
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/storageccl	5.161s
FAIL	github.com/cockroachdb/cockroach/pkg/server	39.587s
FAIL	github.com/cockroachdb/cockroach/pkg/sql/logictest	1201.909s
FAIL	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder	822.459s
```

The `ccl/storageccl` failure is due to the lack of support for [`CheckForKeyCollisions`](https://github.com/cockroachdb/cockroach/issues/41744).

The `server` failure is in `TestStatusEngineStatsJson`. Cause unknown.

The `sql/logictest` failure is a timeout. Presumably something is spinning and not making progress.

The `execbuilder` failure is in `TestExecBuild/5node-dist/distsql_join`. I've seen similar failures using RocksDB, so it is possible this is something weird in my dev environment.

**Comment by petermattis** [comment]
> The sql/logictest failure is a timeout. Presumably something is spinning and not making progress.

Not sure what is going on, but running `COCKROACH_TEST_STORAGE_ENGINE=pebble make test PKG=./sql/logictest TESTFLAGS=-v` shows the `logic.test` process using close to 7GB of RAM. When using `rocksdb` the test hovers close to 1GB.

**Comment by petermattis** [comment]
Well, these results are a lot less impressive than they first appeared because in-memory stores currently always use RocksDB. In-memory stores are the default for `TestServer` and `TestCluster`. The only tests which are affected are the ones which start disk-based servers.

**Comment by petermattis** [comment]
There are currently failures in 10 packages:

```
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/backupccl	0.437s
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl	0.355s
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/importccl	66.321s
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/partitionccl	120.870s
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/storageccl	0.274s
FAIL	github.com/cockroachdb/cockroach/pkg/cli	495.557s
FAIL	github.com/cockroachdb/cockroach/pkg/sql	224.883s
FAIL	github.com/cockroachdb/cockroach/pkg/sql/logictest	474.707s
FAIL	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder	453.156s
FAIL	github.com/cockroachdb/cockroach/pkg/storage	206.315s
```

The `*ccl` failures all seem to be due to the missing `ExportToSst` which is in progress. The other failures are either timeouts, or stats inconsistencies. The failures in the `storage` package look relatively innocuous and easy to fix. The stats inconsistencies are the most disturbing.

**Comment by petermattis** [comment]
The `cli` failure is even more disturbing:

```
F191105 23:54:37.905557 720784 storage/replica.go:1005  [n6,s6,r1/6:/{Min-System/NodeL…}] on-disk and in-memory state diverged: [TruncatedState.Index: 606 != 685]
```

On the bright side, I think this is the failure I saw running `kv95`. I've been able to reproduce this failure which means finding the cause is only a matter of time.

**Comment by petermattis** [comment]
Update: many of the `ccl/...` tests passes. The `ccl/importccl` package completely passes. `cli` and `storage` still have failures. Looks like the failures are various timeouts during test setup due to conditions not being met, or a disturbing failure (that happens in multiple tests) with the symptom:

```
F191108 20:07:35.466154 4389 storage/replica.go:1005  [n2,s2,r226/2:/Table/80/1/-4.06947092049069…] on-disk and in-memory state diverged: [Lease.Start.WallTime: 1573243650575455000 != 1573243654097626000 Lease.Replica.NodeID: 3 != 2 Lease.Rep
lica.StoreID: 3 != 2 Lease.Replica.ReplicaID: 1 != 2 Lease.ProposedTS.WallTime: 1573243650575456000 != 1573243654097627000 Lease.Sequence: 10 != 11]
goroutine 4389 [running]:
```

The easiest reproduction of the above is:

```
~ COCKROACH_TEST_STORAGE_ENGINE=pebble make test PKG=./cli TESTS=TestRemoveDeadReplicas
```

Another interesting common failure has a timeout symptom. The logs show:

```
I191108 19:43:03.735739 2991 ccl/backupccl/backup_test.go:123  SucceedsSoon: found "sstsnapshot" remaining in /var/folders/hb/f910f4j93_l7kfp2xc8hy9pr0000gp/T/cockroach-auxiliary275695675
I191108 19:43:04.738738 2991 ccl/backupccl/backup_test.go:123  SucceedsSoon: found "sstsnapshot" remaining in /var/folders/hb/f910f4j93_l7kfp2xc8hy9pr0000gp/T/cockroach-auxiliary275695675
I191108 19:43:05.742675 2991 ccl/backupccl/backup_test.go:123  SucceedsSoon: found "sstsnapshot" remaining in /var/folders/hb/f910f4j93_l7kfp2xc8hy9pr0000gp/T/cockroach-auxiliary275695675
I191108 19:43:06.744637 2991 ccl/backupccl/backup_test.go:123  SucceedsSoon: found "sstsnapshot" remaining in /var/folders/hb/f910f4j93_l7kfp2xc8hy9pr0000gp/T/cockroach-auxiliary275695675
I191108 19:43:07.748375 2991 ccl/backupccl/backup_test.go:123  SucceedsSoon: found "sstsnapshot" remaining in /var/folders/hb/f910f4j93_l7kfp2xc8hy9pr0000gp/T/cockroach-auxiliary275695675
...
```

This can be reproduced via:

```
~ COCKROACH_TEST_STORAGE_ENGINE=pebble make test PKG=./ccl/backupccl TESTS=TestBackupRestorePartitioned
```

I'm guessing there is a simple fix for this one.

**Comment by petermattis** [comment]
Closing this out in favor of https://github.com/cockroachdb/cockroach/issues/42355.
