### ISSUE TITLE
panic: IO error: /tmp/db"/038965.sst: No space left on device

### ISSUE THREAD

**Issue by dmitry-si** [cockroachdb/cockroach#420]
```
panic: IO error: /tmp/db"/038965.sst: No space left on device

goroutine 50 [running]:
github.com/cockroachdb/cockroach/multiraft.(*writeTask).start(0xc208144750)
	/go/src/github.com/cockroachdb/cockroach/multiraft/storage.go:158 +0x6e5
created by github.com/cockroachdb/cockroach/multiraft.(*state).start
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:409 +0x166

goroutine 1 [chan receive, 1314 minutes]:
github.com/cockroachdb/cockroach/server/cli.runStart(0x186b020, 0xc20800a050, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/cli/start.go:164 +0x96b
github.com/cockroachdb/cockroach/server/cli.runInit(0x186b020, 0xc20800a050, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/cli/start.go:115 +0x4d4
code.google.com/p/go-commander.(*Commander).Run(0xc20809cdb0, 0xc20800a050, 0x0, 0x0, 0x0, 0x0)
	/go/src/code.google.com/p/go-commander/commands.go:75 +0x776
main.main()
	/go/src/github.com/cockroachdb/cockroach/main.go:110 +0x5af
```

```
if err != nil {
  panic(err) // TODO(bdarnell): mark this node dead on storage errors
}
```
Well, it seems important to go into RO mode for this node. It also happened on a cluster of 3 roach nodes, it seems all the data went into a since roach storage, any hints on balancing data distribution on the cluster?

Anything I can do to help here?

**Comment by dmitry-si** [comment]
followed by
```
F0312 23:53:57.389445      11 clock_offset.go:160] clock offset from the cluster time for remote clocks map[roach-0.c.scaled-inference.internal:9000:{-1426204418550021265 4878 1426204418550026143 []} 10.240.113.163:56664:{76414947 781835 1426204410288375611 []} roach-2.c.scaled-inference.internal:9000:{-1426204434622117877 3597 1426204434622121474 []}] could not be determined: a majority of connected remote clocks have failed to encompass the true time for the cluster
goroutine 10 [running]:
github.com/golang/glog.stacks(0x1894d00, 0x0, 0x0, 0x0)
	/go/src/github.com/golang/glog/glog.go:766 +0xcd
github.com/golang/glog.(*loggingT).output(0x188cb80, 0xc200000003, 0xc20805c0c0, 0x150be9f, 0xf, 0xa0, 0x0)
	/go/src/github.com/golang/glog/glog.go:717 +0x283
github.com/golang/glog.(*loggingT).printf(0x188cb80, 0x3, 0x13035b0, 0x53, 0xc2081ebf80, 0x2, 0x2)
	/go/src/github.com/golang/glog/glog.go:655 +0x1ef
github.com/golang/glog.Fatalf(0x13035b0, 0x53, 0xc2081ebf80, 0x2, 0x2)
	/go/src/github.com/golang/glog/glog.go:1145 +0x64
github.com/cockroachdb/cockroach/rpc.(*RemoteClockMonitor).MonitorRemoteOffsets(0xc20801eb00)
	/go/src/github.com/cockroachdb/cockroach/rpc/clock_offset.go:160 +0x1f6
created by github.com/cockroachdb/cockroach/server.NewServer
	/go/src/github.com/cockroachdb/cockroach/server/server.go:112 +0x726
Warning: Permanently added '130.211.167.54' (RSA) to the list of known hosts.
```

**Comment by petermattis** [comment]
Thanks for the report. Looks like you ran out of disk space and cockroach didn't handle that condition nicely. We haven't spent very much time on robustness in this area. 

I'm not sure what caused the clock_offset error. Perhaps related to nodes in the cluster not responding because they crashed. That's just a guess. 

How did you start this cluster (e.g. `run/local-cluster.sh`)? Were you running on linux, mac os x or something else?

**Comment by dmitry-si** [comment]
```
Dmitrys-MBP-3:si-go dmitry$ cat roach_usage.sh 
#!/bin/bash

for i in "roach-0" "roach-1" "roach-2"; do gcloud compute ssh $i --command 'sudo du -sh /media/roach*'; done 

# Expected:
#
# 5.1G	/media/roach-0-hdd-a
# Warning: Permanently added '130.211.114.215' (RSA) to the list of known hosts.
# 40K	/media/roach-1-hdd-a
# Warning: Permanently added '130.211.138.174' (RSA) to the list of known hosts.
# 40K	/media/roach-2-hdd-a
# Dmitrys-MBP-3:si-go dmitry$ 
Dmitrys-MBP-3:si-go dmitry$ bash roach_usage.sh 
Warning: Permanently added '130.211.115.0' (RSA) to the list of known hosts.
5.2G	/media/roach-0-hdd-a
Warning: Permanently added '130.211.114.215' (RSA) to the list of known hosts.
40K	/media/roach-1-hdd-a
Warning: Permanently added '130.211.138.174' (RSA) to the list of known hosts.
40K	/media/roach-2-hdd-a
```

**Comment by dmitry-si** [comment]
```
Dmitrys-MBP-3:si-go dmitry$ cat roach_usage.sh 
#!/bin/bash

for i in "roach-0" "roach-1" "roach-2"; do gcloud compute ssh $i --command 'sudo du -sh /media/roach*'; done 

# Expected:
#
# 5.1G	/media/roach-0-hdd-a
# Warning: Permanently added '130.211.114.215' (RSA) to the list of known hosts.
# 40K	/media/roach-1-hdd-a
# Warning: Permanently added '130.211.138.174' (RSA) to the list of known hosts.
# 40K	/media/roach-2-hdd-a
# Dmitrys-MBP-3:si-go dmitry$ 
Dmitrys-MBP-3:si-go dmitry$ bash roach_usage.sh 
Warning: Permanently added '130.211.115.0' (RSA) to the list of known hosts.
5.2G	/media/roach-0-hdd-a
Warning: Permanently added '130.211.114.215' (RSA) to the list of known hosts.
40K	/media/roach-1-hdd-a
Warning: Permanently added '130.211.138.174' (RSA) to the list of known hosts.
40K	/media/roach-2-hdd-a
```

**Comment by petermattis** [comment]
Nice, you were trying to run cockroach on gcloud. The fine print should probably be enlarged. Cockroach isn't quite ready for that. In particular, rebalancing isn't there which is why you see all of the disk usage on one node.

**Comment by tschottdorf** [comment]
Closing, since the offset condition is loggeed in #999 and rebalancing isn't implemented yet.
