### ISSUE TITLE
Windows Unexpected panic : Could not get current user or $HOME

### ISSUE THREAD

**Issue by israellot** [cockroachdb/cockroach#42114]
**Environment:**
 - CockroachDB version 19.1.5
 - Server OS: Windows

```
*
* ERROR: Reported as error f19e179954984faab71c0034d307fc7c
*
F191101 13:25:43.623492 21122615 util/log/log.go:40  unexpected panic: Could not get current user or $HOME: The system cannot find the file specified.
goroutine 21122615 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc000075b00, 0xc000075b00, 0x54fbd00, 0xf)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xdb
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x574eee0, 0xc000000004, 0x54fbd9d, 0xf, 0x28, 0xc00724d650, 0x62)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x96c
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3c3fde0, 0xc000090160, 0xc000000004, 0x2, 0x34df65e, 0x14, 0xc0122c37c0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2df
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3c3fde0, 0xc000090160, 0x1, 0x4, 0x34df65e, 0x14, 0xc0122c37c0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x93
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x3c3fde0, 0xc000090160, 0x34df65e, 0x14, 0xc0122c37c0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:182 +0x85
github.com/cockroachdb/cockroach/pkg/util/log.FatalOnPanic()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:40 +0xae
panic(0x2fc4500, 0xc008e237f0)
	/usr/local/go/src/runtime/panic.go:513 +0x1c7
github.com/cockroachdb/cockroach/vendor/github.com/maruel/panicparse/stack.getGOPATHs(0x3bf5dc0, 0xd, 0x3c0d840)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/maruel/panicparse/stack/context.go:373 +0x3a1
github.com/cockroachdb/cockroach/vendor/github.com/maruel/panicparse/stack.ParseDump(0x3c05e00, 0xc00d098930, 0x3c0d840, 0x57761c0, 0xc00a47ba01, 0x20c7a68, 0xc019b74000, 0x100000)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/maruel/panicparse/stack/context.go:69 +0xcc
github.com/cockroachdb/cockroach/pkg/server/debug/goroutineui.NewDumpFromBytes(0x19886724, 0xed54e2957, 0x0, 0xc019b74000, 0x3ac0a, 0x100000, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/debug/goroutineui/dump.go:59 +0xe0
github.com/cockroachdb/cockroach/pkg/server/debug/goroutineui.NewDump(0x19886724, 0xed54e2957, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/debug/goroutineui/dump.go:53 +0xa6
github.com/cockroachdb/cockroach/pkg/server/debug.NewServer.func2(0x3c2b9e0, 0xc0077c9680, 0xc0130ba800)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/debug/server.go:141 +0x40
net/http.HandlerFunc.ServeHTTP(0x362e498, 0x3c2b9e0, 0xc0077c9680, 0xc0130ba800)
	/usr/local/go/src/net/http/server.go:1964 +0x4b
github.com/cockroachdb/cockroach/pkg/server/debug.(*Server).ServeHTTP(0xc0002ca220, 0x3c2b9e0, 0xc0077c9680, 0xc0130ba800)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/debug/server.go:172 +0x98
net/http.(*ServeMux).ServeHTTP(0xc000859838, 0x3c2b9e0, 0xc0077c9680, 0xc0130ba800)
	/usr/local/go/src/net/http/server.go:2361 +0x12e
github.com/cockroachdb/cockroach/pkg/server.(*safeServeMux).ServeHTTP(0xc000859820, 0x3c2b9e0, 0xc0077c9680, 0xc0130ba800)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:147 +0x64
github.com/cockroachdb/cockroach/pkg/server.(*Server).ServeHTTP(0xc000859500, 0x3c3b260, 0xc007a047e0, 0xc0130ba800)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:2006 +0x127
net/http.serverHandler.ServeHTTP(0xc000da75f0, 0x3c3b260, 0xc007a047e0, 0xc0130ba800)
	/usr/local/go/src/net/http/server.go:2741 +0xb2
net/http.(*conn).serve(0xc008a3f220, 0x3c3fda0, 0xc008a370c0)
	/usr/local/go/src/net/http/server.go:1847 +0x64d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2fc
```

**Comment by ricardocrdb** [comment]
Hey @israellot 

There were a number of issues that had crept up in 19.1.X when running cockroach on Windows. Some of these had similar `No file or directory` errors in reference to the local paths of a user's $HOME, so I would suggest trying the latest version 19.2.0, as these issues have been addressed.

Let me know how it works out for you.

**Comment by israellot** [comment]
Thanks for the response. 
At the time I managed to investigate further and this error was in fact a side effect. The original error was the missing timezone info files. The error bumped to the debug routines and there the home path wasn’t found at some point and that’s the error I saw. Apparently it happens when running crdb without a Go installation, so there wasn’t a gopath either.  
Setting the environment variable for the GoPath did the trick, and including the timezone zip file was of course necessary. 
I just wish the documentation for those little details were better organized, I find information to be rather scattered.

**Comment by ricardocrdb** [comment]
Hey @israellot 

Apologies for the lack of clarity. I can pass this along to the docs team in order to see if maybe we can expand on this further. The Windows binary is something we don't recommend for production cases, as the docs mention [here](https://www.cockroachlabs.com/docs/v19.2/install-cockroachdb-windows.html#main-content), but this is something that should still be clarified.

Let me know if there are any other questions.

**Comment by jordanlewis** [comment]
Closing due to age.
