### ISSUE TITLE
sql: "invalid row length" in FK cascades code

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#42120]
Create the following logic test file:
```
statement ok
CREATE TABLE self_ab (a INT UNIQUE, b INT DEFAULT 1, INDEX (b))

statement ok
INSERT INTO self_ab VALUES (1, 2), (2, 2)

statement ok
ALTER TABLE self_ab ADD CONSTRAINT fk FOREIGN KEY (b) REFERENCES self_ab(a) ON UPDATE SET DEFAULT

statement ok
UPDATE self_ab SET a=3 WHERE a=2
```

About half the time I try to run this, I get the error below.

I spent some time trying to figure it out but there is a ton of code here that I'm not very familiar with. I would appreciate if someone more familiar with it can take a look.

```
panic: invalid row length 3, expected 2 [recovered]
	panic: panic while executing 1 statements: UPDATE _ SET _ = _ WHERE _ = _; caused by invalid row length 3, expected 2

goroutine 1142 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00171ed80, 0x429dfe0, 0xc000cd5340, 0x349db00, 0xc00190a5a0)
	/go2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:731 +0x330
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc00171ed80, 0x429dfe0, 0xc000cd5340)
	/go2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:442 +0x61
panic(0x349db00, 0xc00190a5a0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*RowContainer).AddRow(0xc00040b560, 0x429dfe0, 0xc00152e440, 0xc00185ea50, 0x3, 0x3, 0x0, 0xc00106f700, 0x2, 0x2, ...)
	/go2/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/datum_row_container.go:221 +0x441
github.com/cockroachdb/cockroach/pkg/sql/row.(*cascader).cascadeAll(0xc0011b4600, 0x429dfe0, 0xc00152e440, 0xc001e2a480, 0xc00185f5f0, 0x2, 0x3, 0xc00185ea50, 0x3, 0x3, ...)
	/go2/src/github.com/cockroachdb/cockroach/pkg/sql/row/cascader.go:1019 +0x26ad
github.com/cockroachdb/cockroach/pkg/sql/row.(*Updater).UpdateRow(0xc000596a48, 0x429dfe0, 0xc00152e440, 0xc0016d6580, 0xc00185f5f0, 0x2, 0x3, 0xc00190a2c0, 0x1, 0x1, ...)
	/go2/src/github.com/cockroachdb/cockroach/pkg/sql/row/updater.go:490 +0x1c19
github.com/cockroachdb/cockroach/pkg/sql.(*tableUpdater).rowForUpdate(...)
	/go2/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter_update.go:51
github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).processSourceRow(0xc000596a00, 0x429dfe0, 0xc00152e440, 0xc001603d40, 0xc00171f0f0, 0xc00185f5f0, 0x3, 0x3, 0x37f0600, 0xc000fb9801)
	/go2/src/github.com/cockroachdb/cockroach/pkg/sql/update.go:328 +0x83d
github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).BatchedNext(0xc000596a00, 0x429dfe0, 0xc00152e440, 0xc001603d40, 0xc00171f0f0, 0x3552200, 0xc000577470, 0xc000fb9880)
	/go2/src/github.com/cockroachdb/cockroach/pkg/sql/update.go:186 +0x150
github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode).startExec(0xc0002ca440, 0x429dfe0, 0xc00152e440, 0xc001603d40, 0xc00171f0f0, 0xc00190a450, 0xc000fb98c8)
	/go2/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:159 +0xcd
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x39db8f8, 0x5, 0x429fba0, 0xc0002ca440, 0xc0011b48a0, 0xc000fb98d8)
	/go2/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:339 +0x55
```

**Comment by RaduBerinde** [comment]
Note: this is blocking work on #42117.

**Comment by RaduBerinde** [comment]
I figured out why it only fails sometimes - this is thanks to @mjibson's change to randomize column faimilies. If I specify `FAMILY (a,b)` then it never failes, and if I specify `FAMILY (a), FAMILY (b)` it fails every time.

```
CREATE TABLE self_ab (
  a INT UNIQUE,
  b INT DEFAULT 1,
  INDEX (b),
  FAMILY (a),
  FAMILY (b)
)
```

**Comment by BramGruneir** [comment]
Interesting.  I don't know if I ever tested Cascades with multiple column
families.

I'll try to take a look this afternoon.  But it's been a long time since I
last looked at this code.

**Comment by rohany** [comment]
@RaduBerinde it doesnt look like this constraint even works in the non family case -- 
```
root@127.0.0.1:62322/movr> CREATE TABLE self_ab (a INT UNIQUE, b INT DEFAULT 1, INDEX (b));
CREATE TABLE

Time: 3.156ms

root@127.0.0.1:62322/movr> INSERT INTO self_ab VALUES (1, 2), (2, 2);
INSERT 2

Time: 3.327ms

root@127.0.0.1:62322/movr> ALTER TABLE self_ab ADD CONSTRAINT fk FOREIGN KEY (b) REFERENCES self_ab(a) ON UPDATE SET DEFAULT;
ALTER TABLE

Time: 106.071ms

root@127.0.0.1:62322/movr> UPDATE self_ab SET a=3 WHERE a=2;
UPDATE 1

Time: 2.426ms

root@127.0.0.1:62322/movr> select * from self_ab;
  a | b
+---+---+
  1 | 1
  3 | 2
(2 rows)

Time: 579µs

root@127.0.0.1:62322/movr>
```

I think that doing the select should show the rows (1,1) and (3, 1) right?

**Comment by RaduBerinde** [comment]
Indeed.. When it rains, it pours. The end result violates the FK.

**Comment by BramGruneir** [comment]
Don't you need to add a `ALTER TABLE orders VALIDATE CONSTRAINT fk;` ?

It's been a while, I might be wrong.

**Comment by rohany** [comment]
An interesting note -- i added a fix that stopped the panic, and now gives the correct result??? when the table has column families, but still gives the incorrect result on the table without families.

**Comment by rohany** [comment]
```
--- a/pkg/sql/row/updater.go
+++ b/pkg/sql/row/updater.go
@@ -13,7 +13,6 @@ package row
 import (
        "bytes"
        "context"
-
        "github.com/cockroachdb/cockroach/pkg/internal/client"
        "github.com/cockroachdb/cockroach/pkg/keys"
        "github.com/cockroachdb/cockroach/pkg/roachpb"
@@ -184,7 +183,7 @@ func makeUpdaterWithoutCascader(
                UpdateColIDtoRowIndex: updateColIDtoRowIndex,
                primaryKeyColChange:   primaryKeyColChange,
                marshaled:             make([]roachpb.Value, len(updateCols)),
-               newValues:             make([]tree.Datum, len(tableCols)),
        }

        if primaryKeyColChange {
@@ -265,6 +264,8 @@ func makeUpdaterWithoutCascader(
                }
        }

+       ru.newValues = make([]tree.Datum, len(ru.FetchCols))
+
```

heres a diff to stop the panic, but outside of that I'm not sure about the rest of the code (I haven't looked into this part much) to say whats causing the other problems

**Comment by RaduBerinde** [comment]
A minor issue I noticed in this code that could be fixed in the same PR: we pass the number of columns as the initial row capacity of the container. This is bogus, I think we should just pass 1 since we're only adding one row:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/row/cascader.go#L559
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/row/cascader.go#L1015

**Comment by rohany** [comment]
@RaduBerinde  are you taking a look a this?

**Comment by RaduBerinde** [comment]
No, I tried to look at it but got lost in the weeds.

**Comment by rohany** [comment]
Do you know who would be a good person to take this over? I don't have much context in this area either.

**Comment by BramGruneir** [comment]
I'm not going to be able to take a look until next week.  But I might be
able to help then.
