### ISSUE TITLE
Failed tests (12480): TestStoreRangeRemoveDead

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4222]
The following test appears to have failed:

[#12480](https://circleci.com/gh/cockroachdb/cockroach/12480):

```
[Trace cRd@0.000000000,0]
 *  15:34:20.614594 sending batch
 *  15:34:20.614613 meta descriptor lookup
 *  15:34:20.614646 sending RPC
I0208 15:34:20.615977 612 storage/replica_command.go:463  auto-gc'ed 5aa57cd6 (3 intents)
panic: assignment to entry in nil map

goroutine 8743 [running]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).addInternal(0xc82013efd0, 0xc820121040, 0xc8201f6601, 0x3ff0000000000000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:312 +0xa46
github.com/cockroachdb/cockroach/storage.(*baseQueue).Add(0xc82013efd0, 0xc820121040, 0x3ff0000000000000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:245 +0xf5
github.com/cockroachdb/cockroach/storage.(*Replica).changeReplicasTrigger.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1644 +0xb4
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBBatch).Commit(0xc820396ab0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:471 +0x273
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommand(0xc820121040, 0x7fea01b84d40, 0xc820396a80, 0x12, 0x100000001, 0x1, 0x989680, 0x5, 0x100000001, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1293 +0x744
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200d9e30, 0xc8201f6af0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x70

goroutine 1 [chan receive]:
testing.RunTests(0x1d5b270, 0x24a7200, 0xe3, 0xe3, 0x1)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc82029ff00, 0x1)
	/tmp/workdir/go/src/testing/testing.go:494 +0xe5
github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck(0xc82029ff00)
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:37 +0x2f
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc82029ff00)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:38 +0x34
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:514 +0x20a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x27f1a00)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1029 +0x76
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:610 +0x117

goroutine 8714 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8202a45f0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:123 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:124 +0x581

goroutine 8706 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8202a41e0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:123 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:124 +0x581

goroutine 8852 [runnable]:
sync.runtime_Semacquire(0xc8200d9e54)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8200d9e48)
	/tmp/workdir/go/src/sync/waitgroup.go:126 +0x118
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc8200d9e30)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:223 +0x22b
github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).Stop.func1(0xc8208e2000, 0xc8209fb980)
	/go/src/github.com/cockroachdb/cockroach/storage/client_test.go:271 +0x3ff
created by github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).Stop
	/go/src/github.com/cockroachdb/cockroach/storage/client_test.go:279 +0x8c

goroutine 8739 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8202a4870)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:123 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:124 +0x581

goroutine 8687 [select]:
github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).Stop(0xc8208e2000)
	/go/src/github.com/cockroachdb/cockroach/storage/client_test.go:281 +0x318
github.com/cockroachdb/cockroach/storage_test.TestStoreRangeRemoveDead(0xc8201421b0)
	/go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:1169 +0x10a7
testing.tRunner(0xc8201421b0, 0x24a8478)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4
FAIL	github.com/cockroachdb/cockroach/storage	18.456s
=== RUN   TestBatchBasics
I0208 15:34:32.332211 687 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I0208 15:34:32.341963 687 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I0208 15:34:32.355071 687 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Dupe #4220.
