### ISSUE TITLE
sql: panic: windowNode can't be run in local mode

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#42247]
```
CREATE TABLE tab_6739 (col0 FLOAT4 NOT NULL, col1 BIT(47) NOT NULL, col2 REGCLASS, col3 TIMESTAMPTZ, col4 FLOAT4, col5 REGNAMESPACE, col6 INT2 NOT NULL, col7 REGCLASS NOT NULL, FAMILY fam0 (col3, col0, col2, col7), FAMILY fam1 (col1), FAMILY fam2 (col6, col5, col4), PRIMARY KEY (col3 ASC), UNIQUE (col6 ASC, col1, col2 ASC, col4 ASC, col7 DESC, col3 DESC, col5, col0), UNIQUE (col5 DESC), UNIQUE (col1, col3 DESC, col2 DESC, col5 ASC, col0 ASC, col4, col6 ASC), INDEX (col3, col4, col6 DESC), INDEX (col3 ASC, col7, col0, col4 ASC, col2, col5 ASC), INDEX (col7 ASC, col6 DESC, col1 ASC, col0 ASC, col4, col2, col3 ASC), UNIQUE (col5 ASC, col1 DESC, col4 ASC, col2, col6, col3 DESC, col7, col0), UNIQUE (col0 ASC));

INSERT
INTO
	defaultdb.public.tab_118 AS tab_11761 (col1, col2, col3, col_17229, col8)
WITH
	with_2833 (col_25920)
		AS (
			SELECT
				*
			FROM
				(
					VALUES
						('U':::STRING),
						(('':::STRING::STRING || NULL::STRING)::STRING),
						(e'NQj2Pmt\x0bw':::STRING),
						(e'\\=+eb]K':::STRING),
						(e'mv4T\x18sPDL':::STRING),
						('':::STRING)
				)
					AS tab_11762 (col_25920)
		),
	with_2834 (col_25921) AS (SELECT * FROM (VALUES (NULL)) AS tab_11763 (col_25921))
SELECT
	min(tab_11764.col7::OID)::OID AS col_25922,
	'J':::STRING AS col_25923,
	min(tab_11764.col7::OID) OVER (PARTITION BY tab_11764.col7, tab_11764.col1)::OID AS col_25924,
	0.1900811493396759:::FLOAT8 AS col_25925,
	char_length(e'\\x965108d3aa':::BYTES::BYTES)::INT8 AS col_25926
FROM
	with_2833, defaultdb.public.tab_6739 AS tab_11764
WHERE
	true
GROUP BY
	tab_11764.col1, tab_11764.col7;
```

```
E191106 07:18:20.729303 688 util/log/crash_reporting.go:216  [n1,client=104.196.61.98:42310,user=root] a panic has occurred!
panic: windowNode can't be run in local mode
	panic: windowNode can't be run in local mode [recovered]
	panic: panic while executing 1 statements: INSERT INTO _._._ AS _(_, _, _, _, _) WITH _ (_) AS (SELECT * FROM (VALUES (_:::STRING), (__more5__)) AS _ (_)) , _ (_) AS (SELECT * FROM (VALUES (_)) AS _ (_)) SELECT min(_._::OID)::OID AS _, _:::STRING AS _, min(_._::OID) OVER (PARTITION BY _._, _._)::OID AS _, _:::FLOAT8 AS _, char_length(_::BYTES)::INT8 AS _ FROM _, _._._ AS _ WHERE _ GROUP BY _._, _._; caused by windowNode can't be run in local mode

goroutine 688 [running]:
panic(0x3143900, 0xc012f342a0)
	/usr/local/go/src/runtime/panic.go:556 +0x2cb fp=0xc00adbf778 sp=0xc00adbf6e8 pc=0x735f1b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00a361100, 0x3a522a0, 0xc00aa35d40, 0x2dd3ba0, 0x3a0aa40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:722 +0x36d fp=0xc00adbf838 sp=0xc00adbf778 pc=0x1fd331d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc00a361100, 0x3a522a0, 0xc00aa35d40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:434 +0x61 fp=0xc00adbf870 sp=0xc00adbf838 pc=0x2161b41
runtime.call32(0x0, 0x343cba0, 0xc0000d0490, 0x1800000018)
	/usr/local/go/src/runtime/asm_amd64.s:522 +0x3b fp=0xc00adbf8a0 sp=0xc00adbf870 pc=0x764aeb
panic(0x2dd3ba0, 0x3a0aa40)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9 fp=0xc00adbf930 sp=0xc00adbf8a0 pc=0x735e09
github.com/cockroachdb/cockroach/pkg/sql.(*windowNode).Next(0xc010124000, 0x3a52360, 0xc012f05aa0, 0xc00f7d8a00, 0xc00a361450, 0xc00adbf9a8, 0x713edd, 0x2f10800)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/window.go:175 +0x39 fp=0xc00adbf950 sp=0xc00adbf930 pc=0x213b9d9
github.com/cockroachdb/cockroach/pkg/sql.(*insertNode).BatchedNext(0xc009af7680, 0x3a52360, 0xc012f05aa0, 0xc00f7d8a00, 0xc00a361450, 0xc00adbfa00, 0xc00adbfa10, 0x7df1d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/insert.go:471 +0xcc fp=0xc00adbf9b8 sp=0xc00adbf950 pc=0x207205c
github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode).startExec(0xc011719780, 0x3a52360, 0xc012f05aa0, 0xc00f7d8a00, 0xc00a361450, 0x71d165, 0xc00bfea418)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:173 +0xd0 fp=0xc00adbfa08 sp=0xc00adbf9b8 pc=0x20bbb30
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x32caa43, 0x5, 0x3a54020, 0xc011719780, 0xc00adbfab8, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:496 +0x55 fp=0xc00adbfa50 sp=0xc00adbfa08 pc=0x216fe95
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc0108f6de0, 0x32caa43, 0x5, 0x3a54020, 0xc011719780)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:146 +0x5d fp=0xc00adbfa90 sp=0xc00adbfa50 pc=0x217edbd
runtime.call64(0x0, 0x343cc88, 0xc000a7d9b0, 0x2800000028)
	/usr/local/go/src/runtime/asm_amd64.s:523 +0x3b fp=0xc00adbfae0 sp=0xc00adbfa90 pc=0x764b6b
panic(0x2dd3ba0, 0x3a0aa30)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9 fp=0xc00adbfb70 sp=0xc00adbfae0 pc=0x735e09
github.com/cockroachdb/cockroach/pkg/sql.(*windowNode).startExec(0xc010124000, 0x3a52360, 0xc012f05aa0, 0xc00f7d8a00, 0xc00a361450, 0xc010126480, 0xc00adbfc08)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/window.go:171 +0x39 fp=0xc00adbfb90 sp=0xc00adbfb70 pc=0x213b989
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x32cd7c1, 0x6, 0x3a546a0, 0xc010124000, 0xc00f57d500, 0xc00adbfc18)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:496 +0x55 fp=0xc00adbfbd8 sp=0xc00adbfb90 pc=0x216fe95
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc0108f6de0, 0x32cd7c1, 0x6, 0x3a546a0, 0xc010124000)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:146 +0x5d fp=0xc00adbfc18 sp=0xc00adbfbd8 pc=0x217edbd
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc0108f6de0, 0x3a546a0, 0xc010124000, 0x32cd7c1, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:613 +0x1a2 fp=0xc00adc0670 sp=0xc00adbfc18 pc=0x2135572
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc0108f6de0, 0x3a546a0, 0xc010124000, 0x32ccbfd, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:113 +0x8d fp=0xc00adc06e0 sp=0xc00adc0670 pc=0x21351fd
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc0108f6de0, 0x3a53c60, 0xc009af7680, 0x32ccbfd, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:452 +0x47c6 fp=0xc00adc1138 sp=0xc00adc06e0 pc=0x2139b96
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitConcrete(0xc0108f6de0, 0x3a53c60, 0xc009af7680)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:126 +0x81 fp=0xc00adc1170 sp=0xc00adc1138 pc=0x21353b1
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc0108f6de0, 0x3a54020, 0xc011719780, 0x32caa43, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:533 +0x4ceb fp=0xc00adc1bc8 sp=0xc00adc1170 pc=0x213a0bb
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc0108f6de0, 0x3a54020, 0xc011719780, 0x203004, 0x717d89)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:113 +0x8d fp=0xc00adc1c38 sp=0xc00adc1bc8 pc=0x21351fd
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x3a52360, 0xc012f05aa0, 0x3a54020, 0xc011719780, 0x0, 0x343d430, 0x0, 0x0, 0x0, 0xc012f05c50, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:77 +0x1a4 fp=0xc00adc1d60 sp=0xc00adc1c38 pc=0x2135104
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x3a52360, 0xc012f05aa0, 0xc00f7d8a00, 0xc00a361450, 0x3a54020, 0xc011719780, 0xc0118540f8, 0xc0118540f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:499 +0x116 fp=0xc00adc1e10 sp=0xc00adc1d60 pc=0x20b52d6
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc00b217400, 0x3a52360, 0xc012f05aa0, 0x5bc4480, 0x2dd2e20)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:124 +0xd9 fp=0xc00adc1e60 sp=0xc00adc1e10 pc=0x20be209
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc00b217400, 0x3a52360, 0xc012f05aa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:800 +0x52 fp=0xc00adc1ea0 sp=0xc00adc1e60 pc=0x1dfea72
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc01096d0e0, 0x3a52360, 0xc012f05aa0, 0x343cb20, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:626 +0x1e9 fp=0xc00adc1f00 sp=0xc00adc1ea0 pc=0x1dddee9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00004e8c0, 0xc0108f6840, 0xc00e98bcb0, 0xc00adc2838, 0xc00ab4f080, 0xc00a361510, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:251 +0x8a0 fp=0xc00adc2728 sp=0xc00adc1f00 pc=0x203bb30
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00004e8c0, 0x3a52360, 0xc012e8fd70, 0xc00a361510, 0xc0108f6840, 0xc00e98bcb0, 0x3a54020, 0xc011719780, 0xc00ab4f080)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:838 +0x227 fp=0xc00adc29e8 sp=0xc00adc2728 pc=0x203f1b7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc00a361100, 0x3a52360, 0xc012e8fd70, 0xc00a361450, 0x2, 0x7f58d0cb6d28, 0xc011748dc0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1125 +0x283 fp=0xc00adc2a78 sp=0xc00adc29e8 pc=0x1fe5633
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00a361100, 0x3a52360, 0xc012e8fd70, 0xc00a361450, 0x7f58d0cb6d28, 0xc011748dc0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:961 +0x658 fp=0xc00adc2b78 sp=0xc00adc2a78 pc=0x1fe4508
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00a361100, 0x3a52360, 0xc012e8fd70, 0x3a579a0, 0xc012a85bd0, 0xc00c523a32, 0x369, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:456 +0xdd0 fp=0xc00adc3358 sp=0xc00adc2b78 pc=0x1fe05f0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00a361100, 0x3a52360, 0xc012e8fd70, 0x3a579a0, 0xc012a85bd0, 0xc00c523a32, 0x369, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:102 +0x610 fp=0xc00adc3600 sp=0xc00adc3358 pc=0x1fdf3a0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00a361100, 0x3a522a0, 0xc00aa35d40, 0xc000ba2c38, 0x5400, 0x15000, 0xc000ba2cd0, 0xc00a99d0f0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1186 +0x21d4 fp=0xc00adc3e68 sp=0xc00adc3600 pc=0x1fd6ad4
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000910b00, 0x3a522a0, 0xc00aa35d40, 0xc00a361100, 0x5400, 0x15000, 0xc000ba2cd0, 0xc00a99d0f0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:436 +0xce fp=0xc00adc3ec8 sp=0xc00adc3e68 pc=0x1fd169e
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00aaf0836, 0xc00aae2680, 0x3a522a0, 0xc00aa35d40, 0xc00a99d0f0, 0xc000910b00, 0xc009e2b200, 0x3a55fe0, 0xc00aae2660, 0xc00aa3d5c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:580 +0x21f fp=0xc00adc3f68 sp=0xc00adc3ec8 pc=0x225d47f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00adc3f70 sp=0xc00adc3f68 pc=0x766801
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:515 +0x17b
```

This is from a roachtest failure at #42215, which is running a 4 node cluster. The above SQL is what produce the panic, and I looked through the logs to find the CREATE TABLE. Probably not copy-pasteable, but may get you close.

See logs at https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/1575698:id/sqlsmith/setup%3Dempty/setting%3Ddefault/1.logs/cockroach.log

**Comment by yuzefovich** [comment]
This was also on 19.1.5 and was fixed by #42617.
