### ISSUE TITLE
Examples-ORMs fails with "No module named 'django'"

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#42559]
https://teamcity.cockroachdb.com/viewLog.html?buildId=1597803&buildTypeId=Cockroach_ExampleORMs&tab=buildResultsDiv&branch_Cockroach=v19.2.0-rc.4

```
cd cockroach-django && pip3 install .
Processing /home/agent/go/src/github.com/cockroachdb/examples-orms/python/django/cockroach-django
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-y1wdh8hz-build/setup.py", line 5, in <module>
        version=__import__('django_cockroachdb').__version__,
      File "/tmp/pip-y1wdh8hz-build/django_cockroachdb/__init__.py", line 1, in <module>
        from .functions import register_functions
      File "/tmp/pip-y1wdh8hz-build/django_cockroachdb/functions.py", line 3, in <module>
        from django.db.models import (
    ImportError: No module named 'django'
```

**Comment by irfansharif** [comment]
Likely similar to https://github.com/cockroachdb/cockroach/issues/42083. Seems like https://github.com/cockroachdb/django-cockroachdb is unpinned as well, and has seen recent activity.

**Comment by jordanlewis** [comment]
Let's disable this test if it's blocking people.

**Comment by irfansharif** [comment]
TestDjango specifically is as of https://github.com/cockroachdb/examples-orms/pull/83. It seems like things as failing in the make/build step:
```
[23:23:01] [Step 2/2] make deps -C ./python/django
[23:23:01] [Step 2/2] make[1]: Entering directory '/home/agent/go/src/github.com/cockroachdb/examples-orms/python/django'
[23:23:01] [Step 2/2] git clone https://github.com/cockroachlabs/cockroach-django || true
[23:23:01] [Step 2/2] Cloning into 'cockroach-django'...
[23:23:01] [Step 2/2] cd cockroach-django && pip3 install .
[23:23:02] [Step 2/2] Processing /home/agent/go/src/github.com/cockroachdb/examples-orms/python/django/cockroach-django
[23:23:03] [Step 2/2]     Complete output from command python setup.py egg_info:
[23:23:03] [Step 2/2]     Traceback (most recent call last):
...
```
