### ISSUE TITLE
storage/engine: too many address space collisions for -race mode

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#42938]
@otan saw at least 3 different occurrences of CI failing `testrace` with the error `too many address space collisions for -race mode`.

* https://teamcity.cockroachdb.com/repository/download/Cockroach_UnitTests_Testrace/1623338:id/testrace.log
* https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1623358&_focus=542
* https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1623534&_focus=1971

In each case, the failure emanates from the following stack:

```
fatal error: too many address space collisions for -race mode

runtime stack:
runtime.throw(0x58938a6, 0x30)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.(*mheap).sysAlloc(0x93ce580, 0x7f0a00002000, 0x93ce590, 0x3f8500001)
	/usr/local/go/src/runtime/malloc.go:589 +0x732
runtime.(*mheap).grow(0x93ce580, 0x3f8500001, 0x0)
	/usr/local/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x93ce580, 0x3f8500001, 0x9d8d308, 0x75)
	/usr/local/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x93ce580, 0x3f8500001, 0x101, 0x0)
	/usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x93ce580, 0x3f8500001, 0x4000101, 0x7f0a64258848)
	/usr/local/go/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x7f0a0000001a, 0xc000ed0100, 0xc000ed75a0)
	/usr/local/go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x7f0a697ff330)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153

goroutine 815 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc000ed7620 sp=0xc000ed7618 pc=0xc06e80
runtime.mallocgc(0x7f0a0000001a, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:949 +0x8b8 fp=0xc000ed76d0 sp=0xc000ed7620 pc=0xbb5fb8
github.com/cockroachdb/cockroach/pkg/storage/engine.nonZeroingMakeByteSlice(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/slice.go:16
github.com/cockroachdb/cockroach/pkg/storage/engine.copyFromSliceVector(0x7f0a68222000, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2562 +0xe8 fp=0xc000ed7768 sp=0xc000ed76d0 pc=0x43a9728
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).MVCCGet(0xc000bb6028, 0xc000308820, 0x8, 0x20, 0x0, 0x0, 0xc000ed0000, 0x0, 0xc000062500, 0xc000ed7a50, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2433 +0x3e8 fp=0xc000ed79d0 sp=0xc000ed7768 pc=0x43a6c08
github.com/cockroachdb/cockroach/pkg/storage/engine.(*batchIterator).MVCCGet(0xc000bb6028, 0xc000308820, 0x8, 0x20, 0x0, 0x7f0a00000000, 0x0, 0x0, 0xc000452000, 0xc000ed7b00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1571 +0xe1 fp=0xc000ed7a60 sp=0xc000ed79d0 pc=0x439f111
github.com/cockroachdb/cockroach/pkg/storage/engine.(*reusableBatchIterator).MVCCGet(0xc000bb6028, 0xc000308820, 0x8, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f0a64233140, ...)
	<autogenerated>:1 +0xc4 fp=0xc000ed7af0 sp=0xc000ed7a60 pc=0x43c6f04
github.com/cockroachdb/cockroach/pkg/storage/engine.mvccGet(0x66bb440, 0xc00079d3b0, 0x673f160, 0xc000bb6028, 0xc000308820, 0x8, 0x20, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:753 +0xac1 fp=0xc000ed7f18 sp=0xc000ed7af0 pc=0x4340ad1
github.com/cockroachdb/cockroach/pkg/storage/engine.MVCCGet(0x66bb440, 0xc00079d3b0, 0x66ffba0, 0xc000bb6000, 0xc000308820, 0x8, 0x20, 0x0, 0xc000000000, 0xc000ed0000, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:735 +0x193 fp=0xc000ed8010 sp=0xc000ed7f18 pc=0x433ff93
github.com/cockroachdb/cockroach/pkg/storage/engine.MVCCGetProto(0x66bb440, 0xc00079d3b0, 0x66ffba0, 0xc000bb6000, 0xc000308820, 0x8, 0x20, 0x0, 0x0, 0x66f3180, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:629 +0xdc fp=0xc000ed80f0 sp=0xc000ed8010 pc=0x433f6bc
github.com/cockroachdb/cockroach/pkg/storage/stateloader.StateLoader.LoadRaftTruncatedState(0xc000308820, 0x3, 0x20, 0x66bb440, 0xc00079d3b0, 0x66ffba0, 0xc000bb6000, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stateloader/stateloader.go:520 +0x2ee fp=0xc000ed8228 sp=0xc000ed80f0 pc=0x43f41be
github.com/cockroachdb/cockroach/pkg/storage/stateloader.StateLoader.SynthesizeRaftState(0xc000308820, 0x3, 0x20, 0x66bb440, 0xc00079d3b0, 0x7f0a70d00300, 0xc000bb6000, 0xc000308820, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stateloader/stateloader.go:600 +0x183 fp=0xc000ed8358 sp=0xc000ed8228 pc=0x43f5753
github.com/cockroachdb/cockroach/pkg/storage/stateloader.WriteInitialState(0x66bb440, 0xc00079d3b0, 0x7f0a70d00300, 0xc000bb6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stateloader/initial.go:117 +0x2cd fp=0xc000ed8728 sp=0xc000ed8358 pc=0x43eba2d
github.com/cockroachdb/cockroach/pkg/storage.WriteInitialClusterData(0x66bb440, 0xc00079d3b0, 0x67718e0, 0xc000606ea0, 0xc000ec8000, 0x32, 0x40, 0x200000013, 0x300000000, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store_bootstrap.go:229 +0xcc6 fp=0xc000ed9100 sp=0xc000ed8728 pc=0x45d97d6
github.com/cockroachdb/cockroach/pkg/server.bootstrapCluster(0x66bb440, 0xc00079d3b0, 0xc0001fd5d0, 0x1, 0x1, 0x200000013, 0x300000000, 0xc00039b2c0, 0xc00039b350, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:247 +0x5ba fp=0xc000ed9300 sp=0xc000ed9100 pc=0x472f7da
github.com/cockroachdb/cockroach/pkg/server.(*Node).bootstrapCluster(0xc0002baa00, 0x66bb440, 0xc00079d3b0, 0xc0001fd5d0, 0x1, 0x1, 0x200000013, 0x300000000, 0xc00039b2c0, 0xc00039b350, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:327 +0x282 fp=0xc000ed9438 sp=0xc000ed9300 pc=0x4730722
github.com/cockroachdb/cockroach/pkg/server.(*Server).bootstrapCluster(0xc00039b000, 0x66bb440, 0xc00079d3b0, 0x200000013, 0x300000000, 0x31, 0xc000a55d60)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1947 +0x124 fp=0xc000ed94f0 sp=0xc000ed9438 pc=0x474d934
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start(0xc00039b000, 0x66bb3c0, 0xc0000e6010, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1452 +0x5d01 fp=0xc000eda5a0 sp=0xc000ed94f0 pc=0x474a641
github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start(0xc00030c900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:378 +0x30a fp=0xc000edae90 sp=0xc000eda5a0 pc=0x476818a
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerRaw(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:218 +0x19a fp=0xc000edb640 sp=0xc000edae90 pc=0x3ab5b7a
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer(0x673cf00, 0xc00048a200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:186 +0x74 fp=0xc000edb9f8 sp=0xc000edb640 pc=0x3ab5414
github.com/cockroachdb/cockroach/pkg/sql/sem/tree_test.TestEval.func5(0xc00048a200)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval_test.go:102 +0xfe fp=0xc000edbf70 sp=0xc000edb9f8 pc=0x47f62de
testing.tRunner(0xc00048a200, 0xc000854fc0)
	/usr/local/go/src/testing/testing.go:865 +0x164 fp=0xc000edbfd0 sp=0xc000edbf70 pc=0xd0b994
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000edbfd8 sp=0xc000edbfd0 pc=0xc08f51
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x65b
```

In particular, notice this bit of the first stack:

```
runtime.largeAlloc(0x7f0a0000001a, 0xc000ed0100, 0xc000ed75a0)
	/usr/local/go/src/runtime/malloc.go:1055 +0x99
```

The first argument to `runtime.largeAlloc` is the size to allocate. In each of the crashes, the size is very large: `0x7f0a0000001a`, `0x7fd40000001a` and `0x7fc40000001a`. These sizes are all approximately 127 TB. That seems impossible for a single `MVCCGet` call to return. 

Is this some sort of fall out from https://github.com/cockroachdb/cockroach/pull/42721?  Notice that the values are all reasonable (and identical) in the low 32-bits: 26. Could one bit of code think that `DBSlice.len` is 32-bits while another part considers it 64-bits? That seems like a real possibility.

**Comment by tbg** [comment]
Also happening on master: https://teamcity.cockroachdb.com/viewLog.html?buildId=1625246&buildTypeId=Cockroach_UnitTests

**Comment by petermattis** [comment]
https://github.com/cockroachdb/cockroach/pull/42954 is an attempt to protect against skew between the C view of the size of `DBSlice` and the Go view. CI on that failure failed on [testrace](https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1625636):

```
[20:20:48][run] GOFLAGS= go test -json -race -tags ' gss make x86_64_pc_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=v20.1.0-alpha.20191118-484-g1f0cd02" -X "github.com/cockroachdb/cockroach/pkg/build.rev=1f0cd02f1b61b032b8963a823d9ae65968511121" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-pc-linux-gnu"  ' -run "."  -timeout 45m ./pkg/cli -v -p 4
[20:21:35][run] # github.com/cockroachdb/cockroach/pkg/storage/engine
[20:21:35][run] /tmp/go-build100464671/b429/_x002.o: In function `_cgo_57b910bc67a4_Cfunc_DBSizeofSlice':
[20:21:35][run] /tmp/go-build/cgo-gcc-prolog:1173: undefined reference to `DBSizeofSlice'
[20:21:35][run] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Notice that this is a link time error. We ran `make testrace PKG=./pkg/cli`, and while linking we couldn't find a reference to the C++ symbol `DBSizeofSlice`. This indicates that we were trying to link against an out of date version of `libroach`. This completely explains the problem seen above. We recently changed the type of the `DBSlice.len` field from 32-bits to 64-bits. The Go code is being compiled with this new size, but we're linking against an old version of `libroach` which is only populating 32-bits. The other 32-bits are being populated from subsequent members in the struct the slice is embedded in.

I need to peruse the test failure more to see where the missing dependency is, but this has massively reduced my anxiety about this issue.

**Comment by itsbilal** [comment]
Wow, good catch. I did notice that any instance where these failures happened in quick succession on CI (eg. the three failures @otan saw and are linked above) were all on the same agent (in the aforementioned three failures' case, gce-agent-12). There were other one-off failures, eg. on gce-agent-14 (the one @tbg linked), and another on gce-agent-9, that were right after a build on the same agent that was based on a pre-DBSlice commit of master. So the dirty agent theory definitely seems to hold.

**Comment by petermattis** [comment]
Here's how to reproduce the CI failure:

```
~ git co master
~ make build
~ git co <#42954>
~ make build ENABLE_LIBROACH_ASSERTIONS=1
```

The problem is that `ENABLE_LIBROACH_ASSERTIONS` affects the directory `libroach` is built in, but we don't regenerate `storage/engine/zcgo_flags_*`. The `zcgo_flags` still refer to the "normal" `/libroach` directory, not `/libroach_assert`. So while the `make build ENABLE_LIBROACH_ASSERTIONS=1` command rebuilt libroach, we didn't actually use the version that was built.

Make sucks. Cc @bobvawter.

**Comment by otan** [comment]
i am wondering if this is related to https://github.com/cockroachdb/cockroach/issues/42634 missing snappy at this point ...

**Comment by petermattis** [comment]
@otan I think that is unrelated. The problem here would cause build time discrepancies, but we've been linking snappy for a long time.
