### ISSUE TITLE
storage/engine: RocksDB assertion failure while running cli.TestDebugCheckStore

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#43020]
On top of #43019, `cli.TestDebugCheckStore` readily triggers a RocksDB assertion failure:

```
~ make stress ENABLE_ROCKSDB_ASSERTIONS=1 PKG=./cli TESTS=TestDebugCheckStore
...
Assertion failed: (!(static_cast<uint32_t>(limit - p) < (*non_shared + *value_length))), function operator(), file /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach
/c-deps/rocksdb/table/block.cc, line 61.
SIGABRT: abort
PC=0x7fff6b4042c6 m=25 sigcode=0
...
goroutine 15 [syscall]:
runtime.cgocall(0x67e9e00, 0xc0034eb030, 0xc002ce3c00)
        /Users/pmattis/Development/go1.13/src/runtime/cgocall.go:128 +0x5b fp=0xc0034eafb0 sp=0xc0034eaf78 pc=0x40051fb
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBOpen(0xc00444bb88, 0xc00549dd60, 0x50, 0x1162a550, 0x2c7800000004, 0x10100, 0x0, 0x0, 0x0, 0x0, ...)
        _cgo_gotypes.go:1037 +0x53 fp=0xc0034eb030 sp=0xc0034eafb0 pc=0x644f3a3
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open.func1(0xc00444bb00, 0x2c78, 0x1, 0x0, 0x0)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:644 +0x2cd fp=0xc0034eb128 sp=0xc0034eb030 pc=0x646646d
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open(0xc00444bb00, 0xc00091f140, 0x5a)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:644 +0x249 fp=0xc0034eb1e8 sp=0xc0034eb128 pc=0x6452619
github.com/cockroachdb/cockroach/pkg/storage/engine.NewRocksDB(0x0, 0x0, 0x0, 0xc000a233b0, 0x50, 0x1, 0x0, 0xc00025ca80, 0x0, 0x0, ...)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:535 +0x1d9 fp=0xc0034eb258 sp=0xc0034eb1e8 pc=0x6451e39
github.com/cockroachdb/cockroach/pkg/cli.OpenEngine(0xc000a233b0, 0x50, 0xc0043ca990, 0xc0043c0101, 0x0, 0x0, 0x0, 0x0)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/cli/debug.go:163 +0x631 fp=0xc0034eb4d8 sp=0xc0034eb258 pc=0x6750ad1
github.com/cockroachdb/cockroach/pkg/cli.OpenExistingStore(...)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/cli/debug.go:117
github.com/cockroachdb/cockroach/pkg/cli.checkStoreRangeStats(0x8338e20, 0xc000106008, 0xc000a233b0, 0x50, 0xc0034eb888, 0x0, 0x0)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/cli/debug_check_store.go:151 +0xea fp=0xc0034eb838 sp=0xc0034eb4d8 pc=0x6759cfa
github.com/cockroachdb/cockroach/pkg/cli.TestDebugCheckStore.func2(0xc000a233b0, 0x50, 0x75ab180, 0xc000455a30, 0x75ab180, 0x82614e0)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/cli/debug_check_store_test.go:67 +0x9c fp=0xc0034eb8a8 sp=0xc0034eb838 pc=0x67d3e6c
github.com/cockroachdb/cockroach/pkg/cli.TestDebugCheckStore(0xc000b99200)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/cli/debug_check_store_test.go:75 +0x54b fp=0xc0034ebf70 sp=0xc0034eb8a8 pc=0x67a7adb
testing.tRunner(0xc000b99200, 0x7ce36f8)
        /Users/pmattis/Development/go1.13/src/testing/testing.go:909 +0xc9 fp=0xc0034ebfd0 sp=0xc0034ebf70 pc=0x4112da9
runtime.goexit()
        /Users/pmattis/Development/go1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0034ebfd8 sp=0xc0034ebfd0 pc=0x4061d41
created by testing.(*T).Run
        /Users/pmattis/Development/go1.13/src/testing/testing.go:960 +0x350
```

This seems serious.

**Comment by petermattis** [comment]
Egads! Pebble is writing the sstable meta-index block with the specified compression. RocksDB always writes the meta-index block uncompressed and assumes that it is uncompressed when reading it (rather than checking the compression byte in the block trailer). Easy enough to fix, though I need to figure out what the repercussions of this are.

**Comment by petermattis** [comment]
I believe the repercussions are somewhat severe, but we seem to have squeaked by any problem with 19.2. In 19.2 we use RocksDB for sstables written for ingestion. And sstables written for backup are written by Pebble in LevelDB format and do not contain range tombstones. These backup sstables will either have an empty meta-index block or one only containing a pointer to the properties block (we don't write bloom filters).

On master, the repercussions seems potentially serious. Sstables written for ingestion by Pebble are not readable by RocksDB. I'm surprised there hasn't been more fallout from this and I need to figure out why.

**Comment by petermattis** [comment]
Interestingly, if an sstable doesn't contain a bloom filter or range tombstones, the meta-index block is small enough that snappy compression isn't effective. This triggers the heuristic to store the block uncompressed since the compressed size is not 12.5% smaller than the compressed size.

**Comment by petermattis** [comment]
It turns out that RocksDB has two different paths for reading the meta-index block. `BlockBasedTable::ReadMetaBlock` will decompress the meta-index block if it is compressed. The `BlockBasedTable` path is the one used during sstable ingestion and during normal operation when opening an sstable. So RocksDB will merrily ingest an sstable with a compressed meta-index block.

The other path for reading a meta-index block is via the `ReadTableProperties` global function. This function is used by the `ldb` and `sst_dump` tools. It is also used by `Version::MaybeInitializeFileMetaData`. This function is called whenever a new version is applied (which happens after an ingestion, compaction, or at startup). `MaybeInitializeFileMetaData` calls `Version::ReadTableProperties`. This function has multiple paths. If the table is in the cache, it utilizes the cached in-memory properties. If the table is not in the cache, as it won't be at startup, then the global `ReadTableProperties` function is called. When RocksDB assertions are not enabled (i.e. a production binary), the `ReadTableProperties` function will return an error which will propagate up to `MaybeInitializeFileMetaData`. This in turn propagates a failure up to `Version::UpdateAccumulatedStats` which will skip over the adding stats for the specified sstable, while logging an error:

```
[db/version_set.cc:1921] Unable to load table properties for file X ...
```

It gets even more nuanced. RocksDB has a code path to preload the table cache at startup which often causes the table properties to be setting in cache when `Version::ReadTableProperties` is called. Often, but not always.

Note that RocksDB is still opening the instance perfectly fine. It is just not able to update some internal stats. What are those stats used for? Computing the average size of a value in sstables which in turn feeds into the "compensated file size" calculation. So it seems like the result of all of this is some scary warnings in the log files, and incorrect compensated file-size calculation which will in turn cause some badness for compaction heuristics. I don't think there is any danger of data loss, though I wouldn't place money on that. We should definitely fix this bug ASAP (see https://github.com/cockroachdb/pebble/pull/423).
