### ISSUE TITLE
sqlsmith: out of bounds during expression generation

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#43124]
```
panic: runtime error: index out of range

goroutine 7117576 [running]:
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeMergeJoinExpr.func1(0xc011cf3a40, 0xc00a82b050, 0xc00c38de00, 0xc013905c40, 0xc013905c80, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:311 +0x751
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeMergeJoinExpr(0xc011cf3a40, 0x0, 0x0, 0x0, 0xc0072aba00, 0x1df78186bc8b57a0, 0x7ffffffd1a121030, 0xc01a121030, 0x878865, 0xc00d8eab40, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:337 +0x1c3
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeTableExpr(0xc011cf3a40, 0x0, 0x0, 0x0, 0x51aa969e75079800, 0x51aa969e75079836, 0xc01a121098, 0x8786f7, 0xc0072aba00, 0x51aa969e75079836, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:167 +0xcd
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeSelectClause(0xc011cf3a40, 0xc01a121458, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:535 +0xeb2
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeSelect(0xc011cf3a40, 0xc01a121458, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc011cf3a40, 0x6c39b00, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:728 +0x15d
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeScalarSubquery(0xc011cf3a40, 0x6c39b00, 0x0, 0x0, 0x0, 0x73, 0x49, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/scalar.go:688 +0xb3
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.scalarNoContext.func1(0xc011cf3a40, 0x0, 0x0, 0x6c39b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/scalar.go:70 +0x5a
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeScalarSample(0xc011997230, 0xc00021c0e0, 0xe, 0xe, 0xc011cf3a40, 0x0, 0x0, 0x6c39b00, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/scalar.go:126 +0xde
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeScalarContext(0xc011cf3a40, 0x0, 0x6876c4bd79c5d800, 0x6c39b00, 0x0, 0x0, 0x0, 0x1, 0xc00a5254c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/scalar.go:96 +0xa9
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeScalar(0xc011cf3a40, 0x6c39b00, 0x0, 0x0, 0x0, 0x728007, 0x1545987f4d18)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/scalar.go:92 +0x6a
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeValues(0xc011cf3a40, 0xc01768a600, 0x2, 0x2, 0x0, 0x0, 0x0, 0x154598920f80, 0x0, 0x203004, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:984 +0x132
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeValuesSelect(0xc011cf3a40, 0xc01768a600, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc000a1e7c8, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:1020 +0x8e
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeSelectStmt(0xc011cf3a40, 0xc01768a600, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc000a1e7c8, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:35 +0x224
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeWith(0xc011cf3a40, 0x8, 0xf4d9c2d860ff0424, 0x0, 0xf40000c010803068)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:399 +0x1a6
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeSelect(0xc011cf3a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc01a121b58, 0xc00c530600, 0xc01a121b90, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:720 +0x43
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeSelect(0xc011cf3a40, 0x0, 0xc0061eecc0, 0xc01a121b08)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:682 +0x5f
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeStmt(0xc011cf3a40, 0xc0061eed20, 0x0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:20 +0x5b
github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).Generate(0xc011cf3a40, 0x46da220, 0xc010045800)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/sqlsmith.go:119 +0x36
github.com/cockroachdb/cockroach/pkg/sql/tests_test.TestRandomSyntaxSQLSmith.func2(0x46da220, 0xc010045800, 0xc0065eef30, 0xc0072ab9e0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/tests/rsg_test.go:522 +0x4e
github.com/cockroachdb/cockroach/pkg/sql/tests_test.testRandomSyntax.func3(0x46da220, 0xc010045800, 0xc0000740d8, 0xc001631790)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/tests/rsg_test.go:717 +0xd0
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1(0x8, 0x3f266c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:166 +0x3a
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0087f1080, 0xc0087f1290)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

Seen in https://teamcity.cockroachdb.com/viewLog.html?buildId=1637506&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

**Comment by jordanlewis** [comment]
Note: this is a panic in sqlsmith itself, not the database.

**Comment by mjibson** [comment]
This was on a 19.2 branch that I can't get to build. But on master when I hard coded these schemas into the rsg test and ran it it worked fine, so I'm not able to reproduce this yet.
