### ISSUE TITLE
colexec: incomplete shutdown of the flows with wrapped processors

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#43269]
I finally was able to reproduce a failure of #42664 locally (although it is different from the mysterious type mismatch that occurred only on TC builds). The following logic test will occasionally timeout on the current master which shows that #42664 is not the one to blame and that, instead, we have another problem, probably with clean up of `ParallelUnorderedSynchronizer`.

```
# LogicTest: fakedist-vec

statement ok
CREATE TABLE square (n INT PRIMARY KEY, sq INT)

statement ok
INSERT INTO square VALUES (1,1), (2,4), (3,9), (4,16), (5,25), (6,36)

statement ok
CREATE TABLE pairs (a INT8, b INT8, FAMILY (a), FAMILY (b))

statement ok
INSERT INTO pairs VALUES (1,1), (1,2), (1,3), (1,4), (1,5), (1,6), (2,3), (2,4), (2,5), (2,6), (3,4), (3,5), (3,6), (4,5), (4,6)

statement ok
SELECT *
  FROM (SELECT * FROM pairs LEFT JOIN square ON b = sq AND a > 1 AND n < 6)
 WHERE b > 1 AND (n IS NULL OR n > 1) AND (n IS NULL OR a  < sq)
```

The only `sql/colexec` goroutine that is stuck is
```
goroutine 1837 [select]:
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init.func2(0xc0018a43c0, 0xc001f4e3a0, 0x7c92a00, 0xc000ec8a90, 0x0)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:182 +0x2e6
created by github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:144 +0x1e2
```

I've been invoking the logic test as follows:
`make test TESTS=TestLogic/^fakedist-vec\$\$/temp PKG=github.com/cockroachdb/cockroach/pkg/sql/logictest TESTTIMEOUT=5s TESTFLAGS='-test.v -show-sql'`

**Comment by yuzefovich** [comment]
I looked into this, I believe I see the root cause. Our flow shutdown mechanism relies on all components to listen to the same context which is canceled by the "root" component (either materializer or outbox) when the query needs to exit. Columnarizers currently capture the context that is passed into their constructor and will pass that context further into their downstream operators. However, I believe it is possible that the cancellation of the "flow" context will not trigger the cancellation of the columnarizer's context, so some components are left hanging.

Consider the following flow:
```
                                                / materializer <- parallel unordered synchronizer ...
outbox <- columnarizer <- rowexec.hashJoiner <-|
                                                \ materializer <- parallel unordered synchronizer ...

```
Reader goroutines of the unordered synchronizers will be listening on the context captured when columnarizer was created, but outbox will cancel a different context.
