### ISSUE TITLE
 storage/replica.go:4471  [n1,s1,r94/1:/System/tsd/cr.node.sql.mem.i…] while committing batch: while committing batch: Corruption: Error: Could not perform merge.

### ISSUE THREAD

**Issue by peymanh** [cockroachdb/cockroach#43541]
**Describe the problem**

Hi. We have 3 replica of cockroach db on three different nodes. Suddenly the one on our manager node stopped working and by seeing the logs ( docker logs roach1_id --tail 100 ) this error has occured:

```
* WARNING: The server appears to be unable to contact the other nodes in the cluster. Please try:
* 
* - starting the other nodes, if you haven't already;
* - double-checking that the '--join' and '--listen'/'--advertise' flags are set up correctly;
* - running the 'cockroach init' command if you are trying to initialize a new cluster.
* 
* If problems persist, please see https://www.cockroachlabs.com/docs/v2.1/cluster-setup-troubleshooting.html.
*
*
* ERROR: [n1,s1,r94/1:/System/tsd/cr.node.sql.mem.i…] Reported as error 6a187e0cb72547178fe6fdd83e64a427
*
F191225 10:49:52.567458 77 storage/replica.go:4471  [n1,s1,r94/1:/System/tsd/cr.node.sql.mem.i…] while committing batch: while committing batch: Corruption: Error: Could not perform merge.
goroutine 77 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc4204aa500, 0xc4204aa540, 0x3f3b500, 0x12)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:997 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x4831fe0, 0xc400000004, 0x3f3b55a, 0x12, 0x1177, 0xc4270126c0, 0x8a)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:864 +0x8fe
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x305a3c0, 0xc4270b1c50, 0x4, 0x2, 0x2adc7e3, 0x6, 0xc42173bc00, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x305a3c0, 0xc4270b1c50, 0x1, 0x4, 0x2adc7e3, 0x6, 0xc42173bc00, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x305a3c0, 0xc4270b1c50, 0x2adc7e3, 0x6, 0xc42173bc00, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.fatalOnRaftReadyErr(0x305a3c0, 0xc4270b1c50, 0x2b01506, 0x16, 0x302f6c0, 0xc4270a1120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4471 +0x1c6
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x305a3c0, 0xc4270b1c50, 0xc4208f7b00, 0x305a3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3869 +0x177
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc4204e8680, 0x305a3c0, 0xc4270b1c50, 0xc4273b8000, 0xc42173bed0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3514 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc4204e8680, 0x305a3c0, 0xc4207c6180, 0x5e)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3856 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420474680, 0x305a3c0, 0xc4207c6180)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:225 +0x21b
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x305a3c0, 0xc4207c6180)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4204536b0, 0xc4201c1320, 0xc420453690)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:201 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:194 +0xad
```

**To Reproduce**

Unfortunately We have no idea how this problem may happen.

**Environment:**
- CockroachDB version 2.1.5
- Server OS: UBUNTU
- Client app cockroach sql

**Comment by petermattis** [comment]
@peymanh That error indicates there was a problem down in the RocksDB layer. This could be a result of a bug in either CockroachDB or RocksDB, or it could be due to on-disk corruption (e.g. due to hardware). The latter (on-disk corruption) is more likely in this instance as I've never seen this particular error before.

If your goal is to get the system back up and operational as quickly as possible, I'd recommend replacing the problematic node. That is, decommission the node experiencing the problem, and add a new node to the cluster.

If you want to determine whether the cause of the error is on-disk corruption or something else, try looking for hardware diagnostics for the node in question. These might be present in `dmesg` or `/var/log/messages`.

**Comment by petermattis** [comment]
A recent private bug report with the same symptoms was tracked down to what appears to be a single bit flip corruption. In that issue, the `Could not perform merge` was being caused by the CockroachDB merge helper returning `false`. Subsequent debugging revealed this was due to the `start_timestamp_nanos` field of two merge records for the same key differing by a single bit (they should be identical):

```
1579759200000000000 = 1010111101100011011101001111101011010101001111100000000000000
1579759165640261632 = 1010111101100011011101001011101011010101001111100000000000000
                                               ^
1579759200000000000 ^ 1579759165640261632 = 1 << 35
```

The merge records in question were persisted to sstables. Because the sstable block checksums are valid on this data, the presumption is that the data was corrupted in memory before being written to the sstables. This would point to memory corruption, though the machines have ECC which makes that a bit less likely.
