### ISSUE TITLE
Test failures for random tests in pkg/cli and pkg/server on ppc64le

### ISSUE THREAD

**Issue by amitsadaphule** [cockroachdb/cockroach#43678]
**Description**

I built the cockroachdb code (commit 0d1ae9cbc49518180e68aa0bfbf982d73854ddae) on ppc64le (with a minor change necessary in the rocksdb makefile to suppress -march option usage in compilation) and when I executed the test suite, I found that there are test failures for random tests in pkg/cli and pkg/server. I tried executing the tests for those two packages independently which resulted in consistent failures for pkg/cli, but random failure/success for pkg/server.

Any pointers on what could be the source of the issue will be a great help.

**To Reproduce**

Here is the command I used to execute the entire test suite:

`make test TESTFLAGS='-v -count=1'`

Here are the commands I used to execute the tests for the failing packages independently:

```
make test PKG=./pkg/cli TESTFLAGS='-v -count=1'
make test PKG=./pkg/server TESTFLAGS='-v -count=1'
```

Pasting relevant parts of the log for pkg/cli:

```
=== RUN   TestRemoveDeadReplicas/1/3/r=3
W200101 15:01:31.209958 10957740 server/status/runtime.go:308  [n?] Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W200101 15:01:35.050067 10957923 storage/store.go:1513  [n1,s1,r6/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r6: replica (n1,s1):1 not lease holder; lease holder unknown
W200101 15:01:35.110500 10957923 storage/store.go:1513  [n1,s1,r6/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r6: replica (n1,s1):1 not lease holder; lease holder unknown
W200101 15:01:35.221454 10957923 storage/store.go:1513  [n1,s1,r6/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r6: replica (n1,s1):1 not lease holder; lease holder unknown

.........

W200101 15:07:25.750097 11239405 storage/node_liveness.go:484  [n2,liveness-hb] failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s
W200101 15:07:26.036232 10960315 server/node.go:835  [n1,summaries] health alerts detected: {Alerts:[{StoreID:1 Category:METRICS Description:ranges.underreplicated Value:13}]}
W200101 15:07:26.804559 11241496 storage/node_liveness.go:559  [n3,liveness-hb] slow heartbeat took 4.5s
W200101 15:07:26.804712 11241496 storage/node_liveness.go:484  [n3,liveness-hb] failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s
W200101 15:07:30.250714 11239405 storage/node_liveness.go:559  [n2,liveness-hb] slow heartbeat took 4.5s
W200101 15:07:30.250835 11239405 storage/node_liveness.go:484  [n2,liveness-hb] failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s
panic: test timed out after 20m0s

goroutine 17047883 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1334 +0xcc
created by time.goFunc
	/usr/local/go/src/time/sleep.go:169 +0x44

goroutine 1 [chan receive, 6 minutes]:
testing.(*T).Run(0xc001286000, 0x136eeaf3, 0x16, 0x13855948, 0x1)
	/usr/local/go/src/testing/testing.go:917 +0x310
testing.runTests.func1(0xc000b9b200)
	/usr/local/go/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc000b9b200, 0xc000b3dd98)
	/usr/local/go/src/testing/testing.go:865 +0xc4
testing.runTests(0xc0002f62e0, 0x162fc500, 0x34, 0x34, 0x0)
	/usr/local/go/src/testing/testing.go:1155 +0x284
testing.(*M).Run(0xc0002e0180, 0x0)
	/usr/local/go/src/testing/testing.go:1072 +0x158
github.com/cockroachdb/cockroach/pkg/cli_test.TestMain(0xc0002e0180)
	/root/amit_sadaphule/go/src/github.com/cockroachdb/cockroach/pkg/cli/main_test.go:34 +0x90
main.main()
	_testmain.go:184 +0x138
.......
```

However, when I executed the same tests or the entire test suite on x86_64, no failures were seen.

**Additional data**

PFA a zip containing the log file:
maketest_log.txt - complete test suite logs showing failures for pkg/cli, pkg/server

[maketest_log.zip](https://github.com/cockroachdb/cockroach/files/4014271/maketest_log.zip)

**Environment**
CockroachDB [commit 0d1ae9cbc49518180e68aa0bfbf982d73854ddae]
Architecture and OS: [ppc64le/RHEL7.6]

**Comment by amitsadaphule** [comment]
For latest stable version (v19.2.2), the tests for both packages are failing while executing entire test suite, but the tests are passing for both packages when executed separately as:

```
make test PKG=./pkg/cli TESTFLAGS='-v -count=1'
make test PKG=./pkg/server TESTFLAGS='-v -count=1'
```

**Comment by amitsadaphule** [comment]
Any pointers on these failures? Thanks in advance!

**Comment by jordanlewis** [comment]
Sorry for the lack of response. These were just timeouts - try running a smaller subset of the tests at a time. Closing due to age. Please open a new issue if you still have a problem here.
