### ISSUE TITLE
Node crash after being run under load for 45 min: "Too many open files"

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4419]
```
panic: IO error: ./data1/000078.log: Too many open files

goroutine 35 [running]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/storage/store.go:1640 +0x337
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202b9180, 0xc820125a50)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 1 [select, 40 minutes]:
github.com/cockroachdb/cockroach/cli.runStart(0x5bd5560, 0xc8202d0030, 0x0, 0x1, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/cli/start.go:142 +0x117b
github.com/spf13/cobra.(*Command).execute(0x5bd5560, 0xc8202b3fe0, 0x1, 0x1, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/spf13/cobra/command.go:565 +0x63b
github.com/spf13/cobra.(*Command).ExecuteC(0x5bd2360, 0x5bd5560, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/spf13/cobra/command.go:656 +0x56b
github.com/spf13/cobra.(*Command).Execute(0x5bd2360, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/spf13/cobra/command.go:615 +0x2d
github.com/cockroachdb/cockroach/cli.Run(0xc82000a1c0, 0x2, 0x2, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/cli/cli.go:85 +0x7c
main.main()
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/main.go:37 +0xe6
```

The stack trace is pretty long, but I'm not sure adding any more would be helpful.

**Comment by tamird** [comment]
How many goroutines are you seeing? It's possible we're leaking some with
the move to grpc.

**Comment by nvanbenschoten** [comment]
The node that went down had 331 before crashing, the other two had 98 and 92.

**Comment by tschottdorf** [comment]
pro tip: `panicparse ${FILE}` gives you a nice summary of goroutines and
their multiplicity.
https://github.com/maruel/panicparse

**Comment by bdarnell** [comment]
Looks like the raft transport is leaking connections/goroutines since the move to GRPC (the default "open files" ulimit on OSX is 256). Dupe of #4422?

**Comment by nvanbenschoten** [comment]
Looks like it is. I had 225 open HTTP connections at the time of crashing.

**Comment by bdarnell** [comment]
#4422 was a test-specific issue and is now closed. Reopening this one since it occurs with the production transport.

**Comment by tamird** [comment]
@nvanbenschoten can you try to reproduce this again now that #4608 is merged?

**Comment by nvanbenschoten** [comment]
I haven't seen this issue since I created it so I'm going to go ahead and close this, but I'll keep an eye out. This issue may have been related to some of the perf issues @spencerkimball was seeing.
