### ISSUE TITLE
kv: TxnCoordSender: close of closed channel

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4426]
From Gitter (user a6802739). Maybe we can spot the race easily.

```
> I0216 00:00:30.720429 58552 storage/replica_command.go:1300  initiating a split of range=1 [/Min-/Table/11) at key /System/"tsd!cr.store.valcount\x00\x01\x89\xf8\x06+`9"
I0216 00:00:35.797282 58552 server/status/runtime.go:137  runtime stats: 140 goroutines, 5.10MiB active, 524.20cgo/sec, 1.16/0.00 %(u/s)time, 0.00 %gc (3x)
I0216 00:00:45.537755 58552 storage/replica_command.go:1227  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1455552046.534s
panic: close of closed channel

goroutine 44 [running]:
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).cleanupTxn(0xc8203741e0, 0x7f1063e035f8, 0x23db298, 0xc82049bea0, 0xc820528540, 0x28, 0x30, 0x0, 0x143328dc2f3219fc, 0x0, ...)
    /root/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:523 +0x188
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState(0xc8203741e0, 0x7f1063e03660, 0xc8206c79e0, 0x143328dc2f3219fc, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc8209463b8, ...)
    /root/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:796 +0x2c5
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send(0xc8203741e0, 0x7f1063e03660, 0xc8206c79e0, 0x143328dc2f3219fc, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc8209463b8, ...)
    /root/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:418 +0xe4a
github.com/cockroachdb/cockroach/client.(*txnSender).Send(0xc820946360, 0x7f1063e035b8, 0xc820013ac0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8209463b8, ...)
    /root/go/src/github.com/cockroachdb/cockroach/client/txn.go:54 +0xca
github.com/cockroachdb/cockroach/client.(*DB).send(0xc820946360, 0xc820774da8, 0x1, 0x1, 0x91be9b, 0xc8207a77a0)
    /root/go/src/github.com/cockroachdb/cockroach/client/db.go:482 +0x16b
github.com/cockroachdb/cockroach/client.(*Txn).send(0xc820946360, 0xc820774da8, 0x1, 0x1, 0xc82098a000, 0xc8201570e0)
    /root/go/src/github.com/cockroachdb/cockroach/client/txn.go:501 +0x9d4
github.com/cockroachdb/cockroach/client.(*Txn).sendEndTxnReq(0xc820946360, 0xc820a70600, 0x0, 0x10)
    /root/go/src/github.com/cockroachdb/cockroach/client/txn.go:382 +0x1fa
github.com/cockroachdb/cockroach/client.(*Txn).Rollback(0xc820946360, 0xc8202d3ba0)
    /root/go/src/github.com/cockroachdb/cockroach/client/txn.go:378 +0x2f
github.com/cockroachdb/cockroach/client.(*Txn).Cleanup(0xc820946360, 0xc8206c7740)
    /root/go/src/github.com/cockroachdb/cockroach/client/txn.go:327 +0x3b
github.com/cockroachdb/cockroach/client.(*Txn).exec(0xc820946360, 0xc820775318, 0x15)
    /root/go/src/github.com/cockroachdb/cockroach/client/txn.go:439 +0x67b
github.com/cockroachdb/cockroach/client.(*DB).Txn(0xc82036c5a0, 0xc820775318, 0xc820845328)
    /root/go/src/github.com/cockroachdb/cockroach/client/db.go:463 +0x157
github.com/cockroachdb/cockroach/storage.(*Replica).AdminSplit(0xc8205561a0, 0x23db298, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /root/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1302 +0xdee
github.com/cockroachdb/cockroach/storage.(*Replica).addAdminCmd(0xc8205561a0, 0x7f1063e03660, 0xc8206c7410, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /root/go/src/github.com/cockroachdb/cockroach/storage/replica.go:795 +0x565
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc8205561a0, 0x7f1063e03660, 0xc8206c7410, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /root/go/src/github.com/cockroachdb/cockroach/storage/replica.go:648 +0x157
github.com/cockroachdb/cockroach/client.SendWrappedWith(0x7f1062578fd0, 0xc8205561a0, 0x7f1063e03660, 0xc8206c7410, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /root/go/src/github.com/cockroachdb/cockroach/client/sender.go:91 +0x1a6
```

**Comment by tschottdorf** [comment]
@RaduBerinde not anything concrete to do here, but a quick review whether there's an obvious way in which this double close can happen would be nice.

**Comment by tschottdorf** [comment]
Ok, just happened again, #5292 has logs.

**Comment by mberhault** [comment]
#5292 is `close of nil channel`. maybe something was tweaked.

**Comment by tschottdorf** [comment]
You're right, not exactly the same. Should be the same underlying issue-though - two calls to `cleanupTxn` (or whichever one closes that channel).

**Comment by RaduBerinde** [comment]
[This commit](https://github.com/cockroachdb/cockroach/commit/0ee3a436315ab05713e96336404d667e5f9b9e4d) sets the channel to `nil` after close so now we will see it as `close on nil channel`.

**Comment by RaduBerinde** [comment]
I've been looking at this code for a while but I'm having trouble understanding a couple of things.

I am assuming that it is possible to get requests on a txn that was already aborted/committed (in the stack trace it looks like we send an `endTxnReq` in response to an error on commit). When that happens, won't we then get a `TransactionAbortedError/StatusError` error inside `TxnCoordSender.Send` when we send the request below, and then clean up the txn again in `updateState`? What prevents that from happening normally?

I don't see any races wrt the heartbeat (the heartbeat doesn't clean up `txnEnd`, only the Send path does).

**Comment by tschottdorf** [comment]
You're right. The fix is "morally" (but not actually)

```diff
diff --git a/kv/txn_coord_sender.go b/kv/txn_coord_sender.go
index 3d2912b..50d3c35 100644
--- a/kv/txn_coord_sender.go
+++ b/kv/txn_coord_sender.go
@@ -527,6 +527,7 @@ func (tc *TxnCoordSender) cleanupTxn(ctx context.Context, txn roachpb.Transactio
        if !ok {
                return
        }
+       delete(tc.txns, *txn.ID)

        // The supplied txn may be newer than the one in txnMeta, which is relevant
        // for stats.
```

but `unregisterTxnLocked` called from the heartbeat should do the delete so that everything works as expected.

Instead,

```diff
diff --git a/kv/txn_coord_sender.go b/kv/txn_coord_sender.go
index 3d2912b..4fd7372 100644
--- a/kv/txn_coord_sender.go
+++ b/kv/txn_coord_sender.go
@@ -524,7 +524,7 @@ func (tc *TxnCoordSender) cleanupTxn(ctx context.Context, txn roachpb.Transactio
        defer tc.Unlock()
        txnMeta, ok := tc.txns[*txn.ID]
        // The heartbeat might've already removed the record.
-       if !ok {
+       if !ok || txnMeta.txnEnd == nil {
                return
        }
```

What do you think?

**Comment by RaduBerinde** [comment]
In other words, you are suggesting just tolerating multiple `cleanupTxn` calls right? That's easy enough, I think it used to be like that (there even used to be a test for that that I can dig up).

But I feel we must be missing something, or this crash would be very common. client/txn always does a `Rollback` (`sendEndTxnReq`) after a commit error, wouldn't it crash every time? There must be something else that "usually" prevents the duplicate call.

**Comment by tschottdorf** [comment]
I would think that most of the time, `TxnCoordSender` drops its state early enough so that the second request doesn't even make it far enough. Can't hurt to make sure though.

**Comment by RaduBerinde** [comment]
By "drops its state" you mean the txnMeta gets removed from txns? I don't see how that would happen (other than the heartbeat, but that's only once every 5 secs)
