### ISSUE TITLE
Node won't rejoin the cluster after power loss: Node not in liveness table

### ISSUE THREAD

**Issue by Fornax96** [cockroachdb/cockroach#44531]
**Describe the problem**

I have a 5 node cluster: 2 nodes in the USA and 3 in Europe. One of the USA nodes had a power failure and now it can't join the cluster anymore. The other 4 nodes are still working.

**To Reproduce**

Set up a 5 node cluster under moderate load (~30 queries per second on average) and yank the power on one of them. See if it can join again.

**Expected behavior**
The node rejoins the cluster and continues processing queries.

**Additional data / screenshots**
```
*
* ERROR: [n7,s7,r2/15:/System/NodeLiveness{-Max}] Reported as error 2451891afbc14a67ba62fd8c0cef73b6
*
F200130 07:49:08.897279 134 vendor/go.etcd.io/etcd/raft/log.go:203  [n7,s7,r2/15:/System/NodeLiveness{-Max}] tocommit(30452820) is out of range [lastIndex(30452811)]. Was the raft log corrupted, truncated, or lost?
goroutine 134 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc000426300, 0xc000426300, 0x0, 0xc006712b58)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1017 +0xb1
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x7514940, 0xc000000004, 0x6ce09d3, 0x22, 0xcb, 0xc000812e60, 0x92)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:871 +0x95b
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4a5e5c0, 0xc000b04690, 0x7fd500000004, 0x3, 0x41b5ae2, 0x5d, 0xc00631ab40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2cc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4a5e5c0, 0xc000b04690, 0x2, 0xc000000004, 0x41b5ae2, 0x5d, 0xc00631ab40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.FatalfDepth(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:199
github.com/cockroachdb/cockroach/pkg/storage.(*raftLogger).Panicf(0xc0004367f0, 0x41b5ae2, 0x5d, 0xc00631ab40, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.go:102 +0xf1
github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft.(*raftLog).commitTo(0xc0011aa460, 0x1d0ac54)
        /go/src/github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft/log.go:203 +0x131
github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft.(*raft).handleHeartbeat(0xc00081e280, 0x8, 0xf, 0xd, 0x504, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft/raft.go:1396 +0x54
github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft.stepCandidate(0xc00081e280, 0x8, 0xf, 0xd, 0x504, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft/raft.go:1296 +0x742
github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft.(*raft).Step(0xc00081e280, 0x8, 0xf, 0xd, 0x504, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft/raft.go:984 +0x1113
github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft.(*RawNode).Step(0xc000d00f40, 0x8, 0xf, 0xd, 0x504, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft/rawnode.go:114 +0xcc
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).stepRaftGroup.func1(0xc000d00f40, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:398 +0x108
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked.func1(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:1385
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc00003d000, 0x426fd00, 0xc0065cf880, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:1386 +0x79
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroup(0xc00003d000, 0x0, 0xc00626a880, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:1412 +0x8c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).stepRaftGroup(0xc00003d000, 0xc00093b800, 0x4a1b240, 0xc00003d000)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:391 +0x66
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequestWithReplica(0xc0011ba000, 0x4a5e5c0, 0xc003f17f20, 0xc00003d000, 0xc00093b800, 0xc00626acf0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store_raft.go:243 +0x192
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x4a5e5c0, 0xc003f17f20, 0xc00003d000, 0x4a5e5c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store_raft.go:441 +0x99
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc0011ba000, 0x4a5e5c0, 0xc003f17f20, 0xc00093b800, 0xc00626aec0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store_raft.go:200 +0x16b
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc0011ba000, 0x4a5e5c0, 0xc0011e84b0, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store_raft.go:436 +0x1f4
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc00045d600, 0x4a5e5c0, 0xc0011e84b0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:238 +0x214
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x4a5e5c0, 0xc0011e84b0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:161 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00041a980, 0xc000809680, 0xc00041a970)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xfb
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xa8
****************************************************************************
This node experienced a fatal error (printed above), and as a result the
process is terminating.
Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
problem in CockroachDB. With your help, the support team at Cockroach Labs
will try to determine the root cause, recommend next steps, and we can
improve CockroachDB based on your report.
Please submit a crash report by following the instructions here:
    https://github.com/cockroachdb/cockroach/issues/new/choose
If you would rather not post publicly, please contact us directly at:
    support@cockroachlabs.com
The Cockroach Labs team appreciates your feedback.
```

I can e-mail logs if you need them.

**Environment:**
 - CockroachDB version v19.2.2
 - Server OS: Ubuntu server edition 18.04.3 LTS
 - Client app golang pq and sqlx

**Additional context**
pixeldrain.com is down in the US because of this. I need to get it up ASAP so I'm gonna try decommissioning and recommissioning it.

**Comment by Fornax96** [comment]
Recommissioning the node worked. It's live again.

The exact steps were:

Log in to a different cockroach node, `cockroach node decommission 7`, `cockroach node recommission 7`, start node 7, success.

**Comment by jordanlewis** [comment]
Closing due to age.
