### ISSUE TITLE
kv: TestKVNemesisSingleNode sometimes blocks

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#44611]
```
make test PKG='./pkg/kv/kvnemesis/' TESTS=TestKVNemesisSingleNode  TESTFLAGS="-count=200 -v"
```

Usually everything is fast, but at some point `TestKVNemesisSingleNode` just seems to run forever. 

I got stack traces by sending a `SIGABRT`. Interestingly, there's no `_test.go` in there. Don't know what to make of it.

```
=== RUN   TestKVNemesisSingleNode


SIGABRT: abort
PC=0x7fff757ea866 m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x1ab2b28, 0x1ab2ae8, 0x0)
	/Users/andrei/goroot/src/runtime/sys_darwin.go:378 +0x39
runtime.semasleep(0xffffffffffffffff, 0xc0012d3048)
	/Users/andrei/goroot/src/runtime/os_darwin.go:63 +0x85
runtime.notesleep(0x1ab28e8)
	/Users/andrei/goroot/src/runtime/lock_sema.go:173 +0xe0
runtime.stopm()
	/Users/andrei/goroot/src/runtime/proc.go:1928 +0xc0
runtime.exitsyscall0(0xc00059b080)
	/Users/andrei/goroot/src/runtime/proc.go:3140 +0x111
runtime.mcall(0x105a6b6)
	/Users/andrei/goroot/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc0000e0028)
	/Users/andrei/goroot/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0000e0020)
	/Users/andrei/goroot/src/sync/waitgroup.go:130 +0x64
cmd/go/internal/work.(*Builder).Do(0xc0008b72c0, 0xc001848c80)
	/Users/andrei/goroot/src/cmd/go/internal/work/exec.go:186 +0x3c5
cmd/go/internal/test.runTest(0x1aa7040, 0xc0000cad20, 0xb, 0xb)
	/Users/andrei/goroot/src/cmd/go/internal/test/test.go:770 +0xecc
main.main()
	/Users/andrei/goroot/src/cmd/go/main.go:189 +0x57f

goroutine 35 [syscall]:
os/signal.signal_recv(0x172d6e0)
	/Users/andrei/goroot/src/runtime/sigqueue.go:144 +0x96
os/signal.loop()
	/Users/andrei/goroot/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/Users/andrei/goroot/src/os/signal/signal_unix.go:29 +0x41

goroutine 7139 [IO wait]:
internal/poll.runtime_pollWait(0x5e61e18, 0x72, 0xffffffffffffffff)
	/Users/andrei/goroot/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00035f0f8, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
	/Users/andrei/goroot/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/Users/andrei/goroot/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00035f0e0, 0xc0023ce000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/Users/andrei/goroot/src/internal/poll/fd_unix.go:169 +0x22b
os.(*File).read(...)
	/Users/andrei/goroot/src/os/file_unix.go:259
os.(*File).Read(0xc000211ba0, 0xc0023ce000, 0x8000, 0x8000, 0x41, 0x0, 0x0)
	/Users/andrei/goroot/src/os/file.go:116 +0x71
io.copyBuffer(0x1726980, 0xc000bd51a0, 0x1726ce0, 0xc000211ba0, 0xc0023ce000, 0x8000, 0x8000, 0x1006a65, 0xc00035ea80, 0xc0001147b0)
	/Users/andrei/goroot/src/io/io.go:402 +0x122
io.Copy(...)
	/Users/andrei/goroot/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0xc00035ea80, 0xc0001147b0)
	/Users/andrei/goroot/src/os/exec/exec.go:311 +0x63
os/exec.(*Cmd).Start.func1(0xc0014e69a0, 0xc000bd52a0)
	/Users/andrei/goroot/src/os/exec/exec.go:435 +0x27
created by os/exec.(*Cmd).Start
	/Users/andrei/goroot/src/os/exec/exec.go:434 +0x608

goroutine 7125 [syscall]:
syscall.syscall6(0x10ad1d0, 0x1cd0, 0xc000115e9c, 0x0, 0xc0001af170, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/andrei/goroot/src/runtime/sys_darwin.go:74 +0x2e
syscall.wait4(0x1cd0, 0xc000115e9c, 0x0, 0xc0001af170, 0x90, 0x1625060, 0x10c3201)
	/Users/andrei/goroot/src/syscall/zsyscall_darwin_amd64.go:44 +0x87
syscall.Wait4(0x1cd0, 0xc000115eec, 0x0, 0xc0001af170, 0x1597960, 0xc000115f58, 0x1006f29)
	/Users/andrei/goroot/src/syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc000d77e30, 0xc00035e300, 0x0, 0x0)
	/Users/andrei/goroot/src/os/exec_unix.go:38 +0x7b
os.(*Process).Wait(...)
	/Users/andrei/goroot/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc0014e69a0, 0xc00035e6c0, 0xc000115fb0)
	/Users/andrei/goroot/src/os/exec/exec.go:501 +0x60
cmd/go/internal/test.(*runCache).builderRunTest.func1(0xc000f918c0, 0xc0014e69a0)
	/Users/andrei/goroot/src/cmd/go/internal/test/test.go:1179 +0x2b
created by cmd/go/internal/test.(*runCache).builderRunTest
	/Users/andrei/goroot/src/cmd/go/internal/test/test.go:1178 +0xd6d

goroutine 7095 [select]:
cmd/go/internal/test.(*runCache).builderRunTest(0xc0013cc000, 0xc0008b72c0, 0xc00139c500, 0x0, 0x0)
	/Users/andrei/goroot/src/cmd/go/internal/test/test.go:1182 +0xe11
cmd/go/internal/work.(*Builder).Do.func2(0xc00139c500)
	/Users/andrei/goroot/src/cmd/go/internal/work/exec.go:117 +0x36d
cmd/go/internal/work.(*Builder).Do.func3(0xc0000e0020, 0xc0008b72c0, 0xc0003c5600)
	/Users/andrei/goroot/src/cmd/go/internal/work/exec.go:177 +0x79
created by cmd/go/internal/work.(*Builder).Do
	/Users/andrei/goroot/src/cmd/go/internal/work/exec.go:164 +0x3a1
```

**Comment by danhhz** [comment]
That is strange, I’ve roachprod stressed this with a timeout quite a bit. In case it’s relevant, what SHA are you on?

**Comment by danhhz** [comment]
Am I missing something (am on mobile) or do none of those stacktraces have any sort of cockroach code in them?

**Comment by andreimatei** [comment]
1a3c23278a981cc4123e71f389953a7a76b03f81

**Comment by andreimatei** [comment]
> Am I missing something (am on mobile) or do none of those stacktraces have any sort of cockroach code in them?

Yeah, that's what I was saying. I was thinking that perhaps this is a case of `t.Fatal()` killing the wrong go routine, but I don't think so, and also there's not many `t.Fatal()` or `require.Foo` calls in this test.

**Comment by irfansharif** [comment]
Closing due to age.
