### ISSUE TITLE
sql: async pyscopg2 cursor should not allow partial execution

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#44706]
When passing multiple statements into an async cursor, the behavior with Postgres is that if one fails, then the whole batch of statements does not get executed. However, with CockroachDB, the batch can be partially executed. This causes the psycopg2 test `AsyncTests.test_error` to fail. Here is a more concrete example:

schema:
```
create table a (a int primary key);
```

Connecting to Postgres:
```
>>> import psycopg2
>>> import select
>>> def wait(cur_or_conn):
...     pollable = cur_or_conn
...     if not hasattr(pollable, 'poll'):
...         pollable = cur_or_conn.connection
...     while True:
...         state = pollable.poll()
...         if state == psycopg2.extensions.POLL_OK:
...             break
...         elif state == psycopg2.extensions.POLL_READ:
...             select.select([pollable], [], [], 1)
...         elif state == psycopg2.extensions.POLL_WRITE:
...             select.select([], [pollable], [], 1)
...         else:
...             raise Exception("Unexpected result from poll: %r", state)
>>> conn = psycopg2.connect("dbname='postgres' user='rafiss' host='localhost' password='' port=5432", async_=True)
>>> wait(conn)
>>> cur = conn.cursor()
>>> cur.execute("insert into a values(%s); insert into a values(%s)", (2,2))
>>> wait(cur)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in wait
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "a_pkey"
DETAIL:  Key (a)=(2) already exists.

# at this point, table a is empty
```

But with CockroachDB:
```
>>> conn_crdb = psycopg2.connect("dbname='defaultdb' user='root' host='localhost' password='' port=26257", async_=True)
>>> wait(conn_crdb)
>>> cur_crdb = conn_crdb.cursor()
>>> cur_crdb.execute("insert into a values(%s); insert into a values(%s)", (2,2))
>>> wait(cur_crdb)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in wait
psycopg2.errors.UniqueViolation: duplicate key value (a)=(2) violates unique constraint "primary"

# at this point, table a has one row with the value 2
```

**Comment by rafiss** [comment]
This is likely explained by #44803

**Comment by jordanlewis** [comment]
This definitely looks like it's explained by #44803, so I'll close this one as a duplicate for now.
