### ISSUE TITLE
changefeedccl: span use after finish

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#44927]
A customer reported the following crash. This kind of crash usually means a span is used after it was `Finish()ed`. I looked superficially and couldn't see what's wrong; afaics, the changefeed polling happens all in a very high-level span opened by a `stopper`.
They were running 19.1.5 with `set cluster setting trace.debug.enable = true;`.

@danhhz is this you?

```
panic: runtime error: index out of range
goroutine 125478402 [running]:
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).addEvent(0xc0302d1ba0, 0x2ea3700, 0xc0df8103c0, 0xc094530000)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:805 +0x6fa
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace.(*trace).LazyPrintf(0xc0302d1ba0, 0x32c5849, 0x2, 0xc094531270, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:834 +0x9a
github.com/cockroachdb/cockroach/pkg/util/tracing.(*span).LogFields(0xc0767a41a0, 0xc04a1b8140, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tracer_span.go:388 +0x6c5
github.com/cockroachdb/cockroach/pkg/util/log.eventInternal(0x3a4f1c0, 0xc0420d5440, 0x2dd0000, 0x32ce32c, 0x8, 0xc092957750, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:132 +0x27b
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3a4f1c0, 0xc0420d5440, 0x1, 0x2, 0x336f61f, 0x3b, 0xc092957c30, 0x5, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:84 +0x28b
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3a4f1c0, 0xc0420d5440, 0x1, 0xc000000001, 0x336f61f, 0x3b, 0xc092957c30, 0x5, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Infof(0x3a4f1c0, 0xc0420d5440, 0x336f61f, 0x3b, 0xc092957c30, 0x5, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:97 +0x7e
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*poller).exportSpan(0xc096dffe10, 0x3a4f1c0, 0xc0420d5440, 0xc0d9400240, 0x1f, 0x20, 0xc0d94002a0, 0x1f, 0x20, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/poller.go:502 +0xbf1
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*poller).exportSpansParallel.func1(0x3a4f1c0, 0xc0420d5440, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/poller.go:457 +0x180
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1(0xc000000008, 0x3440238)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:170 +0x3a
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc09d363d40, 0xc09d363dd0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

**Comment by andreimatei** [comment]
cc @ajwerner ?

**Comment by ajwerner** [comment]
I touched the code only very recently. I guess I'm not super surprised that there's a span lifecycle problem here. I guess you can assign it to me?

**Comment by andreimatei** [comment]
The code in question here has gone away, and also I've done a bunch of work recently to tighten our use of spans. Also we're going to test against span-use-after-Finish more rigorously. I think it's time for this issue to go away.
