### ISSUE TITLE
EXPERIMENTAL SCRUB TABLE crashes server for table with TIMESTAMP column

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#44992]
Consider the following statements:

```sql
CREATE TABLE t0(c0 TIMESTAMP UNIQUE);
INSERT INTO t0(c0) VALUES(TIMESTAMP '1969-1-1');
INSERT INTO t0(c0) VALUES(TIMESTAMP '1969-1-2');
EXPERIMENTAL SCRUB TABLE t0; -- crashes server
```
Unexpectedly, the `EXPERIMENTAL SCRUB TABLE` crashes the server with the following stack trace:

```
*
* ERROR: [n1,client=127.0.0.1:33704,user=root] a SQL panic has occurred while executing "EXPERIMENTAL SCRUB TABLE t0": runtime error: invalid memory address or nil pointer dereference
*
*
* ERROR: [n1,client=127.0.0.1:33704,user=root] a panic has occurred!
*
panic while executing 1 statements: EXPERIMENTAL SCRUB TABLE _

goroutine 85416 [running]:
runtime/debug.Stack(0x4a637e0, 0xc00d8af440, 0x3)
	/usr/lib/go-1.13/src/runtime/debug/stack.go:24 +0x9d
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x4a637e0, 0xc00d8af440, 0xc000038a80, 0x3ff1ba0, 0xc004d57140, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:218 +0xb5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00aeed000, 0x4a637e0, 0xc00d8af440, 0x3cdfca0, 0x6a88fe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:769 +0x348
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc00aeed000, 0x4a637e0, 0xc00d8af440)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:450 +0x61
panic(0x3cdfca0, 0x6a88fe0)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*EvalContext).GetLocation(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3021
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.timeFromDatumForComparison(0xc010076fc0, 0x4adea80, 0xc0100a6498, 0xc0100a6498, 0x1b8, 0x1b8, 0xc010076fc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:2165 +0xf1
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.compareTimestamps(0xc010076fc0, 0x4adea80, 0xc0100a6498, 0x4adea80, 0xc0100a6480, 0xc010076fc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:2181 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*DTimestamp).Compare(0xc0100a6498, 0xc010076fc0, 0x4adea80, 0xc0100a6480, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:2234 +0x62
github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).checkKeyOrdering(0xc006674ea0, 0x4a637e0, 0xc00f8c9600, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:1401 +0x19c
github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).NextRowWithErrors(0xc006674ea0, 0x4a637e0, 0xc00f8c9600, 0xc005e1db28, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:1284 +0x334
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*scrubTableReader).Next(0xc000698a80, 0x0, 0x0, 0x0, 0x4a637e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/scrub_tablereader.go:239 +0x75
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run(0x4a637e0, 0xc00f8c9600, 0x4a87420, 0xc000698a80, 0x4a427a0, 0xc00f885880)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:170 +0x35
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run(0xc000698a80, 0x4a637e0, 0xc00f8c9600)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:749 +0x92
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc006674d80, 0x4a637e0, 0xc00f8c9600, 0x437f4f8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370 +0x247
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00011e000, 0xc00cf85ec0, 0xc00f1a7050, 0xc008063698, 0xc010060000, 0xc00f8b7400, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:377 +0x426
github.com/cockroachdb/cockroach/pkg/sql.scrubRunDistSQL(0x4a637e0, 0xc00f15bac0, 0xc00cf85ec0, 0xc00aeed3c0, 0xc008063698, 0x7127d20, 0x3, 0x3, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/scrub.go:480 +0x31f
github.com/cockroachdb/cockroach/pkg/sql.(*physicalCheckOperation).Start(0xc0069efaa0, 0x4a637e0, 0xc00f15bac0, 0xc00f87e000, 0xc00aeed3c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/scrub_physical.go:131 +0x8af
github.com/cockroachdb/cockroach/pkg/sql.(*scrubNode).Next(0xc00f3a3d10, 0x4a637e0, 0xc00f15bac0, 0xc00f87e000, 0xc00aeed3c0, 0x0, 0x4a637e0, 0xc00f15bac0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/scrub.go:114 +0x232
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc000518000, 0xc00aeed3c0, 0x4a65c20, 0xc00f3a3d10, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:171 +0x439
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run(0x4a637e0, 0xc00f15bac0, 0x4a83c20, 0xc000518000, 0x4a427a0, 0xc00f7adc00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:170 +0x35
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run(0xc000518000, 0x4a637e0, 0xc00f15bac0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:749 +0x92
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc00de7ab40, 0x4a637e0, 0xc00f15bac0, 0x437f4f8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370 +0x247
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00011e000, 0xc0069ef9e0, 0xc00f1a7050, 0xc008064558, 0xc00cf6adc0, 0xc00aeed4a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:377 +0x426
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00011e000, 0x4a638a0, 0xc0057cecc0, 0xc00aeed4a0, 0xc0069ef9e0, 0xc00f1a7050, 0x4a65c20, 0xc00f3a3d10, 0xc00cf6adc0, 0xc00aeed1d8)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:987 +0x225
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc00aeed000, 0x4a638a0, 0xc0057cecc0, 0xc00aeed3c0, 0x3, 0x7f1f8dea0048, 0xc0006cca80, 0xc008064900, 0xc00f3a3d08, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:834 +0x3cf
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00aeed000, 0x4a638a0, 0xc0057cecc0, 0xc00aeed3c0, 0x7f1f8dea0048, 0xc0006cca80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:724 +0x70a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00aeed000, 0x4a638a0, 0xc0057cecc0, 0x4a7d2a0, 0xc00f3a3c70, 0xc00afee6a9, 0x1b, 0x0, 0x1, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:420 +0x9aa
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00aeed000, 0x4a638a0, 0xc0057cecc0, 0x4a7d2a0, 0xc00f3a3c70, 0xc00afee6a9, 0x1b, 0x0, 0x1, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:93 +0x4f6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00aeed000, 0x4a637e0, 0xc00f15ba40, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1316 +0x1a63
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00aeed000, 0x4a637e0, 0xc00d8af440, 0xc0003c2a00, 0x5400, 0x15000, 0xc0003c2a98, 0xc00aecce60, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1245 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc00078af00, 0x4a637e0, 0xc00d8af440, 0xc00aeed000, 0x5400, 0x15000, 0xc0003c2a98, 0xc00aecce60, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:452 +0x104
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00036c709, 0xc00aedb6e0, 0x4a637e0, 0xc00d8af440, 0xc00aecce60, 0xc00078af00, 0xc0006cc400, 0x4a7b1e0, 0xc00aedb6c0, 0xc0065b4ae0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:566 +0x2e8
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:498 +0x17e
```
I found this bug based on commit `afc1cb2923ec86cc274a0ef96b341d9fcbdd5b61`.

**Comment by otan** [comment]
This is seemingly because the `EvalContext.SessionData` is never initialised when a SCRUB command is called. Is this deliberate?

We could add a `if ctx.SessionData == nil { return UTC }` to `GetLocation()`, but having a nil `SessionData` breaks things like `cast` as well.
