### ISSUE TITLE
sql: crash creating temp dir

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#45031]
Encountered on a [TC run](https://teamcity.cockroachdb.com/viewLog.html?buildId=1746721&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test)

@asubiotto have you seen this before?

```
=== RUN   TestLogic/fakedist-vec/manual_retry/rename_savepoint
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f86f57a8c6a]

runtime stack:
runtime.throw(0x3af698e, 0x2a)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 4477710 [syscall]:
runtime.cgocall(0x2e32180, 0xc00e93cca8, 0x100)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc00e93cc60 sp=0xc00e93cc28 pc=0x65cdbb
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBEnvCreateDir(0x7f86e6e59790, 0xc016b91620, 0x24, 0x0, 0x0)
	_cgo_gotypes.go:587 +0x4d fp=0xc00e93cca8 sp=0xc00e93cc60 pc=0x2b4644d
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).CreateDir.func1(0xc006ecfe00, 0xc016b915f0, 0x24, 0x24, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:3485 +0xbd fp=0xc00e93cd00 sp=0xc00e93cca8 pc=0x2b66b7d
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).CreateDir(0xc006ecfe00, 0xc016b915f0, 0x24, 0xc016b915f0, 0x24)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:3485 +0x43 fp=0xc00e93cd48 sp=0xc00e93cd00 pc=0x2b5cd23
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Setup(0xc000e695c0, 0x424e6a0, 0xc010430600, 0xc00fea9b40, 0x424e600, 0xc01585ae40, 0xc0394fa900, 0x19437e4c715431ec, 0xeb060289b55fcab4)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:91 +0x3e3 fp=0xc00e93d0c0 sp=0xc00e93cd48 pc=0x27dc6e3
github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).setupFlow(0xc0394fa900, 0x424e6a0, 0xc01585ae40, 0x0, 0x0, 0xc0394faa80, 0xc00fea9b30, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:349 +0x5bb fp=0xc00e93d568 sp=0xc00e93d0c0 pc=0x27f2fbb
github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupFlow(0xc0394fa900, 0x424e6a0, 0xc010430570, 0xc00fea9b30, 0xc0394fa900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:517 +0x20b fp=0xc00e93d660 sp=0xc00e93d568 pc=0x27f50cb
github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler.func1(0x424e6a0, 0xc010430570, 0x3928840, 0xc00fea9b30, 0x3928840, 0xc00fea9b30, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:630 +0x86 fp=0xc00e93d6a8 sp=0xc00e93d660 pc=0x1aa6fd6
github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x424e6a0, 0xc010430570, 0x3928840, 0xc00fea9b30, 0xc031689620, 0xc031689660, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:44 +0x9ef fp=0xc00e93d948 sp=0xc00e93d6a8 pc=0x142f30f
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func2(0x424e6a0, 0xc010430570, 0x3928840, 0xc00fea9b30, 0xc031689620, 0xc031689660, 0x666a48, 0x20, 0x36b2320, 0xc00780b601)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:223 +0xb6 fp=0xc00e93d9b0 sp=0xc00e93d948 pc=0x143ea76
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func4(0x424e6a0, 0xc010430570, 0x3928840, 0xc00fea9b30, 0xc031689620, 0xc031689660, 0xc0043faa78, 0x7629b8, 0x3883b00, 0xc010430570)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:253 +0xac fp=0xc00e93da18 sp=0xc00e93d9b0 pc=0x143ed5c
github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler(0x39d66e0, 0xc0394fa900, 0x424e6a0, 0xc010430570, 0xc00780b680, 0xc0232c80c0, 0x424e6a0, 0xc010430570, 0xc010bd2c00, 0x293)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:632 +0x14b fp=0xc00e93da88 sp=0xc00e93da18 pc=0x1a248db
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc007ad1b00, 0x429e0a0, 0xc01b595080, 0xc010bae300, 0xc0234b1920, 0x6122080, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:999 +0x460 fp=0xc00e93de18 sp=0xc00e93da88 pc=0xcbd340
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc007ad1b00, 0x429e0a0, 0xc01b595080, 0xc010bae300, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1279 +0xd97 fp=0xc00e93df48 sp=0xc00e93de18 pc=0xcc1347
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0300a4930, 0xc007ad1b00, 0x429e0a0, 0xc01b595080, 0xc010bae300)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:717 +0xbb fp=0xc00e93dfb8 sp=0xc00e93df48 pc=0xccdcab
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00e93dfc0 sp=0xc00e93dfb8 pc=0x6b95c1
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:715 +0xa1
```

**Comment by asubiotto** [comment]
No, this is recent code. @sumeerbhola do you have any ideas how a segfault could happen when creating a directory through the rocksdb engine?

**Comment by sumeerbhola** [comment]
What are our typical tools to figure this out -- core files and some debugger? 
The 0x0 in the following look suspicious: `Cfunc_DBEnvCreateDir(0x7f86e6e59790, 0xc016b91620, 0x24, 0x0, 0x0)`
But I can't map that parameter list to `DBStatus DBEnvCreateDir(DBEngine* db, DBSlice name)` where DBSlice is a `char*`, `size_t`.

**Comment by petermattis** [comment]
If this can be reproduced, then you can add logging to figure out what is going on. `make stress` is your friend here. 

> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f86f57a8c6a]

I believe the `addr=0x10` means some sort of nil pointer dereference. That looks like some object is a nil pointer and we tried to dereference a field that is `0x10` offset within it. That might be enough to figure out what is going on by code inspection.

> github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBEnvCreateDir(0x7f86e6e59790, 0xc016b91620, 0x24, 0x0, 0x0)

The hex values map to 64-bit chunks of the parameters. So `0x7f86e6e59790` should be `DBEngine*`. `0xc016b91620` and `0x24` should be the pointer and length fields of the `DBSlice`. Nothing looks obviously wrong to my eyes. `make stress` is the path I'd take to try and reproduce the segfault.

**Comment by sumeerbhola** [comment]
This should be fixed by cockroachdb/rocksdb/pull/74
