### ISSUE TITLE
ccl/backupccl: TestBackupRestoreMultiNodeRemote failure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#45469]
Saw this failure on CI which I'm pretty sure was unrelated to my PR (bumping a vendored dependency). https://teamcity.cockroachdb.com/viewLog.html?buildId=1768926&buildTypeId=Cockroach_UnitTests:

```
panic: interface conversion: jobspb.isPayload_Details is *jobspb.Payload_CreateStats, not *jobspb.Payload_Backup [recovered]
	panic: interface conversion: jobspb.isPayload_Details is *jobspb.Payload_CreateStats, not *jobspb.Payload_Backup [recovered]
	panic: interface conversion: jobspb.isPayload_Details is *jobspb.Payload_CreateStats, not *jobspb.Payload_Backup

goroutine 13422 [running]:
testing.tRunner.func1(0xc004734a00)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x3910540, 0xc001d8b260)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/util/leaktest.AfterTest.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/leaktest/leaktest.go:98 +0x210
panic(0x3910540, 0xc001d8b260)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/ccl/backupccl_test.backupAndRestore(0x45ba560, 0xc000074130, 0xc004734a00, 0xc001912070, 0xc000415c40, 0x1, 0x1, 0xc000415c70, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_test.go:567 +0x1754
github.com/cockroachdb/cockroach/pkg/ccl/backupccl_test.TestBackupRestoreMultiNodeRemote(0xc004734a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_test.go:323 +0x1e1
testing.tRunner(0xc004734a00, 0x3f22688)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
```

**Comment by dt** [comment]
#45369
