### ISSUE TITLE
Cockroach panics when passing int64 arg using github.com/lib/pq driver

### ISSUE THREAD

**Issue by unstppbl** [cockroachdb/cockroach#45925]
**Describe the problem**

Cockroach panics when passing int64 arg using github.com/lib/pq driver
```
panic: runtime error: index out of range [7] with length 4 [recovered]
	panic: runtime error: index out of range [7] with length 4

goroutine 1 [running]:
github.com/lib/pq.(*conn).errRecover(0xc0000a4000, 0xc0000abd20)
	/go/src/github.com/lib/pq/error.go:488 +0x41c
panic(0x6724a0, 0xc000148000)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
encoding/binary.bigEndian.Uint64(...)
	/usr/local/go/src/encoding/binary/binary.go:124
github.com/lib/pq.binaryDecode(0xc0000a4258, 0xc0000a4026, 0x4, 0x1fa, 0x14, 0x0, 0xc0000abbe8)
	/go/src/github.com/lib/pq/encode.go:74 +0x229
github.com/lib/pq.decode(0xc0000a4258, 0xc0000a4026, 0x4, 0x1fa, 0x14, 0x1, 0xc0000abc90, 0x7f884b9fa060)
	/go/src/github.com/lib/pq/encode.go:61 +0x69
github.com/lib/pq.(*rows).Next(0xc000140000, 0xc000146000, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/lib/pq/conn.go:1473 +0x3ff
database/sql.(*Rows).nextLocked(0xc000142000, 0x420000)
	/usr/local/go/src/database/sql/sql.go:2767 +0xd5
database/sql.(*Rows).Next.func1()
	/usr/local/go/src/database/sql/sql.go:2745 +0x3c
database/sql.withLock(0x6e1c20, 0xc000142030, 0xc0000abe30)
	/usr/local/go/src/database/sql/sql.go:3184 +0x6d
database/sql.(*Rows).Next(0xc000142000, 0x65a180)
	/usr/local/go/src/database/sql/sql.go:2744 +0x87
database/sql.(*Row).Scan(0xc000144000, 0xc0000abf40, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:3129 +0x110
main.main()
	/home/test.go:38 +0x148
exit status 2
```

**To Reproduce**
Just create a table with similar data

```golang
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/lib/pq"
)

func main() {
	db, err := initdb()
	if err != nil {
		log.Fatal(err)
	}
	var interval int64
	idObject := int64(536022077707485185)
	if err := db.QueryRow(`SELECT MIN (interval) FROM configs WHERE id_object = $1`, idObject).Scan(&interval); err != nil {
		log.Fatal(err)
	}
	log.Printf("MIN INTERVAL: %+v", interval)
}

func initdb() (db *sql.DB, err error) {
	dbinfo := "host=localhost port=26257 user=root password=password dbname=test sslmode=disable"
	db, err = sql.Open("postgres", dbinfo)
	if err != nil {
		return nil, fmt.Errorf("Unable to connect to database: %s", err)
	}
	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("Unable ping database: %s", err)
	}
	return db, nil
}

```

**Expected behavior**
Return the min value

**Additional info**

Panicking line: https://github.com/lib/pq/blob/master/encode.go#L74

**Comment by rafiss** [comment]
What is the schema of the `configs` table in this example?

**Comment by rafiss** [comment]
I created the following schema, and ran the attached code, and did not reproduce the error. I'm using CockroachDB v20.1 and lib/pq v1.3.0

```
root@:26257/test> create table configs(id_object int primary key, interval int);
CREATE TABLE

root@:26257/test> insert into configs values (1,2);
INSERT 1

root@:26257/test> insert into configs values (536022077707485185,2);
INSERT 1
```

I'm going to close this, but if you still have an issue, please re-open and let us know.
