### ISSUE TITLE
server: job status endpoint crashes node

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#46049]
I noticed some funky jobs on the UI and tried to test out the debug endpoint to get more details but attempting to load it crashed the node. Looking at the logs:

```
panic: attempt to clone *jobspb.Payload, which contains uncloneable field of type jobspb.isPayload_Details

goroutine 870200 [running]:
panic(0x3c74880, 0xc09f0c01d0)
        /usr/local/go/src/runtime/panic.go:722 +0x2c2 fp=0xc000c79590 sp=0xc000c79500 pc=0x79a3d2
github.com/cockroachdb/cockroach/pkg/util/protoutil.Clone(0x4ba0960, 0xc00eb78800, 0xc000c795f0, 0xc000c795e8)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/protoutil/clone.go:77 +0x173 fp=0xc000c795f8 sp=0xc000c79590 pc=0xf91563
github.com/cockroachdb/cockroach/pkg/jobs.(*Job).ToProto(0xc00eb787e0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:575 +0xc3 fp=0xc000c79670 sp=0xc000c795f8 pc=0x16fb753
github.com/cockroachdb/cockroach/pkg/server.(*statusServer).JobStatus(0xc00028d6c0, 0x4b67ae0, 0xc05cc554a0, 0xc0928ac0e0, 0xc00028d6c0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:2072 +0xf7 fp=0xc000c796c8 sp=0xc000c79670 pc=0x30580d7
github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_JobStatus_Handler.func1(0x4b67ae0, 0xc05cc554a0, 0x4111980, 0xc0928ac0e0, 0x4111980, 0xc0928ac0e0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:4470 +0x89 fp=0xc000c79710 sp=0xc000c796c8 pc=0x22499a9
github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x4b67ae0, 0xc05cc554a0, 0x4111980, 0xc0928ac0e0, 0xc04197c5e0, 0xc04197c600, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:44 +0x9ef fp=0xc000c799b0 sp=0xc000c79710 pc=0x15aebff
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func2(0x4b67ae0, 0xc05cc554a0, 0x4111980, 0xc0928ac0e0, 0xc04197c5e0, 0xc04197c600, 0xc0005f6a78, 0x95fe18, 0x405ffc0, 0xc05cc554a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:223 +0xb6 fp=0xc000c79a18 sp=0xc000c799b0 pc=0x15be386
github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_JobStatus_Handler(0x427e280, 0xc00028d6c0, 0x4b67ae0, 0xc05cc554a0, 0xc0746c01e0, 0xc00032c220, 0x4b67ae0, 0xc05cc554a0, 0xc0928ac0a6, 0xa)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:4472 +0x14b fp=0xc000c79a88 sp=0xc000c79a18 pc=0x21dca3b
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008a2300, 0x4bc17e0, 0xc000796180, 0xc000502300, 0xc000601b60, 0x6dfb380, 0x0, 0x0, 0x0)
```

The job in question was `537299064518082561`. debug.zip too large to be attached, but I grabbed its [system.jobs.txt](https://github.com/cockroachdb/cockroach/files/4326204/system.jobs.txt) and this is from master so it includes the hex repr (this can be a chance to verify that that works for debugging such an issue).

**Comment by pbardea** [comment]
Saw this issue in passing and wanted to add a bit of context. The jobs payload was made uncloneable by #44739 when the protected timestamp record uuid was introduced into the jobs details. This was so the protobuf could be fuzzed on test race. `MaybeFuzz` may be a good place  to start looking for usage uncloneable and how it handles uncloneable types.

**Comment by spaskob** [comment]
Thank you both! Looking t this right now.

**Comment by spaskob** [comment]
I just discussed this with @ajwerner and he has a nice idea to have a `ImmutableJob` which has only accessors that is embedded in `Job` and then have another method `LoadImmutableJob` on `Job` that calls `LoadJob` and just pops the immutable part out the `Job` struct so that it can be safely used to copy fields like `Payload` without cloning. I want to get this into 20.1 - should be a small change.

Thoughts?

**Comment by ajwerner** [comment]
I would not block the fixing of this on the API refactor.

**Comment by spaskob** [comment]
I was able to repro the failure with a unit test and have a half-baked PR. It will be ready for review tomorrow morning.
