### ISSUE TITLE
build: `build/builder.sh mkrelease` node-related failure

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#46209]
I'm seeing the following `builder.sh` failure.

```
$ git show HEAD --oneline
d0bc686d6a (HEAD -> 200317.scaledata-flake, upstream/master, master) Merge pull request #45639 from elkmaster/feature/debug-page

$ git status
On branch 200317.scaledata-flake
nothing to commit, working tree clean

$ build/builder.sh mkrelease
+ CGO_ENABLED=1
+ make BUILDTYPE=release XGOOS=linux XGOARCH=amd64 XCMAKE_SYSTEM_NAME=Linux TARGET_TRIPLE=x86_64-unknown-linux-gnu 'LDFLAGS=-static-libgcc -static-libstdc++' SUFFIX=-linux-2.6.32-gnu-amd64
Running make with -j12
GOPATH set to /go
[  1%] Built target js_embed
[ 47%] Built target libprotobuf
[ 97%] Built target libprotoc
[100%] Built target protoc
find pkg/ui/distccl -mindepth 1 -not -name distccl.go -delete
set -e; shopt -s extglob; for dll in protos.ccl.dll.js vendor.oss.dll.js; do \
  ln -s ../dist/$dll pkg/ui/distccl/${dll/@(.ccl|.oss)}; \
done
build/node-run.sh -C pkg/ui ./node_modules/.bin/webpack --config webpack.app.js --env.dist=ccl
make  all-am
make[2]: Nothing to be done for 'all-am'.
make[1]: Nothing to be done for 'build_lib_static'.
(node:148) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

ERROR in ./src/index.tsx
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Cannot find module 'chalk'
Require stack:
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/ts-loader/dist/instances.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/ts-loader/dist/index.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/ts-loader/index.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/loadLoader.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/LoaderRunner.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/webpack/lib/NormalModule.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/webpack/lib/NormalModuleFactory.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/webpack/lib/Compiler.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/webpack/lib/webpack.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/webpack-cli/bin/utils/validate-options.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/webpack-cli/bin/utils/convert-argv.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/webpack-cli/bin/cli.js
- /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/ts-loader/dist/instances.js:3:17)
    at Module._compile (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/ts-loader/dist/index.js:5:21)
    at Module._compile (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/ts-loader/index.js:1:76)
    at Module._compile (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at loadLoader (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/loadLoader.js:18:17)
    at iteratePitchingLoaders (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/LoaderRunner.js:188:6
    at context.callback (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/cache-loader/dist/index.js:176:7
    at ReadFileContext.callback (/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/cache-loader/dist/index.js:274:7)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13)
 @ multi ./src/index.tsx main[0]
Makefile:1360: recipe for target 'pkg/ui/distccl/bindata.go' failed
make: *** [pkg/ui/distccl/bindata.go] Error 2
```

**Comment by irfansharif** [comment]
Ran into the same thing after a `make clean` as well.

**Comment by irfansharif** [comment]
Not seeing it anymore updating to `master` at the time.

```
$ git show HEAD --one-line
aa18c27ce7 (HEAD -> 200317.scaledata-flake, upstream/master, master) Merge #45906
```

**Comment by irfansharif** [comment]
I'm closing the issue, but +cc @dhartunian if you have any ideas what caused this, and whether this should have been caught in our build system somehow.

**Comment by dhartunian** [comment]
Interesting @irfansharif. This is a new one that I haven't seen before. Agree that this kind of issue shouldn't pass CI. I checked the `chalk` dependency specifically and its version hasn't changed in months.

We're tracking build improvements in the Makefile for the JS side in #45222
