### ISSUE TITLE
circleci: failed tests (13387): Example_basic

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4634]
The following test appears to have failed:

[#13387](https://circleci.com/gh/cockroachdb/cockroach/13387):

```
E160225 06:06:08.007318 storage/queue.go:143  [raftlog] range=1 [/Min-/Max): error: failed to send RPC: too many errors encountered (1 of 1 total): kv/send.go:286: rpc to Node.Batch: client not ready after 5s
E160225 06:06:08.014421 server/server.go:369  failed to send RPC: too many errors encountered (1 of 1 total): kv/send.go:286: rpc to Node.Batch: client not ready after 5s
E160225 06:06:09.191708 rpc/client.go:328  dial tcp 127.0.0.1:54013: getsockopt: connection refused
E160225 06:06:13.007539 client/txn.go:328  failure aborting transaction: failed to send RPC: too many errors encountered (1 of 1 total): kv/send.go:286: rpc to Node.Batch: client not ready after 5s; abort caused by: failed to send RPC: too many errors encountered (1 of 1 total): kv/send.go:286: rpc to Node.Batch: client not ready after 5s
E160225 06:06:13.009454 storage/queue.go:143  [split] range=1 [/Min-/Max): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Max) at key "/Table/11/0": storage/replica_command.go:1395: split at key /Table/11 failed: failed to send RPC: too many errors encountered (1 of 1 total): kv/send.go:286: rpc to Node.Batch: client not ready after 5s
F160225 06:06:13.012977 cli/cli_test.go:64  Could not start server: server/testserver.go:259: had 1 ranges at startup, expected 4
goroutine 1 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xece609001, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:843 +0xcf
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x2a42cc0, 0x3, 0x23f12ae, 0xf, 0x40, 0xc820376fc0, 0x55)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:710 +0x178
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x1bfbf60, 0x1a, 0xc8207f1988, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0x10a
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0xc800000003, 0x1bfbf60, 0x1a, 0xc8207f1988, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x8d
github.com/cockroachdb/cockroach/util/log.Fatalf(0x1bfbf60, 0x1a, 0xc8207f1988, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x74
--
github.com/cockroachdb/cockroach/cli_test.TestMain(0xc8207f1ee0)
	/go/src/github.com/cockroachdb/cockroach/cli/main_test.go:34 +0x2f
main.main()
	github.com/cockroachdb/cockroach/cli/_test/_testmain.go:92 +0x20b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2a42cc0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:985 +0x76
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:583 +0x117

goroutine 21 [syscall]:
os/signal.signal_recv(0x62a601)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x26
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x45

goroutine 669 [syscall]:
syscall.Syscall(0x0, 0x4, 0xc8208e8000, 0x200, 0x7fbdfca6d9c8, 0x61ce20, 0x62b2e4)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x4, 0xc8208e8000, 0x200, 0x200, 0x5d97e9, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x6d
syscall.Read(0x4, 0xc8208e8000, 0x200, 0x200, 0x1f45650, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:161 +0x5f
os.(*File).read(0xc820080018, 0xc8208e8000, 0x200, 0x200, 0x200, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:228 +0x8a
os.(*File).Read(0xc820080018, 0xc8208e8000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0xbd
--
testing.runExample.func1(0xc820080018, 0xc82005c180)
	/usr/local/go/src/testing/example.go:60 +0xf2
created by testing.runExample
	/usr/local/go/src/testing/example.go:67 +0x3a2

goroutine 692 [runnable]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8203abae0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:123 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:124 +0x6f8
clog: Flush took longer than 10s
FAIL	github.com/cockroachdb/cockroach/cli	65.325s
=== RUN   TestClientTxnSequenceNumber
--- PASS: TestClientTxnSequenceNumber (0.02s)
=== RUN   TestTxnRequestTxnTimestamp
--- PASS: TestTxnRequestTxnTimestamp (0.00s)
=== RUN   TestTxnResetTxnOnAbort
--- PASS: TestTxnResetTxnOnAbort (0.01s)
=== RUN   TestTransactionConfig
--- PASS: TestTransactionConfig (0.01s)
=== RUN   TestCommitReadOnlyTransaction
--- PASS: TestCommitReadOnlyTransaction (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
#4693 might have fixed this, closing for now.
