### ISSUE TITLE
circleci: failed tests (13401): TestDockerPHP TestPut 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4643]
The following test appears to have failed:

[#13401](https://circleci.com/gh/cockroachdb/cockroach/13401):

```
  trace: https://0.0.0.0:32801/debug/requests
  logs:  /tmp/circle-artifacts.y4mPbw8/acceptance/testDocker/roach2.local/cockroach.INFO
  pprof: docker exec -it 9d7a4 /bin/bash -c 'go tool pprof /cockroach <(wget --no-check-certificate -qO- https://$(hostname):26257/debug/pprof/heap)'
I160225 16:16:08.343885 acceptance/replication_test.go:50  waiting for first range to have 3 replicas
I160225 16:16:30.906485 acceptance/replication_test.go:66  found 2 replicas
--- FAIL: TestDockerPHP (46.48s)
	testing.go:169: acceptance/replication_test.go:72: condition failed to evaluate within 20s: expected 3 replicas, only found 2
=== RUN   TestPut
I160225 16:16:30.906859 acceptance/cluster/docker.go:72  ImagePull cockroachdb/docker-spy:20160209-143235 starting
I160225 16:16:31.309064 acceptance/cluster/docker.go:87  ImagePull cockroachdb/docker-spy:20160209-143235 complete
I160225 16:16:31.311172 acceptance/cluster/localcluster.go:606  stopping
--- FAIL: TestPut (0.41s)
panic: Error response from daemon: Conflict. The name "docker-spy" is already in use by container 7b11b92dca9b. You have to delete (or rename) that container to be able to reuse that name. [recovered]
	panic: Error response from daemon: Conflict. The name "docker-spy" is already in use by container 7b11b92dca9b. You have to delete (or rename) that container to be able to reuse that name. [recovered]
	panic: Error response from daemon: Conflict. The name "docker-spy" is already in use by container 7b11b92dca9b. You have to delete (or rename) that container to be able to reuse that name.

goroutine 927 [running]:
testing.tRunner.func1(0xc82035a990)
	/usr/local/go/src/testing/testing.go:467 +0x192
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).stopOnPanic(0xc8200605b0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:218 +0x9b
github.com/cockroachdb/cockroach/acceptance/cluster.maybePanic(0x7f6293118028, 0xc820308080)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/docker.go:114 +0x4b
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).runDockerSpy(0xc8200605b0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:256 +0x2ca
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start(0xc8200605b0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:540 +0xbf
--
testing.tRunner(0xc82035a990, 0x12b3be0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 1 [chan receive]:
testing.RunTests(0xe2a540, 0x12b3b20, 0xf, 0xf, 0xcbf92c47eb380d00)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc82025fef8, 0xe29938)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc82025fef8)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:48 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:80 +0x114

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x12d0260)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:985 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:583 +0xbc

goroutine 6 [select, 2 minutes, locked to thread]:
runtime.gopark(0xe2ad58, 0xc820022f28, 0xcc1058, 0x6, 0xc820092718, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820022f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820022f28)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 23 [syscall, 2 minutes]:
os/signal.signal_recv(0x6)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 24 [chan receive, 2 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:39 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:47 +0x30

goroutine 28 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f62930e3cd8, 0x72, 0xc8201e7000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82020a1b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020a1b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020a150, 0xc8201e7000, 0x1000, 0x1000, 0x0, 0x7f6293118050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820098350, 0xc8201e7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201ced00)
	/usr/local/go/src/net/http/transport.go:1053 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:837 +0x10a6

goroutine 29 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc8201ced00)
	/usr/local/go/src/net/http/transport.go:1257 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:838 +0x10cb

goroutine 152 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f62930e39d8, 0x72, 0xc82020d000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82020a7d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020a7d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020a770, 0xc82020d000, 0x1000, 0x1000, 0x0, 0x7f6293118050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820098030, 0xc82020d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201cea90)
	/usr/local/go/src/net/http/transport.go:1053 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:837 +0x10a6

goroutine 378 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f62930e3b58, 0x72, 0xc820488000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82020a990, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020a990, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020a930, 0xc820488000, 0x1000, 0x1000, 0x0, 0x7f6293118050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820098028, 0xc820488000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200a05b0)
	/usr/local/go/src/net/http/transport.go:1053 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:837 +0x10a6

goroutine 946 [IO wait]:
net.runtime_pollWait(0x7f62930e3558, 0x72, 0xc8203b9000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820056450, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820056450, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200563f0, 0xc8203b9000, 0x1000, 0x1000, 0x0, 0x7f6293118050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a260, 0xc8203b9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200608f0)
	/usr/local/go/src/net/http/transport.go:1053 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:837 +0x10a6

goroutine 153 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc8201cea90)
	/usr/local/go/src/net/http/transport.go:1257 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:838 +0x10cb

goroutine 773 [IO wait]:
net.runtime_pollWait(0x7f62930e3918, 0x72, 0xc8204bc000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82020aa00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020aa00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020a9a0, 0xc8204bc000, 0x1000, 0x1000, 0x0, 0x7f6293118050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820098050, 0xc8204bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201cf1e0)
	/usr/local/go/src/net/http/transport.go:1053 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:837 +0x10a6

goroutine 904 [select]:
net/http.(*persistConn).readLoop(0xc820060c30)
	/usr/local/go/src/net/http/transport.go:1162 +0xd52
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:837 +0x10a6

goroutine 905 [select]:
net/http.(*persistConn).writeLoop(0xc820060c30)
	/usr/local/go/src/net/http/transport.go:1257 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:838 +0x10cb

goroutine 879 [select]:
net/http.(*persistConn).writeLoop(0xc8200604e0)
	/usr/local/go/src/net/http/transport.go:1257 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:838 +0x10cb

goroutine 652 [select]:
net/http.(*persistConn).writeLoop(0xc8201ce5b0)
	/usr/local/go/src/net/http/transport.go:1257 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:838 +0x10cb

goroutine 255 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8201ceb60)
	/usr/local/go/src/net/http/transport.go:1257 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:838 +0x10cb

goroutine 254 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f62930e3a98, 0x72, 0xc8204be000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82020ad10, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020ad10, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020acb0, 0xc8204be000, 0x1000, 0x1000, 0x0, 0x7f6293118050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a048, 0xc8204be000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201ceb60)
	/usr/local/go/src/net/http/transport.go:1053 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:837 +0x10a6

goroutine 379 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8200a05b0)
	/usr/local/go/src/net/http/transport.go:1257 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:838 +0x10cb

goroutine 878 [IO wait]:
net.runtime_pollWait(0x7f62930e3c18, 0x72, 0xc8202b4000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82020afb0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020afb0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020af50, 0xc8202b4000, 0x1000, 0x1000, 0x0, 0x7f6293118050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200982a8, 0xc8202b4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200604e0)
	/usr/local/go/src/net/http/transport.go:1053 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:837 +0x10a6

goroutine 651 [IO wait]:
net.runtime_pollWait(0x7f62930e3858, 0x72, 0xc820304000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82020a920, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020a920, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020a8c0, 0xc820304000, 0x1000, 0x1000, 0x0, 0x7f6293118050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a040, 0xc820304000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201ce5b0)
	/usr/local/go/src/net/http/transport.go:1053 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:837 +0x10a6

goroutine 900 [IO wait]:
net.runtime_pollWait(0x7f62930e36d8, 0x72, 0xc820311000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202c0ed0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202c0ed0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202c0e70, 0xc820311000, 0x1000, 0x1000, 0x0, 0x7f6293118050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200982d0, 0xc820311000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).monitor(0xc820060270)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:514 +0x218
created by github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:548 +0x3b3

goroutine 545 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f62930e3798, 0x72, 0xc82036d000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82020a3e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020a3e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020a380, 0xc82036d000, 0x1000, 0x1000, 0x0, 0x7f6293118050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820098038, 0xc82036d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200a0750)
	/usr/local/go/src/net/http/transport.go:1053 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:837 +0x10a6

goroutine 906 [select]:
github.com/docker/engine-api/client/transport/cancellable.Do.func3(0x7f62930ef2f0, 0xc8202b8380, 0xc8200159b0, 0xc8202bac60)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:78 +0xef
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:84 +0x336

goroutine 546 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8200a0750)
	/usr/local/go/src/net/http/transport.go:1257 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:838 +0x10cb

goroutine 938 [runnable]:
github.com/docker/engine-api/client/transport/cancellable.Do.func3(0x7f62930e2b88, 0xc820014d88, 0xc820015120, 0xc820092600)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:77
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:84 +0x336

goroutine 774 [select]:
net/http.(*persistConn).writeLoop(0xc8201cf1e0)
	/usr/local/go/src/net/http/transport.go:1257 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:838 +0x10cb

goroutine 947 [select]:
net/http.(*persistConn).writeLoop(0xc8200608f0)
	/usr/local/go/src/net/http/transport.go:1257 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:838 +0x10cb
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
#4693 might have fixed this, closing for now.
