### ISSUE TITLE
sql: no bytes in account to release

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#46788]
From a CI failure that is unrelated to the PR it occurred on: https://teamcity.cockroachdb.com/viewLog.html?buildId=1815818&buildTypeId=Cockroach_UnitTests

```
=== RUN   TestLogic/fakedist-disk/alter_table/regression_qualification_feature_counts
panic: hash-router-[3,8,13]: no bytes in account to release, current 284, free 441 [recovered]
	panic: hash-router-[3,8,13]: no bytes in account to release, current 284, free 441

goroutine 9431260 [running]:
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror.CatchVectorizedRuntimeError.func1(0xc067fb7cf8)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:62 +0x566
panic(0x34f2020, 0xc025a59d50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink(0xc073cb77e0, 0x426fda0, 0xc05490c5c0, 0x1b9)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:568 +0x1a9
github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Close(0xc05386dc20, 0x426fda0, 0xc05490c5c0, 0xc040ee0b80, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:428 +0x23d
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*spillingQueue).close(0xc05006d680, 0x426fda0, 0xc05490c5c0, 0xc0070bed80, 0x3c0cdd8)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/spilling_queue.go:263 +0x73
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).closeLocked(0xc04b0db950, 0x426fda0, 0xc05490c5c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:225 +0x4b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).Next(0xc04b0db950, 0x426fda0, 0xc05490c5c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:218 +0x23b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*deselectorOp).Next(0xc02c129950, 0x426fda0, 0xc05490c5c0, 0x68f7ea, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/deselector.go:51 +0x73
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).sendBatches.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:220 +0x5f
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror.CatchVectorizedRuntimeError(0xc067fb7da0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:95 +0x5f
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).sendBatches(0xc04b0dbc20, 0x426fe60, 0xc05112e300, 0x7f9765f95738, 0xc025a59cd0, 0xc04c5cda00, 0xc04b0dbc20, 0xc027a16a20, 0x66b625)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:227 +0xbb
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).runWithStream(0xc04b0dbc20, 0x426fe60, 0xc05112e300, 0x7f9765f95738, 0xc025a59cd0, 0xc04c5cda00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:307 +0x104
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).Run(0xc04b0dbc20, 0x426fda0, 0xc05490c5c0, 0x41f86a0, 0xc089a1efa0, 0x926dc36c00000002, 0xe034ec842d44e93c, 0xfe12dd55, 0xd, 0xc04c5cda00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:167 +0x586
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRemoteOutputStream.func1(0x426fda0, 0xc05490c5c0, 0xc04c5cda00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:544 +0x9a
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1(0xc073cb7aa0, 0x426fda0, 0xc05490c5c0, 0xc04c5cda00, 0xc03e989e10)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1090 +0x44
created by github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1089 +0x6f
```

Sending to @asubiotto for triage as I see something about vectorized execution in the stack trace.

**Comment by yuzefovich** [comment]
We have fixed a couple of issues like this, I think probably a rebase onto current `master` should be sufficient.
