### ISSUE TITLE
sql: server panics during Walk of `UPDATE` with placeholders in CASE.

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#4691]
Running the bank example over pg_wire causes server to die:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x78 pc=0x4676b9e]

goroutine 92 [running]:
panic(0x501f780, 0xc8200100f0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql/parser.MapArgs.SetInferredType(0xc820d246c0, 0x791ecd0, 0xc8207f4d80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/david/code/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:745 +0x19e
github.com/cockroachdb/cockroach/sql/parser.(*CaseExpr).TypeCheck(0xc82097ae40, 0xc820d246c0, 0x0, 0x0, 0x0, 0x0)
	/Users/david/code/go/src/github.com/cockroachdb/cockroach/sql/parser/type_check.go:129 +0x6aa
github.com/cockroachdb/cockroach/sql.(*planner).Update(0xc820140000, 0xc820d51130, 0x5f331e00, 0x0, 0x0, 0xc800000001)
	/Users/david/code/go/src/github.com/cockroachdb/cockroach/sql/update.go:161 +0x1767
```

**Comment by petermattis** [comment]
That's weird. I thought @mjibson fixed this when I changed `BenchmarkBank` to use pgwire.

**Comment by dt** [comment]
Looks like difference is bank example does `$3` vs bank bench which does `x+$3`. I'll bet a cast fixes it.

**Comment by dt** [comment]
repro: https://github.com/dt/cockroach/commit/73e11a21780bc0fdf1183f0e89adf237dda07aff

**Comment by dt** [comment]
`CaseExpr.TypeCheck` is passing a nil `dummyVal` to `SetInferredType` if there's no `Else` clause. I'm not quite sure what the intent here was though.
