### ISSUE TITLE
backupccl: TestProtectedTimestampsDuringBackup is flaky on master

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#47522]
On 82294d100ad1cb26b488f53e7241242d474d58d7, I ran
```
roachprod create lucy-stress
make roachprod-stress CLUSTER=lucy-stress STRESSFLAGS='-p 16' PKG=./pkg/ccl/backupccl TESTS=TestProtectedTimestampsDuringBackup
```
 and got this failure within a few hundred runs:
```
--- FAIL: TestProtectedTimestampsDuringBackup (57.99s)
    backup_test.go:3673: condition failed to evaluate within 45s: expected (?s)shouldQueue=true.*processing replica.*GC score after GC in trace:      0.000ms      0.000ms    === operation:manual gc queue run node:1 range:33/1:/{Table/52-Max} store:1 unfinished:
             0.012ms      0.012ms    event:[n1,s1,r33/1:/{Table/52-Max}] running gc.shouldQueue
             0.038ms      0.026ms    event:[n1,s1,r33/1:/{Table/52-Max}] shouldQueue=false, priority=0.000318


        goroutine 45 [running]:
        runtime/debug.Stack(0xc0041d3c60, 0x481bc60, 0xc002b13930)
                /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x4913400, 0xc0005c5100, 0xc0041d3c60)
                /go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:37 +0x6b
        github.com/cockroachdb/cockroach/pkg/ccl/backupccl_test.TestProtectedTimestampsDuringBackup(0xc0005c5100)
                /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_test.go:3673 +0x802
        testing.tRunner(0xc0005c5100, 0x41d5550)
                /usr/local/go/src/testing/testing.go:909 +0xc9
        created by testing.(*T).Run
                /usr/local/go/src/testing/testing.go:960 +0x350
```
Full logs: [out.1586960612.gz](https://github.com/cockroachdb/cockroach/files/4481811/out.1586960612.gz)

**Comment by lucy-zhang** [comment]
I think this is a different failure than #45932.
