### ISSUE TITLE
sql: TestMigrateSchemaChanges/drop-table-blocked-at-after-reversing-mutations-canceled is flaky

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#47532]
On 82294d100ad1cb26b488f53e7241242d474d58d7, running
```
make roachprod-stress CLUSTER=lucy-stress STRESSFLAGS='-p 16' PKG=./pkg/sql TESTS=TestMigrateSchemaChanges
```
produces
```
    --- FAIL: TestMigrateSchemaChanges/drop-table-blocked-at-after-reversing-mutations-canceled (48.59s)
        schema_change_migrations_test.go:202: condition failed to evaluate within 45s: query 'SELECT * FROM [SHOW JOBS] WHERE (job_type = 'SCHEMA CHANGE' OR job_type = 'SCHEMA CHANGE GC') AND NOT (status = 'succeeded' OR status = 'canceled')': expected:

            got:
            546898560510820353, SCHEMA CHANGE, DROP TABLE t.public.test, , root, failed, NULL, 2020-04-15 17:09:55.405294 +0000 +0000, 2020-04-15 17:09:55.519922 +0000 +0000, 2020-04-15 17:09:56.827307 +0000 +0000, 2020-04-15 17:09:56.353098 +0000 +0000, 0, job 546898560510820353: cannot be reverted, manual cleanup may be required: job canceled by user, 2


            goroutine 84664 [running]:
            runtime/debug.Stack(0xc005ef9ce0, 0x46c6160, 0xc008db9460)
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
            github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x47b8960, 0xc006f49b00, 0xc005ef9ce0)
            	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:37 +0x6b
            github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).CheckQueryResultsRetry(0xc00415ba30, 0x47b8960, 0xc006f49b00, 0x3fbeeff, 0x93, 0x6b07f10, 0x0, 0x0)
            	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:199 +0xde
            github.com/cockroachdb/cockroach/pkg/sql_test.testSchemaChangeMigrations(0xc006f49b00, 0x2, 0x1, 0x7, 0x3efbc7e, 0x18)
            	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_change_migrations_test.go:202 +0x71b
            github.com/cockroachdb/cockroach/pkg/sql_test.TestMigrateSchemaChanges.func1(0xc006f49b00)
            	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_change_migrations_test.go:846 +0x92
            testing.tRunner(0xc006f49b00, 0xc00de56e40)
            	/usr/local/go/src/testing/testing.go:909 +0xc9
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:960 +0x350
```
This took about half an hour and ~700 runs. It'll be faster to reproduce without running the other subtests.

This seems to be fallout from #47446, which is uncovering a pre-existing problem with the tests (and probably doesn't reflect a problem with #47446 itself). The problem is that we were expecting a canceled job, but in some cases rolling back the job was failing. This error would have been swallowed before #47446, but now it's getting propagated properly and causing the job to be failed instead of canceled.

Full logs: [out.1586968821.gz](https://github.com/cockroachdb/cockroach/files/4482737/out.1586968821.gz)

**Comment by lucy-zhang** [comment]
I have not been able to reproduce this with the logging turned on over several thousand runs (and isolating the particular subtest didn't help; I think the presence of the other subtests slows everything down, or something).

What this subtest is doing is the following:
1. Start dropping a table.
2. From inside a testing knob, cancel the job after names have been drained and we've created a GC job but before the job resumer has completed.
3. Once the job has been canceled and enters `OnFailOrCancel`, rewrite the table descriptor and job from inside a testing knob to mimic what they would be in 19.2, and then return a retry error to exit `OnFailOrCancel`.
4. Run the job migration to upgrade the job to the 20.1 format.
5. Let the job run to completion (i.e., finish running `OnFailOrCancel`) and verify that it ends up in the `canceled` state.

The failures are coming from OnFailOrCancel returning a non-retriable error, causing the job to end up as `canceled`:
```
I200415 17:09:56.775672 86998 jobs/registry.go:803  [n2] job 546898560510820353: stepping through state failed with error job 546898560510820353: cannot be reverted, manual cleanup may be required: job canceled by user
```
I was originally speculating that this was caused by the GC job completing before we got to this point (which, unfortunately, is possible due to the fact that we don't mark the job as done and start the GC job in the same transaction or capture this dependency in any other way), but after adding some sleeps to encourage this to happen, I verified that we do handle this correctly and gracefully exit the original job. So it's not that.

**Comment by lucy-zhang** [comment]
I suspect I know why `job canceled by user` is getting returned from `OnFailOrCancel` (which is what that log message is indicating, and definitely should not be possible). It's because I returned the wrong error here:
https://github.com/cockroachdb/cockroach/pull/47446/files#diff-69eed08e8c77d1724a12ac0b0de73912R639
That should be `errReverse`, not `err`.

**Comment by lucy-zhang** [comment]
I've confirmed that the problem is the wrong error being returned. It turns out we were returning `ErrDescriptorNotFound` from `maybeReverseMutations`, which, if correctly returned, would have just caused `OnFailOrCancel` to return a nil error.

(It's still not great that we can have the GC job start and finish before the original schema change job has finished, but at least all the important operations are still happening in the right order; you can't start a GC job until you've finished draining names.)

Somewhat surprisingly, I haven't gotten any test failures out of stressing the logic tests or the tests in schema_changer_test.go (after ~1500 runs for the former and ~400 for the latter). I would have expected problems from the table descriptors accumulating abandoned, partially completed mutations, but I guess we don't explicitly test for that, and it's possible for there to be no obvious user-visible effects aside from seeing the error in the jobs table.
