### ISSUE TITLE
ui: the new "cypress" dependency breaks the build

### ISSUE THREAD

**Issue by bra-fsn** [cockroachdb/cockroach#47666]
**Describe the problem**

When trying to build cockroachdb@6bdfc9953e82320f05400ed216825522928f2b2e (master), I get this error:

```
[5/5] Building fresh packages...
error /home/bra/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /home/bra/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/cypress
Output:
/home/bra/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/cypress/lib/tasks/state.js:40
      throw new Error('Platform: "' + platform + '" is not supported.');
      ^

Error: Platform: "freebsd" is not supported.
    at getPlatFormBinaryFolder (/home/bra/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/cypress/lib/tasks/state.js:40:13)
    at Object.getBinaryDir (/home/bra/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/cypress/lib/tasks/state.js:66:44)
    at Object.start (/home/bra/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/cypress/lib/tasks/install.js:177:25)
    at Object.<anonymous> (/home/bra/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/cypress/index.js:13:36)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
gmake: *** [Makefile:337: pkg/ui/yarn.installed] Error 1
```

Could you please make this optional? I guess having cypress is not needed to produce (nor to run) the `cockroachdb` binary.

Building from 38a4cbe92e343f5b8e9d8cbda2d279fff3561c8f (the commit before introducing cypress) works fine.

**To Reproduce**

Try to build cockroachdb master on FreeBSD after 38a4cbe92e343f5b8e9d8cbda2d279fff3561c8f.

**Comment by rohany** [comment]
I'm not sure about the FreeBSD related issues (@knz might know more), but you could try running `make buildshort` which will skip the building of the web UI in the meantime.

**Comment by knz** [comment]
@bra-fsn indeed you can use `make buildshort` to get a UI-less binary until this problem is fixed.

@koorosh @dhartunian this situation is unfortunate. I also use FreeBSD for all my development. Right now this new bug is preventing me from doing any kind of UI testing. Can you please fix this? Thanks.

**Comment by knz** [comment]
It's especially annoying because every time I try to edit `state.js` manually to fix it, the next time I run `make build` it reverts my change.

For reference, the following patch should be applied:

```diff
--- state.js    2020-04-20 11:38:25.107050000 +0200
+++ pkg/ui/node_modules/cypress/lib/tasks/state.js      2020-04-20 11:38:54.714127000 +0200
@@ -15,13 +15,10 @@
   switch (platform) {
     case 'darwin':
       return 'Contents/MacOS/Cypress';
-    case 'linux':
-      return 'Cypress';
     case 'win32':
       return 'Cypress.exe';
-    // TODO handle this error using our standard
     default:
-      throw new Error('Platform: "' + platform + '" is not supported.');
+      return 'Cypress';
   }
 };

@@ -31,13 +28,8 @@
   switch (platform) {
     case 'darwin':
       return 'Cypress.app';
-    case 'linux':
-      return 'Cypress';
-    case 'win32':
-      return 'Cypress';
-    // TODO handle this error using our standard
     default:
-      throw new Error('Platform: "' + platform + '" is not supported.');
+      return 'Cypress';
   }
 };

@@ -47,13 +39,8 @@
   switch (platform) {
     case 'darwin':
       return path.join(binaryDir, 'Contents', 'Resources', 'app', 'package.json');
-    case 'linux':
-      return path.join(binaryDir, 'resources', 'app', 'package.json');
-    case 'win32':
-      return path.join(binaryDir, 'resources', 'app', 'package.json');
-    // TODO handle this error using our standard
     default:
-      throw new Error('Platform: "' + platform + '" is not supported.');
+      return path.join(binaryDir, 'resources', 'app', 'package.json');
   }
 };

```

**Comment by knz** [comment]
Actually scratch that, the patch is not sufficient. I tricked it (by manually overwriting the file in `~/.cache/yarn/v6/npm-cypress-4.3.0-74694c2407846119368a6aecc456b3ee1a8ee32b-integrity/node_modules/cypress/lib/tasks/`) but then the build fails with this error:

```
[11:42:09]  Downloading Cypress     [started]
[11:42:09]  Downloading Cypress     [failed]
[11:42:09] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.3.0?platform=freebsd&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: freebsd (13.0-CURRENT)
Cypress Version: 4.3.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.3.0?platform=freebsd&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: freebsd (13.0-CURRENT)
Cypress Version: 4.3.0
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by knz** [comment]
There are two problems here:

1) the **proximate** problem is that the tool is not available for this platform
2) the **root** problem is that the `make` command is downloading an external program into the build
   - this is an unregistered dependency
   - it makes the build non-deterministic
   - it's potentially a security problem

**Comment by knz** [comment]
The proper solution is to:
1) ensure `make build` is independent from Cypress
2) **not download cypress automatically** - make it an external dependency
3) only use `cypress` when one of the test targets is used

**Comment by knz** [comment]
@bra-fsn in the meantime you can run `git revert -n 244659864004257d0a79711f402775d14e98f887` this will unblock `make build` for you.

**Comment by dhartunian** [comment]
Sorry you ran into this @bra-fsn, thank you for filing the issue.
@knz, thank you for the investigation and suggestions.

I filed #47694 to use this dependency using a different workflow.
