### ISSUE TITLE
sql: BenchmarkBank_Cockroach instantly panics

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#4769]
```
make bench PKG=./sql TESTS=Cockroach TESTTIMEOUT=1h TESTFLAGS='-benchmem -count 5' | tee old.txt
go test -v  -i ./sql
go test  -run - -bench Cockroach -timeout 5m ./sql -benchmem -count 5
PASS
BenchmarkBank_Cockroach-4                	I160302 07:00:26.207658 server/node.go:352  store store=0:0 ([]=) not bootstrapped
I160302 07:00:26.209327 storage/replica_command.go:1272  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1456920027.209s
I160302 07:00:26.209653 server/node.go:298  **** cluster 83e90b82-b45d-46be-a11d-55855d162c5e has been created
I160302 07:00:26.209670 server/node.go:299  **** add additional nodes by specifying --join=127.0.0.1:65391
I160302 07:00:26.211052 server/node.go:365  initialized store store=1:1 ([]=): {Capacity:249779191808 Available:111422287872 RangeCount:0}
I160302 07:00:26.211094 server/node.go:274  node ID 1 initialized
I160302 07:00:26.211149 storage/stores.go:289  read 0 node addresses from persistent storage
I160302 07:00:26.211647 server/node.go:480  connecting to gossip network to verify cluster ID...
I160302 07:00:26.211681 server/node.go:501  node connected via gossip and verified as part of cluster "83e90b82-b45d-46be-a11d-55855d162c5e"
I160302 07:00:26.211711 storage/split_queue.go:97  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0]
I160302 07:00:26.211722 server/node.go:330  [node=1] Started node with [[]=] engine(s) and attributes []
I160302 07:00:26.211759 server/server.go:324  starting https/postgres server at 127.0.0.1:65391
I160302 07:00:26.235975 storage/replica_command.go:1349  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160302 07:00:26.247754 storage/replica_command.go:1272  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1456920027.260s
I160302 07:00:26.247820 storage/replica_command.go:1349  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160302 07:00:26.253247 storage/replica_command.go:1272  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1456920027.260s
I160302 07:00:26.253302 storage/replica_command.go:1349  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
W160302 07:00:26.256416 storage/replica.go:1741  [node=1,store=1,range=1] failed to push during intent resolution: conflicting intents on [/Meta2/Table/13 /Meta2/Max]: resolved? false
I160302 07:00:26.310798 storage/replica_command.go:1272  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1456920027.310s
I160302 07:00:26.310963 storage/split_queue.go:97  splitting range=4 [/Table/13-/Max) at keys [/Table/50/0]
I160302 07:00:26.311742 storage/replica_command.go:1349  initiating a split of range=4 [/Table/13-/Max) at key /Table/50
I160302 07:00:26.319222 storage/replica_command.go:1272  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1456920027.319s
panic: interface conversion: parser.VariableExpr is *parser.QualifiedName, not *sql.qvalue

goroutine 213 [running]:
panic(0x50bf960, 0xc820ae47c0)
	/Users/tamird/src/go1.6/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql.(*planner).initSelect.func1(0x64719c8, 0xc820ae4200, 0xc820ae4200, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/select.go:215 +0x195
github.com/cockroachdb/cockroach/sql.(*varConvertVisitor).VisitPre(0xc8204a63c0, 0x64a7ee0, 0xc820ae4200, 0x0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/expr_filter.go:80 +0x170
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x64a8360, 0xc8204a63c0, 0x64a7ee0, 0xc820ae4200, 0x0, 0x0, 0x5dbb1e8)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:384 +0x56
github.com/cockroachdb/cockroach/sql/parser.(*ComparisonExpr).Walk(0xc820738d20, 0x64a8360, 0xc8204a63c0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:160 +0x6d
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x64a8360, 0xc8204a63c0, 0x64a7f70, 0xc820738d20, 0x64a7f70, 0xc820738d20, 0x40131d6)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:387 +0x98
github.com/cockroachdb/cockroach/sql/parser.(*Select).WalkStmt(0xc820670280, 0x64a8360, 0xc8204a63c0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:533 +0x130
github.com/cockroachdb/cockroach/sql/parser.WalkStmt(0x64a8360, 0xc8204a63c0, 0x64a2cc0, 0xc820670280, 0x0, 0x0, 0xc82058a5c0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:710 +0xbc
github.com/cockroachdb/cockroach/sql/parser.(*ParenSelect).WalkStmt(0xc8206699c0, 0x64a8360, 0xc8204a63c0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:495 +0x81
github.com/cockroachdb/cockroach/sql/parser.WalkStmt(0x64a8360, 0xc8204a63c0, 0x6471950, 0xc8206699c0, 0x0, 0x0, 0xc820738ea0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:710 +0xbc
github.com/cockroachdb/cockroach/sql/parser.(*Subquery).Walk(0xc820669a00, 0x64a8360, 0xc8204a63c0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:271 +0x81
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x64a8360, 0xc8204a63c0, 0x64714a8, 0xc820669a00, 0x64714a8, 0xc820669a00, 0x50e7800)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:387 +0x98
github.com/cockroachdb/cockroach/sql/parser.(*AndExpr).Walk(0xc82058a8e0, 0x64a8360, 0xc8204a63c0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:59 +0xba
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x64a8360, 0xc8204a63c0, 0x64714e8, 0xc82058a8e0, 0x64714e8, 0xc82058a8e0, 0xc8204a63c0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:387 +0x98
github.com/cockroachdb/cockroach/sql/parser.WalkExprConst(0x64a8360, 0xc8204a63c0, 0x64714e8, 0xc82058a8e0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:397 +0x3f
github.com/cockroachdb/cockroach/sql.exprCheckVars(0x64714e8, 0xc82058a8e0, 0xc82058aa80, 0xc8204a6340)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/expr_filter.go:104 +0xa6
github.com/cockroachdb/cockroach/sql.splitBoolExpr(0x64714e8, 0xc82058a8e0, 0xc82058aa80, 0xe2344b46d5279601, 0x0, 0x0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/expr_filter.go:166 +0x75
github.com/cockroachdb/cockroach/sql.splitFilter(0x64714e8, 0xc82058a8e0, 0xc82058aa80, 0x0, 0x0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/expr_filter.go:247 +0x83
github.com/cockroachdb/cockroach/sql.(*planner).initSelect(0xc82007cd00, 0xc82067c000, 0xc820cf8628, 0x0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/select.go:224 +0x5b8
github.com/cockroachdb/cockroach/sql.(*planner).Select(0xc82007cd00, 0xc820cf8628, 0x0, 0x0, 0x3)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/select.go:159 +0x80
github.com/cockroachdb/cockroach/sql.(*planner).Update(0xc82007cd00, 0xc82048c050, 0x5f331e00, 0x0, 0x0, 0xc800000001)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/update.go:140 +0x1322
github.com/cockroachdb/cockroach/sql.(*planner).prepare(0xc82007cd00, 0x6471528, 0xc82048c050, 0x0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/plan.go:195 +0x138
github.com/cockroachdb/cockroach/sql.(*Executor).Prepare(0xc82013c500, 0xc820610022, 0x4, 0xc8205aa006, 0xae, 0xc82018a140, 0xc820738a20, 0x0, 0x0, 0x0, ...)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/executor.go:296 +0x587
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleParse(0xc82018a000, 0xc82018a028, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:326 +0x553
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc82018a000, 0xc8200f3fc0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:251 +0xf1b
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc8201ca070, 0x646a400, 0xc820606600, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:161 +0xab5
github.com/cockroachdb/cockroach/server.(*Server).Start.func4.1(0x646a3a0, 0xc8205e0bb0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/server/server.go:290 +0x4b
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc8202bf700, 0x646a3a0, 0xc8205e0bb0, 0xc820488000)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/net.go:157 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/net.go:159 +0x31f
exit status 2
FAIL	github.com/cockroachdb/cockroach/sql	0.238s
make: *** [bench] Error 1
```

**Comment by RaduBerinde** [comment]
Had PR #4765 out for this.
