### ISSUE TITLE
test failure #914

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#479]
The following test appears to have failed:

[#914](https://circleci.com/gh/cockroachdb/cockroach/914):

```
I0326 05:26:29.194389      81 multiraft.go:449] node 1: group 1 got message 8->1 MsgHeartbeatResp Term:6 Log:0/0
I0326 05:26:29.194408      81 multiraft.go:449] node 1: group 1 got message 4->1 MsgHeartbeatResp Term:6 Log:0/0
I0326 05:26:29.194422      81 multiraft.go:449] node 1: group 1 got message 5->1 MsgAppResp Term:6 Log:0/11
I0326 05:26:29.194440      81 multiraft.go:449] node 1: group 1 got message 6->1 MsgAppResp Term:6 Log:0/11
E0326 05:26:29.687754      81 heartbeat_test.go:51] timeout when reading from intercept channel
panic: test timed out after 30s

goroutine 384 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0x9a5d20, 0xb0d340, 0x7, 0x7, 0xc207ffc301)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
goroutine 345 [select]:
github.com/cockroachdb/cockroach/multiraft.func·009()
	/go/src/github.com/cockroachdb/cockroach/multiraft/events_test.go:51 +0x3fc
created by github.com/cockroachdb/cockroach/multiraft.(*eventDemux).start
	/go/src/github.com/cockroachdb/cockroach/multiraft/events_test.go:72 +0x8c
FAIL	github.com/cockroachdb/cockroach/multiraft	30.023s
=== RUN TestMemoryStorage
--- PASS: TestMemoryStorage (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/multiraft/storagetest	0.004s
=== RUN TestClientCmdIDIsEmpty
--- PASS: TestClientCmdIDIsEmpty (0.00s)
=== RUN TestResponseHeaderSetGoError
--- PASS: TestResponseHeaderSetGoError (0.00s)
=== RUN TestResponseHeaderNilError
--- PASS: TestResponseHeaderNilError (0.00s)
I0326 05:26:29.194389      81 multiraft.go:449] node 1: group 1 got message 8->1 MsgHeartbeatResp Term:6 Log:0/0
I0326 05:26:29.194408      81 multiraft.go:449] node 1: group 1 got message 4->1 MsgHeartbeatResp Term:6 Log:0/0
I0326 05:26:29.194422      81 multiraft.go:449] node 1: group 1 got message 5->1 MsgAppResp Term:6 Log:0/11
I0326 05:26:29.194440      81 multiraft.go:449] node 1: group 1 got message 6->1 MsgAppResp Term:6 Log:0/11
E0326 05:26:29.687754      81 heartbeat_test.go:51] timeout when reading from intercept channel
panic: test timed out after 30s

goroutine 384 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0x9a5d20, 0xb0d340, 0x7, 0x7, 0xc207ffc301)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
goroutine 345 [select]:
github.com/cockroachdb/cockroach/multiraft.func·009()
	/go/src/github.com/cockroachdb/cockroach/multiraft/events_test.go:51 +0x3fc
created by github.com/cockroachdb/cockroach/multiraft.(*eventDemux).start
	/go/src/github.com/cockroachdb/cockroach/multiraft/events_test.go:72 +0x8c
FAIL	github.com/cockroachdb/cockroach/multiraft	30.023s
=== RUN TestMemoryStorage
--- PASS: TestMemoryStorage (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/multiraft/storagetest	0.004s
=== RUN TestClientCmdIDIsEmpty
--- PASS: TestClientCmdIDIsEmpty (0.00s)
=== RUN TestResponseHeaderSetGoError
--- PASS: TestResponseHeaderSetGoError (0.00s)
=== RUN TestResponseHeaderNilError
--- PASS: TestResponseHeaderNilError (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
This looks like a duplicate of #473: The snippet from the log below shows 10 nodes starting and taking more than 500ms to even finish elections. It's odd to see a timeout on the intercept channel, but looking at the snippet below, it seems like the only messages that pass through the intercept successfully are the MsgVote requests at the beginning, and then there's nothing (received by a group) until the timeout hits, even though some MsgVoteResps have been queued (and are subsequently processed by the non-intercepting transport after the first timeout).
The message interception loop quitting that early in the test stalls the main goroutine (as it's triggering new heartbeats while receiving old ones, which never happens).

I'm still having trouble believing that an election can take more than 500ms, but some of these CircleCI machines are very seriously choked.


```
I0326 05:26:28.673826      81 multiraft.go:408] node 1 starting
I0326 05:26:28.673862      81 multiraft.go:408] node 2 starting
I0326 05:26:28.673898      81 multiraft.go:408] node 3 starting
I0326 05:26:28.673933      81 multiraft.go:408] node 4 starting
I0326 05:26:28.673956      81 multiraft.go:408] node 5 starting
I0326 05:26:28.673973      81 multiraft.go:408] node 6 starting
I0326 05:26:28.673989      81 multiraft.go:408] node 7 starting
I0326 05:26:28.674007      81 multiraft.go:408] node 8 starting
I0326 05:26:28.674022      81 multiraft.go:408] node 9 starting
I0326 05:26:28.674038      81 multiraft.go:408] node 10 starting
I0326 05:26:28.674152      81 raft.go:315] raft: 1 became follower at term 5
I0326 05:26:28.674180      81 raft.go:134] raft: newRaft 1 [peers: [1,2,3,4,5,6,7,8,9,a], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:26:28.674258      81 raft.go:315] raft: 2 became follower at term 5
I0326 05:26:28.674289      81 raft.go:134] raft: newRaft 2 [peers: [1,2,3,4,5,6,7,8,9,a], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:26:28.674368      81 raft.go:315] raft: 3 became follower at term 5
I0326 05:26:28.674386      81 raft.go:134] raft: newRaft 3 [peers: [1,2,3,4,5,6,7,8,9,a], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:26:28.674454      81 raft.go:315] raft: 4 became follower at term 5
I0326 05:26:28.674483      81 raft.go:134] raft: newRaft 4 [peers: [1,2,3,4,5,6,7,8,9,a], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:26:28.674564      81 raft.go:315] raft: 5 became follower at term 5
I0326 05:26:28.674582      81 raft.go:134] raft: newRaft 5 [peers: [1,2,3,4,5,6,7,8,9,a], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:26:28.674648      81 raft.go:315] raft: 6 became follower at term 5
I0326 05:26:28.674676      81 raft.go:134] raft: newRaft 6 [peers: [1,2,3,4,5,6,7,8,9,a], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:26:28.674764      81 raft.go:315] raft: 7 became follower at term 5
I0326 05:26:28.674782      81 raft.go:134] raft: newRaft 7 [peers: [1,2,3,4,5,6,7,8,9,a], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:26:28.674852      81 raft.go:315] raft: 8 became follower at term 5
I0326 05:26:28.674881      81 raft.go:134] raft: newRaft 8 [peers: [1,2,3,4,5,6,7,8,9,a], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:26:28.674962      81 raft.go:315] raft: 9 became follower at term 5
I0326 05:26:28.674980      81 raft.go:134] raft: newRaft 9 [peers: [1,2,3,4,5,6,7,8,9,a], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:26:28.675039      81 raft.go:315] raft: a became follower at term 5
I0326 05:26:28.675060      81 raft.go:134] raft: newRaft a [peers: [1,2,3,4,5,6,7,8,9,a], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:26:28.675108      81 raft.go:389] raft: 1 is starting a new election at term 5
I0326 05:26:28.675130      81 raft.go:328] raft: 1 became candidate at term 6
I0326 05:26:28.675188      81 raft.go:372] raft: 1 received vote from 1 at term 6
I0326 05:26:28.675202      81 raft.go:365] raft: 1 [logterm: 5, index: 10] sent vote request to 2 at term 6
I0326 05:26:28.675213      81 raft.go:365] raft: 1 [logterm: 5, index: 10] sent vote request to 3 at term 6
I0326 05:26:28.675225      81 raft.go:365] raft: 1 [logterm: 5, index: 10] sent vote request to 4 at term 6
I0326 05:26:28.675237      81 raft.go:365] raft: 1 [logterm: 5, index: 10] sent vote request to 7 at term 6
I0326 05:26:28.675247      81 raft.go:365] raft: 1 [logterm: 5, index: 10] sent vote request to 9 at term 6
I0326 05:26:28.675258      81 raft.go:365] raft: 1 [logterm: 5, index: 10] sent vote request to 6 at term 6
I0326 05:26:28.675267      81 raft.go:365] raft: 1 [logterm: 5, index: 10] sent vote request to 8 at term 6
I0326 05:26:28.675277      81 raft.go:365] raft: 1 [logterm: 5, index: 10] sent vote request to a at term 6
I0326 05:26:28.675287      81 raft.go:365] raft: 1 [logterm: 5, index: 10] sent vote request to 5 at term 6
I0326 05:26:28.675304      81 multiraft.go:626] node 1: group 1 raft ready
I0326 05:26:28.675310      81 multiraft.go:628] SoftState updated: {Lead:0 RaftState:StateCandidate}
I0326 05:26:28.675351      81 multiraft.go:631] HardState updated: {Term:6 Vote:1 Commit:10 XXX_unrecognized:[]}
I0326 05:26:28.675371      81 multiraft.go:643] Outgoing Message[0]: 1->2 MsgVote Term:6 Log:5/10
I0326 05:26:28.675385      81 multiraft.go:643] Outgoing Message[1]: 1->3 MsgVote Term:6 Log:5/10
I0326 05:26:28.675399      81 multiraft.go:643] Outgoing Message[2]: 1->4 MsgVote Term:6 Log:5/10
I0326 05:26:28.675409      81 multiraft.go:643] Outgoing Message[3]: 1->7 MsgVote Term:6 Log:5/10
I0326 05:26:28.675416      81 multiraft.go:643] Outgoing Message[4]: 1->9 MsgVote Term:6 Log:5/10
I0326 05:26:28.675423      81 multiraft.go:643] Outgoing Message[5]: 1->6 MsgVote Term:6 Log:5/10
I0326 05:26:28.675429      81 multiraft.go:643] Outgoing Message[6]: 1->8 MsgVote Term:6 Log:5/10
I0326 05:26:28.675435      81 multiraft.go:643] Outgoing Message[7]: 1->10 MsgVote Term:6 Log:5/10
I0326 05:26:28.675441      81 multiraft.go:643] Outgoing Message[8]: 1->5 MsgVote Term:6 Log:5/10
I0326 05:26:28.675483      81 multiraft.go:449] node 2: group 1 got message 1->2 MsgVote Term:6 Log:5/10
I0326 05:26:28.675508      81 raft.go:404] raft: 2 [term: 5] received a MsgVote message with higher term from 1 [term: 6]
I0326 05:26:28.675522      81 raft.go:315] raft: 2 became follower at term 6
I0326 05:26:28.675544      81 raft.go:559] raft: 2 [logterm: 5, index: 10, vote: 0] voted for 1 [logterm: 5, index: 10] at term 6
I0326 05:26:28.675569      81 multiraft.go:626] node 2: group 1 raft ready
I0326 05:26:28.675579      81 multiraft.go:631] HardState updated: {Term:6 Vote:1 Commit:10 XXX_unrecognized:[]}
I0326 05:26:28.675621      81 multiraft.go:643] Outgoing Message[0]: 2->1 MsgVoteResp Term:6 Log:0/0
I0326 05:26:28.675642      81 multiraft.go:449] node 3: group 1 got message 1->3 MsgVote Term:6 Log:5/10
I0326 05:26:28.675675      81 raft.go:404] raft: 3 [term: 5] received a MsgVote message with higher term from 1 [term: 6]
I0326 05:26:28.675687      81 raft.go:315] raft: 3 became follower at term 6
I0326 05:26:28.675700      81 raft.go:559] raft: 3 [logterm: 5, index: 10, vote: 0] voted for 1 [logterm: 5, index: 10] at term 6
I0326 05:26:28.675728      81 multiraft.go:626] node 3: group 1 raft ready
I0326 05:26:28.675738      81 multiraft.go:631] HardState updated: {Term:6 Vote:1 Commit:10 XXX_unrecognized:[]}
I0326 05:26:28.675786      81 multiraft.go:643] Outgoing Message[0]: 3->1 MsgVoteResp Term:6 Log:0/0
I0326 05:26:28.675814      81 multiraft.go:449] node 4: group 1 got message 1->4 MsgVote Term:6 Log:5/10
I0326 05:26:28.675842      81 raft.go:404] raft: 4 [term: 5] received a MsgVote message with higher term from 1 [term: 6]
I0326 05:26:28.675854      81 raft.go:315] raft: 4 became follower at term 6
I0326 05:26:28.675867      81 raft.go:559] raft: 4 [logterm: 5, index: 10, vote: 0] voted for 1 [logterm: 5, index: 10] at term 6
I0326 05:26:28.675888      81 multiraft.go:626] node 4: group 1 raft ready
I0326 05:26:28.675893      81 multiraft.go:631] HardState updated: {Term:6 Vote:1 Commit:10 XXX_unrecognized:[]}
I0326 05:26:28.675920      81 multiraft.go:643] Outgoing Message[0]: 4->1 MsgVoteResp Term:6 Log:0/0
I0326 05:26:29.186791      81 multiraft.go:449] node 7: group 1 got message 1->7 MsgVote Term:6 Log:5/10
I0326 05:26:29.186866      81 raft.go:404] raft: 7 [term: 5] received a MsgVote message with higher term from 1 [term: 6]
I0326 05:26:29.186895      81 raft.go:315] raft: 7 became follower at term 6
I0326 05:26:29.186922      81 raft.go:559] raft: 7 [logterm: 5, index: 10, vote: 0] voted for 1 [logterm: 5, index: 10] at term 6
I0326 05:26:29.186991      81 multiraft.go:626] node 7: group 1 raft ready
I0326 05:26:29.187008      81 multiraft.go:631] HardState updated: {Term:6 Vote:1 Commit:10 XXX_unrecognized:[]}
I0326 05:26:29.187076      81 multiraft.go:643] Outgoing Message[0]: 7->1 MsgVoteResp Term:6 Log:0/0
I0326 05:26:29.187130      81 multiraft.go:449] node 9: group 1 got message 1->9 MsgVote Term:6 Log:5/10
I0326 05:26:29.187270      81 raft.go:404] raft: 9 [term: 5] received a MsgVote message with higher term from 1 [term: 6]
I0326 05:26:29.187301      81 raft.go:315] raft: 9 became follower at term 6
I0326 05:26:29.187326      81 raft.go:559] raft: 9 [logterm: 5, index: 10, vote: 0] voted for 1 [logterm: 5, index: 10] at term 6
E0326 05:26:29.173939      81 heartbeat_test.go:51] timeout when reading from intercept channel
```
