### ISSUE TITLE
Update-Database is not working with EntityFrameworkCore

### ISSUE THREAD

**Issue by pheelLikeWater** [cockroachdb/cockroach#47943]
Hello,

today I wanted to change to .NET Core Web API and EntityFrameWork. I've installed the Npqsql and EntityFramworkCore packages.

Added a test DTO e.g. User and my WebApiContext.

`public WebApiContext(DbContextOptions<WebApiContext> options) : base(options) { }
 public DbSet<User> Users { get; set; }`

When calling the "update-database" command, im always getting an error.

`update-database
Build started...
Build succeeded.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "Users" (
          "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
          "Name" text NULL,
          "Email" text NULL,
          CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
      );
Failed executing DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "Users" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Email" text NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);
Npgsql.PostgresException (0x80004005): 42601: at or near "generated": syntax error
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
  Exception data:
    Severity: ERROR
    SqlState: 42601
    MessageText: at or near "generated": syntax error
    Detail: source SQL:
CREATE TABLE "Users" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          ^
    Hint: try \h CREATE TABLE
    File: lexer.go
    Line: 189
    Routine: Error
42601: at or near "generated": syntax error`

Is it not possible to use the entity framework with the newest version of cockroackDB?

Would be awesome if that works. I want to use EF because I can't generate my tables with NPoco automatically.

Thank you

Cheers

**Comment by pheelLikeWater** [comment]
To fix the issue i just needed to add the "[DatabaseGenerated(DatabaseGeneratedOption.None)]" attribute for my primary key fields.

But is there another solution to use the old way adding auto increment functionality?

**Comment by pheelLikeWater** [comment]
Same issue here.

https://github.com/npgsql/efcore.pg/issues/1339

closed.

**Comment by rafiss** [comment]
@pheelLikeWater Thanks for the issue and investigation!

I've created this issue for adding support for the `GENERATED` syntax. Please watch that issue to follow any updates for that feature. https://github.com/cockroachdb/cockroach/issues/48532
