### ISSUE TITLE
possible Gossip deadlock in TestRangeSplitsWithWritePressure

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#480]
The following test appears to have failed:

[#915](https://circleci.com/gh/cockroachdb/cockroach/915):

```
I0326 05:44:16.705357      69 multiraft.go:631] HardState updated: {Term:6 Vote:257 Commit:117 XXX_unrecognized:[]}
I0326 05:44:16.705514      69 multiraft.go:634] New Entry[0]: 6/117 EntryNormal 00000000000000007078d73cd7485ab0: raft_id:2 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:765 > cmd_id:<wall_time:0 random:0 > key:"sVJgQbWLmM" user:"root" rep
I0326 05:44:16.705660      69 multiraft.go:637] Committed Entry[0]: 6/117 EntryNormal 00000000000000007078d73cd7485ab0: raft_id:2 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:765 > cmd_id:<wall_time:0 random:0 > key:"sVJgQbWLmM" user:"root" rep
I0326 05:44:16.706278      69 queue.go:207] processing range range=1 (""-"IZNbVZhCts") from split queue...
I0326 05:44:16.707374      69 range.go:1858] initiating a split of range 1 "\"\""-"\"IZNbVZhCts\"" at key "\"FnxZTCgeqD\""
panic: test timed out after 30s

goroutine 729 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0xfdd788, 0x145a340, 0x2b, 0x2b, 0xc208029a01)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
	/go/src/github.com/cockroachdb/cockroach/storage/split_queue.go:117 +0xaa6
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop(0xc208182540, 0xc2080bce80, 0xc20821e0c0)
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:208 +0x55a
created by github.com/cockroachdb/cockroach/storage.(*baseQueue).Start
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:132 +0x5d
FAIL	github.com/cockroachdb/cockroach/kv	30.018s
=== RUN TestHeartbeatSingleGroup
I0326 05:44:16.717716      78 multiraft.go:408] node 1 starting
I0326 05:44:16.717848      78 multiraft.go:408] node 2 starting
I0326 05:44:16.717996      78 raft.go:315] raft: 1 became follower at term 5
I0326 05:44:16.718045      78 raft.go:134] raft: newRaft 1 [peers: [1,2], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:44:16.718148      78 raft.go:315] raft: 2 became follower at term 5
I0326 05:44:16.718183      78 raft.go:134] raft: newRaft 2 [peers: [1,2], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:44:16.718243      78 raft.go:389] raft: 1 is starting a new election at term 5
I0326 05:44:16.718290      78 raft.go:328] raft: 1 became candidate at term 6
I0326 05:44:16.718309      78 raft.go:372] raft: 1 received vote from 1 at term 6
I0326 05:44:16.705357      69 multiraft.go:631] HardState updated: {Term:6 Vote:257 Commit:117 XXX_unrecognized:[]}
I0326 05:44:16.705514      69 multiraft.go:634] New Entry[0]: 6/117 EntryNormal 00000000000000007078d73cd7485ab0: raft_id:2 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:765 > cmd_id:<wall_time:0 random:0 > key:"sVJgQbWLmM" user:"root" rep
I0326 05:44:16.705660      69 multiraft.go:637] Committed Entry[0]: 6/117 EntryNormal 00000000000000007078d73cd7485ab0: raft_id:2 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:765 > cmd_id:<wall_time:0 random:0 > key:"sVJgQbWLmM" user:"root" rep
I0326 05:44:16.706278      69 queue.go:207] processing range range=1 (""-"IZNbVZhCts") from split queue...
I0326 05:44:16.707374      69 range.go:1858] initiating a split of range 1 "\"\""-"\"IZNbVZhCts\"" at key "\"FnxZTCgeqD\""
panic: test timed out after 30s

goroutine 729 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0xfdd788, 0x145a340, 0x2b, 0x2b, 0xc208029a01)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
	/go/src/github.com/cockroachdb/cockroach/storage/split_queue.go:117 +0xaa6
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop(0xc208182540, 0xc2080bce80, 0xc20821e0c0)
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:208 +0x55a
created by github.com/cockroachdb/cockroach/storage.(*baseQueue).Start
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:132 +0x5d
FAIL	github.com/cockroachdb/cockroach/kv	30.018s
=== RUN TestHeartbeatSingleGroup
I0326 05:44:16.717716      78 multiraft.go:408] node 1 starting
I0326 05:44:16.717848      78 multiraft.go:408] node 2 starting
I0326 05:44:16.717996      78 raft.go:315] raft: 1 became follower at term 5
I0326 05:44:16.718045      78 raft.go:134] raft: newRaft 1 [peers: [1,2], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:44:16.718148      78 raft.go:315] raft: 2 became follower at term 5
I0326 05:44:16.718183      78 raft.go:134] raft: newRaft 2 [peers: [1,2], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0326 05:44:16.718243      78 raft.go:389] raft: 1 is starting a new election at term 5
I0326 05:44:16.718290      78 raft.go:328] raft: 1 became candidate at term 6
I0326 05:44:16.718309      78 raft.go:372] raft: 1 received vote from 1 at term 6

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
The log indicates the test hitting a 30s timeout, but the timestamps in the logs don't cover nearly that amount of time. Since the last entry is just before running the range split txn, it looks like we've managed to produce a complete deadlock here.

The goroutine list shows various `semaquire` states for goroutines from `gossip`, so probably it's a locking problem there. For example, `server.Gossip` is stuck right at the mutex (and so is probably everyone else).
Would be interesting to know who has the mutex at that point...
