### ISSUE TITLE
backupccl: failure in TestBackupRestoreChecksum caused by "transaction already committed"

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#48258]
```
I200430 22:20:29.814750 168891 kv/kvserver/replica_command.go:397  [n1,s1,r36/1:/{Table/53/1/9…-Max}] initiating a split of this range at key /Table/54 [r43] (manual)
I200430 22:20:29.819718 168891 kv/kvserver/replica_command.go:397  [n1,s1,r43/1:/{Table/54-Max}] initiating a split of this range at key /Table/54/1/300 [r44] (manual)
I200430 22:20:29.820319 168893 kv/kvserver/replica_command.go:397  [n1,s1,r43/1:/{Table/54-Max}] initiating a split of this range at key /Table/54/1/100 [r45] (manual)
I200430 22:20:29.830087 168892 kv/kvserver/replica_command.go:397  [n1,s1,r44/1:/{Table/54/1/3…-Max}] initiating a split of this range at key /Table/54/1/400 [r47] (manual)
I200430 22:20:29.833694 168891 kv/kvserver/replica_command.go:397  [n1,s1,r44/1:/{Table/54/1/3…-Max}] initiating a split of this range at key /Table/54/1/600 [r46] (manual)
I200430 22:20:29.841527 168892 kv/kvserver/replica_command.go:397  [n1,s1,r47/1:/{Table/54/1/4…-Max}] initiating a split of this range at key /Table/54/1/500 [r48] (manual)
I200430 22:20:29.890083 168891 kv/kvserver/replica_command.go:397  [n1,s1,r48/1:/{Table/54/1/5…-Max}] initiating a split of this range at key /Table/54/1/600 [r49] (manual)
I200430 22:20:29.897796 168891 kv/kvserver/replica_command.go:397  [n1,s1,r49/1:/{Table/54/1/6…-Max}] initiating a split of this range at key /Table/54/1/900 [r50] (manual)
I200430 22:20:29.899075 168892 kv/kvserver/replica_command.go:397  [n1,s1,r49/1:/{Table/54/1/6…-Max}] initiating a split of this range at key /Table/54/1/700 [r51] (manual)
I200430 22:20:29.900461 168893 kv/kvserver/replica_command.go:397  [n1,s1,r43/1:/Table/54{-/1/300}] initiating a split of this range at key /Table/54/1/100 [r52] (manual)
I200430 22:20:29.905760 168893 kv/kvserver/replica_command.go:397  [n1,s1,r52/1:/Table/54/1/{100-300}] initiating a split of this range at key /Table/54/1/200 [r53] (manual)
I200430 22:20:29.907374 168739 jobs/registry.go:806  [n1] job 551206354219827201: stepping through state reverting with error importing 10 ranges: importing span /Table/53/1/{100-200}: checksum mismatch for 551206353828970497.sst
F200430 22:20:29.908373 168974 kv/kvclient/kvcoord/txn_coord_sender.go:804  [n1,txn=6123afa1] transaction unexpectedly committed: TransactionStatusError: already committed (REASON_TXN_COMMITTED): meta={id=6123afa1 key=/Local/Range/Table/54/1/600/RangeDescriptor pri=0.02571801 epo=0 ts=1588285229.899917750,0 min=1588285229.899917750,0 seq=11} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=8. ba: [txn: 6123afa1], EndTxn(commit:false tsflex:false) [/Local/Range/Table/54/1/600/RangeDescriptor] . txn: meta={id=6123afa1 key=/Local/Range/Table/54/1/600/RangeDescriptor pri=0.02571801 epo=0 ts=1588285229.899917750,0 min=1588285229.899917750,0 seq=11} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=8.
goroutine 168974 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x6c24801, 0xed63d462d, 0x0, 0x7e7820)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb8
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0x6c21540, 0xc000000004, 0x653cd18, 0x27, 0x324, 0xc00184b680, 0x27f)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:212 +0xbcd
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x47ad020, 0xc005a65b90, 0xc000000004, 0x2, 0x3fed7a7, 0x38, 0xc001fa7658, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2c9
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x47ad020, 0xc005a65b90, 0x1, 0xc000000004, 0x3fed7a7, 0x38, 0xc001fa7658, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:44 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:155
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).updateStateLocked(0xc001946480, 0x47ad020, 0xc005a65b90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:804 +0x65e
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send(0xc001946480, 0x47ad020, 0xc005a65b90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:505 +0x479
github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender(0xc00138c500, 0x47acfe0, 0xc002f8f260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:739 +0x122
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send(0xc001fe6900, 0x47acfe0, 0xc002f8f260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:911 +0x11e
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).rollback.func1.1(0x47acfe0, 0xc002f8f260, 0xb2d05e00, 0x47acfe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:730 +0x98
github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout(0x47acfe0, 0xc002f8f260, 0x3f561ce, 0x12, 0xb2d05e00, 0xc0010bae00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:135 +0xbf
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).rollback.func1(0x47acf60, 0xc003129940)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:729 +0x174
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc000ecce10, 0x47acf60, 0xc003129940, 0xc005099300, 0x16, 0x0, 0x0, 0xc00301d880)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:323 +0x152
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:318 +0x131

```

Seen in a random PR: https://teamcity.cockroachdb.com/viewLog.html?buildId=1911843&buildTypeId=Cockroach_UnitTests

**Comment by andreimatei** [comment]
Was fixed by #48227
