### ISSUE TITLE
kv/kvserver: TestStoreReadInconsistent fails under race on Pebble

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#48461]
Saw this on [CI](https://teamcity.cockroachdb.com/viewLog.html?buildId=1922468&buildTypeId=Cockroach_UnitTests), then reproduced on #48145 outside of CI:

```
~ make testrace PKG=./kv/kvserver TESTS=TestStoreReadInconsistent 2>&1 | tee out
Running make with -j16
GOPATH set to /Users/pmattis/Development/go
mkdir -p lib
ln -sf /Users/pmattis/Development/go/native/x86_64-apple-darwin19.3.0/geos/lib/lib{geos,geos_c}.dylib lib
GOFLAGS= go test  -race -tags ' make x86_64_apple_darwin19.3.0' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=v20.1.0-beta.4-1295-gc0da218d4c" -X "github.com/cockroachdb/cockroach/pkg/build.rev=c0da218d4c38af6a4aa6eb063506792a7ea02bd0" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-apple-darwin19.3.0"  ' -run "TestStoreReadInconsistent"  -timeout 30m ./pkg/./kv/kvserver
I200505 21:12:30.495986 1 rand.go:85  Random seed: -1185532325996819864
I200505 21:12:30.502612 14 vendor/github.com/cockroachdb/pebble/version_set.go:140  [JOB 1] MANIFEST created 000001
I200505 21:12:30.502767 14 vendor/github.com/cockroachdb/pebble/open.go:270  [JOB 1] WAL created 000002
W200505 21:12:30.572287 46 kv/kvserver/intentresolver/intent_resolver.go:440  failed to push during intent resolution: failed to push meta={id=92f3646b key="true-a" pri=0.00000005 epo=0 ts=0.000000123,106 min=0.000000123,106 seq=1} lock=true stat=PENDING rts=0,0 wto=false max=0,0
panic: interface conversion: roachpb.Response is nil, not *roachpb.ReverseScanResponse [recovered]
	panic: interface conversion: roachpb.Response is nil, not *roachpb.ReverseScanResponse [recovered]
	panic: interface conversion: roachpb.Response is nil, not *roachpb.ReverseScanResponse [recovered]
	panic: interface conversion: roachpb.Response is nil, not *roachpb.ReverseScanResponse

goroutine 14 [running]:
testing.tRunner.func1(0xc000222700)
	/Users/pmattis/Development/go1.13/src/testing/testing.go:874 +0x69f
panic(0x8e71580, 0xc000a39320)
	/Users/pmattis/Development/go1.13/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000702000, 0xa412f00, 0xc000132010)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0x154
panic(0x8e71580, 0xc000a39320)
	/Users/pmattis/Development/go1.13/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc000702000, 0xa412f00, 0xc000132010)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:479 +0x74d
panic(0x8e71580, 0xc000a39320)
	/Users/pmattis/Development/go1.13/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/kv/kvserver.TestStoreReadInconsistent.func1(0xc000222700)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_test.go:2073 +0x4fd7
testing.tRunner(0xc000222700, 0xc000314450)
	/Users/pmattis/Development/go1.13/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/Users/pmattis/Development/go1.13/src/testing/testing.go:960 +0x652
FAIL	github.com/cockroachdb/cockroach/pkg/kv/kvserver	4.417s
FAIL
```

I'm suspecting a difference in Pebble's MVCC layer.

Cc @itsbilal in case you happen to immediately know what the problem is. Otherwise, I'll dig into this tomorrow.

**Comment by petermattis** [comment]
A little more debugging info shows this is the same problem as #48463:

```
cannot read undeclared span /M{in-ax}
```
