### ISSUE TITLE
sql: panic: EXECUTE _ DISCARD ROWS; caused by flow: unexpected leftover bytes

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#48509]
With the tpch-1 dataset:

```
USE tpch;
SET allow_prepare_as_opt_plan = 'on';

prepare p as opt plan '
(Root
    (MakeLookupJoin
        (Scan
            [
                (Table "supplier")
                (Index "supplier@s_nk")
                (Cols "s_suppkey")
                (HardLimit 6000)
            ]
        )
        [
            (JoinType "inner-join")
            (Table "lineitem")
            (Index "lineitem@l_sk")
            (KeyCols "s_suppkey")
            (Cols "l_suppkey")
            (LookupColsAreTableKey "true")
        ]
        []
    )
    (Presentation "l_suppkey")
    (NoOrdering)
)
';

SET statement_timeout = 100;
execute p discard rows;
```

panics with:
```
E200506 20:40:24.193724 666 sql/conn_executor.go:798  [n1,client=[::1]:55964,hostnossl,user=root] a SQL panic has occurred while executing "EXECUTE p DISCARD ROWS": flow: unexpected 25282560 leftover bytes
E200506 20:40:24.193775 666 util/log/log.go:50  [n1,client=[::1]:55964,hostnossl,user=root] a panic has occurred!
panic: flow: unexpected 25282560 leftover bytes [recovered]
        panic: panic while executing 1 statements: EXECUTE _ DISCARD ROWS; caused by flow: unexpected 25282560 leftover bytes

goroutine 666 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc003093000, 0x4c33000, 0xc000b91e80, 0x3cb3a00, 0xc000346970)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:812 +0x39a
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc003093000, 0x4c33000, 0xc000b91e80)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:475 +0x61
panic(0x3cb3a00, 0xc000346970)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/util/log.ReportOrPanic(0x4c33000, 0xc004603800, 0xc0005e6a80, 0x436f8d2, 0x20, 0xc003eac280, 0x2, 0x2)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:550 +0x215
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc00461c1e0, 0x4c33000, 0xc004603800, 0x1)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:397 +0x375
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:384
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*EvalContext).Stop(...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:2992
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Cleanup(0xc00460c480, 0x4c33000, 0xc004603800)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:422 +0x78
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup(0xc004610360, 0x4c33000, 0xc004603800)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:342 +0x1ea
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func8()
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:424 +0xcf
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc003093000, 0x4c330c0, 0xc004589a40, 0xc0030933d0, 0x3, 0x7f385df03e78, 0xc0006c3880, 0xc0040de801, 0xc0044bd138, 0x0, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:898 +0x46b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc003093000, 0x4c330c0, 0xc004589a40, 0xc0030933d0, 0x7f385df03e78, 0xc0006c3880, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:782 +0x6ad
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc003093000, 0x4c330c0, 0xc004589a40, 0x4c4bc00, 0xc0045898c0, 0xc0040aaa5a, 0x16, 0x0, 0x0, 0x0, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:485 +0xb09
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc003093000, 0x4c330c0, 0xc004589a40, 0x4c4bc00, 0xc0045898c0, 0xc0040aaa5a, 0x16, 0x0, 0x0, 0x0, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x4f6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc003093000, 0x4c33000, 0xc004602600, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1371 +0x1aa8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc003093000, 0x4c33000, 0xc000b91e80, 0xc000048580, 0x5400, 0x15000, 0xc000048618, 0xc000420be0, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1300 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0003d1700, 0x4c33000, 0xc000b91e80, 0xc003093000, 0x5400, 0x15000, 0xc000048618, 0xc000420be0, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:477 +0x104
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc004086501, 0xc000367e40, 0x4c33000, 0xc000b91e80, 0xc000420be0, 0xc0003d1700, 0xc0006c3200, 0x4c56b80, 0xc003d89f50, 0xc00308f0e0, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:591 +0x2e8
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:523 +0x17e
```

It doesn't do this for hash or merge join, just lookup. The key part is the statement timeout. I found this by ctrl+c'ing during the a lookup join test. So I suspect the culprit is not cleaning up some memory during ctx cancellation.

**Comment by asubiotto** [comment]
Was this easily reproducible? I'm trying to reproduce on current master but having no luck. Can't see anything wrong with the cleanup code in the join reader at first glance.

**Comment by mjibson** [comment]
Did you load in the tpch-1 dataset? I recall it being easily reproducible with that. If not then...close I guess?

**Comment by asubiotto** [comment]
This reproduces easily on 20.1 but not 20.2. It's likely that my refactoring of the `joinReader` fixed a wrong state transition when canceling. This is a great find though, thanks!
