### ISSUE TITLE
kvserver: consistency check failed (19.2.2)

### ISSUE THREAD

**Issue by peymanh** [cockroachdb/cockroach#48665]
**Describe the problem**

Hi! we have 3 nodes on which we have 3 dockerized replica of cochroachdb. Today suddenly our second instance  stopped working and gives a fatal error. By seeing the logs ( docker logs roach2_id --tail 100 ) this error has occured:

```
this node is terminating because a replica inconsistency was detected between [n6,s6,r43/6:/System/tsd/cr.store.{ro…-ts…}]
and its other replicas. Please check your cluster-wide log files for more
information and contact the CockroachDB support team. It is not necessarily safe
to replace this node; cluster data may still be at risk of corruption.

A checkpoints directory to aid (expert) debugging should be present in:
/cockroach/cockroach-data/auxiliary

A file preventing this node from restarting was placed at:
/cockroach/cockroach-data/auxiliary/_CRITICAL_ALERT.txt

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc000418300, 0xc000418300, 0x0, 0x31071cd)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1017 +0xb1
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x7514940, 0xc000000004, 0x6ccabd2, 0xc, 0x1c7, 0xc000d46b00, 0x28e)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:871 +0x95b
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4a5e540, 0xc000076028, 0x4, 0x2, 0x0, 0x0, 0xc000ceb860, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2cc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4a5e540, 0xc000076028, 0x1, 0x4, 0x0, 0x0, 0xc000ceb860, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:189
github.com/cockroachdb/cockroach/pkg/cli.runStart(0x70e9e60, 0xc000073310, 0x0, 0x5, 0xc000cb1500, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:455 +0x1769
github.com/cockroachdb/cockroach/pkg/cli.runStartJoin(0x70e9e60, 0xc000073310, 0x0, 0x5, 0x3bd21e0, 0xc0004447e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:428 +0x4e
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x70e9e60, 0xc000073310, 0x0, 0x5, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:65 +0x6e
github.com/cockroachdb/cockroach/pkg/cli.maybeShoutError.func1(0x70e9e60, 0xc000073310, 0x0, 0x5, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:218 +0x4d
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x70e9e60, 0xc0000732c0, 0x5, 0x5, 0x70e9e60, 0xc0000732c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x70e3d00, 0x426c5a8, 0x4a5e540, 0xc000076028)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:800
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:224
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:66 +0x24e
main.main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:26 +0x20

```

**To Reproduce**

Unfortunately We have no idea how this problem may happen.

**Environment:**

CockroachDB version 19.2.2
Server OS: UBUNTU
Client app cockroach sql

**Comment by jordanlewis** [comment]
cc @tbg

**Comment by tbg** [comment]
Hi @peymanh, that's a pretty bad error (it means that the copies of your data got out of sync somehow). Unfortunately the interesting part of the error is missing. Could you send me the whole logs? And please preserve the data directories (i.e. take a copy). (both from all nodes). This will help understand the failure.

**Comment by peymanh** [comment]
@tbg Sorry for my delayed response. Unfortunately we had to correct our problem immediately so we corrected it in the hard way :) by removing our second instance and its volume and redeploying the service. So now it works fine.

If I can help you with checking old log file inside the container please tell me the directory so I can send you the logs.

**Comment by andreimatei** [comment]
Hey @peymanh unfortunately I don't think we can do anything here without the data directories. I'll close it hoping that either we've fixed the issue in the meantime, or to be rediscovered again.
