### ISSUE TITLE
sql: BenchmarkParallelPgbenchQuery_Cockroach crashing when run

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4877]
The benchmark is crashing with the following error:

```
panic: runTxnAttempt wasn't called in the txn we set up for it

goroutine 1017 [running]:
panic(0x4e833c0, 0xc821c1d9a0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc820148700, 0xc820066d00, 0xc82370de00, 0xc826286cd0, 0xc821c6c000, 0xc8237045b4, 0xc821c3cb80, 0x7, 0x8, 0xc8213d0768, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:699 +0x95
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func2(0xc821c6c000, 0xc8237045b4, 0xc82362f9e0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:608 +0x8d
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc821c6c000, 0xc821070001, 0xc8213d08a8, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/client/txn.go:462 +0x394
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc820148700, 0xc826286cd0, 0xc820fa3a8c, 0x182, 0xc820066d00, 0x0, 0x0, 0x0, 0x784fe00)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:611 +0x8d3
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc820148700, 0xc820f8c044, 0x4, 0xc82372a300, 0xc820fa3a8c, 0x182, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:481 +0x5c7
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc82372a1c0, 0xc820fa3a8c, 0x182, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2362db01, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:555 +0xbd
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc82372a1c0, 0xc82372a1e8, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:284 +0xcd
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc82372a1c0, 0xc82258e9c0, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:244 +0xf72
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc8206b8220, 0x79072b0, 0xc82052a600, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:161 +0xab5
github.com/cockroachdb/cockroach/server.(*Server).Start.func4.1(0x7907250, 0xc8246480b0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/server/server.go:281 +0x4b
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc820287e80, 0x7907250, 0xc8246480b0, 0xc822b8e000)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/util/net.go:157 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/util/net.go:159 +0x31f
```

**Comment by nvanbenschoten** [comment]
@andreimatei Is currently working on the issue that committing a transaction always clears the `txn` from the `txnState` in case of error, which can mess up parallel queries. It seems like that's the cause of this crash. We'll reexamine this issue once his fix goes through.
