### ISSUE TITLE
sql: populate EXPLAIN(DEBUG) of UPDATE

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#4945]
currently:
```
explain (debug) update deletes set a = 4 where k = 6;
 RowIdx | Key | Value | Disposition
--------+-----+-------+-------------
(0 rows)
```

**Comment by tamird** [comment]
This is even worse now:
```
insert into system.users values ('a','b'); explain (debug) update system.users set username = 'abcd' where hashedPassword = 'b';
driver: bad connection
```
That's because the server has crashed:
```
panic: runtime error: slice bounds out of range

goroutine 772 [running]:
panic(0x52fda40, 0xc8200140c0)
	/Users/tamird/src/go1.6/src/runtime/panic.go:481 +0x3e6
github.com/cockroachdb/cockroach/sql.(*updateNode).Next(0xc8207b0900, 0xc8207b0900, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/update.go:296 +0x90c
github.com/cockroachdb/cockroach/sql.(*explainDebugNode).Next(0xc8207a6650, 0xc8201596c0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/explain.go:381 +0x45
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc8201d2000, 0x81146f0, 0xc820cef200, 0xc82079e090, 0xc820cef201, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/executor.go:1050 +0x41c
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInOpenTxn(0xc8201d2000, 0x81146f0, 0xc820cef200, 0xc82079e090, 0x101, 0xc82079e028, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/executor.go:908 +0x439
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc8201d2000, 0xc820972b30, 0x1, 0x1, 0xc82079e090, 0xc82079e028, 0x5c50101, 0x0, 0x0, 0x0, ...)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/executor.go:666 +0x5da
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc8201d2000, 0xc82079e090, 0x1, 0xc82079e028, 0xc820880520, 0xc820972b30, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/executor.go:594 +0x18d
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func2(0xc82016a2c0, 0xc820880520, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/executor.go:486 +0x470
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc82016a2c0, 0xc8207e0101, 0x145cecca2f866ee5, 0x0, 0xc8207e61e0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/client/txn.go:541 +0x2eb
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc8201d2000, 0x81c0370, 0xc8207ba600, 0xc82079e000, 0xc8206a6071, 0x80, 0x0, 0x0, 0x0, 0xc8206a6000)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/executor.go:491 +0xba7
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8201d2000, 0x81c0370, 0xc8207ba600, 0xc82079e000, 0xc8206a6071, 0x80, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/executor.go:360 +0xf6
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc82012d500, 0x81c0370, 0xc8207ba600, 0xc8206a6071, 0x80, 0x0, 0x0, 0x0, 0x0, 0x8191401, ...)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:640 +0x98
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc82012d500, 0x81c0370, 0xc8207ba600, 0xc82012d528, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:320 +0xe8
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc82012d500, 0x0, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:275 +0x100c
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc820010d80, 0x8195ef8, 0xc820178840, 0x0, 0x0)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:231 +0x9d9
github.com/cockroachdb/cockroach/server.(*Server).Start.func8.1(0x8195ef8, 0xc820178840)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/server/server.go:369 +0x42
github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith.func1(0xc8200dc140, 0x8195ef8, 0xc820178840, 0xc820492030)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:131 +0x62
created by github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:133 +0x333
```
