### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#49820]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
CRDB cluster has five nodes(64 CPU，128GB memory， 3T SSD（200GB used）), I try to insert 100000000 rows(1KB size per row) to the cluster.

one node crash:
```
runtime error: invalid memory address or nil pointer dereference goroutine 1606 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000015b00, 0x469abc0, 0xc00aab6150)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:177 +0x97
panic(0x398a5e0, 0x67b5140)
        /usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).processQueue(0xc000712ff0, 0x2, 0xc00a84bd40, 0xc00a8db500, 0x46e63a0, 0xc00a54fe40, 0x46e6300, 0x0, 0x0)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:494 +0x488
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).startProcessNewQueue.func2(0x469abc0, 0xc00aab6150)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:633 +0x39a
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00a54fdb0, 0xc000015b00, 0xc00aab60f0)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:202 +0xfd
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xa8

W200602 08:37:51.196467 1606 util/stop/stopper.go:179  [n5] panic goroutine 1606 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000015b00, 0x469abc0, 0xc00aab6150)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:177 +0x97
panic(0x398a5e0, 0x67b5140)
        /usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).processQueue(0xc000712ff0, 0x2, 0xc00a84bd40, 0xc00a8db500, 0x46e63a0, 0xc00a54fe40, 0x46e6300, 0x0, 0x0)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:494 +0x488
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).startProcessNewQueue.func2(0x469abc0, 0xc00aab6150)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:633 +0x39a
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00a54fdb0, 0xc000015b00, 0xc00aab60f0)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:202 +0xfd
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xa8
E200602 08:37:51.196529 1606 util/log/crash_reporting.go:207  [n5] a panic has occurred!
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1aedfa8]

goroutine 1606 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000015b00, 0x469abc0, 0xc00aab6150)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:187 +0x332
panic(0x398a5e0, 0x67b5140)
        /usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).processQueue(0xc000712ff0, 0x2, 0xc00a84bd40, 0xc00a8db500, 0x46e63a0, 0xc00a54fe40, 0x46e6300, 0x0, 0x0)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:494 +0x488
```
**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
   V 19.2 release go 14.2
 - Server OS: [e.g. Linux/Distrib]
   Centos 7.6
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?
Exception caused by channel shutdown. A nil is received from a closed channel。
```
for {
		raftIdleTimer.Reset(raftIdleTimeout)
		select {
		case <-t.stopper.ShouldStop():
			return nil
		case <-raftIdleTimer.C:
			raftIdleTimer.Read = true
			return nil
		case err := <-errCh:
			return err
		case req := <-ch:
                       // panic: req == nil ?????
			batch.Requests = append(batch.Requests, *req)
			// Pull off as many queued requests as possible.
			//
			// TODO(peter): Think about limiting the size of the batch we send.
			for done := false; !done; {
				select {
				case req = <-ch:
					batch.Requests = append(batch.Requests, *req)
				default:
					done = true
				}
			}
```

**Comment by yuzefovich** [comment]
cc @irfansharif

**Comment by heidawei** [comment]
@yuzefovich  I saw a suspicious code in `func (t *RaftTransport) SendAsync(req *RaftMessageRequest, class rpc.ConnectionClass) (sent bool):`
```
	ch, existingQueue := t.getQueue(toNodeID, class)
	if !existingQueue {
		// Note that startProcessNewQueue is in charge of deleting the queue.
		if !t.startProcessNewQueue(ctx, toNodeID, class, stats) {
			return false
		}
	}
```
In the `startProcessNewQueue`, we will delete the channel :
```
worker := func(ctx context.Context) {
		ch, existingQueue := t.getQueue(toNodeID, class)
		if !existingQueue {
			log.Fatalf(t.AnnotateCtx(context.Background()), "queue for n%d does not exist", toNodeID)
		}
		defer cleanup(ch)
		defer t.queues[class].Delete(int64(toNodeID))
		conn, err := t.dialer.Dial(ctx, toNodeID, class)
		if err != nil {
			// DialNode already logs sufficiently, so just return.
			return
		}
		client := NewMultiRaftClient(conn)
		batchCtx, cancel := context.WithCancel(ctx)
		defer cancel()

		stream, err := client.RaftMessageBatch(batchCtx) // closed via cancellation
		if err != nil {
			log.Warningf(ctx, "creating batch client for node %d failed: %+v", toNodeID, err)
			return
		}

		if err := t.processQueue(toNodeID, ch, stats, stream, class); err != nil {
			log.Warningf(ctx, "while processing outgoing Raft queue to node %d: %s:", toNodeID, err)
		}
	}
```

Therefore, there is a scenario where the channel just obtained has been deleted from the map. Although it seems that this will not lead to panic, it should be a bug

we store channel in a map, the value is the channel's pointer, is it safe for golang GC??

**Comment by irfansharif** [comment]
@heidawei: what's the exact cockroach version you were running? `cockroach version` should tell you the answer. Did you compile it manually? I noticed you listed go1.14 as your go version. Are there any changes added on top of CRDB code that you're running here? (Just sanity checking the obvious before we dig in further - looking through our sentry reports I haven't see this particular null ptr exception fire before)

**Comment by heidawei** [comment]
@irfansharif  It's very strange. I carefully compared my code with the official code. I'm sure I didn't modify this part of the logic. I only made a little modification in the SQL layer. If the illegal nil is imported from the outside, it will be found before.
···
func (t *RaftTransport) SendAsync(req *RaftMessageRequest, class rpc.ConnectionClass) (sent bool) {
	toNodeID := req.ToReplica.NodeID     // XXX: if req == nil, It will panic here
	stats := t.getStats(toNodeID, class)
	defer func() {
		if !sent {
			atomic.AddInt64(&stats.clientDropped, 1)
		}
	}()

	ctx := t.AnnotateCtx(context.Background())
	if req.RangeID == 0 && len(req.Heartbeats) == 0 && len(req.HeartbeatResps) == 0 {
		// Coalesced heartbeats are addressed to range 0; everything else
		// needs an explicit range ID.
		panic("only messages with coalesced heartbeats or heartbeat responses may be sent to range ID 0")
	}
	if req.Message.Type == raftpb.MsgSnap {
		panic("snapshots must be sent using SendSnapshot")
	}

	if !t.dialer.GetCircuitBreaker(toNodeID, class).Ready() {
		return false
	}

	ch, existingQueue := t.getQueue(toNodeID, class)
	if !existingQueue {
		// Note that startProcessNewQueue is in charge of deleting the queue.
		if !t.startProcessNewQueue(ctx, toNodeID, class, stats) {
			return false
		}
	}

	select {
	case ch <- req:
		l := int32(len(ch))
		if v := atomic.LoadInt32(&stats.queueMax); v < l {
			atomic.CompareAndSwapInt32(&stats.queueMax, v, l)
		}
		return true
	default:
		return false
	}
}
···

**Comment by irfansharif** [comment]
Agreed, this is very strange. And good catch identifying that it would've panic-ed earlier if `req` was nil. I took a brief look at this again, and it's pretty bizzare. It should be safe from my understanding of the golang GC, my argument being that if we have a handle on the channel we're reading from, by definition it should never have been GC-ed away. We're masking the pointer to the channel behind an `unsafe.Pointer` when storing in in the `IntMap` underneath, but that should still be safe according to the [golang spec](https://utcc.utoronto.ca/~cks/space/blog/programming/GoUintptrVsUnsafePointer). 

I wonder if what we're seeing happening is something like the `req` being safely inserted into the map, and it being GC-ed away from underneath us? That doesn't sound likely either. 

Is this something you're able to reproduce reliably?

**Comment by heidawei** [comment]
I've done a lot of performance tests. This is the first time I've found it. It doesn't appear later. It's not like a poison pill event, because there are no problems with other nodes and ranges, and the data has been migrated to other nodes safely。

**Comment by mwang1026** [comment]
Closing due to inactivity
