### ISSUE TITLE
Crash on Kubernetes

### ISSUE THREAD

**Issue by huiser** [cockroachdb/cockroach#50007]
**Describe the problem**

xxxx@xxxx ~ $ kubectl get pods
NAME                                READY   STATUS             RESTARTS   AGE
cockroachdb-0                       1/1     Running            152        5d19h
cockroachdb-1                       0/1     CrashLoopBackOff   5          3m38s
cockroachdb-2                       1/1     Running            151        5d19h

kubectl logs cockroachdb-1:

```
+ exec /cockroach/cockroach start --join=cockroachdb-0.cockroachdb.default.svc.cluster.local:26257,cockroachdb-1.cockroachdb.default.svc.cluster.local:26257,cockroachdb-2.cockroachdb.default.svc.cluster.local:26257 --advertise-host=cockroachdb-1.cockroachdb.default.svc.cluster.local --logtostderr=INFO --certs-dir=/cockroach/cockroach-certs/ --http-port=8080 --port=26257 --cache=1Gi --max-disk-temp-storage=0 --max-offset=500ms --max-sql-memory=1Gi
F200609 09:23:56.697073 1 cli/start.go:481  From /cockroach/cockroach-data/auxiliary/_CRITICAL_ALERT.txt:

ATTENTION:

this node is terminating because a replica inconsistency was detected between [n3,s3,r148/3:/System/tsd/cr.node.{sy…-tx…}]
and its other replicas. Please check your cluster-wide log files for more
information and contact the CockroachDB support team. It is not necessarily safe
to replace this node; cluster data may still be at risk of corruption.

A checkpoints directory to aid (expert) debugging should be present in:
/cockroach/cockroach-data/auxiliary

A file preventing this node from restarting was placed at:
/cockroach/cockroach-data/auxiliary/_CRITICAL_ALERT.txt

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x7507000, 0xed6714c2c, 0x0, 0x20300000000000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb8
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0x7503c60, 0xc000000004, 0x6a440ff, 0xc, 0x1e1, 0xc000935340, 0x28e)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:210 +0xa29
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4bb8400, 0xc00007c088, 0x4, 0x2, 0x0, 0x0, 0xc000a797c0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2c9
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4bb8400, 0xc00007c088, 0x1, 0x7f8b00000004, 0x0, 0x0, 0xc000a797c0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:44 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:164
github.com/cockroachdb/cockroach/pkg/cli.runStart(0x6e6d4a0, 0xc000946500, 0x0, 0xa, 0x42f4b00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:481 +0x1623
github.com/cockroachdb/cockroach/pkg/cli.runStartJoin(0x6e6d4a0, 0xc000946500, 0x0, 0xa, 0xc000862500, 0xc000862800)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:445 +0x4e
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x6e6d4a0, 0xc000946500, 0x0, 0xa, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:187 +0x79
github.com/cockroachdb/cockroach/pkg/cli.maybeShoutError.func1(0x6e6d4a0, 0xc000946500, 0x0, 0xa, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:351 +0x51
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x6e6d4a0, 0xc0009463c0, 0xa, 0xa, 0x6e6d4a0, 0xc0009463c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:762 +0x460
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x6e65b80, 0xc00007c088, 0x42f0b55, 0x6)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:800
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:223
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:67 +0x272
main.main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:26 +0x20
```

**To Reproduce**

Just deployed, and not using it for a few days.

**Expected behavior**
No crash

**Additional data / screenshots**

see above

**Environment:**
```
helm list 
NAME       	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART                       	APP VERSION
cockroachdb	default  	6       	2020-06-05 21:47:05.007973685 +0200 CEST	deployed	cockroachdb-3.0.7           	19.2.5     
```

Running on K3S

**Comment by solongordon** [comment]
Sending to KV for triage, cc @tbg

**Comment by tbg** [comment]
Hi Stephan, thank you for reaching out. Interesting. This should not happen and I would love to ge to the bottom of this.

I sent you an email with a link to upload files (and a description of what to upload) in case this is possible.

In the meantime, I'm curious when this cluster was created (did it ever go through a version upgrade?) and whether it had any notable events in its lifetime (nonstandard config, unusual filesystem or settings, earlier crashes, etc).

I will have to see the log files to help you further (instructions see email).

**Comment by huiser** [comment]
I created the cluster 6 days ago, on Kubernetes (K3S) using the Helm chart, as described in the documentation.
I haven't been using CRDB since, but I noticed today, on of the pods was in CrashloopBackOff status. In the opening post you see the 'kubectl logs cockroachdb-1'.
I think it might be related to maintenance to Longhorn (storage engine I use for persistant storage).

**Comment by tbg** [comment]
Interesting, we don't have experience running CRDB on longhorn. Would you be able to upload the files I requested privately? Without more information, there's not much I'll be able to do here.

**Comment by huiser** [comment]
I don't have the content of the data directory of the crashed node anymore, sorry. I only have the log fragment mentioned above.

**Comment by tbg** [comment]
Ok. Thank you for your report anyway! I'll make a note that problems were observed running under longhorn. Feel free to comment if you have anything else to add or if you have questions.
