### ISSUE TITLE
kvserver: TestClosedTimestampCanServeWithConflictingIntent fails in testrace

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#50091]
This test is failing nearly every Publish Bleeding Edge run in testrace:

For example, https://teamcity.cockroachdb.com/viewLog.html?buildId=2005819&buildTypeId=Cockroach_MergeToMaster

Looks like it times out.

**Comment by tbg** [comment]
Will skip this

**Comment by tbg** [comment]
Trying to repro now. Looking into the failure posted above, surprisingly we hang here:

https://github.com/cockroachdb/cockroach/blob/a8ae1bf96c5900aecee4471ae89f35b8bbc6b6af/pkg/kv/kvserver/closed_timestamp_test.go#L553

This is before the test has really done much and plenty of other closed timestamp tests use the same invocation. Which also tells me - they are probably all flaky.

**Comment by tbg** [comment]
I would hazard a guess that this is the backend side of the `db0.Exec` statement and that it's stuck in some sort of commit loop, perhaps related to low closed timestamp target duration of `800ms`:

```
goroutine 362043 [runnable]:
github.com/cockroachdb/cockroach/pkg/roachpb.MergeSpans(0xc060566000, 0x1882, 0x1882, 0x1882, 0xc06051c000, 0x187a, 0x18aa)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/merge_spans.go:42 +0xccc
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.mergeIntoSpans(0xc06051c000, 0x187a, 0x18aa, 0xc0083e3400, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:390 +0x216
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked(0xc044b54868, 0x7e45fc0, 0xc034f75a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:183 +0x9af
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts(0xc044b547d0, 0x7e45fc0, 0xc034f75a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:247 +0x108
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked(0xc044b547d0, 0x7e45fc0, 0xc034f75a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:182 +0x2cb
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked(0xc044b54710, 0x7e45fc0, 0xc034f75a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go:252 +0x1ea
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked(0xc044b546f0, 0x7e45fc0, 0xc034f75a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:105 +0x2c3
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked(0xc044b54650, 0x7e45fc0, 0xc034f75a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:172 +0xff
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send(0xc044b54480, 0x7e45fc0, 0xc034f75a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:503 +0x6b7
github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender(0xc043382100, 0x7e45fc0, 0xc035a0aea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:744 +0x174
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send(0xc03e029c20, 0x7e45fc0, 0xc035a0aea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:908 +0x1d2
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).commit(0xc03e029c20, 0x7e45fc0, 0xc035a0aea0, 0xc035a0aea0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:585 +0x230
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Commit(0xc03e029c20, 0x7e45fc0, 0xc035a0aea0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:620 +0x112
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransactionInternal(0xc03d6d1b00, 0x7e45fc0, 0xc035a0aea0, 0x7e64d80, 0xc00fcd8780, 0x2d10ce6, 0xc044b54480)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:659 +0xd7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction(0xc03d6d1b00, 0x7e45fc0, 0xc035a0aea0, 0x7e64d80, 0xc00fcd8780, 0xc3a1fc, 0xc657bf, 0xc044b54480, 0xc0ffffffff)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:641 +0x74
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).handleAutoCommit(0xc03d6d1b00, 0x7e45fc0, 0xc035a0aea0, 0x7e64d80, 0xc00fcd8780, 0xc000000000, 0xc0834fff90, 0x1dcaaa9, 0xc03e029c58)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1272 +0x15d
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState.func6(0xc03d6d1b00, 0xc083500cb8, 0xc083500ca8, 0xc083500c00, 0xc04ab50f50, 0xc083500c98, 0x7e008c0, 0xaab6791)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:279 +0x1a4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc03d6d1b00, 0x7e45fc0, 0xc035a0aea0, 0x7e64d80, 0xc00fcd8780, 0xc05334e0cb, 0x16, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:519 +0x1145
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc03d6d1b00, 0x7e45fc0, 0xc035a0aea0, 0x7e64d80, 0xc00fcd8780, 0xc05334e0cb, 0x16, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:99 +0x6d8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc03d6d1b00, 0x7e45f00, 0xc01cb82180, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1356 +0x2611
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc03d6d1b00, 0x7e45f00, 0xc06bea8fc0, 0xc02dbda890, 0x5400, 0x15000, 0xc02dbda930, 0xc029abda40, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1285 +0x487
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc038a7f180, 0x7e45f00, 0xc06bea8fc0, 0xc03d6d1b00, 0x5400, 0x15000, 0xc02dbda930, 0xc029abda40, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:490 +0x132
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc02b3912ad, 0xc01879c860, 0x7e45f00, 0xc06bea8fc0, 0xc029abda40, 0xc038a7f180, 0xc042e6cd00, 0x7e71800, 0xc01a9c53b0, 0xc00fcd8600, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:595 +0x39b
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:523 +0x1ea
```

**Comment by tbg** [comment]
txnSpanRefresher internally will refresh at most 5 times (the default) in this case, so that won't be it.

I think it's more likely that we're auto-retrying the statement in SQL (@andreimatei: would we do that for this statement:

```go
	if _, err := db0.Exec(fmt.Sprintf(`
SET CLUSTER SETTING kv.closed_timestamp.target_duration = '%s';
SET CLUSTER SETTING kv.closed_timestamp.close_fraction = %.3f;
SET CLUSTER SETTING kv.closed_timestamp.follower_reads_enabled = true;
CREATE DATABASE cttest;
CREATE TABLE cttest.kv (id INT PRIMARY KEY, value STRING);
`, targetDuration, closeFraction)); err != nil {
		t.Fatal(err)
	}
```

**Comment by tbg** [comment]
So far, have been unable to repro in 15 minutes of

```
make roachprod-stressrace CLUSTER=tobias-stress PKG=./pkg/kv/kvrver TESTS=TestClosedTimestampCanServeWithConflictingIntent STRESSFLAGS='-p 4 -timeout 5m' TESTTIMEOUT=4m 2>&1 | tee stress.log
```

**Comment by tbg** [comment]
Got a repro with `-p 8`:

```
make roachprod-stressrace CLUSTER=tobias-stress PKG=./pkg/kv/kvserver TESTS=TestClosedTimestampCanServeWithConflictingIntent STRESSFLAGS='-p 8 -timeout 5m' TESTTIMEOUT=4m 2>&1 | tee stress.log
```

**Comment by tbg** [comment]
I think we're just pushing too much load on a machine and causing statements to retry eternally. Still might be something to learn here.

Here's output with added debugging: https://gist.github.com/tbg/cf7343e05cafbf4924d5b24be1834cbf

Created via `make roachprod-stressrace CLUSTER=tobias-stress PKG=./pkg/kv/kvserver TESTS=TestClosedTimestampCanServeWithConflictingIntent TESTFLAGS='-vmodule=conn_executor=2' STRESSFLAGS='-p 8 -timeout 5m' TESTTIMEOUT=4m 2>&1 | tee stress.log` on branch https://github.com/tbg/cockroach/tree/repro-ct

@andreimatei could you take a look? I think we're stuck in a SET CLUSTER SETTING.

**Comment by tbg** [comment]
Here's the actual file: [stress.log](https://github.com/cockroachdb/cockroach/files/4766038/stress.log)

**Comment by andreimatei** [comment]
I haven't gotten to it today, but I can take it tomorrow. You can leave it to me.
