### ISSUE TITLE
sql: pgcli compatibility broken in 20.1 due to vtable lookup join

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#50157]
[pgcli](https://github.com/dbcli/pgcli) is a Postgres CLI implemented in Python.

It works fine against v19.2. However, autocomplete functionality is broken when using v20.1: 

```
❯ pgcli -h localhost -p 26257 -U root -w -d defaultdb
Server: PostgreSQL 9.5.0
Version: 3.0.0
Chat: https://gitter.im/dbcli/pgcli
Home: http://pgcli.com
root@localhost:defaultdb> Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/completion_refresher.py", line 65, in _bg_refresh
    refresher(completer, executor)
  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/completion_refresher.py", line 114, in refresh_tables
    completer.extend_foreignkeys(executor.foreignkeys())
  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgcompleter.py", line 272, in extend_foreignkeys
    for fk in fk_data:
  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 671, in foreignkeys
    cur.execute(query)
psycopg2.InternalError: use of crdb_internal_vtable_pk column not allowed.
```
The `use of crdb_internal_vtable_pk column not allowed.` error is caused by [the query pgcli makes to gather all foreign keys](https://github.com/dbcli/pgcli/blob/0c24e8bda226f3dbd6ccb0381515a9c903847249/pgcli/pgexecute.py#L635):

```
SELECT
  s_p.nspname AS parentschema,
  t_p.relname AS parenttable,
  unnest(
    (
      SELECT
        array_agg(attname ORDER BY i)
      FROM
        (
          SELECT
            unnest(confkey) AS attnum,
            generate_subscripts(confkey, 1) AS i
        )
          AS x
        JOIN pg_catalog.pg_attribute AS c USING (attnum)
      WHERE
        c.attrelid = fk.confrelid
    )
  )
    AS parentcolumn,
  s_c.nspname AS childschema,
  t_c.relname AS childtable,
  unnest(
    (
      SELECT
        array_agg(attname ORDER BY i)
      FROM
        (
          SELECT
            unnest(conkey) AS attnum,
            generate_subscripts(conkey, 1) AS i
        )
          AS x
        JOIN pg_catalog.pg_attribute AS c USING (attnum)
      WHERE
        c.attrelid = fk.conrelid
    )
  )
    AS childcolumn
FROM
  pg_catalog.pg_constraint AS fk
  JOIN pg_catalog.pg_class AS t_p ON t_p.oid = fk.confrelid
  JOIN pg_catalog.pg_namespace AS s_p ON
      s_p.oid = t_p.relnamespace
  JOIN pg_catalog.pg_class AS t_c ON t_c.oid = fk.conrelid
  JOIN pg_catalog.pg_namespace AS s_c ON
      s_c.oid = t_c.relnamespace
WHERE
  fk.contype = 'f';
```

**Comment by RaduBerinde** [comment]
I think it's this check, we can probably remove it:
https://github.com/cockroachdb/cockroach/blob/63507a4ee545f827d624b9f6c9c5b3f430d5e315/pkg/sql/opt_exec_factory.go#L728

This is the plan by the way:
```
  project
   └── project-set
        ├── group-by
        │    ├── left-join-apply
        │    │    ├── group-by
        │    │    │    ├── left-join-apply
        │    │    │    │    ├── inner-join (hash)
        │    │    │    │    │    ├── scan s_c
        │    │    │    │    │    ├── inner-join (hash)
        │    │    │    │    │    │    ├── scan s_p
        │    │    │    │    │    │    ├── inner-join (lookup pg_class@pg_class_oid_idx)
        │    │    │    │    │    │    │    ├── lookup columns are key
        │    │    │    │    │    │    │    ├── inner-join (lookup pg_class@pg_class_oid_idx)
        │    │    │    │    │    │    │    │    ├── lookup columns are key
        │    │    │    │    │    │    │    │    ├── select
        │    │    │    │    │    │    │    │    │    ├── scan fk
        │    │    │    │    │    │    │    │    │    └── filters
        │    │    │    │    │    │    │    │    │         └── contype = 'f'
        │    │    │    │    │    │    │    │    └── filters (true)
        │    │    │    │    │    │    │    └── filters (true)
        │    │    │    │    │    │    └── filters
        │    │    │    │    │    │         └── s_p.oid = t_p.relnamespace
        │    │    │    │    │    └── filters
        │    │    │    │    │         └── s_c.oid = t_c.relnamespace
        │    │    │    │    ├── window partition=() ordering=+97 opt(96,98-119)
        │    │    │    │    │    ├── inner-join (hash)
        │    │    │    │    │    │    ├── scan c
        │    │    │    │    │    │    ├── project-set
        │    │    │    │    │    │    │    ├── values
        │    │    │    │    │    │    │    │    └── ()
        │    │    │    │    │    │    │    └── zip
        │    │    │    │    │    │    │         ├── unnest(confkey)
        │    │    │    │    │    │    │         └── generate_subscripts(confkey, 1)
        │    │    │    │    │    │    └── filters
        │    │    │    │    │    │         ├── unnest = attnum
        │    │    │    │    │    │         └── attrelid = confrelid
        │    │    │    │    │    └── windows
        │    │    │    │    │         └── array-agg [frame="range from unbounded to unbounded"]
        │    │    │    │    │              └── attname
        │    │    │    │    └── filters (true)
        │    │    │    └── aggregations
        │    │    │         ├── const-not-null-agg
        │    │    │         │    └── array_agg
        │    │    │         ├── const-agg
        │    │    │         │    └── conrelid
        │    │    │         ├── const-agg
        │    │    │         │    └── conkey
        │    │    │         ├── const-agg
        │    │    │         │    └── t_p.relname
        │    │    │         ├── const-agg
        │    │    │         │    └── s_p.nspname
        │    │    │         ├── const-agg
        │    │    │         │    └── t_c.relname
        │    │    │         └── const-agg
        │    │    │              └── s_c.nspname
        │    │    ├── window partition=() ordering=+123 opt(122,124-145)
        │    │    │    ├── inner-join (hash)
        │    │    │    │    ├── scan c
        │    │    │    │    ├── project-set
        │    │    │    │    │    ├── values
        │    │    │    │    │    │    └── ()
        │    │    │    │    │    └── zip
        │    │    │    │    │         ├── unnest(conkey)
        │    │    │    │    │         └── generate_subscripts(conkey, 1)
        │    │    │    │    └── filters
        │    │    │    │         ├── unnest = attnum
        │    │    │    │         └── attrelid = conrelid
        │    │    │    └── windows
        │    │    │         └── array-agg [frame="range from unbounded to unbounded"]
        │    │    │              └── attname
        │    │    └── filters (true)
        │    └── aggregations
        │         ├── const-not-null-agg
        │         │    └── array_agg
        │         ├── const-agg
        │         │    └── t_p.relname
        │         ├── const-agg
        │         │    └── s_p.nspname
        │         ├── const-agg
        │         │    └── t_c.relname
        │         ├── const-agg
        │         │    └── s_c.nspname
        │         └── const-agg
        │              └── array_agg
        └── zip
             ├── unnest(array_agg)
             └── unnest(array_agg)
```

**Comment by jordanlewis** [comment]
Hmm, @RaduBerinde I'm not sure if it's okay to get rid of that check. The plan with opt,verbose contains a lot of instances of the `crdb_internal_vtable_pk` in various places that don't seem safe, like grouping columns in a group by. How did that column sneak in there? It looks like it's required by the `project-set` up top, but it doesn't seem right that the column should be present in any of these sets.

**Comment by RaduBerinde** [comment]
I thought that check is only meant to prevent the user from using the `crdb_internal_vtable_pk` directly, not to prevent any other type of badness, no? Why isn't it safe for the column to be used in a group by? There are decorrelation rules that push joins through group-bys and they have to append the key from one side to the grouping columns.

**Comment by jordanlewis** [comment]
I didn't think this column had a runtime value, so it seems kind of sketchy? But maybe it's fine. I see what you mean that we meant to only ban it from being explicitly selected.

**Comment by RaduBerinde** [comment]
Oh... I see.. if it doesn't have a real value that's a problem. Part of the problem is that we advertise this column as a key for the scan. We could stop doing that in `MakeTableFuncDep` if we had a way of knowing that we're dealing with a dummy column. We would also need a similar check in the rules that create lookup joins.

**Comment by jordanlewis** [comment]
I could also have the vtable code emit a counter value for this column, I suppose.

**Comment by RaduBerinde** [comment]
Yeah. We would still need to disallow lookup joins on that dummy column though (unless we actually can do a lookup from the counter), though I'm not sure that would ever happen in practice.
