### ISSUE TITLE
circleci: failed tests (14133): TestSendToOneClient TestComplexScenarios TestRangeSplitsWithConcurrentTxns TestTxnCoordSenderHeartbeat TestTxnCommit TestEnumerateIsolations TestTxnDBWriteSkewAnomaly TestNoSequenceCachePutOnRangeMismatchError 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5023]
The following test appears to have failed:

[#14133](https://circleci.com/gh/cockroachdb/cockroach/14133):

```
--- PASS: TestReplicaSetRandPerm (0.01s)
=== RUN   TestInvalidAddrLength
--- PASS: TestInvalidAddrLength (0.01s)
=== RUN   TestSendToOneClient
E160309 18:25:54.594025 rpc/context.go:146  rpc error: code = 13 desc = "transport is closing"
--- FAIL: TestSendToOneClient (5.15s)
	<autogenerated>:31: Leaked goroutine: goroutine 486 [select]:
		google.golang.org/grpc/transport.(*serverHandlerTransport).runStream(0xc820490060)
			/go/src/google.golang.org/grpc/transport/handler_server.go:345 +0x154
		google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams(0xc820490060, 0xc8203956b0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:335 +0x112b
		google.golang.org/grpc.(*Server).serveStreams(0xc820088180, 0x7fc3efabdc18, 0xc820490060)
			/go/src/google.golang.org/grpc/server.go:325 +0x1dd
		google.golang.org/grpc.(*Server).ServeHTTP(0xc820088180, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
			/go/src/google.golang.org/grpc/server.go:368 +0x1c0
		net/http.serverHandler.ServeHTTP(0xc8208fe080, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
--
I160309 18:26:01.905852 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial 127.0.0.1:41639: grpc: the client connection is closing; please retry.
I160309 18:26:01.936746 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial 127.0.0.1:59184: grpc: the client connection is closing; please retry.
I160309 18:26:01.937184 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial 127.0.0.1:43362: grpc: the client connection is closing; please retry.
I160309 18:26:01.941784 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial 127.0.0.1:55148: grpc: the client connection is closing; please retry.
I160309 18:26:01.942523 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial 127.0.0.1:58546: grpc: the client connection is closing; please retry.
--- FAIL: TestComplexScenarios (5.55s)
	<autogenerated>:31: Leaked goroutine: goroutine 486 [select]:
		google.golang.org/grpc/transport.(*serverHandlerTransport).runStream(0xc820490060)
			/go/src/google.golang.org/grpc/transport/handler_server.go:345 +0x154
		google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams(0xc820490060, 0xc8203956b0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:335 +0x112b
		google.golang.org/grpc.(*Server).serveStreams(0xc820088180, 0x7fc3efabdc18, 0xc820490060)
			/go/src/google.golang.org/grpc/server.go:325 +0x1dd
		google.golang.org/grpc.(*Server).ServeHTTP(0xc820088180, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
			/go/src/google.golang.org/grpc/server.go:368 +0x1c0
		net/http.serverHandler.ServeHTTP(0xc8208fe080, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
--
I160309 18:26:07.795253 kv/range_cache.go:189  adding descriptor: key=/Meta2/"s" desc=range_id:5 start_key:"l" end_key:"s" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160309 18:26:07.796913 storage/replica.go:1238  reproposing 1 commands after empty entry
I160309 18:26:07.797169 kv/range_cache.go:189  adding descriptor: key=/Meta2/"s" desc=range_id:5 start_key:"l" end_key:"s" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160309 18:26:07.797451 kv/range_cache.go:313  clearing overlapping descriptor: key=/Meta2/"s" desc=range_id:5 start_key:"l" end_key:"s" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160309 18:26:07.824483 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- FAIL: TestRangeSplitsWithConcurrentTxns (6.11s)
	<autogenerated>:31: Leaked goroutine: goroutine 486 [select]:
		google.golang.org/grpc/transport.(*serverHandlerTransport).runStream(0xc820490060)
			/go/src/google.golang.org/grpc/transport/handler_server.go:345 +0x154
		google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams(0xc820490060, 0xc8203956b0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:335 +0x112b
		google.golang.org/grpc.(*Server).serveStreams(0xc820088180, 0x7fc3efabdc18, 0xc820490060)
			/go/src/google.golang.org/grpc/server.go:325 +0x1dd
		google.golang.org/grpc.(*Server).ServeHTTP(0xc820088180, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
			/go/src/google.golang.org/grpc/server.go:368 +0x1c0
		net/http.serverHandler.ServeHTTP(0xc8208fe080, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
--
I160309 18:26:14.628974 storage/replica.go:1706  [node=1,store=1,range=1] gossiping sentinel from store 1, range 1
I160309 18:26:14.629273 storage/replica.go:1712  [node=1,store=1,range=1] gossiping first range from store 1, range 1
I160309 18:26:14.641129 stopper.go:273  draining; tasks left:
1      kv/txn_coord_sender.go:825
I160309 18:26:14.642428 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- FAIL: TestTxnCoordSenderHeartbeat (5.09s)
	<autogenerated>:31: Leaked goroutine: goroutine 486 [select]:
		google.golang.org/grpc/transport.(*serverHandlerTransport).runStream(0xc820490060)
			/go/src/google.golang.org/grpc/transport/handler_server.go:345 +0x154
		google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams(0xc820490060, 0xc8203956b0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:335 +0x112b
		google.golang.org/grpc.(*Server).serveStreams(0xc820088180, 0x7fc3efabdc18, 0xc820490060)
			/go/src/google.golang.org/grpc/server.go:325 +0x1dd
		google.golang.org/grpc.(*Server).ServeHTTP(0xc820088180, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
			/go/src/google.golang.org/grpc/server.go:368 +0x1c0
		net/http.serverHandler.ServeHTTP(0xc8208fe080, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
--
I160309 18:26:20.122255 kv/range_cache.go:189  adding descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160309 18:26:20.123269 kv/range_cache.go:189  adding descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160309 18:26:20.123591 kv/range_cache.go:313  clearing overlapping descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160309 18:26:20.127266 storage/replica_command.go:453  auto-gc'ed 3d759f25 (1 intents)
I160309 18:26:20.132460 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- FAIL: TestTxnCommit (5.04s)
	<autogenerated>:31: Leaked goroutine: goroutine 486 [select]:
		google.golang.org/grpc/transport.(*serverHandlerTransport).runStream(0xc820490060)
			/go/src/google.golang.org/grpc/transport/handler_server.go:345 +0x154
		google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams(0xc820490060, 0xc8203956b0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:335 +0x112b
		google.golang.org/grpc.(*Server).serveStreams(0xc820088180, 0x7fc3efabdc18, 0xc820490060)
			/go/src/google.golang.org/grpc/server.go:325 +0x1dd
		google.golang.org/grpc.(*Server).ServeHTTP(0xc820088180, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
			/go/src/google.golang.org/grpc/server.go:368 +0x1c0
		net/http.serverHandler.ServeHTTP(0xc8208fe080, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
--
I160309 18:26:25.318686 storage/replica_command.go:453  auto-gc'ed 55d491e9 (1 intents)
I160309 18:26:25.323539 storage/replica_command.go:453  auto-gc'ed de1d8e5f (1 intents)
I160309 18:26:25.328445 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- PASS: TestTxnDurations (0.07s)
=== RUN   TestEnumerateIsolations
--- FAIL: TestEnumerateIsolations (5.02s)
	<autogenerated>:31: Leaked goroutine: goroutine 486 [select]:
		google.golang.org/grpc/transport.(*serverHandlerTransport).runStream(0xc820490060)
			/go/src/google.golang.org/grpc/transport/handler_server.go:345 +0x154
		google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams(0xc820490060, 0xc8203956b0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:335 +0x112b
		google.golang.org/grpc.(*Server).serveStreams(0xc820088180, 0x7fc3efabdc18, 0xc820490060)
			/go/src/google.golang.org/grpc/server.go:325 +0x1dd
		google.golang.org/grpc.(*Server).ServeHTTP(0xc820088180, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
			/go/src/google.golang.org/grpc/server.go:368 +0x1c0
		net/http.serverHandler.ServeHTTP(0xc8208fe080, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
--
I160309 18:26:56.128450 kv/txn_correctness_test.go:103  executing R0(B)
I160309 18:26:56.129490 kv/txn_correctness_test.go:555  PASSED: iso=[SNAPSHOT SNAPSHOT], pri=[2 1], history="SC2.1(A-C)[] I2.1(B)[1] SUM2.1(B)[0 ts={62135596800 0 44119392}] C2.1 SC1.1(A-C)[1] I1.1(A)[1] SUM1.1(A)[1 ts={62135596800 0 44119392}] C1.1"
I160309 18:26:56.129621 stopper.go:273  draining; tasks left:
1      kv/txn_coord_sender.go:825
I160309 18:26:56.130490 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- FAIL: TestTxnDBWriteSkewAnomaly (12.66s)
	<autogenerated>:31: Leaked goroutine: goroutine 486 [select, 1 minutes]:
		google.golang.org/grpc/transport.(*serverHandlerTransport).runStream(0xc820490060)
			/go/src/google.golang.org/grpc/transport/handler_server.go:345 +0x154
		google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams(0xc820490060, 0xc8203956b0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:335 +0x112b
		google.golang.org/grpc.(*Server).serveStreams(0xc820088180, 0x7fc3efabdc18, 0xc820490060)
			/go/src/google.golang.org/grpc/server.go:325 +0x1dd
		google.golang.org/grpc.(*Server).ServeHTTP(0xc820088180, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
			/go/src/google.golang.org/grpc/server.go:368 +0x1c0
		net/http.serverHandler.ServeHTTP(0xc8208fe080, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
--
W160309 18:27:17.160762 storage/replica.go:1798  [node=1,store=1,range=1] failed to resolve intents: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:700: node 1 stopped
I160309 18:27:18.160310 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:37208: getsockopt: connection refused"; Reconnecting to "127.0.0.1:37208"
I160309 18:27:20.025506 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:37208: getsockopt: connection refused"; Reconnecting to "127.0.0.1:37208"
I160309 18:27:20.026001 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial 127.0.0.1:37208: grpc: timed out trying to connect; please retry.
I160309 18:27:20.026262 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- FAIL: TestNoSequenceCachePutOnRangeMismatchError (8.79s)
	<autogenerated>:31: Leaked goroutine: goroutine 486 [select, 1 minutes]:
		google.golang.org/grpc/transport.(*serverHandlerTransport).runStream(0xc820490060)
			/go/src/google.golang.org/grpc/transport/handler_server.go:345 +0x154
		google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams(0xc820490060, 0xc8203956b0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:335 +0x112b
		google.golang.org/grpc.(*Server).serveStreams(0xc820088180, 0x7fc3efabdc18, 0xc820490060)
			/go/src/google.golang.org/grpc/server.go:325 +0x1dd
		google.golang.org/grpc.(*Server).ServeHTTP(0xc820088180, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
			/go/src/google.golang.org/grpc/server.go:368 +0x1c0
		net/http.serverHandler.ServeHTTP(0xc8208fe080, 0x7fc3efabdb90, 0xc82006c120, 0xc820357a40)
--
I160309 18:27:26.005595 kv/range_cache.go:228  evict cached descriptor: key=/Meta1/"b" desc=<nil>
I160309 18:27:26.005726 client/db.go:422  failed batch: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:700: node 1 stopped
W160309 18:27:26.005835 storage/replica.go:1798  [node=1,store=1,range=1] failed to resolve intents: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:700: node 1 stopped
I160309 18:27:26.007184 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- PASS: TestPropagateTxnOnPushError (0.54s)
FAIL
FAIL	github.com/cockroachdb/cockroach/kv	92.784s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestKeyNext
--- PASS: TestKeyNext (0.00s)
=== RUN   TestKeyPrefixEnd
--- PASS: TestKeyPrefixEnd (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Related to #5020
