### ISSUE TITLE
circleci: failed tests (14218): Example_cput

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5045]
The following test appears to have failed:

[#14218](https://circleci.com/gh/cockroachdb/cockroach/14218):

```
I160310 03:34:35.701730 stopper.go:273  draining; tasks left:
1      storage/queue.go:375
1      server/node.go:699
E160310 03:34:35.701949 client/txn.go:346  failure aborting transaction: kv/txn_coord_sender.go:383: transaction is already committed or aborted; abort caused by: node unavailable; try another peer
E160310 03:34:35.702195 storage/queue.go:441  [split] range=1 [/Min-/Table/11): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Table/11) at key "/Table/14/0": storage/replica_command.go:1379: split at key /Table/14 failed: node unavailable; try another peer
F160310 03:34:35.702750 cli/cli_test.go:65  Could not start server: server/testserver.go:274: had 4 ranges at startup, expected 5
goroutine 1 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xece72e200, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:868 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x2584c60, 0x3, 0x1f378ec, 0xf, 0x41, 0xc820859920, 0x55)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:732 +0x178
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x1883d20, 0x1a, 0xc8209f7978, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x1883d20, 0x1a, 0xc8209f7978, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x1883d20, 0x1a, 0xc8209f7978, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x66
--
	/usr/local/go/src/testing/example.go:36 +0x314
testing.(*M).Run(0xc8209f7ec8, 0x85)
	/usr/local/go/src/testing/testing.go:516 +0xbd
main.main()
	github.com/cockroachdb/cockroach/cli/_test/_testmain.go:96 +0x117
FAIL	github.com/cockroachdb/cockroach/cli	19.260s
=== RUN   TestClientTxnSequenceNumber
--- PASS: TestClientTxnSequenceNumber (0.00s)
=== RUN   TestTxnRequestTxnTimestamp
--- PASS: TestTxnRequestTxnTimestamp (0.00s)
=== RUN   TestTxnResetTxnOnAbort
--- PASS: TestTxnResetTxnOnAbort (0.00s)
=== RUN   TestTransactionConfig
--- PASS: TestTransactionConfig (0.00s)
=== RUN   TestCommitReadOnlyTransaction
--- PASS: TestCommitReadOnlyTransaction (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
dupe #5043
