### ISSUE TITLE
circleci: failed tests (14240): TestDockerC 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5054]
The following test appears to have failed:

[#14240](https://circleci.com/gh/cockroachdb/cockroach/14240):

```
I160310 05:34:25.760764 server/node.go:464  bootstrapped store store=2:2 ([]=/data2.0)
I160310 05:34:26.162895 storage/replica_command.go:1260  range 1: new leader lease replica {2 2 2} 2016-03-10 05:34:26 +0000 UTC +1.007s
I160310 05:34:26.544216 storage/stores.go:304  wrote 2 node addresses to persistent storage
I160310 05:34:27.222763 storage/queue.go:491  [replicate] purgatory is now empty
E160310 05:34:27.275370 storage/queue.go:441  [replicate] range=1 [/Min-/Table/11): error: storage/replica_command.go:2087: change replicas of 1 failed: unexpected value: raw_bytes:"\267\343%\344\003\010\001\022\000\032\001\223\"\006\010\001\020\001\030\001\"\006\010\002\020\002\030\002\"\006\010\003\020\003\030\003(\004" timestamp:<wall_time:1457588067411085939 logical:1 > 
panic: checksums: e = [78 169 224 37 243 83 40 131 141 194 58 64 164 122 87 115 162 233 41 135 128 213 51 86 88 74 134 117 168 160 111 209 195 149 229 88 39 134 69 153 188 169 192 220 134 171 117 88 193 152 220 63 169 83 244 241 7 88 42 156 137 240 233 72], v = [13 15 15 172 241 38 100 224 24 253 156 145 51 228 76 74 70 251 32 78 179 53 202 81 238 15 102 110 122 19 233 66 82 113 158 154 114 184 103 178 65 187 43 67 110 190 255 180 199 36 38 63 36 237 202 6 226 201 230 74 102 31 142 7]

goroutine 84 [running]:
panic(0x13e32c0, 0xc8208c7f90)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/storage.(*Replica).VerifyChecksum(0xc820544fc0, 0x7f40398caab0, 0xc8208c02d0, 0xc820863030, 0x143a64a1c38e4ab8, 0x0, 0x0, 0x0, 0x2, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1496 +0x829
github.com/cockroachdb/cockroach/storage.(*Replica).executeCmd(0xc820544fc0, 0x7f40398caab0, 0xc8208c02d0, 0xc820863030, 0x143a64a1c38e4ab8, 0x0, 0x0, 0x0, 0x2, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:160 +0x1bd2
github.com/cockroachdb/cockroach/storage.(*Replica).executeBatch(0xc820544fc0, 0x7f40398caab0, 0xc8208c02d0, 0xc820863030, 0x143a64a1c38e4ab8, 0x0, 0x0, 0x0, 0x2, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1605 +0x3e0
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommandInBatch(0xc820544fc0, 0x7f40399164c8, 0xc8208c0270, 0x31, 0x100000001, 0xc800000001, 0x143a64a1c38e4ab8, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1468 +0x433
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommand(0xc820544fc0, 0x7f40399164c8, 0xc8208c0270, 0x31, 0x100000001, 0xc800000001, 0x143a64a1c38e4ab8, 0x0, 0x0, 0x0, ...)
sql:       postgresql://root@roach2:26257?sslcert=%2Fcerts%2Froot.client.crt&sslkey=%2Fcerts%2Froot.client.key&sslmode=verify-full&sslrootcert=%2Fcerts%2Fca.crt
logs:      /logs/roach2
store[0]:  path=/data3.0
I160310 05:34:26.548289 server/status/runtime.go:137  runtime stats: 44 goroutines, 3.64MiB active, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (2x)
I160310 05:34:26.552026 server/node.go:464  bootstrapped store store=3:3 ([]=/data3.0)
panic: checksums: e = [78 169 224 37 243 83 40 131 141 194 58 64 164 122 87 115 162 233 41 135 128 213 51 86 88 74 134 117 168 160 111 209 195 149 229 88 39 134 69 153 188 169 192 220 134 171 117 88 193 152 220 63 169 83 244 241 7 88 42 156 137 240 233 72], v = [143 130 226 2 150 79 221 51 194 34 188 194 217 109 106 217 247 215 182 35 107 100 54 218 184 22 164 228 67 231 22 205 137 40 250 87 112 150 138 184 242 137 198 121 46 69 187 19 16 232 101 114 82 235 30 44 3 96 131 204 199 158 213 9]

goroutine 39 [running]:
panic(0x13e32c0, 0xc8201bb670)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/storage.(*Replica).VerifyChecksum(0xc82017cc40, 0x7f23ca3fa2f8, 0xc820636fc0, 0xc8207b3030, 0x143a64a1c38e4ab8, 0x0, 0x0, 0x0, 0x2, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1496 +0x829
github.com/cockroachdb/cockroach/storage.(*Replica).executeCmd(0xc82017cc40, 0x7f23ca3fa2f8, 0xc820636fc0, 0xc8207b3030, 0x143a64a1c38e4ab8, 0x0, 0x0, 0x0, 0x2, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:160 +0x1bd2
github.com/cockroachdb/cockroach/storage.(*Replica).executeBatch(0xc82017cc40, 0x7f23ca3fa2f8, 0xc820636fc0, 0xc8207b3030, 0x143a64a1c38e4ab8, 0x0, 0x0, 0x0, 0x2, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1605 +0x3e0
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommandInBatch(0xc82017cc40, 0x7f23ca3f8d60, 0xc820636f60, 0x31, 0x100000001, 0xc800000001, 0x143a64a1c38e4ab8, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1468 +0x433
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommand(0xc82017cc40, 0x7f23ca3f8d60, 0xc820636f60, 0x31, 0x100000001, 0xc800000001, 0x143a64a1c38e4ab8, 0x0, 0x0, 0x0, ...)
E160310 05:34:35.481846 acceptance/cluster/localcluster.go:463  node=1 status=die
...................................................................................................................................................................................................................................................................................................................................................................................I160310 05:34:58.107553 acceptance/cluster/docker.go:89  ImagePull cockroachdb/postgres-test:20160203-140220 complete
I160310 05:34:59.131518 acceptance/cluster/localcluster.go:592  stopping
I160310 05:35:00.633550 acceptance/cluster/localcluster.go:632  node 1: stderr at /tmp/circle-artifacts.S0Whply/acceptance/TestDockerC/roach1/stderr.2016-03-10T05_35_00Z.log
I160310 05:35:01.061563 acceptance/cluster/localcluster.go:632  node 2: stderr at /tmp/circle-artifacts.S0Whply/acceptance/TestDockerC/roach2/stderr.2016-03-10T05_35_01Z.log
--- FAIL: TestDockerC (38.46s)
	localcluster.go:569: unexpected extra event &{2 die} (after [])
=== RUN   TestClusterRecovery
I160310 05:35:01.920445 acceptance/cluster/localcluster.go:261  Initializing Cluster:
Cluster Setup: AdHoc 3x1
Duration: 5s, Stall: 2m0s
Node 0 - Store 0
Node 1 - Store 0
Node 2 - Store 0
Total Nodes Count:3, Total Store Count:3
I160310 05:35:01.920610 acceptance/cluster/docker.go:74  ImagePull cockroachdb/builder:20160305-182433 starting
--
W160310 05:35:11.002358 acceptance/chaos_test.go:247  round 1: monkey sleeping while cluster recovers...
E160310 05:35:11.610281 acceptance/cluster/localcluster.go:463  node=2 status=die
E160310 05:35:11.977436 acceptance/cluster/localcluster.go:463  node=1 status=die
I160310 05:35:12.538877 acceptance/chaos_test.go:179  client 2 shutting down
I160310 05:35:12.539023 acceptance/chaos_test.go:179  client 1 shutting down
panic: test timed out after 5m0s

goroutine 313 [running]:
panic(0xaba8a0, 0xc8203860a0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 3 minutes]:
testing.RunTests(0xe9a708, 0x13403a0, 0xf, 0xf, 0xf6761e983d041b00)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820038f08, 0xe99650)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc820038f08)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:48 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:80 +0x114

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [runnable]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x135cc20)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1010 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 8 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:39 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:47 +0x30

goroutine 7 [syscall, 4 minutes]:
os/signal.signal_recv(0x6)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 217 [runnable]:
time.NewTimer(0x3b9aca00, 0x18)
	/usr/local/go/src/time/sleep.go:67 +0x30
time.After(0x3b9aca00, 0xc821a747e0)
	/usr/local/go/src/time/sleep.go:110 +0x21
github.com/cockroachdb/cockroach/acceptance.waitClientsStop(0x3, 0xc82030ad80, 0x1bf08eb000)
	/go/src/github.com/cockroachdb/cockroach/acceptance/chaos_test.go:273 +0x1e1
github.com/cockroachdb/cockroach/acceptance.testClusterRecoveryInner(0xc8202206c0, 0x7f35130024d0, 0xc820060750, 0xc820386b80, 0x9, 0xc820163680, 0x1, 0x1, 0x12a05f200, 0x1bf08eb000)
	/go/src/github.com/cockroachdb/cockroach/acceptance/chaos_test.go:351 +0x72f
github.com/cockroachdb/cockroach/acceptance.runTestOnConfigs.func1(0xc8202206c0, 0xc82029dec8, 0xe996a8)
	/go/src/github.com/cockroachdb/cockroach/acceptance/util_test.go:127 +0xb1
--
testing.tRunner(0xc8202206c0, 0x13403d0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 21 [select, 4 minutes, locked to thread]:
runtime.gopark(0xe9af08, 0xc820023f28, 0xd2a5b0, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820023f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820023f28)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 12 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f351303ee90, 0x72, 0xc8201f5000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201def40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201def40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201deee0, 0xc8201f5000, 0x1000, 0x1000, 0x0, 0x7f3513033050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a368, 0xc8201f5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201a76c0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 13 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc8201a76c0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 240 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc8200600d0)
	/usr/local/go/src/net/http/transport.go:1178 +0xd52
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 137 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f351303eb90, 0x72, 0xc82025e000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201de220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201de220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201de1c0, 0xc82025e000, 0x1000, 0x1000, 0x0, 0x7f3513033050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a030, 0xc82025e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820060270)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 312 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc82033ca50)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 241 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc8200600d0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 138 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc820060270)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 221 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc8200608f0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 220 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f351303ec50, 0x72, 0xc8202aa000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820252f40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820252f40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820252ee0, 0xc8202aa000, 0x1000, 0x1000, 0x0, 0x7f3513033050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f6288, 0xc8202aa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200608f0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 242 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f351303ed10, 0x72, 0xc820299000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202a6140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202a6140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202a60e0, 0xc820299000, 0x1000, 0x1000, 0x0, 0x7f3513033050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f6000, 0xc820299000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).monitor(0xc820060750)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:500 +0x218
created by github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:534 +0x3b3

goroutine 258 [select, 3 minutes]:
github.com/docker/engine-api/client/transport/cancellable.Do.func3(0x7f3513002138, 0xc820307100, 0xc820386060, 0xc8202ee540)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:78 +0xef
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:84 +0x336

goroutine 276 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8204b53f0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 290 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc820468160)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 274 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8204b51e0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 277 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f351303e7d0, 0x72, 0xc820262400)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201df4f0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201df4f0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201df490, 0xc820262400, 0x400, 0x400, 0x0, 0x7f3513033050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f63b8, 0xc820262400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
github.com/cockroachdb/cockroach/acceptance.transferMoneyLoop(0x0, 0xc82030ad80, 0x3e7, 0x3e7)
	/go/src/github.com/cockroachdb/cockroach/acceptance/chaos_test.go:167 +0xb9
created by github.com/cockroachdb/cockroach/acceptance.testClusterRecoveryInner
	/go/src/github.com/cockroachdb/cockroach/acceptance/chaos_test.go:336 +0x53f

goroutine 294 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc820468420)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 285 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc82033c840)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 323 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8204696b0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
see #5051
