### ISSUE TITLE
circleci: failed tests (14251): TestRetryableError TestNoSequenceCachePutOnRangeMismatchError 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5058]
The following test appears to have failed:

[#14251](https://circleci.com/gh/cockroachdb/cockroach/14251):

```
=== RUN   TestSendToOneClient
--- PASS: TestSendToOneClient (0.14s)
=== RUN   TestRetryableError
E160310 06:42:07.638274 rpc/context.go:155  rpc error: code = 4 desc = "context deadline exceeded"
I160310 06:42:07.643152 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial 127.0.0.1:60021: grpc: the client connection is closing; please retry.
--- FAIL: TestRetryableError (5.14s)
	send_test.go:154: &{127.0.0.1:60021 127.0.0.1 {{} <nil> <nil> 0xc8201f6720 false false { <nil> [0xc8201a1900] 3000000000}}} has unexpectedly shut down
	<autogenerated>:31: Leaked goroutine: goroutine 626 [chan receive]:
		github.com/cockroachdb/cockroach/rpc.NewContext.func1()
			/go/src/github.com/cockroachdb/cockroach/rpc/context.go:99 +0x68
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8203a6070, 0xc820480120)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x60
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x70
	<autogenerated>:31: Leaked goroutine: goroutine 627 [chan receive]:
		github.com/cockroachdb/cockroach/util.ListenAndServe.func1()
--
W160310 06:43:06.866888 storage/replica.go:1809  [node=1,store=1,range=1] failed to resolve intents: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:700: node 1 stopped
I160310 06:43:07.865414 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35764: getsockopt: connection refused"; Reconnecting to "127.0.0.1:35764"
I160310 06:43:09.693407 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35764: getsockopt: connection refused"; Reconnecting to "127.0.0.1:35764"
I160310 06:43:09.693757 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial 127.0.0.1:35764: grpc: timed out trying to connect; please retry.
I160310 06:43:09.693964 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- FAIL: TestNoSequenceCachePutOnRangeMismatchError (9.60s)
	<autogenerated>:31: Leaked goroutine: goroutine 626 [chan receive, 1 minutes]:
		github.com/cockroachdb/cockroach/rpc.NewContext.func1()
			/go/src/github.com/cockroachdb/cockroach/rpc/context.go:99 +0x68
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8203a6070, 0xc820480120)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x60
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x70
	<autogenerated>:31: Leaked goroutine: goroutine 627 [chan receive, 1 minutes]:
		github.com/cockroachdb/cockroach/util.ListenAndServe.func1()
			/go/src/github.com/cockroachdb/cockroach/util/net.go:45 +0x65
--
I160310 06:43:17.703322 kv/dist_sender_server_test.go:594  Waiting for the txn commit
I160310 06:43:17.706302 storage/replica_command.go:458  auto-gc'ed 9682a460 (1 intents)
I160310 06:43:17.721808 storage/replica_command.go:458  auto-gc'ed 4e2f2ebd (1 intents)
I160310 06:43:17.725743 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- PASS: TestPropagateTxnOnPushError (1.71s)
FAIL
FAIL	github.com/cockroachdb/cockroach/kv	72.170s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestKeyNext
--- PASS: TestKeyNext (0.00s)
=== RUN   TestKeyPrefixEnd
--- PASS: TestKeyPrefixEnd (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
unable to repro
