### ISSUE TITLE
opt: getNodeColumnOrdinal() column not in input

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#50746]
From [this Roachtest run](https://teamcity.cockroachdb.com/viewLog.html?buildId=2041122&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=artifacts&branch_Cockroach_Nightlies=%3Cdefault%3E#%2Fhibernate%2Frun_1%2Flogs%2Freport%2Fresults), the Hibernate test `org.hibernate.test.legacy.MasterDetailTest#testMasterDetail` failed.

This was testing against `CockroachDB v20.2.0-alpha.1-664-gd3791a81c0`.

The failure described here happens very rarely. Most of the time the test passes. I only saw this error once over several days of this test running nightly.

The stack trace is:

```
org.hibernate.exception.GenericJDBCException: could not extract ResultSet
 at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
 at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
 at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
 at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
 at org.hibernate.loader.Loader.getResultSet(Loader.java:2292)
 at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2050)
 at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
 at org.hibernate.hql.internal.classic.QueryTranslatorImpl.iterate(QueryTranslatorImpl.java:1056)
 at org.hibernate.engine.query.spi.HQLQueryPlan.performIterate(HQLQueryPlan.java:320)
 at org.hibernate.internal.SessionImpl.iterateFilter(SessionImpl.java:1759)
 at org.hibernate.query.internal.CollectionFilterImpl.iterate(CollectionFilterImpl.java:66)
 at org.hibernate.test.legacy.MasterDetailTest.testMasterDetail(MasterDetailTest.java:455)

Caused by: org.postgresql.util.PSQLException: ERROR: internal error: column 3 not in input
Detail: stack trace:
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:103: getNodeColumnOrdinal()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:130: sqlOrdering()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1242: buildSort()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:210: buildRelational()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1201: buildLimitOffset()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:207: buildRelational()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1271: buildIndexJoin()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:213: buildRelational()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1067: buildGroupByInput()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:937: buildGroupBy()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:200: buildRelational()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:136: build()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:105: Build()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:215: makeOptimizerPlan()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:838: makeExecPlan()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:727: dispatchToExecutionEngine()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:500: execStmtInOpenState()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:99: execStmt()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1418: execCmd()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1285: run()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:490: ServeConn()
 /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:595: func1()
 /usr/local/go/src/runtime/asm_amd64.s:1357: goexit()

 Hint: You have encountered an unexpected error.

 Please check the public issue tracker to check whether this problem is
 already tracked. If you cannot find it there, please report the error
 with details by creating a new issue.

 If you would rather not post publicly, please contact us directly
 using the support form. We appreciate your feedback.

 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
 at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
 at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
 at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
 at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
 at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
 at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
 at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57) ... 23 more
 ```

This is the schema used by this test:

```
root@:26257/defaultdb> show create table detail;
  table_name |                                                create_statement
-------------+-----------------------------------------------------------------------------------------------------------------
  detail     | CREATE TABLE detail (
             |     detail_key_column INT8 NOT NULL,
             |     x INT4 NOT NULL,
             |     i INT4 NOT NULL,
             |     master_key INT8 NOT NULL,
             |     more_master_key INT8 NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (detail_key_column ASC),
             |     CONSTRAINT cc FOREIGN KEY (master_key) REFERENCES master(master_key_column),
             |     CONSTRAINT fk15juufw00u0mv5w1nivigp178 FOREIGN KEY (more_master_key) REFERENCES master(master_key_column),
             |     UNIQUE INDEX uk (x ASC, i ASC, master_key ASC),
             |     INDEX detail_auto_index_cc (master_key ASC),
             |     INDEX detail_auto_index_fk15juufw00u0mv5w1nivigp178 (more_master_key ASC),
             |     FAMILY "primary" (detail_key_column, x, i, master_key, more_master_key)
             | )

root@:26257/defaultdb> show create table master;
  table_name |                                              create_statement
-------------+-------------------------------------------------------------------------------------------------------------
  master     | CREATE TABLE master (
             |     master_key_column INT8 NOT NULL,
             |     version INT4 NOT NULL,
             |     name VARCHAR(255) NULL,
             |     x INT4 NULL,
             |     big_dec DECIMAL(7,3) NULL,
             |     othermaster INT8 NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (master_key_column ASC),
             |     CONSTRAINT fkjy918ylifmde4gnlbhtfe92u0 FOREIGN KEY (othermaster) REFERENCES master(master_key_column),
             |     INDEX master_auto_index_fkjy918ylifmde4gnlbhtfe92u0 (othermaster ASC),
             |     FAMILY "primary" (master_key_column, version, name, x, big_dec, othermaster)
             | )
```

And the error was caused by this query
```
SELECT
  max(this.i) AS col_0_0_
FROM
  detail AS this
WHERE
  this.master_key = 1;
```

**Comment by RaduBerinde** [comment]
I believe this is a dup of #50689.
