### ISSUE TITLE
stress: failed test in cockroach/storage/storage.test: TestRestoreReplicas

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5084]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/e9f364bea3014b627b66e8dddcc79a4f3cbcfaad

Stress build found a failed test:

```
=== RUN   TestRestoreReplicas
W160310 06:23:59.827962 gossip/gossip.go:912  not connected to cluster; use --join to specify a connected node
W160310 06:23:59.830614 gossip/gossip.go:385  bad address {localhost 1}: gossip/resolver/resolver.go:95: unknown address network "localhost" for 1
I160310 06:23:59.830954 storage/replica_command.go:1249  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1.000s
W160310 06:23:59.831776 gossip/gossip.go:385  bad address {localhost 2}: gossip/resolver/resolver.go:95: unknown address network "localhost" for 2
I160310 06:23:59.832594 storage/replica.go:1085  raft: proposing ADD_REPLICA {2 2 2} for range 1
panic: gossip infostore's NodeID is 0

goroutine 4213 [running]:
panic(0x1578000, 0xc82019a1c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/gossip.(*infoStore).newInfo(0xc820170000, 0xc820bf5ab0, 0x10, 0x10, 0x1bf08eb000, 0xc800000001)
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:135 +0x84
github.com/cockroachdb/cockroach/gossip.(*Gossip).AddInfo(0xc8202b4280, 0x1940f40, 0x8, 0xc820bf5ab0, 0x10, 0x10, 0x1bf08eb000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:515 +0xca
github.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc8202321a0, 0x278a2a0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1700 +0xafd
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc8200d8800, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:806 +0x307
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:750 +0x59
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820057500, 0xc8202171c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62


ERROR: exit status 2
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
2 runs so far, 0 failures, over 25s
5 runs so far, 0 failures, over 30s
8 runs so far, 0 failures, over 35s
8 runs so far, 0 failures, over 40s
8 runs so far, 0 failures, over 45s
8 runs so far, 0 failures, over 50s
10 runs so far, 0 failures, over 55s
14 runs so far, 0 failures, over 1m0s
16 runs so far, 0 failures, over 1m5s
16 runs so far, 0 failures, over 1m10s
16 runs so far, 0 failures, over 1m15s
16 runs so far, 0 failures, over 1m20s
21 runs so far, 0 failures, over 1m25s
24 runs so far, 0 failures, over 1m30s
24 runs so far, 0 failures, over 1m35s
24 runs so far, 0 failures, over 1m40s
24 runs so far, 0 failures, over 1m45s
26 runs so far, 0 failures, over 1m50s
29 runs so far, 0 failures, over 1m55s
32 runs so far, 0 failures, over 2m0s
32 runs so far, 0 failures, over 2m5s
32 runs so far, 0 failures, over 2m10s
32 runs so far, 0 failures, over 2m15s
34 runs so far, 0 failures, over 2m20s
38 runs so far, 0 failures, over 2m25s
40 runs so far, 0 failures, over 2m30s
40 runs so far, 0 failures, over 2m35s
40 runs so far, 0 failures, over 2m40s
42 runs so far, 0 failures, over 2m45s
45 runs so far, 0 failures, over 2m50s
46 runs so far, 0 failures, over 2m55s
48 runs so far, 0 failures, over 3m0s
48 runs so far, 0 failures, over 3m5s
48 runs so far, 0 failures, over 3m10s
51 runs so far, 0 failures, over 3m15s
54 runs so far, 0 failures, over 3m20s
55 runs so far, 0 failures, over 3m25s
56 runs so far, 0 failures, over 3m30s
56 runs so far, 0 failures, over 3m35s
57 runs so far, 0 failures, over 3m40s
61 runs so far, 0 failures, over 3m45s
62 runs so far, 0 failures, over 3m50s
63 runs so far, 0 failures, over 3m55s
64 runs so far, 0 failures, over 4m0s
64 runs so far, 0 failures, over 4m5s
67 runs so far, 0 failures, over 4m10s
69 runs so far, 0 failures, over 4m15s
70 runs so far, 0 failures, over 4m20s
71 runs so far, 0 failures, over 4m25s
72 runs so far, 0 failures, over 4m30s
72 runs so far, 0 failures, over 4m35s
75 runs so far, 0 failures, over 4m40s
78 runs so far, 0 failures, over 4m45s
79 runs so far, 0 failures, over 4m50s
79 runs so far, 0 failures, over 4m55s
80 runs so far, 0 failures, over 5m0s
81 runs so far, 0 failures, over 5m5s
85 runs completed, 1 failures, over 5m10s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
#4821
