### ISSUE TITLE
circleci: failed tests (14288): TestNodeStatus

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5100]
The following test appears to have failed:

[#14288](https://circleci.com/gh/cockroachdb/cockroach/14288):

```
--- PASS: TestFlagUsage (0.01s)
=== RUN   TestNodeStatus
E160310 19:37:59.729185 storage/replica_consistency_queue.go:61  key range /Min-/Max outside of bounds of range /Min-/Table/11
E160310 19:38:16.522685 client/txn.go:346  failure aborting transaction: kv/txn_coord_sender.go:383: transaction is already committed or aborted; abort caused by: node unavailable; try another peer
E160310 19:38:16.523060 storage/queue.go:441  [split] range=1 [/Min-/Table/11): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Table/11) at key "/Table/13/0": storage/replica_command.go:1631: split at key /Table/13 failed: node unavailable; try another peer
F160310 19:38:16.523952 cli/cli_test.go:65  Could not start server: server/testserver.go:274: had 3 ranges at startup, expected 5
goroutine 119 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xece73c400, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:868 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x25b5160, 0x3, 0x1f64f57, 0xf, 0x41, 0xc820a1d2c0, 0x55)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:732 +0x178
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x18a6500, 0x1a, 0xc820ae3c98, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x18a6500, 0x1a, 0xc820ae3c98, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x18a6500, 0x1a, 0xc820ae3c98, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x66
--
	/go/src/github.com/cockroachdb/cockroach/cli/cli_test.go:763 +0xd4
testing.tRunner(0xc8204e4120, 0x2257d30)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
FAIL	github.com/cockroachdb/cockroach/cli	17.388s
=== RUN   TestClientTxnSequenceNumber
--- PASS: TestClientTxnSequenceNumber (0.00s)
=== RUN   TestTxnRequestTxnTimestamp
--- PASS: TestTxnRequestTxnTimestamp (0.01s)
=== RUN   TestTxnResetTxnOnAbort
--- PASS: TestTxnResetTxnOnAbort (0.02s)
=== RUN   TestTransactionConfig
--- PASS: TestTransactionConfig (0.00s)
=== RUN   TestCommitReadOnlyTransaction
--- PASS: TestCommitReadOnlyTransaction (0.01s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
#5060
