### ISSUE TITLE
circleci: failed tests (14301): TestSplitOnTableBoundaries 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5104]
The following test appears to have failed:

[#14301](https://circleci.com/gh/cockroachdb/cockroach/14301):

```
--- PASS: TestRunQuery (0.27s)
=== RUN   Example_basic
E160310 20:34:42.837379 storage/queue.go:441  [raftlog] range=2 [/Table/11-/Table/12): error: node unavailable; try another peer
E160310 20:34:42.837806 client/txn.go:346  failure aborting transaction: kv/txn_coord_sender.go:383: transaction is already committed or aborted; abort caused by: node unavailable; try another peer
E160310 20:34:42.838050 storage/queue.go:441  [split] range=1 [/Min-/Table/11): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Table/11) at key "/Table/13/0": storage/replica_command.go:1631: split at key /Table/13 failed: node unavailable; try another peer
F160310 20:34:42.838500 cli/cli_test.go:65  Could not start server: server/testserver.go:280: had 3 ranges at startup, expected 5
goroutine 1 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xece73d100, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:868 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x25b48a0, 0x3, 0x1f64d8f, 0xf, 0x41, 0xc8203be780, 0x55)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:732 +0x178
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x18a65a0, 0x1a, 0xc820bdf8a8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x18a65a0, 0x1a, 0xc820bdf8a8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x18a65a0, 0x1a, 0xc820bdf8a8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x66
--
	/usr/local/go/src/testing/example.go:36 +0x314
testing.(*M).Run(0xc820bdfed8, 0x85)
	/usr/local/go/src/testing/testing.go:516 +0xbd
main.main()
	github.com/cockroachdb/cockroach/cli/_test/_testmain.go:96 +0x117
FAIL	github.com/cockroachdb/cockroach/cli	17.460s
=== RUN   TestClientTxnSequenceNumber
--- PASS: TestClientTxnSequenceNumber (0.01s)
=== RUN   TestTxnRequestTxnTimestamp
--- PASS: TestTxnRequestTxnTimestamp (0.00s)
=== RUN   TestTxnResetTxnOnAbort
--- PASS: TestTxnResetTxnOnAbort (0.01s)
=== RUN   TestTransactionConfig
--- PASS: TestTransactionConfig (0.00s)
=== RUN   TestCommitReadOnlyTransaction
--- PASS: TestCommitReadOnlyTransaction (0.01s)
--
I160310 20:36:58.096059 stopper.go:273  draining; tasks left:
1      storage/queue.go:379
I160310 20:36:58.096073 client/db.go:416  failed batch: storage/replica_command.go:1631: split at key /Table/13 failed: node unavailable; try another peer
E160310 20:36:58.096135 storage/queue.go:441  [split] range=1 [/Min-/Table/11): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Table/11) at key "/Table/13/0": storage/replica_command.go:1631: split at key /Table/13 failed: node unavailable; try another peer
I160310 20:36:58.096259 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- FAIL: TestSplitOnTableBoundaries (10.80s)
	main_test.go:167: server/testserver.go:280: had 3 ranges at startup, expected 5
=== RUN   TestAllocateIDs
--- PASS: TestAllocateIDs (0.00s)
=== RUN   TestValidateTableDesc
--- PASS: TestValidateTableDesc (0.00s)
=== RUN   TestColumnTypeSQLString
--- PASS: TestColumnTypeSQLString (0.01s)
=== RUN   TestInitialKeys
--- PASS: TestInitialKeys (0.00s)
=== RUN   TestExplainTrace
--
I160310 20:36:58.529712 storage/replica_command.go:63  test injecting error: read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
W160310 20:36:58.529913 kv/dist_sender.go:627  failed to invoke BeginTransaction [/Table/51/1/"g"/0,/Min), ConditionalPut [/Table/51/1/"g"/0,/Min), ConditionalPut [/Table/51/1/"g"/2/1,/Min): read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
I160310 20:36:58.529983 client/db.go:416  failed batch: read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
I160310 20:36:58.530400 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- PASS: TestTxnRestart (0.27s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	54.168s
=== RUN   TestEval
--- PASS: TestEval (0.01s)
=== RUN   TestEvalError
--- PASS: TestEvalError (0.00s)
=== RUN   TestEvalComparisonExprCaching
--- PASS: TestEvalComparisonExprCaching (0.00s)
=== RUN   TestSimilarEscape
--- PASS: TestSimilarEscape (0.00s)
=== RUN   TestQualifiedNameString
--- PASS: TestQualifiedNameString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
#5060
