### ISSUE TITLE
circleci: failed tests (14301): Example_quoted

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5105]
The following test appears to have failed:

[#14301](https://circleci.com/gh/cockroachdb/cockroach/14301):

```
--- PASS: Example_basic (3.19s)
=== RUN   Example_quoted
E160310 20:34:40.009234 storage/replica.go:1342  [node=1,store=1,range=1] error executing raft command: retry txn "storage/replica_command.go:1630 (*Replica).AdminSplit" id=09fc990f key=/Local/Range/"\x95"/RangeDescriptor rw=true pri=0.01521558 iso=SERIALIZABLE stat=PENDING epo=1 ts=1457642079.991666481,1 orig=1457642079.991666481,1 max=1457642079.947778136,0
E160310 20:34:57.270257 client/txn.go:346  failure aborting transaction: kv/txn_coord_sender.go:383: transaction is already committed or aborted; abort caused by: kv/txn_coord_sender.go:339: transaction must not write on multiple coordinators
E160310 20:34:57.273215 storage/queue.go:441  [split] range=1 [/Min-/Table/11): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Table/11) at key "/Table/14/0": storage/replica_command.go:1631: split at key /Table/14 failed: kv/txn_coord_sender.go:339: transaction must not write on multiple coordinators
F160310 20:34:57.779097 cli/cli_test.go:65  Could not start server: server/testserver.go:280: had 4 ranges at startup, expected 5
goroutine 1 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0x34e0c00, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:868 +0xcf
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x2b38e20, 0x3, 0x24e0f69, 0xf, 0x41, 0xc820a81c20, 0x55)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:732 +0x199
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x1ca58a0, 0x1a, 0xc8204bd868, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0x10a
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0xc800000003, 0x1ca58a0, 0x1a, 0xc8204bd868, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x8d
github.com/cockroachdb/cockroach/util/log.Fatalf(0x1ca58a0, 0x1a, 0xc8204bd868, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x74
--
	/usr/local/go/src/testing/example.go:36 +0x397
testing.(*M).Run(0xc8204bded0, 0xc820281680)
	/usr/local/go/src/testing/testing.go:516 +0x181
main.main()
	github.com/cockroachdb/cockroach/cli/_test/_testmain.go:96 +0x211
FAIL	github.com/cockroachdb/cockroach/cli	28.809s
=== RUN   TestClientTxnSequenceNumber
--- PASS: TestClientTxnSequenceNumber (0.03s)
=== RUN   TestTxnRequestTxnTimestamp
--- PASS: TestTxnRequestTxnTimestamp (0.55s)
=== RUN   TestTxnResetTxnOnAbort
--- PASS: TestTxnResetTxnOnAbort (0.03s)
=== RUN   TestTransactionConfig
--- PASS: TestTransactionConfig (0.01s)
=== RUN   TestCommitReadOnlyTransaction
--- PASS: TestCommitReadOnlyTransaction (0.02s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
#5060
