### ISSUE TITLE
circleci: failed tests (14314): TestQuit

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5109]
The following test appears to have failed:

[#14314](https://circleci.com/gh/cockroachdb/cockroach/14314):

```
PASS
ok  	github.com/cockroachdb/cockroach/base	0.031s
=== RUN   TestQuit
E160310 21:22:08.801596 client/txn.go:346  failure aborting transaction: kv/txn_coord_sender.go:383: transaction is already committed or aborted; abort caused by: kv/txn_coord_sender.go:339: transaction must not write on multiple coordinators
E160310 21:22:08.802268 storage/queue.go:441  [split] range=1 [/Min-/Table/11): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Table/11) at key "/Table/13/0": storage/replica_command.go:1631: split at key /Table/13 failed: kv/txn_coord_sender.go:339: transaction must not write on multiple coordinators
F160310 21:22:10.403091 cli/cli_test.go:65  Could not start server: server/testserver.go:280: had 3 ranges at startup, expected 5
goroutine 11 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xece73dc00, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:868 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x25b5b60, 0x3, 0x1f66639, 0xf, 0x41, 0xc8203d2840, 0x55)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:732 +0x178
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x18a76c0, 0x1a, 0xc8207c7c78, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x18a76c0, 0x1a, 0xc8207c7c78, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x18a76c0, 0x1a, 0xc8207c7c78, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x66
--
	/go/src/github.com/cockroachdb/cockroach/cli/cli_test.go:193 +0x74
testing.tRunner(0xc8202c4090, 0x2258fc0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
FAIL	github.com/cockroachdb/cockroach/cli	17.772s
=== RUN   TestClientTxnSequenceNumber
--- PASS: TestClientTxnSequenceNumber (0.01s)
=== RUN   TestTxnRequestTxnTimestamp
--- PASS: TestTxnRequestTxnTimestamp (0.00s)
=== RUN   TestTxnResetTxnOnAbort
--- PASS: TestTxnResetTxnOnAbort (0.01s)
=== RUN   TestTransactionConfig
--- PASS: TestTransactionConfig (0.00s)
=== RUN   TestCommitReadOnlyTransaction
--- PASS: TestCommitReadOnlyTransaction (0.01s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
#5060
