### ISSUE TITLE
circleci: failed tests (14314): ExampleDB_Put_insecure

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5110]
The following test appears to have failed:

[#14314](https://circleci.com/gh/cockroachdb/cockroach/14314):

```
E160310 21:22:13.398748 client/txn.go:346  failure aborting transaction: kv/txn_coord_sender.go:383: transaction is already committed or aborted; abort caused by: kv/txn_coord_sender.go:339: transaction must not write on multiple coordinators
W160310 21:22:13.399319 kv/dist_sender.go:627  failed to invoke AdminSplit [/Table/13/0,/Min): storage/replica_command.go:1631: split at key /Table/13 failed: kv/txn_coord_sender.go:339: transaction must not write on multiple coordinators
I160310 21:22:13.399537 client/db.go:416  failed batch: storage/replica_command.go:1631: split at key /Table/13 failed: kv/txn_coord_sender.go:339: transaction must not write on multiple coordinators
E160310 21:22:13.400047 storage/queue.go:441  [split] range=1 [/Min-/Table/11): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Table/11) at key "/Table/13/0": storage/replica_command.go:1631: split at key /Table/13 failed: kv/txn_coord_sender.go:339: transaction must not write on multiple coordinators
I160310 21:22:13.830610 storage/engine/rocksdb.go:148  closing in-memory rocksdb instance
F160310 21:22:13.831424 client/db_test.go:269  Could not start server: server/testserver.go:280: had 3 ranges at startup, expected 5
goroutine 1 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0x334e500, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:868 +0xcf
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x29a69e0, 0x3, 0x23564ec, 0x11, 0x10d, 0xc8206aaae0, 0x55)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:732 +0x199
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x1b81ce0, 0x1a, 0xc82074fa98, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0x10a
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0xc800000003, 0x1b81ce0, 0x1a, 0xc82074fa98, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x8d
github.com/cockroachdb/cockroach/util/log.Fatalf(0x1b81ce0, 0x1a, 0xc82074fa98, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x74
--
	/usr/local/go/src/testing/example.go:36 +0x397
testing.(*M).Run(0xc82074fee0, 0x37cbb9dd)
	/usr/local/go/src/testing/testing.go:516 +0x181
main.main()
	github.com/cockroachdb/cockroach/client/_test/_testmain.go:130 +0x211
FAIL	github.com/cockroachdb/cockroach/client	40.990s
?   	github.com/cockroachdb/cockroach/cmd/gossipsim	[no test files]
?   	github.com/cockroachdb/cockroach/cmd/protoc-gen-gogoroach	[no test files]
=== RUN   TestObjectIDForKey
--- PASS: TestObjectIDForKey (0.02s)
=== RUN   TestGet
--- PASS: TestGet (0.02s)
=== RUN   TestGetLargestID
--- PASS: TestGetLargestID (0.02s)
=== RUN   TestComputeSplits
E160310 21:22:21.108798 config/config.go:378  unable to determine largest reserved object ID from system config: descriptor table not found in system config of 0 values

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
#5060
