### ISSUE TITLE
cli,kvserver: panic in `cockroach debug range-data`

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#51151]
**Describe the problem**

When running `cockroach debug range-data` on a cluster running on master, we seem to hit a panic. 

```
0,0 /Local/RangeID/8/r/RangeLastGC (0x016990726c67632d00): %!s(PANIC=String method: field raftpb.Entry.Type has invalid type: got raftpb.EntryType, want pointer): EMPTY

0,0 /Local/RangeID/8/r/RangeAppliedState (0x016990727261736b00): raft_applied_index:43 lease_applied_index:29 range_stats:<last_update_nanos:1594224924492979971 live_bytes:5945 live_count:75 key_bytes:3520 key_count:75 val_bytes:2425 val_count:75 sys_bytes:130 sys_count:3 > 
0,0 /Local/RangeID/8/r/RangeLease (0x01699072726c6c2d00): repl=(n1,s1):1 seq=1 start=0,0 epo=1 pro=1594224924.059517853,0
E200708 16:18:47.178033 1 util/log/log.go:50  a panic has occurred!
E200708 16:18:47.178089 1 util/log/log.go:50  a panic has occurred!
panic: field raftpb.HardState.term has invalid type: got uint64, want pointer [recovered]
	panic: field raftpb.HardState.term has invalid type: got uint64, want pointer [recovered]
	panic: field raftpb.HardState.term has invalid type: got uint64, want pointer [recovered]
	panic: field raftpb.HardState.term has invalid type: got uint64, want pointer

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.RecoverAndReportPanic(0x554dd20, 0xc000130090, 0xc0001b8a80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:88 +0x9f
panic(0x4382080, 0xc0008e3a40)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc0009b22d0, 0x554dd20, 0xc000130090)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0x11f
panic(0x4382080, 0xc0008e3a40)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc0009b22d0, 0x554dd20, 0xc000130090)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:479 +0x68c
panic(0x4382080, 0xc0008e3a40)
	/usr/local/go/src/runtime/panic.go:969 +0x166
google.golang.org/protobuf/internal/impl.fieldInfoForScalar(0x55efca0, 0xc000396840, 0x42c9f9f, 0x4, 0x0, 0x0, 0x55efdc0, 0x4382280, 0x42c9fa5, 0x2d, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go:228 +0x800
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc00015a8c0, 0xffffffffffffffff, 0xffffffffffffffff, 0x18, 0xffffffffffffffff, 0xc000733290, 0xc0007332c0, 0xc0007332f0, 0xc000733320)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect.go:67 +0x938
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc00015a8c0, 0x55efdc0, 0x4765c20, 0xffffffffffffffff, 0xffffffffffffffff, 0x18, 0xffffffffffffffff, 0xc000733290, 0xc0007332c0, 0xc0007332f0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect.go:36 +0x63
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc00015a8c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message.go:90 +0x182
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(0xc00015a8c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message.go:72 +0x3c
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).Has(0xc0008e3510, 0x55efca0, 0xc000396840, 0xc000396840)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect_gen.go:185 +0x33
github.com/golang/protobuf/proto.(*textWriter).writeMessage(0xc000733260, 0x55dcd00, 0xc0008e3510, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/protobuf/proto/text_encode.go:278 +0x925
github.com/golang/protobuf/proto.(*TextMarshaler).marshal(0x7b9e532, 0x55321e0, 0xc000733230, 0xc00073cc20, 0xb, 0x10, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/protobuf/proto/text_encode.go:86 +0x18a
github.com/golang/protobuf/proto.(*TextMarshaler).Text(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/protobuf/proto/text_encode.go:44
github.com/golang/protobuf/proto.CompactTextString(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/protobuf/proto/text_encode.go:106
go.etcd.io/etcd/raft/raftpb.(*HardState).String(0xc000733230, 0xb, 0x10)
	/go/src/github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft/raftpb/raft.pb.go:324 +0x44
github.com/cockroachdb/cockroach/pkg/kv/kvserver.tryRangeIDKey(0xc000b5688e, 0x8, 0x8, 0x0, 0x0, 0xc000b56896, 0x19, 0x19, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/debug_print.go:294 +0x4c9
github.com/cockroachdb/cockroach/pkg/kv/kvserver.SprintKeyValue(0xc000b5688e, 0x8, 0x8, 0x0, 0x0, 0xc000b56896, 0x19, 0x19, 0x1, 0x19, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/debug_print.go:63 +0x146
github.com/cockroachdb/cockroach/pkg/kv/kvserver.PrintKeyValue(0xc000b5688e, 0x8, 0x8, 0x0, 0x0, 0xc000b56896, 0x19, 0x19)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/debug_print.go:33 +0x5b
github.com/cockroachdb/cockroach/pkg/cli.runDebugRangeData(0x7b783a0, 0xc000734120, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/debug.go:308 +0x469
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x7b783a0, 0xc000734120, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:188 +0x79
github.com/spf13/cobra.(*Command).execute(0x7b783a0, 0xc0007340e0, 0x2, 0x2, 0x7b783a0, 0xc0007340e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x7b75ba0, 0xc000130090, 0xc0004b658a, 0x10)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:223
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:67 +0x270
main.main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:26 +0x20
```

**To Reproduce**

Create a cluster on master (this was at db4dbd9f08f0a461bd4f093172be7db20d066168). Start the cluster, stop it, run:

`cockroach debug range-data`

**Comment by erikgrinaker** [comment]
This was fixed by #56147.
