### ISSUE TITLE
stress: failed test in cockroach/gossip/gossip.test: TestClientNodeID

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5136]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/e9f364bea3014b627b66e8dddcc79a4f3cbcfaad

Stress build found a failed test:

```
=== RUN   TestClientNodeID
W160311 03:50:09.218659 gossip/gossip.go:912  not connected to cluster; use --join to specify a connected node
E160311 03:50:09.224185 rpc/context.go:146  rpc error: code = 13 desc = "transport is closing"
--- FAIL: TestClientNodeID (5.03s)
	leaktest.go:80: Leaked goroutine: goroutine 178 [select]:
		google.golang.org/grpc/transport.(*serverHandlerTransport).runStream(0xc8200106c0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:345 +0x115
		google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams(0xc8200106c0, 0xc820177ce0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:335 +0xca3
		google.golang.org/grpc.(*Server).serveStreams(0xc820096480, 0x7f00771afbe0, 0xc8200106c0)
			/go/src/google.golang.org/grpc/server.go:325 +0x159
		google.golang.org/grpc.(*Server).ServeHTTP(0xc820096480, 0x7f00771afb58, 0xc820120040, 0xc8201661c0)
			/go/src/google.golang.org/grpc/server.go:368 +0x1a8
		net/http.(Handler).ServeHTTP-fm(0x7f00771afb58, 0xc820120040, 0xc8201661c0)
			/usr/local/go/src/net/http/h2_bundle.go:3847 +0x50
		golang.org/x/net/http2.(*serverConn).runHandler(0xc82017e1e0, 0xc820120040, 0xc8201661c0, 0xc82013c240)
			/go/src/golang.org/x/net/http2/server.go:1649 +0x9f
		created by golang.org/x/net/http2.(*serverConn).processHeaders
			/go/src/golang.org/x/net/http2/server.go:1428 +0x8d8
```

Run Details:

```
63 runs so far, 0 failures, over 5s
128 runs so far, 0 failures, over 10s
182 runs so far, 0 failures, over 15s
197 runs completed, 1 failures, over 16s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment]
@tamird Should we be ignoring these goroutines in leaktest? I'm not clear on how they are intended to be shut down. Also, I thought we weren't using `ServeHTTP` anymore.

**Comment by petermattis** [comment]
Ah, this is insecure, so I guess `ServeHTTP` is still used.

**Comment by tamird** [comment]
`ServeHTTP` is still used but not because it's insecure - it's because
`util/net.go`'s `ListenAndServe` didn't change as part of the move to
`grpc.(*Server).Serve`; these tests are still using `ServeHTTP`.
