### ISSUE TITLE
stress: failed test in cockroach/rpc/rpc.test: TestFailedOffsetMeasurement

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5153]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/e9f364bea3014b627b66e8dddcc79a4f3cbcfaad

Stress build found a failed test:

```
=== RUN   TestFailedOffsetMeasurement
E160311 04:42:48.745855 rpc/context.go:146  rpc error: code = 4 desc = "context deadline exceeded"
I160311 04:42:48.758320 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial 127.0.0.1:38075: grpc: the client connection is closing; please retry.
SIGABRT: abort
PC=0x460f91 m=0

goroutine 0 [idle]:
runtime.futex(0x11a0108, 0x0, 0x0, 0x0, 0x0, 0x119f6b0, 0x0, 0x0, 0x40fb94, 0x11a0108, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:302 +0x21
runtime.futexsleep(0x11a0108, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x11a0108)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1535 +0x10b
runtime.findrunnable(0xc820017500, 0x0)
	/usr/local/go/src/runtime/proc.go:1973 +0x739
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2072 +0x24f
runtime.park_m(0xc820632000)
	/usr/local/go/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x7ffe38c132f0)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0xd32468, 0x11813a0, 0x12, 0x12, 0xb8d201)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820039f08, 0xb8d2e0)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:88 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x119f4e0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1010 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 30 [chan send, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.TestFailedOffsetMeasurement(0xc820464000)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:163 +0x8a2
testing.tRunner(0xc820464000, 0x11814d8)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 98 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:90 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820056070, 0xc8200f74c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 31 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:90 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820056070, 0xc82000a440)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 33 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f14f52c8798, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201a7020, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201a7020, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201a6fc0, 0x0, 0x7f14f534d180, 0xc82047e200)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82017c150, 0xc800000000, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82017c150, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
crypto/tls.(*listener).Accept(0xc8200f7320, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/tls.go:52 +0x60
net/http.(*Server).Serve(0xc8200f9a00, 0x7f14f52c8918, 0xc8200f7320, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2117 +0x129
github.com/cockroachdb/cockroach/util.ServeHandler.func2(0xc8200f9a00, 0x7f14f52c8918, 0xc8200f7320, 0xc820056070, 0xc820158480, 0xc8201ec990)
	/go/src/github.com/cockroachdb/cockroach/util/net.go:122 +0x4a
created by github.com/cockroachdb/cockroach/util.ServeHandler
	/go/src/github.com/cockroachdb/cockroach/util/net.go:130 +0x3f1

goroutine 32 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServe.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:45 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820056070, 0xc8200f72a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

rax    0xca
rbx    0x0
rcx    0x460f93
rdx    0x0
rdi    0x11a0108
rsi    0x0
rbp    0x1
rsp    0x7ffe38c13150
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x10
r13    0xd2f345
r14    0xf
r15    0x8
rip    0x460f91
rflags 0x286
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
138 runs so far, 0 failures, over 5s
287 runs so far, 0 failures, over 10s
436 runs so far, 0 failures, over 15s
586 runs so far, 0 failures, over 20s
728 runs so far, 0 failures, over 25s
870 runs so far, 0 failures, over 30s
1017 runs so far, 0 failures, over 35s
1160 runs so far, 0 failures, over 40s
1304 runs so far, 0 failures, over 45s
1453 runs so far, 0 failures, over 50s
1598 runs so far, 0 failures, over 55s
1743 runs so far, 0 failures, over 1m0s
1888 runs so far, 0 failures, over 1m5s
2035 runs so far, 0 failures, over 1m10s
2182 runs so far, 0 failures, over 1m15s
2332 runs so far, 0 failures, over 1m20s
2477 runs so far, 0 failures, over 1m25s
2623 runs so far, 0 failures, over 1m30s
2772 runs so far, 0 failures, over 1m35s
2914 runs so far, 0 failures, over 1m40s
3062 runs so far, 0 failures, over 1m45s
3204 runs so far, 0 failures, over 1m50s
3354 runs so far, 0 failures, over 1m55s
3505 runs so far, 0 failures, over 2m0s
3650 runs so far, 0 failures, over 2m5s
3797 runs so far, 0 failures, over 2m10s
3942 runs so far, 0 failures, over 2m15s
4084 runs so far, 0 failures, over 2m20s
4228 runs so far, 0 failures, over 2m25s
4380 runs so far, 0 failures, over 2m30s
4526 runs so far, 0 failures, over 2m35s
4670 runs so far, 0 failures, over 2m40s
4816 runs so far, 0 failures, over 2m45s
4959 runs so far, 0 failures, over 2m50s
5105 runs so far, 0 failures, over 2m55s
5249 runs so far, 0 failures, over 3m0s
5397 runs so far, 0 failures, over 3m5s
5530 runs so far, 0 failures, over 3m10s
5676 runs so far, 0 failures, over 3m15s
5813 runs so far, 0 failures, over 3m20s
5961 runs so far, 0 failures, over 3m25s
6109 runs so far, 0 failures, over 3m30s
6253 runs so far, 0 failures, over 3m35s
6401 runs so far, 0 failures, over 3m40s
6549 runs so far, 0 failures, over 3m45s
6692 runs so far, 0 failures, over 3m50s
6837 runs so far, 0 failures, over 3m55s
6953 runs so far, 0 failures, over 4m0s
7092 runs so far, 0 failures, over 4m5s
7228 runs so far, 0 failures, over 4m10s
7367 runs so far, 0 failures, over 4m15s
7512 runs so far, 0 failures, over 4m20s
7661 runs so far, 0 failures, over 4m25s
7808 runs so far, 0 failures, over 4m30s
7948 runs so far, 0 failures, over 4m35s
8091 runs so far, 0 failures, over 4m40s
8235 runs so far, 0 failures, over 4m45s
8382 runs so far, 0 failures, over 4m50s
8524 runs so far, 0 failures, over 4m55s
8669 runs so far, 0 failures, over 5m0s
8806 runs so far, 0 failures, over 5m5s
8951 runs so far, 0 failures, over 5m10s
9092 runs so far, 0 failures, over 5m15s
9223 runs so far, 0 failures, over 5m20s
9367 runs so far, 0 failures, over 5m25s
9506 runs so far, 0 failures, over 5m30s
9651 runs so far, 0 failures, over 5m35s
9791 runs so far, 0 failures, over 5m40s
9934 runs so far, 0 failures, over 5m45s
10075 runs so far, 0 failures, over 5m50s
10209 runs so far, 0 failures, over 5m55s
10353 runs so far, 0 failures, over 6m0s
10492 runs so far, 0 failures, over 6m5s
10632 runs so far, 0 failures, over 6m10s
10775 runs so far, 0 failures, over 6m15s
10917 runs so far, 0 failures, over 6m20s
11054 runs so far, 0 failures, over 6m25s
11197 runs so far, 0 failures, over 6m30s
11335 runs so far, 0 failures, over 6m35s
11473 runs so far, 0 failures, over 6m40s
11615 runs so far, 0 failures, over 6m45s
11753 runs so far, 0 failures, over 6m50s
11893 runs so far, 0 failures, over 6m55s
12034 runs so far, 0 failures, over 7m0s
12176 runs so far, 0 failures, over 7m5s
12320 runs so far, 0 failures, over 7m10s
12472 runs so far, 0 failures, over 7m15s
12618 runs so far, 0 failures, over 7m20s
12759 runs so far, 0 failures, over 7m25s
12895 runs so far, 0 failures, over 7m30s
13042 runs so far, 0 failures, over 7m35s
13187 runs so far, 0 failures, over 7m40s
13328 runs so far, 0 failures, over 7m45s
13472 runs so far, 0 failures, over 7m50s
13614 runs so far, 0 failures, over 7m55s
13750 runs so far, 0 failures, over 8m0s
13895 runs so far, 0 failures, over 8m5s
14031 runs so far, 0 failures, over 8m10s
14171 runs so far, 0 failures, over 8m15s
14314 runs so far, 0 failures, over 8m20s
14454 runs so far, 0 failures, over 8m25s
14597 runs so far, 0 failures, over 8m30s
14742 runs so far, 0 failures, over 8m35s
14877 runs so far, 0 failures, over 8m40s
15023 runs so far, 0 failures, over 8m45s
15160 runs so far, 0 failures, over 8m50s
15302 runs so far, 0 failures, over 8m55s
15447 runs so far, 0 failures, over 9m0s
15592 runs so far, 0 failures, over 9m5s
15736 runs so far, 0 failures, over 9m10s
15876 runs so far, 0 failures, over 9m15s
16016 runs so far, 0 failures, over 9m20s
16153 runs so far, 0 failures, over 9m25s
16296 runs so far, 0 failures, over 9m30s
16433 runs so far, 0 failures, over 9m35s
16567 runs so far, 0 failures, over 9m40s
16710 runs so far, 0 failures, over 9m45s
16849 runs so far, 0 failures, over 9m50s
16986 runs so far, 0 failures, over 9m55s
17131 runs so far, 0 failures, over 10m0s
17272 runs so far, 0 failures, over 10m5s
17411 runs so far, 0 failures, over 10m10s
17550 runs so far, 0 failures, over 10m15s
17691 runs so far, 0 failures, over 10m20s
17828 runs so far, 0 failures, over 10m25s
17975 runs so far, 0 failures, over 10m30s
18104 runs so far, 0 failures, over 10m35s
18249 runs so far, 0 failures, over 10m40s
18393 runs so far, 0 failures, over 10m45s
18537 runs so far, 0 failures, over 10m50s
18680 runs so far, 0 failures, over 10m55s
18823 runs so far, 0 failures, over 11m0s
18962 runs so far, 0 failures, over 11m5s
19105 runs so far, 0 failures, over 11m10s
19247 runs so far, 0 failures, over 11m15s
19393 runs so far, 0 failures, over 11m20s
19534 runs so far, 0 failures, over 11m25s
19672 runs so far, 0 failures, over 11m30s
19814 runs so far, 0 failures, over 11m35s
19951 runs so far, 0 failures, over 11m40s
20091 runs so far, 0 failures, over 11m45s
20227 runs so far, 0 failures, over 11m50s
20368 runs so far, 0 failures, over 11m55s
20508 runs so far, 0 failures, over 12m0s
20650 runs so far, 0 failures, over 12m5s
20791 runs so far, 0 failures, over 12m10s
20934 runs so far, 0 failures, over 12m15s
21072 runs so far, 0 failures, over 12m20s
21206 runs so far, 0 failures, over 12m25s
21343 runs so far, 0 failures, over 12m30s
21485 runs so far, 0 failures, over 12m35s
21628 runs so far, 0 failures, over 12m40s
21774 runs so far, 0 failures, over 12m45s
21915 runs so far, 0 failures, over 12m50s
22055 runs so far, 0 failures, over 12m55s
22186 runs so far, 0 failures, over 13m0s
22325 runs so far, 0 failures, over 13m5s
22466 runs so far, 0 failures, over 13m10s
22606 runs so far, 0 failures, over 13m15s
22748 runs so far, 0 failures, over 13m20s
22888 runs so far, 0 failures, over 13m25s
23023 runs so far, 0 failures, over 13m30s
23159 runs so far, 0 failures, over 13m35s
23298 runs so far, 0 failures, over 13m40s
23441 runs so far, 0 failures, over 13m45s
23584 runs so far, 0 failures, over 13m50s
23727 runs so far, 0 failures, over 13m55s
23820 runs completed, 1 failures, over 13m58s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
can't repro this guy
