### ISSUE TITLE
roachtest: Nightly job aborting after running 28 tests 

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#51553]
**Describe the problem**

It looks like the last 3 Roachtest Nightly jobs for the master branch quit early after only running 28 tests. Examples: [one](https://teamcity.cockroachdb.com/viewLog.html?buildId=2096175&buildTypeId=Cockroach_Nightlies_WorkloadNightly), [two](https://teamcity.cockroachdb.com/viewLog.html?buildId=2093071&buildTypeId=Cockroach_Nightlies_WorkloadNightly), and [three](https://teamcity.cockroachdb.com/viewLog.html?buildId=2090320&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=buildResultsDiv&branch_Cockroach_Nightlies=%3Cdefault%3E). 

I don't know if it's the cause of the problem, but I see this in all the logs:

```
[02:23:38][Step 2/2] panic: t.Fatal() was called
[02:23:38][Step 2/2] 
[02:23:38][Step 2/2] goroutine 5417 [running]:
[02:23:38][Step 2/2] main.(*test).fatalfInner(0xc000166d80, 0x0, 0x0, 0xc000d4e5b0, 0x1, 0x1)
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test.go:279 +0xcd
[02:23:38][Step 2/2] main.FatalIfErr(...)
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test.go:285
[02:23:38][Step 2/2] main.(*cluster).Start(0xc000a921e0, 0x4846940, 0xc0006daf00, 0xc000166d80, 0xc0010e5f00, 0x2, 0x2)
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1996 +0xe5
[02:23:38][Step 2/2] main.runDecommission.func5(0x0, 0x0)
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/decommission.go:251 +0x926
[02:23:38][Step 2/2] golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000426720, 0xc000d305f0)
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
[02:23:38][Step 2/2] created by golang.org/x/sync/errgroup.(*Group).Go
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
[02:23:38][Step 2/2] + upload_stats
[02:23:38][Step 2/2] + [[ master == \m\a\s\t\e\r ]]
[02:23:38][Step 2/2] + bucket=cockroach-nightly-gce
[02:23:38][Step 2/2] + [[ gce == \g\c\e ]]
[02:23:38][Step 2/2] + bucket=cockroach-nightly
[02:23:38][Step 2/2] + cd /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts
[02:23:38][Step 2/2] ++ sed 's/^\.\///'
[02:23:38][Step 2/2] ++ find . -name stats.json
[02:23:38][Step 2/2] + IFS=
[02:23:38][Step 2/2] + read -r f
[02:23:38][Step 2/2] + gsutil cp '' gs://cockroach-nightly/artifacts/20200716-2093071/
[02:23:38][Step 2/2] CommandException: No URLs matched: 
[02:23:39][Step 2/2] Process exited with code 1
```

**To Reproduce**

Run a Roachtest Nightly job.

**Expected behavior**

All of the tests should run. There are a few hundred tests.

**Additional context**

The fact that not all tests are being run isn't super obvious. See: #50618

**Comment by jordanlewis** [comment]
It looks to me like this is failing because `cluster.Start` runs `t.Fatal` if it gets an error back. Is that expected? I would have expected `roachtest` to not run `t.Fatal` if just a single cluster fails, but I don't know.

cc @tbg @andreimatei based on the `git blame` info, hoping you have an idea what's supposed to be happening here architecture wise?
