### ISSUE TITLE
stress: failed test in cockroach/storage/storage.test: TestRestoreReplicas

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5158]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/e9f364bea3014b627b66e8dddcc79a4f3cbcfaad

Stress build found a failed test:

```
=== RUN   TestRestoreReplicas
W160311 06:19:39.713783 gossip/gossip.go:912  not connected to cluster; use --join to specify a connected node
W160311 06:19:39.716163 gossip/gossip.go:385  bad address {localhost 1}: gossip/resolver/resolver.go:95: unknown address network "localhost" for 1
I160311 06:19:39.716394 storage/replica_command.go:1249  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1.000s
W160311 06:19:39.716955 gossip/gossip.go:385  bad address {localhost 2}: gossip/resolver/resolver.go:95: unknown address network "localhost" for 2
I160311 06:19:39.717484 storage/replica.go:1085  raft: proposing ADD_REPLICA {2 2 2} for range 1
panic: gossip infostore's NodeID is 0

goroutine 4418 [running]:
panic(0x1578000, 0xc82000f170)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/gossip.(*infoStore).newInfo(0xc820176000, 0xc820756ab0, 0x10, 0x10, 0x0, 0xc800000001)
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:135 +0x84
github.com/cockroachdb/cockroach/gossip.(*Gossip).AddInfo(0xc82000c500, 0x1932ec0, 0xa, 0xc820756ab0, 0x10, 0x10, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:515 +0xca
github.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc8201811e0, 0x278a2a0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1691 +0x740
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc82045c000, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:806 +0x307
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:750 +0x59
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820186cb0, 0xc820164a00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62


ERROR: exit status 2
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
7 runs so far, 0 failures, over 30s
8 runs so far, 0 failures, over 35s
8 runs so far, 0 failures, over 40s
8 runs so far, 0 failures, over 45s
8 runs so far, 0 failures, over 50s
9 runs so far, 0 failures, over 55s
16 runs so far, 0 failures, over 1m0s
16 runs so far, 0 failures, over 1m5s
16 runs so far, 0 failures, over 1m10s
16 runs so far, 0 failures, over 1m15s
16 runs so far, 0 failures, over 1m20s
20 runs so far, 0 failures, over 1m25s
24 runs so far, 0 failures, over 1m30s
24 runs so far, 0 failures, over 1m35s
24 runs so far, 0 failures, over 1m40s
24 runs so far, 0 failures, over 1m45s
25 runs so far, 0 failures, over 1m50s
31 runs so far, 0 failures, over 1m55s
32 runs so far, 0 failures, over 2m0s
32 runs so far, 0 failures, over 2m5s
32 runs so far, 0 failures, over 2m10s
33 runs so far, 0 failures, over 2m15s
36 runs so far, 0 failures, over 2m20s
40 runs so far, 0 failures, over 2m25s
40 runs so far, 0 failures, over 2m30s
40 runs so far, 0 failures, over 2m35s
40 runs so far, 0 failures, over 2m40s
41 runs so far, 0 failures, over 2m45s
46 runs so far, 0 failures, over 2m50s
48 runs so far, 0 failures, over 2m55s
48 runs so far, 0 failures, over 3m0s
49 runs so far, 0 failures, over 3m5s
50 runs completed, 1 failures, over 3m7s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Looks like this ran with pre #4926 code.

**Comment by mberhault** [comment]
All the nightly stuff is using whatever the latest AWS binary is, which at
this point is from two days ago.
