### ISSUE TITLE
circleci: failed tests (14354): TestRetryableError TestTxnRestartedSerializableTimestampRegression TestNoSequenceCachePutOnRangeMismatchError 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5160]
The following test appears to have failed:

[#14354](https://circleci.com/gh/cockroachdb/cockroach/14354):

```
=== RUN   TestSendToOneClient
--- PASS: TestSendToOneClient (0.27s)
=== RUN   TestRetryableError
E160311 14:17:20.914461 rpc/context.go:155  rpc error: code = 4 desc = "context deadline exceeded"
I160311 14:17:20.965000 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial 127.0.0.1:59879: grpc: the client connection is closing; please retry.
--- FAIL: TestRetryableError (5.26s)
	send_test.go:153: &{127.0.0.1:59879 127.0.0.1 {{} <nil> <nil> 0xc8208da9c0 false false { <nil> [0xc8202637c0] 3000000000}}} has unexpectedly shut down
	<autogenerated>:31: Leaked goroutine: goroutine 501 [chan receive]:
		github.com/cockroachdb/cockroach/rpc.NewContext.func1()
			/go/src/github.com/cockroachdb/cockroach/rpc/context.go:99 +0x68
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202a8070, 0xc8202a4180)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x60
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x70
	<autogenerated>:31: Leaked goroutine: goroutine 502 [chan receive]:
		github.com/cockroachdb/cockroach/util.ListenAndServe.func1()
--
I160311 14:18:03.193688 client/db.go:416  failed batch: retry txn "kv/txn_test.go:513 TestTxnRestartedSerializableTimestampRegression.func1" id=0f026df8 key="a" rw=true pri=0.00000005 iso=SERIALIZABLE stat=PENDING epo=2 ts=0.000000000,38 orig=0.000000000,38 max=0.000000000,12
I160311 14:18:03.198609 storage/replica_command.go:458  auto-gc'ed 0f026df8 (2 intents)
I160311 14:18:03.200132 stopper.go:273  draining; tasks left:
1      kv/txn_coord_sender.go:803
I160311 14:18:03.204105 storage/engine/rocksdb.go:148  closing in-memory rocksdb instance
--- FAIL: TestTxnRestartedSerializableTimestampRegression (5.09s)
	<autogenerated>:31: Leaked goroutine: goroutine 503 [IO wait]:
		net.runtime_pollWait(0x7fbbd65a7330, 0x72, 0x5e5109)
			/usr/local/go/src/runtime/netpoll.go:160 +0x63
		net.(*pollDesc).Wait(0xc8201a7800, 0x72, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:73 +0x56
		net.(*pollDesc).WaitRead(0xc8201a7800, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:78 +0x44
		net.(*netFD).accept(0xc8201a77a0, 0x0, 0x7fbbd6601dc0, 0xc820197c20)
			/usr/local/go/src/net/fd_unix.go:426 +0x2f6
		net.(*TCPListener).AcceptTCP(0xc820118258, 0x0, 0x0, 0x0)
--
I160311 14:18:21.024943 kv/range_cache.go:189  adding descriptor: key=/Meta2/Max desc=range_id:5 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160311 14:18:21.025266 kv/range_cache.go:313  clearing overlapping descriptor: key=/Meta2/Max desc=range_id:5 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160311 14:18:21.030570 storage/replica_command.go:1260  range 7: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457705902.026s
I160311 14:18:21.031311 storage/replica.go:1767  [node=1,store=1,range=7] gossiping system config from store 1, range 7, hash 49de9ef342f66657ac1397aab2a480188e899cf9
I160311 14:18:21.051173 storage/engine/rocksdb.go:148  closing in-memory rocksdb instance
--- FAIL: TestNoSequenceCachePutOnRangeMismatchError (6.04s)
	<autogenerated>:31: Leaked goroutine: goroutine 501 [chan receive, 1 minutes]:
		github.com/cockroachdb/cockroach/rpc.NewContext.func1()
			/go/src/github.com/cockroachdb/cockroach/rpc/context.go:99 +0x68
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202a8070, 0xc8202a4180)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x60
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x70
	<autogenerated>:31: Leaked goroutine: goroutine 502 [chan receive, 1 minutes]:
		github.com/cockroachdb/cockroach/util.ListenAndServe.func1()
			/go/src/github.com/cockroachdb/cockroach/util/net.go:46 +0x65
--
I160311 14:18:27.610826 kv/dist_sender_server_test.go:594  Waiting for the txn commit
I160311 14:18:27.613994 storage/replica_command.go:458  auto-gc'ed fb910d90 (1 intents)
I160311 14:18:27.625843 storage/replica_command.go:458  auto-gc'ed 1e1af6e3 (1 intents)
I160311 14:18:27.631802 storage/engine/rocksdb.go:148  closing in-memory rocksdb instance
--- PASS: TestPropagateTxnOnPushError (0.73s)
FAIL
FAIL	github.com/cockroachdb/cockroach/kv	68.633s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestKeyNext
--- PASS: TestKeyNext (0.00s)
=== RUN   TestKeyPrefixEnd
--- PASS: TestKeyPrefixEnd (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment]
See #5211.

**Comment by petermattis** [comment]
I'm unable to reproduce failures in `TestTxnRestartedSerializableTimestampRegression` or `TestNoSequenceCachePutOnRangeMismatchError`.
