### ISSUE TITLE
sql: SELECT COUNT(1) crashes the server

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#5170]
`COUNT(expr)` is supposed to evaluate `expr` and return the count of rows on which `expr` is true.
We seem to only support `COUNT(*)`?

```
goroutine 189 [running]:
panic(0x5071920, 0xc82000e0e0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql/parser.(*FuncExpr).Eval(0xc8205c0120, 0x1, 0xece751167, 0x63f97a0, 0x5d63560, 0xece751167, 0x63f97a0, 0x5d63560, 0xc820301730, 0xc82075d850, ...)
        /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:1142 +0x53a
github.com/cockroachdb/cockroach/sql/parser.(*normalizeVisitor).VisitPost(0xc820064bf0, 0x7a1c150, 0xc8205c0120, 0x0, 0x0)
        /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/normalize.go:406 +0x18d
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7e61d08, 0xc820064bf0, 0x7a1c150, 0xc8205c00c0, 0x7a1c150, 0xc8205c0120, 0x44ee564)
        /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:388 +0xd0
github.com/cockroachdb/cockroach/sql/parser.(*Parser).NormalizeExpr(0xc820064740, 0x1, 0xece751167, 0x63f97a0, 0x5d63560, 0xece751167, 0x63f97a0, 0x5d63560, 0xc820301730, 0xc82075d850, ...)
        /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/parse.go:89 +0x107
github.com/cockroachdb/cockroach/sql.(*selectNode).addRender(0xc82007a120, 0x7a1c150, 0xc8205c00c0, 0x0, 0x0, 0xdeaddeaddeaddead)
        /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/select.go:535 +0x7d5
github.com/cockroachdb/cockroach/sql.(*selectNode).initTargets(0xc82007a120, 0xc8206a2160, 0x1, 0x1, 0xc8202b21e0)
        /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/select.go:389 +0xf2
github.com/cockroachdb/cockroach/sql.(*planner).initSelect(0xc820064680, 0xc82007a120, 0xc820783600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x51064a0)
        /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/select.go:231 +0x122
github.com/cockroachdb/cockroach/sql.(*planner).Select(0xc820064680, 0xc8202b2180, 0xc8eb5b2f01, 0x0, 0x0, 0x7a1c150)
        /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/select.go:178 +0x19a
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc820064680, 0x7e616f8, 0xc8202b2180, 0xc820783601, 0x0, 0x0, 0xdeaddead00000000)
        /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/plan.go:138 +0x148c
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc8204a8000, 0x7e616f8, 0xc8202b2180, 0xc820064680, 0xece751167, 0xc8063fe858, 0x5d63560, 0x1, 0x0, 0x0, ...)
        /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/executor.go:918 +0x89
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInOpenTxn(0xc8204a8000, 0x7e616f8, 0xc8202b2180, 0xc820064680, 0x7a10101, 0xece751167, 0x63f97a0, 0x5d63560, 0xc8200125a0, 0x0, ...)
```

**Comment by andreimatei** [comment]
from gitter:

andrei:
btw, why does select count(*) (no FROM) return 1, in both cockroach and postgres?
And how does even count(*) work, given that we don’t set a .fn in the builtin here? There’s no implementation for count?
https://github.com/cockroachdb/cockroach/blob/master/sql/parser/builtins.go#L980

tamird 14:28
it’s an aggregate, they are handled elsewhere

**Comment by dt** [comment]
looks like the issue is the normalize visitors think that `COUNT(1)` is a constant expression, but it isn't actually. marking `COUNT` as impure should do the trick.

**Comment by dt** [comment]
just where `expr` is non-nil I think?
