### ISSUE TITLE
stress: failed test in cockroach/server/server.test: TestBootstrapNewStore

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5221]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/f587240217828432af6a84192503586355af19ab

Stress build found a failed test:

```
=== RUN   TestBootstrapNewStore
I160314 05:08:40.910792 storage/replica_command.go:1296  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457932121.911s
W160314 05:08:40.912283 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
W160314 05:08:40.912322 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
W160314 05:08:40.913575 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
I160314 05:08:40.917077 server/node.go:362  initialized store store=1:1 ([]=): {Capacity:8312655872 Available:6104748032 RangeCount:0}
I160314 05:08:40.917334 server/node.go:349  store store=0:0 ([]=) not bootstrapped
I160314 05:08:40.917608 server/node.go:349  store store=0:0 ([]=) not bootstrapped
I160314 05:08:40.917628 server/node.go:278  node ID 1 initialized
I160314 05:08:40.917652 storage/split_queue.go:97  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160314 05:08:40.917692 storage/stores.go:289  read 0 node addresses from persistent storage
I160314 05:08:40.917753 server/node.go:482  connecting to gossip network to verify cluster ID...
I160314 05:08:40.917776 server/node.go:503  node connected via gossip and verified as part of cluster "210507c0-38e3-4d18-953d-c34d21bb5555"
I160314 05:08:40.917818 server/node.go:327  [node=1] Started node with [[]= []= []=] engine(s) and attributes []
I160314 05:08:40.940125 server/node.go:465  bootstrapped store store=1:2 ([]=)
I160314 05:08:40.940242 server/node.go:465  bootstrapped store store=1:3 ([]=)
I160314 05:08:40.940535 storage/replica_command.go:1614  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160314 05:08:40.944965 storage/replica_command.go:1296  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457932121.945s
I160314 05:08:40.945043 storage/replica_command.go:1614  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160314 05:08:40.946672 stopper.go:273  draining; tasks left:
1      storage/queue.go:379
1      server/node.go:700
1      kv/txn_coord_sender.go:814
I160314 05:08:40.946709 stopper.go:273  draining; tasks left:
1      storage/queue.go:379
1      server/node.go:700
E160314 05:08:40.946868 storage/queue.go:441  [split] range=1 [/Min-/Table/11): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Table/11) at key "/Table/12/0": failed to send RPC: too many errors encountered (1 of 1 total): rpc error: code = 13 desc = "transport is closing"
I160314 05:08:40.946906 stopper.go:273  draining; tasks left:
1      server/node.go:700
I160314 05:08:41.946998 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:41162: getsockopt: connection refused"; Reconnecting to "127.0.0.1:41162"
I160314 05:08:43.564037 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:41162: getsockopt: connection refused"; Reconnecting to "127.0.0.1:41162"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0xb55b62]

goroutine 1957 [running]:
panic(0x162f8c0, 0xc82000e0f0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/storage.(*treeContext).insertCase4(0xc820856f00, 0xc820171b20, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/range_tree.go:393 +0xe2
github.com/cockroachdb/cockroach/storage.(*treeContext).insertCase3(0xc820856f00, 0xc820171b20, 0x1)
	/go/src/github.com/cockroachdb/cockroach/storage/range_tree.go:376 +0x3c5
github.com/cockroachdb/cockroach/storage.(*treeContext).insertCase2(0xc820856f00, 0xc820171b20, 0x1)
	/go/src/github.com/cockroachdb/cockroach/storage/range_tree.go:349 +0xa1
github.com/cockroachdb/cockroach/storage.(*treeContext).insertCase1(0xc820856f00, 0xc820171b20, 0xc820607c60)
	/go/src/github.com/cockroachdb/cockroach/storage/range_tree.go:336 +0xee
github.com/cockroachdb/cockroach/storage.(*treeContext).insert(0xc820856f00, 0xc820171b20, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/range_tree.go:326 +0xba
github.com/cockroachdb/cockroach/storage.InsertRange(0xc8205d3e00, 0xc820321880, 0xc82104e770, 0x1, 0x8, 0x8)
	/go/src/github.com/cockroachdb/cockroach/storage/range_tree.go:280 +0xb2
github.com/cockroachdb/cockroach/storage.(*Replica).AdminSplit.func1(0xc8205d3e00, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1645 +0x47b
github.com/cockroachdb/cockroach/client.(*DB).Txn.func1(0xc8205d3e00, 0xc82104ecc0, 0x4)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:393 +0x25
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc8205d3e00, 0x1d60101, 0xc820608178, 0x1)
	/go/src/github.com/cockroachdb/cockroach/client/txn.go:462 +0x394
github.com/cockroachdb/cockroach/client.(*DB).Txn(0xc8205a7720, 0xc820608448, 0xc820600438)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:394 +0x1a1
github.com/cockroachdb/cockroach/storage.(*Replica).AdminSplit(0xc8205d4b40, 0x7f370e48e038, 0xc820594030, 0xc82104e738, 0x2, 0x8, 0x0, 0x0, 0x0, 0xc82104e770, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1616 +0xf10
github.com/cockroachdb/cockroach/storage.(*Replica).addAdminCmd(0xc8205d4b40, 0x7f370e48e038, 0xc820594030, 0x143b9d8a1f8c31bf, 0x0, 0x100000001, 0x1, 0x2, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:868 +0x904
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc8205d4b40, 0x7f370e48e038, 0xc820594030, 0x143b9d8a1f8c31bf, 0x0, 0x100000001, 0x1, 0x2, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:714 +0x1ed
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc8201d8fc0, 0x7f370e48e038, 0xc820594030, 0x143b9d8a1f8c31bf, 0x0, 0x100000001, 0x1, 0x2, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1563 +0xf49
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc8204b0a80, 0x7f370e48e038, 0xc820594ab0, 0x0, 0x0, 0x100000001, 0x1, 0x2, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/stores.go:186 +0x5ef
github.com/cockroachdb/cockroach/server.(*Node).Batch.func2()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:688 +0x4ed
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc8206acfc0, 0xc820609880, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:125 +0xd9
github.com/cockroachdb/cockroach/server.(*Node).Batch(0xc820377800, 0x7f370e48e038, 0xc82076bf50, 0xc820170ee0, 0x86064c, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/node.go:700 +0x2ce
github.com/cockroachdb/cockroach/roachpb._Internal_Batch_Handler(0x175a300, 0xc820377800, 0x7f370e48e038, 0xc82076bf50, 0xc8202501c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:1211 +0x132
google.golang.org/grpc.(*Server).processUnaryRPC(0xc820144200, 0x7f370e4da678, 0xc820664120, 0xc8201196c0, 0xc8202a1a80, 0x2206fb0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:497 +0xe13
google.golang.org/grpc.(*Server).handleStream(0xc820144200, 0x7f370e4da678, 0xc820664120, 0xc8201196c0, 0x0)
	/go/src/google.golang.org/grpc/server.go:646 +0x109d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc8205d6dc0, 0xc820144200, 0x7f370e4da678, 0xc820664120, 0xc8201196c0)
	/go/src/google.golang.org/grpc/server.go:323 +0xa0
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/google.golang.org/grpc/server.go:324 +0x9a


ERROR: exit status 2
```

Run Details:

```
0 runs so far, 0 failures, over 5s
4 runs so far, 0 failures, over 10s
8 runs so far, 0 failures, over 15s
14 runs so far, 0 failures, over 20s
18 runs so far, 0 failures, over 25s
23 runs so far, 0 failures, over 30s
25 runs so far, 0 failures, over 35s
30 runs so far, 0 failures, over 40s
34 runs so far, 0 failures, over 45s
40 runs so far, 0 failures, over 50s
44 runs so far, 0 failures, over 55s
47 runs so far, 0 failures, over 1m0s
52 runs so far, 0 failures, over 1m5s
55 runs so far, 0 failures, over 1m10s
60 runs so far, 0 failures, over 1m15s
66 runs so far, 0 failures, over 1m20s
69 runs so far, 0 failures, over 1m25s
73 runs so far, 0 failures, over 1m30s
78 runs so far, 0 failures, over 1m35s
82 runs so far, 0 failures, over 1m40s
87 runs so far, 0 failures, over 1m45s
92 runs so far, 0 failures, over 1m50s
95 runs so far, 0 failures, over 1m55s
100 runs so far, 0 failures, over 2m0s
103 runs so far, 0 failures, over 2m5s
108 runs so far, 0 failures, over 2m10s
111 runs so far, 0 failures, over 2m15s
116 runs so far, 0 failures, over 2m20s
118 runs so far, 0 failures, over 2m25s
124 runs so far, 0 failures, over 2m30s
130 runs so far, 0 failures, over 2m35s
132 runs so far, 0 failures, over 2m40s
136 runs so far, 0 failures, over 2m45s
142 runs so far, 0 failures, over 2m50s
147 runs so far, 0 failures, over 2m55s
151 runs so far, 0 failures, over 3m0s
154 runs so far, 0 failures, over 3m5s
160 runs so far, 0 failures, over 3m10s
163 runs so far, 0 failures, over 3m15s
168 runs so far, 0 failures, over 3m20s
174 runs so far, 0 failures, over 3m25s
176 runs so far, 0 failures, over 3m30s
181 runs so far, 0 failures, over 3m35s
185 runs so far, 0 failures, over 3m40s
190 runs so far, 0 failures, over 3m45s
194 runs so far, 0 failures, over 3m50s
197 runs so far, 0 failures, over 3m55s
202 runs so far, 0 failures, over 4m0s
206 runs so far, 0 failures, over 4m5s
211 runs so far, 0 failures, over 4m10s
214 runs so far, 0 failures, over 4m15s
220 runs so far, 0 failures, over 4m20s
224 runs so far, 0 failures, over 4m25s
228 runs so far, 0 failures, over 4m30s
233 runs so far, 0 failures, over 4m35s
238 runs so far, 0 failures, over 4m40s
242 runs so far, 0 failures, over 4m45s
246 runs so far, 0 failures, over 4m50s
249 runs so far, 0 failures, over 4m55s
254 runs so far, 0 failures, over 5m0s
259 runs so far, 0 failures, over 5m5s
262 runs so far, 0 failures, over 5m10s
268 runs so far, 0 failures, over 5m15s
272 runs so far, 0 failures, over 5m20s
276 runs so far, 0 failures, over 5m25s
282 runs so far, 0 failures, over 5m30s
287 runs so far, 0 failures, over 5m35s
292 runs completed, 1 failures, over 5m40s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by BramGruneir** [comment]
Can't repro locally and we need the other go routines to get a sense of what's happening.  Closing for now.  All go routines will now be posted with stress test results (see #5233).
