### ISSUE TITLE
sql: fix panic when changing primary key of table with partial index

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#52371]
* Fix the panic (below)
* Address this TODO: https://github.com/cockroachdb/cockroach/blob/7ca4a4622a4950245cf35705889f3dd79ada2217/pkg/sql/backfill/backfill.go#L317-L318

```
root@127.0.0.1:56917/defaultdb> create table t (k INT NOT NULL, a INT, index i (a) where a > 5);
CREATE TABLE

Time: 2.729ms

root@127.0.0.1:56917/defaultdb> insert into t values (1, 1);
INSERT 1

Time: 3.308ms

root@127.0.0.1:56917/defaultdb> insert into t values (6, 6);
INSERT 1

Time: 841µs

root@127.0.0.1:56917/defaultdb> select * from t@i where a > 5;
  k | a
----+----
  6 | 6
(1 row)

Time: 947µs

root@127.0.0.1:56917/defaultdb> alter table t add primary key (k);
*
* ERROR: [n1] a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   | runtime.gopanic
*   |   /usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:969
*   | runtime.panicmem
*   |   /usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:212
*   | runtime.sigpanic
*   |   /usr/local/Cellar/go/1.14.4/libexec/src/runtime/signal_unix.go:695
*   | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfiller).BuildIndexEntriesChunk
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill/backfill.go:635
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*indexBackfiller).runChunk.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/indexbackfiller.go:169
*   | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:707
*   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:811
*   | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:706
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*indexBackfiller).runChunk
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/indexbackfiller.go:164
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*backfiller).mainLoop
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/backfiller.go:201
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*backfiller).doRun
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/backfiller.go:138
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*backfiller).Run
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/backfiller.go:122
*   | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:421
*   | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).distBackfill.func4
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:885
*   | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:707
*   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:811
*   | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:706
*   | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).distBackfill
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:825
*   | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).backfillIndexes
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:1300
*   | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).runBackfill
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:263
*   | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).runStateMachineAndBackfill
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1145
*   | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).exec
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:531
*   | github.com/cockroachdb/cockroach/pkg/sql.schemaChangeResumer.Resume.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1750
*   | github.com/cockroachdb/cockroach/pkg/sql.schemaChangeResumer.Resume
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1820
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:850
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resume.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:986
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347
*   | runtime.goexit
*   |   /usr/local/Cellar/go/1.14.4/libexec/src/runtime/asm_amd64.s:1373
* Wraps: (2) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) runtime.errorString
*
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x54ab3d9]

goroutine 9057 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc0000f01b0, 0x9064f80, 0xc00100c600)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:207 +0x11f
panic(0x7e5b500, 0xbaa6480)
        /usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:969 +0x166
github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfiller).BuildIndexEntriesChunk(0xc0001ac128, 0x9065040, 0xc001e5a540, 0xc0009c0b40, 0xc0026f6000, 0xc001714290, 0x2, 0x8, 0xc001714298, 0x2, ...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill/backfill.go:635 +0x3c9
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*indexBackfiller).runChunk.func1(0x9065040, 0xc001e5a540, 0xc0009c0b40, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/indexbackfiller.go:169 +0x154
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn.func1(0x9065040, 0xc001e5a540, 0xc0009c0b40, 0x3ff0000000000000, 0x910e3e0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:707 +0x43
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec(0xc0009c0b40, 0x9065040, 0xc001e5a540, 0xc0029d9158, 0xc0009c0b40, 0xc035277f88)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:811 +0xd9
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn(0xc0001f8000, 0x9065040, 0xc001e5a540, 0xc0029d9338, 0xc00004e000, 0x9065040)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:706 +0xfa
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*indexBackfiller).runChunk(0xc0001ab900, 0x9065040, 0xc001e5a540, 0xc002712700, 0x2, 0x2, 0xc001714290, 0x2, 0x8, 0xc001714298, ...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/indexbackfiller.go:164 +0x2a5
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*backfiller).mainLoop(0xc0001ab900, 0x9065040, 0xc001e5a540, 0xc002712700, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/backfiller.go:201 +0x3d6
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*backfiller).doRun(0xc0001ab900, 0x9065040, 0xc001e5a540, 0xf)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/backfiller.go:138 +0x470
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*backfiller).Run(0xc0001ab900, 0x9065040, 0xc001e5a540)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/backfiller.go:122 +0x1c3
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc0026d7680, 0x9064f80, 0xc002712600, 0x85e08c0, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370 +0x241
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00123ba20, 0xc000578bd0, 0x0, 0xc0029db608, 0xc00207e900, 0xc00207a580, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:421 +0x5c9
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).distBackfill.func4(0x9065040, 0xc002d41e60, 0xc0009c0870, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:885 +0x6d9
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn.func1(0x9065040, 0xc002d41e60, 0xc0009c0870, 0x3ff0000000000000, 0x910e3e0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:707 +0x43
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec(0xc0009c0870, 0x9065040, 0xc002d41e60, 0xc0029dc140, 0xc0009c0870, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:811 +0xd9
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn(0xc0001f8000, 0x9065040, 0xc002d41e60, 0xc0029dc2a8, 0x2, 0x84498f5)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:706 +0xfa
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).distBackfill(0xc002827340, 0x9065040, 0xc002d41e60, 0x3, 0x2, 0xc350, 0x85e14a8, 0xc00208c0c0, 0x2, 0x2, ...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:825 +0x407
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).backfillIndexes(0xc002827340, 0x9065040, 0xc002d41e60, 0x3, 0xc00208c0c0, 0x2, 0x2, 0x2, 0xc000b38210)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:1300 +0x2e2
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).runBackfill(0xc002827340, 0x9065040, 0xc002d41e60, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill.go:263 +0x89f
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).runStateMachineAndBackfill(0xc002827340, 0x9065040, 0xc002d41e60, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1145 +0x89
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).exec(0xc002827340, 0x9065040, 0xc002d41e30, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:531 +0x3ad
github.com/cockroachdb/cockroach/pkg/sql.schemaChangeResumer.Resume.func1(0x100000036, 0xc000000000, 0xc002a05780, 0x9113740)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1750 +0x52e
github.com/cockroachdb/cockroach/pkg/sql.schemaChangeResumer.Resume(0xc001fbab40, 0x9065040, 0xc002d41e30, 0x83f29e0, 0xc0001e8000, 0xc002ace600, 0x9065040, 0xc002d41e30)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1820 +0x69d
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine(0xc000016c40, 0x9065040, 0xc001fb7bc0, 0x83f29e0, 0xc0001e8000, 0x901a700, 0xc000f2a5c8, 0xc002ace600, 0xc001fbab40, 0xc0018cb038, ...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:850 +0x747
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resume.func1(0x9064f80, 0xc00100c600)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:986 +0x594
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0000f01b0, 0x9064f80, 0xc00100c600, 0xc0004b95e0, 0x1e, 0x0, 0x0, 0xc0009a5590)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0xee
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:342 +0x131
```

**Comment by mgartner** [comment]
Closing. This was an issue originally in #52213 that is now fixed and tested before merging.
