### ISSUE TITLE
sql/multitenancy: DROP DATABASE CASCADE hangs in multitenant environment

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#52567]
Minimal repro:
```
# LogicTest: 3node-tenant

statement ok
CREATE DATABASE a

statement ok
SET DATABASE = a

statement ok
CREATE TABLE t (id INT PRIMARY KEY)

statement ok
DROP DATABASE a CASCADE
```

**Comment by asubiotto** [comment]
Looks like we're waiting for an update on the drop database:
```
goroutine 2993 [sync.Cond.Wait, 1 minutes]:
runtime.goparkunlock(...)
    /usr/local/opt/go/libexec/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc003389390, 0x0)
    /usr/local/opt/go/libexec/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc003389380)
    /usr/local/opt/go/libexec/src/sync/cond.go:56 +0x9d
github.com/cockroachdb/cockroach/pkg/sql.(*databaseCacheHolder).WaitForCacheState(0xc0009bfdc0, 0xc001bf6670)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:895 +0x86
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).WaitForCacheToDropDatabases(0xc001556aa8, 0x9118f40, 0xc002f975c0)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:714 +0xf8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper(0xc001556880, 0x908d260, 0xb8ad180, 0x7f6ade0, 0xc005116818, 0x36805530, 0xc004c30f80, 0xc, 0x0, 0x0, ...)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2234 +0x73c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc001556880, 0x9118f40, 0xc005042400, 0x0, 0x0)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1532 +0xf4c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001556880, 0x9118f40, 0xc002f975c0, 0xc002360500, 0x5400, 0x15000, 0xc0023605a0, 0xc004c192b0, 0x0, 0x0)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1338 +0x1ee
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc001872c00, 0x9118f40, 0xc002f975c0, 0xc001556880, 0x5400, 0x15000, 0xc0023605a0, 0xc004c192b0, 0x0, 0x0)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:496 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc000cd782d, 0xc004c2d9a0, 0x9118f40, 0xc002f975c0, 0xc004c192b0, 0xc001872c00, 0xc004c30900, 0x9144ec0, 0xc0040cdcb0, 0xc004c58ba0, ...)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:580 +0x39b
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:508 +0x17e
```

Which never happens because `updateSystemConfig` is never called. @nvanbenschoten is this a case of having to use https://github.com/cockroachdb/cockroach/pull/52034?

**Comment by nvanbenschoten** [comment]
I think this may actually be related to https://github.com/cockroachdb/cockroach/issues/49692. @ajwerner or @lucy-zhang do you mind weighing in on this?

**Comment by ajwerner** [comment]
Yeah, whoops, that fix just doesn't work. https://github.com/cockroachdb/cockroach/pull/52553 is going to fix this the right way.
