### ISSUE TITLE
sql: panic running `show create table` on table in offline state

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#52829]
```
root@localhost:26257/defaultdb> select * from foo;
ERROR: table is being added
root@localhost:26257/defaultdb> show create table foo;
ERROR: driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the transaction status: dial tcp 127.0.0.1:26257: connect: connection refused
warning: connection lost!
```
and in the logs:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x31d98e9]

goroutine 47810 [running]:
panic(0x4a06080, 0x89d51e0)
        /usr/local/go/src/runtime/panic.go:722 +0x2c2 fp=0xc00151fb60 sp=0xc00151fad0 pc=0x7b0ae2
runtime.panicmem(...)
        /usr/local/go/src/runtime/panic.go:199
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:394 +0x3ec fp=0xc00151fb90 sp=0xc00151fb60 pc=0x7c67ac
github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.(*TableDescriptor).IsVirtualTable(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb/structured.go:246
github.com/cockroachdb/cockroach/pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func2(0x60cb380, 0xc002992340, 0x6226760, 0xc000816488, 0xc001940770, 0xc001a38d20, 0xc001c26aa0, 0x7de6c7, 0xc000ed2f58, 0x7b2c8c)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1097 +0x129 fp=0xc00151fcb8 sp=0xc00151fb90 pc=0x31d98e9
github.com/cockroachdb/cockroach/pkg/sql.virtualDefEntry.makeConstrainedRowsGenerator.func1(0x60353c0, 0xc001a5e6c0, 0x2, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:578 +0x468 fp=0xc00151fe98 sp=0xc00151fcb8 pc=0x31ef448
github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func2(0x60cb380, 0xc0029923c0, 0xc0013b87e0, 0xc002260690, 0xc001a5e6c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:112 +0x109 fp=0xc00151ffb8 sp=0xc00151fe98 pc=0x31efa79
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00151ffc0 sp=0xc00151ffb8 pc=0x7e12b1
created by github.com/cockroachdb/cockroach/pkg/sql.setupGenerator
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:101 +0xf7```

**Comment by ajwerner** [comment]
Did you have an easy way to get the table stuck in adding?

**Comment by dt** [comment]
@ajwerner I hit this after hitting #52828

**Comment by lucy-zhang** [comment]
I think whatever is happening here is specific to the aborted backfill from #52828. When I create a materialized view with the same schema as in that issue and leave the table in the adding state pre-backfill, I get a normal error `pq: relation "foo" does not exist`. I'll keep looking.

**Comment by lucy-zhang** [comment]
Never mind, that's not true. I was running this on master, where this is fixed: we seem to correctly no longer allow resolution of tables in the adding state, which I think is the correct solution. The change happened in #52497. Presumably we now filter tables by state somewhere. I'm trying to understand this.

**Comment by lucy-zhang** [comment]
The change is just due to us previously mishandling tables in the adding state returned from `planner.LookupTableByID()`: it was supposed to be indicated in a flag but we weren't checking it and just assuming the descriptor would be returned. Here's the diff: https://github.com/cockroachdb/cockroach/commit/6afa86100c15f1963369cd633e2233546d9a920c#diff-a91d03681cbe82ce7782155f6a35e0f2L494

Now we don't use `catalog.TableEntry` and just pass the error along. So we're fine now. I'll add a test.
