### ISSUE TITLE
stress: failed test in cockroach/storage/storage.test: TestBaseQueueProcess

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5289]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/8971c97744391a80c02dafcebff3266105b854ee

Stress build found a failed test:

```
=== RUN   TestBaseQueueProcess
W160316 06:41:22.027194 gossip/gossip.go:898  not connected to cluster; use --join to specify a connected node
SIGABRT: abort
PC=0x661131 m=0

goroutine 0 [idle]:
runtime.futex(0x27a54c8, 0x0, 0x0, 0x0, 0x0, 0x27a43d0, 0x0, 0x0, 0x60fa04, 0x27a54c8, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:302 +0x21
runtime.futexsleep(0x27a54c8, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x27a54c8)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1535 +0x10b
runtime.findrunnable(0xc820018a00, 0x0)
	/usr/local/go/src/runtime/proc.go:1973 +0x739
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2072 +0x24f
runtime.park_m(0xc8204a6180)
	/usr/local/go/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x7ffdfa75d520)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0x1cbf648, 0x2454180, 0xf1, 0xf1, 0x609e2548c02d1601)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc8200e4f08, 0xc6ce8d)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc8200e4f08)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:36 +0x26
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:542 +0x114

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x27a4200)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1003 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 403 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc820154104)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc8201540f8)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc8201540e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:302 +0x1dd
github.com/cockroachdb/cockroach/storage.TestBaseQueueProcess(0xc8201b6000)
	/go/src/github.com/cockroachdb/cockroach/storage/queue_test.go:305 +0x91b
testing.tRunner(0xc8201b6000, 0x24544e0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 367 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/storage.(*testQueueImpl).timer(0xc82013e980, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/queue_test.go:88 +0x45
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:367 +0x172
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201540e0, 0xc820188aa0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

rax    0xca
rbx    0x0
rcx    0x661133
rdx    0x0
rdi    0x27a54c8
rsi    0x0
rbp    0x1
rsp    0x7ffdfa75d380
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc820188d80
r13    0x7f51c48d6320
r14    0x1
r15    0x8
rip    0x661131
rflags 0x286
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
1 runs so far, 0 failures, over 20s
1 runs so far, 0 failures, over 25s
8 runs so far, 0 failures, over 30s
8 runs so far, 0 failures, over 35s
8 runs so far, 0 failures, over 40s
9 runs so far, 0 failures, over 45s
9 runs so far, 0 failures, over 50s
15 runs so far, 0 failures, over 55s
15 runs so far, 0 failures, over 1m0s
15 runs so far, 0 failures, over 1m5s
16 runs so far, 0 failures, over 1m10s
16 runs so far, 0 failures, over 1m15s
21 runs so far, 0 failures, over 1m20s
21 runs so far, 0 failures, over 1m25s
21 runs so far, 0 failures, over 1m30s
21 runs so far, 0 failures, over 1m35s
21 runs so far, 0 failures, over 1m40s
25 runs so far, 0 failures, over 1m45s
26 runs so far, 0 failures, over 1m50s
27 runs so far, 0 failures, over 1m55s
27 runs so far, 0 failures, over 2m0s
27 runs so far, 0 failures, over 2m5s
30 runs so far, 0 failures, over 2m10s
30 runs so far, 0 failures, over 2m15s
32 runs so far, 0 failures, over 2m20s
32 runs so far, 0 failures, over 2m25s
32 runs so far, 0 failures, over 2m30s
35 runs so far, 0 failures, over 2m35s
35 runs so far, 0 failures, over 2m40s
36 runs so far, 0 failures, over 2m45s
37 runs so far, 0 failures, over 2m50s
37 runs so far, 0 failures, over 2m55s
40 runs so far, 0 failures, over 3m0s
40 runs so far, 0 failures, over 3m5s
40 runs so far, 0 failures, over 3m10s
43 runs so far, 0 failures, over 3m15s
43 runs so far, 0 failures, over 3m20s
45 runs so far, 0 failures, over 3m25s
45 runs so far, 0 failures, over 3m30s
46 runs so far, 0 failures, over 3m35s
48 runs so far, 0 failures, over 3m40s
48 runs so far, 0 failures, over 3m45s
49 runs so far, 0 failures, over 3m50s
49 runs so far, 0 failures, over 3m55s
50 runs so far, 0 failures, over 4m0s
52 runs so far, 0 failures, over 4m5s
52 runs so far, 0 failures, over 4m10s
52 runs so far, 0 failures, over 4m15s
53 runs so far, 0 failures, over 4m20s
54 runs so far, 0 failures, over 4m25s
57 runs so far, 0 failures, over 4m30s
57 runs so far, 0 failures, over 4m35s
58 runs so far, 0 failures, over 4m40s
59 runs so far, 0 failures, over 4m45s
60 runs so far, 0 failures, over 4m50s
63 runs so far, 0 failures, over 4m55s
64 runs so far, 0 failures, over 5m0s
65 runs so far, 0 failures, over 5m5s
66 runs so far, 0 failures, over 5m10s
66 runs so far, 0 failures, over 5m15s
69 runs so far, 0 failures, over 5m20s
71 runs so far, 0 failures, over 5m25s
72 runs so far, 0 failures, over 5m30s
73 runs so far, 0 failures, over 5m35s
74 runs so far, 0 failures, over 5m40s
75 runs so far, 0 failures, over 5m45s
77 runs so far, 0 failures, over 5m50s
77 runs so far, 0 failures, over 5m55s
79 runs so far, 0 failures, over 6m0s
80 runs so far, 0 failures, over 6m5s
81 runs so far, 0 failures, over 6m10s
83 runs so far, 0 failures, over 6m15s
83 runs so far, 0 failures, over 6m20s
85 runs so far, 0 failures, over 6m25s
86 runs so far, 0 failures, over 6m30s
86 runs so far, 0 failures, over 6m35s
88 runs so far, 0 failures, over 6m40s
90 runs so far, 0 failures, over 6m45s
91 runs so far, 0 failures, over 6m50s
92 runs so far, 0 failures, over 6m55s
93 runs so far, 0 failures, over 7m0s
93 runs so far, 0 failures, over 7m5s
96 runs so far, 0 failures, over 7m10s
96 runs so far, 0 failures, over 7m15s
98 runs so far, 0 failures, over 7m20s
98 runs so far, 0 failures, over 7m25s
98 runs so far, 0 failures, over 7m30s
101 runs so far, 0 failures, over 7m35s
102 runs so far, 0 failures, over 7m40s
104 runs so far, 0 failures, over 7m45s
104 runs so far, 0 failures, over 7m50s
104 runs so far, 0 failures, over 7m55s
107 runs so far, 0 failures, over 8m0s
108 runs so far, 0 failures, over 8m5s
108 runs so far, 0 failures, over 8m10s
110 runs so far, 0 failures, over 8m15s
110 runs so far, 0 failures, over 8m20s
113 runs so far, 0 failures, over 8m25s
115 runs so far, 0 failures, over 8m30s
115 runs so far, 0 failures, over 8m35s
116 runs so far, 0 failures, over 8m40s
116 runs so far, 0 failures, over 8m45s
120 runs so far, 0 failures, over 8m50s
121 runs so far, 0 failures, over 8m55s
121 runs so far, 0 failures, over 9m0s
122 runs so far, 0 failures, over 9m5s
122 runs so far, 0 failures, over 9m10s
125 runs so far, 0 failures, over 9m15s
127 runs so far, 0 failures, over 9m20s
127 runs so far, 0 failures, over 9m25s
128 runs so far, 0 failures, over 9m30s
128 runs so far, 0 failures, over 9m35s
131 runs so far, 0 failures, over 9m40s
133 runs so far, 0 failures, over 9m45s
133 runs so far, 0 failures, over 9m50s
133 runs so far, 0 failures, over 9m55s
133 runs so far, 0 failures, over 10m0s
135 runs so far, 0 failures, over 10m5s
137 runs so far, 0 failures, over 10m10s
137 runs so far, 0 failures, over 10m15s
137 runs so far, 0 failures, over 10m20s
137 runs so far, 0 failures, over 10m25s
138 runs so far, 0 failures, over 10m30s
141 runs so far, 0 failures, over 10m35s
141 runs so far, 0 failures, over 10m40s
142 runs so far, 0 failures, over 10m45s
142 runs so far, 0 failures, over 10m50s
143 runs so far, 0 failures, over 10m55s
146 runs so far, 0 failures, over 11m0s
147 runs so far, 0 failures, over 11m5s
148 runs so far, 0 failures, over 11m10s
148 runs so far, 0 failures, over 11m15s
149 runs so far, 0 failures, over 11m20s
151 runs so far, 0 failures, over 11m25s
151 runs so far, 0 failures, over 11m30s
152 runs so far, 0 failures, over 11m35s
152 runs so far, 0 failures, over 11m40s
153 runs completed, 1 failures, over 11m42s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment]
I can reproduce a failure with this test. Both the reproduced failure and the one above show that the `defer stopper.Stop()` call is failing to return.

**Comment by petermattis** [comment]
This is the problematic goroutine:

```
goroutine 30 [chan receive]:
github.com/cockroachdb/cockroach/storage.(*testQueueImpl).timer(0xc8201bed40, 0x0)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/queue_test.go:88 +0x45
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/queue.go:367 +0x172
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201b4070, 0xc8201c8300)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

Looks like we're not setting `testQueueImpl.blocker` in a safe manner.
