### ISSUE TITLE
cdc: panic: semaphore release without acquire

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#53366]
Test flake?

```
=== RUN   TestChangefeedNemeses/sinkless
panic: semaphore release without acquire [recovered]
  panic: semaphore release without acquire
goroutine 218102 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc00209c240, 0x5c2ff60, 0xc001494740)
  /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:207 +0x11f
panic(0x44e0a40, 0x5b3b180)
  /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/marusama/semaphore.(*semaphore).Release(0xc003d35e60, 0x1, 0xc001d26000)
  /go/src/github.com/cockroachdb/cockroach/vendor/github.com/marusama/semaphore/semaphore.go:170 +0x11d
github.com/cockroachdb/cockroach/pkg/util/limit.(*ConcurrentRequestLimiter).Finish(...)
  /go/src/github.com/cockroachdb/cockroach/pkg/util/limit/limiter.go:54
github.com/cockroachdb/cockroach/pkg/kv/kvserver.iteratorWithCloser.Close(0x5c86b40, 0xc001d26000, 0xc009813150)
  /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_rangefeed.go:120 +0x3b
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registration).maybeRunCatchupScan.func1(0x5c87500, 0xc002a32dc0, 0xc001091ea0, 0x2453900d, 0xed6d61674, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:290 +0x31
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registration).maybeRunCatchupScan(0xc001091ea0, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:411 +0xe22
```

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2217816?

**Comment by irfansharif** [comment]
I have a somewhat reliable repro for this running https://github.com/cockroachdb/cockroach/pull/52526/files#diff-3d4bd4076f3843bd43527cb196fb5d06R35-R39. I can polish it up for others if hard to repro through if TestChangefeedNemeses is not reliable enough for it.

**Comment by irfansharif** [comment]
+cc @mwang1026.

**Comment by irfansharif** [comment]
@ajwerner know anything about this? I see you were in the area as of #52844.

**Comment by ajwerner** [comment]
This was introduced in #52844 but should have been fixed by https://github.com/cockroachdb/cockroach/pull/53295.

**Comment by ajwerner** [comment]
I'm going to close this as I do think #53295 fixed it.
