### ISSUE TITLE
geo/geomfn: ST_AsText output different from PostGIS (extra space)

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#53651]
**Describe the problem**

The output of ST_AsText is different from PostGIS, causing a test failure in Django's test suite:
```
======================================================================
FAIL: test_aswkt (gis_tests.geoapp.test_functions.GISFunctionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/test/testcases.py", line 1215, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/home/tim/code/django/tests/gis_tests/geoapp/test_functions.py", line 171, in test_aswkt
    self.assertEqual(wkt, 'POINT (1.0 2.0)' if oracle else 'POINT(1 2)')
AssertionError: 'POINT (1 2)' != 'POINT(1 2)'
- POINT (1 2)
?      -
+ POINT(1 2)
```

**To Reproduce**
```sql
> SELECT ST_AsText(ST_GeomFromEWKB('\x0101000020e6100000000000000000f03f0000000000000040'::bytea));
   st_astext
---------------
  POINT (1 2)
```
**Expected behavior**

Outputs: `POINT(1 2)` (without the space after POINT)

**Environment:**
 - CockroachDB version 20.2 alpha 3

\cc @otan

**Comment by otan** [comment]
unlikely we'll resolve this in v20.2, but maybe later. both are correct representations.

**Comment by timgraham** [comment]
Still a valid issue.
