### ISSUE TITLE
kv,storage: another occurrence of iterator created after the stopper quiesces

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#53821]
Found in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/2241826

```
------- Stdout: -------
=== RUN   TestLogic/fakedist-disk/fk/Composite_Full_Add_Constraint_Valid
--- done: testdata/logic_test/distsql_automatic_stats with config fakedist-disk: 21 tests, 0 failures
panic: pebble: closed
goroutine 9539655 [running]:
github.com/cockroachdb/pebble.(*DB).Apply(0xc081398000, 0xc05b2ef0e0, 0x7f3ac82, 0x3fd0d80, 0xc04a042800)
  /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:524 +0x3f5
github.com/cockroachdb/pebble.(*Batch).Commit(...)
  /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/batch.go:727
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMapBatchWriter).Flush(0xc0707bafc0, 0xc04a042800, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/storage/disk_map.go:434 +0x48
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMapBatchWriter).Close(0xc0707bafc0, 0x5694640, 0xc0550af780, 0x183160f, 0xc04a042800)
  /go/src/github.com/cockroachdb/cockroach/pkg/storage/disk_map.go:449 +0x2b
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*DiskRowContainer).Close(0xc072ce97c0, 0x5694640, 0xc0550af780)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/disk_row_container.go:390 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/rowcontainer.(*DiskBackedRowContainer).Close(0xc061bc5200, 0x5694640, 0xc0550af780)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowcontainer/row_container.go:553 +0xfc
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*sorterBase).close(0xc061e3ea00)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/sorter.go:122 +0x92
github.com/cockroachdb/cockroach/pkg/sql/rowexec.newSortAllProcessor.func1(0x5694640, 0xc0550af780, 0x0, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/sorter.go:257 +0x2c
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).moveToTrailingMeta(0xc061e3ea00)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:716 +0x135
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).DrainHelper(0xc061e3ea00, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:650 +0x1e6
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*sorterBase).Next(0xc061e3ea00, 0x0, 0x0, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/sorter.go:112 +0x16a
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run(0x5694640, 0xc0550af780, 0x56bf7c0, 0xc061e3ea00, 0x56734c0, 0xc061e98000)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:170 +0x35
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run(0xc061e3ea00, 0x5694640, 0xc0550af780)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:763 +0x92
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc061de87e0, 0x5694640, 0xc0550af780, 0x4cb2e40, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:380 +0x24d
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc03c84fce0, 0xc072e32d90, 0xc074c27440, 0xc07eaa4c00, 0xc0552f9180, 0xc061c2a500, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:422 +0x5d9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc03c84fce0, 0x5694700, 0xc070ead770, 0xc061c2a500, 0xc072e32d90, 0xc074c27440, 0x5697140, 0xc0707ba9f0, 0x0, 0xc0552f9180, ...)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:991 +0x1d1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc061c2a000, 0x5694700, 0xc070ead770, 0xc061c2a410, 0x3, 0x57024a0, 0xc05dec62a0, 0xc028a6c200, 0xc05dec6358, 0x0, ...)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1058 +0x3c0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc061c2a000, 0x5694700, 0xc070ead770, 0xc061c2a410, 0x57024a0, 0xc05dec62a0, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:929 +0x6ff
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc061c2a000, 0x5694700, 0xc070ead770, 0x56b30c0, 0xc0130042d0, 0x488e091, 0xca, 0x1, 0x1, 0xc07410c780, ...)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:609 +0xb58
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc061c2a000, 0x5694700, 0xc070ead770, 0x56b30c0, 0xc0130042d0, 0x488e091, 0xca, 0x1, 0x1, 0xc07410c780, ...)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:116 +0x909
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal(0xc061c2a000, 0x5694700, 0xc070ead740, 0xc05b2eed20, 0xc03ecab690, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:205 +0x27e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc061c2a000, 0x5694640, 0xc0550aee80, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1504 +0x10a7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc061c2a000, 0x5694700, 0xc0713d7ef0, 0xc07f477b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1377 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1(0xc061c2a000, 0x5694700, 0xc0713d7ef0, 0xc01588ec60, 0xc084ac01e0, 0x0, 0xc064977270)
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:175 +0x64
created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx
  /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:174 +0x2f0
```

**Comment by knz** [comment]
cc @tbg  for triage
