### ISSUE TITLE
roachtest: acceptance/bank/cluster-recovery failed [skipped]

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#53829]
```
[Run local roachtests] local: stopping and waiting06:25:41 test.go:337: test failure: 	bank.go:354,bank.go:548,acceptance.go:91,test_runner.go:754: pq: cannot up-replicate to s2; missing gossiped StoreDescriptor
[06:25:41]
[Run local roachtests] 06:25:41 bank.go:163: client 3 shutting down
[06:25:41]
[Run local roachtests] 06:25:41 bank.go:163: client 1 shutting down
[06:25:41]
[Run local roachtests] 06:25:41 test.go:337: [not the first failure] test failure: 
[06:25:41]
[Run local roachtests] 	cluster.go:2163,cluster.go:2094,bank.go:240: /go/src/github.com/cockroachdb/cockroach/bin/roachprod stop local:3 returned: context canceled
[06:25:41]
[Run local roachtests] 		(1) /go/src/github.com/cockroachdb/cockroach/bin/roachprod stop local:3 returned
[06:25:41]
[Run local roachtests] 		  | stderr:
[06:25:41]
[Run local roachtests] 		  |
[06:25:41]
[Run local roachtests] 		  | stdout:
[06:25:41]
[Run local roachtests] 		  | local: stopping and waiting
[06:25:41]
[Run local roachtests] 		Wraps: (2) secondary error attachment
[06:25:41]
[Run local roachtests] 		  | signal: killed
[06:25:41]
[Run local roachtests] 		  | (1) signal: killed
[06:25:41]
[Run local roachtests] 		  | Error types: (1) *exec.ExitError
[06:25:41]
[Run local roachtests] 		Wraps: (3) context canceled
[06:25:41]
[Run local roachtests] 		Error types: (1) *main.withCommandDetails (2) *secondary.withSecondaryError (3) *errors.errorString
[06:25:41]
[Run local roachtests] 06:25:41 bank.go:168: client 2 shutting down
[06:25:41]
[Run local roachtests] panic: t.Fatal() was called
[06:25:41]
[Run local roachtests] 
[06:25:41]
[Run local roachtests] goroutine 23199 [running]:
[06:25:41]
[Run local roachtests] main.(*test).fatalfInner(0xc0003387e0, 0x0, 0x0, 0xc000529510, 0x1, 0x1)
[06:25:41]
[Run local roachtests] 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test.go:291 +0xcd
[06:25:41]
[Run local roachtests] main.(*test).Fatal(0xc0003387e0, 0xc000529510, 0x1, 0x1)
[06:25:41]
[Run local roachtests] 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test.go:266 +0x51
[06:25:41]
[Run local roachtests] main.(*cluster).Stop(0xc000c8c1e0, 0x526cb20, 0xc00137c420, 0xc00120fd90, 0x1, 0x1)
[06:25:41]
[Run local roachtests] 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2163 +0x105
[06:25:41]
[Run local roachtests] main.(*cluster).Restart(0xc000c8c1e0, 0x526cb20, 0xc00137c420, 0xc0003387e0, 0xc00050ffc8, 0x1, 0x1)
[06:25:41]
[Run local roachtests] 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2094 +0xed
[06:25:41]
[Run local roachtests] main.(*bankState).startChaosMonkey.func1(0xc00137e3c0, 0xc000c8c1e0, 0x526caa0, 0xc000b22040, 0xc0003387e0, 0xc000902fa0)
[06:25:41]
[Run local roachtests] 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/bank.go:240 +0x4b6
[06:25:41]
[Run local roachtests] created by main.(*bankState).startChaosMonkey
[06:25:41]
[Run local roachtests] 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/bank.go:210 +0x92
[06:25:41]
[Run local roachtests] 
```

**Comment by tbg** [comment]
PS I believe this affects all acceptance/bank tests potentially.

**Comment by sumeerbhola** [comment]
Failed again https://teamcity.cockroachdb.com/viewLog.html?buildId=2525179&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Roachtest

**Comment by tbg** [comment]
This last one looks more like https://github.com/cockroachdb/cockroach/issues/57798#issuecomment-755221635. Tracking in https://github.com/cockroachdb/cockroach/issues/57342
