### ISSUE TITLE
sql: panic during types.PGName on spatial type

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#53952]
```
* ERROR: [n4,client=127.0.0.1:44342,hostnossl,user=root] a SQL panic has occurred while executing "SELECT column_name FROM [SHOW COLUMNS FROM table20] ORDER BY random() LIMIT 1": unknown PG name for oid 90005
*
*
* ERROR: [n4,client=127.0.0.1:44342,hostnossl,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT _ FROM [SHOW COLUMNS FROM _] ORDER BY random() LIMIT _

goroutine 3455 [running]:
runtime/debug.Stack(0x4be3420, 0xc0046d2240, 0x3)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x4be3420, 0xc0046d2240, 0xc000547500, 0x411e400, 0xc0045c2180, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:218 +0xb5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0011da000, 0x4be3420, 0xc0046d2240, 0x3fafe60, 0xc0056e6f60)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:818 +0x348
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0011da000, 0x4be3420, 0xc0046d2240)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:477 +0x61
panic(0x3fafe60, 0xc0056e6f60)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/sql/types.(*T).PGName(0xc003c7ecb0, 0x4c601c0, 0x7594960)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/types/types.go:1102 +0x148
github.com/cockroachdb/cockroach/pkg/sql.glob..func64.1.1(0xc003c7ec98, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:417 +0x33f
github.com/cockroachdb/cockroach/pkg/sql.forEachColumnInTable(0xc003c7c000, 0xc00386cef8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1720 +0x86
github.com/cockroachdb/cockroach/pkg/sql.glob..func64.1(0xc0049fcde0, 0x4314418, 0x6, 0xc003c7c000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:380 +0x10d
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDesc.func1(0xc0049fcde0, 0x4314418, 0x6, 0xc003c7c000, 0xc004855900, 0x1, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1532 +0x4d
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternal(0x4be3420, 0xc00574b2c0, 0xc0011da3d8, 0xc004bcf4a0, 0x0, 0x0, 0xc00386d0b0, 0xc0048558b0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1692 +0x432
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookup(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1597
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDesc(0x4be3420, 0xc00574b2c0, 0xc0011da3d8, 0xc004bcf4a0, 0x0, 0xc00386d110, 0x50, 0x4026240)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1526 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.glob..func64(0x4be3420, 0xc00574b2c0, 0xc0011da3d8, 0xc004bcf4a0, 0xc0048558b0, 0xc004855860, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:377 +0x81
github.com/cockroachdb/cockroach/pkg/sql.virtualDefEntry.getPlanInfo.func1(0x4be3420, 0xc00574b2c0, 0xc0011da3d8, 0xc000249120, 0xc, 0xc00004e000, 0x3e2a540, 0x3ed28c0, 0x7f4d5117f048)
```

Seen during a random schema change test, in `acceptance/version-upgrade`: https://teamcity.cockroachdb.com/viewLog.html?buildId=2247238&buildTypeId=Cockroach_UnitTests&tab=artifacts#%2Facceptance%2Facceptance;%2Froachtest%2Facceptance%2Fversion-upgrade

Code is here:

```
// PGName returns the Postgres name for the type. This is sometimes different
// than the native CRDB name for it (i.e. the Name function). It is used when
// compatibility with PG is important. Examples of differences:
//
//   Name()       PGName()
//   --------------------------
//   char         bpchar
//   "char"       char
//   bytes        bytea
//   int4[]       _int4
//
func (t *T) PGName() string {
	name, ok := oidext.TypeName(t.Oid())
	if ok {
		return strings.ToLower(name)
	}

	// For user defined types, return the basename.
	if t.UserDefined() {
		return t.TypeMeta.Name.Basename()
	}

	// Postgres does not have an UNKNOWN[] type. However, CRDB does, so
	// manufacture a name for it.
	if t.Family() != ArrayFamily || t.ArrayContents().Family() != UnknownFamily {
		panic(errors.AssertionFailedf("unknown PG name for oid %d", t.Oid()))
	}
	return "_unknown"
}
```

**Comment by jordanlewis** [comment]
While we're at it, can we change this to not panic? Return a string with an error and log to sentry. Anything is better than panicking from sql.

**Comment by otan** [comment]
this smells like we're trying to use box2d in v20.1, despite the version gate not permitting it (https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/create_table.go#L176) -- is there a path to adding a column i'm not aware of?

**Comment by otan** [comment]
oh i see, it's an array.
