### ISSUE TITLE
circleci: failed tests (14861): TestSchemaChangeLease

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5402]
The following test appears to have failed:

[#14861](https://circleci.com/gh/cockroachdb/cockroach/14861):

```
I160319 18:02:48.493968 client/db.go:422  failed batch: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:702: node 1 stopped
W160319 18:02:48.494014 storage/intent_resolver.go:283  [node=1,store=1,range=5] failed to resolve intents: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:702: node 1 stopped
I160319 18:02:48.494028 stopper.go:352  draining; tasks left:
1      storage/intent_resolver.go:330
I160319 18:02:49.493966 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:45742: getsockopt: connection refused"; Reconnecting to "127.0.0.1:45742"
panic: test timed out after 1m10s

goroutine 24090 [running]:
panic(0x1482280, 0xc8207bb000)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x1bb21b0, 0x232b7a0, 0x48, 0x48, 0xd0ddd18a389d7e01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820322f08, 0x11)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/sql_test.TestMain(0xc820322f08)
	/go/src/github.com/cockroachdb/cockroach/sql/main_test.go:234 +0x26
main.main()
	github.com/cockroachdb/cockroach/sql/_test/_testmain.go:382 +0x114

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x25ff440)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1003 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 22913 [semacquire]:
sync.runtime_Semacquire(0xc8205fa024)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc8205fa018)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc8205fa000)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:302 +0x1dd
github.com/cockroachdb/cockroach/server.(*Server).Stop(0xc8213dc0d0)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:359 +0x28
github.com/cockroachdb/cockroach/server.(*TestServer).Stop(0xc820016780)
	/go/src/github.com/cockroachdb/cockroach/server/testserver.go:318 +0x5d
--
testing.tRunner(0xc8200195f0, 0x232bcf8)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 23407 [sleep]:
time.Sleep(0x62691250)
	/usr/local/go/src/runtime/time.go:59 +0xf9
google.golang.org/grpc.(*Conn).resetTransport(0xc8207e9500, 0xc800000000, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:461 +0x79f
google.golang.org/grpc.NewConn.func1(0xc8207e9500)
	/go/src/google.golang.org/grpc/clientconn.go:317 +0x2a
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:323 +0x509

goroutine 22993 [IO wait]:
net.runtime_pollWait(0x7f0a34074918, 0x72, 0xc8201c4800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820052220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820052220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200521c0, 0xc8201c4800, 0x400, 0x400, 0x0, 0x7f0a38a58050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82042e000, 0xc8201c4800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc/transport.(*http2Client).reader(0xc820634c30)
	/go/src/google.golang.org/grpc/transport/http2_client.go:754 +0xef
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

goroutine 22938 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8211c1680)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:135 +0x3a
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:136 +0x7c9

goroutine 22992 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc820634c30)
	/go/src/google.golang.org/grpc/transport/http2_client.go:831 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 23408 [select]:
google.golang.org/grpc.(*Conn).Wait(0xc8207e9500, 0x7f0a340779f0, 0xc820528900, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:552 +0x360
google.golang.org/grpc.(*unicastPicker).Pick(0xc820793140, 0x7f0a340779f0, 0xc820528900, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/picker.go:84 +0x51
google.golang.org/grpc.Invoke(0x7f0a340779f0, 0xc820528900, 0x19333c0, 0x1d, 0x17abf80, 0xc820734600, 0x179e700, 0xc8203294c0, 0xc820ddf860, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:154 +0x6d0
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc82042f590, 0x7f0a340779f0, 0xc820528900, 0xc820734600, 0x0, 0x0, 0x0, 0xc820a32890, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:115 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8209f47e0, 0xc820ddf860, 0xc8207ba830, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:183 +0x2b5
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8205fa000, 0xc8204a0f90)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 22962 [IO wait]:
net.runtime_pollWait(0x7f0a34074c18, 0x72, 0xc820623000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820052290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820052290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820052230, 0xc820623000, 0x1000, 0x1000, 0x0, 0x7f0a38a58050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82042e008, 0xc820623000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc.(*Server).handleRawConn(0xc82053b200, 0x7f0a38a6f558, 0xc82032e000)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 22949 [chan receive]:
github.com/cockroachdb/cockroach/server.RegisterAdminHandlerFromEndpoint.func1.1(0x7f0a34074060, 0xc820479600, 0xc82021db80, 0xc820e863c0, 0xf)
	/go/src/github.com/cockroachdb/cockroach/server/admin.pb.gw.go:177 +0x51
created by github.com/cockroachdb/cockroach/server.RegisterAdminHandlerFromEndpoint.func1
	/go/src/github.com/cockroachdb/cockroach/server/admin.pb.gw.go:181 +0x205

goroutine 22988 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc8209066c0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:610 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

goroutine 22948 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc820104a80)
	/go/src/google.golang.org/grpc/clientconn.go:511 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc820104a80)
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:323 +0x509
FAIL	github.com/cockroachdb/cockroach/sql	70.041s
=== RUN   TestEval
--- PASS: TestEval (0.01s)
=== RUN   TestEvalError
--- PASS: TestEvalError (0.00s)
=== RUN   TestEvalComparisonExprCaching
--- PASS: TestEvalComparisonExprCaching (0.00s)
=== RUN   TestSimilarEscape
--- PASS: TestSimilarEscape (0.00s)
=== RUN   TestQualifiedNameString
--- PASS: TestQualifiedNameString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by vivekmenezes** [comment]
I'll look into this later tonight. Seems odd that it should fail with a
change to the storage layer!

**Comment by andreimatei** [comment]
I think the many timeouts we're seeing are #5376

**Comment by vivekmenezes** [comment]
Thanks

**Comment by tschottdorf** [comment]
For this one I don't think so:

There's a worker running: https://circleci.com/gh/cockroachdb/cockroach/14895,
which presumably blocks shutdown. Some tests before are slow but it doesn't seem that they add up to 1m10s (didn't do the math though).

```
goroutine 24085 [select]:
google.golang.org/grpc.(*Conn).Wait(0xc82051ed20, 0x7f55dee13160, 0xc820cb44e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:552 +0x360
google.golang.org/grpc.(*unicastPicker).Pick(0xc820c744a0, 0x7f55dee13160, 0xc820cb44e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/picker.go:84 +0x51
google.golang.org/grpc.Invoke(0x7f55dee13160, 0xc820cb44e0, 0x19324e0, 0x1d, 0x17ab1e0, 0xc82054f080, 0x179d960, 0xc8213eb7a0, 0xc8210f2820, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:154 +0x6d0
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc820026c90, 0x7f55dee13160, 0xc820cb44e0, 0xc82054f080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:115 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc820462a20, 0xc8210f2820, 0xc8204e0ef0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:187 +0x2b5
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:167 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82129c070, 0xc820417b90)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

cc @tamird

**Comment by vivekmenezes** [comment]
https://circleci.com/gh/cockroachdb/cockroach/14914

probably related

**Comment by vivekmenezes** [comment]
https://circleci.com/gh/cockroachdb/cockroach/14918

probably related

**Comment by mrtracy** [comment]
https://circleci.com/gh/cockroachdb/cockroach/15004

Also probably related

**Comment by RaduBerinde** [comment]
It does look like just another instance of tests timing out (#5376)
```
test: --- PASS: TestLeaseManagerPublishVersionChanged (11.72s)
test: --- PASS: TestLogic (23.39s)
test: --- PASS: TestParallel (12.25s)
test: --- PASS: TestPGPreparedExec (2.88s)
test: --- PASS: TestCmdCompleteVsEmptyStatements (3.09s)
test: --- PASS: TestScanBatches (3.62s)
``
