### ISSUE TITLE
circleci: failed tests (14870): TestNonRetriableError

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5410]
The following test appears to have failed:

[#14870](https://circleci.com/gh/cockroachdb/cockroach/14870):

```
W160320 00:31:17.657940 kv/dist_sender.go:659  failed to invoke AdminSplit [/Table/51/0,/Min): storage/replica_command.go:1664: split at key /Table/51 failed: node unavailable; try another peer
I160320 00:31:17.657988 client/db.go:422  failed batch: storage/replica_command.go:1664: split at key /Table/51 failed: node unavailable; try another peer
E160320 00:31:17.658061 storage/queue.go:444  [split] range=6 [/Table/50-/Max): error: storage/split_queue.go:100: unable to split range=6 [/Table/50-/Max) at key "/Table/51/0": storage/replica_command.go:1664: split at key /Table/51 failed: node unavailable; try another peer
I160320 00:31:17.658128 stopper.go:352  draining; tasks left:
1      storage/queue.go:381
panic: test timed out after 1m10s

goroutine 27130 [running]:
panic(0x1481520, 0xc820750a10)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x1bb0eb0, 0x232a0e0, 0x48, 0x48, 0x88b28d3c4389d701)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820033f08, 0x11)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/sql_test.TestMain(0xc820033f08)
	/go/src/github.com/cockroachdb/cockroach/sql/main_test.go:234 +0x26
main.main()
	github.com/cockroachdb/cockroach/sql/_test/_testmain.go:382 +0x114

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x25fdd80)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1003 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 27076 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8204542a0)
	/go/src/google.golang.org/grpc/clientconn.go:511 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8204542a0)
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:323 +0x509

goroutine 27077 [chan receive]:
github.com/cockroachdb/cockroach/server.RegisterAdminHandlerFromEndpoint.func1.1(0x7f3e405a2320, 0xc82020c340, 0xc82071b540, 0xc8204dd970, 0xf)
	/go/src/github.com/cockroachdb/cockroach/server/admin.pb.gw.go:177 +0x51
created by github.com/cockroachdb/cockroach/server.RegisterAdminHandlerFromEndpoint.func1
	/go/src/github.com/cockroachdb/cockroach/server/admin.pb.gw.go:181 +0x205

goroutine 27161 [select]:
google.golang.org/grpc.(*Conn).Wait(0xc8207bddc0, 0x7f3e405a5a98, 0xc8212d8e40, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:552 +0x360
google.golang.org/grpc.(*unicastPicker).Pick(0xc820444320, 0x7f3e405a5a98, 0xc8212d8e40, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/picker.go:84 +0x51
google.golang.org/grpc.Invoke(0x7f3e405a5a98, 0xc8212d8e40, 0x19322c0, 0x1d, 0x17aafc0, 0xc8211e0300, 0x179d740, 0xc8202afe40, 0xc820377d60, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:154 +0x6d0
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc820124590, 0x7f3e405a5a98, 0xc8212d8e40, 0xc8211e0300, 0x0, 0x0, 0x0, 0xc800000000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:115 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc820d9a6c0, 0xc820377d60, 0xc820dbc7f0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:183 +0x2b5
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8212b0000, 0xc8206909f0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 27052 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc82033f0e0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:610 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

goroutine 27160 [sleep]:
time.Sleep(0x3b94cef7)
	/usr/local/go/src/runtime/time.go:59 +0xf9
google.golang.org/grpc.(*Conn).resetTransport(0xc8207bddc0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:461 +0x79f
google.golang.org/grpc.NewConn.func1(0xc8207bddc0)
	/go/src/google.golang.org/grpc/clientconn.go:317 +0x2a
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:323 +0x509

goroutine 27051 [IO wait]:
net.runtime_pollWait(0x7f3e405a3418, 0x72, 0xc820af4c00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820654220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820654220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8206541c0, 0xc820af4c00, 0x400, 0x400, 0x0, 0x7f3e40584050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820026028, 0xc820af4c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc.(*Server).handleRawConn(0xc820e38800, 0x7f3e3cb9d230, 0xc82113a000)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 27054 [IO wait]:
net.runtime_pollWait(0x7f3e405a3298, 0x72, 0xc82043b000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8206541b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8206541b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820654150, 0xc82043b000, 0x1000, 0x1000, 0x0, 0x7f3e40584050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820026000, 0xc82043b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc/transport.(*http2Client).reader(0xc82052aa50)
	/go/src/google.golang.org/grpc/transport/http2_client.go:754 +0xef
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

goroutine 27059 [semacquire]:
sync.runtime_Semacquire(0xc8212b0024)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc8212b0018)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc8212b0000)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:302 +0x1dd
github.com/cockroachdb/cockroach/server.(*Server).Stop(0xc8212b8000)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:359 +0x28
github.com/cockroachdb/cockroach/server.(*TestServer).Stop(0xc820416000)
	/go/src/github.com/cockroachdb/cockroach/server/testserver.go:318 +0x5d
--
testing.tRunner(0xc82069a360, 0x232a788)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 27066 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc820697b60)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:135 +0x3a
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:136 +0x7c9

goroutine 27053 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc82052aa50)
	/go/src/google.golang.org/grpc/transport/http2_client.go:831 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b
FAIL	github.com/cockroachdb/cockroach/sql	70.044s
=== RUN   TestEval
--- PASS: TestEval (0.01s)
=== RUN   TestEvalError
--- PASS: TestEvalError (0.00s)
=== RUN   TestEvalComparisonExprCaching
--- PASS: TestEvalComparisonExprCaching (0.00s)
=== RUN   TestSimilarEscape
--- PASS: TestSimilarEscape (0.00s)
=== RUN   TestQualifiedNameString
--- PASS: TestQualifiedNameString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by vivekmenezes** [comment]
https://circleci.com/gh/cockroachdb/cockroach/14864

**Comment by RaduBerinde** [comment]
```
test: --- PASS: TestParallel (12.38s)
test: --- PASS: TestLogic (22.76s)
```
Dup of #5376
