### ISSUE TITLE
circleci: failed tests (14872): TestValidateTableDesc

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5411]
The following test appears to have failed:

[#14872](https://circleci.com/gh/cockroachdb/cockroach/14872):

```
I160320 00:58:21.780785 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestSplitOnTableBoundaries (0.36s)
=== RUN   TestAllocateIDs
--- PASS: TestAllocateIDs (0.00s)
=== RUN   TestValidateTableDesc
panic: test timed out after 1m10s

goroutine 24708 [running]:
panic(0x1481600, 0xc820b5e040)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x1bb1108, 0x232a2e0, 0x48, 0x48, 0x134b78f791ce8f01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820483ef8, 0x11)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/sql_test.TestMain(0xc820483ef8)
	/go/src/github.com/cockroachdb/cockroach/sql/main_test.go:234 +0x26
main.main()
	github.com/cockroachdb/cockroach/sql/_test/_testmain.go:382 +0x114

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x25fdf80)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1003 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 24703 [semacquire]:
runtime.Stack(0xc821c04000, 0x200000, 0x200000, 0xc821c04001, 0x200000)
	/usr/local/go/src/runtime/mprof.go:586 +0x3a
github.com/cockroachdb/cockroach/util/leaktest.interestingGoroutines(0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:24 +0x9f
github.com/cockroachdb/cockroach/util/leaktest.AfterTest.func1()
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:69 +0x13a
github.com/cockroachdb/cockroach/sql_test.TestValidateTableDesc(0xc820b641b0)
	/go/src/github.com/cockroachdb/cockroach/sql/structured_test.go:368 +0x1bae
testing.tRunner(0xc820b641b0, 0x232a8b0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
FAIL	github.com/cockroachdb/cockroach/sql	70.058s
=== RUN   TestEval
--- PASS: TestEval (0.01s)
=== RUN   TestEvalError
--- PASS: TestEvalError (0.00s)
=== RUN   TestEvalComparisonExprCaching
--- PASS: TestEvalComparisonExprCaching (0.00s)
=== RUN   TestSimilarEscape
--- PASS: TestSimilarEscape (0.00s)
=== RUN   TestQualifiedNameString
--- PASS: TestQualifiedNameString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by RaduBerinde** [comment]
sql test timeout, dup of #5376
