### ISSUE TITLE
sql: panic on hydrating dropped types

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#54343]
**Describe the problem**

CockroachDB hits an NPE when trying to fetch all descriptors after dropping a database with a type and a table referencing it. In this case, the crash was manifested via a `SHOW GRANTS` command on a table.

**To Reproduce**

On Cockroach demo, run:
```
CREATE DATABASE test;
USE test;
CREATE TYPE greeting AS ENUM ('hi');
CREATE TABLE t(a greeting);
USE defaultdb;
DROP DATABASE test CASCADE;
CREATE TYPE another AS ENUM ('hi');
CREATE TABLE s(a another);
SHOW GRANTS ON s;
```

This should make Cockroach crash:
```
root@127.0.0.1:53997/test> show grants on t;
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x5400dbb]

goroutine 10789 [running]:
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.HydrateGivenDescriptors.func1(0x977a8a0, 0xc003703f00, 0x3c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1510 +0x8b
github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.TypeLookupFunc.GetTypeDescriptor(0xc001ea15c0, 0x977a8a0, 0xc003703f00, 0x3c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/type_desc.go:494 +0x87
github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.HydrateTypesInTableDescriptor.func1(0xc000ea2900, 0x0, 0x0)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/type_desc.go:528 +0x123
github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.HydrateTypesInTableDescriptor(0x977a8a0, 0xc003703f00, 0xc002959900, 0x96e7a80, 0xc001ea15c0, 0x0, 0x0)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/type_desc.go:540 +0xd1
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.HydrateGivenDescriptors(0x977a8a0, 0xc003703f00, 0xc002fa4840, 0x2c, 0x2c, 0x0, 0xc002fa4840)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1529 +0x1ab
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetAllDescriptors(0xc001a54230, 0x977a8a0, 0xc003703f00, 0xc00126e630, 0x0, 0xc000437040, 0xb, 0x4069c52, 0x405739c)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1472 +0x124
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternal(0x977a8a0, 0xc003703f00, 0xc001a54420, 0x0, 0x0, 0x0, 0xc003c6fda0, 0xc001638e40, 0x2)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1807 +0x69
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookup(...)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1768
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDesc(0x977a8a0, 0xc003703f00, 0xc001a54420, 0x0, 0x0, 0xc002926e00, 0x60, 0x8370060)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1697 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.populateTablePrivileges(0x977a8a0, 0xc003703f00, 0xc001a54420, 0x0, 0xc001638e40, 0xc002926f80, 0x4067ac0)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1383 +0x81
github.com/cockroachdb/cockroach/pkg/sql.virtualDefEntry.getPlanInfo.func1.1(0x96e7940, 0xc00349a2c0, 0x2, 0x1)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:492 +0x11a
github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func2(0x977a8a0, 0xc003ab4180, 0xc002a4faa0, 0xc002658cc0, 0xc00349a2c0)
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:115 +0x109
created by github.com/cockroachdb/cockroach/pkg/sql.setupGenerator
	/Users/pbardea/Developer/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:104 +0xf7
```

I only briefly looked at what's going on here, but it looks like the issue here is that when we drop a database, we drop the type descriptor immediately, but the table descriptor hangs around referencing the dropped type. When we want to create a collection with all descriptors, we try and hydrate the type which no longer exists on the dropped table descriptor.

**Expected behavior**

**Environment:**
Dev machine. Cockroach version:
```
Build Tag:        v20.2.0-alpha.3-1051-g0c89e7b81a
Build Time:       2020/09/13 20:31:28
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19.5.0)
Go Version:       go1.14.4
C Compiler:       4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.62)
Build Commit ID:  0c89e7b81aa65d6afa35135faf03c37a0082cb8b
Build Type:       development
```

**Comment by pbardea** [comment]
cc @solongordon (?) for triage. Unsure if this falls under features or schema.

**Comment by pbardea** [comment]
I've also pre-emptively added the release blocker tag for now since it crashes a node. Feel free to update if y'all feel otherwise.

**Comment by ajwerner** [comment]
I’ll take this. The fix I’m thinking that I’m going to go with is to not hydrate dropped tables.
