### ISSUE TITLE
circleci: failed tests (14983): TestNonRetriableError

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5451]
The following test appears to have failed:

[#14983](https://circleci.com/gh/cockroachdb/cockroach/14983):

```
E160321 21:39:57.577911 client/txn.go:349  failure aborting transaction: kv/txn_coord_sender.go:344: writing transaction timed out, was aborted,  or ran on multiple coordinators; abort caused by: node unavailable; try another peer
W160321 21:39:57.578035 kv/dist_sender.go:676  failed to invoke AdminSplit [/Table/50/0,/Min): storage/replica_command.go:1664: split at key /Table/50 failed: node unavailable; try another peer
I160321 21:39:57.578082 client/db.go:422  failed batch: storage/replica_command.go:1664: split at key /Table/50 failed: node unavailable; try another peer
E160321 21:39:57.578153 storage/queue.go:444  [split] range=5 [/Table/14-/Max): error: storage/split_queue.go:100: unable to split range=5 [/Table/14-/Max) at key "/Table/50/0": storage/replica_command.go:1664: split at key /Table/50 failed: node unavailable; try another peer
I160321 21:39:58.575893 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:57497: getsockopt: connection refused"; Reconnecting to "127.0.0.1:57497"
panic: test timed out after 1m10s

goroutine 27663 [running]:
panic(0x14836e0, 0xc8203873a0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x1bb5850, 0x232fc80, 0x48, 0x48, 0xcd3ee054b7792401)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820039f08, 0x11)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/sql_test.TestMain(0xc820039f08)
	/go/src/github.com/cockroachdb/cockroach/sql/main_test.go:234 +0x26
main.main()
	github.com/cockroachdb/cockroach/sql/_test/_testmain.go:382 +0x114

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2603cc0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1003 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 26270 [select]:
google.golang.org/grpc.(*Conn).Wait(0xc820c29ea0, 0x7f2e0a7bc368, 0xc820aec8a0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:552 +0x360
google.golang.org/grpc.(*unicastPicker).Pick(0xc82071afe0, 0x7f2e0a7bc368, 0xc820aec8a0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/picker.go:84 +0x51
google.golang.org/grpc.Invoke(0x7f2e0a7bc368, 0xc820aec8a0, 0x19362a0, 0x1d, 0x17ae3e0, 0xc821332580, 0x17a0fa0, 0xc820790c40, 0xc8200d81e0, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:154 +0x6d0
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc820302a08, 0x7f2e0a7bc368, 0xc820aec8a0, 0xc821332580, 0x0, 0x0, 0x0, 0xc800000000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:115 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8204766c0, 0xc8200d81e0, 0xc82107b440, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:187 +0x2b5
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820650000, 0xc820a695f0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 25674 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc821339dd0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:610 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

goroutine 25609 [semacquire]:
sync.runtime_Semacquire(0xc820650024)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc820650018)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc820650000)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:302 +0x1dd
github.com/cockroachdb/cockroach/server.(*Server).Stop(0xc8209ca0d0)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:359 +0x28
github.com/cockroachdb/cockroach/server.(*TestServer).Stop(0xc820b8e030)
	/go/src/github.com/cockroachdb/cockroach/server/testserver.go:318 +0x5d
--
testing.tRunner(0xc820018090, 0x2330328)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 25631 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8212f1c20)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:135 +0x3a
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:136 +0x7c9

goroutine 25642 [chan receive]:
github.com/cockroachdb/cockroach/server.RegisterAdminHandlerFromEndpoint.func1.1(0x7f2e0a779638, 0xc820719200, 0xc821178000, 0xc820e0c0c0, 0xf)
	/go/src/github.com/cockroachdb/cockroach/server/admin.pb.gw.go:177 +0x51
created by github.com/cockroachdb/cockroach/server.RegisterAdminHandlerFromEndpoint.func1
	/go/src/github.com/cockroachdb/cockroach/server/admin.pb.gw.go:181 +0x205

goroutine 25678 [IO wait]:
net.runtime_pollWait(0x7f2e0a6fc298, 0x72, 0xc820490c00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820230ca0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820230ca0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820230c40, 0xc820490c00, 0x400, 0x400, 0x0, 0x7f2e0a7a7050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820302080, 0xc820490c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc/transport.(*http2Client).reader(0xc820e223c0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:754 +0xef
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

goroutine 25617 [IO wait]:
net.runtime_pollWait(0x7f2e0a779a70, 0x72, 0xc8201d8800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820230d10, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820230d10, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820230cb0, 0xc8201d8800, 0x400, 0x400, 0x0, 0x7f2e0a7a7050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820026158, 0xc8201d8800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc.(*Server).handleRawConn(0xc820e9d180, 0x7f2e0a77ade0, 0xc8212cc8f0)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 25677 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc820e223c0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:831 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 26269 [sleep]:
time.Sleep(0x54bb3ebd)
	/usr/local/go/src/runtime/time.go:59 +0xf9
google.golang.org/grpc.(*Conn).resetTransport(0xc820c29ea0, 0xad0300, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:461 +0x79f
google.golang.org/grpc.NewConn.func1(0xc820c29ea0)
	/go/src/google.golang.org/grpc/clientconn.go:317 +0x2a
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:323 +0x509

goroutine 25641 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8206a4000)
	/go/src/google.golang.org/grpc/clientconn.go:511 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8206a4000)
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:323 +0x509
FAIL	github.com/cockroachdb/cockroach/sql	70.054s
=== RUN   TestEval
--- PASS: TestEval (0.01s)
=== RUN   TestEvalError
--- PASS: TestEvalError (0.00s)
=== RUN   TestEvalComparisonExprCaching
--- PASS: TestEvalComparisonExprCaching (0.00s)
=== RUN   TestSimilarEscape
--- PASS: TestSimilarEscape (0.00s)
=== RUN   TestQualifiedNameString
--- PASS: TestQualifiedNameString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by RaduBerinde** [comment]
Dup of #5376
