### ISSUE TITLE
circleci: failed tests (14994): TestSchemaChangeProcess

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5460]
The following test appears to have failed:

[#14994](https://circleci.com/gh/cockroachdb/cockroach/14994):

```
I160322 00:42:11.194927 kv/range_cache.go:228  evict cached descriptor: key=/Meta2/Table/13 desc=range_id:1 start_key:"" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160322 00:42:11.194975 kv/range_cache.go:228  evict cached descriptor: key=/Meta1/Table/13 desc=<nil>
I160322 00:42:11.195033 client/db.go:422  failed batch: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:687: node 1 stopped
W160322 00:42:11.195082 storage/intent_resolver.go:283  [node=1,store=1,range=6] failed to resolve intents: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:687: node 1 stopped
I160322 00:42:12.194402 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:44491: getsockopt: connection refused"; Reconnecting to "127.0.0.1:44491"
panic: test timed out after 1m10s

goroutine 23057 [running]:
panic(0x1480740, 0xc820b7cba0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x1bb21d0, 0x232c8e0, 0x48, 0x48, 0x253db2c0d9cedb01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820032f08, 0x11)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/sql_test.TestMain(0xc820032f08)
	/go/src/github.com/cockroachdb/cockroach/sql/main_test.go:234 +0x26
main.main()
	github.com/cockroachdb/cockroach/sql/_test/_testmain.go:382 +0x114

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x26005e0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1003 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 22531 [chan receive]:
github.com/cockroachdb/cockroach/server.RegisterAdminHandlerFromEndpoint.func1.1(0x7fb5273cb780, 0xc820a42340, 0xc820f56fa0, 0xc8210782a0, 0xf)
	/go/src/github.com/cockroachdb/cockroach/server/admin.pb.gw.go:177 +0x51
created by github.com/cockroachdb/cockroach/server.RegisterAdminHandlerFromEndpoint.func1
	/go/src/github.com/cockroachdb/cockroach/server/admin.pb.gw.go:181 +0x205

goroutine 22446 [semacquire]:
sync.runtime_Semacquire(0xc820a84024)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc820a84018)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc820a84000)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:302 +0x1dd
github.com/cockroachdb/cockroach/server.(*Server).Stop(0xc82005c000)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:359 +0x28
github.com/cockroachdb/cockroach/server.(*TestServer).Stop(0xc820016780)
	/go/src/github.com/cockroachdb/cockroach/server/testserver.go:318 +0x5d
--
testing.tRunner(0xc821216cf0, 0x232ce50)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 22579 [IO wait]:
net.runtime_pollWait(0x7fb5273cbeb8, 0x72, 0xc820d94000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc821543790, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc821543790, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc821543730, 0xc820d94000, 0x1000, 0x1000, 0x0, 0x7fb5273b6050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820026288, 0xc820d94000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc.(*Server).handleRawConn(0xc8209adc80, 0x7fb5273cf1f8, 0xc820305760)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 22570 [IO wait]:
net.runtime_pollWait(0x7fb5273cbbb8, 0x72, 0xc82025e800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8215421b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8215421b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc821542150, 0xc82025e800, 0x400, 0x400, 0x0, 0x7fb5273b6050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820026050, 0xc82025e800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc/transport.(*http2Client).reader(0xc8203de000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:754 +0xef
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

goroutine 22530 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8204d42a0)
	/go/src/google.golang.org/grpc/clientconn.go:511 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8204d42a0)
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:323 +0x509

goroutine 22873 [sleep]:
time.Sleep(0x60bdd6f4)
	/usr/local/go/src/runtime/time.go:59 +0xf9
google.golang.org/grpc.(*Conn).resetTransport(0xc82106da40, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:461 +0x79f
google.golang.org/grpc.NewConn.func1(0xc82106da40)
	/go/src/google.golang.org/grpc/clientconn.go:317 +0x2a
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:323 +0x509

goroutine 22505 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc820474cc0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:135 +0x3a
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:136 +0x7c9

goroutine 22874 [select]:
google.golang.org/grpc.(*Conn).Wait(0xc82106da40, 0x7fb5273ceb38, 0xc82074cfc0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:552 +0x360
google.golang.org/grpc.(*unicastPicker).Pick(0xc8206686e0, 0x7fb5273ceb38, 0xc82074cfc0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/picker.go:84 +0x51
google.golang.org/grpc.Invoke(0x7fb5273ceb38, 0xc82074cfc0, 0x1933140, 0x1d, 0x17ab1c0, 0xc8214ec900, 0x179db60, 0xc820689f60, 0xc82043b540, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:154 +0x6d0
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc8202cb470, 0x7fb5273ceb38, 0xc82074cfc0, 0xc8214ec900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:115 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8204be6c0, 0xc82043b540, 0xc820c9e200, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:187 +0x2b5
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820a84000, 0xc82044c090)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 22569 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8203de000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:831 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 22568 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc8204ae120)
	/go/src/google.golang.org/grpc/transport/http2_server.go:610 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853
FAIL	github.com/cockroachdb/cockroach/sql	70.049s
=== RUN   TestEval
--- PASS: TestEval (0.01s)
=== RUN   TestEvalError
--- PASS: TestEvalError (0.00s)
=== RUN   TestEvalComparisonExprCaching
--- PASS: TestEvalComparisonExprCaching (0.00s)
=== RUN   TestSimilarEscape
--- PASS: TestSimilarEscape (0.00s)
=== RUN   TestQualifiedNameString
--- PASS: TestQualifiedNameString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by RaduBerinde** [comment]
Dup of #5376
