### ISSUE TITLE
CockroachDB cluster raises "result is ambiguous" to application in some cases but not others

### ISSUE THREAD

**Issue by neildunbar** [cockroachdb/cockroach#54867]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

We had a recent network flapping issue which resulted in some nodes in the cluster being held as suspect, before eventually correcting themselves.

This happened a few days ago too, but the python code handled the exception caused by "40003/result is ambiguous" and it retried the work at a later point. Good - that's what is supposed to happen.
However, today, we had the same network issue, but while the node logs reported "result is ambiguous" internally, the python code never got to see the error raised, so was unable to retry to logic.

**To Reproduce**

It seems very hard to reproduce as it seems highly dependent on transient conditions. We've tested with this snippet but without consistent results

```python
def update(session):
    data = session.query(Items).first()
    data.count = 10
run_transaction(update)
```

When we re-read the database the count is not the expected value 10, although the write commit seemed to work without issue.

**Expected behavior**

Result is ambiguous errors to be reported to application in all circumstances

**Additional data / screenshots**

```
Sep 28 14:14:13 db1-phx1 cockroach[805]: E200928 14:14:13.694143 124237568 kv/kvclient/kvcoord/txn_interceptor_committer.go:449  making txn commit explicit failed for "unnamed" meta={id=de89ceea key=/Table/11/1/30/1/2020-09-28T14:19:11.191439Z/1/0 pri=100.00000000 epo=0 ts=1601302439.289837120,0 min=1601302439.289837120,0 seq=2} lock=true stat=STAGING rts=1601302439.289837120,0 wto=false max=1601302439.609538711,0 ifw=1: result is ambiguous (error=unable to dial n2: breaker open [exhausted])
```

This did not cause an application exception, but a few days ago, we got the following in our app log

```
Sep 25 13:57:57 db1-phx1 cockroach[805]: E200925 13:57:57.790976 110745747 kv/kvserver/queue.go:1090  [n1,raftlog,s1,r3/11:/System/{NodeLive…-tsd}] operation "raftlog queue process replica 3" timed out after 1m0s: result is ambiguous (context deadline exceeded)
```

```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1246, in _execute_context
        cursor, statement, parameters, context
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 581, in do_execute
        cursor.execute(statement, parameters)
    psycopg2.InternalError: result is ambiguous (error=unable to dial n2: breaker open [propagate])
    The above exception was the direct cause of the following exception:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.1-py3.6.egg/flask/app.py", line 1949, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.1-py3.6.egg/flask/app.py", line 1935, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/usr/local/lib/python3.6/dist-packages/app_utils-1.1.1-py3.6.egg/app_utils/flask_utils.py", line 216, in _wrapped
        return view_func(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_apispec/annotations.py", line 118, in wrapped
        return wrapper(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_apispec/wrapper.py", line 32, in __call__
        response = self.call_view(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_apispec/wrapper.py", line 54, in call_view
        return self.func(*args, **kwargs)
      File "/deploy/app_queue_api/app_queue_api/views/paused_work_resume/queue_pending_work.py", line 58, in queue_pending_work
        total_work_count, work_pile = run_transaction(get_work_pile)
      File "/deploy/app_queue_api/app_queue_api/views/paused_work_resume/queue_pending_work.py", line 44, in get_work_pile
        _total_work_count = _work_pile.count()
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3630, in count
        return self.from_self(col).scalar()
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3355, in scalar
        ret = self.one()
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3325, in one
        ret = self.one_or_none()
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3294, in one_or_none
        ret = list(self)
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3367, in __iter__
        return self._execute_and_instances(context)
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
        result = conn.execute(querycontext.statement, self._params)
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 982, in execute
        return meth(self, multiparams, params)
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
        distilled_params,
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1250, in _execute_context
        e, statement, parameters, cursor, context
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
        util.raise_from_cause(sqlalchemy_exception, exc_info)
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 398, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 152, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1246, in _execute_context
        cursor, statement, parameters, context
      File "/usr/local/lib/python3.6/dist-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 581, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.InternalError: (psycopg2.InternalError) result is ambiguous (error=unable to dial n2: breaker open [propagate])
```

**Environment:**

 - CockroachDB version 20.1.4
 - Server OS: [e.g. Ubuntu 18.04 ]
 - Client app [e.g. `python 3.6 with SQLAlchemy 1.3.12`]

Jira issue: CRDB-3708

**Comment by nvanbenschoten** [comment]
Hi @neildunbar, thanks for the detailed writeup! @rafiss will have to weigh in on the SQLAlchemy portion of your question, but I can give you a little bit of background on the ambiguous result error.

When a machine fails or network connectivity breaks in a distributed system, it can make it difficult to determine whether ongoing operations completed or failed. This is what a `result is ambiguous` error is indicating. See https://www.cockroachlabs.com/docs/stable/common-errors.html#result-is-ambiguous for more details. What this means is that the python code can't blindly retry the operation, because it doesn't want to perform the same modification twice. For instance, imagine if the transaction incremented a value – if it was performed twice, it would increment the value twice. For this reason, it's only safe to retry on this form of error if your transactions are idempotent.

**Comment by rafiss** [comment]
@neildunbar In general, you should not expect a 1-to-1 relation between error messages in the CockroachDB log, and errors reported to your application.

Could you provide a few more details:
- In the case where the application did not receive the `result is ambiguous` error, was there a different error reported?
- Could you provide a code sample that we can run? I understand the small example you posted, but I wonder what other details were needed? Also, can you provide the schema of the relevant table?

**Comment by rimadeodhar** [comment]
Closing this as stale. @neildunbar please reopen if you are continuing to see this issue.
