### ISSUE TITLE
compatibility: keystone db_sync migration

### ISSUE THREAD

**Issue by robinbraemer** [cockroachdb/cockroach#55662]
**Describe the problem**

Since CRDB is mostly postgresl protocol compatible I tried to use CRDB as OpenStack database backend for Keystone.

I set up a CRDB v20.1.7 cluster using the newer Helm Chart, created a new database `keystone` and tried to initialize it with the `keystone-manage db_sync` tool which migrates/inits all tables required by OpenStack Keystone.

Dockerfile for the sync pod:
```dockerfile
FROM docker.io/openstackhelm/keystone:ussuri-ubuntu_bionic
# Install cockroachdb adapter
RUN pip install sqlalchemy-cockroachdb psycopg2-binary
```
(I also made sure I configured the correct`database connection` string in `keystone.conf` to use the `cockroachdb` adapter for sqlalchemy).

I think the migration process involves assumptions on table `constraint` names where CRDB probably names them different than Postgres does. I'm not sure if this is a fault by CRDB or the `keystone-manage db_sync` tool having to strict assumptions on how Postges names constraints by default.

Logs/errors:
```
kubectl logs -f keystone-db-sync-4bffx
+ keystone-manage --config-file=/etc/keystone/keystone.conf db_sync
2020-10-14 16:16:14.573 7 CRITICAL keystone [-] Unhandled error: oslo_db.exception.DBMigrationError: (psycopg2.errors.UndefinedObject) constraint "assignment_pkey" does not exist

[SQL: ALTER TABLE assignment DROP CONSTRAINT assignment_pkey]
(Background on this error at: http://sqlalche.me/e/f405)
2020-10-14 16:16:14.573 7 ERROR keystone Traceback (most recent call last):
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
2020-10-14 16:16:14.573 7 ERROR keystone     cursor, statement, parameters, context
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
2020-10-14 16:16:14.573 7 ERROR keystone     cursor.execute(statement, parameters)
2020-10-14 16:16:14.573 7 ERROR keystone psycopg2.errors.UndefinedObject: constraint "assignment_pkey" does not exist
2020-10-14 16:16:14.573 7 ERROR keystone 
2020-10-14 16:16:14.573 7 ERROR keystone 
2020-10-14 16:16:14.573 7 ERROR keystone The above exception was the direct cause of the following exception:
2020-10-14 16:16:14.573 7 ERROR keystone 
2020-10-14 16:16:14.573 7 ERROR keystone Traceback (most recent call last):
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/oslo_db/sqlalchemy/migration.py", line 79, in db_sync
2020-10-14 16:16:14.573 7 ERROR keystone     migration = versioning_api.upgrade(engine, repository, version)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/versioning/api.py", line 186, in upgrade
2020-10-14 16:16:14.573 7 ERROR keystone     return _migrate(url, repository, version, upgrade=True, err=err, **opts)
2020-10-14 16:16:14.573 7 ERROR keystone   File "<decorator-gen-15>", line 2, in _migrate
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
2020-10-14 16:16:14.573 7 ERROR keystone     return f(*a, **kw)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/versioning/api.py", line 366, in _migrate
2020-10-14 16:16:14.573 7 ERROR keystone     schema.runchange(ver, change, changeset.step)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/versioning/schema.py", line 93, in runchange
2020-10-14 16:16:14.573 7 ERROR keystone     change.run(self.engine, step)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/versioning/script/py.py", line 154, in run
2020-10-14 16:16:14.573 7 ERROR keystone     script_func(engine)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/keystone/common/sql/migrate_repo/versions/073_insert_assignment_inherited_pk.py", line 111, in upgrade
2020-10-14 16:16:14.573 7 ERROR keystone     migrate.PrimaryKeyConstraint(table=assignment_table).drop()
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/changeset/constraint.py", line 59, in drop
2020-10-14 16:16:14.573 7 ERROR keystone     self.__do_imports('constraintdropper', *a, **kw)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/changeset/constraint.py", line 32, in __do_imports
2020-10-14 16:16:14.573 7 ERROR keystone     run_single_visitor(engine, visitorcallable, self, *a, **kw)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/changeset/databases/visitor.py", line 85, in run_single_visitor
2020-10-14 16:16:14.573 7 ERROR keystone     fn(element, **kwargs)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/changeset/ansisql.py", line 282, in visit_migrate_primary_key_constraint
2020-10-14 16:16:14.573 7 ERROR keystone     self._visit_constraint(*p, **k)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/changeset/ansisql.py", line 303, in _visit_constraint
2020-10-14 16:16:14.573 7 ERROR keystone     self.execute()
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/migrate/changeset/ansisql.py", line 44, in execute
2020-10-14 16:16:14.573 7 ERROR keystone     return self.connection.execute(self.buffer.getvalue())
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 976, in execute
2020-10-14 16:16:14.573 7 ERROR keystone     return self._execute_text(object_, multiparams, params)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1151, in _execute_text
2020-10-14 16:16:14.573 7 ERROR keystone     parameters,
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
2020-10-14 16:16:14.573 7 ERROR keystone     e, statement, parameters, cursor, context
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1479, in _handle_dbapi_exception
2020-10-14 16:16:14.573 7 ERROR keystone     util.raise_(newraise, with_traceback=exc_info[2], from_=e)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
2020-10-14 16:16:14.573 7 ERROR keystone     raise exception
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
2020-10-14 16:16:14.573 7 ERROR keystone     cursor, statement, parameters, context
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
2020-10-14 16:16:14.573 7 ERROR keystone     cursor.execute(statement, parameters)
2020-10-14 16:16:14.573 7 ERROR keystone oslo_db.exception.DBError: (psycopg2.errors.UndefinedObject) constraint "assignment_pkey" does not exist
2020-10-14 16:16:14.573 7 ERROR keystone 
2020-10-14 16:16:14.573 7 ERROR keystone [SQL: ALTER TABLE assignment DROP CONSTRAINT assignment_pkey]
2020-10-14 16:16:14.573 7 ERROR keystone (Background on this error at: http://sqlalche.me/e/f405)
2020-10-14 16:16:14.573 7 ERROR keystone 
2020-10-14 16:16:14.573 7 ERROR keystone During handling of the above exception, another exception occurred:
2020-10-14 16:16:14.573 7 ERROR keystone 
2020-10-14 16:16:14.573 7 ERROR keystone Traceback (most recent call last):
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/bin/keystone-manage", line 8, in <module>
2020-10-14 16:16:14.573 7 ERROR keystone     sys.exit(main())
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/keystone/cmd/manage.py", line 41, in main
2020-10-14 16:16:14.573 7 ERROR keystone     cli.main(argv=sys.argv, developer_config_file=developer_config)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/keystone/cmd/cli.py", line 1379, in main
2020-10-14 16:16:14.573 7 ERROR keystone     CONF.command.cmd_class.main()
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/keystone/cmd/cli.py", line 348, in main
2020-10-14 16:16:14.573 7 ERROR keystone     CONF.command.version)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/keystone/common/sql/upgrades.py", line 226, in offline_sync_database_to_version
2020-10-14 16:16:14.573 7 ERROR keystone     expand_schema()
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/keystone/common/sql/upgrades.py", line 300, in expand_schema
2020-10-14 16:16:14.573 7 ERROR keystone     _sync_common_repo(version=None)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/keystone/common/sql/upgrades.py", line 146, in _sync_common_repo
2020-10-14 16:16:14.573 7 ERROR keystone     init_version=init_version, sanity_check=False)
2020-10-14 16:16:14.573 7 ERROR keystone   File "/var/lib/openstack/lib/python3.6/site-packages/oslo_db/sqlalchemy/migration.py", line 81, in db_sync
2020-10-14 16:16:14.573 7 ERROR keystone     raise exception.DBMigrationError(ex)
2020-10-14 16:16:14.573 7 ERROR keystone oslo_db.exception.DBMigrationError: (psycopg2.errors.UndefinedObject) constraint "assignment_pkey" does not exist
2020-10-14 16:16:14.573 7 ERROR keystone 
2020-10-14 16:16:14.573 7 ERROR keystone [SQL: ALTER TABLE assignment DROP CONSTRAINT assignment_pkey]
2020-10-14 16:16:14.573 7 ERROR keystone (Background on this error at: http://sqlalche.me/e/f405)
2020-10-14 16:16:14.573 7 ERROR keystone 
```

Jira issue: CRDB-3649

**Comment by rafiss** [comment]
Thanks for the report! I haven't looked into what the Keystone code is doing yet, but based on the error message, I wonder if it is hitting this problem #52833
