### ISSUE TITLE
fault under mvccResolveWriteIntent

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#5585]
I hit this every time just by running
`make bench PKG=./sql TESTS=BenchmarkScan10000FilterLimit50.*Cockroach`

```
W160325 18:09:27.454420 storage/intent_resolver.go:273  [node=1,store=1,range=1] failed to push during intent resolution: failed to push "storage/replica_command.go:1685 (*Replica).AdminSplit" id=4ba627d1 key=/Local/Range/"\xba"/RangeDescriptor rw=true pri=0.01482903 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458943767.141033624,0 orig=1458943767.141033624,0 max=1458943767.141033624,0 wto=false
I160325 18:09:27.776402 storage/replica_command.go:1370  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405262h9m28.77604421s
unexpected fault address 0x2b7593bd933a
fatal error: fault
[signal 0xb code=0x1 addr=0x2b7593bd933a pc=0x627ddc]

goroutine 72 [running]:
runtime.throw(0x18400b0, 0x5)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8202a0a28 sp=0xc8202a0a10
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc8202a0a78 sp=0xc8202a0a28
runtime.cmpbody()
	/usr/local/go/src/runtime/asm_amd64.s:1548 +0x1fc fp=0xc8202a0a80 sp=0xc8202a0a78
github.com/cockroachdb/cockroach/roachpb.Key.Compare(0xc820a18dd8, 0x7, 0x8, 0x2b7591287148, 0xc8202a0b10, 0x2b7591287148)
	/go2/src/github.com/cockroachdb/cockroach/roachpb/data.go:182 +0x96 fp=0xc8202a0ad8 sp=0xc8202a0a80
github.com/cockroachdb/cockroach/storage/engine.MVCCKey.Equal(0xc820a18dd8, 0x7, 0x8, 0x0, 0x0, 0x2b7593bd933a, 0x7, 0x7, 0x0, 0x0, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:87 +0xa2 fp=0xc8202a0b30 sp=0xc8202a0ad8
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBIterator).Seek(0xc820d50e10, 0xc820a18dd8, 0x7, 0x8, 0x0, 0x0)
	/go2/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:631 +0x22e fp=0xc8202a0d40 sp=0xc8202a0b30
github.com/cockroachdb/cockroach/storage/engine.mvccGetMetadata(0x2b7591286f30, 0xc820d50e10, 0xc820a18dd8, 0x7, 0x8, 0x0, 0x0, 0xc82056e2a0, 0xffffffffffffffbf, 0x0, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:636 +0x8f fp=0xc8202a0e78 sp=0xc8202a0d40
github.com/cockroachdb/cockroach/storage/engine.mvccResolveWriteIntent(0x2b75912875f0, 0xc820c32030, 0x2b7591286f30, 0xc820d50e10, 0xc8202a3028, 0xc820a18dd8, 0x7, 0x8, 0x0, 0x0, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:1499 +0x21a fp=0xc8202a1450 sp=0xc8202a0e78
github.com/cockroachdb/cockroach/storage/engine.MVCCResolveWriteIntentUsingIter(0x2b75912875f0, 0xc820c32030, 0xc82056e2a0, 0x2b7591286f30, 0xc820d50e10, 0xc8202a3028, 0xc820a18dd8, 0x7, 0x8, 0x0, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:1481 +0x9b fp=0xc8202a1510 sp=0xc8202a1450
github.com/cockroachdb/cockroach/storage.(*Replica).EndTransaction.func1(0xc8202a1b30, 0xc8202a1b08, 0xc8202a1900, 0xc8202a1a68, 0xc8202a3028, 0xc8202a18f8, 0x2b75912875f0, 0xc820c32030, 0xc82056e2a0, 0x2b7591286f30, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/replica_command.go:501 +0x2c7 fp=0xc8202a1798 sp=0xc8202a1510
github.com/cockroachdb/cockroach/storage.(*Replica).EndTransaction(0xc820822380, 0x2b75912875f0, 0xc820c32030, 0xc8202a3028, 0x143f35a0721acaa4, 0x0, 0x100000001, 0x1, 0x6, 0x0, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/replica_command.go:484 +0x15f5 fp=0xc8202a1bf8 sp=0xc8202a1798
github.com/cockroachdb/cockroach/storage.(*Replica).executeCmd(0xc820822380, 0x2b7591287a38, 0xc820c332f0, 0xc8209ab490, 0x8, 0x2711, 0x2b75912875f0, 0xc820c32030, 0xc8202a3028, 0x143f35a0721acaa4, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/replica_command.go:126 +0xc17 fp=0xc8202a2440 sp=0xc8202a1bf8
github.com/cockroachdb/cockroach/storage.(*Replica).executeBatch(0xc820822380, 0x2b7591287a38, 0xc820c332f0, 0xc8209ab490, 0x8, 0x2b75912875f0, 0xc820c32030, 0xc8202a3028, 0x143f35a0721acaa4, 0x0, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/replica.go:1676 +0x237 fp=0xc8202a2b18 sp=0xc8202a2440
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommandInBatch(0xc820822380, 0x2b7591287a38, 0xc820c332f0, 0xc8209ab490, 0x8, 0x100000001, 0x1, 0x143f35a0721acaa4, 0x0, 0x100000001, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/replica.go:1562 +0x497 fp=0xc8202a2f30 sp=0xc8202a2b18
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommand(0xc820822380, 0xc8209ab490, 0x8, 0x2b7591287a38, 0xc820c332f0, 0xd, 0x100000001, 0x1, 0x143f35a0721acaa4, 0x0, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/replica.go:1458 +0x4a7 fp=0xc8202a3220 sp=0xc8202a2f30
github.com/cockroachdb/cockroach/storage.(*Replica).processRaftCommand(0xc820822380, 0xc8209ab490, 0x8, 0xd, 0x6, 0x100000001, 0x1, 0x143f35a0721acaa4, 0x0, 0x100000001, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/replica.go:1423 +0x265 fp=0xc8202a3380 sp=0xc8202a3220
github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady(0xc820822380, 0x0, 0x0)
	/go2/src/github.com/cockroachdb/cockroach/storage/replica.go:1287 +0xa49 fp=0xc8202a3c48 sp=0xc8202a3380
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/go2/src/github.com/cockroachdb/cockroach/storage/store.go:1859 +0x35a fp=0xc8202a3f60 sp=0xc8202a3c48
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201c2000, 0xc82049ea60)
	/go2/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52 fp=0xc8202a3f80 sp=0xc8202a3f60
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8202a3f88 sp=0xc8202a3f80
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go2/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

**Comment by RaduBerinde** [comment]
It's very strange. I hit this every time, even if I sync to older commits where it definitely worked before. I tried it in two separate GOPATHs, I also tried a `make clean` and no difference. I wonder if we have a dependency that we are not controlling with glock which was recently updated (?!) Can't think of anything else. Maybe there is something wrong with my machine, I'll reboot and try again.

**Comment by RaduBerinde** [comment]
It looks like `rocksDBIterator.unsafeKey()` (inside `Seek()`) returns an invalid address.

```
k.key=0xc8209047b8 k.timestamp=0.000000000,0 l.key=0x7fee4c0fa076 l.timestamp=0.000000000,0
k.key=0xc8209047c0 k.timestamp=0.000000000,0 l.key=0x7fee4c0fa0db l.timestamp=0.000000000,0
k.key=0xc8209047c8 k.timestamp=0.000000000,0 l.key=0x7fee4c0fa140 l.timestamp=0.000000000,0
k.key=0xc8209047e0 k.timestamp=0.000000000,0 l.key=0x7fee4c0fa1a5 l.timestamp=0.000000000,0
k.key=0xc8209047e8 k.timestamp=0.000000000,0 l.key=0x7fee4c0fa20a l.timestamp=0.000000000,0
k.key=0xc8209047f0 k.timestamp=0.000000000,0 l.key=0x7fee4c0fa26f l.timestamp=0.000000000,0
k.key=0xc8209047f8 k.timestamp=0.000000000,0 l.key=0x7fee4c0fa2d4 l.timestamp=0.000000000,0
k.key=0xc820904800 k.timestamp=0.000000000,0 l.key=0x7fee4c0fa339 l.timestamp=0.000000000,0
unexpected fault address 0x7fee4c0fa339
fatal error: fault
```

```
 635 func mvccGetMetadata(iter Iterator, metaKey MVCCKey,
 636     meta *MVCCMetadata) (ok bool, keyBytes, valBytes int64, err error) {
 637     iter.Seek(metaKey) <---

623 func (r *rocksDBIterator) Seek(key MVCCKey) {
624     r.checkEngineOpen()
625     if len(key.Key) == 0 {
..
629     } else {
630         // We can avoid seeking if we're already at the key we seek.
631         if r.valid && key.Equal(r.unsafeKey()) {  <--

  86 func (k MVCCKey) Equal(l MVCCKey) bool {
  87     fmt.Printf("k.key=%p k.timestamp=%+v l.key=%p l.timestamp=%+v\n", k.Key, k.Timestamp, l.Key, l.Timestamp)
  88     return k.Key.Compare(l.Key) == 0 && k.Timestamp == l.Timestamp   <---
  89 }       
```

**Comment by RaduBerinde** [comment]
Ok, I think I figured it out. Looks like `make bench` doesn't actually rebuild everything it needs. If I run `make build` before, it works.

**Comment by RaduBerinde** [comment]
A few folks confirmed that the benchmark works for them. Maybe it's the gcc on my system (Debian 8). `gcc --version` reports `gcc (Debian 4.9.2-10) 4.9.2`

**Comment by knz** [comment]
Same issue here with Ubuntu 15 -- same stack trace, same error.
Running Ubuntu 15 with `gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010`.

**Comment by RaduBerinde** [comment]
Thanks @knz! Glad to know it's not just me. I tried compiling c-rocksdb with clang 3.5 and I hit the same.

**Comment by bdarnell** [comment]
If you change `unsafeKey` to `Key` on that line, does the failure remain?

**Comment by RaduBerinde** [comment]
Similar crash with `Key()`

```
unexpected fault address 0x7f1279564339
fatal error: fault
[signal 0xb code=0x1 addr=0x7f1279564339 pc=0x63e64c]

goroutine 61 [running]:
runtime.throw(0x182be30, 0x5)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8206b0990 sp=0xc8206b0978
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc8206b09e0 sp=0xc8206b0990
runtime.memmove(0xc820e29b10, 0x7f1279564339, 0x7)
	/usr/local/go/src/runtime/memmove_amd64.s:136 +0x36c fp=0xc8206b09e8 sp=0xc8206b09e0
runtime.gobytes(0x7f1279564339, 0x7, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:332 +0xd3 fp=0xc8206b0a38 sp=0xc8206b09e8
github.com/cockroachdb/cockroach/storage/engine._Cfunc_GoBytes(0x7f1279564339, 0x7f1200000007, 0x0, 0x0, 0x0)
	??:0 +0x3c fp=0xc8206b0a68 sp=0xc8206b0a38
github.com/cockroachdb/cockroach/storage/engine.cSliceToGoBytes(0x7f1279564339, 0xc800000007, 0x0, 0x0, 0x0)
	/go2/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:796 +0x90 fp=0xc8206b0ab0 sp=0xc8206b0a68
github.com/cockroachdb/cockroach/storage/engine.cToGoKey(0x7f1279564339, 0xc800000007, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go2/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:756 +0x47 fp=0xc8206b0ae0 sp=0xc8206b0ab0
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBIterator).Key(0xc821a9d0e0, 0x0, 0x0, 0x0, 0x0, 0xc800000000)
```

**Comment by petermattis** [comment]
You'll be happy to know I can reproduce this on a linux box (doesn't happen on OS X). I'll take a closer look tonight or tomorrow.

**Comment by petermattis** [comment]
The crash goes away if we switch from using the `MVCCResolveWriteIntent{,Range}WithIter()` routines to the (less efficient) `MVCCResolveWriteIntent{,Range}()` routines.
