### ISSUE TITLE
build: fatal error during node-run.sh "no such Type or Enum"

### ISSUE THREAD

**Issue by gglawits** [cockroachdb/cockroach#56029]
Describe the problem

Please describe the issue you observed, and any steps we can take to reproduce it:

To Reproduce

I typed "make" on Ubuntu 20.04, after checking out  20.2.0-rc.3

If possible, provide steps to reproduce the behavior:

make

I got:
.... lots of lines ...

echo '// GENERATED FILE DO NOT EDIT' > pkg/ui/ccl/src/js/protos.js
build/node-run.sh pkg/ui/node_modules/.bin/pbjs -t static-module -w es6 --strict-long --keep-case --path pkg --path ./vendor/github.com --path ./vendor/github.com/gogo/protobuf --path ./vendor/github.com/cockroachdb/errors --path ./vendor/go.etcd.io --path ./vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis ./pkg/server/serverpb/admin.proto ./pkg/server/serverpb/status.proto ./pkg/server/serverpb/authentication.proto ./pkg/ts/tspb/timeseries.proto ./pkg/ccl/storageccl/engineccl/enginepbccl/stats.proto >> pkg/ui/ccl/src/js/protos.js
/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/cli/pbjs.js:235
            throw err;
            ^

Error: no such Type or Enum 'raftpb.HardState' in Type .cockroach.server.serverpb.RaftState
    at Type.lookupTypeOrEnum (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:410:15)
    at Field.resolve (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/field.js:265:94)
    at Type.set (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/type.js:177:38)
    at Type.get (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/type.js:155:45)
    at Field.resolve (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/field.js:314:21)
    at Type.resolveAll (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
make: *** [Makefile:1363: pkg/ui/ccl/src/js/protos.js] Error 1
make: *** Deleting file 'pkg/ui/ccl/src/js/protos.js'

Expected behavior: make works, leaving a binary behind

Environment:

CockroachDB version   20.2.0 rc3
Server OS: [e.g. Linux/Distrib] Ubuntu 20.04
Client app [e.g. cockroach sql, JDBC, ...]  none - trying to compile from source

node -v 
prints
v15.0.1 
(I manually installed this version, because the build process didn't like the version which came with Ubuntu 20.04)

**Comment by ajwerner** [comment]
When you say "tried to compile" can you be more specific about the exact commands you ran and their outputs? Also please attach the git sha and your operating system.

**Comment by gglawits** [comment]
I updated the bug. OS is Ubuntu 20.04 as stated in the original bug report. 
The command was "make"
The output was posted in the original bug report. 
I downloaded the file v20.2.0-rc.3.zip and thus don't have a git sha handy, but I can probably generate that by cloning instead of downloading.

**Comment by ajwerner** [comment]
Hmm, I've never tried building from the source archive. Out of curiosity I pulled the source archive and ran `make build` as instructed in https://www.cockroachlabs.com/docs/dev/install-cockroachdb-linux.html#build-from-source. It worked for me on ubuntu 20.04. It might be that you need node v12.

**Comment by ajwerner** [comment]
You may need to re-extract the archive and just run `make build` rather than `make`.

**Comment by gglawits** [comment]
make build
does the exactly same thing.

$ make build
Running make with -j1
GOPATH set to /home/greg/go
Warning: 'ccache' not found, consider installing it for faster builds
fatal: not a git repository (or any of the parent directories): .git
# Add comment recognized by reviewable.
echo '// GENERATED FILE DO NOT EDIT' > pkg/ui/ccl/src/js/protos.js
build/node-run.sh pkg/ui/node_modules/.bin/pbjs -t static-module -w es6 --strict-long --keep-case --path pkg --path ./vendor/github.com --path ./vendor/github.com/gogo/protobuf --path ./vendor/github.com/cockroachdb/errors --path ./vendor/go.etcd.io --path ./vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis ./pkg/server/serverpb/admin.proto ./pkg/server/serverpb/status.proto ./pkg/server/serverpb/authentication.proto ./pkg/ts/tspb/timeseries.proto ./pkg/ccl/storageccl/engineccl/enginepbccl/stats.proto >> pkg/ui/ccl/src/js/protos.js
/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/cli/pbjs.js:235
            throw err;
            ^

Error: no such Type or Enum 'raftpb.HardState' in Type .cockroach.server.serverpb.RaftState
    at Type.lookupTypeOrEnum (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:410:15)
    at Field.resolve (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/field.js:265:94)
    at Type.set (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/type.js:177:38)
    at Type.get (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/type.js:155:45)
    at Field.resolve (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/field.js:314:21)
    at Type.resolveAll (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (/home/greg/go/src/skyflow.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
make: *** [Makefile:1363: pkg/ui/ccl/src/js/protos.js] Error 1
make: *** Deleting file 'pkg/ui/ccl/src/js/protos.js'

**Comment by ajwerner** [comment]
1) Did you adjust your node version to v12?
2) Did you re-extract the archive before trying again?

**Comment by gglawits** [comment]
Working on it. Merely downgrading node to 12.19 didn't help.

**Comment by gglawits** [comment]
I nuked the source tree, copied it in from a .zip file afresh, and it still shows the very same error with node version 12.19:

...
echo '// GENERATED FILE DO NOT EDIT' > pkg/ui/ccl/src/js/protos.js
build/node-run.sh pkg/ui/node_modules/.bin/pbjs -t static-module -w es6 --strict-long --keep-case --path pkg --path ./vendor/github.com --path ./vendor/github.com/gogo/protobuf --path ./vendor/github.com/cockroachdb/errors --path ./vendor/go.etcd.io --path ./vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis ./pkg/server/serverpb/admin.proto ./pkg/server/serverpb/status.proto ./pkg/server/serverpb/authentication.proto ./pkg/ts/tspb/timeseries.proto ./pkg/ccl/storageccl/engineccl/enginepbccl/stats.proto >> pkg/ui/ccl/src/js/protos.js
/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/cli/pbjs.js:235
            throw err;
            ^

Error: no such Type or Enum 'raftpb.HardState' in Type .cockroach.server.serverpb.RaftState
    at Type.lookupTypeOrEnum (/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:410:15)
    at Field.resolve (/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/field.js:265:94)
    at Type.set (/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/type.js:177:38)
    at Type.get (/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/type.js:155:45)
    at Field.resolve (/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/field.js:314:21)
    at Type.resolveAll (/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (/home/greg/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/namespace.js:307:25)
make: *** [Makefile:1363: pkg/ui/ccl/src/js/protos.js] Error 1
make: *** Deleting file 'pkg/ui/ccl/src/js/protos.js'

**Comment by ajwerner** [comment]
What go version do you have installed?

**Comment by gglawits** [comment]
go version
go1.13.8
default for Ubuntu 20.04

**Comment by ajwerner** [comment]
Hmm, I legitimately have no idea why this is not working for you. It worked for me when I tried it. Would you be willing to do the following:

* create a completely new directory with the extracted files
* cd into that directory
* run `env > out.env.txt`
* run `make build 2>&1 | tee out.build.txt`

Then upload `out.env.txt` and `out.build.txt` here for a more detailed review?

**Comment by gglawits** [comment]
Will do. Stay tuned.

**Comment by gglawits** [comment]
[out.env.txt](https://github.com/cockroachdb/cockroach/files/5453244/out.env.txt)
[out.build.txt](https://github.com/cockroachdb/cockroach/files/5453245/out.build.txt)

**Comment by gglawits** [comment]
By the way, I just reproduced the issue on a brand new Ubuntu 20.10 VM.
I was forced to install yarn manually, but kept the stock node (12.18.2) and golang (1.14.7)
The very same thing happened.

**Comment by gglawits** [comment]
The home directory for the build is 
$GOPATH/src/github.com/cockroachdb/cockroach
in case it matters (shouldn't matter)

**Comment by rickystewart** [comment]
@gglawits Sorry this issue got lost -- this just got added to the dev-inf tracker, so I'm just seeing this for the first time.

It's been a while, but let me know if you're still looking for support with this and I can try to see if there's anything else we can do.

**Comment by gglawits** [comment]
No, I can compile it now with a VERY PRECISE SET of tool versions.
gcc / g++ has to be an EXACT version, no other one seems to work.
node, too.

Regards,

Greg

Am Mi., 3. März 2021 um 15:19 Uhr schrieb rickystewart <
notifications@github.com>:

**Comment by rickystewart** [comment]
Hmm, okay, I'm glad you got it working for you then. I'll close this. Please feel free to open a new issue if you become unable to build again.
