### ISSUE TITLE
cli - cockroach demo hidden flag --global no longer works

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#56264]
When cockroach demo is invoked with the --global hidden flag, it's supposed to simulate inter-node latencies as though they were situated around the globe.  Unfortunately, it doesn't seem to work anymore.

**To Reproduce**

```    
> cockroach demo --nodes 9 --global                                                                                                                                                             
panic: didn't get expected magic bytes header

goroutine 856 [running]:
github.com/cockroachdb/cockroach/pkg/rpc.delayingConn.Read(0x952ab20, 0xc00401a720, 0x0, 0x0, 0x0, 0x0, 0xc003aabbf0, 0xc003f06b40, 0x205, 0x205, ...)
	/Users/storm/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:879 +0x3a2
crypto/tls.(*atLeastReader).Read(0xc003b1aa40, 0xc003f06b40, 0x205, 0x205, 0xc003f06b40, 0x0, 0xc003c935f0)
	/usr/local/opt/go@1.13/libexec/src/crypto/tls/conn.go:780 +0x60
bytes.(*Buffer).ReadFrom(0xc003d36958, 0x9406800, 0xc003b1aa40, 0x400eca5, 0x7d4a5e0, 0x82435a0)
	/usr/local/opt/go@1.13/libexec/src/bytes/buffer.go:204 +0xb4
crypto/tls.(*Conn).readFromUntil(0xc003d36700, 0x15148278, 0xc003cde7c0, 0x5, 0xc003cde7c0, 0x0)
	/usr/local/opt/go@1.13/libexec/src/crypto/tls/conn.go:802 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc003d36700, 0x0, 0x0, 0x0)
	/usr/local/opt/go@1.13/libexec/src/crypto/tls/conn.go:609 +0x124
crypto/tls.(*Conn).readRecord(...)
	/usr/local/opt/go@1.13/libexec/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).readHandshake(0xc003d36700, 0x0, 0x0, 0x0, 0x0)
	/usr/local/opt/go@1.13/libexec/src/crypto/tls/conn.go:993 +0x6d
crypto/tls.(*Conn).readClientHello(0xc003d36700, 0x0, 0x0, 0x0)
	/usr/local/opt/go@1.13/libexec/src/crypto/tls/handshake_server.go:135 +0x40
crypto/tls.(*Conn).serverHandshake(0xc003d36700, 0x0, 0x401b22e)
	/usr/local/opt/go@1.13/libexec/src/crypto/tls/handshake_server.go:43 +0x70
crypto/tls.(*Conn).Handshake(0xc003d36700, 0x0, 0x0)
	/usr/local/opt/go@1.13/libexec/src/crypto/tls/conn.go:1364 +0x23a
google.golang.org/grpc/credentials.(*tlsCreds).ServerHandshake(0xc0014c60e0, 0x952c200, 0xc003cde7c0, 0xc00401a720, 0xbfe08f586bc56608, 0x1c1d69520b, 0xc3a8160, 0x0, 0x0)
	/Users/storm/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials/tls.go:102 +0x9b
google.golang.org/grpc.(*Server).useTransportAuthenticator(0xc000b74340, 0x952c200, 0xc003cde7c0, 0xc3a8160, 0x0, 0x0, 0xc3a8160, 0xc001174360, 0xc0014c6d68)
	/Users/storm/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:552 +0x50
google.golang.org/grpc.(*Server).handleRawConn(0xc000b74340, 0x952c200, 0xc003cde7c0)
	/Users/storm/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:677 +0xca
google.golang.org/grpc.(*Server).Serve.func3(0xc000b74340, 0x952c200, 0xc003cde7c0)
	/Users/storm/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:663 +0x3f
created by google.golang.org/grpc.(*Server).Serve
	/Users/storm/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:662 +0x7bb
```

**Environment:**
 - CockroachDB version 20.2
 - Server OS: MacOS

There is a comment in the code (context.go) that suggests this may be a known problem:

```
		// If we somehow don't get our expected magic, throw an error.
		if hdr.Magic != magic {
			panic(errors.New("didn't get expected magic bytes header"))
			// TODO (rohany): I can't get this to work. I suspect that the problem
			//  is with that maybe the improperly parsed struct is not written back
			//  into the same binary format that it was read as. I tried this with sending
			//  the magic integer over first and saw the same thing.
```

**Comment by jordanlewis** [comment]
I'm guessing that we added a new connection that isn't getting the test connection dependency injection stuff properly set up. Something like that, but I'm not sure.

**Comment by otan** [comment]
resolved by https://github.com/cockroachdb/cockroach/pull/58466
