### ISSUE TITLE
sql,tracing: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#57232]
Saw the following panic in CI [here](https://teamcity.cockroachdb.com//viewLog.html?buildId=2481540&buildTypeId=Cockroach_MergeToMaster&tab=buildResultsDiv):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb4b182]

goroutine 639392 [running]:
golang.org/x/net/trace.(*traceSet).Remove(0x0, 0xc00adac820)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:478 +0x22
golang.org/x/net/trace.(*trace).Finish(0xc00adac820)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/trace/trace.go:412 +0x13e
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).Finish(0xc00416f0e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:401 +0x112
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send(0xc00c608000, 0x534f680, 0xc00c5a0db0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:528 +0x545
github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender(0xc0050d1f80, 0x534f680, 0xc00c5a0330, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:744 +0x13c
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send(0xc01091c000, 0x534f680, 0xc00c5a0330, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:919 +0x12e
github.com/cockroachdb/cockroach/pkg/kv.sendAndFill(0x534f680, 0xc00c5a0330, 0xc002ab8880, 0xc009427400, 0x0, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:654 +0x107
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Run(0xc01091c000, 0x534f680, 0xc00c5a0330, 0xc009427400, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:590 +0xe7
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Get(0xc01091c000, 0x534f680, 0xc00c5a0330, 0x4391de0, 0xc00d4d3b80, 0x3, 0x8, 0x8, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:369 +0xbf
github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv.LookupObjectID(0x534f680, 0xc00c5a0330, 0xc01091c000, 0xc0082fe520, 0xc0082fe520, 0x0, 0x0, 0x0, 0x0, 0xc00c6081b8, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/namespace.go:211 +0x41d
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.(*Manager).resolveName.func1(0x534f680, 0xc00c5a0330, 0xc01091c000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:1501 +0x172
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn.func1(0x534f680, 0xc00c5a0330, 0xc01091c000, 0x3ff0000000000000, 0x549e620)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:707 +0x43
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec(0xc01091c000, 0x534f680, 0xc00c5a0330, 0xc002ab8f18, 0xc01091c000, 0xc008c37e00)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:811 +0xdc
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn(0xc0050d1f80, 0x534f680, 0xc00c5a0330, 0xc002ab8f70, 0x183ece0, 0x534f680)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:706 +0x105
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.(*Manager).resolveName(0xc00870b400, 0x534f680, 0xc00c5a0330, 0x164c4787f1f8da8f, 0x0, 0x0, 0x0, 0x0, 0xc002ab9030, 0x182bb56, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:1489 +0xe7
I201130 12:03:36.310882 3601 server/server.go:851 ⋮ [n?] monitoring forward clock jumps based on server.clock.forward_jump_check_enabled
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.(*Manager).AcquireByName(0xc00870b400, 0x534f680, 0xc00c5a0330, 0x164c4787f1f8da8f, 0x0, 0x0, 0x0, 0x0, 0xc008c37d80, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:1414 +0x468
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getLeasedDescriptorByName(0xc00e703210, 0x534f680, 0xc00c5a0330, 0xc009e618c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:220 +0x129
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetDatabaseVersion(0xc00e703210, 0x534f680, 0xc00c5a0330, 0xc009e618c0, 0x0, 0x0, 0x0, 0x185ea22, 0xc009426500, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:592 +0x23f
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getObjectVersion(0xc00e703210, 0x534f680, 0xc00c5a0330, 0xc009e618c0, 0x539bf40, 0xc0032dd980, 0x0, 0x0, 0x0, 0x40, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:659 +0x1a5
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetTableVersion(0xc00e703210, 0x534f680, 0xc00c5a0330, 0xc009e618c0, 0xc0032dd980, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:624 +0x89
github.com/cockroachdb/cockroach/pkg/sql/catalog/accessors.(*LogicalSchemaAccessor).getPhysicalObjectDesc(0xc00aafe200, 0x534f680, 0xc00c5a0330, 0xc009e618c0, 0x0, 0x0, 0x47c133d, 0x6, 0x47c1344, 0x8, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/accessors/logical_schema_accessors.go:188 +0x695
github.com/cockroachdb/cockroach/pkg/sql/catalog/accessors.(*LogicalSchemaAccessor).GetObjectDesc(0xc00aafe200, 0x534f680, 0xc00c5a0330, 0xc009e618c0, 0xc00c69a000, 0xc0082fe520, 0xc0082fe520, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/accessors/logical_schema_accessors.go:157 +0x145
github.com/cockroachdb/cockroach/pkg/sql.(*planner).LookupObject(0xc00e7033c0, 0x534f680, 0xc00c5a0330, 0x0, 0x0, 0x0, 0x0, 0x0, 0x47c133d, 0x6, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/resolver.go:214 +0x11a
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.ResolveExisting(0x534f680, 0xc00c5a0330, 0xc002ab9d10, 0x7fd3325c3008, 0xc00e7033c0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/name_resolution.go:317 +0x573
github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingObject(0x534f680, 0xc00c5a0330, 0x53bd8a0, 0xc00e7033c0, 0xc002ab9d10, 0x1, 0x0, 0x0, 0x1, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:153 +0x193
github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingTableObject(0x534f680, 0xc00c5a0330, 0x53bd8a0, 0xc00e7033c0, 0xc00e703ad8, 0x1, 0x0, 0x0, 0xc001c56ea0, 0xc0047f2000, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:90 +0x145
github.com/cockroachdb/cockroach/pkg/sql.(*optCatalog).ResolveDataSource(0xc00e703ac0, 0x534f680, 0xc00c5a0330, 0x0, 0xc0053d99f8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:207 +0x185
github.com/cockroachdb/cockroach/pkg/sql/opt.(*Metadata).CheckDependencies(0xc0045b7a00, 0x534f680, 0xc00c5a0330, 0x53c6a20, 0xc00e703ac0, 0x30, 0x30, 0x7fd35f31c8d8)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/metadata.go:282 +0x378
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).IsStale(0xc0045b7a00, 0x534f680, 0xc00c5a0330, 0xc00e7035c8, 0x53c6a20, 0xc00e703ac0, 0xc002ab9fc0, 0x428998, 0x30)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:287 +0x10b
github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo(0xc00e703ab8, 0x534f680, 0xc00c5a0330, 0x970000c00d4d2fe0, 0xc002aba0b0, 0x426065)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:460 +0x77e
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc00e7033c0, 0x534f680, 0xc00c5a0330, 0x10aa3dc302aba100, 0x5fc4df98)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:195 +0xde
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan(0xc00e703000, 0x534f680, 0xc00c5a0330, 0xc00e7033c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:878 +0x5a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00e703000, 0x534f680, 0xc00c5a0330, 0xc00e7033c0, 0x53c2b20, 0xc00ccac1e0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:764 +0x145
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00e703000, 0x534f680, 0xc00c5a0330, 0x536d300, 0xc00b5eeb90, 0x47c1331, 0x7b, 0x4, 0x1, 0xc001f98d20, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:622 +0xeee
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00e703000, 0x534f680, 0xc00c5a02d0, 0x536d300, 0xc00b5eeb90, 0x47c1331, 0x7b, 0x4, 0x1, 0xc001f98d20, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:119 +0xb14
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal(0xc00e703000, 0x534f680, 0xc00c5a02d0, 0xc001f98d20, 0xc0032dd8c0, 0x4, 0x4, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:206 +0x14e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2(0x0, 0x0, 0x0, 0x107d63d2, 0xed756d698, 0x0, 0xc00e703000, 0xc002abbc20, 0xc002abbc10, 0x2, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1513 +0x47b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00e703000, 0x534f680, 0xc00c5a01b0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1515 +0x445
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00e703000, 0x534f680, 0xc008d0fb30, 0xc009ccb680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1371 +0x1cd
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1(0xc00e703000, 0x534f680, 0xc008d0fb30, 0xc00c473860, 0xc00aafe1a0, 0xc009e618c0, 0xc00fb47164)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:177 +0x65
created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:176 +0x325

```

The SHA in question was d9f7bcb6905860e0f62265a3b6707e6f149403d2. Nothing jumped out to me at a cursory glance, but we've been changing up our tracing infrastructure recently, and this looks related.

**Comment by tbg** [comment]
Pretty sure this will be closed by https://github.com/cockroachdb/cockroach/pull/57942
