### ISSUE TITLE
Panic: index out of range in hlc.encodeVarintLegacyTimestamp

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#57418]
A panic from a v20.1.1 node in generated protobuf code.  See ZenDesk 6930 for more logs.  No Sentry report available due to customer environment.

```
panic: runtime error: index out of range [8] with length 8

goroutine 5135411509 [running]:
github.com/cockroachdb/cockroach/pkg/util/hlc.encodeVarintLegacyTimestamp(0xc17ecbf1cc, 0x8, 0x8, 0x1, 0x164d074c3fc597c3, 0x9)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/hlc/legacy_timestamp.pb.go:120 +0x80
github.com/cockroachdb/cockroach/pkg/util/hlc.(*LegacyTimestamp).MarshalTo(0xc0b981d510, 0xc17ecbf1cc, 0x8, 0x8, 0xc, 0x7, 0x1)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/hlc/legacy_timestamp.pb.go:111 +0x65
github.com/cockroachdb/cockroach/pkg/kv/kvserver/storagepb.(*Liveness).MarshalTo(0xc0b981d500, 0xc17ecbf1c5, 0xf, 0xf, 0x13, 0x38, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storagepb/liveness.pb.go:159 +0x185
github.com/cockroachdb/cockroach/pkg/kv/kvserver/storagepb.(*LeaseStatus).MarshalTo(0xc0b981d498, 0xc17ecbf18d, 0x47, 0x47, 0x4b, 0x237, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storagepb/lease_status.pb.go:176 +0x309
github.com/cockroachdb/cockroach/pkg/server/serverpb.(*RangeInfo).MarshalTo(0xc0b981d2d8, 0xc17ecbef56, 0x27e, 0x27e, 0x284, 0x29cf56, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:5449 +0xc06
github.com/cockroachdb/cockroach/pkg/server/serverpb.(*RangesResponse).MarshalTo(0xc045778560, 0xc17ea22000, 0x29d1d4, 0x29d1d4, 0x7757a3, 0x3e212e0, 0x4165320)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:5539 +0x19e
github.com/cockroachdb/cockroach/pkg/server/serverpb.(*RangesResponse).Marshal(0xc045778560, 0x4165320, 0xc045778560, 0x7f3c595ae988, 0xc045778560, 0x1)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:5522 +0x7a
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/encoding/proto.codec.Marshal(0x4165320, 0xc045778560, 0x1, 0xc000343920, 0x1, 0x1, 0x0)
    /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/encoding/proto/proto.go:70 +0x194
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.encode(0x7f445bb8e2a0, 0xc0002b6660, 0x4165320, 0xc045778560, 0xc0002b6660, 0x0, 0xc000330ba0, 0xc0b981da08, 0x15c656c)
    /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:543 +0x52
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).sendResponse(0xc000847800, 0x4c2a0a0, 0xc0000df680, 0xc0b1e95200, 0x4165320, 0xc045778560, 0x0, 0x0, 0xc01a0b4638, 0x4bb9da0, ...)
    /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:837 +0x89
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000847800, 0x4c2a0a0, 0xc0000df680, 0xc0b1e95200, 0xc00072ab40, 0x6e91018, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1034 +0x551
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000847800, 0x4c2a0a0, 0xc0000df680, 0xc0b1e95200, 0x0)
    /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1279 +0xd97
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000366050, 0xc000847800, 0x4c2a0a0, 0xc0000df680, 0xc0b1e95200)
    /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:717 +0xbb
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:715 +0xa1
```

**Comment by mwang1026** [comment]
@bobvawter closing -- let's resolve this through zendesk channels
