### ISSUE TITLE
panic: logging already active on Example_demo_locality

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#57499]
This happened on a recent bors run, seems unrelated to any of our changes.

See: https://teamcity.cockroachdb.com/viewLog.html?buildId=2493499&buildTypeId=Cockroach_UnitTests

```
------- Stdout: -------
=== RUN   Example_demo_locality
[demo --nodes 3 -e select node_id, locality from crdb_internal.gossip_nodes order by node_id]
[demo --nodes 9 -e select node_id, locality from crdb_internal.gossip_nodes order by node_id]
--- FAIL: Example_demo_locality (12.10s)
panic: logging already active; first used at:
goroutine 988956 [running]:
runtime/debug.Stack(0x8, 0x1, 0x8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/cockroachdb/cockroach/pkg/util/log.setActive()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:400 +0x9b
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc0048fde20, 0x1, 0x164d4c2712c956ff, 0xf171c, 0x6bfaf44, 0x32, 0xa75, 0xc008e02100, 0x20, 0xc009291a90, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:232 +0xb0
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x4fcd980, 0xc00599f590, 0x3, 0x300000001, 0x43222af, 0x2, 0xc003299660, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:50 +0x17e
github.com/cockroachdb/cockroach/pkg/util/log.loggerStorage.InfofDepth(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:1012
github.com/cockroachdb/cockroach/pkg/storage.pebbleLogger.Infof(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble.go:404
github.com/cockroachdb/pebble.MakeLoggingEventListener.func10(0x87, 0xc0084d4480, 0xa, 0xa4, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/event.go:540 +0xed
github.com/cockroachdb/pebble.(*DB).deleteObsoleteFile(0xc00c2b9400, 0x2, 0x87, 0xc0084d4480, 0xa, 0xa4)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:2677 +0x252
github.com/cockroachdb/pebble.(*DB).paceAndDeleteObsoleteFiles(0xc00c2b9400, 0x87, 0xc00c8bcfa0, 0x4, 0x4)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:2624 +0x1a5
created by github.com/cockroachdb/pebble.(*DB).doDeleteObsoleteFiles
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:2600 +0xa3f [recovered]
	panic: logging already active; first used at:
goroutine 988956 [running]:
runtime/debug.Stack(0x8, 0x1, 0x8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/cockroachdb/cockroach/pkg/util/log.setActive()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:400 +0x9b
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc0048fde20, 0x1, 0x164d4c2712c956ff, 0xf171c, 0x6bfaf44, 0x32, 0xa75, 0xc008e02100, 0x20, 0xc009291a90, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:232 +0xb0
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x4fcd980, 0xc00599f590, 0x3, 0x300000001, 0x43222af, 0x2, 0xc003299660, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:50 +0x17e
github.com/cockroachdb/cockroach/pkg/util/log.loggerStorage.InfofDepth(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:1012
github.com/cockroachdb/cockroach/pkg/storage.pebbleLogger.Infof(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble.go:404
github.com/cockroachdb/pebble.MakeLoggingEventListener.func10(0x87, 0xc0084d4480, 0xa, 0xa4, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/event.go:540 +0xed
github.com/cockroachdb/pebble.(*DB).deleteObsoleteFile(0xc00c2b9400, 0x2, 0x87, 0xc0084d4480, 0xa, 0xa4)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:2677 +0x252
github.com/cockroachdb/pebble.(*DB).paceAndDeleteObsoleteFiles(0xc00c2b9400, 0x87, 0xc00c8bcfa0, 0x4, 0x4)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:2624 +0x1a5
created by github.com/cockroachdb/pebble.(*DB).doDeleteObsoleteFiles
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:2600 +0xa3f

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc006e35ca0, 0xc001e82300, 0x10e, 0x2d120212e, 0x3fd87c0, 0xc001f48240, 0x432cd4)
	/usr/local/go/src/testing/example.go:89 +0x648
testing.runExample.func2(0xbfea6d9a26a430ea, 0x3de9ed6a07, 0x71b7d00, 0xc0047a2850, 0xc000126008, 0xc009f37680, 0xc006e35ca0, 0xc006e35cd0)
	/usr/local/go/src/testing/run_example.go:58 +0x10d
panic(0x3fd87c0, 0xc001f48240)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cockroachdb/cockroach/pkg/cli.setupLogging(0x4fcd900, 0xc000124010, 0x6e83260, 0x4320100, 0x7, 0x432f0a9)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/log_flags.go:50 +0xd9c
github.com/cockroachdb/cockroach/pkg/cli.setupAndInitializeLoggingAndProfiling(0x4fcd900, 0xc000124010, 0x6e83260, 0xc0041f2500, 0x80, 0x420f260, 0xc000eeec01)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:978 +0x6e
github.com/cockroachdb/cockroach/pkg/cli.(*transientCluster).checkConfigAndSetupLogging(0xc00c0c5480, 0x4fcd900, 0xc000124010, 0x6e83260, 0xc0002fe900, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo_cluster.go:91 +0x185
github.com/cockroachdb/cockroach/pkg/cli.runDemo(0x6e83260, 0x4f8c180, 0xc0002fe900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:272 +0x1c5
github.com/cockroachdb/cockroach/pkg/cli.init.4.func1(0x6e83260, 0xc002080400, 0x0, 0x4, 0xc000b57050, 0xd)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:57 +0x33
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x6e83260, 0xc002080400, 0x0, 0x4, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:194 +0x79
github.com/spf13/cobra.(*Command).execute(0x6e83260, 0xc0020803c0, 0x4, 0x4, 0x6e83260, 0xc0020803c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:826 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x6e81be0, 0xc0047a2850, 0xc006e359a0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:277
github.com/cockroachdb/cockroach/pkg/cli.cliTest.RunWithArgs.func1(0xc00311b180, 0x5, 0x5, 0x0, 0xc0068c8cd0, 0x44, 0x49eac58, 0xc0001266a0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli_test.go:359 +0x2ab
github.com/cockroachdb/cockroach/pkg/cli.cliTest.RunWithArgs(0x0, 0xc0068c8cd0, 0x44, 0x49eac58, 0xc0001266a0, 0x0, 0x0, 0x0, 0xc00311b180, 0x5, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli_test.go:360 +0x85
github.com/cockroachdb/cockroach/pkg/cli.Example_demo_locality()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo_locality_test.go:43 +0x410
testing.runExample(0x4360a33, 0x15, 0x49ea6e0, 0x4810bf8, 0x2dd, 0x0, 0x0)
	/usr/local/go/src/testing/run_example.go:62 +0x209
testing.runExamples(0xc006e35e48, 0x6e94080, 0x17, 0x17, 0xbfea6f19b973b4a9)
	/usr/local/go/src/testing/example.go:44 +0x1af
testing.(*M).Run(0xc000a38480, 0x0)
	/usr/local/go/src/testing/testing.go:1346 +0x273
github.com/cockroachdb/cockroach/pkg/cli_test.TestMain(0xc000a38480)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/main_test.go:34 +0x8e
main.main()
	_testmain.go:221 +0x165

goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:75 +0x73
created by github.com/cockroachdb/cockroach/pkg/util/log.init.5
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:41 +0x35

goroutine 20 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/pkg/util/log.signalFlusher()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:98 +0x126
created by github.com/cockroachdb/cockroach/pkg/util/log.init.5
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:42 +0x4d

goroutine 34 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:150 +0x45

goroutine 13 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00030f600)
	/go/src/github.com/cockroachdb/cockroach/vendor/go.opencensus.io/stats/view/worker.go:152 +0xdd
created by go.opencensus.io/stats/view.init.0
	/go/src/github.com/cockroachdb/cockroach/vendor/go.opencensus.io/stats/view/worker.go:29 +0x57
```

**Comment by sumeerbhola** [comment]
Happened again
https://teamcity.cockroachdb.com/viewLog.html?buildId=2525384&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

**Comment by knz** [comment]
dup  #57759
