### ISSUE TITLE
sql: adding "NOT NULL" column to table without specifying a default leads to a panic 

### ISSUE THREAD

**Issue by nullstyle** [cockroachdb/cockroach#5751]
Given a brand new single node:

```shell
➜  cockroach-beta-20160330.darwin-10.9-amd64  ./cockroach start --insecure
build:     beta-20160330 @ 2016/03/30 14:58:36 (go1.6)
admin:     http://scott-2.local:8080
sql:       postgresql://root@scott-2.local:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
```

The following script causes a node panic:

```sql
CREATE DATABASE test;
SET DATABASE = test;
CREATE TABLE test (v DECIMAL);
INSERT INTO test VALUES (DECIMAL '1.0');
ALTER TABLE test ADD COLUMN v2 DECIMAL NOT NULL;
SELECT * FROM test;
```

Stack trace:
```
panic: Non-nullable column with no value!

goroutine 136 [running]:
panic(0x4e7c220, 0xc820d79680)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql.(*scanNode).maybeOutputRow(0xc820943400, 0xc820d79601)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/scan.go:547 +0x291
github.com/cockroachdb/cockroach/sql.(*scanNode).Next(0xc820943400, 0x7e0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/scan.go:157 +0x92
github.com/cockroachdb/cockroach/sql.(*selectNode).Next(0xc820938fc0, 0xc8201c1ef0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/select.go:108 +0x53
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc820514000, 0x7492b78, 0xc820d1cfc0, 0xc820747078, 0xece8e7232, 0xc81ba2ef85, 0x5d4b540, 0x1, 0x0, 0x0, ...)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/executor.go:894 +0x353
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInOpenTxn(0xc820514000, 0x7492b78, 0xc820d1cfc0, 0xc820747078, 0xc820d70101, 0x1440c8e9f6ec41b7, 0x0, 0xc820747028, 0x0, 0x0, ...)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/executor.go:778 +0x58d
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc820514000, 0xc820d785b0, 0x1, 0x1, 0xc820747078, 0xc820747028, 0x1e0101, 0x0, 0x0, 0x0, ...)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/executor.go:556 +0x630
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc820514000, 0xc820747078, 0x1, 0xc820747028, 0xc82067fb80, 0xc820d785b0, 0x1, 0x1, 0xc820911390, 0xc8209113a8, ...)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/executor.go:488 +0x147
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func1(0xc8208106e0, 0xc82067fb80, 0x4)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/executor.go:401 +0x325
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc8208106e0, 0x5310101, 0x1440c8e9f6ec0e27, 0x0, 0xc8209114e8, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/client/txn.go:531 +0x410
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc820514000, 0x7416210, 0xc82094a180, 0xc820747000, 0xc820a0c0a4, 0x13, 0x0, 0x0, 0x0, 0x745cd00)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/executor.go:405 +0x892
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc820514000, 0x7416210, 0xc82094a180, 0xc820747000, 0xc820a0c0a4, 0x13, 0x0, 0x0, 0x0, 0x0, ...)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/executor.go:295 +0xe2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc8202af200, 0x7416210, 0xc82094a180, 0xc820a0c0a4, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:598 +0xb2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc8202af200, 0x7416210, 0xc82094a180, 0xc8202af228, 0x0, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:308 +0xf2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc8202af200, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:268 +0x109b
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc820368358, 0x9200028, 0xc82075e210, 0x0, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:159 +0x929
github.com/cockroachdb/cockroach/server.(*Server).Start.func4.1(0x9200028, 0xc82075e210)
	/ext-go/1/src/github.com/cockroachdb/cockroach/server/server.go:300 +0x4b
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc820308100, 0x9200028, 0xc82075e210, 0xc820222060)
	/ext-go/1/src/github.com/cockroachdb/cockroach/util/net.go:125 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/ext-go/1/src/github.com/cockroachdb/cockroach/util/net.go:127 +0x31f
```

As a note, the alter table statement is accepted and reports as succeeded.  The panic gets triggered by the select statement.

**Comment by tamird** [comment]
Looks relevant: https://github.com/cockroachdb/cockroach/blob/887cf85/sql/backfill.go#L87:L88

**Comment by seiflotfy** [comment]
When backfilling what value is expected if no default is defined. Or should it log out warnings?

**Comment by tamird** [comment]
Without a default it should probably fail. I'd check against postgres to
see what the error should look like.

**Comment by seiflotfy** [comment]
Yes altering should fail, Postgres errors out too:
```
ERROR:  column "v2" contains null values
STATEMENT:  ALTER TABLE test ADD COLUMN v2 DECIMAL NOT NULL;
```
