### ISSUE TITLE
changefeedccl: skipped TestChangefeedInitialScan under race because of timeout

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#57754]
https://teamcity.cockroachdb.com/viewLog.html?buildId=2508080&buildTypeId=Cockroach_UnitTests_Testrace&tab=buildResultsDiv

**Comment by lucy-zhang** [comment]
I got a timeout in `test` on my branch, and I'm pretty sure it's not related to the PR: https://teamcity.cockroachdb.com/viewLog.html?buildId=2720931&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

It looks like #60787 also ran into this.

**Comment by andreimatei** [comment]
happened again [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=2907924&buildTypeId=Cockroach_UnitTests)

All the test goroutines below:

```
goroutine 42558 [chan receive, 29 minutes]:
testing.(*T).Run(0xc002836a80, 0x49c257a, 0x1a, 0xc001537280, 0x1)
	/usr/local/go/src/testing/testing.go:1169 +0x2da
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedInitialScan.func1(0xc00311a180, 0xc002f88680, 0x57234a0, 0xc001d24e70)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_test.go:427 +0x19c
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.enterpriseTestWithServerArgs.func1(0xc00311a180)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/helpers_test.go:346 +0x865
testing.tRunner(0xc00311a180, 0xc001094700)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3

goroutine 44768 [select]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdctest.(*jobFeed).fetchJobError(0xc0017e8960, 0xc000124010, 0xc0005b64e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdctest/testfeed.go:245 +0xe9
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdctest.(*TableFeed).Next(0xc0017e8960, 0xc000000001, 0x2, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdctest/testfeed.go:412 +0x57
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.readNextMessages(0x58c2520, 0xc002836a80, 0x579c2e0, 0xc0017e8960, 0x1, 0x3d40600, 0x7624a00, 0xc0027a9200, 0xc00153fe30)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/helpers_test.go:69 +0xbc
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase(0x58c2520, 0xc002836a80, 0x579c2e0, 0xc0017e8960, 0xc0037bcbc0, 0x1, 0x1, 0xc0037bcb00)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/helpers_test.go:102 +0x9a
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloads(0x58c2520, 0xc002836a80, 0x579c2e0, 0xc0017e8960, 0xc0037bcbc0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/helpers_test.go:113 +0x87
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedInitialScan.func1.2(0xc002836a80)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_test.go:442 +0x45b
testing.tRunner(0xc002836a80, 0xc001537280)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3


goroutine 40704 [chan receive, 29 minutes]:
testing.(*T).Run(0xc00311a180, 0x4986412, 0xa, 0xc001094700, 0x9f9c81400000001)
	/usr/local/go/src/testing/testing.go:1169 +0x2da
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedInitialScan(0xc002f23980)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_test.go:449 +0x152
testing.tRunner(0xc002f23980, 0x5048fb0)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3
```
