### ISSUE TITLE
circleci: failed tests (15685): TestBuildInfo 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5778]
The following test appears to have failed:

[#15685](https://circleci.com/gh/cockroachdb/cockroach/15685):

```
I160331 19:48:02.585577 acceptance/cluster/localcluster.go:649  stopping
I160331 19:48:02.585784 acceptance/cluster/localcluster.go:547  event stream done, resetting...: net/http: request canceled
I160331 19:48:02.585802 acceptance/cluster/localcluster.go:570  events monitor exits
I160331 19:48:02.587028 acceptance/cluster/docker.go:363  ContainerKill: *errors.errorString: Error response from daemon: Cannot kill container 5e2b4124589ca95e477a0b79c4270b26066653f54130425cc879fec3c8c97457: Container 5e2b4124589ca95e477a0b79c4270b26066653f54130425cc879fec3c8c97457 is not running
I160331 19:48:14.922431 acceptance/cluster/docker.go:363  ContainerKill: *errors.errorString: An error occurred trying to connect: context deadline exceeded
--- FAIL: TestBuildInfo (19.31s)
panic: An error occurred trying to connect: context deadline exceeded [recovered]
	panic: An error occurred trying to connect: context deadline exceeded

goroutine 153 [running]:
panic(0x12fa260, 0xc82041c820)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8202602d0)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0x12fa260, 0xc82041c820)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/cockroachdb/cockroach/acceptance/cluster.maybePanic(0x7f99bc215028, 0xc82041c820)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/docker.go:133 +0x4b
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).stop(0xc820108820)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:675 +0x580
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).AssertAndStop(0xc820108820, 0xc8202602d0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:638 +0x53
github.com/cockroachdb/cockroach/acceptance.runTestOnConfigs.func1(0xc8202602d0, 0xc8200d3ec8, 0x174f1e0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/util_test.go:159 +0xae
github.com/cockroachdb/cockroach/acceptance.runTestOnConfigs(0xc8202602d0, 0x174f1e0)
--
testing.tRunner(0xc8202602d0, 0x1dcbc58)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 1 [chan receive]:
testing.RunTests(0x1751248, 0x1dcbc40, 0x12, 0x12, 0x115bd6e5aafdd901)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820038f08, 0x174f180)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc820038f08)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:48 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:86 +0x114

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 7 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x20a2180)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:993 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:594 +0x8a

goroutine 20 [select, locked to thread]:
runtime.gopark(0x1751a80, 0xc820028728, 0x1491500, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820028728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820028728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 9 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 10 [chan receive]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:39 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:47 +0x30

goroutine 14 [IO wait]:
net.runtime_pollWait(0x7f99bc223930, 0x72, 0xc820233000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201a3bf0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201a3bf0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201a3b90, 0xc820233000, 0x1000, 0x1000, 0x0, 0x7f99bc215050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a368, 0xc820233000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820234410)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 15 [select]:
net/http.(*persistConn).writeLoop(0xc820234410)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 157 [select]:
net/http.(*persistConn).writeLoop(0xc8201089c0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 156 [IO wait]:
net.runtime_pollWait(0x7f99bc2237b0, 0x72, 0xc8204ab000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82039a6f0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82039a6f0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82039a690, 0xc8204ab000, 0x1000, 0x1000, 0x0, 0x7f99bc215050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82012a270, 0xc8204ab000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201089c0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 295 [runnable]:
github.com/docker/engine-api/client/transport/cancellable.Do.func2(0xc8200d8a80)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:61
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:66 +0x1dd

goroutine 269 [runnable]:
net/http.(*persistConn).roundTrip(0xc8201089c0, 0xc82041c400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc8201cc0c0, 0xc82013a540, 0xc8201cc0c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:320 +0x9bb
net/http.send(0xc82013a540, 0x7f99bc219820, 0xc8201cc0c0, 0x0, 0x0, 0x0, 0xc82012e500, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc8203ea3c0, 0xc82013a540, 0x0, 0x0, 0x0, 0xc820392058, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc8203ea3c0, 0xc82013a540, 0x17515f0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment]
This failure was due to incorrect detection of the `deadline exceeded` error when retrying docker calls. Fixed by #5781.
