### ISSUE TITLE
sql: found repro for "adding questionable descriptor 4294867296"

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57868]
Courtesy of the `pgx` go driver:

```
$ ./cockroach demo --empty --logtostderr=WARNING
```

```sql
> SELECT t.oid, t.typname
  FROM pg_type AS t
  JOIN pg_type AS base_type ON t.typelem = base_type.oid
 WHERE (t.typtype = 'b') AND (base_type.typtype = 'e');
```

```
W201212 22:57:42.309093 2021 sql/catalog/lease/lease.go:1651  adding questionable descriptor 4294867296 to lease manager: &{{{{0 0}} {[]} false 0} 0xc000d98cf0 4294867296 0} goroutine 2021 [running]:
runtime/debug.Stack(0x878e60, 0xc0012bea40, 0xc0fffe7960)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.(*Manager).findDescriptorState(0xc0012fc640, 0x1fffe7960, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:1650 +0x1a5
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.(*Manager).Acquire(0xc0012fc640, 0x18e39c0, 0xc000987f80, 0x16501a306fd47660, 0x0, 0xfffe7960, 0x0, 0x0, 0x8, 0x9, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:1535 +0x45
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorVersionByID(0xc0004d6210, 0x18e39c0, 0xc000987f80, 0xc00076ecf0, 0xfffe7960, 0xc001180100, 0xc00118a6c0, 0x1934901, 0xc0006b9510, 0x36e9425)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:759 +0x2ea
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetTypeVersionByID(0xc0004d6210, 0x18e39c0, 0xc000987f80, 0xc00076ecf0, 0xc0fffe7960, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1138 +0x85
github.com/cockroachdb/cockroach/pkg/sql.glob..func140(0x18e39c0, 0xc000987f80, 0x1a2d160, 0xc00118a6c0, 0xc0004d63c0, 0xc0028ff980, 0xc00152a100, 0x0, 0x14, 0xc0024d4d80)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:2376 +0x23c
github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).makeConstrainedRowsGenerator.func1(0x1852b20, 0xc000570d80, 0x4, 0xc0012be340)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:586 +0x4a2
github.com/cockroachdb/cockroach/pkg/sql.(*vTableLookupJoinNode).Next(0xc000570d80, 0x18e39c0, 0xc000987f80, 0xc00079cdc0, 0xc0004d63c0, 0x0, 0x12beb80, 0xc001e56060)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:305 +0x51c
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc000527800, 0xc0004d63c0, 0x18e6540, 0xc000570d80, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:173 +0x447
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run(0x18e39c0, 0xc000987f80, 0x1909e80, 0xc000527800, 0x18ba4c0, 0xc002ae2000)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:171 +0x35
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run(0xc000527800, 0x18e39c0, 0xc000987f80)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:765 +0x92
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc000570fc0, 0x18e39c0, 0xc000987f80, 0x12bdf98, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:392 +0x24b
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc001957600, 0xc001e3d0a0, 0xc00076ecf0, 0xc00111fc80, 0xc002ae3180, 0xc0004d65c8, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:384 +0x469
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc001957600, 0x18e3a80, 0xc002a53bf0, 0xc0004d65c8, 0xc001e3d0a0, 0xc00076ecf0, 0x18e5e80, 0xc0018ad9a0, 0x0, 0xc002ae3180, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:977 +0x1d2
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc0004d6000, 0x18e3a80, 0xc002a53bf0, 0xc0004d63c0, 0x3, 0x831094810, 0xc000f6c680, 0xc0006ba300, 0xc001c92958, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:997 +0x3aa
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0004d6000, 0x18e3a80, 0xc002a53bf0, 0xc0004d63c0, 0x831094810, 0xc000f6c680, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:876 +0x706
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0004d6000, 0x18e3a80, 0xc002a53bf0, 0x19021c0, 0xc000fe0050, 0xc000462160, 0x96, 0x0, 0x2, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:631 +0xf46
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0004d6000, 0x18e3a80, 0xc002a53bc0, 0x19021c0, 0xc000fe0050, 0xc000462160, 0x96, 0x0, 0x2, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:119 +0xb14
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0x19021c0, 0xc000fe0050, 0xc000462160, 0x96, 0x0, 0x2, 0x125d9588, 0xed76741e6, 0x0, 0x125da214, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1445 +0x225
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc0004d6000, 0x18e3a80, 0xc002a53bc0, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1447 +0x13f7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0004d6000, 0x18e39c0, 0xc002a48440, 0xc000fd43c0, 0x5400, 0x15000, 0xc000fd4460, 0xc002ae14f0, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1372 +0x1cd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000a91700, 0x18e39c0, 0xc002a48440, 0xc0004d6000, 0x5400, 0x15000, 0xc000fd4460, 0xc002ae14f0, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:481 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc001c281ed, 0xc001696fa0, 0x18e39c0, 0xc002a48440, 0xc002ae14f0, 0xc000a91700, 0xc000f6c000, 0x1943ae0, 0xc0028f7480, 0xc000ffe600, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:628 +0x3ea
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:556 +0x185

```

cc @ajwerner @rafiss for triage

**Comment by jordanlewis** [comment]
Yay, thanks for finding this case.

It looks like if you call `Acquire` with an id of a descriptor that doesn't exist, you get this stack trace.

I think we likely get into trouble here with more than just user-defined types, actually. There are a bunch of code paths that call `GetTableVersionByID` with arbitrary descriptor ids that may not exist, as long as they are invoked without the `AvoidCache` option, which eagerly tries to fetch the descriptor and errors out if it doesn't exist. Such a code path will trigger this error every time.

Here is a simple example:

```
SELECT * FROM pg_class WHERE oid=4294867297
```

This causes a call to `planner.LookupTableID` with the arbitrary number above.

I'm not sure how bad of a problem this is. Is it essential that we only lease descriptors that exist, or is it merely sloppy not to? Tagging @lucy-zhang as well.

**Comment by knz** [comment]
I'd be mildly in favor of splitting the lookup/access functions, into

- one to look up descriptors expected to exist already, which would assert if given something invalid

- one to look up possibly invalid IDs, and would also return a boolean to indicate there's nothing for that ID

A bit like we already distinguish name resolution for creation, from that of existing objects.

**Comment by lucy-zhang** [comment]
> I'd be mildly in favor of splitting the lookup/access functions

That's what the `Required` flag on `tree.CommonLookupFlags` is for, and all the methods on `descs.Collection` take those flags as an argument. (Although those methods don't return a boolean indicating whether the descriptor exists, and I'm leaning toward adding them, in part to avoid problems with nil values and interfaces.) We ultimately intend to replace all the methods like `planner.LookupTableID` which are thin wrappers around `descs.Collection` methods with calls to the `descs.Collection` methods themselves.

>  There are a bunch of code paths that call `GetTableVersionByID` with arbitrary descriptor ids that may not exist, as long as they are invoked without the `AvoidCache` option, which eagerly tries to fetch the descriptor and errors out if it doesn't exist. Such a code path will trigger this error every time.

This is due to a bug (or API inconsistency) in the `descs.Collection`. https://github.com/cockroachdb/cockroach/pull/57343 will fix it.

**Comment by jordanlewis** [comment]
Assigning @lucy-zhang to investigate/close once #57343 is in.

**Comment by ajwerner** [comment]
For what it's worth, the issues here are caused by `typelem` values of `0` which we then try to resolve to a user-defined type. That's bad. 

All of this stuff takes place inside this virtual index generator: 
https://github.com/cockroachdb/cockroach/blob/c723c408c80cd74f8da1bef521a978c5db845af7/pkg/sql/pg_catalog.go#L2393

It seems to me that we should consider panicking if attempting to discover a user defined type with an OID that certainly doesn't correspond to one. We should definitely return false in this function if the value is `0`.

**Comment by ajwerner** [comment]
Created #58416 to fix this and the underlying issues. Created #58414 to make it less likely to happen in the future.
