### ISSUE TITLE
demo movr: fatal: morestack on g0

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#57885]
**Describe the problem**

`alter` of non-existent index and table seem to have caused a fatal error.

**To Reproduce**

Could not reproduce, but the below commands were run while testing various syntax for a customer.

```
cockroach demo movr --geo-partitioned-replicas
create table city (city string primary key);
insert into city values ('seattle'), ('san francisco'), ('los angeles');
create table city2 as select * from city;
select * from city where city in (select city from city);
create index on rides (start_address) partition by list (start_address) (partition us_west values in (select city from city));


ALTER INDEX students_by_list@name_idx PARTITION BY LIST (country) (
    PARTITION north_america VALUES IN (select city from city),
    PARTITION australia VALUES IN (select city from city),
    PARTITION DEFAULT VALUES IN (default)
  );
```
**Expected behavior**

N/A

**Additional data / screenshots**

```
root@127.0.0.1:59938/movr> ALTER INDEX students_by_list@name_idx PARTITION BY LIST (country) (
    PARTITION north_america VALUES IN (select city from city),
    PARTITION australia VALUES IN (select city from city),
    PARTITION DEFAULT VALUES IN (default)
  );
invalid syntax: statement ignored: at or near "select": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
ALTER INDEX students_by_list@name_idx PARTITION BY LIST (country) (
    PARTITION north_america VALUES IN (select city from city),
                                       ^
HINT: try \h ALTER INDEX
root@127.0.0.1:59938/movr> fatal: morestack on g0
SIGTRAP: trace trap
PC=0x4061b42 m=2 sigcode=1

goroutine 824633722176 [???, locked to thread]:
runtime.abort()
	/usr/local/go/src/runtime/asm_amd64.s:859 +0x2
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:416 +0x25

goroutine 1 [syscall]:
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix._C2func_go_libedit_gets(0x13303600, 0x13c10c60, 0x0, 0x0, 0xc0093a7dd8, 0xc0093a7ddc, 0xc000000001, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:187 +0x56
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix.EditLine.GetLine.func1(0xc00f8db100, 0xc0093a7dd8, 0xc0093a7ddc, 0xc00f8db148, 0xc00f8db100, 0xc00c2c56e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix/editline_unix.go:281 +0xf5
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix.EditLine.GetLine(0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix/editline_unix.go:281 +0xaa
github.com/cockroachdb/cockroach/pkg/cli.(*cliState).doReadLine(0xc011115c00, 0x6, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:893 +0x617
github.com/cockroachdb/cockroach/pkg/cli.runInteractive(0xc00be98b40, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1316 +0xf3
github.com/cockroachdb/cockroach/pkg/cli.runClient(0xc000725b80, 0xc00be98b40, 0xc00758fb00, 0xb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1531 +0x78
github.com/cockroachdb/cockroach/pkg/cli.runDemo(0xc000725b80, 0x82891e0, 0xc000643320, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:353 +0x8a7
github.com/cockroachdb/cockroach/pkg/cli.init.5.func1(0xc000725b80, 0xc000275be0, 0x0, 0x1, 0xc000891e70, 0xc000b2dbe8)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:142 +0x3d
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0xc000725b80, 0xc000275be0, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:187 +0x79
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0xc000725b80, 0xc000275b80, 0x1, 0x1, 0xc000725b80, 0xc000275b80)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:762 +0x460
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa86dea0, 0xc00007a120, 0xc00023768a, 0x9)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:800
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:224
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:67 +0x272
main.main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:26 +0x20

goroutine 65535 [??? (scan)]:
```

**Environment:**
 - CockroachDB version [20.2.0]
 - Server OS: [OSX 11.0.1]
 - Client app [`cockroach demo movr`, JDBC]

**Additional context**

N/A

Jira issue: CRDB-6295

**Comment by jordanlewis** [comment]
It's a bug in the CLI's line editor, not sure what.

**Comment by knz** [comment]
We'd need more testing but I suspect this happens when either:

- resizing the terminal
- handling ctrl+z / resume
- the tab key

And  is fundamentally caused by yet another oddity of macos Big Sur.

At this point (and given the other big sur issues cropping up) I am tempted to mark native macos execution as unsupported, disable the interactive deadline handling entirely in that case, and recommend folk use the Linux binary inside docker instead.

**Comment by robert-s-lee** [comment]
this time, the `iterm2` session crashed by itself.  The session was not closed, the laptop was closed,  the session was idle overnight, and the next morning it crashed.  

```
root@127.0.0.1:60745/movr> fatal: morestack on g0
SIGTRAP: trace trap
PC=0x4061b42 m=2 sigcode=1

goroutine 824633722176 [???, locked to thread]:
runtime.abort()
	/usr/local/go/src/runtime/asm_amd64.s:859 +0x2
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:416 +0x25

goroutine 1 [syscall]:
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix._C2func_go_libedit_gets(0x15343600, 0x1120dba0, 0x0, 0x0, 0xc00e6d5948, 0xc00e6d594c, 0xc000000001, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:187 +0x56
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix.EditLine.GetLine.func1(0xc01124fe80, 0xc00e6d5948, 0xc00e6d594c, 0xc01124fec8, 0xc01124fe80, 0xc003dcf6e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix/editline_unix.go:281 +0xf5
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix.EditLine.GetLine(0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix/editline_unix.go:281 +0xaa
github.com/cockroachdb/cockroach/pkg/cli.(*cliState).doReadLine(0xc01136d700, 0x6, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:893 +0x617
github.com/cockroachdb/cockroach/pkg/cli.runInteractive(0xc0122d32c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1316 +0xf3
github.com/cockroachdb/cockroach/pkg/cli.runClient(0xc000715b80, 0xc0122d32c0, 0xc008047560, 0xb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1531 +0x78
github.com/cockroachdb/cockroach/pkg/cli.runDemo(0xc000715b80, 0x82891e0, 0xc00061f560, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:353 +0x8a7
github.com/cockroachdb/cockroach/pkg/cli.init.5.func1(0xc000715b80, 0xc0002bd7f0, 0x0, 0x1, 0xc00091bf40, 0xc000b39be8)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:142 +0x3d
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0xc000715b80, 0xc0002bd7f0, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:187 +0x79
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0xc000715b80, 0xc0002bd7e0, 0x1, 0x1, 0xc000715b80, 0xc0002bd7e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:762 +0x460
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa86dea0, 0xc00007a120, 0xc0002e366a, 0x9)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:800
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:224
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:67 +0x272
main.main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:26 +0x20

goroutine 65535 [??? (scan)]:
```

**Comment by knz** [comment]
Robert when you laptop resumed from sleep, all processes were sent the signal SIGCONT.

The issue is with signal handling so that will also cause it.

**Comment by erikgrinaker** [comment]
Yeah, I'm also seeing this. Rapidly resizing the terminal triggers it consistently.
