### ISSUE TITLE
tree: geos can panic nodes with SIGFPE

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#57905]
```
fatal error: unexpected signal during runtime execution
[signal SIGFPE: floating-point exception code=0x1 addr=0x1515194ecd26 pc=0x1515194ecd26]

runtime stack:
runtime.throw(0x48e475d, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 3972829 [syscall]:
_ZN4geos9algorithm8distance23DiscreteFrechetDistance13getSegementAtERKNS_4geom18CoordinateSequenceEm
	pc=0x1515194ecd26
_ZN4geos9algorithm8distance23DiscreteFrechetDistance17getFrecheDistanceERSt6vectorIS3_INS1_17PointPairDistanceESaIS4_EESaIS6_EEmmRKNS_4geom18CoordinateSequenceESD_
	pc=0x1515194ecfa5
_ZN4geos9algorithm8distance23DiscreteFrechetDistance7computeERKNS_4geom8GeometryES6_
	pc=0x1515194eda37
_ZN4geos9algorithm8distance23DiscreteFrechetDistance8distanceERKNS_4geom8GeometryES6_d
	pc=0x1515194edd27
GEOSFrechetDistanceDensify_r
	pc=0x151519218005
CR_GEOS_FrechetDistanceDensify
	pc=0x3beafae
runtime.cgocall(0x3be5c10, 0xc002732e90, 0x450101)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc002732e48 sp=0xc002732e10 pc=0x4485db
github.com/cockroachdb/cockroach/pkg/geo/geos._Cfunc_CR_GEOS_FrechetDistanceDensify(0x15152202b000, 0xc00344a640, 0xcd, 0xc013df0b00, 0xdd, 0x1, 0xc02f593908, 0x0, 0x0)
	_cgo_gotypes.go:340 +0x50 fp=0xc002732e90 sp=0xc002732e48 pc=0x113f450
github.com/cockroachdb/cockroach/pkg/geo/geos.FrechetDistanceDensify.func1(0x15152202b000, 0xc00344a640, 0xcd, 0x140, 0xc013df0b00, 0xdd, 0x150, 0x1, 0xc02f593908, 0xc002732fd0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/geo/geos/geos.go:791 +0xd7 fp=0xc002732f08 sp=0xc002732e90 pc=0x114c297
github.com/cockroachdb/cockroach/pkg/geo/geos.FrechetDistanceDensify(0xc00344a640, 0xcd, 0x140, 0xc013df0b00, 0xdd, 0x150, 0x1, 0x55ef941b29a1c187, 0x22fff58, 0x55ef941b29a1c187)
	/go/src/github.com/cockroachdb/cockroach/pkg/geo/geos/geos.go:791 +0xf8 fp=0xc002732f98 sp=0xc002732f08 pc=0x1147958
github.com/cockroachdb/cockroach/pkg/geo/geomfn.FrechetDistanceDensify(0x2, 0xc00344a640, 0xcd, 0x140, 0x300000000, 0xc0188f4860, 0x2, 0xc013df0b00, 0xdd, 0x150, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/geo/geomfn/distance.go:742 +0xf8 fp=0xc0027331a0 sp=0xc002732f98 pc=0x176e958
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func375(0xc0027065c8, 0xc005d1ff50, 0x3, 0x3, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/geo_builtins.go:2984 +0x20d fp=0xc0027332a8 sp=0xc0027331a0 pc=0x207172d
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval(0xc003c5df00, 0xc0027065c8, 0x0, 0xc005d1fef0, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3961 +0xbc fp=0xc0027333c0 sp=0xc0027332a8 pc=0x167dd9c
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).FoldFunction(0xc002706b28, 0xc005d1fec0, 0x3, 0x3, 0xc0027335c8, 0x3, 0x4)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/fold_constants_funcs.go:569 +0x237 fp=0xc002733450 sp=0xc0027333c0 pc=0x23f8c57
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructFunction(0xc002706b18, 0xc005d1fec0, 0x3, 0x3, 0xc0027335c8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:16829 +0x11a fp=0xc0027334c8 sp=0xc002733450 pc=0x23b209a
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFunction(0xc001cc9680, 0xc003c5dd80, 0xc0028ab8f0, 0xc0028ab9e0, 0xc020709680, 0x0, 0xc0028ab8f0, 0xc00d034d80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:506 +0x318 fp=0xc002733678 sp=0xc0027334c8 pc=0x307c9d8
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar(0xc001cc9680, 0x55aba80, 0xc003c5dd80, 0xc0028ab8f0, 0xc0028ab9e0, 0xc020709680, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:294 +0x1bf3 fp=0xc002733a08 sp=0xc002733678 pc=0x30799b3
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildProjectionList(0xc001cc9680, 0xc0028ab8f0, 0xc0028ab9e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:175 +0x68 fp=0xc002733a70 sp=0xc002733a08 pc=0x30777e8
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause(0xc001cc9680, 0xc020709540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1110 +0x365 fp=0xc002733b60 sp=0xc002733a70 pc=0x30919e5
[02:18:21][Test Output]
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens(0xc001cc9680, 0x55900e0, 0xc020709540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1029 +0x68d fp=0xc002733c30 sp=0xc002733b60 pc=0x30914cd
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1(0xc0028ab800, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1002 +0xaa fp=0xc002733cb8 sp=0xc002733c30 pc=0x30aa86a
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).processWiths(0xc001cc9680, 0x0, 0xc0028ab800, 0xc002733df8, 0xc005d1f9e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:29 +0x69 fp=0xc002733cf0 sp=0xc002733cb8 pc=0x30a51c9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc001cc9680, 0xc0057a8f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0028ab800, 0x402aaa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1001 +0x435 fp=0xc002733e68 sp=0xc002733cf0 pc=0x3090af5
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc001cc9680, 0x5582aa0, 0xc0057a8f00, 0x0, 0x0, 0x0, 0xc0028ab800, 0x400)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:265 +0x3b7 fp=0xc002733f38 sp=0xc002733e68 pc=0x304cf97
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot(0xc001cc9680, 0x5582aa0, 0xc0057a8f00, 0x0, 0x0, 0x0, 0xc0028ab800, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:229 +0xb8 fp=0xc002733fa0 sp=0xc002733f38 pc=0x304cb78
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc001cc9680, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:200 +0x245 fp=0xc002734050 sp=0xc002733fa0 pc=0x304c705
github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo(0xc002706ab8, 0x5564360, 0xc005d1fc20, 0x13120c7, 0xc0208ba900, 0x55d4c40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:509 +0x485 fp=0xc002734150 sp=0xc002734050 pc=0x31fde65
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc0027063c0, 0x5564360, 0xc005d1fc20, 0x107b6a3320709580, 0x5fd703ac)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:195 +0xde fp=0xc002734208 sp=0xc002734150 pc=0x31fc99e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan(0xc002706000, 0x5564360, 0xc005d1fc20, 0xc0027063c0, 0x43b8280, 0x425a6a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:898 +0x5a fp=0xc0027342a8 sp=0xc002734208 pc=0x31224fa
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc002706000, 0x5564360, 0xc005d1fc20, 0xc0027063c0, 0x1515223a92f8, 0xc002388f80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:784 +0x145 fp=0xc002734568 sp=0xc0027342a8 pc=0x31216e5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc002706000, 0x5564360, 0xc005d1fc20, 0x5582aa0, 0xc0057a8f00, 0xc002da0000, 0x39c, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:631 +0xf46 fp=0xc002735300 sp=0xc002734568 pc=0x311e9c6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc002706000, 0x5564360, 0xc005d1fbf0, 0x5582aa0, 0xc0057a8f00, 0xc002da0000, 0x39c, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:119 +0xb14 fp=0xc002735830 sp=0xc002735300 pc=0x311d374
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0x5582aa0, 0xc0057a8f00, 0xc002da0000, 0x39c, 0x0, 0x0, 0x107a7907, 0xed768faac, 0x0, 0x107a7d71, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1445 +0x225 fp=0xc0027358f0 sp=0xc002735830 pc=0x32a59a5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc002706000, 0x5564360, 0xc005d1fbf0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1447 +0x13f7 fp=0xc002735d18 sp=0xc0027358f0 pc=0x31134f7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc002706000, 0x55642a0, 0xc00175f940, 0xc013868820, 0x5400, 0x15000, 0xc0138688c0, 0xc0002d4240, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1372 +0x1cd fp=0xc002735db8 sp=0xc002735d18 pc=0x3111ead
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc001255b80, 0x55642a0, 0xc00175f940, 0xc002706000, 0x5400, 0x15000, 0xc0138688c0, 0xc0002d4240, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:481 +0xce fp=0xc002735e40 sp=0xc002735db8 pc=0x310db0e
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00ad31a2d, 0xc03912f960, 0x55642a0, 0xc00175f940, 0xc0002d4240, 0xc001255b80, 0xc002388900, 0x558e760, 0xc0067537d0, 0xc0167d3560, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:621 +0x3a5 fp=0xc002735f60 sp=0xc002735e40 pc=0x33941e5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc002735f68 sp=0xc002735f60 pc=0x4b5a61
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:549 +0x17e

```

Found by RSG: https://teamcity.cockroachdb.com//viewLog.html?buildId=2516758&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests&tab=buildLog&_focus=9279#_state=9279

**Comment by jordanlewis** [comment]
Maybe this is a divide by zero?

**Comment by jordanlewis** [comment]
```
+++ b/pkg/geo/geomfn/distance_test.go
@@ -759,6 +759,7 @@ func TestFrechetDistanceDensify(t *testing.T) {
                {"LINESTRING (0 0, 3 7, 5 5)", "LINESTRING (0 0, 9 1, 2 2)", 0.6, pf(6.670832032063167)},
                {"LINESTRING (0 0, 3 7, 5 5)", "LINESTRING (0 0, 9 1, 2 2)", 0.8, pf(7.615773105863909)},
                {"LINESTRING (0 0, 3 7, 5 5)", "LINESTRING (0 0, 9 1, 2 2)", 1.0, pf(7.615773105863909)},
+               {"LINESTRING (0 0, 3 7, 5 5)", "LINESTRING (0 0, 9 1, 2 2)", 0.000000001, pf(7.615773105863909)},
        }

        for _, tc := range testCases {
```

This diff repros the issue (it panicked my machine, actually)... not for faint of heart.

**Comment by jordanlewis** [comment]
@erikgrinaker would you be able to take a look at this if you have a spare moment?

**Comment by erikgrinaker** [comment]
Yikes, thanks for the repro. If I remember correctly these functions should basically just pass the inputs through to GEOS itself, which the stack trace indicates too, but I'll have a look.

**Comment by erikgrinaker** [comment]
This crashes PostgreSQL too, fwiw:

```
test=# SELECT st_frechetdistance('LINESTRING (0 0, 3 7, 5 5)', 'LINESTRING (0 0, 9 1, 2 2)', 0.0001);
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

2020-12-14 19:49:24.320 CET [89197] LOG:  server process (PID 71066) was terminated by signal 11: Segmentation fault: 11
2020-12-14 19:49:24.320 CET [89197] DETAIL:  Failed process was running: SELECT st_frechetdistance('LINESTRING (0 0, 3 7, 5 5)', 'LINESTRING (0 0, 9 1, 2 2)', 0.0001);
```

Smaller densify parameters are exponentially more expensive to compute:

>The smaller densifyFrac we specify, the more acurate Fréchet distance we get. But, the computation time and the memory usage increase with the square of the number of subsegments.

I guess that's as expected, and not really a bug? Anything less than 0.001 is likely to be prohibitively expensive, maybe we need to constrain the generated inputs?

I'm not seeing any SIGFPE though, is it possible to get the the specific inputs that caused the panic?

**Comment by jordanlewis** [comment]
Unfortunately, the specific inputs seem not to have been preserved... I think the test is supposed to, but I can't find the logs anywhere.

Probably if you "fuzzed" the function you could find the issue, though. The test that found this issue randomly generates input for every SQL builtin function. You could re-run the test but constrain it to just this SQL builtin. The test is called `TestRandomSyntaxFunctions` and it lives in `pkg/sql/tests/rsg_test.go`.

As far as your point, I think that it's acceptable to provide functions that are prohibitively expensive with some inputs. But it's not acceptable to allow such functions to crash the server with SIGFPE or SIGSEGV, I'd consider the crash in Postgres a bug for them too.

**Comment by erikgrinaker** [comment]
>Unfortunately, the specific inputs seem not to have been preserved... I think the test is supposed to, but I can't find the logs anywhere.

Yeah, the logs had the random seed though (-1247787334609188706) so I'll try to rerun the test with that.

>As far as your point, I think that it's acceptable to provide functions that are prohibitively expensive with some inputs. But it's not acceptable to allow such functions to crash the server with SIGFPE or SIGSEGV, I'd consider the crash in Postgres a bug for them too.

Totally agree, I'll take it upstream once I've investigated the SIGFPE.

**Comment by jordanlewis** [comment]
```
demo@127.0.0.1:26257/defaultdb> SELECT st_frechetdistance('LINESTRING (0 0, 3 7, 5 5)', 'LINESTRING (0 0, 9 1, 2 2)', 0.0000000000000000000000001);
fatal error: unexpected signal during runtime execution
[signal SIGFPE: floating-point exception code=0x7 addr=0x187969df pc=0x187969df]

runtime stack:
runtime.throw(0x8261510, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x48c

goroutine 1804 [syscall]:
_ZN4geos9algorithm8distance23DiscreteFrechetDistance13getSegementAtERKNS_4geom18CoordinateSequenceEm
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x187969e0
_ZN4geos9algorithm8distance23DiscreteFrechetDistance17getFrecheDistanceERNSt3__16vectorINS4_INS1_17PointPairDistanceENS3_9allocatorIS5_EEEENS6_IS8_EEEEmmRKNS_4geom18CoordinateSequenceESF_
```

**Comment by erikgrinaker** [comment]
Heh, that was easy enough, thanks! I believe we can handle the `SIGFPE` and return an error, will prepare a PR for this tomorrow if it's not critical (been a long day).

**Comment by jordanlewis** [comment]
No strong rush!

**Comment by otan** [comment]
(if it's GEOS you should probably report to https://trac.osgeo.org/geos/report)

**Comment by erikgrinaker** [comment]
Submitted a PR that works around the `SIGFPE` in #57966, and verified that `ST_HausdorffDistance` doesn't have the same problem. I'm waiting for the OSGeo admins to give me a user account on the GEOS issue tracker, will submit an upstream issue then.

As for the `SIGSEGV`, that's just macOS' way of handling out-of-memory errors. On Linux, the OOM killer instead kills the process. I know we do memory accounting to prevent queries using too much memory in our own Go code, but is it possible to manage this with external linked C++ libraries at all?

**Comment by jordanlewis** [comment]
Gotcha, regarding `SIGSEGV` and OOM. That makes sense.

No, it's not possible to do memory accounting for external functions which we don't control. Our memory accounting is cooperative and by hand. When creating a buffer that needs to be accounted for, we explicitly increment a counter, and decrement that counter when the buffer is freed. We don't have any kind of custom allocator that could be sent to CGO here.

I think what we should do here is cap the precision for all geo functions that we know can use arbitrary amounts of memory. I suppose this will be a lot of work, but I don't have a better suggestion.

**Comment by erikgrinaker** [comment]
>I think what we should do here is cap the precision for all geo functions that we know can use arbitrary amounts of memory.

I think that's the only realistic mitigation we can do. However, it's going to be best-effort and a bit tricky, since available memory differs by environment (e.g. physical RAM and other processes) and some users may want the higher precision. Do we do any similar mitigation in other areas?

What's your take @otan?

**Comment by erikgrinaker** [comment]
Reported upstream: https://trac.osgeo.org/geos/ticket/1086
