### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#57940]
node crashed.  ubuntu x86_64. 
cockroachdb v20.2.2 Release.
3 nodes cluster run 11 days, and one node crashed.

An inability to maintain liveness will prevent a node from participating in a
cluster. If this problem persists, it may be a sign of resource starvation or
of network connectivity problems. For help troubleshooting, visit:

    https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html#node-liveness-issues

```
E201215 07:41:43.486769 687 jobs/registry.go:621 ⋮ error expiring job sessions: ‹expire-sessions›: ‹remote wall time is too far ahead (991.309885ms) to be trustworthy›
E201215 07:41:43.488028 687 jobs/registry.go:626 ⋮ failed to serve pause and cancel requests: could not query jobs table: ‹cancel/pause-requested›: ‹remote wall time is too far ahead (989.728915ms) to be trustworthy›
E201215 07:41:45.213680 231 kv/kvserver/replica_gossip.go:294 ⋮ [n1,s1,r1/1:‹/{Min-System/NodeL…}›] failed to gossip cluster ID: info not fresh
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/gossip.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:81
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) info not fresh
Error types: (1) *withstack.withStack (2) *errutil.leafError
E201215 07:41:47.463577 231 kv/kvserver/replica_gossip.go:294 ⋮ [n1,s1,r1/1:‹/{Min-System/NodeL…}›] failed to gossip cluster ID: info not fresh
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/gossip.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:81
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) info not fresh
Error types: (1) *withstack.withStack (2) *errutil.leafError
E201215 07:41:49.713664 231 kv/kvserver/replica_gossip.go:294 ⋮ [n1,s1,r1/1:‹/{Min-System/NodeL…}›] failed to gossip cluster ID: info not fresh
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/gossip.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:81
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) info not fresh
Error types: (1) *withstack.withStack (2) *errutil.leafError
W201215 07:41:49.954609 684 sql/stmtdiagnostics/statement_diagnostics.go:134 ⋮ [n1] error polling for statement diagnostics requests: ‹stmt-diag-poll›: ‹remote wall time is too far ahead (1.015703829s) to be trustworthy›
W201215 07:41:50.257657 622 server/node.go:785 ⋮ [n1,summaries] health alerts detected: ‹{Alerts:[{StoreID:0 Category:METRICS Description:liveness.heartbeatfailures Value:1}]}›
E201215 07:41:50.445375 689 jobs/registry.go:636 ⋮ error claiming jobs: could not query jobs table: ‹claim-jobs›: ‹remote wall time is too far ahead (1.062518399s) to be trustworthy›
E201215 07:41:50.446796 689 jobs/registry.go:646 ⋮ error processing claimed jobs: could query for claimed jobs: ‹select-running/get-claimed-jobs›: ‹remote wall time is too far ahead (1.061128077s) to be trustworthy›
W201215 07:41:51.484715 24991648 kv/txn.go:618 ⋮ [n1,s1,r606/1:‹/Table/16{2-3}›] failure aborting transaction: ‹remote wall time is too far ahead (848.411805ms) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (848.541204ms) to be trustworthy›
E201215 07:41:51.484896 24991648 kv/kvserver/replica_range_lease.go:383 ⋮ [n1,s1,r606/1:‹/Table/16{2-3}›] ‹remote wall time is too far ahead (848.541204ms) to be trustworthy›
I201215 07:41:51.665646 276 server/status/runtime.go:522 ⋮ [n1] runtime stats: 949 MiB RSS, 280 goroutines, 128 MiB/271 MiB/297 MiB GO alloc/idle/total, 332 MiB/440 MiB CGO alloc/total, 0.1 CGO/sec, 22.4/3.3 %(u/s)time, 0.0 %gc (1x), 294 KiB/1.1 MiB (r/w)net
E201215 07:41:51.963502 231 kv/kvserver/replica_gossip.go:294 ⋮ [n1,s1,r1/1:‹/{Min-System/NodeL…}›] failed to gossip cluster ID: info not fresh
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/gossip.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:81
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) info not fresh
Error types: (1) *withstack.withStack (2) *errutil.leafError
W201215 07:41:51.980064 278 kv/txn.go:618 ⋮ [n1,liveness-hb] failure aborting transaction: ‹remote wall time is too far ahead (1.067756238s) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (1.067875753s) to be trustworthy›
W201215 07:41:51.980231 278 kv/kvserver/node_liveness.go:650 ⋮ [n1,liveness-hb] failed node liveness heartbeat: ‹remote wall time is too far ahead (1.067875753s) to be trustworthy›
(1) ‹remote wall time is too far ahead (1.067875753s) to be trustworthy›
Error types: (1) *roachpb.internalError

An inability to maintain liveness will prevent a node from participating in a
cluster. If this problem persists, it may be a sign of resource starvation or
of network connectivity problems. For help troubleshooting, visit:

    https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html#node-liveness-issues

W201215 07:41:52.483504 24991770 kv/txn.go:618 ⋮ [n1,s1,r14/1:‹/Table/1{8-9}›] failure aborting transaction: ‹remote wall time is too far ahead (1.009811412s) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (1.009938807s) to be trustworthy›
E201215 07:41:52.483693 24991770 kv/kvserver/replica_range_lease.go:383 ⋮ [n1,s1,r14/1:‹/Table/1{8-9}›] ‹remote wall time is too far ahead (1.009938807s) to be trustworthy›
W201215 07:41:53.487756 24991817 kv/txn.go:618 ⋮ [n1,s1,r31/1:‹/Table/3{5-6}›] failure aborting transaction: ‹remote wall time is too far ahead (811.31416ms) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (811.447622ms) to be trustworthy›
E201215 07:41:53.487947 24991817 kv/kvserver/replica_range_lease.go:383 ⋮ [n1,s1,r31/1:‹/Table/3{5-6}›] ‹remote wall time is too far ahead (811.447622ms) to be trustworthy›
E201215 07:41:53.490032 687 jobs/registry.go:621 ⋮ error expiring job sessions: ‹expire-sessions›: ‹remote wall time is too far ahead (809.40312ms) to be trustworthy›
E201215 07:41:53.491109 687 jobs/registry.go:626 ⋮ failed to serve pause and cancel requests: could not query jobs table: ‹cancel/pause-requested›: ‹remote wall time is too far ahead (808.2097ms) to be trustworthy›
E201215 07:41:54.213477 231 kv/kvserver/replica_gossip.go:294 ⋮ [n1,s1,r1/1:‹/{Min-System/NodeL…}›] failed to gossip cluster ID: info not fresh
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/gossip.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:81
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) info not fresh
Error types: (1) *withstack.withStack (2) *errutil.leafError
W201215 07:41:54.484222 24991909 kv/txn.go:618 ⋮ [n1,s1,r275/1:‹/Table/1{37-53}›] failure aborting transaction: ‹remote wall time is too far ahead (1.05379283s) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (1.053913592s) to be trustworthy›
E201215 07:41:54.484392 24991909 kv/kvserver/replica_range_lease.go:383 ⋮ [n1,s1,r275/1:‹/Table/1{37-53}›] ‹remote wall time is too far ahead (1.053913592s) to be trustworthy›
W201215 07:41:55.317993 24991921 kv/txn.go:618 ⋮ [n1,s1,r6/1:‹/Table/{SystemCon…-11}›] failure aborting transaction: ‹remote wall time is too far ahead (921.293308ms) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (921.426237ms) to be trustworthy›
E201215 07:41:55.318159 24991921 kv/kvserver/replica_range_lease.go:383 ⋮ [n1,s1,r6/1:‹/Table/{SystemCon…-11}›] ‹remote wall time is too far ahead (921.426237ms) to be trustworthy›
W201215 07:41:55.484849 24991948 kv/txn.go:618 ⋮ [n1,s1,r20/1:‹/Table/2{4-5}›] failure aborting transaction: ‹remote wall time is too far ahead (927.752907ms) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (927.91438ms) to be trustworthy›
E201215 07:41:55.485066 24991948 kv/kvserver/replica_range_lease.go:383 ⋮ [n1,s1,r20/1:‹/Table/2{4-5}›] ‹remote wall time is too far ahead (927.91438ms) to be trustworthy›
W201215 07:41:55.678526 138 kv/kvserver/closedts/provider/provider.go:155 ⋮ [ct-closer] unable to move closed timestamp forward: not live
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/node_liveness.go:61
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) not live
Error types: (1) *withstack.withStack (2) *errutil.leafError
E201215 07:41:56.463549 231 kv/kvserver/replica_gossip.go:294 ⋮ [n1,s1,r1/1:‹/{Min-System/NodeL…}›] failed to gossip cluster ID: info not fresh
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/gossip.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:81
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) info not fresh
Error types: (1) *withstack.withStack (2) *errutil.leafError
W201215 07:41:56.481043 278 kv/txn.go:618 ⋮ [n1,liveness-hb] failure aborting transaction: ‹remote wall time is too far ahead (1.047247056s) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (1.048478928s) to be trustworthy›
W201215 07:41:56.481207 278 kv/kvserver/node_liveness.go:650 ⋮ [n1,liveness-hb] failed node liveness heartbeat: ‹remote wall time is too far ahead (1.048478928s) to be trustworthy›
(1) ‹remote wall time is too far ahead (1.048478928s) to be trustworthy›
Error types: (1) *roachpb.internalError

An inability to maintain liveness will prevent a node from participating in a
cluster. If this problem persists, it may be a sign of resource starvation or
of network connectivity problems. For help troubleshooting, visit:

    https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html#node-liveness-issues

W201215 07:41:58.124409 622 server/node.go:756 ⋮ [n1,summaries] error recording status summaries: ‹remote wall time is too far ahead (874.020536ms) to be trustworthy›
W201215 07:41:58.203540 277 ts/db.go:194 ⋮ [n1,ts-poll] error writing time series data: ‹remote wall time is too far ahead (1.058501849s) to be trustworthy›
E201215 07:41:58.713517 231 kv/kvserver/replica_gossip.go:294 ⋮ [n1,s1,r1/1:‹/{Min-System/NodeL…}›] failed to gossip cluster ID: info not fresh
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/gossip.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:81
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) info not fresh
Error types: (1) *withstack.withStack (2) *errutil.leafError
W201215 07:41:59.957545 684 sql/stmtdiagnostics/statement_diagnostics.go:134 ⋮ [n1] error polling for statement diagnostics requests: ‹stmt-diag-poll›: ‹remote wall time is too far ahead (1.060994328s) to be trustworthy›
W201215 07:42:00.263065 622 server/node.go:785 ⋮ [n1,summaries] health alerts detected: ‹{Alerts:[{StoreID:0 Category:METRICS Description:timeseries.write.errors Value:1} {StoreID:0 Category:METRICS Description:liveness.heartbeatfailures Value:2} {StoreID:1 Category:METRICS Description:ranges.underreplicated Value:106} {StoreID:1 Category:METRICS Description:ranges.unavailable Value:106}]}›
E201215 07:42:00.475614 608578 util/log/crash_reporting.go:321 ⋮ [n1] Queued as error ‹5b53afa5399d4eefbf6c215962a58b27›
E201215 07:42:00.475663 531 util/log/crash_reporting.go:321 ⋮ [n1] Queued as error ‹4e0c1335c7544f0e97318269820e6fac›
E201215 07:42:00.487095 608543 util/log/crash_reporting.go:321 ⋮ [n1] Queued as error ‹89a2e6a286a34ed2b9d6511ebed044cb›
E201215 07:42:00.491503 59777 util/log/crash_reporting.go:321 ⋮ [n1] Queued as error ‹4106960788014b1b959da2c9dda30df0›
E201215 07:42:00.491996 245 util/log/crash_reporting.go:321 ⋮ [n1] Queued as error ‹5f0f2252316e485cb27bf10e4b0cb0a5›
E201215 07:42:00.963377 231 kv/kvserver/replica_gossip.go:294 ⋮ [n1,s1,r1/1:‹/{Min-System/NodeL…}›] failed to gossip cluster ID: info not fresh
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/gossip.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:81
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) info not fresh
Error types: (1) *withstack.withStack (2) *errutil.leafError
W201215 07:42:00.979935 278 kv/txn.go:618 ⋮ [n1,liveness-hb] failure aborting transaction: ‹remote wall time is too far ahead (1.058897956s) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (1.058960131s) to be trustworthy›
W201215 07:42:00.980012 278 kv/kvserver/node_liveness.go:650 ⋮ [n1,liveness-hb] failed node liveness heartbeat: ‹remote wall time is too far ahead (1.058960131s) to be trustworthy›
(1) ‹remote wall time is too far ahead (1.058960131s) to be trustworthy›
Error types: (1) *roachpb.internalError

An inability to maintain liveness will prevent a node from participating in a
cluster. If this problem persists, it may be a sign of resource starvation or
of network connectivity problems. For help troubleshooting, visit:

    https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html#node-liveness-issues

I201215 07:42:01.665025 276 server/status/runtime.go:522 ⋮ [n1] runtime stats: 949 MiB RSS, 284 goroutines, 147 MiB/261 MiB/297 MiB GO alloc/idle/total, 332 MiB/440 MiB CGO alloc/total, 0.2 CGO/sec, 19.3/4.3 %(u/s)time, 0.0 %gc (0x), 392 KiB/804 KiB (r/w)net
W201215 07:42:02.486708 24992523 kv/txn.go:618 ⋮ [n1,s1,r506/1:‹/Table/161/1/"{N\xc9…-]\xe7…}›] failure aborting transaction: ‹remote wall time is too far ahead (1.055397408s) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (1.055517677s) to be trustworthy›
E201215 07:42:02.486884 24992523 kv/kvserver/replica_range_lease.go:339 ⋮ [n1,s1,r506/1:‹/Table/161/1/"{N\xc9…-]\xe7…}›] ‹remote wall time is too far ahead (1.055517677s) to be trustworthy›
E201215 07:42:03.213451 231 kv/kvserver/replica_gossip.go:294 ⋮ [n1,s1,r1/1:‹/{Min-System/NodeL…}›] failed to gossip cluster ID: info not fresh
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/gossip.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:81
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) info not fresh
Error types: (1) *withstack.withStack (2) *errutil.leafError
E201215 07:42:03.492564 687 jobs/registry.go:621 ⋮ error expiring job sessions: ‹expire-sessions›: ‹remote wall time is too far ahead (946.372329ms) to be trustworthy›
E201215 07:42:03.493667 687 jobs/registry.go:626 ⋮ failed to serve pause and cancel requests: could not query jobs table: ‹cancel/pause-requested›: ‹remote wall time is too far ahead (945.134844ms) to be trustworthy›
W201215 07:42:04.488490 24992674 kv/txn.go:618 ⋮ [n1,s1,r523/1:‹/Table/1{57-61}›] failure aborting transaction: ‹remote wall time is too far ahead (965.464886ms) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (965.595171ms) to be trustworthy›
E201215 07:42:04.488676 24992674 kv/kvserver/replica_range_lease.go:339 ⋮ [n1,s1,r523/1:‹/Table/1{57-61}›] ‹remote wall time is too far ahead (965.595171ms) to be trustworthy›
E201215 07:42:05.463537 231 kv/kvserver/replica_gossip.go:294 ⋮ [n1,s1,r1/1:‹/{Min-System/NodeL…}›] failed to gossip cluster ID: info not fresh
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/gossip.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:81
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) info not fresh
Error types: (1) *withstack.withStack (2) *errutil.leafError
I201215 07:42:05.472241 240 gossip/gossip.go:568 ⋮ [n1] gossip status (ok, 3 node‹s›)
gossip client (0/3 cur/max conns)
gossip server (2/3 cur/max conns, infos 6620440/1894958 sent/received, bytes 871210527B/310012887B sent/received)
  3: ‹10.91.26.226:26257› (262h31m23s)
  2: ‹10.91.26.227:26257› (262h31m31s)
W201215 07:42:05.482015 278 kv/txn.go:618 ⋮ [n1,liveness-hb] failure aborting transaction: ‹remote wall time is too far ahead (1.007008129s) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (1.007226791s) to be trustworthy›
W201215 07:42:05.482198 278 kv/kvserver/node_liveness.go:650 ⋮ [n1,liveness-hb] failed node liveness heartbeat: ‹remote wall time is too far ahead (1.007226791s) to be trustworthy›
(1) ‹remote wall time is too far ahead (1.007226791s) to be trustworthy›
Error types: (1) *roachpb.internalError

An inability to maintain liveness will prevent a node from participating in a
cluster. If this problem persists, it may be a sign of resource starvation or
of network connectivity problems. For help troubleshooting, visit:

    https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html#node-liveness-issues

W201215 07:42:05.487058 24992734 kv/txn.go:618 ⋮ [n1,s1,r17/1:‹/Table/2{1-2}›] failure aborting transaction: ‹remote wall time is too far ahead (1.001942449s) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (1.002052094s) to be trustworthy›
E201215 07:42:05.487204 24992734 kv/kvserver/replica_range_lease.go:339 ⋮ [n1,s1,r17/1:‹/Table/2{1-2}›] ‹remote wall time is too far ahead (1.002052094s) to be trustworthy›
E201215 07:42:06.485538 24992804 kv/kvserver/queue.go:1087 ⋮ [n1,raftlog,s1,r7/1:‹/Table/1{1-2}›] ‹remote wall time is too far ahead (1.02242703s) to be trustworthy›
W201215 07:42:06.488346 24992796 kv/txn.go:618 ⋮ [n1,s1,r7/1:‹/Table/1{1-2}›] failure aborting transaction: ‹remote wall time is too far ahead (1.019603067s) to be trustworthy›; abort caused by: ‹remote wall time is too far ahead (1.01974792s) to be trustworthy›
E201215 07:42:06.488502 24992796 kv/kvserver/replica_range_lease.go:339 ⋮ [n1,s1,r7/1:‹/Table/1{1-2}›] ‹remote wall time is too far ahead (1.01974792s) to be trustworthy›
F201215 07:42:07.455326 608578 server/server.go:275 ⋮ [n1] clock synchronization error: this node is more than 500ms away from at least half of the known nodes (1 of 3 are within the offset)
goroutine 608578 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x964b900, 0x78ea26, 0xc00142b3a8, 0x78ea26)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb8
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0x964ab00, 0x4, 0x1650d3f79f5d12f2, 0x94942, 0x88bcff1, 0x10, 0x113, 0xc0011f45a0, 0x83, 0xc003437a88, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:241 +0xa02
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x62e01e0, 0xc000c7a150, 0xc000000004, 0x2, 0x51d73fc, 0x2, 0xc00142b9f0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:52 +0x1ac
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x62e01e0, 0xc000c7a150, 0x1, 0x4, 0x51d73fc, 0x2, 0xc00142b9f0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:44 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:165
github.com/cockroachdb/cockroach/pkg/server.NewServer.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:275 +0xd2
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat.func3(0x62e0120, 0xc000ad21c0, 0xd, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1202 +0x582
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc000bfc000, 0x62e0120, 0xc000ad21c0, 0x51f5a09, 0xd, 0xc00142bd68, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:326 +0x140
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc000072480, 0xc0066ebc20, 0xc002acb4a0, 0x12, 0xc004f73740, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1132 +0x45a
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).grpcDialNodeInternal.func1.1.1(0x62e01e0, 0xc003409f80)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1058 +0x79
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc005dfe0d0, 0xc000bfc000, 0xc0066ebd10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:222 +0x13d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xa8

For more context, check log files in: /home/eco/cockroach/dblog


****************************************************************************

This node experienced a fatal error (printed above), and as a result the
process is terminating.

Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
problem in CockroachDB. With your help, the support team at Cockroach Labs
will try to determine the root cause, recommend next steps, and we can
improve CockroachDB based on your report.

Please submit a crash report by following the instructions here:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.
```

**Comment by nvanbenschoten** [comment]
Hi @carr123, what you're seeing here is a coordinated shutdown due to CRDB detecting that the clocks within your cluster are not well synchronized. We have some more details on this in https://www.cockroachlabs.com/docs/v20.2/common-errors.html#clock-synchronization-error-this-node-is-more-than-500ms-away-from-at-least-half-of-the-known-nodes. Are you running an NTP or Chrony service on this cluster?

**Comment by carr123** [comment]
@nvanbenschoten hello, yes, NTP tool indeed installed on the 3 nodes cluster, and i run ntpdate command manually on each node before starting CRDB.
this is not the first time i see one node crash due to time synchronization, few months ago, crdb version 19.2 encounter the same problem.  my cluster deployed on premise in a local testing server group.

**Comment by mwang1026** [comment]
We're closing this because of inactivity and 19.2 no longer being a supported version. If you want to reopen the ticket with new info feel free. Thanks
