### ISSUE TITLE
roachtest: acceptance/version-upgrade failure

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#58017]
In [this CI run](https://teamcity.cockroachdb.com/viewLog.html?buildId=2525418&buildTypeId=Cockroach_UnitTests), I saw the following seg fault:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12a2516]

goroutine 40 [running]:
panic(0x1e35b60, 0x519d690)
	/usr/local/go/src/runtime/panic.go:1064 +0x545 fp=0xc000deb758 sp=0xc000deb690 pc=0x4504a5
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:212
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:742 +0x413 fp=0xc000deb788 sp=0xc000deb758 pc=0x467073
github.com/cockroachdb/cockroach/pkg/sql/types.(*T).Family(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/types/types.go:1124
github.com/cockroachdb/cockroach/pkg/sql/types.(*T).Equivalent(0xc0002109c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/types/types.go:1752 +0x36 fp=0xc000deb7d0 sp=0xc000deb788 pc=0x12a2516
github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*operationGenerator).setColumnDefault(0xc000eede90, 0xc000dae750, 0x18, 0xc0003730a8, 0xc, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:1395 +0x2ab fp=0xc000deb960 sp=0xc000deb7d0 pc=0x187878b
github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*operationGenerator).randOp(0xc000eede90, 0xc000dae750, 0x1, 0x5, 0x0, 0x7fbcf46fc1f8, 0x20, 0x28)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:230 +0x20b fp=0xc000deba78 sp=0xc000deb960 pc=0x186e52b
github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn(0xc000eedef0, 0xc000dae750, 0x0, 0x0, 0xc000dae750, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:239 +0xff fp=0xc000debc38 sp=0xc000deba78 pc=0x18826ff
github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run(0xc000eedef0, 0x3fc7c80, 0xc000eeeec0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:322 +0x125 fp=0xc000debea8 sp=0xc000debc38 pc=0x1883d05
github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run-fm(0x3fc7c80, 0xc000eeeec0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:313 +0x3e fp=0xc000debee0 sp=0xc000debea8 pc=0x18871de
github.com/cockroachdb/cockroach/pkg/workload/cli.workerRun(0x3fc7c80, 0xc000eeeec0, 0xc0002f6c00, 0xc0003c37c0, 0x0, 0xc0007a31d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:237 +0xaf fp=0xc000debf58 sp=0xc000debee0 pc=0x13f432f
github.com/cockroachdb/cockroach/pkg/workload/cli.runRun.func2.1(0xc0006f6000, 0xc0003dc080, 0xc0002f6c00, 0x0, 0x3fc7c80, 0xc000eeeec0, 0xc0003c37c0, 0x0, 0xc0007a31d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:426 +0xec fp=0xc000debf98 sp=0xc000debf58 pc=0x13f82cc
```
This occurred when running the `schemachange` workload:
```
run_041420.658_n1_workload_run_schemachange: 04:14:20 cluster.go:386: > /go/src/github.com/cockroachdb/cockroach/bin/roachprod run local:1 -- ./workload run schemachange --verbose=1 --tolerate-errors=true --max-ops 10 --concurrency 2 {pgurl:1-4}
```
cc @jayshrivastava, since I think you're the one working most closely in this area these days.

**Comment by jayshrivastava** [comment]
Ack. Looking into it.

**Comment by jayshrivastava** [comment]
This issue also occurs in https://github.com/cockroachdb/cockroach/issues/58007 and here https://github.com/cockroachdb/cockroach/pull/58014#issuecomment-747458408. I can repro it as well. The root cause is essentially that we assume a column name is new/unique, and this assumption is incorrect. My repro involves this path:
1. A table 1 gets created with columns `col1_1, col1_2, col1_3` etc. We do not tell the workload that the sequence numbers `1,2,3` have been used.
2. We try to intentionally cause an error by altering the type of a column that does not exist. This requires first fetching a column that does not exist. From the perspective of the workload, the sequence numbers `1,2,3` have not been used, so it may return one of the column names in step 1 while assuming the column name is unique compared to any column names in the db. This assumption leads to a seg fault in code.

The solution here is to update the `createTable` operation to atomically increment the global sequence number when naming columns.
