### ISSUE TITLE
SQL Client: panic on DELETE statement 

### ISSUE THREAD

**Issue by dacamp** [cockroachdb/cockroach#5808]
I've been experimenting with CockroachDB running three nodes locally, so the answers below apply to all nodes.

1) What version of CockroachDB are you using (`cockroach version`)?

```
$ cockroach version
Build Tag:   beta-20160331-15-gee7c859
Build Time:  2016/03/31 21:12:53
Platform:    darwin amd64
Go Version:  go1.6
C Compiler:  4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)
```

```
$ ./cockroach start --insecure &
build:     beta-20160331-15-gee7c859 @ 2016/03/31 21:12:53 (go1.6)
admin:     http://DCam-MBP-3.local:8080
sql:       postgresql://root@DCam-MBP-3.local:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
```
I'm on master commit ee7c859 built locally with `make build`

2) What operating system and processor architecture are you using?
OS X 10.11.4
```
$ uname -a
Darwin DCam-MBP-3.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

3) What flags/environment variables did you pass to `cockroach start`?
```
  650  ./cockroach start --insecure &
  651  ./cockroach start --insecure --store=cockroach-data2 --port=26258 --http-port=8081 --join=localhost:26257 &
  654  ./cockroach start --insecure --store=cockroach-data3 --port=26259 --http-port=8082 --join=localhost:26257 &
  655  ./cockroach sql --insecure
```

Please describe the issue you observed:

1) What did you do?

Execute a DELETE statement from the built-in SQL client:

```
root@:26257> SET DATABASE = testdb;
SET
root@:26257> SHOW COLUMNS FROM clusters;
+------------------+-------------+-------+-----------------------+
|      Field       |    Type     | Null  |        Default        |
+------------------+-------------+-------+-----------------------+
| uuid             | BYTES       | false | NULL                  |
| owner            | STRING(128) | false | NULL                  |
| created_at       | TIMESTAMP   | false | "CURRENT_TIMESTAMP"() |
| name             | STRING(128) | false | NULL                  |
+------------------+-------------+-------+-----------------------+
root@:26257> SHOW INDEX FROM clusters;
+----------+-------------------+--------+-----+--------+-----------+---------+
|  Table   |       Name        | Unique | Seq | Column | Direction | Storing |
+----------+-------------------+--------+-----+--------+-----------+---------+
| clusters | primary           | true   |   1 | uuid   | ASC       | false   |
| clusters | clusters_name_key | true   |   1 | name   | ASC       | false   |
+----------+-------------------+--------+-----+--------+-----------+---------+
root@:26257> SELECT * FROM clusters WHERE name = 'asdasd';
+-------------------------------------------+---------------+-------------------------------------------+--------+
|                   uuid                    |     owner     |                created_at                 |  name  |
+-------------------------------------------+---------------+-------------------------------------------+--------+
| "O\xf7o%V\x9f\xb7\u068c[7\xeaG\xba\x18\t" | dcam@foo.com | 2016-03-31 22:37:48.795197683 +0000 +0000 | asdasd |
+-------------------------------------------+---------------+-------------------------------------------+--------+
root@:26257> DELETE FROM "clusters"  WHERE "clusters"."name" = 'asdasd';
driver: bad connection
root@:26257> panic: interface conversion: sql.planNode is *sql.indexJoinNode, not *sql.scanNode
```
I also tried different syntax and even a different table without success:
```
root@:26257> DELETE FROM clusters  WHERE clusters.name = 'asdasd';
driver: bad connection
root@:26257> panic: interface conversion: sql.planNode is *sql.indexJoinNode, not *sql.scanNode
[...]
root@:26257> DELETE FROM users WHERE email = 'asfasdsad@foo.com';
driver: bad connection
root@:26257> panic: interface conversion: sql.planNode is *sql.indexJoinNode, not *sql.scanNode
[...]
```

Once the panic was observed, I was still connected to the SQL client, but was unable to execute any further commands.
```
root@:26257> DELETE FROM clusters  WHERE name = 'asdasd';
driver: bad connection
root@:26257> panic: interface conversion: sql.planNode is *sql.indexJoinNode, not *sql.scanNode
root@:26257> DELETE FROM clusters  WHERE name = 'asdasd';
dial tcp [::1]:26257: getsockopt: connection refused
```

After exiting and restarting the node with ` ./cockroach start --insecure &`, I could reconnect as expected.

No other statements cause panic.  I've tested `ALTER TABLE`,  `CREATE DATABASE`, `CREATE INDEX`, `CREATE TABLE`, `DROP DATABASE`, `DROP TABLE`, `INSERT`, `RENAME COLUMN`, `SELECT`, `SET DATABASE`, `SHOW COLUMNS`, `SHOW DATABASES`, `SHOW TABLES`, 
and `UPDATE` successfully from the CLI.

2) What did you expect to see?

A successful transaction.  Using the golang postgres client (via GORM) and enabling debug mode showed a successful DELETE on the same table.

```(/Users/dcam/golang/src/foo/bar/blah/models/cluster.go:118)
[2016-04-01 10:13:21]  [3.11ms]  DELETE FROM "clusters"  WHERE "clusters"."uuid" = '{c72e0219-272f-43fb-8163-a32d249d9ddb true}'
```

3) What did you see instead?
```
root@:26257> DELETE FROM "clusters"  WHERE "clusters"."name" = 'asdasd';
driver: bad connection
root@:26257> panic: interface conversion: sql.planNode is *sql.indexJoinNode, not *sql.scanNode

goroutine 2762 [running]:
panic(0x50d60e0, 0xc8208c8280)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql.(*planner).Delete(0xc820588878, 0xc82136cae0, 0x88eff801, 0x0, 0x0, 0xc8204bc000)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/delete.go:57 +0x15e7
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc820588878, 0x6eabdb0, 0xc82136cae0, 0xc820c82c01, 0x0, 0x0, 0x7582e20ac)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/plan.go:208 +0x889
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc8201562a0, 0x6eabdb0, 0xc82136cae0, 0xc820588878, 0xece90a368, 0xc812163e51, 0x5d6e3c0, 0x1, 0x0, 0x0, ...)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/executor.go:874 +0x89
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInOpenTxn(0xc8201562a0, 0x6eabdb0, 0xc82136cae0, 0xc820588878, 0x101, 0x14414b94b4b023c0, 0x0, 0xc820588828, 0x0, 0x0, ...)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/executor.go:778 +0x58d
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc8201562a0, 0xc821aa3230, 0x1, 0x1, 0xc820588878, 0xc820588828, 0x1e0101, 0x0, 0x0, 0x0, ...)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/executor.go:556 +0x630
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc8201562a0, 0xc820588878, 0x1, 0xc820588828, 0xc820ceb560, 0xc821aa3230, 0x1, 0x1, 0xc8211d53a0, 0xc8211d53b8, ...)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/executor.go:488 +0x147
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func1(0xc82019a2c0, 0xc820ceb560, 0x4)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/executor.go:401 +0x325
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc82019a2c0, 0x5320101, 0x14414b94b4afe596, 0x0, 0xc8211d54f8, 0x0)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/client/txn.go:531 +0x410
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc8201562a0, 0x6e9f7d0, 0xc8207713c0, 0xc820588800, 0xc8205c903b, 0x3b, 0x0, 0x0, 0x0, 0x7a11100)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/executor.go:405 +0x892
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8201562a0, 0x6e9f7d0, 0xc8207713c0, 0xc820588800, 0xc8205c903b, 0x3b, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/executor.go:295 +0xe2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc820567200, 0x6e9f7d0, 0xc8207713c0, 0xc8205c903b, 0x3b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:604 +0xb2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc820567200, 0x6e9f7d0, 0xc8207713c0, 0xc820567228, 0x0, 0x0)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:314 +0xf2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc820567200, 0x0, 0x0, 0x0)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:270 +0x10d3
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc8203c41d8, 0x7a81e38, 0xc8200f6420, 0x0, 0x0)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:159 +0x929
github.com/cockroachdb/cockroach/server.(*Server).Start.func4.1(0x7a81e38, 0xc8200f6420)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/server/server.go:300 +0x4b
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc820130180, 0x7a81e38, 0xc8200f6420, 0xc82030e010)
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/util/net.go:125 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/Users/dcam/golang/src/github.com/cockroachdb/cockroach/util/net.go:127 +0x31f
```

**Comment by dacamp** [comment]
If I can provide any additional information, LMK.

**Comment by petermattis** [comment]
Thanks for the detailed bug report.
