### ISSUE TITLE
roachtest: acceptance/version-upgrade failed: invalid attempted write of database descriptor

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#58307]
While bumping Pebble in the release-20.2 branch, my PR #58304 hit this roachtest failure that appears to be unrelated to the change: 

```
I201228 16:35:06.841433 201 server/server.go:1119 â‹® active cluster version is now 20.2 (up from 20.1)
I201228 16:35:08.772686 793 sql/sqlliveness/slstorage/slstorage.go:342 â‹® [n2] inserted sqlliveness session â€¹a418c755aebf4c96b7bbefa64d909a9bâ€º
I201228 16:35:08.772738 793 sql/sqlliveness/slinstance/slinstance.go:143 â‹® [n2] created new SQL liveness session â€¹a418c755aebf4c96b7bbefa64d909a9bâ€º
I201228 16:35:08.777500 5035 sql/table.go:102 â‹® [n2,client=â€¹127.0.0.1:58956â€º,hostnossl,user=root] queued new database schema change job 619652411466579970 for database 162
F201228 16:35:08.777559 5035 sql/database.go:112 â‹® [n2,client=â€¹127.0.0.1:58956â€º,hostnossl,user=root] invalid attempted write of database descriptor
goroutine 5035 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x95a7701, 0x742236, 0xc00130eb80, 0x20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb8
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0x95a69a0, 0x4, 0x1654ee993bb9f652, 0x13ab, 0x874e1bf, 0xf, 0x70, 0xc0021cc750, 0x2e, 0xc00086eac0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:243 +0x9e5
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x618ba80, 0xc002726400, 0x4, 0x2, 0x512df6f, 0x2e, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:52 +0x1ac
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x618ba80, 0xc002726400, 0x1, 0xc000000004, 0x512df6f, 0x2e, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:44 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:173
github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeDatabaseChangeToBatch(0xc001e9b418, 0x618ba80, 0xc002726400, 0xc0029f7980, 0xc000f9e000, 0x4e, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/database.go:112 +0x13f
github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeNonDropDatabaseChange(0xc001e9b418, 0x618ba80, 0xc002726400, 0xc0029f7980, 0xc0009453b0, 0x4e, 0x4e, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/database.go:99 +0xeb
github.com/cockroachdb/cockroach/pkg/sql.(*planner).createUserDefinedSchema(0xc001e9b418, 0x618ba80, 0xc002726400, 0xc001f47340, 0xc001e9b418, 0xc00169f230, 0x7b5601, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/create_schema.go:136 +0x83f
github.com/cockroachdb/cockroach/pkg/sql.(*createSchemaNode).startExec(0xc001a69f08, 0x618ba80, 0xc002726400, 0xc001f47340, 0xc001e9b418, 0xc001c35300, 0x2749212)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/create_schema.go:36 +0x5b
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x5092b12, 0xd, 0x618d900, 0xc001a69f08, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:506 +0xb9
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc0027996e8, 0x5092b12, 0xd, 0x618d900, 0xc001a69f08)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:119 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc001c356e8, 0x618d900, 0xc001a69f08, 0x5092b12, 0xd)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:298 +0xbf
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc001c356e8, 0x618d900, 0xc001a69f08, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:86 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:50
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x618ba80, 0xc002726400, 0xc001f47340, 0xc001e9b418, 0x618d900, 0xc001a69f08, 0x0, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:509 +0x11f
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc000f9ef00, 0x618ba80, 0xc002726400, 0x95f4e20, 0x48a1840)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:125 +0xd6
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run(0xc000f9ef00, 0x618ba80, 0xc002726400)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:774 +0x52
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc0019c6c60, 0x618ba80, 0xc002726400, 0x567fc80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:392 +0x24d
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0008914a0, 0xc0008477a0, 0xc001934a20, 0xc002a2ec00, 0xc00012ea80, 0xc001e9b518, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:422 +0x5d9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc0008914a0, 0x618bb40, 0xc00169f290, 0xc001e9b518, 0xc0008477a0, 0xc001934a20, 0x618d900, 0xc001a69f08, 0x0, 0xc00012ea80, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1002 +0x1d1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001e9b000, 0x618bb40, 0xc00169f290, 0xc001e9b418, 0x1, 0x7f277540da78, 0xc001fda680, 0xc001c36100, 0xc000910ef8, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1001 +0x3c0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001e9b000, 0x618bb40, 0xc00169f290, 0xc001e9b418, 0x7f277540da78, 0xc001fda680, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:872 +0x6ff
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001e9b000, 0x618bb40, 0xc00169f290, 0x61a9440, 0xc00169f230, 0xc002ca63b5, 0x24, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:639 +0xbb1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001e9b000, 0x618bb40, 0xc00169f290, 0x61a9440, 0xc00169f230, 0xc002ca63b5, 0x24, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:114 +0x924
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0x61a9440, 0xc00169f230, 0xc002ca63b5, 0x24, 0x0, 0x0, 0x362d543f, 0xed77c003a, 0x0, 0x362d5cb9, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1465 +0x2d5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc001e9b000, 0x618ba80, 0xc002726340, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1467 +0x148d
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001e9b000, 0x618ba80, 0xc002c8a080, 0xc000e34fa0, 0x5400, 0x15000, 0xc000e35040, 0xc002c82090, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1391 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0010b4680, 0x618ba80, 0xc002c8a080, 0xc001e9b000, 0x5400, 0x15000, 0xc000e35040, 0xc002c82090, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:508 +0x104
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc0026a003e, 0xc002a82080, 0x618ba80, 0xc002c8a080, 0xc002c82090, 0xc0010b4680, 0xc001fda000, 0x61bb380, 0xc0023cc330, 0xc00275a3c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:626 +0x317
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:554 +0x17e
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=2547260&buildTypeId=Cockroach_UnitTests_Roachtest&tab=buildResultsDiv

**Comment by ajwerner** [comment]
Yikes, the version switch happens mid-statement and we hit the panic.

**Comment by ajwerner** [comment]
Easy enough to fix. The defensive check doesn't seem super important.

**Comment by ajwerner** [comment]
Ah yeah so we're not doing the gate check for user defined schemas properly. I think the window for this crash is very small but it's still worthy of a fix.

**Comment by yuzefovich** [comment]
Hit an instance of this in the wild #59752.

**Comment by andreimatei** [comment]
Happened again at the tip of release-20.2:
https://teamcity.cockroachdb.com/viewLog.html?buildId=2800079&buildTypeId=Cockroach_UnitTests

@postamar did you look into this at all?
Sounds likely easy to repro since we've had all these reports from `acceptance/version-upgrade`. You can stress this roachtest locally - I can show you how if you want.

**Comment by postamar** [comment]
No I haven't, it was in our backlog. That being said if it's a low-hanging fruit I'll take a look ASAP.

**Comment by ajwerner** [comment]
This is low-hanging fruit for the 20.1->20.2 upgrade. We've got a problem with how we check the gate on User Defined Schemas. That being said, it's a transient error that is not super common to come up so we deprioritized it.
