### ISSUE TITLE
various acceptance tests fail in docker with "unexpected extra event"

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#58955]
```
    dockercluster.go:683: unexpected extra event &{0 die} (after [])
```

TestDockerJava: https://github.com/cockroachdb/cockroach/issues/58951
TestDockerPSQL: https://github.com/cockroachdb/cockroach/issues/58488
TestDockerNodeJS: https://github.com/cockroachdb/cockroach/issues/58353
TestDockerCSharp: https://github.com/cockroachdb/cockroach/pull/58706

**Comment by RaduBerinde** [comment]
CC @knz Not sure who can help with this.

**Comment by knz** [comment]
I think this is really for dev-inf. Since there are no changes in this code, any behavioral change are a combination of:

- changes to the acceptance runner image (`cockroachdb/acceptance`)
- changes to the version of `docker` running on the TC agents

@kenliu can you route this? It seems to affect v20.2 only.

**Comment by RaduBerinde** [comment]
It affects both 20.2 and master.

**Comment by kenliu** [comment]
we'll take a look at it next Tuesday

**Comment by RaduBerinde** [comment]
I am seeing the same failure mode on master:
https://teamcity.cockroachdb.com//viewLog.html?buildId=2595789&buildTypeId=Cockroach_MergeToMaster&tab=buildResultsDiv&branch_Cockroach=50453

**Comment by RaduBerinde** [comment]
Opened a PR to skip all these tests for now.

**Comment by rickystewart** [comment]
My investigation here hasn't turned up anything interesting. I haven't found that the new Docker we've upgraded to is deficient in any way -- we're using Docker for a lot of our builds and tests, and there doesn't appear to be a trend of general Docker flakiness. Since the problem is isolated to this one branch for this one test, I'm more inclined to believe that the Docker glue code that we have in `pkg/acceptance/cluster` has become incompatible in some way with the latest implementation of the Docker API.

My proposal is that we re-enable the flaky tests and augment `dockercluster.go` to add some extra logging where we [process events form Docker](https://github.com/cockroachdb/cockroach/blob/4516f636b55c79643e06158a551b33efa60ab683/pkg/acceptance/cluster/dockercluster.go#L537). My hope is that if we log every event that Docker sends us, then we can put together a stronger hypothesis about what the cause of the failure is. I'll probably have to work with someone who's knowledgeable about the `acceptance` tests to clarify about how the glue code is supposed to work. Any thoughts?

**Comment by knz** [comment]
I'm all for the additional logging.
As to how the infrastructure works here, the experts are @tbg and @bdarnell .

**Comment by RaduBerinde** [comment]
> Since the problem is isolated to this one branch 

The problem was seen on 20.2 and master..

Reenabling with additional logging sounds like a good plan.

**Comment by tbg** [comment]
I don't think this is a docker problem. Look at the cockroach logs from these failures, taken from https://teamcity.cockroachdb.com/viewLog.html?buildId=2650123&buildTypeId=Cockroach_UnitTests_Acceptance&tab=artifacts&branch_Cockroach_UnitTests=%3Cdefault%3E#%2Facceptance%2FTestDockerJava%2FrunMode%3Ddocker

```
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3  000006.log:
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 +orig err: open â€¹/data0.0/000006.logâ€º: no such file or directory
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 +list err: readdirent: no such file or directory
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !goroutine 260 [running]:
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x8170900, 0x203000, 0x203000, 0x7f892f0bd998)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb9
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000eaf280, 0xc0025ab4a0, 0x24, 0x1, 0x0, 0x0, 0x0, 0x16610602dd2562ba, 0x400000000, 0x3, ...)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:277 +0xc67
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x5650740, 0xc000e7d650, 0x2, 0x300000004, 0x4969015, 0x1d, 0xc002b68390, 0x3, 0x3)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:58 +0x198
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/util/log.loggerStorage.FatalfDepth(...)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:2022
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/storage.pebbleLogger.Fatalf(...)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble.go:401
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/pebble/internal/base.MustExist(0x5794980, 0xc000d9d800, 0xc00231baa0, 0x13, 0x7f892f0c4000, 0xc000d9d8e0, 0x55b7de0, 0xc002865260)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 +0x6a8
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/pebble.(*DB).makeRoomForWrite(0xc000600800, 0xc001776960, 0x18115, 0x20000)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:1419 +0x110f
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/pebble.(*DB).commitWrite(0xc000600800, 0xc001776960, 0xc001776a20, 0xc001776a30, 0xc000381b40, 0xc001776960, 0xc000381b40)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:640 +0xc5
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/pebble.(*commitPipeline).prepare(0xc000381300, 0xc001776960, 0xc002518101, 0xb, 0xb, 0x0)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/commit.go:377 +0x175
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/pebble.(*commitPipeline).Commit(0xc000381300, 0xc001776960, 0x1, 0x0, 0xc0016d52a8)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/commit.go:253 +0x73
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/pebble.(*DB).Apply(0xc000600800, 0xc001776960, 0x77f9a96, 0xed7afeeee, 0x0)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:568 +0x111
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/pebble.(*Batch).Commit(...)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/batch.go:732
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit(0xc001d8fc00, 0xed7afee01, 0x0, 0x5650740)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:470 +0x5e
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked(0xc000b4c800, 0x5650740, 0xc001cd7590, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:710 +0xaca
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady(0xc000b4c800, 0x5650740, 0xc001cd7590, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:434 +0x110
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc00039f500, 0x5650740, 0xc0015cfb30, 0x4)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:523 +0x134
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker(0xc001620aa0, 0x5650740, 0xc0015cfb30)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:284 +0x2c2
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc00070ea80, 0x5650740, 0xc0015cfb30, 0xc000ecb0c0, 0xc000640880)
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:352 +0xb9
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0xfc
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !For more context, check log files in: /logs/roach-767e5b6c-0
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !****************************************************************************
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !This node experienced a fatal error (printed above), and as a result the
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !process is terminating.
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !problem in CockroachDB. With your help, the support team at Cockroach Labs
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !will try to determine the root cause, recommend next steps, and we can
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !improve CockroachDB based on your report.
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !Please submit a crash report by following the instructions here:
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !    https://github.com/cockroachdb/cockroach/issues/new/choose
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !If you would rather not post publicly, please contact us directly at:
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !    support@cockroachlabs.com
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !
F210206 01:59:10.945264 260 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 3 !The Cockroach Labs team appreciates your feedback.

```

**Comment by tbg** [comment]
If anything, the problem could be that for some reason we're janking out files out from under a running process. Or, of course, pebble has some bug.

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/blob/05efcbd5eab35d291e1e196f46c5092e24d0cfd3/pkg/acceptance/cluster/dockercluster.go#L244

Is this right? Shouldn't this be `WaitConditionNextExit`?

```
// Possible WaitCondition Values.
//
// WaitConditionNotRunning (default) is used to wait for any of the non-running
// states: "created", "exited", "dead", "removing", or "removed".
//
// WaitConditionNextExit is used to wait for the next time the state changes
// to a non-running state. If the state is currently "created" or "exited",
// this would cause Wait() to block until either the container runs and exits
// or is removed.
//
// WaitConditionRemoved is used to wait for the container to be removed.
const (
	WaitConditionNotRunning WaitCondition = "not-running"
	WaitConditionNextExit   WaitCondition = "next-exit"
	WaitConditionRemoved    WaitCondition = "removed"
)

```

Perhaps for some reason we now sometimes race the calls to `Start` and `Wait` in the wrong order, so we will return from `Wait` on container creation rather than the container having finished running. We will then nuke some files too early:

https://github.com/cockroachdb/cockroach/blob/35095d919220724f97039d5921318d032a74661e/pkg/acceptance/util_docker.go#L91-L95

**Comment by tbg** [comment]
FYI there's another one here:

https://github.com/cockroachdb/cockroach/blob/05efcbd5eab35d291e1e196f46c5092e24d0cfd3/pkg/acceptance/cluster/dockercluster.go#L380

**Comment by rickystewart** [comment]
acceptance tests look pretty healthy now -- I can't find an instance of a failure since @tbg's patch went in. I'm closing this.

**Comment by tbg** [comment]
Wohoo!

**Comment by rafiss** [comment]
It seems like TestDockerJava failed with the same symptom today. https://github.com/cockroachdb/cockroach/issues/58951#issuecomment-791521889

**Comment by tbg** [comment]
Confirmed, I looked at the logs

```
210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5  000006.log:
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 +orig err: open â€¹/data0.0/000006.logâ€º: no such file or directory
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 +list err: readdirent: no such file or directory
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !goroutine 226 [running]:
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x857ec00, 0x203000, 0x203000, 0x7f598b27d778)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb9
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc0005fa7a0, 0xc0004862d0, 0x24, 0x1, 0x0, 0x0, 0x0, 0x16697dcf45d3bb45, 0x400000000, 0x3, ...)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:277 +0xc67
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x595e0a0, 0xc0007d8f90, 0x2, 0x300000004, 0x4b7f40d, 0x1d, 0xc0039aaae0, 0x3, 0x3)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:58 +0x198
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/util/log.loggerStorage.FatalfDepth(...)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:2022
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/storage.pebbleLogger.Fatalf(...)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble.go:402
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/pebble/internal/base.MustExist(0x5aa6280, 0xc000b36000, 0xc00390be40, 0x13, 0x7f5988f282d8, 0xc000b36160, 0x58c16c0, 0xc002b6d3c0)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 +0x6a8
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/pebble.(*DB).makeRoomForWrite(0xc000680800, 0xc00251a3c0, 0x8f0b, 0x10000)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:1419 +0x110f
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/pebble.(*DB).commitWrite(0xc000680800, 0xc00251a3c0, 0xc00251a480, 0xc00251a490, 0xc00173cd80, 0xc00251a3c0, 0xc00173cd80)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:640 +0xc5
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/pebble.(*commitPipeline).prepare(0xc00173c000, 0xc00251a3c0, 0xc001234701, 0xb, 0xb, 0x0)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/commit.go:377 +0x175
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/pebble.(*commitPipeline).Commit(0xc00173c000, 0xc00251a3c0, 0x1, 0x0, 0xc0023452a8)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/commit.go:253 +0x73
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/pebble.(*DB).Apply(0xc000680800, 0xc00251a3c0, 0x7bb1558, 0xed7d44d8e, 0x0)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:568 +0x111
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/pebble.(*Batch).Commit(...)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/batch.go:732
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit(0xc002af5200, 0xed7d44d01, 0x0, 0x595e0a0)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:493 +0x5e
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked(0xc0011afb00, 0x595e0a0, 0xc000afacc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:736 +0xaea
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady(0xc0011afb00, 0x595e0a0, 0xc000afacc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:459 +0x110
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc00145fc00, 0x595e0a0, 0xc000f23290, 0x3)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:523 +0x134
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker(0xc00133e0a0, 0x595e0a0, 0xc000f23290)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:284 +0x2c2
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc000a76600, 0x595e0a0, 0xc000f23290, 0xc000f187c0, 0xc001226230)
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0xb9
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0xfc
F210305 16:04:30.572239 226 3@vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 â‹® [n1,pebble] 5 !

**Comment by rickystewart** [comment]
I think we've ruled out that this is a dev-inf thing, right? Are we okay with moving this out of the dev-inf tracker, or is additional support from dev-inf still required here?

**Comment by tbg** [comment]
It's still a likely problem with the acceptance test harness, and so unfortunately remains a dev-inf problem, at least more than any other team's.

**Comment by tbg** [comment]
Nobody changes this code, and it never failed like that until recently, so $something must have changed. What was that $something?

**Comment by rafiss** [comment]
Completely uninformed shot-in-the-dark, but is there any chance it relates to https://github.com/cockroachdb/cockroach/issues/57192

I'm only asking because I pattern matched the keywords of `pebble`, `docker`, and `no such file`. (Point against these being related is that #57192 seemed to only affect Docker on MacOS.)

cc @jbowens -- would you be able to take a look at the symptoms here and determine if there's any relation to #57192 ?

**Comment by cucaroach** [comment]
@rafiss Should we declare victory here?

**Comment by rafiss** [comment]
I support that. It seems less flaky now.
