### ISSUE TITLE
panic: unexpected descriptor type

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#59031]
A CI run hit the panic below.

https://teamcity.cockroachdb.com/viewLog.html?buildId=2585672&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

```
=== RUN   TestLogic/local/enums/schema_changes
panic: unexpected descriptor type &descpb.Descriptor{Union:descpb.isDescriptor_Union(nil)} [recovered]
	panic: unexpected descriptor type &descpb.Descriptor{Union:descpb.isDescriptor_Union(nil)}

goroutine 834874 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc004f09950, 0x52308c0, 0xc00749a660)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:207 +0x126
panic(0x41373a0, 0xc0039e94d0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/catalog/systemschema.ShouldSplitAtDesc(0xc0050b6798, 0xc005536608)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/systemschema/system.go:48 +0x267
github.com/cockroachdb/cockroach/pkg/config.(*SystemConfig).shouldSplitOnSystemTenantObject(0xc003712e60, 0x32, 0x8)
	/go/src/github.com/cockroachdb/cockroach/pkg/config/system.go:700 +0x166
github.com/cockroachdb/cockroach/pkg/config.(*SystemConfig).systemTenantTableBoundarySplitKey.func1(0x3300000032, 0x0, 0x71ba380, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/config/system.go:533 +0x585
github.com/cockroachdb/cockroach/pkg/config.(*SystemConfig).systemTenantTableBoundarySplitKey(0xc003712e60, 0x52308c0, 0xc00749a660, 0xc00d3441a8, 0x1, 0x8, 0xc00d3441c0, 0x1, 0x8, 0xc00f981912, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/config/system.go:585 +0x233
github.com/cockroachdb/cockroach/pkg/config.(*SystemConfig).ComputeSplitKey(0xc003712e60, 0x52308c0, 0xc00749a660, 0xc00d3441a8, 0x1, 0x8, 0xc00d3441c0, 0x1, 0x8, 0xc0021a45e0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/config/system.go:491 +0x165
github.com/cockroachdb/cockroach/pkg/config.(*SystemConfig).NeedsSplit(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/config/system.go:676
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).requiresSplit(0xc00306c8c0, 0x52308c0, 0xc00749a660, 0xc003712e60, 0x52a3a80, 0xc0042cc800, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/queue.go:674 +0xbb
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica(0xc00306c8c0, 0x52308c0, 0xc00749a660, 0x52a3a80, 0xc0042cc800, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/queue.go:908 +0x337
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processLoop.func1.2(0x52308c0, 0xc00749a660)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/queue.go:845 +0xe6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc004f09950, 0x52308c0, 0xc00749a660, 0xc009901f50, 0x2d, 0x0, 0xc00749a690)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0xdd
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:342 +0x11d
```

**Comment by lucy-zhang** [comment]
Another nil descriptor...that's not good. I wonder if it's related to https://github.com/cockroachdb/cockroach/pull/58998.

**Comment by lucy-zhang** [comment]
The descriptor is coming from here:

https://github.com/cockroachdb/cockroach/blob/0fe51ca4a6911e133f8a9001c54410b4be746bb3/pkg/config/system.go#L699-L700

It's strange that this is a wrapped nil value. It's not clear to me why we would read such a `Descriptor` out of the system config.

**Comment by lucy-zhang** [comment]
@ajwerner wondering if you've seen anything like this, before we look further.

**Comment by ajwerner** [comment]
This is precisely what happens if you get a `NULL` value in the descriptor table. It happens if you use `SQL` to write to `system.descriptor`.

**Comment by jordanlewis** [comment]
But we don't do this anywhere in the logic tests, right?

**Comment by lucy-zhang** [comment]
Let's add the descriptor ID to the panic message so we can at least have more information next time.

**Comment by RaduBerinde** [comment]
Looks like there's a dup issue #59091.
