### ISSUE TITLE
circleci: failed tests: TestNodeStatus

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5913]
The following test appears to have failed:

[#15996](https://circleci.com/gh/cockroachdb/cockroach/15996):

```
--- PASS: TestFlagUsage (0.02s)
=== RUN   TestNodeStatus
E160407 00:33:15.697236 storage/replica.go:1468  [node=1,store=1,range=1] error executing raft command: retry txn "storage/replica_command.go:1890 (*Replica).AdminSplit" id=0f456293 key=/Local/Range/"\x95"/RangeDescriptor rw=false pri=0.00298773 iso=SERIALIZABLE stat=PENDING epo=0 ts=1459989195.693338725,0 orig=1459989195.693338725,0 max=1459989195.693338725,0 wto=false
E160407 00:33:20.559626 storage/replica.go:1468  [node=1,store=1,range=1] error executing raft command: write at timestamp 1459989195.695420503,0 too old; wrote at 1459989195.695420503,1
E160407 00:33:20.573307 storage/queue.go:446  [split] range=1 [/Min-/Table/11): error: storage/split_queue.go:103: unable to split range=1 [/Min-/Table/11) at key "/Table/13/0": failed to send RPC: too many errors encountered (1 of 1 total): rpc error: code = 4 desc = "context deadline exceeded"
F160407 00:33:26.022460 cli/cli_test.go:66  Could not start server: server/testserver.go:280: had 4 ranges at startup, expected 5
goroutine 531 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0x352dd00, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:858 +0xcf
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x2b83f40, 0x3, 0x25bdc09, 0xf, 0x42, 0xc8207e1080, 0x55)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:722 +0x199
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x1d295e0, 0x1a, 0xc820411bb0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0x10a
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0xc800000003, 0x1d295e0, 0x1a, 0xc820411bb0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x8d
github.com/cockroachdb/cockroach/util/log.Fatalf(0x1d295e0, 0x1a, 0xc820411bb0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x74
--
	/go/src/github.com/cockroachdb/cockroach/cli/cli_test.go:800 +0xe5
testing.tRunner(0xc8204ae000, 0x289eb10)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3
FAIL	github.com/cockroachdb/cockroach/cli	12.957s
?   	github.com/cockroachdb/cockroach/cli/cliflags	[no test files]
=== RUN   TestTxnRequestTxnTimestamp
--- PASS: TestTxnRequestTxnTimestamp (0.01s)
=== RUN   TestTxnResetTxnOnAbort
--- PASS: TestTxnResetTxnOnAbort (0.01s)
=== RUN   TestTransactionConfig
--- PASS: TestTransactionConfig (0.01s)
=== RUN   TestCommitReadOnlyTransaction
--- PASS: TestCommitReadOnlyTransaction (0.00s)
=== RUN   TestCommitReadOnlyTransactionExplicit

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment]
Looks like the `AdminSplit` RPC timed out. There doesn't seem to be much in the logs to go on here.

**Comment by tamird** [comment]
Looks stale.
