### ISSUE TITLE
bazel: acceptance tests fail when run under Bazel

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#59446]
`bazel test pkg/acceptance:acceptance_test` fails immediately with:

```
panic: cannot find package "github.com/cockroachdb/cockroach" in any of:
	GOROOT/src/github.com/cockroachdb/cockroach (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.glob..func1(0xc000d23b60, 0xc000d23b68)
	pkg/acceptance/cluster/dockercluster.go:74 +0xf4
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.init()
	pkg/acceptance/cluster/dockercluster.go:79 +0x36a
```

Not sure why this is happening. I assume the acceptance tests run the `go` binary from within the test somewhere?

Epic CRDB-8306

**Comment by rickystewart** [comment]
I assume it's [this](https://github.com/cockroachdb/cockroach/blob/04f694a38169ecbdde2362809cff1897205add21/pkg/acceptance/cluster/dockercluster.go#L72).

**Comment by rickystewart** [comment]
See [documentation](https://github.com/bazelbuild/rules_go#how-do-i-access-go_binary-executables-from-go_test) for how to appropriately access binaries from a test. The [gotags](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go_test) for the test also need to be updated. I didn't look to see whether there were other issues that would prevent the tests from running.

This issue is specifically about the `acceptance` tests, but it would be good to audit around and make sure many tests aren't affected by these issues.
