### ISSUE TITLE
log: multi-line messages look ugly with the new log format

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#59558]
See an example below. The prefix on every line is kind of a bummer. For example notice how stack traces pasted in github need horizontal scrolling now.
Besides esthetics, it was much easier to figure out that all these lines are part of the same log message before.

```
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4  !!! refcnt: -1
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !goroutine 242 [running]:
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xaec8400, 0x203000, 0x203000, 0x34a43060)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb9
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc0003a94c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x165e83bd82d36570, 0x400000000, 0x0, ...)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:277 +0xc67
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x8e214e0, 0xc000795840, 0x1, 0x4, 0x8136147, 0xe, 0xc000ceed90, 0x1, 0x1)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:58 +0x198
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:804
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/tracker.(*lockfreeTracker).Untrack(0xc000826c00, 0x8e214e0, 0xc000795840, 0x8d951c0, 0xc000826c00)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/tracker/lockfree_tracker.go:174 +0x125
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*TrackedRequestToken).doneRLocked(0xc000cef250, 0x8e214e0, 0xc000795840)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_proposal_buf.go:744 +0xcf
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*TrackedRequestToken).Done(0xc000cef250, 0x8e214e0, 0xc000795840)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_proposal_buf.go:733 +0x71
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*TrackedRequestToken).DoneIfNotMoved(0xc000cef250, 0x8e214e0, 0xc000795840)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_proposal_buf.go:752 +0x4e
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch(0xc000d7e800, 0x8e214e0, 0xc000795840, 0xc000cde000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_write.go:292 +0x1460
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries(0xc000d7e800, 0x8e214e0, 0xc000795840, 0xc000cde000, 0x87cb4c0, 0x0, 0x0)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:352 +0x491
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendWithRangeID(0xc000d7e800, 0x8e214e0, 0xc000795840, 0x1, 0xc000cde000, 0x0, 0x0)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:97 +0x53d
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).Send(...)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:36
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*pendingLeaseRequest).requestLeaseAsync.func2(0x8e214e0, 0xc000795840)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_range_lease.go:408 +0x650
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc000699780, 0x8e214e0, 0xc000795840, 0xc000aac180, 0x35, 0xc00081e340, 0xc000556280)
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:352 +0xdd
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !	/Users/andrei/work/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0x11d
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !****************************************************************************
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !This node experienced a fatal error (printed above), and as a result the
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !process is terminating.
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !problem in CockroachDB. With your help, the support team at Cockroach Labs
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !will try to determine the root cause, recommend next steps, and we can
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !improve CockroachDB based on your report.
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !Please submit a crash report by following the instructions here:
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !    https://github.com/cockroachdb/cockroach/issues/new/choose
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !If you would rather not post publicly, please contact us directly at:
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !    support@cockroachlabs.com
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !
F210128 21:49:26.612166 242 kv/kvserver/closedts/tracker/lockfree_tracker.go:174  [s1,r1/1:/M{in-ax}] 4 !The Cockroach Labs team appreciates your feedback.
```

Jira issue: CRDB-3273

**Comment by ajwerner** [comment]
I've been sad about this, and also the fact that long single lines get split over multiple lines. The answer that I'm thinking I'd like to pursue is to make `cockroach debug merge-logs` capable of parsing the new format into messages of the old format and thus also able to print out the old format. I almost always have cockroach around when I'm processing logs and merge-logs is handy enough that I almost always use it. I think it's also probably a good idea to make merge-logs capable of outputting json giving us the power of `jq` and the likes when mucking around with logs

**Comment by andreimatei** [comment]
> I've been sad about this, and also the fact that long single lines get split over multiple lines. 

Oh I didn't know about this. But it now makes sense why the fact that our logs api endpoint has some stupid per-line byte limit is no longer a problem.
Nobody asked for my opinion, but I do question these changes. I liked our log format when it was dumb.
I'm sure there were reasons for these changes, but I'm hoping we can go back on some of these changes and push some of the parsing difficulty into tools. Or at least go back to using the dumber logs by default, and opt into these more structured ones.

**Comment by ajwerner** [comment]
Let's start with the tooling changes and see if you can get by with them. Then if we're still sad, we can talk about backing this out.

**Comment by andreimatei** [comment]
Well a lot of the logs I consume are from tests, locally or on TC. The tools don't quite apply there.

**Comment by ajwerner** [comment]
But for that can't you just switch to the old format?

**Comment by ajwerner** [comment]
Should we set the old format for logs as the default in CI?

**Comment by andreimatei** [comment]
I would take any improvement, but I should say that personally I was pretty happy with the old format :P

**Comment by knz** [comment]
There's a balance to be stricken here. Lots of folk besides you were actually unhappy.

What we have now makes it much more reliable to get useful data out of concurrent tests with interleaved test and log output.

If you want something different let's try to achieve that with post filtering. That at least has become possible, and was totally impossible to do reliably with crdb-v1.

**Comment by andreimatei** [comment]
> What we have now makes it much more reliable to get useful data out of concurrent tests with interleaved test and log output.

Is anybody actually taking advantage of this? Perhaps it can be enabled particularly for whatever CI needs it?

I came back here because test panics now don't fit well on my terminal. I respectfully insist that if somebody wanted a multi-line message in the log, they did not intend for that message to be consumed with tens of characters of prefix on every line. I imagine there's various technical difficulties here, but I want to speak for the little guy - when I'm consuming logs through the console or by reading a file, the experience has become worse.

**Comment by knz** [comment]
There's a bag of wants and desires here but the log format is not the solution you're looking for. This needs a little more thought.

**Comment by knz** [comment]
Here's a few notes from the discussion I had with Andrei:

- unit tests and CI runs generally could benefit from a different/simpler format, since the logs do not need to be robust to data transfers through a customer / tech-support boundary as much.
- we want to improve `debug merge-logs` in multiple ways including the ability to strip the prefix and merge broken lines.

I will comment further on the topic of line length in the linked issue #61681
