### ISSUE TITLE
sql: panic if trying to run `INSERT .. RETURNING COUNT(*)`

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#6016]
I was wondering if something like this worked:

`INSERT INTO a VALUES (1,2), (3,4) RETURNING COUNT(*)`

```
store[0]:  path=cockroach-data
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb2943a]

goroutine 1319 [running]:
panic(0x16068a0, 0xc82000e140)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql/parser.(*FuncExpr).Eval(0xc820957200, 0x1, 0xece9f45a3, 0x17181bd5, 0x24fe680, 0x1444b3d17632956a, 0x0, 0xc82033b830, 0xc82081ab70, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:1185 +0x53a
github.com/cockroachdb/cockroach/sql.(*returningHelper).append(0xc820741650, 0xc8207416e0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/returning.go:90 +0x1c0
github.com/cockroachdb/cockroach/sql.(*planner).Insert(0xc820338878, 0xc82058f080, 0xe984f101, 0x0, 0x0, 0x1699528)
	/go/src/github.com/cockroachdb/cockroach/sql/insert.go:280 +0x26f1
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc820338878, 0x7f3586c540d0, 0xc82058f080, 0xc82058cd01, 0x0, 0x0, 0x871a4)
	/go/src/github.com/cockroachdb/cockroach/sql/plan.go:220 +0x1313
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc8200d41c0, 0x7f3586c540d0, 0xc82058f080, 0xc820338878, 0xece9f45a3, 0xc817183655, 0x24fe680, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:875 +0x89
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInOpenTxn(0xc8200d41c0, 0x7f3586c540d0, 0xc82058f080, 0xc820338878, 0x101, 0x1444b3d17632b9d5, 0x0, 0xc820338828, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:778 +0x58d
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc8200d41c0, 0xc82081abe0, 0x1, 0x1, 0xc820338878, 0xc820338828, 0x1e0101, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:556 +0x630
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc8200d41c0, 0xc820338878, 0x1, 0xc820338828, 0xc82065a720, 0xc82081abe0, 0x1, 0x1, 0xc82099b390, 0xc82099b3a8, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:488 +0x147
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func1(0xc8208cb600, 0xc82065a720, 0x4)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:401 +0x325
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc8208cb600, 0x1860101, 0x1444b3d17632956a, 0x0, 0xc82099b4e8, 0x0)
	/go/src/github.com/cockroachdb/cockroach/client/txn.go:531 +0x410
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc8200d41c0, 0x7f3586d187a0, 0xc820780380, 0xc820338800, 0xc8208628c3, 0x35, 0x0, 0x0, 0x0, 0x7f3586ce5100)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:405 +0x892
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8200d41c0, 0x7f3586d187a0, 0xc820780380, 0xc820338800, 0xc8208628c3, 0x35, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:295 +0xe2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc82053fc80, 0x7f3586d187a0, 0xc820780380, 0xc8208628c3, 0x35, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:603 +0xb2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc82053fc80, 0x7f3586d187a0, 0xc820780380, 0xc82053fca8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:313 +0xf2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc82053fc80, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:269 +0x10d3
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc8203307d8, 0x7f3586c9adc0, 0xc8205bc000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:159 +0x929
github.com/cockroachdb/cockroach/server.(*Server).Start.func6.1(0x7f3586c9adc0, 0xc8205bc000)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:313 +0x4b
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc820076500, 0x7f3586c9adc0, 0xc8205bc000, 0xc82033b870)
	/go/src/github.com/cockroachdb/cockroach/util/net.go:125 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/go/src/github.com/cockroachdb/cockroach/util/net.go:127 +0x31f
```

**Comment by knz** [comment]
Fixed by #7052.
