### ISSUE TITLE
sql: Close() called on nil StmtBuf

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#60423]
On master today

```
$ make stress PKG=./pkg/kv/kvserver/protectedts/ptcache/ TESTS=TestSettingChangedLeadsToFetch 
[10 seconds-ish pass]

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x311c009]

goroutine 512 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*StmtBuf).Close(0x0)
	/home/tobias/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_io.go:387 +0x29
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal.func3(0x4e05d20, 0xc0000ca280)
	/home/tobias/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:715 +0x3a
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1(0xc002346000, 0x4e93780, 0xc002176a50, 0xc0005ae900, 0xc00216d020, 0xc00210cd80, 0xc001a4c7e0, 0xc001a10d20)
	/home/tobias/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:204 +0x153
created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx
	/home/tobias/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:201 +0x356


ERROR: exit status 2

558 runs completed, 1 failures, over 9s
context canceled
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptcache	9.230s
FAIL
make: *** [Makefile:1034: stress] Error 1
```

**Comment by nvanbenschoten** [comment]
I've seen this in CI as well on two different tests, so it appears to be fairly prevalent.

**Comment by yuzefovich** [comment]
Thanks for pinging, I have just put out a PR to fix it.
