### ISSUE TITLE
stress: failed test in cockroach/client/client.test: TestDebugName

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6060]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/371017263b122dbd2423dc1c2c6b8e98b1ff19f0

Stress build found a failed test:

```
=== RUN   TestDebugName
W160414 02:59:15.524318 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
I160414 02:59:15.533911 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160414 02:59:15.534706 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
I160414 02:59:15.534825 server/node.go:360  store store=0:0 ([]=) not bootstrapped
I160414 02:59:15.535870 storage/replica_command.go:1409  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405722h59m16.535699453s
I160414 02:59:15.536221 server/node.go:310  **** cluster {c65b4c07-8715-4d1d-8153-0ef8664b0dfa} has been created
I160414 02:59:15.536233 server/node.go:311  **** add additional nodes by specifying --join=127.0.0.1:35138
W160414 02:59:15.536238 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
I160414 02:59:15.536664 server/node.go:373  initialized store store=1:1 ([]=): {Capacity:8312655872 Available:6032011264 RangeCount:0}
I160414 02:59:15.536687 server/node.go:285  node ID 1 initialized
I160414 02:59:15.536729 storage/stores.go:286  read 0 node addresses from persistent storage
I160414 02:59:15.536777 server/node.go:494  connecting to gossip network to verify cluster ID...
I160414 02:59:15.536912 server/node.go:515  node connected via gossip and verified as part of cluster {"c65b4c07-8715-4d1d-8153-0ef8664b0dfa"}
I160414 02:59:15.536947 server/node.go:338  [node=1] Started node with [[]=] engine(s) and attributes []
I160414 02:59:15.536974 server/server.go:363  starting https server at 127.0.0.1:33026
I160414 02:59:15.536990 server/server.go:364  starting grpc/postgres server at 127.0.0.1:35138
I160414 02:59:15.537053 storage/split_queue.go:100  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160414 02:59:15.537633 server/updates.go:147  No previous updates check time.
I160414 02:59:15.539379 storage/replica_command.go:1862  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160414 02:59:15.548636 storage/replica_command.go:1409  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405722h59m16.586357603s
I160414 02:59:15.548744 storage/replica_command.go:1862  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160414 02:59:15.552726 storage/replica_command.go:1409  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405722h59m16.586357603s
I160414 02:59:15.552826 storage/replica_command.go:1862  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160414 02:59:15.559271 storage/replica_command.go:1409  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405722h59m16.586357603s
I160414 02:59:15.559394 storage/replica_command.go:1862  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160414 02:59:18.548367 server/status/runtime.go:160  runtime stats: 57 MiB RSS, 48 goroutines, 9.6 MiB active, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (120x)
--- FAIL: TestDebugName (5.09s)
	leaktest.go:82: Leaked goroutine: goroutine 447 [IO wait]:
		net.runtime_pollWait(0x7f2bc9e7f6d0, 0x72, 0xc820134400)
			/usr/local/go/src/runtime/netpoll.go:160 +0x60
		net.(*pollDesc).Wait(0xc820056140, 0x72, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
		net.(*pollDesc).WaitRead(0xc820056140, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
		net.(*netFD).Read(0xc8200560e0, 0xc820134400, 0x400, 0x400, 0x0, 0x7f2bc9e6c050, 0xc82000e068)
			/usr/local/go/src/net/fd_unix.go:250 +0x23a
		net.(*conn).Read(0xc82002a028, 0xc820134400, 0x400, 0x400, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/net.go:172 +0xe4
		crypto/tls.(*block).readFromUntil(0xc8207a6bd0, 0x7f2bc9e86c40, 0xc82002a028, 0x5, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
		crypto/tls.(*Conn).readRecord(0xc8208bc000, 0x1a8f117, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
		crypto/tls.(*Conn).Read(0xc8208bc000, 0xc820464000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:939 +0x167
		bufio.(*Reader).fill(0xc820720540)
			/usr/local/go/src/bufio/bufio.go:97 +0x1e9
		bufio.(*Reader).Read(0xc820720540, 0xc8205ac038, 0x9, 0x9, 0xc81ff6ddc3, 0x0, 0x0)
			/usr/local/go/src/bufio/bufio.go:207 +0x260
		io.ReadAtLeast(0x7f2bb5fbd180, 0xc820720540, 0xc8205ac038, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
			/usr/local/go/src/io/io.go:297 +0xe6
		io.ReadFull(0x7f2bb5fbd180, 0xc820720540, 0xc8205ac038, 0x9, 0x9, 0xc820da4308, 0x0, 0x0)
			/usr/local/go/src/io/io.go:315 +0x62
		golang.org/x/net/http2.readFrameHeader(0xc8205ac038, 0x9, 0x9, 0x7f2bb5fbd180, 0xc820720540, 0x0, 0xc800000000, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
		golang.org/x/net/http2.(*Framer).ReadFrame(0xc8205ac000, 0x0, 0x0, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:463 +0x106
		google.golang.org/grpc/transport.(*framer).readFrame(0xc8206a0270, 0x0, 0x0, 0x0, 0x0)
			/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
		google.golang.org/grpc/transport.(*http2Client).reader(0xc820930000)
			/go/src/google.golang.org/grpc/transport/http2_client.go:757 +0x109
		created by google.golang.org/grpc/transport.newHTTP2Client
			/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a
	leaktest.go:82: Leaked goroutine: goroutine 476 [select]:
		github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc8205868c0, 0xecea0fe81, 0x2151e749, 0x248ff00, 0xc8205d1cc0, 0xc8207de000, 0xc82078c0e0, 0xc8204dde00)
			/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:162 +0x568
		github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc82078c0e0, 0xc8207b1b30)
			/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:204 +0x78
		github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc8207b1c50, 0xc8207e00c0)
			/go/src/github.com/cockroachdb/cockroach/storage/store.go:237 +0x246
		github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
			/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:206 +0x21e
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8207de000, 0xc8202427a0)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

Run Details:

```
7 runs so far, 0 failures, over 5s
16 runs so far, 0 failures, over 10s
29 runs so far, 0 failures, over 15s
37 runs so far, 0 failures, over 20s
48 runs so far, 0 failures, over 25s
59 runs so far, 0 failures, over 30s
68 runs so far, 0 failures, over 35s
82 runs so far, 0 failures, over 40s
89 runs so far, 0 failures, over 45s
102 runs so far, 0 failures, over 50s
110 runs so far, 0 failures, over 55s
123 runs so far, 0 failures, over 1m0s
131 runs so far, 0 failures, over 1m5s
144 runs so far, 0 failures, over 1m10s
151 runs so far, 0 failures, over 1m15s
163 runs so far, 0 failures, over 1m20s
173 runs so far, 0 failures, over 1m25s
184 runs so far, 0 failures, over 1m30s
195 runs so far, 0 failures, over 1m35s
206 runs so far, 0 failures, over 1m40s
216 runs so far, 0 failures, over 1m45s
228 runs so far, 0 failures, over 1m50s
237 runs so far, 0 failures, over 1m55s
248 runs so far, 0 failures, over 2m0s
260 runs so far, 0 failures, over 2m5s
270 runs so far, 0 failures, over 2m10s
280 runs so far, 0 failures, over 2m15s
291 runs so far, 0 failures, over 2m20s
302 runs so far, 0 failures, over 2m25s
312 runs so far, 0 failures, over 2m30s
323 runs so far, 0 failures, over 2m35s
333 runs so far, 0 failures, over 2m40s
345 runs so far, 0 failures, over 2m45s
354 runs so far, 0 failures, over 2m50s
365 runs so far, 0 failures, over 2m55s
375 runs so far, 0 failures, over 3m0s
385 runs so far, 0 failures, over 3m5s
396 runs so far, 0 failures, over 3m10s
408 runs so far, 0 failures, over 3m15s
417 runs so far, 0 failures, over 3m20s
429 runs so far, 0 failures, over 3m25s
439 runs so far, 0 failures, over 3m30s
450 runs so far, 0 failures, over 3m35s
458 runs so far, 0 failures, over 3m40s
473 runs so far, 0 failures, over 3m45s
481 runs so far, 0 failures, over 3m50s
494 runs so far, 0 failures, over 3m55s
502 runs so far, 0 failures, over 4m0s
514 runs so far, 0 failures, over 4m5s
524 runs so far, 0 failures, over 4m10s
535 runs so far, 0 failures, over 4m15s
546 runs so far, 0 failures, over 4m20s
556 runs so far, 0 failures, over 4m25s
568 runs so far, 0 failures, over 4m30s
579 runs so far, 0 failures, over 4m35s
589 runs so far, 0 failures, over 4m40s
600 runs so far, 0 failures, over 4m45s
610 runs so far, 0 failures, over 4m50s
620 runs so far, 0 failures, over 4m55s
632 runs so far, 0 failures, over 5m0s
643 runs so far, 0 failures, over 5m5s
653 runs so far, 0 failures, over 5m10s
665 runs so far, 0 failures, over 5m15s
675 runs so far, 0 failures, over 5m20s
686 runs so far, 0 failures, over 5m25s
696 runs so far, 0 failures, over 5m30s
707 runs so far, 0 failures, over 5m35s
719 runs so far, 0 failures, over 5m40s
728 runs so far, 0 failures, over 5m45s
739 runs so far, 0 failures, over 5m50s
750 runs so far, 0 failures, over 5m55s
760 runs so far, 0 failures, over 6m0s
772 runs so far, 0 failures, over 6m5s
780 runs so far, 0 failures, over 6m10s
793 runs so far, 0 failures, over 6m15s
804 runs so far, 0 failures, over 6m20s
814 runs so far, 0 failures, over 6m25s
825 runs so far, 0 failures, over 6m30s
836 runs so far, 0 failures, over 6m35s
846 runs so far, 0 failures, over 6m40s
855 runs so far, 0 failures, over 6m45s
867 runs so far, 0 failures, over 6m50s
876 runs so far, 0 failures, over 6m55s
888 runs so far, 0 failures, over 7m0s
897 runs so far, 0 failures, over 7m5s
909 runs so far, 0 failures, over 7m10s
920 runs so far, 0 failures, over 7m15s
930 runs so far, 0 failures, over 7m20s
943 runs so far, 0 failures, over 7m25s
951 runs so far, 0 failures, over 7m30s
963 runs so far, 0 failures, over 7m35s
973 runs so far, 0 failures, over 7m40s
984 runs so far, 0 failures, over 7m45s
994 runs so far, 0 failures, over 7m50s
1006 runs so far, 0 failures, over 7m55s
1015 runs so far, 0 failures, over 8m0s
1026 runs so far, 0 failures, over 8m5s
1035 runs so far, 0 failures, over 8m10s
1047 runs so far, 0 failures, over 8m15s
1057 runs so far, 0 failures, over 8m20s
1066 runs so far, 0 failures, over 8m25s
1079 runs so far, 0 failures, over 8m30s
1089 runs so far, 0 failures, over 8m35s
1099 runs so far, 0 failures, over 8m40s
1110 runs so far, 0 failures, over 8m45s
1121 runs so far, 0 failures, over 8m50s
1132 runs so far, 0 failures, over 8m55s
1142 runs so far, 0 failures, over 9m0s
1152 runs so far, 0 failures, over 9m5s
1165 runs so far, 0 failures, over 9m10s
1174 runs so far, 0 failures, over 9m15s
1186 runs so far, 0 failures, over 9m20s
1196 runs so far, 0 failures, over 9m25s
1205 runs so far, 0 failures, over 9m30s
1219 runs so far, 0 failures, over 9m35s
1227 runs so far, 0 failures, over 9m40s
1240 runs so far, 0 failures, over 9m45s
1251 runs so far, 0 failures, over 9m50s
1261 runs so far, 0 failures, over 9m55s
1272 runs so far, 0 failures, over 10m0s
1283 runs so far, 0 failures, over 10m5s
1292 runs so far, 0 failures, over 10m10s
1304 runs so far, 0 failures, over 10m15s
1314 runs so far, 0 failures, over 10m20s
1325 runs so far, 0 failures, over 10m25s
1335 runs so far, 0 failures, over 10m30s
1346 runs so far, 0 failures, over 10m35s
1356 runs so far, 0 failures, over 10m40s
1368 runs so far, 0 failures, over 10m45s
1378 runs so far, 0 failures, over 10m50s
1388 runs so far, 0 failures, over 10m55s
1400 runs so far, 0 failures, over 11m0s
1411 runs so far, 0 failures, over 11m5s
1419 runs so far, 0 failures, over 11m10s
1430 runs so far, 0 failures, over 11m15s
1439 runs so far, 0 failures, over 11m20s
1443 runs completed, 1 failures, over 11m21s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
Test failure is unrelated to what this test is asserting. The second leaked goroutine is sitting on a `select` that has `stopper.ShouldStop` in it, but the test itself appears to have completed. No actionable information here.
