### ISSUE TITLE
log: weird behavior with `log.SetNodeIDs` and tests and `--show-logs`

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#60688]
**Describe the problem**

If I run the same test twice but one of them uses `--show-logs` the test fails with a surprising error. This is on the current master (had me worried I broke something, 738e60ad1a50ebfc13fb61490c71673c92d67b90). 

```
$ make test TESTS=TestTenantCannotSetClusterSetting PKG=github.com/cockroachdb/cockroach/pkg/ccl/serverccl/ TESTFLAGS='--count 2'
Running make with -j8
GOPATH set to /home/ajwerner
mkdir -p lib
rm -f lib/lib{geos,geos_c}.so
cp -L /home/ajwerner/native/x86_64-linux-gnu/geos/lib/lib{geos,geos_c}.so lib
GOFLAGS= go test   -mod=vendor -tags ' gss make x86_64_linux_gnu crdb_test' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=v21.1.0-alpha.3-489-g738e60ad1a" -X "github.com/cockroachdb/cockroach/pkg/build.rev=738e60ad1a50ebfc13fb61490c71673c92d67b90" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-linux-gnu"  ' -run "TestTenantCannotSetClusterSetting"  -timeout 30m github.com/cockroachdb/cockroach/pkg/ccl/serverccl/ --count 2
ok  	github.com/cockroachdb/cockroach/pkg/ccl/serverccl	0.645s
```

Now with `--show-logs`:

```
--- FAIL: TestTenantCannotSetClusterSetting (0.25s)
    panic.go:969: clusterID already set
        goroutine 1598 [running]:
        runtime/debug.Stack(0xc0008360b8, 0x4222860, 0x572f9d0)
        	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
        github.com/cockroachdb/cockroach/pkg/util/leaktest.AfterTest.func1()
        	/home/ajwerner/src/github.com/cockroachdb/cockroach/pkg/util/leaktest/leaktest.go:110 +0x278
        panic(0x4222860, 0x572f9d0)
        	/usr/local/go/src/runtime/panic.go:969 +0x1b9
        github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc0023460c0, 0x5840040, 0xc000124010)
        	/home/ajwerner/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:471 +0x31e
        panic(0x4222860, 0x572f9d0)
        	/usr/local/go/src/runtime/panic.go:969 +0x1b9
        github.com/cockroachdb/cockroach/pkg/util/log.SetNodeIDs(0xc0033ab860, 0x24, 0x0)
        	/home/ajwerner/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:228 +0x286
        github.com/cockroachdb/cockroach/pkg/server.StartTenant(0x5840040, 0xc000124010, 0xc0023461e0, 0x0, 0x0, 0xc002dd6000, 0xc0028b8460, 0xc0024f9d70, 0x0, 0x0, ...)
        	/home/ajwerner/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:878 +0xd09
        github.com/cockroachdb/cockroach/pkg/server.(*TestServer).StartTenant(0xc002b0c900, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        	/home/ajwerner/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:731 +0x2a5
        github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartTenant(0x5988f20, 0xc002bc6600, 0x599e180, 0xc002b0c900, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        	/home/ajwerner/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:335 +0x7c
        github.com/cockroachdb/cockroach/pkg/ccl/serverccl.TestTenantCannotSetClusterSetting(0xc002bc6600)
        	/home/ajwerner/src/github.com/cockroachdb/cockroach/pkg/ccl/serverccl/server_sql_test.go:77 +0x278
        testing.tRunner(0xc002bc6600, 0x510fe00)
        	/usr/local/go/src/testing/testing.go:1123 +0xef
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:1168 +0x2b3
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/serverccl	0.684s
FAIL
```

**Comment by ajwerner** [comment]
FWIW, it's not just this test. Lots of tests seem to present this behavior.

**Comment by ajwerner** [comment]
In fact, if I just run that package with `--show-logs` I see this failure.
