### ISSUE TITLE
missing rows.Err() checks in multiple packages 

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#61059]
**Describe the problem**

The `database/sql.Rows` type provides an [`Err()`](https://golang.org/pkg/database/sql/#Rows.Err) method that is supposed to be called after Next() returns false.  This check appears to be missing in 150+ places according to the [rowserrcheck linter](https://github.com/jingyugao/rowserrcheck).  This linter has some false positives, so the actual cases of missing checks is likely lower than that.  However, many of them are actual violations.

My guess is that many of these are low impact as (1) most of the violations are in test code and (2) often the error would be found some other way.  But it is possible checking for the errors will make various test failures easier to debug.

If we wanted to integrate this linter into the set of linters we run, we would likely need to work with the upstream to fix a number of bugs as in addition to false positives, the checker also segfaults on a the sql/pgwire/pgerror package

**To Reproduce**

> go get -u github.com/jingyugao/rowserrcheck
> go vet -vettool $(which rowserrcheck) ./pkg/...

<details><summary>rowerrcheck reported for ./pkg/... as of b4e93775840be27ef10b809b962a25f72d676013</summary>

```
# github.com/cockroachdb/cockroach/pkg/workload/tpch
pkg/workload/tpch/tpch.go:352:25: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/workload/tpcds
pkg/workload/tpcds/tpcds.go:311:26: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/workload/rand
pkg/workload/rand/rand.go:139:23: rows.Err must be checked
pkg/workload/rand/rand.go:181:24: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/acceptance
pkg/acceptance/util_cluster.go:111:26: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/workload/querylog
pkg/workload/querylog/querylog.go:497:23: rows.Err must be checked
pkg/workload/querylog/querylog.go:742:24: rows.Err must be checked
pkg/workload/querylog/querylog.go:764:23: rows.Err must be checked
pkg/workload/querylog/querylog.go:821:25: rows.Err must be checked
pkg/workload/querylog/querylog.go:845:27: rows.Err must be checked
pkg/workload/querylog/querylog.go:853:27: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/acceptance/localcluster
pkg/acceptance/localcluster/cluster.go:344:23: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/cmd/zerosum
pkg/cmd/zerosum/main.go:176:25: rows.Err must be checked
pkg/cmd/zerosum/main.go:334:23: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/jobs
pkg/jobs/job_scheduler_test.go:337:24: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/jobs_test
pkg/jobs/jobs_test.go:1704:26: rows.Err must be checked
pkg/jobs/jobs_test.go:1890:32: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdctest
pkg/ccl/changefeedccl/cdctest/nemeses.go:517:27: rows.Err must be checked
pkg/ccl/changefeedccl/cdctest/validator.go:371:27: rows.Err must be checked
pkg/ccl/changefeedccl/cdctest/validator.go:691:26: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl_test
pkg/ccl/multiregionccl/region_test.go:108:27: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/ccl/workloadccl
pkg/ccl/workloadccl/fixture.go:446:25: rows.Err must be checked
pkg/ccl/workloadccl/fixture.go:586:27: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/ccl/partitionccl
pkg/ccl/partitionccl/partition_test.go:1092:21: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/ccl/backupccl
pkg/ccl/backupccl/backup_test.go:265:52: rows.Err must be checked
pkg/ccl/backupccl/backup_test.go:916:26: rows.Err must be checked
pkg/ccl/backupccl/backup_test.go:1064:27: rows.Err must be checked
pkg/ccl/backupccl/create_scheduled_backup_test.go:132:38: rows.Err must be checked
pkg/ccl/backupccl/create_scheduled_backup_test.go:639:23: rows.Err must be checked
pkg/ccl/backupccl/create_scheduled_backup_test.go:646:22: rows.Err must be checked
pkg/ccl/backupccl/helpers_test.go:117:21: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/ccl/importccl_test
pkg/ccl/importccl/exportcsv_test.go:181:19: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/cli
pkg/cli/debug_test.go:203:22: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/cmd/roachtest
pkg/cmd/roachtest/allocator.go:141:24: rows.Err must be checked
pkg/cmd/roachtest/allocator.go:270:24: rows.Err must be checked
pkg/cmd/roachtest/decommission.go:800:24: rows.Err must be checked
pkg/cmd/roachtest/engine_switch.go:84:27: rows.Err must be checked
pkg/cmd/roachtest/gossip.go:228:24: rows.Err must be checked
pkg/cmd/roachtest/gossip.go:474:24: rows.Err must be checked
pkg/cmd/roachtest/rebalance_load.go:157:23: rows.Err must be checked
pkg/cmd/roachtest/rebalance_load.go:165:24: rows.Err must be checked
pkg/cmd/roachtest/restore.go:108:31: rows.Err must be checked
pkg/cmd/roachtest/secondary_indexes.go:116:26: rows.Err must be checked
pkg/cmd/roachtest/tpchvec.go:327:33: rows.Err must be checked
pkg/cmd/roachtest/version.go:87:27: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql
pkg/sql/builtin_test.go:38:31: rows.Err must be checked
pkg/sql/distsql_physical_planner_test.go:228:28: rows.Err must be checked
pkg/sql/explain_bundle_test.go:75:30: rows.Err must be checked
pkg/sql/explain_bundle_test.go:93:26: rows.Err must be checked
pkg/sql/instrumentation_test.go:64:21: rows.Err must be checked
pkg/sql/plan_opt_test.go:214:34: rows.Err must be checked
pkg/sql/plan_opt_test.go:256:34: rows.Err must be checked
pkg/sql/plan_opt_test.go:412:34: rows.Err must be checked
pkg/sql/plan_opt_test.go:417:35: rows.Err must be checked
pkg/sql/temporary_schema_test.go:87:29: rows.Err must be checked
pkg/sql/temporary_schema_test.go:119:19: rows.Err must be checked
pkg/sql/temporary_schema_test.go:181:29: rows.Err must be checked
pkg/sql/temporary_schema_test.go:213:19: rows.Err must be checked
pkg/sql/temporary_schema_test.go:217:19: rows.Err must be checked
pkg/sql/temporary_schema_test.go:373:30: rows.Err must be checked
pkg/sql/temporary_schema_test.go:387:32: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql/catalog/lease_test
pkg/sql/catalog/lease/lease_test.go:974:32: rows.Err must be checked
pkg/sql/catalog/lease/lease_test.go:1005:26: rows.Err must be checked
pkg/sql/catalog/lease/lease_test.go:1090:26: rows.Err must be checked
pkg/sql/catalog/lease/lease_test.go:1196:24: rows.Err must be checked
pkg/sql/catalog/lease/lease_test.go:1560:23: rows.Err must be checked
pkg/sql/catalog/lease/lease_test.go:1580:27: rows.Err must be checked
pkg/sql/catalog/lease/lease_test.go:1863:23: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/server
pkg/server/admin_test.go:1409:18: rows.Err must be checked
pkg/server/admin_test.go:1674:23: rows.Err must be checked
pkg/server/status_test.go:174:23: rows.Err must be checked
pkg/server/status_test.go:209:24: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql_test
pkg/sql/ambiguous_commit_test.go:182:30: rows.Err must be checked
pkg/sql/conn_executor_savepoints_test.go:79:32: rows.Err must be checked
pkg/sql/conn_executor_savepoints_test.go:112:32: rows.Err must be checked
pkg/sql/conn_executor_test.go:488:21: rows.Err must be checked
pkg/sql/conn_executor_test.go:880:29: rows.Err must be checked
pkg/sql/crdb_internal_test.go:238:26: rows.Err must be checked
pkg/sql/crdb_internal_test.go:487:26: rows.Err must be checked
pkg/sql/create_test.go:439:24: rows.Err must be checked
pkg/sql/descriptor_mutation_test.go:293:30: rows.Err must be checked
pkg/sql/descriptor_mutation_test.go:561:28: rows.Err must be checked
pkg/sql/drop_test.go:63:26: rows.Err must be checked
pkg/sql/drop_test.go:94:26: rows.Err must be checked
pkg/sql/drop_test.go:1125:23: rows.Err must be checked
pkg/sql/err_count_test.go:40:20: rows.Err must be checked
pkg/sql/err_count_test.go:51:23: rows.Err must be checked
pkg/sql/err_count_test.go:126:25: rows.Err must be checked
pkg/sql/indexbackfiller_test.go:162:26: rows.Err must be checked
pkg/sql/mutation_test.go:55:20: rows.Err must be checked
pkg/sql/run_control_test.go:237:33: rows.Err must be checked
pkg/sql/run_control_test.go:351:33: rows.Err must be checked
pkg/sql/run_control_test.go:511:35: rows.Err must be checked
pkg/sql/run_control_test.go:489:36: rows.Err must be checked
pkg/sql/run_control_test.go:921:28: rows.Err must be checked
pkg/sql/run_control_test.go:932:30: rows.Err must be checked
pkg/sql/schema_changer_test.go:1513:26: rows.Err must be checked
pkg/sql/schema_changer_test.go:1893:26: rows.Err must be checked
pkg/sql/schema_changer_test.go:2871:26: rows.Err must be checked
pkg/sql/schema_changer_test.go:2892:25: rows.Err must be checked
pkg/sql/schema_changer_test.go:2912:25: rows.Err must be checked
pkg/sql/schema_changer_test.go:2940:25: rows.Err must be checked
pkg/sql/schema_changer_test.go:3176:27: rows.Err must be checked
pkg/sql/schema_changer_test.go:4946:31: rows.Err must be checked
pkg/sql/schema_changer_test.go:5161:23: rows.Err must be checked
pkg/sql/schema_changer_test.go:5493:26: rows.Err must be checked
pkg/sql/schema_changer_test.go:5496:26: rows.Err must be checked
pkg/sql/schema_changer_test.go:5502:26: rows.Err must be checked
pkg/sql/schema_changer_test.go:5505:26: rows.Err must be checked
pkg/sql/schema_changer_test.go:5583:26: rows.Err must be checked
pkg/sql/schema_changer_test.go:5589:26: rows.Err must be checked
pkg/sql/schema_changer_test.go:6038:26: rows.Err must be checked
pkg/sql/schema_changer_test.go:6041:26: rows.Err must be checked
pkg/sql/scrub_test.go:156:23: rows.Err must be checked
pkg/sql/scrub_test.go:186:22: rows.Err must be checked
pkg/sql/scrub_test.go:263:23: rows.Err must be checked
pkg/sql/scrub_test.go:383:23: rows.Err must be checked
pkg/sql/scrub_test.go:614:23: rows.Err must be checked
pkg/sql/scrub_test.go:706:23: rows.Err must be checked
pkg/sql/scrub_test.go:825:23: rows.Err must be checked
pkg/sql/scrub_test.go:919:23: rows.Err must be checked
pkg/sql/scrub_test.go:996:23: rows.Err must be checked
pkg/sql/show_test.go:645:25: rows.Err must be checked
pkg/sql/show_test.go:709:24: rows.Err must be checked
pkg/sql/show_test.go:679:26: rows.Err must be checked
pkg/sql/show_test.go:825:26: rows.Err must be checked
pkg/sql/trace_test.go:335:33: rows.Err must be checked
pkg/sql/trace_test.go:431:27: rows.Err must be checked
pkg/sql/trace_test.go:474:27: rows.Err must be checked
pkg/sql/trace_test.go:556:18: rows.Err must be checked
pkg/sql/trace_test.go:568:17: rows.Err must be checked
pkg/sql/txn_restart_test.go:826:29: rows.Err must be checked
pkg/sql/txn_restart_test.go:961:28: rows.Err must be checked
pkg/sql/txn_restart_test.go:1413:23: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql/logictest
pkg/sql/logictest/logic.go:2319:27: rows.Err must be checked
pkg/sql/logictest/logic.go:3060:26: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11fd450]

goroutine 9 [running]:
golang.org/x/tools/go/ssa.(*Type).Object(...)
	/Users/ssd/go/src/golang.org/x/tools/go/ssa/ssa.go:1467
github.com/jingyugao/rowserrcheck/passes/rowserr.runner.run(0xc000c31ba0, 0x0, 0x0, 0x0, 0x0, 0xc0013930f0, 0x1, 0x1, 0xc000c31ba0, 0x131e661, ...)
	/Users/ssd/go/src/github.com/jingyugao/rowserrcheck/passes/rowserr/rowserr.go:65 +0x130
github.com/jingyugao/rowserrcheck/passes/rowserr.NewRun.func1(0xc000c31ba0, 0xad729e6, 0x14f1e60, 0xc000c31b18, 0x0)
	/Users/ssd/go/src/github.com/jingyugao/rowserrcheck/passes/rowserr/rowserr.go:46 +0x15c
golang.org/x/tools/go/analysis/unitchecker.run.func5.1()
	/Users/ssd/go/src/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:352 +0x726
sync.(*Once).doSlow(0xc0006e4780, 0xc00004c728)
	/usr/local/Cellar/go/1.15.8/libexec/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/Cellar/go/1.15.8/libexec/src/sync/once.go:57
golang.org/x/tools/go/analysis/unitchecker.run.func5(0xc000191380, 0x0)
	/Users/ssd/go/src/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:304 +0x1bb
golang.org/x/tools/go/analysis/unitchecker.run.func6.1(0xc0004c1100, 0xc0004b7490, 0xc000191380)
	/Users/ssd/go/src/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:364 +0x33
created by golang.org/x/tools/go/analysis/unitchecker.run.func6
	/Users/ssd/go/src/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:363 +0xa5
# github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester
pkg/sql/opt/testutils/opttester/stats_tester.go:240:29: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql/schemachange
pkg/sql/schemachange/alter_column_type_test.go:386:25: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql/pgwire
pkg/sql/pgwire/conn_test.go:1210:31: rows.Err must be checked
pkg/sql/pgwire/conn_test.go:1565:30: rows.Err must be checked
pkg/sql/pgwire/conn_test.go:1570:30: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql/pgwire_test
pkg/sql/pgwire/pgwire_test.go:852:27: rows.Err must be checked
pkg/sql/pgwire/pgwire_test.go:1412:25: rows.Err must be checked
pkg/sql/pgwire/pgwire_test.go:1645:30: rows.Err must be checked
pkg/sql/pgwire/pgwire_test.go:1952:23: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql/rowexec
pkg/sql/rowexec/sample_aggregator_test.go:165:18: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql/tests
pkg/sql/tests/repair_test.go:115:24: rows.Err must be checked
pkg/sql/tests/repair_test.go:222:25: rows.Err must be checked
pkg/sql/tests/repair_test.go:230:24: rows.Err must be checked
pkg/sql/tests/repair_test.go:447:21: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/storage/cloudimpl/filetable/filetabletest
pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go:378:32: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/sql/tests_test
pkg/sql/tests/inverted_index_test.go:68:22: rows.Err must be checked
pkg/sql/tests/monotonic_insert_test.go:195:28: rows.Err must be checked
pkg/sql/tests/rsg_test.go:173:28: rows.Err must be checked
# github.com/cockroachdb/cockroach/pkg/workload/tpcc
pkg/workload/tpcc/checks.go:99:31: rows.Err must be checked
pkg/workload/tpcc/checks.go:112:31: rows.Err must be checked
pkg/workload/tpcc/checks.go:125:28: rows.Err must be checked
pkg/workload/tpcc/checks.go:214:27: rows.Err must be checked
pkg/workload/tpcc/checks.go:226:28: rows.Err must be checked
pkg/workload/tpcc/checks.go:274:30: rows.Err must be checked
pkg/workload/tpcc/checks.go:287:31: rows.Err must be checked
pkg/workload/tpcc/checks.go:310:30: rows.Err must be checked
pkg/workload/tpcc/checks.go:326:31: rows.Err must be checked
```

</details>

**Comment by ajwerner** [comment]
cc @otan you may be interested in this. I went looking for the linter and found our friend @stevendanna.

**Comment by stevendanna** [comment]
We've gotten the panic fixed upstream (there was an existing PR that fixed that problem) and at least one class of false-positives fixed.

**Comment by knz** [comment]
The way to go about this type of linter finding is to break up the findings into different issues, one per team, and assign each sub-issue to the appropriate TL for handling within their area.

A large issue like this will go nowhere because nobody will feel responsible for the bits they don't know about.

**Comment by stevendanna** [comment]
@knz Sounds good. I held off on doing anything like that at the time because the linter itself was too broken to use on a lot of the packages, but now that it is fixed it might be more viable.
