### ISSUE TITLE
circleci: failed tests: TestTxnCoordIdempotentCleanup TestPropagateTxnOnPushError 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6129]
The following test appears to have failed:

[#16489](https://circleci.com/gh/cockroachdb/cockroach/16489):

```
I160418 20:29:43.732666 kv/range_cache.go:569  adding descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160418 20:29:43.733242 kv/range_cache.go:593  clearing overlapping descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160418 20:29:43.733462 kv/range_cache.go:569  adding descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160418 20:29:43.736990 client/db.go:490  failed batch: kv/txn_coord_sender.go:473: writing transaction timed out or ran on multiple coordinators
I160418 20:29:48.724283 kv/txn_coord_sender.go:282  txn coordinator: 0.77 txn/sec, 0.00/0.00/0.00/100.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (1 samples)
--- FAIL: TestTxnCoordIdempotentCleanup (5.07s)
	txn_coord_sender_test.go:767: kv/txn_coord_sender.go:473: writing transaction timed out or ran on multiple coordinators
	<autogenerated>:31: Leaked goroutine: goroutine 1632 [chan receive]:
		github.com/cockroachdb/cockroach/rpc.NewContext.func1()
			/go/src/github.com/cockroachdb/cockroach/rpc/context.go:105 +0x68
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820ac04d0, 0xc820a46740)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70
	<autogenerated>:31: Leaked goroutine: goroutine 1633 [chan receive]:
		github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc820b6dbc0)
--
I160418 20:30:29.231216 kv/dist_sender_server_test.go:631  Waiting for the txn commit
I160418 20:30:29.233420 storage/replica_command.go:611  auto-gc'ed 7f5109c3 (1 intents)
I160418 20:30:29.239579 storage/replica_command.go:611  auto-gc'ed 0e7c60d6 (1 intents)
I160418 20:30:29.242729 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
I160418 20:30:33.796006 kv/txn_coord_sender.go:282  txn coordinator: 0.04 txn/sec, 0.00/0.00/0.00/100.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (1 samples)
--- FAIL: TestPropagateTxnOnPushError (5.58s)
	<autogenerated>:31: Leaked goroutine: goroutine 1667 [select]:
		github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
			/go/src/github.com/cockroachdb/cockroach/storage/store.go:1878 +0xfc7
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820ac04d0, 0xc820adeb00)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70
FAIL
FAIL	github.com/cockroachdb/cockroach/kv	75.935s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestMustSetInner
--- PASS: TestMustSetInner (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestBatchRequestString
--- PASS: TestBatchRequestString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
dupe #6093
