### ISSUE TITLE
spatial: panic caused by SIGFPE: floating-point exception in FrechetDistanceDensify

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#61367]
The RandomSyntax tests seem to have found a query that causes an unhandled panic.

https://teamcity.cockroachdb.com/viewLog.html?buildId=2736928&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests&tab=buildLog&branch_Cockroach_Nightlies=release-20.2#_state=5743

```
fatal error: unexpected signal during runtime execution
[signal SIGFPE: floating-point exception code=0x1 addr=0x7f19fe1025fc pc=0x7f19fe1025fc]

runtime stack:
runtime.throw(0x5384861, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 4096689 [syscall]:
non-Go function
	pc=0x7f19fe1025fc
non-Go function
	pc=0x7f19fe102814
non-Go function
	pc=0x7f19fe103217
non-Go function
	pc=0x7f19fe1034a2
non-Go function
	pc=0x7f19fe6e316d
non-Go function
	pc=0x40bb665
runtime.cgocall(0x40b6990, 0xc001d32c90, 0x770101)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc001d32c48 sp=0xc001d32c10 pc=0x76be1b
github.com/cockroachdb/cockroach/pkg/geo/geos._Cfunc_CR_GEOS_FrechetDistanceDensify(0x7f1a05826000, 0xc027144840, 0x15, 0xc027144880, 0x15, 0x36a0000000000000, 0xc02959acf0, 0x0, 0x0)
	_cgo_gotypes.go:323 +0x50 fp=0xc001d32c90 sp=0xc001d32c48 pc=0x13d9b50
github.com/cockroachdb/cockroach/pkg/geo/geos.FrechetDistanceDensify.func1(0x7f1a05826000, 0xc027144840, 0x15, 0x40, 0xc027144880, 0x15, 0x40, 0x36a0000000000000, 0xc02959acf0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/geo/geos/geos.go:761 +0xd7 fp=0xc001d32d08 sp=0xc001d32c90 pc=0x13e5817
github.com/cockroachdb/cockroach/pkg/geo/geos.FrechetDistanceDensify(0xc027144840, 0x15, 0x40, 0xc027144880, 0x15, 0x40, 0x36a0000000000000, 0x801f500, 0x52e1da7, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/geo/geos/geos.go:761 +0xf8 fp=0xc001d32d98 sp=0xc001d32d08 pc=0x13e15f8
github.com/cockroachdb/cockroach/pkg/geo/geomfn.FrechetDistanceDensify(0x2, 0xc027144840, 0x15, 0x40, 0x100000000, 0xc00418bc00, 0x2, 0xc027144880, 0x15, 0x40, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/geo/geomfn/distance.go:742 +0xf8 fp=0xc001d32fa0 sp=0xc001d32d98 pc=0x19b8d18
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func366(0xc001930518, 0xc0028ba8a0, 0x3, 0x3, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/geo_builtins.go:2900 +0x20d fp=0xc001d330a8 sp=0xc001d32fa0 pc=0x1ff2ded
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval(0xc021ffa280, 0xc001930518, 0x0, 0xc0028ba840, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3904 +0xbc fp=0xc001d33228 sp=0xc001d330a8 pc=0x18cf21c
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).FoldFunction(0xc001930ac0, 0xc0028ba810, 0x3, 0x3, 0xc001d33430, 0x3, 0x4)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/fold_constants_funcs.go:572 +0x237 fp=0xc001d332b8 sp=0xc001d33228 pc=0x238d5f7
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructFunction(0xc001930ab0, 0xc0028ba810, 0x3, 0x3, 0xc001d33430, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:16729 +0x11a fp=0xc001d33330 sp=0xc001d332b8 pc=0x234c7ba
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFunction(0xc012064180, 0xc021ffa100, 0xc001cbdcf0, 0xc001cbdde0, 0xc00e6af0e0, 0x0, 0xc001cbdcf0, 0xc004b54500)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:506 +0x318 fp=0xc001d334e0 sp=0xc001d33330 pc=0x3408838
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar(0xc012064180, 0x5fba580, 0xc021ffa100, 0xc001cbdcf0, 0xc001cbdde0, 0xc00e6af0e0, 0x0, 0x0, 0x0)
```

I can't find the query that caused this.

Hopefully we can fix this error, but also in general are we able to catch exceptions from CGo code?

**Comment by otan** [comment]
this is not really actionable unless we have the query.
why are the queries not being logged?

**Comment by jordanlewis** [comment]
Some ideas based on previous messing around with these geo builtins:

```
emo@127.0.0.1:26257/defaultdb> select st_frechetdistance('POLYGON((0 0, 1 1, 1 1, 0 0))'::geometry, 'POLYGON((0 0, 1 1, 1 1, 0 0))'::geometry, 0.0000000000001);
ERROR: st_frechetdistance(): geos error: std::bad_alloc
demo@127.0.0.1:26257/defaultdb> select st_frechetdistance('POLYGON((0 0, 1 1, 1 1, 0 0))'::geometry, 'POLYGON((0 0, 1 1, 1 1, 0 0))'::geometry, 0.000000000001);
ERROR: st_frechetdistance(): geos error: std::bad_alloc
demo@127.0.0.1:26257/defaultdb> select st_frechetdistance('POLYGON((0 0, 1 1, 1 1, 0 0))'::geometry, 'POLYGON((0 0, 1 1, 1 1, 0 0))'::geometry, 0.00000000001);

<hangs forever>
```

**Comment by jordanlewis** [comment]
It seems like it's very common to run into bad edge conditions with these builtins that has to do with a fraction parameter. I think we've added some limitations to some of them. Can we limit all of these in one fell swoop some how?

**Comment by otan** [comment]
ah i see small fractions maybe.
psql handles this the same way unfortunately :(

**Comment by rafiss** [comment]
I tried more random syntax after https://github.com/cockroachdb/cockroach/pull/61427 got merged and found another query that hangs:

```
SELECT st_frechetdistance('010600000002000000010300000001000000090000008CD246683E8FD44790B0964347CCD3C788D57D25B9EED147D28F7790E93DE3C78E2B0B652066E047406E62543896B0C770A2536D8C71EE4710787E8B61E1C1476E126C204A7DE447D61D5C55FF62E9479CAF289655DADB47B008A52CB4EDDA47944071A0C0E1D547E408F656DCE0E74700182B38A5074CC7D245CE9F51ACE0478CD246683E8FD44790B0964347CCD3C70103000000010000000A0000008B66C4D878DEEEC7BA7E1D56B3A6D1C74C58DD49B0CEC6C70F39D449D0C6E3C7801604C854868BC734433213C2FFD7C7A007D7179C6BACC7BE9DE753847ADEC7564BBABD2932EF479843A6FD0C57E3C78626CA45CDFFEF47827FBB44FBCCE847BCE28DA6ED1DD9479CE254717C1CD14774B3CEFDE379D847941A1711F1B5DF47BC170809E36AD1479A7546095B04E3478B66C4D878DEEEC7BA7E1D56B3A6D1C7':::GEOMETRY, '01030000000100000009000000A78D43D56977E0C720A2839F3B41BDC7847B0AD2E326D347665D41AA4883D6C78A6385E57A1DEB47D4CB20163F31E8C7DED19A2751F0E4472C484C9C2328D4C7A16A183FC24BEAC7D4B369C430B4EC47B46A94CAB140E8C7CE1C64980DE8E9474B961CFDFC34E0C784206F71B806DA47CBC6A9EE82F3EFC780663D34EF1AD147A78D43D56977E0C720A2839F3B41BDC7':::GEOMETRY, 0.011139764577360906:::FLOAT8);
```

**Comment by otan** [comment]
the coordinates are too big.

i don't think realistically we can "stop" these, but when can make RSG not generate such massive coordinates.

@andyyang890 can you change the generator to only generate points in a range of say [-10000, 10000]? these points are 10e38 so yeah they get nasty. also then [backport](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/900005932/Backporting+a+change+to+a+release+branch) this to 20.2.
