### ISSUE TITLE
circleci: failed tests: TestTxnCoordIdempotentCleanup 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6136]
The following test appears to have failed:

[#16502](https://circleci.com/gh/cockroachdb/cockroach/16502):

```
I160418 22:21:44.986483 kv/range_cache.go:569  adding descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160418 22:21:44.986995 kv/range_cache.go:593  clearing overlapping descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160418 22:21:44.987179 kv/range_cache.go:569  adding descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160418 22:21:44.996506 client/db.go:490  failed batch: kv/txn_coord_sender.go:473: writing transaction timed out or ran on multiple coordinators
I160418 22:21:49.978863 kv/txn_coord_sender.go:282  txn coordinator: 0.77 txn/sec, 0.00/0.00/0.00/100.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (1 samples)
--- FAIL: TestTxnCoordIdempotentCleanup (5.03s)
	txn_coord_sender_test.go:767: kv/txn_coord_sender.go:473: writing transaction timed out or ran on multiple coordinators
	<autogenerated>:31: Leaked goroutine: goroutine 1745 [select]:
		github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
			/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x408
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820220850, 0xc82036a6e0)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70
	<autogenerated>:31: Leaked goroutine: goroutine 1774 [chan receive]:
		github.com/cockroachdb/cockroach/rpc.NewContext.func1()
--
I160418 22:22:37.180131 kv/dist_sender_server_test.go:631  Waiting for the txn commit
I160418 22:22:37.182424 storage/replica_command.go:611  auto-gc'ed c5635200 (1 intents)
I160418 22:22:37.188962 storage/replica_command.go:611  auto-gc'ed 9e9f3489 (1 intents)
I160418 22:22:37.192331 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestPropagateTxnOnPushError (0.55s)
FAIL
FAIL	github.com/cockroachdb/cockroach/kv	64.736s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestMustSetInner
--- PASS: TestMustSetInner (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestBatchRequestString
--- PASS: TestBatchRequestString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
dupe #6093
