### ISSUE TITLE
circleci: failed tests: TestTxnCoordIdempotentCleanup TestTxnRestartedSerializableTimestampRegression 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6184]
The following test appears to have failed:

[#16586](https://circleci.com/gh/cockroachdb/cockroach/16586):

```
I160420 18:49:19.111611 kv/range_cache.go:569  adding descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160420 18:49:19.112398 kv/range_cache.go:593  clearing overlapping descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160420 18:49:19.112717 kv/range_cache.go:569  adding descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160420 18:49:19.116958 client/db.go:490  failed batch: kv/txn_coord_sender.go:473: writing transaction timed out or ran on multiple coordinators
I160420 18:49:24.101993 kv/txn_coord_sender.go:282  txn coordinator: 0.77 txn/sec, 0.00/0.00/0.00/100.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (1 samples)
--- FAIL: TestTxnCoordIdempotentCleanup (5.07s)
	txn_coord_sender_test.go:767: kv/txn_coord_sender.go:473: writing transaction timed out or ran on multiple coordinators
	<autogenerated>:31: Leaked goroutine: goroutine 1708 [select]:
		github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).startStats(0xc8205f2780)
			/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:239 +0x10d4
		github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).(github.com/cockroachdb/cockroach/kv.startStats)-fm()
			/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:224 +0x2e
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820294150, 0xc82058a040)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70
--
I160420 18:49:53.941512 storage/replica_command.go:611  auto-gc'ed f4df7c55 (2 intents)
I160420 18:49:53.942047 stopper.go:352  draining; tasks left:
1      kv/txn_coord_sender.go:893
I160420 18:49:53.943282 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
I160420 18:49:54.126685 kv/txn_coord_sender.go:282  txn coordinator: 0.10 txn/sec, 0.00/0.00/0.00/100.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (1 samples)
--- FAIL: TestTxnRestartedSerializableTimestampRegression (5.08s)
	<autogenerated>:31: Leaked goroutine: goroutine 1754 [select]:
		github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc82022a2a0, 0xecea9c62f, 0x685da84, 0x2a393c0, 0xc8206c80c0, 0xc820294150, 0xc8201242a0, 0x60abec)
			/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:162 +0x6a2
		github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc8201242a0, 0xc8202c2540)
			/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:204 +0xf6
		github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc8202c23f0, 0xc82053c580)
			/go/src/github.com/cockroachdb/cockroach/storage/store.go:237 +0x46b
		github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
			/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:206 +0x33b
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820294150, 0xc8206bc920)
--
I160420 18:50:14.345471 /go/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:39696: getsockopt: connection refused"; Reconnecting to "127.0.0.1:39696"
I160420 18:50:14.345828 /go/src/google.golang.org/grpc/clientconn.go:317  Failed to dial 127.0.0.1:39696: grpc: timed out trying to connect; please retry.
I160420 18:50:14.346082 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
I160420 18:50:14.346265 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestRequestToUninitializedRange (3.33s)
FAIL
FAIL	github.com/cockroachdb/cockroach/kv	67.047s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestMustSetInner
--- PASS: TestMustSetInner (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestBatchRequestString
--- PASS: TestBatchRequestString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
fixed by #6173
