### ISSUE TITLE
bench: package ./pkg/ccl/importccl fails benchmarking

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#62085]
```
make bench PKG=./pkg/ccl/importccl
```

This results in a crash in `BenchmarkConvertToKVs`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6f41383]

goroutine 7028 [running]:
github.com/cockroachdb/cockroach/pkg/sql.NewTableDesc(0x9621b48, 0xc000074120, 0x0, 0x97425b8, 0xc0019724b8, 0x0, 0xc003cfa1e0, 0x1d00000031, 0xd8ba058700000032, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/pkg/sql/create_table.go:1551 +0x2c3
github.com/cockroachdb/cockroach/pkg/ccl/importccl.MakeSimpleTableDescriptor(0x9621b48, 0xc000074120, 0xc002650300, 0x0, 0xc003cfa1e0, 0x1d00000031, 0x32, 0x0, 0xc000fd5c50, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_table_creation.go:158 +0xa85
github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/format.ToTableDescriptor(0x8290fb2, 0x9, 0xc0006a6f00, 0x165, 0x1, 0xc00fdc80c0, 0x0, 0x0, 0xc002026000, 0x9, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/format/sstable.go:47 +0x2e7
github.com/cockroachdb/cockroach/pkg/ccl/importccl_test.benchmarkConvertToKVs(0xc00276c480, 0x95def88, 0xc001d28000)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/bench_test.go:170 +0x2f3
github.com/cockroachdb/cockroach/pkg/ccl/importccl_test.BenchmarkConvertToKVs.func1(0xc00276c480)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/bench_test.go:158 +0x3d
testing.(*B).runN(0xc00276c480, 0x1)
	/Users/nathan/Go/go/src/testing/benchmark.go:192 +0xeb
testing.(*B).run1.func1(0xc00276c480)
	/Users/nathan/Go/go/src/testing/benchmark.go:232 +0x57
created by testing.(*B).run1
	/Users/nathan/Go/go/src/testing/benchmark.go:225 +0x7f
exit status 2
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/importccl	19.488s
```

Jira issue: CRDB-2679

**Comment by yuzefovich** [comment]
Running the benchmarks of `pkg/sql/importer` no longer fails.
