### ISSUE TITLE
build: `make bazel-generate` fails on my machine

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#62146]
This occurs today -- it used to work two weeks ago:

```
kena@kenax ....com/cockroachdb/cockroach % bx gmake bazel-generate
TMPDIR set to /tmp/tmp.uZSoZnnE
Running make with -j32
GOPATH set to /data/home/kena/src/go
Generating DEPS.bzl and BUILD files using gazelle
./build/bazelutil/bazel-generate.sh
+ bazel run //:gazelle -- update-repos -from_file=go.mod -build_file_proto_mode=disable_global -to_macro=DEPS.bzl%go_deps -prune=true
Starting local Bazel server and connecting to it...
INFO: Repository llvm_toolchain instantiated at:
  /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/WORKSPACE:151:15: in <toplevel>
Repository rule llvm_toolchain defined at:
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 55, column 42, in llvm_toolchain_impl
                sysroot_path, sysroot = _sysroot_path(rctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/sysroot.bzl", line 39, column 13, in sysroot_path
                fail("Unsupported OS: " + rctx.os.name)
Error in fail: Unsupported OS: freebsd
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 55, column 42, in llvm_toolchain_impl
                sysroot_path, sysroot = _sysroot_path(rctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/sysroot.bzl", line 39, column 13, in sysroot_path
                fail("Unsupported OS: " + rctx.os.name)
Error in fail: Unsupported OS: freebsd
ERROR: no such package '@llvm_toolchain//': Unsupported OS: freebsd
INFO: Elapsed time: 3.266s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
gmake: *** [Makefile:1794: bazel-generate] Error 1
command failed (2); temp files in /tmp/tmp.uZSoZnnE
```

**Comment by knz** [comment]
cc @rail @rickystewart for triage

**Comment by knz** [comment]
The code in that file, btw, is complete nonsense:

```python
def sysroot_path(rctx):
    if rctx.os.name == "linux":
        sysroot = rctx.attr.sysroot.get("linux", default = "")
    elif rctx.os.name == "mac os x":
        sysroot = rctx.attr.sysroot.get("darwin", default = "")
    else:
        fail("Unsupported OS: " + rctx.os.name)
```

The idea to hardcode just 2 OS strings and fail at the unknown is nonsense. The proper code should look like this:

```python
   osstring = rctx.os.name
   if osstring = "mac os x": osstring = "darwin"
   sysroot = rctx.attr.sysroot.get(osstring, default = "")
```

As usual, Apple is ruining open source for everyone else... :angry:

**Comment by knz** [comment]
IF I fix this manually I encounter the next stage of utter nonsense:

```
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 109, column 26, in llvm_toolchain_impl
                if not _download_llvm(rctx):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 206, column 13, in download_llvm
                fail("Unsupported OS: " + rctx.os.name)
Error in fail: Unsupported OS: freebsd
```

Again, the person who wrote this code is a fool:

```python
def download_llvm(rctx):
    if rctx.os.name == "linux":
        urls = rctx.attr.urls.get("linux", default = [])
        sha256 = rctx.attr.sha256.get("linux", default = "")
        prefix = rctx.attr.strip_prefix.get("linux", default = "")
    elif rctx.os.name == "mac os x":
        urls = rctx.attr.urls.get("darwin", default = [])
        sha256 = rctx.attr.sha256.get("darwin", default = "")
        prefix = rctx.attr.strip_prefix.get("darwin", default = "")
    else:
        fail("Unsupported OS: " + rctx.os.name)
```

This makes no sense again, as this uncodnitional code completely works:

```python
        urls = rctx.attr.urls.get(rctx.os.name, default = [])
        sha256 = rctx.attr.sha256.get(rctx.os.name, default = "")
        prefix = rctx.attr.strip_prefix.get(rctx.os.name, default = "")
```

**Comment by knz** [comment]
After I fix this, I get the next wave of nonsense garbage:

```
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
                _download_llvm_preconfigured(rctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 164, column 20, in download_llvm_preconfigured
                _python(rctx),
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 153, column 13, in _python
                fail("python not found")
```

Which makes no sense whatsoever:

```
kena@kenax ....com/cockroachdb/cockroach % which python
/data/home/kena/bin/python
```

That is, this code is not properly checking `$PATH` (or not properly downloading its python dependency in its sandbox)

**Comment by knz** [comment]
After I fix this manually I get another error message:

```
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
                _download_llvm_preconfigured(rctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 159, column 17, in download_llvm_preconfigured
                fail("Failed to detect host OS version: \n%s\n%s" % (exec_result.stdout, exec_result.stderr))
Error in fail: Failed to detect host OS version:

Unsupported system: FreeBSD
```

This one stumps me - where is the code that generates this error message?

It's very confusing because the source file (`llvm_distributions.bzl`) does list all the binary archives for freebsd, so it should know how to download them too.

**Comment by knz** [comment]
@rickystewart I guess the questions I need to ask is this:

1. what is the magic incantation I need to simply bypass the sandbox and use the llvm provided by my host system (The ability to bypass the sandbox for manual build has been a prereq of this project since the beginning, so I assume this is already documented somewhere, I just haven't found how yet)

2. why is this even needed to run `make bazel-generate` -- that command should merely populate BUILD.bzl file and I do not understand why it needs to download/use LLVM to do so.

**Comment by otan** [comment]
> why is this even needed to run make bazel-generate -- that command should merely populate BUILD.bzl file and I do not understand why it needs to download/use LLVM to do so.

make bazel-generate invokes bazel to download gazel into it's sandbox before it can run it.
i think in the meantime you can comment out this line

https://github.com/cockroachdb/cockroach/blob/7894414edfd430fc1ce3e7cc9162b6ba51395618/WORKSPACE#L159

**Comment by knz** [comment]
That PR—#61274— says that the pinning occurs only if the user manually opts in via `.bazelrc.user`.  I do not have such a file. Why is the behavior enabled automatically then?

**Comment by otan** [comment]
pinning != registering the resources apparently (i don't think it's lazily loaded)

**Comment by knz** [comment]
I had to remove the entire `llvm_toolchain` block to get it to work:

```
#llvm_toolchain(
#    name = "llvm_toolchain",
#    absolute_paths = True,
#    llvm_version = "10.0.0",
#)

#load("@llvm_toolchain//:toolchains.bzl", "llvm_register_toolchains")
```

I was able to keep `bazel_toolchain_dependencies()` - that one works fine apparently.

**Comment by knz** [comment]
Is there a way to have a conditional statement inside the `WORKSPACE` file, conditional on e.g. a command-line flag?

**Comment by otan** [comment]
you'll need to make like LLVM.bzl, and have something like

```
# relevant imports here

def crdb_llvm_toolchain():
   if rctx.os.name == "freebsd": return

   llvm_toolchain(
    name = "llvm_toolchain",
    absolute_paths = True,
    llvm_version = "10.0.0",
   )
   llvm_register_toolchains()
```

and then call `crdb_llvm_toolchain` from WORKSPACE. if that works, feel free to send a PR my way

**Comment by rickystewart** [comment]
llvm_toolchain is dead now.
