### ISSUE TITLE
builtins: st_union panics when a collection contains an EMPTY

### ISSUE THREAD

**Issue by andyyang890** [cockroachdb/cockroach#62184]
See also: https://trac.osgeo.org/geos/ticket/1110#ticket

**Describe the problem**

The following steps cause a panic:

```
create table t(a geometry);

insert into t values
	('POLYGON Z ((-8576813007.651572 -932867148.5664893 -594332188.2168996, -9076378702.816006 -1058770692.353365 -2286612467.79976, -8577214214.487094 -923078893.7098079 -922845555.2543786, -8763948942.517227 3632693707.16387 -1890400776.3303413, -7612818442.454826 3813396489.705141 -376275881.4206352, -4258868082.9764023 2821219037.959036 -7927470779.677084, -2376927148.576969 762393778.6277254 -5185416958.8125515, 8374297972.826973 3684983643.201231 -3159751777.281743, -2311638561.4350195 690968693.0169502 -2246826599.5283184, 3511882417.12018 -5679907177.601899 -7190612231.893617, -8305726872.755655 -7546563480.596777 3891638858.362171, -8576813007.651572 -932867148.5664893 -594332188.2168996))'::geometry),
	('GEOMETRYCOLLECTION ZM (MULTIPOINT ZM (-572200857.2088509 7909820002.898613 -5497698646.885041 6664440051.466028, -429525248.49892807 9279013845.258144 1865812608.4202595 -5627983850.52976, -8961875736.194313 -3646093887.306757 6114061050.084791 7928242422.52462, -1658395500.6136656 5463281975.551853 1226372454.8883152 -6033337335.334749, EMPTY), LINESTRING ZM (5640013450.60927 -4034194887.4798727 7233778169.767132 -8214889161.72134, 9862309549.538734 5014594919.08839 -925144949.3365879 -5659691769.45695), MULTIPOLYGON ZM EMPTY, MULTIPOINT ZM (EMPTY, 4481472784.121752 -8278911850.336457 6955040725.022459 4792703658.978086, EMPTY))'::geometry);

select st_union(a) from t;
```

The panic seems to result from a segfault from the `CR_GEOS_Union` function.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x182157d6]

runtime stack:
runtime.throw(0x8704d39, 0x2a)
	/usr/local/opt/go/libexec/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/opt/go/libexec/src/runtime/signal_unix.go:726 +0x48c

goroutine 1814 [syscall]:
_ZN4geos9algorithm12PointLocator15computeLocationERKNS_4geom10CoordinateEPKNS2_8GeometryE
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x182157d7
_ZN4geos9algorithm12PointLocator15computeLocationERKNS_4geom10CoordinateEPKNS2_8GeometryE
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x182159d3
_ZN4geos9algorithm12PointLocator15computeLocationERKNS_4geom10CoordinateEPKNS2_8GeometryE
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x182159d3
_ZN4geos9algorithm12PointLocator6locateERKNS_4geom10CoordinateEPKNS2_8GeometryE
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x18215501
_ZN4geos9operation7overlay9OverlayOp19labelIncompleteNodeEPNS_9geomgraph4NodeEi
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x18298494
_ZN4geos9operation7overlay9OverlayOp20labelIncompleteNodesEv
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x182983e2
_ZN4geos9operation7overlay9OverlayOp14computeOverlayENS2_6OpCodeE
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x182974b6
_ZN4geos9operation7overlay9OverlayOp9overlayOpEPKNS_4geom8GeometryES6_NS2_6OpCodeE
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x18296bbf
_ZN4geos4geom8BinaryOpINS_9operation7overlay9overlayOpEEENSt3__110unique_ptrINS0_8GeometryENS5_14default_deleteIS7_EEEEPKS7_SC_T_
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x18221351
_ZNK4geos4geom8Geometry5UnionEPKS1_
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos.dylib:0 pc=0x18221f38
GEOSUnion_r
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/lib/libgeos_c.dylib:0 pc=0x17fcb432
CR_GEOS_Union
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/./cockroach:0 pc=0x7a4ac21
_cgo_11f633bdbd71_Cfunc_CR_GEOS_Union
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/./cockroach:0 pc=0x7a451d2
runtime.cgocall(0x7a451a0, 0xc0035d5308, 0x4000001)
	/usr/local/opt/go/libexec/src/runtime/cgocall.go:133 +0x5b fp=0xc0035d52c0 sp=0xc0035d5288 pc=0x40077bb
github.com/cockroachdb/cockroach/pkg/geo/geos._Cfunc_CR_GEOS_Union(0xed3b000, 0xc003362000, 0x12d, 0xc00336212d, 0x195, 0xc003b53550, 0x0, 0x0)
	_cgo_gotypes.go:902 +0x4d fp=0xc0035d5308 sp=0xc0035d52c0 pc=0x54d17ed
github.com/cockroachdb/cockroach/pkg/geo/geos.Union.func1(0xed3b000, 0xc003362000, 0x12d, 0x12d, 0xc00336212d, 0x195, 0x195, 0xc003b53550, 0xc001257d60, 0x94aee20)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/geo/geos/geos.go:533 +0xfd fp=0xc0035d5378 sp=0xc0035d5308 pc=0x54db6bd
github.com/cockroachdb/cockroach/pkg/geo/geos.Union(0xc003362000, 0x12d, 0x12d, 0xc00336212d, 0x195, 0x195, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/geo/geos/geos.go:533 +0xd3 fp=0xc0035d5400 sp=0xc0035d5378 pc=0x54d5313
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.(*stUnionAgg).Add(0xc0027bb900, 0x94aee20, 0xc001d8f018, 0x95d42e0, 0xc0031dc030, 0x0, 0x0, 0x0, 0xc0035d5601, 0x6495ec5)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/aggregate_builtins.go:819 +0x450 fp=0xc0035d5620 sp=0xc0035d5400 pc=0x585c3f0
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecagg.(*defaultOrderedAgg).Compute.func1()
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecagg/ordered_default_agg.eg.go:84 +0x542 fp=0xc0035d5730 sp=0xc0035d5620 pc=0x65e1142
github.com/cockroachdb/cockroach/pkg/sql/colmem.(*Allocator).PerformOperation(0xc002430960, 0xc0035d5790, 0x1, 0x1, 0xc0035d57a0)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:298 +0x59 fp=0xc0035d5768 sp=0xc0035d5730 pc=0x64c8ed9
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecagg.(*defaultOrderedAgg).Compute(0xc001e3fa70, 0xc003b53530, 0x1, 0x1, 0xc0022c3248, 0x1, 0x2, 0x1, 0x0, 0x0, ...)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecagg/ordered_default_agg.eg.go:53 +0x10d fp=0xc0035d57f8 sp=0xc0035d5768 pc=0x65c196d
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*defaultAggregatorHelper).performAggregation(0xc00072cbd8, 0x94aee20, 0xc001d8f838, 0xc003b53530, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/aggregators_util.go:114 +0x102 fp=0xc0035d5878 sp=0xc0035d57f8 pc=0x680a1c2
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*orderedAggregator).Next(0xc00335e000, 0x94aee20, 0xc001d8f838, 0x400, 0x0)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/ordered_aggregator.go:243 +0x407 fp=0xc0035d59c8 sp=0xc0035d5878 pc=0x6826227
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next(0xc004584fc0, 0x94aee20, 0xc001d8f838, 0x0, 0x0)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:91 +0x5d fp=0xc0035d5a18 sp=0xc0035d59c8 pc=0x6e66dfd
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next(0xc0006a8600, 0xc0035d5a70, 0x6e73b3c, 0xc00335e000)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:273 +0x163 fp=0xc0035d5a50 sp=0xc0035d5a18 pc=0x6824c83
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter(...)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:298
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter-fm()
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:297 +0x2f fp=0xc0035d5a88 sp=0xc0035d5a50 pc=0x68996ef
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0xc0035d5ad0, 0x0, 0x0)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91 +0x57 fp=0xc0035d5ab8 sp=0xc0035d5a88 pc=0x64c2157
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next(0xc0006a8600, 0x94aee20, 0xc001d8f838, 0x6899660, 0x16d9c080)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:304 +0x5b fp=0xc0035d5af0 sp=0xc0035d5ab8 pc=0x6824ddb
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run(0x94aee20, 0xc001d8f838, 0x94b5620, 0xc0006a8600, 0x9458060, 0xc0023b1880)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:171 +0x35 fp=0xc0035d5b30 sp=0xc0035d5af0 pc=0x5f8cc35
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run(0xc0006a8600, 0x948f3a0, 0xc0027bb700)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:774 +0x96 fp=0xc0035d5b70 sp=0xc0035d5b30 pc=0x5f93ab6
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc00286f320, 0x948f3a0, 0xc0027bb700, 0x8d4bba0, 0x0, 0x0)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:382 +0x2e2 fp=0xc0035d5c18 sp=0xc0035d5b70 pc=0x61eac62
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00114b4a0, 0xc002ad0620, 0xc001e3f830, 0xc003967080, 0xc0023b1880, 0xc0023dece8, 0x0, 0x0)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:370 +0x492 fp=0xc0035d60d0 sp=0xc0035d5c18 pc=0x7072832
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00114b4a0, 0x94aee20, 0xc001d8f018, 0xc0023dece8, 0xc002ad0620, 0xc001e3f830, 0x94910a0, 0xc001e3f8c0, 0x0, 0xc0023b1880, ...)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:979 +0x1d2 fp=0xc0035d6148 sp=0xc0035d60d0 pc=0x7075f92
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc0023de600, 0x94aee20, 0xc001d8f018, 0xc0023dead0, 0x3, 0x16d93178, 0xc001ed9c80, 0xc0035d6301, 0xc0005eefb8, 0x0, ...)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1040 +0x428 fp=0xc0035d6228 sp=0xc0035d6148 pc=0x70078c8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0023de600, 0x94aee20, 0xc001d8f018, 0xc0023dead0, 0x16d93178, 0xc001ed9c80, 0x0, 0x0)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:912 +0x75b fp=0xc0035d64e8 sp=0xc0035d6228 pc=0x70068db
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0023de600, 0x94aee20, 0xc001d8f018, 0x94adce0, 0xc0024438b0, 0xc0028cfb63, 0x19, 0x0, 0x1, 0x0, ...)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:656 +0xf86 fp=0xc0035d72b0 sp=0xc0035d64e8 pc=0x7003466
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0023de600, 0x948f3a0, 0xc0027bb400, 0x94adce0, 0xc0024438b0, 0xc0028cfb63, 0x19, 0x0, 0x1, 0x0, ...)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:120 +0xb14 fp=0xc0035d77e0 sp=0xc0035d72b0 pc=0x7001dd4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0x94adce0, 0xc0024438b0, 0xc0028cfb63, 0x19, 0x0, 0x1, 0x59b64f0, 0xed7e49ae3, 0x0, 0x59b6cc0, ...)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1514 +0x225 fp=0xc0035d78a0 sp=0xc0035d77e0 pc=0x71b5025
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc0023de600, 0x948f3a0, 0xc0027bb400, 0x0, 0x0)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1516 +0x1413 fp=0xc0035d7cc8 sp=0xc0035d78a0 pc=0x6ff7333
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0023de600, 0x948f3a0, 0xc002ae82c0, 0xc00180d4a0, 0x5400, 0x15000, 0xc00180d540, 0xc002404f40, 0x0, 0x0)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1437 +0x228 fp=0xc0035d7d68 sp=0xc0035d7cc8 pc=0x6ff5ca8
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0007a7080, 0x948f3a0, 0xc002ae82c0, 0xc0023de600, 0x5400, 0x15000, 0xc00180d540, 0xc002404f40, 0x0, 0x0)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:482 +0xce fp=0xc0035d7df0 sp=0xc0035d7d68 pc=0x6ff174e
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc0022c3050, 0xc0028a5f80, 0x948f3a0, 0xc002ae82c0, 0xc002404f40, 0xc0007a7080, 0xc001ed9600, 0x94f5bc0, 0xc002094100, 0xc002098480, ...)
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:625 +0x3ea fp=0xc0035d7f38 sp=0xc0035d7df0 pc=0x768762a
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0035d7f40 sp=0xc0035d7f38 pc=0x4074041
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/Users/andyyang/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:553 +0x185
```

**To Reproduce**

See above.

**Expected behavior**

Query should not cause a panic.

Jira issue: CRDB-2828

**Comment by otan** [comment]
https://trac.osgeo.org/osgeo4w/ticket/668#ticket

**Comment by rafiss** [comment]
IDK if related, but I also saw a panic in `Intersects`: https://teamcity.cockroachdb.com/viewLog.html?buildId=2785150&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests&tab=buildLog&branch_Cockroach_Nightlies=%3Cdefault%3E

it seems like these can't be caught as normal panics?

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fb0c9341391]

_ZN4geos9algorithm12PointLocator6locateERKNS_4geom10CoordinateEPKNS2_5PointE
	pc=0x7fb0c9341391
_ZN4geos9algorithm12PointLocator15computeLocationERKNS_4geom10CoordinateEPKNS2_8GeometryE
	pc=0x7fb0c9341671
_ZN4geos9algorithm12PointLocator15computeLocationERKNS_4geom10CoordinateEPKNS2_8GeometryE
	pc=0x7fb0c934184f
_ZN4geos9algorithm12PointLocator6locateERKNS_4geom10CoordinateEPKNS2_8GeometryE
	pc=0x7fb0c9341918
_ZN4geos9operation6relate14RelateComputer17labelIsolatedNodeEPNS_9geomgraph4NodeEi
	pc=0x7fb0c93cc8c0
_ZN4geos9operation6relate14RelateComputer18labelIsolatedNodesEv
	pc=0x7fb0c93cc9dc
_ZN4geos9operation6relate14RelateComputer9computeIMEv
	pc=0x7fb0c93cd73e
_ZN4geos9operation6relate8RelateOp21getIntersectionMatrixEv
	pc=0x7fb0c93ce408
_ZN4geos9operation6relate8RelateOp6relateEPKNS_4geom8GeometryES6_
	pc=0x7fb0c93ce469
_ZNK4geos4geom8Geometry6relateEPKS1_
	pc=0x7fb0c934c561
_ZNK4geos4geom8Geometry10intersectsEPKS1_
	pc=0x7fb0c934cc0f
runtime.cgocall(0x3f581e0, 0xc000dd2dd8, 0x450101)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000dd2d90 sp=0xc000dd2d58 pc=0x44931b
github.com/cockroachdb/cockroach/pkg/geo/geos._Cfunc_CR_GEOS_Intersects(0x7fb1010f8000, 0xc000a9ef20, 0xf1, 0xc0010ded00, 0x12d, 0xc0125d8a70, 0x0, 0x0)
	_cgo_gotypes.go:448 +0x4d fp=0xc000dd2dd8 sp=0xc000dd2d90 pc=0x18c9ecd
github.com/cockroachdb/cockroach/pkg/geo/geos.Intersects.func1(0x7fb1010f8000, 0xc000a9ef20, 0xf1, 0x148, 0xc0010ded00, 0x12d, 0x1a0, 0xc0125d8a70, 0x181b50b, 0xc000dd2f10)
	/go/src/github.com/cockroachdb/cockroach/pkg/geo/geos/geos.go:764 +0xc8 fp=0xc000dd2e48 sp=0xc000dd2dd8 pc=0x18d6e88
github.com/cockroachdb/cockroach/pkg/geo/geos.Intersects(0xc000a9ef20, 0xf1, 0x148, 0xc0010ded00, 0x12d, 0x1a0, 0xc000dd2f50, 0x14b467cf, 0x13b5e81cf1e4d398)
	/go/src/github.com/cockroachdb/cockroach/pkg/geo/geos/geos.go:764 +0xd3 fp=0xc000dd2ed0 sp=0xc000dd2e48 pc=0x18d1a93
github.com/cockroachdb/cockroach/pkg/geo/geomfn.Intersects(0x2, 0xc000a9ef20, 0xf1, 0x148, 0x4000000400000000, 0xc00b5e4220, 0x2, 0xc0010ded00, 0x12d, 0x1a0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/geo/geomfn/binary_predicates.go:108 +0x1d8 fp=0xc000dd30e0 sp=0xc000dd2ed0 pc=0x18e7578
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.geometryOverload2BinaryPredicate.func1(0xc0017bace8, 0xc002753740, 0xc002753890, 0x5b1ed20, 0xc002753890, 0x2, 0x1)
```

**Comment by otan** [comment]
related since ST_Union calls ST_Intersects underneath.

i don't know how to catch panics in cgo -- if you find a way i'd be *very* curious to hear it!

**Comment by rafiss** [comment]
good points! i see @andyyang890 just merged https://github.com/cockroachdb/cockroach/commit/8f7160247bceb06488f6b234518358e1c54d1620 so we shouldn't see the error in these tests now :)

**Comment by otan** [comment]
oops, ticket is https://trac.osgeo.org/geos/ticket/1110#ticket

**Comment by otan** [comment]
fixed by GEOS upgrade
