### ISSUE TITLE
Upsert with regional by row table not working as expected:

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#63109]
Repro:

Start cockroach w/ 
`./cockroach start-single-node   --locality=region=test-region`

```
create table multi (a int, b string);
alter table multi set locality regional by row;
insert into multi values (1, 'one');

-- this works fine
update multi set b='minus one' where a=1;

-- this returns an error -- it shouldn't
upsert into multi values (1, 'back to one');
ERROR: missing "crdb_region" primary key column

-- Explicitly specifying region also does not work either
upsert into multi (crdb_region, a,b) values ('test-region', 1, 'back to one');

-- this works however:
upsert into multi (a,b) values (1, 'back to one');

```

**Comment by otan** [comment]
cc @rytaft in case you have a clue

looks like the default expr for upsert does not trigger?

```
goroutine 9031 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/opt/go@1.15/libexec/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/opt/go@1.15/libexec/src/runtime/debug/stack.go:16 +0x25
github.com/cockroachdb/cockroach/pkg/sql/row.MakeInserter(0x952b800, 0xc01579ba80, 0xc0140f5d40, 0xc0013acf40, 0xc0013acf40, 0x0, 0x969f120, 0xc00a8f1200, 0xb8d4ea8, 0x0, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/inserter.go:70 +0x445
github.com/cockroachdb/cockroach/pkg/sql/row.MakeUpdater(0x952b800, 0xc01579ba80, 0xc0140f5d40, 0xc0013acf40, 0xc0013acf40, 0x0, 0x969f120, 0xc00a8f1200, 0xc0150cc900, 0x3, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/updater.go:184 +0x953
github.com/cockroachdb/cockroach/pkg/sql.(*execFactory).ConstructUpsert(0xc015799ce0, 0x83156e0, 0xc015793ae0, 0x967ef00, 0xc00f936280, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go:1469 +0x490
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.(*Factory).ConstructUpsert(0xc015799cf0, 0x826c780, 0xc0095b9280, 0x967ef00, 0xc00f936280, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/explain_factory.og.go:1090 +0x3e3
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildUpsert(0xc00dff2540, 0xc0140bef90, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00b607850, 0x9584580)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/mutation.go:444 +0x6a6
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildRelational(0xc00dff2540, 0x9670200, 0xc0140bef90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0157a5c70)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:254 +0x27be
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).build(0xc00dff2540, 0x9555700, 0xc0140bef90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:173 +0x256
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).Build(0xc00dff2540, 0xc00dff2540, 0xc0140bef90, 0x9555700, 0xc0140bef90)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:135 +0x71
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildExplain.func1(0x9692740, 0xc015799cf0, 0xb8d4ea8, 0x0, 0x0, 0xb80b0a0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/statement.go:128 +0x1cb
github.com/cockroachdb/cockroach/pkg/sql.(*execFactory).ConstructExplain(0xc015799cc0, 0xc0157b3160, 0x2, 0xc005bf7960, 0x0, 0x0, 0x0, 0x0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go:1913 +0xbd
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.(*Factory).ConstructExplain(0xc015799cd0, 0xc0157b3160, 0x2, 0xc005bf7960, 0x400efff, 0x400efff, 0xc00004e000, 0x81978a0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/explain_factory.og.go:886 +0x113
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildExplain(0xc00dff2480, 0xc0157b3150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/statement.go:121 +0xd5
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildRelational(0xc00dff2480, 0x966e860, 0xc0157b3150, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0157b2fc0, 0xc0157b31b8)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:275 +0x21fe
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).build(0xc00dff2480, 0x9553340, 0xc0157b3150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:173 +0x256
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).Build(0xc00dff2480, 0xc00dff2480, 0x10, 0xed03748, 0xc015799cc0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:135 +0x71
github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).runExecBuilder(0xc00b6077f8, 0xc00b607608, 0xc00b6070e8, 0x96921a0, 0xc015799cc0, 0xc00cea08c0, 0xc00b6072f0, 0xc005bf7401, 0xc019126118, 0x53a6602)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:566 +0x1ae
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc00b6070d8, 0x952b8c0, 0xc0157a7dd0, 0x2ae333c8, 0x2ae333c800000000)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:262 +0x1ac
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan(0xc00b606c00, 0x952b8c0, 0xc0157a7dd0, 0xc00b6070d8, 0xc0157a5b80, 0x0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:937 +0x5a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00b606c00, 0x952b8c0, 0xc0157a7dd0, 0xc00b6070d8, 0x18d16198, 0xc00bbecf80, 0x0, 0x0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:818 +0x18a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00b606c00, 0x952b8c0, 0xc0157a7dd0, 0x9549600, 0xc005bf7460, 0xc00c8bc4cb, 0x33, 0x0, 0x1, 0x0, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:656 +0xf86
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00b606c00, 0x952b800, 0xc01579ba80, 0x9549600, 0xc005bf7460, 0xc00c8bc4cb, 0x33, 0x0, 0x1, 0x0, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:120 +0xb14
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0x9549600, 0xc005bf7460, 0xc00c8bc4cb, 0x33, 0x0, 0x1, 0x2ae11ca0, 0xed7fd7f39, 0x0, 0x2ae12470, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1527 +0x225
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00b606c00, 0x952b800, 0xc01579ba80, 0x0, 0x0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1529 +0x1457
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00b606c00, 0x952b800, 0xc00c60b080, 0xc00079d9a0, 0x5400, 0x15000, 0xc00079da40, 0xc00c612650, 0x0, 0x0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1450 +0x228
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc00044fb80, 0x952b800, 0xc00c60b080, 0xc00b606c00, 0x5400, 0x15000, 0xc00079da40, 0xc00c612650, 0x0, 0x0)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:484 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00c600910, 0xc00c61f5c0, 0x952b800, 0xc00c60b080, 0xc00c612650, 0xc00044fb80, 0xc00bbec900, 0x9592aa0, 0xc008c4e500, 0xc00c72cc00, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:626 +0x3ea
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:554 +0x185
ERROR: missing "crdb_region" primary key column
```

**Comment by otan** [comment]
(i'm guessing some part of #59654 is related)
