### ISSUE TITLE
storage: TestStoreRangeRemoveDead is flaky

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6319]
https://circleci.com/gh/cockroachdb/cockroach/16885

Test is sitting on its WaitGroup:

```
goroutine 14692 [semacquire]:
sync.runtime_Semacquire(0xc82139f62c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82139f620)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/storage_test.TestStoreRangeRemoveDead(0xc821691ef0)
	/go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:1168 +0x617
testing.tRunner(0xc821691ef0, 0x23ab710)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
```

```
I160426 14:50:28.310914 kv/txn_coord_sender.go:286  txn coordinator: 0.05 txn/sec, 100.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (2 samples)
I160426 14:50:28.312368 kv/txn_coord_sender.go:286  txn coordinator: 0.00 txn/sec, 0.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (0 samples)
I160426 14:50:28.327542 kv/txn_coord_sender.go:286  txn coordinator: 0.00 txn/sec, 0.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (0 samples)
panic: test timed out after 1m10s

goroutine 14940 [running]:
panic(0x14e9560, 0xc820cae540)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a
```

**Comment by tschottdorf** [comment]
https://circleci.com/gh/cockroachdb/cockroach/17533?utm_campaign=build-failed&utm_medium=email&utm_source=notification

**Comment by andreimatei** [comment]
Ben, your name is all over this test. It repros easily in 200 iterations with `stress` and any timeout.

**Comment by bdarnell** [comment]
I touched it last but I think @BramGruneir was the original author

**Comment by d4l3k** [comment]
I just ran into this issue locally.

**Comment by BramGruneir** [comment]
I'll take a look shortly.  Got a few flaky tests I need to tackle.
