### ISSUE TITLE
sql/tests: TestRandomSyntaxSchemaChangeColumn failed

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#63393]
[sql/tests.TestRandomSyntaxSchemaChangeColumn failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2862755&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2862755&tab=artifacts#/) on [master @ 9a335c3b2eaac8a5b36ed4e4299be0bbb3d9f548](https://github.com/cockroachdb/cockroach/commits/9a335c3b2eaac8a5b36ed4e4299be0bbb3d9f548):

```
[14:52:40]
[post issues]
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0xfc
[14:52:40]
[post issues]         
[14:52:40]
[post issues]         goroutine 8553553 [select, 2 minutes]:
[14:52:40]
[post issues]         github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptcache.(*Cache).periodicallyRefreshProtectedtsCache(0xc01a8acbb0, 0x5bcca60, 0xc00b9329f0)
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptcache/cache.go:160 +0x25b
[14:52:40]
[post issues]         github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc007dda200, 0x5bcca60, 0xc00b9329f0, 0x0, 0xc017a32600)
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0xb9
[14:52:40]
[post issues]         created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0xfc
[14:52:40]
[post issues]         
[14:52:40]
[post issues]         goroutine 8553583 [select, 1 minutes]:
[14:52:40]
[post issues]         github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.(*Manager).PeriodicallyRefreshSomeLeases.func1(0x5bcca60, 0xc00b9329f0)
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:1808 +0x285
[14:52:40]
[post issues]         github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc007dda200, 0x5bcca60, 0xc00b9329f0, 0x0, 0xc017a32e50)
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0xb9
[14:52:40]
[post issues]         created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0xfc
[14:52:40]
[post issues]         
[14:52:40]
[post issues]         goroutine 8553324 [select, 5 minutes]:
[14:52:40]
[post issues]         google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc008ed7ac0)
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:69 +0xc8
[14:52:40]
[post issues]         created by google.golang.org/grpc.newCCBalancerWrapper
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:60 +0x172
[14:52:40]
[post issues]         
[14:52:40]
[post issues]         goroutine 8553286 [select, 5 minutes]:
[14:52:40]
[post issues]         github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x5bcca60, 0xc00b9329f0)
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:105 +0x13d
[14:52:40]
[post issues]         github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc007dda200, 0x5bcca60, 0xc00b9329f0, 0x0, 0xc006286c10)
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0xb9
[14:52:40]
[post issues]         created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0xfc
[14:52:40]
[post issues]         
[14:52:40]
[post issues]         goroutine 8553316 [chan receive, 5 minutes]:
[14:52:40]
[post issues]         github.com/cockroachdb/cockroach/pkg/server.(*Server).startServeUI.func1(0x5bcca60, 0xc00b9329f0)
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:2022 +0x53
[14:52:40]
[post issues]         github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc007dda200, 0x5bcca60, 0xc00b9329f0, 0x0, 0xc004556160)
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0xb9
[14:52:40]
[post issues]         created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
[14:52:40]
[post issues]         	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0xfc
[14:52:40]
[post issues]         
[14:52:40]
[post issues]     rsg_test.go:186: SELECT 1 executed successfully: probably a slow statement
[14:52:40]
[post issues]     rsg_test.go:755: Crash detected: 
[14:52:40]
[post issues]         ALTER TABLE ident.ident ADD IF NOT EXISTS SURVIVE INTERVAL DAY TO MINUTE [ ]
[14:52:40]
[post issues]         
[14:52:40]
[post issues]         Stack trace:
[14:52:40]
[post issues]         timeout: "ALTER TABLE ident.ident ADD IF NOT EXISTS SURVIVE INTERVAL DAY TO MINUTE [ ]". currently executing: map[ALTER TABLE ident.ident ADD IF NOT EXISTS SURVIVE INTERVAL DAY TO MINUTE [ ]:1]
[14:52:40]
[post issues]     rsg_test.go:764: 6923 executions, 1292 successful
[14:52:40]
[post issues]     rsg_test.go:401: -- test log scope end --
[14:52:40]
[post issues] test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRandomSyntaxSchemaChangeColumn880718491
[14:52:40]
[post issues] --- FAIL: TestRandomSyntaxSchemaChangeColumn (357.99s)
[14:52:40]
[post issues] ```
[14:52:40]
[post issues] <details><summary>Reproduce</summary>
[14:52:40]
[post issues] <p>
[14:52:40]
[post issues] <p>To reproduce, try:
[14:52:40]
[post issues] ```bash
[14:52:40]
[post issues] make stressrace TESTS=TestRandomSyntaxSchemaChangeColumn PKG=./pkg/sql/tests TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
[14:52:40]
[post issues] ```
[14:52:40]
[post issues] </p>
[14:52:40]
[post issues] </p>
[14:52:40]
[post issues] </details>
[14:52:40]
[post issues] <details><summary>Same failure on other branches</summary>
[14:52:40]
[post issues] <p>
[14:52:40]
[post issues] - #63202 sql/tests: TestRandomSyntaxSchemaChangeColumn failed [C-test-failure O-robot branch-release-20.1]</p>
[14:52:40]
[post issues] </details>
[14:52:40]
[post issues] [See this test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxSchemaChangeColumn.*&sort=title+created&display=lastcommented+project)
[14:52:40]
[post issues] <sub>[Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub>
[14:52:40]
[post issues] ", Labels:["O-robot" "C-test-failure" "branch-master"], Assignee:"mjibson"}: POST https://api.github.com/repos/cockroachdb/cockroach/issues: 422 Validation Failed [{Resource:Issue Field:assignee Code:invalid Message:}]
[14:52:40]
[Run Random Syntax tests] artifacts (7s)
[14:52:47]
[Run Random Syntax tests] exit status
[14:52:47]
[Run Random Syntax tests] Process exited with code 2
[14:52:47]
[Step 2/2] Process exited with code 2 (Step: Command Line)
[14:52:47]
[Step 2/2] Step Command Line failed
[14:52:47]
Publishing internal artifacts (4s)
[14:52:47]
Publishing artifacts (5s)
[14:52:53]
Build finished
```

cc @ajwerner

**Comment by rafiss** [comment]
I'm creating this manually since it looks like the automatic issue posting failed.

```
POST https://api.github.com/repos/cockroachdb/cockroach/issues: 422 Validation Failed [{Resource:Issue Field:assignee Code:invalid Message:}]
```

@tbg do you happen to know if there's something special to be done to make this test not try to assign Matt to the issue? I'm assuming the posting failed because he no longer is in the Github org, but I thought your recent changes got rid of issue assignees entirely.

**Comment by tbg** [comment]
Look at `oldFriendsMap` in `issues.go`.

Weird, my recent changes should have made the issue poster more resilient to invalid assignee, not less :-) I'll take a look early next week.

**Comment by tbg** [comment]
Ah I see what this is. Matt's Github login works and is found alright, but you can't assign cockroachdb/cockroach projects to him any more, so the creation fails. Sneaky.

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/issues/63202 now fixes this in a commit I just pushed, by not even trying to assign these issues to the authors any more. It simply mentions the author in the comments instead, so it wouldn't have that issue. I mapped Matt to you, Rafi, in that same commit. Enjoy your weekend!

**Comment by tbg** [comment]
^-- nice, that worked.

**Comment by ajwerner** [comment]
@rafiss do you remember why you tagged me on this? @fqazi could you repro this and figure out what's going on?

**Comment by rafiss** [comment]
I think my initial tag was just to let you know that there was an issue with the automated issue posting from this test.

**Comment by fqazi** [comment]
Confirmed this is linked with the timeout, no longer reproduces if I bump up from the default 1-minute statement timeout.
