### ISSUE TITLE
logging: only the first line of the string representation of positional arguments is printed

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#63500]
Consider the following output from a `log.Fatal` call:
```
andrei-desktop> I210412 20:25:58.363351 346 1@kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 85  the server is terminating due to a fatal error (see the DEV channel for details)
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86  ???: raft closed timestamp regression in cmd: ‹×›; batch state: ‹×›, command: ‹×›, lease: ‹×›, req: ‹×›, applying at LAI: 694.
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +(1) assertion failure
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +Wraps: (2) attached stack trace
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  -- stack trace:
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).assertNoCmdClosedTimestampRegression
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_application_state_machine.go:1072
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).Stage
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_application_state_machine.go:479
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.mapCmdIter
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/cmd.go:175
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:280
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:247
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:796
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:459
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:523
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:284
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | runtime.goexit
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  |   /home/andrei/goroot/src/runtime/asm_amd64.s:1374
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +Wraps: (3) raft closed timestamp regression in cmd: ‹×›; batch state: ‹×›, command: ‹×›, lease: ‹×›, req: ‹×›, applying at LAI: 694.
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +  | Closed timestamp was set by req: ‹×› under lease: ‹×›; applied at LAI: ‹×›. Batch idx: 9.
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 +Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !goroutine 346 [running]:
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x7e56500, 0x203001, 0x203001, 0x7f16444b7a38)
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !      /home/andrei/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb9
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc00106f980, 0xc00014b560, 0x24, 0x1, 0x0, 0x0, 0x0, 0x1675362170c616dd, 0x400000000, 0x0, ...)
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !      /home/andrei/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:277 +0xc67
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x5a46320, 0xc002aa78c0, 0x2, 0x4, 0x4bfc6b7, 0x7, 0xc0022a1cf8, 0x2, 0x2)
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !      /home/andrei/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:58 +0x198
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !github.com/cockroachdb/cockroach/pkg/util/log.FatalfDepth(...)
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !      /home/andrei/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:873
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.maybeFatalOnRaftReadyErr(0x5a46320, 0xc002aa78c0, 0x4bf3923, 0x3, 0x59a7020, 0xc0044dc2a0, 0x0)
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !      /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:904 +0x185
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc001f2a000, 0x5a46320, 0xc000f076b0, 0x26)
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !      /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:524 +0x1ad
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker(0xc001a8bc20, 0x5a46320, 0xc000f076b0)
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !      /home/andrei/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:284 +0x2c2
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc00082a180, 0x5a46320, 0xc000f076b0, 0xc000eddc40, 0xc00061b960)
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !      /home/andrei/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0xb9
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
andrei-desktop> F210412 20:25:58.363412 346 kv/kvserver/store_raft.go:524 ⋮ [n1,s1,r38/1:‹×›] 86 !      /home/andrei/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0xfc
```

Notice the line
```
???: raft closed timestamp regression in cmd: ‹×›; batch state: ‹×›, command: ‹×›, lease: ‹×›, req: ‹×›, applying at LAI: 694.
```
This corresponds to the following inner error printed below:
```
Wraps: (3) raft closed timestamp regression in cmd: ‹×›; batch state: ‹×›, command: ‹×›, lease: ‹×›, req: ‹×›, applying at LAI: 694.
Closed timestamp was set by req: ‹×› under lease: ‹×›; applied at LAI: ‹×›. Batch idx: 9.
```
I'm wondering why the 2nd line of the error message didn't make it to the top. I would have liked it to.

Perhaps this is a report for the `errors` repo?

Jira issue: CRDB-6611

**Comment by knz** [comment]
I think this is a dup of  #62355 - I have observed this before.

**Comment by knz** [comment]
it's not just errors. Changed the title to explain.

**Comment by knz** [comment]
We've fixed this since.
