### ISSUE TITLE
simulation: (*Network).Stop stuck on gRPCDial/Heartbeat (via kv/TestCountRanges)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6372]
https://circleci.com/gh/cockroachdb/cockroach/17015

probably harder to repro locally. I tried 15k iters, but no dice.

```
=== RUN   TestCountRanges
I160428 12:13:57.968829 gossip/simulation/network.go:57  simulating gossip network with 1 nodes
W160428 12:13:57.969014 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
W160428 12:13:57.969092 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160428 12:13:57.978436 stopper.go:352  draining; tasks left:
5      gossip/infostore.go:286
1      gossip/gossip.go:750
I160428 12:13:57.979095 gossip/gossip.go:918  starting client to 127.0.0.1:52590
panic: test timed out after 1m10s

goroutine 667 [running]:
panic(0x13d6120, 0xc82023e790)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0x1af4328, 0x222c440, 0x6f, 0x6f, 0xc8202af401)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820032f08, 0x5a2ac3)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/kv/_test/_testmain.go:280 +0x117

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2503360)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 678 [select]:
google.golang.org/grpc/transport.(*Stream).Header(0xc820130c40, 0xc820130c40, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x7fae8be3a348, 0x252be90, 0x0, 0x0, 0x0, 0x0, 0x7fae8be3ba38, 0xc82025c000, 0x100, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x7fae8be3bb78, 0xc8201cd2c0, 0x1870e00, 0x1d, 0x16f6ae0, 0xc820240ec0, 0x16e8a80, 0xc8201a72c0, 0xc82022e000, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:178 +0xae6
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc820026028, 0x7fae8be3bb78, 0xc8201cd2c0, 0xc820240ec0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:115 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).heartbeat(0xc8201c8230, 0x7fae8be3bb20, 0xc820026028, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:237 +0x150
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8201c8230, 0xc82022e000, 0xc82023e210, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:192 +0x247
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:173 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201c8070, 0xc820272600)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 648 [semacquire]:
sync.runtime_Semacquire(0xc8201c8094)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc8201c8088)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc8201c8070)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:302 +0x1dd
github.com/cockroachdb/cockroach/gossip/simulation.(*Network).Stop(0xc820240100)
	/go/src/github.com/cockroachdb/cockroach/gossip/simulation/network.go:176 +0x9c
github.com/cockroachdb/cockroach/gossip/simulation.(*Network).Stop-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_test.go:86 +0x20
github.com/cockroachdb/cockroach/kv.TestCountRanges(0xc82014a000)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_test.go:1646 +0xe02
testing.tRunner(0xc82014a000, 0x222c638)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 677 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc820130460)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc820130460)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 679 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc82021c000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 680 [IO wait]:
net.runtime_pollWait(0x7fae8be3b230, 0x72, 0xc820204000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201c8140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201c8140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201c80e0, 0xc820204000, 0x8000, 0x8000, 0x0, 0x7fae8be6a050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820026030, 0xc820204000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc8202341e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8202341e0, 0xc8200baab8, 0x9, 0x9, 0x87c538, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7fae8be71180, 0xc8202341e0, 0xc8200baab8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fae8be71180, 0xc8202341e0, 0xc8200baab8, 0x9, 0x9, 0xc820240148, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8200baab8, 0x9, 0x9, 0x7fae8be71180, 0xc8202341e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8200baa80, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc820273950, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc82021c000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:743 +0x42
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a
FAIL	github.com/cockroachdb/cockroach/kv	70.038s
```

**Comment by tamird** [comment]
Doesn't seem to have reproduced in the interim, closing.
