### ISSUE TITLE
circleci: failed tests: TestSequenceUpdate

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6383]
The following test appears to have failed:

[#17041](https://circleci.com/gh/cockroachdb/cockroach/17041):

```
3      gossip/infostore.go:286
I160428 15:49:22.345428 stopper.go:352  draining; tasks left:
2      gossip/infostore.go:286
I160428 15:49:22.345478 stopper.go:352  draining; tasks left:
1      gossip/infostore.go:286
panic: test timed out after 1m10s

goroutine 652 [running]:
panic(0x13d0140, 0xc82025fda0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0x1aebbf8, 0x2221fc0, 0x6f, 0x6f, 0xc820253a01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820039f08, 0x5a2ac3)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/kv/_test/_testmain.go:280 +0x117

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 22 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x24f8e80)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 628 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc8201b21e4)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc8201b21d8)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc8201b21c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:302 +0x1dd
github.com/cockroachdb/cockroach/gossip/simulation.(*Network).Stop(0xc820014240)
	/go/src/github.com/cockroachdb/cockroach/gossip/simulation/network.go:176 +0x9c
github.com/cockroachdb/cockroach/gossip/simulation.(*Network).Stop-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_test.go:86 +0x20
--
testing.tRunner(0xc82008e000, 0x2222170)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 644 [select]:
google.golang.org/grpc/transport.(*Stream).Header(0xc82011ab60, 0xc82011ab60, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x7f5408a51f30, 0x25219a0, 0x0, 0x0, 0x0, 0x0, 0x7f5408a537d8, 0xc820219440, 0x100, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x7f5408a53918, 0xc8201b6de0, 0x1869720, 0x1d, 0x16efd80, 0xc820227540, 0x16e1d20, 0xc820245d60, 0xc8200948c0, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:178 +0xae6
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc82006c398, 0x7f5408a53918, 0xc8201b6de0, 0xc820227540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:115 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).heartbeat(0xc8201b22a0, 0x7f5408a538c0, 0xc82006c398, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:237 +0x150
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201b21c0, 0xc820190570)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 643 [select, 1 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc82011a380)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc82011a380)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 645 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc82020a0f0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 646 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f5408a52e18, 0x72, 0xc8201fa000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201b3c60, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201b3c60, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201b3c00, 0xc8201fa000, 0x8000, 0x8000, 0x0, 0x7f5408a3d028, 0xc820060080)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82006c3a0, 0xc8201fa000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc82020a0f0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:743 +0x42
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a
FAIL	github.com/cockroachdb/cockroach/kv	70.085s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestMustSetInner
--- PASS: TestMustSetInner (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestBatchRequestString
--- PASS: TestBatchRequestString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
```
goroutine 644 [select]:
google.golang.org/grpc/transport.(*Stream).Header(0xc82011ab60, 0xc82011ab60, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x7f5408a51f30, 0x25219a0, 0x0, 0x0, 0x0, 0x0, 0x7f5408a537d8, 0xc820219440, 0x100, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x7f5408a53918, 0xc8201b6de0, 0x1869720, 0x1d, 0x16efd80, 0xc820227540, 0x16e1d20, 0xc820245d60, 0xc8200948c0, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:178 +0xae6
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc82006c398, 0x7f5408a53918, 0xc8201b6de0, 0xc820227540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:115 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).heartbeat(0xc8201b22a0, 0x7f5408a538c0, 0xc82006c398, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:237 +0x150
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8201b22a0, 0xc8200948c0, 0xc82025e8d0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:192 +0x247
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:173 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201b21c0, 0xc820190570)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

I checked that the call to `heartbeat` should comes with a nontrivial timeout, but it looks like it got stuck.
`Header` does honor the context (and has done so for a while), so it doesn't seem that the context got cancelled.

```go
func (s *Stream) Header() (metadata.MD, error) {
	select {
	case <-s.ctx.Done():
		return nil, ContextErr(s.ctx.Err())
	case <-s.headerChan:
		return s.header.Copy(), nil
	}
}
```

I'm closing this for now since the test failure is unrelated to what the test is asserting. We should investigate faster the next time this happens since the interesting part may be in grpc.
