### ISSUE TITLE
kv: panic in `(*Replica).tick`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#64203]
Found by @jseldess in https://github.com/cockroachdb/cockroach/issues/62283#issuecomment-825928981

```
root@127.0.0.1:26257/movr> *
* ERROR: [n9,s9] a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	/usr/local/go/src/runtime/panic.go:969
*   | runtime.panicmem
*   | 	/usr/local/go/src/runtime/panic.go:212
*   | runtime.sigpanic
*   | 	/usr/local/go/src/runtime/signal_unix.go:742
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).tick
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:951
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processTick
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:563
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:279
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351
*   | runtime.goexit
*   | 	/usr/local/go/src/runtime/asm_amd64.s:1374
* Wraps: (2) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) runtime.errorString
*
*
* ERROR: [n9,s9] Queued as error 5f5e8ae8ab344fe28313d817ccb9b7f9
*
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]
goroutine 2432 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc00289c400, 0x9494180, 0xc00563a420)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:233 +0x126
panic(0x7fa7880, 0xbd94420)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).tick(0xc00590b600, 0x9494180, 0xc008cb0180, 0xc006ed3b30, 0xc008cb0100, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:951 +0x31c
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processTick(0xc00565e000, 0x9494180, 0xc00563a420, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:563 +0x14a
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker(0xc003aac1e0, 0x9494180, 0xc00563a420)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:279 +0x309
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc00289c400, 0x9494180, 0xc00563a420, 0x0, 0xc003adca00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0xb9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0xfc
```

Version details:

```
~/cockroach-v21.1.0-beta.4.darwin-10.9-amd64$ ./cockroach version
Build Tag:        v21.1.0-beta.4
Build Time:       2021/04/19 15:35:45
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19)
Go Version:       go1.15.10
C Compiler:       Clang 10.0.0
Build Commit ID:  abc4eb5acda343e64415f0267ccd94805d7f2760
Build Type:       release
```

Jira issue: CRDB-6951

**Comment by erikgrinaker** [comment]
Panic happens here:

https://github.com/cockroachdb/cockroach/blob/729cb7863168d0c7973d5b8b5032fb46c127f6f7/pkg/kv/kvserver/replica_raft.go#L951

So `Replica.store` must be `nil`. A naïve fix would be to wrap that block in `if r.store != nil`, but I'm not sure why it would even be `nil` at this point, so let's try to dig into that first.

**Comment by pavelkalinnikov** [comment]
I browsed the code, and so far did not find why `Replica.store` can be nil, there is only a couple of initialisation paths both of which set it.

**Comment by erikgrinaker** [comment]
We haven't been able to reproduce this, nor seen any other reports of it, nor found a plausible explanation for it, so I'm closing this as outdated. Will reopen if we see it happen again.
