### ISSUE TITLE
colflow: unexpectedly not all closers were closed before Flow.Cleanup

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#64248]
Extracted from #60824.

sql/logictest.TestLogic [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2925863&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2925863&tab=artifacts#/) on master @ [05880958efb6fda9ab80ed16495d98922de3fbf6](https://github.com/cockroachdb/cockroach/commits/05880958efb6fda9ab80ed16495d98922de3fbf6):

Fatal error:

```
panic: expected 2 components to be closed, but found that only 0 were

```
Stack: 

```
goroutine 9453985 [running]:
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.InternalError(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:192
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup(0xc146920aa0, 0x51d5e40, 0xc037fcf240)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:285 +0x505
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func8()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:373 +0x82
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc0c811c600, 0x51f4140, 0xc05fff0318, 0xc0c811cae0, 0x3, 0x5243ee0, 0xc08e468c00, 0xc109496401, 0xc0b0f19078, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1055 +0x4cc
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0c811c600, 0x51f4140, 0xc05fff0318, 0xc0c811cae0, 0x5243ee0, 0xc08e468c00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:915 +0x75b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0c811c600, 0x51f4140, 0xc05fff0318, 0x5200700, 0xc02c975f90, 0xc0979d1bc0, 0x3c, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:659 +0xf86
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0c811c600, 0x51d5e40, 0xc0ce4d52c0, 0x5200700, 0xc02c975f90, 0xc0979d1bc0, 0x3c, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:122 +0xb14
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0x5200700, 0xc02c975f90, 0xc0979d1bc0, 0x3c, 0x0, 0x0, 0xad5db37, 0xed8193acf, 0x0, 0xad5db37, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1527 +0x225
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc0c811c600, 0x51d5e40, 0xc0ce4d52c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1529 +0x1457
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0c811c600, 0x51d5f00, 0xc08e468870, 0xc081bf7e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1450 +0x228
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1(0xc0c811c600, 0x51d5f00, 0xc08e468870, 0xc0b0f18960, 0xc08e4689c0, 0x5188200, 0xc0ce4d5140, 0xc02ad0a630, 0xc17f462d20)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:202 +0x65
created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:201 +0x2f2
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestLogic/fakedist-disk/serial/serial_virtual_sequence
E210426 22:50:55.106794 9444974 jobs/adopt.go:260  [n1] 954  job 653417037656260609: adoption completed with error failed to ingest index entries during backfill: duplicate key value violates unique constraint "bar"
```
</p>
</details>
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=TestLogic PKG=./pkg/sql/logictest TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
<p>Parameters in this failure:

- GOFLAGS=-json
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #63262 sql/logictest: TestLogic failed [C-test-failure O-robot branch-release-20.2]
- #61657 sql/logictest: TestLogic failed [C-test-failure O-robot branch-release-21.1]
- #58269 sql/logictest: TestLogic failed [C-test-failure O-robot branch-release-20.1]
</p>
</details>
/cc @jordanlewis
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

**Comment by yuzefovich** [comment]
Hm, it's possible that a `Columnarizer` (to be more precise, the materializer on the other side of the wrapped processor) was responsible for closing some components, and then the columnarizer was removed from the flow. This made `Columnarizer.Close` a noop resulting in the materializer never closing some components. I'll have to think a bit on how to go around this problem.

**Comment by yuzefovich** [comment]
No, the scenario I described above isn't feasible. The reason is that the materializer (that is actually responsible for handling meta components) is never removed from the flow, and it'll be a part of the input tree to the processor that is about to be created. Consider the following example:
```
        └ *rowexec.joinReader (2)
          └ *rowexec.joinReader (1)
            └ *colfetcher.ColBatchScan
```
ColBatchScan is a Closer, then we creating joinReader (1), we will:
- make a materializer that will take over the ColBatchScan
- create the joinReader with the materializer as its input
- create the columnarizer to convert the joinReader to the vectorized format.

When creating joinReader (2), we will:
- remove the columnarizer and use its input (joinReader (1)) as the input to the new joinReader
- create the joinReader (2) with joinReader (1) as its input
- create new columnarizer.

Thus, the materializer responsible for closing the colbatchscan is still part of the resulting tree.

**Comment by yuzefovich** [comment]
However, I think I do see a case when some closers might not be closed: in the parallel unordered synchronizer we initialize all inputs in `sync.Init`, each input might have some closers assigned to it, those are closed in the same goroutine as the input is being read from. But those goroutines are only spawned up if either `sync.Next` or `sync.DrainMeta` is called. Now imagine a scenario that `sync.Init` initialized some of the inputs but then encountered an error which resulted in a panic - then initialized inputs must be closed, but the overall initialization of the sync failed, so the consumer of the sync might never call `Next` or `DrainMeta` on it because it is considered unsafe.

**Comment by yuzefovich** [comment]
Hm, this issue is a bit non-deterministic, I have a fix for the scenario described above, and I couldn't find any other places where we could not close something. Rerunning the logic tests on the gceworker.

**Comment by yuzefovich** [comment]
Hm, on the first repro I hit #64294 (that has a pending fix for it), so I'll cherry-pick the PR and see what happens.

**Comment by yuzefovich** [comment]
Okay, I got 16 successful runs, and then a flake. Kicked off again, but I'm feeling optimistic.

**Comment by yuzefovich** [comment]
81 successful runs for far.
