### ISSUE TITLE
build/bazel:  build chokes when `make` doesn't point to GNU make

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#64334]
On my system, `make` is a non-GNU make and the GNU make is called `gmake`.

When I run `gmake build` everything works, because GNU make propagates itself to sub-commands via the `MAKE` environment variable.

With `bazel build` I get the following errors:

```
ERROR: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/c-deps/BUILD.bazel:10:15: CcConfigureMakeRule c-deps/libjemalloc/include failed: (Exit 1): bash failed: error executing command /usr/local/bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /usr/local/bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox

rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory  and dependencies directory  for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify '--sandbox_debug' Bazel command line flag.

rules_foreign_cc: Printing build logs:

_____ BEGIN BUILD LOGS _____
Bazel external C/C++ Rules #0.0.8. Building library 'libjemalloc'
...
config.status: executing include/jemalloc/jemalloc.h commands
===============================================================================
jemalloc version   : 0.0.0-0-g0000000000000000000000000000000000000000
...
===============================================================================
make: "/tmp/tmp.D82ZsUSa/Makefile" line 3: Invalid line type
make: "/tmp/tmp.D82ZsUSa/Makefile" line 4: Invalid line type
make: "/tmp/tmp.D82ZsUSa/Makefile" line 72: Invalid line type
make: "/tmp/tmp.D82ZsUSa/Makefile" line 74: Invalid line type
make: "/tmp/tmp.D82ZsUSa/Makefile" line 75: Invalid line type
make: "/tmp/tmp.D82ZsUSa/Makefile" line 77: Invalid line type
make: "/tmp/tmp.D82ZsUSa/Makefile" line 79: Invalid line type
make: "/tmp/tmp.D82ZsUSa/Makefile" line 80: Invalid line type
```

There are a couple of problems:

- `bazel` picks up whatever `make` is found in PATH, probably needs to pin something instead

  ~This is not strictly a problem because it also gives me a workaround: I created a temporary `bin` directory with a symlink `make` -> `gmake` inside, and that solved the problem.~

- the command "make" is hardcoded inside the `c-deps/BUILD.bazel` scripts

I think the proper UX for this would be to have a version pin, plus an ability for the user to override e.g. via an env var, preferably `$MAKE`.

cc @rickystewart

**Comment by knz** [comment]
> This is not strictly a problem because it also gives me a workaround: I created a temporary bin directory with a symlink make -> gmake inside, and that solved the problem.

I wrote too soon, it still doesn't seem to work. I get failures building jemalloc.

(same as above)

If I manually edit `c-deps/BUILD.bazel` and change the hardcoded use of `make` by (an equally harcoded use of) `gmake`, then the error disappears.

**Comment by knz** [comment]
Note: I only needed to change the harcoded `make` invocation for the `libjemalloc` build.

The remaining two uses of `"make"` (libroach/libkrb5) don't seem to cause issues.

**Comment by rickystewart** [comment]
#61405 for the overall `make` "toolchain" issue.

**Comment by rickystewart** [comment]
I wonder if we rebase our fork of `rules_foreign_cc` whether this would continue to be a problem. Newer versions of the library bootstrap `make` from source by default.

**Comment by rickystewart** [comment]
Got a draft commit that might work, except it breaks in CI for unknown reasons: https://github.com/rickystewart/cockroach/tree/upgrade_rules_foreign_cc

**Comment by knz** [comment]
@rickystewart when I run with your patch I get this:

```
ERROR: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/c-deps/BUILD.bazel:93:6: in cmake rule //c-deps:libroach:
Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/rules_foreign_cc/foreign_cc/cmake.bzl", line 36, column 53, in _cmake_impl
                generator, generate_args = _get_generator_target(ctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/rules_foreign_cc/foreign_cc/cmake.bzl", line 201, column 17, in _get_generator_target
                fail("No generator set and no default is known. Please set the cmake `generator` attribute")
Error in fail: No generator set and no default is known. Please set the cmake `generator` attribute
ERROR: Analysis of target '//pkg/cmd/cockroach-short:cockroach-short' failed; build aborted: Analysis of target '//c-deps:libroach' failed
```

Not surprising, given this code in that file:

```python
    if not generator:
        execution_os_name = os_name(ctx)
        if "win" in execution_os_name:
            generator = "Ninja"
        elif "macos" in execution_os_name:
            generator = "Unix Makefiles"
        elif "linux" in execution_os_name:
            generator = "Unix Makefiles"
        else:
            fail("No generator set and no default is known. Please set the cmake `generator` attribute")
```

This should be `else: generator = "Unix Makefiles"`.

**Comment by rickystewart** [comment]
If you add a `generator = "Unix Makefiles"` kwarg to the `cmake()` calls in `c-deps/BUILD.bazel`, does that allow your build to get farther?

**Comment by knz** [comment]
then I get this:

```
ERROR: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/c-deps/BUILD.bazel:32:6: //c-deps:libproj: no such attribute 'generator' in 'cmake' rule
ERROR: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/c-deps/BUILD.bazel:45:6: //c-deps:libgeos: no such attribute 'generator' in 'cmake' rule
ERROR: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/c-deps/BUILD.bazel:95:6: //c-deps:libroach: no such attribute 'generator' in 'cmake' rule
```

**Comment by knz** [comment]
Ah, but now I understand why you asked. here's the solution:

```
cmake(...
 cmake_options = ["-GUnix Makefiles"],
```

That works and brings me one step further.

Then I get a different kind of failure:

```
 cd . && /bin/sh /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/sandbox/processwrapper-sandbox/1/execroot/cockroach/bazel-out/host/bin/external/rules_foreign_cc/toolchains/make.build_tmpdir/build-aux/missing automake-1.16 --foreign
configure.ac:35: error: version mismatch.  This is Automake 1.16.3,
configure.ac:35: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:35: comes from Automake 1.16.1.  You should recreate
configure.ac:35: aclocal.m4 with aclocal and run automake again.
WARNING: 'automake-1.16' is probably too old.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [Makefile:1086: Makefile.in] Error 1
Target //pkg/cmd/cockroach-short:cockroach-short failed to build
```

**Comment by knz** [comment]
Separately, the new version of the `foreign_cc` package will re-build `CMake` from source.

This is expensive! There are two things that surprise me:

- why does it not fetch a pre-built binary?
- it runs `make` (in my case, `gmake`) without the `-j` flag and I can see the poor thing compiling gigantic C++ files one by one. This would benefit from some parallelization.

**Comment by knz** [comment]
The `Automake` error is odd: I only saw it the first time, then subsequent `bazel build` runs don't observe it any more.

I even tried `bazel clean` and then ran again, and still did not repro. What's up with that?
