### ISSUE TITLE
sql/logictest: schema_change_in_txn failed due to "unexpectedly found 1 active spans"

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#64647]
I've been seeing this error a lot lately:
```
testcluster.go:135: condition failed to evaluate within 45s: unexpectedly found 1 active spans:
0.000ms      0.000ms    === operation:colbatchscan
goroutine 3784692 [running]:
runtime/debug.Stack(0xc04bd21860, 0x5196580, 0xc0cc60d7c0)
  GOROOT/src/runtime/debug/stack.go:24 +0x9f
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x524f460, 0xc0388ec900, 0xc04bd21860)
  pkg/testutils/soon.go:35 +0x6d
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).stopServers(0xc034a78900, 0x5222720, 0xc00007a098)
  pkg/testutils/testcluster/testcluster.go:135 +0x265
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start.func2()
  pkg/testutils/testcluster/testcluster.go:335 +0x45
github.com/cockroachdb/cockroach/pkg/util/stop.CloserFn.Close(0xc0939f37f0)
  pkg/util/stop/stopper.go:110 +0x25
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc05525f000, 0x5222720, 0xc00007a098)
  pkg/util/stop/stopper.go:479 +0x22f
github.com/cockroachdb/cockroach/pkg/sql/logictest.(*logicTest).shutdownCluster(0xc02ce47400)
  pkg/sql/logictest/logic.go:1602 +0x1da
github.com/cockroachdb/cockroach/pkg/sql/logictest.(*logicTest).close(0xc02ce47400)
  pkg/sql/logictest/logic.go:1237 +0x3d
github.com/cockroachdb/cockroach/pkg/sql/logictest.(*logicTest).runFile(0xc02ce47400, 0xc000f038c0, 0x28, 0x453ea68, 0x8, 0x3, 0x1, 0x4534291, 0x2, 0x0, ...)
  pkg/sql/logictest/logic.go:3132 +0x189
github.com/cockroachdb/cockroach/pkg/sql/logictest.RunLogicTestWithDefaultConfig.func1.1(0xc0388ec900)
  pkg/sql/logictest/logic.go:3324 +0x2de
testing.tRunner(0xc0388ec900, 0xc097ae3680)
  GOROOT/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
  GOROOT/src/testing/testing.go:1168 +0x2b3
--- progress: testdata/logic_test/alter_table: 134 statements/queries
--- FAIL: TestLogic/fakedist/schema_change_in_txn (78.27s)
```

**Comment by rytaft** [comment]
Here's one build where it happened (not sure if this is related to bazel somehow...): https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/2946607

**Comment by jordanlewis** [comment]
@yuzefovich says in Slack that it's most likely related to some recent change, so I'll assign to him and move to the Queries board.

**Comment by yuzefovich** [comment]
I ran `TestLogic//schema_change_in_txn` with no failures over 900 runs on the gceworker. Will kick off the whole logic test suite. I think all known recent problems with logic tests have been fixed, so possibly this issue as well.

**Comment by yuzefovich** [comment]
I haven't seen another occurrence of this issue in over a week, so I'm assuming it was fixed.
