### ISSUE TITLE
kvserver: starting a SQL pod for an invalid tenant ID causes a panic and poisons that tenant ID

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#64963]
**Describe the problem**

Try the following:
```
$ cockroach start-single-node --insecure --logtostderr=INFO --accept-sql-without-tls
$ cockroach mt start-sql --insecure --tenant-id 123 --http-addr 127.0.0.1:8081 --kv-addrs 127.0.0.1:26257 --sql-addr 127.0.0.1:36257 --log-dir=logs/mt-123 --logtostderr=INFO
$ cockroach sql --insecure -e 'select crdb_internal.create_tenant(123);'
```

Step two fatals with the following; I'd expect a nicer looking error for the operator.

<details>

```
W210510 21:06:56.344348 148 sql/temporary_schema.go:599  [-] 16  failed to clean temp objects: isMeta1Leaseholder is not available to secondary tenants
I210510 21:06:56.344408 148 sql/temporary_schema.go:610  [-] 17  temporary object cleaner next scheduled to run at 2021-05-10 21:36:56.344119 +0000 UTC
E210510 21:06:56.348965 159 sql/sqlliveness/slinstance/slinstance.go:135  [-] 18  failed to create a session at 1-th attempt: could not insert session ed9ffdfc7b844d50a719280451243558: insert-session: descriptor 39 not found: descriptor not found
W210510 21:06:56.349003 154 sql/stmtdiagnostics/statement_diagnostics.go:134  [-] 19  error polling for statement diagnostics requests: stmt-diag-poll: descriptor 35 not found: descriptor not found
W210510 21:06:56.427481 1 sqlmigrations/migrations.go:436  [-] 20  failed to run
W210510 21:06:56.427481 1 sqlmigrations/migrations.go:436  [-] 20 +             UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', false)
W210510 21:06:56.427481 1 sqlmigrations/migrations.go:436  [-] 20 +     : addRootUser: descriptor 4 not found: descriptor not found
W210510 21:06:56.476651 1 sqlmigrations/migrations.go:436  [-] 21  failed to run
W210510 21:06:56.476651 1 sqlmigrations/migrations.go:436  [-] 21 +             UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', false)
W210510 21:06:56.476651 1 sqlmigrations/migrations.go:436  [-] 21 +     : addRootUser: descriptor 4 not found: descriptor not found
W210510 21:06:56.581487 1 sqlmigrations/migrations.go:436  [-] 22  failed to run
W210510 21:06:56.581487 1 sqlmigrations/migrations.go:436  [-] 22 +             UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', false)
W210510 21:06:56.581487 1 sqlmigrations/migrations.go:436  [-] 22 +     : addRootUser: descriptor 4 not found: descriptor not found
W210510 21:06:56.766581 1 sqlmigrations/migrations.go:436  [-] 23  failed to run
W210510 21:06:56.766581 1 sqlmigrations/migrations.go:436  [-] 23 +             UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', false)
W210510 21:06:56.766581 1 sqlmigrations/migrations.go:436  [-] 23 +     : addRootUser: descriptor 4 not found: descriptor not found
W210510 21:06:57.157100 1 sqlmigrations/migrations.go:436  [-] 24  failed to run
W210510 21:06:57.157100 1 sqlmigrations/migrations.go:436  [-] 24 +             UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', false)
W210510 21:06:57.157100 1 sqlmigrations/migrations.go:436  [-] 24 +     : addRootUser: descriptor 4 not found: descriptor not found
E210510 21:06:57.413860 159 sql/sqlliveness/slinstance/slinstance.go:135  [-] 25  failed to create a session at 11-th attempt: could not insert session ed9ffdfc7b844d50a719280451243558: insert-session: descriptor 39 not found: descriptor not found
W210510 21:06:58.058522 1 sqlmigrations/migrations.go:436  [-] 26  failed to run
W210510 21:06:58.058522 1 sqlmigrations/migrations.go:436  [-] 26 +             UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', false)
W210510 21:06:58.058522 1 sqlmigrations/migrations.go:436  [-] 26 +     : addRootUser: descriptor 4 not found: descriptor not found
W210510 21:06:58.097695 1 sqlmigrations/migrations.go:436  [-] 27  failed to run
W210510 21:06:58.097695 1 sqlmigrations/migrations.go:436  [-] 27 +          UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', true): addAdminRole: descriptor 4 not found: descriptor not found
W210510 21:06:58.144658 1 sqlmigrations/migrations.go:436  [-] 28  failed to run
W210510 21:06:58.144658 1 sqlmigrations/migrations.go:436  [-] 28 +          UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', true): addAdminRole: descriptor 4 not found: descriptor not found
W210510 21:06:58.234171 1 sqlmigrations/migrations.go:436  [-] 29  failed to run
W210510 21:06:58.234171 1 sqlmigrations/migrations.go:436  [-] 29 +          UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', true): addAdminRole: descriptor 4 not found: descriptor not found
W210510 21:06:58.438834 1 sqlmigrations/migrations.go:436  [-] 30  failed to run
W210510 21:06:58.438834 1 sqlmigrations/migrations.go:436  [-] 30 +          UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', true): addAdminRole: descriptor 4 not found: descriptor not found
W210510 21:06:58.835055 1 sqlmigrations/migrations.go:436  [-] 31  failed to run
W210510 21:06:58.835055 1 sqlmigrations/migrations.go:436  [-] 31 +          UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', true): addAdminRole: descriptor 4 not found: descriptor not found
E210510 21:06:58.924563 159 sql/sqlliveness/slinstance/slinstance.go:135  [-] 32  failed to create a session at 13-th attempt: could not insert session ed9ffdfc7b844d50a719280451243558: insert-session: descriptor 39 not found: descriptor not found
W210510 21:06:59.646371 1 sqlmigrations/migrations.go:436  [-] 33  failed to run
W210510 21:06:59.646371 1 sqlmigrations/migrations.go:436  [-] 33 +          UPSERT INTO system.users (username, "hashedPassword", "isRole") VALUES ($1, '', true): addAdminRole: descriptor 4 not found: descriptor not found
W210510 21:06:59.668549 1 sqlmigrations/migrations.go:436  [-] 34  failed to run
W210510 21:06:59.668549 1 sqlmigrations/migrations.go:436  [-] 34 +          UPSERT INTO system.role_members ("role", "member", "isAdmin") VALUES ($1, $2, true): addRootToAdminRole: descriptor 23 not found: descriptor not found
W210510 21:06:59.721630 1 sqlmigrations/migrations.go:436  [-] 35  failed to run
W210510 21:06:59.721630 1 sqlmigrations/migrations.go:436  [-] 35 +          UPSERT INTO system.role_members ("role", "member", "isAdmin") VALUES ($1, $2, true): addRootToAdminRole: descriptor 23 not found: descriptor not found
W210510 21:06:59.824880 1 sqlmigrations/migrations.go:436  [-] 36  failed to run
W210510 21:06:59.824880 1 sqlmigrations/migrations.go:436  [-] 36 +          UPSERT INTO system.role_members ("role", "member", "isAdmin") VALUES ($1, $2, true): addRootToAdminRole: descriptor 23 not found: descriptor not found
W210510 21:07:00.014509 1 sqlmigrations/migrations.go:436  [-] 37  failed to run
W210510 21:07:00.014509 1 sqlmigrations/migrations.go:436  [-] 37 +          UPSERT INTO system.role_members ("role", "member", "isAdmin") VALUES ($1, $2, true): addRootToAdminRole: descriptor 23 not found: descriptor not found
E210510 21:07:00.146081 159 sql/sqlliveness/slinstance/slinstance.go:135  [-] 38  failed to create a session at 14-th attempt: could not insert session ed9ffdfc7b844d50a719280451243558: insert-session: descriptor 39 not found: descriptor not found
W210510 21:07:00.427719 1 sqlmigrations/migrations.go:436  [-] 39  failed to run
W210510 21:07:00.427719 1 sqlmigrations/migrations.go:436  [-] 39 +          UPSERT INTO system.role_members ("role", "member", "isAdmin") VALUES ($1, $2, true): addRootToAdminRole: descriptor 23 not found: descriptor not found
W210510 21:07:01.183998 1 sqlmigrations/migrations.go:436  [-] 40  failed to run
W210510 21:07:01.183998 1 sqlmigrations/migrations.go:436  [-] 40 +          UPSERT INTO system.role_members ("role", "member", "isAdmin") VALUES ($1, $2, true): addRootToAdminRole: descriptor 23 not found: descriptor not found
E210510 21:07:02.280194 159 sql/sqlliveness/slinstance/slinstance.go:135  [-] 41  failed to create a session at 15-th attempt: could not insert session ed9ffdfc7b844d50a719280451243558: insert-session: descriptor 39 not found: descriptor not found
I210510 21:07:02.883668 24 1@sql/descriptor.go:162  [intExec=create-default-DB] 42  the server is terminating due to a fatal error (see the DEV channel for details)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43  cannot create descriptor with an empty ID: dbdesc.Mutable: {ID: 0, Version: 1, IsUncommitted: true, ModificationTime: "0,0", State: PUBLIC}
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !goroutine 24 [running]:
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xba1f000, 0x4b087a, 0x1, 0xffffffff00203000)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb9
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc0016afcc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x167dd09f26457c00, 0x400000000, 0x0, ...)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:277 +0xc67
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x96325a0, 0xc0008e7dc0, 0x1, 0x4, 0x87a9046, 0x2, 0xc002161730, 0x1, 0x1)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:58 +0x198
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:804
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*planner).createDescriptorWithID(0xc0016184f0, 0x96325a0, 0xc0008e7dc0, 0xc000ec6b00, 0x15, 0x20, 0x0, 0x9788e80, 0xc0007b87e0, 0x0, ...)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/descriptor.go:162 +0x168
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*planner).createDatabase(0xc0016184f0, 0x96325a0, 0xc0008e7dc0, 0xc0007b83f0, 0xc0001785a0, 0x27, 0x1a, 0xc0016b5930, 0x53648d0, 0xc0007b8548)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/descriptor.go:128 +0x431
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*createDatabaseNode).startExec(0xc000884248, 0x96325a0, 0xc0008e7dc0, 0xc0012d6600, 0xc0016184f0, 0x80d2901, 0xba71078)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/create_database.go:110 +0x114
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x87d0db4, 0xf, 0x9633a20, 0xc000884248, 0x0, 0x0)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:499 +0xcb
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc002161b28, 0x87d0db4, 0xf, 0x9633a20, 0xc000884248)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:119 +0x5d
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc0016b5b28, 0x9633a20, 0xc000884248, 0x87d0db4, 0xf)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:296 +0x188
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc0016b5b28, 0x9633a20, 0xc000884248, 0x96325a0, 0xc0008e7dc0)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:86 +0x8f
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.walkPlan(...)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:50
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.startExec(0x96325a0, 0xc0008e7dc0, 0xc0012d6600, 0xc0016184f0, 0x9633a20, 0xc000884248, 0x96325a0, 0xc0008e7dc0)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:502 +0x11f
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc0012fe000, 0x96325a0, 0xc0008e7dc0)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:128 +0xb6
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run(0xc0012fe000, 0x96325a0, 0xc0008e7dc0)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:802 +0x52
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc001328ea0, 0x96325a0, 0xc0008e7dc0, 0x8eb3868, 0x0, 0x0)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:388 +0x2e2
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00151f8c0, 0xc001b356c0, 0xc0007b8510, 0xc001ea5200, 0xc001274380, 0xc001618708, 0x0, 0x0)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:357 +0x4a9
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00151f8c0, 0x9650aa0, 0xc0012124b8, 0xc001618708, 0xc001b356c0, 0xc0007b8510, 0x9633a20, 0xc000884248, 0x0, 0xc001274380, ...)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1001 +0x1c8
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001618000, 0x9650aa0, 0xc0012124b8, 0xc0016184f0, 0x1, 0x96a8ce0, 0xc00137dcb0, 0xc0006da400, 0xc00129a598, 0x0, ...)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1054 +0x455
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001618000, 0x9650aa0, 0xc0012124b8, 0xc0016184f0, 0x96a8ce0, 0xc00137dcb0, 0x0, 0x0)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:921 +0x75b
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001618000, 0x9650aa0, 0xc0012124b8, 0x965d560, 0xc0007b83f0, 0xc000178510, 0x29, 0x0, 0x0, 0x0, ...)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:665 +0x1006
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001618000, 0x96325a0, 0xc0008e7cc0, 0x965d560, 0xc0007b83f0, 0xc000178510, 0x29, 0x0, 0x0, 0x0, ...)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:122 +0xb14
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0x965d560, 0xc0007b83f0, 0xc000178510, 0x29, 0x0, 0x0, 0x324d4608, 0xed82b9776, 0x0, 0x324d4608, ...)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1525 +0x225
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc001618000, 0x96325a0, 0xc0008e7cc0, 0x0, 0x0)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1527 +0x1457
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001618000, 0x9632660, 0xc00137d980, 0xc001a72320, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1449 +0x228
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1(0xc001618000, 0x9632660, 0xc00137d980, 0xc0018f94a0, 0xc00137d9e0, 0x95dace0, 0xc0008e7bc0, 0x0, 0xc000ea0a10)
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:203 +0x65
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !      /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:202 +0x2f2
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !For more context, check log files in: /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/logs/mt-125
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !****************************************************************************
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !This node experienced a fatal error (printed above), and as a result the
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !process is terminating.
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !problem in CockroachDB. With your help, the support team at Cockroach Labs
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !will try to determine the root cause, recommend next steps, and we can
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !improve CockroachDB based on your report.
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !Please submit a crash report by following the instructions here:
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !    https://github.com/cockroachdb/cockroach/issues/new/choose
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !If you would rather not post publicly, please contact us directly at:
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !    support@cockroachlabs.com
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !
F210510 21:07:02.883712 24 sql/descriptor.go:162  [intExec=create-default-DB] 43 !The Cockroach Labs team appreciates your feedback.
```

</details>

Worse than that, subsequent attempts to create the tenant unable to go through. It's unclear how to recover from it, but probably undesirable to leave it polluted.

```
$ cockroach sql --insecure -e 'select crdb_internal.create_tenant(123);'
ERROR: crdb_internal.create_tenant(): programming error: tenant already exists but was not in system.tenants table: unexpected value: raw_bytes:"\037\364\375\203\001\032" timestamp:<wall_time:1620680661570997000 >
Failed running "sql"
```

**To Reproduce**

See above.

**Expected behavior**

Nicer errors, and not polluting system.tenants to bar future attempts to add the tenant.

**Comment by ajwerner** [comment]
Though, this leads to some interesting questions. What prevents a tenant from writing or connecting to a cluster if it doesn't exist in the tenants table? In the real cluster, the security stuff I *think* makes this case not really possible. Perhaps we should have `mt start` somehow prove that the tenant has been created. It's crashing here because its descriptor table was never bootstrapped. This is silly

**Comment by ajwerner** [comment]
Perhaps we should rework this issue to say something like KV servers never verify the status of a tenant.

**Comment by dhartunian** [comment]
> I think this should be handled hand in hand with #64474. @rimadeodhar @dhartunian what do you think?

@knz seems like something that would be good for Obs Infra to pick up given the other work we're doing in this space. We'll need to get acquainted with this code anyway over the next few weeks.

**Comment by rimadeodhar** [comment]
> > I think this should be handled hand in hand with #64474. @rimadeodhar @dhartunian what do you think?
> 
> @knz seems like something that would be good for Obs Infra to pick up given the other work we're doing in this space. We'll need to get acquainted with this code anyway over the next few weeks.

Seems reasonable, I can look into this along with #64474.

**Comment by rimadeodhar** [comment]
Looking into this, my idea was to check if the system.tenants contained a record for the tenant id and return an error if it doesn't so as to make it obvious to the operator that a tenant needs to be created first through create_tenant. However. it seems like we cannot use GetTenantRecord within [preStart](https://github.com/cockroachdb/cockroach/blob/4c80a2e5b4d232c07ee69ec8314a4e8bada2a61f/pkg/server/server_sql.go) to verify if the tenant was successfully created since we don't have access to the records with the system.tenants table within StartTenant. Unless there is a way to do this and I'm missing something?
Another option would be to check that the descriptor table has been bootstrapped correctly and return a "Tenant not created" error if it is not. But not sure whats the best way to check if the descriptor table has been bootstrapped correctly. Thoughts?

**Comment by ajwerner** [comment]
> Another option would be to check that the descriptor table has been bootstrapped correctly and return a "Tenant not created" error if it is not. But not sure whats the best way to check if the descriptor table has been bootstrapped correctly. Thoughts?

I think this is the right idea! Simpler than a descriptor would be to read the system database namespace entry. Try:

```go
func checkTenantExists{ctx context.Context, codec keys.SQLCodec, db *kv.DB) error { 
    key := catalogkeys.NewDatabaseKey(systemschema.SystemDatabaseName).Key(codec)
    kv, err := db.Get(key)
    if err != nil {
        return err
    }
    // at least check if the value exists, maybe confirm it is equal to keys.SystemDatabaseID
}
```

**Comment by knz** [comment]
Isn't that check incomplete? I vaguely recall the tenant's system tables are created incrementally (i.e. not at once in one big transaction) so this check could succeed while the remainder system tables are not created yet?

Ideally we'd have a "completion" marker at the end of the creation process and assert that it's available.

**Comment by ajwerner** [comment]
This is just a sanity check for dev environments; in production we rely on the tenant record existing in order to generate certificates iiuc. I don't think the check needs to be complete.

**Comment by rimadeodhar** [comment]
Sounds good, thanks @ajwerner and @knz!
