### ISSUE TITLE
"deadline below read timestamp is nonsensical; txn has would have no chance to commit" when testing enum-related schema changes

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#65136]
**Describe the problem**

In https://github.com/cockroachdb/cockroach/pull/64725 we've attempted to add a new event to ChangefeedNemeses that adds an enum and then adds a column to a table being targetted by a changefeed.  This test immediately revealed the following error:

```
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4  deadline below read timestamp is nonsensical; txn has would have no chance to commit. Deadline: 1620919820.842365000,1. Read timestamp: 1620919822.147064000,0 Previous Deadline: <nil>.
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !goroutine 23857 [running]:
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xbdd6600, 0xc003a6b6c8, 0x73, 0xc003a6b6c8)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb9
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000d6e520, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x167ea9fd80791c30, 0x400000000, 0x0, ...)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:277 +0xc87
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x9abe970, 0xc002c3c930, 0x1, 0x4, 0x877278d, 0x8d, 0xc001dd6120, 0x3, 0x3)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:58 +0x198
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:834
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/kv.(*Txn).UpdateDeadline(0xc002c530e0, 0x9abe970, 0xc002c3c930, 0x167ea9fd32b2f048, 0x1, 0x0, 0x0)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:703 +0x227
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).MaybeUpdateDeadline(0xc004064280, 0x9abe970, 0xc002c3c930, 0xc002c530e0, 0x82f3860, 0xc007f54c30)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:355 +0x1cf
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc004064000, 0x9abe970, 0xc002c3c930, 0x9ae59b8, 0xc007f54c30, 0xc000abf4f0, 0x78, 0x3, 0x1, 0xc006270ff0, ...)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:255 +0x15e
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc004064000, 0x9abe8c8, 0xc002b7c200, 0x9ae59b8, 0xc007f54c30, 0xc000abf4f0, 0x78, 0x3, 0x1, 0xc006270ff0, ...)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:122 +0xb7c
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal(0xc004064000, 0x9abe8c8, 0xc002b7c200, 0xc006270ff0, 0xc002c3c7b0, 0x3, 0x3, 0xbe25418, 0x1, 0x1, ...)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:209 +0x14e
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2(0xc000abf5a5, 0x0, 0x0, 0x8c39b48, 0xed82f3d0e, 0x0, 0xc004064000, 0xc001dd7a00, 0xc001dd79f0, 0x1cc, ...)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1594 +0x47b
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc004064000, 0x9abe8c8, 0xc002b7c200, 0x0, 0x0)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1596 +0x4df
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc004064000, 0x9abe8c8, 0xc0031f5ec0, 0xc0037f1220, 0x5400, 0x15000, 0xc0037f12c0, 0xc002ebecd0, 0x0, 0x0)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1450 +0x22f
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc006196b00, 0x9abe8c8, 0xc0031f5ec0, 0xc004064000, 0x5400, 0x15000, 0xc0037f12c0, 0xc002ebecd0, 0x0, 0x0)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:485 +0xce
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00568d910, 0xc001966b70, 0x9abe8c8, 0xc0031f5ec0, 0xc002ebecd0, 0xc006196b00, 0xc00370db00, 0x9b1b890, 0xc005848400, 0xc004f16d20, ...)
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:626 +0x3f5
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !  /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:554 +0x185
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !For more context, check log files in: /var/folders/b4/2b8v9mcx5x9d64k7q3m0fz_40000gp/T/logTestChangefeedNemeses613980182
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !****************************************************************************
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !This node experienced a fatal error (printed above), and as a result the
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !process is terminating.
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !problem in CockroachDB. With your help, the support team at Cockroach Labs
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !will try to determine the root cause, recommend next steps, and we can
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !improve CockroachDB based on your report.
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !Please submit a crash report by following the instructions here:
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !    https://github.com/cockroachdb/cockroach/issues/new/choose
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !If you would rather not post publicly, please contact us directly at:
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !    support@cockroachlabs.com
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !
F210513 15:30:22.147198 23857 kv/txn.go:703  [n1,client=127.0.0.1:57785,hostssl,user=root] 4 !The Cockroach Labs team appreciates your feedback.
```

- Logging manually added shows that the descriptor in question is for the enum that we are adding in the nemeses tests:
```
unexpected descriptor with lease below read timestamp: lease for enum0 55@3 1620918946.159067000,0 exp 1620918946.187000000,1 > 1620918947.309196000,0
```

- CI failure with all goroutine stacks: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2976561 (see testlogs in artifacts tab)

<details>
<summary>  Additional logging from the Nemeses tests showing the sequence of operations</summary>

```
I210513 15:30:19.311593 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2697  upsert transaction
I210513 15:30:19.315672 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2698  upsert transaction
I210513 15:30:19.316451 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2699  upsert transaction
I210513 15:30:19.317215 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2700  upsert transaction
I210513 15:30:19.317969 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2701  upsert transaction
I210513 15:30:19.318733 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2702  upsert transaction
I210513 15:30:19.319446 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2703  upsert transaction
I210513 15:30:19.325648 22152 ccl/changefeedccl/cdctest/nemeses.go:563 ⋮ [-] 2704  delete transaction
I210513 15:30:19.327616 22152 ccl/changefeedccl/cdctest/nemeses.go:563 ⋮ [-] 2705  delete transaction
I210513 15:30:19.328568 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2706  upsert transaction
I210513 15:30:19.329306 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2707  upsert transaction
I210513 15:30:19.330055 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2708  upsert transaction
I210513 15:30:19.330790 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2709  upsert transaction
I210513 15:30:19.331545 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2710  upsert transaction
I210513 15:30:19.332249 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2711  upsert transaction
I210513 15:30:19.332999 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2712  upsert transaction
I210513 15:30:19.333767 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2713  upsert transaction
I210513 15:30:19.334516 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2714  upsert transaction
I210513 15:30:19.335293 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2715  upsert transaction
I210513 15:30:19.336364 22152 ccl/changefeedccl/cdctest/nemeses.go:563 ⋮ [-] 2716  delete transaction
I210513 15:30:19.414075 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2737  event: ‹cdctest.eventOpenTxn{}› openTxn?: false
I210513 15:30:19.414180 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2738  upsert transaction
I210513 15:30:19.414657 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2739  event: ‹cdctest.eventPause{}› openTxn?: true
I210513 15:30:19.426679 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2742  event: ‹cdctest.eventResume{}› openTxn?: true
I210513 15:30:19.428678 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2743  event: ‹cdctest.eventCommit{}› openTxn?: true
I210513 15:30:19.428954 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2744  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:20.420316 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2748  event: ‹cdctest.eventSplit{}› openTxn?: false
I210513 15:30:20.423793 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2750  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:20.424457 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2751  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:20.425060 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2752  event: ‹cdctest.eventCreateEnum{}› openTxn?: false
I210513 15:30:20.427360 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2754  event: ‹cdctest.eventCreateEnum{}› openTxn?: false
I210513 15:30:20.430256 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2757  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:20.431203 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2758  event: ‹cdctest.eventOpenTxn{}› openTxn?: false
I210513 15:30:20.431311 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2759  upsert transaction
I210513 15:30:20.431776 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2760  event: ‹cdctest.eventCommit{}› openTxn?: true
I210513 15:30:20.432076 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2761  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:20.470737 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2762  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:20.726177 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2763  event: ‹cdctest.eventAddColumn{CanAddColumnAfter:true}› openTxn?: false
I210513 15:30:20.726204 22152 ccl/changefeedccl/cdctest/nemeses.go:616 ⋮ [-] 2764  adding enum column
I210513 15:30:20.787048 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2808  event: ‹cdctest.eventPause{}› openTxn?: false
I210513 15:30:20.798056 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2811  event: ‹cdctest.eventOpenTxn{}› openTxn?: false
I210513 15:30:20.798140 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 2812  upsert transaction
I210513 15:30:20.798752 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2813  event: ‹cdctest.eventResume{}› openTxn?: true
I210513 15:30:20.800691 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2814  event: ‹cdctest.eventRollback{}› openTxn?: true
I210513 15:30:20.800940 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2815  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:20.841512 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2818  event: ‹cdctest.eventAddColumn{CanAddColumnAfter:true}› openTxn?: false
I210513 15:30:20.841532 22152 ccl/changefeedccl/cdctest/nemeses.go:616 ⋮ [-] 2819  adding enum column
I210513 15:30:20.904352 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2884  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.146182 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2886  event: ‹cdctest.eventAddColumn{CanAddColumnAfter:true}› openTxn?: false
I210513 15:30:21.146200 22152 ccl/changefeedccl/cdctest/nemeses.go:623 ⋮ [-] 2887  adding string column
I210513 15:30:21.218892 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2952  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.222846 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2953  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.224007 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2954  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.225119 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 2955  event: ‹cdctest.eventAddColumn{CanAddColumnAfter:true}› openTxn?: false
I210513 15:30:21.225133 22152 ccl/changefeedccl/cdctest/nemeses.go:623 ⋮ [-] 2956  adding string column
I210513 15:30:21.285559 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3021  event: ‹cdctest.eventAddColumn{CanAddColumnAfter:true}› openTxn?: false
I210513 15:30:21.285590 22152 ccl/changefeedccl/cdctest/nemeses.go:623 ⋮ [-] 3022  adding string column
I210513 15:30:21.358433 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3088  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.367011 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3089  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.369478 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3090  event: ‹cdctest.eventOpenTxn{}› openTxn?: false
I210513 15:30:21.369570 22152 ccl/changefeedccl/cdctest/nemeses.go:554 ⋮ [-] 3091  upsert transaction
I210513 15:30:21.370689 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3092  event: ‹cdctest.eventAbort{}› openTxn?: true
I210513 15:30:21.382750 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3093  event: ‹cdctest.eventRollback{}› openTxn?: true
I210513 15:30:21.383028 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3094  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.419663 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3095  event: ‹cdctest.eventAddColumn{CanAddColumnAfter:true}› openTxn?: false
I210513 15:30:21.419681 22152 ccl/changefeedccl/cdctest/nemeses.go:623 ⋮ [-] 3096  adding string column
I210513 15:30:21.482560 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3161  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.532319 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3164  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.567338 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3165  event: ‹cdctest.eventRemoveColumn{CanRemoveColumnAfter:true}› openTxn?: false
I210513 15:30:21.637460 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3231  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.731498 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3232  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
I210513 15:30:21.931447 22152 ccl/changefeedccl/cdctest/nemeses.go:514 ⋮ [-] 3233  event: ‹cdctest.eventFeedMessage{}› openTxn?: false
```
</details>

**To Reproduce**

- Checkout branch from https://github.com/cockroachdb/cockroach/pull/53771
- Run: `make test GOTESTFLAGS="-v -count 1" PKG=./pkg/ccl/changefeedccl TESTS=TestChangefeedNemeses` until you hit it

**Comment by jordanlewis** [comment]
Thanks for the issue, this does seem problematic. @fqazi do you understand what's going on here?

**Comment by fqazi** [comment]
Let me take a look at this one, its linked to the deadline logic overhaul

**Comment by fqazi** [comment]
This looks similar to https://github.com/cockroachdb/cockroach/issues/64140, the bind is acquiring leases inside the desc collection. When the transaction hits an open state the deadline is based on an old completed transaction. Fixing the bind issue would also fix this.

**Comment by jordanlewis** [comment]
Interesting...
