### ISSUE TITLE
txn error

### ISSUE THREAD

**Issue by James601232** [cockroachdb/cockroach#65603]
**Describe the problem**
I have a method that insert and update table use mybatis. there are txn errors while frequently or concurrency invoke. following are errors log:

2021-05-20 17:24:23 ERROR c.q.b.s.w.c.GlobalDefaultExceptionHandler - Exception occurred: Could not commit JDBC transaction; nested exception is org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=160ce3ca key=/Table/727/1/12050/0 pri=0.01029400 epo=0 ts=1621502662.123867538,1 min=1621502659.839426765,0 seq=75} lock=true stat=PENDING rts=1621502659.839426765,0 wto=false max=1621502660.339426765,0
  Hint: See: https://www.cockroachlabs.com/docs/v20.2/transaction-retry-error-reference.html#retry_serializable
org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=160ce3ca key=/Table/727/1/12050/0 pri=0.01029400 epo=0 ts=1621502662.123867538,1 min=1621502659.839426765,0 seq=75} lock=true stat=PENDING rts=1621502659.839426765,0 wto=false max=1621502660.339426765,0
  Hint: See: https://www.cockroachlabs.com/docs/v20.2/transaction-retry-error-reference.html#retry_serializable
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:332)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:534)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:305)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)

And my method like this:
 **@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
    public void saveInstance(InstanceRequest instance)**

Anyone can help me how to avoid this error. thanks in advance.

**Comment by rafiss** [comment]
hi @James601232 -- have you seen the docs about transaction retry errors? https://www.cockroachlabs.com/docs/stable/transaction-retry-error-reference.html These kinds of errors are expected, since CockroachDB uses SERIALIZABLE isolation.

Also, here is an example of how to configure Spring to automatically retry these errors: https://github.com/cockroachlabs/roach-data/blob/master/roach-data-jpa/src/main/java/io/roach/data/jpa/RetryableTransactionAspect.java

**Comment by zhangliangcome** [comment]
@James601232 How to solve this problem? I also encountered the same problem.

**Comment by zhangliangcome** [comment]
I got it

**Comment by Satyam012** [comment]
@zhangliangcome I'm also facing the same error, how did you resolve it?
