### ISSUE TITLE
backupccl: NPE during write to GCS

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#65611]
Created a scheduled backup to gcs. Two nodes crashed with NPE:

```goroutine 2879382 [running]:
panic(0x46894c0, 0x7f3f210)
        /usr/local/go/src/runtime/panic.go:1064 +0x545 fp=0xc00483fe00 sp=0xc00483fd38 pc=0x48b725
runtime.panicmem(...)
        /usr/local/go/src/runtime/panic.go:212
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:742 +0x413 fp=0xc00483fe30 sp=0xc00483fe00 pc=0x4a2473
cloud.google.com/go/storage.(*Writer).open.func1(0xc01fcc4b40, 0xc015571880, 0xc04cc15278, 0xc01bb4ca60, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/vendor/cloud.google.com/go/storage/writer.go:131 +0xfa fp=0xc00483ffb0 sp=0xc00483fe30 pc=0x375c95a
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00483ffb8 sp=0xc00483ffb0 pc=0x4c4ae1
created by cloud.google.com/go/storage.(*Writer).open
        /go/src/github.com/cockroachdb/cockroach/vendor/cloud.google.com/go/storage/writer.go:118 +0x412```

**Comment by dt** [comment]
I think this is an upstream bug in the SDK, since some println debugging revealed that when we hit this crash, we've already closed both the writer and the client that created it. File as https://github.com/googleapis/google-cloud-go/issues/4167

**Comment by dt** [comment]
#65660
