### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestTxnCoordSenderNoDuplicateIntents

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6575]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/c2e0eb023866ede8a42c8a8b4b77cef36825838e

Stress build found a failed test:

```
=== RUN   TestTxnCoordSenderNoDuplicateIntents
I160508 04:32:26.598847 stopper.go:352  draining; tasks left:
1      kv/txn_coord_sender.go:895
--- FAIL: TestTxnCoordSenderNoDuplicateIntents (5.05s)
	leaktest.go:85: Leaked goroutine: goroutine 1509 [select]:
		github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
			/go/src/github.com/cockroachdb/cockroach/storage/store.go:2065 +0xbf1
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200621c0, 0xc820b44950)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
1 runs so far, 0 failures, over 20s
7 runs so far, 0 failures, over 25s
14 runs so far, 0 failures, over 30s
16 runs so far, 0 failures, over 35s
16 runs so far, 0 failures, over 40s
19 runs so far, 0 failures, over 45s
23 runs so far, 0 failures, over 50s
31 runs so far, 0 failures, over 55s
32 runs so far, 0 failures, over 1m0s
33 runs so far, 0 failures, over 1m5s
36 runs so far, 0 failures, over 1m10s
39 runs so far, 0 failures, over 1m15s
45 runs so far, 0 failures, over 1m20s
49 runs so far, 0 failures, over 1m25s
50 runs so far, 0 failures, over 1m30s
53 runs so far, 0 failures, over 1m35s
56 runs so far, 0 failures, over 1m40s
60 runs completed, 1 failures, over 1m43s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
Fluke. Investigating when it reappears.
