### ISSUE TITLE
TestStoreRangeDownReplicate failing

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#6600]
https://circleci.com/gh/cockroachdb/cockroach/17540

I don't think the test itself failed.

```
W160510 01:20:43.788779 kv/dist_sender.go:763  range 2 was not found
I160510 01:20:43.789071 client/db.go:479  failed batch: range 2 was not found
I160510 01:20:43.789428 storage/intent_resolver.go:104  [node=1,store=1,range=1] on Put: range 2 was not found
W160510 01:20:43.791605 kv/dist_sender.go:732  failed to invoke BeginTransaction [/Local/Range/"m"/RangeDescriptor,/Min), ConditionalPut [/Local/Range/"m"/RangeDescriptor,/Min), Put [/Meta2/Max,/Min): range 2 was not found
W160510 01:20:43.791859 kv/dist_sender.go:763  range 2 was not found
F160510 01:20:43.792098 kv/txn_coord_sender.go:832  retryable internal error must not happen at this level: range 2 was not found
goroutine 6049 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0x36d1d00, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:862 +0xcf
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x2d28480, 0x3, 0x276d419, 0x16, 0x340, 0xc820a5c960, 0x4d)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:726 +0x199
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x200000003, 0x2, 0x1f3fde0, 0x3a, 0xc8207e8040, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0x10a
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x7f4900000003, 0x1f3fde0, 0x3a, 0xc8207e8040, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x8d
github.com/cockroachdb/cockroach/util/log.Fatalf(0x1f3fde0, 0x3a, 0xc8207e8040, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x74
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:383 +0x361
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8204c9180, 0xc82049cec0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	14.072s
=== RUN   TestBatchBasics
I160510 01:20:58.763317 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160510 01:20:58.765128 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.03s)
=== RUN   TestBatchGet
I160510 01:20:58.790999 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160510 01:20:58.792640 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I160510 01:20:58.800668 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
```

**Comment by bdarnell** [comment]
Other similar issues: #6446, #6436, #2500, #5722. I'm doing some work related to this in #2500, but I'm not sure yet whether it will fix this test or just downgrade it from a panic to an error.
