### ISSUE TITLE
circleci: failed tests: TestRetryOnWrongReplicaError

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6623]
The following test appears to have failed:

[#17619](https://circleci.com/gh/cockroachdb/cockroach/17619):

```
I160511 11:58:21.027104 gossip/simulation/network.go:57  simulating gossip network with 1 nodes
W160511 11:58:21.027472 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
W160511 11:58:21.027554 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
W160511 11:58:21.027948 kv/dist_sender.go:655  key "\"a\"" not contained in range lookup's resulting decriptor range_id:2 start_key:"m" end_key:"z" replicas:<node_id:1 store_id:1 replica_id:0 > next_replica_id:0 
I160511 11:58:21.028027 gossip/gossip.go:918  starting client to 127.0.0.1:55692
panic: test timed out after 1m10s

goroutine 308 [running]:
panic(0x1442180, 0xc8201a0a20)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0x1ba7d40, 0x2306bc0, 0x77, 0x77, 0x1)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820037f08, 0x1824738)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/kv/_test/_testmain.go:296 +0x117

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x25de8a0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 252 [semacquire]:
sync.runtime_Semacquire(0xc82022e174)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82022e168)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc82022e150)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:302 +0x1dd
github.com/cockroachdb/cockroach/gossip/simulation.(*Network).Stop(0xc8200146c0)
	/go/src/github.com/cockroachdb/cockroach/gossip/simulation/network.go:176 +0x9c
github.com/cockroachdb/cockroach/gossip/simulation.(*Network).Stop-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_test.go:86 +0x20
--
testing.tRunner(0xc82024e1b0, 0x2306c80)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 297 [select]:
google.golang.org/grpc/transport.(*Stream).Header(0xc82021c460, 0xc82021c460, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x7fd5d6653ad0, 0x2607be8, 0x0, 0x0, 0x0, 0x0, 0x7fd5d66553c8, 0xc8200b3960, 0x7fd5d66553f0, 0xc8200b39c0, ...)
	/go/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x7fd5d6655530, 0xc8201849c0, 0x1911160, 0x1d, 0x1789300, 0xc8201c6b40, 0x1777c80, 0xc82016f520, 0xc8200e24d0, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:178 +0xae6
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc820026378, 0x7fd5d6655530, 0xc8201849c0, 0xc8201c6b40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:119 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).heartbeat(0xc82022e1c0, 0x7fd5d66554d8, 0xc820026378, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:237 +0x150
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82022e150, 0xc820187920)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 298 [IO wait]:
net.runtime_pollWait(0x7fd5d6654b38, 0x72, 0xc820200000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82022ef40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82022ef40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82022eee0, 0xc820200000, 0x8000, 0x8000, 0x0, 0x7fd5d668f050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820026380, 0xc820200000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc/transport.(*http2Client).reader(0xc8202180f0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:774 +0x42
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:174 +0xd21

goroutine 299 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8202180f0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:866 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:201 +0x15c2

goroutine 296 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc820218000)
	/go/src/google.golang.org/grpc/clientconn.go:544 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc820218000)
	/go/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3
FAIL	github.com/cockroachdb/cockroach/kv	70.038s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestMustSetInner
--- PASS: TestMustSetInner (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestBatchRequestString
--- PASS: TestBatchRequestString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment]
This is likely related to my work in #6578

**Comment by bdarnell** [comment]
This hasn't happened again, and I made a bunch of changes in the `kv` package after we saw this, so I assume it's fixed.
