### ISSUE TITLE
Geoserver support on the fly simplification

### ISSUE THREAD

**Issue by elariroop** [cockroachdb/cockroach#66309]
Hi, it seems that this is still missing a function for geoserver on the fly simplification:

CockroachDB CCL v21.1.2 (x86_64-unknown-linux-gnu, built 2021/06/07 18:09:50, go1.15.11)

Caused by: org.postgresql.util.PSQLException: ERROR: unknown function: st_hasarc()
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)

"Support on the fly geometry simplification" is on by default so this would be really nice to have.

**Comment by otan** [comment]
v21.2.4 should have the fix (#66531)
