### ISSUE TITLE
importccl: TestImportCSVStatement failed [deadlock on shutdown]

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#66875]
TestImportCSVStatement failed on an unrelated PR (touching only roachtest) on testcluster shutdown, with this goroutine preventing termination:

```
goroutine 152119 [chan receive, 27 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/importccl.TestImportCSVStmt.func1(0x94c763d953c8001, 0xc00864a300, 0xc00c5d7a58)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt_test.go:1743 +0x33
github.com/cockroachdb/cockroach/pkg/sql/gcjob.schemaChangeGCResumer.Resume(0x94c763d953c8001, 0x5e26bf0, 0xc01543ac00, 0x4681a80, 0xc00c5d7a58, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/gcjob/gc_job.go:93 +0xaa6
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1(0xc004cc82c0, 0x5de1f30, 0xc0119d2a78, 0x5e26bf0, 0xc01543ac00, 0x4681a80, 0xc00c5d7a58, 0xc0194dd9f8)
	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1025 +0xae
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine(0xc00a2184e0, 0x5e26bf0, 0xc015a203f0, 0x4681a80, 0xc00c5d7a58, 0x5de1f30, 0xc0119d2a78, 0xc0189b5680, 0xc0119d2971, 0x7, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1026 +0x87c
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob(0xc00a2184e0, 0x5e26b48, 0xc011a149c0, 0x5de1f30, 0xc0119d2a78, 0xc0189b5680, 0xc0119d2971, 0x7, 0xc005973a70, 0x16, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:281 +0x47b
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1(0x5e26b48, 0xc006420380)
	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:222 +0x165
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc00c3ce380, 0x5e26b48, 0xc006420380, 0x0, 0xc01274be00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0xb9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:342 +0xfc
```

https://teamcity.cockroachdb.com/repository/download/Cockroach_UnitTests_Test/3115686:id/raw.1.json.txt.tgz!/artifacts/full_output.txt

Epic CRDB-7778

Jira issue: CRDB-8274

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/blob/a40102ab744ef9f5ee18ce84d26b3c94d7be5e16/pkg/ccl/importccl/import_stmt_test.go#L1743-L1742

**Comment by stevendanna** [comment]
Import goroutine management has changed a lot since this was opened. I'm going to close this.
