### ISSUE TITLE
circleci: failed tests: TestMultiRangeMergeStaleDescriptor

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6699]
The following test appears to have failed:

[#17832](https://circleci.com/gh/cockroachdb/cockroach/17832):

```
3      gossip/infostore.go:286
I160516 13:56:14.402911 stopper.go:352  draining; tasks left:
2      gossip/infostore.go:286
I160516 13:56:14.402944 stopper.go:352  draining; tasks left:
1      gossip/infostore.go:286
panic: test timed out after 1m10s

goroutine 462 [running]:
panic(0x14522c0, 0xc820011ef0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0x1bc6b08, 0x232f160, 0x78, 0x78, 0x1)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc8202d7f08, 0x183c408)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/kv/_test/_testmain.go:298 +0x117

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2606f60)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 437 [semacquire]:
sync.runtime_Semacquire(0xc82013a174)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82013a168)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc82013a150)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:302 +0x1dd
github.com/cockroachdb/cockroach/gossip/simulation.(*Network).Stop(0xc82017c180)
	/go/src/github.com/cockroachdb/cockroach/gossip/simulation/network.go:176 +0x9c
github.com/cockroachdb/cockroach/gossip/simulation.(*Network).Stop-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_test.go:127 +0x20
--
testing.tRunner(0xc8202763f0, 0x232f298)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 453 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8202280f0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:866 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:201 +0x15c2

goroutine 451 [select]:
google.golang.org/grpc/transport.(*Stream).Header(0xc8201388c0, 0xc8201388c0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x7f98f1d4dff0, 0x2630390, 0x0, 0x0, 0x0, 0x0, 0x7f98f1d819d0, 0xc8201b0b80, 0x7f98f1d819f8, 0xc8201b0be0, ...)
	/go/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x7f98f1d81b38, 0xc82024c6f0, 0x192a4c0, 0x1d, 0x17a0260, 0xc8201d7a00, 0x178ec00, 0xc820162a80, 0xc820236370, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:178 +0xae6
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc8200260b8, 0x7f98f1d81b38, 0xc82024c6f0, 0xc8201d7a00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:119 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).heartbeat(0xc82013a230, 0x7f98f1d81ae0, 0xc8200260b8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:237 +0x150
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82013a150, 0xc8201d91a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 450 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc820228000)
	/go/src/google.golang.org/grpc/clientconn.go:544 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc820228000)
	/go/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3

goroutine 452 [IO wait]:
net.runtime_pollWait(0x7f98f1d4f058, 0x72, 0xc8202c6000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82013ad80, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82013ad80, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82013ad20, 0xc8202c6000, 0x8000, 0x8000, 0x0, 0x7f98f1d7d050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200260c0, 0xc8202c6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc8202280f0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:774 +0x42
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:174 +0xd21
FAIL	github.com/cockroachdb/cockroach/kv	70.047s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestMustSetInner
--- PASS: TestMustSetInner (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestBatchRequestString
--- PASS: TestBatchRequestString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment]
This test is almost a year old and has never been flaky before. I'm going to guess that this (and perhaps other recent timeouts) are due to my retry-related changes.

**Comment by tschottdorf** [comment]
Are you sure? Looks like a stuck gossip task to me, in which it would make sense that it'd hit random tests that use a gossip network.

**Comment by bdarnell** [comment]
Yeah, but my sense is that these have become much more common since around the time that my changes started merging, and there haven't been substantial changes to gossip or rpc over the same time period (the timeouts I've found have been in the kv package and not the gossip package). I suspect it's something incidental to my changes (especially to the way tests are set up and run), not directly related to retries.

**Comment by tschottdorf** [comment]
I see. https://github.com/cockroachdb/cockroach/issues/6593 might be related.

**Comment by tschottdorf** [comment]
And https://github.com/cockroachdb/cockroach/issues/6674

**Comment by bdarnell** [comment]
The root cause is a GRPC bug: grpc/grpc-go#684. We're also not checking stopper.ShouldStop when we should in the rpc heartbeat loop. None of this code has seen any substantial changes recently, so the only reason it would have gotten more common is if incidental timing changes make the race more likely.
