### ISSUE TITLE
sql: TestPGPreparedQuery timed out

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6701]
Gave it a passing glance, wasn't able to spot anything obvious.
https://circleci.com/gh/cockroachdb/cockroach/17837

**Comment by tschottdorf** [comment]
Looks like a client connection stuck during the handshake. Not sure whether this is just a fluke, but could potentially be something about cmux? @tamird

server:
```
goroutine 33299 [IO wait]:
net.runtime_pollWait(0x7fa021087788, 0x72, 0xc820b1a400)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820b22140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820b22140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820b220e0, 0xc820b1a400, 0x400, 0x400, 0x0, 0x7fa0210be050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82018a970, 0xc820b1a400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/cockroachdb/cmux.(*MuxConn).Read(0xc821045810, 0xc820b1a400, 0x400, 0x400, 0xd, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cmux/cmux.go:204 +0x117
crypto/tls.(*block).readFromUntil(0xc8202f1b00, 0x7fa021089bb0, 0xc821045810, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820ca6000, 0x1c32417, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820ca6000, 0xc8206a3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc82055d260)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadByte(0xc82055d260, 0x6, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:229 +0x7a
github.com/cockroachdb/cockroach/sql/pgwire.(*readBuffer).readTypedMsg(0xc820dc0028, 0x7fa0210e3370, 0xc82055d260, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/encoding.go:93 +0x3a
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc820dc0000, 0xc820d9b640, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:256 +0x967
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc820717d70, 0x7fa02108a5e0, 0xc820ca6000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:224 +0x99b
github.com/cockroachdb/cockroach/server.(*Server).Start.func6.1(0x7fa021089b50, 0xc821045810)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:341 +0x3f
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc820a71500, 0x7fa021089b50, 0xc821045810, 0xc82074e030)
	/go/src/github.com/cockroachdb/cockroach/util/net.go:125 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/go/src/github.com/cockroachdb/cockroach/util/net.go:127 +0x31f
```

client:
```
goroutine 33136 [IO wait]:
net.runtime_pollWait(0x7fa0210876c8, 0x72, 0xc820b28000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202dba30, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202dba30, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202db9d0, 0xc820b28000, 0x400, 0x400, 0x0, 0x7fa0210be050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8208dc308, 0xc820b28000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82032eb10, 0x7fa0210dc838, 0xc8208dc308, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8207bf200, 0xc820116e16, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).readHandshake(0xc8207bf200, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:800 +0xd3
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc8219f31a0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_client.go:312 +0xa4a
crypto/tls.(*Conn).clientHandshake(0xc8207bf200, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_client.go:213 +0x1737
crypto/tls.(*Conn).Handshake(0xc8207bf200, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1033 +0xec
crypto/tls.(*Conn).Write(0xc8207bf200, 0xc820bb71a1, 0x50, 0x1ff, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:880 +0x142
github.com/cockroachdb/pq.(*conn).sendStartupPacket(0xc820bb7180, 0xc8219f3648)
	/go/src/github.com/cockroachdb/pq/conn.go:912 +0x225
github.com/cockroachdb/pq.(*conn).startup(0xc820bb7180, 0xc8219f3b78)
	/go/src/github.com/cockroachdb/pq/conn.go:1222 +0x532
github.com/cockroachdb/pq.DialOpen(0x7fa02108c2e0, 0x26b3978, 0xc820270750, 0xc4, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/pq/conn.go:336 +0xf71
github.com/cockroachdb/pq.Open(0xc8204c62a0, 0xd2, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/pq/conn.go:246 +0x9e
github.com/cockroachdb/pq.(*drv).Open(0x26b3978, 0xc8204c62a0, 0xd2, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/pq/conn.go:45 +0x43
database/sql.(*DB).conn(0xc8212f5340, 0xc820d33d01, 0x7fa0210be028, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:821 +0x59d
database/sql.(*DB).prepare(0xc8212f5340, 0x188d0f0, 0xf, 0xc820010701, 0x1, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:981 +0x4e
database/sql.(*DB).Prepare(0xc8212f5340, 0x188d0f0, 0xf, 0xc8219f4c30, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:963 +0x76
github.com/cockroachdb/cockroach/sql_test.TestPGPreparedQuery(0xc820bb9170)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire_test.go:626 +0x119f1
testing.tRunner(0xc820bb9170, 0x23b0ae8)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
```

**Comment by tamird** [comment]
Cmux is an unlikely culprit here, we're already past the protocol sniffing stage, so we should not be doing anything other than a straight passthrough read. What's weird is that the client seems to think it's doing a handshake, but the server has already advanced beyond that stage.

**Comment by bdarnell** [comment]
There's another server stack trace that is in the middle of its handshake.

```
goroutine 33293 [runnable]:
math/big.(*Int).Mul(0xc820786840, 0xc820786840, 0xc8207867c0, 0xc821302c00)
	/usr/local/go/src/math/big/int.go:151
math/big.(*Int).GCD(0xc820786908, 0xc820c71ae0, 0xc8207868e8, 0xc820c71ac0, 0xc820852080, 0xc820c71ac0)
	/usr/local/go/src/math/big/int.go:469 +0x319
crypto/rsa.modInverse(0xc820c71ac0, 0xc820852080, 0x0, 0xc820c71a00)
	/usr/local/go/src/crypto/rsa/rsa.go:411 +0xb3
crypto/rsa.decrypt(0x7fa0210c2580, 0xc820017230, 0xc82083b1a0, 0xc820786bc8, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/rsa/rsa.go:487 +0x169
crypto/rsa.decryptAndCheck(0x7fa0210c2580, 0xc820017230, 0xc82083b1a0, 0xc820786bc8, 0xc820ccabd8, 0x0, 0x0)
	/usr/local/go/src/crypto/rsa/rsa.go:539 +0x66
crypto/rsa.SignPKCS1v15(0x7fa0210c2580, 0xc820017230, 0xc82083b1a0, 0x5, 0xc820c71aa0, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/crypto/rsa/pkcs1v15.go:249 +0x3d1
crypto/rsa.(*PrivateKey).Sign(0xc82083b1a0, 0x7fa0210c2580, 0xc820017230, 0xc820c71aa0, 0x20, 0x20, 0x7fa02108a388, 0xc8206ea3f0, 0x0, 0x0, ...)
	/usr/local/go/src/crypto/rsa/rsa.go:102 +0x184
crypto/tls.(*ecdheKeyAgreement).generateServerKeyExchange(0xc820a2bf80, 0xc8201f2780, 0xc820da3260, 0xc8201dadc0, 0xc820b8b760, 0x34f, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/key_agreement.go:255 +0xcc0
crypto/tls.(*serverHandshakeState).doFullHandshake(0xc820787610, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_server.go:373 +0x594
crypto/tls.(*Conn).serverHandshake(0xc820ca6f00, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_server.go:80 +0x31c
crypto/tls.(*Conn).Handshake(0xc820ca6f00, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1035 +0x169
crypto/tls.(*Conn).Read(0xc820ca6f00, 0xc820c71938, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:922 +0x6c
io.ReadAtLeast(0x7fa02108a668, 0xc820ca6f00, 0xc820c71938, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fa02108a668, 0xc820ca6f00, 0xc820c71938, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
github.com/cockroachdb/cockroach/sql/pgwire.(*readBuffer).readUntypedMsg(0xc820c71920, 0x7fa02108a668, 0xc820ca6f00, 0x7fa02108a668, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/encoding.go:73 +0xa4
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc820717d70, 0x7fa02108a5e0, 0xc820ca6f00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:186 +0x4bc
github.com/cockroachdb/cockroach/server.(*Server).Start.func6.1(0x7fa021089b50, 0xc820b8b6b0)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:341 +0x3f
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc820a71500, 0x7fa021089b50, 0xc820b8b6b0, 0xc82074e030)
	/go/src/github.com/cockroachdb/cockroach/util/net.go:125 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/go/src/github.com/cockroachdb/cockroach/util/net.go:127 +0x31f
```

**Comment by tamird** [comment]
That's also weird, since that goroutine is [runnable] while the client is in [IO wait].

**Comment by tamird** [comment]
Nothing left to go on here, giving this an unsatisfying close.
