### ISSUE TITLE
test failures - possible new http2 deadlock

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#67658]
I am seeing frequent CI failures with either the following symptoms:

- leaked goroutine 
- test timeout

in both cases with a stack trace that looks like the one below.

This suggests to me that there's again something amiss in the http2 code. We have upgraded the Go runtime in the past because there was a bug in the standard library. Maybe there is a new one.

```
goroutine 91182 [IO wait]:
internal/poll.runtime_pollWait(0x7f8d253b70d8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0071c3e98, 0x72, 0xcd00, 0xcd08, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0071c3e80, 0xc007cb2000, 0xcd08, 0xcd08, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0071c3e80, 0xc007cb2000, 0xcd08, 0xcd08, 0xc007cb2005, 0xc006622a18, 0xc0056a2828)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0005b4a98, 0xc007cb2000, 0xcd08, 0xcd08, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:183 +0x91
github.com/cockroachdb/cmux.(*MuxConn).Read(0xc006ad8240, 0xc007cb2000, 0xcd08, 0xcd08, 0x4527bb, 0xc001a08c00, 0x18)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:218 +0x11c
crypto/tls.(*atLeastReader).Read(0xc001a08c00, 0xc007cb2000, 0xcd08, 0xcd08, 0xcd03, 0xc0000b2800, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc00127fe78, 0x6523420, 0xc001a08c00, 0x450545, 0x4908fc0, 0x4cbb780)
        /usr/local/go/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc00127fc00, 0x7f8d207e6b98, 0xc006ad8240, 0x5, 0xc006ad8240, 0x58)
        /usr/local/go/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00127fc00, 0x0, 0x0, 0x4)
        /usr/local/go/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc00127fc00, 0xc0059fc000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc0090700c0, 0xc004f48c78, 0x9, 0x9, 0xc009c842a0, 0xc0056a2ce0, 0x44bb25)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x65231e0, 0xc0090700c0, 0xc004f48c78, 0x9, 0x9, 0x9, 0x4c3114, 0xc009d9c9c0, 0x6)
        /usr/local/go/src/io/io.go:328 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader(0xc004f48c78, 0x9, 0x9, 0x65231e0, 0xc0090700c0, 0x0, 0x0, 0x4f, 0x0)

```

Jira issue: CRDB-8655

**Comment by knz** [comment]
Example here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3187265?

**Comment by tbg** [comment]
Do avoid the fallout for now, we may want to consider allowlisting this stack in `leaktest.AfterTest`.

**Comment by knz** [comment]
It's not happening all the time
also the allowlist would not fix the test timeouts...

**Comment by knz** [comment]
I'm going to bump some things in #66880 and that includes one bit of http2. Let's see if the flakes reduce after that.

cc @miretskiy

**Comment by knz** [comment]
nvm, it still flakes https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/3212345?
