### ISSUE TITLE
rttanalysisccl: logging already active

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#67760]
An instance of the bench build failing with `panic: logging already active` in the `rttanalysisccl` package:

https://teamcity.cockroachdb.com/viewLog.html?buildId=3193819&buildTypeId=Cockroach_UnitTests_Bench&tab=buildLog

**Comment by RaduBerinde** [comment]
```
panic: logging already active; first use:
goroutine 93358 [running]:
runtime/debug.Stack(0xc0040cf4d8, 0x49cca5, 0x7a28458)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/cockroachdb/cockroach/pkg/util/log.setActive()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:433 +0x9b
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc008e08140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16927db28251d4cc, 0x100000000, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:262 +0x5a
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x64f14b0, 0xc007532b40, 0x1, 0x1, 0x4fe6218, 0x2d, 0xc0040cfca0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:58 +0x198
github.com/cockroachdb/cockroach/pkg/util/log.Infof(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:263
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).WriteBootstrapInfo(0xc0006e1490, 0xc00020c1f8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/stores.go:269 +0x1e5
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).maybeCleanupBootstrapAddressesLocked(0xc00020c1a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:755 +0x2ce
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).maybeSignalStatusChangeLocked(0xc00020c1a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1508 +0x345
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).manage.func1(0x64f14b0, 0xc009405620)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1421 +0x576
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc006530a80, 0x64f14b0, 0xc009405620, 0x0, 0xc00649c1d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0xb9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:342 +0xfc [recovered]
```

```

goroutine 93238 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc006530900, 0x64f1440, 0xc000124010)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:466 +0x2d3
panic(0x4b44b40, 0xc008e32540)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig(0xc0084acab0, 0xc000c15df0, 0xc000c15df8, 0xc000c15e01, 0x1, 0xc0084ac710, 0xc000c15dd8, 0xc000c15dd9, 0xc000c15e00, 0xc000c15e2d, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/flags.go:88 +0x1773
github.com/cockroachdb/cockroach/pkg/util/log.newLogScope(0x6553798, 0xc004cea240, 0x1, 0xc006468280)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/test_log_scope.go:163 +0x3db
github.com/cockroachdb/cockroach/pkg/util/log.ScopeWithoutShowLogs(0x6553798, 0xc004cea240, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/test_log_scope.go:94 +0x4e
github.com/cockroachdb/cockroach/pkg/util/log.Scope(0x6553798, 0xc004cea240, 0xc0021b7b00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/test_log_scope.go:73 +0x73
github.com/cockroachdb/cockroach/pkg/bench/rttanalysis.ExecuteRoundTripTest(0xc004cea240, 0xc00449dd58, 0xc007532540, 0x4fdfe6d, 0x2d, 0x53bbe44, 0x2b0, 0x4ffcc5a, 0x31, 0x4f4b451, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/bench/rttanalysis/rtt_analysis_bench.go:84 +0xae
github.com/cockroachdb/cockroach/pkg/ccl/benchccl/rttanalysisccl.RunRoundTripBenchmarkMultiRegion.func1(0xc004cea240)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/benchccl/rttanalysisccl/rtt_analysis_bench.go:53 +0x325
testing.(*B).runN(0xc004cea240, 0x1)
	/usr/local/go/src/testing/benchmark.go:192 +0xeb
testing.(*B).run1.func1(0xc004cea240)
	/usr/local/go/src/testing/benchmark.go:232 +0x57
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:225 +0x7f
```

**Comment by rafiss** [comment]
cc @pawalt -- just in case you have any thoughts right off the bat. if not, we can look into this later
