### ISSUE TITLE
storage/engine: Segfault in DBIterNext

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6800]
Seen on the gamma cluster with a jemalloc build of 5430fae (the beta candidate: #6770). Probably related to #6684.

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x7f2fd6979e78 pc=0x11023d6]

runtime stack:
runtime.throw(0x1aa5300, 0x2a)
        /usr/local/go/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 13849894 [syscall, locked to thread]:
runtime.cgocall(0x1120280, 0xc826755238, 0x0)
        /usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc8267551e8 sp=0xc8267551b8
github.com/cockroachdb/cockroach/storage/engine._Cfunc_DBIterNext(0x7f36a0c1c080, 0x7f36a0c1c001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        ??:0 +0x67 fp=0xc826755238 sp=0xc8267551e8
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBIterator).NextKey(0xc8271a8d70)
        /go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:760 +0xa3 fp=0xc826755310 sp=0xc826755238
github.com/cockroachdb/cockroach/storage/engine.MVCCIterate(0x7f36bcb2b068, 0xc8355ef0e0, 0x7f36bcb186e0, 0xc820383aa0, 0xc8355eec90, 0x26, 0x30, 0xc837559d60, 0x7, 0x8, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:1704 +0x1217 fp=0xc8267557b0 sp=0xc826755310
github.com/cockroachdb/cockroach/storage/engine.mvccScanInternal(0x7f36bcb2b068, 0xc8355ef0e0, 0x7f36bcb186e0, 0xc820383aa0, 0xc8355eec90, 0x26, 0x30, 0xc837559d60, 0x7, 0x8, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:1513 +0x171 fp=0xc826755890 sp=0xc8267557b0
github.com/cockroachdb/cockroach/storage/engine.MVCCScan(0x7f36bcb2b068, 0xc8355ef0e0, 0x7f36bcb186e0, 0xc820383aa0, 0xc8355eec90, 0x26, 0x30, 0xc837559d60, 0x7, 0x8, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:1534 +0x12e fp=0xc826755958 sp=0xc826755890
github.com/cockroachdb/cockroach/storage.(*Replica).Scan(0xc8212f9b00, 0x7f36bcb2b068, 0xc8355ef0e0, 0x7f36bcb186e0, 0xc820383aa0, 0x144fe0d3d3440c14, 0x20, 0x700000007, 0x2, 0x8e2, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:307 +0x1a6 fp=0xc826755a18 sp=0xc826755958
github.com/cockroachdb/cockroach/storage.(*Replica).executeCmd(0xc8212f9b00, 0x7f36bcb2b068, 0xc8355ef0e0, 0x0, 0x0, 0x0, 0x7f36bcb186e0, 0xc820383aa0, 0x0, 0x144fe0d3d3440c14, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:114 +0x1b71 fp=0xc8267561a0 sp=0xc826755a18
github.com/cockroachdb/cockroach/storage.(*Replica).executeBatch(0xc8212f9b00, 0x7f36bcb2b068, 0xc8355ef0e0, 0x0, 0x0, 0x7f36bcb186e0, 0xc820383aa0, 0x0, 0x144fe0d3d3440c14, 0x20, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2000 +0x331 fp=0xc8267568d8 sp=0xc8267561a0
github.com/cockroachdb/cockroach/storage.(*Replica).addReadOnlyCmd(0xc8212f9b00, 0x7f36bcb2b068, 0xc8355ef0e0, 0x144fe0d3d3440c14, 0x20, 0x700000007, 0x2, 0x8e2, 0x0, 0xc83f49f5c0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1166 +0x2af fp=0xc826756a10 sp=0xc8267568d8
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc8212f9b00, 0x7f36bcb2b068, 0xc8355ef0e0, 0x144fe0d3d3440c14, 0x20, 0x700000007, 0x2, 0x8e2, 0x0, 0xc83f49f5c0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:848 +0x500 fp=0xc826756bc0 sp=0xc826756a10
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc820244000, 0x7f36bcb2b068, 0xc8355ef0e0, 0x144fe0d3d3440c14, 0x20, 0x700000007, 0x2, 0x8e2, 0x0, 0xc83f49f5c0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:1792 +0xd12 fp=0xc826757228 sp=0xc826756bc0
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc820392440, 0x7f36bcb2b068, 0xc8355eede0, 0x0, 0x0, 0x700000007, 0x2, 0x8e2, 0x0, 0xc83f49f5c0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/stores.go:178 +0x501 fp=0xc8267574d8 sp=0xc826757228
github.com/cockroachdb/cockroach/server.(*Node).Batch.func3()
        /go/src/github.com/cockroachdb/cockroach/server/node.go:791 +0x55b fp=0xc826757708 sp=0xc8267574d8
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc820390540, 0xc826757850, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:166 +0xd9 fp=0xc826757768 sp=0xc826757708
github.com/cockroachdb/cockroach/server.(*Node).Batch(0xc820328000, 0x7f36bcb2b068, 0xc8355eea80, 0xc831c57dc0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/server/node.go:803 +0x327 fp=0xc8267579f0 sp=0xc826757768
github.com/cockroachdb/cockroach/roachpb._Internal_Batch_Handler(0x18c7160, 0xc820328000, 0x7f36bcb2b068, 0xc8355eea80, 0xc82aab0dc0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:1442 +0x168 fp=0xc826757a98 sp=0xc8267579f0
google.golang.org/grpc.(*Server).processUnaryRPC(0xc82008c090, 0x7f36bca9a6b0, 0xc8230f5320, 0xc82c536000, 0xc8203e4120, 0x2433020, 0x0, 0x0, 0x0)
        /go/src/google.golang.org/grpc/server.go:522 +0xe24 fp=0xc826757de0 sp=0xc826757a98
google.golang.org/grpc.(*Server).handleStream(0xc82008c090, 0x7f36bca9a6b0, 0xc8230f5320, 0xc82c536000, 0x0)
        /go/src/google.golang.org/grpc/server.go:682 +0x109d fp=0xc826757f38 sp=0xc826757de0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc8226baeb0, 0xc82008c090, 0x7f36bca9a6b0, 0xc8230f5320, 0xc82c536000)
        /go/src/google.golang.org/grpc/server.go:348 +0xa0 fp=0xc826757f68 sp=0xc826757f38
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc826757f70 sp=0xc826757f68
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/google.golang.org/grpc/server.go:349 +0x9a
```

**Comment by petermattis** [comment]
My guess is we're calling `NextKey` on a RocksDB iterator that was deallocated. But I can't see how that is happening in these code paths. When we close a `rocksDBIterator` we clear its fields so that a subsequent access would panic with a nil-pointer dereference. Before calling into the RocksDB code, `rocksDBIterator.NextKey` checks that we haven't closed the associated engine (a `rocksDBBatch` in this case).

**Comment by petermattis** [comment]
Oh, in this code path (`Replica.addReadOnlyCmd`) the `engine.Engine` is actually a `*RocksDB` and not a `*rocksDBBatch`. That points the finger away from #6684. Still looking.

**Comment by petermattis** [comment]
Has this happened again? I'm at a loss to explain what happened.

**Comment by petermattis** [comment]
Closing as unreproducible.
