### ISSUE TITLE
streamclient: panic in TestSinklessReplicationClient

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#68168]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3234996?expandedTest=build%3A%28id%3A3234990%29%2Cid%3A130957

```
panic: close of closed channel

goroutine 2276 [running]:
github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamclient.(*sinklessReplicationClient).ConsumePartition.func1(0xc0003d6540, 0xc0022c47e0, 0xc00136c9c0, 0xc0028c1200, 0x58448f0, 0xc00218ce00)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamclient/cockroach_sinkless_replication_client.go:128 +0x6f5
created by github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamclient.(*sinklessReplicationClient).ConsumePartition
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamclient/cockroach_sinkless_replication_client.go:88 +0x3f0

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000489680, 0x4468a5f, 0x1d, 0x4a73ca0, 0x4b31a6)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000489500)
	/usr/local/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000489500, 0xc000c7fd60)
	/usr/local/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc0007da060, 0x75cb490, 0x1, 0x1, 0xc03869a2bab3f627, 0x274afbd7e58, 0x7931660, 0xc000978740)
	/usr/local/go/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc000bc7d00, 0x0)
	/usr/local/go/src/testing/testing.go:1417 +0x1eb
github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamclient.TestMain(0xc000bc7d00)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamclient/main_test.go:31 +0xde
main.main()
	_testmain.go:47 +0x165
```

**Comment by knz** [comment]
related to #67592
cc @adityamaru
