### ISSUE TITLE
Unique Key cannot be dropped

### ISSUE THREAD

**Issue by walter-weinmann** [cockroachdb/cockroach#68222]
### DDL Statement: CREATE TABLE

```
CREATE TABLE public.country (
	pk_country_id INT8 NOT NULL,
	country_map BYTES NULL,
	created TIMESTAMP NOT NULL,
	iso3166 STRING NULL,
	modified TIMESTAMP NULL,
	name STRING NOT NULL,
	CONSTRAINT "primary" PRIMARY KEY (pk_country_id ASC),
	UNIQUE INDEX country_name_key (name ASC),
	FAMILY "primary" (pk_country_id, country_map, created, iso3166, modified, name)
);
```

### DDL Statement: DROP INDEX

`DROP INDEX "country_name_key" CASCADE
`
### Error message:

```
2021-07-29 09:52:07,816 [DatabaseSeeder.java] INFO  Start CockroachDB
org.postgresql.util.PSQLException: ERROR: requested table does not have a primary key
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2434)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:307)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.executeSQLStmnts(AbstractJdbcSeeder.java:1310)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.dropTableConstraints(AbstractJdbcSeeder.java:1207)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:415)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:113)
Processing of the script was aborted, error code=1
```

**Comment by ajwerner** [comment]
What version are you using? I just tried this on both master and 20.2 and it works just fine.

```
root@localhost:26257/defaultdb> CREATE TABLE public.country (
pk_country_id INT8 NOT NULL,
country_map BYTES NULL,
created TIMESTAMP NOT NULL,
iso3166 STRING NULL,
modified TIMESTAMP NULL,
name STRING NOT NULL,
CONSTRAINT "primary" PRIMARY KEY (pk_country_id ASC),
UNIQUE INDEX country_name_key (name ASC),
FAMILY "primary" (pk_country_id, country_map, created, iso3166, modified, name)
);
CREATE TABLE


Time: 112ms total (execution 112ms / network 0ms)

root@localhost:26257/defaultdb> DROP INDEX "country_name_key" CASCADE;
NOTICE: the data for dropped indexes is reclaimed asynchronously
HINT: The reclamation delay can be customized in the zone configuration for the table.
DROP INDEX


Time: 664ms total (execution 664ms / network 0ms)
```

Also, it works in a transaction:
```
root@localhost:26257/defaultdb> BEGIN ; CREATE TABLE public.country (
pk_country_id INT8 NOT NULL,
country_map BYTES NULL,
created TIMESTAMP NOT NULL,
iso3166 STRING NULL,
modified TIMESTAMP NULL,
name STRING NOT NULL,
CONSTRAINT "primary" PRIMARY KEY (pk_country_id ASC),
UNIQUE INDEX country_name_key (name ASC),
FAMILY "primary" (pk_country_id, country_map, created, iso3166, modified, name)
);
CREATE TABLE

Note: timings for multiple statements on a single line are not supported. See https://go.crdb.dev/issue-v/48180/v21.2.

root@localhost:26257/defaultdb  OPEN> DROP INDEX "country_name_key" CASCADE;
NOTICE: the data for dropped indexes is reclaimed asynchronously
HINT: The reclamation delay can be customized in the zone configuration for the table.
DROP INDEX


Time: 3ms total (execution 3ms / network 0ms)

root@localhost:26257/defaultdb  OPEN> COMMIT;
COMMIT


Time: 38ms total (execution 38ms / network 0ms)
```

**Comment by walter-weinmann** [comment]
I work with JDBC and the DatabaseMetaData class.  The error message `requested table does not have a primary key` is very strange. 

I try to execute INSERTs into the database and for performance reasons I drop all constraints before - in the order FK, UK and then PK - and after the INSERTs I add the constraints again, but in reverse order: PK, UK, and FK.

**Comment by ajwerner** [comment]
Oh, in cockroach you cannot use a table which does not have a primary constraint.

**Comment by ajwerner** [comment]
We only added the syntax to drop it to support migrations which change the primary key. Also, you approach does not help you at all in cockroach and instead hurts quite badly. In cockroach, schema changes are async and online and performed after the transaction commits.

**Comment by walter-weinmann** [comment]
Ok thanks - this was very helpful.
