### ISSUE TITLE
sql: enum value usage in check constraints is not tracked

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#68361]
**Describe the problem**

When dropping enum values, we now check all expressions in all referencing tables except check constraints. Unfortunately we also need to detect when such expressions use types and rewrite/track them with references. 

**To Reproduce**

```
demo@127.0.0.1:52964/movr> CREATE TYPE typ AS ENUM ('a', 'b');
CREATE TYPE
demo@127.0.0.1:52964/movr> CREATE TABLE t (k STRING CHECK (k::typ = 'a'));
CREATE TABLE
demo@127.0.0.1:52964/movr> SET enable_drop_enum_value = true ;
SET
demo@127.0.0.1:52964/movr> ALTER TYPE typ DROP VALUE 'a';
ALTER TYPE
demo@127.0.0.1:52964/movr> INSERT INTO t VALUES ('a');
ERROR: could not find [64] in enum "public.typ" representation PhysicalReps: [[128]]; LogicalReps: [b] goroutine 6392 [running]:
runtime/debug.Stack(0x8b2f483, 0x21, 0xc00077d1f8)
	/usr/local/Cellar/go/1.16.5/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical(0xc0025cc900, 0xc002eeb4d8, 0x1, 0x8, 0x8aba585, 0x0, 0xc6f6fc0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/types/types.go:2412 +0x27e
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep(0xc0025cc900, 0xc002eeb4d8, 0x1, 0x8, 0xc002eeb4d8, 0x8, 0xc002eeb4d8, 0xc00077d368, 0x405a285, 0xc002eeb4d8, ...)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:4061 +0x4d
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.MakeDEnumFromPhysicalRepresentation(0xc0025cc900, 0xc002eeb4d8, 0x1, 0x8, 0x1, 0x8, 0x40fe4a5)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:4078 +0x76
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*StrVal).ResolveAsType(0xc003204640, 0xa104df8, 0xc002006390, 0xc0006d46c8, 0xc0025cc900, 0x4102af1, 0xc00491d45f, 0x8b3eb50, 0x7)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/constant.go:554 +0x23f
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeCheckConstant(0xa104df8, 0xc002006390, 0xc0006d46c8, 0xa13db18, 0xc003204640, 0xc0025cc900, 0x30, 0xc00077d500, 0x40930fc, 0xc6749e0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/constant.go:74 +0x313
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*StrVal).TypeCheck(0xc003204640, 0xa104df8, 0xc002006390, 0xc0006d46c8, 0xc0025cc900, 0xc00077d580, 0x40faf0b, 0xc00179bad0, 0xc00491d440)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1431 +0x66
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeCheckAndRequire(0xa104df8, 0xc002006390, 0xc0006d46c8, 0xa104b58, 0xc003204640, 0xc0025cc900, 0xc002c84a20, 0x26, 0x0, 0xc0001b0fc0, ...)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1786 +0x7d
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*AnnotateTypeExpr).TypeCheck(0xc0031fdad0, 0xa104df8, 0xc002006390, 0xc0006d46c8, 0xc6a3be0, 0x3b, 0xc00077d7b0, 0xc0020b0180, 0x1)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:578 +0x1af
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeCheckOverloadedExprs(0xa104df8, 0xc002006390, 0xc0006d46c8, 0xc6a3a60, 0xc0002ed900, 0x3b, 0x50, 0xa053901, 0xc003994200, 0x2, ...)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/overload.go:566 +0x8e4
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeCheckComparisonOp(0xa104df8, 0xc002006390, 0xc0006d46c8, 0x0, 0xc003204600, 0xa104030, 0xc0031fdb30, 0xa103f18, 0xc0031fdad0, 0xc003204640, ...)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:2058 +0x2d6
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr).TypeCheck(0xc0029c0370, 0xa104df8, 0xc002006390, 0xc0006d46c8, 0xc6a4ea0, 0xc00077de08, 0x53ca48f, 0x887a500, 0xc0029c0370)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:755 +0x4b5
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheck(0xa104df8, 0xc002006390, 0xa104180, 0xc0029c0370, 0xc0006d46c8, 0xc6a4ea0, 0xc0029c0370, 0xc00077de68, 0x53ce7e2, 0xc000e041e0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:253 +0x104
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheckAndRequire(0xa104df8, 0xc002006390, 0xa104180, 0xc0029c0370, 0xc0006d46c8, 0xc6a4ea0, 0x0, 0x0, 0x1, 0x1, ...)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:263 +0x85
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).resolveAndRequireType(0xc000e041e0, 0xa104180, 0xc0029c0320, 0xc6a4ea0, 0xc0029c0320, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:457 +0x115
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).addCheckConstraintCols(0xc000f9a800, 0xa104700)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder.go:867 +0x2dc
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).buildInsert(0xc000f9a800, 0x0, 0x0, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:656 +0x45
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildInsert(0xc001ab2460, 0xc000c649b0, 0xc000e04000, 0x3711bde0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:285 +0x892
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt.func2(0xc000e04000, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:287 +0x3d
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).processWiths(0xc001ab2460, 0x0, 0xc000e04000, 0xc00077e3c8, 0x400)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:111 +0x9b
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc001ab2460, 0xa111238, 0xc000c649b0, 0x0, 0x0, 0x0, 0xc000e04000, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:286 +0xb52
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot(0xc001ab2460, 0xa111238, 0xc000c649b0, 0x0, 0x0, 0x0, 0xd8)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:235 +0x11d
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc001ab2460, 0x0, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:209 +0x239
github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo(0xc0006d4cf0, 0xa104df8, 0xc002006390, 0xc00077e718, 0x5369a4a, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:521 +0x4cb
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc0006d4590, 0xa104df8, 0xc002006390, 0x33c63df000000000, 0x6108d327)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:194 +0xde
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan(0xc0006d4000, 0xa104df8, 0xc002006390, 0xc0006d4590, 0x0, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:999 +0x5a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0006d4000, 0xa104df8, 0xc002006390, 0xc0006d4590, 0x3718d238, 0xc0041f4698, 0x0, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:878 +0x1a7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0006d4000, 0xa104df8, 0xc002006390, 0xa111238, 0xc000c649b0, 0xc00209c532, 0x1a, 0x0, 0x1, 0x0, ...)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:690 +0x1046
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0006d4000, 0xa0e9c68, 0xc0032d0e40, 0xa111238, 0xc000c649b0, 0xc00209c532, 0x1a, 0x0, 0x1, 0x0, ...)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:126 +0xb8f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0xa111238, 0xc000c649b0, 0xc00209c532, 0x1a, 0x0, 0x1, 0x33c3b198, 0xed89aca27, 0x0, 0x33c3b968, ...)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1626 +0x233
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc0006d4000, 0xa0e9c68, 0xc0032d0e40, 0x0, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1628 +0x1691
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0006d4000, 0xa0e9c68, 0xc0010acf80, 0xc001a710e0, 0x5400, 0x15000, 0xc001a712c0, 0xc001d90610, 0x0, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1550 +0x225
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc001a83700, 0xa0e9c68, 0xc0010acf80, 0xc0006d4000, 0x5400, 0x15000, 0xc001a712c0, 0xc001d90610, 0x0, 0x0)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:627 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc0018afa4f, 0xc0018348e8, 0xa0e9c68, 0xc0010acf80, 0xc001d90610, 0xc001a83700, 0xc0041f4000, 0xa14e100, 0xc0023d8b00, 0xc00331a3c0, ...)
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:645 +0x3f5
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/Users/ajwerner/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:573 +0x185
```

**Expected behavior**
The value drop should fail.

Epic CRDB-2451

**Comment by ajwerner** [comment]
I'd do this in two phases:

1) Check the check constraints on the descriptors which actually reference the type (this is not captured in the above repro but feels much more likely).
2) Rewrite these check constraints and do proper forward and backward references to the type like we do for computed and default expressions.
