### ISSUE TITLE
changefeeds fail to restart/exit when encountering some schema changes

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#68791]
**Describe the problem**

Certain schema changes should result in a changefeed restart:

- `ALTER TABLE .. SET LOCALITY REGIONAL BY ROW`
- `ALTER TABLE .. ALTER PRIMARY KEY ...`

The restart is required to ensure that we start new rangefeeds on the new index that that these schema changes create.

Further when the user specifies `schema_change_policy=stop` schema changes such as `ALTER TABLE ... ADD COLUMN .. DEFUALT ..` should result in the changefeed permanently exiting.

However, we've observed some cases where the changefeed fails to exit or restart correctly.  In these cases, the changefeed appears to still be running, but no newly inserted rows or resolved timestamps will be sent to the sink.

Internally in nn such cases, what we've found so far is that the `kvFeed` encounters the schema change, forwards Resolved spans with the appropriate schema change boundary type set to the `changeAggregator` and attempts to exit. Further the `changeAggregator` correctly forwards the schema change boundary to the `changeFrontier`. The changeFrontier advances to the boundary and attempts to exit.  However, it appears that at this point we can become deadlocked (the exact cause of the deadlock is not known).

For example, below are some of the relevant Goroutines from a 3-node cluster where this occurred.  Nodes 1 and 2 are the nodes involved in the changefeed, with the changeAggregator running on Node 2 and the changeFrontier on Node 1.

<details><summary>Some Node 1 Goroutines</summary>

```
goroutine 17754 [chan receive, 7 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Start.func1(0x66a3068, 0xc003f06300, 0xc0033aea80)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1134 +0x48
created by github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Start
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1133 +0x43b

goroutine 17752 [select, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaSink).workerLoop(0xc0044c23c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_kafka.go:338 +0x155
created by github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaSink).start
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_kafka.go:164 +0x8b

goroutine 17682 [chan receive, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*RowChannel).Next(0xc003ed01e0, 0xc003747490, 0x1, 0x1, 0x4e1a45)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:508 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).DrainHelper(0xc0033aea80, 0xc002c2a5d8)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:571 +0xac
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Next(0xc0033aea80, 0x34d10769, 0xc000bd0000, 0xc0044c23c0, 0xc000ba9380)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1234 +0x4d6
github.com/cockroachdb/cockroach/pkg/sql/execinfra.DrainAndForwardMetadata(0x66a3068, 0xc003f06300, 0x66c3458, 0xc0033aea80, 0x665abc8, 0xc00350c000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:228 +0x63
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run(0x66a3068, 0xc003f06300, 0x66c3458, 0xc0033aea80, 0x665abc8, 0xc00350c000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:193 +0x105
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run(0xc0033aea80, 0x66a3068, 0xc003f06300)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:731 +0x90
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc00350a420, 0x66a3068, 0xc003f06300, 0x56ee700)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:418 +0x2c4
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc001e99590, 0xc001dff5e0, 0x0, 0xc0049d91e8, 0xc003eadc00, 0xc004222e00, 0xc0049d9088, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:525 +0x4d7
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeeddist.StartDistChangefeed(0x66a3110, 0xc0014b4090, 0x6703180, 0xc001986468, 0x97cb833750b0001, 0xc004032ff0, 0xc002e9fa20, 0x1a, 0xc004032fc0, 0x169a4a37f1ed281a, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeeddist/distflow.go:144 +0xac6
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.distChangefeedFlow(0x66a3110, 0xc0014b4090, 0x6703180, 0xc001986468, 0x97cb833750b0001, 0xc004032ff0, 0xc002e9fa20, 0x1a, 0xc004032fc0, 0x169a4a37f1ed281a, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_dist.go:117 +0x387
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changefeedResumer).resumeWithRetries(0xc002bd8490, 0x66a3110, 0xc0014b4090, 0x6703180, 0xc001986468, 0x97cb833750b0001, 0xc004032ff0, 0xc002e9fa20, 0x1a, 0xc004032fc0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:681 +0x215
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changefeedResumer).Resume(0xc002bd8490, 0x66a3110, 0xc0014b4090, 0x4cabf00, 0xc001986468, 0x48ef3a0, 0x8fda5e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:614 +0x247
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1(0xc0017c0d40, 0x66598e0, 0xc002bd8490, 0x66a3110, 0xc0014b4090, 0x4cabf00, 0xc001986468, 0xc0014359f0)
        /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1173 +0xae
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine(0xc00023d1e0, 0x66a3110, 0xc0014b4000, 0x4cabf00, 0xc001986468, 0x66598e0, 0xc002bd8490, 0xc003026000, 0x502c329, 0x7, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1174 +0x87c
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob(0xc00023d1e0, 0x66a3068, 0xc004237280, 0x66598e0, 0xc002bd8490, 0xc003026000, 0x502c329, 0x7, 0xc003b1afc0, 0x16, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:322 +0x46c
github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2(0x66beb60, 0xc0028e9650)
        /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:874 +0xf6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2(0xc000ccc800, 0x66beb60, 0xc0028e9650, 0xc0028e94a0, 0x0, 0xc00266d3b0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:442 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:434 +0x22b
```

</details>

<details>
<summary>Some Node 2 Goroutines</summary>

```
goroutine 17061 [chan receive, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed.Run(0x66a3068, 0xc0036b92c0, 0xc000872000, 0xc00176f380, 0xc00174a348, 0xc00174a348, 0x0, 0xc000c68d70, 0x4fff280, 0xc000ac4000, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed/kv_feed.go:112 +0x7b6
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).startKVFeed.func1(0x66a3068, 0xc0036b92c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:288 +0xfe
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2(0xc00176e880, 0x66a3068, 0xc0036b92c0, 0xc000b66e00, 0x0, 0xc002cd8f60)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:442 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:434 +0x22b


goroutine 16960 [select, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent.(*chanBuffer).Get(0xc000ed0750, 0x66a3068, 0xc0036b92c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent/chan_buffer.go:50 +0xe7
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent.(*throttlingBuffer).Get(0xc002cd8f30, 0x66a3068, 0xc0036b92c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent/throttling_buffer.go:30 +0xa6
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*bufEventProducer).GetEvent(0xc002cd6240, 0x66a3068, 0xc0036b92c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:585 +0xa6
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).tick(0xc0040b2300, 0x0, 0xc004c7def0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:466 +0x85
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).Next(0xc0040b2300, 0xc002b9e0c0, 0x4, 0x4, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:445 +0x85
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run(0x66a3068, 0xc0036b92c0, 0x66c3418, 0xc0040b2300, 0x665abc8, 0xc002fda380)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:186 +0x35
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run(0xc0040b2300, 0x66a3068, 0xc0036b8ac0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:731 +0x90
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).StartInternal.func1(0xc001419520, 0x1, 0x1, 0x66a3068, 0xc0036b8ac0, 0xc0031ca9a0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:371 +0x5c
created by github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).StartInternal
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370 +0x2e8


goroutine 17060 [select, 7 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaSink).workerLoop(0xc003083140)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_kafka.go:338 +0x155
created by github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaSink).start
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_kafka.go:164 +0x8b
```

</details>

It appears to me that:

- the `changeFrontier` has entered a draining state and is waiting for its inputs to drain:

```
goroutine 17682 [chan receive, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*RowChannel).Next(0xc003ed01e0, 0xc003747490, 0x1, 0x1, 0x4e1a45)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:508 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).DrainHelper(0xc0033aea80, 0xc002c2a5d8)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:571 +0xac
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Next(0xc0033aea80, 0x34d10769, 0xc000bd0000, 0xc0044c23c0, 0xc000ba9380)
```

https://github.com/cockroachdb/cockroach/blob/4c4135e7f4edc7142051ada818aeaad0e2bed710/pkg/sql/execinfra/processorsbase.go#L567-L571

- The kvFeed is waiting for a context to cancel before it finishes exiting:

```
goroutine 17061 [chan receive, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed.Run(0x66a3068, 0xc0036b92c0, 0xc000872000, 0xc00176f380, 0xc00174a348, 0xc00174a348, 0x0, 0xc000c68d70, 0x4fff280, 0xc000ac4000, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed/kv_feed.go:112 +0x7b6
```

https://github.com/cockroachdb/cockroach/blob/e723a85739a2e1b514f5de3221a2177a3a37d0e6/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L106-L115

- The changeAggregator is waiting for an event from its channel buffer (which the kvFeed is the writer for so it is likely to be blocked until ca.Ctx is cancelled:

https://github.com/cockroachdb/cockroach/blob/4c4135e7f4edc7142051ada818aeaad0e2bed710/pkg/ccl/changefeedccl/changefeed_processors.go#L466-L469

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster with non-trivial latency between the nodes. For example, a node in us-east1, us-west1, and europe-west2.  In the following, all commands are run from the us-east1 node.

2. Setup a kafka sink (or any other sink where you can easily observe the changefeed output).

3. Setup table and changefeed

```sql
CREATE DATABASE test;
\c test
ALTER DATABASE test PRIMARY REGION "us-west1";
ALTER DATABASE test ADD region "us-east1";
ALTER DATABASE test ADD region "europe-west2";

CREATE TABLE tab1 (pk INT PRIMARY KEY, a INT UNIQUE NOT NULL, b INT);
INSERT INTO tab1 VALUES(1, 11, 3);
INSERT INTO tab1 VALUES(2, 22, 3);
INSERT INTO tab1 VALUES(3, 33, 4);
CREATE CHANGEFEED FOR TABLE tab1 INTO 'kafka://10.142.15.195:9092' WITH updated, resolved, confluent_schema_registry = 'http://10.142.15.195:8081', format = 'experimental_avro';
```

4. You should observe the 3 rows being send to the sink followed by resolved timestamps.
5. Do the schema change:

```
ALTER TABLE tab1 ALTER PRIMARY KEY USING COLUMNS(a);
```

6. If you trigger the issue, you will observe resolved timestamps right up to the timestamp of the schema change.  The changefeed job will still show as "running" in the jobs table.  But further writes will not be sent to the sink.

**Expected behavior**

The changefeedFrontier, changefeedAggregator, and kvFeed should completely exit and either restart or report as a failed job depending on the situation.

**Comment by stevendanna** [comment]
Follow up:

This only seem to reproduce for me when the the `changeAggregator` and `changeFrontier` live on different nodes.  To help ensure this, I make sure that the leaseholder for the range for the table is on node 2, and then I start the changefeed from node 1.
