### ISSUE TITLE
range frequently unavailable for multiregion placement logic tests

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#69233]
See https://teamcity.cockroachdb.com/viewLog.html?buildId=3339223&buildTypeId=Cockroach_UnitTests_BazelUnitTests&tab=artifacts#%2Fbazel-testlogs%2Fpkg%2Fccl%2Fmultiregionccl;%2Fbazel-testlogs%2Fpkg%2Fccl%2Flogictestccl as an example.

Tests usually fail with:
```

    testcluster.go:1217: condition failed to evaluate within 45s: failed to create a status client: initial connection heartbeat failed: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
        goroutine 200202 [running]:
        runtime/debug.Stack(0xc073d53118, 0x68bba60, 0xc07c9ba330)
        	GOROOT/src/runtime/debug/stack.go:24 +0x9f
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x697e158, 0xc00572b200, 0xc073d53118)
        	github.com/cockroachdb/cockroach/pkg/testutils/soon.go:35 +0x70
        github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForNodeStatuses(0xc01c5b6500, 0x6a987f0, 0xc00572b200)
        	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1217 +0x94
        github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start(0xc01c5b6500, 0x6a987f0, 0xc00572b200)
        	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:355 +0x645
        github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartNewTestCluster(0x6a987f0, 0xc00572b200, 0x9, 0x68b5a80, 0xc003f7c600, 0x0, 0x0, 0x0, 0x0, 0x68b6780, ...)
        	github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_cluster_shim.go:218 +0xfe
        github.com/cockroachdb/cockroach/pkg/sql/logictest.(*logicTest).newCluster(0xc003f7c400, 0xc000000, 0x0, 0x0)
        	github.com/cockroachdb/cockroach/pkg/sql/logictest/logic.go:1438 +0xa38
        github.com/cockroachdb/cockroach/pkg/sql/logictest.(*logicTest).setup(0xc003f7c400, 0x52fb076, 0x1e, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x528d69a, ...)
        	github.com/cockroachdb/cockroach/pkg/sql/logictest/logic.go:1625 +0x119
        github.com/cockroachdb/cockroach/pkg/sql/logictest.RunLogicTestWithDefaultConfig.func1.1(0xc00572b200)
        	github.com/cockroachdb/cockroach/pkg/sql/logictest/logic.go:3312 +0x26f
        testing.tRunner(0xc00572b200, 0xc008c90440)
        	GOROOT/src/testing/testing.go:1193 +0xef
        created by testing.(*T).Run
        	GOROOT/src/testing/testing.go:1238 +0x2b3
        --- FAIL: TestCCLLogic/multiregion-9node-3region-3azs/placement (206.41s)
```

The logs end up with something like this:
```
=== RUN   TestCCLLogic/multiregion-9node-3region-3azs/placement
=== PAUSE TestCCLLogic/multiregion-9node-3region-3azs/placement
=== RUN   TestCCLLogic/multiregion-9node-3region-3azs/regional_by_row
=== PAUSE TestCCLLogic/multiregion-9node-3region-3azs/regional_by_row
=== RUN   TestCCLLogic/multiregion-9node-3region-3azs/regional_by_row_placement_restricted
=== PAUSE TestCCLLogic/multiregion-9node-3region-3azs/regional_by_row_placement_restricted
=== RUN   TestCCLLogic/multiregion-9node-3region-3azs/regional_by_row_rename_column
=== PAUSE TestCCLLogic/multiregion-9node-3region-3azs/regional_by_row_rename_column
=== RUN   TestCCLLogic/multiregion-9node-3region-3azs/regional_by_table_placement_restricted
=== PAUSE TestCCLLogic/multiregion-9node-3region-3azs/regional_by_table_placement_restricted
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/alter_table_locality
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/multi_region_show
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/multi_region_default_primary_region
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/regional_by_table_placement_restricted
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/multi_region_privileges
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/regional_by_row_rename_column
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/regional_by_row_placement_restricted
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/multi_region
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/global_placement_restricted
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/multi_region_import_export
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/multi_region_drop_region
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/regional_by_row
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/multi_region_backup
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/placement
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/multi_region_zone_configs
=== CONT  TestCCLLogic/multiregion-9node-3region-3azs/multi_region_tpcc
E210823 06:12:12.247337 318080 kv/kvserver/replica_range_lease.go:365  [n1,s1,r35/1:/Table/{39-40}] 38  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:12:12.686027 318286 kv/kvserver/replica_range_lease.go:365  [n1,s1,r4/1:/System{/tsd-tse}] 39  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:12:12.906670 318897 kv/kvserver/replica_range_lease.go:365  [n1,s1,r31/1:/Table/3{5-6}] 40  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:12:13.197194 318127 kv/kvserver/replica_range_lease.go:365  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 41  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:12:13.936596 319939 kv/kvserver/replica_range_lease.go:365  [n1,s1,r11/1:/Table/1{5-6}] 42  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:12:14.082247 319940 kv/kvserver/replica_range_lease.go:365  [n1,s1,r8/1:/Table/1{2-3}] 43  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:12:14.137238 319941 kv/kvserver/replica_range_lease.go:365  [n1,s1,r27/1:/{NamespaceTabâ€¦-Table/32}] 44  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:12:14.325386 319942 kv/kvserver/replica_range_lease.go:365  [n1,s1,r7/1:/Table/1{1-2}] 45  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:12:22.142189 336772 kv/kvserver/replica_range_lease.go:365  [n1,s1,r35/1:/Table/{39-40}] 46  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:12:22.143364 337310 kv/kvserver/replica_range_lease.go:365  [n1,s1,r4/1:/System{/tsd-tse}] 47  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:13:06.326561 559181 kv/kvserver/replica_range_lease.go:365  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 48  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:13:06.336112 559862 kv/kvserver/replica_range_lease.go:365  [n1,s1,r35/1:/Table/{39-40}] 49  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210823 06:13:06.660278 551400 kv/kvclient/kvcoord/txn_interceptor_committer.go:479  [-] 50  making txn commit explicit failed for "unnamed" meta={id=4af93c9b pri=100.00000000 epo=0 ts=1629699176.726988900,0 min=1629699176.726988900,0 seq=2} lock=true stat=STAGING rts=1629699176.726988900,0 wto=false gul=1629699177.226988900,0 ifw=1: result is ambiguous (error=rpc error: code = Unavailable desc = error reading from server: EOF [exhausted])
E210823 06:13:08.451244 585343 kv/kvclient/kvcoord/txn_interceptor_committer.go:479  [-] 51  making txn commit explicit failed for "unnamed" meta={id=d2691ec8 pri=0.02119127 epo=0 ts=1629699176.533832403,2 min=1629699174.403291420,0 seq=6} lock=true stat=STAGING rts=1629699176.533832403,2 wto=false gul=1629699174.903291420,0 ifw=5: result is ambiguous (error=rpc error: code = Canceled desc = grpc: the client connection is closing [exhausted])
E210823 06:13:17.855558 602499 kv/kvserver/replica_range_lease.go:365  [n1,s1,r6/1:/Table/{SystemConâ€¦-11}] 52  failed to heartbeat own liveness record: context canceled
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53  range unavailable: have been waiting 15.11s for proposing command ConditionalPut [/System/StatusNode/5,/Min).
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +This range is likely unavailable.
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +Please submit this message to Cockroach Labs support along with the following information:
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +Descriptor:  r3:/System/{NodeLivenessMax-tsd} [(n1,s1):1, next=2, gen=0]
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +Live:        
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +Non-live:    (n1,s1):1
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +Raft Status: {"id":"1","term":6,"vote":"1","commit":187,"lead":"1","raftState":"StateLeader","applied":187,"progress":{"1":{"match":187,"next":188,"state":"StateReplicate"}},"leadtransferee":"0"}
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +and a copy of https://yourhost:8080/#/reports/range/3
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +If you are using CockroachDB Enterprise, reach out through your
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +support contract. Otherwise, please open an issue at:
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +
E210823 06:13:40.679479 648796 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 53 +  https://github.com/cockroachdb/cockroach/issues/new/choose
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54  range unavailable: have been waiting 15.18s for proposing command Put [/Table/39/1/"\x88\rf\xc9\x1bQJÜ˜\xe85E\xe0\u007f:\xa8"/0,/Min).
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +This range is likely unavailable.
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +Please submit this message to Cockroach Labs support along with the following information:
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +Descriptor:  r35:/Table/{39-40} [(n1,s1):1, next=2, gen=0]
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +Live:        
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +Non-live:    (n1,s1):1
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +Raft Status: {"id":"1","term":6,"vote":"1","commit":143,"lead":"1","raftState":"StateLeader","applied":142,"progress":{"1":{"match":143,"next":144,"state":"StateReplicate"}},"leadtransferee":"0"}
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +and a copy of https://yourhost:8080/#/reports/range/35
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +If you are using CockroachDB Enterprise, reach out through your
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +support contract. Otherwise, please open an issue at:
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +
E210823 06:13:40.845932 651480 kv/kvserver/replica_write.go:290  [n1,s1,r35/1:/Table/{39-40}] 54 +  https://github.com/cockroachdb/cockroach/issues/new/choose
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55  range unavailable: have been waiting 16.38s for proposing command RequestLease [/System/NodeLiveness,/Min).
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +This range is likely unavailable.
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +Please submit this message to Cockroach Labs support along with the following information:
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +Descriptor:  r2:/System/NodeLiveness{-Max} [(n1,s1):1, next=2, gen=0]
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +Live:        
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +Non-live:    (n1,s1):1
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +Raft Status: {"id":"1","term":6,"vote":"1","commit":252,"lead":"1","raftState":"StateLeader","applied":252,"progress":{"1":{"match":252,"next":253,"state":"StateReplicate"}},"leadtransferee":"0"}
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +and a copy of https://yourhost:8080/#/reports/range/2
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +If you are using CockroachDB Enterprise, reach out through your
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +support contract. Otherwise, please open an issue at:
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +
E210823 06:13:43.501805 654252 kv/kvserver/replica_write.go:290  [n1,s1,r2/1:/System/NodeLiveness{-Max}] 55 +  https://github.com/cockroachdb/cockroach/issues/new/choose
E210823 06:13:43.815302 726893 kv/kvserver/replica_range_lease.go:365  [n1,s1,r16/1:/Table/2{0-1}] 56  failed to heartbeat own liveness record: context canceled
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57  range unavailable: have been waiting 15.10s for proposing command ConditionalPut [/System/StatusNode/3,/Min).
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +This range is likely unavailable.
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +Please submit this message to Cockroach Labs support along with the following information:
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +Descriptor:  r3:/System/{NodeLivenessMax-tsd} [(n1,s1):1, next=2, gen=0]
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +Live:        
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +Non-live:    (n1,s1):1
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +Raft Status: {"id":"1","term":6,"vote":"1","commit":190,"lead":"1","raftState":"StateLeader","applied":187,"progress":{"1":{"match":190,"next":191,"state":"StateReplicate"}},"leadtransferee":"0"}
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +and a copy of https://yourhost:8080/#/reports/range/3
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +If you are using CockroachDB Enterprise, reach out through your
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +support contract. Otherwise, please open an issue at:
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +
E210823 06:13:41.516641 652946 kv/kvserver/replica_write.go:290  [n1,s1,r3/1:/System/{NodeLiveâ€¦-tsd}] 57 +  https://github.com/cockroachdb/cockroach/issues/new/choose
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58  range unavailable: have been waiting 15.00s for proposing command Merge [/System/tsd/cr.node.rpc.heartbeats.loops.started/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.rpc.heartbeats.loops.exited/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.rpc.heartbeats.initializing/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.rpc.heartbeats.nominal/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.rpc.heartbeats.failed/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.ca/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.client-ca/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.ui-ca/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.node/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.node-client/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.ui/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.ca-client-tenant/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.client-tenant/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.connections.incoming/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.connections.refused/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.bytes.received/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.bytes.sent/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.infos.received/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.infos.sent/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.connections.outgoing/3/10s/2021-08-23T06:00:00Z,/Min),... 1105 skipped ..., Merge [/System/tsd/cr.store.txnrecovery.successes.aborted/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.store.txnrecovery.successes.pending/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.store.txnrecovery.failures/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.store.rebalancing.lease.transfers/3/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.store.rebalancing.range.rebalances/3/10s/2021-08-23T06:00:00Z,/Min).
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +This range is likely unavailable.
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +Please submit this message to Cockroach Labs support along with the following information:
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +Descriptor:  r4:/System{/tsd-tse} [(n1,s1):1, next=2, gen=0]
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +Live:        
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +Non-live:    (n1,s1):1
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +Raft Status: {"id":"1","term":6,"vote":"1","commit":161,"lead":"1","raftState":"StateLeader","applied":160,"progress":{"1":{"match":161,"next":162,"state":"StateReplicate"}},"leadtransferee":"0"}
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +and a copy of https://yourhost:8080/#/reports/range/4
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +If you are using CockroachDB Enterprise, reach out through your
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +support contract. Otherwise, please open an issue at:
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +
E210823 06:13:41.539247 651482 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 58 +  https://github.com/cockroachdb/cockroach/issues/new/choose
E210823 06:13:44.641882 720221 kv/kvserver/replica_range_lease.go:365  [n1,s1,r6/1:/Table/{SystemConâ€¦-11}] 59  failed to heartbeat own liveness record: context canceled
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60  range unavailable: have been waiting 15.54s for proposing command EndTxn(commit:true) [/Table/12/1/2021-08-23T06:13:09.312468Z/"ÕŸ\xb3\nÍJ\xaf\x9fCÆ¤9\x97Ñ¦"/0], [txn: 771f09f3], [can-forward-ts].
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +This range is likely unavailable.
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +Please submit this message to Cockroach Labs support along with the following information:
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +Descriptor:  r8:/Table/1{2-3} [(n1,s1):1, next=2, gen=0]
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +Live:        (n1,s1):1
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +Non-live:    
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +Raft Status: {"id":"1","term":6,"vote":"1","commit":73,"lead":"1","raftState":"StateLeader","applied":72,"progress":{"1":{"match":73,"next":74,"state":"StateReplicate"}},"leadtransferee":"0"}
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +and a copy of https://yourhost:8080/#/reports/range/8
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +If you are using CockroachDB Enterprise, reach out through your
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +support contract. Otherwise, please open an issue at:
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +
E210823 06:13:41.826681 650543 kv/kvserver/replica_write.go:290  [n1,s1,r8/1:/Table/1{2-3}] 60 +  https://github.com/cockroachdb/cockroach/issues/new/choose
E210823 06:13:41.902650 648797 kv/kvserver/replica_write.go:290  [n1,s1,r4/1:/System{/tsd-tse}] 61  range unavailable: have been waiting 15.10s for proposing command Merge [/System/tsd/cr.node.rpc.heartbeats.loops.started/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.rpc.heartbeats.loops.exited/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.rpc.heartbeats.initializing/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.rpc.heartbeats.nominal/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.rpc.heartbeats.failed/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.ca/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.client-ca/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.ui-ca/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.node/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.node-client/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.ui/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.ca-client-tenant/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.security.certificate.expiration.client-tenant/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.connections.incoming/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.connections.refused/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.bytes.received/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.bytes.sent/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.infos.received/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.infos.sent/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.connections.outgoing/5/10s/2021-08-23T06:00:00Z,/Min),... 1105 skipped ..., Merge [/System/tsd/cr.store.txnrecovery.successes.aborted/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.store.txnrecovery.successes.pending/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.store.txnrecovery.failures/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.store.rebalancing.lease.transfers/5/10s/2021-08-23T06:00:00Z,/Min), Merge [/System/tsd/cr.store.rebalancing.range.rebalances/5/10s/2021-08-23T06:00:00Z,/Min).
```

**Comment by otan** [comment]
cc @pawalt in case you'd know why 15s reads may be needed.
