### ISSUE TITLE
roachtest: run asyncpg test suite in nightlies

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#70209]
I ran the `asyncpg` test suite locally with the following commands:

```
git clone --recurse-submodules git@github.com:MagicStack/asyncpg.git
cd asyncpg
pip install -e .
# modified asyncpg/connect_utils.py to point at CRDB
python setup.py test
```

It passed except for two tests that check the Postgres port
```
======================================================================
FAIL: test_connect_params (test_connect.TestConnectParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rafiss/scratch/asyncpg/tests/test_connect.py", line 792, in test_connect_params
    self.run_testcase(testcase)
  File "/Users/rafiss/scratch/asyncpg/tests/test_connect.py", line 748, in run_testcase
    self.assertEqual(expected, result, 'Testcase: {}'.format(testcase))
AssertionError: Tuples differ: ([('host1', 5432), ('host2', 5432)], {'database': 'db', 'user': 'user'}) != ([('host1', 26257), ('host2', 26257)], {'user': 'user', 'database': 'db'})

First differing element 0:
[('host1', 5432), ('host2', 5432)]
[('host1', 26257), ('host2', 26257)]

- ([('host1', 5432), ('host2', 5432)], {'database': 'db', 'user': 'user'})
?              ^^^              ^^^

+ ([('host1', 26257), ('host2', 26257)], {'database': 'db', 'user': 'user'})
?             +++ ^             +++ ^
 : Testcase: {'name': 'dsn_only_multi_host', 'dsn': 'postgresql://user@host1,host2/db', 'result': ([('host1', 5432), ('host2', 5432)], {'database': 'db', 'user': 'user'})}

======================================================================
FAIL: test_connect_pgpass_regular (test_connect.TestConnectParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rafiss/scratch/asyncpg/tests/test_connect.py", line 845, in test_connect_pgpass_regular
    self.run_testcase({
  File "/Users/rafiss/scratch/asyncpg/tests/test_connect.py", line 748, in run_testcase
    self.assertEqual(expected, result, 'Testcase: {}'.format(testcase))
AssertionError: Tuples differ: ([('abc', 5432)], {'password': 'password from pgpas[46 chars]db'}) != ([('abc', 26257)], {'user': 'user', 'password': 'pa[47 chars]db'})

First differing element 0:
[('abc', 5432)]
[('abc', 26257)]

- ([('abc', 5432)],
?            ^^^

+ ([('abc', 26257)],
?           +++ ^

   {'database': 'db',
    'password': 'password from pgpass for user@abc',
    'user': 'user'}) : Testcase: {'dsn': 'postgres://user@abc/db?passfile=/var/folders/1_/_kcb28_94w16ml515w877ynm0000gn/T/tmpjh5aawll', 'result': ([('abc', 5432)], {'password': 'password from pgpass for user@abc', 'user': 'user', 'database': 'db'})}

----------------------------------------------------------------------
Ran 284 tests in 122.763s

FAILED (failures=2, skipped=3)
Test failed: <unittest.runner.TextTestResult run=284 errors=0 failures=2>
error: Test failed: <unittest.runner.TextTestResult run=284 errors=0 failures=2>
```

Let's turn this into a nightly test that automates all the above steps.

**Comment by rafiss** [comment]
fixed by https://github.com/cockroachdb/cockroach/pull/72161
