### ISSUE TITLE
serverccl: TestTenantHTTP failed

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#70263]
https://teamcity.cockroachdb.com//viewLog.html?buildId=3442741&buildTypeId=Cockroach_MergeToMaster
https://teamcity.cockroachdb.com//viewLog.html?buildId=3448008&buildTypeId=Cockroach_MergeToMaster

```
panic: tenant-usage-select: context canceled

goroutine 30749 [running]:
github.com/cockroachdb/cockroach/pkg/ccl/multitenantccl/tenantcostserver.(*instance).TokenBucketRequest.func1(0x69a8e10, 0xc003a9aa80, 0xc00114bad0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go:83 +0x60a
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn.func1(0x69a8e10, 0xc003a9aa80, 0xc00114bad0, 0xc004d0a900, 0x3ff0000000000000)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:818 +0x43
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec(0xc00114bad0, 0x69a8e10, 0xc003a9aa80, 0xc007c574c0, 0xc00114bad0, 0xc0070897e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:879 +0xdc
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn(0xc003235600, 0x69a8e10, 0xc003a9aa80, 0xc0060495c0, 0xc003a9adb0, 0xc003a9ade0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:817 +0x105
github.com/cockroachdb/cockroach/pkg/ccl/multitenantccl/tenantcostserver.(*instance).TokenBucketRequest(0xc0043e5380, 0x69a8e10, 0xc003a9aa80, 0xa, 0xc000bc52d0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go:54 +0x2ff
github.com/cockroachdb/cockroach/pkg/server.(*Node).TokenBucket(0xc0010f1c00, 0x69a8e10, 0xc003a9aa80, 0xc000bc52d0, 0xc0010f1c00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:1403 +0x18e
github.com/cockroachdb/cockroach/pkg/roachpb._Internal_TokenBucket_Handler.func1(0x69a8e10, 0xc003a9aa80, 0x50b7c00, 0xc000bc52d0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:8745 +0x89
github.com/cockroachdb/cockroach/pkg/util/tracing.ServerInterceptor.func1(0x69a8e10, 0xc003a9aa80, 0x50b7c00, 0xc000bc52d0, 0xc0070897a0, 0xc0004aeb10, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:126 +0x529
google.golang.org/grpc.getChainUnaryHandler.func1(0x69a8e10, 0xc003a9aa80, 0x50b7c00, 0xc000bc52d0, 0xc003b8c988, 0xb6c208, 0x4f73200, 0xc002af82c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1134 +0xe7
github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1(0x69a8e10, 0xc003a9aa80, 0x50b7c00, 0xc000bc52d0, 0xc0070897a0, 0xc002af82c0, 0xc002af82c0, 0x6, 0x49d9e40, 0xc005707990)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:177 +0xab
google.golang.org/grpc.getChainUnaryHandler.func1(0x69a8e10, 0xc003a9aa80, 0x50b7c00, 0xc000bc52d0, 0x50b7c00, 0xc000bc52d0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1134 +0xe7
github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor(0x1, 0x69a8e10, 0xc003a9aa80, 0x50b7c00, 0xc000bc52d0, 0xc0070897a0, 0xc002af8280, 0xc003b8cac8, 0xb6c208, 0x4f73200, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:71 +0xc3
google.golang.org/grpc.chainUnaryServerInterceptors.func1(0x69a8e10, 0xc003a9a9f0, 0x50b7c00, 0xc000bc52d0, 0xc0070897a0, 0xc0004aeb10, 0xc003b8cba0, 0x568b86, 0x4f92740, 0xc003a9a9f0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1120 +0xd0
github.com/cockroachdb/cockroach/pkg/roachpb._Internal_TokenBucket_Handler(0x523e000, 0xc0010f1c00, 0x69a8e10, 0xc003a9a9f0, 0xc0014cff20, 0xc005f5fe00, 0x69a8e10, 0xc003a9a9f0, 0xc0047d5200, 0x13)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:8747 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00723a700, 0x6a13af8, 0xc00405e180, 0xc004d0a7e0, 0xc0053bfe30, 0x8dbde48, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1293 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00723a700, 0x6a13af8, 0xc00405e180, 0xc004d0a7e0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1618 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00459b7f0, 0xc00723a700, 0x6a13af8, 0xc00405e180, 0xc004d0a7e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:939 +0x1fd

```

**Comment by jbowens** [comment]
Not sure who should look into this test failure. Tagging @knz for DB Sever & Security, @tbg and @dhartunian as people who have touched this test before.

**Comment by dhartunian** [comment]
Thx for finding the panic @jbowens I will take a look later today and see if I can repro

**Comment by dhartunian** [comment]
@RaduBerinde do you have some color on this since the panic originates from the tenant cost server? Am I missing some configuration in the test servers?
https://github.com/cockroachdb/cockroach/blob/2e67a03036096c99b20620072b508c0c946317c1/pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go#L82-L84

**Comment by dhartunian** [comment]
I just pushed up https://github.com/cockroachdb/cockroach/pull/70276 which *might* be related but I'm not able to reproduce this yet.

I don't think this test failure signals something wrong since the `maybeCheckInvariants` function failed due to a canceled context, not because of a failed invariant check. The canceled context will make a lot of other things not work as well.

**Comment by dhartunian** [comment]
Ah I see Radu has already fixed this panic in the release branch an hour ago: https://github.com/cockroachdb/cockroach/pull/70142

Closing.

**Comment by jbowens** [comment]
Thanks @dhartunian, @RaduBerinde !
