### ISSUE TITLE
changefeedccl: TestChangefeedTruncateOrDrop deadlock

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#70272]
https://teamcity.cockroachdb.com//viewLog.html?buildId=3447474&buildTypeId=Cockroach_MergeToMaster

```
goroutine 394887 [chan receive, 39 minutes]:
testing.(*T).Run(0xc00690f080, 0x4f46dd5, 0x7, 0xc00f7cd140, 0xc00f7cd140)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedTruncateOrDrop(0xc002dc8000)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_test.go:2098 +0x20a
testing.tRunner(0xc002dc8000, 0x55e1d68)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3

goroutine 404254 [select, 39 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*webhookFeed).Next(0xc008e14b40, 0x65d9fd8, 0xc00690f080, 0x4fa4bb1)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/testfeed_test.go:1426 +0x633
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedTruncateOrDrop.func2(0xc00690f080, 0xc004dc5e10, 0x65655a8, 0xc0004c6de0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_test.go:2073 +0x4be
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.webhookTestWithOptions.func1(0xc00690f080)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/helpers_test.go:602 +0x1c5
testing.tRunner(0xc00690f080, 0xc00f7cd140)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3

goroutine 404632 [select, 39 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).RangeFeed.func1(0x65af248, 0xc007f047c0, 0xc006d6ba00, 0x55e7cc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:76 +0x145
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1(0x0, 0x55e7d68)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:166 +0x3a
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0048c4c60, 0xc0048c4cc0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

Jira issue: CRDB-10013

**Comment by HonoreDB** [comment]
Strong likelihood that this is A: specific to the webhook sink mocking and B: sporadic (passes locally), so I'll remove the release-blocker tag tomorrow if the nightly passes.

**Comment by nicktrav** [comment]
Looks like this happened again [here](https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=7153202&_focus=182335).

**Comment by miretskiy** [comment]
@HonoreDB any updates on this?
