### ISSUE TITLE
sqlccl: TestTenantTempTableCleanup failed

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#70292]
```
I210915 19:57:22.556545 9487 1@ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 481  the server is terminating due to a fatal error (see the DEV channel for details)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482  temporary table was not correctly dropped, expected [[temp_table]] and got [[temp_table] [temp_table2]]
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !goroutine 9487 [running]:
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc09d201, 0xc002ff7cf0, 0x484f65, 0xa91dbd4)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xc6
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc0003baed0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16a5171a7ee287c6, 0x400000000, 0x0, ...)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:301 +0xed5
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x9336828, 0xc0001a6010, 0x1, 0x4, 0x64c42e1, 0x41, 0xc002ff8db8, 0x2, 0x2)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:58 +0x1e5
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:834
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !github.com/cockroachdb/cockroach/pkg/ccl/testccl/sqlccl_test.TestTenantTempTableCleanup(0xc0023e6900)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/testccl/sqlccl/temp_table_clean_test.go:105 +0x12e5
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !testing.tRunner(0xc0023e6900, 0x6a24a48)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/usr/local/go/src/testing/testing.go:1193 +0x203
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !created by testing.(*T).Run
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/usr/local/go/src/testing/testing.go:1238 +0x5d8
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !goroutine 1 [chan receive]:
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !testing.(*T).Run(0xc000103500, 0x6405136, 0x1a, 0x6a24a48, 0x1)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/usr/local/go/src/testing/testing.go:1239 +0x610
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !testing.runTests.func1(0xc000103500)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/usr/local/go/src/testing/testing.go:1511 +0xa7
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !testing.tRunner(0xc000103500, 0xc000d3fc28)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/usr/local/go/src/testing/testing.go:1193 +0x203
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !testing.runTests(0xc0006c2540, 0xb2e6a20, 0x5, 0x5, 0xc048b560f9500d82, 0x3463e18978f, 0xb63c100, 0xc000ae88a0)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/usr/local/go/src/testing/testing.go:1509 +0x613
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !testing.(*M).Run(0xc000b82600, 0x0)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/usr/local/go/src/testing/testing.go:1417 +0x3b4
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !github.com/cockroachdb/cockroach/pkg/ccl/testccl/sqlccl_test.TestMain(0xc000b82600)
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/testccl/sqlccl/main_test.go:30 +0x15c
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !main.main()
F210915 19:57:22.557036 9487 ccl/testccl/sqlccl/temp_table_clean_test.go:105  [-] 482 !	_testmain.go:53 +0x272
F
```
https://teamcity.cockroachdb.com/viewLog.html?buildId=3449532&buildTypeId=Cockroach_UnitTests_Testrace&tab=buildResultsDiv

**Comment by ajwerner** [comment]
Cc @fqazi, never a dull moment
