### ISSUE TITLE
acceptance: tests should try to kill leftover containers from failed previous invocations.

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#7097]
I ran `make acceptance` against sha `093e1e3` and encountered the following panic:

```
+ go test -tags acceptance ./acceptance -run . -timeout 10m -v -nodes 3
I160608 09:58:36.104754 rand.go:76  Random seed: -7777799812709100292
=== RUN   TestAdminLossOfQuorum
I160608 09:58:36.156787 acceptance/cluster/localcluster.go:658  stopping
--- FAIL: TestAdminLossOfQuorum (0.05s)
panic: Error response from daemon: network cockroachdb_acceptance has active endpoints [recovered]
        panic: Error response from daemon: network cockroachdb_acceptance has active endpoints [recovered]
        panic: Error response from daemon: network cockroachdb_acceptance has active endpoints

goroutine 9 [running]:
panic(0x5217c20, 0xc8202e8030)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc820084510)
        /usr/local/Cellar/go/1.6.2/libexec/src/testing/testing.go:467 +0x192
panic(0x5217c20, 0xc8202e8030)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).stopOnPanic(0xc82012e1c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:238 +0x9b
panic(0x5217c20, 0xc8202e8030)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
github.com/cockroachdb/cockroach/acceptance/cluster.maybePanic(0xb740028, 0xc8202e8030)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/cluster/docker.go:166 +0x4b
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).createNetwork(0xc82012e1c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:268 +0x2ef
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start(0xc82012e1c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:588 +0xc2
github.com/cockroachdb/cockroach/acceptance.StartCluster(0xc820084510, 0xc82017ab60, 0x9, 0xc82017c4e0, 0x1, 0x1, 0x12a05f200, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/util_test.go:184 +0x3d1
github.com/cockroachdb/cockroach/acceptance.runTestOnConfigs.func1(0xc820084510, 0xc82013bec8, 0x580b240)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/util_test.go:157 +0x34
github.com/cockroachdb/cockroach/acceptance.runTestOnConfigs(0xc820084510, 0x580b240)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/util_test.go:160 +0x247
github.com/cockroachdb/cockroach/acceptance.TestAdminLossOfQuorum(0xc820084510)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/admin_test.go:34 +0x2d
testing.tRunner(0xc820084510, 0x6056d80)
        /usr/local/Cellar/go/1.6.2/libexec/src/testing/testing.go:473 +0x98
created by testing.RunTests
        /usr/local/Cellar/go/1.6.2/libexec/src/testing/testing.go:582 +0x892
exit status 2
FAIL    github.com/cockroachdb/cockroach/acceptance     0.100s
```

**Comment by tschottdorf** [comment]
This happens when a previous invocation of the acceptance tests crashed (so some containers are still running).

Try `docker kill $(docker -ps -q)`.

**Comment by tschottdorf** [comment]
While you're at it, maybe take a look whether the failed network removal call above has an option to force-kill all active containers using the endpoint. I suppose not, but it'd help.

**Comment by jordanlewis** [comment]
Thanks - that was indeed the issue. I'll look into the force-kill idea.

**Comment by jordanlewis** [comment]
I think it's fairly straightforward to do this cleanup with the golang docker api. There's a call called `NetworkInspect` that can give all of the running containers for a named network. So we could run this call before we try to destroy the network, and destroy any running containers before we do so.

**Comment by tschottdorf** [comment]
I think (?) there's already code that kills running containers, but we don't get there if the network can't be removed. Maybe instead of removing the network we can no-op if it already exists. Then the later code which runs the containers might do the right thing.

If there isn't such code -- that would be the next thing we'd need, so the above might still make sense.
