### ISSUE TITLE
circleci: failed test: TestMultiRangeScanReverseScanInconsistent

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7117]
Found in [#18807](https://circleci.com/gh/cockroachdb/cockroach/18807):

```
	<autogenerated>:31: Leaked goroutine: goroutine 11855 [select]:
		google.golang.org/grpc/transport.(*http2Server).controller(0xc820afc240)
			/go/src/google.golang.org/grpc/transport/http2_server.go:660 +0x8e3
		created by google.golang.org/grpc/transport.newHTTP2Server
			/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0xb6d
	<autogenerated>:31: Leaked goroutine: goroutine 11856 [IO wait]:
		net.runtime_pollWait(0x7f8a642aedd8, 0x72, 0x5c51c9)
			/usr/local/go/src/runtime/netpoll.go:160 +0x63
		net.(*pollDesc).Wait(0xc820600610, 0x72, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:73 +0x56
		net.(*pollDesc).WaitRead(0xc820600610, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:78 +0x44
		net.(*netFD).Read(0xc8206005b0, 0xc820483800, 0x400, 0x400, 0x0, 0x7f8a64304050, 0xc820010048)
			/usr/local/go/src/net/fd_unix.go:250 +0x27b
		net.(*conn).Read(0xc8200ee6b8, 0xc820483800, 0x400, 0x400, 0xc82048380d, 0x0, 0x0)
			/usr/local/go/src/net/net.go:172 +0x121
		net.(*TCPConn).Read(0xc8200ee6b8, 0xc820483800, 0x400, 0x400, 0x26, 0x0, 0x0)
			<autogenerated>:68 +0x7d
		crypto/tls.(*block).readFromUntil(0xc820586330, 0x7f8a642af6b8, 0xc8200ee6b8, 0x5, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:460 +0x143
		crypto/tls.(*Conn).readRecord(0xc8201b6900, 0x2286c17, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:562 +0x3aa
		crypto/tls.(*Conn).Read(0xc8201b6900, 0xc8204a4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:939 +0x1bd
		bufio.(*Reader).fill(0xc82066cf00)
			/usr/local/go/src/bufio/bufio.go:97 +0x365
		bufio.(*Reader).Read(0xc82066cf00, 0xc820480878, 0x9, 0x9, 0x4000000000009, 0x0, 0x0)
			/usr/local/go/src/bufio/bufio.go:207 +0x54e
		io.ReadAtLeast(0x7f8a642af708, 0xc82066cf00, 0xc820480878, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
			/usr/local/go/src/io/io.go:297 +0x119
		io.ReadFull(0x7f8a642af708, 0xc82066cf00, 0xc820480878, 0x9, 0x9, 0x0, 0x0, 0x0)
			/usr/local/go/src/io/io.go:315 +0x77
		golang.org/x/net/http2.readFrameHeader(0xc820480878, 0x9, 0x9, 0x7f8a642af708, 0xc82066cf00, 0x64000000, 0xc800000000, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:237 +0xcd
		golang.org/x/net/http2.(*Framer).ReadFrame(0xc820480840, 0x0, 0x0, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:464 +0x186
		google.golang.org/grpc/transport.(*framer).readFrame(0xc820767da0, 0x0, 0x0, 0x0, 0x0)
			/go/src/google.golang.org/grpc/transport/http_util.go:417 +0x62
		google.golang.org/grpc/transport.(*http2Client).reader(0xc8208f3770)
			/go/src/google.golang.org/grpc/transport/http2_client.go:795 +0x19e
		created by google.golang.org/grpc/transport.newHTTP2Client
			/go/src/google.golang.org/grpc/transport/http2_client.go:174 +0x1182
	<autogenerated>:31: Leaked goroutine: goroutine 11857 [select]:
		google.golang.org/grpc/transport.(*http2Client).controller(0xc8208f3770)
			/go/src/google.golang.org/grpc/transport/http2_client.go:873 +0x8e3
		created by google.golang.org/grpc/transport.newHTTP2Client
			/go/src/google.golang.org/grpc/transport/http2_client.go:201 +0x1b67
	<autogenerated>:31: Leaked goroutine: goroutine 11872 [select]:
		google.golang.org/grpc.(*Conn).transportMonitor(0xc8203fbc20)
			/go/src/google.golang.org/grpc/clientconn.go:547 +0x252
		google.golang.org/grpc.NewConn.func1(0xc8203fbc20)
			/go/src/google.golang.org/grpc/clientconn.go:355 +0x1fc
		created by google.golang.org/grpc.NewConn
			/go/src/google.golang.org/grpc/clientconn.go:356 +0x6d7
	<autogenerated>:31: Leaked goroutine: goroutine 11875 [IO wait]:
		net.runtime_pollWait(0x7f8a642aef58, 0x72, 0x5c51c9)
			/usr/local/go/src/runtime/netpoll.go:160 +0x63
		net.(*pollDesc).Wait(0xc820600680, 0x72, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:73 +0x56
		net.(*pollDesc).WaitRead(0xc820600680, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:78 +0x44
		net.(*netFD).Read(0xc820600620, 0xc820483c00, 0x400, 0x400, 0x0, 0x7f8a64304050, 0xc820010048)
			/usr/local/go/src/net/fd_unix.go:250 +0x27b
		net.(*conn).Read(0xc8200ee6c0, 0xc820483c00, 0x400, 0x400, 0x7f8a64304028, 0x0, 0x0)
			/usr/local/go/src/net/net.go:172 +0x121
		net.(*TCPConn).Read(0xc8200ee6c0, 0xc820483c00, 0x400, 0x400, 0x1, 0x0, 0x0)
			<autogenerated>:68 +0x7d
		github.com/cockroachdb/cmux.(*MuxConn).Read(0xc8203eca50, 0xc820483c00, 0x400, 0x400, 0x26, 0x0, 0x0)
			/go/src/github.com/cockroachdb/cmux/cmux.go:204 +0x168
		crypto/tls.(*block).readFromUntil(0xc820586420, 0x7f8a557ccc30, 0xc8203eca50, 0x5, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:460 +0x143
		crypto/tls.(*Conn).readRecord(0xc8201b6c00, 0x2286c17, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:562 +0x3aa
		crypto/tls.(*Conn).Read(0xc8201b6c00, 0xc820712000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:939 +0x1bd
		bufio.(*Reader).fill(0xc82066cc00)
			/usr/local/go/src/bufio/bufio.go:97 +0x365
		bufio.(*Reader).Read(0xc82066cc00, 0xc8204807b8, 0x9, 0x9, 0x4000000000009, 0x0, 0x0)
			/usr/local/go/src/bufio/bufio.go:207 +0x54e
		io.ReadAtLeast(0x7f8a642af708, 0xc82066cc00, 0xc8204807b8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
			/usr/local/go/src/io/io.go:297 +0x119
		io.ReadFull(0x7f8a642af708, 0xc82066cc00, 0xc8204807b8, 0x9, 0x9, 0x0, 0x0, 0x0)
			/usr/local/go/src/io/io.go:315 +0x77
		golang.org/x/net/http2.readFrameHeader(0xc8204807b8, 0x9, 0x9, 0x7f8a642af708, 0xc82066cc00, 0x64000000, 0xc800000000, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:237 +0xcd
		golang.org/x/net/http2.(*Framer).ReadFrame(0xc820480780, 0x0, 0x0, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:464 +0x186
		google.golang.org/grpc/transport.(*framer).readFrame(0xc820767c50, 0x0, 0x0, 0x0, 0x0)
			/go/src/google.golang.org/grpc/transport/http_util.go:417 +0x62
		google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc820afc240, 0xc820767ce0)
			/go/src/google.golang.org/grpc/transport/http2_server.go:243 +0x78b
		google.golang.org/grpc.(*Server).serveStreams(0xc820211710, 0x7f8a642af9d8, 0xc820afc240)
			/go/src/google.golang.org/grpc/server.go:354 +0x1dd
		google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc820211710, 0x7f8a64313df0, 0xc8201b6c00, 0x7f8a64313e50, 0xc8204ec2c0)
			/go/src/google.golang.org/grpc/server.go:341 +0x54e
		google.golang.org/grpc.(*Server).handleRawConn(0xc820211710, 0x7f8a557ccbd0, 0xc8203eca50)
			/go/src/google.golang.org/grpc/server.go:318 +0x5b2
		created by google.golang.org/grpc.(*Server).Serve
			/go/src/google.golang.org/grpc/server.go:290 +0x3fb
```

**Comment by tamird** [comment]
Fixed in #7241.
