### ISSUE TITLE
sqlproxyccl: segfault when stopping the proxy

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#71386]
I get a sigsegv when interrupting the proxy with Ctrl+C:

```
^CI211011 03:55:11.614529 1 1@cli/mt_proxy.go:139  [-] 414  received signal 'interrupt'
I211011 03:55:11.614590 181 cli/mt_proxy.go:144  [-] 415  server stopping
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417  a panic has occurred!
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +runtime error: invalid memory address or nil pointer dereference
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +(1) attached stack trace
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  -- stack trace:
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  | runtime.gopanic
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  |    /usr/local/go/src/runtime/panic.go:1038
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  | runtime.panicmem
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  |    /usr/local/go/src/runtime/panic.go:221
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  | runtime.sigpanic
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  |    /usr/local/go/src/runtime/signal_unix.go:735
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  | github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*proxyHandler).handle.func4
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  |    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/proxy_handler.go:397
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  | runtime.gopanic
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  |    /usr/local/go/src/runtime/panic.go:1052
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  | runtime.panicmem
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  |    /usr/local/go/src/runtime/panic.go:221
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  | runtime.sigpanic
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  |    /usr/local/go/src/runtime/signal_unix.go:735
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  | io.ReadAtLeast
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  |    /usr/local/go/src/io/io.go:328
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  | github.com/jackc/chunkreader/v2.(*ChunkReader).appendAtLeast
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  |    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/vendor/github.com/jackc/chunkreader/v2/chun
kreader.go:88
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  | github.com/jackc/chunkreader/v2.(*ChunkReader).Next
E211011 03:55:11.614739 122 1@util/log/logcrash/crash_reporting.go:140  [-] 417 +  |    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/vendor/github.com/jackc/chunkreader/v2/chun
kreader.go:78
[...]
```

And more stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x873c042]

goroutine 122 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc001a74700, {0x224f3c8, 0xc000706500})
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:231 +0xcd
panic({0x5a5640, 0x8ae67a0})
        /usr/local/go/src/runtime/panic.go:1038 +0x25b
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*proxyHandler).handle.func4({0x0, 0x0})
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/proxy_handler.go:397 +0x22
panic({0x5a5640, 0x8ae67a0})
        /usr/local/go/src/runtime/panic.go:1052 +0x2fe
io.ReadAtLeast({0x0, 0x0}, {0xc0004ac000, 0x2000, 0x2000}, 0x5)
        /usr/local/go/src/io/io.go:328 +0x8b
github.com/jackc/chunkreader/v2.(*ChunkReader).appendAtLeast(...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/vendor/github.com/jackc/chunkreader/v2/chunkreader.go:88
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc000662700, 0x5)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/vendor/github.com/jackc/chunkreader/v2/chunkreader.go:78 +0x348
github.com/jackc/pgproto3/v2.(*Frontend).Receive(0xc00041e000)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/vendor/github.com/jackc/pgproto3/v2/frontend.go:72 +0x62
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.glob..func1({0x22c6160, 0xc001e2e000}, {0x0, 0x0})
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/authentication.go:30 +0x405
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*proxyHandler).handle(0xc001c2c700, {0x224f470, 0xc001d05740}, 0xc001d05710)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/proxy_handler.go:400 +0x20f8
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*Server).Serve.func2({0x224f3c8, 0xc000706500})
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/server.go:185 +0x151
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2(0xc001a74700, {0x224f3c8, 0xc000706500}, 0x0, 0x0, 0xc001068378)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:442 +0x110
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:434 +0x37a

```

and more:
```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x873c042]

goroutine 169 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc001a74700, {0x224f3c8, 0xc000706500})
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:231 +0xcd
panic({0x5a5640, 0x8ae67a0})
        /usr/local/go/src/runtime/panic.go:1038 +0x25b
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*proxyHandler).handle.func4({0x0, 0x0})
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/proxy_handler.go:397 +0x22
panic({0x5a5640, 0x8ae67a0})
        /usr/local/go/src/runtime/panic.go:1052 +0x2fe
io.ReadAtLeast({0x0, 0x0}, {0xc0004c2000, 0x2000, 0x2000}, 0x5)
        /usr/local/go/src/io/io.go:328 +0x8b
github.com/jackc/chunkreader/v2.(*ChunkReader).appendAtLeast(...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/vendor/github.com/jackc/chunkreader/v2/chunkreader.go:88
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc0004ba0c0, 0x5)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/vendor/github.com/jackc/chunkreader/v2/chunkreader.go:78 +0x348
github.com/jackc/pgproto3/v2.(*Frontend).Receive(0xc000babc00)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/vendor/github.com/jackc/pgproto3/v2/frontend.go:72 +0x62
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.glob..func1({0x22c6160, 0xc001e2f180}, {0x0, 0x0})
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/authentication.go:30 +0x405
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*proxyHandler).handle(0xc001c2c700, {0x224f470, 0xc001aba930}, 0xc001aba900)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/proxy_handler.go:400 +0x20f8
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*Server).Serve.func2({0x224f3c8, 0xc000706500})
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/server.go:185 +0x151
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2(0xc001a74700, {0x224f3c8, 0xc000706500}, 0x0, 0x0, 0xc001a228e8)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:442 +0x110
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:434 +0x37a

```

cc @jaylim-crl for triage

Jira issue: CRDB-10543

**Comment by darinpp** [comment]
I cannot reproduce the issue. @knz Can you provide some details as to what were you doing when you got the errors? We did major changes in `pkg/ccl/sqlproxyccl/authentication.go` that may have affected the possibility of segfault.

**Comment by knz** [comment]
As I explained, I pressed "Ctrl+C" while the proxy was running.

I understand there were changes since then, but it may merely mean the issue has been moved elsewhere or has become harder to reproduce.

Is it possible to use `git checkout` to a version of the `master` branch from around Oct 11, and investigate the code at the file/line numbers indicated in the stack trace?
