### ISSUE TITLE
stress: failed test in cockroach/sql/distsql/distsql.test: TestJoinReader

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#7153]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/19503c4f6d3de020f62877d47dea404511be3461

Stress build found a failed test:

```
=== RUN   TestJoinReader
I160610 05:56:18.668869 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160610 05:56:18.672519 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
W160610 05:56:18.678765 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160610 05:56:18.679036 server/node.go:401  store store=0:0 ([]=) not bootstrapped
I160610 05:56:18.681264 storage/replica_command.go:1531  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407093h56m23.180760314s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 05:56:18.681160229 +0000 UTC]
I160610 05:56:18.681791 server/node.go:327  **** cluster {3a4e94a4-f3be-4d75-a5db-f97caef5a51b} has been created
I160610 05:56:18.681820 server/node.go:328  **** add additional nodes by specifying --join=127.0.0.1:46635
W160610 05:56:18.681836 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160610 05:56:18.682482 server/node.go:414  initialized store store=1:1 ([]=): {Capacity:10365558784 Available:8197918720 RangeCount:0}
I160610 05:56:18.682518 server/node.go:302  node ID 1 initialized
I160610 05:56:18.682575 storage/stores.go:287  read 0 node addresses from persistent storage
I160610 05:56:18.682696 server/node.go:535  connecting to gossip network to verify cluster ID...
I160610 05:56:18.683377 server/node.go:556  node connected via gossip and verified as part of cluster {"3a4e94a4-f3be-4d75-a5db-f97caef5a51b"}
I160610 05:56:18.683499 server/node.go:355  [node=1] Started node with [[]=] engine(s) and attributes []
I160610 05:56:18.683543 server/server.go:417  starting https server at 127.0.0.1:36966
I160610 05:56:18.683565 server/server.go:418  starting grpc/postgres server at 127.0.0.1:46635
I160610 05:56:18.683800 storage/split_queue.go:96  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160610 05:56:18.734293 server/updates.go:156  No previous updates check time.
I160610 05:56:18.736958 storage/replica_command.go:2079  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160610 05:56:18.746688 storage/replica_command.go:1531  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407093h56m23.296350944s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 05:56:18.746647837 +0000 UTC]
I160610 05:56:18.746872 storage/replica_command.go:2079  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160610 05:56:18.752524 storage/replica_command.go:1531  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407093h56m23.302153035s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 05:56:18.752485258 +0000 UTC]
I160610 05:56:18.752848 storage/replica_command.go:2079  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160610 05:56:18.764630 storage/replica_command.go:1531  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407093h56m23.314313285s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 05:56:18.764592484 +0000 UTC]
I160610 05:56:18.764760 storage/replica_command.go:2079  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160610 05:56:18.817058 storage/replica_command.go:1531  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407093h56m23.366847204s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 05:56:18.817019178 +0000 UTC]
I160610 05:56:18.817522 storage/split_queue.go:96  splitting range=5 [/Table/14-/Max) at keys [/Table/50/0]
I160610 05:56:18.817834 storage/replica_command.go:2079  initiating a split of range=5 [/Table/14-/Max) at key /Table/50
I160610 05:56:18.826671 storage/replica_command.go:1531  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407093h56m23.375972079s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 05:56:18.826627001 +0000 UTC]
I160610 05:56:18.826777 storage/split_queue.go:96  splitting range=6 [/Table/50-/Max) at keys [/Table/51/0]
I160610 05:56:18.827128 storage/replica_command.go:2079  initiating a split of range=6 [/Table/50-/Max) at key /Table/51
I160610 05:56:18.854594 storage/replica_command.go:1531  range 7: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407093h56m23.404302806s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 05:56:18.8545551 +0000 UTC]
I160610 05:56:18.855688 stopper.go:352  draining; tasks left:
1      storage/intent_resolver.go:341
1      storage/intent_resolver.go:302
W160610 05:56:18.855781 storage/intent_resolver.go:318  [node=1,store=1,range=6] failed to resolve intents: server/node.go:804: node 1 stopped
I160610 05:56:18.855810 stopper.go:352  draining; tasks left:
1      storage/intent_resolver.go:302
W160610 05:56:18.855861 storage/intent_resolver.go:299  [node=1,store=1,range=1] failed to push during intent resolution: server/node.go:804: node 1 stopped
--- FAIL: TestJoinReader (5.21s)
	leaktest.go:86: Leaked goroutine: goroutine 168 [IO wait]:
		net.runtime_pollWait(0x7f93e2e7ae18, 0x72, 0xc8204e3400)
			/usr/local/go/src/runtime/netpoll.go:160 +0x60
		net.(*pollDesc).Wait(0xc820687090, 0x72, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
		net.(*pollDesc).WaitRead(0xc820687090, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
		net.(*netFD).Read(0xc820687030, 0xc8204e3400, 0x400, 0x400, 0x0, 0x7f93e2f39028, 0xc82009a0b0)
			/usr/local/go/src/net/fd_unix.go:250 +0x23a
		net.(*conn).Read(0xc82009e2a0, 0xc8204e3400, 0x400, 0x400, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/net.go:172 +0xe4
		github.com/cockroachdb/cmux.(*MuxConn).Read(0xc820585550, 0xc8204e3400, 0x400, 0x400, 0xd, 0x0, 0x0)
			/go/src/github.com/cockroachdb/cmux/cmux.go:204 +0x117
		crypto/tls.(*block).readFromUntil(0xc8207fa630, 0x7f93e2e7b358, 0xc820585550, 0x5, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
		crypto/tls.(*Conn).readRecord(0xc82043a300, 0x1ce0117, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
		crypto/tls.(*Conn).Read(0xc82043a300, 0xc8207b6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:939 +0x167
		bufio.(*Reader).fill(0xc8206a18c0)
			/usr/local/go/src/bufio/bufio.go:97 +0x1e9
		bufio.(*Reader).Read(0xc8206a18c0, 0xc8204980f8, 0x9, 0x9, 0x9, 0x0, 0x0)
			/usr/local/go/src/bufio/bufio.go:207 +0x260
		io.ReadAtLeast(0x7f93e2f80d48, 0xc8206a18c0, 0xc8204980f8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
			/usr/local/go/src/io/io.go:297 +0xe6
		io.ReadFull(0x7f93e2f80d48, 0xc8206a18c0, 0xc8204980f8, 0x9, 0x9, 0x6947d2a14a4b6f01, 0x0, 0x0)
			/usr/local/go/src/io/io.go:315 +0x62
		golang.org/x/net/http2.readFrameHeader(0xc8204980f8, 0x9, 0x9, 0x7f93e2f80d48, 0xc8206a18c0, 0xe2000000, 0xc800000000, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
		golang.org/x/net/http2.(*Framer).ReadFrame(0xc8204980c0, 0x0, 0x0, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:464 +0x106
		google.golang.org/grpc/transport.(*framer).readFrame(0xc8207acba0, 0x0, 0x0, 0x0, 0x0)
			/go/src/google.golang.org/grpc/transport/http_util.go:417 +0x3d
		google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc8206e41b0, 0xc8207acc30)
			/go/src/google.golang.org/grpc/transport/http2_server.go:243 +0x646
		google.golang.org/grpc.(*Server).serveStreams(0xc820935a70, 0x7f93e2f80d98, 0xc8206e41b0)
			/go/src/google.golang.org/grpc/server.go:354 +0x159
		google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc820935a70, 0x7f93e2f80c70, 0xc82043a300, 0x7f93e2f80cd0, 0xc8201aa420)
			/go/src/google.golang.org/grpc/server.go:341 +0x49d
		google.golang.org/grpc.(*Server).handleRawConn(0xc820935a70, 0x7f93e2e7b2f8, 0xc820585550)
			/go/src/google.golang.org/grpc/server.go:318 +0x4ee
		created by google.golang.org/grpc.(*Server).Serve
			/go/src/google.golang.org/grpc/server.go:290 +0x38c
	leaktest.go:86: Leaked goroutine: goroutine 38 [select]:
		google.golang.org/grpc.(*Conn).transportMonitor(0xc8201f40f0)
			/go/src/google.golang.org/grpc/clientconn.go:547 +0x1d3
		google.golang.org/grpc.NewConn.func1(0xc8201f40f0)
			/go/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
		created by google.golang.org/grpc.NewConn
			/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3
	leaktest.go:86: Leaked goroutine: goroutine 40 [select]:
		google.golang.org/grpc/transport.(*http2Server).controller(0xc8206e41b0)
			/go/src/google.golang.org/grpc/transport/http2_server.go:660 +0x5da
		created by google.golang.org/grpc/transport.newHTTP2Server
			/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x84f
	leaktest.go:86: Leaked goroutine: goroutine 41 [IO wait]:
		net.runtime_pollWait(0x7f93e2e7b058, 0x72, 0xc8206a3000)
			/usr/local/go/src/runtime/netpoll.go:160 +0x60
		net.(*pollDesc).Wait(0xc8207803e0, 0x72, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
		net.(*pollDesc).WaitRead(0xc8207803e0, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
		net.(*netFD).Read(0xc820780380, 0xc8206a3000, 0x400, 0x400, 0x0, 0x7f93e2f39028, 0xc82009a0b0)
			/usr/local/go/src/net/fd_unix.go:250 +0x23a
		net.(*conn).Read(0xc82018c170, 0xc8206a3000, 0x400, 0x400, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/net.go:172 +0xe4
		crypto/tls.(*block).readFromUntil(0xc8207aca50, 0x7f93e2f40ad0, 0xc82018c170, 0x5, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
		crypto/tls.(*Conn).readRecord(0xc82043a000, 0x1ce0117, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
		crypto/tls.(*Conn).Read(0xc82043a000, 0xc8203f6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:939 +0x167
		bufio.(*Reader).fill(0xc8206a1c20)
			/usr/local/go/src/bufio/bufio.go:97 +0x1e9
		bufio.(*Reader).Read(0xc8206a1c20, 0xc8204981b8, 0x9, 0x9, 0x9, 0x0, 0x0)
			/usr/local/go/src/bufio/bufio.go:207 +0x260
		io.ReadAtLeast(0x7f93e2f80d48, 0xc8206a1c20, 0xc8204981b8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
			/usr/local/go/src/io/io.go:297 +0xe6
		io.ReadFull(0x7f93e2f80d48, 0xc8206a1c20, 0xc8204981b8, 0x9, 0x9, 0x6947d2a14a4b6f01, 0x0, 0x0)
			/usr/local/go/src/io/io.go:315 +0x62
		golang.org/x/net/http2.readFrameHeader(0xc8204981b8, 0x9, 0x9, 0x7f93e2f80d48, 0xc8206a1c20, 0xe2000000, 0xc800000000, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
		golang.org/x/net/http2.(*Framer).ReadFrame(0xc820498180, 0x0, 0x0, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:464 +0x106
		google.golang.org/grpc/transport.(*framer).readFrame(0xc8207acd50, 0x0, 0x0, 0x0, 0x0)
			/go/src/google.golang.org/grpc/transport/http_util.go:417 +0x3d
		google.golang.org/grpc/transport.(*http2Client).reader(0xc820936000)
			/go/src/google.golang.org/grpc/transport/http2_client.go:795 +0x109
		created by google.golang.org/grpc/transport.newHTTP2Client
			/go/src/google.golang.org/grpc/transport/http2_client.go:174 +0xd21
	leaktest.go:86: Leaked goroutine: goroutine 42 [select]:
		google.golang.org/grpc/transport.(*http2Client).controller(0xc820936000)
			/go/src/google.golang.org/grpc/transport/http2_client.go:873 +0x5da
		created by google.golang.org/grpc/transport.newHTTP2Client
			/go/src/google.golang.org/grpc/transport/http2_client.go:201 +0x15c2
```

Run Details:

```
77 runs so far, 0 failures, over 5s
163 runs so far, 0 failures, over 10s
244 runs so far, 0 failures, over 15s
327 runs so far, 0 failures, over 20s
411 runs so far, 0 failures, over 25s
498 runs so far, 0 failures, over 30s
584 runs so far, 0 failures, over 35s
668 runs so far, 0 failures, over 40s
756 runs so far, 0 failures, over 45s
836 runs so far, 0 failures, over 50s
922 runs so far, 0 failures, over 55s
1008 runs so far, 0 failures, over 1m0s
1091 runs so far, 0 failures, over 1m5s
1177 runs so far, 0 failures, over 1m10s
1262 runs so far, 0 failures, over 1m15s
1345 runs so far, 0 failures, over 1m20s
1427 runs so far, 0 failures, over 1m25s
1514 runs so far, 0 failures, over 1m30s
1597 runs so far, 0 failures, over 1m35s
1679 runs so far, 0 failures, over 1m40s
1766 runs so far, 0 failures, over 1m45s
1851 runs so far, 0 failures, over 1m50s
1934 runs so far, 0 failures, over 1m55s
2019 runs so far, 0 failures, over 2m0s
2105 runs so far, 0 failures, over 2m5s
2189 runs so far, 0 failures, over 2m10s
2273 runs so far, 0 failures, over 2m15s
2359 runs so far, 0 failures, over 2m20s
2444 runs so far, 0 failures, over 2m25s
2528 runs so far, 0 failures, over 2m30s
2609 runs so far, 0 failures, over 2m35s
2695 runs so far, 0 failures, over 2m40s
2778 runs so far, 0 failures, over 2m45s
2862 runs so far, 0 failures, over 2m50s
2946 runs so far, 0 failures, over 2m55s
3029 runs so far, 0 failures, over 3m0s
3112 runs so far, 0 failures, over 3m5s
3195 runs so far, 0 failures, over 3m10s
3280 runs so far, 0 failures, over 3m15s
3365 runs so far, 0 failures, over 3m20s
3448 runs so far, 0 failures, over 3m25s
3536 runs so far, 0 failures, over 3m30s
3622 runs so far, 0 failures, over 3m35s
3706 runs so far, 0 failures, over 3m40s
3792 runs so far, 0 failures, over 3m45s
3871 runs so far, 0 failures, over 3m50s
3895 runs completed, 1 failures, over 3m51s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Fixed in #7241.
