### ISSUE TITLE
bazel: unable to fetch non-mirrored dependencies in CI

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#71679]
**Describe the problem**

Saw the following error in [this build](https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=3599992&_focus=5829) for #71225. Is it a known issue?

```
WARNING: Download from https://github.com/bazelbuild/rules_nodejs/releases/download/4.1.0/rules_nodejs-4.1.0.tar.gz failed: class java.io.IOException GET returned 403 Forbidden
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_nodejs':
   Traceback (most recent call last):
	File "/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_nodejs/releases/download/4.1.0/rules_nodejs-4.1.0.tar.gz] to /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/build_bazel_rules_nodejs/temp2605887283821107915/rules_nodejs-4.1.0.tar.gz: GET returned 403 Forbidden
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_nodejs/releases/download/4.1.0/rules_nodejs-4.1.0.tar.gz] to /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/build_bazel_rules_nodejs/temp2605887283821107915/rules_nodejs-4.1.0.tar.gz: GET returned 403 Forbidden
ERROR: no such package '@build_bazel_rules_nodejs//': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_nodejs/releases/download/4.1.0/rules_nodejs-4.1.0.tar.gz] to /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/build_bazel_rules_nodejs/temp2605887283821107915/rules_nodejs-4.1.0.tar.gz: GET returned 403 Forbidden
```

Poking around other failing bors builds, I'm also seeing the [following](https://teamcity.cockroachdb.com/viewLog.html?buildId=3599613&buildTypeId=Cockroach_UnitTests) for #71625 (+cc @dt).

```
[Run Bazel build] ERROR: An error occurred during the fetch of repository 'cmake-3.19.6-Linux-x86_64':
[19:16:34]	[Run Bazel build]    Traceback (most recent call last):
[19:16:34]	[Run Bazel build] 	File "/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
[19:16:34]	[Run Bazel build] 		download_info = ctx.download_and_extract(
[19:16:34]	[Run Bazel build] Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6-Linux-x86_64.tar.gz] to /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/cmake-3.19.6-Linux-x86_64/temp2048485385104842867/cmake-3.19.6-Linux-x86_64.tar.gz: GET returned 403 Forbidden
[19:16:34]	[Run Bazel build] ERROR: Error fetching repository: Traceback (most recent call last):
[19:16:34]	[Run Bazel build] 	File "/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
[19:16:34]	[Run Bazel build] 		download_info = ctx.download_and_extract(
[19:16:34]	[Run Bazel build] Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6-Linux-x86_64.tar.gz] to /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/cmake-3.19.6-Linux-x86_64/temp2048485385104842867/cmake-3.19.6-Linux-x86_64.tar.gz: GET returned 403 Forbidden
[19:16:34]	[Run Bazel build] ERROR: /go/src/github.com/cockroachdb/cockroach/c-deps/BUILD.bazel:70:6: //c-deps:libgeos depends on @cmake-3.19.6-Linux-x86_64//:cmake_tool in repository @cmake-3.19.6-Linux-x86_64 which failed to fetch. no such package '@cmake-3.19.6-Linux-x86_64//': java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6-Linux-x86_64.tar.gz] to /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/cmake-3.19.6-Linux-x86_64/temp2048485385104842867/cmake-3.19.6-Linux-x86_64.tar.gz: GET returned 403 Forbidden
[19:16:34]	[Run Bazel build] ERROR: Analysis of target '//c-deps:libgeos' failed; build aborted: Analysis failed
```

**Comment by rickystewart** [comment]
We're not mirroring Go dependencies at all yet -- work in progress. :)
