### ISSUE TITLE
stress: failed test in cockroach/storage/storage.test: TestStoreRangeRebalance

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#7176]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/e1f8b0c508b0e090684da878b95df80050bd3115

Stress build found a failed test:

```
=== RUN   TestStoreRangeRebalance
I160612 07:22:19.835827 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160612 07:22:19.836335 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
W160612 07:22:19.839548 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160612 07:22:19.840381 storage/replica_command.go:1531  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900ms following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00 +0000 UTC]
I160612 07:22:19.840632 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160612 07:22:19.841124 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160612 07:22:19.841584 gossip/gossip.go:923  starting client to 127.0.0.1:33574
I160612 07:22:19.841657 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160612 07:22:19.842164 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160612 07:22:19.842680 gossip/gossip.go:923  starting client to 127.0.0.1:33574
I160612 07:22:19.842756 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160612 07:22:19.843153 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160612 07:22:19.843573 gossip/gossip.go:923  starting client to 127.0.0.1:45088
I160612 07:22:19.844832 storage/replica_raftstorage.go:587  generated snapshot for range 1 at index 12 in 100.374µs. encoded size=2429, 25 KV pairs, 2 log entries
I160612 07:22:19.845447 storage/replica.go:1446  raft: proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 1
I160612 07:22:19.845959 storage/replica_raftstorage.go:587  generated snapshot for range 1 at index 14 in 98.964µs. encoded size=3368, 28 KV pairs, 4 log entries
I160612 07:22:19.846857 storage/replica_raftstorage.go:587  generated snapshot for range 1 at index 14 in 132.394µs. encoded size=3368, 28 KV pairs, 4 log entries
I160612 07:22:19.847093 storage/replica_raftstorage.go:681  replica 2 received snapshot for range 1 at index 14. encoded size=3368, 28 KV pairs, 4 log entries
I160612 07:22:19.847263 storage/replica_raftstorage.go:683  replica 2 applied snapshot for range 1 in 147.724µs
I160612 07:22:19.848472 storage/replica.go:1446  raft: proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3} for range 1
I160612 07:22:19.941045 storage/replica_raftstorage.go:587  generated snapshot for range 1 at index 16 in 195.615µs. encoded size=4371, 31 KV pairs, 6 log entries
I160612 07:22:19.941396 storage/replica_raftstorage.go:681  replica 3 received snapshot for range 1 at index 16. encoded size=4371, 31 KV pairs, 6 log entries
I160612 07:22:19.941625 storage/replica_raftstorage.go:683  replica 3 applied snapshot for range 1 in 205.786µs
I160612 07:22:19.999547 storage/replica_command.go:1538  range 1: replicaID 1 transfer raft leadership to replicaID 2
I160612 07:22:19.999871 storage/replica_command.go:1531  range 1: new leader lease replica {2 2 2} 1970-01-01 00:00:00.9 +0000 UTC 1.8s following replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900ms [physicalTime=1970-01-01 00:00:01.8 +0000 UTC]
I160612 07:22:20.000607 storage/replica_raftstorage.go:587  generated snapshot for range 1 at index 17 in 199.733µs. encoded size=4494, 31 KV pairs, 7 log entries
I160612 07:22:20.002693 storage/replica.go:1446  raft: proposing ADD_REPLICA {NodeID:4 StoreID:4 ReplicaID:4} for range 1
I160612 07:22:20.004738 storage/replica_raftstorage.go:587  generated snapshot for range 1 at index 21 in 176.16µs. encoded size=6793, 41 KV pairs, 11 log entries
I160612 07:22:20.004996 storage/replica_raftstorage.go:681  replica 4 received snapshot for range 1 at index 21. encoded size=6793, 41 KV pairs, 11 log entries
I160612 07:22:20.005036 storage/replica.go:1446  raft: proposing REMOVE_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 1
I160612 07:22:20.005242 storage/replica_raftstorage.go:683  replica 4 applied snapshot for range 1 in 225.868µs
I160612 07:22:20.245295 storage/replica_command.go:1538  range 1: replicaID 3 transfer raft leadership to replicaID 1
I160612 07:22:20.245495 storage/replica_command.go:1531  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:02.7 +0000 UTC 1.8s following replica {2 2 2} 1970-01-01 00:00:00.9 +0000 UTC 1.8s [physicalTime=1970-01-01 00:00:03.6 +0000 UTC]
I160612 07:22:20.245834 stopper.go:352  draining; tasks left:
1      storage/queue.go:386
E160612 07:22:20.246233 storage/queue.go:449  [replicaGC] range=1 [/Min-/Max): error: failed to send RPC: sending to all 3 replicas failed; last error: range 1: replica node_id:3 store_id:3 replica_id:3  not leader; leader is node_id:1 store_id:1 replica_id:1 
I160612 07:22:20.246629 http2_client.go:919  transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:43672->127.0.0.1:35573: read: connection reset by peer.
I160612 07:22:21.246918 /go/src/google.golang.org/grpc/clientconn.go:499  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35573: getsockopt: connection refused"; Reconnecting to "127.0.0.1:35573"
I160612 07:22:22.836694 /go/src/google.golang.org/grpc/clientconn.go:499  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35573: getsockopt: connection refused"; Reconnecting to "127.0.0.1:35573"
I160612 07:22:22.866109 http2_client.go:919  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I160612 07:22:23.866400 /go/src/google.golang.org/grpc/clientconn.go:499  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35573: getsockopt: connection refused"; Reconnecting to "127.0.0.1:35573"
--- FAIL: TestStoreRangeRebalance (5.45s)
	leaktest.go:86: Leaked goroutine: goroutine 11602 [select]:
		google.golang.org/grpc.(*Conn).resetTransport(0xc8207210e0, 0x0, 0x0, 0x0)
			/go/src/google.golang.org/grpc/clientconn.go:494 +0xa45
		google.golang.org/grpc.(*Conn).reconnect(0xc8207210e0, 0xc821cfc360)
			/go/src/google.golang.org/grpc/clientconn.go:532 +0xc4
		google.golang.org/grpc.(*Conn).transportMonitor(0xc8207210e0)
			/go/src/google.golang.org/grpc/clientconn.go:557 +0x16b
		google.golang.org/grpc.NewConn.func1(0xc8207210e0)
			/go/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
		created by google.golang.org/grpc.NewConn
			/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
0 runs so far, 0 failures, over 35s
10 runs so far, 0 failures, over 40s
15 runs so far, 0 failures, over 45s
15 runs so far, 0 failures, over 50s
15 runs so far, 0 failures, over 55s
15 runs so far, 0 failures, over 1m0s
15 runs so far, 0 failures, over 1m5s
15 runs so far, 0 failures, over 1m10s
15 runs so far, 0 failures, over 1m15s
27 runs so far, 0 failures, over 1m20s
28 runs completed, 1 failures, over 1m23s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Fixed in #7241.
