### ISSUE TITLE
stress: failed test in cockroach/sql/sql.test: TestCantLeaseDeletedTable

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#7183]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/0b950ce267fae48b64e66211cb0e51cdecb3d4fa

Stress build found a failed test:

```
=== RUN   TestCantLeaseDeletedTable
I160613 07:02:48.900935 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160613 07:02:48.904784 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160613 07:02:48.905861 server/node.go:401  store store=0:0 ([]=) not bootstrapped
W160613 07:02:48.905884 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160613 07:02:48.911940 storage/replica_command.go:1531  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407167h2m53.411469821s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-13 07:02:48.911837238 +0000 UTC]
I160613 07:02:48.912478 server/node.go:327  **** cluster {e6a4283b-1b45-4ee4-8665-289ef4bb9e34} has been created
I160613 07:02:48.912509 server/node.go:328  **** add additional nodes by specifying --join=127.0.0.1:33252
W160613 07:02:48.912530 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160613 07:02:48.913130 server/node.go:414  initialized store store=1:1 ([]=): {Capacity:10365558784 Available:7930716160 RangeCount:0}
I160613 07:02:48.913287 server/node.go:302  node ID 1 initialized
I160613 07:02:48.913349 storage/stores.go:287  read 0 node addresses from persistent storage
I160613 07:02:48.913415 server/node.go:535  connecting to gossip network to verify cluster ID...
I160613 07:02:48.913698 server/node.go:556  node connected via gossip and verified as part of cluster {"e6a4283b-1b45-4ee4-8665-289ef4bb9e34"}
I160613 07:02:48.913729 server/node.go:355  [node=1] Started node with [[]=] engine(s) and attributes []
I160613 07:02:48.913762 server/server.go:417  starting https server at 127.0.0.1:41107
I160613 07:02:48.913779 server/server.go:418  starting grpc/postgres server at 127.0.0.1:33252
I160613 07:02:48.913906 storage/split_queue.go:96  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160613 07:02:48.962599 server/updates.go:156  No previous updates check time.
I160613 07:02:48.968553 storage/replica_command.go:2079  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160613 07:02:49.013065 storage/replica_command.go:1531  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407167h2m53.562734033s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-13 07:02:49.013024244 +0000 UTC]
I160613 07:02:49.013207 storage/replica_command.go:2079  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160613 07:02:49.020698 storage/replica_command.go:1531  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407167h2m53.570404008s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-13 07:02:49.020659761 +0000 UTC]
I160613 07:02:49.020844 storage/replica_command.go:2079  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160613 07:02:49.027014 storage/replica_command.go:1531  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407167h2m53.576707909s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-13 07:02:49.026973978 +0000 UTC]
I160613 07:02:49.027149 storage/replica_command.go:2079  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160613 07:02:49.148496 storage/replica_command.go:1531  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407167h2m53.698227887s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-13 07:02:49.148449196 +0000 UTC]
I160613 07:02:49.150854 storage/split_queue.go:96  splitting range=5 [/Table/14-/Max) at keys [/Table/50/0]
I160613 07:02:49.151154 storage/replica_command.go:2079  initiating a split of range=5 [/Table/14-/Max) at key /Table/50
I160613 07:02:49.162367 storage/replica_command.go:1531  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407167h2m53.712060979s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-13 07:02:49.162318552 +0000 UTC]
I160613 07:02:49.162521 storage/split_queue.go:96  splitting range=6 [/Table/50-/Max) at keys [/Table/51/0]
I160613 07:02:49.162999 storage/replica_command.go:2079  initiating a split of range=6 [/Table/50-/Max) at key /Table/51
I160613 07:02:49.163699 stopper.go:352  draining; tasks left:
1      storage/queue.go:386
1      server/node.go:803
E160613 07:02:49.168489 storage/queue.go:449  [split] range=6 [/Table/50-/Max): error: storage/split_queue.go:99: unable to split range=6 [/Table/50-/Max) at key "/Table/51/0": storage/replica_command.go:2132: split at key /Table/51 failed: server/node.go:804: node 1 stopped
I160613 07:02:49.170267 stopper.go:352  draining; tasks left:
1      storage/queue.go:386
--- FAIL: TestCantLeaseDeletedTable (5.30s)
	leaktest.go:86: Leaked goroutine: goroutine 2688 [IO wait]:
		net.runtime_pollWait(0x7f1cfbe48fa8, 0x72, 0xc8205ef000)
			/usr/local/go/src/runtime/netpoll.go:160 +0x60
		net.(*pollDesc).Wait(0xc82128bf00, 0x72, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
		net.(*pollDesc).WaitRead(0xc82128bf00, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
		net.(*netFD).Read(0xc82128bea0, 0xc8205ef000, 0x400, 0x400, 0x0, 0x7f1cfbe39050, 0xc82000e068)
			/usr/local/go/src/net/fd_unix.go:250 +0x23a
		net.(*conn).Read(0xc8207cc540, 0xc8205ef000, 0x400, 0x400, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/net.go:172 +0xe4
		github.com/cockroachdb/cmux.(*MuxConn).Read(0xc8207f0630, 0xc8205ef000, 0x400, 0x400, 0xd, 0x0, 0x0)
			/go/src/github.com/cockroachdb/cmux/cmux.go:204 +0x117
		crypto/tls.(*block).readFromUntil(0xc8215c4c00, 0x7f1cfbdfd128, 0xc8207f0630, 0x5, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
		crypto/tls.(*Conn).readRecord(0xc8205d8000, 0x1e4cc17, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
		crypto/tls.(*Conn).Read(0xc8205d8000, 0xc8208ae000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:939 +0x167
		bufio.(*Reader).fill(0xc820626600)
			/usr/local/go/src/bufio/bufio.go:97 +0x1e9
		bufio.(*Reader).Read(0xc820626600, 0xc8204055f8, 0x9, 0x9, 0x9, 0x0, 0x0)
			/usr/local/go/src/bufio/bufio.go:207 +0x260
		io.ReadAtLeast(0x7f1cfbd7ee28, 0xc820626600, 0xc8204055f8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
			/usr/local/go/src/io/io.go:297 +0xe6
		io.ReadFull(0x7f1cfbd7ee28, 0xc820626600, 0xc8204055f8, 0x9, 0x9, 0x46e9fea829ac8f01, 0x0, 0x0)
			/usr/local/go/src/io/io.go:315 +0x62
		golang.org/x/net/http2.readFrameHeader(0xc8204055f8, 0x9, 0x9, 0x7f1cfbd7ee28, 0xc820626600, 0xfb000000, 0xc800000000, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
		golang.org/x/net/http2.(*Framer).ReadFrame(0xc8204055c0, 0x0, 0x0, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:464 +0x106
		google.golang.org/grpc/transport.(*framer).readFrame(0xc8215c4ea0, 0x0, 0x0, 0x0, 0x0)
			/go/src/google.golang.org/grpc/transport/http_util.go:417 +0x3d
		google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc820096360, 0xc8215c4f30)
			/go/src/google.golang.org/grpc/transport/http2_server.go:243 +0x646
		google.golang.org/grpc.(*Server).serveStreams(0xc8215c37a0, 0x7f1cfbd7ee78, 0xc820096360)
			/go/src/google.golang.org/grpc/server.go:354 +0x159
		google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc8215c37a0, 0x7f1cfbd7ed50, 0xc8205d8000, 0x7f1cfbd7edb0, 0xc82011fb80)
			/go/src/google.golang.org/grpc/server.go:341 +0x49d
		google.golang.org/grpc.(*Server).handleRawConn(0xc8215c37a0, 0x7f1cfbdfd0c8, 0xc8207f0630)
			/go/src/google.golang.org/grpc/server.go:318 +0x4ee
		created by google.golang.org/grpc.(*Server).Serve
			/go/src/google.golang.org/grpc/server.go:290 +0x38c
	leaktest.go:86: Leaked goroutine: goroutine 3054 [select]:
		google.golang.org/grpc.(*Conn).transportMonitor(0xc82089e000)
			/go/src/google.golang.org/grpc/clientconn.go:547 +0x1d3
		google.golang.org/grpc.NewConn.func1(0xc82089e000)
			/go/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
		created by google.golang.org/grpc.NewConn
			/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3
	leaktest.go:86: Leaked goroutine: goroutine 3056 [select]:
		google.golang.org/grpc/transport.(*http2Server).controller(0xc820096360)
			/go/src/google.golang.org/grpc/transport/http2_server.go:660 +0x5da
		created by google.golang.org/grpc/transport.newHTTP2Server
			/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x84f
	leaktest.go:86: Leaked goroutine: goroutine 3057 [IO wait]:
		net.runtime_pollWait(0x7f1cfbe48ee8, 0x72, 0xc820186800)
			/usr/local/go/src/runtime/netpoll.go:160 +0x60
		net.(*pollDesc).Wait(0xc8206281b0, 0x72, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
		net.(*pollDesc).WaitRead(0xc8206281b0, 0x0, 0x0)
			/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
		net.(*netFD).Read(0xc820628150, 0xc820186800, 0x400, 0x400, 0x0, 0x7f1cfbe39050, 0xc82000e068)
			/usr/local/go/src/net/fd_unix.go:250 +0x23a
		net.(*conn).Read(0xc82017c010, 0xc820186800, 0x400, 0x400, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/net.go:172 +0xe4
		crypto/tls.(*block).readFromUntil(0xc8205fa2d0, 0x7f1cfbd7e710, 0xc82017c010, 0x5, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
		crypto/tls.(*Conn).readRecord(0xc820204300, 0x1e4cc17, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
		crypto/tls.(*Conn).Read(0xc820204300, 0xc820808000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:939 +0x167
		bufio.(*Reader).fill(0xc820626960)
			/usr/local/go/src/bufio/bufio.go:97 +0x1e9
		bufio.(*Reader).Read(0xc820626960, 0xc8204056b8, 0x9, 0x9, 0x9, 0x0, 0x0)
			/usr/local/go/src/bufio/bufio.go:207 +0x260
		io.ReadAtLeast(0x7f1cfbd7ee28, 0xc820626960, 0xc8204056b8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
			/usr/local/go/src/io/io.go:297 +0xe6
		io.ReadFull(0x7f1cfbd7ee28, 0xc820626960, 0xc8204056b8, 0x9, 0x9, 0x46e9fea829ac8f01, 0x0, 0x0)
			/usr/local/go/src/io/io.go:315 +0x62
		golang.org/x/net/http2.readFrameHeader(0xc8204056b8, 0x9, 0x9, 0x7f1cfbd7ee28, 0xc820626960, 0xfb000000, 0xc800000000, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
		golang.org/x/net/http2.(*Framer).ReadFrame(0xc820405680, 0x0, 0x0, 0x0, 0x0)
			/go/src/golang.org/x/net/http2/frame.go:464 +0x106
		google.golang.org/grpc/transport.(*framer).readFrame(0xc8215c4ff0, 0x0, 0x0, 0x0, 0x0)
			/go/src/google.golang.org/grpc/transport/http_util.go:417 +0x3d
		google.golang.org/grpc/transport.(*http2Client).reader(0xc8204cb1d0)
			/go/src/google.golang.org/grpc/transport/http2_client.go:795 +0x109
		created by google.golang.org/grpc/transport.newHTTP2Client
			/go/src/google.golang.org/grpc/transport/http2_client.go:174 +0xd21
	leaktest.go:86: Leaked goroutine: goroutine 3090 [select]:
		google.golang.org/grpc/transport.(*http2Client).controller(0xc8204cb1d0)
			/go/src/google.golang.org/grpc/transport/http2_client.go:873 +0x5da
		created by google.golang.org/grpc/transport.newHTTP2Client
			/go/src/google.golang.org/grpc/transport/http2_client.go:201 +0x15c2
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
0 runs so far, 0 failures, over 35s
0 runs so far, 0 failures, over 40s
0 runs so far, 0 failures, over 45s
15 runs so far, 0 failures, over 50s
16 runs so far, 0 failures, over 55s
16 runs so far, 0 failures, over 1m0s
16 runs so far, 0 failures, over 1m5s
16 runs so far, 0 failures, over 1m10s
16 runs so far, 0 failures, over 1m15s
16 runs so far, 0 failures, over 1m20s
16 runs so far, 0 failures, over 1m25s
16 runs so far, 0 failures, over 1m30s
24 runs so far, 0 failures, over 1m35s
31 runs so far, 0 failures, over 1m40s
32 runs so far, 0 failures, over 1m45s
32 runs so far, 0 failures, over 1m50s
32 runs so far, 0 failures, over 1m55s
32 runs so far, 0 failures, over 2m0s
32 runs so far, 0 failures, over 2m5s
32 runs so far, 0 failures, over 2m10s
32 runs so far, 0 failures, over 2m15s
37 runs so far, 0 failures, over 2m20s
45 runs so far, 0 failures, over 2m25s
48 runs so far, 0 failures, over 2m30s
48 runs so far, 0 failures, over 2m35s
48 runs so far, 0 failures, over 2m40s
48 runs so far, 0 failures, over 2m45s
48 runs so far, 0 failures, over 2m50s
48 runs so far, 0 failures, over 2m55s
48 runs so far, 0 failures, over 3m0s
49 runs so far, 0 failures, over 3m5s
57 runs so far, 0 failures, over 3m10s
63 runs so far, 0 failures, over 3m15s
64 runs so far, 0 failures, over 3m20s
64 runs so far, 0 failures, over 3m25s
64 runs so far, 0 failures, over 3m30s
64 runs so far, 0 failures, over 3m35s
64 runs so far, 0 failures, over 3m40s
64 runs so far, 0 failures, over 3m45s
65 runs so far, 0 failures, over 3m50s
68 runs so far, 0 failures, over 3m55s
78 runs so far, 0 failures, over 4m0s
80 runs so far, 0 failures, over 4m5s
80 runs so far, 0 failures, over 4m10s
80 runs so far, 0 failures, over 4m15s
80 runs so far, 0 failures, over 4m20s
80 runs so far, 0 failures, over 4m25s
80 runs so far, 0 failures, over 4m30s
80 runs so far, 0 failures, over 4m35s
81 runs so far, 0 failures, over 4m40s
88 runs so far, 0 failures, over 4m45s
96 runs so far, 0 failures, over 4m50s
96 runs so far, 0 failures, over 4m55s
96 runs so far, 0 failures, over 5m0s
96 runs so far, 0 failures, over 5m5s
96 runs so far, 0 failures, over 5m10s
96 runs so far, 0 failures, over 5m15s
96 runs so far, 0 failures, over 5m20s
96 runs so far, 0 failures, over 5m25s
101 runs so far, 0 failures, over 5m30s
110 runs so far, 0 failures, over 5m35s
112 runs so far, 0 failures, over 5m40s
112 runs so far, 0 failures, over 5m45s
112 runs so far, 0 failures, over 5m50s
112 runs so far, 0 failures, over 5m55s
112 runs so far, 0 failures, over 6m0s
112 runs so far, 0 failures, over 6m5s
112 runs so far, 0 failures, over 6m10s
115 runs so far, 0 failures, over 6m15s
123 runs so far, 0 failures, over 6m20s
127 runs so far, 0 failures, over 6m25s
128 runs so far, 0 failures, over 6m30s
128 runs so far, 0 failures, over 6m35s
128 runs so far, 0 failures, over 6m40s
128 runs so far, 0 failures, over 6m45s
128 runs so far, 0 failures, over 6m50s
129 runs so far, 0 failures, over 6m55s
129 runs so far, 0 failures, over 7m0s
134 runs so far, 0 failures, over 7m5s
141 runs so far, 0 failures, over 7m10s
144 runs so far, 0 failures, over 7m15s
144 runs so far, 0 failures, over 7m20s
144 runs so far, 0 failures, over 7m25s
144 runs so far, 0 failures, over 7m30s
144 runs so far, 0 failures, over 7m35s
144 runs so far, 0 failures, over 7m40s
145 runs so far, 0 failures, over 7m45s
148 runs so far, 0 failures, over 7m50s
155 runs so far, 0 failures, over 7m55s
159 runs so far, 0 failures, over 8m0s
160 runs so far, 0 failures, over 8m5s
160 runs so far, 0 failures, over 8m10s
160 runs so far, 0 failures, over 8m15s
160 runs so far, 0 failures, over 8m20s
160 runs so far, 0 failures, over 8m25s
161 runs so far, 0 failures, over 8m30s
164 runs so far, 0 failures, over 8m35s
168 runs so far, 0 failures, over 8m40s
173 runs so far, 0 failures, over 8m45s
176 runs so far, 0 failures, over 8m50s
176 runs so far, 0 failures, over 8m55s
176 runs so far, 0 failures, over 9m0s
176 runs so far, 0 failures, over 9m5s
176 runs so far, 0 failures, over 9m10s
176 runs so far, 0 failures, over 9m15s
180 runs so far, 0 failures, over 9m20s
182 runs so far, 0 failures, over 9m25s
186 runs so far, 0 failures, over 9m30s
191 runs so far, 0 failures, over 9m35s
192 runs so far, 0 failures, over 9m40s
192 runs so far, 0 failures, over 9m45s
192 runs so far, 0 failures, over 9m50s
192 runs so far, 0 failures, over 9m55s
192 runs so far, 0 failures, over 10m0s
195 runs so far, 0 failures, over 10m5s
197 runs so far, 0 failures, over 10m10s
201 runs so far, 0 failures, over 10m15s
205 runs so far, 0 failures, over 10m20s
207 runs so far, 0 failures, over 10m25s
207 runs so far, 0 failures, over 10m30s
208 runs so far, 0 failures, over 10m35s
208 runs so far, 0 failures, over 10m40s
208 runs so far, 0 failures, over 10m45s
209 runs so far, 0 failures, over 10m50s
213 runs so far, 0 failures, over 10m55s
216 runs so far, 0 failures, over 11m0s
220 runs so far, 0 failures, over 11m5s
223 runs so far, 0 failures, over 11m10s
223 runs so far, 0 failures, over 11m15s
224 runs so far, 0 failures, over 11m20s
224 runs so far, 0 failures, over 11m25s
224 runs so far, 0 failures, over 11m30s
225 runs so far, 0 failures, over 11m35s
228 runs so far, 0 failures, over 11m40s
230 runs so far, 0 failures, over 11m45s
234 runs so far, 0 failures, over 11m50s
238 runs so far, 0 failures, over 11m55s
239 runs so far, 0 failures, over 12m0s
240 runs so far, 0 failures, over 12m5s
240 runs so far, 0 failures, over 12m10s
240 runs so far, 0 failures, over 12m15s
241 runs so far, 0 failures, over 12m20s
242 runs so far, 0 failures, over 12m25s
246 runs completed, 1 failures, over 12m29s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Fixed in #7241.
