### ISSUE TITLE
stability: OOM in receiving raft message

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#7184]
`beta` cluster running c17928f

node 2 (`104.196.0.165`) was killed by the OOM killer.

Logs show a ~5GB memory increase in Go over the span of a minute:

```
I160610 12:53:05.842280 server/status/runtime.go:187  runtime stats: 8.4 GiB RSS, 188 goroutines, 210 MiB/181 MiB/483 MiB GO alloc/idle/total, 6.0 GiB/7.1 GiB CGO alloc/total, 99120.17cgo/sec, 2.09/0.37 %(u/s)time, 0.00 %gc (11x)
I160610 12:53:15.842709 server/status/runtime.go:187  runtime stats: 8.5 GiB RSS, 187 goroutines, 179 MiB/474 MiB/760 MiB GO alloc/idle/total, 6.0 GiB/7.1 GiB CGO alloc/total, 86458.08cgo/sec, 2.19/0.39 %(u/s)time, 0.01 %gc (12x)
I160610 12:53:26.396601 server/status/runtime.go:187  runtime stats: 12 GiB RSS, 200 goroutines, 3.3 GiB/919 MiB/4.4 GiB GO alloc/idle/total, 6.0 GiB/7.1 GiB CGO alloc/total, 44454.67cgo/sec, 1.56/0.78 %(u/s)time, 0.48 %gc (7x)
I160610 12:53:35.843805 server/status/runtime.go:187  runtime stats: 12 GiB RSS, 191 goroutines, 4.4 GiB/536 KiB/4.5 GiB GO alloc/idle/total, 6.0 GiB/7.1 GiB CGO alloc/total, 61107.71cgo/sec, 1.20/0.44 %(u/s)time, 0.00 %gc (1x)
I160610 12:53:45.843410 server/status/runtime.go:187  runtime stats: 13 GiB RSS, 189 goroutines, 4.8 GiB/416 MiB/5.4 GiB GO alloc/idle/total, 6.0 GiB/7.2 GiB CGO alloc/total, 46877.51cgo/sec, 1.04/0.51 %(u/s)time, 0.00 %gc (1x)
I160610 12:53:55.861760 server/status/runtime.go:187  runtime stats: 14 GiB RSS, 212 goroutines, 3.5 GiB/2.4 GiB/6.1 GiB GO alloc/idle/total, 6.0 GiB/7.1 GiB CGO alloc/total, 35444.66cgo/sec, 1.64/0.69 %(u/s)time, 0.00 %gc (1x)
I160610 12:54:05.844682 server/status/runtime.go:187  runtime stats: 14 GiB RSS, 189 goroutines, 4.1 GiB/1.8 GiB/6.1 GiB GO alloc/idle/total, 6.0 GiB/7.1 GiB CGO alloc/total, 32914.19cgo/sec, 0.89/0.33 %(u/s)time, 0.00 %gc (0x)
I160610 12:54:15.845297 server/status/runtime.go:187  runtime stats: 14 GiB RSS, 196 goroutines, 5.3 GiB/607 MiB/6.1 GiB GO alloc/idle/total, 6.0 GiB/7.1 GiB CGO alloc/total, 73930.84cgo/sec, 1.09/0.38 %(u/s)time, 0.00 %gc (0x)
```

Nothing particularly suspicious, but this is the receiver, so I don't expect much logging:

```
I160610 12:53:05.842280 server/status/runtime.go:187  runtime stats: 8.4 GiB RSS, 188 goroutines, 210 MiB/181 MiB/483 MiB GO alloc/idle/total, 6.0 GiB/7.1 GiB CGO alloc/total, 99120.17cgo/sec, 2.09/0.37 %(u/s)time, 0.00 %gc (11x)
I160610 12:53:06.864106 storage/replica_command.go:1530  range 3832: new leader lease replica {2 2 2} 1970-01-01 00:00:00 +0000 UTC 407100h53m11.609192255s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 12:53:06.864005708 +0000 UTC]
I160610 12:53:07.478891 storage/replica_command.go:1530  range 3804: new leader lease replica {2 2 2} 2016-06-10 12:51:28.395239079 +0000 UTC 1m43.706840063s following replica {6 6 3} 2016-06-10 12:50:39.075091015 +0000 UTC 49.320148064s [physicalTime=2016-06-10 12:53:07.478824609 +0000 UTC]
I160610 12:53:07.923123 storage/replica_command.go:1530  range 3813: new leader lease replica {2 2 2} 2016-06-10 12:52:51.669391886 +0000 UTC 20.942843485s following replica {3 3 3} 2016-06-10 12:52:36.011554913 +0000 UTC 15.657836973s [physicalTime=2016-06-10 12:53:07.923075273 +0000 UTC]
I160610 12:53:09.014703 storage/replica_command.go:1537  range 3702: replicaID 2 transfer raft leadership to replicaID 3
I160610 12:53:09.901665 storage/replica_command.go:1537  range 3710: replicaID 2 transfer raft leadership to replicaID 1
I160610 12:53:10.409564 storage/replica_command.go:1537  range 3863: replicaID 2 transfer raft leadership to replicaID 3
I160610 12:53:12.817042 storage/replica_raftstorage.go:552  generated snapshot for range 2482 at index 2557 in 652.054017ms. encoded size=35375158, 88144 KV pairs, 87 log entries
I160610 12:53:15.325325 storage/replica_command.go:1537  range 3868: replicaID 3 transfer raft leadership to replicaID 1
I160610 12:53:15.842142 server/status/runtime_jemalloc.go:102  jemalloc stats: allocated: 6.0 GiB, active: 6.3 GiB, metadata: 161 MiB, resident: 7.1 GiB, mapped: 8.6 GiB
I160610 12:53:15.842709 server/status/runtime.go:187  runtime stats: 8.5 GiB RSS, 187 goroutines, 179 MiB/474 MiB/760 MiB GO alloc/idle/total, 6.0 GiB/7.1 GiB CGO alloc/total, 86458.08cgo/sec, 2.19/0.39 %(u/s)time, 0.01 %gc (12x)
I160610 12:53:16.418353 storage/replica_command.go:1530  range 3777: new leader lease replica {2 2 2} 2016-06-10 12:53:03.378745087 +0000 UTC 17.786484593s following replica {4 4 1} 2016-06-10 12:52:23.719545772 +0000 UTC 39.659199315s [physicalTime=2016-06-10 12:53:16.418285188 +0000 UTC]
I160610 12:53:16.839053 storage/replica_command.go:1530  range 2482: new leader lease replica {2 2 5} 2016-06-10 12:53:16.08025054 +0000 UTC 5.505696656s following replica {3 3 1} 2016-06-10 09:46:16.230096714 +0000 UTC 3h6m59.850153826s [physicalTime=2016-06-10 12:53:16.838984936 +0000 UTC]
I160610 12:53:17.530877 storage/replica_command.go:1530  range 2142: new leader lease replica {2 2 2} 2016-06-10 12:53:11.704455919 +0000 UTC 10.260887837s following replica {1 1 1} 2016-06-10 12:52:45.743780355 +0000 UTC 25.960675564s [physicalTime=2016-06-10 12:53:17.530762487 +0000 UTC]
I160610 12:53:17.768081 storage/replica_command.go:1530  range 3725: new leader lease replica {2 2 2} 2016-06-10 12:53:11.974713467 +0000 UTC 10.513514393s following replica {6 6 1} 2016-06-10 12:51:35.876578455 +0000 UTC 1m36.098135012s [physicalTime=2016-06-10 12:53:17.768028393 +0000 UTC]
I160610 12:53:17.788946 storage/replica_command.go:1537  range 3804: replicaID 2 transfer raft leadership to replicaID 3
I160610 12:53:18.278074 storage/replica_raftstorage.go:646  replica 7 received snapshot for range 1269 at index 77503. encoded size=34926117, 86802 KV pairs, 84 log entries
I160610 12:53:18.598957 storage/replica_raftstorage.go:648  replica 7 applied snapshot for range 1269 in 319.308384ms
W160610 12:53:19.943574 raft/raft.go:593  [group 848] 2 stepped down to follower since quorum is not active
I160610 12:53:26.395954 server/status/runtime_jemalloc.go:102  jemalloc stats: allocated: 6.0 GiB, active: 6.3 GiB, metadata: 162 MiB, resident: 7.1 GiB, mapped: 8.6 GiB
I160610 12:53:26.396601 server/status/runtime.go:187  runtime stats: 12 GiB RSS, 200 goroutines, 3.3 GiB/919 MiB/4.4 GiB GO alloc/idle/total, 6.0 GiB/7.1 GiB CGO alloc/total, 44454.67cgo/sec, 1.56/0.78 %(u/s)time, 0.48 %gc (7x)
```

Heap profile shows all the usage in `grpc.(*parser).recvMsg`, with caller `storage.(*multiRaftRaftMessageServer).Recv`.

It's unclear exactly what the data is for. Heap `inuse-objects` shows only 2 in that trace, one at 3.1GB, the other at 33MB, both coming through multiraft: [node1.go.heap.inuse-objects.pdf](https://github.com/cockroachdb/cockroach/files/311814/node1.go.heap.inuse-objects.pdf)

Heap profile:  [node1.go.heap.pdf](https://github.com/cockroachdb/cockroach/files/311799/node1.go.heap.pdf)
Diff between 12:53:02 and 12:54:12: [node1.go.heap.diff.pdf](https://github.com/cockroachdb/cockroach/files/311800/node1.go.heap.diff.pdf)
Focus on recvMsg: [node1.go.focus-recvmsg.pdf](https://github.com/cockroachdb/cockroach/files/311801/node1.go.focus-recvmsg.pdf)

Latest log: [node1.stderr.gz](https://github.com/cockroachdb/cockroach/files/311808/node1.stderr.gz)
Latest goroutines: [node1.goroutines.txt](https://github.com/cockroachdb/cockroach/files/311809/node1.goroutines.txt)

**Comment by mberhault** [comment]
`logs/` directory (which includes go/cgo heap and goroutine profiles) backed up on every machine to `~/logs.7184`

**Comment by mberhault** [comment]
btw: rolling back `gamma` nodes to 093e1e3 crashed two of them with:
```
F160613 16:02:44.438105 storage/store.go:2186  store=5:5 ([]=/mnt/data) replicaDescCache: clobbering {6 6 5} with {2 2 5}
goroutine 104 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xecef0d001, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:862 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x2879de0, 0x3, 0x228d6f3, 0x10, 0x88a, 0xc8249602d0, 0x4a)
        /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:728 +0x9c5
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0xc800000003, 0x2, 0x1b617a0, 0x2a, 0xc822f7b980, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0xc800000003, 0x1b617a0, 0x2a, 0xc822f7b980, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x1b617a0, 0x2a, 0xc822f7b980, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x66
github.com/cockroachdb/cockroach/storage.(*Store).cacheReplicaDescriptorLocked(0xc82018e280, 0xe53, 0x200000002, 0xc800000005)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2186 +0x288
github.com/cockroachdb/cockroach/storage.(*Store).handleRaftMessage(0xc82018e280, 0xc8243dc7e0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:1985 +0x4e5
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2066 +0x552
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820343570, 0xc82139cbb0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

**Comment by bdarnell** [comment]
From the saved logs, it looks like all the snapshots we're generating are about 33MB, so the huge one must not be a snapshot. All the other raft messages are supposed to be limited in size to 1MB (or one log entry, whichever is larger); I'm looking for places where it might exceed that.

**Comment by mberhault** [comment]
do we have a good vmodule setting to use to gain a bit more visibility? Something along the lines of logging for each beginning/end of potentially sizable operations would be good. Still not insanely verbose though.
I'm happy to increase the number of log files we keep.

**Comment by bdarnell** [comment]
We don't have a good vmodule setting currently. It would be trivial to add a log entry for any large raft message. Is the OOM reproducible if you restart the nodes or does the clobbering issue get in the way?

**Comment by mberhault** [comment]
`beta` has been happy since I restarted that node. To clarify, the clobbering issues were only on gamma, my previous update here mentioning them was a mispost

**Comment by mberhault** [comment]
way old. closing.
