### ISSUE TITLE
circleci: failed tests: TestSchemaChangeLease 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7193]
The following test appears to have failed:

[#19021](https://circleci.com/gh/cockroachdb/cockroach/19021):

```
I160613 20:13:47.669315 kv/dist_sender.go:983  application error: storage/replica_command.go:2132: split at key /Table/51 failed: node unavailable; try another peer
W160613 20:13:47.669477 kv/dist_sender.go:728  failed to invoke AdminSplit [/Table/51/0,/Min): storage/replica_command.go:2132: split at key /Table/51 failed: node unavailable; try another peer
I160613 20:13:47.669648 client/db.go:474  failed batch: storage/replica_command.go:2132: split at key /Table/51 failed: node unavailable; try another peer
E160613 20:13:47.669981 storage/queue.go:449  [split] range=6 [/Table/50-/Max): error: storage/split_queue.go:99: unable to split range=6 [/Table/50-/Max) at key "/Table/51/0": storage/replica_command.go:2132: split at key /Table/51 failed: node unavailable; try another peer
I160613 20:13:47.671497 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- FAIL: TestSchemaChangeLease (6.02s)
	<autogenerated>:31: Leaked goroutine: goroutine 13073 [select]:
		google.golang.org/grpc/transport.(*http2Server).controller(0xc8204b8fc0)
			/go/src/google.golang.org/grpc/transport/http2_server.go:660 +0x8e3
		created by google.golang.org/grpc/transport.newHTTP2Server
			/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0xb6d
	<autogenerated>:31: Leaked goroutine: goroutine 13084 [select]:
		google.golang.org/grpc.(*Conn).transportMonitor(0xc8205842d0)
			/go/src/google.golang.org/grpc/clientconn.go:547 +0x252
		google.golang.org/grpc.NewConn.func1(0xc8205842d0)
			/go/src/google.golang.org/grpc/clientconn.go:355 +0x1fc
--
E160613 20:14:23.327228 client/txn.go:370  failure aborting transaction: testError; abort caused by: testError
I160613 20:14:23.327882 stopper.go:352  draining; tasks left:
1      kv/txn_coord_sender.go:870
I160613 20:14:23.329975 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestNonRetryableErrorFromCommit (0.35s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	149.230s
I160613 20:12:07.734725 rand.go:76  Random seed: 6251425159758707349
=== RUN   TestProcessExpression
--- PASS: TestProcessExpression (0.01s)
=== RUN   TestJoinReader
I160613 20:12:07.763228 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160613 20:12:07.785838 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160613 20:12:07.804474 server/node.go:401  store store=0:0 ([]=) not bootstrapped
W160613 20:12:07.805141 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160613 20:12:07.816005 storage/replica_command.go:1531  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407180h12m12.313820833s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-13 20:12:07.815695015 +0000 UTC]
I160613 20:12:07.818772 server/node.go:327  **** cluster {ccb58706-f900-469c-9729-a81c4e21fe0f} has been created

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
#7168.
