### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestTxnRestartedSerializableTimestampRegression

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#7208]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/d9039b883cc2c9190448216f57ccfe4676d4e7e1

Stress build found a failed test:

```
=== RUN   TestTxnRestartedSerializableTimestampRegression
W160614 04:33:54.756873 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160614 04:33:54.756933 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160614 04:33:54.759327 storage/replica_command.go:1531  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900ms following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00 +0000 UTC]
E160614 04:33:54.760333 config/config.go:382  unable to determine largest reserved object ID from system config: descriptor table not found in system config of 0 values
I160614 04:33:54.763467 stopper.go:352  draining; tasks left:
1      kv/txn_coord_sender.go:870
--- FAIL: TestTxnRestartedSerializableTimestampRegression (5.05s)
	leaktest.go:86: Leaked goroutine: goroutine 6469 [select]:
		github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
			/go/src/github.com/cockroachdb/cockroach/storage/store.go:2101 +0xbf1
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8208d84d0, 0xc8205dece0)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
3 runs so far, 0 failures, over 20s
13 runs so far, 0 failures, over 25s
16 runs so far, 0 failures, over 30s
17 runs so far, 0 failures, over 35s
19 runs so far, 0 failures, over 40s
23 runs so far, 0 failures, over 45s
29 runs so far, 0 failures, over 50s
32 runs so far, 0 failures, over 55s
35 runs so far, 0 failures, over 1m0s
38 runs so far, 0 failures, over 1m5s
44 runs so far, 0 failures, over 1m10s
48 runs so far, 0 failures, over 1m15s
49 runs so far, 0 failures, over 1m20s
51 runs so far, 0 failures, over 1m25s
57 runs so far, 0 failures, over 1m30s
62 runs so far, 0 failures, over 1m35s
64 runs so far, 0 failures, over 1m40s
66 runs so far, 0 failures, over 1m45s
70 runs so far, 0 failures, over 1m50s
77 runs so far, 0 failures, over 1m55s
79 runs so far, 0 failures, over 2m0s
81 runs so far, 0 failures, over 2m5s
85 runs so far, 0 failures, over 2m10s
90 runs so far, 0 failures, over 2m15s
94 runs so far, 0 failures, over 2m20s
96 runs so far, 0 failures, over 2m25s
98 runs so far, 0 failures, over 2m30s
101 runs so far, 0 failures, over 2m35s
108 runs so far, 0 failures, over 2m40s
110 runs completed, 1 failures, over 2m42s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by vivekmenezes** [comment]
same as #7236
