### ISSUE TITLE
cli: PGHOSTADDR causes panic

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#72936]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

Trying to disable DNS lookup on connection. Enabled `PGHOSTADDR` env variable and tried to connect

```bash
export PGHOSTADDR=172.28.0.6
```

```bash
[root@client ~]# cockroach sql  --certs-dir=/certs --url  "postgresql://tester:nopassword@lb:26257/defaultdb?sslmode=verify-full&sslrootcert=/certs/ca.crt&krbsrvname=customspn"
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1  a panic has occurred!
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +panic: setting PGHOSTADDR not supported
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +(1) attached stack trace
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  -- stack trace:
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/lib/pq.parseEnviron
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1975
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/lib/pq.NewConnector
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/connector.go:56
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli/clisqlclient.(*sqlConn).EnsureConn
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlclient/conn.go:145
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg.(*Context).Run
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg/context.go:190
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.runTerm
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_shell_cmd.go:63
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:67
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/spf13/cobra.(*Command).execute
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/spf13/cobra.(*Command).ExecuteC
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/spf13/cobra.(*Command).Execute
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.Run
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:283
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.doMain
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:130
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.Main
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:59
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | main.main
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:26
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | runtime.main
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /usr/local/go/src/runtime/proc.go:225
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | runtime.goexit
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /usr/local/go/src/runtime/asm_amd64.s:1371
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +Wraps: (2) panic: setting PGHOSTADDR not supported
E211118 18:58:59.307815 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +Error types: (1) *withstack.withStack (2) *errutil.leafError
panic: setting PGHOSTADDR not supported [recovered]
        panic: setting PGHOSTADDR not supported

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.RecoverAndReportPanic(0x8c19420, 0xc0000760a0, 0xc000b96000)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:90 +0xa5
panic(0x497cbc0, 0xc00065a4f0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/lib/pq.parseEnviron.func2(...)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1962
github.com/lib/pq.parseEnviron(0xc000b3f860, 0xf, 0xf, 0xc000f85920)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1975 +0x130d
github.com/lib/pq.NewConnector(0xc000153290, 0xae, 0x7f303a8e2a08, 0xc8, 0xc8)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/connector.go:56 +0x145
github.com/cockroachdb/cockroach/pkg/cli/clisqlclient.(*sqlConn).EnsureConn(0xc000dc6750, 0x10, 0xc00065a4d0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlclient/conn.go:145 +0x8d
github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg.(*Context).Run(0xc000b8eb60, 0x8d54508, 0xc000dc6750, 0x8d54508, 0xc000dc6750)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg/context.go:190 +0x62
github.com/cockroachdb/cockroach/pkg/cli.runTerm(0xb24a660, 0xc000f85020, 0x0, 0x3, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_shell_cmd.go:63 +0x174
github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1(0xb24a660, 0xc000f85020, 0x0, 0x3, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:67 +0x79
github.com/spf13/cobra.(*Command).execute(0xb24a660, 0xc000f84ff0, 0x3, 0x3, 0xb24a660, 0xc000f84ff0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xb246a60, 0xc0000760a0, 0xc000bebf8a, 0x3)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:283
github.com/cockroachdb/cockroach/pkg/cli.doMain(0xb24a660, 0xc000bebf8a, 0x3, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:130 +0x11a
github.com/cockroachdb/cockroach/pkg/cli.Main()
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:59 +0x13a
main.main()
        /go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:26 +0x25
```

**Expected behavior**
based on @rafiss search, libpq ignores the variable https://github.com/lib/pq/blob/8446d16b8935fdf2b5c0fe333538ac395e3e1e4b/conn.go#L1997-L1998
We should at the minimum do a no-op but not cause panic.

**Environment:**
 - CockroachDB version 21.2.0
 - Server OS: CockroachDB 21.2.0 Docker image (UBI8) RHEL 8
 - Client app: `cockroach sql`

**Additional context**

Also tested on OSX with `cockroach demo` and it is the same result

```bash
cockroach sql --url "postgresql://demo:demo35293@127.0.0.1:26257/movr?sslmode=require" --insecure
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1  a panic has occurred!
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +panic: setting PGHOSTADDR not supported
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +(1) attached stack trace
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  -- stack trace:
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/lib/pq.parseEnviron
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1975
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/lib/pq.NewConnector
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/connector.go:56
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli/clisqlclient.(*sqlConn).EnsureConn
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlclient/conn.go:145
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg.(*Context).Run
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg/context.go:190
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.runTerm
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_shell_cmd.go:63
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:67
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/spf13/cobra.(*Command).execute
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/spf13/cobra.(*Command).ExecuteC
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/spf13/cobra.(*Command).Execute
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.Run
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:283
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.doMain
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:130
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | github.com/cockroachdb/cockroach/pkg/cli.Main
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:59
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | main.main
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:26
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | runtime.main
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /usr/local/go/src/runtime/proc.go:225
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  | runtime.goexit
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +  |        /usr/local/go/src/runtime/asm_amd64.s:1371
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +Wraps: (2) panic: setting PGHOSTADDR not supported
E211118 19:40:47.804573 1 1@util/log/logcrash/crash_reporting.go:140  [-] 1 +Error types: (1) *withstack.withStack (2) *errutil.leafError
panic: setting PGHOSTADDR not supported [recovered]
        panic: setting PGHOSTADDR not supported

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.RecoverAndReportPanic(0xc6f5380, 0xc000138008, 0xc00090e000)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:90 +0xa5
panic(0x8459f20, 0xc0009e6410)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/lib/pq.parseEnviron.func2(...)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1962
github.com/lib/pq.parseEnviron(0xc000d95600, 0x2b, 0x2b, 0xc00079fdd0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1975 +0x130d
github.com/lib/pq.NewConnector(0xc00050b900, 0x6c, 0x16a815d0, 0xc8, 0xc8)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/connector.go:56 +0x145
github.com/cockroachdb/cockroach/pkg/cli/clisqlclient.(*sqlConn).EnsureConn(0xc000af75f0, 0x10, 0xc0009e63f0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlclient/conn.go:145 +0x8d
github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg.(*Context).Run(0xc0005a3ad0, 0xc830568, 0xc000af75f0, 0xc830568, 0xc000af75f0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg/context.go:190 +0x62
github.com/cockroachdb/cockroach/pkg/cli.runTerm(0xedd43a0, 0xc000cc8060, 0x0, 0x3, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_shell_cmd.go:63 +0x174
github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1(0xedd43a0, 0xc000cc8060, 0x0, 0x3, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:67 +0x79
github.com/spf13/cobra.(*Command).execute(0xedd43a0, 0xc000ffdec0, 0x3, 0x3, 0xedd43a0, 0xc000ffdec0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xedd07a0, 0xc000138008, 0xc00094e77a, 0x3)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:283
github.com/cockroachdb/cockroach/pkg/cli.doMain(0xedd43a0, 0xc00094e77a, 0x3, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:130 +0x11a
github.com/cockroachdb/cockroach/pkg/cli.Main()
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:59 +0x13a
main.main()
        /go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:26 +0x25
```

**Comment by knz** [comment]
in case it wsn't clear, the workaround is to disable the environment variable.

**Comment by rafiss** [comment]
also, if you `export PGHOST=172.28.0.6` instead of `PGHOSTADDR` you'd still avoid the DNS lookups
