### ISSUE TITLE
sqllitelogic tests crash on some batch sizes

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#73162]
**Describe the problem**

I ran the sql lite logic tests locally without the crdb_test_off tag set and hit the following error. We originally turned off batch size randomization in https://github.com/cockroachdb/cockroach/pull/59277 because of test timeouts.

```
--- progress: /Users/ssd/go/src/github.com/cockroachdb/sqllogictest/test/index/delete/10/slt_good_1.test: 234 statements/queries
 batch with MaxSpanRequestKeys=0, TargetBytes=10485760 needs splitting
!goroutine 29682 [running]:
!github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x8a
!github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000c46d20, {{{0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0}, 0x16bad328ed72dcc8, 0x0, 0x4, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:306 +0xb8
!github.com/cockroachdb/cockroach/pkg/util/log.logfDepth({0x8ce66b0, 0xc00ebead40}, 0x1, 0x4, 0x0, {0x799ff25, 0x40}, {0xc0205e3470, 0x2, 0x2})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:60 +0x385
!github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:834
!github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send(0xc002fb4000, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:771 +0x39e
!github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnLockGatekeeper).SendLocked(0xc044186958, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go:82 +0x291
!github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnMetricRecorder).SendLocked(0xc044186920, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go:46 +0x138
!github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked(0xc0441868f0, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:128 +0x725
!github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts(0xc044186850, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...}, ...)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:240 +0x258
!github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked(0xc044186850, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:175 +0x34b
!github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked(0xc044186780, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go:285 +0x30b
!github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked(0xc044186760, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:105 +0xb5
!github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked(0xc0441866c0, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:241 +0x4f0
!github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send(0xc044186500, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:514 +0x587
!github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender(0xc000e6d880, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...}, ...)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:860 +0x155
!github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send(0xc025cdb130, {0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, ...}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:1065 +0x236
!github.com/cockroachdb/cockroach/pkg/sql/row.makeKVBatchFetcherDefaultSendFunc.func1({0x8ce66b0, 0xc00ebead40}, {{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0, 0x0}, ...}, ...})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:182 +0x85
!github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVFetcher).fetch(0xc0109eb1d0, {0x8ce66b0, 0xc00ebead40})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:419 +0x705
!github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVFetcher).nextBatch(0xc0109eb1d0, {0x8ce66b0, 0xc00ebead40})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:576 +0x925
!github.com/cockroachdb/cockroach/pkg/sql/row.(*KVFetcher).NextKV(0xc037264a50, {0x8ce66b0, 0xc00ebead40}, 0x0)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/kv_fetcher.go:192 +0xeb
!github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).NextBatch(0xc00e8a4a80, {0x8ce66b0, 0xc00ebead40})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:765 +0xc6
!github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColBatchScan).Next(0xc03f0c75e0)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/colfetcher/colbatch_scan.go:109 +0x30
!github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Next(0xc00ebead80)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:94 +0x4c
!github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next(0xc00ebeadc0)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59 +0x30
!github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Next(0xc00ebeae00)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:94 +0x4c
!github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter(...)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:240
!github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0x8ce66b0)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91 +0x62
!github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next(...)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:244
!github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run(0xc025cdb290, {0x8ce66b0, 0xc00ebead40})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:283 +0x373
!github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run(0xc01adddf40, {0x8ce66b0, 0xc00ebead40}, 0xc025cdb130)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:259 +0x1d9
!github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0070ae100, 0xc0109eae10, 0xc025cdb130, 0xc04635f500, 0xc03ee54000, 0xc0054181c8, 0x0)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:537 +0xc31
!github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0x8ce6758, {0x8ce6758, 0xc0159650b0}, 0xc005417f28, 0xc0109eae10, 0xc01331f128, {{0x8ce8400, 0xc00f176120}, 0x0}, 0xc03ee54000)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1352 +0x191
!github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc005417900, {0x8ce6758, 0xc0159650b0}, 0xc005417f28, 0xc0159650b0, {0x377abde0, 0xc01331f128}, 0x0, 0xc0439ed198)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1385 +0x5f4
!github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc005417900, {0x8ce6758, 0xc0159650b0}, 0xc005417f28, {0x377abde0, 0xc01331f128})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1062 +0x991
!github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc005417900, {0x8ce6758, 0xc0159650b0}, {{0x8d131f8, 0xc03225bd60}, {0xc02b1ab54b, 0x53}, 0x0, 0x1}, 0x0, ...)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:700 +0x248e
!github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc005417900, {0x8ce66b0, 0xc00ebeab40}, {{0x8d131f8, 0xc03225bd60}, {0xc02b1ab54b, 0x53}, 0x0, 0x1}, 0x0, ...)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129 +0x565
!github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1({{{0x8d131f8, 0xc03225bd60}, {0xc02b1ab54b, 0x53}, 0x0, 0x1}, {0xe306e58, 0xed931a093, 0x0}, {0xe307240, ...}, ...}, ...)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1752 +0x28d
!github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc005417900, {0x8ce66b0, 0xc00ebeab40})
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1754 +0xbf0
!github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc005417900, {0x8ce66b0, 0xc0180fb440}, 0xc00b63e060, {0xc00b375e10, 0x400999d, 0xc00a66b2c0}, 0xc0174357a0)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1676 +0x285
!github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc01331ea80, {0x8ce66b0, 0xc0180fb440}, {0xc00a670600}, {0x3, 0xc0175bf250, 0xc00a66b2c0}, 0xc000647b60)
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:683 +0x9a
!github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:666 +0x2f5
!created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
! /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:594 +0x273
!
!For more context, check log files in: /var/folders/b4/2b8v9mcx5x9d64k7q3m0fz_40000gp/T/logTestSqlLiteLogic1551452583
!
!
!****************************************************************************
!
!This node experienced a fatal error (printed above), and as a result the
!process is terminating.
!
!Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
!problem in CockroachDB. With your help, the support team at Cockroach Labs
!will try to determine the root cause, recommend next steps, and we can
!improve CockroachDB based on your report.
!
!Please submit a crash report by following the instructions here:
!
!    https://github.com/cockroachdb/cockroach/issues/new/choose
!
!If you would rather not post publicly, please contact us directly at:
!
!    support@cockroachlabs.com
!
!The Cockroach Labs team appreciates your feedback.
FAIL    github.com/cockroachdb/cockroach/pkg/sql/logictest      14.257s
```

**To Reproduce**

```
make test PKG=./pkg/sql/logictest/ TESTS=TestSqlLiteLogic GOTESTFLAGS="-v" TESTFLAGS="-bigtest"
```

**Comment by stevendanna** [comment]
I seem to be able to hit this with and without `crdb_test_off`

**Comment by stevendanna** [comment]
This is happening in CI as well here: https://github.com/cockroachdb/cockroach/issues/73103

**Comment by yuzefovich** [comment]
Closing as a dup of #73103
