### ISSUE TITLE
cli: `demo` will crash when launched in background

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#73183]
**Describe the problem**

`./cockroach demo&` won't work, in fact it will crash once `fg` brings it back to the front (until then, it is stopped).

**To Reproduce**

```
cockroach $ ./cockroach demo &
[1] 15889
cockroach $ #
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB cluster of 1 node.
#
# You are connected to tenant 1, but can connect to the system tenant with
# \connect and the SQL url below.
#
# This demo session will attempt to enable enterprise features
# by acquiring a temporary license from Cockroach Labs in the background.
# To disable this behavior, set the environment variable
# COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true.
#
# Beginning initialization of the movr dataset, please wait...
#
# The cluster has been preloaded with the "movr" dataset
# (MovR is a fictional vehicle sharing company).
#
# Reminder: your changes to data stored in the demo session will not be saved!
#
# If you wish to access this demo cluster using another tool, you will need
# the following details:
#
#   - Connection parameters:
#   system tenant
#     (webui)    http://127.0.0.1:8080/demologin?password=demo15889&username=demo
#     (sql)      postgresql://demo:demo15889@127.0.0.1:26257/movr?sslmode=require
#     (sql/jdbc) jdbc:postgresql://127.0.0.1:26257/movr?password=demo15889&sslmode=require&user=demo
#     (sql/unix) postgresql://demo:demo15889@/movr?host=%2Fvar%2Ffolders%2Fnm%2Fj0343rr1275fpm9r3bk3vr200000gq%2FT%2Fdemo3034784078&port=26257
#   
#   tenant 1:
#      (sql):  postgresql://demo:demo15889@127.0.0.1:55187/movr?sslmode=require
#   
#   - Username: "demo", password: "demo15889"
#   - Directory with certificate files (for certain SQL drivers/tools): /var/folders/nm/j0343rr1275fpm9r3bk3vr200000gq/T/demo3034784078
#
# Server version: CockroachDB CCL v22.1.0-alpha.00000000-1567-ga213807107 (x86_64-apple-darwin20.6.0, built , go1.17.3) (same version as client)
# Cluster ID: d3cba60d-9692-488d-9ddd-923416d04d2f
# Organization: Cockroach Demo


[1]+  Stopped                 ./cockroach demo
cockroach $ fg
./cockroach demo
*
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.sigpanic
*   |   /usr/local/go/src/runtime/signal_unix.go:735
*   | runtime.deferreturn
*   |   /usr/local/go/src/runtime/panic.go:596
*   | github.com/cockroachdb/cockroach/pkg/cli/clisqlshell.(*cliState).doRunShell
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlshell/sql.go:1702
*   | github.com/cockroachdb/cockroach/pkg/cli/clisqlshell.(*cliState).RunInteractive
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlshell/sql.go:1689
*   | github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg.(*Context).Run
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg/context.go:204
*   | github.com/cockroachdb/cockroach/pkg/cli.runDemo
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:355
*   | github.com/cockroachdb/cockroach/pkg/cli.init.4.func1
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:56
*   | github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:67
*   | github.com/spf13/cobra.(*Command).execute
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852
*   | github.com/spf13/cobra.(*Command).ExecuteC
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
*   | github.com/spf13/cobra.(*Command).Execute
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
*   | github.com/cockroachdb/cockroach/pkg/cli.Run
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:283
*   | github.com/cockroachdb/cockroach/pkg/cli.doMain
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:130
*   | github.com/cockroachdb/cockroach/pkg/cli.Main
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:59
*   | main.main
*   |   /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach-short/main.go:26
*   | runtime.main
*   |   /usr/local/go/src/runtime/proc.go:255
*   | runtime.goexit
*   |   /usr/local/go/src/runtime/asm_amd64.s:1581
* Wraps: (2) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) runtime.errorString
*
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40368fc]

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.RecoverAndReportPanic({0x9c3ed60, 0xc0001b0008}, 0x0)
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:90 +0x78
panic({0x7eb9fc0, 0xc7dfce0})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/cockroachdb/cockroach/pkg/cli/clisqlshell.(*cliState).doRunShell(0xc005180120, 0x400ffc7, 0x48, 0x8334b60, 0xc0045b7801)
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlshell/sql.go:1702 +0x437
github.com/cockroachdb/cockroach/pkg/cli/clisqlshell.(*cliState).RunInteractive(0xc000b115f0, 0x9dc3b48, 0xc0010e7450, 0x400ffc7)
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlshell/sql.go:1689 +0x25
github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg.(*Context).Run(0xc000b115f0, {0x9dc3b48, 0xc0010e7450})
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/clisqlcfg/context.go:204 +0x1f9
github.com/cockroachdb/cockroach/pkg/cli.runDemo(0xc82e5a0, {0x0, 0x0})
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:355 +0xc85
github.com/cockroachdb/cockroach/pkg/cli.init.4.func1(0xc000647ae8, {0x40b2e91, 0x0, 0x40b6146})
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:56 +0x1d
github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1(0xc82e5a0, {0xc8c7d98, 0x0, 0x0})
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:67 +0x43
github.com/spf13/cobra.(*Command).execute(0xc82e5a0, {0xc8c7d98, 0x0, 0x0})
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc828420)
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:283
github.com/cockroachdb/cockroach/pkg/cli.doMain(0xc82e5a0, {0xc000cff35a, 0x4})
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:130 +0x1de
github.com/cockroachdb/cockroach/pkg/cli.Main()
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:59 +0x136
main.main()
        /Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach-short/main.go:26 +0x17
⚠2 cockroach $ 
```

**Expected behavior**

I was hoping `./cockroach demo&` would "just work".

**Additional data / screenshots**

**Environment:**
`master` at time of writing

**Additional context**
Not a big deal for me.

Jira issue: CRDB-11447

**Comment by knz** [comment]
I have tested this on my machine but could not repro. Is this still active?
