### ISSUE TITLE
stability: better handling of clock skew

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#7326]
two nodes on `gamma` cluster died in a row due to clock skew.

I enabled ntpstats logging after the first one crashed, so I only have information for the second crash:

```
W160620 13:04:30.671606 util/hlc/hlc.go:236  remote wall time is too far ahead (2.089401384s) to be trustworthy - updating anyway
W160620 13:04:30.681176 util/hlc/hlc.go:236  remote wall time is too far ahead (2.089367887s) to be trustworthy - updating anyway
W160620 13:04:30.684049 util/hlc/hlc.go:236  remote wall time is too far ahead (2.089204087s) to be trustworthy - updating anyway
F160620 13:04:30.714051 server/server.go:133  rpc/clock_offset.go:132: fewer than half the known nodes are within the maximum offset of 250ms (3 of 7)
```

ntpstats on that node do show issues: the format is in `modified_julian_day seconds_since_midnight_UTC peer status offset ....`
You can see the offset jumping from 0s to 2s in the span of about 5 minutes.

```
$ cat /var/log/ntpstats/peerstats
57559 46003.592 169.254.169.254 9024 0.000030460 0.000353603 7.937500539 0.000000119
57559 46070.593 169.254.169.254 9024 0.000100240 0.000600058 3.937752060 0.000069779
57559 46136.592 169.254.169.254 9024 -0.000011491 0.000287826 1.937997819 0.000084391
57559 46202.592 169.254.169.254 9024 0.000000797 0.000477980 0.938182574 0.000060332
57559 46730.593 169.254.169.254 963a 0.000066294 0.000628305 0.003782836 0.000043455
57559 47125.593 169.254.169.254 963a 0.000001759 0.000674793 0.003158345 1.117098665
57559 47453.593 169.254.169.254 963a 2.089933360 0.000682738 0.002831743 0.789936151
57559 47713.593 169.254.169.254 963a 2.089880884 0.000642802 0.002580610 0.000053129
57559 48237.593 169.254.169.254 963a 2.089912306 0.000714558 0.004998892 0.000029653
57559 48240.682 169.254.169.254 9044 -0.000099178 0.000313817 7.937500539 0.000000119
57559 48308.683 169.254.169.254 9044 -0.000052460 0.000817912 3.937755812 0.000046718
57559 48374.683 169.254.169.254 9044 -0.000015971 0.000793103 1.937999698 0.000064245
57559 48443.683 169.254.169.254 9044 -0.000035834 0.000760616 0.938203204 0.000039511
57559 48784.683 169.254.169.254 965a 0.000003758 0.000708737 0.002200279 0.000053934
```

I'm not sure what we can do better, but for now, dying on a temporary blip seems rather terrible.

**Comment by petermattis** [comment]
A `2s` jump is horrific. Any clues in any ntp or system log as to what happened? Was this some sort of VM badness?

**Comment by bdarnell** [comment]
We also saw clock offsets of 1.7s in #7224, which lead to crashes (but not, as far as we can tell, to the inconsistencies being investigated there).

**Comment by petermattis** [comment]
Since we've seen a `2s` jump, what would you set `COCKROACH_MAX_OFFSET` to? I think we need to figure out what is causing these jumps.

**Comment by bdarnell** [comment]
Set it to 2.5s and see if we break through again? 

My guess as to the cause is that our VM was moved to new hardware. 

In general virtualized deployments are going to provide fairly weak guarantees around clock behavior, so we'll have to do a lot of testing and observation (on each major platform) to see what ranges are reasonable.

**Comment by petermattis** [comment]
We can disable live VM migration on GCE. We can also see if any such migrations have been performed. See https://cloud.google.com/compute/docs/instances/setting-instance-scheduling-options#before-you-begin:

> When Google Compute Engine migrates your instance, it reports a system event that is published to the your list of zone operations. You can review this event by performing a gcloud compute operations list --zones ZONE request or by viewing the list of operations in the Google Cloud Platform Console, or through an API request.

**Comment by bdarnell** [comment]
No live migrations in the last few days. There was one on June 10 when gamma-6 crashed (in #7224), but the time of day doesn't line up unless someone is misreporting time zones.

```
$ gcloud compute operations list --zones us-east1-d
NAME                                                       TYPE                                        TARGET                                  HTTP_STATUS  STATUS  TIMESTAMP
operation-1465332938718-534b6694a3b31-997e18c8-be6f6023    reset                                       us-east1-d/instances/cockroach-rho-2    200          DONE    2016-06-07T13:55:39.010-07:00
systemevent-1465492549985-534db92dce46b-552a8ca4-6a4e741b  compute.instances.migrateOnHostMaintenance  us-east1-d/instances/cockroach-beta-6   200          DONE    2016-06-09T10:15:49.985-07:00
systemevent-1465504055255-534de40a16234-774b2070-39d7c2f2  compute.instances.migrateOnHostMaintenance  us-east1-d/instances/cockroach-beta-3   200          DONE    2016-06-09T13:27:35.255-07:00
systemevent-1465526818748-534e38d70b90a-86573ab1-ff269fbc  compute.instances.migrateOnHostMaintenance  us-east1-d/instances/cockroach-gamma-3  200          DONE    2016-06-09T19:46:58.748-07:00
systemevent-1465527825279-534e3c96f28e2-b3432652-d8b9ba6d  compute.instances.migrateOnHostMaintenance  us-east1-d/instances/cockroach-rho-1    200          DONE    2016-06-09T20:03:45.279-07:00
systemevent-1465546273166-534e81503932c-bddb0745-3c30e654  compute.instances.migrateOnHostMaintenance  us-east1-d/instances/cockroach-rho-2    200          DONE    2016-06-10T01:11:13.166-07:00
systemevent-1465552755468-534e99763a79a-145fb91f-656637e1  compute.instances.migrateOnHostMaintenance  us-east1-d/instances/cockroach-gamma-6  200          DONE    2016-06-10T02:59:15.468-07:00
```

**Comment by petermattis** [comment]
Heh, I just tracked down that same info.

**Comment by mberhault** [comment]
It's still unclear. The operation list shows no migrations in the last 10 days or so.
The only thing I have in the logs (right before each event) is:
```
Jun 20 13:04:09 cockroach-gamma-6 google-address-manager: ERROR SyncAddresses exception: HTTP Error 503: Service Unavailable
```

Not particularly helpful.

**Comment by bdarnell** [comment]
This happened again on gamma. 

```
W160715 18:01:12.462779 util/hlc/hlc.go:236  remote wall time is too far ahead (2.404474554s) to be trustworthy - updating anyway
E160715 18:01:12.488055 storage/replica_raftstorage.go:295  range 1261: error generating snapshot: couldn't find range descriptor
E160715 18:01:12.535101 storage/replica_raftstorage.go:295  range 1261: error generating snapshot: couldn't find range descriptor
E160715 18:01:12.648038 storage/replica_raftstorage.go:295  range 1261: error generating snapshot: couldn't find range descriptor
W160715 18:01:12.656519 util/hlc/hlc.go:236  remote wall time is too far ahead (2.298065139s) to be trustworthy - updating anyway
E160715 18:01:12.702123 storage/replica_raftstorage.go:295  range 1261: error generating snapshot: couldn't find range descriptor
F160715 18:01:12.702422 server/server.go:133  fewer than half the known nodes are within the maximum offset of 250ms (2 of 7)
goroutine 10 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xecf1b1b01, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:862 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x29e1600, 0x3, 0x23b2263, 0x10, 0x85, 0xc873e9efa0, 0x4f)
        /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:728 +0x9c5
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0xc800000003, 0x2, 0x0, 0x0, 0xc820d51be8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x0, 0x0, 0xc820d51be8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatal(0xc820d51be8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/util/log/log.go:172 +0x5e
```

This time we do see VM migrations in the logs - a lot of them. Some nodes have been migrated many times in the last few days. This is just a portion of the log. 

```
systemevent-1468497251788-53797290be5cd-38514d58-9b3c9940  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-gamma-4  200          DONE    2016-07-14T04:54:11.788-07:00
systemevent-1468508879770-53799de20d3bf-e0c1a878-6c1c7847  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-beta-4   200          DONE    2016-07-14T08:07:59.770-07:00
systemevent-1468523691270-5379d50f66245-be63065a-acc3403b  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-beta-1   200          DONE    2016-07-14T12:14:51.270-07:00
systemevent-1468529685391-5379eb63d6738-1ccef19d-4ef45d1e  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-beta-1   200          DONE    2016-07-14T13:54:45.391-07:00
systemevent-1468584181257-537ab6672547e-39c75fbe-98f61e09  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-beta-4   200          DONE    2016-07-15T05:03:01.257-07:00
systemevent-1468607212693-537b0c33a28fc-b0096d6c-94506bea  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-gamma-1  200          DONE    2016-07-15T11:26:52.693-07:00
systemevent-1468609662875-537b15544f889-395f5cb4-65314c3e  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-beta-1   200          DONE    2016-07-15T12:07:42.875-07:00
systemevent-1468615976574-537b2cd985ce5-9fe16080-153464ab  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-gamma-1  200          DONE    2016-07-15T13:52:56.574-07:00
systemevent-1468621801525-537b428ca0f4e-3023da4d-cfab9f98  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-beta-1   200          DONE    2016-07-15T15:30:01.525-07:00
systemevent-1468623601726-537b49416f378-10ba8eb1-d553d053  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-gamma-4  200          DONE    2016-07-15T16:00:01.726-07:00
systemevent-1468624875230-537b4dfff16de-7eb84caa-4931e710  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-gamma-4  200          DONE    2016-07-15T16:21:15.230-07:00
systemevent-1468640810001-537b895c86297-9c0337c8-b93a6118  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-gamma-4  200          DONE    2016-07-15T20:46:50.001-07:00
systemevent-1468643306483-537b92a95ae7a-a33d023f-f6976619  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-gamma-1  200          DONE    2016-07-15T21:28:26.483-07:00
systemevent-1468648864391-537ba75dc9fb8-506033f4-a479c97d  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-beta-1   200          DONE    2016-07-15T23:01:04.391-07:00
systemevent-1468650054413-537babccaeb63-b48ff817-7d7b8e06  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-gamma-4  200          DONE    2016-07-15T23:20:54.413-07:00
systemevent-1468656658217-537bc4668fad5-79425dcc-d91cd669  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-beta-1   200          DONE    2016-07-16T01:10:58.217-07:00
systemevent-1468657798470-537bc8a5fdc8f-a2480575-3d025f3a  compute.instances.migrateOnHostMaintenance  us-east1-b/instances/cockroach-gamma-1  200          DONE    2016-07-16T01:29:58.470-07:00
```

Sounds like we should disable live migration on our VMs, and make sure we have everything set up to restart on reboot.

The migrations are happening as often as 7 minutes apart. If each of these migrations turned into a reboot that could be a problem.

**Comment by bdarnell** [comment]
I'll restart the servers but they were seeing migrations as recently as 9:27 this morning so the problems may continue.

**Comment by mberhault** [comment]
closing in favor of #12655
