### ISSUE TITLE
logictestccl: repeated PackageLevel test failure possibly caused pebble panic

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#73378]
**Describe the problem**

We've seen repeated package-level failures in `logictestccl`. In every log from such a failure that I've checked so far, I've found the following panic:

```
panic: pebble: closed

goroutine 1734902 [running]:
github.com/cockroachdb/pebble.(*DB).newIterInternal(0xc00ffdbb00, 0xc014498288, 0x10000c00ffdbc90, 0x7f14b3357018)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:746 +0x317
github.com/cockroachdb/pebble.(*DB).NewIter(0x7f14e4bc2688, 0x120)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:923 +0x25
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).init(0xc0093b66c0, {0x61bca40, 0xc010c0a000}, {0x0, 0x0}, {0x1, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:170 +0x6d6
github.com/cockroachdb/cockroach/pkg/storage.newPebbleIterator({0x61bca40, 0xc010c0a000}, {0x0, 0x0}, {0x1, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...})
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:90 +0xbb
github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).NewMVCCIterator(0x1, 0x0, {0x1, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0, ...})
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble.go:855 +0x185
github.com/cockroachdb/cockroach/pkg/storage.newMVCCIterator(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:804
github.com/cockroachdb/cockroach/pkg/storage.MVCCGet({0x620c730, 0xc018a8ca80}, {0x62be9a0, 0xc022725b00}, {0xc0173b1190, 0xa, 0xa}, {0x0, 0x0, 0x0}, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:834 +0x123
github.com/cockroachdb/cockroach/pkg/server.(*nodeTombstoneStorage).IsDecommissioned(0xc00bc7ca80, {0x620c730, 0xc018a8ca80}, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node_tombstone_storage.go:62 +0x3f1
github.com/cockroachdb/cockroach/pkg/server.NewServer.func1({0x620c730, 0xc018a8ca80}, 0x1, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:308 +0x71
github.com/cockroachdb/cockroach/pkg/server.NewServer.func3(0x620c730)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:342 +0x31
github.com/cockroachdb/cockroach/pkg/rpc.(*HeartbeatService).Ping(0xc012a457c0, {0x620c730, 0xc012729470}, 0xc0210d52c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.go:172 +0x498
github.com/cockroachdb/cockroach/pkg/rpc._Heartbeat_Ping_Handler.func1({0x620c730, 0xc012729470}, {0x4908e20, 0xc0210d52c0})
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go:283 +0x78
github.com/cockroachdb/cockroach/pkg/util/tracing.ServerInterceptor.func1({0x620c730, 0xc012729470}, {0x4908e20, 0xc0210d52c0}, 0xc0130f4380, 0xc02dadb110)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:115 +0x234
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x620c730, 0xc012729470}, {0x4908e20, 0xc0210d52c0})
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1131 +0x63
github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1({0x620c730, 0xc012729470}, {0x4908e20, 0xc0210d52c0}, 0xc012729440, 0xc0091d5e80)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:183 +0x83
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x620c730, 0xc012729470}, {0x4908e20, 0xc0210d52c0})
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1134 +0x87
github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor({{{0x10000c010520b60}}}, {0x620c730, 0xc0127292c0}, {0x4908e20, 0xc0210d52c0}, 0xc0130f4380, 0xc0091d5e80)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:71 +0x173
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x620c730, 0xc0127292c0}, {0x4908e20, 0xc0210d52c0})
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1134 +0x87
google.golang.org/grpc.chainUnaryInterceptors.func1({0x620c730, 0xc0127292c0}, {0x4908e20, 0xc0210d52c0}, 0xc0130f4380, 0xc02dadb110)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1136 +0x159
github.com/cockroachdb/cockroach/pkg/rpc._Heartbeat_Ping_Handler({0x43e8d60, 0xc012a457c0}, {0x620c730, 0xc0127292c0}, 0xc0210d5260, 0xc0200dcd80)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go:285 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc017c26540, {0x6294980, 0xc0089f2900}, 0xc0288ff440, 0xc018d5b4d0, 0x8afa050, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc017c26540, {0x6294980, 0xc0089f2900}, 0xc0288ff440, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1626 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:939 +0x294

.... additional goroutines elided....
```

From what I've seen so far, there doesn't seem to be a _particular_ test that triggers this.  However, we have recently (71118eeab5aac0692b0dd7dcaa78b6db8d1e91a0 and 510a7983d3b1d44f04b260f810f12985f962dee6) enabled the 3node-tenant configuration for more tests.

**Comment by tbg** [comment]
In all likelihood this will be fixed by https://github.com/cockroachdb/cockroach/pull/73155, but it's been a bit of a struggle to push this over the finish line. I think I'm nearing completion though.

**Comment by stevendanna** [comment]
@tbg Awesome, thanks for the pointer!

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/pull/73155 has landed, so 🤞🏽 that this is now fixed.
