### ISSUE TITLE
demo panics from "ERROR: bind: address already in use"

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#73448]
**Describe the problem**

Normally, `cockroach demo --empty` will gracefully exit if another demo is already running on the same port. The output looks like:

```
*
* ERROR: listen tcp 127.0.0.1:8081: bind: address already in use
*
ERROR: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

listen tcp 127.0.0.1:8081: bind: address already in use
Failed running "demo"
```

However, if there is a demo running on another version, like `v21.2.2`, and `cockroach-master` is built from the latest commits on master (`7c88d5b` at the time of writing), then `cockroach-master demo --empty` panics.

```
*
* ERROR: listen tcp 127.0.0.1:26257: bind: address already in use
*
*
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.sigpanic
*   |   /usr/local/opt/go/libexec/src/runtime/signal_unix.go:735
*   | github.com/cockroachdb/cockroach/pkg/server.(*SQLServer).AnnotateCtx
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1185
*   | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Start.func8.1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:421
*   | github.com/cockroachdb/cockroach/pkg/util/stop.CloserFn.Close
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:108
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:560
*   | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Close
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:808
*   | github.com/cockroachdb/cockroach/pkg/cli.runDemo
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:243
*   | github.com/cockroachdb/cockroach/pkg/cli.init.4.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:56
*   | github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:67
*   | github.com/spf13/cobra.(*Command).execute
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852
*   | github.com/spf13/cobra.(*Command).ExecuteC
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
*   | github.com/spf13/cobra.(*Command).Execute
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
*   | github.com/cockroachdb/cockroach/pkg/cli.Run
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:283
*   | github.com/cockroachdb/cockroach/pkg/cli.doMain
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:130
*   | github.com/cockroachdb/cockroach/pkg/cli.Main
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:59
*   | main.main
*   |   /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach-short/main.go:26
*   | runtime.main
*   |   /usr/local/opt/go/libexec/src/runtime/proc.go:255
*   | runtime.goexit
*   |   /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1581
* Wraps: (2) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) runtime.errorString
*
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6f86dbe]

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.RecoverAndReportPanic({0x9c61280, 0xc0001b2008}, 0xc0009d9830)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:90 +0x78
panic({0x7ece560, 0xc810f00})
        /usr/local/opt/go/libexec/src/runtime/panic.go:1038 +0x215
github.com/cockroachdb/cockroach/pkg/server.(*SQLServer).AnnotateCtx(0x0, {0x9c61280, 0xc0001b2008})
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1185 +0x1e
github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Start.func8.1()
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:421 +0x48
github.com/cockroachdb/cockroach/pkg/util/stop.CloserFn.Close(0xc0009d9830)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:108 +0x1a
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc0009d9830, {0x9c61280, 0xc0001b2008})
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:560 +0x262
github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Close(0xc001a0d0e0, {0x9c61280, 0xc0001b2008})
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:808 +0x34
github.com/cockroachdb/cockroach/pkg/cli.runDemo(0xc85f6a0, {0x0, 0x0})
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:243 +0xec6
github.com/cockroachdb/cockroach/pkg/cli.init.4.func1(0xc000525ae8, {0x40b4351, 0x0, 0x40b7606})
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:56 +0x1d
github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1(0xc85f6a0, {0xc000bb7de0, 0x1, 0x1})
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:67 +0x43
github.com/spf13/cobra.(*Command).execute(0xc85f6a0, {0xc000bb7dd0, 0x1, 0x1})
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc859520)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:283
github.com/cockroachdb/cockroach/pkg/cli.doMain(0xc85f6a0, {0xc00091dc7a, 0x4})
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:130 +0x1de
github.com/cockroachdb/cockroach/pkg/cli.Main()
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:59 +0x136
main.main()
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach-short/main.go:26 +0x17
```

**To Reproduce**

1. Run `cockroach demo --empty` where `cockroach` is a v21.2.2 binary.
2. Fetch the latest commits on master and create a binary with `make buildshort`. (I discovered this on `7c88d5b`).
3. Run `./cockroachshort demo --empty`.

**Comment by mgartner** [comment]
Please let me know if I've assigned this to the correct project. I want to make sure it is addressed before the coming release.
