### ISSUE TITLE
sql: investigate server panic when running graphile-engine test suite

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#73610]
**Describe the problem**

Running graphile-engine tests resulted in the following error:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x46114d]

goroutine 312791 [running]:
runtime.throw(0x53bf155, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0078c4908 sp=0xc0078c48d8 pc=0x48b652
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5 fp=0xc0078c4940 sp=0xc0078c4908 pc=0x4a3105
runtime.mallocgc(0x50, 0x30, 0x1, 0xc00554b608)
	/usr/local/go/src/runtime/malloc.go:1097 +0x5cd fp=0xc0078c49c8 sp=0xc0078c4940 pc=0x46114d
runtime.newobject(0x4e60b80, 0xc007704838)
	/usr/local/go/src/runtime/malloc.go:1177 +0x38 fp=0xc0078c49f8 sp=0xc0078c49c8 pc=0x461638
github.com/cockroachdb/cockroach/pkg/sql/parser.(*sqlParserImpl).Parse(0xc007704718, 0x8db98e0, 0xc0077046b0, 0x0)
        sql-gen.y:12949 +0x86e99 fp=0xc0078cb228 sp=0xc0078c49f8 pc=0x1854299
github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).parse(0xc007704680, 0x2, 0x556a7bc, 0x15a, 0xc00773b000, 0x4f, 0x80, 0xb46f
da0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:195 +0x175 fp=0xc0078cb2f8 sp=0xc0078cb228 pc=0x17c9875
github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).parseWithDepth(0xc007704680, 0x1, 0x556a7bb, 0x15d, 0xb46fda0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:175 +0x1d1 fp=0xc0078cb430 sp=0xc0078cb2f8 pc=0x17c9451
github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).parseOneWithInt(0xc007704680, 0x556a7bb, 0x15d, 0xb46fda0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:126 +0x77 fp=0xc0078cb4a0 sp=0xc0078cb430 pc=0x17c8c97
github.com/cockroachdb/cockroach/pkg/sql/parser.ParseOneWithInt(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:264
github.com/cockroachdb/cockroach/pkg/sql/parser.ParseOne(0x556a7bb, 0x15d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8e056d0, 0xc003490de0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:257 +0xb3 fp=0xc0078cb578 sp=0xc0078cb4a0 pc=0x17c9d93
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal(0xc0013fbd40, 0x8e05628, 0xc003490de0, 0x53147d6, 0xa, 0xc0078a5000, 0xc003646a50, 0x5300399, 0x4, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:690 +0x4a5 fp=0xc0078cb9c8 sp=0xc0078cb578 pc=0x358e265
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).queryInternalBuffered(0xc0013fbd40, 0x8e05628, 0xc0078a4e00, 0x53147d6, 0xa, 0xc003646a50, 0x5300399, 0x4, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:431 +0x195 fp=0xc0078cbae0 sp=0xc0078cb9c8 pc=0x358c875
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryBufferedEx(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:400
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryBuffered(0xc0013fbd40, 0x8e05628, 0xc0078a4e00, 0x53147d6, 0xa, 0xc
003646a50, 0x556a7bb, 0x15d, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:382 +0x1ad fp=0xc0078cbc50 sp=0xc0078cbae0 pc=0x358c32d
github.com/cockroachdb/cockroach/pkg/sql.forEachRole(0x8e05628, 0xc0078a4e00, 0xc007a2c5d0, 0xc0078cbd58, 0xc001bf3d88, 0xc000600000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2582 +0x105 fp=0xc0078cbd28 sp=0xc0078cbc50 pc=0x35849
65
github.com/cockroachdb/cockroach/pkg/sql.glob..func239(0x8e05628, 0xc0078a4e00, 0xc007a2c5d0, 0x8f57c58, 0xc003876000, 0xc0078a4fc0,
0xc00353e118, 0xc001bf3e7c)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:2357 +0xc5 fp=0xc0078cbda0 sp=0xc0078cbd28 pc=0x368d125
github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1(0x8d70280, 0xc0106f6d80, 0x0, 0x0)
```

**To Reproduce**

Rough instructions:

1. Clone this repo: https://github.com/graphile/graphile-engine
2. Checkout the `cockroachdb` branch
3. Run `yarn` to install the correct versions of the dependencies throughout the monorepo (you need to have Node.js and yarn installed; once Node is installed you can install yarn with `npm install -g yarn`)
4. In the root of the repo, execute `yarn watch` and leave it running. If it raises some issues the first time wait 15 seconds, kill it, then run it again. It should succeed the second time (and should never fail like that ever again, unless you clear the built code folders).
5. Follow the instructions here: https://github.com/graphile/graphile-engine/blob/cockroachdb/packages/pg-analogues/cockroach/README.md
6. 
Please note the run script does some custom configuration of cockroach which is required for the tests to run: https://github.com/graphile/graphile-engine/blob/cockroachdb/packages/pg-analogues/cockroach/run - you may need to adjust with your local copies of cockroach

**Expected behavior**
No crash.

**Additional data / screenshots**
See https://cockroachlabs.slack.com/archives/C01QUMARDRS/p1634752828007100

**Environment:**
 - CockroachDB version v22.1.0-alpha.00000000-535-g300e4b08e2
 - Server OS: Ubuntu 21.04

Epic CRDB-2410

**Comment by otan** [comment]
```
* Wraps: (2) while executing: WITH _ AS (SELECT to_json((((jsonb_build_object('_'::STRING, json_build_array(_._), '_'::STRING, (_._), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._))))) || jsonb_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))))) || jsonb_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._)))), '_'::STRING, (SELECT json_build_object('_'::STRING, (SELECT json_build_object('_'::STRING, count(_)) FROM _ AS _ WHERE (_._ = _._))))))::JSONB)) AS _ FROM (SELECT _.* FROM _ AS _ WHERE _ AND _ ORDER BY _._ ASC LIMIT _) AS _), _ AS (SELECT json_agg(to_json(_)) AS _ FROM _) SELECT COALESCE((SELECT _._ FROM _), '_'::JSONB [...]
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:679
*   | runtime.gopanic
*   | 	/usr/local/go/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/util/ring.(*Buffer).GetFirst
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/ring/ring_buffer.go:69
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).recordInternalLocked
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go:478
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).recordFinishedChildrenLocked
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go:380
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).recordFinishedChildren
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go:360
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*spanInner).ImportRemoteSpans
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/span_inner.go:80
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).ImportRemoteSpans
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:180
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).pushMeta
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:967
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).Push
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1047
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:189
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:733
*   | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:453
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:246
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:563
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunSubquery
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1269
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1174
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1398
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1084
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:721
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:135
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:222
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1820
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1822
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1676
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:681
*   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:666
*   | runtime.goexit
*   | 	/usr/local/go/src/runtime/asm_amd64.s:1581
* Wraps: (4) panic: getting first from empty ring buffer
* Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) *errutil.leafError
* ```
hmmm

**Comment by rafiss** [comment]
Interesting.. the SIGSEGV was first seen on 300e4b08e2

**Comment by knz** [comment]
No matter how much or little memory there is, this stack trace is indicative of a problem in the go runtime.
There's not much the CRL team can do.

Can this be reproduced reliably? (Possibly, by creating a docker container to ensure everything is captured?) 
If so, it would be good to file the issue at the go repository.

**Comment by ecwall** [comment]
The fixes above appear to have fixed it since running the test suite no longer crashes the DB.
