### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestSlowLeaderRetry

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#7384]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/f2e3441898c341dd9c35b68faa15eddfe2f191c3

Stress build found a failed test:

```
=== RUN   TestSlowLeaderRetry
I160622 04:19:27.295832 gossip/simulation/network.go:57  simulating gossip network with 1 nodes
W160622 04:19:27.295995 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
W160622 04:19:27.296056 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160622 04:19:27.296601 gossip/gossip.go:923  starting client to 127.0.0.1:41990
I160622 04:19:27.299902 gossip/client.go:86  closing client to node 1 (127.0.0.1:41990): gossip/client.go:184: stopping outgoing client to node 1 (127.0.0.1:41990); loopback connection
I160622 04:19:28.296777 gossip/gossip.go:923  starting client to 127.0.0.1:41990
I160622 04:19:28.297329 gossip/client.go:86  closing client to node 1 (127.0.0.1:41990): gossip/client.go:184: stopping outgoing client to node 1 (127.0.0.1:41990); loopback connection
SIGABRT: abort
PC=0x63ae71 m=0

goroutine 0 [idle]:
runtime.futex(0x2909348, 0x0, 0x0, 0x0, 0x0, 0x2908050, 0x0, 0x0, 0x5e9604, 0x2909348, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:306 +0x21
runtime.futexsleep(0x2909348, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x2909348)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1538 +0x10b
runtime.findrunnable(0xc82001a000, 0x0)
	/usr/local/go/src/runtime/proc.go:1976 +0x739
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2075 +0x24f
runtime.goexit0(0xc8204ddb00)
	/usr/local/go/src/runtime/proc.go:2210 +0x1f9
runtime.mcall(0x7fff2a400e20)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0x1dff4b8, 0x25f4f40, 0x7b, 0x7b, 0x1)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820045f08, 0x0)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/kv/_test/_testmain.go:304 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2907e80)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 647 [chan send, 9 minutes]:
github.com/cockroachdb/cockroach/kv.(*slowLeaderTransport).IsExhausted(0xc820160600, 0xc8200eca20)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_test.go:1695 +0x8e
github.com/cockroachdb/cockroach/kv.(*DistSender).sendToReplicas(0xc82021efc0, 0x7f384b8c7988, 0xc8201942d0, 0xf4240, 0xb2d05e00, 0xc8201568b0, 0x2, 0xc820160ac0, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:970 +0x5ad
github.com/cockroachdb/cockroach/kv.(*DistSender).sendRPC(0xc82021efc0, 0x7f384b8c7988, 0xc8201942d0, 0x2, 0xc820160ac0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:344 +0x1ee
github.com/cockroachdb/cockroach/kv.(*DistSender).sendSingleRange(0xc82021efc0, 0x7f384b8c7988, 0xc8201942d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:460 +0x1ea
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk.func2(0xc8202a4f30, 0xc8202a4c18, 0xc8202a56c8, 0xc82021efc0, 0xc8202a56b8, 0x8, 0xc8201569b0)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:719 +0x443
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk(0xc82021efc0, 0x7f384b8c7988, 0xc8201942d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:720 +0xa20
github.com/cockroachdb/cockroach/kv.(*DistSender).Send(0xc82021efc0, 0x7f384b8c7880, 0xc82000eac8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:564 +0x6d4
github.com/cockroachdb/cockroach/kv.TestSlowLeaderRetry(0xc82021f050)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_test.go:1734 +0x3fc
testing.tRunner(0xc82021f050, 0x25f5150)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 661 [select]:
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8200ec300, 0xc820278a50, 0xc8201561a0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:235 +0x649
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1.1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:172 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820176460, 0xc820191a10)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 662 [IO wait]:
net.runtime_pollWait(0x7f384b94fdb0, 0x72, 0xc82072a000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820177db0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820177db0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820177d50, 0xc82072a000, 0x8000, 0x8000, 0x0, 0x7f384b946050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820036158, 0xc82072a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc8200ed020)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8200ed020, 0xc8200e44b8, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f384b950820, 0xc8200ed020, 0xc8200e44b8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f384b950820, 0xc8200ed020, 0xc8200e44b8, 0x9, 0x9, 0xc8204d0600, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8200e44b8, 0x9, 0x9, 0x7f384b950820, 0xc8200ed020, 0x20000000, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8200e4480, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:464 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc820158390, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:417 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc82021f320, 0xc820158690)
	/go/src/google.golang.org/grpc/transport/http2_server.go:243 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc82021e000, 0x7f384b950870, 0xc82021f320)
	/go/src/google.golang.org/grpc/server.go:354 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc82021e000, 0x7f384b913ce0, 0xc820036158, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:341 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc82021e000, 0x7f384b913ce0, 0xc820036158)
	/go/src/google.golang.org/grpc/server.go:318 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:290 +0x38c

goroutine 666 [semacquire, 9 minutes]:
sync.runtime_Syncsemacquire(0xc820014a90)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc820014a80)
	/usr/local/go/src/sync/cond.go:63 +0x9b
github.com/cockroachdb/cockroach/gossip.(*server).gossipReceiver(0xc8200ec480, 0xc820036198, 0xc820174ab0, 0xc820042f60, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:223 +0x719
github.com/cockroachdb/cockroach/gossip.(*server).Gossip.func3.1()
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:101 +0x8b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820176460, 0xc820782500)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 619 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/gossip.(*server).start.func3()
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:298 +0x5c
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820176460, 0xc8201602e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 663 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc82021f320)
	/go/src/google.golang.org/grpc/transport/http2_server.go:660 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x84f

goroutine 665 [select, 9 minutes]:
github.com/cockroachdb/cockroach/gossip.(*server).Gossip(0xc8200ec480, 0x7f384b8c7e90, 0xc8201573f0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:134 +0xa0f
github.com/cockroachdb/cockroach/gossip._Gossip_Gossip_Handler(0x1933a40, 0xc8200ec480, 0x7f384b8c7e48, 0xc82009a100, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.pb.go:210 +0xd8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc82021e000, 0x7f384b950870, 0xc82021f320, 0xc820184e00, 0xc820160220, 0x25e9100, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:607 +0x47a
google.golang.org/grpc.(*Server).handleStream(0xc82021e000, 0x7f384b950870, 0xc82021f320, 0xc820184e00, 0x0)
	/go/src/google.golang.org/grpc/server.go:691 +0x114e
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc8201570b0, 0xc82021e000, 0x7f384b950870, 0xc82021f320, 0xc820184e00)
	/go/src/google.golang.org/grpc/server.go:352 +0xa0
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/google.golang.org/grpc/server.go:353 +0x9a

goroutine 648 [IO wait]:
net.runtime_pollWait(0x7f384b94fe70, 0x72, 0xc8202a6000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820177cd0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820177cd0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820177c70, 0xc8202a6000, 0x8000, 0x8000, 0x0, 0x7f384b946050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f2000, 0xc8202a6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820012240)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820012240, 0xc82011c3f8, 0x9, 0x9, 0xc81fffaec6, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f384b950820, 0xc820012240, 0xc82011c3f8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f384b950820, 0xc820012240, 0xc82011c3f8, 0x9, 0x9, 0xc8201deab8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82011c3f8, 0x9, 0x9, 0x7f384b950820, 0xc820012240, 0x0, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82011c3c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:464 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8202183f0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:417 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc8204fc000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:795 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:174 +0xd21

goroutine 649 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8204fc000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:873 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:201 +0x15c2

goroutine 633 [select, 9 minutes]:
github.com/cockroachdb/cockroach/gossip.(*server).Gossip(0xc8200ec480, 0x7f384b8c7e90, 0xc82000f810, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:134 +0xa0f
github.com/cockroachdb/cockroach/gossip._Gossip_Gossip_Handler(0x1933a40, 0xc8200ec480, 0x7f384b8c7e48, 0xc82016a180, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.pb.go:210 +0xd8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc82021e000, 0x7f384b950870, 0xc82021f320, 0xc820212000, 0xc820160220, 0x25e9100, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:607 +0x47a
google.golang.org/grpc.(*Server).handleStream(0xc82021e000, 0x7f384b950870, 0xc82021f320, 0xc820212000, 0x0)
	/go/src/google.golang.org/grpc/server.go:691 +0x114e
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc8201570b0, 0xc82021e000, 0x7f384b950870, 0xc82021f320, 0xc820212000)
	/go/src/google.golang.org/grpc/server.go:352 +0xa0
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/google.golang.org/grpc/server.go:353 +0x9a

goroutine 616 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:104 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820176460, 0xc82000a360)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 618 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f384b9502f0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820176530, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820176530, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201764d0, 0x0, 0x7f384b913c40, 0xc8201612a0)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820036020, 0xc820044ea8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820036020, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc82021e000, 0x7f384b94f408, 0xc820036020, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:281 +0x1cf
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:52 +0x3f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820176460, 0xc82000a560)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 660 [select, 9 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8201e2000)
	/go/src/google.golang.org/grpc/clientconn.go:547 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8201e2000)
	/go/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3

goroutine 620 [select, 9 minutes]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).bootstrap.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:767 +0x219
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820176460, 0xc8201603c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 621 [select]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).manage.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:796 +0x33b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820176460, 0xc820160400)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 634 [semacquire, 9 minutes]:
sync.runtime_Syncsemacquire(0xc820014a90)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc820014a80)
	/usr/local/go/src/sync/cond.go:63 +0x9b
github.com/cockroachdb/cockroach/gossip.(*server).gossipReceiver(0xc8200ec480, 0xc82015e2c8, 0xc8201f6ed0, 0xc820043f60, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:223 +0x719
github.com/cockroachdb/cockroach/gossip.(*server).Gossip.func3.1()
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:101 +0x8b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820176460, 0xc82009c200)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 617 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:47 +0x47
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820176460, 0xc82000a540)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

rax    0xca
rbx    0x0
rcx    0x63ae73
rdx    0x0
rdi    0x2909348
rsi    0x0
rbp    0x1
rsp    0x7fff2a400c78
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x5
r13    0xc
r14    0x1a51ab0
r15    0x8
rip    0x63ae71
rflags 0x286
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
16 runs so far, 0 failures, over 30s
16 runs so far, 0 failures, over 35s
16 runs so far, 0 failures, over 40s
16 runs so far, 0 failures, over 45s
16 runs so far, 0 failures, over 50s
18 runs so far, 0 failures, over 55s
32 runs so far, 0 failures, over 1m0s
32 runs so far, 0 failures, over 1m5s
32 runs so far, 0 failures, over 1m10s
32 runs so far, 0 failures, over 1m15s
32 runs so far, 0 failures, over 1m20s
48 runs so far, 0 failures, over 1m25s
48 runs so far, 0 failures, over 1m30s
48 runs so far, 0 failures, over 1m35s
48 runs so far, 0 failures, over 1m40s
48 runs so far, 0 failures, over 1m45s
54 runs so far, 0 failures, over 1m50s
63 runs so far, 0 failures, over 1m55s
63 runs so far, 0 failures, over 2m0s
63 runs so far, 0 failures, over 2m5s
63 runs so far, 0 failures, over 2m10s
65 runs so far, 0 failures, over 2m15s
78 runs so far, 0 failures, over 2m20s
78 runs so far, 0 failures, over 2m25s
78 runs so far, 0 failures, over 2m30s
78 runs so far, 0 failures, over 2m35s
79 runs so far, 0 failures, over 2m40s
93 runs so far, 0 failures, over 2m45s
93 runs so far, 0 failures, over 2m50s
93 runs so far, 0 failures, over 2m55s
93 runs so far, 0 failures, over 3m0s
93 runs so far, 0 failures, over 3m5s
104 runs so far, 0 failures, over 3m10s
108 runs so far, 0 failures, over 3m15s
108 runs so far, 0 failures, over 3m20s
108 runs so far, 0 failures, over 3m25s
108 runs so far, 0 failures, over 3m30s
112 runs so far, 0 failures, over 3m35s
123 runs so far, 0 failures, over 3m40s
123 runs so far, 0 failures, over 3m45s
123 runs so far, 0 failures, over 3m50s
123 runs so far, 0 failures, over 3m55s
125 runs so far, 0 failures, over 4m0s
138 runs so far, 0 failures, over 4m5s
138 runs so far, 0 failures, over 4m10s
138 runs so far, 0 failures, over 4m15s
138 runs so far, 0 failures, over 4m20s
139 runs so far, 0 failures, over 4m25s
152 runs so far, 0 failures, over 4m30s
153 runs so far, 0 failures, over 4m35s
153 runs so far, 0 failures, over 4m40s
153 runs so far, 0 failures, over 4m45s
154 runs so far, 0 failures, over 4m50s
161 runs so far, 0 failures, over 4m55s
168 runs so far, 0 failures, over 5m0s
168 runs so far, 0 failures, over 5m5s
168 runs so far, 0 failures, over 5m10s
168 runs so far, 0 failures, over 5m15s
171 runs so far, 0 failures, over 5m20s
183 runs so far, 0 failures, over 5m25s
183 runs so far, 0 failures, over 5m30s
183 runs so far, 0 failures, over 5m35s
183 runs so far, 0 failures, over 5m40s
186 runs so far, 0 failures, over 5m45s
198 runs so far, 0 failures, over 5m50s
198 runs so far, 0 failures, over 5m55s
198 runs so far, 0 failures, over 6m0s
198 runs so far, 0 failures, over 6m5s
199 runs so far, 0 failures, over 6m10s
210 runs so far, 0 failures, over 6m15s
213 runs so far, 0 failures, over 6m20s
213 runs so far, 0 failures, over 6m25s
213 runs so far, 0 failures, over 6m30s
214 runs so far, 0 failures, over 6m35s
220 runs so far, 0 failures, over 6m40s
228 runs so far, 0 failures, over 6m45s
228 runs so far, 0 failures, over 6m50s
228 runs so far, 0 failures, over 6m55s
229 runs so far, 0 failures, over 7m0s
231 runs so far, 0 failures, over 7m5s
243 runs so far, 0 failures, over 7m10s
243 runs so far, 0 failures, over 7m15s
243 runs so far, 0 failures, over 7m20s
244 runs so far, 0 failures, over 7m25s
246 runs so far, 0 failures, over 7m30s
258 runs so far, 0 failures, over 7m35s
258 runs so far, 0 failures, over 7m40s
258 runs so far, 0 failures, over 7m45s
259 runs so far, 0 failures, over 7m50s
260 runs so far, 0 failures, over 7m55s
272 runs so far, 0 failures, over 8m0s
272 runs so far, 0 failures, over 8m5s
272 runs so far, 0 failures, over 8m10s
272 runs so far, 0 failures, over 8m15s
274 runs so far, 0 failures, over 8m20s
285 runs so far, 0 failures, over 8m25s
286 runs so far, 0 failures, over 8m30s
286 runs so far, 0 failures, over 8m35s
286 runs so far, 0 failures, over 8m40s
287 runs so far, 0 failures, over 8m45s
297 runs so far, 0 failures, over 8m50s
300 runs so far, 0 failures, over 8m55s
300 runs so far, 0 failures, over 9m0s
300 runs so far, 0 failures, over 9m5s
301 runs so far, 0 failures, over 9m10s
311 runs so far, 0 failures, over 9m15s
314 runs so far, 0 failures, over 9m20s
314 runs so far, 0 failures, over 9m25s
314 runs so far, 0 failures, over 9m30s
315 runs so far, 0 failures, over 9m35s
325 runs so far, 0 failures, over 9m40s
328 runs so far, 0 failures, over 9m45s
328 runs so far, 0 failures, over 9m50s
328 runs so far, 0 failures, over 9m55s
329 runs so far, 0 failures, over 10m0s
335 runs so far, 0 failures, over 10m5s
342 runs so far, 0 failures, over 10m10s
342 runs so far, 0 failures, over 10m15s
342 runs so far, 0 failures, over 10m20s
343 runs so far, 0 failures, over 10m25s
349 runs so far, 0 failures, over 10m30s
356 runs so far, 0 failures, over 10m35s
356 runs so far, 0 failures, over 10m40s
356 runs so far, 0 failures, over 10m45s
357 runs so far, 0 failures, over 10m50s
362 runs so far, 0 failures, over 10m55s
370 runs so far, 0 failures, over 11m0s
370 runs so far, 0 failures, over 11m5s
370 runs so far, 0 failures, over 11m10s
371 runs so far, 0 failures, over 11m15s
374 runs so far, 0 failures, over 11m20s
382 runs completed, 1 failures, over 11m22s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
This looks like a deadlock in gossip. Closing in favour of the latest instance #8085.
