### ISSUE TITLE
Node crashes with "panic: use of enum metadata before hydration as an enum" in log file

### ISSUE THREAD

**Issue by mgoddard** [cockroachdb/cockroach#73851]
**Describe the problem**

Running the following query fails and one of the cockroach processes crashed:
```
SELECT status
FROM rbac.role_assignment
WHERE resource_ari='ari:cloud:product_e::workspace/45910bcf-7096-49ae-acd3-e51b597ee619'
  AND role_ari IN
    (SELECT DISTINCT role_ari
     FROM rbac.role_definition
     WHERE status='active'
       AND permission='admin')
  AND principal_ari IN
    (SELECT group_ari
     FROM ph.membership
     WHERE status='active'
       AND user_ari IN
         (SELECT user_ari
          FROM ph.user
          WHERE status='active'
            AND user_ari='ari:cloud:identity::user/00010c00-1fdd-41fa-8c88-e7553d394e04')
     UNION SELECT user_ari
     FROM ph.user
     WHERE status='active'
       AND user_ari='ari:cloud:identity::user/00010c00-1fdd-41fa-8c88-e7553d394e04');
```

Please describe the issue you observed, and any steps we can take to reproduce it:

```
$ cat cockroach-stderr.ip-10-124-237-125.ec2-user.2021-11-24T19_29_59Z.009464.log 
I211124 19:29:59.928561 1 util/log/file_sync_buffer.go:238 ⋮ [config]   file created at: 2021/11/24 19:29:59
I211124 19:29:59.928584 1 util/log/file_sync_buffer.go:238 ⋮ [config]   running on machine: ‹ip-10-124-237-125›
I211124 19:29:59.928595 1 util/log/file_sync_buffer.go:238 ⋮ [config]   binary: CockroachDB CCL v21.2.0 (x86_64-unknown-linux-gnu, built 2021/11/15 13:58:04, go1.16.6)
I211124 19:29:59.928604 1 util/log/file_sync_buffer.go:238 ⋮ [config]   arguments: [‹cockroach› ‹start› ‹--certs-dir=/home/ec2-user/certs› ‹--advertise-addr=10.124.237.125:5432› ‹--listen-addr=:5432› ‹--http-addr=:26257› ‹--join=10.124.239.99:5432,10.124.237.125:5432,10.124.239.27:5432› ‹--cache=.25› ‹--max-sql-memory=.25›]
I211124 19:29:59.928631 1 util/log/file_sync_buffer.go:238 ⋮ [config]   log format (utf8=✓): crdb-v2
I211124 19:29:59.928638 1 util/log/file_sync_buffer.go:238 ⋮ [config]   line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid [chan@]file:line redactionmark \[tags\] [counter] msg
I211124 19:29:59.928354 1 util/log/flags.go:202  [-] 1  stderr capture started
panic: use of enum metadata before hydration as an enum [recovered]
	panic: use of enum metadata before hydration as an enum [recovered]
	panic: use of enum metadata before hydration as an enum

goroutine 6144962817 [running]:
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1(0xc005915e08)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58 +0x6b0
panic(0x4d846e0, 0xc01f3b9890)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1(0xc005915d08)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58 +0x6b0
panic(0x4d846e0, 0xc01f3b9890)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/types.(*T).ensureHydratedEnum(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/types/types.go:2435
github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical(0xc01915ca80, 0xc03f6288d0, 0x1, 0x30, 0x1, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/types/types.go:2400 +0x4a6
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep(0xc01915ca80, 0xc03f6288d0, 0x1, 0x30, 0x0, 0x2f, 0xc03f6288d0, 0x1, 0x30, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:4130 +0x4d
github.com/cockroachdb/cockroach/pkg/sql/rowenc.DecodeUntaggedDatum(0xc0006115d8, 0xc01915ca80, 0xc03f6288cf, 0x2, 0x31, 0x3, 0x6, 0x0, 0x0, 0xc00672cb48, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowenc/column_type_encoding.go:686 +0x33b1
github.com/cockroachdb/cockroach/pkg/sql/rowenc.DecodeTableValue(0xc0006115d8, 0xc01915ca80, 0xc03f6288ce, 0x3, 0x32, 0x0, 0x0, 0x0, 0xc0059156a0, 0x22ce279, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowenc/column_type_encoding.go:533 +0x165
github.com/cockroachdb/cockroach/pkg/sql/rowenc.(*EncDatum).EnsureDecoded(0xc002b9fcd0, 0xc01915ca80, 0xc0006115d8, 0xc018512000, 0x4c94a80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:238 +0xa7
github.com/cockroachdb/cockroach/pkg/sql/execinfrapb.(*ExprHelper).IndexedVarEval(0xc000611568, 0x7, 0xc002bea000, 0x45ed25, 0x4c94a80, 0x4edd420, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/expr.go:131 +0x78
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*IndexedVar).Eval(0xc00cff1318, 0xc002bea000, 0xc00cff1318, 0x8c63c90, 0xc00cff1318, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/indexed_vars.go:81 +0xc7
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr).Eval(0xc00ab550e0, 0xc002bea000, 0x8, 0x7f72af117f18, 0xc01f3b9870, 0xc00dcde750)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:4097 +0x7d
github.com/cockroachdb/cockroach/pkg/sql/execinfrapb.RunFilter(0x8c63468, 0xc00ab550e0, 0xc002bea000, 0x0, 0x1, 0xc01f3b9870)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/expr.go:202 +0x48
github.com/cockroachdb/cockroach/pkg/sql/execinfrapb.(*ExprHelper).EvalFilter(0xc000611568, 0xc002b9fb80, 0xd, 0xd, 0x8, 0x8, 0x8)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/expr.go:191 +0xf6
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinerBase).render(0xc000611000, 0xc000611bc8, 0x5, 0x5, 0xc003c83c80, 0x8, 0x8, 0xc0188ff6c0, 0x8c19490, 0xc021a1d920, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinerbase.go:180 +0xf3
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReaderNoOrderingStrategy).nextRowToEmit(0xc0188ff6c0, 0x8c19490, 0xc021a1d920, 0xc00040b880, 0x1a0, 0x497bfc0, 0xb2d5430, 0x497bfc0, 0xb2d5430)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader_strategies.go:270 +0x14c
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).emitRow(0xc000611000, 0x3, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:859 +0x50
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).Next(0xc000611000, 0x1, 0x0, 0x0, 0xc0182176c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:608 +0x252
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next(0xc01cb55c00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:222 +0x10b
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).processNextBatch(0xc005b69500, 0x8c19490, 0xc021a1d920, 0xc000611000)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:639 +0x48
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run.func1.1()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:563 +0x45
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0xc012b8fd98, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91 +0x57
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:601 +0x15e
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0xc003860e88, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91 +0x57
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run(0xc005b69500, 0x8c19490, 0xc021a1d920)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:558 +0x129
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.func1(0x8c193e8, 0xc0103ede40, 0xc009180500)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:796 +0xdb
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1(0xc00541a960, 0x8c193e8, 0xc0103ede40, 0xc009180500, 0xc01541c0f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1322 +0x44
created by github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1321 +0x6f
```

**Additional data / screenshots**

We can provide DDL, etc. as required.

**Environment:**
 - CockroachDB version v21.2.0
 - Server OS: Linux AWS EC2
 - Client app Python / pycopg2 or psql

**Additional context**
We're unable to proceed with our evaluation.

**Comment by mgoddard** [comment]
#sql-queries

**Comment by yuzefovich** [comment]
The schema is [here](https://cockroachlabs.slack.com/archives/CHVV403F0/p1639586469345000?thread_ts=1639522753.332500&cid=CHVV403F0).

**Comment by yuzefovich** [comment]
Closing in favor of https://github.com/cockroachlabs/support/issues/1358
