### ISSUE TITLE
jepsen nightly: strobe-time is not compatible with modern distro

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#74614]
Tests using strobe-skews nemesis are broken.
Helper tool that manipulate system time uses arguments that are deprecated and cause system calls to fail on ubuntu 20.04 image that is used for tests.
We implemented a fix for another tool bump-time to avoid using tz argument, so we need to make a similar change.
Check invoke.log on for example jepsen/sequential/strobe-skews on tc-nightly build.

```
Caused by: java.lang.RuntimeException: sudo -S -u root bash -x -c "cd /; /opt/jepsen/strobe-time 200 10 10" returned non-zero exit status 2 on 10.142.0.102.


STDERR:
+ cd /
+ /opt/jepsen/strobe-time 200 10 10
settimeofday: Invalid argument

        at jepsen.control$throw_on_nonzero_exit.invokeStatic(control.clj:129) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.control$throw_on_nonzero_exit.invoke(control.clj:122) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.control$exec_STAR_.invokeStatic(control.clj:166) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.control$exec_STAR_.doInvoke(control.clj:163) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.8.0.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:646) [clojure-1.8.0.jar:na]
        at clojure.core$apply.invoke(core.clj:641) [clojure-1.8.0.jar:na]
        at jepsen.control$exec.invokeStatic(control.clj:182) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at jepsen.control$exec.doInvoke(control.clj:176) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:457) [clojure-1.8.0.jar:na]
        at jepsen.nemesis.time$strobe_time_BANG_.invokeStatic(time.clj:60) ~[classes/:na]
        at jepsen.nemesis.time$strobe_time_BANG_.invoke(time.clj:56) ~[classes/:na]
        at jepsen.cockroach.nemesis$strobe_time$reify__852$fn__854.invoke(nemesis.clj:216) ~[classes/:na]
        at jepsen.control$on_nodes$fn__2116.invoke(control.clj:372) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) [clojure-1.8.0.jar:na]
        at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.8.0.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:646) [clojure-1.8.0.jar:na]
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881) [clojure-1.8.0.jar:na]
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881) [clojure-1.8.0.jar:na]
        at clojure.lang.RestFn.applyTo(RestFn.java:142) [clojure-1.8.0.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:650) [clojure-1.8.0.jar:na]
        at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911) [clojure-1.8.0.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.8.0.jar:na]
        at jepsen.util$real_pmap$launcher__1168$fn__1169.invoke(util.clj:49) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
        at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) ~[clojure-1.8.0.jar:na]
        at clojure.lang.AFn.call(AFn.java:18) [clojure-1.8.0.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_312]
        ... 1 common frames omitted
INFO [2022-01-07 21:53:51,212] jepsen nemesis - jepsen.util :nemesis    :info   ["strobe-skews" :start] nil     indeterminate: sudo -S -u root bash -x -c "c


STDERR:
+ cd /
+ /opt/jepsen/strobe-time 200 10 10
settimeofday: Invalid argument
```

**Comment by aliher1911** [comment]
Fixed by https://github.com/cockroachdb/jepsen/pull/32
