### ISSUE TITLE
server: TestServeIndexHTML fails under Go 1.17.6

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#74657]
First observed in https://github.com/cockroachdb/cockroach/pull/74655:

```
=== RUN   TestServeIndexHTML
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/5af90cb183adf3be59aa2645ef0012f2/logTestServeIndexHTML2606840330
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestServeIndexHTML
    server_test.go:945: -- test log scope end --
    server_test.go:945: Leaked goroutine: goroutine 67965 [select]:
        net/http.setRequestCancel.func4()
          GOROOT/src/net/http/client.go:398 +0x94
        created by net/http.setRequestCancel
          GOROOT/src/net/http/client.go:397 +0x43e
--- FAIL: TestServeIndexHTML (6.50s)
```

This blocks the Go upgrade (#74617).

**Comment by knz** [comment]
This, sadly, is a new upstream regression: https://github.com/golang/go/issues/50652
