### ISSUE TITLE
logs FATAL and ERROR show activity upon 3rd node joining cluster

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#7472]
* I started 1 cockroach node on cr1, and added some data to it. I killed it and restarted it to stress it, confirming that data was present afterwards. It seemed fine.
* I started a 2nd node, on cr2, joining it to the cluster.  I check the logs, no goroutine crashes at this point.
* After I started a 3rd node, a check of the error and fatal logs revealed activity that seems to be of some concern -- a goroutine crash.

Details:
```
 node cr1 started as:
$ cockroach start --insecure --host=cr1 --background
 node cr2 started as:
$ cockroach start --insecure --join=cr1:26257 --background 
 node cr3 started as:
$ cockroach start --insecure --join=cr1:26257 --background
```

details:
Running on linux/amd64 Centos7.2 [digital ocean, three 512MB droplets] using cockroach-beta-20160616.linux-amd64.tgz

config for each cluster node:
```
[jaten@cr1 logs]$ grep -F '[config]' ~/cockroach-data/logs/cockroach.INFO
I160625 16:52:59.421856 util/log/clog.go:998  [config] file created at: 2016/06/25 16:52:59
I160625 16:52:59.421856 util/log/clog.go:998  [config] running on machine: cr1
I160625 16:52:59.421856 util/log/clog.go:998  [config] binary: CockroachDB beta-20160616 (linux amd64, built 2016/06/16 16:51:45, go1.6.2)
I160625 16:52:59.421856 util/log/clog.go:998  [config] arguments: [cockroach start --insecure --host=cr1]
[jaten@cr1 logs]$ 

[jaten@cr2 logs]$ grep -F '[config]' ~/cockroach-data/logs/cockroach.INFO
I160625 16:58:00.945049 util/log/clog.go:998  [config] file created at: 2016/06/25 16:58:00
I160625 16:58:00.945049 util/log/clog.go:998  [config] running on machine: cr2
I160625 16:58:00.945049 util/log/clog.go:998  [config] binary: CockroachDB beta-20160616 (linux amd64, built 2016/06/16 16:51:45, go1.6.2)
I160625 16:58:00.945049 util/log/clog.go:998  [config] arguments: [cockroach start --insecure --join=cr1:26257]
[jaten@cr2 logs]$ 

[jaten@cr3 logs]$ grep -F '[config]' ~/cockroach-data/logs/cockroach.INFO
I160625 17:05:55.596839 util/log/clog.go:998  [config] file created at: 2016/06/25 17:05:55
I160625 17:05:55.596839 util/log/clog.go:998  [config] running on machine: cr3
I160625 17:05:55.596839 util/log/clog.go:998  [config] binary: CockroachDB beta-20160616 (linux amd64, built 2016/06/16 16:51:45, go1.6.2)
I160625 17:05:55.596839 util/log/clog.go:998  [config] arguments: [cockroach start --insecure --join=cr1:26257]
[jaten@cr3 logs]$ 
```

the contents of logs/cockroach.FATAL on cr1:
```
[jaten@cr1 logs]$ cat cockroach.FATAL 
F160625 17:05:59.446242 util/log/clog.go:998  [config] file created at: 2016/06/25 17:05:59
F160625 17:05:59.446242 util/log/clog.go:998  [config] running on machine: cr1
F160625 17:05:59.446242 util/log/clog.go:998  [config] binary: CockroachDB beta-20160616 (linux amd64, built 2016/06/16 16:51:45, go1.6.2)
F160625 17:05:59.446242 util/log/clog.go:998  [config] arguments: [cockroach start --insecure --host=cr1]
F160625 17:05:59.446242 util/log/clog.go:998  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu file:line msg
F160625 17:05:59.446189 storage/replica.go:2492  [node=1,store=1,range=1] store 1 belongs to cluster {f11f329d-5126-4e8b-b271-581899e0cd6c}, but attempted to join cluster df6a16ff-ece4-4faf-83d5-3669e3861573 via gossip
goroutine 35 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xecf00e900, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:862 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x28ca720, 0xc800000003, 0x22df244, 0x12, 0x9bc, 0xc8201b11e0, 0xa9)
    /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:726 +0x178
github.com/cockroachdb/cockroach/util/log.addStructured(0x7faeeaa505a8, 0xc8213c73e0, 0x3, 0x2, 0x1c478c0, 0x4b, 0xc8208c5c80, 0x3, 0x3)
    /go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x7faeeaa505a8, 0xc8213c73e0, 0x1, 0xc800000003, 0x1c478c0, 0x4b, 0xc8208c5c80, 0x3, 0x3)
    /go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalc(0x7faeeaa505a8, 0xc8213c73e0, 0x1c478c0, 0x4b, 0xc8208c5c80, 0x3, 0x3)
    /go/src/github.com/cockroachdb/cockroach/util/log/log.go:165 +0x71
github.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc820510480, 0x2918540)
    /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2492 +0x46c
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc820370500, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/storage/store.go:1091 +0x210
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
    /go/src/github.com/cockroachdb/cockroach/storage/store.go:1048 +0x269
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202d4310, 0xc8202dbd20)
    /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
    /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
[jaten@cr1 logs]$ 
```

the contents of logs/cockroach.ERROR
```
[jaten@cr1 logs]$ cat cockroach.ERROR 
E160625 16:56:04.035104 util/log/clog.go:998  [config] file created at: 2016/06/25 16:56:04
E160625 16:56:04.035104 util/log/clog.go:998  [config] running on machine: cr1
E160625 16:56:04.035104 util/log/clog.go:998  [config] binary: CockroachDB beta-20160616 (linux amd64, built 2016/06/16 16:51:45, go1.6.2)
E160625 16:56:04.035104 util/log/clog.go:998  [config] arguments: [cockroach start --insecure --host=cr1]
E160625 16:56:04.035104 util/log/clog.go:998  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu file:line msg
E160625 16:56:04.035102 storage/raft_transport.go:262  failed to send Raft snapshot to node 2 at cr2:26257: rpc error: code = 1 desc = context canceled
E160625 16:56:04.035701 storage/raft_transport.go:262  failed to send Raft snapshot to node 2 at cr2:26257: rpc error: code = 1 desc = context canceled
E160625 16:56:06.747554 storage/queue.go:449  [replicate] range=2 [/Table/11-/Table/12): error: storage/replica_command.go:2688: change replicas of 2 failed: context deadline exce\
eded
E160625 17:03:04.447757 storage/queue.go:514  [replicate] 4 replicas failing with "0 of 2 stores with an attribute matching []; likely not enough nodes in cluster"
F160625 17:05:59.446189 storage/replica.go:2492  [node=1,store=1,range=1] store 1 belongs to cluster {f11f329d-5126-4e8b-b271-581899e0cd6c}, but attempted to join cluster df6a16ff\
-ece4-4faf-83d5-3669e3861573 via gossip
goroutine 35 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xecf00e900, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:862 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x28ca720, 0xc800000003, 0x22df244, 0x12, 0x9bc, 0xc8201b11e0, 0xa9)
    /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:726 +0x178
github.com/cockroachdb/cockroach/util/log.addStructured(0x7faeeaa505a8, 0xc8213c73e0, 0x3, 0x2, 0x1c478c0, 0x4b, 0xc8208c5c80, 0x3, 0x3)
    /go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x7faeeaa505a8, 0xc8213c73e0, 0x1, 0xc800000003, 0x1c478c0, 0x4b, 0xc8208c5c80, 0x3, 0x3)
    /go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalc(0x7faeeaa505a8, 0xc8213c73e0, 0x1c478c0, 0x4b, 0xc8208c5c80, 0x3, 0x3)
    /go/src/github.com/cockroachdb/cockroach/util/log/log.go:165 +0x71
github.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc820510480, 0x2918540)
    /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2492 +0x46c
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc820370500, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/storage/store.go:1091 +0x210
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
    /go/src/github.com/cockroachdb/cockroach/storage/store.go:1048 +0x269
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202d4310, 0xc8202dbd20)
    /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
    /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
[jaten@cr1 logs]$ 
```

**Comment by glycerine** [comment]
Attaching the full data directories, in case this is of help:
[data-dirs.3nodes.tar.gz](https://github.com/cockroachdb/cockroach/files/333296/data-dirs.3nodes.tar.gz)

**Comment by tschottdorf** [comment]
Hi Jason,

from the logs I see that only one cluster was initialized:

```
$ grep -R 'has been created' .
./cr1/cockroach-data/logs/cockroach.cr1.jaten.log.INFO.2016-06-25T16_18_37-04_00.21370:I160625 16:18:37.838249 server/node.go:327  **** cluster {f11f329d-5126-4e8b-b271-581899e0cd6c} has been created
```

but the error message mentions a cluster `df6a16ff-ece4-4faf-83d5-3669e3861573`.

Were you perhaps running a node from a previous test cluster concurrently with the new one, so that they may have cross-joined? (Accidentally) linking together two separate clusters is what is indicated in the error message.

**Comment by glycerine** [comment]
Hi Tobias, 

Well drat. That does seem to point to user error on my part. Sorry about that.

I tried it again, deleting the data directories first. I only get a "failed to send Raft snapshot to node 3" upon joining the 3rd node in.  I guess this might be expected?

```
[jaten@cr1 logs]$ cat cockroach.ERROR 
E160625 18:01:29.914000 util/log/clog.go:998  [config] file created at: 2016/06/25 18:01:29
E160625 18:01:29.914000 util/log/clog.go:998  [config] running on machine: cr1
E160625 18:01:29.914000 util/log/clog.go:998  [config] binary: CockroachDB beta-20160616 (linux amd64, built 2016/06/16 16:51:45, go1.6.2)
E160625 18:01:29.914000 util/log/clog.go:998  [config] arguments: [cockroach start --insecure --host=cr1]
E160625 18:01:29.914000 util/log/clog.go:998  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu file:line msg
E160625 18:01:29.913999 storage/raft_transport.go:262  failed to send Raft snapshot to node 3 at cr3:26257: rpc error: code = 1 desc = context canceled
E160625 18:01:29.914476 storage/raft_transport.go:262  failed to send Raft snapshot to node 3 at cr3:26257: rpc error: code = 1 desc = context canceled
[jaten@cr1 logs]$ 
```

**Comment by tschottdorf** [comment]
No worries.
Yes, that snapshot error may happen occasionally, though I would not have expected it on an empty cluster.

**Comment by glycerine** [comment]
Well I had made a database, a table, and a single row.

**Comment by glycerine** [comment]
Closing this out.

**Comment by tschottdorf** [comment]
Thanks Jason. Even with a single table single row that's a bit surprising, but I think it might be #7372. When that is fixed, I would expect that error only for large datasets during heavy rebalances.
