### ISSUE TITLE
tools: support the Vendure framework

### ISSUE THREAD

**Issue by vaibhavsanap** [cockroachdb/cockroach#74796]
Describe the bug
Unable to connect to cockroachDB from vendure worker 

To Reproduce
1. Deploy cockroachDB using operator(cockroachdb/cockroach:v21.1.11)
2. Deploy vendure with cockroachDB as database for it

Expected behaviour
Vendure worker and server should run as expected

Environment 
1. cockroachdb/cockroach:v21.1.11
2. vendure = ^1.0.0

Vendure worker is crashing in loop with following error

`(node:29) UnhandledPromiseRejectionWarning: LockNotSupportedOnGivenDriverError: Locking not supported on given driver.
    at new LockNotSupportedOnGivenDriverError (/usr/src/app/node_modules/typeorm/error/LockNotSupportedOnGivenDriverError.js:10:28)
    at SelectQueryBuilder.createLockExpression (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1254:27)
    at SelectQueryBuilder.getQuery (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:54:21)
    at SelectQueryBuilder.QueryBuilder.getQueryAndParameters (/usr/src/app/node_modules/typeorm/query-builder/QueryBuilder.js:243:26)
    at SelectQueryBuilder.<anonymous> (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1594:50)
    at step (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at /usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:111:16)
(Use `node --trace-warnings ...` to show where the warning was created)`

**Comment by msbutler** [comment]
seems like vendure is built on graphql, which currently does not support crdb. https://github.com/hasura/graphql-engine/issues/678

**Comment by rafiss** [comment]
In this case it looks like the error is coming from TypeORM, specifically here: https://github.com/typeorm/typeorm/blob/90a8deb6383c31686965893cdea96151f40be396/src/query-builder/SelectQueryBuilder.ts#L1699

@vaibhavsanap can you please sure the version of TypeORM you are using?

Most likely the problem is that your app is generating a query using syntax we don't support; see https://github.com/cockroachdb/cockroach/issues/40476

Consider filing an issue with the vendure project, to see if they can add CockroachDB support. cc @kernfeld-cockroach

**Comment by vaibhavsanap** [comment]
@rafiss  we are able o integrate cockroachDB with vendure. 
Above issue disappeared once we started using BullMQPlugin

**Comment by rafiss** [comment]
Glad to hear it!
