### ISSUE TITLE
storage: intermittent up-replication stalls

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#7489]
Build: 624c68b521cb00f162408a6935e77bf55901edaf

One way to reproduce this is to run the acceptance test `TestUpreplicate1to3Small`.

For example, my test cluster was stuck in this state for 2-3 minutes, well beyond any of the reservation timeouts we have.

<img width="1430" alt="screenshot 2016-06-27 14 58 27" src="https://cloud.githubusercontent.com/assets/1564582/16392016/d1375510-3c77-11e6-8f4c-8f028d3abaee.png">

When left alone, up-replication does complete after several more minutes (which is much slower than it should be).

This seems to correlate with the following log entries, which occur as replica adds are being logged to `rangelog` but replica counts aren't going up:

```
I160627 19:00:39.169135 storage/replica.go:1793  applying command with forced error: storage/replica.go:1714: no-op on empty Raft entry
E160627 19:00:39.169441 storage/replica.go:1804  [node=1,store=1,range=169] error executing raft command: storage/replica.go:1714: no-op on empty Raft entry
```

Full logs: [stall_logs.zip](https://github.com/cockroachdb/cockroach/files/335639/stall_logs.zip)

cc @petermattis @tschottdorf @BramGruneir

**Comment by tamird** [comment]
FWIW, I'm not sure those logged errors are relevant. From `storage/replica.go`:
```go
	if idKey == "" {
		// This is an empty Raft command (which is sent by Raft after elections
		// to trigger reproposals or during concurrent configuration changes).
		// Nothing to do here except making sure that the corresponding batch
		// (which is bogus) doesn't get executed (for it is empty and so
		// properties like key range are undefined).
		forcedErr = roachpb.NewErrorf("no-op on empty Raft entry")
	}
```

**Comment by tschottdorf** [comment]
No, they're not relevant (though a bit noisy). They just mean a Raft election or config change happened (so if they are all over the place for the same Raft group, it could be indicative of that group not managing to keep a leader alive).

Some other findings (looking at my 108gb 1-to-5 upreplication experiment which sees the same stalls):

```
goroutine 133 [select, 220 minutes]:
github.com/cockroachdb/cockroach/storage.(*RaftTransport).RaftMessage(0xc82049c150, 0x7feca6e42138, 0xc821317110, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/raft_transport.go:136 +0x216
github.com/cockroachdb/cockroach/storage._MultiRaft_RaftMessage_Handler(0x193ae40, 0xc82049c150, 0x7feca6e420f0, 0xc820ed4380, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/raft.pb.go:159 +0xd8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc8204b6000, 0x7feca6efae10, 0xc821d261b0, 0xc821d922a0, 0xc8204b8020, 0x2632e60, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:607 +0x47a
google.golang.org/grpc.(*Server).handleStream(0xc8204b6000, 0x7feca6efae10, 0xc821d261b0, 0xc821d922a0, 0x0)
	/go/src/google.golang.org/grpc/server.go:691 +0x114e
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc820011e30, 0xc8204b6000, 0x7feca6efae10, 0xc821d261b0, 0xc821d922a0)
	/go/src/google.golang.org/grpc/server.go:352 +0xa0
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/google.golang.org/grpc/server.go:353 +0x9a
```

This shouldn't happen - it's waiting on the error channel for a goroutine sending a message.

Similarly,

```
goroutine 226 [select, 220 minutes]:
google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc822543d10, 0xc8206f72b0, 0x5, 0x5, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/transport.go:141 +0x7e6
google.golang.org/grpc/transport.(*Stream).Read(0xc822872000, 0xc8206f72b0, 0x5, 0x5, 0x40, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/transport.go:294 +0x71
io.ReadAtLeast(0x7feca6f721b0, 0xc822872000, 0xc8206f72b0, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7feca6f721b0, 0xc822872000, 0xc8206f72b0, 0x5, 0x5, 0xc82035ba80, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
google.golang.org/grpc.(*parser).recvMsg(0xc8206f72a0, 0xc821fcb460, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/rpc_util.go:216 +0xb9
google.golang.org/grpc.recv(0xc8206f72a0, 0x7feca6e7f050, 0x29a8158, 0xc822872000, 0x0, 0x0, 0x19a0660, 0x29a8158, 0x0, 0x0)
	/go/src/google.golang.org/grpc/rpc_util.go:297 +0x45
google.golang.org/grpc.(*clientStream).RecvMsg(0xc821ff5360, 0x19a0660, 0x29a8158, 0x0, 0x0)
	/go/src/google.golang.org/grpc/stream.go:234 +0xac
github.com/cockroachdb/cockroach/storage.(*multiRaftRaftMessageClient).RecvMsg(0xc822ad12c0, 0x19a0660, 0x29a8158, 0x0, 0x0)
	<autogenerated>:221 +0x6f
github.com/cockroachdb/cockroach/storage.(*RaftTransport).processQueue.func1.1()
	/go/src/github.com/cockroachdb/cockroach/storage/raft_transport.go:189 +0x79
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820370460, 0xc8206f72c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:142 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:143 +0x62

goroutine 215 [select, 220 minutes]:
google.golang.org/grpc.NewClientStream.func1(0x7feca6f720e0, 0xc8201b43c0, 0xc820160380, 0xc8201ca780)
	/go/src/google.golang.org/grpc/stream.go:151 +0x258
created by google.golang.org/grpc.NewClientStream
	/go/src/google.golang.org/grpc/stream.go:159 +0xab2
```

and certainly this one too suggests things going awry:

```

goroutine 29 [select, 177 minutes]:
github.com/cockroachdb/cockroach/storage.(*Replica).redirectOnOrAcquireLeaderLease(0xc82099f860, 0x7feca6f58bb8, 0xc85058aea0, 0xc82da686c0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:522 +0x484
github.com/cockroachdb/cockroach/storage.(*baseQueue).processReplica(0xc820166dd0, 0xc82099f860, 0xc82035ba80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:434 +0x65a
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1.1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:389 +0x4e
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc820370460, 0xc82198de78, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:169 +0xf3
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:393 +0x275
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820370460, 0xc820012300)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:142 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:143 +0x62
```

This last one might be a Replica which should have been gc'ed at some point (due to having rebalanced away; I'm looking at node1) but which isn't making progress on that front? That's a bit odd since #7404 is already in that version. I would expect the GC queue to throw this thing away and the in-flight request being cancelled, but I have to look more into what state this range actually is in. I hope I can pull something out of the /debug/ranges endpoint.

**Comment by tamird** [comment]
Yikes, 220 minutes in that state? Looks like network shenanigans are not being handled. It's possible #7494 will help with this.

**Comment by tschottdorf** [comment]
I should add that `220min` is also the total uptime of that process, so it lost it pretty early in.

**Comment by tschottdorf** [comment]
Yeah, I think the leader lease command is stuck on a replica which has rebalanced away and doesn't know it. One pending command, permanent candidate state, lease expiration `6/27/2016, 10:06:33 AM GMT-4:00 DST`:

```
 {
      "span": {
        "start_key": "/Table/51/1/3350589697967382398/\"15eecf25-c738-4df9-84ac-9425f09eea4f\"/1968766",
        "end_key": "/Table/51/1/3355203320546184858/\"0f015912-5ed4-4b40-b872-73703d75d307\"/216550"
      },
      "raft_state": "StateCandidate",
      "state": {
        "state": {
          "raft_applied_index": "12472",
          "lease_applied_index": "10",
          "desc": {
            "range_id": "629",
            "start_key": "u4n9Ln+vk/9t334SMTVlZWNmMjUtYzczOC00ZGY5LTg0YWMtOTQyNWYwOWVlYTRmAAH4Hgp+",
            "end_key": "u4n9LpATpLZdzpoSMGYwMTU5MTItNWVkNC00YjQwLWI4NzItNzM3MDNkNzVkMzA3AAH4A03m",
            "replicas": [
              {
                "node_id": 1,
                "store_id": 1,
                "replica_id": 1
              },
              {
                "node_id": 2,
                "store_id": 2,
                "replica_id": 2
              },
              {
                "node_id": 5,
                "store_id": 5,
                "replica_id": 3
              },
              {
                "node_id": 3,
                "store_id": 3,
                "replica_id": 4
              }
            ],
            "next_replica_id": 5
          },
          "lease": {
            "start": {
              "wall_time": "1467035220486909109",
              "logical": 1
            },
            "start_stasis": {
              "wall_time": "1467036393343212565",
              "logical": 0
            },
            "expiration": {
              "wall_time": "1467036393593212565",
              "logical": 0
            },
            "replica": {
              "node_id": 1,
              "store_id": 1,
              "replica_id": 1
            }
          },
          "truncated_state": {
            "index": "12372",
            "term": "6"
          },
          "gc_threshold": {
            "wall_time": "0",
            "logical": 0
          },
          "stats": {
            "last_update_nanos": "1467036392010741449",
            "intent_age": "0",
            "gc_bytes_age": "0",
            "live_bytes": "57461017",
            "live_count": "51820",
            "key_bytes": "3548292",
            "key_count": "51820",
            "val_bytes": "53912725",
            "val_count": "51820",
            "intent_bytes": "0",
            "intent_count": "0",
            "sys_bytes": "2719",
            "sys_count": "10"
          },
          "frozen": false
        },
        "lastIndex": "12472",
        "num_pending": "1"
      }
    },
```

(from http://104.196.35.16:8080/_status/ranges/local)

It's conceivable that that would block the replicate queue (first pass rebalances it away, second pass gets stuck forever). I'll try to find out what the GC queue is doing.

Note to self: checking for ranges which have a wildly expired leader lease and a pending command is a good heuristic for finding problematic ones.

**Comment by tschottdorf** [comment]
btw @d4l3k, the Raft frontend picks this one up but doesn't show the descriptor for node1 (though it's still there, as copy-pasted above). Probably a small bug in the logic here.

<img width="1314" alt="screen shot 2016-06-27 at 6 09 07 pm" src="https://cloud.githubusercontent.com/assets/5076964/16397408/49d74466-3c92-11e6-8d6d-02b65eb60762.png">

**Comment by tschottdorf** [comment]
The GC queue was considering ranges regularly as it should (though not adding any, and I wasn't able to find that particular range in the events endpoint, likely because I didn't get lucky the 20x I tried)

**Comment by tschottdorf** [comment]
Oh. The ReplicaGCQueue uses a 10 days (!) timeout. That's (for that situation) crazy, given that we're going to get stuck here all the time. That might already be the root cause of the problem - maybe a smart heuristic can help if we don't want to turn that wayyy down: when we time out trying to get the leader lease, i.e. when the in-flight request's expiration passes, and the Raft group is in CANDIDATE state, then there's a good chance we ought to be looking at that thing even if it's not old.

For now, I'll try to fiddle with env vars to see whether a lower timeout unblocks it all.

**Comment by tschottdorf** [comment]
I'm working on a prototype to improve the situation here (using a heuristic to add replicas in candidate state to the queue more eagerly). It's important that we don't let the GC queue do too much work, but it is currently too lazy.

**Comment by tschottdorf** [comment]
Even with my last stop-gap commit #7533 I see stalls, sometimes for minutes at a time.

```
60629 17:57:34.148424 acceptance/allocator_test.go:269  last range event: add for range 255/store 2 (1m2.409707s ago)
I160629 17:57:44.222534 acceptance/allocator_test.go:269  last range event: add for range 255/store 2 (1m12.474808s ago)
I160629 17:57:54.291151 acceptance/allocator_test.go:269  last range event: add for range 255/store 2 (1m22.545515s ago)
I160629 17:58:04.363038 acceptance/allocator_test.go:269  last range event: add for range 255/store 2 (1m32.615134s ago)
I160629 17:58:14.430423 acceptance/allocator_test.go:269  last range event: add for range 255/store 2 (1m42.69034s ago)
I160629 17:58:24.493096 acceptance/allocator_test.go:269  last range event: add for range 255/store 2 (1m52.75455s ago)
I160629 17:58:34.565097 acceptance/allocator_test.go:269  last range event: add for range 255/store 2 (2m2.815615s ago)
I160629 17:58:44.630415 acceptance/allocator_test.go:269  last range event: add for range 255/store 2 (2m12.88642s ago)
I160629 17:58:54.689631 acceptance/allocator_test.go:269  last range event: add for range 255/store 2 (2m22.953054s ago)
I160629 17:59:04.749260 acceptance/allocator_test.go:269  last range event: add for range 255/store 2 (2m33.012636s ago)
```

The events endpoint has these:

```
22:01:30.467898	2.294713	... range=223 [/Table/51/1/8890508768364113222/"312a44b5-3019-45ee-9fcf-896c87d5544a"/831-/Table/51/1/8925628962213292420/"a73ca9fb-b64f-4219-b8a8-a76e652b0190"/1000): adding: priority=1001.000
22:01:30.469767	 .  1869	... range=223 [/Table/51/1/8890508768364113222/"312a44b5-3019-45ee-9fcf-896c87d5544a"/831-/Table/51/1/8925628962213292420/"a73ca9fb-b64f-4219-b8a8-a76e652b0190"/1000): processing
22:01:31.223476	 .753710	... range=223 [/Table/51/1/8890508768364113222/"312a44b5-3019-45ee-9fcf-896c87d5544a"/831-/Table/51/1/8925628962213292420/"a73ca9fb-b64f-4219-b8a8-a76e652b0190"/1000): adding: priority=1000.000
22:01:31.223509	 .    33	... range=223 [/Table/51/1/8890508768364113222/"312a44b5-3019-45ee-9fcf-896c87d5544a"/831-/Table/51/1/8925628962213292420/"a73ca9fb-b64f-4219-b8a8-a76e652b0190"/1000): done: 753.606346ms
22:01:31.223596	 .    87	... range=223 [/Table/51/1/8890508768364113222/"312a44b5-3019-45ee-9fcf-896c87d5544a"/831-/Table/51/1/8925628962213292420/"a73ca9fb-b64f-4219-b8a8-a76e652b0190"/1000): processing
22:01:32.764784	1.541188	... range=26 [/Table/51/1/8925628962213292420/"a73ca9fb-b64f-4219-b8a8-a76e652b0190"/1000-/Table/51/1/8964570231838034092/"1d590643-7650-4aca-8900-63bb6f54b750"/980): adding: priority=0.000
22:01:34.288404	1.523620	.E. on range=223 [/Table/51/1/8890508768364113222/"312a44b5-3019-45ee-9fcf-896c87d5544a"/831-/Table/51/1/8925628962213292420/"a73ca9fb-b64f-4219-b8a8-a76e652b0190"/1000): change replicas of 223 failed: context deadline exceeded
```

which roughly coincide with the following stall:

```
I160629 18:00:15.197828 acceptance/allocator_test.go:269  last range event: add for range 264/store 3 (56.40139s ago)
I160629 18:00:25.258619 acceptance/allocator_test.go:269  last range event: add for range 264/store 3 (1m6.462403s ago)
I160629 18:00:35.318997 acceptance/allocator_test.go:269  last range event: add for range 264/store 3 (1m16.524015s ago)
I160629 18:00:45.379193 acceptance/allocator_test.go:269  last range event: add for range 264/store 3 (1m26.584062s ago)
I160629 18:00:55.441415 acceptance/allocator_test.go:269  last range event: add for range 264/store 3 (1m36.646329s ago)
I160629 18:01:05.501696 acceptance/allocator_test.go:269  last range event: add for range 264/store 3 (1m46.705274s ago)
I160629 18:01:15.563430 acceptance/allocator_test.go:269  last range event: add for range 264/store 3 (1m56.76754s ago)
I160629 18:01:25.632587 acceptance/allocator_test.go:269  last range event: add for range 264/store 3 (2m6.82991s ago)
```

I think the key to understanding better what is happening here lies in the tracing endpoint:

```
Family: tracing

[Normal/Summary] [Normal/Expanded] [Traced/Summary] [Traced/Expanded]
Completed Requests
When	Elapsed (s)
2016/06/29 21:54:25.208283	61.004080	replicate
21:54:25.208300	 .    18	... request range lease (attempt #1)
2016/06/29 21:51:25.870491	60.580638	replicate
21:51:25.870504	 .    13	... request range lease (attempt #1)
2016/06/29 21:46:20.157633	59.995402	replicate
21:46:20.157647	 .    14	... request range lease (attempt #1)
2016/06/29 21:43:54.532613	60.788765	replicate
21:43:54.532623	 .    10	... request range lease (attempt #1)
2016/06/29 21:42:50.926146	59.099630	replicate
21:42:50.926158	 .    12	... request range lease (attempt #1)
2016/06/29 21:39:42.464974	59.564111	replicate
21:39:42.464987	 .    13	... request range lease (attempt #1)
2016/06/29 21:33:53.011499	60.331981	replicate
21:33:53.011520	 .    20	... request range lease (attempt #1)
2016/06/29 21:32:14.134260	59.485853	replicate
21:32:14.134274	 .    13	... request range lease (attempt #1)
2016/06/29 21:24:25.345190	13.424997	replicate
21:24:25.345207	 .    17	... request range lease (attempt #1)
2016/06/29 21:23:22.972881	62.568762	replicate
21:23:22.972887	 .     6	... request range lease (attempt #1)
```

Various replications take exactly one minute, which is very telling, but no tracing exists inside of the actual logic. Should be a massive and easy win to plumb the trace in there.

**Comment by petermattis** [comment]
Aren't those event logs indicating that acquiring the leader lease is taking ~60s? Unless I'm misreading, the only place we create a span named `replicate` is for the duration of leader lease acquisition.

**Comment by tschottdorf** [comment]
I haven't had a chance to check, but that could be - wonder what makes it take that long?

**Comment by tschottdorf** [comment]
A minute always sounds suspicious like gossiping, for example, the first range. I can't lend credibility to that theory from the phone, but that's a candidate. Rebalancing lease holders away is an expected troublemaker, too. @bram, could you take a look as part of #7535? That issue as written now assumed that we were missing out on most of the interesting tracepoints (and we do as we likely don't trace the actual change at all, only the leader lease acquisition), which isn't strictly true if the lease acquisition is actually the slow part, but still definitely improvable.

**Comment by petermattis** [comment]
Agreed that a minute sounds like it could be the first-range gossip problem. So this is possibly related to #7297. @paperstreet It's looking like this is fairly important.

**Comment by tschottdorf** [comment]
Small update - I'm not sure it's the leader lease at all - #7535 would tell. We do create the span for getting the leader lease, but we finish it only when the queue has processed the replica (which could take any amount of time). So in the above traces, it's also conceivable that the replication really did take 99% of the time. So, doing #7535 looks most important.

**Comment by tschottdorf** [comment]
@BramGruneir: Assigned you. Should be relatively straightforward to tell once your queue tracing changes are in (you're running rebalances anyway, right :))

**Comment by BramGruneir** [comment]
I'm excited to take a crack at it actually.  Want to see where the
bottleneck is.

**Comment by tschottdorf** [comment]
Spending a lot of time getting the range lease:

```
2016/07/19 14:04:14.119595	53.695245	replicate:1950
14:04:14.119608	 .    13	... request range lease (attempt #1)
14:05:02.906885	48.787277	... request range lease (attempt #2)
14:05:02.910654	 .  3769	... got range lease
14:05:02.910788	 .   134	... adding a new replica
14:05:02.910843	 .    52	... (2 events discarded)
14:05:02.911614	 .   772	... reservation granted
14:05:04.369512	1.457898	... generated snapshot
14:05:04.369518	 .     6	... starting txn
14:05:07.814744	3.445226	... txn complete
14:05:07.814839	 .    95	... done
```

**Comment by tschottdorf** [comment]
potentially long snapshot generation (though the 1 minute inbetween suggests that something that wasn't caught by a tracepoint ran a 1min timeout; perhaps some gossip issue?)

```
2016/07/19 14:36:22.964148	61.982447	replicate:106
14:36:22.964158	 .    10	... request range lease (attempt #1)
14:36:22.966236	 .  2078	... got range lease
14:36:22.966323	 .    87	... considering a rebalance
14:36:22.966384	 .    61	... rebalancing to {NodeID:3 StoreID:3 ReplicaID:0}
14:36:22.966387	 .     3	... requesting reservation
14:36:22.966990	 .   603	... reservation granted
14:37:24.896879	61.929889	... generated snapshot
14:37:24.896885	 .     6	... starting txn
14:37:24.946447	 . 49563	... txn complete
14:37:24.946593	 .   146	... done
```

**Comment by petermattis** [comment]
Not a lot of code between the `reservation granted` and `generated snapshot` trace entries. I suspect what is happening is we're in the retry loop of `Replica.GetSnapshot` waiting for other snapshots to complete. Would be straightforward to add a trace entry when we're retrying waiting for `Store.AcquireRaftSnapshot` to let us proceed.

I understand why `Replica.Snapshot` can't block waiting for permission to generate a snapshot, but `Replica.GetSnapshot` could. We should get rid of the retry loop there and have some blocking call to `Store` to get the snapshot token.

**Comment by tschottdorf** [comment]
A general taste of the speed of things:

```
I160719 12:38:12.692115 acceptance/allocator_test.go:292  last range event: remove for range 1934/store 1 (48.316007s ago)
I160719 12:38:23.117732 acceptance/allocator_test.go:292  last range event: remove for range 1934/store 1 (58.784375s ago)
I160719 12:38:33.543712 acceptance/allocator_test.go:292  last range event: remove for range 307/store 1 (7.235473s ago)
I160719 12:38:43.965666 acceptance/allocator_test.go:292  last range event: remove for range 307/store 1 (17.664567s ago)
I160719 12:38:54.373967 acceptance/allocator_test.go:292  last range event: remove for range 307/store 1 (28.083839s ago)
I160719 12:39:04.774406 acceptance/allocator_test.go:292  last range event: remove for range 307/store 1 (38.494125s ago)
```

**Comment by petermattis** [comment]
Well that's not good. Does it start off at that speed or degrade over time?

**Comment by tschottdorf** [comment]
I think it degrades. This is from very early:

```
I160719 07:32:29.197832 acceptance/allocator_test.go:292  last range event: add for range 1163/store 3 (3.618528s ago)
I160719 07:33:03.988139 acceptance/allocator_test.go:292  last range event: add for range 536/store 1 (4.857284s ago)
I160719 07:33:14.287097 acceptance/allocator_test.go:292  last range event: add for range 1897/store 1 (346.255ms ago)
I160719 07:33:24.557413 acceptance/allocator_test.go:292  last range event: add for range 176/store 2 (2.187561s ago)
```

There are probably some insanely low-hanging fruit here. Somewhat surprisingly, I didn't see many gc'able replicas (at least not judging from http://104.196.46.121:8080/#/raft/ranges?_k=jn4mqv), the gcqueue-on-speed must be doing a reasonable job with the stop-gaps I put in a while ago (though we should still do the event-driven thing sooner than later).

Btw, wont 1-to-x upreplication essentially not work when we disallow moving the lease holder? After all, the replicate queue requires that a lease be held, so how do we get from 1 to 2 replicas?

**Comment by petermattis** [comment]
We're going to disallow removing the lease holder. Adding a new replica (i.e. moving from 1 to 2 replicas) will be unaffected.

**Comment by petermattis** [comment]
Are the instructions in `allocator_test.go` still accurate for running this test?

**Comment by tschottdorf** [comment]
Ah, duh. Yes, they are.

**Comment by BramGruneir** [comment]
See #7918 for disallowing the lease holder from being down replicated.

I'll plumb some tracing into the snapshot generation to see if we can get closer to the cause of the delays.

**Comment by cuongdo** [comment]
I don't see these any more in my most recent allocator test runs. They were probably addressed by some subset of the many Raft improvements that have been made.
