### ISSUE TITLE
streamer: no bytes in account to release

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#75299]
ccl/logictestccl.TestTenantLogic [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4149826&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4149826&tab=artifacts#/) on master @ [912964e02ddd951c77d4f71981ae18b3894e9084](https://github.com/cockroachdb/cockroach/commits/912964e02ddd951c77d4f71981ae18b3894e9084):

Fatal error:

```
panic: streamer-2-unlimited-4: no bytes in account to release, current 1024, free 1025 [recovered]
	panic: streamer-2-unlimited-4: no bytes in account to release, current 1024, free 1025

```
Stack: 

```
goroutine 141601611 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc01487ccf0, {0x5fcc2d8, 0xc01c3441a0})
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:251 +0x94
panic({0x48b38e0, 0xc019752528})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic({0x5fcc2d8, 0xc01c3441a0}, 0xc01954a000, {0x4d39956, 0x5}, {0xc028199a08, 0x45bab00, 0xc02c693bc0})
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:376 +0x1af
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink(0xc0236e3f38, {0x5fcc2d8, 0xc01c3441a0}, 0x401)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:636 +0x127
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*budget).release(0xc02c693bc0, {0x5fcc2d8, 0xc01c3441a0}, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/budget.go:117 +0xb0
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*workerCoordinator).performRequestAsync.func1({0x5fcc2d8, 0xc01c3441a0})
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/streamer.go:1025 +0x3af
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:488 +0x12a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:478 +0x445
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestTenantLogic/3node-tenant/cast/assignment_casts_insert_do_update
*
* ERROR: a panic has occurred!
* streamer-2-unlimited-4: no bytes in account to release, current 1024, free 1025
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	/usr/local/go/src/runtime/panic.go:1038
*   | [...repeated from below...]
* Wraps: (2) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:374
*   | github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:636
*   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*budget).release
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/budget.go:117
*   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*workerCoordinator).performRequestAsync.func1
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/streamer.go:1025
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:488
*   | runtime.goexit
*   | 	/usr/local/go/src/runtime/asm_amd64.s:1581
* Wraps: (3) streamer-2-unlimited-4: no bytes in account to release, current 1024, free 1025
* Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *errutil.leafError
*
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantLogic.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

_Originally posted by @cockroach-teamcity in https://github.com/cockroachdb/cockroach/issues/63466#issuecomment-1016133270_

**Comment by rytaft** [comment]
cc @yuzefovich

**Comment by yuzefovich** [comment]
dup of #74898
