### ISSUE TITLE
insert on table "customer" violates foreign key constraint with SERIAL mapping to Java Integer type

### ISSUE THREAD

**Issue by rbygrave** [cockroachdb/cockroach#75927]
**Describe the problem**

io.ebean.DataIntegrityException: Error[ERROR: insert on table "customer" violates foreign key constraint "fk_customer_billing_address_id"   Detail: Key (billing_address_id)=(176979969) is not present in table "address".]

The underlying issue causing this error is when a Cockroach `SERIAL` column is mapped back to a Java `int/Integer` type. In this case there is number overflow and the client does not get the correct value back via JDBC/GetGeneratedKeys, and hence tries to use that value as a foreign key value for a later insert and hence the error.

**Workaround / Fix**

The workaround / fix is to make sure that Cockroach `SERIAL` columns to mapped to Java `long` or `Long` (or bigger).

Noting that Postgres has 3 serial types - `bigserial`, `serial` and `smallserial` and with Cockroach currently these are all alias to one type - `serial` which I'd say is more a match for Postgres `bigserial`. Having hit this issue I think there is a chance that people porting JDBC applications from Postgres to Cockroach hit this issue when the app is using Java `int` or `Integer` types for `SERIAL` columns.

**To Reproduce**

```sql
create table address (
  id                            serial not null,
  line1                         varchar(255),
  line2                         varchar(255),
  constraint pk_address primary key (id)
);

create table customer (
  id                            uuid not null,
  name                          varchar(255),
  billing_address_id            integer,
  constraint pk_customer primary key (id)
);

create index ix_customer_billing_address_id on customer (billing_address_id);
alter table customer add constraint fk_customer_billing_address_id foreign key (billing_address_id) references address (id) on delete restrict on update restrict;

```

Mapping using Ebean ORM
```java
@Entity
public class Address {

    @Id int id;
    final String line1;
    final String line2;

    public Address(String line1, String line2) {
        this.line1 = line1;
        this.line2 = line2;
    }
}
@Entity
public class Customer extends Model {

    @Id UUID id;
    final String name;

    @ManyToOne(cascade = CascadeType.ALL)
    Address billingAddress;

    public Customer(String name) {
        this.name = name;
    }
   ...
```
## Test case
```java
    @Test
    void insert() {

        Address address = new Address("foo", "bar");
        Customer customer = new Customer("frank");
        customer.billingAddress(address);

        customer.save();
    }
```
## Log
```
22:26:31.597 [main] INFO  io.ebean - ebean version: 12.15.1-SNAPSHOT
22:26:31.639 [ForkJoinPool.commonPool-worker-2] INFO  io.ebean.test - Using jdbc settings - username:root url:jdbc:postgresql://localhost:26257/my_app?sslmode=disable driver:org.postgresql.Driver
22:26:31.717 [ForkJoinPool.commonPool-worker-2] INFO  io.ebean.docker.commands.Commands - Container ut_cockroach running with host:localhost port:26257 db:my_app user:root/ shutdown:None
22:26:31.717 [ForkJoinPool.commonPool-worker-2] DEBUG io.ebean.docker.commands.Commands - docker exec -i ut_cockroach ./cockroach sql --insecure -e show databases
22:26:31.905 [ForkJoinPool.commonPool-worker-2] DEBUG io.ebean.docker.commands.Commands - Container ut_cockroach ready with host:localhost port:26257
22:26:31.909 [main] INFO  io.ebean.test - For testing purposes a current user and tenant provider has been configured. Use io.ebean.test.UserContext to set current user and tenant in tests.
22:26:32.045 [main] INFO  io.ebean.datasource - DataSourcePool [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[200] in[99ms]
22:26:32.414 [main] INFO  io.ebean.DDL - Executing db-drop-all.sql - 4 statements, autoCommit:true
22:26:32.414 [main] DEBUG io.ebean.DDL - executing 1 of 4 alter table if exists customer drop constraint if exists fk_customer_billing_add...
22:26:32.899 [main] DEBUG io.ebean.DDL - executing 2 of 4 drop index if exists ix_customer_billing_address_id
22:26:33.405 [main] DEBUG io.ebean.DDL - executing 3 of 4 drop table if exists address cascade
22:26:33.750 [main] DEBUG io.ebean.DDL - executing 4 of 4 drop table if exists customer cascade
22:26:33.935 [main] INFO  io.ebean.DDL - Executing db-create-all.sql - 4 statements, autoCommit:true
22:26:33.935 [main] DEBUG io.ebean.DDL - executing 1 of 4 create table address (   id                            serial not null,   line1...
22:26:33.952 [main] DEBUG io.ebean.DDL - executing 2 of 4 create table customer (   id                            uuid not null,   name...
22:26:33.973 [main] DEBUG io.ebean.DDL - executing 3 of 4 create index ix_customer_billing_address_id on customer (billing_address_id)
22:26:34.295 [main] DEBUG io.ebean.DDL - executing 4 of 4 alter table customer add constraint fk_customer_billing_address_id foreign key (...
22:26:34.795 [main] INFO  io.ebean.core - Started database[db] platform[COCKROACH] in 2886ms
22:26:34.801 [main] DEBUG io.ebean.SUM - txn[1001] BatchControl flush [Address:0 i:1]
22:26:34.803 [main] DEBUG io.ebean.SQL - txn[1001] insert into address (line1, line2) values (?,?)
22:26:34.804 [main] DEBUG io.ebean.SQL - txn[1001]  -- bind(foo,bar)
22:26:34.807 [main] DEBUG io.ebean.SUM - txn[1001] Inserted [Address] [176979969]
22:26:34.824 [main] DEBUG io.ebean.SQL - txn[1001] insert into customer (id, name, billing_address_id) values (?,?,?); -- bind(8eccb484-eb94-43b6-9d11-f05b51220cba,frank,176979969)
22:26:34.827 [main] DEBUG io.ebean.SUM - txn[1001] Error[ERROR: insert on table "customer" violates foreign key constraint "fk_customer_billing_address_id"   Detail: Key (billing_address_id)=(176979969) is not present in table "address".]
22:26:34.830 [main] DEBUG io.ebean.TXN - txn[1001] Rollback

io.ebean.DataIntegrityException: Error[ERROR: insert on table "customer" violates foreign key constraint "fk_customer_billing_address_id"   Detail: Key (billing_address_id)=(176979969) is not present in table "address".]

	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:74)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:245)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:77)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:46)
	at io.ebeaninternal.server.core.PersistRequestBean.executeInsert(PersistRequestBean.java:1221)
	at io.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:743)
	at io.ebeaninternal.server.persist.BatchControl.executeOrQueue(BatchControl.java:168)
	at io.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:776)
	at io.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:470)
	at io.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:419)
	at io.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:403)
	at io.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1635)
	at io.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1627)
	at io.ebean.Model.save(Model.java:192)
	at org.example.domain.CustomerTest.insert(CustomerTest.java:14)
	...
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.postgresql.util.PSQLException: ERROR: insert on table "customer" violates foreign key constraint "fk_customer_billing_address_id"
  Detail: Key (billing_address_id)=(176979969) is not present in table "address".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:134)
	at io.ebean.datasource.pool.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:130)
	at io.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:100)
	at io.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:106)
	at io.ebeaninternal.server.persist.dml.DmlHandler.executeNoBatch(DmlHandler.java:87)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:69)
	... 77 more

```

# Fix / Workaround
Change the Address `id` property to be a `long` type instead of `int`
```java
@Entity
public class Address {

    @Id
    long id;   // <!-- HERE
   ...
```
## Log of working test
```
...
22:29:27.371 [main] INFO  io.ebean.core - Started database[db] platform[COCKROACH] in 2678ms
22:29:27.378 [main] DEBUG io.ebean.SUM - txn[1001] BatchControl flush [Address:0 i:1]
22:29:27.381 [main] DEBUG io.ebean.SQL - txn[1001] insert into address (line1, line2) values (?,?)
22:29:27.381 [main] DEBUG io.ebean.SQL - txn[1001]  -- bind(foo,bar)
22:29:27.386 [main] DEBUG io.ebean.SUM - txn[1001] Inserted [Address] [733381156485136385]
22:29:27.402 [main] DEBUG io.ebean.SQL - txn[1001] insert into customer (id, name, billing_address_id) values (?,?,?); -- bind(b43be3ac-5901-4682-9215-456d5c70bcb3,frank,733381156485136385)
22:29:27.404 [main] DEBUG io.ebean.SUM - txn[1001] Inserted [Customer] [b43be3ac-5901-4682-9215-456d5c70bcb3]
22:29:27.406 [main] DEBUG io.ebean.TXN - txn[1001] Commit
22:29:27.419 [EbeanHook] INFO  io.ebean.datasource - DataSourcePool [db] shutdown min[2] max[200] free[2] busy[0] waiting[0] highWaterMark[1] waitCount[0] hitCount[4]  psc[hit:0 miss:10 put:10 rem:0]

```

**Environment:**
 - CockroachDB version - v21.2.4
 - Server OS: Linux/Mint
 - Client app: JDBC, Ebean ORM

**Additional context**
Logging this in case other people hit a similar issue in the future. I believe this issue can just be closed and treated as informational / documentation.

**Comment by rafiss** [comment]
Thanks for reporting this! This topic is definitely has some nuance in CockroachDB.

> Noting that Postgres has 3 serial types - `bigserial`, `serial` and `smallserial` and with Cockroach currently these are all alias to one type - `serial` which I'd say is more a match for Postgres `bigserial`.

This is true when the setting `serial_normalization` is set to `rowid` (which is the default). See the docs on it here https://www.cockroachlabs.com/docs/stable/serial.html#modes-of-operation

However, if you change `serial_normalization` to `sql_sequence_cached` or `sql_sequence`, then the datatype will be the size you want.

There's an important caveat: using an auto-incrementing value as the primary key of a table can lead to bad performance in CockroachDB. See https://www.cockroachlabs.com/docs/v21.2/schema-design-indexes#best-practices

And one more thing to be aware of is that CockroachDB v21.2 also supported the `GENERATED ... AS IDENTITY` syntax, which makes a column that is always be backed by a sequence, and will be of the integer type you specify (INT2, INT4, INT8). See https://www.cockroachlabs.com/docs/v21.2/create-table.html#identity-columns

**Comment by rbygrave** [comment]
> There's an important caveat: using an auto-incrementing value as the primary key of a table can lead to bad performance

Yes, I got that but yes it can't be stated enough. For myself Ebean ORM has a test suite of 3000+ tests covering many databases so for my case I'm looking to get all those existing tests to pass rather than creating a new application and making the correct choice for identity columns for CockroachDB (which I get would largely be to generally use UUID).

> if you change serial_normalization to sql_sequence_cached or sql_sequence, then

Nice.

>  CockroachDB v21.2 also supported the GENERATED ... AS IDENTITY syntax

Ah, that is actually **_perfect_** for me (wrt getting all these existing tests to pass).  Changing Ebean ORM to generate that DDL.

```sql
create table address (
  id                            integer generated by default as identity not null,
  line1                         varchar(255),
  line2                         varchar(255),
  constraint pk_address primary key (id)
);
...
```
... and it works as expected. Very nice !!

### Logs ...
```
txn[1001] BatchControl flush [Address:0 i:1]
txn[1001] insert into address (line1, line2) values (?,?)
txn[1001]  -- bind(foo,bar)
txn[1001] Inserted [Address] [1]
txn[1001] insert into customer (id, name, billing_address_id) values (?,?,?); -- bind(38e357cd-6cb0-41e6-a506-d75abb6a5ce0,frank,1)
txn[1001] Inserted [Customer] [38e357cd-6cb0-41e6-a506-d75abb6a5ce0]
txn[1001] Commit

```

For myself, I think we have everything we need in this ticket so I'll close it.  Thanks for all the details that I missed, that was excellent.  I'll look to make that DDL change to Ebean ORM and look to add some documentation on the Ebean side around this.

Thanks.

**Comment by rafiss** [comment]
Glad it's working. I'll close this ticket, but we are always thinking of ways to make this experience easier.
