### ISSUE TITLE
sql: rollback hits NPE

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7595]
seen on `Build Tag:   beta-20160629-53-g02a236f` on the registration cluster (see 
```
E160701 21:07:33.563958 internal/client/txn.go:364  failure aborting transaction: context deadline exceeded; abort caused by: context deadline exceeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x140 pc=0x9ee630]

goroutine 766754 [running]:
panic(0x18a5e40, 0xc82000e100)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cockroachdb/cockroach/internal/client.(*Txn).sendEndTxnReq(0x0, 0xc8cfa52f00, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:440 +0x50
github.com/cockroachdb/cockroach/internal/client.(*Txn).Rollback(0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:433 +0x3b
github.com/cockroachdb/cockroach/internal/client.(*Txn).CleanupOnError(0x0, 0x7f7e91681d98, 0xc859972210)
        /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:363 +0x92
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc8201b4000, 0x7f7f680e4c58, 0xc84eed71c0, 0xc8239ee800, 0xc873bbfb89, 0x27, 0x0, 0x0, 0x0, 0xc82013a800)
        /go/src/github.com/cockroachdb/cockroach/sql/executor.go:501 +0xd07
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8201b4000, 0x7f7f680e4c58, 0xc84eed71c0, 0xc8239ee800, 0xc873bbfb89, 0x27, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/sql/executor.go:360 +0xf6
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc840f33800, 0x7f7f680e4c58, 0xc84eed71c0, 0xc873bbfb89, 0x27, 0x0, 0x0, 0x0, 0x0, 0x7f7f6811fd01, ...)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:640 +0x98
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc840f33800, 0x7f7f680e4c58, 0xc84eed71c0, 0xc840f33828, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:320 +0xe8
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc840f33800, 0xc874c1bb20, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:275 +0x100c
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc8201ee2d0, 0x7f7f680e4d90, 0xc8666e8300, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:229 +0x98f
github.com/cockroachdb/cockroach/server.(*Server).Start.func8.1(0x7f7f680e4d30, 0xc853304420)
        /go/src/github.com/cockroachdb/cockroach/server/server.go:369 +0x42
github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith.func1(0xc8200d0218, 0x7f7f680e4d30, 0xc853304420, 0xc82000e420)
        /go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:131 +0x62
created by github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith
        /go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:133 +0x333
```

**Comment by petermattis** [comment]
@andreimatei I think you're most familiar with this code.

**Comment by tamird** [comment]
Closing as stale.
