### ISSUE TITLE
colflow: closing some operators out of order leads to span use-after-Finish

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#76096]
I've got another one for you @yuzefovich :)

In a statement from a logic test, it would appear that the `BatchFlowCoordinator` is closing some operators out of order. It seems that there's an upstream `noopProcessor` that gets closed before a downstream disk spiller and external sorter. Closing the `noopProcessor` finishes its span, but that span had been captured by the downstream operators. When those operator try to use the captured ctx in their `Close()` methods -> boom.

To reproduce, patch in https://github.com/cockroachdb/cockroach/pull/75424 (which includes fixes for a bunch of other span problems and adds more aggresive use-after-finish detection) and run:
```
COCKROACH_DEBUG_SPAN_USE_AFTER_FINISH=true make test PKG='./pkg/sql/logictest' TESTS=TestLogic/fakedist-disk/datetime/regression_36146
```
The reproduction is deterministic.

First, the `noopProcessor` is closed when the `BatchFlowCoordinator` drains. Then, the closing of the operators happens through these `Closers`:
https://github.com/cockroachdb/cockroach/blob/4d0f9fe5a3d80c441c914a1a90dee6b47b247672/pkg/sql/colflow/flow_coordinator.go#L339
Maybe these operators that are closed this way are unusual?

I don't know who to blame. 

The stack traces for the span finishing and the use after finish are below.

```
panic: use of Span after Finish. Span: noop. Finish previously called at: goroutine 2292 [running]:
runtime/debug.Stack()
	/home/andrei/goroot/src/runtime/debug/stack.go:24 +0x65
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).finishInternal(0xc006e47800)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:256 +0x73
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).Finish(...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:247
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose(0xc006346580)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:916 +0x139
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).moveToTrailingMeta(0xc006346580)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:688 +0x425
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).DrainHelper(0xc006346580)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:577 +0x189
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*noopProcessor).Next(0xc006346580)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/noop.go:93 +0xc5
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next(0xc0063ca400)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:231 +0x345
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Next(0xc0050b1ae0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:96 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next(0xc003c40dd0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:100 +0x3b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*bufferExportingOperator).Next(0x22c9ea0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:323 +0x97
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*inputPartitioningOperator).Next(0xc000efd600)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/external_sort.go:764 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*allSpooler).spool(0xc0058d9da0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/sort.go:135 +0x7b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*sortOp).Next(0xc005b40c80)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/sort.go:279 +0x7a
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*externalSorter).Next(0xc0056cb2c0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/external_sort.go:346 +0xee
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*diskSpillerBase).Next(0xc00669ad20)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:212 +0x14b
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next(0xc004cf8310)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:125 +0x3f
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Next(0xc0050b1d60)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:96 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next(0xc003c40ea0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:100 +0x3b
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter(...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:242
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0xc006e47500)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91 +0x62
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next(...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:246
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run(0xc0066a2630, {0x4ee06d0, 0xc00631bc80})
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:290 +0x30a
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run(0xc006876280, {0x4ee06d0, 0xc00631bc80}, 0x1)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:259 +0x1d9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0023c7c00, 0xc000852c30, 0xc0055d1a20, 0xc0024d7a00, 0xc006083c00, 0xc003f16f38, 0x0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:573 +0xc51
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0x4ee0778, {0x4ee0778, 0xc006561dd0}, 0x1, 0xc000852c30, 0xc0054d5140, {{0x4ee23e8, 0xc006454d20}, 0x0}, 0xc006083c00)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1409 +0x191
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc003f16600, {0x4ee0778, 0xc006561dd0}, 0xc003f16c78, 0xc006561dd0, {0x7faf3ec8f408, 0xc0054d5140}, 0x0, 0xc00395f9d8)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1413 +0x5f4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc003f16600, {0x4ee0778, 0xc006561dd0}, 0xc003f16c78, {0x7faf3ec8f408, 0xc0054d5140})
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1090 +0x9c7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc003f16600, {0x4ee06d0, 0xc0058a3680}, {{0x4f0dbd8, 0xc000f2d520}, {0xc0053591ad, 0x14}, 0x0, 0x1}, 0x0, ...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:720 +0x2625
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc003f16600, {0x4ee06d0, 0xc0058a3680}, {{0x4f0dbd8, 0xc000f2d520}, {0xc0053591ad, 0x14}, 0x0, 0x1}, 0x0, ...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:139 +0x57e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1({{{0x4f0dbd8, 0xc000f2d520}, {0xc0053591ad, 0x14}, 0x0, 0x1}, {0x29658c54, 0xed98fb3f6, 0x0}, {0x29658ea3, ...}, ...}, ...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1769 +0x299
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc003f16600)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1773 +0xb0b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc003f16600, {0x4ee06d0, 0xc00207ad40}, 0xc000450000, {0xc005647e10, 0x4201fd, 0xc002640140}, 0xc00524fc10)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1702 +0x209
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0054d4a80, {0x4ee06d0, 0xc00207ad40}, {0xc001d90700}, {0x3, 0xc004392a00, 0xc002640140}, 0xc000f94768)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:700 +0x9a
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:680 +0x2f5
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:608 +0x273
 [recovered]
	panic: panic: use of Span after Finish. Span: noop. Finish previously called at: goroutine 2292 [running]:
runtime/debug.Stack()
	/home/andrei/goroot/src/runtime/debug/stack.go:24 +0x65
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).finishInternal(0xc006e47800)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:256 +0x73
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).Finish(...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:247
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose(0xc006346580)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:916 +0x139
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).moveToTrailingMeta(0xc006346580)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:688 +0x425
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).DrainHelper(0xc006346580)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:577 +0x189
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*noopProcessor).Next(0xc006346580)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/noop.go:93 +0xc5
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next(0xc0063ca400)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:231 +0x345
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Next(0xc0050b1ae0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:96 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next(0xc003c40dd0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:100 +0x3b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*bufferExportingOperator).Next(0x22c9ea0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:323 +0x97
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*inputPartitioningOperator).Next(0xc000efd600)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/external_sort.go:764 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*allSpooler).spool(0xc0058d9da0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/sort.go:135 +0x7b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*sortOp).Next(0xc005b40c80)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/sort.go:279 +0x7a
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*externalSorter).Next(0xc0056cb2c0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/external_sort.go:346 +0xee
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*diskSpillerBase).Next(0xc00669ad20)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:212 +0x14b
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next(0xc004cf8310)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:125 +0x3f
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Next(0xc0050b1d60)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:96 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next(0xc003c40ea0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:100 +0x3b
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter(...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:242
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0xc006e47500)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91 +0x62
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next(...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:246
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run(0xc0066a2630, {0x4ee06d0, 0xc00631bc80})
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:290 +0x30a
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run(0xc006876280, {0x4ee06d0, 0xc00631bc80}, 0x1)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:259 +0x1d9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0023c7c00, 0xc000852c30, 0xc0055d1a20, 0xc0024d7a00, 0xc006083c00, 0xc003f16f38, 0x0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:573 +0xc51
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0x4ee0778, {0x4ee0778, 0xc006561dd0}, 0x1, 0xc000852c30, 0xc0054d5140, {{0x4ee23e8, 0xc006454d20}, 0x0}, 0xc006083c00)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1409 +0x191
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc003f16600, {0x4ee0778, 0xc006561dd0}, 0xc003f16c78, 0xc006561dd0, {0x7faf3ec8f408, 0xc0054d5140}, 0x0, 0xc00395f9d8)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1413 +0x5f4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc003f16600, {0x4ee0778, 0xc006561dd0}, 0xc003f16c78, {0x7faf3ec8f408, 0xc0054d5140})
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1090 +0x9c7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc003f16600, {0x4ee06d0, 0xc0058a3680}, {{0x4f0dbd8, 0xc000f2d520}, {0xc0053591ad, 0x14}, 0x0, 0x1}, 0x0, ...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:720 +0x2625
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc003f16600, {0x4ee06d0, 0xc0058a3680}, {{0x4f0dbd8, 0xc000f2d520}, {0xc0053591ad, 0x14}, 0x0, 0x1}, 0x0, ...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:139 +0x57e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1({{{0x4f0dbd8, 0xc000f2d520}, {0xc0053591ad, 0x14}, 0x0, 0x1}, {0x29658c54, 0xed98fb3f6, 0x0}, {0x29658ea3, ...}, ...}, ...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1769 +0x299
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc003f16600)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1773 +0xb0b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc003f16600, {0x4ee06d0, 0xc00207ad40}, 0xc000450000, {0xc005647e10, 0x4201fd, 0xc002640140}, 0xc00524fc10)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1702 +0x209
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0054d4a80, {0x4ee06d0, 0xc00207ad40}, {0xc001d90700}, {0x3, 0xc004392a00, 0xc002640140}, 0xc000f94768)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:700 +0x9a
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:680 +0x2f5
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:608 +0x273

goroutine 2292 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc003f16600, {0x4ee06d0, 0xc00207ad40}, {0x3743dc0, 0xc002afac50})
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:995 +0x1a5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1()
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:698 +0x53
panic({0x3743dc0, 0xc002afac50})
	/home/andrei/goroot/src/runtime/panic.go:1038 +0x215
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish(0x7537c58)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:183 +0x134
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsVerbose(0xc006e47800)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:355 +0x1e
github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog({0x4ee0778, 0xc004620600})
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:92 +0x3a
github.com/cockroachdb/cockroach/pkg/util/log.Eventf({0x4ee0778, 0xc004620600}, {0x3d7e3c1, 0x8}, {0x0, 0x0, 0x0})
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:179 +0x66
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*diskSpillerBase).Close(0xc00669a960)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:241 +0x97
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1.1.1()
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1143 +0xed
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*callbackCloser).Close(0xc004293b30)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1047 +0x1a
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1.1.1()
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1143 +0xed
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*callbackCloser).Close(0xc004438450)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1047 +0x1a
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).close(0xc0066a2630)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:343 +0x8f
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run.func1()
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:272 +0x79
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run(0xc0066a2630, {0x4ee06d0, 0xc00631bc80})
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:335 +0x51b
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run(0xc006876280, {0x4ee06d0, 0xc00631bc80}, 0x1)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:259 +0x1d9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0023c7c00, 0xc000852c30, 0xc0055d1a20, 0xc0024d7a00, 0xc006083c00, 0xc003f16f38, 0x0)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:573 +0xc51
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0x4ee0778, {0x4ee0778, 0xc006561dd0}, 0x1, 0xc000852c30, 0xc0054d5140, {{0x4ee23e8, 0xc006454d20}, 0x0}, 0xc006083c00)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1409 +0x191
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc003f16600, {0x4ee0778, 0xc006561dd0}, 0xc003f16c78, 0xc006561dd0, {0x7faf3ec8f408, 0xc0054d5140}, 0x0, 0xc00395f9d8)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1413 +0x5f4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc003f16600, {0x4ee0778, 0xc006561dd0}, 0xc003f16c78, {0x7faf3ec8f408, 0xc0054d5140})
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1090 +0x9c7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc003f16600, {0x4ee06d0, 0xc0058a3680}, {{0x4f0dbd8, 0xc000f2d520}, {0xc0053591ad, 0x14}, 0x0, 0x1}, 0x0, ...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:720 +0x2625
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc003f16600, {0x4ee06d0, 0xc0058a3680}, {{0x4f0dbd8, 0xc000f2d520}, {0xc0053591ad, 0x14}, 0x0, 0x1}, 0x0, ...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:139 +0x57e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1({{{0x4f0dbd8, 0xc000f2d520}, {0xc0053591ad, 0x14}, 0x0, 0x1}, {0x29658c54, 0xed98fb3f6, 0x0}, {0x29658ea3, ...}, ...}, ...)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1769 +0x299
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc003f16600)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1773 +0xb0b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc003f16600, {0x4ee06d0, 0xc00207ad40}, 0xc000450000, {0xc005647e10, 0x4201fd, 0xc002640140}, 0xc00524fc10)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1702 +0x209
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0054d4a80, {0x4ee06d0, 0xc00207ad40}, {0xc001d90700}, {0x3, 0xc004392a00, 0xc002640140}, 0xc000f94768)
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:700 +0x9a
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:680 +0x2f5
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/home/andrei/work2/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:608 +0x273
FAIL	github.com/cockroachdb/cockroach/pkg/sql/logictest	2.065s
```

**Comment by andreimatei** [comment]
One way to fix it, perhaps, is to pass in a `ctx` to the `Close()` of these operators that the `BatchFlowCoordinator` closes. But I've got no idea if that'd be sane.

**Comment by andreimatei** [comment]
I should have also said that the `NoopProcessor` is drained and closed when the `BatchFlowCoordinator` drains.
