### ISSUE TITLE
Error running TestBenchmarkExpectation - not enough time left on migration lease, terminating for safety

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#76296]
```
=== RUN   TestBenchmarkExpectation/ORMQueries/pg_type
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1  not enough time left on migration lease, terminating for safety
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !goroutine 111018 [running]:
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0)
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !	/Users/ewall/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x8a
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc0003d4aa0, {{{0xc064e6c210, 0x24}, {0x7a774d1, 0x1}, {0x0, 0x0}, {0x0, 0x0}}, 0x16d2223d748618b8, ...})
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !	/Users/ewall/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:237 +0xb8
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth({0x8b678d8, 0xc084c5a990}, 0x1, 0x4, 0x0, {0x7b0c984, 0x3f}, {0x0, 0x0, 0x0})
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !	/Users/ewall/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:60 +0x385
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !github.com/cockroachdb/cockroach/pkg/util/log.Fatal(...)
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !	/Users/ewall/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:882
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !github.com/cockroachdb/cockroach/pkg/startupmigrations.(*Manager).EnsureMigrations.func2({0x8b678d8, 0xc084c5a990})
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !	/Users/ewall/go/src/github.com/cockroachdb/cockroach/pkg/startupmigrations/migrations.go:590 +0x1c6
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !	/Users/ewall/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494 +0x16f
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !	/Users/ewall/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:483 +0x445
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !For more context, check log files in: /var/folders/hc/gng26svn1yq13l017705xqjr0000gq/T/logTestBenchmarkExpectation3467137478
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !****************************************************************************
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !This node experienced a fatal error (printed above), and as a result the
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !process is terminating.
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !problem in CockroachDB. With your help, the support team at Cockroach Labs
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !will try to determine the root cause, recommend next steps, and we can
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !improve CockroachDB based on your report.
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !Please submit a crash report by following the instructions here:
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !    https://github.com/cockroachdb/cockroach/issues/new/choose
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !If you would rather not post publicly, please contact us directly at:
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !    support@cockroachlabs.com
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !
F220209 13:47:41.286947 111018 startupmigrations/migrations.go:590  [n1] 1 !The Cockroach Labs team appreciates your feedback.
```

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
Run either of these on master (currently d50b01317719cb536814b4239291cbf097dcc128)
Command line
```
make test PKG=./pkg/bench/rttanalysis TESTS=TestBenchmarkExpectation/ORMQueries TESTFLAGS='-rewrite --rewrite-iterations=10'
```
GoLang launch config
<img width="869" alt="image" src="https://user-images.githubusercontent.com/8524448/153230593-bb00f7b2-200b-441c-a2b8-d68a8081d940.png">

**Comment by rafiss** [comment]
I was not able to reproduce this when I ran `make test PKG=./pkg/bench/rttanalysis TESTS=TestBenchmarkExpectation/ORMQueries TESTFLAGS='-rewrite --rewrite-iterations=10'`

**Comment by ecwall** [comment]
It looks like it is not happening for me either anymore so I'm closing it.
