### ISSUE TITLE
catalog: span use-after-finish

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#76926]
**Describe the problem**

From https://github.com/cockroachdb/cockroach/pull/76894, saw this failure (master @ 97cc8de9483f0e123d4a5cbde0a7584fe9a89609)

```
=== RUN   TestSnapshotAfterTruncationWithUncommittedTail
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/751d67000aac5f3394c2369309253f02/logTestSnapshotAfterTruncationWithUncommittedTail2372052169
    test_log_scope.go:80: use -show-logs to present logs inline
panic: use of Span after Finish. Span: prepare stmt. Finish previously called at: <stack not captured. Set debugUseAfterFinish>

goroutine 292096 [running]:
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish(0xc003f1bb00)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:185 +0x245
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).RecordingType(0xc003f1bb00)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:387 +0x2f
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsVerbose(...)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:395
github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog({0x93ddb98, 0xc00a9677d0})
	github.com/cockroachdb/cockroach/pkg/util/log/trace.go:92 +0x4f
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth({0x93ddb98, 0xc00a9677d0}, 0x1, 0x2, 0x0, {0x625bac6, 0x22}, {0xc007597b70, 0x2, 0x2})
	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:55 +0x2b0
github.com/cockroachdb/cockroach/pkg/util/log.Warningf(...)
	github.com/cockroachdb/cockroach/bazel-out/k8-dbg/bin/pkg/util/log/log_channels_generated.go:449
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.releaseLease({0x93ddb98, 0xc00a9677d0}, 0xc001519710, 0xc0078fd500)
	github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:543 +0x377
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.acquireNodeLease.func1()
	github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:510 +0x4f2
github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall(0xc000639710, 0xc0072ce550, {0xc0058a7eb7, 0x9}, 0xc00aa2acc0)
	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128 +0x68
created by github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).DoChan
	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:121 +0x59b
I220222 18:42:11.234987 1 (gostd) testmain.go:1556  [-] 1  Test //pkg/kv/kvserver:kvserver_test exited with error code 2
```

This suggests a problem with the span lifecycles in the `catalog` package.

Jira issue: CRDB-13329

**Comment by ajwerner** [comment]
@andreimatei is there something new here?
