### ISSUE TITLE
circleci: failed tests: Example_sql

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7759]
The following test appears to have failed:

[#20129](https://circleci.com/gh/cockroachdb/cockroach/20129):

```
I160711 23:08:06.963933 storage/log.go:84  Range Event: "split", range: 4, info: {"UpdatedDesc":{"range_id":4,"start_key":"lQ==","end_key":"lg==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":5,"start_key":"lg==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160711 23:08:22.307080 gossip/gossip.go:960  starting client to 127.0.0.1:56971
I160711 23:08:22.312045 server/status/runtime.go:187  runtime stats: 330 MiB RSS, 56 goroutines, 12 MiB/21 MiB/40 MiB GO alloc/idle/total, 26 MiB/37 MiB CGO alloc/total, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (104x)
I160711 23:08:22.315779 gossip/client.go:93  closing client to node 1 (127.0.0.1:56971): stopping outgoing client to node 1 (127.0.0.1:56971); loopback connection
I160711 23:08:22.336421 storage/log.go:84  Range Event: "split", range: 4, info: {"UpdatedDesc":{"range_id":4,"start_key":"lQ==","end_key":"lg==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":5,"start_key":"lg==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
F160711 23:08:22.385617 cli/cli_test.go:70  Could not start server: had 4 ranges at startup, expected 5
goroutine 1 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0x3a57d01, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:862 +0xcf
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x309b7e0, 0x3, 0x2a8d768, 0xf, 0x46, 0xc820523200, 0x3b)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:728 +0xb50
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x205f800, 0x1a, 0xc820ccf5a8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0x10a
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x7fdd00000003, 0x205f800, 0x1a, 0xc820ccf5a8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x8d
github.com/cockroachdb/cockroach/util/log.Fatalf(0x205f800, 0x1a, 0xc820ccf5a8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x74
--
github.com/cockroachdb/cockroach/cli_test.TestMain(0xc820ccfed0)
	/go/src/github.com/cockroachdb/cockroach/cli/main_test.go:35 +0xbf
main.main()
	github.com/cockroachdb/cockroach/cli/_test/_testmain.go:112 +0x20b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x309b7e0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x76
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0xbd

goroutine 22 [syscall]:
os/signal.signal_recv(0x616cd1)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x26
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x45

goroutine 5174 [syscall]:
syscall.Syscall(0x0, 0x5, 0xc820efe600, 0x200, 0xecf161dd7, 0xc838fc8e50, 0x6179b4)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x5, 0xc820efe600, 0x200, 0x200, 0x5c5c29, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x6d
syscall.Read(0x5, 0xc820efe600, 0x200, 0x200, 0x24befb0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:161 +0x5f
os.(*File).read(0xc8200de9b8, 0xc820efe600, 0x200, 0x200, 0x200, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:228 +0x8a
os.(*File).Read(0xc8200de9b8, 0xc820efe600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0xbd
--
testing.runExample.func1(0xc8200de9b8, 0xc8203bdc20)
	/usr/local/go/src/testing/example.go:60 +0xf2
created by testing.runExample
	/usr/local/go/src/testing/example.go:67 +0x3a2

goroutine 5175 [runnable]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8203bde00)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:319 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:320 +0xcc4
FAIL	github.com/cockroachdb/cockroach/cli	45.478s
?   	github.com/cockroachdb/cockroach/cli/cliflags	[no test files]
?   	github.com/cockroachdb/cockroach/cmd/gossipsim	[no test files]
?   	github.com/cockroachdb/cockroach/cmd/protoc-gen-gogoroach	[no test files]
=== RUN   TestObjectIDForKey
--- PASS: TestObjectIDForKey (0.03s)
=== RUN   TestGet
--- PASS: TestGet (0.02s)
=== RUN   TestGetLargestID
--- PASS: TestGetLargestID (0.01s)
=== RUN   TestComputeSplits

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Not seen recently, closing.
