### ISSUE TITLE
spanconfigstore: duplicate updates in the systemspanconfigstore is crashing the node

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#77828]
Relevant stack:

```
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1  found duplicate updates {entire-keyspace} and {entire-keyspace}
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !goroutine 488912 [running]:
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x9c
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc00d822ab0, {{{0xc008cc4630, 0x24}, {0x6c0adb0, 0x1}, {0x0, 0x0}, {0x0, 0x0}}, 0x16dc78114ea1ba47, ...})
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:237 +0xb7
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth({0xa6711c8, 0xc00da7c0f0}, 0x1, 0x4, 0x0, {0x6b7bdb2, 0x2}, {0xc00c095e38, 0x1, 0x1})
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:60 +0x386
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/bazel-out/k8-dbg/bin/pkg/util/log/log_channels_generated.go:834
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigstore.(*Store).Apply(0x0, {0xa6711c8, 0xc00da7c0f0}, 0x0, {0xc008317080, 0x3, 0x3})
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigstore/store.go:113 +0x148
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler.(*incrementalReconciler).reconcile.func1({0xa6711c8, 0xc00da7c0f0}, {0xc00b272320, 0x4, 0x4}, {0xc008421001, 0x75b1c08, 0xc0})
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler/reconciler.go:453 +0xca5
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigsqlwatcher.(*SQLWatcher).watch(0xc010c963c0, {0xa6711c8, 0xc00da7c0f0}, {0xc0075b1bd8, 0x0, 0x0}, 0xc0075b1bd8)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigsqlwatcher/sqlwatcher.go:174 +0x998
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigsqlwatcher.(*SQLWatcher).WatchForSQLUpdates(0x18, {0xa6711c8, 0xc00da7c0f0}, {0xc0054f0400, 0x75b1bc0, 0xc0}, 0x0)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigsqlwatcher/sqlwatcher.go:89 +0x72
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler.(*incrementalReconciler).reconcile(0xc00b816d80, {0xa6711c8, 0xc00da7c0f0}, {0x8, 0x8, 0x0}, 0xc0075b1bc0)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler/reconciler.go:386 +0x136
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler.(*Reconciler).Reconcile(0xc0062b2090, {0xa6711c8, 0xc00da7c0f0}, {0xc004e12928, 0xf913a78, 0xc0}, 0xc00f416b40)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler/reconciler.go:173 +0x525
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigjob.(*resumer).Resume(0xc0004bf1c0, {0xa6711c8, 0xc00da7c0f0}, 
```

First seen - https://github.com/cockroachdb/cockroach/issues/77814

@arulajmani probably going to need your help to figure out whats going on here.

Jira issue: CRDB-13791

**Comment by adityamaru** [comment]
I'm not sure what the reasoning behind this check is https://github.com/cockroachdb/cockroach/blob/99c969102111beaa3025ba0046cdc0a83337fcba/pkg/spanconfig/spanconfigstore/systemspanconfigstore.go#L179. Is it not possible for two consecutive cluster target records to be applied by the store?

**Comment by adityamaru** [comment]
I don't have a minimal reproduction yet but I have some sort of reproduction in the test I added - https://github.com/cockroachdb/cockroach/pull/77726

The updates that are causing the node to crash are of the form:
```
[{target:{span:{Key:[] EndKey:[]} systemTarget:{sourceTenantID:{InternalValue:1} targetTenantID:{InternalValue:0} systemTargetType:2}} config:{RangeMinBytes:0 RangeMaxBytes:0 GCPolicy:{TTLSeconds:0 ProtectionPolicies:[] IgnoreStrictEnforcement:false} GlobalReads:false NumReplicas:0 NumVoters:0 Constraints:[] VoterConstraints:[] LeasePreferences:[] RangefeedEnabled:false ExcludeDataFromBackup:false}} 

{target:{span:{Key:[] EndKey:[]} systemTarget:{sourceTenantID:{InternalValue:1} targetTenantID:{InternalValue:0} systemTargetType:2}} config:{RangeMinBytes:0 RangeMaxBytes:0 GCPolicy:{TTLSeconds:0 ProtectionPolicies:[{ProtectedTimestamp:{WallTime:3 Logical:0 Synthetic:false} IgnoreIfExcludedFromBackup:false}] IgnoreStrictEnforcement:false} GlobalReads:false NumReplicas:0 NumVoters:0 Constraints:[] VoterConstraints:[] LeasePreferences:[] RangefeedEnabled:false ExcludeDataFromBackup:false}}]
```

This corresponds to a release and a protect being processed in the same batch of updates. This seems okay unless I'm missing some higher level invariant that should be preventing this?

**Comment by arulajmani** [comment]
> This corresponds to a release and a protect being processed in the same batch of updates. This seems okay unless I'm missing some higher-level invariant that should be preventing this?

When I wrote this, I was following this invariant: https://github.com/cockroachdb/cockroach/blob/99c969102111beaa3025ba0046cdc0a83337fcba/pkg/spanconfig/spanconfig.go#L208 We do something similar for "regular span configs" as well: 
https://github.com/cockroachdb/cockroach/blob/99c969102111beaa3025ba0046cdc0a83337fcba/pkg/spanconfig/spanconfigstore/spanconfigstore.go#L414-L420

Do we know how this invariant enforced for regular span configs in the `Reconciler` and `KVSubscriber`?

**Comment by arulajmani** [comment]
@adityamaru and I looked at this together a bit, and seems like the real issue is the way we're constructing `Updates` to be passed in to the store. Specifically, we construct `SystemSpanConfigs` deletions using this list: 

https://github.com/cockroachdb/cockroach/blob/99c969102111beaa3025ba0046cdc0a83337fcba/pkg/spanconfig/spanconfigreconciler/reconciler.go#L416-L420

And we construct updates using the SQLTranslator: 
https://github.com/cockroachdb/cockroach/blob/99c969102111beaa3025ba0046cdc0a83337fcba/pkg/spanconfig/spanconfigreconciler/reconciler.go#L422-L425

As the SQLTranslator creates its own transaction internally, these things are happening in separate transactions. This means we're susceptible to races like: 

```
Backup 1: Release()
Watcher: Notifies on entire keyspace. 
Reconciler: Filter missing update for entire keyspace
Backup 2: Protect()
Reconciler: Translate entire-keyspace, constructing an update 
--- panic
Watcher: Notifies on Entire keyspace (corresponding to the `Protect`)
```

----

I don't think we want to remove the duplication check in the `systemSpanConfigStore` and rely on the ordering of updates passed to it. Instead, we probably don't want to end up in this situation to begin with by only creating a transactional view of updates to apply to the store. There's actually a TODO that talks about this hazard:

https://github.com/cockroachdb/cockroach/blob/91563a5086e0628aa64288871ad3613f3edfb29e/pkg/spanconfig/spanconfigreconciler/reconciler.go#L406-L409

My proposal is to make it such that we can bind a transaction to the `SQLTranslator` and make it single use. Let's create a `SQLTranslatorFactory` that does this binding and pass it as a dependency to the `Reconciler`. 

----

This was on the `Reconciler` side of things -- I'm going to spend some time auditing the `KVSubscriber` side and make sure this check doesn't trip us up.
