### ISSUE TITLE
storage: (*tlsCreds).ClientHandshake leaked from TestNodeJoinSelf

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7793]
Seen near 69132c5fc439a0663f654f05da48a1abc87350c4 in unrelated WIP.

```
I160713 05:12:54.184828 server/node.go:401  store store=0:0 ([]=) not bootstrapped
--- FAIL: TestNodeJoinSelf (5.01s)
	leaktest.go:94: Leaked goroutine: goroutine 4191 [IO wait]:
		net.runtime_pollWait(0x6791120, 0x72, 0xc8204c3000)
			/usr/local/Cellar/go/1.6.2/libexec/src/runtime/netpoll.go:160 +0x60
		net.(*pollDesc).Wait(0xc820906140, 0x72, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
		net.(*pollDesc).WaitRead(0xc820906140, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
		net.(*netFD).Read(0xc8209060e0, 0xc8204c3000, 0x400, 0x400, 0x0, 0x6780050, 0xc8200101c0)
			/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_unix.go:250 +0x23a
		net.(*conn).Read(0xc820312350, 0xc8204c3000, 0x400, 0x400, 0x0, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/net/net.go:172 +0xe4
		crypto/tls.(*block).readFromUntil(0xc8203de240, 0x6b07d48, 0xc820312350, 0x5, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/conn.go:460 +0xcc
		crypto/tls.(*Conn).readRecord(0xc8201c0000, 0x16, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/conn.go:562 +0x2d1
		crypto/tls.(*Conn).readHandshake(0xc8201c0000, 0x0, 0x0, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/conn.go:800 +0xd3
		crypto/tls.(*Conn).clientHandshake(0xc8201c0000, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/handshake_client.go:149 +0xfcb
		crypto/tls.(*Conn).Handshake(0xc8201c0000, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/conn.go:1033 +0xec
		google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake.func2(0xc820460300, 0xc8201c0000)
			/Users/tschottdorf/go/src/google.golang.org/grpc/credentials/credentials.go:166 +0x21
		created by google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake
			/Users/tschottdorf/go/src/google.golang.org/grpc/credentials/credentials.go:167 +0x36c
```

**Comment by tschottdorf** [comment]
one more, near 4f50c6f6418dad43ad2e4c6bb972102f594eaa94 (master at time of writing).
```
--- FAIL: TestNodeJoinSelf (5.04s)
	leaktest.go:97: Leaked goroutine: goroutine 4137 [IO wait]:
		net.runtime_pollWait(0x67b5068, 0x72, 0xc8203f2c00)
			/usr/local/Cellar/go/1.6.2/libexec/src/runtime/netpoll.go:160 +0x60
		net.(*pollDesc).Wait(0xc8201a9020, 0x72, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
		net.(*pollDesc).WaitRead(0xc8201a9020, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
		net.(*netFD).Read(0xc8201a8fc0, 0xc8203f2c00, 0x400, 0x400, 0x0, 0x67a8050, 0xc8200121e0)
			/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_unix.go:250 +0x23a
		net.(*conn).Read(0xc8202bc008, 0xc8203f2c00, 0x400, 0x400, 0x0, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/net/net.go:172 +0xe4
		crypto/tls.(*block).readFromUntil(0xc82034c0f0, 0x7e60000, 0xc8202bc008, 0x5, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/conn.go:460 +0xcc
		crypto/tls.(*Conn).readRecord(0xc82000c300, 0x16, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/conn.go:562 +0x2d1
		crypto/tls.(*Conn).readHandshake(0xc82000c300, 0x0, 0x0, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/conn.go:800 +0xd3
		crypto/tls.(*Conn).clientHandshake(0xc82000c300, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/handshake_client.go:149 +0xfcb
		crypto/tls.(*Conn).Handshake(0xc82000c300, 0x0, 0x0)
			/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/conn.go:1033 +0xec
		google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake.func2(0xc8206d0000, 0xc82000c300)
			/Users/tschottdorf/go/src/google.golang.org/grpc/credentials/credentials.go:166 +0x21
		created by google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake
			/Users/tschottdorf/go/src/google.golang.org/grpc/credentials/credentials.go:167 +0x36c
```

**Comment by tamird** [comment]
This is another instance of shitty cancellation in grpc.

**Comment by tamird** [comment]
Upstream PR: https://github.com/grpc/grpc-go/pull/796/files

**Comment by tamird** [comment]
Closing in favour of #8136 since that has a more interesting stack trace.
