### ISSUE TITLE
statement_timeout is unreliable timing out long running statements

### ISSUE THREAD

**Issue by ebmarine** [cockroachdb/cockroach#78175]
**Describe the problem**
Setting statement_timeout does not always results in statements timing out when they take longer than the specified time.

**To Reproduce**
I've run this via the CLI, a GUI database client, and a java app all with the same results using the cockroach docker image. Create a table (testing) with a single column (testa) and filled with 15,000 rows of numbers sequentially incremented. Then execute "set statement_timeout = '10s';", after which in the same session run "SELECT SUM(nt1.testa + nt2.testa + nt3.testa) FROM testing nt1 CROSS JOIN testing nt2 CROSS JOIN testing nt3;". Mostly it times out during the first run of the select statement some time between 10 and 20 seconds, but running it again (whether setting the statement_timeout again or not) will not time out.

Oddly, using 8 seconds I've found seems to be more reliable than 10, but it could be chance.

**Expected behavior**
The statement to be cancelled after the amount of time specified every time it takes longer than that amount of time.

**Additional data / screenshots**
I see no errors in the logs.

Schema used:
CREATE TABLE public.testing (
	testa INT8 NOT NULL,
	rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
	CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
	FAMILY "primary" (testa, rowid)
);

**Environment:**
 - CockroachDB version : 21.1.6 and 21.2.7
 - Server OS: cockroachdb/cockroach docker build (Linux)
 - Client app: cockroach sql, JDBC, and DBeaver

**Comment by mgartner** [comment]
@cucaroach as L2 primary can you triage this?

**Comment by cucaroach** [comment]
I just tried this 3 times with 21.2.10 on OS X and it worked 3 times in a row, timeout was more ~15s but it worked.  However I tried on linux with 21.2.7 and was able to reproduce it.  After 40s or so I killed the server and connExecutor was here:

```
goroutine 2551 [runnable]:
math/big.(*Int).SetInt64(0xc00b23baa0, 0x5400, 0xc00b23ba90)
	/usr/local/go/src/math/big/int.go:49 +0xb9
github.com/cockroachdb/apd/v2.(*Decimal).setCoefficient(0xc00b23ba90, 0x5400)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd/v2/decimal.go:249 +0x45
github.com/cockroachdb/apd/v2.(*Decimal).SetFinite(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd/v2/decimal.go:239
github.com/cockroachdb/apd/v2.(*Decimal).SetInt64(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd/v2/decimal.go:234
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecagg.(*sumInt64OrderedAgg).Compute.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecagg/ordered_sum_agg.eg.go:660 +0xa5b
github.com/cockroachdb/cockroach/pkg/sql/colmem.(*Allocator).PerformOperation(0xc004192600, 0xc00b23ba30, 0x1, 0x1, 0xc00b23ba40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:307 +0x59
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecagg.(*sumInt64OrderedAgg).Compute(0xc000627e60, 0xc002f10ad0, 0x1, 0x1, 0xc00383a648, 0x1, 0x2, 0x0, 0x400, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecagg/ordered_sum_agg.eg.go:584 +0x205
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*defaultAggregatorHelper).performAggregation(0xc0029841e8, 0x8ce8d60, 0xc002bd7830, 0xc002f10ad0, 0x1, 0x1, 0x400, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/aggregators_util.go:114 +0x10b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*orderedAggregator).Next(0xc00489fc00, 0xc000c4e0d0, 0x8ce8d60)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/ordered_aggregator.go:249 +0x41f
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next(0xc000c4e0d0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:98 +0x49
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:239
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0xc001945e68, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91 +0x57
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:243
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run(0xc002b1c000, 0x8cccfc8, 0xc004203180)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:282 +0x197
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run(0xc001898690, 0x8cccfc8, 0xc004203180, 0x7c84378)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:258 +0x234
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc002232500, 0xc001e642d0, 0xc00034f080, 0xc004737b00, 0xc0029ea380, 0xc001464e38, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:548 +0x66f
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc002232500, 0x8ce8d60, 0xc002bd61b0, 0xc001464e38, 0xc001e642d0, 0xc00034f080, 0x8cce998, 0xc001ea6ab0, 0x0, 0xc0029ea380, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1289 +0x1b1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001464600, 0x8ce8d60, 0xc002bd61b0, 0xc001464bd8, 0x3, 0x7f6c1be8b680, 0xc001a6eaa0, 0xc001946901, 0xc001906478, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1381 +0x472
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001464600, 0x8ce8d60, 0xc002bd61b0, 0xc001464bd8, 0x7f6c1be8b680, 0xc001a6eaa0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1072 +0x90b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001464600, 0x8ce8d60, 0xc002bd61b0, 0x8cf5cb8, 0xc0006b9e50, 0xc002bda645, 0x6c, 0x0, 0x3, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:709 +0x11a6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001464600, 0x8cccfc8, 0xc004202600, 0x8cf5cb8, 0xc0006b9e50, 0xc002bda645, 0x6c, 0x0, 0x3, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129 +0xb0a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0x8cf5cb8, 0xc0006b9e50, 0xc002bda645, 0x6c, 0x0, 0x3, 0x3882e979, 0xeda2828ae, 0x0, 0x3882fa0d, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1705 +0x293
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc001464600, 0x8cccfc8, 0xc004202600, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1707 +0x1711
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001464600, 0x8cccfc8, 0xc0010a91c0, 0xc002246820, 0x5400, 0x15000, 0xc002246aa0, 0xc000613be0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1629 +0x22f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc00159e700, 0x8cccfc8, 0xc0010a91c0, 0xc001464600, 0x5400, 0x15000, 0xc002246aa0, 0xc000613be0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:668 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc000ffc084, 0xc001f30fa8, 0x8cccfc8, 0xc0010a91c0, 0xc000613be0, 0xc00159e700, 0xc001a6e400, 0x8d41540, 0xc0007ca870, 0xc00189c4e0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:648 +0x3d4
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:576 +0x188
```

Suspecting some vectorized cancelation failure, I tried with vectorize = off and it worked 3 times in a row.  Will sync up with @yuzefovich to debug this further.  Seems to happen on master as well.
