### ISSUE TITLE
ui: unable to view SQL Activity or Jobs in 21.2 non upgrade finalized state

### ISSUE THREAD

**Issue by nick-jones** [cockroachdb/cockroach#78351]
**Describe the problem**

We're upgrading a cluster from 21.1.12 to 21.2.7. We disabled auto upgrade finalizaton beforehand, and the upgrade is not yet finalized. I went checking to see if the cluster is healthy in the DB console, which it is. However I'm now unable to view the SQL Activity or Jobs sections.

The UI renders the following message under the SQL Activity `Statements` and `Transactions` tabs:

```
This page had an unexpected error while loading statements. Reload this page.
``` 

And the following against the Jobs page:

```
An internal server error has occurred. Please check your CockroachDB logs for more details.
```

The user I'm logged in is granted `admin` role:

```
root@cockroachdb-proxy:26257/defaultdb> SHOW GRANTS ON ROLE admin FOR nicjones;
  role_name |  member  | is_admin
------------+----------+-----------
  admin     | nicjones |  false
(1 row)
```

I've also looked to access the UI via the root user, just to avoid doubt around it being a permissions issue. This was achieved via `cockroach auth-session login root` and I do indeed receive an error still.

For the Jobs page, the 500 response contains the following string:

```
An internal server error has occurred. Please check your CockroachDB logs for more details.
```

Checking the logs from the relevant node, the following is logged out when viewing the Jobs page:

```
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591  ‹client already committed or rolled back the transaction. Trying to execute: 1 EndTxn›. stack:
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹goroutine 169917 [running]:›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹runtime/debug.Stack(0x542c98d, 0x4e, 0xc013b81060)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /usr/local/go/src/runtime/debug/stack.go:24 +0x9f›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).maybeRejectClientLocked(0xc01010c500, 0x8cccfc8, 0xc013d8bbc0, 0xc013b81510, 0xc012b2cf90)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:677 +0x4d0›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send(0xc01010c500, 0x8cccfc8, 0xc013d8bbc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:480 +0xdb›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender(0xc0007cdb00, 0x8cccfc8, 0xc013d8bbc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:872 +0x142›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send(0xc00813cfd0, 0x8cccfc8, 0xc013d8bbc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:1030 +0x14c›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/kv.(*Txn).rollback(0xc00813cfd0, 0x8cccfc8, 0xc013d8bbc0, 0x45d97f)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:810 +0x3b8›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/kv.(*Txn).CleanupOnError(0xc00813cfd0, 0x8cccfc8, 0xc013d8bbc0, 0x8c2fdc0, 0xc005f7fb60)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:701 +0x7a›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/sql.cleanupAndFinishOnError(0x8ccd070, 0xc012b2ca20, 0x8c37da0, 0xc00060fb80, 0x5017600, 0xc013016090, 0x8c37be0, 0xc00c6f15d0, 0x4cb4760, 0xc00c6f15e0, ...)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_fsm.go:473 +0xca›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/util/fsm.Transitions.apply(0xc000712ba0, 0x8ccd070, 0xc012b2ca20, 0x8c37da0, 0xc00060fb80, 0x5017600, 0xc013016090, 0x8c37be0, 0xc00c6f15d0, 0x4cb4760, ...)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:106 +0x175›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/util/fsm.(*Machine).ApplyWithPayload(...)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:135›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close(0xc013016000, 0x8ccd070, 0xc012b2ca20, 0x0)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:976 +0x998›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1(0xc013016000, 0x8ccd070, 0xc012b2ca20, 0xc0018a5b00, 0xc012b2cc60, 0x8c81860, 0xc013d8b700, 0x0, 0xc007f0be90)›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:219 +0xd8›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx›
E220323 18:04:41.225345 169917 kv/kvclient/kvcoord/txn_coord_sender.go:678 ⋮ [n1,intExec=‹admin-jobs›] 591 +‹   /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:209 +0x453›
E220323 18:04:41.226113 170037 server/admin.go:1841 ⋮ [-] 592  source type assertion failed
```

I've confirmed that downgrading back to the previous version makes the pages load fine again.

**To Reproduce**

```sh
#!/bin/bash

function cleanup() {
  echo "cleaning up.."
  docker stop cockroachdb
  docker volume rm cockroachdb-data-01
}

trap cleanup EXIT

docker volume create cockroachdb-data-01

echo "starting cockroach v21.1.16"
docker run --detach \
  --rm \
  --name cockroachdb \
  --mount source=cockroachdb-data-01,target=/cockroach/cockroach-data \
  -p 9080:8080 \
  cockroachdb/cockroach:v21.1.16 start-single-node --insecure

while [[ $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:9080/health?ready=1") != "200" ]]; do
  echo "waiting for cockroachdb to be ready.."
  sleep 1
done

echo "cockroachdb ready"

echo "creating stub table and truncating to force job creation"
docker exec cockroachdb cockroach sql --insecure --execute "CREATE TABLE foo ( id int not null primary key ); TRUNCATE foo;"

echo "disabling auto-finalization"
docker exec cockroachdb cockroach sql --insecure --execute "SET CLUSTER SETTING cluster.preserve_downgrade_option = '21.1';"

echo "show jobs + preserve_downgrade_option"
docker exec cockroachdb cockroach sql --insecure --execute "SHOW JOBS;"
docker exec cockroachdb cockroach sql --insecure --execute "SHOW CLUSTER SETTING cluster.preserve_downgrade_option;"

sleep 10
echo "stopping cockroachdb"
docker stop cockroachdb

echo "starting cockroach v21.2.7"
docker run --detach \
  --rm \
  --name cockroachdb \
  --mount source=cockroachdb-data-01,target=/cockroach/cockroach-data \
  -p 9080:8080 \
  cockroachdb/cockroach:v21.2.7 start-single-node --insecure

echo "open: http://localhost:9080/#/jobs"
sleep 3600
```

**Expected behavior**

The relevant pages should load, or at minimum provide an indication that they cannot be rendered due to the non-finalized state of the cluster.

**Additional data / screenshots**

21.1.12

<img width="1272" alt="Screenshot 2022-03-23 at 17 34 21" src="https://user-images.githubusercontent.com/350792/159766690-0a3b60f7-409e-426d-a846-11c2b22aa9c7.png">

21.2.7

<img width="1269" alt="Screenshot 2022-03-23 at 17 44 40" src="https://user-images.githubusercontent.com/350792/159766744-26bb7999-7900-4b03-a35b-85b6a1d78560.png">

**Environment:**
 - CockroachDB version: 21.2.7
 - Server OS: Linux (containerised)
 - Client app: web UI

**Additional context**

We're unsure if we should finalise the upgrade.

Jira issue: CRDB-14086

**Comment by nick-jones** [comment]
For the Jobs page, I'm wondering if this is because there is an attempt to scan `num_runs` into an int64:

- https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/server/admin.go#L1945
- https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/server/serverpb/admin.pb.go#L1955

... but in all cases this is `NULL` for us:

```
root@cockroachdb-proxy:26257/defaultdb> SELECT COUNT(*) FROM crdb_internal.jobs WHERE num_runs IS NULL;
  count
---------
    333
(1 row)
```

Will finalizing the upgrade potentially resolve this?

**Comment by nick-jones** [comment]
I've wrote a quick script to reproduce this (added to the description). In doing so, I can see that resetting `cluster.preserve_downgrade_option` does ultimately make the error go away on the Jobs page. Whilst that answers my most pressing question (can I finalize the upgrades), I'll leave this for others to decide if this remains an issue or not. When we disable auto-finalization we're basically looking for reasons to finish the upgrade, and having errors spitting out of the DB console does not send good signals.

**Comment by tbg** [comment]
Thank you for the detailed bug report, Nick! I'm glad you were able to proceed with the upgrade and solve the problem that way. We'll investigate.

**Comment by Azhng** [comment]
Closed by #79795

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14086](https://cockroachlabs.atlassian.net/browse/CRDB-14086) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-78351`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by jocrl** [comment]
Hello dev-inf team!

The Jira issue looks like it correctly has the updates from Github. I'm not sure what change on the Jira side conflicted with this.

Thanks!

**Comment by joereyna** [comment]
I'm hitting this on 
V21.2.4
