### ISSUE TITLE
sql: DATE values cannot be parsed from JDBC-generated DATE string inputs

### ISSUE THREAD

**Issue by samlotti2** [cockroachdb/cockroach#7865]
Hi, 

Im trying to insert a date using a prepared statement, however all the approaches I tried result in errors: 

```
ERROR: error in argument for $3: could not parse string "2016-7-17 -4:0:0" as date
```

Below is a simple example of the error (added date to the example from website).

```sql
CREATE TABLE accounts (id INT PRIMARY KEY, balance INT, cdate DATE)'
```

```java
PreparedStatement prepareStatement = db.prepareStatement("INSERT INTO accounts (id, balance, cdate) VALUES ( ?, ?, ? )");

prepareStatement.setObject(1, 1);
prepareStatement.setObject(2, 1000);
prepareStatement.setObject(3, new java.sql.Date(System.currentTimeMillis()));
// works: prepareStatement.setObject(3, "2011-01-11" );

prepareStatement.execute();
```

**Comment by knz** [comment]
Hi @samlotti2, thanks for your report. Can you also check what happens if you use `prepareStatement.setDate` instead of `setObject`?

**Comment by samlotti2** [comment]
Hi @knz 

I did try all the versions that were commented.  

Below is the version with setDate:
			prepareStatement.setDate(3, new java.sql.Date(System.currentTimeMillis()));

Here is the code.
[cockroach-sample.zip](https://github.com/cockroachdb/cockroach/files/368128/cockroach-sample.zip)

---The exception ---
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: error in argument for $3: could not parse string "2016-7-17 -4:0:0" as date
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:155)
	at com.hapticapps.cockroach_sample.BasicSample.main(BasicSample.java:38)

Thank you
-Sam

**Comment by knz** [comment]
Thanks! We'll have a look at this.

**Comment by tamird** [comment]
I believe we've seen this report before; the issue is the format in which
the date is sent. Postgres is more lenient in its date parsing than we are.

**Comment by petermattis** [comment]
@dt Didn't we expand which date formats we parse?
