### ISSUE TITLE
sql: panic on UPDATE: interface conversion

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#7873]
See #7861, #7863.

SQL:

```
CREATE DATABASE d;
SET DATABASE = d;
CREATE TABLE t();
UPDATE t SET ident.* = DEFAULT;
```

Panic:

```
panic: interface conversion: parser.IndirectionElem is parser.StarIndirection, not parser.NameIndirection

goroutine 371 [running]:
github.com/cockroachdb/cockroach/sql/parser.(*QualifiedName).Column(0xc820178b00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:770 +0x1bb
github.com/cockroachdb/cockroach/sql.(*planner).processColumns(0xc8206cc090, 0xc820cc5a00, 0xc82073fc40, 0x3, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/insert.go:341 +0x281
github.com/cockroachdb/cockroach/sql.(*planner).Update(0xc8206cc090, 0xc8207ca5a0, 0x0, 0x0, 0x0, 0x7fd043cbc501, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/update.go:151 +0x446
github.com/cockroachdb/cockroach/sql.(*planner).newPlan(0xc8206cc090, 0x7fd043cc1be0, 0xc8207ca5a0, 0x0, 0x0, 0x0, 0x19a29801, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/plan.go:306 +0x717
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc8206cc090, 0x7fd043cc1be0, 0xc8207ca5a0, 0x6aa501, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/plan.go:212 +0x83
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc820208000, 0x7fd043cc1be0, 0xc8207ca5a0, 0xc8206cc090, 0xc8207ca501, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:1047 +0x93
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInOpenTxn(0xc820208000, 0x7fd043cc1be0, 0xc8207ca5a0, 0xc8206cc090, 0x101, 0xc8206cc028, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:945 +0x439
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc820208000, 0xc8206e71f0, 0x1, 0x1, 0xc8206cc090, 0xc8206cc028, 0x2220101, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:693 +0x5da
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc820208000, 0xc8206cc090, 0x1, 0xc8206cc028, 0xc82071e420, 0xc8206e71f0, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:621 +0x18d
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func2(0xc8207aedc0, 0xc82071e420, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:513 +0x470
github.com/cockroachdb/cockroach/internal/client.(*Txn).Exec(0xc8207aedc0, 0xc820330101, 0x146250324c035440, 0x0, 0xc820333980, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:548 +0x2eb
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc820208000, 0x7fd043d3c830, 0xc820756140, 0xc8206cc000, 0xc820862137, 0x9e, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:518 +0xba7
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc820208000, 0x7fd043d3c830, 0xc820756140, 0xc8206cc000, 0xc820862137, 0x9e, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:384 +0x146
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc8201a1500, 0x7fd043d3c830, 0xc820756140, 0xc820862137, 0x9e, 0x0, 0x0, 0x0, 0x0, 0x7fd047c76001, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:640 +0x98
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc8201a1500, 0x7fd043d3c830, 0xc820756140, 0xc8201a1528, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:320 +0xe8
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc8201a1500, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:275 +0x100c
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc820186720, 0x7fd043cfc100, 0xc8200f6420, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:231 +0x9d9
github.com/cockroachdb/cockroach/server.(*Server).Start.func8.1(0x7fd043cfc100, 0xc8200f6420)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:370 +0x42
github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith.func1(0xc8205a2050, 0x7fd043cfc100, 0xc8200f6420, 0xc82039c000)
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:131 +0x62
created by github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:133 +0x333
```

Found with random syntax generator.

**Comment by knz** [comment]
Repros also with `INSERT INTO foo(col.*) VALUES ...`
