### ISSUE TITLE
cockroach demo crash on macOS laptop (v22.1.0-beta.3)

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#80306]
[Searched and did not find text 'newTracingClientStream' from the backtrace in any issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+panic+runtime+error+newTracingClientStream)

Demo cluster running 22.1.0-beta.3 on macOS. Demo cluster started with:

```
$ cockroach demo --insecure --global --nodes 9
```

Laptop info:

```
$ uname -a
Darwin crlMBP-C02F51KPML7JMTI2.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
```

Cockroach binary info:
```
# Server version: CockroachDB CCL v22.1.0-beta.3 (x86_64-apple-darwin19, built 2022/04/18 16:32:35, go1.17.6) (same version as client)
# Cluster ID: e55d4aac-a7bb-4df5-8a03-0f8400f84235
# Organization: Cockroach Demo
```

Context: had `cockroach demo` running on the laptop for a few days.  Came back to laptop this morning and the demo cluster had crashed with the following:

```
root@127.0.0.1:26257/test> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x465f68e]

goroutine 2800904 [running]:
google.golang.org/grpc/internal/transport.(*Stream).Context(...)
	google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/transport.go:403
google.golang.org/grpc.(*clientStream).Context(0xc12d049500)
	google.golang.org/grpc/external/org_golang_google_grpc/stream.go:668 +0x2e
github.com/cockroachdb/cockroach/pkg/util/tracing.newTracingClientStream.func2()
	github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:389 +0x38
created by github.com/cockroachdb/cockroach/pkg/util/tracing.newTracingClientStream
	github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:384 +0x151

Process cockroach exited abnormally with code 2
```

**Comment by andreimatei** [comment]
It looks to me like `cs.attempt.s` was `nil` [here](https://github.com/grpc/grpc-go/blob/v1.43.0/stream.go#L668).
I think this is a gRPC bug. Hopefully it's OSX only. Let's see if it shows up more.

**Comment by andreimatei** [comment]
Well, it showed up more. Let's take the party to https://github.com/cockroachdb/cockroach/issues/80689
