### ISSUE TITLE
circleci: failed tests: TestReplicateAfterTruncation 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8064]
The following test appears to have failed:

[#20621](https://circleci.com/gh/cockroachdb/cockroach/20621):

```
I160727 18:14:57.839008 gossip/client.go:182  node 2 received [cluster-id first-range node:1 sentinel system-db] from node 1 (2 fresh)
W160727 18:14:57.841642 storage/replica.go:337  range 1: outgoing raft transport stream to {2 2 0} closed by the remote: <nil>
I160727 18:14:57.843998 storage/replica_raftstorage.go:591  store=2:2 ([]=) range=1 [/Min-/Max): with replicaID [?], applied preemptive snapshot for range 1 in 7.712899ms
I160727 18:14:57.844232 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
I160727 18:14:57.844788 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- FAIL: TestReplicateAfterTruncation (0.09s)
panic: descriptor is not initialized [recovered]
	panic: descriptor is not initialized [recovered]
	panic: descriptor is not initialized [recovered]
	panic: descriptor is not initialized

goroutine 68521 [running]:
panic(0x1bae880, 0xc8250c61e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3ff
testing.tRunner.func1(0xc8255b4480)
	/usr/local/go/src/testing/testing.go:467 +0x22a
panic(0x1bae880, 0xc8250c61e0)
	/usr/local/go/src/runtime/panic.go:443 +0x521
github.com/cockroachdb/cockroach/util/leaktest.AfterTest.func1()
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:77 +0xb1
panic(0x1bae880, 0xc8250c61e0)
	/usr/local/go/src/runtime/panic.go:443 +0x521
github.com/cockroachdb/cockroach/storage.(*Store).Send.func1(0xc82c2f9378, 0xc82c2f93f0, 0x0, 0x57, 0xc82c2f93e8, 0xc825464c80)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2119 +0x72
panic(0x1bae880, 0xc8250c61e0)
	/usr/local/go/src/runtime/panic.go:443 +0x521
github.com/cockroachdb/cockroach/roachpb.NewRangeKeyMismatchError(0xc8250c6078, 0x1, 0x8, 0x0, 0x0, 0x0, 0xc82c03be60, 0x0)
	/go/src/github.com/cockroachdb/cockroach/roachpb/errors.go:301 +0xda
github.com/cockroachdb/cockroach/storage.(*Replica).checkCmdHeader(0xc82024ac00, 0xc8250c6078, 0x1, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:855 +0x10e
github.com/cockroachdb/cockroach/storage.(*Replica).executeCmd(0xc82024ac00, 0x7f1ebd17d678, 0xc824cc46c0, 0x0, 0x0, 0x0, 0x7f1ebd17bf30, 0xc824f8cea0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:75 +0x16f
github.com/cockroachdb/cockroach/storage.(*Replica).executeBatch(0xc82024ac00, 0x7f1ebd17d678, 0xc824cc46c0, 0x0, 0x0, 0x7f1ebd17bf30, 0xc824f8cea0, 0x0, 0x0, 0x56, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2321 +0x70b
github.com/cockroachdb/cockroach/storage.(*Replica).addReadOnlyCmd(0xc82024ac00, 0x7f1ebd17d678, 0xc824cc46c0, 0x0, 0x56, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
--
testing.tRunner(0xc8255b4480, 0x2e60088)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3

goroutine 1 [chan receive]:
testing.RunTests(0x25bbd40, 0x2e5ea20, 0x127, 0x127, 0xc820209d01)
	/usr/local/go/src/testing/testing.go:583 +0xb39
testing.(*M).Run(0xc820097f00, 0xc82025bc90)
	/usr/local/go/src/testing/testing.go:515 +0x11e
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc820097f00)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:57 +0x2d5
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:652 +0x20b

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x317b9e0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1015 +0x76
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0xc5
FAIL	github.com/cockroachdb/cockroach/storage	163.566s
=== RUN   TestBatchBasics
I160727 18:14:17.481855 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
I160727 18:14:17.485299 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.03s)
=== RUN   TestBatchRepr
I160727 18:14:17.511743 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
I160727 18:14:17.513819 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.03s)
=== RUN   TestBatchGet
I160727 18:14:17.542710 storage/engine/rocksdb.go:353  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
#8086
