### ISSUE TITLE
circleci: failed tests: TestReplicateAfterTruncation 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8065]
The following test appears to have failed:

[#20623](https://circleci.com/gh/cockroachdb/cockroach/20623):

```
I160727 18:47:23.589324 gossip/server.go:139  node 1 returned 2 info(s) to node 2
W160727 18:47:23.593617 storage/replica.go:337  range 1: outgoing raft transport stream to {2 2 0} closed by the remote: <nil>
I160727 18:47:23.596424 storage/replica_raftstorage.go:591  store=2:2 ([]=) range=1 [/Min-/Max): with replicaID [?], applied preemptive snapshot for range 1 in 6.992606ms
I160727 18:47:23.596647 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
I160727 18:47:23.597032 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- FAIL: TestReplicateAfterTruncation (0.09s)
panic: descriptor is not initialized [recovered]
	panic: descriptor is not initialized [recovered]
	panic: descriptor is not initialized [recovered]
	panic: descriptor is not initialized

goroutine 68476 [running]:
panic(0x1bae820, 0xc826ec63e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3ff
testing.tRunner.func1(0xc825560e10)
	/usr/local/go/src/testing/testing.go:467 +0x22a
panic(0x1bae820, 0xc826ec63e0)
	/usr/local/go/src/runtime/panic.go:443 +0x521
github.com/cockroachdb/cockroach/util/leaktest.AfterTest.func1()
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:77 +0xb1
panic(0x1bae820, 0xc826ec63e0)
	/usr/local/go/src/runtime/panic.go:443 +0x521
github.com/cockroachdb/cockroach/storage.(*Store).Send.func1(0xc8282d3378, 0xc8282d33f0, 0x0, 0x3a, 0xc8282d33e8, 0xc820852a00)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2119 +0x72
panic(0x1bae820, 0xc826ec63e0)
	/usr/local/go/src/runtime/panic.go:443 +0x521
github.com/cockroachdb/cockroach/roachpb.NewRangeKeyMismatchError(0xc826ec6258, 0x1, 0x8, 0x0, 0x0, 0x0, 0xc82f090180, 0x0)
	/go/src/github.com/cockroachdb/cockroach/roachpb/errors.go:301 +0xda
github.com/cockroachdb/cockroach/storage.(*Replica).checkCmdHeader(0xc826ed4c00, 0xc826ec6258, 0x1, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:855 +0x10e
github.com/cockroachdb/cockroach/storage.(*Replica).executeCmd(0xc826ed4c00, 0x7f429cf7f8c8, 0xc824d7fa40, 0x0, 0x0, 0x0, 0x7f429cf7e658, 0xc827ee07e0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:75 +0x16f
github.com/cockroachdb/cockroach/storage.(*Replica).executeBatch(0xc826ed4c00, 0x7f429cf7f8c8, 0xc824d7fa40, 0x0, 0x0, 0x7f429cf7e658, 0xc827ee07e0, 0x0, 0x0, 0x39, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2321 +0x70b
github.com/cockroachdb/cockroach/storage.(*Replica).addReadOnlyCmd(0xc826ed4c00, 0x7f429cf7f8c8, 0xc824d7fa40, 0x0, 0x39, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
--
testing.tRunner(0xc825560e10, 0x2e600c8)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3

goroutine 1 [chan receive]:
testing.RunTests(0x25bbc40, 0x2e5ea60, 0x127, 0x127, 0xc82013b301)
	/usr/local/go/src/testing/testing.go:583 +0xb39
testing.(*M).Run(0xc820097f00, 0xc820255c90)
	/usr/local/go/src/testing/testing.go:515 +0x11e
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc820097f00)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:57 +0x2d5
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:652 +0x20b

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x317ba20)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1015 +0x76
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0xc5
FAIL	github.com/cockroachdb/cockroach/storage	158.350s
=== RUN   TestBatchBasics
I160727 18:47:10.210457 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
I160727 18:47:10.213862 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchRepr
I160727 18:47:10.225863 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
I160727 18:47:10.227738 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.03s)
=== RUN   TestBatchGet
I160727 18:47:10.247932 storage/engine/rocksdb.go:353  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
#8086
