### ISSUE TITLE
rangefeed: rare panic when closing monitor in tests

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#80808]
In this [build](https://teamcity.cockroachdb.com/viewLog.html?buildId=5059733&buildTypeId=Cockroach_UnitTests), I got the following failure:
```
=== RUN   TestStreamerMultiRangeScan
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestStreamerMultiRangeScan2920046259
    test_log_scope.go:80: use -show-logs to present logs inline
    panic.go:1038: -- test log scope end --
panic: rangefeed-system-monitor: unexpected 20480 leftover bytes

goroutine 921 [running]:
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic({0x55cfff8, 0xc0008dcdb0}, 0xc00054e000, {0x41da3ee, 0xc000fc2518}, {0xc001caf730, 0xb40680, 0xc002c7acb0})
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:376 +0x1af
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc000c8d080, {0x55cfff8, 0xc0008dcdb0}, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:426 +0x22a
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:406
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*BudgetFactory).Stop(0xc0005c1350, {0x55cfff8, 0xc0008dcdb0})
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/budget.go:356 +0x45
github.com/cockroachdb/cockroach/pkg/server.NewServer.func7()
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:509 +0x25
github.com/cockroachdb/cockroach/pkg/util/stop.CloserFn.Close(0xc001469560)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:107 +0x1a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:551 +0x2ef
```
The test is newly-added in #80749, but I don't think that it's the test to blame - it simply issues several queries.

**Comment by yuzefovich** [comment]
Never mind - the test was the problem (but the root cause of calling `rng.Intn(0)` which panics was non-obvious at all).
