### ISSUE TITLE
sql: failure in TestParallel (time out, but not on shutdown)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8089]
https://circleci.com/gh/tschottdorf/cockroach/2643

cc @RaduBerinde 

```
goroutine 31196 [semacquire]:
sync.runtime_Semacquire(0xc82022fb1c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc82022fb18)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/storage.(*Store).ReplicaCount(0xc82022f900, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2058 +0x3d
github.com/cockroachdb/cockroach/storage.(*Store).Descriptor(0xc82022f900, 0xd75b35, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2046 +0xa2
github.com/cockroachdb/cockroach/storage.(*Store).ComputeMetrics(0xc82022f900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2838 +0x45
github.com/cockroachdb/cockroach/testutils/testcluster.(*TestCluster).WaitForFullReplication.func1(0xc82022f900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/testcluster.go:436 +0x3a
github.com/cockroachdb/cockroach/storage.(*Stores).VisitStores(0xc8204f2040, 0xc822ea5608, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/stores.go:121 +0x102
github.com/cockroachdb/cockroach/testutils/testcluster.(*TestCluster).WaitForFullReplication(0xc820114900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/testcluster.go:435 +0x1f8
github.com/cockroachdb/cockroach/sql_test.(*parallelTest).setup(0xc820114540, 0xc820114660)
	/go/src/github.com/cockroachdb/cockroach/sql/parallel_test.go:212 +0xa97
github.com/cockroachdb/cockroach/sql_test.(*parallelTest).run(0xc820114540, 0xc8203d8060, 0x24)
	/go/src/github.com/cockroachdb/cockroach/sql/parallel_test.go:138 +0x4d4
github.com/cockroachdb/cockroach/sql_test.TestParallel(0xc820a99b00)
	/go/src/github.com/cockroachdb/cockroach/sql/parallel_test.go:232 +0x43e
testing.tRunner(0xc820a99b00, 0x2747058)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

```

**Comment by RaduBerinde** [comment]
This is the temporarily disabled test;  just setting up a TestCluster of 5 nodes, creating a database, and doing `WaitForFullReplication` times out.

This is similar to the failure documented here: https://github.com/cockroachdb/cockroach/issues/8057#issuecomment-235617267 (except that it happens a bit after creating the database).

**Comment by RaduBerinde** [comment]
Just like in the other case, I see a bunch of `dist_sender.go:948  RPC error: rpc error: code = 4 desc = context deadline exceeded`; I believe PR #8076 should help with debugging this.

**Comment by RaduBerinde** [comment]
Temporarily removed the test, #8057 tracks fixing the underlying issues and reenabling.
