### ISSUE TITLE
log: blocked log file rotation can prevent fatal log lines from crashing process in a timely fashion

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#81025]
**Describe the problem**

An longer than typical log file rotation - a slow flush of the existing file, followed by latency creating the new file (e.g. in a period of elevated filesystem latency, or "stalls") - can prevent "fatal" log lines from crashing the process in a timely fashion.

**To Reproduce**

Assume the filesystem on which log files are written is under duress - certain operations may take many seconds to complete (specifically writes, syncs, and creation of new files).

Consider the following sequence of events during this period:
- a logging event triggers the rotation of a log file - this happens via the following calls:
  - [`(l *fileSink).output()` acquires the mutex for the log sink](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file.go#L183) before calling [`(l *fileSink).writeToFileLocked()`](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file.go#L190)
  - `(l *fileSink).writeToFileLocked()` [calls `Write()`](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file_sync_buffer.go#L59) on the sink's `flushSyncWriter` interface
  - the concrete type is a `syncBuffer`, with an implementation of `Write()` that [rotates the file](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file_sync_buffer.go#L46-L50) if it exceeds some limit
- this file rotation:
  - first [flushes the existing log file](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file_sync_buffer.go#L154)
  - [creates a new log file](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file_sync_buffer.go#L162)
  - either of these two operations could stall indefinitely

Assume the filesystem prevents rotating this log file.

Consider now another goroutine that wishes to crash the process by calling [`log.Fatalf`](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/log_channels_generated.go#L734-L736). This function may need to log into the sink that is blocked waiting for its log file to rotate.

When logging a fatal event, [`logfDepth` first calls itself recursively with the same event, downgrading the severity to `INFO`](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/channels.go#L67-L84). As this event is logged to the sink that is blocked on the file rotation, this recursive call blocks. This effectively prevents the "fatal" part (after the recursion pops back up) from occurring.

This sounds academic. However, in a real world example (see [this](https://github.com/cockroachlabs/support/issues/1571) support case), the following occurred:
- One or more storage volumes were degraded (at least one volume for a Pebble store, and another that backed the log files)
- A Pebble write / sync operation stalled.
- Pebble calls `Fatalf` after 60 seconds - at this point the process should crash.
- However, the process remained alive for 7 minutes.
- After the log file eventually rotated and the new file was created - the fatal event made its way through the logging framework and killed the process, printing the desired fatal line - albeit 7 minutes too late. 

**Expected behavior**

Calling `Fatalf` should crash the process as soon as reasonably possible, even if this means that logs may not be durably persisted in a timely fashion. It should honor the "fatal" part of the API.

**Additional data / screenshots**

We do already have a timer that should kill the process if logging is blocked. However, this is for syncing the file. There is an [existing TODO](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file.go#L243-L256) that points at #56893. The timer is only set after a the write has completed. The write may block (as explained above), so the timer is too late.

**Environment:**
 - CockroachDB version: observed on v21.2.9
 - Server OS: Linux

**Comment by nicktrav** [comment]
I've have been able to reproduce this with some butchering of the existing logging code to simulate a stall in the log file rotation. It's late here, so I plan on writing this up some more when I log on again tomorrow.

**Comment by tbg** [comment]
Great investigation! The logging code already tries to be smart about making sure the exiting happens either way. Similar to a circuit breaker, we likely need to lift that all the way to the top:

https://github.com/cockroachdb/cockroach/blob/dd6d46c085bdc9ee07909499ff3d7c311b982245/pkg/util/log/clog.go#L278-L285

**Comment by nicktrav** [comment]
I pushed a unit test with a repro in #81067.

**Comment by knz** [comment]
> When logging a fatal event, [logfDepth first calls itself recursively with the same event, downgrading the severity to INFO](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/channels.go#L67-L84). As this event is logged to the sink that is blocked on the file rotation, this recursive call blocks. This effectively prevents the "fatal" part (after the recursion pops back up) from occurring.

Can you show us more precisely what you mean here? The code you've linked to does not match your description. My own reading of the fatal code is that it always terminates.

**Comment by nicktrav** [comment]
> The code you've linked to does not match your description.

_Mae culpa._ I should have linked to [`logfDepth`](https://github.com/cockroachdb/cockroach/blob/fb8e09abd776e23a334292ad8e0bad70f7d98698/pkg/util/log/channels.go#L34-L61), not `shoutfDepth`.

Here's a restatement of what I believe to be happening (I'm browsing `master` at fb8e09abd7): 

- Some goroutine wants to panic with a fatal log line, calling `log.Fatalf`
- `log.Fatalf` calls `logfDepth` with `severity.FATAL`
- This calls itself recursively to inform `channel.OPS` with `severity.INFO`
- This calls into `outputLogEntry`, which then calls into `(*fileSink).output`
- `(*fileSink).output` blocks waiting to acquire the mutex that another goroutine is holding (the one blocked rotating the file as the disk is stalled)

The installation of the timer (which panics for slow syncs) is only installed _after_ acquiring the mutex. The other goroutine (the one holding the mutex) hasn't got there yet either, as it's blocked in `(*fileSink).writeToFileLocked` (due to the disk stall), therefore no early panic due to slow logging.

**Comment by nicktrav** [comment]
I tweaked the reproducer a bit to dump the goroutine stacks, and here's an example of the blocking behavior described above.

```console
goroutine 11 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*blockingSyncBuffer).rotateFileLocked(...)
        github.com/cockroachdb/cockroach/pkg/util/log/file_rotation_test.go:43
github.com/cockroachdb/cockroach/pkg/util/log.(*blockingSyncBuffer).Write(0xc0005a9640, {0xc0005c67b8, 0x3, 0x3})
        github.com/cockroachdb/cockroach/pkg/util/log/file_rotation_test.go:52 +0x7d
github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).writeToFileLocked(...)
        github.com/cockroachdb/cockroach/pkg/util/log/file_sync_buffer.go:59
github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).output(0xc00033c8f0, {0xc0005c67b8, 0x3, 0x3}, {0x80, 0x1f, 0x51})
        github.com/cockroachdb/cockroach/pkg/util/log/file.go:194 +0xf7
github.com/cockroachdb/cockroach/pkg/util/log.TestRepro81025.func4()
        github.com/cockroachdb/cockroach/pkg/util/log/file_rotation_test.go:153 +0x65
created by github.com/cockroachdb/cockroach/pkg/util/log.TestRepro81025
        github.com/cockroachdb/cockroach/pkg/util/log/file_rotation_test.go:152 +0x5f1

goroutine 12 [semacquire]:
sync.runtime_SemacquireMutex(0x0, 0x0, 0x0)
        GOROOT/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc00033c980)
        GOROOT/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        GOROOT/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0x2)
        GOROOT/src/sync/rwmutex.go:111 +0x36
github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).output(0xc00033c8f0, {0xc000040300, 0x99, 0xb5}, {0x0, 0x0, 0x0})
        github.com/cockroachdb/cockroach/pkg/util/log/file.go:187 +0x78
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc00013be60, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, 0x16f095aea15e54b0, ...})
        github.com/cockroachdb/cockroach/pkg/util/log/clog.go:336 +0x947
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth({0x4ec44d0, 0xc000138008}, 0x2, 0x1, 0x1, {0x4d20a2c, 0x4f}, {0xc000093e80, 0x1, 0x1})
        github.com/cockroachdb/cockroach/pkg/util/log/channels.go:60 +0x385
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth({0x4ec44d0, 0xc000138008}, 0x1, 0x4, 0x0, {0x4cc723d, 0x5}, {0x0, 0x0, 0x0})
        github.com/cockroachdb/cockroach/pkg/util/log/channels.go:46 +0x1aa
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
        github.com/cockroachdb/cockroach/bazel-out/darwin-fastbuild/bin/pkg/util/log/log_channels_generated.go:834
github.com/cockroachdb/cockroach/pkg/util/log.TestRepro81025.func5()
        github.com/cockroachdb/cockroach/pkg/util/log/file_rotation_test.go:165 +0x59
created by github.com/cockroachdb/cockroach/pkg/util/log.TestRepro81025
        github.com/cockroachdb/cockroach/pkg/util/log/file_rotation_test.go:164 +0x665
```

The first stack is a best effort to simulate the stalled file. The channel receive is what I'm using to emulate that - I believe if we had dumps from a real world example (unfortunately, we weren't able to gather these), this would most likely be stuck in a syscall instead.

**Comment by erikgrinaker** [comment]
@dhartunian Have you had a chance to look into this yet? This is (nearly) the last outstanding short-term item from https://github.com/cockroachlabs/support/issues/1571#issuecomment-1131424413.

**Comment by dhartunian** [comment]
@erikgrinaker yes I started taking a look last week. Will update with my progress later today.
