### ISSUE TITLE
circleci: failed tests: TestNodeJoinSelf 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8122]
The following test appears to have failed:

[#20718](https://circleci.com/gh/cockroachdb/cockroach/20718):

```
W160729 16:21:35.380988 gossip/gossip.go:953  not connected to cluster; use --join to specify a connected node
I160729 16:21:35.381348 gossip/client.go:75  starting client to 127.0.0.1:48634
I160729 16:21:35.387861 server/node.go:397  store store=0:0 ([]=) not bootstrapped
W160729 16:21:35.388209 gossip/gossip.go:953  not connected to cluster; use --join to specify a connected node
I160729 16:21:35.388464 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- FAIL: TestNodeJoinSelf (5.04s)
	leaktest.go:92: Leaked goroutine: goroutine 4083 [chan receive]:
		google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake(0xc820024210, 0xc820f0c550, 0xf, 0x7f4653750ce8, 0xc820024270, 0x4a811e114, 0x0, 0x0, 0x0, 0x0, ...)
			/go/src/google.golang.org/grpc/credentials/credentials.go:170 +0x3b5
		google.golang.org/grpc/transport.newHTTP2Client(0xc820f0c550, 0xf, 0x0, 0x0, 0xc820764180, 0x0, 0x0, 0x0, 0x0, 0x7f46537929d0, ...)
			/go/src/google.golang.org/grpc/transport/http2_client.go:134 +0x3ac
		google.golang.org/grpc/transport.NewClientTransport(0xc820f0c550, 0xf, 0x0, 0x0, 0xc820764180, 0x0, 0x0, 0x0, 0x0, 0x7f46537929d0, ...)
			/go/src/google.golang.org/grpc/transport/transport.go:373 +0x6e
		google.golang.org/grpc.(*addrConn).resetTransport(0xc8210ec6c0, 0x0, 0x0, 0x0)
			/go/src/google.golang.org/grpc/clientconn.go:568 +0x42f
		google.golang.org/grpc.(*ClientConn).newAddrConn.func1(0xc8210ec6c0)
--
E160729 16:21:45.347740 storage/replica.go:1923  store=1:1 ([]=) range=5 [/Table/14-/Max): error executing raft command: storage/replica.go:1802: no-op on empty Raft entry
I160729 16:21:45.348077 http2_server.go:268  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:39909->127.0.0.1:52249: use of closed network connection
I160729 16:21:45.348221 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
I160729 16:21:45.348403 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- PASS: TestReportUsage (0.22s)
FAIL
FAIL	github.com/cockroachdb/cockroach/server	16.315s
?   	github.com/cockroachdb/cockroach/server/serverpb	[no test files]
=== RUN   TestMetricsRecorder
--- PASS: TestMetricsRecorder (0.06s)
PASS
ok  	github.com/cockroachdb/cockroach/server/status	0.092s
I160729 16:22:13.604392 rand.go:76  Random seed: -4831352986520552551
=== RUN   TestSplitOrExpr
--- PASS: TestSplitOrExpr (0.00s)
=== RUN   TestSplitAndExpr
--- PASS: TestSplitAndExpr (0.01s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
#7793.

**Comment by tamird** [comment]
This is another instance of shitty cancellation in grpc.
