### ISSUE TITLE
kvserver: `TestReplicaProbeRequest` is flaky

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#81424]
Reproduces fairly readily under stress on `master`. I've seen two failure modes:

```
=== RUN   TestReplicaProbeRequest
    test_log_scope.go:79: test logs captured to: /home/erik/.cache/bazel/_bazel_erik/58b8816bb117734f0a0eaaef7fcef95b/sandbox/linux-sandbox/677/execroot/com_github_cockroachdb_cockroach/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestReplicaProbeRequest1952254550
    test_log_scope.go:80: use -show-logs to present logs inline
    replica_probe_test.go:108: condition failed to evaluate within 45s: saw only 5 probes on s3
        goroutine 83 [running]:
        runtime/debug.Stack()
        	GOROOT/src/runtime/debug/stack.go:24 +0x65
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithin({0x5b779b8, 0xc0000fcd00}, 0x0, 0x1290420)
        	github.com/cockroachdb/cockroach/pkg/testutils/soon.go:60 +0x5f
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon({0x5b779b8, 0xc0000fcd00}, 0x0)
        	github.com/cockroachdb/cockroach/pkg/testutils/soon.go:41 +0x4a
        github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestReplicaProbeRequest(0xc0000fcd00)
        	github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/replica_probe_test.go:108 +0x69d
        testing.tRunner(0xc0000fcd00, 0x4862238)
        	GOROOT/src/testing/testing.go:1259 +0x102
        created by testing.(*T).Run
        	GOROOT/src/testing/testing.go:1306 +0x35a
    panic.go:642: -- test log scope end --
test logs left over in: /home/erik/.cache/bazel/_bazel_erik/58b8816bb117734f0a0eaaef7fcef95b/sandbox/linux-sandbox/677/execroot/com_github_cockroachdb_cockroach/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestReplicaProbeRequest1952254550
--- FAIL: TestReplicaProbeRequest (46.45s)
```

and

```
=== RUN   TestReplicaProbeRequest
    test_log_scope.go:79: test logs captured to: /home/erik/.cache/bazel/_bazel_erik/58b8816bb117734f0a0eaaef7fcef95b/sandbox/linux-sandbox/728/execroot/com_github_cockroachdb_cockroach/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestReplicaProbeRequest1647998711
    test_log_scope.go:80: use -show-logs to present logs inline
    replica_probe_test.go:98: 
        	Error Trace:	replica_probe_test.go:98
        	Error:      	Received unexpected error:
        	            	result is ambiguous: unable to determine whether command was applied via snapshot
        	            	(1) result is ambiguous: unable to determine whether command was applied via snapshot
        	            	Wraps: (2)
        	            	  | (opaque error wrapper)
        	            	  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
        	            	  | reportable 0:
        	            	  |
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).refreshProposalsLocked
        	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1286
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
        	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1047
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest.func1
        	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:457
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).withReplicaForRequest
        	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:336
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest
        	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:395
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).receiveSnapshot
        	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go:788
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot.func1
        	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:211
        	            	  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
        	            	  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:344
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot
        	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:208
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).RaftSnapshot.func1.1
        	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:525
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).RaftSnapshot.func1
        	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:526
        	            	  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
        	            	  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494
        	            	  | runtime.goexit
        	            	  | 	GOROOT/src/runtime/asm_amd64.s:1581
        	            	Wraps: (3) unable to determine whether command was applied via snapshot
        	            	Error types: (1) *roachpb.AmbiguousResultError (2) *errbase.opaqueWrapper (3) *errutil.leafError
        	Test:       	TestReplicaProbeRequest
    panic.go:642: -- test log scope end --
test logs left over in: /home/erik/.cache/bazel/_bazel_erik/58b8816bb117734f0a0eaaef7fcef95b/sandbox/linux-sandbox/728/execroot/com_github_cockroachdb_cockroach/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestReplicaProbeRequest1647998711
--- FAIL: TestReplicaProbeRequest (2.37s)
```

Jira issue: CRDB-15197

**Comment by pavelkalinnikov** [comment]
I tried this under `--stress`/`--race` and bisecting between master and afb50d62. Reproduces very rarely. I saw the "unable to determine whether command was applied via snapshot" failure once over a few hours. Could not trigger either of the errors on master, but they still seem to occur sometimes in CI (last time Sep 30 on master).

**Comment by tbg** [comment]
```
I221123 09:39:58.160086 2698 kv/kvserver/replica_raftstorage.go:739 ⋮ [n3,s3,r54/3:‹/{Table/Max-Max}›] 149  applied INITIAL snapshot 2e6828d9 from (n1,s1):1 at applied index 18 (total=2ms data=1.5 KiB ingestion=6@2ms)
I221123 09:39:58.170182 2827 kv/kvserver/replica_raftstorage.go:739 ⋮ [n3,s3,r54/3:‹/{Table/Max-Max}›] 150  applied VIA_SNAPSHOT_QUEUE snapshot 98b85f5d from (n1,s1):1 at applied index 20 (total=3ms data=1.5 KiB ingestion=6@2ms)
```

This is the problem - for some reason, sometimes there's an extra raft snapshot. When that snapshot replaces the application of the probe's log position, the interceptor doesn't fire (i.e. the test doesn't see that probe log entry apply on that replica), so it gets confused. Why is there a snapshot there? It's basically one case in https://github.com/cockroachdb/cockroach/blob/master/docs/tech-notes/raft-snapshots.md.

I think the following ordering happens:

- `tc.AddVoterOrWhatever` starts
- it calls changereplicas
- adds follower
- follower gets a raft msg, asks for snapshot, leader has it enqueued in raft snap queue
- locks snapshot queue against sending snaps
- send INITIAL snapshot
- unlocks
- AddVoterOrWhatever returns to the test
- test sends probe
- log queue processes
- sends another snap which includes the probe
- follower applies the probe via the snap.

Sending a PR.
