### ISSUE TITLE
circleci: failed tests: TestParallel TestSchemaChangeRetry TestErrorOnCommitResultsInRollback 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8146]
The following test appears to have failed:

[#20744](https://circleci.com/gh/cockroachdb/cockroach/20744):

```
I160730 16:40:44.834301 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
I160730 16:40:44.836067 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
I160730 16:40:44.838207 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
I160730 16:40:44.839218 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
2 parallel tests passed
--- FAIL: TestParallel (16.88s)
	<autogenerated>:31: Leaked goroutine: goroutine 37807 [select]:
		google.golang.org/grpc/transport.(*http2Client).controller(0xc8205db000)
			/go/src/google.golang.org/grpc/transport/http2_client.go:965 +0x8ef
		created by google.golang.org/grpc/transport.newHTTP2Client
			/go/src/google.golang.org/grpc/transport/http2_client.go:206 +0x19ce
=== RUN   TestPGWire
I160730 16:40:49.848197 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
W160730 16:40:49.850777 server/server.go:111  running in insecure mode, this is strongly discouraged. See --insecure.
W160730 16:40:49.851464 gossip/gossip.go:1006  not connected to cluster; use --join to specify a connected node
I160730 16:40:49.861341 server/node.go:397  store store=0:0 ([]=) not bootstrapped
--
I160730 16:41:41.231868 kv/dist_sender.go:934  application error: retry txn "sql/lease.go:228 LeaseStore.Release" id=ce71ff96 key=/Table/11/1/51/3/2016-07-30T16:45:26.232365868Z/1 rw=true pri=0.00649109 iso=SERIALIZABLE stat=PENDING epo=0 ts=1469896901.213082436,1 orig=1469896901.205785883,0 max=1469896901.205785883,0 wto=false rop=false
W160730 16:41:41.232098 kv/dist_sender.go:729  failed to invoke EndTransaction [/Table/11/1/51/3/2016-07-30T16:45:26.232365868Z/1,/Min): retry txn "sql/lease.go:228 LeaseStore.Release" id=ce71ff96 key=/Table/11/1/51/3/2016-07-30T16:45:26.232365868Z/1 rw=true pri=0.00649109 iso=SERIALIZABLE stat=PENDING epo=0 ts=1469896901.213082436,1 orig=1469896901.205785883,0 max=1469896901.205785883,0 wto=false rop=false
I160730 16:41:41.232596 internal/client/db.go:489  failed batch: retry txn "sql/lease.go:228 LeaseStore.Release" id=ce71ff96 key=/Table/11/1/51/3/2016-07-30T16:45:26.232365868Z/1 rw=true pri=0.02725865 iso=SERIALIZABLE stat=PENDING epo=1 ts=1469896901.213082436,1 orig=1469896901.213082436,1 max=1469896901.255785883,0 wto=false rop=false
I160730 16:41:41.321316 http2_server.go:268  transport: http2Server.HandleStreams failed to read frame: EOF
I160730 16:41:41.321792 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- FAIL: TestSchemaChangeRetry (6.34s)
	<autogenerated>:31: Leaked goroutine: goroutine 37807 [select, 1 minutes]:
		google.golang.org/grpc/transport.(*http2Client).controller(0xc8205db000)
			/go/src/google.golang.org/grpc/transport/http2_client.go:965 +0x8ef
		created by google.golang.org/grpc/transport.newHTTP2Client
			/go/src/google.golang.org/grpc/transport/http2_client.go:206 +0x19ce
=== RUN   TestSchemaChangePurgeFailure
I160730 16:41:46.333458 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
W160730 16:41:46.357319 gossip/gossip.go:1006  not connected to cluster; use --join to specify a connected node
I160730 16:41:46.396235 server/node.go:397  store store=0:0 ([]=) not bootstrapped
I160730 16:41:46.422433 storage/replica.go:1881  store=1:1 ([]=) range=1 [/Min-/Max): applying command with forced error: storage/replica.go:1802: no-op on empty Raft entry
--
I160730 16:42:00.321959 kv/dist_sender.go:934  application error: txn aborted "sql/executor.go:465 sql txn" id=d4a503a2 key=/Table/51/1/0/0 rw=true pri=46.56612871 iso=SERIALIZABLE stat=ABORTED epo=0 ts=1469896920.295781974,1 orig=1469896920.175000617,0 max=1469896920.175000617,0 wto=false rop=false
W160730 16:42:00.322187 kv/dist_sender.go:729  failed to invoke EndTransaction [/Table/51/1/0/0,/Min): txn aborted "sql/executor.go:465 sql txn" id=d4a503a2 key=/Table/51/1/0/0 rw=true pri=46.56612871 iso=SERIALIZABLE stat=ABORTED epo=0 ts=1469896920.295781974,1 orig=1469896920.175000617,0 max=1469896920.175000617,0 wto=false rop=false
I160730 16:42:00.322948 internal/client/db.go:489  failed batch: txn aborted "sql/executor.go:465 sql txn" id=d4a503a2 key=/Table/51/1/0/0 rw=true pri=46.56612871 iso=SERIALIZABLE stat=ABORTED epo=0 ts=1469896920.295781974,1 orig=1469896920.175000617,0 max=1469896920.225000617,0 wto=false rop=false
I160730 16:42:00.330220 http2_server.go:268  transport: http2Server.HandleStreams failed to read frame: EOF
I160730 16:42:00.330664 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- FAIL: TestErrorOnCommitResultsInRollback (5.81s)
	<autogenerated>:31: Leaked goroutine: goroutine 37807 [select, 1 minutes]:
		google.golang.org/grpc/transport.(*http2Client).controller(0xc8205db000)
			/go/src/google.golang.org/grpc/transport/http2_client.go:965 +0x8ef
		created by google.golang.org/grpc/transport.newHTTP2Client
			/go/src/google.golang.org/grpc/transport/http2_client.go:206 +0x19ce
=== RUN   TestCommitFinalizesTxnOnError
I160730 16:42:05.344694 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
W160730 16:42:05.367021 gossip/gossip.go:1006  not connected to cluster; use --join to specify a connected node
I160730 16:42:05.384432 server/node.go:397  store store=0:0 ([]=) not bootstrapped
I160730 16:42:05.395527 storage/replica.go:1881  store=1:1 ([]=) range=1 [/Min-/Max): applying command with forced error: storage/replica.go:1802: no-op on empty Raft entry
--
W160730 16:42:10.601930 kv/dist_sender.go:729  failed to invoke Scan [/Table/51/1/"test_key",/Table/51/1/"test_key\x00"): read at time 1469898430.598761988,7 encountered previous write with future timestamp 1469898430.598761988,7 within uncertainty interval
I160730 16:42:10.602248 internal/client/db.go:489  failed batch: read at time 1469898430.598761988,7 encountered previous write with future timestamp 1469898430.598761988,7 within uncertainty interval
I160730 16:42:10.630823 http2_server.go:268  transport: http2Server.HandleStreams failed to read frame: EOF
I160730 16:42:10.631241 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- PASS: TestReacquireLeaseOnRestart (0.80s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	237.244s
I160730 16:38:24.031056 rand.go:76  Random seed: -7741247978217708256
=== RUN   TestProcessExpression
--- PASS: TestProcessExpression (0.03s)
=== RUN   TestFlowRegistry
--- PASS: TestFlowRegistry (0.30s)
=== RUN   TestOrderedSync
--- PASS: TestOrderedSync (0.00s)
=== RUN   TestJoinReader
I160730 16:38:24.374255 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
W160730 16:38:24.398197 gossip/gossip.go:1006  not connected to cluster; use --join to specify a connected node

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
#8133.
