### ISSUE TITLE
storage: `panic: descriptor is not initialized` in TestReplicateRange

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#8157]
Seen in #8150: https://circleci.com/gh/tamird/cockroach/355.

```
panic: descriptor is not initialized [recovered]
	panic: descriptor is not initialized [recovered]
	panic: descriptor is not initialized [recovered]
	panic: descriptor is not initialized

goroutine 67996 [running]:
panic(0x1bd9520, 0xc8221ca500)
	/usr/local/go/src/runtime/panic.go:481 +0x3ff
testing.tRunner.func1(0xc825ea3200)
	/usr/local/go/src/testing/testing.go:467 +0x22a
panic(0x1bd9520, 0xc8221ca500)
	/usr/local/go/src/runtime/panic.go:443 +0x521
github.com/cockroachdb/cockroach/util/leaktest.AfterTest.func1()
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:88 +0xb1
panic(0x1bd9520, 0xc8221ca500)
	/usr/local/go/src/runtime/panic.go:443 +0x521
github.com/cockroachdb/cockroach/storage.(*Store).Send.func1(0xc824f5d3c0, 0xc824f5d438, 0x0, 0x37, 0xc824f5d430, 0xc825bc7900)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2112 +0x72
panic(0x1bd9520, 0xc8221ca500)
	/usr/local/go/src/runtime/panic.go:443 +0x521
github.com/cockroachdb/cockroach/roachpb.NewRangeKeyMismatchError(0xc8221ca388, 0x1, 0x8, 0x0, 0x0, 0x0, 0xc824963b60, 0x0)
	/go/src/github.com/cockroachdb/cockroach/roachpb/errors.go:301 +0xd5
github.com/cockroachdb/cockroach/storage.(*Replica).checkCmdHeader(0xc822188a00, 0xc8221ca388, 0x1, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:855 +0x10e
github.com/cockroachdb/cockroach/storage.(*Replica).executeCmd(0xc822188a00, 0x7f54da98d440, 0xc8252ef680, 0x0, 0x0, 0x0, 0x7f54da98a858, 0xc824e07c80, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:75 +0x16f
github.com/cockroachdb/cockroach/storage.(*Replica).executeBatch(0xc822188a00, 0x7f54da98d440, 0xc8252ef680, 0x0, 0x0, 0x7f54da98a858, 0xc824e07c80, 0x0, 0x0, 0x36, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2324 +0x70f
github.com/cockroachdb/cockroach/storage.(*Replica).addReadOnlyCmd(0xc822188a00, 0x7f54da98d440, 0xc8252ef680, 0x0, 0x36, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1186 +0x3d4
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc822188a00, 0x7f54da98d440, 0xc8252ef680, 0x0, 0x36, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:830 +0x5fa
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc825bc7900, 0x7f54da98a600, 0xc82000e538, 0x0, 0x36, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2207 +0x1080
github.com/cockroachdb/cockroach/internal/client.Wrap.func1(0x7f54da98a600, 0xc82000e538, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/sender.go:76 +0xc5
github.com/cockroachdb/cockroach/internal/client.SenderFunc.Send(0xc822122700, 0x7f54da98a600, 0xc82000e538, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/sender.go:37 +0x64
github.com/cockroachdb/cockroach/internal/client.SendWrappedWith(0x7f54da922b10, 0xc822122700, 0x7f54da98a600, 0xc82000e538, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/sender.go:54 +0x1f3
github.com/cockroachdb/cockroach/storage_test.TestReplicateRange.func2(0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:288 +0x375
github.com/cockroachdb/cockroach/util.RetryForDuration(0x37e11d600, 0xc824f5dd18, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/testing.go:127 +0x193
github.com/cockroachdb/cockroach/util.SucceedsSoonDepth(0x1, 0x7f54da98ea00, 0xc825ea3200, 0xc824f5dd18)
	/go/src/github.com/cockroachdb/cockroach/util/testing.go:114 +0x45
github.com/cockroachdb/cockroach/util.SucceedsSoon(0x7f54da98ea00, 0xc825ea3200, 0xc824f5dd18)
	/go/src/github.com/cockroachdb/cockroach/util/testing.go:108 +0x4c
github.com/cockroachdb/cockroach/storage_test.TestReplicateRange(0xc825ea3200)
	/go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:294 +0x1233
testing.tRunner(0xc825ea3200, 0x2eaef60)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3
```

**Comment by tschottdorf** [comment]
`make stress PKG=./storage TESTS=TestReplicateAfterTruncation` gets this in `<<1min`. Looking.
