### ISSUE TITLE
roachtest: crash in saveDiskUsageToLogsDir

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#81655]
**Describe the problem**

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[15:18:29]		panic: runtime error: invalid memory address or nil pointer dereference
[15:18:29]	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43ae2d7]
[15:18:29]	
[15:18:29]	goroutine 19727 [running]:
[15:18:29]	github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc0020cfe60, {0x66fa338, 0xc0021e0240})
[15:18:29]		github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:251 +0x94
[15:18:29]	panic({0x4a179c0, 0x9619a70})
[15:18:29]		GOROOT/src/runtime/panic.go:1038 +0x215
[15:18:29]	os.(*File).Name(...)
[15:18:29]		GOROOT/src/os/file.go:57
[15:18:29]	main.(*clusterImpl).RunE(0x0, {0x66fa300, 0xc00142c120}, {0xc002184800, 0x4, 0x4}, {0xc0005c2be0, 0xc0006ed938, 0x1})
[15:18:29]		main/pkg/cmd/roachtest/cluster.go:1979 +0x2f7
[15:18:29]	main.saveDiskUsageToLogsDir.func1({0x66fa300, 0xc00142c120})
[15:18:29]		main/pkg/cmd/roachtest/cluster.go:1148 +0xb1
[15:18:29]	github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout({0x66fa338, 0xc0021e0240}, {0x517dae0, 0xa}, 0x4a817c800, 0xc0006edaa8)
[15:18:29]		github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:91 +0xb4
[15:18:29]	main.saveDiskUsageToLogsDir({0x66fa338, 0xc0021e0240}, {0x6820ee8, 0xc001ecc280})
[15:18:29]		main/pkg/cmd/roachtest/cluster.go:1147 +0x146
[15:18:29]	main.(*testRunner).collectClusterArtifacts(0xc001ecc280, {0x66fa338, 0xc0021e0240}, 0xc00136f2c0, {0x67fe9e8, 0xc00136f2c0})
[15:18:29]		main/pkg/cmd/roachtest/test_runner.go:1100 +0xae
[15:18:29]	main.(*testRunner).teardownTest.func1({0x66fa338, 0xc0021e0240})
[15:18:29]		main/pkg/cmd/roachtest/test_runner.go:982 +0x50d
[15:18:29]	github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
[15:18:29]		github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494 +0x16f
[15:18:29]	created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
[15:18:29]		github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:483 +0x445
```

https://cockroachlabs.slack.com/archives/C026MSSL926/p1652887194849339

Jira issue: CRDB-16014

**Comment by tbg** [comment]
This is on 22.1 btw, and much has changed, so this is likely lower priority as we are seeing fewer builds of these branches.
