### ISSUE TITLE
tests: Leaked goroutines resulting from client connection with low timeout

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#8204]
In CockroachDB tests, I have observed that leaked goroutines can result over HTTP connections with extremely low timeouts.  This can be reproduced easily by running `make stress` with the following test, which issues a trivial HTTP GET response to the server.

``` go
func TestFastTimeout(t *testing.T) {
    defer leaktest.AfterTest(t)()
    tc := testcluster.StartTestCluster(t, 3, base.TestClusterArgs{
        ReplicationMode: base.ReplicationAuto,
    })
    defer tc.Stopper().Stop()

    server0 := tc.Server(0)
    url := server0.AdminURL() + "/_admin/v1/health"
    client, err := server0.GetHTTPClient()
    if err != nil {
        t.Fatal(err)
    }
    var tsResponse serverpb.HealthResponse

    client.Timeout = 1 * time.Nanosecond
    if err := util.GetJSON(client, url, &tsResponse); err == nil {
        t.Fatal("Expected low-timeout request to fail, but it succeeded.")
    }
}
```

The output from leaktest is as follows:

```
--- FAIL: TestFastTimeout (8.18s)
        leaktest.go:108: Leaked goroutine: goroutine 591 [chan receive]:
                net/http.(*Transport).dialConn(0xc82039f380, 0x0, 0xc820838030, 0x5, 0xc820838038, 0xf, 0x0, 0x0, 0x0)
                        /usr/local/go/src/net/http/transport.go:834 +0x9c2
                net/http.(*Transport).getConn.func4(0xc82039f380, 0x0, 0xc820838030, 0x5, 0xc820838038, 0xf, 0xc8206b3ec0)
                        /usr/local/go/src/net/http/transport.go:706 +0x66
                created by net/http.(*Transport).getConn
                        /usr/local/go/src/net/http/transport.go:708 +0x262
        leaktest.go:108: Leaked goroutine: goroutine 592 [chan receive]:
                net/http.(*Transport).getConn.func2.1(0xc8206b3ec0, 0xc82039f380, 0x589d4d0)
                        /usr/local/go/src/net/http/transport.go:695 +0x48
                created by net/http.(*Transport).getConn.func2
                        /usr/local/go/src/net/http/transport.go:699 +0x70
```

This behavior is racy, but does reproduce quickly in stress tests.

**Comment by tamird** [comment]
This probably reproduces with a trivial HTTP handler outside of cockroach, no?

**Comment by mrtracy** [comment]
Another leak from this:

```
leaktest.go:108: Leaked goroutine: goroutine 1578 [IO wait]:
                net.runtime_pollWait(0xa245370, 0x72, 0xc821917c00)
                        /usr/local/go/src/runtime/netpoll.go:160 +0x60
                net.(*pollDesc).Wait(0xc82118e290, 0x72, 0x0, 0x0)
                        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
                net.(*pollDesc).WaitRead(0xc82118e290, 0x0, 0x0)
                        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
                net.(*netFD).Read(0xc82118e230, 0xc821917c00, 0x400, 0x400, 0x0, 0x7500050, 0xc820010098)
                        /usr/local/go/src/net/fd_unix.go:250 +0x23a
                net.(*conn).Read(0xc820a0c480, 0xc821917c00, 0x400, 0x400, 0x0, 0x0, 0x0)
                        /usr/local/go/src/net/net.go:172 +0xe4
                github.com/cockroachdb/cmux.(*MuxConn).Read(0xc8202b3c30, 0xc821917c00, 0x400, 0x400, 0xd, 0x0, 0x0)
                        /Users/matt/go/src/github.com/cockroachdb/cmux/cmux.go:221 +0x117
                crypto/tls.(*block).readFromUntil(0xc82198e000, 0x75c1d40, 0xc8202b3c30, 0x5, 0x0, 0x0)
                        /usr/local/go/src/crypto/tls/conn.go:460 +0xcc
                crypto/tls.(*Conn).readRecord(0xc820cc4f00, 0x589d817, 0x0, 0x0)
                        /usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
                crypto/tls.(*Conn).Read(0xc820cc4f00, 0xc8215a0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
                        /usr/local/go/src/crypto/tls/conn.go:939 +0x167
                net/http.(*connReader).Read(0xc82187fe20, 0xc8215a0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
                        /usr/local/go/src/net/http/server.go:526 +0x196
                bufio.(*Reader).fill(0xc8215b1560)
                        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
                bufio.(*Reader).ReadSlice(0xc8215b1560, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
                        /usr/local/go/src/bufio/bufio.go:328 +0x21a
                bufio.(*Reader).ReadLine(0xc8215b1560, 0x0, 0x0, 0x0, 0x5452e00, 0x0, 0x0)
                        /usr/local/go/src/bufio/bufio.go:357 +0x53
                net/textproto.(*Reader).readLineSlice(0xc821972cc0, 0x0, 0x0, 0x0, 0x0, 0x0)
                        /usr/local/go/src/net/textproto/reader.go:55 +0x81
                net/textproto.(*Reader).ReadLine(0xc821972cc0, 0x0, 0x0, 0x0, 0x0)
                        /usr/local/go/src/net/textproto/reader.go:36 +0x40
                net/http.readRequest(0xc8215b1560, 0xc81ff54600, 0xc82044bdc0, 0x0, 0x0)
                        /usr/local/go/src/net/http/request.go:721 +0xb6
                net/http.(*conn).readRequest(0xc821201200, 0x0, 0x0, 0x0)
                        /usr/local/go/src/net/http/server.go:705 +0x359
                net/http.(*conn).serve(0xc821201200)
                        /usr/local/go/src/net/http/server.go:1425 +0x947
                created by net/http.(*Server).Serve
                        /usr/local/go/src/net/http/server.go:2137 +0x44e
        leaktest.go:108: Leaked goroutine: goroutine 1653 [IO wait]:
                net.runtime_pollWait(0xa245970, 0x72, 0xc821917000)
                        /usr/local/go/src/runtime/netpoll.go:160 +0x60
                net.(*pollDesc).Wait(0xc8217f9c60, 0x72, 0x0, 0x0)
                        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
                net.(*pollDesc).WaitRead(0xc8217f9c60, 0x0, 0x0)
                        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
                net.(*netFD).Read(0xc8217f9c00, 0xc821917000, 0x400, 0x400, 0x0, 0x7500050, 0xc820010098)
                        /usr/local/go/src/net/fd_unix.go:250 +0x23a
                net.(*conn).Read(0xc82077e360, 0xc821917000, 0x400, 0x400, 0x0, 0x0, 0x0)
                        /usr/local/go/src/net/net.go:172 +0xe4
                crypto/tls.(*block).readFromUntil(0xc8210c2060, 0x75c1c90, 0xc82077e360, 0x5, 0x0, 0x0)
                        /usr/local/go/src/crypto/tls/conn.go:460 +0xcc
                crypto/tls.(*Conn).readRecord(0xc8207fa900, 0x589d817, 0x0, 0x0)
                        /usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
                crypto/tls.(*Conn).Read(0xc8207fa900, 0xc82135a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
                        /usr/local/go/src/crypto/tls/conn.go:939 +0x167
                net/http.noteEOFReader.Read(0x7550980, 0xc8207fa900, 0xc82190a6e8, 0xc82135a000, 0x1000, 0x1000, 0x60, 0x0, 0x0)
                        /usr/local/go/src/net/http/transport.go:1687 +0x67
                net/http.(*noteEOFReader).Read(0xc82187fee0, 0xc82135a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
                        <autogenerated>:284 +0xd0
                bufio.(*Reader).fill(0xc8215b1680)
                        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
                bufio.(*Reader).Peek(0xc8215b1680, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
                        /usr/local/go/src/bufio/bufio.go:132 +0xcc
                net/http.(*persistConn).readLoop(0xc82190a680)
                        /usr/local/go/src/net/http/transport.go:1073 +0x177
                created by net/http.(*Transport).dialConn
                        /usr/local/go/src/net/http/transport.go:857 +0x10a6
        leaktest.go:108: Leaked goroutine: goroutine 1654 [select]:
                net/http.(*persistConn).writeLoop(0xc82190a680)
                        /usr/local/go/src/net/http/transport.go:1277 +0x472
                created by net/http.(*Transport).dialConn
                        /usr/local/go/src/net/http/transport.go:858 +0x10cb
```

**Comment by mrtracy** [comment]
Still getting a leak: 

```
net/http.(*persistConn).writeLoop(0xc82130b930)
                        /usr/local/go/src/net/http/transport.go:1277 +0x472
                created by net/http.(*Transport).dialConn
                        /usr/local/go/src/net/http/transport.go:858 +0x10cb
```

**Comment by tamird** [comment]
@mrtracy ah, missed one. just add `net/http.(*persistConn).writeLoop` to leaktest in your PR.

**Comment by petermattis** [comment]
@tamird, @mrtracy Is there anything left to do here?

**Comment by tamird** [comment]
Nah.
