### ISSUE TITLE
storage: MVCC GC queue is getting tripped up on spanset assertions

### ISSUE THREAD

**Issue by lunevalex** [cockroachdb/cockroach#82143]
We are seeing mvccGC get tripped up on the spanset checks repeatedly. 

```
goroutine 631830 [chan receive, 57 minutes]:
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).WaitForNStores(0xc00528ca00, {0x9b15680, 0xc0044d21a0}, 0x4, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:538 +0x2ff
github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestGossipHandlesReplacedNode(0xc0044d21a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/gossip_test.go:199 +0x77c
testing.tRunner(0xc0044d21a0, 0x680e918)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727
```

Example of this is on the liveness range:

```
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578  cannot â€¹readâ€º undeclared span â€¹/{Min-System/NodeLiveness/2}â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +declared:
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹read local: /Local/Range/System/NodeLiveness/RangeDescriptor at 0,0â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹read local: /Local/Lock/Intent/Local/Range/System/NodeLiveness/RangeDescriptor at 0,0â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹write global: /System/NodeLiveness/1 at 1651055373.590339728,0â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹write global: /System/NodeLiveness/2 at 1651055373.590339728,0â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹write global: /System/NodeLiveness/3 at 1651055373.590339728,0â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹write local: /Local/Range/System/NodeLiveness/RangeDescriptor at 0,0â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹write local: /Local/Lock/Intent/System/NodeLiveness/1 at 0,0â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹write local: /Local/Lock/Intent/System/NodeLiveness/2 at 0,0â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹write local: /Local/Lock/Intent/System/NodeLiveness/3 at 0,0â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹write local: /Local/Lock/Intent/Local/Range/System/NodeLiveness/RangeDescriptor at 0,0â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +stack:
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹goroutine 860401 [running]:â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹runtime/debug.Stack()â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/usr/local/go/src/runtime/debug/stack.go:24 +0x72â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanset.(*SpanSet).checkAllowed(0xc006567ce0, 0x0, {{0x0, 0x0, 0x0}, {0xc02aa6dc0c, 0xc, 0xc}}, 0x680e660)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanset/spanset.go:352 +0x2edâ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanset.(*SpanSet).CheckAllowed(0xc006567ec0, 0xc004c761c8, {{0x0, 0x0, 0x0}, {0xc02aa6dc0c, 0xc, 0xc}})â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanset/spanset.go:283 +0xd4â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanset.(*MVCCIterator).checkAllowed(0xc003167ae0, {{0x0, 0x0, 0x0}, {0xc02aa6dc0c, 0xc, 0xc}}, 0x1)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanset/batch.go:133 +0x1a5â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanset.(*MVCCIterator).SeekLT(0xc003167ae0, {{0xc02aa6dc0c, 0xc, 0xc}, {0x16e9b9865d89f592, 0x0, 0x0}})â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanset/batch.go:101 +0x150â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/storage.MVCCGarbageCollect({0x9a445a0, 0xc01f4c5d40}, {0x7fe0c11440b8, 0xc000fc5170}, 0xc00842f400, {0xc00dd4b720, 0x0, 0x4}, {0x16e9ba1d575a2090, 0x0, ...})â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:3604 +0x1049â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval.GC({_, _}, {_, _}, {{0x9b453e8, 0xc000876fc0}, {{0x16e9ba1d575a2090, 0x0, 0x0}, 0x0, ...}, ...}, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_gc.go:115 +0x39dâ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateCommand({_, _}, {_, _}, {_, _}, _, {{0x16e9ba1d575a2090, 0x0, 0x0}, ...}, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_evaluate.go:493 +0x2c7â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch({_, _}, {_, _}, {_, _}, {_, _}, _, 0xc02c37de00, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_evaluate.go:270 +0xf4fâ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper(_, {_, _}, {_, _}, {_, _}, _, _, {{0x0, ...}, ...}, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_write.go:646 +0x1a7â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes(_, {_, _}, {_, _}, {_, _}, _, _, {{0x0, ...}, ...}, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_write.go:614 +0x29câ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatch(_, {_, _}, {_, _}, _, {{0x0, 0x0, 0x0}, {0x0, ...}}, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_write.go:429 +0x8ddâ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateProposal(0xc0038bd400, {0x9a445a0, 0xc01f4c5d40}, {0xc007acd8d8, 0x8}, 0xc02c37de00, {{0x0, 0x0, 0x0}, {0x0, ...}}, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_proposal.go:679 +0x21dâ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).requestToProposal(0xc00759edd8, {0x9a445a0, _}, {_, _}, _, {{{0x16e9b713f02277b4, 0x0, 0x0}, 0xc005f12c00, ...}, ...}, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_proposal.go:779 +0xfaâ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose(0xc0038bd400, {0x9a445a0, _}, _, _, {{{0x16e9b713f02277b4, 0x0, 0x0}, 0xc005f12c00, {0x3, ...}, ...}, ...}, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:113 +0x205â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch(0xc0038bd400, {0x9a445a0, 0xc01f4c5d40}, 0xc02c37de00, 0xc00db74d20)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_write.go:167 +0x86bâ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries(0xc0038bd400, {0x9a445a0, 0xc01f4c5d40}, 0xc02c37de00, 0x680d120)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:483 +0x514â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendWithoutRangeID(0xc0038bd400, {0x9a445a0, 0xc01f4c5d40}, 0xc02c37de00)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:179 +0x559â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).Send(...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:101â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaGCer).send(0xc0028b35c0, {0x9a445a0, 0xc01f4c5d40}, {{{0xc00908b830, 0xb, 0x10}, {0xc00908b840, 0xb, 0x10}, 0x0}, ...})â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/mvcc_gc_queue.go:468 +0x5f6â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaGCer).GC(0xc02bea8be8, {0x9a445a0, 0xc01f4c5d40}, {0xc00dd4b680, 0x0, 0x4})â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/mvcc_gc_queue.go:491 +0x150â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver/gc.processReplicatedKeyRange({0x9a445a0, 0xc01f4c5d40}, 0x0, {0x9ad4c48, 0xc023c59080}, {0x0, 0x0, 0x0}, {0x16e9b98697a90dd8, 0x0, ...}, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/gc/gc.go:423 +0x1231â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver/gc.Run({_, _}, _, {_, _}, {_, _, _}, {0x16e9b98697a90dd8, 0x0, ...}, ...)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/gc/gc.go:256 +0x2cdâ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*mvccGCQueue).process(0xc000e0def0, {0x9a445a0, 0xc01f4c5d40}, 0xc0038bd400, {0xc01f4c5d40, 0x0})â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/mvcc_gc_queue.go:567 +0x10c6â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica.func1({0x9a445a0, 0xc01f4c5d40})â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/queue.go:967 +0x283â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout({0x9a445d8, 0xc0028b31d0}, {0xc0087caf00, 0x1e}, 0x8bb2c97000, 0xc005711cc8)â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:91 +0xeeâ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica(0xc00bb0af20, {0x9a445d8, 0xc0028b31a0}, {0x9ad1ab8, 0xc0038bd400})â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/queue.go:926 +0x565â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processLoop.func2.1({0x9a445d8, 0xc0028b31a0})â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/queue.go:845 +0x105â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494 +0x236â€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskExâ€º
E220427 10:29:33.661166 860401 kv/kvserver/queue.go:1096 â‹® [n3,mvccGC,s3,r2/3:â€¹/System/NodeLiveness{-Max}â€º] 2578 +â€¹	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:483 +0x616â€º
```

First observed here https://github.com/cockroachdb/cockroach/pull/80619#issuecomment-1110994494 

Jira issue: CRDB-16380

**Comment by ajwerner** [comment]
Should this be a release blocker?
