### ISSUE TITLE
circleci: failed tests: TestCheckVersion

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8264]
The following test appears to have failed:

[#20924](https://circleci.com/gh/cockroachdb/cockroach/20924):

```
1      server/node.go:654
I160802 19:54:54.072131 storage/replica.go:1982  store=1:1 range=5 [/Table/14-/Max): applying command with forced error: storage/replica.go:1903: no-op on empty Raft entry
E160802 19:54:54.072420 storage/replica.go:2017  store=1:1 range=5 [/Table/14-/Max): error executing raft command: storage/replica.go:1903: no-op on empty Raft entry
I160802 19:54:54.073638 internal/client/db.go:489  failed batch: node unavailable; try another peer
W160802 19:54:54.073717 server/node.go:633  error recording initial status summaries: node unavailable; try another peer
panic: test timed out after 2m0s

goroutine 7634 [running]:
panic(0x15b5300, 0xc820700c60)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0x1df01a8, 0x25d1980, 0x33, 0x33, 0x5cfa01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc821001f08, 0x17c2540)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/server_test.TestMain(0xc821001f08)
	/go/src/github.com/cockroachdb/cockroach/server/main_test.go:32 +0xb2
main.main()
	github.com/cockroachdb/cockroach/server/_test/_testmain.go:154 +0x114

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x28f0e40)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1015 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 7630 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820017080)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 7539 [semacquire]:
sync.runtime_Syncsemacquire(0xc82105afd0)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc82105afc0)
	/usr/local/go/src/sync/cond.go:63 +0x9b
google.golang.org/grpc.(*Server).GracefulStop(0xc820448640)
	/go/src/google.golang.org/grpc/server.go:836 +0x25f
github.com/cockroachdb/cockroach/server.(*Server).Start.func6()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:362 +0x67
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82045e090, 0xc82118f400)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x62

goroutine 7511 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8210b8480)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:384 +0x3a
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:385 +0xb46

goroutine 7591 [IO wait]:
net.runtime_pollWait(0x7f54c6401880, 0x72, 0xc820e58800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820f32df0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820f32df0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820f32d90, 0xc820e58800, 0x400, 0x400, 0x0, 0x7f54c63ca050, 0xc82000e058)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201246b0, 0xc820e58800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc.(*Server).handleRawConn(0xc820448640, 0x7f54c6391fb0, 0xc8212c3290)
	/go/src/google.golang.org/grpc/server.go:385 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:357 +0x38c

goroutine 7509 [semacquire]:
sync.runtime_Semacquire(0xc82045e0bc)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82045e0b0)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc82045e090)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:354 +0x20b
github.com/cockroachdb/cockroach/server.TestCheckVersion(0xc82045e120)
	/go/src/github.com/cockroachdb/cockroach/server/updates_test.go:62 +0x423
testing.tRunner(0xc82045e120, 0x25d1e18)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 7623 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc820076120)
	/go/src/google.golang.org/grpc/transport/http2_server.go:673 +0x6ed
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:139 +0x84f
FAIL	github.com/cockroachdb/cockroach/server	120.043s
?   	github.com/cockroachdb/cockroach/server/serverpb	[no test files]
=== RUN   TestMetricsRecorder
--- PASS: TestMetricsRecorder (0.07s)
PASS
ok  	github.com/cockroachdb/cockroach/server/status	0.141s
I160802 19:55:05.262455 rand.go:76  Random seed: -5914992256904513429
=== RUN   TestSplitOrExpr
--- PASS: TestSplitOrExpr (0.00s)
=== RUN   TestSplitAndExpr
--- PASS: TestSplitAndExpr (0.01s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
likely fixed by #8277.
