### ISSUE TITLE
storage: up-replication is broken

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#8267]
SHA: 36d693594ca39c91946d6a16735214267df9f763

Steps to repro:
1. Use `roachdemo` or manually start a node on localhost
2. Use `block_writer` until you have some replicas (I had 14 replicas on my node).
3. Add 2 more nodes to the cluster.
4. Wait 8 or so minutes and notice that full replication hasn't occurred.

My UI several minutes after stopping load: 
<img width="917" alt="screenshot 2016-08-02 16 22 34" src="https://cloud.githubusercontent.com/assets/1564582/17343756/56d5712c-58cd-11e6-8467-32748b2b3b6e.png">

First node logs have lots of these messages:
```
E160802 16:13:58.079597 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=11 [/Table/51/1/8066815000180517192/"f1bb11fa-d0a5-4cc2-80d9-47fb499688fa"/12442-/Max): 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160802 16:13:58.079718 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=9 [/Table/51/1/6905099058192869454/"ba47c93d-ba45-46cf-bbca-22d8be3c0b2d"/7257-/Table/51/1/8066815000180517192/"f1bb11fa-d0a5-4cc2-80d9-47fb499688fa"/12442): 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160802 16:13:58.079835 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=12 [/Table/51/1/5746020457527034543/"20c1db92-e9e6-4637-8e2e-f81579f18049"/23352-/Table/51/1/6905099058192869454/"ba47c93d-ba45-46cf-bbca-22d8be3c0b2d"/7257): 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160802 16:13:58.081499 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=4 [/Table/13-/Table/14): 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160802 16:13:58.083024 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=5 [/Table/14-/Table/50): 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160802 16:14:44.017542 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=10 [/Table/51/1/2284333991187876666/"2e5eba36-9f26-44e7-9db2-f6ffae056f5c"/5106-/Table/51/1/3432100885105267539/"fb92fc20-73b3-41c8-a018-5606e6280922"/9173): 0 of 2 stores with an attribute matching []; likely not enough nodes in cluster
E160802 16:14:46.763930 storage/queue.go:497  [replicate] on store=1:1 range=14 [/Table/51/1/1142067297708073482/"27be8a3b-3aed-4db9-9f96-53419dcd0fa5"/8552-/Table/51/1/2284333991187876666/"2e5eba36-9f26-44e7-9db2-f6ffae056f5c"/5106): change replicas of range 14 failed: reservation declined:header:<node_id:3 store_id:3 > from_node_id:1 from_store_id:1 range_id:14 range_size:58970985
E160802 16:14:46.779365 storage/queue.go:497  [replicate] on store=1:1 range=10 [/Table/51/1/2284333991187876666/"2e5eba36-9f26-44e7-9db2-f6ffae056f5c"/5106-/Table/51/1/3432100885105267539/"fb92fc20-73b3-41c8-a018-5606e6280922"/9173): change replicas of range 10 failed: reservation declined:header:<node_id:3 store_id:3 > from_node_id:1 from_store_id:1 range_id:10 range_size:59384404
E160802 16:14:50.291948 storage/queue.go:497  [replicate] on store=1:1 range=11 [/Table/51/1/8066815000180517192/"f1bb11fa-d0a5-4cc2-80d9-47fb499688fa"/12442-/Max): change replicas of range 11 failed: context deadline exceeded
```

Long-running tasks:
<img width="339" alt="screenshot 2016-08-02 16 25 30" src="https://cloud.githubusercontent.com/assets/1564582/17343864/c52bc810-58cd-11e6-96b8-fff2d149c135.png">

**Comment by petermattis** [comment]
I reproduced this and noticed that the replicate queue wasn't doing anything (see the /debug/events). Looked at the goroutines and saw:

```
goroutine 76 [select, 13 minutes]:
github.com/cockroachdb/cockroach/storage.(*Replica).redirectOnOrAcquireLease(0xc4254aa240, 0x96a2800, 0xc42c3fa900, 0xc42c7b2580)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/replica.go:664 +0x51b
github.com/cockroachdb/cockroach/storage.(*baseQueue).processReplica(0xc4202f0460, 0xc4254aa240, 0xc42038a5c0, 0x0, 0x0)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/queue.go:468 +0x6ec
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1.1()
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/queue.go:423 +0x58
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc420369560, 0xc42dccde78, 0x0, 0x0)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x100
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/queue.go:427 +0x271
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420369560, 0xc4200e1980)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66
```

Blocked for 13 minutes trying to acquire the lease. That's not good. This seems pretty high priority. 

Cc @bdarnell.

**Comment by cuongdo** [comment]
Yes, almost done with `git bisect`

**Comment by cuongdo** [comment]
```
f52db97c2539e51845de267675c352c4fd89b4f0 is the first bad commit
commit f52db97c2539e51845de267675c352c4fd89b4f0
Author: Tamir Duberstein <tamird@gmail.com>
Date:   Sat Jul 30 14:12:33 2016 -0400


    Update dependencies
```

cc @tamird

**Comment by cuongdo** [comment]
grpc update?

**Comment by petermattis** [comment]
That's surprising?

**Comment by tamird** [comment]
Ah, shit, I know what this is. https://github.com/grpc/grpc-go/pull/780.

We need to instantiate our grpc servers with `grpc.MaxMsgSize(64 << 20)`. I
ran some acceptance tests because I feared this, but they passed =/

**Comment by petermattis** [comment]
The max-msg-size is 4MB?!? Even 64MB might not be enough. Let's set this to `128 << 20`.

**Comment by petermattis** [comment]
Our acceptance tests aren't creating large enough ranges. I bet our Raft snapshots are getting dropped.

**Comment by petermattis** [comment]
Unless I messed something up, using `grpc.MaxMsgSize(128 << 20)` didn't help.

**Comment by petermattis** [comment]
I think grpc is a red-herring. I reverted back to grpc@5a547ed72c09faf4050739d54caea1d51f4d276d and still see the problem.

**Comment by petermattis** [comment]
Egad, I must have messed up my testing somehow. Looks like `grpc.MaxMsgSize(128 << 20)` does fix the problem. Not sure what I was doing.

**Comment by tamird** [comment]
Phew.

**Comment by tamird** [comment]
By the way, when I said I ran acceptance tests, I really meant the GCE rebalancing tests

**Comment by cuongdo** [comment]
They passed, because they were "succeeding" after a period of balancer
inactivity. They weren't checking whether range counts were actually
balanced. #8265 fixes this.

**Comment by tamird** [comment]
Ah, I see.
