### ISSUE TITLE
circleci: failed tests: TestStopServer

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8276]
The following test appears to have failed:

[#20948](https://circleci.com/gh/cockroachdb/cockroach/20948):

```
W160803 02:30:54.708501 storage/intent_resolver.go:349  could not GC completed transaction: context deadline exceeded
I160803 02:30:54.709897 storage/replica_command.go:3017  store=1:1 range=5 [/Table/14-/Max): change replicas of 5: read existing descriptor range_id:5 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I160803 02:30:54.710302 internal/client/db.go:489  failed batch: node unavailable; try another peer
E160803 02:30:54.710724 storage/queue.go:497  [replicate] on store=1:1 range=5 [/Table/14-/Max): change replicas of range 5 failed: node unavailable; try another peer
I160803 02:30:54.712279 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
panic: test timed out after 5m0s

goroutine 3450 [running]:
panic(0x19c1da0, 0xc82175c010)
	/usr/local/go/src/runtime/panic.go:481 +0x3ff
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x184
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x2353bc0, 0x2bab5c0, 0x4, 0x4, 0x388f201)
	/usr/local/go/src/testing/testing.go:583 +0xb39
testing.(*M).Run(0xc8204ecf10, 0x1bd0e80)
	/usr/local/go/src/testing/testing.go:515 +0x11e
github.com/cockroachdb/cockroach/testutils/testcluster.TestMain(0xc8204ecf10)
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/main_test.go:34 +0xf4
main.main()
	github.com/cockroachdb/cockroach/testutils/testcluster/_test/_testmain.go:58 +0x20b

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2ed0760)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1015 +0x76
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0xc5

goroutine 2357 [chan receive, 4 minutes]:
github.com/cockroachdb/cmux.(*muxListener).Accept(0xc8216a3040, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:9 +0x156
google.golang.org/grpc.(*Server).Serve(0xc8215fadc0, 0x7f1e3e2c6e50, 0xc8216a3040, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:348 +0x221
github.com/cockroachdb/cockroach/server.(*Server).Start.func7()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:369 +0x7d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82115aab0, 0xc8216a31c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x70

goroutine 3199 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f1e3e2c68d8, 0x72, 0x5dd749)
	/usr/local/go/src/runtime/netpoll.go:160 +0x63
net.(*pollDesc).Wait(0xc820051090, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x56
net.(*pollDesc).WaitRead(0xc820051090, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x44
net.(*netFD).Read(0xc820051030, 0xc82030cc00, 0x400, 0x400, 0x0, 0x7f1e3e2b6028, 0xc82007a0b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x27b
net.(*conn).Read(0xc820024520, 0xc82030cc00, 0x400, 0x400, 0x7f1e3e2b6000, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0x121
--
google.golang.org/grpc.(*Server).handleRawConn(0xc8215fadc0, 0x7f1e3e2c9558, 0xc821297550)
	/go/src/google.golang.org/grpc/server.go:364 +0x5b
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:357 +0x3fb

goroutine 2599 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc821104d10)
	/usr/local/go/src/database/sql/sql.go:727 +0x66
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x442

goroutine 3200 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f1e3e2c6d58, 0x72, 0x5dd749)
	/usr/local/go/src/runtime/netpoll.go:160 +0x63
net.(*pollDesc).Wait(0xc821a07f00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x56
net.(*pollDesc).WaitRead(0xc821a07f00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x44
net.(*netFD).Read(0xc821a07ea0, 0xc820a22c00, 0x400, 0x400, 0x0, 0x7f1e3e2b6028, 0xc82007a0b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x27b
net.(*conn).Read(0xc820024528, 0xc820a22c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0x121
--
google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake.func1(0xc8216b7c20, 0xc82158c900)
	/go/src/google.golang.org/grpc/credentials/credentials.go:152 +0x2f
created by google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake
	/go/src/google.golang.org/grpc/credentials/credentials.go:153 +0x2d0

goroutine 2358 [chan receive, 4 minutes]:
github.com/cockroachdb/cmux.(*muxListener).Accept(0xc8216a3020, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:9 +0x156
github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith(0xc820024e78, 0xc82115aab0, 0x7f1e3e2c6e50, 0xc8216a3020, 0xc82043c410, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:117 +0x78
github.com/cockroachdb/cockroach/server.(*Server).Start.func8()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:377 +0x104
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82115aab0, 0xc820df07b0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x70

goroutine 2116 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc82115aadc)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82115aad0)
	/usr/local/go/src/sync/waitgroup.go:127 +0x118
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc82115aab0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:354 +0x287
github.com/cockroachdb/cockroach/testutils/testcluster.(*TestCluster).stopServers(0xc820d91e60)
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/testcluster.go:84 +0x1fa
github.com/cockroachdb/cockroach/testutils/testcluster.(*TestCluster).(github.com/cockroachdb/cockroach/testutils/testcluster.stopServers)-fm()
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/testcluster.go:154 +0x2e
--
testing.tRunner(0xc8208e21b0, 0x2bab608)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3

goroutine 3201 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f1e3e32d628, 0x72, 0x5dd749)
	/usr/local/go/src/runtime/netpoll.go:160 +0x63
net.(*pollDesc).Wait(0xc820051100, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x56
net.(*pollDesc).WaitRead(0xc820051100, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x44
net.(*netFD).Read(0xc8200510a0, 0xc8219cef18, 0x4, 0x4, 0x0, 0x7f1e3e2b6028, 0xc82007a0b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x27b
net.(*conn).Read(0xc820024540, 0xc8219cef18, 0x4, 0x4, 0x13b4ba1, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0x121
--
github.com/cockroachdb/cmux.(*cMux).serve(0xc820d07ac0, 0x7f1e3e3268c0, 0xc820024540, 0xc8201b7440, 0xc82118a190)
	/go/src/github.com/cockroachdb/cmux/cmux.go:143 +0x448
created by github.com/cockroachdb/cmux.(*cMux).Serve
	/go/src/github.com/cockroachdb/cmux/cmux.go:133 +0x1c2

goroutine 3197 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f1e3e2c6a58, 0x72, 0x5dd749)
	/usr/local/go/src/runtime/netpoll.go:160 +0x63
net.(*pollDesc).Wait(0xc820051020, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x56
net.(*pollDesc).WaitRead(0xc820051020, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x44
net.(*netFD).Read(0xc820050fc0, 0xc82030c800, 0x400, 0x400, 0x0, 0x7f1e3e2b6028, 0xc82007a0b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x27b
net.(*conn).Read(0xc820024518, 0xc82030c800, 0x400, 0x400, 0x7d2e118c78dc92b0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0x121
--
google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake.func1(0xc8216b7aa0, 0xc82158c300)
	/go/src/google.golang.org/grpc/credentials/credentials.go:152 +0x2f
created by google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake
	/go/src/google.golang.org/grpc/credentials/credentials.go:153 +0x2d0

goroutine 2344 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc820defb60)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:384 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:385 +0xd6a

goroutine 2451 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc82118a19c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82118a190)
	/usr/local/go/src/sync/waitgroup.go:127 +0x118
github.com/cockroachdb/cmux.(*cMux).Serve.func1(0xc820d07ac0, 0xc82118a190)
	/go/src/github.com/cockroachdb/cmux/cmux.go:112 +0x74
github.com/cockroachdb/cmux.(*cMux).Serve(0xc820d07ac0, 0x7f1e3e2eb5c8, 0xc820851e00)
	/go/src/github.com/cockroachdb/cmux/cmux.go:127 +0x13b
github.com/cockroachdb/cockroach/server.(*Server).Start.func11()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:437 +0x40
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82115aab0, 0xc820ff9d60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x70
FAIL	github.com/cockroachdb/cockroach/testutils/testcluster	300.087s
=== RUN   TestStoreTimeSeries
W160803 02:30:45.217143 gossip/gossip.go:1008  not connected to cluster; use --join to specify a connected node
I160803 02:30:45.217643 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
I160803 02:30:45.235121 storage/store.go:2696  system config not yet available
I160803 02:30:45.239438 storage/replica.go:2607  gossiping cluster id {"00000000-0000-0000-0000-000000000000"} from store 1, range 1
I160803 02:30:45.242288 storage/replica.go:1990  store=1:1 range=1 [/Min-/Max): applying command with forced error: storage/replica.go:1911: no-op on empty Raft entry
E160803 02:30:45.243035 storage/replica.go:2025  store=1:1 range=1 [/Min-/Max): error executing raft command: storage/replica.go:1911: no-op on empty Raft entry
I160803 02:30:45.244281 storage/replica_trigger.go:308  store=1:1 range=1 [/Min-/Max): new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900ms following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00 +0000 UTC]
I160803 02:30:45.244433 storage/replica.go:2629  gossiping sentinel from store 1, range 1
I160803 02:30:45.244779 storage/replica.go:2636  gossiping first range from store 1, range 1: [{1 1 1}]

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
#8250.
