### ISSUE TITLE
stability: panic in context with go1.7

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#8293]
`beta` cluster running `e5e7518dc3edb358ddbddb39e96d9512775540b2`

Two nodes were upgraded first and crashed within 1h.
The panic shows backtrace as the first few stack frames, but that's due to the recover call.
The actual panic ends with `context.propagateCancel`, both triggered originally by `PeriodicallyCheckForUpdates`.

We have not seen this on builds before 1.7, and the `/go/src/golang.org/x/net/context/go17.go` trace seems to indicate a switch to the built-in library code path for `Context`. This could be a red herring.

on `104.196.54.82`:
```
I160803 15:10:21.972426 cli/start.go:334  CockroachDB beta-20160728-258-ge5e7518 (linux amd64, built 2016/08/03 13:24:33, go1.7rc3)
...
[bcd] 2016/08/03 16:11:18 Tracer finished execution
[bcd] 2016/08/03 16:11:18 Trace request complete
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xbd7c86]

goroutine 111 [running]:
panic(0x1535620, 0xc420010060)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/cli.initBacktrace.func2(0x1535620, 0xc420010060)
        /go/src/github.com/cockroachdb/cockroach/cli/backtrace.go:98 +0xca
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc42038c1b0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:173 +0x56
panic(0x1535620, 0xc420010060)
        /usr/local/go/src/runtime/panic.go:458 +0x243
context.propagateCancel(0x0, 0x0, 0x1fba300, 0xc442465780)
        /usr/local/go/src/context/context.go:245 +0x26
context.WithCancel(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/context/context.go:231 +0x180
golang.org/x/net/context.WithCancel(0x0, 0x0, 0x0, 0x0, 0x1fcb0c0)
        /go/src/golang.org/x/net/context/go17.go:33 +0x5d
github.com/cockroachdb/cockroach/sql.NewSession(0x0, 0x0, 0x0, 0x0, 0x1664f99, 0x4, 0xc4202a8600, 0x0, 0x0, 0xc459dc56e0)
        /go/src/github.com/cockroachdb/cockroach/sql/session.go:94 +0x318
github.com/cockroachdb/cockroach/server.(*adminServer).GetUIData(0xc42007b5b0, 0x0, 0x0, 0xc457f67da0, 0xc42892ee48, 0xc44d92df60, 0xc42017cea0)
        /go/src/github.com/cockroachdb/cockroach/server/admin.go:641 +0x86
github.com/cockroachdb/cockroach/server.(*Server).usageReportingEnabled(0xc42007b340, 0xc457f67e60)
        /go/src/github.com/cockroachdb/cockroach/server/updates.go:213 +0xce
github.com/cockroachdb/cockroach/server.(*Server).maybeReportUsage(0xc42007b340, 0x351bca41811, 0x22e5940)
        /go/src/github.com/cockroachdb/cockroach/server/updates.go:238 +0x47
github.com/cockroachdb/cockroach/server.(*Server).PeriodicallyCheckForUpdates.func1()
        /go/src/github.com/cockroachdb/cockroach/server/updates.go:97 +0xa8
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc42038c1b0, 0xc4213dfdc0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66
```

```
I160803 15:44:54.851751 cli/start.go:334  CockroachDB beta-20160728-258-ge5e7518 (linux amd64, built 2016/08/03 13:24:33, go1.7rc3)
...
[bcd] 2016/08/03 16:45:49 Tracer failed to run: fork/exec /opt/backtrace/bin/ptrace: cannot allocate memory
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xbd7c86]

goroutine 78 [running]:
panic(0x1535620, 0xc420010060)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/cli.initBacktrace.func2(0x1535620, 0xc420010060)
        /go/src/github.com/cockroachdb/cockroach/cli/backtrace.go:98 +0xca
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc42035f050)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:173 +0x56
panic(0x1535620, 0xc420010060)
        /usr/local/go/src/runtime/panic.go:458 +0x243
context.propagateCancel(0x0, 0x0, 0x1fba300, 0xc5cf1eca00)
        /usr/local/go/src/context/context.go:245 +0x26
context.WithCancel(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/context/context.go:231 +0x180
golang.org/x/net/context.WithCancel(0x0, 0x0, 0x0, 0x0, 0x1fcb0c0)
        /go/src/golang.org/x/net/context/go17.go:33 +0x5d
github.com/cockroachdb/cockroach/sql.NewSession(0x0, 0x0, 0x0, 0x0, 0x1664f99, 0x4, 0xc42006a700, 0x0, 0x0, 0xc57a348240)
        /go/src/github.com/cockroachdb/cockroach/sql/session.go:94 +0x318
github.com/cockroachdb/cockroach/server.(*adminServer).GetUIData(0xc420307df0, 0x0, 0x0, 0xc4d9cbfda0, 0xc4e6fb4a88, 0xc428935f50, 0xc420060b60)
        /go/src/github.com/cockroachdb/cockroach/server/admin.go:641 +0x86
github.com/cockroachdb/cockroach/server.(*Server).usageReportingEnabled(0xc420307b80, 0xc4d9cbfe60)
        /go/src/github.com/cockroachdb/cockroach/server/updates.go:213 +0xce
github.com/cockroachdb/cockroach/server.(*Server).maybeReportUsage(0xc420307b80, 0x3518a7a786e, 0x22e5940)
        /go/src/github.com/cockroachdb/cockroach/server/updates.go:238 +0x47
github.com/cockroachdb/cockroach/server.(*Server).PeriodicallyCheckForUpdates.func1()
        /go/src/github.com/cockroachdb/cockroach/server/updates.go:97 +0xa8
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc42035f050, 0xc420a35fd0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66
```

**Comment by petermattis** [comment]
The go1.7 context code is almost identical to the `x/net/context` code. I would suspect our recent changes to context propagation tickled something. Looks like we're passing a `nil` context somewhere we shouldn't.

**Comment by petermattis** [comment]
Btw, do we have the backtrace dump?

**Comment by mberhault** [comment]
It's definitely possible that 1.7 has nothing to do with it, there were two commits mentioning `Context` since yesterday's build (f2a807a).

While this is being fixed, we'll run the e5e7518 on beta with the `COCKROACH_SKIP_UPDATE_CHECK=1` env variable. @WillHaack: that will require a change to `supervisord.conf` (see the `environment` field in the `[program:cockroach]` section), and a restart.

**Comment by mberhault** [comment]
@petermattis: we do have it for the first node. The second node failed to run ptrace (`fork/exec /opt/backtrace/bin/ptrace: cannot allocate memory`).

First node btt: (added .txt for github, although it really isn't a text file)
[cockroach.e5e7518dc3edb358ddbddb39e96d9512775540b2.17707.1470240677.btt.txt](https://github.com/cockroachdb/cockroach/files/400109/cockroach.e5e7518dc3edb358ddbddb39e96d9512775540b2.17707.1470240677.btt.txt)

**Comment by cuongdo** [comment]
This happened in `TestRebalance_3To5Small` as well:

https://teamcity.cockroachdb.com/viewLog.html?buildId=8541&buildTypeId=Cockroach_AllocatorTest3to510g&tab=artifacts#!12njl7g

**Comment by tamird** [comment]
@petermattis it looks like the context's parent is nil. How could that have happened?

**Comment by petermattis** [comment]
@tamird I don't know. This is precisely the sort of crash backtrace is designed to debug.

**Comment by petermattis** [comment]
@tamird This is the problem: https://github.com/cockroachdb/cockroach/blob/master/server/updates.go#L211-L213

**Comment by mberhault** [comment]
@WillHaack, @arjunravinarayan: once [46307e1](https://circleci.com/gh/cockroachdb/cockroach/20978) is green, we can try pushing that to `beta`
