### ISSUE TITLE
logictest: failure on master branch

### ISSUE THREAD

**Issue by wenyihu6** [cockroachdb/cockroach#83525]
*Describe the problem**
Running `./dev testlogic` on the master branch failed. I tried running 
`./dev testlogic –rewrite`, and a lot of changes were made. 
But running `./dev testlogic --config local` was a success.

If possible, provide steps to reproduce the behavior:
1. Create a new repository by cloning the repo on the [master branch](https://github.com/cockroachdb/cockroach.git)
2. Run `./dev testlogic`
3. A lot of errors and failures were shown.

```

goroutine 409352 [select]:
github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:408 +0x1dc
created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs
	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:381 +0x5b

goroutine 409351 [select]:
github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:336 +0x8c
created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue
	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:333 +0x445

goroutine 409355 [chan receive]:
github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x93b4658, 0xc04a802720})
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:302 +0x5b
runtime/pprof.Do({0x93b45e8, 0xc0001aa008}, {{0xc0001c29e0, 0x4c35fc0, 0x93b4658}}, 0xc004f627a8)
	GOROOT/src/runtime/pprof/runtime.go:40 +0xa3
github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc004f62770)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:301 +0x58
created by github.com/cockroachdb/pebble.(*tableCacheShard).init
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:293 +0xd1

goroutine 392932 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1({0xc040372e00, 0xc017f9f740})
	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:114 +0x10c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489 +0x159
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:480 +0x445

goroutine 406955 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initCancelingWorkers.func1({0x93b4658, 0xc0704bd4d0})
	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:140 +0xd3
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489 +0x159
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:480 +0x445

goroutine 410249 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0260e7110, 0x268)
	GOROOT/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0x78ffd60)
	GOROOT/src/sync/cond.go:56 +0x8c
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker(0xc06a4d30e0, {0x93b4658, 0xc031d16bd0})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:275 +0x2f6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489 +0x159
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:480 +0x445

goroutine 406710 [select]:
github.com/cockroachdb/cockroach/pkg/rpc.(*rangeFeedPipe).recvInternal(0xc02b574e60)
	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:1061 +0xa5
github.com/cockroachdb/cockroach/pkg/rpc.(*rangeFeedPipe).RecvMsg(0xc077eb55b8, {0x7dd2680, 0xc06d84b160})
	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:1048 +0x3c
github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.(*tracingClientStream).RecvMsg(0xc02b574ec0, {0x7dd2680, 0xc06d84b160})
	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:391 +0x37
github.com/cockroachdb/cockroach/pkg/rpc.rangeFeedClientAdapter.Recv({{0x93e8c70, 0xc02b574ec0}})
	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:988 +0x59
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).singleRangeFeed(0xc01ed21b00, {0x93b45b0, 0xc03e5bd140}, {{0xc05c6a1dd8, 0x1, 0x8}, {0xc05c6a1de0, 0x1, 0x8}}, {0x16fcd8a4bd3020c0, ...}, ...)
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:491 +0xa98
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).partialRangeFeed(0xc01ed21b00, {0x93b45b0, 0xc03e5bd140}, 0xc02fc8fa40, {{0xc05c6a1dd8, 0x1, 0x8}, {0xc05c6a1de0, 0x1, 0x8}}, ...)
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:341 +0x726
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).RangeFeedSpans.func1.1({0x93b45b0, 0xc03e5bd140})
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:140 +0xbe
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:169 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:74 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:71 +0xa9

goroutine 406948 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1({0xc0232d3880, 0xc0420103f0})
	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:114 +0x10c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489 +0x159
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:480 +0x445
I220628 17:22:49.235657 1 (gostd) testmain.go:82  [-] 1  Test //pkg/sql/logictest:logictest_test exited with error code 2
================================================================================
Target //pkg/sql/logictest:logictest_test up-to-date:
  _bazel/bin/pkg/sql/logictest/logictest_test_/logictest_test
INFO: Elapsed time: 140.013s, Critical Path: 134.57s
INFO: 449 processes: 13 internal, 436 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 449 total actions
//pkg/sql/logictest:logictest_test                                       FAILED in 52.0s
  /private/var/tmp/_bazel_wenyihu/5a022f7c41b3c607217003f3679c893e/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/testlogs/pkg/sql/logictest/logictest_test/test.log

INFO: Build completed, 1 test FAILED, 449 total actions
ERROR: exit status 3
```

*Related issue:** 
https://github.com/cockroachdb/cockroach/issues/74107

*Add any other context about the problem here.**
I asked this question on slack, and @ajwerner provided some context here. 

> In particular, these tests rely
on zone configuration propagation, which can be slow (see the [note](https://github.com/cockroachdb/cockroach/blob/2048e567f44381106ef905b57a0bd637621576e9/pkg/ccl/logictestccl/testdata/logic_test/zone#L3-L5)). It’s likely
we should do something about this. Probably we should have some
added directive to wait for the propagation in some form or another 

Jira issue: CRDB-17126

**Comment by yuzefovich** [comment]
@wenyihu6 do you have logs from the failure? Also, it looks like the config name was cut off (`loca` rather than `local`) - maybe that was the issue?

**Comment by wenyihu6** [comment]
> @wenyihu6 do you have logs from the failure? Also, it looks like the config name was cut off (`loca` rather than `local`) - maybe that was the issue?

Thanks for taking a look! My bad! The output I pasted there was for another failure. I just updated the description. Running `./dev testlogic --timeout=60m --config local` was a success, but `./dev testlogic --timeout=60m` was not.

**Comment by yuzefovich** [comment]
I think this issue is unactionable - we are running full logic test suite all the time and fixing the issues as they arise. One speculative theory for what happened here was running all configs at once overloaded the machine so the test timed out.
