### ISSUE TITLE
rangefeed,streamingccl: panic: rangefeed-system-monitor: unexpected 51200 leftover bytes

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#83697]
Running `TestTenantStreaming` (currently skipped on master), produces a panic:

```
panic: rangefeed-system-monitor: unexpected 51200 leftover bytes

goroutine 13541 [running]:
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic({0xf00daa8, 0xc000bc5e90}, 0xc000e80000, {0xac554d5, 0x20}, {0xc000a10700, 0x2, 0x2})
        github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:378 +0x3a5
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc001565c70, {0xf00daa8, 0xc000bc5e90}, 0x1)
        github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:430 +0x2d6
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
        github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:410
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*BudgetFactory).Stop(0xc0015a2210, {0xf00daa8, 0xc000bc5e90})
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/budget.go:356 +0x65
github.com/cockroachdb/cockroach/pkg/server.NewServer.func7()
        github.com/cockroachdb/cockroach/pkg/server/server.go:528 +0x4d
github.com/cockroachdb/cockroach/pkg/util/stop.CloserFn.Close(0xc000c2bd40)
        github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:107 +0x2f
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop
        github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:546 +0x465
```

Jira issue: CRDB-17215
Epic CRDB-7077

**Comment by stevendanna** [comment]
Looking into this a bit more closely.  The rangefeed panic is a secondary error that we get along a recovery path.  The primary error is:

```
--- FAIL: TestTenantStreaming (61.40s)
    test_log_scope.go:76: test logs captured to: /Users/ssd/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/55eb8b405f3a1b5e47cc0acac0358a7e/logTestTenantStreaming2064397029
    panic.go:1038: -- test log scope end --
    panic.go:1038: runtime error: invalid memory address or nil pointer dereference
        goroutine 14 [running]:
        runtime/debug.Stack()
                GOROOT/src/runtime/debug/stack.go:24 +0x65
        github.com/cockroachdb/cockroach/pkg/util/leaktest.AfterTest.func1()
                github.com/cockroachdb/cockroach/pkg/util/leaktest/leaktest.go:110 +0x166
        panic({0x8179f20, 0xcd14860})
                GOROOT/src/runtime/panic.go:1038 +0x215
        github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc000adcb40, {0x9ee5d78, 0xc00007e080})
                github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:550 +0x385
        panic({0x8179f20, 0xcd14860})
                GOROOT/src/runtime/panic.go:1038 +0x215
        github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest.verifyIngestionStats.func1({0x0, 0x0}, {0x885bc9a, 0xc0088cae70})
                github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go:49 +0x2c
        github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest.verifyIngestionStats(0xc000bdc340, 0x9e4b180, {0xc000bdc340, 0x8946675, 0x0}, {0xc0042fcc80, 0x1})
                github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go:75 +0x4ce
        github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest.TestTenantStreaming(0xc000bdc340)
                github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go:200 +0xea5
        testing.tRunner(0xc000bdc340, 0x8add3f0)
                GOROOT/src/testing/testing.go:1259 +0x102
        created by testing.(*T).Run
                GOROOT/src/testing/testing.go:1306 +0x35a
```

**Comment by andreimatei** [comment]
The stopper [shuts things down differently](https://github.com/cockroachdb/cockroach/blob/ae1804b872de36913f0b74a697f553d5cba81b31/pkg/util/stop/stopper.go#L538-L550) when recovering from a panic. This must have to do with what's going on here. The panic unwind code runs the closers in parallel with quiescing, which seems dubious. If you add a `1s` sleep between signaling the quiescing and running the closers, the monitor panic goes away.

I don't know what the answer is. Perhaps shutting down memory monitors in stopper closers is a bad idea? Or perhaps there's something that can be done to the rangefeeds in particular to make their shutdown less prone to this apparent race?
FWIW, the BytesMonitor has an EmergencyStop()[ method](https://github.com/cockroachdb/cockroach/blob/cc223604e595a14272f6810fdcd4eab96d5d8e85/pkg/util/mon/bytes_usage.go#L415) that we're supposed to call instead of the regular Stop when recovering from a panic - but it seems hard to plumb the information that we're recovering to where our troublesome monitor is being used.
