### ISSUE TITLE
TestStoreRangeMergeNonConsecutive times out after 30sec

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#838]
The following test appears to have failed:

[#1891](https://circleci.com/gh/cockroachdb/cockroach/1891):

```
I0428 21:34:22.755362     257 multiraft.go:696] New Entry[3]: 6/41 EntryNormal 00000000000000007cd139bff9aef795: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0428 21:34:22.755546     257 multiraft.go:699] Committed Entry[0]: 6/38 EntryNormal 00000000000000005359ab8439abb31b: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0428 21:34:22.755729     257 multiraft.go:699] Committed Entry[1]: 6/39 EntryNormal 00000000000000006448d41ce747221f: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0428 21:34:22.756024     257 multiraft.go:699] Committed Entry[2]: 6/40 EntryNormal 000000000000000017856db6a1a1e735: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0428 21:34:22.756186     257 multiraft.go:699] Committed Entry[3]: 6/41 EntryNormal 00000000000000007cd139bff9aef795: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
panic: test timed out after 30s

goroutine 3084 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0x1075bc8, 0x15112a0, 0xa1, 0xa1, 0xc207ffb901)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
	/go/src/github.com/cockroachdb/cockroach/storage/range.go:854 +0x212
github.com/cockroachdb/cockroach/util.func·005()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0xe3
FAIL	github.com/cockroachdb/cockroach/storage	30.019s
=== RUN TestBatchBasics
I0428 21:35:01.959947     352 rocksdb.go:88] opening in-memory rocksdb instance
I0428 21:35:01.960823     352 rocksdb.go:112] closing rocksdb instance at ""
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0428 21:35:01.961571     352 rocksdb.go:88] opening in-memory rocksdb instance
I0428 21:35:01.961818     352 rocksdb.go:112] closing rocksdb instance at ""
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0428 21:35:01.962618     352 rocksdb.go:88] opening in-memory rocksdb instance
I0428 21:34:22.755362     257 multiraft.go:696] New Entry[3]: 6/41 EntryNormal 00000000000000007cd139bff9aef795: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0428 21:34:22.755546     257 multiraft.go:699] Committed Entry[0]: 6/38 EntryNormal 00000000000000005359ab8439abb31b: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0428 21:34:22.755729     257 multiraft.go:699] Committed Entry[1]: 6/39 EntryNormal 00000000000000006448d41ce747221f: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0428 21:34:22.756024     257 multiraft.go:699] Committed Entry[2]: 6/40 EntryNormal 000000000000000017856db6a1a1e735: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0428 21:34:22.756186     257 multiraft.go:699] Committed Entry[3]: 6/41 EntryNormal 00000000000000007cd139bff9aef795: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
panic: test timed out after 30s

goroutine 3084 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0x1075bc8, 0x15112a0, 0xa1, 0xa1, 0xc207ffb901)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
	/go/src/github.com/cockroachdb/cockroach/storage/range.go:854 +0x212
github.com/cockroachdb/cockroach/util.func·005()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0xe3
FAIL	github.com/cockroachdb/cockroach/storage	30.019s
=== RUN TestBatchBasics
I0428 21:35:01.959947     352 rocksdb.go:88] opening in-memory rocksdb instance
I0428 21:35:01.960823     352 rocksdb.go:112] closing rocksdb instance at ""
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0428 21:35:01.961571     352 rocksdb.go:88] opening in-memory rocksdb instance
I0428 21:35:01.961818     352 rocksdb.go:112] closing rocksdb instance at ""
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0428 21:35:01.962618     352 rocksdb.go:88] opening in-memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment]
This is the same as #640 which was thought to be fixed when this test was re-enabled in #832.

**Comment by bdarnell** [comment]
OK, I've figured it out. 
* When the leader changes, we re-propose all pending commands in case they were dropped, but they may not have been dropped. In fact, in tests the initial leader election and the committing of the first command happen at the same time. Re-proposals get queued up in a channel.
* Once applying committed commands, we signal the client and reset the error channel to nil.
* In this test, when the transaction commits we then call RemoveRange.
* If the proposal channel is processed after the call to RemoveRange, the commands will fail since the range is no longer present. We try to return an error to the client, but this just hangs because the error channel has been reset to nil.

I think we fix this in two places: 1) Add a nil check in multiraft.state.propose so it won't try to send an error to a client that is no longer there. 2) Move the re-proposal (and some nearby code like sending leader election events) from handleRaftReady to handleWriteResponse, so we don't re-propose commands that were committed in the same iteration as the leadership change (this is unlikely to happen outside of tests but it's better to do this later anyway).

**Comment by bdarnell** [comment]
Debugging tip: be on the lookout for "nil chan" in stack traces (as in `goroutine 3324 [chan send (nil chan), 2 minutes]:`). I believe this is always a bug (nil channels in select statements are OK, but those show up as `[select]` instead of `[chan {send,recv} (nil chan)]`), since there is no way for the blocked goroutine to recover.
