### ISSUE TITLE
Crash: panic: RecordingStructured has 30 recordings; expected 1

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#84056]
**Describe the problem**

When executing the following sql statements, CockroachDB crashes.

**To Reproduce**

```sql
CREATE TABLE t2 ();
SET SESSION TRACING=true;
EXPLAIN SELECT count0 FROM t1;
EXPLAIN  SELECT count FROM t1, t2, t0;
EXPLAIN SELECT count0 FROM t2, t1 ;
SELECT * FROM t1, t2, t0;
SELECT count(*) FROM t0  ;
SET CLUSTER SETTING diagnostics.reporting.send_crash_reports = false;
SET experimental_enable_temp_tables = 'on';
CREATE TABLE t0 (c0 DECIMAL );
CREATE TABLE t1 (c0 VARBIT(14));
CREATE TEMP TABLE t2 (c0 BOOL, c1 TIME, c2 TIMESTAMP);
CREATE TABLE t3 (c0 TIMETZ );
CREATE UNIQUE INDEX ON t1(c0);
CREATE VIEW b AS SELECT MIN0 FROM t0, t2, t3;
SET CLUSTER SETTING  kv.range.backpressure_range_size_multiplier=453676394;
DELETE FROM t2 WHERE NULL;
TRUNCATE t1 RESTRICT;
DROP TABLE t2;
COMMENT ON TABLE t0 IS '.';
SHOW SEQUENCES;
EXPLAIN SELECT  () FROM t1, t0, t3;
EXPERIMENTAL SCRUB table t3;
EXPLAIN SELECT * FROM t0 WHERE true;
SELECT count FROM t1, t2, t0;
SELECT * FROM t1, t2, t0;
EXPLAIN SELECT count(*) FROM t1, t2, t0; -- Error: panic: RecordingStructured has 30 recordings; expected 1
```

**Expected behavior**
No error.

**Additional data / screenshots**
```shell
*
* ERROR: a SQL panic has occurred while executing the following statement:
* EXPLAIN SELECT count(*) FROM t1, t2, t0
*
*
* ERROR: a panic has occurred!
* panic: RecordingStructured has 30 recordings; expected 1
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:755
*   | [...repeated from below...]
* Wraps: (2) while executing: EXPLAIN SELECT count(*) FROM _, _, _
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:755
*   | runtime.gopanic
*   |   GOROOT/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).recordFinishedChildrenLocked
*   |   github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go:550
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).childFinished
*   |   github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go:1073
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).finish
*   |   github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go:279
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*spanInner).Finish
*   |   github.com/cockroachdb/cockroach/pkg/util/tracing/span_inner.go:101
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).finishInternal
*   |   github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:263
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).Finish
*   |   github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:251
*   | github.com/cockroachdb/cockroach/pkg/sql.(*txnState).finishSQLTxn
*   |   github.com/cockroachdb/cockroach/pkg/sql/txn_state.go:268
*   | github.com/cockroachdb/cockroach/pkg/sql.(*txnState).finishTxn
*   |   github.com/cockroachdb/cockroach/pkg/sql/conn_fsm.go:502
*   | github.com/cockroachdb/cockroach/pkg/sql.glob..func8
*   |   github.com/cockroachdb/cockroach/pkg/sql/conn_fsm.go:258
*   | github.com/cockroachdb/cockroach/pkg/util/fsm.Transitions.apply
*   |   github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:106
*   | github.com/cockroachdb/cockroach/pkg/util/fsm.(*Machine).ApplyWithPayload
*   |   github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:135
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2845
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper
*   |   github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2846
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
*   |   github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2065
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
*   |   github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1818
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
*   |   github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:757
*   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
*   |   github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:724
*   | runtime.goexit
*   |   GOROOT/src/runtime/asm_amd64.s:1581
* Wraps: (4) panic: RecordingStructured has 30 recordings; expected 1
* Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) *errutil.leafError
*
panic: RecordingStructured has 30 recordings; expected 1 [recovered]
        panic: panic: RecordingStructured has 30 recordings; expected 1

goroutine 4073 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc001837900, {0x6739620, 0xc003c51a40}, {0x4731580, 0xc0057a8f60})
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1055 +0x1b4
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1()
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:755 +0x53
panic({0x4731580, 0xc0057a8f60})
        GOROOT/src/runtime/panic.go:1038 +0x215
github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).recordFinishedChildrenLocked(0xc0025ba058, {0xc001ca6000, 0x4f18dc4e33c9c, 0xc003a45230})
        github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go:550 +0x325
github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).childFinished(0xc0025ba058, 0xc0046e3c58)
        github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go:1073 +0x251
github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).finish(0xc0046e3c58)
        github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go:279 +0x153
github.com/cockroachdb/cockroach/pkg/util/tracing.(*spanInner).Finish(0xc0046e3c08)
        github.com/cockroachdb/cockroach/pkg/util/tracing/span_inner.go:101 +0x45
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).finishInternal(0xc0046e3c00)
        github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:263 +0xb7
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).Finish(...)
        github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:251
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).finishSQLTxn(0xc001837990)
        github.com/cockroachdb/cockroach/pkg/sql/txn_state.go:268 +0x15c
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).finishTxn(0xc001837990, 0x2)
        github.com/cockroachdb/cockroach/pkg/sql/conn_fsm.go:502 +0x3b
github.com/cockroachdb/cockroach/pkg/sql.glob..func8({{0x67396c8, 0xc0040969c0}, {0x669a7a0, 0xc0006db190}, {0x4dae880, 0xc001837990}, {0x669a640, 0x98b5178}, {0x0, 0x0}})
        github.com/cockroachdb/cockroach/pkg/sql/conn_fsm.go:258 +0x37
github.com/cockroachdb/cockroach/pkg/util/fsm.Transitions.apply({0x3}, {{0x67396c8, 0xc0040969c0}, {0x669a7a0, 0xc0006db190}, {0x4dae880, 0xc001837990}, {0x669a640, 0x98b5178}, {0x0, ...}})
        github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:106 +0xfa
github.com/cockroachdb/cockroach/pkg/util/fsm.(*Machine).ApplyWithPayload(...)
        github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:135
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper.func1(0xc001837900, {0x669a640, 0x98b5178}, {0x0, 0x0})
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2845 +0x238
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper(0xc001837900, {0x669a640, 0x98b5178}, {0x0, 0x0}, {0x7f62954bcb50, 0xc001a446c0}, 0x1)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2846 +0x110
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc001837900)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2065 +0x1249
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001837900, {0x6739620, 0xc003c51a40}, 0xc0030f16e0, {0x5400, 0x15000, 0xc003129a40, 0x0, 0x0}, 0xc002b09480)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1818 +0x26c
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0x6739620, {0x6739620, 0xc003c51a40}, {0x3}, {0x5400, 0x15000, 0xc003129a40, 0x0, 0x0}, 0xc002b09480)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:757 +0xf7
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
        github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:724 +0x3b8
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:643 +0x273
```
**Environment:**
 - CockroachDB version [02dcb3816c4148ee15318a614901b266f1b8ae34]
 - Server OS: [Ubuntu 20.04]
 - Client app [`cockroach sql`]

**Additional context**

Jira issue: CRDB-17433

**Comment by stevendanna** [comment]
Thanks for the report! I believe this should be fixed in c66abb3245c5eef847b4ad6b0169f75b74723c19 (https://github.com/cockroachdb/cockroach/pull/83625)
