### ISSUE TITLE
storage: range for RangeID <ID> already exists on store

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#8408]
Using this `block_writer` load test:

```
make test \
  PKG=./acceptance \
  TESTTIMEOUT=6h \
  TESTS=ContinuousLoad_BlockWriter \
  TESTFLAGS='-v -remote -key-name google_compute_engine -cwd terraform -nodes 4 -tf.keep-cluster=always -clt.writers=1'
```

I sporadically (one of every 10-20 runs) get the following panic on a node that's not directly receiving `block_writer` traffic (a different node has all the SQL connections):

```
panic: range for Range ID 20 already exists on store [recovered]
        panic: range for Range ID 20 already exists on store

goroutine 153 [running]:
panic(0x158bda0, 0xc4202fe240)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc4203733b0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:176 +0x6e
panic(0x158bda0, 0xc4202fe240)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/storage.(*Replica).applySnapshot(0xc4202fe240, 0x7fd51f5e7768, 0xc4200142c0, 0xc478328000, 0x43caf3c, 0x43cc000, 0xc43d6adb20, 0x3, 0x4, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:712 +0x10c1
github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady(0xc4202fe240, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1566 +0xfd5
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2546 +0x20e
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc4203733b0, 0xc4201b5e40)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66
```

So, this is most likely caused by up-replication or rebalancing traffic.

Full logs for this node:
[cockroach.stderr.txt](https://github.com/cockroachdb/cockroach/files/408749/cockroach.stderr.txt)

**Comment by cuongdo** [comment]
SHA: 55b2fa2

**Comment by cuongdo** [comment]
Also, I saw this sometime last week, so this isn't new.

**Comment by bdarnell** [comment]
This looks like the `canApplySnapshot` race that @arjunravinarayan is working on in #8365.

**Comment by cuongdo** [comment]
Haven't seen this in a long time, so it looks like it's been fixed.
