### ISSUE TITLE
pebble: possible goroutine leak

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#84423]
**Describe the problem**

In a [recent bors-triggered-build](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/5747110?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) we see a leaktest failure with leaked pebble:

```
=== CONT  TestLogic
    logic.go:4532: -- test log scope end --
    logic_test.go:33: Leaked goroutine: goroutine 8490512 [select]:
        github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked.func1()
          /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:302 +0xe9
        created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked
          /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:297 +0x85
        Leaked goroutine: goroutine 8490786 [select]:
        github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked.func1()
          /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:302 +0xe9
        created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked
          /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:297 +0x85
--- FAIL: TestLogic (2013.60s)
```

Just looking at the stack and the related code, I don't see anything that waits for that ticket goroutine https://github.com/cockroachdb/pebble/blob/d79f9617c9c5205ea26c28838ad3a1918d8fe6d1/vfs/disk_health.go#L297

so perhaps we should open this against pebble. But I wanted an issue here so it comes up in searches for similar stacktraces.

**Comment by yuzefovich** [comment]
Seems like a dup of #84437, should we close this issue in favor of that one?

**Comment by nicktrav** [comment]
Woops - I didn't realize this issue existed when I created #84437. This issues points at Pebble, however, I believe the issue is in the test. Perhaps we close this one?

**Comment by yuzefovich** [comment]
Ok, let's close it in favor of #84437.
