### ISSUE TITLE
stability: panic: "descriptor is not initialized"

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#8447]
Two beta nodes running 6827d40 crashed at the same time with this message: 

```
panic: descriptor is not initialized: range_id:8862 next_replica_id:0  [recovered]
        panic: descriptor is not initialized: range_id:8862 next_replica_id:0 

goroutine 53 [running]:
panic(0x14fc9a0, 0xc46554b770)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/cli.initBacktrace.func2(0x14fc9a0, 0xc46554b770)
        /go/src/github.com/cockroachdb/cockroach/cli/backtrace.go:98 +0xca
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc42039d3b0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:173 +0x56
panic(0x14fc9a0, 0xc46554b770)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/roachpb.NewRangeKeyMismatchError(0xc4578cc6c0, 0x37, 0x40, 0x0, 0x0, 0x0, 0xc42bfa6300, 0x0)
        /go/src/github.com/cockroachdb/cockroach/roachpb/errors.go:301 +0x246
github.com/cockroachdb/cockroach/storage.(*Replica).checkCmdHeader(0xc433563440, 0xc4578cc6c0, 0x37, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:966 +0x108
github.com/cockroachdb/cockroach/storage.(*Replica).executeCmd(0xc433563440, 0x7fc6ff1b2768, 0xc4200721b0, 0xc46554b688, 0x8, 0x0, 0x7fc6ff1b2a18, 0xc45658e700, 0xc4274a3ab0, 0x146957bab5201adf, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:74 +0x142
github.com/cockroachdb/cockroach/storage.(*Replica).executeBatch(0xc433563440, 0x7fc6ff1b2768, 0xc4200721b0, 0xc46554b688, 0x8, 0x7fc6ff1b2a18, 0xc45658e700, 0xc4274a3ab0, 0x146957bab5201adf, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2494 +0x37e
github.com/cockroachdb/cockroach/storage.(*Replica).executeWriteBatch(0xc433563440, 0x7fc6ff1b2768, 0xc4200721b0, 0xc46554b688, 0x8, 0x146957bab5201adf, 0x0, 0x0, 0x0, 0x229e, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2316 +0x1b4
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommandInBatch(0xc433563440, 0x7fc6ff1b2768, 0xc4200721b0, 0xc46554b688, 0x8, 0x400000004, 0x3, 0x146957bab5201adf, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2232 +0xe9
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommand(0xc433563440, 0xc46554b688, 0x8, 0x7fc6ff1b2768, 0xc4200721b0, 0x10ca, 0x0, 0x400000004, 0xc400000003, 0x146957bab5201adf, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2135 +0x98e
github.com/cockroachdb/cockroach/storage.(*Replica).processRaftCommand(0xc433563440, 0xc46554b688, 0x8, 0x10ca, 0x229e, 0x400000004, 0x3, 0x146957bab5201adf, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2051 +0x322
github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady(0xc433563440, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1675 +0x785
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2560 +0x20e
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc42039d3b0, 0xc420547020)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

```

**Comment by tamird** [comment]
Looks like this context has been lost. Closing.
