### ISSUE TITLE
bazel: release-21.2 won't build because of zlib download 404 

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#85064]
```
WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'zlib':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_tpr/1fb42b81c64f8bef29f577c0af436d23/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /private/var/tmp/_bazel_tpr/1fb42b81c64f8bef29f577c0af436d23/external/zlib/temp7736131449392090567/zlib-1.2.11.tar.gz: GET returned 404 Not Found
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_tpr/1fb42b81c64f8bef29f577c0af436d23/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /private/var/tmp/_bazel_tpr/1fb42b81c64f8bef29f577c0af436d23/external/zlib/temp7736131449392090567/zlib-1.2.11.tar.gz: GET returned 404 Not Found
ERROR: /private/var/tmp/_bazel_tpr/1fb42b81c64f8bef29f577c0af436d23/external/com_google_protobuf/BUILD:154:11: @com_google_protobuf//:protobuf depends on @zlib//:zlib in repository @zlib which failed to fetch. no such package '@zlib//': java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /private/var/tmp/_bazel_tpr/1fb42b81c64f8bef29f577c0af436d23/external/zlib/temp7736131449392090567/zlib-1.2.11.tar.gz: GET returned 404 Not Found
ERROR: Analysis of target '//docs/generated/settings:settings' failed; build aborted: Analysis failed
```

**Comment by cucaroach** [comment]
Apparently 1.2.12 exists maybe 1.2.11 had a really bad bug or something.

**Comment by yuzefovich** [comment]
There is no expectation that bazel works on 21.2 branch - we need to use `make` there.

**Comment by cucaroach** [comment]
From zlib site:
```
Version 1.2.12 has these key improvements over 1.2.11:

Fix a deflate bug when using the Z_FIXED strategy that can result in out-of-bound accesses.
Fix a deflate bug when the window is full in deflate_stored().
Speed up CRC-32 computations by a factor of 1.5 to 3.
Use the hardware CRC-32 instruction on ARMv8 processors.
Speed up crc32_combine() with powers of x tables.
Add crc32_combine_gen() and crc32_combine_op() for fast combines.

Due to the bug fixes, any installations of 1.2.11 should be replaced with 1.2.12.

Version 1.2.11 has these key improvements over 1.2.10:

Fix deflate stored bug when pulling last block from window
Permit immediate deflateParams changes before any deflate input
```

**Comment by cucaroach** [comment]
I guess the bigger question is should all branches move to 1.2.12?   Is zlib built into crdb or is it just a bazel build dependency?

**Comment by rickystewart** [comment]
>  Is zlib built into crdb or is it just a bazel build dependency?

At the very least it's a dependency of `protoc`.

```
cockroach$ bazel query 'somepath(pkg/cmd/cockroach-short, @zlib//...)'
//pkg/cmd/cockroach-short:cockroach-short
//pkg/cmd/cockroach-short:cockroach-short_lib
//pkg/cli:cli
//pkg/build:build
//pkg/build:build_go_proto
//pkg/build:build_proto
@com_google_protobuf//:protoc
@com_google_protobuf//:protoc_lib
@com_google_protobuf//:protobuf
@zlib//:zlib
@zlib//:zlib/include/crc32.h
@zlib//:copy_public_headers
```

**Comment by yuzefovich** [comment]
Closing since 21.2 release is long out of support.
