### ISSUE TITLE
admission: CPULoad period of 250ms prevents total slots from increasing fast enough

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#85161]
At the usual 1ms interval, we can increase total slots by 1000 every second (since it increments by 1). However, it is possible that slots are fully used *and* and the CPULoad period has been lowered to 250ms (because CPU utilization is low). In this case we will increase slots by only 4 every 1s.
This was observed running kv0 with 1024 byte blocks with a very high concurrency of 18000 and with a concurrent index creation `CREATE INDEX kv_idx ON kv(v);`. The CPULoad switched to 250ms and a long stretch of time on node n2 with inadequate slots (despite low cpu utilization)

<img width="378" alt="Screen Shot 2022-07-27 at 4 00 37 PM" src="https://user-images.githubusercontent.com/54990988/181361562-284035dd-f592-4f20-b0e4-e549d319f541.png">

The goroutines using these slots were stuck in trying to acquire from the quotapool or in trying to resolve intents. See the following stacktraces.
```
goroutine 5727851 [select, 2 minutes]:
github.com/cockroachdb/cockroach/pkg/util/quotapool.(*AbstractPool).Acquire(0xc0aa49dad0, {0x68becd8, 0xc08df99290}, {0x6839178, 0xc014faaf00})
	github.com/cockroachdb/cockroach/pkg/util/quotapool/quotapool.go:281 +0x77c
github.com/cockroachdb/cockroach/pkg/util/quotapool.(*IntPool).acquireMaybeWait(0xc002289bd8, {0x68becd8, 0xc08df99290}, 0x11a9, 0x1)
	github.com/cockroachdb/cockroach/pkg/util/quotapool/intpool.go:178 +0x13f
github.com/cockroachdb/cockroach/pkg/util/quotapool.(*IntPool).Acquire(...)
	github.com/cockroachdb/cockroach/pkg/util/quotapool/intpool.go:147
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).maybeAcquireProposalQuota(0x977c0e0, {0x68becd8, 0xc08df99290}, 0x68becd8)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal_quota.go:63 +0x232
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose(0xc003bde800, {0x68becd8, 0xc08df99290}, 0xc0cd912600, 0xc05db47180, 0xc128b3da60, {{0x1705c738c61d5b5f, 0x0, 0x0}, {0x1705c738a8668ac4, ...}}, ...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:256 +0xb25
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch(0xc003bde800, {0x68becd8, 0xc08df99290}, 0xc0cd912600, 0xc05db47180)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:168 +0x7e5
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries(0xc003bde800, {0x68becd8, 0xc08df99290}, 0xc0cd912600, 0x539d3b0)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:491 +0x3e8
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendWithoutRangeID(0xc003bde800, {0x68becd8, 0xc08df99260}, 0xc0cd912600)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:191 +0x385
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes(...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:112
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes(_, {_, _}, {{{0x1705c738a84ff65f, 0x0, 0x0}, 0x0, {0x2, 0x2, 0x3, ...}, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:207 +0x7c5
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes(_, {_, _}, {{{0x0, 0x0, 0x0}, 0x0, {0x2, 0x2, 0x3, ...}, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:222 +0x1c8
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc000b52a80, {0x68becd8, 0xc08df99170}, {0x3335b027432d6e78}, 0xc0cd912400)
	github.com/cockroachdb/cockroach/pkg/server/node.go:1022 +0x468
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc000b52a80, {0x68becd8, 0xc08df990b0}, 0xc0cd912400)
	github.com/cockroachdb/cockroach/pkg/server/node.go:1071 +0xfc
```

```
goroutine 5863483 [select, 1 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver.(*IntentResolver).ResolveIntents(0xc002bdc4b0, {0x68becd8, 0xc135397bc0}, {0xc0dbae0d00, 0x2, 0xc12af22d80}, {0x0, {0x1705c71f8d46f5c1, 0x0, 0x0}})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver/intent_resolver.go:900 +0x885
github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver.(*IntentResolver).cleanupFinishedTxnIntents(0xc002bdc4b0, {0x68becd8, 0xc135397bc0}, 0x11a, 0xc0037605a0, 0x90, 0xc135f79880)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver/intent_resolver.go:774 +0x130
github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver.(*IntentResolver).CleanupTxnIntentsAsync.func2({0x68becd8, 0xc135397bc0})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver/intent_resolver.go:580 +0xe5
github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver.(*IntentResolver).runAsyncTask(0xc002bdc4b0, {0x68becd8, 0xc135397bc0}, 0x1, 0xc00fb9de90)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver/intent_resolver.go:442 +0x1a4
github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver.(*IntentResolver).CleanupTxnIntentsAsync(0xc002bdc4b0, {0x68becd8, 0xc135397bc0}, 0x11a, {0xc04fa371e0, 0x1, 0x0}, 0x0)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver/intent_resolver.go:574 +0x17f
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch(0xc003988000, {0x68becd8, 0xc135397bc0}, 0xc0a2a7c200, 0xc00881edc0)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:202 +0x9d0
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries(0xc003988000, {0x68becd8, 0xc135397bc0}, 0xc0a2a7c200, 0x539d3b0)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:491 +0x3e8
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendWithoutRangeID(0xc003988000, {0x68becd8, 0xc135397b90}, 0xc0a2a7c200)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:191 +0x385
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes(...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:112
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes(_, {_, _}, {{{0x1705c71f8d46f5c1, 0x0, 0x0}, 0x0, {0x2, 0x2, 0x3, ...}, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:207 +0x7c5
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes(_, {_, _}, {{{0x0, 0x0, 0x0}, 0x0, {0x2, 0x2, 0x3, ...}, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:222 +0x1c8
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc000b52a80, {0x68becd8, 0xc135397ad0}, {0x0}, 0xc0a2a7c100)
	github.com/cockroachdb/cockroach/pkg/server/node.go:1022 +0x468
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc000b52a80, {0x68becd8, 0xc135397a70}, 0xc0a2a7c100)
	github.com/cockroachdb/cockroach/pkg/server/node.go:1071 +0xfc
```

cc: @tbg @irfansharif 

Jira issue: CRDB-18070

Epic CRDB-25469

**Comment by sumeerbhola** [comment]
https://github.com/sumeerbhola/cockroach/commit/2ec50f151b3eed41eb63f634797b4230afe28ed8 attempts to fix this.

**Comment by sumeerbhola** [comment]
Closing this since https://github.com/cockroachdb/cockroach/pull/111441 may have sufficiently addressed this.
