### ISSUE TITLE
backupccl: TestRestoreOldVersions is flaky; panic due to use of Span after Finish

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#85275]
**Describe the problem**

The test `TestRestoreOldVersions` fails when run under stress.

**To Reproduce**

```console
$ ./dev test ./pkg/ccl/backupccl --filter TestRestoreOldVersions --stress
... snip ...
initialized metamorphic constant "backup-merge-file-buffer-size" with value 6910379
initialized metamorphic constant "span-reuse-rate" with value 46
initialized metamorphic constant "mvcc-incremental-iter-tbi" with value false
initialized metamorphic constant "mvcc-value-disable-simple-encoding" with value true
initialized metamorphic constant "addsst-rewrite-forced" with value true
initialized metamorphic constant "split-scans-right-for-stats-first" with value true
initialized metamorphic constant "raft-log-truncation-clearrange-threshold" with value 280798
initialized metamorphic constant "default-batch-bytes-limit" with value 33675
initialized metamorphic constant "kv-batch-size" with value 1
initialized metamorphic constant "datum-row-converter-batch-size" with value 1
initialized metamorphic constant "row-container-rows-per-chunk-shift" with value 1
initialized metamorphic constant "inverted-joiner-batch-size" with value 1
initialized metamorphic constant "zig-zag-joiner-batch-size" with value 1
initialized metamorphic constant "max-batch-size" with value 1832
initialized metamorphic constant "max-batch-byte-size" with value 4185270
initialized metamorphic constant "parallel-scan-result-threshold" with value 4309
initialized metamorphic constant "spilling-queue-initial-len" with value 4
initialized metamorphic constant "ColIndexJoin-batch-size" with value 4135237
initialized metamorphic constant "ColIndexJoin-using-streamer-batch-size" with value 8025553
initialized metamorphic constant "resolve-membership-single-scan-enabled" with value false
initialized metamorphic constant "async-IE-result-channel-buffer-size" with value 25
initialized metamorphic constant "backup-read-manifest" with value true
initialized metamorphic constant "restore-worker-concurrency" with value 3
I220728 18:51:33.292950 1 (gostd) rand.go:176  [-] 1  random seed: 3281020188925444163
*
* INFO: Running test with the default test tenant. If you are only seeing a test case failure when this message appears, there may be a problem with your test case running within tenants.
*
panic: use of Span after Finish. Span: optimizer. Finish previously called at: <stack not captured. Set debugUseAfterFinish>

goroutine 58343 [running]:
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish(0x88031d8?)
        github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:186 +0x12b
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).RecordingType(0xc00713f500)
        github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:411 +0x1e
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsVerbose(...)
        github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:419
github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog({0x5dd2eb0, 0xc003312780})
        github.com/cockroachdb/cockroach/pkg/util/log/trace.go:92 +0x3a
github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x5dd2eb0, 0xc003312780}, 0x2, 0x3, 0x0, 0x8?, {0x4b5f3a1, 0x2c}, {0xc0039a2f68, 0x1, ...})
        github.com/cockroachdb/cockroach/pkg/util/log/channels.go:101 +0x568
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
        github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
github.com/cockroachdb/cockroach/pkg/util/log.Errorf(...)
        github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:640
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.backupShowerDefault.func1({{0xc002850e5b, 0x11}, {0xc00747f050, 0x1, 0x1}, {0xc00e00bb00, 0x1, 0x1}, {0x0, 0x0}, ...})
        github.com/cockroachdb/cockroach/pkg/ccl/backupccl/show.go:757 +0xe14
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.manifestInfoReader.showBackup({{{0xc00713fc00?, 0x0?, 0x0?}, 0xc01456f400?}}, {0x5dd2eb0, 0xc0033135f0}, 0x45221f?, 0xc003313a40?, {{0xc002850e5b, 0x11}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/ccl/backupccl/show.go:132 +0x137
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.showBackupPlanHook.func1({0x5dd2eb0, 0xc003313590}, {0x0?, 0x0?, 0x0?}, 0xc00feb3620?)
        github.com/cockroachdb/cockroach/pkg/ccl/backupccl/show.go:474 +0x1c2b
github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1()
        github.com/cockroachdb/cockroach/pkg/sql/planhook.go:183 +0xa4
created by github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec
        github.com/cockroachdb/cockroach/pkg/sql/planhook.go:181 +0x1aa
```

I hit this on `master` at 8c7cfe872a91270bfcc0bef7e43f9ab3fe8abbb1.

Jira issue: CRDB-18152

**Comment by nicktrav** [comment]
This is similar to #83739. cc: @yuzefovich

**Comment by yuzefovich** [comment]
This is a dup of #85201.
