### ISSUE TITLE
stability: nil pointer panic in raft

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#8535]
Seen on beta cluster node 1, running 6827d40

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xea6d8d]

goroutine 3372971757 [running]:
panic(0x15549c0, 0xc420010060)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/cli.initBacktrace.func2(0x15549c0, 0xc420010060)
        /go/src/github.com/cockroachdb/cockroach/cli/backtrace.go:98 +0xca
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc420362750)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:173 +0x56
panic(0x15549c0, 0xc420010060)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/coreos/etcd/raft.(*raft).appendEntry(0xc422621860, 0xc4335926e0, 0x1, 0x1)
        /go/src/github.com/coreos/etcd/raft/raft.go:419 +0xdd
github.com/coreos/etcd/raft.(*raft).becomeLeader(0xc422621860)
        /go/src/github.com/coreos/etcd/raft/raft.go:509 +0x21a
github.com/coreos/etcd/raft.stepCandidate(0xc422621860, 0x6, 0x7, 0x6, 0x12094, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/coreos/etcd/raft/raft.go:763 +0xaa3
github.com/coreos/etcd/raft.(*raft).Step(0xc422621860, 0x6, 0x7, 0x6, 0x12094, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/coreos/etcd/raft/raft.go:579 +0x305
github.com/coreos/etcd/raft.(*RawNode).Step(0xc43e4352c0, 0x6, 0x7, 0x6, 0x12094, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/coreos/etcd/raft/rawnode.go:175 +0xbc
github.com/cockroachdb/cockroach/storage.(*Store).handleRaftMessage.func1(0xc43e4352c0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2490 +0x61
github.com/cockroachdb/cockroach/storage.(*Replica).withRaftGroupLocked(0xc42339cb40, 0xc46a34d9a0, 0xc42339cbb0, 0xc42339cbb0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:364 +0xa0
github.com/cockroachdb/cockroach/storage.(*Replica).withRaftGroup(0xc42339cb40, 0xc46a34d9a0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:373 +0x8a
github.com/cockroachdb/cockroach/storage.(*Store).handleRaftMessage(0xc42024a000, 0xc4205aefc0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2491 +0xd96
github.com/cockroachdb/cockroach/storage.(*Store).(github.com/cockroachdb/cockroach/storage.handleRaftMessage)-fm(0xc4205aefc0, 0xc420398690, 0x1)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:1086 +0x34
github.com/cockroachdb/cockroach/storage.(*RaftTransport).RaftMessage.func1.1.1(0x2010880, 0xc42ae4f3f0, 0xc420357e40, 0xc423010788, 0xc423010790)
        /go/src/github.com/cockroachdb/cockroach/storage/raft_transport.go:145 +0xe4
github.com/cockroachdb/cockroach/storage.(*RaftTransport).RaftMessage.func1.1()
        /go/src/github.com/cockroachdb/cockroach/storage/raft_transport.go:149 +0x45
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420362750, 0xc428fbcb10)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66
```

**Comment by tamird** [comment]
Likely related to #9229 which includes an easy repro.

**Comment by bdarnell** [comment]
#9229 was test-only, so this is a separate issue.

**Comment by tamird** [comment]
AFAIK, this has not been seen since August 14th. @bdarnell anything more you'd like to do here?

**Comment by bdarnell** [comment]
I think the bug is still present; it's just rare. From the stack trace, it looks like this is a node that wins an election immediately after being removed from the raft group. This should be a fairly straightforward thing to test (and fix) on the raft side.

**Comment by bdarnell** [comment]
I mentioned the wrong issue in #10530. This one is still open.

**Comment by bdarnell** [comment]
Bah, I'm not reading correctly today. Too many tabs open.
