### ISSUE TITLE
tests: client failure to read certificate when establishing a connection causes Server's Stopper to stall

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#8568]
I'm in a test that runs the cleanup function returned by `sqlutils.PGUrl()` early, and then tries to establish a connection to the server. Establishing a connection fails with a `stat` error on reading the certificate file (as it's been deleted by the cleanup). Then stopping the `Server`'s `Stopper` times out, waiting for the workers to be completed.
I see the goroutines below in the stack traces. I also see this log message that is probably related.

```
I160815 21:47:32.326061 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:58672->127.0.0.1:58674: use of closed network connection
```

I don't know if the 2nd one, with `pgwire.Match()` in there, is expected to be blocked like it is during normal server operation.
I'm also confused about how `Server.ServeWith()` is supposed to return when the stopper is closed, as the function doesn't seem to return under normal operation.

Will come back with repro instructions. @tamird are you a good person to talk about this with?

```
goroutine 52 [chan receive]:
github.com/cockroachdb/cmux.(*muxListener).Accept(0xc4202c0bc0, 0x52b1a48, 0xc42029a120, 0xc4201701f0, 0x5858020)
    <autogenerated>:9 +0x7f
github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith(0xc4201701f0, 0xc42029a120, 0x5850520, 0xc4202c0bc0, 0xc420262010, 0xc4204dd798, 0x4056200)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/util/netutil/net.go:117 +0x5d
github.com/cockroachdb/cockroach/server.(*Server).Start.func8()
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/server/server.go:378 +0xb5
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc42029a120, 0xc4201f9080)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66
```

```
goroutine 187 [IO wait]:
net.runtime_pollWait(0x62aef18, 0x72, 0xc)
    /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42078b720, 0x72, 0xc42056ab28, 0xc4200120c8)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42078b720, 0x5847920, 0xc4200120c8)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42078b6c0, 0xc4207e38d8, 0x4, 0x4, 0x0, 0x5847920, 0xc4200120c8)
    /usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420030108, 0xc4207e38d8, 0x4, 0x4, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:173 +0x70
github.com/cockroachdb/cmux.(*bufferedReader).Read(0xc420727260, 0xc4207e38d8, 0x4, 0x4, 0x0, 0x38, 0x20)
    /Users/andrei/work/src/github.com/cockroachdb/cmux/buffer.go:42 +0x118
io.ReadAtLeast(0x5840360, 0xc420727260, 0xc4207e38d8, 0x4, 0x4, 0x4, 0x5054860, 0x0, 0x1)
    /usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x5840360, 0xc420727260, 0xc4207e38d8, 0x4, 0x4, 0x0, 0x0, 0x2f4b969700000102)
    /usr/local/go/src/io/io.go:325 +0x58
github.com/cockroachdb/cockroach/sql/pgwire.(*readBuffer).readUntypedMsg(0xc4207e38c0, 0x5840360, 0xc420727260, 0x5017280, 0x5117e40, 0xc4201a0500)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/pgwire/encoding.go:73 +0x78
github.com/cockroachdb/cockroach/sql/pgwire.Match(0x5840360, 0xc420727260, 0xc420030108)
    /Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:98 +0x77
github.com/cockroachdb/cmux.(*cMux).serve(0xc4201b4900, 0x5859260, 0xc420030108, 0xc4200ba120, 0xc4204a6ea0)
    /Users/andrei/work/src/github.com/cockroachdb/cmux/cmux.go:143 +0x27e
created by github.com/cockroachdb/cmux.(*cMux).Serve
    /Users/andrei/work/src/github.com/cockroachdb/cmux/cmux.go:133 +0x17b
```

**Comment by tamird** [comment]
`Server.ServeWith()` returns when the listener is closed.

Can't help much without repro.

**Comment by andreimatei** [comment]
Looked through the code with Tamir. It seems that we should be closing all pg connections when the stopper is stopping. But the funny part is that the routine blocked in `Accept` seems to tell us that the stopped didn't even quiesce; so maybe there's a `RunTask` routine blocked on something.

**Comment by tschottdorf** [comment]
This kind of issue will just never get addressed. @andreimatei wanna take action or abandon ship? An explicit repro would make this a lot more actionable.

**Comment by andreimatei** [comment]
I'll abandon ship
