### ISSUE TITLE
sql: enums logic test can be very slow in fakedist-vec-off config

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#86270]
I've been seeing `enums` logic test become very slow in `fakedist-vec-off` config. Sometimes it gets stuck on `CREATE STATISTICS s FROM greeting_stats`, sometimes on `DROP TABLE sc;`. I'm attaching a goroutine dump of the latter case. (It was obtained via `make stress PKG=./pkg/sql/logictest/tests/fakedist-vec-off TESTS=enums TESTFLAGS='-test.v --show-sql' TESTTIMEOUT=4m STRESSFLAGS='-p 1'`.)

[stress.txt](https://github.com/cockroachdb/cockroach/files/9355013/stress.txt)

This goroutine seems suspicious:
```
15548 goroutine 13780 [select, 3 minutes]:
15549 github.com/cockroachdb/cockroach/pkg/sql/gcjob.waitForEmptyPrefix({0x54952f0, 0xc0065ce630}, 0x418cf00?, 0x7a81520?, 0x20?, {0xc001a4f6f0, 0x3,       0x8})
15550 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/gcjob/gc_job.go:380 +0x205
15551 github.com/cockroachdb/cockroach/pkg/sql/gcjob.deleteIndexZoneConfigsAfterGC({0x54952f0, 0xc0065ce630}, 0xc004672c48, 0x9f, 0xc0093febc0)
15552 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/gcjob/index_garbage_collection.go:185 +0xf1
15553 github.com/cockroachdb/cockroach/pkg/sql/gcjob.waitForGC({0x54952f0?, 0xc0065ce630?}, 0x1?, 0xc0097eec38?, 0xfcd733?)
15554 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/gcjob/gc_job.go:344 +0x70
15555 github.com/cockroachdb/cockroach/pkg/sql/gcjob.schemaChangeGCResumer.deleteDataAndWaitForGC({_}, {_, _}, {0xc001510000, {0xc000b9a2c0, 0xc0006b      0940, 0xc000b9a2b0, 0xc0025ca1e0}, {{0xc000964fa8}, {0xc000964fa8}, ...}, ...}, ...)
15556 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/gcjob/gc_job.go:332 +0x129
15557 github.com/cockroachdb/cockroach/pkg/sql/gcjob.schemaChangeGCResumer.Resume({0xc0087a5d40}, {0x54952f0, 0xc0065ce630}, {0x45883c0?, 0xc00944763      8})
15558 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/gcjob/gc_job.go:311 +0x374
15559 github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2(0x54952f0?, 0x54952f0?, {0x5471b50?, 0xc009447618?}, {0x549      52f0?, 0xc0065ce630?}, {0x45883c0?, 0xc009447638?}, 0xc0046738e8)
15560 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1240 +0xcc
15561 github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine(0xc00126f340, {0x54952f0, 0xc0075baa20}, {0x45883c0, 0xc009447638      }, {0x5471b50, 0xc009447618}, 0xc0087a5d40, {0xc0020a17c8, 0x7}, ...)
15562 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1241 +0x6ab
15563 github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob(0xc00126f340, {0x5495248, 0xc0088f25c0}, {0x5471b50, 0xc009447618}, 0xc0087a5d40,       {0xc0020a17c8, 0x7}, {0xc008671248, 0x16})
15564 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:408 +0x545
15565 github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1({0xc004625c00?, 0xc004e500c0?})
15566 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:329 +0xfa
15567 github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
15568 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489 +0x146
15569 created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
15570 › /home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:480 +0x43b
```
cc @ajwerner in case you get nerd-sniped.

**Comment by yuzefovich** [comment]
Here is another goroutine dump for when the test was stuck after all queries in the file had been executed. Looks like some issues with the cluster cleanup.

[stress2.txt](https://github.com/cockroachdb/cockroach/files/9355243/stress2.txt)

**Comment by ajwerner** [comment]
The stack trace you linked is expected. It's the GC job waiting for TTL expiration. The interesting stack traces are:
```
goroutine 27261 [select]:
github.com/cockroachdb/cockroach/pkg/util/retry.(*Retry).Next(0xc00bf493a0)
	/home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:127 +0x13e
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).waitForJobs(0xc00136f340?, {0x5495268, 0xc005eeb280}, {0x54da638, 0xc000c783f0}, {0xc00b5c1098?, 0x1, 0x1}, 0xc0072502a0)
	/home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/jobs/wait.go:91 +0x285
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Run(0xc00c4d2600?, {0x5495268, 0xc005eeb280}, {0x54da638, 0xc000c783f0}, {0xc00b5c1098, 0x1, 0x1})
	/home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/jobs/wait.go:174 +0x145
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper(0xc00c4d2600, {0x54698a0?, 0x7da8910?}, {0x0, 0x0}, {0x7f8a88f02d78?, 0xc000d91140?}, 0x1?)
	/home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2971 +0x975
```
and 
```
goroutine 27125 [select]:
github.com/cockroachdb/cockroach/pkg/util/retry.(*Retry).Next(0xc00c33acf8)
	/home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:127 +0x13e
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.(*Manager).WaitForNoVersion(0xc0001ff500, {0x5495310, 0xc008dfebd0}, 0x6d?, {0xf4240, 0x3b9aca00, 0x3ff8000000000000, 0x0, 0x0, 0x0})
	/home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:84 +0x1fe
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*CollectionFactory).Txn.func1({0xc005e3b000?, 0x2d, 0x54639c0?}, {{{0xc000851f08?, 0x0?}, 0xc00a725f00?}})
	/home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/txn.go:64 +0x157
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*CollectionFactory).Txn(0xc002928680, {0x5495310, 0xc008dfebd0}, {0x54da638, 0xc000c783f0}, 0xc000dc7290, 0xc0058b7028)
	/home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/txn.go:111 +0x1fa
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob(0xc0030acb60, {0x5495310, 0xc008dfebd0}, 0xc009415050?)
	/home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:111 +0xcf
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob({0x5495310, 0xc008dfebd0}, 0xc000475d10, 0x4?, {0x545ee80?, 0xc0030acb60}, 0xaf134e931a20001, {0xc002779800, 0x2d, 0x2d}, ...)
	/home/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:128 +0x517
```

This tells me that we've leaked a lease to a descriptor.

**Comment by yuzefovich** [comment]
I think that e06c2db4977e2dd8ce772a9ad863f1ae9e0f5a61 is broken somehow - it causes this slowness as well as some [panics](https://github.com/cockroachdb/cockroach/pull/86182#issuecomment-1215887705). Do you have an idea what's wrong with that commit?

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/commit/e06c2db4977e2dd8ce772a9ad863f1ae9e0f5a61#r81370236

**Comment by ajwerner** [comment]
My guess is that there's unexpected concurrency. The fact that we've got a `nil` in that tree which shouldn't have any nils in it is surprising. I'd also expect that concurrency could lead to other corruption of the data structure even if we do have the call to `Release` in the right place. The fact that we see this panic though makes me think that maybe the call to `ReleaseAll` is happening concurrently with reads.

**Comment by yuzefovich** [comment]
Indeed, there is concurrency involved. I didn't read the comments on `FlowCtx.Descriptors`, my bad. Thanks for looking into this.

**Comment by yuzefovich** [comment]
I'll revert the commit and will work on a proper fix.
