### ISSUE TITLE
workload/mixed-version/schemachanger: intermittent crash inside checkTxnStatusValid

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#87139]
Running the mixed version schema changer workload with the following options ```COCKROACH_DEV_LICENSE=... bin/roachtest run schemachange/mixed-versions --count 8``` (on the branch https://github.com/fqazi/cockroach/tree/mixedVersion). See attached log file on JIRA.

intermittently runs into the following error: 
```
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498  transaction unexpectedly finalized in (*roachpb.NotLeaseHolderError): ‹[NotLeaseHolderError] lease held by different store; r10: replica (n3,s3):3 not lease holder; current lease is repl=(n2,s2):5 seq=21 start
=1661821810.478834576,0 exp=1661821819.478742975,0 pro=1661821810.478742975,0›: "sql txn" meta={id=e90c75d4 key=‹/Table/15/1/792171021347651585/0› pri=0.06028642 epo=0 ts=1661821810.324165897,1 min=1661821810.312244382,0 seq=10} lock=true stat=ABORTED rts=1661821810.312244382,0 wto=false gul=1661821810.812244382,0
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !goroutine 19088 [running]:
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x1)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x8a
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc0009628a0, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, 0x170ffa21c8510347, ...})
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/util/log/clog.go:239 +0x97
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x5f30ce8, 0xc000076090}, 0x2, 0x4, 0x0, 0x0?, {0x51d1e71, 0x2e}, {0xc000a060f8, 0x2, ...})
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/util/log/channels.go:106 +0x645
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:834
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/roachpb.(*Error).checkTxnStatusValid(0xc009b9c2c0)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/roachpb/pkg/roachpb/errors.go:362 +0x134
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/roachpb.(*Error).UpdateTxn(0xc009b9c2c0, 0xc00a1e4ea0?)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/roachpb/pkg/roachpb/errors.go:347 +0xd0
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/roachpb.(*Error).SetTxn(...)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/roachpb/pkg/roachpb/errors.go:333
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes.func1()
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:130 +0xc5
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes(_, {_, _}, {{{0x170ffa21bba86c9e, 0x0, 0x0}, 0x0, {0x170ffa21c845bd1d, 0x0, 0x0}, ...}, ...})
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:320 +0x1259
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes(_, {_, _}, {{{0x0, 0x0, 0x0}, 0x0, {0x170ffa21c845bd1d, 0x0, 0x0}, ...}, ...})
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:226 +0x1f3
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc000ebc000, {0x5f30d58?, 0xc003f998c0?}, {0x11c?}, 0xc00a1e4d80)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/server/node.go:1002 +0x454
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc000ebc000, {0x5f30d58, 0xc003f996e0}, 0xc00a1e4d80)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/server/node.go:1051 +0xfc
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler.func1({0x5f30d58, 0xc003f996e0}, {0x5092660?, 0xc00a1e4d80})
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/roachpb/bazel-out/k8-fastbuild/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9584 +0x78
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1({0x5f30d58, 0xc003f996e0}, {0x5092660, 0xc00a1e4d80}, 0xc00932a1e0, 0xc0094d4ac8)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:95 +0x24c
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x5f30d58?, 0xc003f996e0?}, {0x5092660?, 0xc00a1e4d80?})
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! google.golang.org/grpc/external/org_golang_google_grpc/server.go:1117 +0x5b
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3({0x5f30d58, 0xc003f996e0}, {0x5092660, 0xc00a1e4d80}, 0xc000a07918?, 0xc009b9c1c0)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:263 +0x83
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x5f30d58?, 0xc003f996e0?}, {0x5092660?, 0xc00a1e4d80?})
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! google.golang.org/grpc/external/org_golang_google_grpc/server.go:1120 +0x83
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1({0x5f30d58?, 0xc003f996e0?})
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:232 +0x39
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc000fcc750, {0x5f30d58, 0xc003f996e0}, {0x203002?, 0x40?}, 0xc000a079e0)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:341 +0xd1
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1({0x5f30d58?, 0xc003f996e0?}, {0x5092660?, 0xc00a1e4d80?}, 0x4dbeb60?, 0x7f88d3097a01?)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:230 +0x95
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x5f30d58?, 0xc003f996e0?}, {0x5092660?, 0xc00a1e4d80?})
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! google.golang.org/grpc/external/org_golang_google_grpc/server.go:1120 +0x83
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !google.golang.org/grpc.chainUnaryInterceptors.func1({0x5f30d58, 0xc003f996e0}, {0x5092660, 0xc00a1e4d80}, 0xc00932a1e0, 0xc0094d4ac8)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! google.golang.org/grpc/external/org_golang_google_grpc/server.go:1122 +0x12b
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler({0x50553c0?, 0xc000ebc000}, {0x5f30d58, 0xc003f996e0}, 0xc00aebe480, 0xc0011465c0)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! github.com/cockroachdb/cockroach/pkg/roachpb/bazel-out/k8-fastbuild/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9586 +0x138
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !google.golang.org/grpc.(*Server).processUnaryRPC(0xc0028001c0, {0x5f761e8, 0xc001ed1860}, 0xc00a1e4c60, 0xc000841290, 0x8b46160, 0x0)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! google.golang.org/grpc/external/org_golang_google_grpc/server.go:1283 +0xcfd
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !google.golang.org/grpc.(*Server).handleStream(0xc0028001c0, {0x5f761e8, 0xc001ed1860}, 0xc00a1e4c60, 0x0)
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! google.golang.org/grpc/external/org_golang_google_grpc/server.go:1620 +0xa1b
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !google.golang.org/grpc.(*Server).serveStreams.func1.2()
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! google.golang.org/grpc/external/org_golang_google_grpc/server.go:922 +0x98
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !created by google.golang.org/grpc.(*Server).serveStreams.func1
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 ! google.golang.org/grpc/external/org_golang_google_grpc/server.go:920 +0x28a
F220830 01:10:10.524619 19088 roachpb/errors.go:362 ⋮ [-] 498 !
```

The rollback in question is consistently caused due to a cancelled context in the jobs code path:

```
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507  original error before rollback: ‹select-job›: context canceled true false false
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹goroutine 10966 [running]:›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹runtime/debug.Stack()›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       GOROOT/src/runtime/debug/stack.go:24 +0x65›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/kv.(*Txn).CleanupOnError(0xc009c38580, {0x5f30d58, 0xc0031fcb10}, {0x5efa260?, 0xc0099315c0})›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/kv/txn.go:702 +0xbf›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/kv.runTxn({0x5f30d58, 0xc0031fcb10}, 0x7?, 0x5f30d58?)›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/kv/db.go:966 +0x86›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl(0x50cd2fe?, {0x5f30d58, 0xc0031fcb10}, 0x5f02240?, 0x0?, 0xc0031f4e00?)›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/kv/db.go:925 +0x89›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn(...)›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/kv/db.go:904›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/jobs.(*Job).runInTxn(0x5f30d58?, {0x5f30d58?, 0xc0031fcb10?}, 0xa?, 0xc00089a230?)›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:745 +0x54›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/jobs.(*Job).update(0xc003c6bba0, {0x5f30d58?, 0xc005434210?}, 0x0?, 0x0, 0xc005e0f080)›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/jobs/update.go:152 +0x196›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/jobs.(*Job).Update(...)›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/jobs/update.go:140›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/jobs.(*Job).succeeded(0xc005e0f450?, {0x5f30d58?, 0xc005434210?}, 0x5f30d58?, 0xc005434210?)›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:634 +0x5c›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine(0xc0004a78c0, {0x5f30d58, 0xc005434210}, {0x4e87b20, 0xc003e51770}, {0x5f09228, 0xc003e51758}, 0xc003c6bba0, {0x50e4cc8, 0x9}, ...)›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1309 +0x13e5›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine(0xc0004a78c0, {0x5f30d58, 0xc005434210}, {0x4e87b20, 0xc003e51770}, {0x5f09228, 0xc003e51758}, 0xc003c6bba0, {0xc003c9ef28, 0x7}, ...)›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1247 +0xc45›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob(0xc0004a78c0, {0x5f30d58, 0xc005434030}, {0x5f09228, 0xc003e51758}, 0xc003c6bba0, {0xc003c9ef28, 0x7}, {0xc003c06dc8, 0x16})›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:410 +0x5c6›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1({0xc0042b0e00?, 0xc0084ff770?})›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:330 +0xfa›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489 +0x146›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx›
E220830 01:10:10.551513 10966 kv/txn.go:702 ⋮ [n3] 507 +‹       github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:480 +0x43b›
W220830 01:10:10.551667 10966 kv/txn.go:707 ⋮ [n3] 508  failure aborting transaction: ‹node unavailable; try another peer›; abort caused by: ‹select-job›: context canceled
```

Jira issue: CRDB-19171

**Comment by ajwerner** [comment]
This is due to something being amiss in https://github.com/cockroachdb/cockroach/pull/86683
