### ISSUE TITLE
tests: a failure in TestDockerJava is not reported properly

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8730]
I've been encountering recently multiple occurences of CircleCI failing without a clear reason, with the only error somewhat cryptic at the end of the build log:

```
acceptance: --- FAIL: TestDockerJava (6.97s)
[...]
error: bufio.Scanner: token too long
read unix @->/var/run/docker.sock: read: connection reset by peer
```

Meanwhile TeamCity is somewhat more informative but not much:

```
[18:51:43][Step 2/2] TestDockerJava (4s)
[18:51:43][TestDockerJava] I160821 18:51:43.642578 acceptance/cluster/localcluster.go:299  Initializing Cluster java:
[18:51:43][TestDockerJava] {"name":"java","nodes":[{"count":1,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
[18:51:43][TestDockerJava] I160821 18:51:43.647239 acceptance/cluster/docker.go:106  ImagePull cockroachdb/builder:20160816-112252 already exists
[18:51:43][TestDockerJava] I160821 18:51:43.924378 acceptance/cluster/localcluster.go:605  creating certs (1024bit) in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/.localcluster.certs.239851517
[18:51:44][TestDockerJava] I160821 18:51:44.017661 acceptance/cluster/localcluster.go:556  events monitor starts
[18:51:44][TestDockerJava] I160821 18:51:44.234855 acceptance/cluster/localcluster.go:505  *** started roach0 ***
[18:51:44][TestDockerJava]   ui:        https://127.0.0.1:36040
[18:51:44][TestDockerJava]   trace:     https://127.0.0.1:36040/debug/requests
[18:51:44][TestDockerJava]   logs:      /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestDockerJava/roach0/cockroach.INFO
[18:51:44][TestDockerJava]   pprof:     docker exec -it 69ca1 /bin/bash -c 'go tool pprof /cockroach <(wget --no-check-certificate -qO- https://$(hostname):8080/debug/pprof/heap)';
[18:51:44][TestDockerJava]   cockroach: [start --ca-cert=/certs/ca.crt --cert=/certs/node.crt --key=/certs/node.key --host=roach0 --alsologtostderr=INFO --verbosity=1 --store=path=/data1.0 --log-dir=/logs/roach0 --logtostderr=false]
[18:51:44][TestDockerJava] 
[18:51:44][TestDockerJava]   cli-env:   COCKROACH_INSECURE=false COCKROACH_CA_CERT=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/.localcluster.certs.239851517/ca.crt COCKROACH_CERT=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/.localcluster.certs.239851517/node.crt COCKROACH_KEY=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/.localcluster.certs.239851517/node.key COCKROACH_HOST=127.0.0.1 COCKROACH_PORT=36040
[18:51:44][TestDockerJava] I160821 18:51:44.234881 acceptance/replication_test.go:55  waiting for first range to have 1 replicas
[18:51:44][TestDockerJava] I160821 18:51:44.236682 rpc/context.go:170  dialing 127.0.0.1:36039
[18:51:44][TestDockerJava] I160821 18:51:44.237524 /go/src/google.golang.org/grpc/clientconn.go:454  Failed to dial 127.0.0.1:36039: connection error: desc = "transport: EOF"; please retry.
[18:51:45][TestDockerJava] I160821 18:51:45.237013 internal/client/db.go:493  failed batch: roachpb.Batch RPC failed: rpc error: code = 13 desc = connection error: desc = "transport: EOF"
[18:51:45][TestDockerJava] I160821 18:51:45.237032 util/stop/stopper.go:342  stop has been called, stopping or quiescing all running tasks
[18:51:45][TestDockerJava] I160821 18:51:45.237047 rpc/context.go:141  closing 127.0.0.1:36039
[18:51:45][TestDockerJava] I160821 18:51:45.238421 rpc/context.go:170  dialing 127.0.0.1:36039
[18:51:46][TestDockerJava] I160821 18:51:46.239737 acceptance/replication_test.go:77  found 1 replicas
[18:51:46][TestDockerJava] I160821 18:51:46.239751 util/stop/stopper.go:342  stop has been called, stopping or quiescing all running tasks
[18:51:46][TestDockerJava] I160821 18:51:46.239766 rpc/context.go:141  closing 127.0.0.1:36039
[18:51:46][TestDockerJava] I160821 18:51:46.239823 acceptance/replication_test.go:85  found 1 replicas
[18:51:46][TestDockerJava] I160821 18:51:46.244115 acceptance/cluster/docker.go:106  ImagePull cockroachdb/postgres-test:20160705-1326 already exists
[18:51:48][TestDockerJava] E160821 18:51:48.099438 acceptance/cluster/localcluster.go:521  node=0 status=die
[18:51:48][TestDockerJava] Exception in thread "main" org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
[18:51:48][TestDockerJava]  at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:201)
[18:51:48][TestDockerJava]  at org.postgresql.core.SetupQueryRunner.run(SetupQueryRunner.java:74)
[18:51:48][TestDockerJava]  at org.postgresql.core.v3.ConnectionFactoryImpl.runInitialQueries(ConnectionFactoryImpl.java:763)
[18:51:48][TestDockerJava]  at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:224)
[18:51:48][TestDockerJava]  at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
[18:51:48][TestDockerJava]  at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:159)
[18:51:48][TestDockerJava]  at org.postgresql.Driver.makeConnection(Driver.java:416)
[18:51:48][TestDockerJava]  at org.postgresql.Driver.connect(Driver.java:283)
[18:51:48][TestDockerJava]  at java.sql.DriverManager.getConnection(DriverManager.java:664)
[18:51:48][TestDockerJava]  at java.sql.DriverManager.getConnection(DriverManager.java:270)
[18:51:48][TestDockerJava]  at main.main(main.java:14)
[18:51:48][TestDockerJava] Caused by: java.io.EOFException
[18:51:48][TestDockerJava]  at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:285)
[18:51:48][TestDockerJava]  at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1719)
[18:51:48][TestDockerJava]  at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
[18:51:48][TestDockerJava]  ... 10 more
[18:51:48][TestDockerJava] I160821 18:51:48.278216 acceptance/cluster/localcluster.go:671  stopping
[18:51:48][TestDockerJava] I160821 18:51:48.278373 acceptance/cluster/localcluster.go:571  event stream done, resetting...: net/http: request canceled
[18:51:48][TestDockerJava] I160821 18:51:48.278380 acceptance/cluster/localcluster.go:594  events monitor exits
[18:51:48][TestDockerJava] I160821 18:51:48.292238 acceptance/cluster/localcluster.go:714  node 0: stderr at /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestDockerJava/roach0/stderr.2016-08-21T18_51_48Z.log
[18:51:48][TestDockerJava]  localcluster.go:650: unexpected extra event &{0 die} (after [])
[18:51:48][TestDockerJava]  localcluster.go:650: unexpected extra event &{0 die} (after [])
```

The error looks like the server is aborting yet the panic message, if any, is not reported by the test. We should modify this so that more output from both the server and the Java client is reported in the test log.

**Comment by dianasaur323** [comment]
@knz is this still an issue? If not, we should close out, otherwise let's assign to probably Q4 2017, unless you disagree?

**Comment by knz** [comment]
This has been addressed by my recent logging changes; we should now expect panic messages more clearly available in CI.
