### ISSUE TITLE
acceptance: TestDocker failing under race

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#87700]
**Describe the problem**

In an unrelated PR I reliably see the "testrace" CI target failing in `TestDockerC` (the first of the docker tests: the specific test doesn't matter, the issue repros with all of them) with the stack trace below.

This corresponds to the following go code failing:
```go
  if *cockroachImage == defaultImage && !exists(*CockroachBinary) {
    log.Fatalf(ctx, "\"%s\": does not exist", *CockroachBinary)
  }
```

**The fatal message suggests that the CockroachBinary string is empty.**

Example here https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_Testrace/6409520?showRootCauses=false&expandBuildChangesSection=true&expandBuildTestsSection=true

```
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1  "": does not exist
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !goroutine 43 [running]:
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0)
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x9c
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000c3b0e0, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, 0x171335b442fe7329, ...})
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:260 +0xb7
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x985c508, 0xc000080098}, 0x2, 0x4, 0x0, 0x0, {0x68641ad, 0x14}, {0xc001bda800, 0x1, ...})
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:106 +0x6e6
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !	github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild-ST-1665e0aa65f7/bin/pkg/util/log/log_channels_generated.go:848
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !github.com/cockroachdb/cockroach/pkg/acceptance/cluster.CreateDocker({0x985c508, 0xc000080098}, {{0x682f22f, 0x1}, {0xc000c3b410, 0x1, 0x1}, 0x12a05f200, 0x0, 0x0}, ...)
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !	github.com/cockroachdb/cockroach/pkg/acceptance/cluster/pkg/acceptance/cluster/dockercluster.go:155 +0x1d6
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !github.com/cockroachdb/cockroach/pkg/acceptance.StartCluster({0x985c508, 0xc000080098}, 0xc000701a00, {{0x682f22f, 0x1}, {0xc000c3b410, 0x1, 0x1}, 0x12a05f200, 0x0, ...})
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !	github.com/cockroachdb/cockroach/pkg/acceptance/util_cluster.go:79 +0x3fd
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !github.com/cockroachdb/cockroach/pkg/acceptance.testDocker.func1(0xc000701a00)
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !	github.com/cockroachdb/cockroach/pkg/acceptance/util_docker.go:124 +0xae7
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !testing.tRunner(0xc000701a00, 0xc000c30440)
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !	GOROOT/src/testing/testing.go:1446 +0x217
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !created by testing.(*T).Run
[15:55:35] :		 [Run race detector tests] F220909 13:55:35.764202 43 acceptance/cluster/dockercluster.go:155  [-] 1 !	GOROOT/src/testing/testing.go:1493 +0x75e
```

Jira issue: CRDB-19489

**Comment by rickystewart** [comment]
Looks like we should skip testing `acceptance` in `testrace`, which makes sense (it's for unit tests, `acceptance` is not a unit test).
