### ISSUE TITLE
changefeedccl: TestChangefeedDescription is flaky

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#89090]
As reported by flaky test fighters, TestChangefeedDescription appears to be flaky
(https://teamcity.cockroachdb.com/test/9211750895698444249?currentProjectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&expandTestHistoryChartSection=true)

Worse still, it flakes with SIGSEGV:
```
 === RUN   TestChangefeedDescription/CREATE_CHANGEFEED_INTO_$1_WITH_updated,_envelope_=_$2,_schema_change_policy='stop'_AS_SELECT_a_FROM_foo_WHERE_status_IN_('open',_'closed')
      panic: runtime error: invalid memory address or nil pointer dereference
      [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9390b8]
      
      goroutine 37942 [running]:
      database/sql.(*DB).Close(0x0)
        GOROOT/src/database/sql/sql.go:883 +0x38
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*sqlSink).Close(0xc0082bb100?)
        github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_sql.go:228 +0x1c
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).close(0xc0082bb100)
        github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1003 +0x66
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).ConsumerClosed(0xc0082bb100?)
        github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1456 +0x19
      github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run({0x6207ef0, 0xc00ccdacf0}, {0x6227860, 0xc0082bb100}, {0x61e2a20?, 0xc0035f3500?})
        github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:197 +0xa4
      github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run(0xc0082bb100, {0x6207e48?, 0xc006081980?})
        github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:730 +0x5b
      github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc008dd63c0, {0x6207e48, 0xc006081980}, 0x0?)
        github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:472 +0x25a
      github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00318b680, {0x6207e48, 0xc006081900}, 0xc0060952c0, 0x0, 0xc0081ab780, 0xc00f8ac000, 0xc004a15800, 0xc003d97f18)
        github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:695 +0xad9
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.startDistChangefeed.func3({0x6207e48, 0xc006081900})
        github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_dist.go:303 +0x2e5
      github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
        github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x25
      golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:74 +0x64
      created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:71 +0xa5
```

Jira issue: CRDB-20110

Epic CRDB-11732

**Comment by miretskiy** [comment]
Having hard time to repro, both on gce and locally.  4K runs

**Comment by samiskin** [comment]
It looks like it hasn't failed in the past 5 days so this may have already been fixed by something
