### ISSUE TITLE
TestStoreRangeMergeNonConsecutive loses Raft command on last range, times out

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#893]
The following test appears to have failed:

[#2050](https://circleci.com/gh/cockroachdb/cockroach/2050):

```
I0502 15:30:39.768189     443 multiraft.go:694] node 100000001: group 2 raft ready
I0502 15:30:39.768254     443 multiraft.go:699] HardState updated: {Term:6 Vote:4294967297 Commit:16 XXX_unrecognized:[]}
I0502 15:30:39.769040     443 multiraft.go:702] New Entry[0]: 6/16 EntryNormal 0000000000000000799e447ae60f42c8: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 15:30:39.769815     443 multiraft.go:705] Committed Entry[0]: 6/16 EntryNormal 0000000000000000799e447ae60f42c8: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 15:30:39.771286     443 multiraft.go:873] dropping stale write to group 3
panic: test timed out after 5m0s

goroutine 3477 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x13466c8, 0x182a420, 0xa3, 0xa3, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:502 +0xd2a
github.com/cockroachdb/cockroach/util.func·005()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0x133
FAIL	github.com/cockroachdb/cockroach/storage	300.049s
=== RUN TestBatchBasics
I0502 15:31:31.356473     531 rocksdb.go:88] opening in-memory rocksdb instance
I0502 15:31:31.357485     531 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0502 15:31:31.360548     531 rocksdb.go:88] opening in-memory rocksdb instance
I0502 15:31:31.360922     531 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0502 15:31:31.364016     531 rocksdb.go:88] opening in-memory rocksdb instance
I0502 15:30:39.768189     443 multiraft.go:694] node 100000001: group 2 raft ready
I0502 15:30:39.768254     443 multiraft.go:699] HardState updated: {Term:6 Vote:4294967297 Commit:16 XXX_unrecognized:[]}
I0502 15:30:39.769040     443 multiraft.go:702] New Entry[0]: 6/16 EntryNormal 0000000000000000799e447ae60f42c8: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 15:30:39.769815     443 multiraft.go:705] Committed Entry[0]: 6/16 EntryNormal 0000000000000000799e447ae60f42c8: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 15:30:39.771286     443 multiraft.go:873] dropping stale write to group 3
panic: test timed out after 5m0s

goroutine 3477 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x13466c8, 0x182a420, 0xa3, 0xa3, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:502 +0xd2a
github.com/cockroachdb/cockroach/util.func·005()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0x133
FAIL	github.com/cockroachdb/cockroach/storage	300.049s
=== RUN TestBatchBasics
I0502 15:31:31.356473     531 rocksdb.go:88] opening in-memory rocksdb instance
I0502 15:31:31.357485     531 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0502 15:31:31.360548     531 rocksdb.go:88] opening in-memory rocksdb instance
I0502 15:31:31.360922     531 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0502 15:31:31.364016     531 rocksdb.go:88] opening in-memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
likely related to #838.
Looks like a Raft command got lost while the test was winding down.

```
goroutine 3433 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*Range).requestLeaderLease(0xc208732000, 0x0, 0x34, 
...
```
first mover here is an intent cleanup that blocks the shutdown because it never hears back from Raft about its leader lease. Presumably this is on the last (merged and re-added) range.

The last log entry about the dropped write to group three is from handleWriteResponse in MultiRaft and is caused by the fact that the group doesn't exist in MultiRaft at that point in time. That suggests that group three should exist and the fact that it doesn't blocks a first mover which then never finishes.

We re-add the third range at the end of the test. When it tries to get the lease, it goes through store.ProposeRaftCommand, which should synchronously create the Raft group previously deleted in the merge. However the merge clearly committed earlier, which means that the synchronous delete of the group should have happened strictly before.

The logs indicate that in the course of the test run only three Raft groups were ever created (it should be four). So the group seems to have been deleted, but not re-added.

**Comment by tschottdorf** [comment]
ping @bdarnell

**Comment by tschottdorf** [comment]
Another one from #899. This time the lease is acquired, but the resolve intent never hears back again. Log indicates no dropped Raft messages.

```
goroutine 3500 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/storage.func·018(0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/range.go:700 +0xe1
github.com/cockroachdb/cockroach/storage.(*Range).addWriteCmd(0xc2080787e0, 0x7fbdaca27b68, 0xc2083a8c80, 0x7fbdaca27bc0, 0xc208011dc0, 0x1, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/range.go:719 +0xc83
github.com/cockroachdb/cockroach/storage.(*Range).AddCmd(0xc2080787e0, 0x7fbdaca27b68, 0xc2083a8c80, 0x7fbdaca27bc0, 0xc208011dc0, 0x1, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/range.go:529 +0x57c
github.com/cockroachdb/cockroach/storage.func·036(0x86926b, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:988 +0x2a5
github.com/cockroachdb/cockroach/util.RetryWithBackoff(0xc20883a580, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc208373db0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/util/retry.go:81 +0x71
github.com/cockroachdb/cockroach/storage.(*Store).ExecuteCmd(0xc20845f380, 0x7fbdaca27b68, 0xc2083a8c80, 0x7fbdaca27bc0, 0xc208011dc0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1038 +0x65b
github.com/cockroachdb/cockroach/kv.(*LocalSender).Send(0xc20846c200, 0x7fbdaca27b68, 0xc2083a8c80, 0x7fbdaca27bc0, 0xc208011dc0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/kv/local_sender.go:148 +0x331
github.com/cockroachdb/cockroach/kv.func·011()
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:142 +0x29f
created by github.com/cockroachdb/cockroach/kv.(*txnMetadata).close
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:147 +0xbae
```

**Comment by tschottdorf** [comment]
In the above failure the stopper is stuck at draining state again. The last Raft entries make it to logRaftReady, but then never into the writeTask. The MultiRaft state loop is still running though and stuck on a select (so if writeReady freed up, it should progress).
The storage task which consumes from writeReady (`writeTask.start`) is stuck on the select that... should consume from writeReady.
I don't understand why it just sits there.

**Comment by tschottdorf** [comment]
Probably it did get a little further. Unfortunately there isn't really anything that gets logged until it ends up in `applyRaftCommand`, I think. We should add a bunch of logging in there unless @bdarnell sees right away who the likely culprit could be.

**Comment by tschottdorf** [comment]
I think what happens is that the InternalResolveIntent gets into Raft while the group is still there, and then the group gets deleted and the command never resolves.
One way to deal with this is to somehow cancel all outstanding commands on a group when it is deleted. That may not be a great thing to do (we have a `pending` map keyed by `commandID`, so we have to scan it) but the pending map should be small and group deletions not too frequent. I'll put together a PR and see if it fixes it.

**Comment by tschottdorf** [comment]
Oh, the pending map is on the group. So it's going to be smooth sailing.
