### ISSUE TITLE
circleci: failed tests: TestReplicaCommandQueueCancellation

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8998]
The following test appears to have failed:

[#22084](https://circleci.com/gh/cockroachdb/cockroach/22084):

```
I160831 19:46:36.126968 1570 storage/replica.go:2738  gossiping sentinel from store 1, range 1
I160831 19:46:36.127216 1570 storage/replica.go:2745  gossiping first range from store 1, range 1: [{1 1 1}]
I160831 19:47:36.126760 1570 storage/replica.go:2716  gossiping cluster id {"82c21f7b-b567-4f92-909e-f590e7130d95"} from store 1, range 1
I160831 19:47:36.127174 1570 storage/replica.go:2738  gossiping sentinel from store 1, range 1
I160831 19:47:36.127415 1570 storage/replica.go:2745  gossiping first range from store 1, range 1: [{1 1 1}]
panic: test timed out after 8m0s

goroutine 1600 [running]:
panic(0x1ae98a0, 0xc420a00110)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:918 +0x14e
created by time.goFunc
	/usr/local/go/src/time/sleep.go:154 +0x78

goroutine 1 [chan receive, 7 minutes]:
testing.(*T).Run(0xc420250d80, 0x1cae512, 0x23, 0x1f59fd0, 0x99f601)
	/usr/local/go/src/testing/testing.go:647 +0x56e
testing.RunTests.func1(0xc420250d80)
	/usr/local/go/src/testing/testing.go:793 +0xba
testing.tRunner(0xc420250d80, 0xc420045b38)
	/usr/local/go/src/testing/testing.go:610 +0xca
testing.RunTests(0x1f5bb58, 0x2833440, 0x13b, 0x13b, 0xc42024edc8)
	/usr/local/go/src/testing/testing.go:799 +0x4bb
testing.(*M).Run(0xc420045ef0, 0xc420285ce0)
	/usr/local/go/src/testing/testing.go:743 +0x130
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc420045ef0)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:57 +0x287
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:692 +0x1b6

goroutine 17 [syscall, 7 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2b7ce00)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1032 +0x85
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:613 +0xc3

goroutine 1564 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:409 +0x36a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc4201ab080)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1586 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc42007d080, 0xecf5929b4, 0xc407a3efd8, 0x2b7bca0, 0xc4201c2940, 0xc420aaa090, 0xc42008a240, 0xc4209e7b28)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:201 +0x299
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc42008a240, 0xc420a26f60)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:259 +0x124
github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc420a272f0, 0xc42095b4c0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:242 +0x453
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:261 +0x3a5
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc4201ab1c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1519 [semacquire, 7 minutes]:
sync.runtime_Semacquire(0xc4203a718c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc4203a7180)
	/usr/local/go/src/sync/waitgroup.go:131 +0xbf
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2545 +0x6f3
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc420a018f0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1518 [select, 3 minutes]:
github.com/cockroachdb/cockroach/storage.(*bookie).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/reservation.go:274 +0x4c8
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc420951880)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1566 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:409 +0x36a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc4201ab0c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1563 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:409 +0x36a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc4201ab060)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1552 [chan receive, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1.1(0xc4209aa120)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2466 +0x58
created by github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2469 +0xd8

goroutine 1562 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:409 +0x36a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc4201ab040)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1515 [chan receive, 7 minutes]:
github.com/cockroachdb/cockroach/storage.TestReplicaCommandQueueCancellation(0xc420116180)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_test.go:2017 +0x857
testing.tRunner(0xc420116180, 0x1f59fd0)
	/usr/local/go/src/testing/testing.go:610 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x530

goroutine 1521 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*Store).Start.func4()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:948 +0x19d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc420951e00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1517 [chan receive, 7 minutes]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc42000ca80)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:388 +0x64
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:389 +0xb61

goroutine 1571 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1044 +0x34a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc420a01930)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1570 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1024 +0x34a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc420a01920)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1569 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:409 +0x36a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc4201ab1a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1551 [chan send, 7 minutes]:
github.com/cockroachdb/cockroach/storage.TestReplicaCommandQueueCancellation.func1(0x7f42aa5dd028, 0xc420a27b90, 0xc4203a71e8, 0x8, 0x0, 0x1, 0x28545e0, 0xc42015f1a0, 0x0, 0x12, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_test.go:1950 +0x9b
github.com/cockroachdb/cockroach/storage.(*Replica).executeCmd(0xc42008a240, 0x7f42aa5dd028, 0xc420a27b90, 0xc4203a71e8, 0x8, 0x0, 0x7f42aa5dc7a0, 0xc42096ca80, 0xc420055260, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:82 +0x450a
github.com/cockroachdb/cockroach/storage.(*Replica).executeBatch(0xc42008a240, 0x7f42aa5dd028, 0xc420a27b90, 0xc4203a71e8, 0x8, 0x7f42aa5dc7a0, 0xc42096ca80, 0xc420055260, 0x0, 0x12, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2553 +0x42c
github.com/cockroachdb/cockroach/storage.(*Replica).executeWriteBatch(0xc42008a240, 0x7f42aa5dd028, 0xc420a27b90, 0xc4203a71e8, 0x8, 0x0, 0x12, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2375 +0x256
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommandInBatch(0xc42008a240, 0x7f42aa5dd028, 0xc420a27b90, 0xc4203a71e8, 0x8, 0x100000001, 0x1, 0x0, 0x12, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2291 +0xf5
--
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1.1(0xc4209aa120)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2467 +0x74
created by github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2469 +0xd8

goroutine 1516 [chan receive, 7 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:122 +0x95
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc4209505c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1568 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc42007d000, 0xecf5929b4, 0xc4079bc2be, 0x2b7bca0, 0xc4201c2940, 0xc420aaa090, 0xc42008a240, 0xc4209e7b28)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:201 +0x299
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc42008a240, 0xc420a26f60)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:259 +0x124
github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc420a27050, 0xc42095b080)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:242 +0x453
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:261 +0x3a5
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc4201ab100)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1554 [chan receive, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1.1(0xc4209aa120)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2466 +0x58
created by github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2469 +0xd8

goroutine 1553 [chan receive, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1.1(0xc4209aa120)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2466 +0x58
created by github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2469 +0xd8

goroutine 1576 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*Replica).addWriteCmd(0xc42008a240, 0x7f42aa5dd028, 0xc420a27b90, 0x0, 0x12, 0x0, 0x0, 0x0, 0x4045000000000000, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1372 +0x5f5
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc42008a240, 0x7f42aa5dd028, 0xc420a27b90, 0x0, 0x12, 0x0, 0x0, 0x0, 0x4045000000000000, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:933 +0x292
github.com/cockroachdb/cockroach/internal/client.Wrap.func1(0x7f42aa5dcb18, 0xc4201c3100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4045000000000000, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/sender.go:76 +0x106
github.com/cockroachdb/cockroach/internal/client.SenderFunc.Send(0xc420951ee0, 0x7f42aa5dcb18, 0xc4201c3100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4045000000000000, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/sender.go:37 +0x86
github.com/cockroachdb/cockroach/storage.TestReplicaCommandQueueCancellation.func2.1()
	/go/src/github.com/cockroachdb/cockroach/storage/replica_test.go:1974 +0x632
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask.func1(0xc420aaa090, 0x253c26f, 0x17, 0x7b8, 0xc4201c3180)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:231 +0xa3
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:232 +0xca

goroutine 1565 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:409 +0x36a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc4201ab0a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74

goroutine 1567 [select, 7 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:409 +0x36a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420aaa090, 0xc4201ab0e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74
FAIL	github.com/cockroachdb/cockroach/storage	480.098s
=== RUN   TestBatchBasics
I160831 19:42:54.725672 21 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160831 19:42:54.727795 21 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchRepr
I160831 19:42:54.739668 7 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160831 19:42:54.741043 7 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.01s)
=== RUN   TestBatchGet
I160831 19:42:54.749710 26 storage/engine/rocksdb.go:354  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
#8986.
