### ISSUE TITLE
Test Timeout issue after 60 m in backupccl package on X86

### ISSUE THREAD

**Issue by ambujkumar3** [cockroachdb/cockroach#91383]
Describe the problem

I built the cockroachdb master on intel(x86) and when I executed the test suite, I found that there were test failures for the following packages:
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/backupccl	3601.209s

make test PKG=./pkg/ccl/backupccl TESTFLAGS='-v -count=1' 

When I analysed the log, I found that the failing tests were due to Timeout failure after 60 m. 
A sample log of test failure

Error:
     panic: test timed out after 1h0m0s
panic: test timed out after 1h0m0s

goroutine 833954 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:2036 +0x8e
created by time.goFunc
        /usr/local/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 1 minutes]:
testing.(*T).Run(0xc0001a51e0, {0x4c76676?, 0x549e25?}, 0x4f4a120)
        /usr/local/go/src/testing/testing.go:1494 +0x37a
testing.runTests.func1(0xc00092df80?)
        /usr/local/go/src/testing/testing.go:1846 +0x6e
testing.tRunner(0xc0001a51e0, 0xc0022bfc60)
        /usr/local/go/src/testing/testing.go:1446 +0x10b
testing.runTests(0xc000b1d2c0?, {0x8a664e0, 0xb6, 0xb6}, {0x0?, 0x0?, 0x8db7ba0?})
        /usr/local/go/src/testing/testing.go:1844 +0x456
testing.(*M).Run(0xc000b1d2c0)
        /usr/local/go/src/testing/testing.go:1726 +0x5d9
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.TestMain(0xffffffffffffffff?)
        /root/go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/main_test.go:31 +0x148

FAIL    github.com/cockroachdb/cockroach/pkg/ccl/backupccl      3604.539s

To Reproduce
  make test PKG=./pkg/ccl/backupccl TESTFLAGS='-v -count=1'

Environment:
CockroachDB [master]
Architecture and OS: [x86_64/RHEL/UBI 8.5]
Go: [1.19.1]
Node: [16.13.0]

Any pointers to resolve the failures would be of great help.

**Comment by msbutler** [comment]
@ambujkumar3 thanks for filing! a few quick notes:

- was there a specific test you were intending to run in the backupccl suite?
- make builds have been deprecated on master. try using bazel via dev: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/2221703221/Developing+with+Bazel
