### ISSUE TITLE
Scala compatibility: client does not see pg error codes

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9317]
This was reported by @kosii in https://github.com/cockroachdb/docs/issues/646: the pg error code is not visible via regular exception handling in a Scala client.

A test project that reproduces the issue is provided here: https://github.com/kosii/reprod-errorcode-problem. That client sees a `retry txn` exception but the corresponding error code is reported to be 0.

The two questions that arise are:
- is there anything we are not doing right in the pgwire protocol that causes the Scala client driver to not pick up and report the error code properly; or
- if this is an issue in the Scala client driver, should be better advertise a different driver or rather explain how to work around the limitation (by emphasizing a test on the text of the error messages in our docs)

**Comment by kosii** [comment]
note: it might nothing to do with Scala, the exception is directly thrown from the Java client driver (`"org.postgresql" % "postgresql" % "9.4.1208"`), scalikejdbc is just a convenience library around the JDBC APIs. Please find the full stacktrace here:

```
org.postgresql.util.PSQLException: ERROR: restart transaction: txn "sql/executor.go:492 sql txn" id=8af60dec key=/Table/52/2/1473772745977/"ns0"/"k28"/0 rw=false pri=0.03528562 iso=SERIALIZABLE stat=PENDING epo=1 ts=1473775603.683415039,1 orig=1473775603.683415039,1 max=1473775599.758548667,0 wto=false rop=false failed to push "sql/executor.go:492 sql txn" id=2f6d7d07 key=/Table/52/1/"ns0"/"k28"/0 rw=true pri=0.03528567 iso=SERIALIZABLE stat=PENDING epo=0 ts=1473775603.679379439,0 orig=1473775603.679379439,0 max=1473775603.679379439,0 wto=false rop=false
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:133)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at scalikejdbc.DBConnectionAttributesWiredPreparedStatement.executeUpdate(DBConnectionAttributesWiredPreparedStatement.scala:79)
	at scalikejdbc.StatementExecutor$$anonfun$executeUpdate$1.apply$mcI$sp(StatementExecutor.scala:342)
	at scalikejdbc.StatementExecutor$$anonfun$executeUpdate$1.apply(StatementExecutor.scala:342)
	at scalikejdbc.StatementExecutor$$anonfun$executeUpdate$1.apply(StatementExecutor.scala:342)
	at scalikejdbc.StatementExecutor$NakedExecutor.apply(StatementExecutor.scala:18)
	at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLAndTiming$$super$apply(StatementExecutor.scala:320)
	at scalikejdbc.StatementExecutor$LoggingSQLAndTiming$class.apply(StatementExecutor.scala:264)
	at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLIfFailed$$super$apply(StatementExecutor.scala:320)
	at scalikejdbc.StatementExecutor$LoggingSQLIfFailed$class.apply(StatementExecutor.scala:297)
	at scalikejdbc.StatementExecutor$$anon$1.apply(StatementExecutor.scala:320)
	at scalikejdbc.StatementExecutor.executeUpdate(StatementExecutor.scala:342)
	at scalikejdbc.DBSession$$anonfun$updateWithFilters$1.apply(DBSession.scala:477)
	at scalikejdbc.DBSession$$anonfun$updateWithFilters$1.apply(DBSession.scala:475)
	at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18)
	at scalikejdbc.ActiveSession.scalikejdbc$DBSession$$super$using(DBSession.scala:706)
	at scalikejdbc.DBSession$class.using(DBSession.scala:30)
	at scalikejdbc.ActiveSession.using(DBSession.scala:706)
	at scalikejdbc.DBSession$class.updateWithFilters(DBSession.scala:474)
	at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:706)
	at scalikejdbc.DBSession$class.updateWithFilters(DBSession.scala:449)
	at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:706)
	at scalikejdbc.SQLUpdate.apply(SQL.scala:632)
	at Main$$anonfun$clean$1.apply(Main.scala:39)
	at Main$$anonfun$clean$1.apply(Main.scala:38)
	at scala.collection.immutable.List.map(List.scala:277)
	at Main$.clean(Main.scala:38)
	at Main$$anonfun$1$$anonfun$6$$anonfun$2.apply$mcJ$sp(Main.scala:59)
	at Main$$anonfun$1$$anonfun$6$$anonfun$2.apply(Main.scala:59)
	at Main$$anonfun$1$$anonfun$6$$anonfun$2.apply(Main.scala:59)
	at scala.util.Try$.apply(Try.scala:192)
	at Main$$anonfun$1$$anonfun$6.apply(Main.scala:59)
	at Main$$anonfun$1$$anonfun$6.apply(Main.scala:57)
	at scalikejdbc.DBConnection$$anonfun$3.apply(DBConnection.scala:305)
	at scalikejdbc.DBConnection$class.scalikejdbc$DBConnection$$rollbackIfThrowable(DBConnection.scala:274)
	at scalikejdbc.DBConnection$class.localTx(DBConnection.scala:303)
	at scalikejdbc.DB.localTx(DB.scala:60)
	at scalikejdbc.DB$.localTx(DB.scala:260)
	at Main$$anonfun$1.apply$mcV$sp(Main.scala:56)
	at Main$$anonfun$1.apply(Main.scala:56)
	at Main$$anonfun$1.apply(Main.scala:56)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by paperstreet** [comment]
fwiw, we have the https://github.com/finagle/finagle-postgres driver in integration tests. @dt knows more

**Comment by knz** [comment]
cc @dt @andreimatei @jordanlewis

**Comment by dt** [comment]
Our (currently skipped) `finagle-postgres` tests wouldn't cover this anyway, since `finagle-postgres` is its own driver and doesn't use JDBC.

**Comment by dt** [comment]
We've filled in lots of error codes since this was filed and I believe @jordanlewis has tested/fixed Java and JDBC support a fair bit as well, which we hadn't done much of at the time. Pretty sure it is safe to close this (I'll let @jordanlewis chime in / reopen if I'm wrong though).
