### ISSUE TITLE
stability: panic on version discrepancy

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#9347]
Upgrading gamma from d8213c2 to d262ae3 using a rolling restart.

Nodes crashed right away with:
```
panic: interface conversion: interface is nil, not roachpb.Request [recovered]
        panic: interface conversion: interface is nil, not roachpb.Request

goroutine 45 [running]:
panic(0x15a5780, 0xc421a466c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/cli.initBacktrace.func2(0x15a5780, 0xc421a466c0)
        /go/src/github.com/cockroachdb/cockroach/cli/backtrace.go:98 +0xca
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc42040d560)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:173 +0x56
panic(0x15a5780, 0xc421a466c0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/roachpb.RequestUnion.GetInner(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/roachpb/api.go:325 +0x6f
github.com/cockroachdb/cockroach/roachpb.(*BatchRequest).GetArg(0xc4217a33b8, 0x16, 0xc421dfe540, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/roachpb/batch.go:139 +0xdd
github.com/cockroachdb/cockroach/roachpb.(*BatchRequest).IsLease(0xc4217a33b8, 0xc4203b9380)
        /go/src/github.com/cockroachdb/cockroach/roachpb/batch.go:78 +0x3e
github.com/cockroachdb/cockroach/storage.(*Replica).processRaftCommand(0xc4203a26c0, 0xc421152970, 0x8, 0x20831, 0x15804, 0x100000001, 0x1, 0x1473ff8ab84d635e, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2357 +0x92a
github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady(0xc4203a26c0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1894 +0x8b8
github.com/cockroachdb/cockroach/storage.(*Store).processReady(0xc4201c6280, 0x15804)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2571 +0xfd
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc42031c620, 0xc42040d560)
        /go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:197 +0x308
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
        /go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc42040d560, 0xc42074aee0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66
```

This is most likely due to 5e1ce5a.

After the first node (`104.196.169.188`) started crash-looping, stopped all of them and restarted at the new version. However, other nodes started crashing. Reverted back to d8213c2

**Comment by mberhault** [comment]
Gave the nodes time to run on d8213c2, then shut down everything, swapped binaries, and restart all nodes. Started panicking again. Reverting once more and will leave it that way.

**Comment by petermattis** [comment]
Presumably one of the Raft logs contains a `BatchRequest` which contains a `VerifyChecksumRequest` that is now unmarshaled into a nil Request.

**Comment by tschottdorf** [comment]
That must be the reason, but if I understood correctly now both versions panicked? Shouldn't the old one keep running?

**Comment by petermattis** [comment]
Sounds like only the new version panicked. Marc tried first with a rolling upgrade, reverted to the previous version and then tried a stop-the-world upgrade. But we really need a `freeze-cluster` upgrade in order to work.

**Comment by tschottdorf** [comment]
Gotcha. I'll give the freeze-cluster upgrade a try, haven't done that in a while.

**Comment by petermattis** [comment]
Sure. I think it is still worthwhile to fix the issue for the next time it arises. #9349 essentially makes removing a request from `RequestUnion` equivalent to replacing whatever was there with a `NoopRequest`.

**Comment by tamird** [comment]
It also makes accidental omissions equivalent to `NoopRequest`s 😨

**Comment by tschottdorf** [comment]
I agree that there's something to fix here, though I disagree about the actual fix (but we can talk about that in #9349).

**Comment by tschottdorf** [comment]
I believe we're back up and running on https://github.com/cockroachdb/cockroach/commit/d262ae331246b89bd919d9c7679556603b9ca16e. I used `freeze-cluster` (which naturally didn't terminate without telling me why not (https://github.com/cockroachdb/cockroach/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20freeze-cluster)) but starting the new version worked fine.

**Comment by mberhault** [comment]
Upgrading `rho` to include the fix, I'm getting the following:
This is on the first node, running a race build of 32df163, the others are still running 186e4e3
```
panic: unsupported type *roachpb.DeprecatedVerifyChecksumRequest [recovered]
        panic: unsupported type *roachpb.DeprecatedVerifyChecksumRequest

goroutine 151 [running]:
panic(0x1ad0ec0, 0xc420d4a4c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1ae
github.com/cockroachdb/cockroach/cli.initBacktrace.func2(0x1ad0ec0, 0xc420d4a4c0)
        /go/src/github.com/cockroachdb/cockroach/cli/backtrace.go:98 +0xe8
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc4204c0900)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:173 +0xb1
panic(0x1ad0ec0, 0xc420d4a4c0)
        /usr/local/go/src/runtime/panic.go:458 +0x271
github.com/cockroachdb/cockroach/roachpb.(*BatchRequest).CreateReply(0xc421470258, 0xa)
        /go/src/github.com/cockroachdb/cockroach/roachpb/batch.go:318 +0x277f
github.com/cockroachdb/cockroach/storage.(*Replica).executeBatch(0xc42107a480, 0x7f32c34448a0, 0xc4210880f0, 0xc420d50f88, 0x8, 0x7f32c344a668, 0xc420e47a40, 0xc420d97260, 0x14743d64e6545738, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2852 +0x7e
github.com/cockroachdb/cockroach/storage.(*Replica).executeWriteBatch(0xc42107a480, 0x7f32c34448a0, 0xc4210880f0, 0xc420d50f88, 0x8, 0x14743d64e6545738, 0x0, 0x0, 0x0, 0x859, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2703 +0x256
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommandInBatch(0xc42107a480, 0x7f32c34448a0, 0xc4210880f0, 0xc420d50f88, 0x8, 0x300000003, 0xc400000009, 0x14743d64e6545738, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2619 +0xf5
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommand(0xc42107a480, 0xc420d50f88, 0x8, 0x7f32c34448a0, 0xc4210880f0, 0x4fd0, 0x2ac2, 0x300000003, 0x9, 0x14743d64e6545738, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2522 +0xc1f
github.com/cockroachdb/cockroach/storage.(*Replica).processRaftCommand(0xc42107a480, 0xc420d50f88, 0x8, 0x4fd0, 0x859, 0x300000003, 0x9, 0x14743d64e6545738, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:2438 +0x3d9
github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady(0xc42107a480, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1904 +0xa20
github.com/cockroachdb/cockroach/storage.(*Store).processReady(0xc420175680, 0x859)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2617 +0x14d
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc4203a1260, 0xc4204c0900)
        /go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:197 +0x428
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
        /go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x4b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc4204c0900, 0xc42034c340)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x74
```
