### ISSUE TITLE
cdc: TestAvroSchema is flakey

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#93514]
```
=== RUN   TestAvroSchema/NULLABLE
    --- FAIL: TestAvroSchema/NULLABLE (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17ec586]

goroutine 4514 [running]:
testing.tRunner.func1.2({0x4e944e0, 0x98cb540})
	GOROOT/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1399 +0x39f
panic({0x4e944e0, 0x98cb540})
	GOROOT/src/runtime/panic.go:884 +0x212
github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.MakeColumnDefDescs({0x6bc7a88, 0xc000080038}, 0xc004c0bba0, 0xc002fe90a0, 0xc004170a00)
	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/table.go:154 +0x306
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.avroFieldMetadataToColDesc({0xc00473a440?, 0xca?})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/avro_test.go:178 +0x20f
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.parseAvroSchema(0x6ba2b10?, {0xc0066732b0, 0xca})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/avro_test.go:148 +0x1a5
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestAvroSchema.func3(0x10a8c20?)
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/avro_test.go:395 +0x249
testing.tRunner(0xc004c0b520, 0xc000a98650)
	GOROOT/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:1493 +0x35f
```

Build: <https://teamcity.cockroachdb.com/viewLog.html?buildId=7935801&buildTypeId=Cockroach_UnitTests_BazelUnitTests>

Jira issue: CRDB-22374

Epic CRDB-11732

**Comment by miretskiy** [comment]
were you able to repro, @HonoreDB ?
