### ISSUE TITLE
bazci: panic while handling build event

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#93522]
```
[Run unit tests] FAILED: Build did NOT complete successfully
[Run unit tests] panic: runtime error: invalid memory address or nil pointer dereference
[Run unit tests] [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xadc345]
[Run unit tests] 
[Run unit tests] goroutine 36 [running]:
[Run unit tests] main.(*monitorBuildServer).handleBuildEvent(0xc000038960, {0xc000296940?, 0xc000317b40?}, 0xc00014d3e0)
[Run unit tests] 	main/pkg/cmd/bazci/bazci.go:213 +0x705
[Run unit tests] main.(*monitorBuildServer).PublishBuildToolEventStream(0xc000317b80?, {0xd92f50, 0xc000321140})
[Run unit tests] 	main/pkg/cmd/bazci/bazci.go:154 +0xaa
[Run unit tests] google.golang.org/genproto/googleapis/devtools/build/v1._PublishBuildEvent_PublishBuildToolEventStream_Handler({0xbd4780?, 0xc000038960}, {0xd91708?, 0xc00032a5b0})
[Run unit tests] 	google.golang.org/genproto/googleapis/devtools/build/v1/bazel-out/k8-fastbuild/bin/external/go_googleapis/google/devtools/build/v1/build_go_proto_/google.golang.org/genproto/googleapis/devtools/build/v1/publish_build_event.pb.go:816 +0x9f
[Run unit tests] google.golang.org/grpc.(*Server).processStreamingRPC(0xc00023afc0, {0xd93398, 0xc0001d3ba0}, 0xc000338480, 0xc000254390, 0x127d3a0, 0x0)
[Run unit tests] 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1542 +0xf5c
[Run unit tests] google.golang.org/grpc.(*Server).handleStream(0xc00023afc0, {0xd93398, 0xc0001d3ba0}, 0xc000338480, 0x0)
[Run unit tests] 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1624 +0x9ea
[Run unit tests] google.golang.org/grpc.(*Server).serveStreams.func1.2()
[Run unit tests] 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:922 +0x98
[Run unit tests] created by google.golang.org/grpc.(*Server).serveStreams.func1
[Run unit tests] 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:920 +0x28a
[Run unit tests] Process exited with code 2
```

Build: <https://teamcity.cockroachdb.com/viewLog.html?buildId=7944996&buildTypeId=Cockroach_UnitTests_BazelUnitTests>

Jira issue: CRDB-22378

**Comment by knz** [comment]
another one in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/7946969?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true
