### ISSUE TITLE
bazci: another panic while handling build event

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#93656]
```
[Run unit tests] FAILED: Build did NOT complete successfully
[Run unit tests] panic: runtime error: invalid memory address or nil pointer dereference
[Run unit tests] [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xadc58a]
[Run unit tests] 
[Run unit tests] goroutine 5 [running]:
[Run unit tests] main.(*monitorBuildServer).handleBuildEvent(0xc0001a0900, {0x0?, 0xc0000b6b40?}, 0xc0001a10e0)
[Run unit tests] 	main/pkg/cmd/bazci/bazci.go:219 +0x94a
[Run unit tests] main.(*monitorBuildServer).PublishBuildToolEventStream(0xc0000b6b80?, {0xd92f50, 0xc0000b8270})
[Run unit tests] 	main/pkg/cmd/bazci/bazci.go:154 +0xaa
[Run unit tests] google.golang.org/genproto/googleapis/devtools/build/v1._PublishBuildEvent_PublishBuildToolEventStream_Handler({0xbd4780?, 0xc0001a0900}, {0xd91708?, 0xc0000e40d0})
[Run unit tests] 	google.golang.org/genproto/googleapis/devtools/build/v1/bazel-out/k8-fastbuild/bin/external/go_googleapis/google/devtools/build/v1/build_go_proto_/google.golang.org/genproto/googleapis/devtools/build/v1/publish_build_event.pb.go:816 +0x9f
[Run unit tests] google.golang.org/grpc.(*Server).processStreamingRPC(0xc00029afc0, {0xd93398, 0xc0002e4680}, 0xc0000ea240, 0xc0002e8390, 0x127d3a0, 0x0)
[Run unit tests] 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1542 +0xf5c
[Run unit tests] google.golang.org/grpc.(*Server).handleStream(0xc00029afc0, {0xd93398, 0xc0002e4680}, 0xc0000ea240, 0x0)
[Run unit tests] 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1624 +0x9ea
[Run unit tests] google.golang.org/grpc.(*Server).serveStreams.func1.2()
[Run unit tests] 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:922 +0x98
[Run unit tests] created by google.golang.org/grpc.(*Server).serveStreams.func1
[Run unit tests] 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:920 +0x28a
[Run unit tests] Process exited with code 2
```

Build: <https://teamcity.cockroachdb.com/viewLog.html?buildId=7966525&buildTypeId=Cockroach_UnitTests_BazelUnitTests>.

Related: #93522.

Jira issue: CRDB-22451

**Comment by renatolabs** [comment]
More occurrences:

* <https://teamcity.cockroachdb.com/viewLog.html?buildId=7983059&buildTypeId=Cockroach_UnitTests_BazelUnitTests>
* <https://teamcity.cockroachdb.com/viewLog.html?buildId=7983501&buildTypeId=Cockroach_UnitTests_BazelUnitTests>
