### ISSUE TITLE
ccl/streamingccl: TestStreamDeleteRange is flakey

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#93752]
It times out frequently in CI. Example build: <https://teamcity.cockroachdb.com/viewLog.html?buildId=7979325&buildTypeId=Cockroach_UnitTests_BazelUnitTests>.

```
=== RUN   TestStreamDeleteRange
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/9ce24496530642208197dda818d65c9e/logTestStreamDeleteRange1059698972
    test_log_scope.go:79: use -show-logs to present logs inline
panic: test timed out after 4m55s

goroutine 34875 [running]:
...
```

cc @cockroachdb/tenant-streaming 

Jira issue: CRDB-22513

**Comment by yuzefovich** [comment]
dup of #93568
