### ISSUE TITLE
TestStoreRangeUpReplicate testrace failure

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#9402]
https://teamcity.cockroachdb.com/viewLog.html?buildId=22328&buildTypeId=Cockroach_UnitTests

```
panic: [n3,s3]: not connected to gossip [recovered]
    panic: [n3,s3]: not connected to gossip [recovered]
    panic: [n3,s3]: not connected to gossip

goroutine 8362 [running]:
panic(0x1b66a80, 0xc4204e8e30)
    /usr/local/go/src/runtime/panic.go:500 +0x1ae
testing.tRunner.func1(0xc420d9a000)
    /usr/local/go/src/testing/testing.go:579 +0x474
panic(0x1b66a80, 0xc4204e8e30)
    /usr/local/go/src/runtime/panic.go:458 +0x271
github.com/cockroachdb/cockroach/util/leaktest.AfterTest.func1()
    /go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:72 +0x53e
panic(0x1b66a80, 0xc4204e8e30)
    /usr/local/go/src/runtime/panic.go:458 +0x271
github.com/cockroachdb/cockroach/storage.(*Store).GossipStore(0xc420234b00, 0x7f62b9881000, 0xc42008e428, 0x7f62b9881000, 0xc42008e428)
    /go/src/github.com/cockroachdb/cockroach/storage/store.go:1147 +0x6b7
github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).gossipStores(0xc4203bc000)
    /go/src/github.com/cockroachdb/cockroach/storage/client_test.go:365 +0x1e3
github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).initGossipNetwork(0xc4203bc000)
    /go/src/github.com/cockroachdb/cockroach/storage/client_test.go:394 +0x46
github.com/cockroachdb/cockroach/storage_test.TestStoreRangeUpReplicate(0xc420d9a000)
    /go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:720 +0xbb
```

**Comment by tamird** [comment]
ref?

**Comment by RaduBerinde** [comment]
Happened with #9400, so `develop` plus a few commits from `master`.

**Comment by tamird** [comment]
Fixed in https://github.com/cockroachdb/cockroach/pull/9693.
