### ISSUE TITLE
bazel: make generate-bazel-extra more resilient with custom symlink

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#94162]
I have the following `build --symlink_prefix=bazel-` in `.bazelrc.user`, and because of this `./dev gen bazel` fails for me with
```
Target //pkg/cmd/generate-bazel-extra:generate-bazel-extra up-to-date:
  bazel-bin/pkg/cmd/generate-bazel-extra/generate-bazel-extra_/generate-bazel-extra
INFO: Elapsed time: 0.687s, Critical Path: 0.16s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: /bin/bash -c 'cd /Users/yuzefovich/go/src/github.com/cockroachdb/cockroach &&  bazel-bin/pkg/cmd/generate-bazel-extra/generaINFO: Build completed successfully, 1 total action
failed to run buildozer, got output: panic: fork/exec _bazel/bin/external/com_github_bazelbuild_buildtools/buildozer/buildozer_/buildozer: no such file or directory

goroutine 1 [running]:
main.runBuildozer({0x14000264000?, 0x14000264010?, 0x1400006cd58?})
	main/pkg/cmd/generate-bazel-extra/main.go:47 +0x130
main.generateTestSuites()
	main/pkg/cmd/generate-bazel-extra/main.go:263 +0x828
main.main()
	main/pkg/cmd/generate-bazel-extra/main.go:340 +0xe8
ERROR: exit status 2
```
IIRC I overriden the symlink prefix in order to be able to view source code of the CPU profiles, so it'd be nice to make `generate-bazel-extra` resilient to such setup.

**Comment by rickystewart** [comment]
The problem is that `generate-bazel-extra` [assumes](https://github.com/cockroachdb/cockroach/blob/b9f3f15e999387dc9696fbfabd73cb2784877465/pkg/cmd/generate-bazel-extra/main.go#L44) `buildozer` can be found at `_bazel/bin/external/com_github_bazelbuild_buildtools/buildozer/buildozer_/buildozer` -- not true in the case of a custom symlink as you've said.

However, the binary can definitely be found *relative to wherever `generate-bazel-extra` is*. Apparently it should be at `....../generate-bazel-extra/../../../../external/com_github_bazelbuild_buildtools/buildozer/buildozer_/buildozer` (or something similar).
