### ISSUE TITLE
circleci: failed tests: TestDockerPHP 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9437]
The following test appears to have failed:

[#22901](https://circleci.com/gh/cockroachdb/cockroach/22901):

```
error: Error response from daemon: Conflict. The name "/roach-cdf0dce0-0" is already in use by container acbf548143718c4e9256c76be3ee3c57fa5bb4306239de5a7582c64d68b5931b. You have to remove (or rename) that container to be able to reuse that name.
containers: [{ID:5476aad95a9145102f93a4c1b3c63375eb53f129ca2adc4fa3ad51ab0ad16c34 Names:[/volumes-cdf0dce0] Image:cockroachdb/builder:20160912-171706 ImageID:sha256:55f4108ed76ee93060c83f19e490d0bea9de474b21ff524304af8d0686fa63b3 Command:/bin/true Created:1474087583 Ports:[] SizeRw:0 SizeRootFs:0 Labels:map[] State: Status:Exited (0) 10 seconds ago HostConfig:{NetworkMode:ac2e6da78a2609538565d8b6ad968fa671110abdf568f9f77db699635c80063b} NetworkSettings:0xc420112690 Mounts:[]} {ID:85ee6c57dd834e11d204c1f210a3ba579575cc1306dcd8062be2193cee97ec1e Names:[/backstabbing_rosalind] Image:cockroachdb/builder:20160912-171706 ImageID:sha256:55f4108ed76ee93060c83f19e490d0bea9de474b21ff524304af8d0686fa63b3 Command:make test 'TESTFLAGS=-v --verbosity=1 --vmodule=monitor=2,tracer=2' Created:1474087220 Ports:[] SizeRw:0 SizeRootFs:0 Labels:map[] State: Status:Exited (0) 2 minutes ago HostConfig:{NetworkMode:default} NetworkSettings:0xc4201126a0 Mounts:[]} {ID:5f378e8355e0776a2eef8154ab540c28294c61868575435eb73932416229de78 Names:[/hungry_mcclintock] Image:cockroachdb/builder:20160912-171706 ImageID:sha256:55f4108ed76ee93060c83f19e490d0bea9de474b21ff524304af8d0686fa63b3 Command:build/circle-deps.sh docker Created:1474087112 Ports:[] SizeRw:0 SizeRootFs:0 Labels:map[] State: Status:Exited (0) 6 minutes ago HostConfig:{NetworkMode:default} NetworkSettings:0xc4201126b0 Mounts:[]}]
I160917 04:46:34.255371 1798 acceptance/cluster/localcluster.go:700  stopping
I160917 04:46:34.255494 1808 acceptance/cluster/localcluster.go:600  event stream done, resetting...: net/http: request canceled
I160917 04:46:34.255523 1808 acceptance/cluster/localcluster.go:623  events monitor exits
--- FAIL: TestDockerPHP (10.76s)
panic: ContainerCreate: exceeded 10 tries with a 10s timeout [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6ed9fc]

goroutine 1798 [running]:
panic(0x1369700, 0xc420018100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc427074300)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x1369700, 0xc420018100)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).expectEvent(0xc420326200, 0xc4204509f0, 0xc424fb80a0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:192 +0x5c
github.com/cockroachdb/cockroach/acceptance/cluster.(*Container).Kill(0xc4204509f0, 0x15ce5d8, 0xc420326218)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/docker.go:175 +0x106
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).stop(0xc420326200)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:711 +0xa52
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).stopOnPanic(0xc420326200)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:248 +0x60
panic(0x134d8a0, 0xc4201adce0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/acceptance/cluster.maybePanic(0x1d58de0, 0xc4201adce0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/docker.go:154 +0x5c
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).createRoach(0xc420326200, 0xc4270cb260, 0xc4204509f0, 0xc42024e9c0, 0x3, 0x3, 0xc420134380, 0xb, 0xe)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:442 +0x6fc
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).startNode(0xc420326200, 0xc4270cb260)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:510 +0x5b4
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start(0xc420326200)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:647 +0x5b8
github.com/cockroachdb/cockroach/acceptance.StartCluster(0xc427074300, 0x148715d, 0x3, 0xc420198320, 0x1, 0x1, 0x12a05f200, 0x0, 0x0)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Docker flake.
