### ISSUE TITLE
Failed tests (22989): TestRollbackInRestartWait

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9483]
Found in https://circleci.com/gh/cockroachdb/cockroach/22989:

```
I160921 15:12:52.718951 23798 kv/txn_coord_sender.go:251  [n1] txn coordinator: 2.74 txn/sec, 100.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 58ms/19ms/80ms avg/σ/max duration, 0.6/0.5/1 avg/σ/max restarts (5 samples)
I160921 15:12:52.752222 23860 server/status/runtime.go:207  runtime stats: 910 MiB RSS, 57 goroutines, 19 MiB/126 MiB/163 MiB GO alloc/idle/total, 25 MiB/38 MiB CGO alloc/total, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (764x)
I160921 15:12:54.975266 23869 rpc/clock_offset.go:151  [n1] 1 of 1 nodes are within the maximum offset of 50ms
I160921 15:12:57.736704 23798 kv/txn_coord_sender.go:251  [n1] txn coordinator: 1.97 txn/sec, 100.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 58ms/19ms/80ms avg/σ/max duration, 0.6/0.5/1 avg/σ/max restarts (5 samples)
I160921 15:12:57.977492 23869 rpc/clock_offset.go:151  [n1] 1 of 1 nodes are within the maximum offset of 50ms
panic: test timed out after 8m0s

goroutine 23896 [running]:
panic(0x1b48960, 0xc427c052a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:918 +0x14e
created by time.goFunc
	/usr/local/go/src/time/sleep.go:154 +0x78

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420087bc0, 0x1d0ea90, 0x19, 0x2043b00, 0x94e301)
	/usr/local/go/src/testing/testing.go:647 +0x56e
testing.RunTests.func1(0xc420087bc0)
	/usr/local/go/src/testing/testing.go:793 +0xba
testing.tRunner(0xc420087bc0, 0xc420091d68)
	/usr/local/go/src/testing/testing.go:610 +0xca
testing.RunTests(0x2045040, 0x298dde0, 0x77, 0x77, 0x0)
	/usr/local/go/src/testing/testing.go:799 +0x4bb
testing.(*M).Run(0xc420091ef0, 0x36ae600)
	/usr/local/go/src/testing/testing.go:743 +0x130
github.com/cockroachdb/cockroach/sql_test.TestMain(0xc420091ef0)
	/go/src/github.com/cockroachdb/cockroach/sql/main_test.go:199 +0x13a
main.main()
	github.com/cockroachdb/cockroach/sql/_test/_testmain.go:666 +0x1b6

goroutine 17 [syscall, 7 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 4 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2cf2640)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:996 +0x85
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:577 +0xc3

goroutine 23862 [select]:
github.com/cockroachdb/cockroach/server.(*Node).startWriteSummaries.func1()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:667 +0x32d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420187830, 0xc4210dce60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:191 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:192 +0x74

goroutine 23810 [select]:
github.com/cockroachdb/cockroach/sql.(*LeaseManager).RefreshLeases.func1()
	/go/src/github.com/cockroachdb/cockroach/sql/lease.go:1144 +0x1204
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420187830, 0xc427642ed0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:191 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:192 +0x74

goroutine 23803 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc420054540, 0xc420187830)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x550
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x4b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420187830, 0xc420011ee0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:191 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:192 +0x74

goroutine 23824 [select]:
github.com/cockroachdb/cockroach/storage.(*bookie).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/reservation.go:274 +0x4c8
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420187830, 0xc4243d3f00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:191 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:192 +0x74

goroutine 23855 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:440 +0x395
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420187830, 0xc4210dcce0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:191 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:192 +0x74

goroutine 23799 [select]:
github.com/cockroachdb/cockroach/storage.NewRaftTransport.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/raft_transport.go:182 +0x12f6
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420187830, 0xc424781f80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:191 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:192 +0x74

goroutine 23839 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc4272227e0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:673 +0xa56
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:139 +0xa91

goroutine 23821 [chan receive]:
github.com/cockroachdb/cockroach/gossip.(*server).start.func3()
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:370 +0x94
```

**Comment by tamird** [comment]
Another unlucky timeout (nothing to do with this test specifically). Closing after 36569 runs on GCE.
