### ISSUE TITLE
sql: TestLogic_testserver_test_22_1_22_2  flaked due to empty conn string (master, x86 build)

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#94871]
See flake[ here](https://teamcity.cockroachdb.com/viewLog.html?buildId=8222053&buildTypeId=Cockroach_BazelEssentialCi). 

Stack trace: 
```
No pass/skip/fail event found for test
=== RUN   TestLogic_testserver_test_22_1_22_2
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/a0cd2ed7268f1ad03abb8f1d57f5fcc9/logTestLogic_testserver_test_22_1_22_22661895086
    test_log_scope.go:79: use -show-logs to present logs inline
panic: empty connection string

goroutine 94 [running]:
github.com/cockroachdb/cockroach-go/v2/testserver.(*testServerImpl).pollListeningURLFile(0xc0002fc900, 0x0)
	github.com/cockroachdb/cockroach-go/v2/testserver/external/com_github_cockroachdb_cockroach_go_v2/testserver/testserver.go:722 +0x765
github.com/cockroachdb/cockroach-go/v2/testserver.(*testServerImpl).StartNode.func1()
	github.com/cockroachdb/cockroach-go/v2/testserver/external/com_github_cockroachdb_cockroach_go_v2/testserver/testservernode.go:108 +0x2f
created by github.com/cockroachdb/cockroach-go/v2/testserver.(*testServerImpl).StartNode
	github.com/cockroachdb/cockroach-go/v2/testserver/external/com_github_cockroachdb_cockroach_go_v2/testserver/testservernode.go:107 +0xcbb
```

Jira issue: CRDB-23194

**Comment by msbutler** [comment]
another[ one ](https://teamcity.cockroachdb.com/viewLog.html?buildId=8246236&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests#testNameId2967917534255592156).

Going to open a PR to skip.
