### ISSUE TITLE
build: infra flake in the bench CI target

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#94988]
Found here https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_Bench/8261989?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true

```
[11:25:51]W:		 [Run benchmark tests]   /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
[11:25:51]W:		 [Run benchmark tests] Repository rule yarn_install defined at:
[11:25:51]W:		 [Run benchmark tests]   /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:977:31: in <toplevel>
[11:25:51]W:		 [Run benchmark tests] ERROR: An error occurred during the fetch of repository 'npm_db_console':
[11:25:51]W:		 [Run benchmark tests]    Traceback (most recent call last):
[11:25:51]W:		 [Run benchmark tests] 	File "/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 973, column 24, in _yarn_install_impl
[11:25:51]W:		 [Run benchmark tests] 		_create_build_files(repository_ctx, "yarn_install", node, repository_ctx.attr.yarn_lock, repository_ctx.attr.generate_local_modules_build_files)
[11:25:51]W:		 [Run benchmark tests] 	File "/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 487, column 13, in _create_build_files
[11:25:51]W:		 [Run benchmark tests] 		fail("generate_build_file.ts failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (result.stdout, result.stderr))
[11:25:51]W:		 [Run benchmark tests] Error in fail: generate_build_file.ts failed: 
[11:25:51]W:		 [Run benchmark tests] STDOUT:
[11:25:51]W:		 [Run benchmark tests] 
[11:25:51]W:		 [Run benchmark tests] STDERR:
[11:25:51]W:		 [Run benchmark tests] node:internal/process/promises:246
[11:25:51]W:		 [Run benchmark tests]           triggerUncaughtException(err, true /* fromPromise */);
[11:25:51]W:		 [Run benchmark tests]           ^
[11:25:51]W:		 [Run benchmark tests] 
[11:25:51]W:		 [Run benchmark tests] [Error: ENOENT: no such file or directory, unlink '_/pkg/ui/workspaces/db-console/node_modules/@cockroachlabs/eslint-plugin-crdb/node_modules/@babel/core/node_modules/.bin/parser'] {
[11:25:51]W:		 [Run benchmark tests]   errno: -2,
[11:25:51]W:		 [Run benchmark tests]   code: 'ENOENT',
[11:25:51]W:		 [Run benchmark tests]   syscall: 'unlink',
[11:25:51]W:		 [Run benchmark tests]   path: '_/pkg/ui/workspaces/db-console/node_modules/@cockroachlabs/eslint-plugin-crdb/node_modules/@babel/core/node_modules/.bin/parser'
[11:25:51]W:		 [Run benchmark tests] }
[11:25:51]W:		 [Run benchmark tests] ERROR: /go/src/github.com/cockroachdb/cockroach/WORKSPACE:310:13: fetching yarn_install rule //external:npm_db_console: Traceback (most recent call last):
[11:25:51]W:		 [Run benchmark tests] 	File "/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 973, column 24, in _yarn_install_impl
```

Jira issue: CRDB-23261

**Comment by rickystewart** [comment]
Irrelevant after #103967
