### ISSUE TITLE
circleci: failed tests: TestValidateCrossTableReferences 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9539]
The following test appears to have failed:

[#23084](https://circleci.com/gh/cockroachdb/cockroach/23084):

```
I160926 15:30:16.109765 14 rpc/context.go:181  [n1] closing 127.0.0.1:53724
I160926 15:30:16.110055 78 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: connection error: desc = "transport: context canceled"
I160926 15:30:16.110420 80 kv/transport_race.go:74  transport race promotion: ran 18 iterations on up to 184 requests
I160926 15:30:16.110662 81 rpc/context.go:181  [n1] closing 127.0.0.1:53724
I160926 15:30:16.124692 31 storage/engine/rocksdb.go:404  closing in-memory rocksdb instance
--- FAIL: TestValidateCrossTableReferences (6.82s)
	<autogenerated>:10: Leaked goroutine: goroutine 120 [runnable]:
		math/big.nat.montgomery(0xc4200832c0, 0x10, 0x26, 0xc4205feea0, 0x10, 0x24, 0xc4205feea0, 0x10, 0x24, 0xc42015c580, ...)
			/usr/local/go/src/math/big/nat.go:227 +0x25c
		math/big.nat.expNNMontgomery(0xc4205feea0, 0x10, 0x26, 0xc420779200, 0x10, 0x25, 0xc420146780, 0x10, 0x25, 0xc42015c580, ...)
			/usr/local/go/src/math/big/nat.go:1141 +0x986
		math/big.nat.expNN(0x0, 0x0, 0x0, 0xc420779200, 0x20, 0x45, 0xc420146780, 0x10, 0x25, 0xc42015c580, ...)
			/usr/local/go/src/math/big/nat.go:955 +0xb5a
		math/big.(*Int).Exp(0xc42044cfd8, 0xc42044cff8, 0xc420225e40, 0xc420225ce0, 0xc420631ac0)
			/usr/local/go/src/math/big/int.go:420 +0x17d
		crypto/rsa.decrypt(0x2663d00, 0xc420016660, 0xc42013d4a0, 0xc42044cff8, 0x0, 0xc4208c4500, 0x100)
--
--- PASS: TestFitColumnToFamily (0.00s)
=== RUN   TestMaybeUpgradeFormatVersion
--- PASS: TestMaybeUpgradeFormatVersion (0.00s)
=== RUN   TestIndexKey
--- PASS: TestIndexKey (0.41s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql/sqlbase	7.563s
?   	github.com/cockroachdb/cockroach/sql/sqlutil	[no test files]
I160926 15:30:52.738514 1 rand.go:76  Random seed: 865872024273751812
=== RUN   TestAbortCachePutGetClearData
I160926 15:30:52.755343 6 storage/engine/rocksdb.go:356  opening in memory rocksdb instance
I160926 15:30:52.758615 6 storage/engine/rocksdb.go:404  closing in-memory rocksdb instance
--- PASS: TestAbortCachePutGetClearData (0.03s)
=== RUN   TestAbortCacheEmptyParams
I160926 15:30:52.776214 23 storage/engine/rocksdb.go:356  opening in memory rocksdb instance
I160926 15:30:52.777772 23 storage/engine/rocksdb.go:404  closing in-memory rocksdb instance
--- PASS: TestAbortCacheEmptyParams (0.02s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Looks like an (extremely?) slow machine - the leaked goroutine is in math/big, so it's likely just in the process of shutting down.
