### ISSUE TITLE
cli: readline lock-up upon reading nul bytes

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9607]
repro:
```
printf 'select 1; --- \x00' | ./cockroach sql
```

Many times in a row. It doesn't lock up deterministically.

**Comment by knz** [comment]
When the process hangs the goroutine report looks like this:
```
goroutine 0 [idle]:
runtime.futex(0x24a5df8, 0x0, 0x7f54bc1feb48, 0x0, 0x7f5400000000, 0x626546, 0x3c, 0x0, 0x7f54bc1feb90, 0x5d5b1b, ...)
        /mnt/kena/go1.7.1/src/runtime/sys_linux_amd64.s:388 +0x23
runtime.futexsleep(0x24a5df8, 0x7f5400000000, 0xdf8475800)
        /mnt/kena/go1.7.1/src/runtime/os_linux.go:62 +0xd7
runtime.notetsleep_internal(0x24a5df8, 0xdf8475800, 0x1)
        /mnt/kena/go1.7.1/src/runtime/lock_futex.go:174 +0xeb
runtime.notetsleep(0x24a5df8, 0xdf8475800, 0x7b84cdd9b75e5)
        /mnt/kena/go1.7.1/src/runtime/lock_futex.go:194 +0x56
runtime.sysmon()
        /mnt/kena/go1.7.1/src/runtime/proc.go:3618 +0x14c
runtime.mstart1()
        /mnt/kena/go1.7.1/src/runtime/proc.go:1126 +0x11e
runtime.mstart()
        /mnt/kena/go1.7.1/src/runtime/proc.go:1096 +0x64

goroutine 1 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc4203140d4)
        /mnt/kena/go1.7.1/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc4203140c8)
        /mnt/kena/go1.7.1/src/sync/waitgroup.go:131 +0x97
github.com/chzyer/readline.(*Terminal).Close(0xc4203140a0, 0xc420028c00, 0xc4200001a0)
        /mnt/kena/go/src/github.com/chzyer/readline/terminal.go:205 +0xcc
github.com/chzyer/readline.(*Instance).Close(0xc4204a8480, 0x61c260, 0xc4204aa380)
        /mnt/kena/go/src/github.com/chzyer/readline/readline.go:252 +0x2f
github.com/cockroachdb/cockroach/cli.runInteractive.func1(0xc4204a8480)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/cli/sql.go:309 +0x2b
github.com/cockroachdb/cockroach/cli.runInteractive(0xc4200159b0, 0xc42027d500, 0x2146540, 0xc4200119b0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/cli/sql.go:406 +0xfdd
github.com/cockroachdb/cockroach/cli.runTerm(0x213bd60, 0x24e2a98, 0x0, 0x0, 0x0, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/cli/sql.go:517 +0x207
github.com/spf13/cobra.(*Command).execute(0x213bd60, 0x24e2a98, 0x0, 0x0, 0x213bd60, 0x24e2a98)
        /mnt/kena/go/src/github.com/spf13/cobra/command.go:599 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0x2137b80, 0xc42000c3a0, 0x16ee2f2c21ae5546, 0xc42000c3d8)
        /mnt/kena/go/src/github.com/spf13/cobra/command.go:689 +0x367
github.com/spf13/cobra.(*Command).Execute(0x2137b80, 0xc42000c3c0, 0x16ee2f2c21ae5546)
        /mnt/kena/go/src/github.com/spf13/cobra/command.go:648 +0x2b
github.com/cockroachdb/cockroach/cli.Run(0xc42000c390, 0x1, 0x1, 0x0, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/cli/cli.go:95 +0x6d
main.main()
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/main.go:37 +0xe1

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
        /mnt/kena/go1.7.1/src/runtime/asm_amd64.s:2086 +0x1

goroutine 8 [chan send, 3 minutes]:
github.com/chzyer/readline.(*CancelableStdin).Read(0xc42014e180, 0xc420414000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /mnt/kena/go/src/github.com/chzyer/readline/std.go:106 +0x106
bufio.(*Reader).fill(0xc420035e68)
        /mnt/kena/go1.7.1/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadRune(0xc420035e68, 0xc42014e2a0, 0xc420035e18, 0x0, 0x0)
        /mnt/kena/go1.7.1/src/bufio/bufio.go:262 +0xad
github.com/chzyer/readline.(*Terminal).ioloop(0xc4203140a0)
        /mnt/kena/go/src/github.com/chzyer/readline/terminal.go:136 +0x116
created by github.com/chzyer/readline.NewTerminal
goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x24a5c40)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:998 +0x77
created by github.com/cockroachdb/cockroach/util/log.init.1
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:579 +0x95

goroutine 20 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
        /mnt/kena/go1.7.1/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /mnt/kena/go1.7.1/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /mnt/kena/go1.7.1/src/os/signal/signal_unix.go:28 +0x41

goroutine 9 [select, 3 minutes, locked to thread]:
runtime.gopark(0x18d2bd0, 0x0, 0x1736611, 0x6, 0x18, 0x2)
        /mnt/kena/go1.7.1/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42017f730, 0x0, 0x18)
        /mnt/kena/go1.7.1/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc42017f730)
        /mnt/kena/go1.7.1/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /mnt/kena/go1.7.1/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
        /mnt/kena/go1.7.1/src/runtime/asm_amd64.s:2086 +0x1

goroutine 10 [chan receive, 3 minutes]:
github.com/chzyer/readline.DefaultOnWidthChanged.func1.1(0xc42014e600)
        /mnt/kena/go/src/github.com/chzyer/readline/utils_unix.go:82 +0x53
created by github.com/chzyer/readline.DefaultOnWidthChanged.func1
        /mnt/kena/go/src/github.com/chzyer/readline/utils_unix.go:88 +0xec

goroutine 11 [chan receive, 3 minutes]:
github.com/chzyer/readline.(*Operation).ioloop(0xc42014e5a0)
        /mnt/kena/go/src/github.com/chzyer/readline/operation.go:98 +0x61
created by github.com/chzyer/readline.NewOperation
        /mnt/kena/go/src/github.com/chzyer/readline/operation.go:82 +0x3f0
```

In short: there's a deadlock situation in readline.

@chzyer care to chime in?

**Comment by chzyer** [comment]
@knz 
Hi, I can't repro this situation.
All of follows are works well.
```
printf 'select 1; --- \x00' | cockroach sql # on mac
# go install github.com/chzyer/readline/example/readline-demo
printf 'select 1; --- \x00' |  readline-demo # on mac/linux
```
Can you test `readline-demo` in your environment ?

**Comment by knz** [comment]
Yes with `readline-demo` I can reproduce the problem easily. Simply try the following multiple times:

```
printf 'bye\x00` | readline-demo
```

hangs in the same place.

**Comment by knz** [comment]
(The problem occurs when the program exits after reading some nul byte apparently.)

**Comment by knz** [comment]
After merging https://github.com/chzyer/readline/pull/89 the issue seems to have been fixed. Thank you @chzyer :)
