### ISSUE TITLE
stability: rho is stalled

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#9778]
After Tamir pushed rho yesterday, it seems to have run for a bit and then traffic went to 2 selects / 5 inserts per sec.
Most workers in the raft pool are blocked on the scheduler mutex, so there's contention there, but unclear why. They're not blocked for a full minute (the point where we'd see that in the goroutine stack profiles).  

```
8: semacquire [Created by stop.(*Stopper).RunWorker @ stopper.go:192]
    sync           sema.go:47                 runtime_Semacquire(#214)
    sync           mutex.go:85                (*Mutex).Lock(#213)
    storage        scheduler.go:208           (*raftScheduler).worker(#212, #240)
    storage        scheduler.go:160           (*raftScheduler).Start.func1()
    stop           stopper.go:191             (*Stopper).RunWorker.func1(#240, *)
```

I'm gonna enable lightstep in the hope that it will show something.

cc @tschottdorf @cockroachdb/stability

**Comment by tamird** [comment]
Possibly a dupe of https://github.com/cockroachdb/cockroach/issues/9533.

**Comment by tschottdorf** [comment]
#9533 is more about periodic crashes, but your [latest post there](https://github.com/cockroachdb/cockroach/issues/9533#issuecomment-251864792) contains relevant screenshots.

**Comment by andreimatei** [comment]
One interesting thing is that restarting photos helped, and throughput returned to 3/4 of what it once was. I'm seeing various mutex contention as in #9749, so I'll redeploy with Tobi's replica visitor fix (https://github.com/cockroachdb/cockroach/commit/7303bdf5e075f957e694baf595508a3d0419a00f) and see if we do better.

We seem to have the same kind of long replica mutex held by the command queue as we saw in #9749.
```
W161006 19:13:46.507498 14417 util/syncutil/timedmutex.go:85  [n5,s5,r1811:/System/tsd/cr.node.sql.txn.…] mutex held for 3.97633488s (>500ms):
goroutine 14417 [running]:
runtime/debug.Stack(0x2db1920, 0x1fa3bdb4, 0x2db4680)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x87
github.com/cockroachdb/cockroach/util/syncutil.(*TimedMutex).Unlock(0xc420869920)
        /go/src/github.com/cockroachdb/cockroach/util/syncutil/timedmutex.go:84 +0x17a
github.com/cockroachdb/cockroach/storage.(*Replica).beginCmds(0xc420869880, 0x7fdc4fadb160, 0xc4252a84e0, 0xc42390ad90, 0xc4235d9680, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1167 +0x463
github.com/cockroachdb/cockroach/storage.(*Replica).addWriteCmd(0xc420869880, 0x7fdc4fadb160, 0xc4252a84e0, 0x147b0733ef1c18db, 0x0, 0x500000005, 0x12, 0x713, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1511 +0x7d6
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc420869880, 0x7fdc4fadb160, 0xc4252a84e0, 0x147b0733ef1c18db, 0x0, 0x500000005, 0x12, 0x713, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1075 +0x2a5
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc420344000, 0x7fdc4fadb160, 0xc4252a8330, 0x147b0733ef1c18db, 0x0, 0x500000005, 0x12, 0x713, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2108 +0x8e2
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc420410550, 0x7fdc4fadb160, 0xc4252a8150, 0x0, 0x0, 0x500000005, 0x12, 0x713, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/stores.go:186 +0x24b
github.com/cockroachdb/cockroach/server.(*Node).Batch.func3()
        /go/src/github.com/cockroachdb/cockroach/server/node.go:837 +0x36a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc420394000, 0xc425a35770, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:219 +0x10e
github.com/cockroachdb/cockroach/server.(*Node).Batch(0xc420196000, 0x7fdc4fadb160, 0xc4252a8090, 0xc42390aa10, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/server/node.go:849 +0x31c
github.com/cockroachdb/cockroach/roachpb._Internal_Batch_Handler(0x1d86900, 0xc420196000, 0x7fdc4fadb160, 0xc4257a9380, 0xc42475ea50, 0x0, 0x0, 0x0, 0xc4278af0a4, 0x0)
        /go/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:1537 +0x346
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420427540, 0x2a71920, 0xc4203ceab0, 0xc422015c20, 0xc4201f65d0, 0x2a35690, 0x0, 0x0, 0x0)
        /go/src/google.golang.org/grpc/server.go:611 +0x10b7
google.golang.org/grpc.(*Server).handleStream(0xc420427540, 0x2a71920, 0xc4203ceab0, 0xc422015c20, 0x0)
        /go/src/google.golang.org/grpc/server.go:769 +0xf9d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4217c9270, 0xc420427540, 0x2a71920, 0xc4203ceab0, 0xc422015c20)
        /go/src/google.golang.org/grpc/server.go:422 +0xb9
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/google.golang.org/grpc/server.go:423 +0xbb
```

Also the store mutex being held while visiting (and locking) replicas, aslo seen in #9749. 
```
W161006 19:16:14.929467 71 util/syncutil/timedmutex.go:85  [n5] mutex held for 4.080187705s (>100ms):
goroutine 71 [running]:
runtime/debug.Stack(0x2db1920, 0x329c1cf0, 0x2db4680)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x87
github.com/cockroachdb/cockroach/util/syncutil.(*TimedMutex).Unlock(0xc420344250)
        /go/src/github.com/cockroachdb/cockroach/util/syncutil/timedmutex.go:84 +0x17a
github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc421317aa0, 0xc421317a80)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:244 +0x267
github.com/cockroachdb/cockroach/storage.(*Store).deadReplicas(0xc420344000, 0xc429cc5380, 0xc420a25110, 0xc420344220, 0xc420344218)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:1929 +0x192
github.com/cockroachdb/cockroach/storage.(*Store).GossipDeadReplicas(0xc420344000, 0x7fdc4fadb160, 0xc4201d7b90, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:1221 +0x6e
github.com/cockroachdb/cockroach/server.(*Node).gossipStores.func1(0xc420344000, 0xc420344000, 0xc424e45c98)
        /go/src/github.com/cockroachdb/cockroach/server/node.go:625 +0xc4
github.com/cockroachdb/cockroach/storage.(*Stores).VisitStores(0xc420410550, 0xc421317d40, 0xc423437f18, 0xc423437f18)
        /go/src/github.com/cockroachdb/cockroach/storage/stores.go:130 +0x327
github.com/cockroachdb/cockroach/server.(*Node).gossipStores(0xc420196000, 0x7fdc4fadb160, 0xc4201d7b90)
        /go/src/github.com/cockroachdb/cockroach/server/node.go:629 +0xc5
github.com/cockroachdb/cockroach/server.(*Node).startGossip.func1()
        /go/src/github.com/cockroachdb/cockroach/server/node.go:607 +0x3e0
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420394000, 0xc4212d40c0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:191 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:192 +0x74
```

On lightstep the only interesting thing I saw was a lease request taking 6s, which I guess is probably caused by all the locking above.
```
0s
[n2,s2,r2344:/Table/55/1/509{40624…-85856…}] request range lease (attempt #1)
6.67s
[n2,s2,r2344:/Table/55/1/509{40624…-85856…}] replica.Send got error: range 2344: replica {2 2 9} not lease holder; node_id:5 store_id:5 replica_id:10 is
```

**Comment by andreimatei** [comment]
closing this as rho is got healthy. I blame changes to the replica visitor pattern.

**Comment by tamird** [comment]
How long has it been healthy? When did the replica visitor pattern change go out?
