### ISSUE TITLE
insights transactions 22.2.6: undefined (reading 'length')

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#98188]
I think the error is likely coming from here which seems to be specific to 22.2. https://github.com/cockroachdb/cockroach/blob/release-22.2/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsTable.tsx#L68

![image](https://user-images.githubusercontent.com/8868107/223591529-40a17797-9e39-408a-8d8f-b0fd4319efe1.png)

![image](https://user-images.githubusercontent.com/8868107/223591548-f6af3756-cd26-4559-888b-c6125b9997eb.png)

Full context: https://cockroachlabs.slack.com/archives/C0159JK877C/p1678228043278399

Jira issue: CRDB-25122

**Comment by j82w** [comment]
```
ErrorBoundary::componentDidCatch] error =  TypeError: Cannot read properties of undefined (reading 'length')
    at limitStringArray (main.js:540249:33)
    at QueriesCell (main.js:519904:88)
    at Object.cell (main.js:519213:80)
    at Object.cell (main.js:526469:31)
    at eval (main.js:526883:10)
    at Array.map (<anonymous>)
    at TableRow (main.js:526878:15)
    at renderWithHooks (react-dom.development.js:16260:18)
    at mountIndeterminateComponent (react-dom.development.js:18794:13)
    at beginWork$1 (react-dom.development.js:20162:16)
```
    
```ts
    const limitStringArray = (arr, limit) => {
  if (!arr || arr.length == 0) {
    return "";
  }
  if (arr.length == 1 || arr[0].length > limit) {
    return limitText(arr[0], limit);
  }
  return arr[0].concat("...");
};
```
