### ISSUE TITLE
sql: calling `(*planner).HasRoleOption` after the user has executed `SET avoid_buffering=true` causes a panic

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#98204]
**Describe the problem**

The `(*planner).HasRoleOption` uses the internal executor to scan the relevant system table to find the user's roles.  The internal executor always creates a streamingCommandResult. However, this is a problem if the user has already executed `SET avoid_buffering=true` in that session because `streamingCommandResult` panics if you attempt to call DisableBuffering on it.

For example, if you do the following as a non-admin user:

```
./cockroach sql --url 'URL_FOR_NON_ADMIN_USER' -e "SET avoid_buffering=true; SELECT crdb_internal.has_role_option('VIEWACTIVITY')"
```

You'll get a panic such as:

```
goroutine 9995 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*streamingCommandResult).DisableBuffering(0x1068ee3d8?)
        github.com/cockroachdb/cockroach/pkg/sql/conn_io.go:1015 +0x27
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00460a000, {0x1068ee3d8, 0xc003a81ef0}, 0xc00460a5e8, {0x106944560, 0xc003a81e30})
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1275 +0x487
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00460a000, {0x1068ee3d8?, 0xc003a81a10?}, {{0x1069183c0, 0xc004070b40}, {0x0, 0x0, 0x0}, {0xc00075b800, 0x60}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:785 +0x2aef
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1({0x1068ee3d8?, 0xc003a81a10?})
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:137 +0xbc
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling(0x1068ee3d8?, {0x1068ee3d8?, 0xc003a81a10?}, {0x1069183c0?, 0xc004070b40?}, 0xc003a81a10?, 0xc002d593c8?)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2683 +0x330
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00460a000, {0x1068ee3d8, 0xc003a81a10}, {{0x1069183c0, 0xc004070b40}, {0x0, 0x0, 0x0}, {0xc00075b800, 0x60}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:136 +0x4fa
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal(0xc00460a000, {0x1068ee3d8, 0xc003a81a10}, {0xc0043d1560, {0xc003e6a4d0, 0x1, 0x1}, {0x0, 0x0, 0x0}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:226 +0x18b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2({{0x0, 0x0}, 0x0, {0xc0fa3d3ac31edfb8, 0x11fc89958d, 0x0}, 0x1}, 0xc00460a000, 0xc002d59990, 0xc002d59980, ...)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2069 +0x56c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00460a000)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2071 +0x733
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00460a000, {0x1068ee3d8, 0xc003a814d0}, 0x1007e6458?, 0xc000cc4960?, 0x10693a7e0?)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1913 +0x20b
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx.func1()
        github.com/cockroachdb/cockroach/pkg/sql/internal.go:172 +0xac
created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx
        github.com/cockroachdb/cockroach/pkg/sql/internal.go:171 +0x195
```

Not that you you likely won't get this panic as an admin user since the HasRoleOption code first checks for the admin role and that check goes through a cache that may avoid the internal executor.

Jira issue: CRDB-25131

**Comment by knz** [comment]
cc @rafiss @yuzefovich for triage

**Comment by knz** [comment]
@rafiss do you think this should be a GA blocker?

**Comment by rafiss** [comment]
yes, it should. i will review @stevendanna's fix now

**Comment by rafiss** [comment]
oh wait, i guess this probably isn't a regression. but since it crashes the node, and we have a fix i'll just add the label anyway
