### ISSUE TITLE
sql: valueNode created for virtual tables not properly released upon error

### ISSUE THREAD

**Issue by alex** [cockroachdb/cockroach#9853]
```
I161010 14:33:20.777685 1 util/log/clog.go:985  [config] file created at: 2016/10/10 14:33:20
I161010 14:33:20.777685 1 util/log/clog.go:985  [config] running on machine: Alexs-MacBook-Air
I161010 14:33:20.777685 1 util/log/clog.go:985  [config] binary: CockroachDB beta-20161006-796-gdc05d14 (darwin amd64, built 2016/10/10 18:27:14, go1.7.1)
I161010 14:33:20.777685 1 util/log/clog.go:985  [config] arguments: [./cockroach start]
```

- What did you do?

Started a server, then attempted to run the Django tests. They errored out with:

`unknown function: pg_catalog.pg_table_is_visible`

- What did you expect to see?

The server to still be running.

- What did you see instead?

A `panic`:

```
panic: unexpected leftover memory: 16601 bytes [recovered]
	panic: unexpected leftover memory: 16601 bytes

goroutine 168 [running]:
panic(0x505a500, 0xc42060a9d0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc42008cd80)
	/private/tmp/x/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:180 +0x6e
panic(0x505a500, 0xc42060a9d0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/sql/mon.(*MemoryUsageMonitor).StopMonitor(0xc4219fc7f0, 0x7290520, 0xc420c3c6c0)
	/private/tmp/x/src/github.com/cockroachdb/cockroach/sql/mon/mem_usage.go:130 +0x2a2
github.com/cockroachdb/cockroach/sql.(*Session).Finish(0xc4219fc000)
	/private/tmp/x/src/github.com/cockroachdb/cockroach/sql/session.go:185 +0xac
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).finish(0xc420118900)
	/private/tmp/x/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:151 +0x7f
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc420239680, 0x59c41c0, 0xc4205fee70, 0x59a8680, 0xc420012140)
	/private/tmp/x/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:242 +0x652
github.com/cockroachdb/cockroach/server.(*Server).Start.func8.1(0x59c41c0, 0xc4205fee70)
	/private/tmp/x/src/github.com/cockroachdb/cockroach/server/server.go:454 +0x4e
github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith.func1(0xc42008cd80, 0xc42012a298, 0x59c41c0, 0xc4205fee70, 0xc420128080)
	/private/tmp/x/src/github.com/cockroachdb/cockroach/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith
	/private/tmp/x/src/github.com/cockroachdb/cockroach/util/netutil/net.go:138 +0x277
```

**Comment by knz** [comment]
Thanks for the report, I'll have a look.

**Comment by alex** [comment]
Confirmed that this is enough to reproduce the issue:

```
$ ./cockroach start
[move to another tab]
$ ./cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257> select * from pg_catalog.pg_class c where pg_catalog.pg_table_is_visible(c.oid);
pq: unknown function: pg_catalog.pg_table_is_visible
root@:26257> ^D
Error: pq: unknown function: pg_catalog.pg_table_is_visible
Failed running "sql"
[server has panic'd]
```
