### ISSUE TITLE
kvserver: Replica.Send write path ctx cancellation doesn't work when disk stalled

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#98957]
**Describe the problem**

When the leaseholder's disk is stalled and a client that is waiting for a write has its ctx canceled, we don't return from `Replica.Send`. This is because the call to `abandon` here:

https://github.com/cockroachdb/cockroach/blob/b4216ac71b92c5014d10f84db89f1542033c86f6/pkg/kv/kvserver/replica_raft.go#L307-L310

tries to acquire `raftMu`, but `raftMu` is with near certainty held by the raft processing goroutine for the range which will be stuck on the disk.

**To Reproduce**

https://github.com/cockroachdb/cockroach/pull/98852 TestWriteWithStuckLeaseholderDisk

**Expected behavior**

Ctx cancellation is obeyed.

**Comment by tbg** [comment]
In #98852 where this is reproduced we see the raft processing goroutine get stuck here:

```
        goroutine 579 [chan send]:
        github.com/cockroachdb/pebble.(*commitPipeline).Commit(0x14001844c00, 0x14005d4c640, 0x1, 0x1)
        	/Users/tobias/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230315152257-e25c9d5142cf/commit.go:298 +0x60
        github.com/cockroachdb/pebble.(*DB).applyInternal(0x140012e5400, 0x14005d4c640, 0xd1ab5e72082?, 0x7d?)
        	/Users/tobias/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230315152257-e25c9d5142cf/db.go:801 +0x1b8
        github.com/cockroachdb/pebble.(*DB).ApplyNoSyncWait(0x140075e4498?, 0x105d007fc?, 0x140075e4498?)
        	/Users/tobias/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230315152257-e25c9d5142cf/db.go:758 +0x28
        github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).CommitNoSyncWait(0x10ae52520?)
        	/Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:556 +0x34
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*LogStore).storeEntriesAndCommitBatch(0x140075e4d48, {0x10ae52520, 0x14006542d50}, {0x0?, 0x0?, 0x0?}, {0x13, 0xffffffffffffffff, 0x1, 0x0, ...}, ...)
        	/Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:247 +0x560
```

i.e. it's not that applying the log entries suddenly hangs, but that `CommitNoSyncWait` starts blocking after a certain amount of data (a couple hundred writes in that test), not sure if that has to do with WAL buffers[1] or something else.

[1]: https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1679001000188959?thread_ts=1679000081.743509&cid=CAC6K3SLU
