### ISSUE TITLE
`Txn` is nil during call to Rollback in `internal/client/txn.go`

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#9896]
I get this failure when my test client crashes or I control-C it. It's pretty easy to repro.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x45b940d]

goroutine 312 [running]:
panic(0x50deb40, 0xc420012070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc4203eb710)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:180 +0x6e
panic(0x50deb40, 0xc420012070)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/internal/client.(*Txn).Rollback(0x0, 0xc4213ab910, 0x40136c8)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:395 +0x2d
github.com/cockroachdb/cockroach/internal/client.(*Txn).CleanupOnError(0x0, 0x59d4560, 0xc420534b60)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:325 +0x2f
github.com/cockroachdb/cockroach/sql.(*txnState).updateStateAndCleanupOnErr(0xc420c70930, 0x59d4560, 0xc420534b60, 0xc420324fc0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/session.go:382 +0xc1
github.com/cockroachdb/cockroach/sql.(*Session).Finish(0xc420c70900)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/session.go:178 +0x141
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).finish(0xc42070b500)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:151 +0x7f
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc420251a00, 0x59ec260, 0xc420b1bd90, 0x59d4e60, 0xc420ef02d0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:242 +0x652
github.com/cockroachdb/cockroach/server.(*Server).Start.func8.1(0x59ec260, 0xc420b1bd90)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/server/server.go:453 +0x4e
github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith.func1(0xc4203eb710, 0xc420126208, 0x59ec260, 0xc420b1bd90, 0xc420012050)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:138 +0x277
```

**Comment by bdarnell** [comment]
Looks similar to #9879

**Comment by spencerkimball** [comment]
Duplicate of #9879
