### ISSUE TITLE
storage: tracer data race + span used after call to Finish()

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9929]
While investigating #9928. Run 

```
make stressrace PKG=./pkg/storage TESTS=TestRaftBlockedReplica
``` 

Most of the time you get the failure that happens in #9928 . One time I got:

```
==================
WARNING: DATA RACE
Write at 0x00c42059e780 by goroutine 237:
  github.com/opentracing/basictracer-go.(*spanImpl).FinishWithOptions()
      /Users/pmattis/Development/go/src/github.com/opentracing/basictracer-go/span.go:234 +0x88a
  github.com/opentracing/basictracer-go.(*spanImpl).Finish()
      /Users/pmattis/Development/go/src/github.com/opentracing/basictracer-go/span.go:163 +0x63
  github.com/opentracing/opentracing-go.(Span).Finish-fm()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/tracer.go:247 +0x46
  github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1095 +0x335
  github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2166 +0x8e1
  github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:186 +0x24a
  github.com/cockroachdb/cockroach/pkg/storage_test.(*multiTestContextKVTransport).SendNext.func1()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_test.go:469 +0x24c
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:239 +0xec

Previous read at 0x00c42059e780 by goroutine 42:
  github.com/opentracing/basictracer-go.(*spanImpl).Tracer()
      /Users/pmattis/Development/go/src/github.com/opentracing/basictracer-go/span.go:243 +0x3b
  github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:88 +0x70
  github.com/cockroachdb/cockroach/pkg/util/log.eventInternal()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:102 +0x5d
  github.com/cockroachdb/cockroach/pkg/util/log.addStructured()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:142 +0x2f4
  github.com/cockroachdb/cockroach/pkg/util/log.logDepth()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:88 +0x99
  github.com/cockroachdb/cockroach/pkg/util/log.VEventf()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:192 +0xb0
  github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2688 +0x6e3
  github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1994 +0xa94
  github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1807 +0xdd
  github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2848 +0x187
  github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:223 +0x34d
  github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:180 +0x4a
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:191 +0x8a

Goroutine 237 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:240 +0x2af
  github.com/cockroachdb/cockroach/pkg/storage_test.(*multiTestContextKVTransport).SendNext()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_test.go:499 +0x481
  github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:975 +0x312
  github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:359 +0x354
  github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:449 +0x184
  github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendChunk.func1()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:724 +0x2ea
  github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendChunk()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:725 +0x4f8
  github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:562 +0x1a0
  github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:414 +0x7b4
  github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).sendInternal()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:572 +0x16e
  github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).send()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:696 +0x63c
  github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).(github.com/cockroachdb/cockroach/pkg/internal/client.send)-fm()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:309 +0x7c
  github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:416 +0x1ab
  github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Run()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:309 +0xfd
  github.com/cockroachdb/cockroach/pkg/storage.(*NodeLiveness).updateLiveness.func1()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness.go:303 +0x54e
  github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:466 +0x46
  github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:507 +0x233
  github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:467 +0x297
  github.com/cockroachdb/cockroach/pkg/storage.(*NodeLiveness).updateLiveness()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness.go:304 +0x158
  github.com/cockroachdb/cockroach/pkg/storage.(*NodeLiveness).heartbeat()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness.go:184 +0x4b3
  github.com/cockroachdb/cockroach/pkg/storage.(*NodeLiveness).StartHeartbeat.func1()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness.go:137 +0x128
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:191 +0x8a

Goroutine 42 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0x73
  github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x1a5
  github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaft()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2896 +0xa8
  github.com/cockroachdb/cockroach/pkg/storage.(*Store).Start()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:966 +0x760
  github.com/cockroachdb/cockroach/pkg/storage_test.(*multiTestContext).addStore()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_test.go:749 +0x17a9
  github.com/cockroachdb/cockroach/pkg/storage_test.(*multiTestContext).Start()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_test.go:293 +0xa8b
  github.com/cockroachdb/cockroach/pkg/storage_test.TestRaftBlockedReplica()
      /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_raft_test.go:2599 +0x245
  testing.tRunner()
      /Users/pmattis/Development/go-1.7/src/testing/testing.go:610 +0xc9
==================
I161012 21:03:41.524834 241 pkg/storage/replica.go:2688  [s3,r1:{/Min-"b"}] error executing raft command: pkg/storage/replica.go:2598: command observed at lease index 45, but required < 44
I161012 21:03:41.525076 241 pkg/storage/replica.go:2647  [s3,r1:{/Min-"b"}] applying command with forced error: pkg/storage/replica.go:2598: command observed at lease index 45, but required < 45
panic: span used after call to Finish():
&{tracer:<nil> event:0x46f0c40 Mutex:{state:0 sema:0} raw:{Context:{TraceID:5391665179285789335 SpanID:6374033924932605382 Sampled:false Baggage:map[]} ParentSpanID:0 Operation:(*Replica).Send Start:{sec:63611917421 nsec:492842240 loc:0x6690e60} Duration:31570667 Tags:map[] Logs:[]} numDroppedLogs:0} [recovered]
	panic: span used after call to Finish():
&{tracer:<nil> event:0x46f0c40 Mutex:{state:0 sema:0} raw:{Context:{TraceID:5391665179285789335 SpanID:6374033924932605382 Sampled:false Baggage:map[]} ParentSpanID:0 Operation:(*Replica).Send Start:{sec:63611917421 nsec:492842240 loc:0x6690e60} Duration:31570667 Tags:map[] Logs:[]} numDroppedLogs:0}

goroutine 14 [running]:
panic(0x57656a0, 0xc420926000)
	/Users/pmattis/Development/go-1.7/src/runtime/panic.go:500 +0x1ae
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4202ca360)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:180 +0xd8
panic(0x57656a0, 0xc420926000)
	/Users/pmattis/Development/go-1.7/src/runtime/panic.go:458 +0x271
github.com/opentracing/basictracer-go.(*spanImpl).maybeAssertSanityLocked(0xc42059e780)
	/Users/pmattis/Development/go/src/github.com/opentracing/basictracer-go/debug.go:31 +0x488
github.com/opentracing/basictracer-go.(*spanImpl).Lock(0xc42059e780)
	/Users/pmattis/Development/go/src/github.com/opentracing/basictracer-go/debug.go:25 +0x4d
github.com/opentracing/basictracer-go.(*spanImpl).Log(0xc42059e780, 0x0, 0x0, 0x0, 0xc4201e4f00, 0x9f, 0x0, 0x0)
	/Users/pmattis/Development/go/src/github.com/opentracing/basictracer-go/span.go:149 +0xae
github.com/opentracing/basictracer-go.(*spanImpl).LogEvent(0xc42059e780, 0xc4201e4f00, 0x9f)
	/Users/pmattis/Development/go/src/github.com/opentracing/basictracer-go/span.go:137 +0xaf
github.com/cockroachdb/cockroach/pkg/util/log.eventInternal(0xbf31000, 0xc4203ea7e0, 0xc420710000, 0x58e1896, 0x8, 0xc420890cb8, 0x3, 0x3)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:123 +0x46b
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0xbf31000, 0xc4203ea7e0, 0x1, 0x2, 0x58fecd1, 0x20, 0xc420890fc8, 0x1, 0x1)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:142 +0x2f5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0xbf31000, 0xc4203ea7e0, 0x1, 0x1, 0x58fecd1, 0x20, 0xc420890fc8, 0x1, 0x1)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:88 +0x9a
github.com/cockroachdb/cockroach/pkg/util/log.VEventf(0xc400000001, 0xbf31000, 0xc4203ea7e0, 0x58fecd1, 0x20, 0xc420890fc8, 0x1, 0x1)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:192 +0xb1
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc4201de000, 0xc4207141e0, 0x8, 0x48, 0x1, 0x100000001, 0x1, 0x0, 0x1ee, 0x100000001, ...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2688 +0x6e4
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4201de000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1994 +0xa95
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc4201de000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1807 +0xde
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4200e22c0, 0x1)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2848 +0x188
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4200a9540, 0xc4202ca360)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:223 +0x34e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:180 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202ca360, 0xc4201c4d60)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:191 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0x74
```

**Comment by tschottdorf** [comment]
```go
func (s *spanImpl) Tracer() opentracing.Tracer {
	return s.tracer
}

func (s *spanImpl) Context() opentracing.SpanContext {
	return s.raw.Context
}
```

These implementations are simply not taking their locks. Seems innocuous to fix, but then there's going to be the weird situation in which `.Tracer()` returns `nil`.

**Comment by RaduBerinde** [comment]
I filed https://github.com/opentracing/basictracer-go/issues/44 for taking locks. In this case it looks like it's a symptom of an incorrectly used span, which I will investigate.

**Comment by RaduBerinde** [comment]
I have been trying to repro both locally and on GCE.. I think I hit it once the first time I tried it but nothing since, in hours of runs. I even added `Sleep` calls in various places in that function (e.g. before the `VEventf` call in the trace) but still nothing.

My hunch is that it may not be ok to keep using `cmd.ctx` in [this case](https://github.com/cockroachdb/cockroach/blob/4bb811eaf53038c48588907b41a6ed0d0dcfa1de/pkg/storage/replica.go#L2623) but I have no way of verifying.
```
				if pErr := r.refurbishPendingCmdLocked(cmd); pErr == nil {
					cmd.done = make(chan roachpb.ResponseWithError, 1)       <---
				} else {
```

**Comment by petermattis** [comment]
Agreed that case seems suspicious and also very hard to trigger? There are some `Refurbish` tests in `replica_test.go`. Perhaps one of them could trigger badness if a span was set on the context.

**Comment by RaduBerinde** [comment]
Tobi removed refurbishment altogether in #10131.
