### ISSUE TITLE
distsql: TestClusterFlow span use-after-finish

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9985]
```
I161014 14:51:50.527167 11 storage/engine/rocksdb.go:396  closing in-memory rocksdb instance
panic: span used after call to Finish():
&{tracer:<nil> event:0x7f5a00 Mutex:{state:0 sema:0} raw:{Context:{TraceID:6227312592976378248 SpanID:7151576361212056128 Sampled:false Baggage:map[]} ParentSpanID:8033824228644420073 Operation:flow Start:{sec:63612053510 nsec:493973503 loc:0x23e27c0} Duration:29156022 Tags:map[] Logs:[]} numDroppedLogs:0}

goroutine 289 [running]:
panic(0x153dda0, 0xc420ab1aa0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/opentracing/basictracer-go.(*spanImpl).maybeAssertSanityLocked(0xc4206348c0)
    /go/src/github.com/opentracing/basictracer-go/debug.go:31 +0x341
github.com/opentracing/basictracer-go.(*spanImpl).Lock(0xc4206348c0)
    /go/src/github.com/opentracing/basictracer-go/debug.go:25 +0x3f
github.com/opentracing/basictracer-go.(*spanImpl).Log(0xc4206348c0, 0x0, 0x0, 0x0, 0xc420ac2dc0, 0x3c, 0x0, 0x0)
    /go/src/github.com/opentracing/basictracer-go/span.go:149 +0x9a
github.com/opentracing/basictracer-go.(*spanImpl).LogEvent(0xc4206348c0, 0xc420ac2dc0, 0x3c)
    /go/src/github.com/opentracing/basictracer-go/span.go:137 +0x9e
github.com/cockroachdb/cockroach/pkg/util/log.eventInternal(0x7f3ee75e79c8, 0xc4201a3320, 0xc420ad0000, 0x16a5f54, 0x8, 0xc420509920, 0x3, 0x3)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:123 +0x3a4
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f3ee75e79c8, 0xc4201a3320, 0xc400000001, 0x2, 0x16b1c5e, 0x13, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:142 +0x25a
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f3ee75e79c8, 0xc4201a3320, 0x1, 0xc400000001, 0x16b1c5e, 0x13, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:88 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Infof(0x7f3ee75e79c8, 0xc4201a3320, 0x16b1c5e, 0x13, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:96 +0x7e
github.com/cockroachdb/cockroach/pkg/sql/distsql.ProcessInboundStream.func1(0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/inbound.go:42 +0x1ef
github.com/cockroachdb/cockroach/pkg/sql/distsql.ProcessInboundStream(0xc42001a630, 0x209eaa0, 0xc420b10190, 0x0, 0x208d3a0, 0xc420180d40, 0x10, 0x10)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/inbound.go:89 +0x4c2
github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).flowStreamInt(0xc420658180, 0x209eaa0, 0xc420b10190, 0xc420940c68, 0x5d2268)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:185 +0x1f6
github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).FlowStream(0xc420658180, 0x209eaa0, 0xc420b10190, 0xc420940ca8, 0x20)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:190 +0x43
github.com/cockroachdb/cockroach/pkg/sql/distsql._DistSQL_FlowStream_Handler(0x1606b40, 0xc420658180, 0x209b620, 0xc42096e120, 0x8000, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/api.pb.go:264 +0xbb
google.golang.org/grpc.(*Server).processStreamingRPC(0xc42041d180, 0x209eec0, 0xc420526750, 0xc420510690, 0xc42040ef60, 0x2075be0, 0x0, 0x0, 0x0)
    /go/src/google.golang.org/grpc/server.go:689 +0x702
google.golang.org/grpc.(*Server).handleStream(0xc42041d180, 0x209eec0, 0xc420526750, 0xc420510690, 0x0)
    /go/src/google.golang.org/grpc/server.go:773 +0xc36
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420aeffe0, 0xc42041d180, 0x209eec0, 0xc420526750, 0xc420510690)
    /go/src/google.golang.org/grpc/server.go:422 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
    /go/src/google.golang.org/grpc/server.go:423 +0xa3

```

https://teamcity.cockroachdb.com/viewLog.html?buildId=31876&buildTypeId=Cockroach_UnitTests

**Comment by RaduBerinde** [comment]
This is a race between `Cleanup` and an inbound stream receiving a connection. We need a mechanism to first unregister the flow and then wait for any outstanding inbout streaming operations that may have started.
