### ISSUE TITLE
sql: leaked goroutine in fakedist-disk logic test

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#99948]
On [this](https://github.com/yuzefovich/cockroach/commits/stats-debug) branch running
```
./dev testlogic base --files=distsql_automatic_stats --config=fakedist-disk -v --stream-output --stress --cpus=48 -- --test_arg -test.timeout=3m
```
triggers a leaked goroutine pretty reliably (although can take a while - I've seen 20minutes and 70minutes) on the gceworker
```
[05:46:55] --- done: /home/yuzefovich/.cache/bazel/_bazel_yahor/a5769c728929ce64afb25a37a8f5deb6/sandbox/linux-sandbox/7102/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats with config fakedist-disk: 12 tests, 0 failures
[05:47:02] --- total progress: 12 statements
--- total: 12 tests, 0 failures
    logic.go:4121: -- test log scope end --
    generated_test.go:591: Leaked goroutine: goroutine 33623 [select]:
        github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked.func1()
        	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:552 +0x10e
        created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked
        	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:546 +0x7a
--- FAIL: TestLogic_distsql_automatic_stats (31.91s)
FAIL
I230329 05:47:07.324175 1 (gostd) testmain.go:704  [-] 1  Test //pkg/sql/logictest/tests/fakedist-disk:fakedist-disk_test exited with error code 1


ERROR: exit status 1

1538 runs completed, 1 failures, over 22m34s
```

Jira issue: CRDB-26150

**Comment by yuzefovich** [comment]
I haven't been able to reproduce this after several hours on gceworker after rebasing the branch. Perhaps this has been fixed already.
